### ISSUE TITLE
array_equal should not raise a FutureWarning

### ISSUE THREAD

**Issue by bryevdv** [numpy/numpy#9210] opened 2017-06-02 20:01 UTC
With NumPy 0.12.1, see the following:
```
In [13]: a = np.arange(5)

In [14]: b = np.array(["a", "b", "c", "d", "e"])

In [15]: np.array_equal(a,b)
/Users/bryan/anaconda/lib/python3.6/site-packages/numpy/core/numeric.py:2629: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(a1 == a2).all())
Out[15]: False
```

I would claim that warnings like this should never be generated from the *implementation* of supported library functions. My reading of the docs for `array_equal` is that it would return `False` unless both the shape and values are equal. Unless I am mistaken, there is no way whatsoever to compare type-incompatible arrays (either returning a scalar boolean, or an array of booleans) that does not generate the future warning. Even a `ValueError` exception would be preferable.

**Comment by bryevdv** [comment] 2017-06-02 20:03
In fact, if the shapes of one of the arrays above is changed, it does return `False` with no warning:
```
In [2]: a = np.arange(6)

In [3]: b = np.array(["a", "b", "c", "d", "e"])

In [4]: np.array_equal(a,b)
Out[4]: False
```

**Comment by shoyer** [comment] 2017-06-02 22:22
I agree, the deprecation warning is not relevant here.

**Comment by charris** [comment] 2017-06-03 02:19
The FutureWarning is expired, so should be removed sometime before 1.14. The source is in `ufunc_object.c`, so probably an artifact of the nasty way ufuncs used to interact with the binary ops. Looks like more than just removing the warning will be needed.

@njsmith The warning was yours, want to comment?

**Comment by njsmith** [comment] 2017-06-03 03:11
The warning is part of the deprecation process to get us out of the weird thing where `array(["a", "b", "c"]) == array([1, 2, 3])` returns `False`. In the future we would like it to return `array([False, False, False])` instead, or maybe raise an error (for comparisons like `<` when the two dtypes can't be cast together), but certainly not `False`. Technically IIRC this is different than the ufunc/binary op brokenness and instead has to do with the ufunc/string brokenness, though that distinction may not be very meaningful.

Certainly `array_equal` warning shouldn't be issuing a warning here; the quoted bit of `array_equal`'s code actually works correctly either way, and even if it didn't that would be a problem for us to fix, not something `array_equal`'s callers needed to worry about.

I'm not sure what the best solution is. The crude solution would be to just filter out the warning :-). Or for `array_equal` to special-case string dtypes and hard-code that they can never be equal to non-string dtypes. Obviously in the long run we would like to make the change, but I'm not sure what the timeline for that is – it depends on how long the warning has been there, and also on how soon we can actually fix this, which isn't trivial since it may require some surgery to the ufunc guts. (Important and long-delayed surgery, but nonetheless...) I doubt it will happen for 1.14.

**Comment by bryevdv** [comment] 2017-06-03 03:22
> but certainly not False

Why not? I understand why `a == b` should return `array([False, False, False])`, but isn't the entire point of `array_equal` to do the reduction? The doctoring claims it should return a bool:

```
In [33]: np.array_equal?
Signature: np.array_equal(a1, a2)
Docstring:
True if two arrays have the same shape and elements, False otherwise.

Parameters
----------
a1, a2 : array_like
    Input arrays.

Returns
-------
b : bool
    Returns True if the arrays are equal.

See Also
--------
allclose: Returns True if two arrays are element-wise equal within a
          tolerance.
array_equiv: Returns True if input arrays are shape consistent and all
             elements equal.
```

**Comment by charris** [comment] 2017-06-03 04:05
@bryevdv The underlying function is the `np.equal` ufunc used to implement  `==`, and that is where the problem is. In this case is returns `NotImplemented`.
```
In [1]: a = np.arange(5)

In [2]: b = np.array(["a", "b", "c", "d", "e"])

In [3]: np.equal(a, b)
/home/charris/.local/bin/ipython:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  #!/usr/bin/python
Out[3]: NotImplemented
```
See https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/ufunc_object.c#L971 and the extended preceding comment.

**Comment by charris** [comment] 2017-06-03 04:08
@njsmith This code was in NumPy 1.10.0, so deprecations have expired. FutureWarnings may be on a different schedule. In fact, I expect fixing this will break a fair amount of code.

**Comment by charris** [comment] 2017-06-03 04:19
Note that the other comparison operators behave a bit differently
```
In [3]: import warnings

In [4]: warnings.simplefilter('always')

In [5]: a < b
/home/charris/.local/bin/ipython:1: DeprecationWarning: unorderable dtypes; returning scalar but in the future this will be an error
  #!/usr/bin/python
/home/charris/.local/bin/ipython:1: DeprecationWarning: unorderable dtypes; returning scalar but in the future this will be an error
  #!/usr/bin/python
/home/charris/.local/bin/ipython:1: DeprecationWarning: unorderable dtypes; returning scalar but in the future this will be an error
  #!/usr/bin/python
Out[5]: True
```
Wow, that's ugly, but at least it will be an error in 1.14.

**Comment by njsmith** [comment] 2017-06-03 05:13
@bryevdv: right, what I'm saying is that the reason that warning is in the code in the first place is to catch the `arr1 == arr2` case, and then it turns out that `array_equal` uses that internally and thus gets caught in the crossfire.

@charris: if we think we can get away with it in 1.14 then that's fine with me, but it's not just a matter of dropping the warning, we also have to fix it so it actually works :-)

**Comment by eric-wieser** [comment] 2017-06-03 10:58
> we also have to fix it so it actually works 

I think @charris' point is that we can get away with making it throw `NotImplementedError` or something, and get an actually correct implementation in at a later date

**Comment by bryevdv** [comment] 2019-02-11 20:51
@njsmith @charris @eric-wieser I have a new but (I think) related situation that has come up. Consider:

```
>>> import numpy as np
>>> t = np.timedelta64(300, "ms")
>>> isinstance(t, np.ndarray)
False
>>> t == 10
__main__:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
False
```

Is it really the intended plan that `some_array == 10` and` some_scalar == 10` *throw an error* in the future? That seems to be what the deprecation warning implies (!)

I was already trying to guard against the original issue with code like this:
```
if isinstance(new, np.ndarray) or isinstance(old, np.ndarray):
    return np.array_equal(new, old)
return new == **old**
```
but that let's scalars through and raises the warning above. I tried adding another guard
```
if isinstance(new, np.number) or isinstance(old, np.number):
    return np.array_equal(new, old)
```
and now there are just warnings about the deprecated behavior coming from inside numpy itself `(return bool(asarray(a1 == a2).all())` in *numeric.py*)

I guess another way to ask: what is the safe, accepted, endorsed way to generically compare numpy values(arrays or scalars) against arbitrary other types, such that trivial type mismatches just return false? i.e. in python `{} == 10 `returns false, it ***doesn't explode*** (and neither should numpy, I humbly submit)

**Comment by shoyer** [comment] 2019-02-11 21:22
> I guess another way to ask: what is the safe, accepted, endorsed way to generically compare numpy values(arrays or scalars) against arbitrary other types, such that trivial type mismatches just return false?

Do you want `array == something_else` to return Python boolean True/False, or to return a boolean array? The former should be `np.array_equal()`, the later should be `==`.

There may be bugs in how NumPy handles this. Certainly you should not be seeing a DeprecationWarning for `t == 10` in your example above.

**Comment by bryevdv** [comment] 2019-02-11 21:30
I want a way to compare numpy types to non-numpy types and just get `False` without a warning or exception. I'm fine if we have to be defensive, i.e. I thought this should work:
```

# handle when one arg is nearly
if isinstance(new, np.ndarray) or isinstance(old, np.ndarray):
    return np.array_equal(new, old)

# handle when one arg is numpy scalar
if isinstance(new, np.number) or isinstance(old, np.number):
    return np.array_equal(new, old)

# handle everything else
return new == old
```
but that does *not* work. I guess my questions are:
* is it true that the above *should* work? 
* can it be prioritized to make sure it does, *before* the exception mentioned in the deprecation warning start getting raised?

**Comment by seberg** [comment] 2019-02-11 21:45
Hmmm, the warning does seem a bit strange at least for scalars. IIRC, for arrays the problem is that the behaviour switches between returning an array of bools and a python True/False. That makes the typical python "just return False" behaviour inconsistent.
Wouldy have to go back to when we thought about this, it may well be that the goal was to go through a Deprecation and then switch to an array of False.

It seems to me that at least not going into the array comparison path that creates this warning for the scalar timedelta should be a pretty clear option to do.

**Comment by bryevdv** [comment] 2019-02-11 21:49
Ugh, I am having a hard time narrowing down the real trigger here. pytest reports this:
```
>       f.dt = np.timedelta64(3000, "ms")

bokeh/core/property/tests/test_dataspec.py:462:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bokeh/core/has_props.py:280: in __setattr__
    super(HasProps, self).__setattr__(name, value)
bokeh/core/property/descriptors.py:545: in __set__
    self._internal_set(obj, value, setter=setter)
bokeh/core/property/descriptors.py:769: in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
bokeh/core/property/descriptors.py:810: in _real_set
    if self.property.matches(value, old) and (hint is None):
bokeh/core/property/bases.py:222: in matches
    return np.array_equal(new, old)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a1 = array(3000, dtype='timedelta64[ms]'), a2 = array(2.59254e+08)
```
But I don't see an error if I try this by hand:
```
In [12]: a1 = np.array(3000, dtype='timedelta64[ms]'); a2 = np.array(2.59254e+08)

In [13]: np.array_equal(a1, a2)
Out[13]: False
```

I will wait to post more until I can actually characterize this more precisely

**Comment by bryevdv** [comment] 2019-02-11 21:52
OK! sorry, I forgot I had to explicitly turn on deprecation warnings. Here is a small test case (that I think should not issue a warning)
```
In [1]: import numpy as np

In [2]: a1 = np.array(3000, dtype='timedelta64[ms]'); a2 = np.array(2.59254e+08)

In [3]: np.array_equal(a1, a2)
/Users/bryanv/anaconda/lib/python3.7/site-packages/numpy/core/numeric.py:2428: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  return bool(asarray(a1 == a2).all())
Out[3]: False
```

**Comment by seberg** [comment] 2019-02-11 21:59
@bryevdv for `np.array_equal` you are also definitely right, since that one returns a python bool, it just gets thrown under the bus currently.

I wonder if we could try to go ahead with some of the deprecation (unless we decide to abort anyway), since I guess if we go ahead, fixing `array_equal` is much simpler.

**Comment by seberg** [comment] 2022-12-06 08:27
Finally fixed in https://github.com/numpy/numpy/pull/22707.

**Closed by seberg** 2022-12-06 08:27 UTC
