### ISSUE TITLE
numpy.isrealobj('a string') is True !

### ISSUE THREAD

**Issue by fjld61** [numpy/numpy#12652] opened 2019-01-03 10:01 UTC
numpy.isrealobj('a string') is True ! and various other inconsistencies between isrealobj, isreal and iscomplexobj

### Reproducing code example:

```
$ python3
Python 3.4.9 (default, Aug 14 2018, 21:28:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version.version
'1.10.4'
>>> numpy.isrealobj('a string')
True
>>> numpy.iscomplexobj('1+1j')
False
>>> numpy.isrealobj(False)
True
>>> numpy.iscomplexobj(False)
False
>>> numpy.isreal('1.0')
False
>>> numpy.isreal(True)
True
>>> numpy.isreal({'a':'1','b':1})
True
```

### Numpy/Python version information:

1.10.4 3.4.9 (default, Aug 14 2018, 21:28:57) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

**Comment by dbarbier** [comment] 2019-03-18 18:05
I suggest to close this ticket, everything works as documented.  Maybe `isrealobj` could be removed, it is defined as `not iscomplexobj`.

**Comment by rgommers** [comment] 2019-03-18 22:11
>  Maybe isrealobj could be removed, it is defined as not iscomplexobj.

I don't think that is warranted. 

> I suggest to close this ticket, everything works as documented.

True. A doc clarification would be nice though; `isrealobj` assumes array input without really stating that in the docstring.

**Comment by fjld61** [comment] 2019-03-19 08:36
I have no problem with closing the ticket. 

My qualms were that on the tin can is written "Tuna" while in the fine print one can read "not Beef".

The doc string clarifies the situation of complex numbers with zero imaginary parts (also in the examples), so why not clarify the situation for argument that are nor real nor complex ?

One could also implement (((without loss of efficiency))) isrealobj the way iscomplexobj was coded with the added benefit of clarity: i.e. numpy.isrealobj('a string') would return False as expected from what is written on the tin can.

But finally considering the last example in the doc string of isrealobj and the implications for iscomplexobj (!) one should really consider isrealobj and iscomplexobj as private functions to numpy (i.e. as _isrealobj_ and _iscomplexobj_) to signal that the content of the tin is not well defined with respect to the labelling on it.

But as I said: I have no problem with closing the ticket.

**Comment by Mukulikaa** [comment] 2021-05-09 14:12
The doc mentions that `isrealobj` will return False only if the argument is of type complex. So does it really require further clarification about other datatypes?

**Comment by rgommers** [comment] 2021-05-09 14:20
I think the issue is that `isrealobj` is only meant for arrays with numerical values in them. However, it happily accepts anything:
```python
>>> np.isrealobj('adasd')
True
>>> np.isrealobj(None)
True
```
Semantically that does not make too much sense, so it deserves an explicit explanation/warning I think.

**Comment by melissawm** [comment] 2021-05-09 14:20
I think a note stating explicitly that isrealobj assumes array input, and that other objects may cause the return value to be True would be nice.

**Comment by Mukulikaa** [comment] 2021-05-09 14:28
Great, @yashasvimisra2798 and I will work on it.

**Closed** 2021-05-10 04:26 UTC
