### ISSUE TITLE
Wrong Product by prod()

### ISSUE THREAD

**Issue by MichalRIcar** [numpy/numpy#15831] opened 2020-03-25 07:10 UTC
Hello, the product function is providing wrong answers even though I tried to provide uint8 format as an array. Please see the screenshot. 

![prod](https://user-images.githubusercontent.com/62614119/77510863-4e8f6880-6ea2-11ea-994f-f35579aeb288.png)

**Comment by mattip** [comment] 2020-03-25 07:38
Hi @MichalRIcar thanks for the report. Please try to use text rather than screenshots when possible. You can also use the "<>" formatting in the toolbar to get a nicely formatted message like (note my answer is different than yours, see below):
```
>>> import numpy as np
>>> d = np.array([6, 7, 10, 7, 9, 5, 12, 9, 8, 3, 29, 10, 34, 2], dtype = np.uint8)
>>> np.prod(d)
6762413952000
>>> 
```
As for the bug: in the [help](https://numpy.org/devdocs/reference/generated/numpy.prod.html) for the `dtype` argument it states:
>  The dtype of a is used by default unless a has an integer dtype of less precision than the default platform integer. In that case, if a is signed then the platform integer is used while if a is unsigned then an unsigned integer of the same precision as the platform integer is used

My guess is that your platform integer is 32bits, so by default you will use `dtype=np.uint32`. Your calculation overflows that dtype, it wraps around and gives your "incorrect" answer:

```
>>> np.prod(d, dtype=np.uint32)
2135428096
```

This is a common problem. We cannot change numpy to emit an overflow warning on integer operations like it does for floating point operations right now, but it is something we would like to do in the future. One way to work around this is to specify `dtype=np.uint64` which will give you a bit more range. Or you could just use `np.uint64` in the array creation.

**Comment by MichalRIcar** [comment] 2020-03-25 10:44
Hi Matti, respect for the prompt help and insight to the actual problem, thanks! With the fix of uint64 during the array creation it now all works well, I will keep that in mind as it was extra problematic during the flow passing the value to another functions before.

**Comment by WarrenWeckesser** [comment] 2020-03-25 11:08
Matti explained the issue well.  Not a bug, so closing.

**Closed by WarrenWeckesser** 2020-03-25 11:08 UTC
