### ISSUE TITLE
Accuracy issues with `std` and `float32` arrays when using `axis`

### ISSUE THREAD

**Issue by vafl** [numpy/numpy#14691] opened 2019-10-13 22:24 UTC
Calculating `std` on `float32` arrays using `axis` can give inaccurate results. See the example below. 

### Reproducing code example:

```python
import numpy as np

n = 1_000_000

# Create a float32 array with two columns with values 100 and -100
# x.shape = (n, 2)
x = np.array([100.0, -100.0])[None, :].repeat(repeats=n, axis=0).astype(np.float32)

# calculating std for the column separately gives 0 as expected
print(x[:, 0].std())  # -> 0.
print(x[:, 1].std())  # -> 0.

# calculating std on both columns in one go using axis=0 gives
print(x.std(axis=0))  # -> [1.3201232, 1.3201232]
```

The magnitude of the error becomes larger with larger `n` and larger values for the columns.
It seems like this loss of accuracy should be avoidable.

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.2 3.7.4 (default, Sep  7 2019, 18:27:02)
[Clang 10.0.1 (clang-1001.0.46.4)]
```

**Comment by pfheatwole** [comment] 2019-10-13 23:39
This affects other functions as well, including `sum` and `mean`.

### Reproducing code example:
```
In [1]: N = 80_000_000                  

In [2]: x = np.ones(shape=(N, 3)).astype(np.float32)                            

In [3]: np.sum(x, axis=0)    # Expected value: [80000000., 80000000., 80000000]
Out[3]: array([16777216., 16777216., 16777216.], dtype=float32)

In [4]: np.sum(x[:, 0])                 
Out[4]: 80000000.0

In [5]: np.mean(x, axis=0)   # Expected value: [1., 1., 1.]
Out[5]: array([0.2097152, 0.2097152, 0.2097152], dtype=float32)

In [6]: np.mean(x[:, 1])                
Out[6]: 1.0

In [7]: np.mean(x, axis=0).dtype        
Out[7]: dtype('float32')

In [8]: np.mean(x[:, 1]).dtype          
Out[8]: dtype('float32')
```

### Numpy/Python version information:
Running Fedora 30 on an i7-6700
```
>>> import sys, numpy; print(numpy.__version__, sys.version)                                     
1.17.2 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0]
```

**Comment by pfheatwole** [comment] 2019-10-13 23:44
Looks like a duplicate of issue #8869

**Comment by rossbar** [comment] 2020-07-22 22:29
Closing this as duplicate of #8869, please feel free to add to the discussion there

**Closed by rossbar** 2020-07-22 22:29 UTC
