### ISSUE TITLE
Installation fail on MSYS2

### ISSUE THREAD

**Issue by EssenWorkbench** [numpy/numpy#11676] opened 2018-08-06 06:31 UTC
$ python --version
Python 3.7.0

$ pip install numpy
...
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0jx06uto/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-b23lp18j/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-0jx06uto/numpy/

**Comment by mattip** [comment] 2018-08-06 06:51
Possible duplicate of #9935 which has some hints but is still open. There the suggestion involves setting an environment variable with a uname that distutils can use.

**Comment by seberg** [comment] 2023-01-02 21:17
Closing, as a years old (MSYS2) installation issue.  Hopefully it works these days.

**Closed by seberg** 2023-01-02 21:17 UTC
