### ISSUE TITLE
TYP: Operators for npt.NDArray[np.number] are missing

### ISSUE THREAD

**Issue by twoertwein** [numpy/numpy#21249] opened 2022-03-26 13:46 UTC
### Describe the issue:

Functions often accepts any ndarray as long as the elements are numbers. Using `npt.NDArray[np.number]` creates many mypy/pyright errors as none of the operators seems to be annotated for it.

### Reproduce the code example:

```python
import numpy as np
import numpy.typing as npt

def foo(x: npt.NDArray[np.number]):
    x * 1
    x * x
```

### Error message:

```shell
error: Unsupported operand types for * ("ndarray[Any, dtype[number[Any]]]" and "int")  [operator]
error: Unsupported operand types for * ("ndarray[Any, dtype[number[Any]]]" and "ndarray[Any, dtype[number[Any]]]")  [operator]
```

### NumPy/Python version information:

1.22.3 3.10.2 (v3.10.2:a58ebcc, Mar 10 2022, 19:36:59) [GCC 9.4.0]

**Comment by BvB93** [comment] 2022-03-29 13:07
Duplicate of https://github.com/numpy/numpy/issues/20442:

--------------------

> I would expect that an array of `np.number` can be multiplied by an integer.

As of the moment dtype-support for the `np.inexact`- and `np.number`-ABCs isn't all that widespread, so for the time being it might be simpler to stick to `np.integer[Any] | np.floating[Any]`.

I agree this is something that should be fixed though, but with the branching of the 1.22 branch the changes will have to wait for numpy 1.23.

_Originally posted by @BvB93 in https://github.com/numpy/numpy/issues/20442#issuecomment-979875816_

**Closed by BvB93** 2022-03-29 13:07 UTC
Labels: 00 - Bug
