### ISSUE TITLE
BUG: ufunc shape (1, ) aliased operands

### ISSUE THREAD

**Issue by mattharrigan** [numpy/numpy#8273] opened 2016-11-13 23:40 UTC
```
>>> x = np.ones(10)
>>> np.add(x,x[:1],x)
array([ 2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])
>>> x = np.ones(10)
>>> np.add(x,x[4:5],x)
array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])
```

The first makes sense, but I expected the second to end with a string of 3's.  Not totally sure if this is a bug or if aliased ufunc operands is documented as undefined behaviour somewhere.

The above was produced using the current master and ubuntu.  On another windows machine with 1.10.4 I get even weirder:
```
>>> np.add(x,x[4:5],x)
array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  3.])
```

**Comment by pv** [comment] 2016-11-13 23:54
duplicate of gh-1683

**Closed by pv** 2016-11-13 23:54 UTC

**Comment by pv** [comment] 2016-11-13 23:55
The short answer is that ufunc operations on aliased inputs is undefined.
