### ISSUE TITLE
BUG: np.double accepts arbitrary keyword arguments

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#19127] opened 2021-05-28 15:33 UTC
### Reproducing code example:

```python
import numpy as np

np.double(3.0,x=3.1,y=3.2,z=3.4,q=3.14)
np.double(3.0,x=3.1)
```
```
3.0
```
returns
```
np.double(x=3.1)
```
returns
```
0.0
```

### Error message:

No error, but too tolerant of keyword arguments

### NumPy/Python version information:

```
1.20.2 3.8.10 (default, May 19 2021, 18:05:58)
[GCC 7.3.0]
```

**Comment by BvB93** [comment] 2021-05-28 17:14
Duplicate of https://github.com/numpy/numpy/issues/17532.

**Closed** 2021-05-28 17:21 UTC
Labels: 00 - Bug, 50 - Duplicate
