### ISSUE TITLE
BUG: Polynomial.fit([0],[0],deg=0) fails

### ISSUE THREAD

**Issue by ggggggggg** [numpy/numpy#27230] opened 2024-08-16 15:03 UTC
### Describe the issue:

`Polynomial.fit([0],[0],deg=0)` fails, it should return something equivalent to `Polynomial([0])`.

### Reproduce the code example:

```python
import numpy as np
np.polynomial.Polynomial.fit([0],[0],deg=0)
```

### Error message:

```shell
Traceback (most recent call last)
Cell In[1], line 2
      1 import numpy as np
----> 2 np.polynomial.Polynomial.fit([0],[0],deg=0)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\polynomial\_polybase.py:1015, in ABCPolyBase.fit(cls, x, y, deg, domain, rcond, full, w, window, symbol)
   1012     window = cls.window
   1014 xnew = pu.mapdomain(x, domain, window)
-> 1015 res = cls._fit(xnew, y, deg, w=w, rcond=rcond, full=full)
   1016 if full:
   1017     [coef, status] = res

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\polynomial\polynomial.py:1362, in polyfit(x, y, deg, rcond, full, w)
   1214 def polyfit(x, y, deg, rcond=None, full=False, w=None):
   1215     """
   1216     Least-squares fit of a polynomial to data.
   1217
   (...)
   1360
   1361     """
-> 1362     return pu._fit(polyvander, x, y, deg, rcond, full, w)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\polynomial\polyutils.py:664, in _fit(vander_f, x, y, deg, rcond, full, w)
    661 scl[scl == 0] = 1
    663 # Solve the least squares problem.
--> 664 c, resids, rank, s = np.linalg.lstsq(lhs.T/scl, rhs.T, rcond)
    665 c = (c.T/scl).T
    667 # Expand c to include non-fitted coefficients which are set to zero

File <__array_function__ internals>:200, in lstsq(*args, **kwargs)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\linalg\linalg.py:2285, in lstsq(a, b, rcond)
   2282 if n_rhs == 0:
   2283     # lapack can't handle n_rhs = 0 - so allocate the array one larger in that axis
   2284     b = zeros(b.shape[:-2] + (m, n_rhs + 1), dtype=b.dtype)
-> 2285 x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
   2286 if m == 0:
   2287     x[...] = 0

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\linalg\linalg.py:101, in _raise_linalgerror_lstsq(err, flag)
    100 def _raise_linalgerror_lstsq(err, flag):
--> 101     raise LinAlgError("SVD did not converge in Linear Least Squares")

LinAlgError: SVD did not converge in Linear Least Squares
```

### Python and NumPy Versions:

In [2]: import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.4
3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

### Runtime Environment:

In [1]: import numpy; numpy.show_runtime()
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX'],
                      'not_found': ['AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL']}},
 {'architecture': 'SkylakeX',
  'filepath': 'C:\\Users\\oneilg\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

### Context for the issue:

I am using a polynomial fit to the gain of a detector system for a rough calibration. In most cases I use a quadratic fit, but I also need to handle the cases where I have fewer than 3 calibration points. I expected to be able to simply use `fit(x,gain,deg=min(2,len(cal_points)-1)` to handle these cases, but due to this error I now need to write special case code for the case of one calibration point.

**Comment by eendebakpt** [comment] 2024-08-16 21:04
This seems to be a duplicate of https://github.com/numpy/numpy/issues/25982. A PR to address this is https://github.com/numpy/numpy/pull/25984. 

@ggggggggg Could you check whether the PR solves your issue?

**Comment by ggggggggg** [comment] 2024-08-16 23:08
Yes that's the same issue so the fix will work for me. Thanks.

**Closed** 2024-08-17 06:28 UTC
Labels: 00 - Bug
