### ISSUE TITLE
np.int64 * int -> np.float64

### ISSUE THREAD

**Issue by daniele-bigoni** [numpy/numpy#7409] opened 2016-03-11 15:08 UTC
This behaviour might be related to these two bugs
[https://github.com/numpy/numpy/issues/5745](url)
[https://github.com/numpy/numpy/issues/7126](url)
but regards int and not uint. I'm running the following code in both python2 and python3 with Numpy v.1.8.2 and v1.10.4.

The issue comes up when running the following code:

```
import numpy as np 
a = 9223372036854775808
type(a)
b = np.int64(0)
type(b)
type(b*a)
```

The result being (in Python3):

```
builtins.int
numpy.int64
numpy.float64
```

Note that if I change it to:

```
a = 9223372036854775807
type(b*a)
```

I get the correct casting:

```
numpy.int64
```

If I change the example to:

```
a = 92233720368547758100
type(b*a)
```

I get again the expected (correct) casting:

```
builtins.int
```

I came by this error while working with indices which should always be integer, so this casting to float64 was a very unexpected behaviour.

**Comment by charris** [comment] 2016-03-11 19:48
That does look odd...

**Comment by seberg** [comment] 2016-03-11 19:57
It is somewhat expected, since it would coerce `b` to `np.uint64`, and then the resulting multiplication of int64 and uint64 gives float due to lack of a better type. The other way around works, because an np.int64 scalar in Python 2 (if long is 64bits) is an integer subclass, so Python will just do the multiplication without asking Numpy.

Maybe we have to fix scalar casting to cast to Python longs instead of float (which kind of makes sense for arrays)? Or...?

**Comment by NeilGirdhar** [comment] 2017-01-24 22:44
This is a duplicate of https://github.com/numpy/numpy/issues/7126

**Comment by seberg** [comment] 2017-01-24 22:53
True enough an dI guess there is more discussion there.

**Closed by seberg** 2017-01-24 22:53 UTC
Labels: 11 - Bug, component: numpy.core
