### ISSUE TITLE
Yet another ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by iacchi** [numpy/numpy#17975] opened 2020-12-10 16:30 UTC
I have installed numpy to use it in a project (using pip), but the import fails with the error "ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'". To rule out program issues, I've just started an interactive python3 shell and typed "import numpy", this is what I get:

```
ash-4.3# python3
Python 3.9.0 (default, Dec 02 2020, 16:57:56)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/opt/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/opt/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/opt/bin/python3"
  * The NumPy version is: "1.19.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

This may also be useful:

```
ash-4.3# ls /opt/lib/python3.9/site-packages/numpy.libs/
libgfortran-2e0d59d6.so.5.0.0  libopenblasp-r0-ae94cfde.3.9.dev.so  libquadmath-2d0c479f.so.0.0.0  libz-eb09ad1d.so.1.2.3
```

### Steps to reproduce:

Hardware: Synology NAS
Python3 installed via Entware package
numpy installed via pip
import numpy -> error

Any idea about how to solve this issue?

**Comment by charris** [comment] 2020-12-10 20:04
Do you have multiple python version installed? And what was the command line you used to install using pip?

**Comment by iacchi** [comment] 2020-12-10 21:15
There are two versions of python installed, one from the Synology package, one from the Entware one. The one in the system path is the Entware one (at least, that's the result of the command `which python`), and this is all done using the Entware package. Python was installed with opkg (the Entware equivalent of linux package managers) and the same for pip. For numpy I did the usual "pip install numpy". Also, Synology's python package doesn't provide pip, so I'm 100% sure the pip I used is the one from Entware.

**Comment by mattip** [comment] 2020-12-10 21:28
Is there a `_multarray_umath*.so` in `/opt/lib/python3.9/site-packages/numpy/core` ? Does its name match other c-extension python packages (like `python -c "import _ssl; print(_ssl.__file__)"`)

**Comment by charris** [comment] 2020-12-10 21:34
Pip usually points to the last installed python. To be safe you should do 'python -mpip install', where python is the one you are using.

**Comment by iacchi** [comment] 2020-12-10 21:37
at `/opt/lib/python3.9/site-packages/numpy/core` there is a `_multiarray_umath.cpython-39-x86_64-linux-gnu.so`. The output of `python -c "import _ssl; print(_ssl.__file__)"` is `/opt/lib/python3.9/lib-dynload/_ssl.cpython-39.so`.

@charris I think I'm using the right python:
```
ash-4.3# python -mpip install numpy
Requirement already satisfied: numpy in /opt/lib/python3.9/site-packages (1.19.4)
ash-4.3# python --version
Python 3.9.0
```

The python version installed by Entware is 3.9, the Synology one is 3.7.7.

**Comment by mattip** [comment] 2020-12-10 21:49
Hmm. That is strange, the `_ssl` module is misnamed. Can you install and use any other wheel packages like lxml? Assuming it is safe, to do so on your system, could you try copying 
`/opt/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so` 
to 
`/opt/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39.so` ? 
Perhaps the Entware python is (mis-)compiled to only load c-extensions without the platform abi tag.

**Comment by mattip** [comment] 2020-12-10 21:50
but then pip should have failed to find the wheel ...

**Comment by iacchi** [comment] 2020-12-10 21:58
I installed the lxml package with pip and then loaded it without any issue:

```
ash-4.3# pip install lxml
Collecting lxml
  Downloading lxml-4.6.2-cp39-cp39-manylinux1_x86_64.whl (5.4 MB)
     |████████████████████████████████| 5.4 MB 5.4 MB/s
Installing collected packages: lxml
Successfully installed lxml-4.6.2
ash-4.3# python
Python 3.9.0 (default, Dec 02 2020, 16:57:56)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
>>>
```

I copied `_multiarray_umath.cpython-39-x86_64-linux-gnu.so` to `_multiarray_umath.cpython-39.so` in the same directory and when I tried to import numpy again the error changed (the same if I put the second in place as a symbolic link rather than a copy):

```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/lib/python3.9/site-packages/numpy/core/__init__.py", line 98, in <module>
    from . import _add_newdocs
  File "/opt/lib/python3.9/site-packages/numpy/core/_add_newdocs.py", line 4406, in <module>
    add_newdoc('numpy.core._multiarray_tests', 'format_float_OSprintf_g',
  File "/opt/lib/python3.9/site-packages/numpy/core/function_base.py", line 497, in add_newdoc
    new = getattr(__import__(place, globals(), {}, [obj]), obj)
ModuleNotFoundError: No module named 'numpy.core._multiarray_tests'
```

so I did `ln -s _multiarray_tests.cpython-39-x86_64-linux-gnu.so _multiarray_tests.cpython-39.so` as well to get multiarray_tests. After that, if I try to import again numpy I get this error:

```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.9/site-packages/numpy/__init__.py", line 143, in <module>
    from . import lib
  File "/opt/lib/python3.9/site-packages/numpy/lib/__init__.py", line 25, in <module>
    from .index_tricks import *
  File "/opt/lib/python3.9/site-packages/numpy/lib/index_tricks.py", line 11, in <module>
    import numpy.matrixlib as matrixlib
  File "/opt/lib/python3.9/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from .defmatrix import *
  File "/opt/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py", line 11, in <module>
    from numpy.linalg import matrix_power
  File "/opt/lib/python3.9/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from .linalg import *
  File "/opt/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 33, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: cannot import name 'lapack_lite' from partially initialized module 'numpy.linalg' (most likely due to a circular import) (/opt/lib/python3.9/site-packages/numpy/linalg/__init__.py)
```

And here I get a bit lost (also, I don't want to start linking a thousand files). What should I do? Provided there is some problem with Entware's python/pip installation, what should I report to the Entware people exactly so they can fix it?

**Comment by mattip** [comment] 2020-12-10 22:31
OK, well at least we have found out what the problem is: somehow you can import `module.cpython-39.so` but not `module.cpython-39-x86_64-linux-gnu.so`.  In lxml, I think they have a fallback if they cannot import the c-extension module so that was a dead end. On my python 
`$ python -c "import _imp; print(_imp.extension_suffixes())"` 
prints 
`['.cpython-38-x86_64-linux-gnu.so', '.abi3.so', '.so']`. I  imagine yours is 
`['.cpython-39.so', '.abi3.so', '.so']`

> what should I report to the Entware people exactly so they can fix it

If I am correct and your `extension_suffixes()` output is what I think it is, then something like:

"I can load a c-extension module `module.cpython-39.so` but not `module.cpython-39-x86_64-linux-gnu.so`. This is problematic since wheels I download from PyPI use the second form. xref numpy/numpy/#17975. The problem stems from `_imp.extension_suffixes()`, which comes from `sysconfig.get_config_var('SOABI')` which comes from the [`configure` script](https://github.com/python/cpython/blob/master/configure.ac#L4776) used to build python".

It just so happens I was digging into these values for another bug.

**Comment by iacchi** [comment] 2020-12-10 22:34
Yes, your assumption on the suffixes is correct. I will open a bug with Entware and reference this bug.

**Comment by diraniyoussef** [comment] 2021-01-13 09:40
I worked after I installed the latest version numpy in PyCharm. I was using sympy.plot
glad it worked.

**Comment by seberg** [comment] 2021-11-05 21:03
Since this is a year old now, and specialized hardware:  It seems the diagnosis was correct and the wheel incorrectly picked up (unrelated to NumPy).  So closing.

**Closed by seberg** 2021-11-05 21:03 UTC
Labels: 32 - Installation
