### ISSUE TITLE
log2 on zero array where x > 0 results in nan, small numbers

### ISSUE THREAD

**Issue by antoneri** [numpy/numpy#12832] opened 2019-01-23 12:52 UTC
Running log2 on an array of zeros with float dtype results in small non-zero numbers and sometimes nan.

### Reproducing code example:

```python
import numpy as np
x = np.zeros((1, 10), dtype=np.float)
print(x > 0)
print(np.log2(x, where=x > 0))
```

### Error message:
```python
[[False False False False False False False False False False]]
[[0.00000000e+000 0.00000000e+000 1.77229088e-310 3.50977866e+064
  0.00000000e+000 0.00000000e+000             nan             nan
  3.50977942e+064 2.23604912e-314]]
```

### Numpy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.15.4 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by antoneri** [comment] 2019-01-23 12:57
A workaround is to use
```python
x = np.zeros((1, 10), dtype=np.float)
logx = np.zeros(x.shape)
np.log2(x, out=logx, where=x > 0)
# >>> logx
# [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
```

**Comment by mattip** [comment] 2019-01-23 13:22
The behaviour is as expected. In the [documentation](http://www.numpy.org/devdocs/reference/generated/numpy.log2.html?highlight=numpy%20log2#numpy.log2) it states "values of False indicate to leave the value in the output alone". This is expected behaviour. Your example output is simply uninitialized memory. Another solution would be
```
x = np.zeros((1, 10), dtype=np.float)
result = np.log2(x, where=x > 0)
result[x <=0] = 0
```
Suggestions for how we could improve documentation are always welcome

**Comment by antoneri** [comment] 2019-01-23 13:32
It makes sense now. I thought "left alone" ment that input values are left alone, that is; copied to the output. I have no suggestions for improvements unfortunately.

**Comment by mhvk** [comment] 2019-01-23 14:32
@antoneri - thanks for reporting regardless. And you're far from the first to have tripped over this. Indeed, there is an attempt to make the documentation clearer in progress in #12025. Could you have a look and see if this might have helped you?

In the meantime, I'll close this issue, since it is in a way a duplicate of #12025.

**Closed by mhvk** 2019-01-23 14:32 UTC
Labels: 04 - Documentation, 50 - Duplicate, component: numpy.ufunc
