### ISSUE TITLE
numpy import on Windows allocates hundreds of megabytes of committed memory

### ISSUE THREAD

**Issue by schlenk** [numpy/numpy#13432] opened 2019-04-30 10:45 UTC
When using the openblas based pypi package for numpy on windows, a simply import allocates a lot (25-30MB/core) of committed memory per CPU core by default. This leads to MemoryErrors due to memory exhaustion, when all memory of a machine is committed used up. This can easily happen when using multiprocessing or other multi process architectures on a server with many cpu cores. Basically kills the server, unless you have at least (core*core)*30MB of RAM free.

This is made worse by packages that simply import numpy for functionality unrelated to openblas, like `openpyxl` that only import some type definitions from numpy, so the memory usage comes as a big surprise.

The problem why this happens is OpenBLAS usage of VirtualAlloc to allocate buffers on init. Using the MEMORY_COMMIT flag right away to emulate Linux mmap behaviour, instead of using only MEMORY_RESERVE and a later MEMORY_COMMIT on first actual use of the buffers, so forcing the reservation of physical (commited) memory instead of just virtual memory. 

Setting the OPENBLAS_NUM_THREADS=1 envvar fixes the memory allocation, but i did not see any direct mention of it related to memory usage, only to threading behaviour.

It would be nice if just importing the module did not allocate and commit all that memory.

### Reproducing code example:

```python
import numpy
```

Check the memory usage with sysinternal vmmap.
https://docs.microsoft.com/en-us/sysinternals/downloads/vmmap

The usage in the 'private data' section (private bytes in process explorer) grows by megabytes, proportional to the number of CPU cores.

This can be reduced to zero growth when ``OPENBLAS_NUM_THREADS`` is set to 1 before the import.

### Numpy/Python version information:
>>> print(numpy.__version__, sys.version)
('1.16.2', '2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]')

**Comment by mattip** [comment] 2019-04-30 11:38
Thanks @shlenk for the detailed analysis. Could you report this upstream to [OpenBLAS](https://github.com/xianyi/OpenBLAS/)? You can link this issue in the report like `numpy/numpy#13432`. It seems we need a documentation section on thread/memory control, which should mention the implications of using a thread pool. It should also mention https://github.com/joblib/threadpoolctl, which is a generic solution to manage common thread pool strategies.

**Comment by jtcalvert197** [comment] 2021-04-13 16:27
@schlenk did you ever end up reporting the memory allocation issue to OpenBLAS? I searched through the issues there but couldn't find it.

**Comment by schlenk** [comment] 2021-04-13 21:52
@jtcalvert197 I do not remember. Probably got distracted by some other issue.

**Comment by rgommers** [comment] 2022-02-18 05:23
Duplicate of gh-19145 and gh-17856. It has gotten better since this bug report. The conclusion was that there's isn't much more that OpenBLAS can do easily. I'll close this issue as a duplicate.

Our wheels are limited to 64 threads, so this will take <2 GB even with the reported 25-30 MB/thread, at least it's not unlimited.

**Closed by rgommers** 2022-02-18 05:23 UTC
Labels: 04 - Documentation, component: numpy.linalg
