### ISSUE TITLE
PY_ARRAY_UNIQUE_SYMBOL not being obeyed when using import_array in a module

### ISSUE THREAD

**Issue by mpconte** [numpy/numpy#19270] opened 2021-06-17 20:28 UTC
I followed the instructions as per https://numpy.org/doc/stable/reference/c-api/array.html#importing-the-api  I have one executable which initializes the python environment (i.e. Py_Initialize and import_array) and does nothing else and a separate module that links to this executable that deals with numpy arrays.  but I'm getting an unresolved external symbol **my_unique_identifier** for the latter module  Am I missing something?

**Comment by mattip** [comment] 2021-06-17 20:43
Maybe? Can you show a minimal reproducer? Does the example shown there work?

**Comment by mpconte** [comment] 2021-06-18 12:21
I tried the example shown and encounter this issue

**Comment by seberg** [comment] 2024-08-09 13:04
Going to close this, there is not enough information in the issue to help and the mechanism is successfully used elsewhere.  The issue is too old to follow up (we can open a new one).

**Closed by seberg** 2024-08-09 13:04 UTC
