### ISSUE TITLE
BUG: np.arccos gives different results on different machines

### ISSUE THREAD

**Issue by adrien-berchet** [numpy/numpy#20988] opened 2022-02-03 15:53 UTC
### Describe the issue:

I use the function `np.arccos` and sometimes I get different results on different machines.
For example:
```python
tested_float = np.float32(0.78354603)
result = np.arccos(test_float)
```
Gives on the machine A:
```python
0.6704438
```
While it gives on the machine B:
```python
0.6704437
```

I wonder if it could not be related to #6081 ?

### Reproduce the code example:

```python
import numpy as np

tested_float = np.float32(0.78354603)
result = np.arccos(test_float)
```

### NumPy/Python version information:

Machine A:
1.22.1 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]

Machine B:
1.22.1 3.8.3 (default, Jan  6 2021, 17:13:49) 
[GCC 9.3.0]

**Comment by seberg** [comment] 2022-02-11 18:50
What you are seeing is a single ULP (unit of least precision) difference.  For complex computations like `arccos` that is typically expected it depends on both the hardware and the implementation (which is typically not provided by NumPy itself).

On 1.22 and if one of the computer has some certain Intel hardware, the reason could also be due to NumPy shipping SVML, which has slightly bigger errors than many other implementations unfortunately.  If you build NumPy yourself you could try `NPY_DISABLE_SVML=1` to see if it makes a difference.
That said, again: one bit of difference should just be expected probably.

Closing for now, going to reopen if there is any reason to believe it is more than typical numerical errors.

**Closed by seberg** 2022-02-11 18:50 UTC
Labels: 33 - Question

**Comment by adrien-berchet** [comment] 2022-02-16 10:08
Thank you for your answer, now I understand.
Nevertheless, in cases where reproducibility is important it is quite annoying. For example our unit tests were randomly failing because of this, depending on which VM the github action was launched. In the end we had to round the values to a few decimals in order to ensure reproducibility (it was not possible to round the results of the tests because the error of the cosine are greatly amplified in our use case). So I am just wondering if it would not make sense to provide some helpers to ensure reproducibility? Or at least provide more info about this issue in the doc?

**Comment by seberg** [comment] 2022-02-16 14:36
> So I am just wondering if it would not make sense to provide some helpers to ensure reproducibility? Or at least provide more info about this issue in the doc?

NumPy has a host of testing function slike `assert_arrays_equal_nulp` to make such testing easier.  We can't make a host of systems do the same reproducible thing, reproducibility on that level is just not the state of the art.

**Comment by adrien-berchet** [comment] 2022-02-18 09:15
Unfortunately functions like `assert_arrays_equal_nulp` can not work in our case since the error is amplified during our algorithm (basically, we draw lines in directions given by `arccos` so the distant points of the lines have large errors). But I get why it's hard to make it reproducible.
Thank you very much for your answer!
