### ISSUE TITLE
Statistics functions handle axis keyword inconsistently

### ISSUE THREAD

**Issue by istvankleijn** [numpy/numpy#10422] opened 2018-01-17 17:24 UTC
When calculating statistics of a `pandas.DataFrame`, it appears that different statistics handle the `axis` keyword differently. For `mean`, `std`, `var`, `amin`, and `amax`, it is possible to specify `axis` as a string (e.g. `axis='index')`, whereas this is not possible for the other statistics, for example `median`, `nanmean`, and `ptp`.  Is this intended behaviour?

For example, the following code runs fine (Python 3.6.4, NumPy 1.14.0, Pandas 0.22.0):
```
import numpy as np
import pandas as pd

df = pd.DataFrame([[1, 1, 1], [2, 3, 4]])
np.mean(df, axis='index')
```
However,
```
np.median(df, axis='index')
```
and the like throw `TypeError`s asking for integers instead of strings.

Both `np.median(df, axis=0)` and `df.median(axis='index')` work as one might expect. What is the reason for this inconsistency?

**Comment by eric-wieser** [comment] 2018-01-17 18:25
The difference is that `np.mean(df, ...)` just calls `df.mean(...)`, whereas `np.median` is a function designed to work only with `ndarray` objects

**Comment by seberg** [comment] 2018-01-17 18:57
Yeah, I would argue, its not a bug. Sure there may be thoughts to make numpy much more of a dispatcher then it is now, but that is a bit unrelated and until it happens there will be those functions that try methods and those that do not. And we definitely will not be adding more methods.

So, since I do not think it is very actionable (nor a serious bug), I will close this for now. Feel free to keep discussing though!

**Closed by seberg** 2018-01-17 18:57 UTC

**Comment by seberg** [comment] 2018-01-17 18:59
Or in other words: I think changing this would be more on the level of writing an NEP ;).

**Comment by istvankleijn** [comment] 2018-01-17 19:01
Ah, that makes sense. Thank you.

Does this mean that it is possible to design an object for which `np.amax(obj) - np.amin(obj) != np.ptp(obj)` (since `np.amin` and `np.amax` behave like `np.mean` in this regard, whereas `np.ptp` does not)?

**Comment by eric-wieser** [comment] 2018-01-17 19:03
> whereas np.ptp does not

[citation needed]

ptp works in the same way as amin and amax

**Comment by istvankleijn** [comment] 2018-01-18 12:01
Hah, I see what's happening: `np.ptp(df, ...)` fails because `df.ptp(...)` does not exist, whereas `np.amax(df, ...)` calls `df.max(...)`.

I lost track of the boundary between pandas and numpy again :)
