### ISSUE TITLE
numpy does not work

### ISSUE THREAD

**Issue by PBahner** [numpy/numpy#13441] opened 2019-04-30 20:23 UTC
Hello!
When I execute the line in python `import numpy` the following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import numpy
  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: cblas_sgemm
```

I use Python 3.5 wich works on my Raspbian.
I reinstalled numpy and it still does not work. I also tried to install different versions of numpy and to install it according to this [guide](https://stackoverflow.com/questions/11443302/compiling-numpy-with-openblas-integration/14391693#14391693) and had no success.

**Comment by mattip** [comment] 2019-04-30 20:32
Duplicate of #12999. They reported that numpy was linking to `libopenblasp-r0-382c8f3a.3.5.dev.so => /usr/local/lib/python3.6/dist-packages/numpy/core/../.libs/libopenblasp-r0-382c8f3a.3.5.dev.so` which should provide this symbol but doesn't. Their solution was to rebuild numpy which then linked to `libopenblas.so.0 => /usr/lib/libopenblas.so.0`. Perhaps you also have this broken libopenblasp ?

**Comment by PBahner** [comment] 2019-04-30 20:49
libopbenblas reinstalled. No succes!

**Comment by seberg** [comment] 2019-05-01 00:12
Libopenblas can be compiled without cblas support, so you really have to make sure that cblas is included in your OpenBLAS.

Also check which OpenBLAS is picked up, e.g. by checking `ldd /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so`, I suppose there may be a small chance that you have two OPenBLAS version and getting the wrong one?

**Comment by PBahner** [comment] 2019-05-03 12:59
When  I enter the command `ldd /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-arm-linux-gnueabihf.so`, I get this:
```
	linux-vdso.so.1 (0x7efaf000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76d48000)
	libf77blas.so.3 => /usr/lib/libf77blas.so.3 (0x76d03000)
	libcblas.so.3 => /usr/lib/arm-linux-gnueabihf/libcblas.so.3 (0x76ca9000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x76a31000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x769b2000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76989000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x7684a000)
	/lib/ld-linux-armhf.so.3 (0x76f6d000)
	libgfortran.so.3 => /usr/lib/arm-linux-gnueabihf/libgfortran.so.3 (0x76795000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76768000)
	libf2c.so.2 => /usr/lib/arm-linux-gnueabihf/libf2c.so.2 (0x7673f000)
```
What could I do?

**Comment by seberg** [comment] 2019-05-03 14:41
@PBahner, not sure right away. But for one thing OpenBLAS does not show up there, did you edit your `site.cfg` to point to the specific path of your openblas installation? Getting a symbol error seems a bit weird to me considering that it does list `/usr/lib/arm-linux-gnueabihf/libcblas.so.3` which seems right. (Maybe check what hides behind your `/usr/lib/arm-linux-gnueabihf/libcblas.so.3`, it could be the problem?)

**Comment by mattip** [comment] 2019-05-30 09:16
Closing, the issue author did not supply any more information. @PBahner if you feel this is still a NumPy issue and not one of your OS package provider,, please reopen with an answer to the last request for information.

**Closed by mattip** 2019-05-30 09:16 UTC
Labels: 57 - Close?

**Comment by Blind0ne** [comment] 2019-07-19 10:58
@PBahner I habe the same issue. Did you solved it?
