### ISSUE TITLE
argument 'where' in np.divide "leaves the value in the output alone", where does the value come from?

### ISSUE THREAD

**Issue by ThibHlln** [numpy/numpy#12022] opened 2018-09-23 17:02 UTC
The numpy documentation on the use of the argument 'where' in [numpy.divide](https://docs.scipy.org/doc/numpy/reference/generated/numpy.divide.html) says:

> **where : _array_like, optional_**
> Values of True indicate to calculate the ufunc at that position, values of False indicate to leave the value in the output alone.

I am wondering what value is used for the positions in the array where the condition in the argument 'where' evaluates to False. It does not set it to np.nan, nor takes the value from x1 / from x2, it seems to assign a random value. Sometimes it takes the value 0, which could make sense, but it is not very convenient to get a value that is not the same across the array, or not the same between two runs of the script.

Obviously, it is possible for the user to assign values in the output array subsequently using Boolean indexing. So, I am wondering if this is the expected behaviour? If so, so be it and I will just assign values subsequently.

Thank you.

### Reproducing code example:

```python
import numpy as np
arr = np.ones((10,), dtype=int)
x1 = arr * 2
x2 = arr * 3
d = np.divide(x1, x2, where=(arr != 1))
print(d)
```

### Numpy/Python version information:

`('1.15.0', '2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]')`

**Comment by eric-wieser** [comment] 2018-09-23 17:34
This is covered by the extended ufunc docs linked under kwargs, and is by design.

It sounds like we need to make this clearer in the short docs too.

**Comment by ThibHlln** [comment] 2018-09-23 17:46
Oops. I did not see that. Apologies for this and thank you for your help!
So an alternative solution to a subsequent Boolean indexing, is to give an initialised array using the 'out' argument. Good to know!

Yes, I think it could be useful to indicate in the short docs that the values stay uninitialised. But from now on, I will look at these linked docs when I want to learn about numpy functions.

I let you close this issue if you wish, as you covered everything! Unless you want to keep it open until the short docs get updated.

Thank you.

**Comment by eric-wieser** [comment] 2018-09-24 02:48
Feel free to propose a wording change yourself at https://github.com/numpy/numpy/blob/master/numpy/core/code_generators/ufunc_docstrings.py#L22-L34

**Comment by ThibHlln** [comment] 2018-09-24 08:43
> 
> 
> Feel free to propose a wording change yourself at https://github.com/numpy/numpy/blob/master/numpy/core/code_generators/ufunc_docstrings.py#L22-L34

I came up with a proposal. See pull request #12025.

**Comment by seberg** [comment] 2021-07-02 00:26
Seems we merged the documentation improvement, so closing this.

**Closed by seberg** 2021-07-02 00:26 UTC
