### ISSUE TITLE
Bug: polynomial.ABCPolyBase.has_samecoef doesn't output the correct boolean

### ISSUE THREAD

**Issue by Mandroide** [numpy/numpy#17765] opened 2020-11-13 05:33 UTC
When I use the method `has_samecoef`, it doesn't output `True` when I have two numpy.polynomial.Polynomial with the same coefficients. I see that this condition on this method is the problem:
https://github.com/numpy/numpy/blob/509b5ae4a7bb3c99324fd302ead1bbf4b130c741/numpy/polynomial/_polybase.py#L195

![Polynomial.has_samecoef](https://user-images.githubusercontent.com/31109774/99032543-26976700-2550-11eb-8645-182769183953.png)

**Comment by charris** [comment] 2020-11-13 05:46
Did you intend to make polynomials with polynomials for coefficients?

**Comment by charris** [comment] 2020-11-13 05:55
Similar comparison works for me. Are you sure the Polynomials are the same? For double precision you need to print about 19 digits.

**Comment by Mandroide** [comment] 2020-11-13 12:22
> Did you intend to make polynomials with polynomials for coefficients?

I printed out the following if you want to take a closer look:
[Colab Notebook](https://drive.google.com/file/d/1xZuo46RJ9nD73113wGwmKE_tVpQAmKfU/view?usp=sharing)

**Comment by WarrenWeckesser** [comment] 2021-11-22 10:52
There is almost certainly a discrepancy in the coefficients that is too small to see when they are printed with just 8 digits after the decimal point.  I'm closing the issue, but @Mandroide, if you can provide a minimal, reproducible, self-contained Python script that demonstrates the problem, we can take another look.

**Closed by WarrenWeckesser** 2021-11-22 10:52 UTC
