### ISSUE TITLE
ENH: strftime for np.datetime64

### ISSUE THREAD

**Issue by attack68** [numpy/numpy#17083] opened 2020-08-14 13:56 UTC
Just noting that there was a PR#14264 a year ago to try and add a `strftime` method to datetime64 object. Wonder if it might be resurrected??? :issue:#14243

To make it a little more friendly for packages downstream like Pandas it helps to compare synonomously with Python datetime and something like:

```
import datetime as dt
import numpy as np

date = dt.datetime.strptime('2020-06-30', format='%Y-%m-%d')
date.strftime('%Y-%m-%d')
dt.datetime.strftime(date, "%Y-%m-%d")

date64 = np.datetime64('2012-06-30T20:00')
np.datetime_as_string(date64, unit='D')
# nice with a direct date64.strftime(format) method..
```

**Comment by eric-wieser** [comment] 2020-08-28 09:38
Duplicate of #14243. I think this is a good idea still, but let's keep discussion in one place.

**Closed by eric-wieser** 2020-08-28 09:38 UTC
