### ISSUE TITLE
Division by zero crash when importing numpy from embedded python

### ISSUE THREAD

**Issue by DmitryOlenchikov** [numpy/numpy#16003] opened 2020-04-17 08:30 UTC
I use a simple embedded python project, which import numpy.
It uses Py_Initialize() and  PyRun_SimpleString("import numpy") only (for test purposes)
(see the code below for details. The code is written on Free Pascal + Lazarus)
It does not work because import numpy raises division by zero error.
I use Python 3.7 and numpy
full_version = '1.18.2'
git_revision = 'df256d0d2f3bc6833699529824781c58f9c6e697'

I found that the crash issue is related with the certain code in the core.getlimits module:
```
    with numeric.errstate(all='ignore'):
        huge_f128 = (ld(1) - epsneg_f128) / tiny_f128 * ld(4)
...
    with numeric.errstate(all='ignore'):
        huge_f80 = (ld(1) - epsneg_f80) / tiny_f80 * ld(4)

If I change it like this
    huge_f128 = inf
...
    huge_f80 = inf
then numpy is imported normaly without crashing the main program.
Is it a bug or I do something wrong?

program numpy_crash;
uses sysutils;
const DLLname = 'C:\Python37\python37.dll';
procedure Py_Initialize();cdecl;external DLLname;
procedure Py_Finalize();cdecl;external DLLname;
function PyRun_SimpleString(script: PAnsiChar): integer;cdecl;external DLLname;
begin
  Py_Initialize();
  try
    PyRun_SimpleString(PAnsiChar('import numpy'));
  except on E: Exception do
    writeln(E.message);
  end;
  Py_Finalize();
  readln;
end.
```

**Comment by seberg** [comment] 2020-04-27 20:40
Are you running on some special system? The only place where I seem to remember having seen this type of error was e.g. on the valgrind virtual machine, which doesn't support `long double` correctly?

**Comment by DmitryOlenchikov** [comment] 2020-05-14 06:54
I do not use virtual machine, I work on Windows 10. The same code works correctly (without division by zero crash) with Python 3.6 and numpy version:
short_version = '1.13.3'
version = '1.13.3'
full_version = '1.13.3'
git_revision = '31465473c491829d636c9104c390062cba005681'

**Comment by seberg** [comment] 2020-05-14 12:59
@DmitryOlenchikov any chance you are running `Py_Initialize` multiple times? That cannot work probably, because of global variables in C/the shared objects and the shared objects cannot be unloaded.

**Comment by DmitryOlenchikov** [comment] 2020-06-01 06:16
&gt; Четверг, 14 мая 2020, 15:59 +03:00 от Sebastian Berg :
&gt; 
&gt; 
&gt; @DmitryOlenchikov any chance you are running  Py_Initialize multiple times? That cannot work probably, because of global variables in C/the shared objects and the shared objects cannot be unloaded.
&gt; —
&gt; You are receiving this because you were mentioned.
&gt; Reply to this email directly,  view it on GitHub , or  unsubscribe .

No, the numpy import crashes after the first Py_initialize
-- 
Best regards
    Dmitry

**Comment by rossbar** [comment] 2020-07-12 02:54
Any updates here? If there was a working version, maybe some additional information could help track down any errors on the NumPy side, e.g. a `bisect`. There's not a lot to go on here so it may be difficult to make progress otherwise.

**Comment by rgommers** [comment] 2022-11-21 11:11
> No, the numpy import crashes after the first `Py_initialize`

This should work, but we need a better reproducer. No updates in >2 years, so I'll close the issue. Please feel free to comment or reopen in case this turns up again or someone has a reproducer. We'd accept a PR to help improve this case as well.

Thanks all!

**Closed by rgommers** 2022-11-21 11:11 UTC
Labels: 57 - Close?, Embedded
