### ISSUE TITLE
For 2.0.0rc1 pp39 windows wheel fails test collection

### ISSUE THREAD

**Issue by charris** [numpy/numpy#26178] opened 2024-03-30 00:10 UTC
See https://github.com/numpy/numpy/actions/runs/8485561340/job/23252932520. The relevant error seems to be
```
ERROR f2py/tests/test_abstract_interface.py - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmp5xhejvww\\meson.build'
```
NumPy v2.0.0b1 built and tested without problems and very little has changed. The only thing that might be suspicious is the upgrade of `pypa/cibuildwheel`, and the wheel built without problems, and I am not sure why that would affect meson using the file. The other candidate might be pytest-xdist, but it hasn't changed.

I am tempted to ignore this for the 2.0.0rc1 release, I don't think it is a blocker.

**Comment by charris** [comment] 2024-03-30 00:45
That last wheel build for main ran without problems 3 days ago. I suppose this could be affected by the same problem that has impacted emscripten.

**Comment by mattip** [comment] 2024-03-30 00:51
Skipping it is fine. If we figure it out we can upload rhe wheel later

**Comment by charris** [comment] 2024-03-30 13:27
Took 4 tries, but eventually the pp39 wheel test did run. Looking back, the 2.0.0b1 release took 3 tries.

**Comment by mattip** [comment] 2024-04-03 17:32
We have seen some problems with test collection caused by a garbage collection bug. Much of the problem has been fixed and will be part of the next release. See [the issue](https://github.com/pypy/pypy/issues/3959) and [a blog post](https://www.pypy.org/posts/2024/03/fixing-bug-incremental-gc.html) about it.

**Comment by charris** [comment] 2024-04-03 17:56
@mattip We should drop Python 3.9 for NumPy 2.1, is there any problem with PyPy on that platform?

**Comment by mattip** [comment] 2024-04-03 19:23
PyPy 3.9 and 3.10 share as much as possible of the same code base, so new problems would be unexpected.

**Comment by rgommers** [comment] 2024-06-12 13:47
We have PyPy 3.9 wheels for 2.0.0rc2. Can this issue be closed @charris, @mattip?

**Closed** 2024-06-12 16:34 UTC
Labels: 14 - Release, 24 - PyPy
