### ISSUE TITLE
[Feature Request] im2col and col2im

### ISSUE THREAD

**Issue by Fnjn** [numpy/numpy#10754] opened 2018-03-16 00:40 UTC
I think  these 2 matlab function [im2col](https://www.mathworks.com/help/images/ref/im2col.html) and [col2im](https://www.mathworks.com/help/images/ref/col2im.html), which rearrange image block to columns and rearrange back, are quite useful. I don't find similar one on numpy or scipy. 

Any chance these can be added in future version? If so, I can work on their implementation.

**Comment by shoyer** [comment] 2018-03-16 00:47
These are too specialized for NumPy.

Maybe they would be appropriate for an image processing library like skimage?

**Comment by eric-wieser** [comment] 2018-03-16 00:54
This sounds similar to the common sliding window request, which I think would be suitable for numpy in `index_tricks`, if we can pin down an API.

**Comment by Fnjn** [comment] 2018-03-16 01:25
@shoyer Not just image processing, these 2 function are extremely useful for doing customized convolution. 

@eric-wieser It's indeed a sliding window rearragement. 'stride_tricks' could be suitable.

**Comment by eric-wieser** [comment] 2018-03-16 01:33
Something like `res = sliding_window_view(arr, axes=None, shape)`, with semantics:

* `len(axes) == len(shape)`
* `res.shape == shape + arr.shape` (arguably more useful for broadcasting than `(arr.shape + shape)`

We could consider adding a `strides` argument later, but I think we should leave it out of the initial proposal

**Comment by eric-wieser** [comment] 2018-03-16 01:44
Closing as a dupe of #7753

**Closed by eric-wieser** 2018-03-16 01:44 UTC
