### ISSUE TITLE
Lack of clarity in RandomState compatibility guarantee

### ISSUE THREAD

**Issue by mdickinson** [numpy/numpy#8771] opened 2017-03-11 12:32 UTC
The [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState) for numpy.random.RandomState say:

> Compatibility Guarantee A fixed seed and a fixed series of calls
> to ‘RandomState’ methods using the same parameters will always
> produce the same results up to roundoff error [...]

Question: in this context, does "always" mean that this guarantee should apply across platforms and machines, or just that it should apply across runs on a single machine?

If the latter, then the "up to roundoff error" is probably unnecessary, which leads me to believe that the intent is that the guarantee should apply across platforms. But now I'm failing to see how it's possible to make such a guarantee: some of the sample generation methods use the rejection method, and so consume some (unknown in advance) number of random samples. The number of samples actually consumed may depend on floating-point and libm variations. A good example is the zipf distribution:

https://github.com/numpy/numpy/blob/b94c2b01ff7ef5b8dc44726512cfa232e9054882/numpy/random/mtrand/distributions.c#L720-L742

Here, the number of calls to rk_double for a given `a` and random state may change depending on tiny floating-point differences in the result of `pow` (for example).

Should the guarantee be restricted to some subset of the RandomState methods?

Related: #6180 (where the wording explicitly includes "regardless of platform"), #6405 (where it doesn't).

**Comment by seberg** [comment] 2017-03-11 15:15
@rkern probably knows this best. I guess you are probably right, but doubt there is much you can do about it (except trying to document details). I don't know if e.g. `pow` has enough round off difference for any problems to be possible (even then I guess they are extremely unlikely) at least on IEEE conform implementations? There are some others such as multivariate normal which also depend on the linear algebra solutions (though I doubt that can cause changes in the stream later on).

**Comment by charris** [comment] 2017-03-11 18:09
The sequences of floats, integers, etc. produced by the base rng should be the same assuming that division conforms to the ieee standard for ieee doubles. Platform variations in library functions such as `log` may change results for more complicated distributions, depending on the particular function involved, which in turn will affect the following sequence of generated results. 

I think you are correct that we cannot make quarantees cross platform, or even between library/compiler versions, when certain of the distributions are involved.

**Comment by charris** [comment] 2017-03-11 18:20
To be a bit more precise, roundoff errors and small function differences will only make small differences in floating results if they are not involved in rejection methods. Differences in functions involved in rejection methods can change the whole following sequence, but that is unlikely unless a very large number of trials are made. We do have tests for repeatability and I'm not aware of any failures at this time.

**Comment by rkern** [comment] 2017-03-11 18:32
There's one other source of cross-platform wonkiness that is somewhat easier to realize: internal integer values are C `long`s. With certain extreme parameter values, 32-bit `long`s overflow and give different results than on platforms with 64-bit `long`s. Of course, since they are overflowing, the result is crap anyways, but they can change the stream afterwards for all of the non-crap results that follow.

**Comment by mdickinson** [comment] 2017-03-11 18:33
> I don't know if e.g. pow has enough round off difference for any problems to be possible (even then I guess they are extremely unlikely) 

Possible, definitely: a single ulp difference in a pow result could be enough to cause a rejection-method inner loop to go for one more iteration, and such single ulp differences are very common: there's wide variation in `pow` implementations across platforms. In contrast to `pow`, reproducibility of arithmetic operations on IEEE 754-implementing hardware should be a fairly safe assumption, provided well-known issues associated with x87 usage are avoided, and I'd expect basic libm functions like exp, cos, log, etc. to be mostly correctly rounded most of the time.

I agree that you'd have to be very unlucky to run into any of these cases by accident, so that in practice the guarantee is likely to hold almost always. So perhaps my objection can be dismissed under "practicality beats purity" rules.

**Comment by rkern** [comment] 2017-03-11 18:56
Yeah, there are two faces to the compatibility policy: what guarantees users can expect and what goals developers should strive towards. Being compatible "up to numerical rounding errors" across platforms is really an aspirational goal of the latter kind, not a firm guarantee of the former. I think I had the developer-goal in my head when I approved the language. And I was probably thinking of the transformation-type algorithms instead of the rejection-type ones.

**Comment by charris** [comment] 2017-03-11 19:11
The multivariate case mentioned by @seberg is probably the most likely to cause problems as the factorization is only unique up to the sign of the eigenvectors if the singular values are distinct and even less unique if the covariance has degenerate eigenvalues, so differences in implementation of the svd that is used can have a big effect. I believe the Cholesky factorization would be more specific.

**Comment by btyukodi** [comment] 2018-09-28 19:45
My issue might be related: I'm using numpy.random for a Monte Carlo simulation where very small acceptance/rejection probabilities are possible. Although I'm seeding the RNG, I'm unable to reproduce the same sequence of random numbers.

In the documentation, what is meant by "incorrect values"? Also, how is roundoff error handled? Aren't values always rounded in precisely the same way? Is it possible at all that my code is not fully deterministic even though I provide a seed? I am certain that the seed is nowhere else reset because I provide my RNG object to each of my function as an argument. Thank you for your comments.

**Comment by mattip** [comment] 2018-10-16 09:37
Can we close this or do we need to clarify the documentation?

**Comment by WarrenWeckesser** [comment] 2018-10-17 00:36
Given that [NEP 19](https://github.com/numpy/numpy/blob/master/doc/neps/nep-0019-rng-policy.rst) has been accepted, it looks like this issue can be closed.

**Closed** 2018-10-17 00:38 UTC
Labels: 04 - Documentation, component: numpy.random
