### ISSUE TITLE
BUG: np.random.zipf hangs the interpreter on pathological input

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#9829] opened 2017-10-06 05:49 UTC
```
>>> np.random.zipf(np.nan) 
# hangs forever, doesn't respond to ctrl C
>>> np.random.zipf(1.0000000000001)
# hangs for a possibly finite but very long time, also not responding to Ctrl+C
```

The former should probably just throw an exception. The latter is sort of inevitable with a rejection algorithm, but if we called [`PyErr_CheckSignals()`](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals) then at least it could be cancelled.

**Comment by kchomski-reef** [comment] 2017-11-20 12:18
Doesn't seem to be present anymore on the current `master`:

```python
Python 3.6.3 (default, Nov 13 2017, 02:17:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.random.zipf(np.nan)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4086, in mtrand.RandomState.zipf
ValueError: 'a' must be a valid float > 1.0
>>> 
```

**Comment by eric-wieser** [comment] 2017-11-20 17:20
It was fixed for Nan, but the problem remains for numbers close to 1

**Comment by toslunar** [comment] 2018-09-12 16:44
While the `nan` case has been fixed, the problem remains for large `a`.
```
>>> np.__version__
'1.16.0.dev0+99f7ad5'
>>> np.random.zipf(10000)
# hangs
```

This is probably because the following code overflows.
```
    am1 = a - 1.0;
    b = pow(2.0, am1);
```

**Comment by bashtage** [comment] 2019-04-10 21:40
```
>>> np.random.zipf(1.0000000000001)
# hangs for a possibly finite but very long time, also not responding to Ctrl+C
```

This doesn't hand forever since there is a positive probability of drawing a value of 0.0, so that `1.0-draw` is 1 and the rejection sampler will always exit.  It may take an extraordinarily long time (1 in 2**53), but not a bug.

**Comment by charris** [comment] 2019-04-11 01:17
I think it is a bug. I think we decided that it reasonable to raise an error for parameters excessively close to 1. Note that this problem can be fixed by using a truncated part of the distribution and rewriting the majorizing distribution so that it succeeds more often, easy speedups of 1000x or more follow. See discussion at #9824. @bashtage The new randomgen should be fixed to handle this better.

**Comment by mattip** [comment] 2019-04-11 03:59
xref #13164 and #13163

**Comment by vks** [comment] 2021-08-02 22:23
I think the biggest problem is that small `a` are very likely to result in an infinite `X`, which is always rejected. Returning `RAND_INT_MAX` instead would fix this issue at the cost of introducing a bias.

**Comment by charris** [comment] 2021-08-02 22:44
> which is always rejected

Yes.  I note that other versions allow setting the maximum via an argument, which is probably the best way to do it.

**Closed** 2024-07-26 15:21 UTC
Labels: 00 - Bug, component: numpy.random
