### ISSUE TITLE
np.vstack does no longer accept generator expressions in numpy master

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#12274] opened 2018-10-26 16:48 UTC
It seems that the scikit-learn test job that runs against numpy master found a breaking change in numpy:

https://github.com/scikit-learn/scikit-learn/pull/12467

Minimal reproduction case:

```python
>>> import numpy as np
>>> np.__version__
'1.16.0.dev0+8aa1214'
>>> np.vstack([0] for _ in range(3))
Traceback (most recent call last):
  File "<ipython-input-5-842ad8069d40>", line 1, in <module>
    np.vstack([0] for _ in range(3))
  File "/opt/venvs/py37/lib/python3.7/site-packages/numpy/core/overrides.py", line 151, in public_api
    implementation, public_api, relevant_args, args, kwargs)
  File "/opt/venvs/py37/lib/python3.7/site-packages/numpy/core/overrides.py", line 96, in array_function_implementation_or_override
    return implementation(*args, **kwargs)
  File "/opt/venvs/py37/lib/python3.7/site-packages/numpy/core/shape_base.py", line 260, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
  File "/opt/venvs/py37/lib/python3.7/site-packages/numpy/core/overrides.py", line 151, in public_api
    implementation, public_api, relevant_args, args, kwargs)
  File "/opt/venvs/py37/lib/python3.7/site-packages/numpy/core/overrides.py", line 96, in array_function_implementation_or_override
    return implementation(*args, **kwargs)
  File "/opt/venvs/py37/lib/python3.7/site-packages/numpy/core/multiarray.py", line 193, in concatenate
    return _multiarray_umath.concatenate(arrays, axis, out)
ValueError: need at least one array to concatenate
```

This used to work in past versions of numpy:

```python
>>> import numpy as np
>>> np.__version__
'1.14.5'
>>> np.vstack([0] for _ in range(3))
array([[0],
       [0],
       [0]])
```

**Comment by tylerjereddy** [comment] 2018-10-26 16:56
For SciPy we just switched from generator to list comprehension to resolve this -- i.e., https://github.com/scipy/scipy/pull/9405

It is related to the array function NEP changes -- see https://github.com/numpy/numpy/issues/12263#issuecomment-433252841 . Stephan may re-enable the behavior for a while, but maybe best not to depend on it long term.

**Comment by amueller** [comment] 2018-10-26 16:59
close this as duplicate of #12263?

**Comment by tylerjereddy** [comment] 2018-10-26 17:02
Yes, let's focus on the issue there

**Closed by tylerjereddy** 2018-10-26 17:02 UTC
