### ISSUE TITLE
BUG: limit memory usage of python processes that uses Python

### ISSUE THREAD

**Issue by bashirmindee** [numpy/numpy#26551] opened 2024-05-27 12:06 UTC
### Describe the issue:

Duplicate of the [stackoverflow question](https://stackoverflow.com/questions/78528014/limit-memory-usage-of-python-processes) because no one answered me.

have Server written in Python / FastAPI + Gunicorn running for a prolonged periods of time. After a couple of hours we are noticing some peaks in memory consumption that we haven't been able to resolve for a long time! These peaks are quiet short in time lasting only a couple of ms. They may involve the creation of large as np.ndarray (a couple hundreds of MBs).

I am trying to figure out a way to improve the visibility of the memory usage of the programs when these memory peaks allocations happen. So I came across this article that discusses a very simple [solution](https://medium.com/metabob/chasing-memory-spikes-and-leaks-in-python-172ae99290d3#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjMyM2IyMTRhZTY5NzVhMGYwMzRlYTc3MzU0ZGMwYzI1ZDAzNjQyZGMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTU0MDU0MjgwOTA1OTk5NzI2NzMiLCJoZCI6Im1pbmRlZS5jbyIsImVtYWlsIjoiYmFzaGlyQG1pbmRlZS5jbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3MTY1Mzc5NDksIm5hbWUiOiJCYXNoaXIgQUJERUwgV0FIRUQiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTGllUUg2SldvdzRCWndwaEFQblgtYnNiUmIyTC15b2pteDc4MU9jWGQ3T3pncVNRPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IkJhc2hpciIsImZhbWlseV9uYW1lIjoiQUJERUwgV0FIRUQiLCJpYXQiOjE3MTY1MzgyNDksImV4cCI6MTcxNjU0MTg0OSwianRpIjoiNmQ3MDU0NTgxYWY5ODE4ZGU1MmFmM2IzN2Y3NTI4ZDkwYTkzNTM5YiJ9.QGEAQrVj97C2TfAIG24vH5MzVA6HgkujEMuVd8Aqkyokunel4qEj5ksRxFSlE-yFK8aPAT1WqZUVdjOZxXYkRJdUQMlt6bKbEh96Kr_Xl4CAvx_-_8-Rf34U7Fh1Bfi3NEDJmiMn4UQjZh7wITtP8yl9aP0v7yRiqOePl5FWcqeFdkJiKPmrr_0_DuSip6vj3u6oqAZSvIL5ZAuh896LSPiKfZwuSk3pk1GX23wlFx6vVNRPfWyVjIEpFUCG2BbOoVLPkP0_M-D_XydA8tT39BbwvX1gzl_q1-HiyPo55UtsdLBR7OyI9iq4GJFo1bJbz9My0Lx-JsLZFKVgj7_5BA) (using the resource module)

I tried to do a POC with it before trying it in the actual server. The idea is simple:

1. put a memory limit (say 1MB)
2. try to allocate memory (descending / ascending between 1MB and 0MB) The expected result is a value close to the limit passed to the arguments (990KB for example)

### Reproduce the code example:

```python
import resource
import sys
import numpy as np

import resource

import resource

def format_b(n_bytes):
    """ Format a number of bytes into a human-readable format. """
    for unit in ['B', 'KB', 'MB', 'GB', 'TB', 'PB']:
        if n_bytes < 1024:
            return "%3.1f %s" % (n_bytes, unit)
        n_bytes /= 1024
    return "%.1f %s" % (n_bytes, 'EB')

def set_memory_limit_as(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_AS)
    resource.setrlimit(resource.RLIMIT_AS, (n_bytes, hard))
    print("Setting memory limit to", format_b(n_bytes))

def set_memory_limit_rss(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_RSS)
    print("Setting RSS memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_RSS, (n_bytes, hard))

def set_memory_limit_data(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_DATA)
    print("Setting heap memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_DATA, (n_bytes, hard))

def set_memory_limit_memlock(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_MEMLOCK)
    print("Setting virtual memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_MEMLOCK, (n_bytes, hard))

def set_memory_limit_stack(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_STACK)
    print("Setting virtual memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_STACK, (n_bytes, hard))    

mem_limit = int(sys.argv[1])
set_memory_limit_as(mem_limit)  # try to change this function and re-run the script with 1MB

size = mem_limit * 2
prev_size = 0


try:
    bla = np.random.randint(0, 255,size=(1 * size,), dtype=np.uint8)
    bla += 1
except MemoryError:
    print("Memory errors occurs for mem_limit:" , format_b(size))
    print("expected")
else:
    print("Memory errors did not occur for mem_limit:" , format_b(size))
    print("unexpected")
    exit(1)

# use dichotomy to find the highest value between size and prev_size that does not raise a MemoryError
while size - prev_size > 1_000:  # a difference of 1KB
    new_size = (size + prev_size) // 2
    print("trying mem_limit:" , format_b(new_size))
    try:
        bla = np.zeros(1* new_size, dtype=np.uint8)
        print("Memory errors did not occur for mem_limit:" , format_b(new_size))
    except MemoryError:
        print("Memory errors occurs for mem_limit:" , format_b(new_size))
        size = new_size
    else:
        prev_size = new_size
 
print("Memory limit is around:" , format_b(prev_size))
```

### Error message:

```shell
Sadly it doesn't behave as expected, whatever the memory limit I use.

Here is the output I am getting on my ubuntu 22:
$ python memory-limit.py 1_000_000 # with RLIMIT_AS
Setting memory limit to 976.6 KB
Memory errors occurs for mem_limit: 1.9 MB
expected
trying mem_limit: 976.6 KB
Memory errors occurs for mem_limit: 976.6 KB
...
Memory limit is around: 61.0 KB
$ python memory-limit.py 1_000_000  # with RLIMIT_RSS                                                                              
Setting RSS memory limit to 976.6 KB
Memory errors did not occur for mem_limit: 1.9 MB
unexpected
$ python memory-limit.py 1_000_000    # with RLIMIT_DATA                                                                          
Setting heap memory limit to 976.6 KB
Memory errors occurs for mem_limit: 1.9 MB
expected
trying mem_limit: 976.6 KB
...
Memory limit is around: 61.0 KB
$  python memory-limit.py 1_000_000  # withRLIMIT_MEMLOCK                                                                             
Setting virtual memory limit to 976.6 KB
Memory errors did not occur for mem_limit: 1.9 MB
unexpected
$ python memory-limit.py 1_000_000   # with RLIMIT_STACK  of course this is an expected behavior because this is the stack memory that we are limiting!                                                                          
Setting virtual memory limit to 976.6 KB
Memory errors did not occur for mem_limit: 1.9 MB
unexpected
```

### Python and NumPy Versions:

1.26.4 + python 3.11 + ubuntu 22.04

### Context for the issue:

Thanks for submitting an edit. It is only visible to you until it’s been [approved](https://stackoverflow.com/suggested-edits/5618036) by trusted community members.
I have Server written in Python / FastAPI + Gunicorn running for a prolonged periods of time. After a couple of hours we are noticing some peaks in memory consumption that we haven't been able to resolve for a long time! These peaks are quiet short in time lasting only a couple of ms. They may involve the creation of large as np.ndarray (a couple hundreds of MBs).

I am trying to figure out a way to improve the visibility of the memory usage of the programs when these memory peaks allocations happen. So I came across this article that discusses a very simple [solution](https://medium.com/metabob/chasing-memory-spikes-and-leaks-in-python-172ae99290d3#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjMyM2IyMTRhZTY5NzVhMGYwMzRlYTc3MzU0ZGMwYzI1ZDAzNjQyZGMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTU0MDU0MjgwOTA1OTk5NzI2NzMiLCJoZCI6Im1pbmRlZS5jbyIsImVtYWlsIjoiYmFzaGlyQG1pbmRlZS5jbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYmYiOjE3MTY1Mzc5NDksIm5hbWUiOiJCYXNoaXIgQUJERUwgV0FIRUQiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jTGllUUg2SldvdzRCWndwaEFQblgtYnNiUmIyTC15b2pteDc4MU9jWGQ3T3pncVNRPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IkJhc2hpciIsImZhbWlseV9uYW1lIjoiQUJERUwgV0FIRUQiLCJpYXQiOjE3MTY1MzgyNDksImV4cCI6MTcxNjU0MTg0OSwianRpIjoiNmQ3MDU0NTgxYWY5ODE4ZGU1MmFmM2IzN2Y3NTI4ZDkwYTkzNTM5YiJ9.QGEAQrVj97C2TfAIG24vH5MzVA6HgkujEMuVd8Aqkyokunel4qEj5ksRxFSlE-yFK8aPAT1WqZUVdjOZxXYkRJdUQMlt6bKbEh96Kr_Xl4CAvx_-_8-Rf34U7Fh1Bfi3NEDJmiMn4UQjZh7wITtP8yl9aP0v7yRiqOePl5FWcqeFdkJiKPmrr_0_DuSip6vj3u6oqAZSvIL5ZAuh896LSPiKfZwuSk3pk1GX23wlFx6vVNRPfWyVjIEpFUCG2BbOoVLPkP0_M-D_XydA8tT39BbwvX1gzl_q1-HiyPo55UtsdLBR7OyI9iq4GJFo1bJbz9My0Lx-JsLZFKVgj7_5BA) (using the resource module)

I tried to do a POC with it before trying it in the actual server. The idea is simple:

put a memory limit (say 1MB)
try to allocate memory (descending / ascending between 1MB and 0MB) The expected result is a value close to the limit passed to the arguments (990KB for example)
import resource
import sys
import numpy as np

import resource

import resource

def format_b(n_bytes):
    """ Format a number of bytes into a human-readable format. """
    for unit in ['B', 'KB', 'MB', 'GB', 'TB', 'PB']:
        if n_bytes < 1024:
            return "%3.1f %s" % (n_bytes, unit)
        n_bytes /= 1024
    return "%.1f %s" % (n_bytes, 'EB')

def set_memory_limit_as(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_AS)
    resource.setrlimit(resource.RLIMIT_AS, (n_bytes, hard))
    print("Setting memory limit to", format_b(n_bytes))

def set_memory_limit_rss(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_RSS)
    print("Setting RSS memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_RSS, (n_bytes, hard))

def set_memory_limit_data(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_DATA)
    print("Setting heap memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_DATA, (n_bytes, hard))

def set_memory_limit_memlock(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_MEMLOCK)
    print("Setting virtual memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_MEMLOCK, (n_bytes, hard))

def set_memory_limit_stack(n_bytes):
    _, hard = resource.getrlimit(resource.RLIMIT_STACK)
    print("Setting virtual memory limit to", format_b(n_bytes))
    resource.setrlimit(resource.RLIMIT_STACK, (n_bytes, hard))    

mem_limit = int(sys.argv[1])
set_memory_limit_as(mem_limit)  # try to change this function and re-run the script with 1MB

size = mem_limit * 2
prev_size = 0

try:
    bla = np.random.randint(0, 255,size=(1 * size,), dtype=np.uint8)
    bla += 1
except MemoryError:
    print("Memory errors occurs for mem_limit:" , format_b(size))
    print("expected")
else:
    print("Memory errors did not occur for mem_limit:" , format_b(size))
    print("unexpected")
    exit(1)

# use dichotomy to find the highest value between size and prev_size that does not raise a MemoryError
while size - prev_size > 1_000:  # a difference of 1KB
    new_size = (size + prev_size) // 2
    print("trying mem_limit:" , format_b(new_size))
    try:
        bla = np.zeros(1* new_size, dtype=np.uint8)
        print("Memory errors did not occur for mem_limit:" , format_b(new_size))
    except MemoryError:
        print("Memory errors occurs for mem_limit:" , format_b(new_size))
        size = new_size
    else:
        prev_size = new_size
 
print("Memory limit is around:" , format_b(prev_size))
Sadly it doesn't behave as expected, whatever the memory limit I use.

Here is the output I am getting on my ubuntu 22:

$ python memory-limit.py 1_000_000 # with RLIMIT_AS
Setting memory limit to 976.6 KB
Memory errors occurs for mem_limit: 1.9 MB
expected
trying mem_limit: 976.6 KB
Memory errors occurs for mem_limit: 976.6 KB
...
Memory limit is around: 61.0 KB
$ python memory-limit.py 1_000_000  # with RLIMIT_RSS                                                                              
Setting RSS memory limit to 976.6 KB
Memory errors did not occur for mem_limit: 1.9 MB
unexpected
$ python memory-limit.py 1_000_000    # with RLIMIT_DATA                                                                          
Setting heap memory limit to 976.6 KB
Memory errors occurs for mem_limit: 1.9 MB
expected
trying mem_limit: 976.6 KB
...
Memory limit is around: 61.0 KB
$  python memory-limit.py 1_000_000  # withRLIMIT_MEMLOCK                                                                             
Setting virtual memory limit to 976.6 KB
Memory errors did not occur for mem_limit: 1.9 MB
unexpected
$ python memory-limit.py 1_000_000   # with RLIMIT_STACK  of course this is an expected behavior because this is the stack memory that we are limiting!                                                                          
Setting virtual memory limit to 976.6 KB
Memory errors did not occur for mem_limit: 1.9 MB
unexpected
Two things shock me in the experiments above:

for the case of RLIMIT_AS and RLIMIT_DATA, why memory fail to be allocated even though the requested memory is far lower than the limit set (memory_limit is set at 1MB and process fails for 100KB!?)
Why memory allocation succeeds in the case of RLIMIT_RSS set to 1MB and requested memory is 2MB!?
Is there any way to achieve my long sought solution ? Or shall I stay an astray man :D ?

**Comment by seberg** [comment] 2024-05-28 08:12
Closing, I don't think these questions belong here, memory allocation is tricky in any case due to virtual memory (which is what you are allocating).

**Closed by seberg** 2024-05-28 08:12 UTC
Labels: 00 - Bug

**Comment by bashirmindee** [comment] 2024-05-28 08:19
do you have any suggestion as to where I can ask this question ? I asked on stackoverflow but I got no answer as I write these words.

**Comment by mattip** [comment] 2024-05-28 11:29
Debugging memory allocation problems is tricky. There are many layers of caching and forms of allocation and virtual memory layers, and there is no one-size-fits all answer. That is probably why you are not getting any answers. From a cursory reading of the description, I am not sure what the problem is and what you actually are tracking. How do you see the spikes you describe, and why do they bother you?

**Comment by bashirmindee** [comment] 2024-05-28 12:11
I have my gunicorn server hosted in a kubernetes cluster. Since multiple PODs run on the same Node, I should put a memory request and a memory limit in order to disallow any POD to take more memory then allowed for it ([cf doc](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#create-a-limitrange-and-a-pod)).

For the usage I currently have, The following sort of configuration:
```yaml
resources:
  limits:
    memory: 10Gi
  requests:
    cpu: 4
    memory: 6Gi
```

I am setting the limit this high only because of memory spikes. These spikes can go up by a couple of GBs at a time which seems a bit off and dangerous.

Also the memory consumption of the POD at the start is somewhere around 1GB. Then it goes up to around 6GB which again seems a little bit too high for a water mark caused by memory fragmentation (x6).

**Comment by mattip** [comment] 2024-05-28 17:12
Don't use `np.zeros` as a proxy for memory allocation. It does not do what you think it does. Use `np.ones` or `np.random.randint` which will actually write to the memory and force true allocation.

**Comment by bashirmindee** [comment] 2024-05-31 09:01
I tried it but  I still have the same issues
