### ISSUE TITLE
f2py: parameter type inference fails because incomplete handling of kind specs

### ISSUE THREAD

**Issue by utke1** [numpy/numpy#8493] opened 2017-01-17 18:18 UTC
The following valid code snippet originally from pymc/gibbsit.f  (cf  https://github.com/pymc-devs/pymc/blob/master/pymc/gibbsit.f )  exhibits the problem: 
```
...
      program   gibbsit

      integer   maxiterates
      parameter (maxiterates=50000)

      integer   maxseries
      parameter (maxseries=20)

      integer   maxqcnt
      parameter (maxqcnt=20)

      integer   wasize
      parameter (wasize=maxiterates*2)
```
showing up for f2py version 2 in numpy 1.12.0 as: 
```
   Line #196 in pymc/gibbsit.f:"      parameter (wasize=maxiterates*2)"
        get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-en5WK5/pymc/setup.py", line 124, in <module>
        **(config_dict))
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/command/egg_info.py", line 18, in run
        self.run_command("build_src")
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/command/build_src.py", line 148, in run
        self.build_sources()
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
        self.build_extension_sources(ext)
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/command/build_src.py", line 327, in build_extension_sources
        sources = self.f2py_sources(sources, ext)
      File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/command/build_src.py", line 564, in f2py_sources
        ['-m', ext_name]+f_sources)
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/f2py2e.py", line 408, in run_main
        postlist = callcrackfortran(files, options)
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
        postlist = crackfortran.crackfortran(files)
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 3245, in crackfortran
        readfortrancode(files, crackline)
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 511, in readfortrancode
        dowithline(finalline)
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 782, in crackline
        analyzeline(m, pat[1], line)
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 1188, in analyzeline
        t = determineexprtype(initexpr, params)
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 2971, in determineexprtype
        return _ensure_exprdict(vars[e])
      File "/usr/local/lib/python2.7/dist-packages/numpy/f2py/crackfortran.py", line 2947, in _ensure_exprdict
        raise AssertionError(repr(r))
    AssertionError: ''
```

a pull request with a proposal to fix it will follow.

**Comment by charris** [comment] 2017-01-17 19:10
Might be a duplicate of #8479.

**Closed** 2017-01-29 01:38 UTC
Labels: component: numpy.f2py
