### ISSUE TITLE
Error in running Python script that import Numpy in C program

### ISSUE THREAD

**Issue by Lequanghy** [numpy/numpy#19569] opened 2021-07-27 17:04 UTC
I'm trying to run the Python script in the C program, here is the code:
``` 
#include <Python.h>
int main(void) 
{
   char filename[MAX_STRING_LENGTH] = "example.py";
   FILE* fp;
   Py_Initialize();
   fp = _Py_fopen(filename, "r");
   PyRun_SimpleFile(fp, filename);
   Py_Finalize();
   return 0;
}
```

Here is the code in *example.py*
```
import numpy as np
```

When I ran the C code in Visual Studio Community 2019, it returns that it could not find ```numpy.core._multiarray_umath```. This is the error message that I got from the run:
```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\USER\Desktop\example.exe"
  * The NumPy version is: "1.21.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```
I tried to uninstall and reinstall Numpy a couple of times but it did not fix the problem.

**Comment by melissawm** [comment] 2021-07-27 17:07
Did you try any of the solutions in the link mentioned in the error message? Did you confirm that you can import NumPy after installing it?

**Comment by mattip** [comment] 2021-07-27 17:15
It seems this is a continuation of the [stackoverflow question](https://stackoverflow.com/questions/68504498/error-in-running-python-script-that-import-numpy-in-c-program?noredirect=1#comment121146067_68504498) from yesterday

Are you linking to the python39.lib in `C:\Users\USER\AppData\Local\Programs\Python\Python39` when you compile your program? What is printed when you add this before importing numpy in your script?
```
import sys
print sys.version
```

**Comment by Lequanghy** [comment] 2021-07-27 19:35
> It seems this is a continuation of the [stackoverflow question](https://stackoverflow.com/questions/68504498/error-in-running-python-script-that-import-numpy-in-c-program?noredirect=1#comment121146067_68504498) from yesterday
> 
> Are you linking to the python39.lib in `C:\Users\USER\AppData\Local\Programs\Python\Python39` when you compile your program? What is printed when you add this before importing numpy in your script?
> 
> ```
> import sys
> print sys.version
> ```

Hi mattip, it printed "3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]".
When I run the Python script in PyCharm or any Python IDE. It can import Numpy. However, it doesn't work when I run the Python script in a C program.

**Comment by Lequanghy** [comment] 2021-07-27 19:39
> Did you try any of the solutions in the link mentioned in the error message? Did you confirm that you can import NumPy after installing it?

Hi melissawm, I have checked the links and tried their solution. I can import and run Numpy in PyCharm, VSCode and Eclipse. But when I import Numpy as a Python code in a C program then it returns that error above.

**Comment by mattip** [comment] 2021-07-27 19:51
1. Can you run `python -c "import numpy"` from a DOS command prompt?
2. How are you running the C program?

**Comment by Lequanghy** [comment] 2021-07-27 20:16
> 1. Can you run `python -c "import numpy"` from a DOS command prompt?
> 2. How are you running the C program?

1. The command prompt can run ```python -c "import numpy"``` but returns nothing.
2. I run my C program in Visual Studio Community 2019. I compile it into an executable file and run it.

**Comment by mattip** [comment] 2021-07-27 22:18
1. That is good, it means there was no error
2. What exactly are you doing to run it? Some example answers: "I am pressing ctrl-f5", "I am running it through the debugger", "I am opening a DOS command prompt just like in (1)". Hint: try the last one.

**Comment by Lequanghy** [comment] 2021-07-29 16:15
Hi @mattip, I did all of the solutions you mentioned. I pressed ctrl-f5, ran the C program through the debugger and compiled the program in Command Prompt. However, they returned the same error.

**Comment by mattip** [comment] 2021-07-29 17:10
Sorry, out of ideas.
FWIW, I can successfully run your code on windows10. You may have some luck studying [the new features related to loading DLLs in python3.8](https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew) or looking for tools like [depends.exe](https://dependencywalker.com/)

**Comment by Lequanghy** [comment] 2021-07-29 17:28
Did you run my code on your computer?

**Comment by mattip** [comment] 2021-07-29 18:21
Yes, on Windows10. I copied your code to a file `main.c`. created an `example.py` with `import numpy as np; print('ok') and ran 
```
cl -I <path-to-python>\include /link /LIBPATH:<path-to-python>\libs main.c
```

Then I could run `main.exe` which printed `ok`

**Comment by seberg** [comment] 2022-11-03 11:02
Closing, since it was not possible to reproduce this import issue and it is old, so I don't think there is anything to be done/picked up here at this point.
A new issue could be opened if necessary, though.

**Closed by seberg** 2022-11-03 11:02 UTC
