### ISSUE TITLE
Problem to accessing column items assigned from single numpy.str_ value in structured array

### ISSUE THREAD

**Issue by xS-Sx** [numpy/numpy#12670] opened 2019-01-05 17:22 UTC
UnicodeDecodeError occurred when accessing an item assigned from another numpy array item. I dont know if this is made by design 
### Reproducing code example:

```python
>>> import numpy as np
>>> strA = np.array([('aa', 2),('bb', 4)], dtype=[('c1', 'U2'), ('c2', 'i4')])
>>> strA['c1'][0]
'aa'
>>> strA['c1'] = strA['c1'][0]
>>> strA['c1'][0]
UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)
```

### Error message:
UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)

### Numpy/Python version information:

python 3.6.5 
numpy 1.14.3 and 1.15.4

**Comment by mattip** [comment] 2019-01-05 19:00
What OS? What does does `python -c 'import sys; print(sys.getdefaultencoding())'` print? I cannot replicate on Ubuntu 18.04 (64 bit linux) using `utf-8`, I get `'aa'` from the last line

**Comment by eric-wieser** [comment] 2019-01-11 08:31
I get this behavior too on windows, default encoding is utf8.

I think this is another windows-stores-unicode-scalars-as-utf16 bug.

**Comment by eric-wieser** [comment] 2019-01-11 08:48
No structured array needed, just broadcasted assignment:
```
>>> a = np.zeros(1, 'U2')
>>> a[:] = 'aa'
>>> a.view(np.uint8)
array([97,  0,  0,  0, 97,  0,  0,  0], dtype=uint8)
>>> a[:] = np.str_('aa')
>>> a.view(np.uint8)
array([97,  0, 97,  0,  0,  0,  0,  0], dtype=uint8)

**Comment by mattip** [comment] 2019-01-11 09:40
Python3 added new functions, maybe `PyUnicode_AsUCS4` would force 4-byte unicode use?

**Comment by eric-wieser** [comment] 2019-01-11 17:15
Duplicate of #3258

**Closed by eric-wieser** 2019-01-11 17:15 UTC
Labels: 00 - Bug, component: numpy.core
