### ISSUE TITLE
uint64 is "promoted" to float64 when adding an integer

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#8522] opened 2017-01-24 01:17 UTC
```
In [8]: a = np.uint64(2)

In [9]: b = a + 1

In [10]: type(b)
Out[10]: numpy.float64
```

!

**Comment by seberg** [comment] 2017-01-24 10:16
Yes, duplicate of gh-7126 (and probably more). A larger discussion about this is probably better on the mailing list.

**Closed by seberg** 2017-01-24 10:16 UTC
