### ISSUE TITLE
Memory leak when using slice array in loop

### ISSUE THREAD

**Issue by juansulloa** [numpy/numpy#15746] opened 2020-03-12 14:35 UTC
Huge amounts of memory used when running a loop that creates or loads a numpy array, slices the array, and saves to a list.

### Reproducing code example:
I found this issue while making a loop that Ioads a sound at each iteration and slices the first seconds. I managed to reproduce the error creating a simple numpy array at each iteration.

```python
import numpy as np

accum = list()
for i in range(1000):
    s = np.arange(3000000)    
    s_slice = s[0:50]
    accum.append(s_slice)
```

Note that the issue seems to be associated to the class `numpy.ndarray`. The huge memory consumption does not occur if the object is of class list or range:

```python
import numpy as np

accum = list()
for i in range(1000):
    s = range(3000000)    
    s_slice = s[0:50]
    accum.append(s_slice)
```

### Numpy/Python version information:
Numpy version: 1.18.1 

Python version: 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]

**Comment by eric-wieser** [comment] 2020-03-12 14:37
Thanks for the well-explained report.

This is by design - the original array is preserved in `accum[i].base`, since in numpy by default slicing returns a view. Your memory leak will go away if you put `s_slice.copy()` in the `accum` array.

**Comment by seberg** [comment] 2020-03-13 18:35
Indeed thanks for the report and the comprehensive answer, closing. @juansulloa if you are unsure about the explanation please ask!

**Closed by seberg** 2020-03-13 18:35 UTC
