### ISSUE TITLE
BUG: Segfault during import in python embedded application

### ISSUE THREAD

**Issue by orjgre** [numpy/numpy#22198] opened 2022-09-02 10:05 UTC
### Describe the issue:

After upgrading to Ubuntu 22.04 and Python 3.10 I get a segfault when importing numpy in c++.

This was working fine before the upgrade. I've tried creating a reproducible sample, but when creating a new project and copying over all the relevant classes numpy import works fine.

As far as I can tell this happens when import hashlib during some open ssl md5 initialization. Import numpy in a normal python interpreter works fine.

See attachment for verbose module loading.
[verbose_module_load.txt](https://github.com/numpy/numpy/files/9477016/verbose_module_load.txt)

### Reproduce the code example:

```python
Py_SetProgramName(reinterpret_cast<const wchar_t*>("CA"));
Py_Initialize();
if (PyRun_SimpleString("import sys") < 0) {
    fail("Could not import sys module!");
}
auto import = []() {
    import_array();
    return 0L;
};
if (import() < 0) {
    fail("Could not initialize numpy!");
}
```

### Error message:

<details> <summary> Backtrace(?)  </summary>

```shell
<unknown> 0x0000000000000000
py_evp_fromname 0x00007fffc58e6f71
_hashlib_openssl_md5_impl 0x00007fffc58e6dc8
_hashlib_openssl_md5 0x00007fffc58e6dc8
cfunction_vectorcall_FASTCALL_KEYWORDS 0x00007fffe9353599
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a0458
_PyEval_EvalFrameDefault 0x00007fffe92a0458
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
PyEval_EvalCode 0x00007fffe93e91ae
builtin_exec_impl 0x00007fffe93e973d
builtin_exec 0x00007fffe93e973d
cfunction_vectorcall_FASTCALL 0x00007fffe9358653
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
import_name 0x00007fffe92a2705
_PyEval_EvalFrameDefault 0x00007fffe92a2705
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
PyEval_EvalCode 0x00007fffe93e91ae
builtin_exec_impl 0x00007fffe93e973d
builtin_exec 0x00007fffe93e973d
cfunction_vectorcall_FASTCALL 0x00007fffe9358653
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
import_name 0x00007fffe92a2705
_PyEval_EvalFrameDefault 0x00007fffe92a2705
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
PyEval_EvalCode 0x00007fffe93e91ae
cfunction_vectorcall_FASTCALL 0x00007fffe9358653
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
<unknown> 0x00007fffc4c9a4d6
<unknown> 0x00007fffc4c875f5
PyModule_ExecDef 0x00007fffe935477e
_imp_exec_dynamic.lto_priv.0 0x00007fffe9414043
cfunction_vectorcall_O 0x00007fffe935852e
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
builtin___import__ 0x00007fffe93ea0ce
cfunction_call 0x00007fffe9353063
_PyObject_MakeTpCall 0x00007fffe930dd9c
_PyObject_VectorcallTstate abstract.h:112
_PyObject_VectorcallTstate abstract.h:99
_PyObject_CallFunctionVa 0x00007fffe930f429
_PyObject_CallFunctionVa 0x00007fffe930fd01
PyObject_CallFunction 0x00007fffe930fd01
PyImport_Import 0x00007fffe941771e
PyImport_ImportModule 0x00007fffe94178fe
<unknown> 0x00007fffc4cbac7a
PyModule_ExecDef 0x00007fffe935477e
_imp_exec_dynamic.lto_priv.0 0x00007fffe9414043
cfunction_vectorcall_O 0x00007fffe935852e
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
import_name 0x00007fffe92a2705
_PyEval_EvalFrameDefault 0x00007fffe92a2705
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
PyEval_EvalCode 0x00007fffe93e91ae
builtin_exec_impl 0x00007fffe93e973d
builtin_exec 0x00007fffe93e973d
cfunction_vectorcall_FASTCALL 0x00007fffe9358653
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
builtin___import__ 0x00007fffe93ea0ce
cfunction_call 0x00007fffe9353063
_PyObject_Call 0x00007fffe930ee1c
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
PyImport_ImportModuleLevelObject 0x00007fffe9416c05
import_name 0x00007fffe92a2705
_PyEval_EvalFrameDefault 0x00007fffe92a2705
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
PyEval_EvalCode 0x00007fffe93e91ae
builtin_exec_impl 0x00007fffe93e973d
builtin_exec 0x00007fffe93e973d
cfunction_vectorcall_FASTCALL 0x00007fffe9358653
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
builtin___import__ 0x00007fffe93ea0ce
cfunction_call 0x00007fffe9353063
_PyObject_Call 0x00007fffe930ee1c
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
PyImport_ImportModuleLevelObject 0x00007fffe9416c05
import_name 0x00007fffe92a2705
_PyEval_EvalFrameDefault 0x00007fffe92a2705
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
PyEval_EvalCode 0x00007fffe93e91ae
builtin_exec_impl 0x00007fffe93e973d
builtin_exec 0x00007fffe93e973d
cfunction_vectorcall_FASTCALL 0x00007fffe9358653
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a39b8
_PyEval_EvalFrameDefault 0x00007fffe92a39b8
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a1eee
_PyEval_EvalFrameDefault 0x00007fffe92a1eee
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
builtin___import__ 0x00007fffe93ea0ce
cfunction_call 0x00007fffe9353063
_PyObject_Call 0x00007fffe930ee1c
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
builtin___import__ 0x00007fffe93ea0ce
cfunction_call 0x00007fffe9353063
_PyObject_Call 0x00007fffe930ee1c
do_call_core 0x00007fffe929e766
_PyEval_EvalFrameDefault 0x00007fffe929e766
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
PyObject_Vectorcall abstract.h:123
call_function 0x00007fffe92a062e
_PyEval_EvalFrameDefault 0x00007fffe92a062e
_PyEval_EvalFrame pycore_ceval.h:46
_PyEval_Vector 0x00007fffe93ee1ff
_PyObject_VectorcallTstate abstract.h:114
object_vacall 0x00007fffe930e054
_PyObject_CallMethodIdObjArgs 0x00007fffe930e3bf
import_find_and_load 0x00007fffe9416d64
PyImport_ImportModuleLevelObject 0x00007fffe9416d64
builtin___import__ 0x00007fffe93ea0ce
cfunction_call 0x00007fffe9353063
_PyObject_MakeTpCall 0x00007fffe930dd9c
_PyObject_VectorcallTstate abstract.h:112
_PyObject_VectorcallTstate abstract.h:99
_PyObject_CallFunctionVa 0x00007fffe930f429
_PyObject_CallFunctionVa 0x00007fffe930fd01
PyObject_CallFunction 0x00007fffe930fd01
PyImport_Import 0x00007fffe941771e
PyImport_ImportModule 0x00007fffe94178fe
```

</details>

### NumPy/Python version information:

1.21.5 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]

**Comment by mattip** [comment] 2022-09-02 10:48
> After upgrading to Ubuntu 22.04 and Python 3.10 I get a segfault when importing numpy in c++. This was working fine before the upgrade.

I don't understand your description. Did you try to run code compiled for a different version of python with python3.10 without recompiling?

**Comment by orjgre** [comment] 2022-09-02 10:57
Sorry for the bad description. The code is recompiled for 3.10 and linked to libpython3.10.so.1.0.

**Comment by seberg** [comment] 2022-09-02 11:34
Is that the GDB backtrace?  I am wondering if the problem is that your C++ program is already preloading openssl and that blows up because there is a version mismatch with the one from Python or so?!

The gdb traceback(?) that you posted doesn't say much about NumPy.  Did you try importing hashlib from within your C++ extension?

**Comment by orjgre** [comment] 2022-09-02 12:38
That is the GDB backtrace. I tried importing hashlib as well now, and that fails in the same way. I think you're right about the version mismatch. I didn't realize it, but one of the dependencies to my project does indeed use an older version of openSSL from conan. Thanks for the help.

**Comment by seberg** [comment] 2022-09-02 13:19
Thanks for the followups.  I will close the issue since it is not NumPy related.  But we can keep discussing.

**Closed by seberg** 2022-09-02 13:19 UTC
Labels: 00 - Bug
