### ISSUE TITLE
Patch with Ziggurat method for Normal distribution (Trac #1450)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2047] opened 2012-10-19 21:02 UTC
_Original ticket http://projects.scipy.org/numpy/ticket/1450 on 2010-04-10 by trac user ilan, assigned to @charris._

I've written a patch which replaces the Box-Muller transform
in numpy/random/mtrand/randomkit.c with the faster Ziggurat method.
The patch also includes updates to doc-strings which include the
relevant references:

```
Doornik, J.A. (2005), "An Improved Ziggurat Method to Generate Normal
Random Samples", mimeo, Nuffield College, University of Oxford, and
www.doornik.com/research.

Marsaglia, G. and Tsang, W. W. (2000), "The Ziggurat Method for
Generating Random Variables", Journal of Statistcal Software 5,
http://www.jstatsoft.org/v05/i08/

Marsaglia, G. (1964) "Generating a variable from the tail of the
normal distribution", Technometrics 6, 101-102.
```

My patch is based on the support code which J. Doornik has made available
on his web page (first reference).  I've contacted him, and he has given
permission to include his code in numpy on the condition that his paper
is referenced (which the patch does).

The patch was written against http://svn.scipy.org/svn/numpy/tags/1.4.0,
and I've just checked to make sure it can still be applied to the
trunk (revision 8324).  I've tested the patch on Windows, MacOSX, Linux
and Solaris.

The speedup is a bit over 2 times, when creating a large number of Standard
Normal distributed random numbers.  To verify that the method works and
produces good random numbers, I have:
- created a large array, using randn()
- transformed (using the cumulative distribution function) it back to
  uniform distributed random numbers
- written the data to a large file
- performed the diehard tests (I used the dieharder program) on the data

Feel free to hammer the patch.  I hope this patch will make its way
into numpy soon.

**Comment by rkern** [comment] 2015-04-28 10:53
My new favorite candidate for a new core PRNG: http://www.pcg-random.org/

**Comment by njsmith** [comment] 2015-04-30 05:48
PCG is definitely sweet. Random123 is probably also worth a look-in:
  http://www.deshawresearch.com/resources_random123.html

(Cribbed from the thread at JuliaLang/julia#5105 that github helpfully auto-linked above. They also have some other links to recent papers on optimizing RNGs.)

**Comment by bashtage** [comment] 2015-12-07 23:37
I have started some initial work trying to produce a usable implementation of pcg at https://github.com/bashtage/pcg-python.

Right not it has some basic RNGs implemented, as well as the ability to produce multiple streams and advance (skip to point in rng chain).  It a little faster (25-50%) than the NumPy rngs, although I don't do as much (e.g., return only 1-d array).  I'm no expert at C/Cython integration, so I would imagine there are some things I could do to eek out some more performance (e.g., doing more directly in C).

The numpy mtrand code seems complex to me, and I'd welcome any collaboration.

**Comment by rkern** [comment] 2015-12-08 09:48
@bashtage Excellent! I have a C implementation of pcg64 with a software implementation of uint128 arithmetic for those platforms that need it.

I think it's worth playing around with the interface that you have now to work out the API for keyed streams and the like before investing the energy to make the rest of the `RandomState` infrastructure deal with it; that's gonna take a lot of work, unfortunately. One possible path forward is to copy over the `randomkit` and `distributions` C files over to your project and work on making that part of it switch between the Mersenne Twister and the PCG variants. We can probably iterate on that part faster in your project than trying to do the integration in numpy which has more moving parts. But once we get that solved, it will be easier to migrate it over into numpy where we can focus on the rest of the moving parts (i.e. `mtrand.pyx` itself).

**Comment by bashtage** [comment] 2015-12-08 14:02
@rkern I've done some initial experiments with the pcg64 and the performance is a little disappointing.  For example 1,000,000 uniforms takes about 5.7ms with pcg32 and 5.0 with pcg64.  When using the NumPy Guassian generation method this difference is completely lost.  So from a performance POV the pcg64 doesn't add much (all tests suing gcc 4.8.1, so YMMV).  pcg64 does have a longer period and can produce more streams, so still might be worth it (also probably better to just go to the better generator).

Looking through mtrand.pxy, randomkit, distributions, etc, this seems like excessively complex code.  I know it was written a long time ago (from what I can tell mostly < 2005) so this isn't a criticism.  In an ideal work, the random generation code would be refactored so that it would accept random uint32/uint64s from an arbitrary generator.  This would allow further generators to be added with much less pain.  This is also unfortunately outside of my competency as there are things in mtrand.pyx that I don't really understand.

I also noticed there are a lot of functions in distributions.c that don't really need to be written in C (e.g. a Cauchy rng, which is just he ratio of two normals).  From a maintenance POV it might make sense to have a layered approach, from lowest level to highest

vendor-supplied rng code (e.g. pcg-*.c)
shim to provide a consistent interface
core random number generators (i.e., rngs with loops)
cython file with class and non-core rngs

Is your modified pcg64 on github?

**Comment by bashtage** [comment] 2015-12-08 14:03
FWIW the fundamental reason I am interested in this is not performance but the need (which I think is pretty essential) for a real multi-stream/advance-able RNG for parallel applications.

**Comment by rkern** [comment] 2015-12-08 17:13
My main motivation for pcg64 is the period, not speed; I'm surprised that it's faster at all. The typical advice is that one should not draw more numbers than `sqrt(period)`. So for pcg32, `sqrt(2**64) ~ 5 billion`, which is plausible for the more demanding use cases, which we have to design for when we choose a general purpose default. Also, it's nice to only do one draw to get a `double`.

The approach I recommended above is along the lines of what you are suggesting and should help avoid the complexity of `mtrand.pyx` per se until we have to. Modify `rk_state` to be that shim of a consistent C-level interface. Make it work both with a pcg* and with the Mersenne Twister as the underlying core PRNG. Make the C distribution functions work with that generic `rk_state` interface. Ignore `mtrand.pyx` for now.

I still need to add the copyright mumbo-jumbo to my implementation of pcg64, then I'll stick it up on Github.

**Comment by bashtage** [comment] 2015-12-08 18:12
> My main motivation for pcg64 is the period, not speed; I'm surprised that it's faster at all. The typical advice is that one should not draw more numbers than sqrt(period). So for pcg32, sqrt(2**64) ~ 5 billion, which is plausible for the more demanding use cases, which we have to design for when we choose a general purpose default.

This said, the effective period is more like 2**127 since you can have 2**63 (independent-ish) streams.  Of course, this requires some understanding of the RNG to avoid making mistakes.

> Also, it's nice to only do one draw to get a double.

I am guessing this is where the small speed increases come in.

**Comment by bashtage** [comment] 2015-12-15 23:45
I now have a generic structure that allows alternative core RNGs to be used. 
Basically uses the structure:

* core rng files
* shim that provides a small number of functions, but esp random uint32/64 and state structure, as well as a pxi file.
* generic distributions file
* generic pyx file + includes and conditional compilation

These are all combined to produce rng-specific externsion (right now it outputs 4).

Comments welcome at this point.

Some performance numbers:

```
Time to produce 1,000,000 normals
****************************************
dummy_inv_standard_normal           51.90 ms
dummy_zig_standard_normal           15.44 ms
numpy.random_inv_standard_normal    68.71 ms
pcg32_inv_standard_normal           61.30 ms
pcg32_zig_standard_normal           26.00 ms
pcg64_inv_standard_normal           59.90 ms
pcg64_zig_standard_normal           23.01 ms
randomkit_inv_standard_normal       66.53 ms
randomkit_zig_standard_normal       31.66 ms
dtype: object

Normals per second
****************************************
dummy_inv_standard_normal           19.27 million
dummy_zig_standard_normal           64.75 million
numpy.random_inv_standard_normal    14.55 million
pcg32_inv_standard_normal           16.31 million
pcg32_zig_standard_normal           38.46 million
pcg64_inv_standard_normal           16.69 million
pcg64_zig_standard_normal           43.47 million
randomkit_inv_standard_normal       15.03 million
randomkit_zig_standard_normal       31.58 million
dtype: object

Speed-up relative to NumPy
****************************************
dummy_inv_standard_normal         32.4%
dummy_zig_standard_normal        344.9%
pcg32_inv_standard_normal         12.1%
pcg32_zig_standard_normal        164.2%
pcg64_inv_standard_normal         14.7%
pcg64_zig_standard_normal        198.7%
randomkit_inv_standard_normal      3.3%
randomkit_zig_standard_normal    117.0%
```

Dummy is a trivial rng that repeats the same 20 numbers.  Just used to test another hypothetical RNG.

**Comment by njsmith** [comment] 2015-12-16 00:14
Sounds like you're making some great progress!
.
I think that eventually, the API we're going to want to expose for
alternative core RNGs will be something like:
For each core RNG, there is a single Python class -- e.g.
np.random.MersenneTwister, np.random.PCG64, etc. Instances of these classes
hold the RNG state, and expose some basic methods for initialization,
generation and getting/setting state (probably only at the C/Cython level
-- we'll want this to keep most of this API private for now). The
RandomState object then is changed so that it HAS-A core RNG object that it
stores as an instance variable, and we replace all the current calls to
global rng functions with calls to methods on this instance variable.
Common end-user usage would look like:
  # instantiates the default core RNG with random seed
  r = RandomState()
  # instantiates the default core RNG with specified seed
  r = RandomState(seed=123)
  # creates a RandomState using PCG64 with specified seed
  r = RandomState(rng=np.random.PCG64(seed=123))
  # convenience short-hand for the above
  r = RandomState(seed=123, rng="PCG64")

On Tue, Dec 15, 2015 at 4:04 PM, Kevin Sheppard <notifications@github.com>
wrote:

> I now have a generic structure that allows alternative core RNGs to be
> used.
> Basically uses the structure:
>
>    - core rng files
>    - shim that provides a small number of functions, but esp random
>    uint32/64 and state structure, as well as a pxi file.
>    - generic distributions file
>    - generic pyx file + includes and conditional compilation
>
> These are all combined to produce rng-specific externsion (right now it
> outputs 4).
>
> Comments welcome at this point.
>
> Some performance numbers:
>
> Time to produce 1,000,000 normals
> ****************************************
> dummy_inv_standard_normal           51.90 ms
> dummy_zig_standard_normal           15.44 ms
> numpy.random_inv_standard_normal    68.71 ms
> pcg32_inv_standard_normal           61.30 ms
> pcg32_zig_standard_normal           26.00 ms
> pcg64_inv_standard_normal           59.90 ms
> pcg64_zig_standard_normal           23.01 ms
> randomkit_inv_standard_normal       66.53 ms
> randomkit_zig_standard_normal       31.66 ms
> dtype: object
>
> Normals per second
> ****************************************
> dummy_inv_standard_normal           19.27 million
> dummy_zig_standard_normal           64.75 million
> numpy.random_inv_standard_normal    14.55 million
> pcg32_inv_standard_normal           16.31 million
> pcg32_zig_standard_normal           38.46 million
> pcg64_inv_standard_normal           16.69 million
> pcg64_zig_standard_normal           43.47 million
> randomkit_inv_standard_normal       15.03 million
> randomkit_zig_standard_normal       31.58 million
> dtype: object
>
> Speed-up relative to NumPy
> ****************************************
> dummy_inv_standard_normal         32.4%
> dummy_zig_standard_normal        344.9%
> pcg32_inv_standard_normal         12.1%
> pcg32_zig_standard_normal        164.2%
> pcg64_inv_standard_normal         14.7%
> pcg64_zig_standard_normal        198.7%
> randomkit_inv_standard_normal      3.3%
> randomkit_zig_standard_normal    117.0%
>
> Dummy is a trivial rng that repeats the same 20 numbers. Just used to test
> another hypothetical RNG.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/2047#issuecomment-164937719>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by rkern** [comment] 2015-12-16 08:27
My objections to the HAS-A API still hold: https://github.com/numpy/numpy/issues/5299#issuecomment-97764637

**Comment by njsmith** [comment] 2015-12-16 08:40
Responding to your comment there:

> The core generators that I am most interested in adding are those that can be parameterized, but each one in different ways. Making the argument signature dependent on the value of one of the arguments is an antipattern I would like to avoid.

Yes, this is one of the advantages of the HAS-A api -- each core generator class can get its own `__init__` signature. In my proposal we still accept a `seed` argument in `RandomState.__init__` for backcompat, but this would just be a shorthand for the real api where users can instantiate the core generator object however they want.

> I am inclined against having the distribution implementations change by a configuration parameter, but I could be persuaded. Not least, having this mechanism be orthogonal to the selection of the core generator would be ideal.

I guess we've converged now on using an instance parameter to change distribution implementations, and exactly the idea here is that having the implementations and the core generator as separate variables makes them orthogonal -- plus it makes it possible to change the default generator using the same logic as we use for changing the default level. (If no generator or seed is specified, we want to default to the best/fastest generator -- but backcompat means that this is only possible to do if we're also able to switch back to MT if the user later calls `seed`.)

**Comment by rkern** [comment] 2015-12-16 11:34
> In my proposal we still accept a seed argument in RandomState.__init__ for backcompat, but this would just be a shorthand for the real api where users can instantiate the core generator object however they want.

Please don't include the shorthand, then.

> (If no generator or seed is specified, we want to default to the best/fastest generator -- but backcompat means that this is only possible to do if we're also able to switch back to MT if the user later calls seed.)

`seed()` silently switching algorithms is a really confusing behavior! Please don't do it. I would suggest simply leaving `RandomState` alone at the Python API level (under the Cython hood, you can do what you like). I would object less to a HAS-A API under a new name that does not have backwards-compatibility requirements.

There is nothing sacred about the name `RandomState`. It's not even a very good name for what it does.

**Comment by njsmith** [comment] 2015-12-16 23:32
> Please don't include the shorthand, then.

We're not going to break backcompat, and this is hardly complicated...:

```
class RandomState:
    def __init__(self, seed=None, rng=None):
        if rng is None:
             rng = DefaultRNG(seed)
       elif seed is not None:
             raise ValueError("Can't specify seed if rng object is given")
       ...
```

The question of whether we should also a string-based shorthand for well-known RNG objects is a little more complicated and I'm not sure whether or not it's a good idea myself; I'm happy to defer that until we get more into the details.

> `seed()` silently switching algorithms is a really confusing behavior! Please don't do it.

Before, seed set the state of the RNG used for future calls. Now, it would set the state+algorithm used for future calls. What's confusing about that? The `version` code already has `seed` potentially changing the algorithm used for complex distributions, which is substantially harder to explain (but it doesn't much matter, because users don't have to care so long as streams are reproducible).

The alternative is that we could just continue defaulting to the old-and-slow-and-lower-quality algorithms forever, but that seems like a worse outcome to me...

**Comment by njsmith** [comment] 2015-12-16 23:32
Oh, hmm, also: @bashtage: could you open a new issue for the work on replacing the core generator? It's orthogonal to the ziggurat issue which this issue is nominally about...

**Comment by rkern** [comment] 2015-12-17 09:52
Ah, the shorthand that you proposed `r = RandomState(seed=123, rng="PCG64")` does not follow the semantics that you then sketched out. It's this that I object to, because the initialization of the new core PRNGs of interest take various forms, not just a single seed number/array. For example, the most desired new feature of the PCG family is that it has selectable streams.

The interface that I would prefer is one in which I grab the class that I want and use it rather than grabbing two classes and combining them. It's simple and well proven by the standard library.

```
from numpy.random import PCG64

prng = PCG64(seed=1234, stream=5678)
x = prng.weibull(...)
prng.jumpahead(10000)
y = prng.normal(...)
# Restart.
prng.seed(1234)
assert_array_equal(x, prng.weibull(...))
```

Compared to:

```
from numpy.random import RandomState, PCG64

prng = RandomState(rng=PCG64(seed=1234, stream=5678))
x = prng.weibull(...)
prng.rng.jumpahead(10000)
y = prng.normal(...)
# Restart.
prng.seed(1234) # Wait, we're now back to using Mersenne Twister?!
assert_array_equal(x, prng.weibull(...))  # AssertionError
```

The standard approach has the benefit of being manifestly backwards compatible. `RandomState` will always be the Mersenne Twister. We would refactor its guts to use a HAS-A implementation at the C/Cython level, but that doesn't need to show up at the Python API level to make us go into contortions to preserve backwards compatibility.

**Comment by bashtage** [comment] 2016-01-12 14:55
I have started an issue to look at multiple PRNGs: #6967

**Comment by NeilGirdhar** [comment] 2018-03-06 22:47
@charris Why is backward compatibility an issue for variate generation?  The documentation never promised that the same variates would be generated across versions.

**Comment by charris** [comment] 2018-03-06 23:11
@NeilGirdhar It was to allow repeatablility. Changing that is under discussion.

**Comment by rkern** [comment] 2018-03-07 00:46
@NeilGirdhar It's documented here ("Compatibility Guarantee"): https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.html#numpy.random.RandomState

**Comment by NeilGirdhar** [comment] 2018-03-07 16:34
@rkern Oh, I see, my mistake.

**Comment by bashtage** [comment] 2019-04-11 22:47
xref #13163 . This is fixed in the randomgen branch.

**Comment by mattip** [comment] 2019-05-29 10:17
The randomgen branch now supports external BitGenerators, and supports PCG64 natively although there is some discussion about removing some of the BitGenerators. Closing, thanks for providing some of the impetus to make this change.

Please reopen if you feel there are pieces of this missing in the new API.

**Closed by mattip** 2019-05-29 10:17 UTC
Labels: 01 - Enhancement, Patch, component: numpy.random
