### ISSUE TITLE
getting unexpected error from: X.dtype = complex (or Y = X.view(complex))

### ISSUE THREAD

**Issue by twmacro** [numpy/numpy#6678] opened 2015-11-12 18:22 UTC
The following works with numpy 1.9.3 and python 3.4.3, but in numpy 1.10.1 and python 3.5.0 I get `ValueError: new type not compatible with array.` on the `b.dtype = complex` line:

    import numpy as np

    A = np.array([[1., 2.], [3., 4.]])
    A.dtype = complex          # this works

    a = np.array([[1., 2.]])
    a.dtype = complex          # this works

    B = np.array([[1., 2.], [3., 4.]], order='F')
    B.dtype = complex          # this works

    b = np.array([[1.], [2.]], order='F')
    b.dtype = complex   # <--  In 1.10.1, gives `ValueError: new type not compatible with array.`

    print('A = ', A)
    print('a = ', a)
    print('B = ', B)
    print('b = ', b)

The output for the older version is as it should be (I think):

    A =  [[ 1.+2.j]
     [ 3.+4.j]]
    a =  [[ 1.+2.j]]
    B =  [[ 1.+3.j  2.+4.j]]
    b =  [[ 1.+2.j]]

Note that the 1.10.1 gave the same results for `A`, `a`, and `B`.

My current workaround is to flatten `b`, set the dtype, and reshape. I’ve seen this same behavior on Linux and on Windows.

**Comment by charris** [comment] 2015-11-12 18:47
I'd say the old behavior was a bug. A better workaround would be
```
In [8]: b.reshape(1,2).view(np.complex)
Out[8]: array([[ 1.+2.j]])
```
I'd also suggest using view instead of assigning to the dtype. I'd go further, and suggest that the dtype for a given array should be made immutable :)

**Comment by twmacro** [comment] 2015-11-13 01:17
@charris, thank you for looking, but I ask you to look again. :-). The old behavior was consistent. In Fortran order, I expect the rows to merge, like they do for the `B` example. Why don't they in the little `b` example?

Maybe another way to ask is: why does the `B` example need the second column to work?

**Comment by ahaldane** [comment] 2015-11-13 01:40
This looks like a bug due to RELAXED_STRIDES to me. 

    >>> np.array([[1.], [2.]], order='F').view(np.complex)
    ValueError: new type not compatible with array.
    >>> np.array([[1., 2], [2., 3]], order='F').view(np.complex)
    array([[ 1.+2.j,  2.+3.j]])

**Comment by ahaldane** [comment] 2015-11-13 02:06
It's due to the change of behavior of [this line](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/getset.c#L495). The problem is that for the dim of size 1 the array now has both C_CONTIGUOUS and F_CONTIGUOUS flags set, while before it only had F.

I think the problem is illustrated by decreasing the length of the inner dimension

    >>> np.array([[1., 2., 3.], [4., 5., 6.]], order='F').view(complex)
    array([[ 1.+4.j,  2.+5.j,  3.+6.j]])
    >>> np.array([[1., 2.], [3., 4.]], order='F').view(np.complex)
    array([[ 1.+3.j,  2.+4.j]])
    >>> np.array([[1.], [2.]], order='F').view(np.complex)
    ValueError: new type not compatible with array.

So it works for all dims except size 1.

I'm not sure it is possible to fix because in 1.9.3 the arrays `np.array([[1.], [2.]])` and `np.array([[1.], [2.]], order='F')` were different, but in 1.10 there is no way to distinguish them. And I think we want to keep the behavior that `np.array([[1.], [2.]]).view(np.complex)` raises an error.

**Comment by njsmith** [comment] 2015-11-13 04:00
The reason the old behavior makes me (and I'm guessing Chuck) wince and
suck in air through my (our) teeth, is that the output of the operation can
change based on the memory layout of the input array, which is a major
violation of numpy's unwritten style guidelines. Memory layout is supposed
to be an implementation detail, not a thing that changes the actual
semantics of an array. So e.g. reshape produces the same results regardless
of the input's memory layout. It *should* be possible to predict the output
shape of a view cast from knowing only the input shape and the old and new
dtypes, and I actually had no idea that it wasn't possible until I read
this bug report.

**Comment by seberg** [comment] 2015-11-13 08:30
@jaimefrio aime had mentioned these things/generalizations of view before in a longer discussion on the mailing list. At first thought it was an intentional change ;).
I fully agree, that ideally view refuses all fortran arrays, unless it has an order or axis parameter itself. The question is how to get there, and whether this regression is bad enough that we need to revert relaxed strides.

**Comment by njsmith** [comment] 2015-11-13 09:00
I can certainly see an argument for making the OP's case work again since
it's a regression. (At least temporarily -- we might want to deprecate it
at the same time we fix it. And if we do deprecate this then we should make
sure to do so for all Fortran arrays, not just ones that are simultaneously
C and Fortran ordered -- it's not clear to me from the discussion whether
1.10 broke both cases or not.) But I don't see any need to pull out relaxed
strides entirely -- surely we could fix this in a more targeted way.

**Comment by seberg** [comment] 2015-11-13 09:33
Hmmm, we would have to infer the "correct" order from the strides directly ignoring relaxed strides. It would be making (using locally) `IS_FORTRAN` as:
```
if arr.order == C & F:
    return nonrelaxed_order(arr) == F
else:
    return order == F
```

**Comment by seberg** [comment] 2015-11-13 10:33
We could do this type of change anyway, just to be a bit more safe sometimes. But then since these are macros, there is no guarantee the user will get it (except inside numpy itself).

**Comment by ahaldane** [comment] 2015-11-13 12:48
It almost seems like we need another set of flags/macros: In addition to C_CONTIGUOUS and F_CONTIGUOUS, also have C_ORDERED and F_ORDERED. Maybe the current flags are serving dual (conflicting) purposes. But I am a little unclear/muddled on how to think about it right now. 

The CONTIGUOUS flags aren't absolutely needed since they are just simple functions of the strides & dims - in C they could be replaced by a macro. Would C_ORDERED and F_ORDERED also just be functions of the strides & dims? I think that's what you were just saying, @seberg, right? If so that seems like a way to fix this regression.

**Comment by seberg** [comment] 2015-11-13 13:58
The problem is only if users actually want to track what type of arrays they got. Otherwise the "C_ordered" and "F_ordered" is not well defined nonsense IMO ;). The suggestion I meant was that we can add "guessing" logic, to mitigate this (and similar problems) for IS_FORTRAN which is of a "track whether I had C or F order" kind of logic (to some degree).

Overall I am not very happy with all of this, I think we do not guarantee this well enough that one should rely on order never changing. Instead one should always at least assert if the desired order is there and for that the current flags make more sense.

**Comment by charris** [comment] 2015-11-13 15:08
Perhaps we could add an `order` argument to `view`.

**Comment by twmacro** [comment] 2015-11-13 15:38
Having written my own Matlab-like code (from which I am now converting the critical scripts to Python), I definitely concur and can empathize with @njsmith’s concern:

> Memory layout is supposed to be an implementation detail, not a thing that changes the actual semantics of an array.

So, @charris’s idea of adding `order` to `view` makes sense to me … users would always get the behavior they want, but would also be able to get the efficiency if they’re careful.

**Comment by njsmith** [comment] 2015-11-13 16:00
If we're going to add new api for size changing casts, then my preference
would be to try to move towards a world where larger->smaller always
creates a new dimension at the end, and smaller->larger always consumes a
dimension at the end. (And the only constraint is that the last dimension
has to be contiguous.) If possible...
.
Re-reading I see why this has some interaction with relaxed strides. For
the OP: a thing to realize is that in array([[1], [2]], order="F"), the
order argument has no actual effect, because the F and C memory layouts are
identical for that array. (In 1.9 it had a tiny effect in that numpy tried
to keep track of whether an array was "supposed to be" F or C ordered even
when these were identical, but we got rid of this silliness in 1.10 -
that's the "relaxed strides" thing people are talking about.)
.
This mostly makes me more convinced that this behavior has to go, not that
relaxed strides has to go :-). Nonetheless, since the only case that's
affected is column vectors, it wouldn't be *that* unreasonable to allow
contiguous column vectors to have small->large view casting applied with a
deprecation warning to get us over the backcompat hump. It's too bad it
would apply even when the user didn't specify order="F", but it wouldn't be
disastrous IMO.
.
Reverting relaxed strides in 1.10.3 and waiting for 1.11 would also be
possible, but that's a really big change for a .3! I'd be nervous about
breaking more than we fix.

**Comment by charris** [comment] 2015-11-13 16:11
>that's a really big change for a .3!

I really want to keep relaxed strides checking. I think it makes for a more efficient interface to Fortran when needed. OTOH, it does make sense to me to add an order argument to `view`, as a view does needs to take the memory layout into conisideration.  The semantics of `order='F'` would then be the same as for `'C'` except that indexes at the beginning would be consumed or added instead of indexes at the end.

**Comment by ahaldane** [comment] 2015-11-13 16:47
I am very much in favor of keeping relaxed strides. 

For this bug, personally I favor having a special computation just in `array_descr_set` which uses the old fortran-order calculation. This would be fully backwards compatible and keeps relaxed strides. Doing these kinds of views is a power user thing, and I expect that a power user will be able to figure out what is going on. Even in numpy 1.10 `array([[1], [2]], order="F")` is distinguishable from `array([[1], [2]])` by looking at the strides. If we want to make this less opaque I think adding some extra 'C_ORDERED' flags, or a `is_c_ordered` method would work, though I probably don't want to mess with the flags for 1.10.3.

Also, on whether views of different sized dtypes are a good thing, personally I like them and I like that they depend on memory layout. For example, I often want to get the unique rows of a 2d matrix of bytes:

    >>> a = np.random.randint(0,3,size=(1000,6)).astype('u1')
    >>> b = a.view('V6')
    >>> len(np.unique(b))
    541

I'll admit I have never wanted to do this with fortran-ordered arrays, where things start to get a bit insane :)
By the way #5508 was looking this code to make such views even more permissive.

**Comment by charris** [comment] 2015-11-13 16:58
The advantage of a keyword is that it makes the intent explicit. I'm not much in favor of adding flags to signal intent.

**Comment by ahaldane** [comment] 2015-11-13 17:03
Hmm true. Maybe we could go all the way and, instead of an 'order' keyword, have an 'axis' keyword as suggested in #5508. That way you could even view along an axes in the middle.

**Comment by charris** [comment] 2015-11-13 17:57
@ahaldane What would be the use case? It seems to me that it would take some work to create an array contiguous along a middle axis and the same effect could be achieved with the same effort starting with a Fortran or C view.

**Comment by ahaldane** [comment] 2015-11-13 21:01
@charris you are probably right about that. 

In fact, is it the case that it is always possible to transpose to C-order, do the view, and transpose back? I think so. Then deprecating such fortran views is an easier decision.

**Comment by twmacro** [comment] 2015-11-14 15:33
On second thought, adding an `order` or `axis` option to `view` doesn't seem like a good idea to me: unless I'm thinking wrongly, it will either make a copy or change what's in memory -- both no-nos for `view` in my mind (it wouldn't be a view at all). My druthers would be to simply fix the bug and do nothing else. The (bug-fixed) behavior is perfectly understandable and predictable. The help on `view` is already sufficient I think to warn users, but could be expanded if deemed necessary.

My take on deprecating this behavior: "taking power away from power users to protect users that shouldn't be using `view` anyway." :wink:

**Comment by seberg** [comment] 2015-11-14 16:02
@twmacro, no it would not make a copy, it would simply error out and tell you to set the order keyword argument correctly. I.e. if you put in a fortran order array, you would have to explicitly also pass in the order keyword argument. That will in turn secure you from other unexpected changes in the arrays order.

**Comment by seberg** [comment] 2015-11-14 16:04
Or in other words "explicit is better than implicit" ;). If you would do copies, you would also have to add a copy keyword argument probably, which should default to `False`.

**Comment by twmacro** [comment] 2015-11-15 02:03
Ah, that's cool. Silly me. Thanks for straightening me out @seberg :)

**Comment by njsmith** [comment] 2015-11-25 21:37
I don't see the point in adding an order kwarg. This is an incredibly rare use case, and the transposing approach works fine, including via the c api and on older versions of numpy which won't have the kwarg regardless.

**Comment by charris** [comment] 2015-11-26 21:40
Note that the `view` method assigns to the `dtype` attribute, so the behavior is determined by the `array_descr_set` function in `getset.c`.

**Comment by charris** [comment] 2016-01-14 18:17
Closing, we will deprecate the usage in 1.11 and go back relaxed strides by default in 1.12.

**Closed by charris** 2016-01-14 18:17 UTC
Labels: component: numpy.core, Regression
