### ISSUE TITLE
Importing the multiarray numpy extension module failed

### ISSUE THREAD

**Issue by atmosmattbrewer** [numpy/numpy#13238] opened 2019-04-01 23:09 UTC
I am getting the 'Importing the multiarray numpy extension module failed' error message when I create a new python environment and install the python package SatPy. I have uninstalled and reinstalled numpy multiple times and created new environements as well as clone working environments. I am not sure if this issue is caused by SatPy or numpy but when I install SatPy everything breaks.

The full error message I am getting is:

```
ImportError                               Traceback (most recent call last)
~\AppData\Local\conda\conda\envs\sats\lib\site-packages\numpy\core\__init__.py in <module>
     39 try:
---> 40     from . import multiarray
     41 except ImportError as exc:

~\AppData\Local\conda\conda\envs\sats\lib\site-packages\numpy\core\multiarray.py in <module>
     11 
---> 12 from . import overrides
     13 from . import _multiarray_umath

~\AppData\Local\conda\conda\envs\sats\lib\site-packages\numpy\core\overrides.py in <module>
      5 
----> 6 from numpy.core._multiarray_umath import (
      7     add_docstring, implement_array_function, _get_implementing_args)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-9619fcfabd12> in <module>
----> 1 from satpy import Scene
      2 import cartopy.crs as ccrs
      3 import cartopy.feature as cfeature
      4 from metpy.plots import USCOUNTIES
      5 from glob import glob

~\AppData\Local\conda\conda\envs\sats\lib\site-packages\satpy\__init__.py in <module>
     53 CALIBRATION_ORDER = {cal: idx for idx, cal in enumerate(CALIBRATION_ORDER)}
     54 
---> 55 from satpy.utils import get_logger  # noqa
     56 from satpy.dataset import DatasetID, DATASET_KEYS  # noqa
     57 from satpy.readers import (DatasetDict, find_files_and_readers,  # noqa

~\AppData\Local\conda\conda\envs\sats\lib\site-packages\satpy\utils.py in <module>
     32 import re
     33 
---> 34 import numpy as np
     35 import xarray.ufuncs as xu
     36 

~\AppData\Local\conda\conda\envs\sats\lib\site-packages\numpy\__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~\AppData\Local\conda\conda\envs\sats\lib\site-packages\numpy\core\__init__.py in <module>
     69 Original error was: %s
     70 """ % (sys.executable, exc)
---> 71     raise ImportError(msg)
     72 finally:
     73     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\Matthew\AppData\Local\conda\conda\envs\sats\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.
```

I am using conda to install packages. 
My numpy version is: 1.16.2
python: 3.7.3
satpy: 0.13.0

Below is other information regarding path and setup
![pathes](https://user-images.githubusercontent.com/29383396/55365190-6a7f4a80-5498-11e9-8b54-3086122c0b83.PNG)

**Comment by MauiJerry** [comment] 2019-06-22 01:56
same (base) error, different install on a Raspberry Pi3B+, using latest 2019-04008 Raspian Stretch on which I installed Python3.7.3 and ### MatPlotLib.:

> wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz
> tar xf Python-3.7.3.tar.xz; cd Python-3.7.3
> ./configure -enable-optimizations
> # next time skip optimizations ... it took hours!
> make
> sudo make altinstall
> # switch around links so python3 is correct
> sudo unlink /usr/bin/pip3
> sudo unlink /usr/bin/python3m
> sudo unlink /usr/bin/python3
> sudo unlink /usr/bin/python3m-config
> sudo unlink /usr/bin/pyenv
> #
> sudo ln -s /usr/local/bin/pip3.7 /usr/bin/pip3
> sudo ln -s /usr/local/bin/python3.7m /usr/bin/python3m
> sudo ln -s /usr/local/bin/python3.7m-config /usr/bin/python3m-config
> sudo ln -s /usr/local/bin/python3.7 /usr/bin/python3
> sudo ln -s /usr/local/bin/pyenv-3.7 /usr/bin/pyenv
> 
> # then get a bunch of things for project
> sudo apt-get -y install build-essentials checkinstall
> sudo apt-get -y install qt-5default
> sudo apt-get -y install qtcreator
> sudo apt-get -y install i2c-tools
> sudo apt-get -y install python3-gpiozero
> sudo apt-get -y install rpi.gpio
> sudo apt-get -y install python3-pyqt5
> sudo apt-get -y install libffi-dev
> #
> sudo pip3 install --upgrade pip setuptools wheel
> sudo python3 -m pip install -U matplotlib
> sudo pip3 install pyqtgraph
> sudo pip3 install smbus2
> sudo pip3 install adafruit-blinka
> sudo pip3 install adafruit-circuitpython-bme280
> sudo pip3 install Rpi.bme280
> sudo pip3 install Adafruit-SSD1306

numpy was installed as part of MatPlotLib, pip3 shows it as v1.16.4
> python3
Python 3.7.3 (default, Jun 20 2019, 17:01:49) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

>>>

**Comment by MauiJerry** [comment] 2019-06-22 02:00
same/similar error install on a Raspberry Pi3B+, using latest 2019-04008 Raspian Stretch on which I installed Python3.7.3 and ### MatPlotLib.:

> wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz
> tar xf Python-3.7.3.tar.xz; cd Python-3.7.3
> ./configure -enable-optimizations
> // next time skip optimizations ... it took hours!
> make
> sudo make altinstall
> # switch around links so python3 is correct
> sudo unlink /usr/bin/pip3
> sudo unlink /usr/bin/python3m
> sudo unlink /usr/bin/python3
> sudo unlink /usr/bin/python3m-config
> sudo unlink /usr/bin/pyenv
> #
> sudo ln -s /usr/local/bin/pip3.7 /usr/bin/pip3
> sudo ln -s /usr/local/bin/python3.7m /usr/bin/python3m
> sudo ln -s /usr/local/bin/python3.7m-config /usr/bin/python3m-config
> sudo ln -s /usr/local/bin/python3.7 /usr/bin/python3
> sudo ln -s /usr/local/bin/pyenv-3.7 /usr/bin/pyenv
> 
> // then get a bunch of things for project
> sudo apt-get -y install build-essentials checkinstall
> sudo apt-get -y install qt-5default
> sudo apt-get -y install qtcreator
> sudo apt-get -y install i2c-tools
> sudo apt-get -y install python3-gpiozero
> sudo apt-get -y install rpi.gpio
> sudo apt-get -y install python3-pyqt5
> sudo apt-get -y install libffi-dev
> #
> sudo pip3 install --upgrade pip setuptools wheel
> sudo python3 -m pip install -U matplotlib
> sudo pip3 install pyqtgraph
> sudo pip3 install smbus2
> sudo pip3 install adafruit-blinka
> sudo pip3 install adafruit-circuitpython-bme280
> sudo pip3 install Rpi.bme280
> sudo pip3 install Adafruit-SSD1306

numpy was installed as part of MatPlotLib, pip3 shows it as v1.16.4
> python3
Python 3.7.3 (default, Jun 20 2019, 17:01:49) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

>>>

**Comment by mattip** [comment] 2019-08-24 21:09
Closing. This is now a mix of the original issue, which was about a windows user installing satpy into a conda environment, and other users who reported issues on raspberry pi (without opening a new issue). @atmosmattbrewer did you use [`conda install satpy`](https://anaconda.org/conda-forge/satpy)? If so please open a new issue, preferably with the [satpy-feedstock](https://github.com/conda-forge/satpy-feedstock/) or a new issue here.

The raspberry pi issue is a duplicate of gh-14348

**Closed by mattip** 2019-08-24 21:09 UTC
