### ISSUE TITLE
Broken link in a doc (numpy.histogram)

### ISSUE THREAD

**Issue by olegserov** [numpy/numpy#10204] opened 2017-12-12 01:11 UTC
The link from this page:
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.histogram.html
"Source code" leads to this page:
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy-histogram-1.py
that is 404

**Comment by eric-wieser** [comment] 2017-12-12 01:15
Think there's a duplicate issue floating about somewhere for this...

I'm pretty surprised that a graph renders there at all - I was expecting some kind of sphinx directive to render it, but it just ... happens.

**Comment by eric-wieser** [comment] 2017-12-12 01:15
Ah, duplicate of #9500.

**Closed by eric-wieser** 2017-12-12 01:15 UTC
Labels: 00 - Bug, component: Documentation
