### ISSUE TITLE
core.arrayprint.dtype_short_repr does not print byte order

### ISSUE THREAD

**Issue by Lewn** [numpy/numpy#11102] opened 2018-05-15 15:19 UTC
While working with different byte orderings in arrays, I noticed that the `__repr__` of a numpy array does not show the byte ordering of a array. This can be quite confusing when working with mixed byte ordered data.

I traced the problem down to [`core.arrayprint.dtype_short_repr()`](https://github.com/numpy/numpy/blob/master/numpy/core/arrayprint.py#L1347), which, for normal types (not flexible or named) only takes the name of the dtype. The solution for this might be to check if assertion in the docstring holds before returning the value, and if this does not hold return the long version.

```python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 16:13:55) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.3.1 -- An enhanced Interactive Python.

In [1]: import numpy as np

In [2]: dt_big = np.dtype('>u8')

In [3]: dt_small = np.dtype('<u8')

In [4]: dt_big
Out[4]: dtype('>u8')

In [5]: dt_small
Out[5]: dtype('uint64')

In [6]: arr_big = np.array(1, dtype=dt_big)

In [7]: arr_small = np.array(1, dtype=dt_small)

In [8]: arr_big
Out[8]: array(1, dtype=uint64)

In [9]: arr_small
Out[9]: array(1, dtype=uint64)

In [10]: arr_big.dtype
Out[10]: dtype('>u8')

In [11]: arr_small.dtype
Out[11]: dtype('uint64')

In [12]: from numpy import *

In [13]: assert eval(np.core.arrayprint.dtype_short_repr(dt_big)) == dt_big
Traceback (most recent call last):

  File "<ipython-input-14-2969c9cd782a>", line 1, in <module>
    assert eval(np.core.arrayprint.dtype_short_repr(dt_big)) == dt_big

AssertionError
```

**Comment by mattip** [comment] 2018-08-10 22:43
Not sure what the problem is. If you need the byteorder, check the value itself via `dtype.byteorder`. `eval(repr)` is not guaranteed to produce an object, it is only recommended practice.

**Comment by eric-wieser** [comment] 2018-08-10 23:13
@mattip: This is a bug, because the repr should not be ambiguous - even if it doesn't need to be `eval`able

**Comment by ganesh-k13** [comment] 2020-10-27 14:15
I think this is a doc bug right? There is no string (`x`) out there such that eval(x) = dtype('>u8'). These lines are ambiguous:

https://github.com/numpy/numpy/blob/723a92e463112b1163e5adb071644506a24027f4/numpy/core/arrayprint.py#L1373-L1375

**Comment by seberg** [comment] 2023-03-14 13:01
Should be fixed by gh-23295, closing.

**Closed by seberg** 2023-03-14 13:01 UTC
Labels: 00 - Bug, component: numpy.dtype
