### ISSUE TITLE
np.nan incorrectly casted into datetime on powerpc, leading to failing tests of pandas

### ISSUE THREAD

**Issue by yarikoptic** [numpy/numpy#8325] opened 2016-11-28 18:49 UTC
originally detected while building fresh pandas for debian [1], and then verified with current master of numpy:
```shell
(sid_powerpc-dchroot)yoh@partch:~/numpy$ python -c 'import numpy as np; print(np.array([np.nan]).astype("M8[ns]")); print np.__version__'; git describe --tags

['2262-04-10T00:12:45.292707840']
1.13.0.dev0+a4dca24
pre-removal-numpybook-3581-ga4dca24
```

expected result (e.g. on amd64 box):
```shell
$> python -c 'import numpy as np; print(np.array([np.nan]).astype("M8[ns]")); print np.__version__'; 
['NaT']
1.11.2
```

[1] https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=powerpc&ver=0.19.1-2&stamp=1480352140

edit 1:  issue is not new (debian jessie/stable):

```shell
(jessie_powerpc-dchroot)yoh@partch:~$ python -c 'import numpy as np; print(np.array([np.nan]).astype("M8[ns]")); print np.__version__'
['2262-04-10T00:12:45.292707840+0000']
1.8.2
```

**Comment by charris** [comment] 2016-11-28 18:54
Hmm. Could you print out the bit value of np.NaN?

**Comment by charris** [comment] 2016-11-28 18:55
That is
```
In [4]: array(np.nan).tostring()
Out[4]: '\x00\x00\x00\x00\x00\x00\xf8\x7f'
```

**Comment by yarikoptic** [comment] 2016-11-28 19:02
```shell
(sid_powerpc-dchroot)yoh@partch:~/numpy$ LC_ALL=C python -c 'import numpy as np; print(repr(np.array(np.nan).tostring()))'
'\x7f\xf8\x00\x00\x00\x00\x00\x00'
```

**Comment by matthew-brett** [comment] 2016-11-28 19:17
This is a long-standing failure over at : http://nipy.bic.berkeley.edu/builders/numpy-py2.7-debian-ppc

**Comment by yarikoptic** [comment] 2016-11-28 21:23
I would be happy to provide more information if necessary... Still have an active session on one PowerPC box @charris

**Comment by charris** [comment] 2016-11-28 21:32
I'm curious what the following gives
```
In [1]: array(np.nan).astype(int64)
Out[1]: array(-9223372036854775808)

In [2]: print(np.array([np.nan]).astype(int64).astype("M8[ns]"))
['NaT']
```

**Comment by yarikoptic** [comment] 2016-11-28 22:26
```ipython
In [4]: print(np.array([np.nan]).astype(int64).astype("M8[ns]"))
['2262-04-10T00:12:45.292707840']

In [5]: print(np.array([np.nan]).astype(int64))
[-9223372034707292160]
```

**Comment by seberg** [comment] 2016-11-28 22:50
So the problem seems the incorrect cast to int? But why would it not end up at `np.iinfo(np.int64).min`?

**Comment by charris** [comment] 2016-11-28 23:01
OK, the int64 value is off. If I use what you have I get the same datetime. In hex
```
In [21]: a = uint64(-9223372034707292160)

In [22]: hex(a)
Out[22]: '0x8000000080000000L'  # Power PC

In [23]: b = uint64(-9223372036854775808)

In [24]: hex(b)
Out[24]: '0x8000000000000000L'  # Intel
```
Looks very suspicious, but I haven't a clue why that happens. Could even be a hardware glitch, but more likely the compiler or a faulty header. Might grep around for `0x8000000080000000` in system headers and see if anything turns up. Maybe take a look in `limits.h`.

**Comment by seberg** [comment] 2016-11-28 23:15
Do we actually do anything special in numpy or is that `INTMIN` behaviour simply the C casting behaviour?

**Comment by seberg** [comment] 2016-11-28 23:18
Or in other words, not the C behaviour, but the most common one and powerpc does it differently?

**Comment by charris** [comment] 2016-11-28 23:54
The C behavior is undefined, but intel does have a hardware instruction that converts as shown above. I suspect the same with PPC, just that it produces a different result. See  http://stackoverflow.com/questions/10366485/problems-casting-nan-floats-to-int. A code snippet like
```
double h = NAN;
printf("%lx %ld\n", (long long)h, (long long)h);
```
Should settle the question.

**Comment by charris** [comment] 2016-11-28 23:57
Note that the PPC result is just two float32 conversions concatenated.

**Comment by charris** [comment] 2016-11-29 00:10
I think the upshot is that if we want consistent behavior we will need to implement it ourselves. The conversion for `astype` is in the array constructor, I suspect the same for `datetime64`.

**Comment by charris** [comment] 2016-11-29 02:29
And for unsigned types the conversion is right in the middle of the range
```
In [5]: hex(array([np.nan]).astype(uint64))
Out[5]: '0x8000000000000000L'
```

**Comment by seberg** [comment] 2016-11-29 08:02
I wonder if we can't fix part of the problem by having a `np.NaT` constant.

**Comment by yarikoptic** [comment] 2016-11-29 13:28
FWIW -- problem is not specific to powerpc, e.g.

mips (https://buildd.debian.org/status/fetch.php?pkg=pandas&arch=mipsel&ver=0.19.1-2&stamp=1480421632&file=log)
and then looking at two older versions - behavior did change in the past:
```shell
bogomips:~
$> python -c 'import numpy as np; print(repr(np.array(np.nan).astype("M8[ns]"))); print np.__version__'
array(datetime.datetime(1970, 4, 17, 127, 47, 14, 707292), dtype=datetime64[ns])
1.6.2
$> schroot -c stable /bin/bash                                                                                      
$> python -c 'import numpy as np; print(repr(np.array(np.nan).astype("M8[ns]"))); print np.__version__'
array(9223372034707292159L, dtype='datetime64[ns]')
1.8.2
```
new long if I got it right ;)
```
bogomips(jessie):~
*$> PYTHONPATH=$PWD python -c 'from numpy import *; print(hex(uint64(-9223372034707292160)))'
0x8000000080000000L

*$> PYTHONPATH=$PWD python -c 'from numpy import *; print(hex(uint64(9223372034707292159L)))'
0x7fffffff7fffffffL
```

**Comment by charris** [comment] 2016-11-29 16:49
@seberg a np.nat (-2**63) would be a bit odd, but maybe usable. It wouldn't work with float16, and would only convert correctly for 64 bit signed integers (datetime types) and we would still need to replace nans before conversion. I think the best thing to do is try to specialize the conversion to the datetime types, but I haven't located where to do that.  If I had my wishes, the time types would be quad precision floats. Oh well...

**Comment by seberg** [comment] 2016-11-29 18:42
Quad precision floats would sound nice, no silly  precision necessary :). What I meant was creating `np.nat = numpy.datetime64('NaT')` to make making initialization easier, because I wondered if half of these things only used `np.nan` there because it seemed an easy way to get not a time.

**Comment by charris** [comment] 2016-11-29 20:32
@rebeck Probably pandas should not be depending on proper conversion of nans. OTOH, maybe it is documented to go correctly. I would have thought floats would be illegal and they are happily accepted. Anyone know if nan behavior is documented?

**Comment by jjhelmus** [comment] 2016-12-21 02:14
I'm seeing a similar issue on an armv7l system (Raspberry Pi 3) with the 1.12.0 release candidate:

```
$ python -c "import numpy; print(numpy.array([numpy.nan]).view('M8[ns]'))"
['2262-03-16T22:17:17.041090560']
$ python -c "import numpy; print(numpy.__version__)"
1.12.0rc1
```

This is causing the `test_structure_format (test_arrayprint.TestArray2String)` unit test to fail as it sets elements of a datetime array using a nan prior to printing:

```
$ nosetests numpy/core/tests/test_arrayprint.py
..F........
======================================================================
FAIL: test_structure_format (test_arrayprint.TestArray2String)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhelmus/dev/numpy/numpy/core/tests/test_arrayprint.py", line 129, in test_structure_format
    "('NaT',) ('NaT',) ('NaT',)]")
  File "/home/jhelmus/dev/numpy/numpy/testing/utils.py", line 404, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: "[('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',)]"
 DESIRED: "[('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',)\n ('1970-01-01T00:00:00',) ('1970-01-01T00:00:00',) ('NaT',) ('NaT',)\n ('NaT',) ('NaT',) ('NaT',)]"

----------------------------------------------------------------------
Ran 11 tests in 0.456s

FAILED (failures=1)
```

Changing line 124 of `test_arrayprint.py` from ` A[5:].fill(np.nan)` to `A[5:].fill(np.datetime64('NaT'))` allows the unit test to pass but does not address the underlying issue.

**Comment by yarikoptic** [comment] 2017-01-09 15:26
to echo @jjhelmus report -- on armel architecture, situation is the same even with the 2nd beta:
```shell
$ python -c 'import numpy as np; print(np.array([np.nan]).astype("M8[ns]")); print np.__version__';
['1970-01-01T00:00:00.000000000']
1.12.0rc2
```

**Comment by charris** [comment] 2017-01-09 21:26
@yarikoptic This won't get fixed in 1.12.x.

**Comment by matthew-brett** [comment] 2017-02-04 23:00
Another shout-out for this one - it's causing numpy's own test suite to fail on PPC - see #8298 .

**Comment by matthew-brett** [comment] 2017-02-22 20:18
Any thoughts here?   I can offer a PPC machine to debug on.

**Comment by jjhelmus** [comment] 2017-02-22 22:41
Can [line 123]( https://github.com/numpy/numpy/blob/master/numpy/core/tests/test_arrayprint.py#L123) in the `test_arrayprint.py` file be changed from `A[5:].fill(np.nan)` to `A[5:].fill(np.datetime64('NaT'))`?

I believe this will fix the test and setting datetime arrays using NaNs does not appear reliable across different architectures.  The test itself does not seem to concern itself with the representation of NaN in a datetime array but rather that 'NaT' datetime64 elements in structured array should be represented by the string 'NaT' and not None as was previously the case, see #5692.

I'm happy to submit a PR with this change if there is interest.

**Comment by jjhelmus** [comment] 2017-03-30 17:23
The cause of this issue, as @charris and @seberg mentioned, is that in C a cast from a [float64 NaN to a int64 is undefined](http://c0x.coding-guidelines.com/6.3.1.4.html).  

On x86 Intel chips (and likely other x86 and x86_64 platforms) the result is a special integer indefinite value, 0x8000000000000000 or -9223372036854775808 for float64. See section 8.2.1 Indefinites of the [Intel 64 and IA-32 Architectures Software Developer’s Manual](https://software.intel.com/en-us/articles/intel-sdm) for details.  Or other platforms this can be a different value.  For example ARM will returns 0 ["because there are no quiet NaNs in integers"](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0808b/BABFBEJJ.html).

We can see behavior with the following Python code:

``` Python
from __future__ import print_function
import numpy as np
a = np.array([np.nan], dtype=np.float64)
a_int64 = a.astype(np.int64)
a_view = a.view(np.int64)
print("sizeof float64", a.dtype.itemsize)
print("int64:", a_int64[0], "hex", hex(a_int64[0]))
print("int64 view:", a_view[0], "hex", hex(a_view[0]))
```

On an x86_64 system this returns:

```
sizeof float64 8
int64: -9223372036854775808 hex -0x8000000000000000
int64 view: 9221120237041090560 hex 0x7ff8000000000000
```

On an armv7l system:

```
sizeof float64 8
int64: 0 hex 0x0
int64 view: 9221120237041090560 hex 0x7ff8000000000000
```

The results can also be obtained with a C program:

``` c
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <math.h>

int main() {
    double d = NAN;
    printf("sizeof float64 %lu\n", sizeof(double));
    printf("int64: %" PRId64 " hex: %" PRIx64 "\n", (int64_t)d, (int64_t)d);
    printf("int64 view: %" PRId64 " hex: %" PRIx64 "\n", * (int64_t * )&d, * (int64_t *)&d);
    return 0;
}
```

x86_64:

```
sizeof float64 8
int64: -9223372036854775808 hex: 8000000000000000
int64 view: 9221120237041090560 hex: 7ff8000000000000
```

armvl7

```
sizeof float64 8
int64: 0 hex: 0
int64 view: 9221120237041090560 hex: 7ff8000000000000
```

I see two solution to this:  One is to accept that this is an undefined behavior and treat it like other unsafe casts, discourage it but do nothing to prevent a user from triggering the undefined behavior.  The other is to rewrite the DOUBLE_TO_DATETIME and the related functions to detect and replace NaNs and other indefinite floating point values with NPY_DATETIME_NAT.  

The first option is consistent with what is done with casts to int64 (float64 NaN to int64 will give different results depending on the platform) as would be my personal preference.

**Comment by yarikoptic** [comment] 2018-02-26 14:05
With hope to reincarnate interest, since issue still persists and bites -- could any reasonable resolution (besides workarounds in the tests) exist?

**Comment by tylerjereddy** [comment] 2018-08-31 23:08
related: https://github.com/numpy/numpy/pull/11851 I wonder if that helps here on other platforms? The assignment of `np.nan` into `np.datetime64`, and casting to `NaT` used there may be a slightly different code path, but if that behavior is genuinely desired, could perhaps be replicated if another code path is used here.

**Comment by charris** [comment] 2018-09-01 00:52
@tylerjereddy It would be good to solve this issue.

**Comment by ahaldane** [comment] 2018-10-14 19:52
Based on my reading of these issues, we should ultimately disallow *all* casting from floats  to datetime, including `np.nan`. Users should always explicity use `np.datetime('NaT')` to get nat.

The cases where numpy happens to allow floats to be cast to datetime appear to be an unintentional oversight/bug, and that any existing float conversions are very buggy.

### Details 

One can see this through the following inconsistency: There are actually two "casting" code-paths within numpy, which I will call 1. the get/set casting path in `DATETIME_setitem` (links [here](https://github.com/numpy/numpy/blob/2c4c93af0b2d20d85a7432093f31318cbf3c457f/numpy/core/src/multiarray/arraytypes.c.src#L1016) and [here](https://github.com/numpy/numpy/blob/2c4c93af0b2d20d85a7432093f31318cbf3c457f/numpy/core/src/multiarray/datetime.c#L2415)), and 2. the array-transfer code in `DOUBLE_to_DATETIME` [here](https://github.com/numpy/numpy/blob/2c4c93af0b2d20d85a7432093f31318cbf3c457f/numpy/core/src/multiarray/arraytypes.c.src#L1137). They are supposed to be equivalent, but it has happened in the past that these two code paths got out-of-sync for other dtypes. Now we see it has happened for datetime too.

##### get/set
In the case of datetime, the get/set path forbids all conversion from floats. Thus the following operations currently fail:
```python
>>> np.array([1.0], dtype="M8[ns]")
ValueError: Could not convert object to NumPy datetime
>>> a = np.ones(1, dtype="M8[ns]")
>>> a[0] = 1.0
ValueError: Could not convert object to NumPy datetime
```
This seems conspicuously intentional, as that code explicitly allows a number of other casts.

##### dtype-transfer
On the other hand, the array-transfer code just has a single-catch-all line for all numerical casts:
```C
*op++ = (npy_datetime)*ip;
```
where in C numpy has defined `npy_datetime` as `typedef npy_int64 npy_datetime`. This does strange undefined things if `ip` is a float, dependent on the platform. Based on the non-specific way this code is organized, it appears to me to be an accident/oversight that this cast from float was allowed.

And it is not just nan that is strange, it is any float that cannot be represented as an int64, which happens to be the majority of possible float values. On x64, for instance, it seem to cycle back to negative values multiple times as you increase the float value past 9e18.

#### summary
One way or another, we have to fix the inconsistency in the casting code. I suggest we make both paths follow the get/set behavior, and always disallow cast from float to datetime.

**Comment by tylerjereddy** [comment] 2018-10-14 23:37
@ahaldane I've been trying to work through some of the casting cases.

Are you ok with the proposed casting in the other direction, from NaT->NaN i.e., in #11890.

I've definitely noticed the getitem vs. inner loop typecasting thing.

**Comment by ahaldane** [comment] 2018-10-14 23:57
Oh OK. Let me comment there.

**Comment by eric-wieser** [comment] 2018-10-15 01:31
I've changed my mind - I think that we should allow casting from any float to timedelta, provided that casting=unsafe.

If I have a collection of floats and nans, amd want to convert to timedeltas and nat, then going through an intermediate int64 doesn't work.

**Comment by seberg** [comment] 2022-06-15 01:03
I think this is long fixed, although maybe not for `float16 -> times`, I will open a new issue for that.  It was fixed in gh-14669.

**Closed by seberg** 2022-06-15 01:03 UTC
Labels: component: numpy.core, 54 - Needs decision
