### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by Arafatk** [numpy/numpy#7640] opened 2016-05-15 19:58 UTC
On this page for numpy least [squares](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.lstsq.html). The last [link](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy-linalg-lstsq-1.py) given for source code is broken.

**Comment by rgommers** [comment] 2016-05-16 07:57
There are two issues. The easy one is figure out why the plot doesn't display. The hard one is figure out what's wrong with ``matplotlib.sphinxext.plot_directive``, because the broken links are not specific to this ``lstsq`` example - see for example [rand](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.random.uniform.html#numpy.random.uniform)

**Comment by rgommers** [comment] 2016-05-16 07:58
marked as easy-fix the part about just getting the plot to display.

**Comment by pv** [comment] 2016-05-16 08:05
The simple "fix" is to just hide the links (even if they work they don't 
add that much value since the source is visible and you have the `>>>` 
buttons) by adding `plot_html_show_formats = False` to the 
docs/source/conf.py

**Comment by bhavikat** [comment] 2016-07-05 16:41
I think the issue with `matplotlib.sphinxext.plot_directive` has been fixed in subsequent matplotlib releases. My setup is using matplotlib v1.3.1 and it generates [this example](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy-linalg-lstsq-1.py) and [rand](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy-random-uniform-1.py) just fine.

**Comment by rohitrango** [comment] 2016-10-13 12:33
I'm unable to reproduce the bug. Running the Makefile generates everything, like source code, png and pdf files as well.
I'm using matplotlib v1.5.3 and numpy  1.12.0.dev

**Comment by charris** [comment] 2016-10-13 15:53
Closing this, sounds like the problem has been fixed somewhere along the line.

**Closed by charris** 2016-10-13 15:53 UTC
Labels: 04 - Documentation, Easy Fix
