### ISSUE TITLE
BUG: numpy 1.23.5 produced incorrect matmul results on some Intel Sapphire Rapids CPUs

### ISSUE THREAD

**Issue by wenchenvincent** [numpy/numpy#24903] opened 2023-10-12 04:23 UTC
### Describe the issue:

With version 1.23.5, the function numpy.matmul would reproduce wrong results on some Intel Sapphire Rapids CPUs, including and not limited to:
Intel(R) Xeon(R) Platinum 8480C
Intel(R) Xeon(R) Platinum 8468

An easy manifestation of the bug is that matmul(A,B) and matmul(B.T, A.T).T produce results that exceed the typical tolerance.

Further investigation shows that this issue occurs on numpy versions from 1.23.0 to 1.23.5, and does not occur before 1.23.0 or from 1.24.0 onwards.

### Reproduce the code example:

```python
import numpy as np

A = np.random.rand(625, 5)
B = np.random.rand(5, 625)

D_row = np.matmul(A, B)
D_col = np.matmul(B.T, A.T).T
print(np.testing.assert_allclose(D_row, D_col))
```

### Error message:

```shell
Traceback (most recent call last):
  File "/workspace/run_matmul.py", line 8, in <module>
    print(np.testing.assert_allclose(D_row, D_col))
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 371950 / 390625 (95.2%)
Max absolute difference: 2.21191806
Max relative difference: 10.78649948
 x: array([[0.659431, 1.363793, 1.90549 , ..., 0.351029, 0.806503, 0.904222],
       [1.769708, 2.061237, 2.123309, ..., 1.327891, 1.120773, 1.482003],
       [1.461434, 1.901671, 2.156117, ..., 1.289918, 1.011914, 1.44562 ],...
 y: array([[0.659431, 1.363793, 1.90549 , ..., 0.628684, 0.856478, 0.784309],
       [1.769708, 2.061237, 2.123309, ..., 1.291828, 1.356259, 0.985162],
       [1.461434, 1.901671, 2.156117, ..., 1.012965, 1.53703 , 0.872774],...
```

### Runtime information:

1.23.5
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

### Context for the issue:

Tensorflow uses the results from numpy as references for some of its unit tests (e.g. //tensorflow/python/kernel_tests/math_ops:tensordot_op_test_gpu). Currently, the numpy version used for running unit tests is 1.23.5. And it would produce wrong reference results on some Intel Sapphire Rapids CPUs.

**Comment by rgommers** [comment] 2023-10-12 09:22
Thanks for the report @wenchenvincent. Could you test with `np.testing.assert_allclose` instead of `np.allclose`? That will show how different the results are (absolute and relative tolerance).

**Comment by wenchenvincent** [comment] 2023-10-12 15:49
> Thanks for the report @wenchenvincent. Could you test with `np.testing.assert_allclose` instead of `np.allclose`? That will show how different the results are (absolute and relative tolerance).

I just updated the ticket with that.

**Comment by wenchenvincent** [comment] 2023-10-24 21:10
@rgommers Hi, Ralf. Could you help assign someone to look into this issue? Thanks!

**Comment by rgommers** [comment] 2023-10-25 06:18
Hmm, it looks like a real bug, but it'll be difficult to reproduce and apparently it's already fixed. Since it's CPU-specific, it seems most likely to be an OpenBLAS or MKL bug - what BLAS library are you using? Or are you using a numpy wheel from PyPI during these tests?

**Comment by seberg** [comment] 2023-10-25 15:54
@wenchenvincent then you have the OpenBLAS that we pack with the NumPy wheels.  You probably have bad luck with a new processor and bugs that made it into OpenBLAS, I do faintly remember there were a few problems like this.
It also means that OpenBLAS fixed those issues, since 1.24 works for you.

Unfortunately, we don't plan on doing additional releases for 1.23, so if 1.24 works for you that would be easiest.  Of course it is possible to build 1.23 with the newer fixed OpenBLAS versions.

There is one other workaround I can offer is that you can use:
```
export OPENBLAS_CORETYPE=Haswell
```
to select a different implementation.  Unfortunately, I am not sure which one would be lower than saphire rapids (or whicher is buggy here).  `Haswell` is almost certainly lower than it should be.

**Comment by wenchenvincent** [comment] 2023-10-27 00:08
Okay. Thanks for the explanation. I will try to ask Tensorflow upstream to bump the numpy version used.

**Comment by seberg** [comment] 2023-10-27 06:38
OK, closing since it's not really actionable.  For testing performance doesn't matter too much and selecting a lower coretype may work well, although not sure how you would do it to just avoid the one broken one.

**Closed by seberg** 2023-10-27 06:38 UTC
Labels: 00 - Bug

**Comment by theintz** [comment] 2024-10-15 08:30
Just putting this here as an FYI for anyone with the same problem searching for a solution: the AWS EC2 instance class m7i uses exactly these processors, so if your application runs on those and uses this particular numpy version, you might run into these described problems.
