### ISSUE TITLE
unnecessary copy of matrix slices in scipy.linalg.blas (due to f2py?)

### ISSUE THREAD

**Issue by bsxfan** [numpy/numpy#15688] opened 2020-03-03 08:42 UTC
This issue is closely related to (https://github.com/scipy/scipy/issues/11606). I have rewritten it here, with a slightly different experiment and a longer explanation. I am posting it also here, because I believe the issue needs a larger audience. My best guess is that the problem is in `f2py`.

Many `numpy` linear algebra operations can be performed efficiently by BLAS (and LAPACK). Some `ndarray` arguments can be sent directly to the underlying BLAS, while others have to be copied, to make types agree and to get the fortran-style memory alignment required by BLAS.

`numpy` usually defaults to C alignment, but fortran-aligned matrices (2d ndarrays) can be obtained in a variety of ways (e.g. by transposition as in my example code below).  
   
To let BLAS perform an operation equivalent to `C = A @ B`, even if `A` and `B` have C alignment, we can still send `A` and `B` almost directly into `scipy.linalg.blas.dgemm` by using their transposed views (shallow copies) `A.T` and `B.T`. We can do this because `dgemm` takes flags that specify that the transposes of the multiplicands should be used, see: [blas.dgemm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.blas.dgemm.html).

However, `dgemm` allows even more. It can be used to do inplace updates equivalent to `C += A @ B`. Although there is no flag to specify to `dgemm` to transpose `C` too, we can still send a C-aligned argument `C` into `dgemm` by using `dgemm` to perform the equivalent of `C.T += B.T @ A.T`.

If however, an argument has neither C nor fortran alignment, then we cannot use the transpose trick and the argument is copied by `scipy.linalg.blas` before it can be sent to the underlying `dgemm` implementation. This happens for example when we take a horizontal slice of a fortran-aligned matrix (see the code example below). 

The [underlying `dgemm`](http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaeda3cbd99c8fb834a60a6412878226e1.html) implementation does however allow such horizontal matrix slices to be processed directly. See the arguments called `LDA, LDB, LDC` in the `dgemm` documentation. These are the strides between elements in the same row and BLAS/LAPACK allows them to be `>=` than the number of rows. I believe `f2py` is too strict here and does an unnecesary copy whenever row stride > number of rows.   

Why does it matter? Mostly speed. In the example below, I found the fortran-aligned `C` argument was updated 25% faster than the slice `S`. My code below demonstrates that the unnecesary copy happens for the sliced argument. The output follows below: 

(Note: The array strides printed by the code below are in terms of bytes. For float64 elements, 8 bytes = 1 float64.)

```python
import numpy as np
import scipy  
from numpy.random import randn
import scipy.linalg.blas as blas

def frandn(m,n): return randn(n,m).T # random m-by-n matrix with fortran order

print("numpy version:",np.__version__)
print("scipy version:",scipy.__version__)
print()

m, n = 1000, 2000

A = frandn(m,n)
B = frandn(m,n)
if A.strides[0]==8: 
    print("A is blas-fiendly, with fortran alignment:")
    print("A.strides = ", A.strides)
    print("Indeed A.flags also show F_CONTIGUOUS: ")
    print(A.flags)
    print()
    
C = frandn(m,m)
print("The same applies to B:")
print("B.flags.f_contiguous = ", B.flags.f_contiguous)
print("and to C:")
print("C.flags.f_contiguous = ", C.flags.f_contiguous,"\n")
    
S = frandn(2*m,m)[0:m,:]  # horizontal slice of fortran matrix
if S.strides[0]==8: 
    print("Although the sliced S is still blas-fiendly, with fortran alignment:")
    print("S.strides = ", S.strides)
if not S.flags.f_contiguous:
    print("... its flags do **not** show F_CONTIGUOUS: ")
    print(S.flags)
    print()


print("Do C += A @ B.T, using dgemm")
C0 = C.copy()
Y = blas.dgemm(1.0, A, B, 
               beta = 1.0, 
               c = C,
               trans_a = False, 
               trans_b = True, 
               overwrite_c = True)
print("in dgemm, return matrix was newly created = ",not Y is C)
print("in dgemm, C was overwritten = ",abs(C0-C).max() > 1e-6)
print("Inplace update  success.")

print("\nDo S += A @ B.T, using dgemm")
S0 = S.copy()
Y = blas.dgemm(1.0, A, B, 
               beta = 0.0, 
               c = S,
               trans_a = False, 
               trans_b = True, 
               overwrite_c = True)
print("in dgemm, return matrix was newly created = ",not Y is S)
print("in dgemm, S was overwritten = ",abs(S0-S).max() > 1e-6)
print("Update was not inplace.")
```

The output was:

```
numpy version: 1.18.1
scipy version: 1.4.1

A is blas-fiendly, with fortran alignment:
A.strides =  (8, 8000)
Indeed A.flags also show F_CONTIGUOUS: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  [ some rows omitted ]

The same applies to B:
B.flags.f_contiguous =  True
and to C:
C.flags.f_contiguous =  True 

Although the sliced S is still blas-fiendly, with fortran alignment:
S.strides =  (8, 16000)
its flags do **not** show F_CONTIGUOUS: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  [ some rows omitted ]


Do C += A @ B.T, using dgemm
in dgemm, return matrix was newly created =  False
in dgemm, C was overwritten =  True
Inplace update  success.

Do S += A @ B.T, using dgemm
in dgemm, return matrix was newly created =  True
in dgemm, S was overwritten =  False
Update was not inplace.
```

**Comment by eric-wieser** [comment] 2020-03-03 09:20
> It can be used to do inplace updates equivalent to `C += A @ B`.

Numpy has no way to detect that you are performing this operation. What you're proposing would have to be spelt `np.linalg.matmul_and_add`, at which point it is sufficiently niche that it probably belongs in scipy instead.

> We can do this because `dgemm` takes flags that specify that the transposes of the multiplicands should be used, see: [blas.dgemm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.blas.dgemm.html).

We already do this today.

> I believe `f2py` is too strict here and does an unnecesary copy whenever row stride > number of rows.

For what it's worth, `f2py` is not used for `@` / `matmul`.

**Comment by eric-wieser** [comment] 2020-03-03 11:09
Phrased more concisely, my guess is that f2py does not appropriately handle array arguments declared as something like:

```fortran
       INTEGER LDA
       DOUBLE PRECISION A(LDA,*)
```

(simplified from `dgemm.f`)

which could indeed accept arrays with strides `(8, 8*LDA)`, even if such an array is not f-contiguous.

**Comment by bsxfan** [comment] 2020-03-03 12:39
@eric-wieser thank you for your clarifications. To summarize: 
- My issue was about a problem in `scipy.linalg.blas`. I was using the numpy `@` and += statements just to explain what the calls to `scipy.linalg.blas.dgemm` were doing. Sorry if this caused confusion.
- I had however tacitly assumed that the implementation of numpy's `@` does make use of `scipy.linalg.blas`.  In contrast, the code you pointed to: [is_blasable2d](https://github.com/numpy/numpy/blob/3296617cc4c0d4a82520caa411050f7c0aeb9aa5/numpy/core/src/umath/matmul.c.src#L40-L62) does look to me like it handles the strides correctly. 
- Question: Do I understand correctly then that numpy uses a different route into BLAS/LAPACK (i.e. not via  `scipy.linalg.blas`). And if so, is that interface callable from user Python code as an alternative to the scipy blas interface?
- We agree that there *is* a problem with `scipy.linalg.blas` and presumably `f2py`. Is **this** issue the right place to highlight that problem and to get it attended to?

**Comment by eric-wieser** [comment] 2020-03-03 13:09
> * Do I understand correctly then that numpy uses a different route into BLAS/LAPACK (i.e. not via  `scipy.linalg.blas`).

Correct, we call blas / lapack directly from C linkage in `umath_linalg.c.src`

> and presumably `f2py`. Is **this** issue the right place to highlight that problem and to get it attended to?

I think it can morph into such an issue, but I think a minimal repro on f2py without involving blas would help a lot with making progress on the issue.

**Comment by rossbar** [comment] 2020-07-12 21:10
Absent a minimal reproducing example it doesn't seem like a lot of progress will be made here.

**Comment by HaoZeke** [comment] 2023-11-19 06:33
Closing for now since there's no reprex :)

**Closed by HaoZeke** 2023-11-19 06:33 UTC
Labels: component: numpy.f2py, 57 - Close?
