### ISSUE TITLE
BUG: nan_to_num change pandas DataFrame in place when copy = True

### ISSUE THREAD

**Issue by lil-blue-curve** [numpy/numpy#27487] opened 2024-09-30 20:12 UTC
### Describe the issue:

When the input to np.nan_to_num is a dataframe with NaNs, the input dataframe is changed in place even when copy=True.

### Reproduce the code example:

```python
import numpy as np
import pandas as pd

x = pd.DataFrame([np.nan])
np.nan_to_num(x, copy=True)
print(x)
```

### Error message:

```shell
Result x is changed to 0.0 even when nan_to_num is called with copy=True.
x should not be changed when copy=True.
```

### Python and NumPy Versions:

2.1.1
3.11.8

**Comment by seberg** [comment] 2024-10-01 09:15
@mtsokol do you happen to remember if there were changes related to `copy=` in 2.1?!  It seems to me that this is a an actual regression from 2.0, in that somewhere it is no assumed that `__array__` returns a copy.

**Comment by seberg** [comment] 2024-10-01 09:18
Sorry, nevermind...  This seems to be a pandas bug.  NumPy passes `copy=True` here, and pandas must not ignore that (but it does ignore it).  @lil-blue-curve could you open a pandas issue?

NumPy could make a defensive copy for a while if this is a huge deal, but I'll doubt that it is enough of an issue for that.

**Comment by lil-blue-curve** [comment] 2024-10-01 17:08
Reported to pandas https://github.com/pandas-dev/pandas/issues/59932

**Comment by mtsokol** [comment] 2024-11-25 11:01
Pandas issue is closed. Can we close it?

**Closed** 2024-11-25 11:05 UTC
Labels: 00 - Bug, 57 - Close?
