### ISSUE TITLE
variance and covariance inconsistency

### ISSUE THREAD

**Issue by tanwang2020** [numpy/numpy#17086] opened 2020-08-14 18:53 UTC
This may be trivial problem, but there seems to be inconsistency between variance and covariance

import numpy as np
x = [1,2,3,4,5,6,7]
np.var(x)

produces 4.0, but then

np.cov(x,x)

produces

array([[4.66666667, 4.66666667],
       [4.66666667, 4.66666667]])

Of course, mathematically var(x) = cov(x,x). The difference here is clearly because in np.var the sum seems to be divided by n while in np.cov the sum seems to be divided by n - 1. For a naive user without paying attention to the detail, this inconsistency may cause some problem.

**Comment by mattip** [comment] 2020-08-15 20:53
Duplicate of #5835, and documented in the note to [var](https://numpy.org/devdocs/reference/generated/numpy.var.html) (about 2/3 down the page)

**Comment by tanwang2020** [comment] 2020-08-15 21:04
Thanks, Matti.

**Comment by tanwang2020** [comment] 2020-08-15 21:11
Dear Matti,

Could I both you with another problem I encountered. I reported this to docs@python.org<mailto:docs%40python.org> but got the bounce-back:
python.org suspects your message is spam and rejected it

Here is the problem:

import math
math.ceil(4*0.20*1000)

produces 800, but

math.ceil(3*0.20*1000)

produces 601.

This is obviously incorrect.

Thanks.

Tan

**Comment by tanwang2020** [comment] 2020-08-15 21:17
By the way,

np.ceil(3*0.20*1000)

gives 601.0

**Comment by mattip** [comment] 2020-08-15 21:46
Floating point numbers are tricky. See [this discussion](https://softwareengineering.stackexchange.com/questions/101163/what-causes-floating-point-rounding-errors).
```
>>> (3 * 0.2) * 1000.0
600.0000000000001
>>> 3 * (0.2 * 1000.0)
600.0
```

**Comment by tanwang2020** [comment] 2020-08-16 00:13
Thanks!

**Comment by rgommers** [comment] 2020-09-23 21:03
closing as a duplicate

**Closed by rgommers** 2020-09-23 21:03 UTC
Labels: 33 - Question, 50 - Duplicate
