### ISSUE TITLE
Polynomial.roots() with Fraction coefficients raises TypeError

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#16565] opened 2020-06-10 18:59 UTC
Attempting to find the roots of a `numpy.polynomial.Polynomial` instance with an object array containing `Fraction` coefficients results in a `TypeError`.

### Reproducing code example:

```python
>>> from fractions import Fraction
>>> from numpy.polynomial import Polynomial
>>> p = Polynomial([Fraction(1, 2), Fraction(1, 3), Fraction(1, 6)])
>>> p.roots()
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Error message:

<details>
  <summary> Full traceback </summary>
  <pre>
Traceback (most recent call last)
<ipython-input-35-68629de4ef51> in <module>
----> 1 p.roots()

~/repos/numpy/numpy/polynomial/_polybase.py in roots(self)
    871 
    872         """
--> 873         roots = self._roots(self.coef)
    874         return pu.mapdomain(roots, self.window, self.domain)
    875 

~/repos/numpy/numpy/polynomial/polynomial.py in polyroots(c)
   1445     # rotated companion matrix reduces error
   1446     m = polycompanion(c)[::-1,::-1]
-> 1447     r = la.eigvals(m)
   1448     r.sort()
   1449     return r

<__array_function__ internals> in eigvals(*args, **kwargs)

~/repos/numpy/numpy/linalg/linalg.py in eigvals(a)
   1061     _assert_stacked_2d(a)
   1062     _assert_stacked_square(a)
-> 1063     _assert_finite(a)
   1064     t, result_t = _commonType(a)
   1065 

~/repos/numpy/numpy/linalg/linalg.py in _assert_finite(*arrays)
    206 def _assert_finite(*arrays):
    207     for a in arrays:
--> 208         if not isfinite(a).all():
    209             raise LinAlgError("Array must not contain infs or NaNs")
    210 

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
  </pre>
</details>

### Numpy/Python version information:

1.20.0.dev0+1d799fd 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0]

**Comment by eric-wieser** [comment] 2020-06-11 07:46
Making this work would require implement `eigvals` on `Fraction` instances, which sounds rather challenging.

**Comment by charris** [comment] 2020-06-11 12:56
There are (irreducible) polynomials that don't factor over the rationals. There are other algorithms for roots that could be implemented for complex types with extended precision, but such things are probably best left to sympy.

**Comment by rossbar** [comment] 2020-06-11 19:53
Agreed - I'm not sure that there's a simple solution. Currently `np.polynomial` allows coefficient arrays of dtype `object` to support things like `Fraction` or `Decimal` coefficients, but the support is not perfect. Some methods work fine (e.g. math operations with `Fraction` coefficients), some silently cast the underlying coefficients (e.g. `p.convert()` casts Fractions to floats, though the dtype remains `object`) and others fail outright (`roots()`). 

Perhaps it's worth documenting that the support for polynomials with coefficient arrays with `dtype=object` is not comprehensive.

**Comment by charris** [comment] 2020-06-11 20:01
Hmm, `c.convert` might be fixable. I expect the problem is in the scaling. What if you pass in object valued domain and window?

**Comment by rossbar** [comment] 2020-06-11 20:10
> What if you pass in object valued domain and window?

This still results in the conversion of the coefficients to floats (at least in the case where the coefficients are originally `Fractions`):

```python
>>> p = Polynomial([Fraction(1, 2), Fraction(1, 3), Fraction(1, 6)])
>>> p.coef
array([Fraction(1, 2), Fraction(1, 3), Fraction(1, 6)], dtype=object)
>>> p.convert().coef
array([0.5, 0.3333333333333333, 0.16666666666666666], dtype=object)
>>> p.domain = np.array([-1, 1], dtype=object)
>>> p.window = np.array([-1, 1], dtype=object)
>>> p.convert().coef
array([0.5, 0.3333333333333333, 0.16666666666666666], dtype=object)
```

Regardless, it seems to me it would be quite challenging to handle this in general for `object` arrays.

**Comment by nikhilreddybilla28** [comment] 2020-09-01 04:34
take

**Comment by charris** [comment] 2022-06-14 17:11
Allowing fractions and such was mostly to allow exact display of polynomial bases as power series for instructional purposes. Computation will generally need floats.

**Comment by charris** [comment] 2022-06-14 18:06
I'm going to close this. It appears that the best fix would be in the documentation.

**Closed by charris** 2022-06-14 18:06 UTC
Labels: component: numpy.polynomial
