### ISSUE TITLE
Default dtype for integers across the int64 upper limit is float  (due to `uint64, int66 -> float64`)

### ISSUE THREAD

**Issue by takluyver** [numpy/numpy#16287] opened 2020-05-18 10:34 UTC
When `np.array()` or `.asarray()` is used to go from a list of integers, without specifying a dtype explicitly, it can pick default dtypes including int64 & uint64. But there's a strange corner case where it defaults to float64 and loses precision, even though all the values could be uint64. Specfically, this occurs when some but not all values can be int64:

```python
In [11]: max_int64 = np.iinfo(np.int64).max                                                                            

In [12]: np.array([max_int64]).dtype                                                                                   
Out[12]: dtype('int64')

In [13]: np.array([max_int64 + 1]).dtype                                                                               
Out[13]: dtype('uint64')

In [14]: np.array([max_int64 + 1, max_int64]).dtype                                                                    
Out[14]: dtype('float64')
```

It doesn't depend on the order they're in, and it's not a general consequence of having two values rather than one - two values above this threshold get `uint64` as I'd expect.

Tested on Numpy 1.18.4, Python 3.8.2.

Sorry if this has already been discussed; it's a tricky thing to search for. This relates to an issue reported on h5py: https://github.com/h5py/h5py/issues/1547 .

**Comment by eric-wieser** [comment] 2020-05-18 12:28
I can confirm we already have an open issue for this, will try to find it later.

**Comment by seberg** [comment] 2020-05-18 13:45
Thanks for the note. There appears to be a recent issue with exactly this report gh-16030

I guess its a combination of two things:

1. We promote `uint64 + int64 -> float64` (e.g. gh-11801 is related, probably more, also gh-5745)
2. We try different dtypes when given an integer with `np.array` when the value does not fit the actual system default. (usually `int64 -> uint64 -> object`) (I feel I/we must have noted it at least once, but do not find it)

The second one is something I somewhat hope to simplify to always giving the default integer (would lead to an error during item assignment, unless there is an actual float around somewhere) at some point.
The first point I am less sure about, but it may be worth trying to deprecate? It might force quite a few people to `view` or cast their arrays explicitly.

**Comment by takluyver** [comment] 2020-05-18 13:54
Thanks, I agree that gh-16030 looks like the same thing. Could it be a recent regression?

Is there a specific bit of code that determines the dtype for some Python objects? I'd be interested to see if I can understand it, but I don't know where to start looking. :slightly_smiling_face:

**Comment by seberg** [comment] 2020-05-18 13:58
Its here: https://github.com/numpy/numpy/blob/2d1e8f38e973f88aeb29dc51caa0f57ab86efc67/numpy/core/src/multiarray/common.c#L39 but no, AFAIK this never changed at least since 1.7 (before that is just before my time), so there should be no regression here. I am hoping to practically rewrite that chunk of NumPy.

It does two things:
1. Find the correct dtype for each element, that is what I linked to.
2. use `np.promote_types(dtype1, dtype2)` which is in the `PyArray_PromoteTypes` function (if I did not typo that).

**Comment by takluyver** [comment] 2020-05-18 14:21
Ah, that makes sense. So it's guessing a dtype for each element, preferring int64 (longlong) over uint64 (ulonglong), and then promoting them together. Switching the preference around would just shift the problem to when you mix positive & negative integers, which would clearly be worse.

I see there's a special case for when all items in the sequence are the same type and either float, bool, or complex, with a comment saying why it doesn't currently cover integers:

https://github.com/numpy/numpy/blob/2d1e8f38e973f88aeb29dc51caa0f57ab86efc67/numpy/core/src/multiarray/common.c#L445-L452

But I guess solving the problem there would fix it only for 1D arrays, because you'd still get different dtypes if you passed in a list of lists.

**Comment by seberg** [comment] 2020-05-18 14:23
Yeah, changing code there would only lead to inconsistencies...

**Comment by takluyver** [comment] 2020-05-18 14:34
I guess one approach would be to have an internal type for non-negative int64, which could be promoted to either int64 or uint64 as needed. But that sounds like a pretty involved change.

**Comment by seberg** [comment] 2020-05-18 14:50
I did that in my new branch first, but while I now still have the "internal type", do not use it in the context of `np.array` currently (I need something like a python-integer-dtype for the value based casting of scalars).

This is an actual use-case where it would help a bit, but honestly, I think it is probably a bit too smart? And it still means that `np.array` coercion gives different results if you coerce chunks of the array first and then concatenate...

**Comment by seberg** [comment] 2020-06-25 22:27
@takluyver once my array-coercion PR is in, I think I will propose to simply deprecate coercing ints to anything other than the default integer... Mainly a bit annoying on windows (with 32bit default) in some cases, I guess.  Or we could at least deprecate any `uint` and `object` results in the promotion... I can see people using this to transparently switch to objects, but considering like integer-overflow/wrapping in the boundary region, I have difficulties seeing how these rules are not a much bigger foot-gun than helpful.

**Comment by seberg** [comment] 2022-05-12 10:06
Closing as a duplicate of the newer gh-19146 (just because its newer).

**Closed by seberg** 2022-05-12 10:06 UTC
Labels: component: numpy.dtype
