### ISSUE TITLE
Unintended behaviour numpy 1.19.2 when using numpy.random.choice with a list of large integers

### ISSUE THREAD

**Issue by mariohevia** [numpy/numpy#17722] opened 2020-11-06 09:39 UTC
When using `numpy.random.choice` to select one object from a list of large integers it sometimes transform the integer into a float losing the exact value of the integer.

**Reproducing code example:**
```import numpy as np
a =[2719731347783780899, 12101784904839573027]
result = np.random.choice(a, 1)[0]
print(type(result), result, int(result))
```
This does not match the behaviour when using larger or smaller values, for example:
```import numpy as np
b = [98639646499002920190162389576535446980143321954085953494713932, 50562095890851553294979528226801422915940222716450081597866592]
c = [12341324134, 52341341312]
result2 = np.random.choice(b, 1)[0]
print(type(result2), result2)
result3 = np.random.choice(b, 1)[0]
print(type(result3), result3)
```

Probable Cause of this behaviour:

When calling ` np.random.choice()` on a list numpy first converts it into a `numpy.array` and it decides a different `dtype` for different sizes of integers, with the same examples as above, the 

```import numpy as np
a =[2719731347783780899, 12101784904839573027]
b = [98639646499002920190162389576535446980143321954085953494713932, 50562095890851553294979528226801422915940222716450081597866592]
c = [12341324134, 52341341312]
print(np.array(a).dtype, np.array(b).dtype, np.array(c).dtype)
```
The results are `dtype('float64')`, `dtype('O')` and `dtype('int64')`. I understand that there is a limit of size on dtype('int64') but I would not expect numpy to transform integers into floats because it does not maintain the initial value, I would expect it to transform it into a python object.

**Comment by eric-wieser** [comment] 2020-11-06 10:25
`random` is a red herring here, the bug is in `np.array`:

```python
>>> np.array([2719731347783780899, 12101784904839573027])
array([2.71973135e+18, 1.21017849e+19])
```
A more minimal reproduction is
```python
>>> np.array([2**63-1, 2**64-1]).dtype
dtype('float64')
```

**Comment by seberg** [comment] 2020-11-09 17:06
Yeah, there is a whole web of these issues, but a central one should be: gh-12525.

**Comment by seberg** [comment] 2020-11-09 17:12
Ah, gh-16287 and gh-16030 are more to the point, going to close this one a duplicate of those.

**Closed by seberg** 2020-11-09 17:12 UTC
Labels: 00 - Bug, component: numpy.dtype
