### ISSUE TITLE
zeros(1) shape differs from eye(1)

### ISSUE THREAD

**Issue by homocomputeris** [numpy/numpy#7306] opened 2016-02-22 16:38 UTC
1-by-1 _eye_ and _zeros_ matrices have different shapes:
```
print(zeros(1))
print(eye(1))
```
yeilds:
```
[ 0.]
[[ 1.]]
```
So, e.g., they cannot be combined in a block matrix:
```
print(bmat([[eye(1), zeros(1)], [eye(1), zeros(1)]]))

Traceback (most recent call last):
  File "/home/user/Code/pydevtest/name.py", line 64, in <module>
    print(bmat([[eye(1), zeros(1)], [eye(1), zeros(1)]]))
  File "/usr/lib/python3.5/site-packages/numpy/matrixlib/defmatrix.py", line 1227, in bmat
    arr_rows.append(concatenate(row, axis=-1))

ValueError: all the input arrays must have same number of dimensions
```

Sysinfo:
```
print(np.version.version) 1.10.4
/usr/bin/python 3.5.1
4.4.1-2-ARCH x86_64 GNU/Linux
Eclipse IDE for C/C++ Developers	4.5.1.20150917-1200
PyDev for Eclipse	4.5.4.201601292234
```

**Comment by ewmoore** [comment] 2016-02-22 16:46
Not a bug.  `eye` is specified to return a 2D array, so it does so in every case.  `zeros` returns the shape you asked for.  So, ask for 2D if that's what you need.

**Comment by homocomputeris** [comment] 2016-02-22 17:01
Well, kinda unexpected. But what is the logic behind that, similar function having different output shape?

**Comment by njsmith** [comment] 2016-02-22 17:25
Almost everything in numpy acts like `zeros` does, because numpy is a general n-dimensional array library with no particular preference for 2d matrices. However, `eye` is an exception to this general rule, because what would it even mean to have a 1d or a 3d identity matrix?

Closing issue because there's nothing to change here ATM, and we like open issues to serve as to-do items. (We certainly wouldn't just change how either function works even if there were a good reason, because it would break lots of code.) Feel free to continue discussing here or on the numpy mailing list (the latter is probably better for general how/why questions), or to reopen of there's an actionable change you think numpy should make.

**Closed by njsmith** 2016-02-22 17:25 UTC

**Comment by homocomputeris** [comment] 2016-02-22 18:29
Thanks for the explanation.

>  what would it even mean to have a 1d or a 3d identity matrix?
If only the first dimension is specified, the output might be consistent with the rest (1D in that case), so it would be a 1 in an 1D array.
