### ISSUE TITLE
Inconsistency in np.in1d functionality for classes with object equivalence implemented

### ISSUE THREAD

**Issue by adrains** [numpy/numpy#9874] opened 2017-10-17 05:14 UTC
The behaviour of `np.in1d(sublist, superlist)` (where sublist and superlist are lists of objects) is inconsistent depending on the size of the lists, and whether the objects have class level object equivalence implemented (i.e. `__eq__`,` __ne__`, and `__cmp__`). When the objects do **not** have such equivalence implemented, the code works as expected (i.e. identical to the brute force case of `[obj_i in superlist for obj_i in sublist]`). However, when the equivalence is implemented the function only works if the lists meet the criteria `if len(ar2) < 10 * len(ar1) ** 0.145:`. If the criteria are not met (meaning it would be optimal to calculate the result using the secondary algorithm), the function fails to work as expected and sublists (or even a list compared to itself) passed to `np.in1d` return an array entirely composed of False. This is obviously not expected behaviour, as all sublists used in this example are created from a list comprehension of the superlist, and should be considered subsets of the larger list.

Example code contained within the following file, with basic class to demonstrate the issue:

<details>

<summary>

[test_class_eq.txt](https://github.com/numpy/numpy/files/1389784/test_class_eq.txt)

</summary>

```python
"""Quick script to test functionality of np.in1d.
"""
import numpy as np

class TestObject:
    def __init__(self, idn, param1, param2):
        """Constructor.
        
        Parameters
        ----------
        idn: int
            The id of the object.
            
        param1: float
            Parameter 1.
        
        param2: float
            Parameter 2.
        """
        self._idn = None
        self._param1 = None
        self._param2 = None
        
        self.idn = idn
        self.param1 = param1
        self.param2 = param2
        
    @property
    def idn(self):
        return self._idn

    @idn.setter
    def idn(self, value):
        if not value: 
            raise Exception('idn may not be empty')
        self._idn = value
        
    @property
    def param1(self):
        return self._param1

    @param1.setter
    def param1(self, value):
        if not value: 
            raise Exception('param1 may not be empty')
        self._param1 = value
        
    @property
    def param2(self):
        return self._param2

    @param2.setter
    def param2(self, value):
        if not value: 
            raise Exception('param2 may not be empty')
        self._param2 = value
    
    # Object equivalence code. Comment out to remove the inconsistency.
    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return (self.idn == other.idn) and (self.param1 == other.param1) and (
                    self.param2 == other.param2)
        return False
    
    def __ne__(self, other):
        return not self.__eq__(other)
    
    def __cmp__(self, other):
        if isinstance(other, self.__class__):
            if (self.idn == other.idn) and (self.param1 == other.param1) and (
                self.param2 == other.param2):
                return 0
        return 1

def mask_test(subset, superset):
    """
    Small function to test np.in1d functionality for sub/superset pairs that don't meet 
    the inbuilt speed cutoff requirements
    """
    ar1 = np.asarray(subset).ravel()
    ar2 = np.asarray(superset).ravel()

    mask = np.zeros(len(ar1), dtype=np.bool)
    for a in ar2:
        mask |= (ar1 == a)
    
    return mask

# Create a set of objects, create small and large subsets, and compare np.in1d results        
ids = np.arange(1, 1001)

test_objects = [TestObject(id, id/2., id/3.) for id in ids]         # All (1000)

large_subset = [tobj for tobj in test_objects if tobj.idn % 2 ==0]  # Even (500)

small_subset = [tobj for tobj in test_objects if tobj.idn < 11]     # First 10

print "\nnp.all(np.in1d(test_objects, test_objects))"
print np.all(np.in1d(test_objects, test_objects))

print "\nnp.all(np.in1d(small_subset, small_subset))"
print np.all(np.in1d(small_subset, small_subset))

print "\nnp.all(np.in1d(small_subset, test_objects))"
print np.all(np.in1d(small_subset, test_objects))

print "\nnp.all(np.in1d(large_subset, test_objects))"
print np.all(np.in1d(large_subset, test_objects))

print "\nnp.all(mask_test(test_objects, test_objects))"
print np.all(mask_test(test_objects, test_objects))

print "\nnp.all(mask_test(small_subset, test_objects))"
print np.all(mask_test(small_subset, test_objects))

print "\nnp.all(mask_test(large_subset, test_objects))"
print np.all(mask_test(large_subset, test_objects))

print "\nnp.all([tobj in test_objects for tobj in large_subset])"
print np.all([tobj in test_objects for tobj in large_subset])
```

</details>

Machine:
macOS Sierra (10.12.6)
Macbook Pro (15-inch, 2016)
numpy version 1.13.1
Anaconda, Python 2.7.13

**Comment by eric-wieser** [comment] 2017-10-18 04:36
Can you come up with a more minimal example?

**Comment by adrains** [comment] 2017-10-23 23:29
I've now stripped out most of the unnecessary code from the class itself (which now just consists of its constructor and the equality functions). I have also found that the problem seems to come from the addition of the `__cmp__` method, not class equivalence in general (i.e it works fine with just `__eq__` and `__ne__`). I note that `__cmp__` is not supported in Python 3, but I don't know whether that has any relevance to this situation.

[test_class_eq_minimal.txt](https://github.com/numpy/numpy/files/1409039/test_class_eq_minimal.txt)

**Comment by eric-wieser** [comment] 2017-10-24 04:29
Can you post the code directly in the comment in future? Files are harder to read in email / on mobile / on plaforms where the default `.txt` reader expects CRLF...

**Comment by adrains** [comment] 2017-10-24 05:12
Sorry about that, will definitely do that next time.

**Comment by eric-wieser** [comment] 2017-10-24 06:59
I think the problem is entirely due to `__cmp__`, because sorting your array gives meaningless results, since for any two elements `a != b`, `a > b and b > a`

**Comment by eric-wieser** [comment] 2017-10-24 07:26
Thanks for the report - I'm going to close this in favor of the more concise #9914

**Closed by eric-wieser** 2017-10-24 07:26 UTC
