### ISSUE TITLE
BUG: Large distances between `start` and `stop` in `np.linspace()` result in non-finite values

### ISSUE THREAD

**Issue by honno** [numpy/numpy#21585] opened 2022-05-24 09:37 UTC
### Describe the issue:

I'm guessing some internal logic causes this issue, like in #20226. Given it's such an edge case this is probably not worth fixing, just thought I'd write an issue for prosperity's sake.

### Reproduce the code example:

```python
>>> np.linspace(-9.9792015476736e+291, 1.7976931348623157e+308, 1)
RuntimeWarning: overflow encountered in double_scalars
  delta = stop - start
RuntimeWarning: invalid value encountered in multiply
  y = y * delta
array([nan])  # expected -9.9792015476736e+291
>>> np.linspace(-9.9792015476736e+291, 1.7976931348623157e+308, 5)
... same warnings ...
array([ nan, inf, inf, inf, 1.79769313e+308] )  # expected finite values in-between
```

### NumPy/Python version information:

1.23.0.dev0+1084.g5ab08cfa8 3.8.12 (default, Mar 13 2022, 19:12:08) 
[GCC 9.4.0]

**Comment by bashtage** [comment] 2022-05-24 09:48
This is a well-known limitation due to the limits of floating-point numbers. This can only be described as "by design".  The only possible solution would be to warn when linspace produces non-finite values.

**Comment by seberg** [comment] 2022-08-22 09:23
I agree with @bashtage.  Unless someone argues from a non hypothesis angle why this is particularly important, I think this is simply one of the many floating-point surprises that can happen and that we should simply not do anything about it.

**Comment by rossbar** [comment] 2022-08-22 10:10
I also agree, closing. Please feel free to reopen if there are further specific instances of users getting bit by this.

**Closed by rossbar** 2022-08-22 10:10 UTC
Labels: 00 - Bug, 57 - Close?
