### ISSUE TITLE
BUG: unexpected behavior when testing equality on numpy types

### ISSUE THREAD

**Issue by bieganski** [numpy/numpy#22810] opened 2022-12-16 10:22 UTC
### Describe the issue:

Following code does not raise any exception. It looks like something wrong with `==` operator.

### Reproduce the code example:

```python
import numpy as np
keys = {np.int8: 1}.keys()
assert not np.dtype("int8") in keys
assert     np.dtype("int8") in list(keys)
```

### NumPy/Python version information:

1.22.3 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]

**Comment by seberg** [comment] 2022-12-18 12:10
Thanks for reporting, closing as duplicate of gh-17864, although it would be nice to find an idea for improvement.  You could use the scalar types hash, but dtypes evaluate equal if `np.dtype(other)` evaluates equal.  And that is probably widely used as in `arr.dtype == "int8"`.

So to fix how dtypes hash (and thus behave w.r.t to sets/dicts) needs some good idea or maybe just limiting the `==` behavior of NumPy `dtype`'s quite drastically from what it is now.

**Closed by seberg** 2022-12-18 12:10 UTC
Labels: 00 - Bug
