### ISSUE TITLE
numpy char array initialise uses only 1st char of source string in v1.20

### ISSUE THREAD

**Issue by chrislast** [numpy/numpy#18407] opened 2021-02-13 00:21 UTC
### Reproducing code example:

```python
import numpy
numpy.array(["ab","cd"],dtype=("U1",2))
```
### Error message:
v1.20.1 loses the string data from list 
```
>>> numpy.array(["ab","cd"],dtype=("U1",2))
array([['a', 'a'],
       ['c', 'c']], dtype='<U1')
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.1 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
```
but v1.19.5 with the same python version...
```
>>> numpy.array(["ab","cd"],dtype=("U1",2))
array([['a', 'b'],
       ['c', 'd']], dtype='<U1')
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.19.5 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
```

### NumPy/Python version information:

1.20.1 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]

**Comment by seberg** [comment] 2021-02-13 01:46
May I ask how it happens that you noticed this?  I did not realize that the old behaviour was so weird here.  To proof my point consider these examples (on NumPy <=1.19):

```python
>>> import numpy as np
>>> np.dtype("(2)U1,") == np.dtype(("U1", 2))  # just to note that this is the same thing.
True
>>> np.array([(1, "ab"), (2, "cd")], dtype="i,(2)U1")  # This is what NumPy 1.20 does always!
array([(1, ['a', 'a']), (2, ['c', 'c'])],
      dtype=[('f0', '<i4'), ('f1', '<U1', (2,))])
>>> np.array("ab",dtype=("(2,2)U1,"))
array([['a', ''],
       ['', '']], dtype='<U1')
>>> np.array("ab", dtype=("U1", 2))  # or dtype="(2)U1,"
array(['a', ''], dtype='<U1')
>>> numpy.array(["ab", "cd"], dtype=("U2", 2))  # "U1" makes things look a bit clearer than it should.
array([['a', 'b'],
       ['c', 'd']], dtype='<U2')
```

I am not sure right now, it might be possible to pretend that strings are considered scalars *unless a subarray dtype was provided*, in which case they are unpacked.  I expect that would effectively revert most to 1.19.x version, but it would probably also cause some weirder cases to just error out.

**Comment by chrislast** [comment] 2021-02-13 10:03
I used it successfully in an adventofcode solution last year  https://github.com/chrislast/AoC20/blob/d462b7ff73a8895cc66f9da5aaa4065beb768336/day20.py#L96 and as it seemed intuitive - initialise a 2-D array with a 1-D list of chararray(string) I didn't question whether it *should* work.

**Comment by chrislast** [comment] 2021-02-13 10:58
If strings aren't considered as scalars then I can change to list(map(list(_stringlist_))) which makes sense too and avoids the need to coerce dtype
```
>>> numpy.array(list(map(list,["abc","def","xyz"])))
array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['x', 'y', 'z']], dtype='<U1')
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.1 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
```

**Comment by seberg** [comment] 2021-02-13 15:15
Yes, passing a list of characters is clear. Also using `np.array(..., dtype="U2").view("U1")` may also make sense.

Well, I am listed those things more for others to make a call how to handle it and as an explanation in case you are were using similar patterns elsewhere.
I agree, the original code does not _read_ surprising, even if it may be inconsistent with the how fields work everywhere else.  It is a weird regression because a historic construct that normally views strings as lists, but in this specific occasion – a subarray dtype whose shape is absorbed into the array during array creation – treats it as a sequence.  (The reason for that is probably that the code never anticipated the possibility, but that also doesn't matter.)

**Comment by mattip** [comment] 2021-02-17 11:05
The [mailing list discussion](http://numpy-discussion.10968.n7.nabble.com/What-to-do-about-structured-string-dtype-and-string-regression-td48982.html) seems to be supporting the idea of rejecting ambiguous dtype/value specifications:
> If there was a way to raise a warning or error in potentially ambiguous situations like this, I would support it.

**Comment by seberg** [comment] 2021-12-20 23:28
Closing, this is change has long sailed and was reviewed on the mailing list.

**Closed by seberg** 2021-12-20 23:28 UTC
