### ISSUE TITLE
BUG: Adding element 1D array with empty array gives empty array instead of raising an error

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [numpy/numpy#21325] opened 2022-04-11 19:22 UTC
### Describe the issue:

In the context of array API spec I observed that `np.add(np.array([0]), np.array([]))` outputs an empty array, while `np.add(np.array([1,2]), np.array([]))` raises a `ValueError` which seems questionable.

I would have expected both inputs to raise an exception.

### Reproduce the code example:

```python
import numpy as np

print(np.add(np.array([1]), np.array([])))  # outputs empty array

print(np.add(np.array([1, 2]), np.array([])))  # raises ValueError
```

### Error message:

```shell
$ python -c "import numpy as np; print(np.add(np.array([1]), np.array([]))); print(np.add(np.array([1, 2]), np.array([])))"
[]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (2,) (0,)
```

### NumPy/Python version information:

```
In [7]: (np.__version__, sys.version)

Out[7]: ('1.21.2', '3.9.7 (default, Oct 27 2021, 01:23:21) \n[GCC 9.3.0]')
```

**Comment by eric-wieser** [comment] 2022-04-11 20:34
Duplicate of #18600

**Comment by oleksandr-pavlyk** [comment] 2022-04-11 21:14
@eric-wieser I think of `np.array(1) + np.array([])` as add 1 to every element of the second argument. Formulation of `np.array([1]) + np.array([])` is just add two vectors, and special-case behavior of size 1 array is odd. 

That being said, this may be a quirk with a long history and fixing this may create more problems that it would solve.

**Comment by eric-wieser** [comment] 2022-04-11 21:55
I agree that special casing size 1 is occasionally unpleasant, but it's central to the broadcasting design in numpy (consider broadcasting a row vs column vector with a 2d array).

A more principled approach might be to use a special `None` value for the size of dimensions being broadcast (which could be introduced with `np.new_axis`), but I don't see this being either without it's own flaws, or remotely backwards compatible.

With a suitable champion pushing for this, maybe we could support this but only actually emit errors behind a flag; but I suspect there are better places to invest work

**Comment by seberg** [comment] 2022-05-12 10:23
Clsing, this is not an issue but correct behaviour.

As Eric also said, the size 1 dimension is special, not the size 0.  The problem is that we assme any size 1 dimension is a "broadcast" dimension.  And for broadcast dimensions you basically assume that the dimension is irrelevant.  Say a mean over a dimension, _lacks_ that dimension.  If you then have an array that _has_ the dimension but with 0 points, the result of 0 points is correct.

The resolution would be to be able to say that there are size 1 dimensions which in fact represent an actual datapoint in that dimension, rather than a placeholder for "can be assumed constant along that dimension".

**Closed by seberg** 2022-05-12 10:23 UTC
Labels: 00 - Bug
