### ISSUE TITLE
numpy unexpectedly raises zero division error if array is long enough

### ISSUE THREAD

**Issue by evfro** [numpy/numpy#11051] opened 2018-05-05 07:21 UTC
Steps to reproduce:

```python
with np.errstate(invalid='ignore', divide='raise'):
    for i in range(10000):
        z = np.zeros(i)
        try:
            z / z
        except(FloatingPointError) as exc:
            print(exc, 'at size', i)
            break
```

output:
`divide by zero encountered in true_divide at size 8001`

**numpy version**: `1.14.2`

Seems like this bug was introduced just recently, as there is no such issue with `1.13.3` and `1.14.1`.

**Comment by charris** [comment] 2018-05-05 14:37
I cannot reproduce this. What platform?

**Comment by mattip** [comment] 2018-05-07 06:43
What do you get when you run `import sys; print(sys.version)`, if not anaconda how did you obtain NumPy?

**Comment by Evfro** [comment] 2018-05-07 07:00
`3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0]`

**Comment by mattip** [comment] 2018-05-07 07:12
How do you get Anaconda on windows 10 compiled with GCC 7.2.0? Is that standard? I thought they use MSVC?

**Comment by Evfro** [comment] 2018-05-07 07:57
My bad, I've mixed terminals. I have double checked and I'm also not able to reproduce it on Windows.
So the problem appears only on `Ubuntu`  (at least `14.04.4 LTS` and `16.04.3 LTS`) both with
`Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux` and numpy version `1.14.2`

**Comment by Evfro** [comment] 2018-10-06 19:49
Hi! Any update on that issue? I'm getting this error also with newer versions of Python: `Python 3.7.0 (default, Jun 28 2018, 13:15:42) [GCC 7.2.0] :: Anaconda, Inc. on linux`, and Numpy: `1.15.2` on Ubuntu system.

**Comment by charris** [comment] 2018-10-06 20:13
I still cannot reproduce this, so it is hard to debug :)

**Comment by charris** [comment] 2018-10-06 20:16
Anyone out there running ubuntu who can check this?

**Comment by charris** [comment] 2018-10-06 20:20
I don't see anything suspicious between NumPy 1.14.1 and 1.14.2
```
A total of 5 pull requests were merged for this release.

* `#10674 <https://github.com/numpy/numpy/pull/10674>`__: BUG: Further back-compat fix for subclassed array repr
* `#10725 <https://github.com/numpy/numpy/pull/10725>`__: BUG: dragon4 fractional output mode adds too many trailing zeros
* `#10726 <https://github.com/numpy/numpy/pull/10726>`__: BUG: Fix f2py generated code to work on PyPy
* `#10727 <https://github.com/numpy/numpy/pull/10727>`__: BUG: Fix missing NPY_VISIBILITY_HIDDEN on npy_longdouble_to_PyLong
* `#10729 <https://github.com/numpy/numpy/pull/10729>`__: DOC: Create 1.14.2 notes and changelog.
```

**Comment by mattip** [comment] 2018-10-06 20:47
Maybe Ananconda switched compilers / mkl libraries. Please check with them.

**Comment by mattip** [comment] 2019-08-18 15:45
@evfro, @oleksandr-pavlyk can we close this?

**Comment by evfro** [comment] 2019-08-18 16:49
I've found a workaround and not using the lines of code that generate that issue.
That said, I've checked whether the issues still persists with the most recent conda/numpy/mkl environment and, unfortunately, it does.

`import sys; print(sys.version)`
3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0]

`numpy.__version__`
1.16.4

`conda list mkl`
mkl                       2019.4                      243  
mkl-service               2.0.2            py36h7b6447c_0

**Comment by oleksandr-pavlyk** [comment] 2019-08-19 14:19
Yes, it is still reproducible:

```
In [2]: z = np.zeros(8001)

In [3]: z/z
/tmp/miniconda3/bin/ipython:1: RuntimeWarning: divide by zero encountered in true_divide
  #!/tmp/miniconda3/bin/python
/tmp/miniconda3/bin/ipython:1: RuntimeWarning: invalid value encountered in true_divide
  #!/tmp/miniconda3/bin/python
Out[3]: array([nan, nan, nan, ..., nan, nan, nan])
```

It is coming from use of MKL VML function `vdDiv` used to perform division.

One can turn errors off by using `mkl.set_vml_mode`:

```
import mkl     # import mkl-service
saved = mkl.vml_set_mode(
    "ha", # accuracy control
     "off", # denormalized numbers handling
     "ignore" # error mode control
)
```

See https://software.intel.com/en-us/mkl-developer-reference-c-vmlsetmode for more details

You can restore the VML behavior with 

```
mkl.vml_set_mode(*saved)
```

**Comment by mattip** [comment] 2019-08-20 05:57
NumPy specifically resets the error state when it is obvious (by emitting NAN) that divide-by-zero occurred. I think the MKL port should do the same inside the ufuncs without requiring global error mode control.

**Comment by mattip** [comment] 2020-12-02 21:22
Closing, as it seems this is a "won't fix" from the mkl port of NumPy. Please reopen if there is something actionable NumPy can do.

**Closed by mattip** 2020-12-02 21:22 UTC
Labels: 00 - Bug, 29 - Intel/Anaconda, component: numpy.ufunc

**Comment by astroboylrx** [comment] 2021-11-01 21:44
> It is coming from use of MKL VML function `vdDiv` used to perform division.

Thanks a lot for explaining that. It's so hard to find relevant information since too many webpages are about real zero-division cases. 

I ran into this issue as well and it only occurs with `numpy` with MKL. I tried to turn errors off with your code snippet and it 
does removed half of such errors. 
@oleksandr-pavlyk @phil-blain I wonder what might be responsible for the other half "divide by zero encountered in true_divide" errors? Any thoughts or suggestions would be greatly appreciated!

**Comment by oleksandr-pavlyk** [comment] 2021-11-02 00:35
Nowadays implementations of universal functions that use MKL VML has all been moved to `mkl_umath` [package](https://github.com/IntelPython/mkl_umath). 

The ufunc loops for certain types are registered with NumPy's universal functions via `PyUFunc_RegisterLoopForType`. 

One can deregister these loops using `mkl_umath.restore()`.
