### ISSUE TITLE
`str` type in recarray `dtype` loses data (infers `'<U'`)

### ISSUE THREAD

**Issue by narfanar** [numpy/numpy#12725] opened 2019-01-13 15:28 UTC
### Reproducing code example:

```python
import numpy as np
x = np.rec.array([('abcd',)], dtype=[('a', str)])
print(repr(x))
```

### Erroneous Behavior:
`str` type is inferred as `<U` dtype.

A similar expression using numpy arrays infers the length for `'<UN'` dtype.

### Numpy/Python version information:

```
1.15.4 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
```

**Comment by eric-wieser** [comment] 2019-01-13 19:53
Duplicate of #8969

**Closed by eric-wieser** 2019-01-13 19:53 UTC
