### ISSUE TITLE
BUG: typing doesn't handle type aliases via Python types

### ISSUE THREAD

**Issue by bmerry** [numpy/numpy#21900] opened 2022-07-01 13:40 UTC
### Describe the issue:

numpy 1.20 [encouraged](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) specifying plain `bool` as a dtype as an equivalent to `np.bool_`, but these aliases don't behave the same as the explicit numpy versions. mypy infers the dtype as "Any" instead. See the example below, where I expected both lines to output the same type.

### Reproduce the code example:

```python
import numpy as np

def what_the() -> None:
    reveal_type(np.arange(10, dtype=bool))
    reveal_type(np.arange(10, dtype=np.bool_))
```

### Error message:

```shell
No error, but output from mypy 0.961:

show_type2.py:4: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[Any]]"
show_type2.py:5: note: Revealed type is "numpy.ndarray[Any, numpy.dtype[numpy.bool_]]"
```
```


### NumPy/Python version information:

1.23.0 3.10.5 (main, Jun 11 2022, 16:53:24) [GCC 9.4.0]

**Comment by bibhabasumohapatra** [comment] 2022-07-02 05:25
```
numpy.__version__ =  '1.23.0'
python version = Python 3.9.12
```

![image](https://user-images.githubusercontent.com/68384968/176986914-3f9e0a0b-d4bc-42f8-8fb5-75831286691a.png)

I tried to do this but got the expected result

but reproducing the results: I could not do that . . . 

![image](https://user-images.githubusercontent.com/68384968/176987062-7140a874-e1d7-4c6e-99f5-d0ad771060ec.png)

But I tried : `np.arange(10, dtype=int) `and `np.arange(10, dtype=float)  `  which mapped to np.int and np.float64  fine.

**Comment by bmerry** [comment] 2022-07-02 06:48
@bibhabasumohapatra you're looking at the runtime type. This bug is about static typing.

**Comment by bibhabasumohapatra** [comment] 2022-07-02 12:02
> @bibhabasumohapatra you're looking at the runtime type. This bug is about static typing.

Yes,  looks like mypy issue.  Should check the  source more.

**Comment by bmerry** [comment] 2022-07-03 13:46
In #21898, @BvB93 suggested that this might duplicate a known issue in #19252.

**Comment by BvB93** [comment] 2022-07-06 09:14
As was noted by @bmerry, this is a duplicate of https://github.com/numpy/numpy/issues/19252 and I’d suggest keep this discussion contained to that issue.

But to summarise: it’s non-trivial to map `builtins` types to their `np.generic` counterpart with the currently available typing tools, hence why the former will more often than not resolve to a `Any`-based data type.

**Closed by BvB93** 2022-07-06 09:14 UTC
Labels: 00 - Bug, Static typing
