### ISSUE TITLE
Unstable behaviour with augmented division

### ISSUE THREAD

**Issue by idofr** [numpy/numpy#6292] opened 2015-09-08 17:16 UTC
I'm loading a numpy array using scipy.misc.imread(path) and then try to normalise it.
If I use img = img / 255.0, I get the expected behaviour, but if I use img /= 255.0 it does what seems to be an int division and I get a lot of zeros.

**Comment by DavidMertz** [comment] 2015-09-08 18:03
As far as I understand it, this is exactly the expected and correct behavior.  `np.array.__iadd__()` and `np.array.__add__()` have different behaviors by design.  The in-place operation makes sense to preserve the type of the original array (i.e. keep it as an int, hence truncate to 0), while the binary operation obeys promotion rules.  

This has an intuitive semantic meaning of "create a new array of the necessary type" versus "mutate the current array".  The current array **has** a .dtype that cannot be changed, only a new object can have a different dtype.

**Comment by idofr** [comment] 2015-09-08 18:56
Thanks for the response.
I understand what you mean and why it could also make sense, yet I don't really think anyone would expect a difference between the two and all of my work-mates have also found this very strange.
When dividing by a float, you always expect a float as a result and even though your explanation is a very reasonable one, I find it hard to accept it.

**Comment by DavidMertz** [comment] 2015-09-08 19:43
I'm certain that a great deal of existing code relies on this documented behavior.  Even if it is surprising to you, I don't believe that changing it in a backward incompatible way is appropriate.  Consider other examples besides division to see why the existing behavior is desirable.

```python
myints = np.arange(10, dtype=int16)
myints += 10.0
```

I think it would be enormously surprising to most users to find that `myints` had suddenly become dtype 'float64' or whatever after that operation.  Moreover, later lines quite likely *depend* upon `myints` being an array of int16.

Having in-place division follow different typing rules from in-place addition, in-place multiplication, in-place modulo, etc. would be extremely surprising.

**Comment by njsmith** [comment] 2015-09-08 20:44
Yeah, numpy just fundamentally can't do what you were expecting, because an array cannot change type. Changing type would require allocating a whole new array in memory.

This is a good thing, in general, because it's part of how numpy gives you control over how your code runs. If you have a 10 gigabyte array in memory, and use an in-place operation like /= on it, then it will never silently allocate a second array -- it will either do the operation in place or fail. Sometimes this is very important :-). This explicit control over array allocations is also important for making it possible to provide features like views.

Note though that in this particular case with int /= float, then instead of getting a silently truncated result, a future version of numpy will give an error. There should already be a warning being emitted, but either you have an old version of numpy or do not have deprecation warnings enabled. (Try running python with -Wdefault.)

**Comment by dadkins** [comment] 2015-09-11 22:52
FWIW, this behavior is departs from the Python 3 position on division, which is that '/' should perform non-truncating division, while '//' is available if you explicitly want that. On ordinary integers, Python happily changes types on /=:

In [20]: a=5

In [21]: type(a)
Out[21]: int

In [22]: a /= 3

In [23]: a
Out[23]: 1.6666666666666667

In [24]: type(a)
Out[24]: float

I'm sympathetic to the "no unexpected allocation" argument here, but that would mean the /= is just not supported on integer numpy arrays, and you would have to ask for //= if that's actually what you meant.

**Comment by njsmith** [comment] 2015-09-11 23:05
> but that would mean the /= is just not supported on integer numpy arrays, and you would have to ask for //= if that's actually what you meant.

Yep, exactly.

I don't think there's anything for us to do here, so closing -- if I'm wrong then please reopen :-)

**Closed by njsmith** 2015-09-11 23:05 UTC
