### ISSUE TITLE
Numpy 1.14.4 does not install on Alpine

### ISSUE THREAD

**Issue by mrfuxi** [numpy/numpy#11279] opened 2018-06-08 07:31 UTC
I tried to install recent NumPy (1.14.4), forced by SciPy :(
It works in local env but not in Docker running Alpine.

Minimal Docker file that reproduces the problem:

```
FROM python:3.6.5-alpine
RUN apk add --no-cache build-base
RUN pip install numpy==1.14.4
```

By using 1.14.3 it all works.

**Comment by shoyer** [comment] 2018-06-08 07:36
What error message do you see?

**Comment by mrfuxi** [comment] 2018-06-08 07:54
Log from the installation: [alpine.1.14.4.log](https://github.com/numpy/numpy/files/2083442/alpine.1.14.4.log)

**Comment by mattip** [comment] 2018-06-08 08:28
Duplicate of #11274, fixed on HEAD

**Comment by mrfuxi** [comment] 2018-06-08 08:35
awesome, thank you. Can't wait for the release

**Closed** 2018-06-08 08:36 UTC
