### ISSUE TITLE
np.clip slower in numpy 1.17

### ISSUE THREAD

**Issue by fmaussion** [numpy/numpy#14281] opened 2019-08-15 10:22 UTC
We've seen a dramatic (about 25%) performance loss in our numerical model tests when switching from numpy 1.16.4 to 1.17.

The code is quite standard numerics on small, but numerous arrays at frequent time steps. After profiling, it turned out that the *number of calls* and the *cumtime* spent on `np.clip` increased drastically.

Microbenchmarks on `np.clip` did not show any significant change until I found this one:

```python
In [1]: import numpy as np
In [2]: np.__version__
Out[2]: '1.16.4'
In [3]: %timeit np.clip(10, 0, None)
2.99 µs ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

To be compared to:

```python
In [1]: import numpy as np                                                      

In [2]: np.__version__                                                          
Out[2]: '1.17.0'

In [3]: %timeit np.clip(10, 0, None)                                            
15.1 µs ± 117 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

So, about 5 times slower.

I made a simple test and profiled it:

```python
def test_clip():
    for i in range(1000000):
        np.clip(1, 0, None)
```

And here are the profiler outputs (trimmed to show only numpy outputs:

**numpy 1.16.4**

```
Thu Aug 15 11:14:12 2019    prof_16/prof/test_clip.prof

         8002900 function calls (8002830 primitive calls) in 4.223 seconds

   Ordered by: cumulative time
   List reduced from 382 to 6 due to restriction <'numpy'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  1000000    0.352    0.000    3.949    0.000 (...)/numpy/core/fromnumeric.py:1903(clip)
  1000000    0.770    0.000    3.597    0.000 (...)/numpy/core/fromnumeric.py:54(_wrapfunc)
  1000000    0.903    0.000    2.565    0.000 (...)/numpy/core/fromnumeric.py:41(_wrapit)
  1000000    0.305    0.000    0.873    0.000 (...)/numpy/core/numeric.py:469(asarray)
  1000000    0.704    0.000    0.704    0.000 {method 'clip' of 'numpy.ndarray' objects}
  1000000    0.568    0.000    0.568    0.000 {built-in method numpy.array}
```

**numpy 1.17**

```
Thu Aug 15 11:15:39 2019    prof_17/prof/test_clip.prof

         35003584 function calls (33003457 primitive calls) in 21.119 seconds

   Ordered by: cumulative time
   List reduced from 448 to 14 due to restriction <'numpy'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
3000000/1000000    0.928    0.000   19.951    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
  1000000    0.565    0.000   19.577    0.000 (...)/numpy/core/fromnumeric.py:1974(clip)
  1000000    0.620    0.000   19.011    0.000 (...)/numpy/core/fromnumeric.py:55(_wrapfunc)
  1000000    1.134    0.000   18.039    0.000 (...)/numpy/core/fromnumeric.py:42(_wrapit)
  1000000    0.431    0.000   15.865    0.000 {method 'clip' of 'numpy.ndarray' objects}
  1000000    1.445    0.000   15.434    0.000 (...)/numpy/core/_methods.py:97(_clip)
  2000000    4.990    0.000   11.738    0.000 (...)/numpy/core/_methods.py:63(_clip_dep_is_scalar_nan)
  2000000    1.603    0.000    3.749    0.000 (...)/numpy/core/fromnumeric.py:2986(ndim)
  3000000    0.945    0.000    3.076    0.000 (...)/numpy/core/_asarray.py:16(asarray)
  3000000    2.130    0.000    2.130    0.000 {built-in method numpy.array}
  1000000    1.434    0.000    1.434    0.000 (...)/numpy/core/_methods.py:78(_clip_dep_invoke_with_casting)
  2000000    0.597    0.000    0.816    0.000 (...)/numpy/core/_methods.py:73(_clip_dep_is_byte_swapped)
  2000000    0.186    0.000    0.186    0.000 (...)/numpy/core/fromnumeric.py:2982(_ndim_dispatcher)
  1000000    0.122    0.000    0.122    0.000 (...)/numpy/core/fromnumeric.py:1970(_clip_dispatcher)
```
These are very different!

**Comment by charris** [comment] 2019-08-15 13:35
Maybe #12519 which changed to use a ufunc for clip. Why did "number of calls" increase I wonder? @eric-wieser Thoughts?

**Comment by fmaussion** [comment] 2019-08-15 13:58
OK, so based on #12519 a simple workaround for us would be to avoid `clip` altogether and rely on `core.umath.clip`.

**Comment by eric-wieser** [comment] 2019-08-15 15:55
I think this is the cost of deprecati be there casting weirdness

**Comment by eric-wieser** [comment] 2019-08-15 16:04
Does the 1.17 version emit any deprecation warnings?

**Comment by fmaussion** [comment] 2019-08-15 16:05
> Does the 1.17 version emit any deprecation warnings?

No, why would it? `np.clip(1, 0, None)` is still valid syntax right?

**Comment by fmaussion** [comment] 2019-08-27 12:05
@eric-wieser sorry for the rude ping on this issue: I just want to make sure it doesn't get lost, as I believe it might affect quite a few numerical models around here.

**Comment by fmaussion** [comment] 2019-11-11 14:42
A short wrapping up if anyone stumbles into this: 
- `np.clip` is about 5 times slower in v1.17 than v1.16
- **on scalars**, the pure python version (`return vmin if value < vmin else vmax if value > vmax else value`) is faster than numpy in all cases: 30 times faster with  v1.16 and 150 times faster with v1.17
- **on arrays** and with numpy v1.16, `np.clip` is faster than the equivalent `np.core.umath.maximum(np.core.umath.minimum(value, vmax), vmin`  as advertised by the docs (about 1.5 times faster in the microbenchmark below). **In numpy v1.17, this is not true because of the issues discussed above**

So, the workarounds if you are using np.clip in numerical code are to:
- not use clip
- use the pure python version for scalars
- call `np.core.umath.maximum` and `np.core.umath.minimum` if you don't need to clip between two values (this is always faster regardless of the numpy version)
- if you need to clip an array between two values, use `np.core.umath.maximum(np.core.umath.minimum(value, vmax), vmin` with numpy>1.17 and `np.clip` for versions <1.16, or wait for a fix in numpy.

I didn't check if conditional indexing is faster, but I would be surprised if it is?

Here is the benchmark code:

```python
import numpy as np
def clip_scalar(value, vmin, vmax):
    return vmin if value < vmin else vmax if value > vmax else value
def clip_array(value, vmin, vmax):
    return np.core.umath.maximum(np.core.umath.minimum(value, vmax), vmin)
clip_min = np.core.umath.maximum
clip_max = np.core.umath.minimum

np.__version__
s = 1
a = np.arange(100)
%timeit np.clip(s, 0, 10)
%timeit clip_scalar(s, 0, 10)
%timeit np.clip(a, 0, 10)
%timeit clip_array(a, 0, 10)
%timeit clip_min(a, 10)
%timeit clip_max(a, 10)
```
And applied with two numpy versions:

**numpy 1.16.5**
```
3.41 µs ± 22.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
99.2 ns ± 0.0948 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
1.27 µs ± 2.58 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.87 µs ± 8.72 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
753 ns ± 5.52 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
759 ns ± 4.68 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**numpy 1.17.4**
```
15.3 µs ± 165 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
95.5 ns ± 1.29 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
13.8 µs ± 604 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.57 µs ± 39.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
646 ns ± 19.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
659 ns ± 13 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by eric-wieser** [comment] 2019-11-11 15:17
How does `np.core.umath.clip` compare to those benchmarks?

**Comment by eric-wieser** [comment] 2019-11-11 15:20
My guess is that this code is what's slowing it down:

https://github.com/numpy/numpy/blob/c592bf2210567ea58bc52f8e15a5f0de582f889b/numpy/core/_methods.py#L104-L111

**Comment by fmaussion** [comment] 2019-11-11 15:25
> How does np.core.umath.clip compare to those benchmarks?

`np.core.umath.clip` is not available in `1.16`, but in `1.17` it is as fast as you would expect from "the old" `np.clip`, i.e. faster than `np.core.umath.maximum(np.core.umath.minimum(value, vmax), vmin)` and *much* faster than `np.clip` in `1.17`

**Comment by fmaussion** [comment] 2019-11-11 15:29
> The other possible cause is the high indirectio

would this be the reason for the 3 times increase in  "number of calls" in the profile above?

**Comment by eric-wieser** [comment] 2019-11-11 15:38
No, that's caused by the other three calls that I missed, `clip` (wrapper) -> `clip` (`__array_function__` dispatcher`) -> `clip` (original function)`, I think. They all have the same name, which I think confuses the profiler.

**Comment by carlosgmartin** [comment] 2019-12-09 01:03
I'm also finding that `clip` is taking a surprisingly long portion of the execution time of my program.

**Comment by fmaussion** [comment] 2019-12-09 08:32
@carlosgmartin see my proposed workarounds above in the meantime. changing `np.clip` to `np.core.umath.clip` is the simplest, but the others are helping as well.

**Comment by vsriram11** [comment] 2020-01-21 07:12
I just want to add that similar to this, I have issues with np.dot in 1.17... np.core.umath.dot is significantly faster. I suggest documenting this somewhere for users.

**Comment by fmaussion** [comment] 2020-06-21 17:44
@eric-wieser do you think it's worth mentioning in the docs that `np.clip` has become significantly slower since `1.17`? I expect that many are unaware of the issue (as mentioned by others above) and this might significantly slow down their program.

I'm happy to do the PR to add a mention to the doc if you think this is useful.

**Comment by igozali** [comment] 2020-07-24 02:37
Encountered this issue as well, and wanted to ask if this is related to the [NUMPY_EXPERIMENTAL_ARRAY_FUNCTION](https://numpy.org/neps/nep-0018-array-function-protocol.html)? Would this mean that all other functions that are using this feature would consequently have degraded performance?

**Comment by leimao** [comment] 2021-10-08 23:46
Has this problem been fixed with the MRs mentioned above?

**Comment by peendebak** [comment] 2022-08-18 13:44
> My guess is that this code is what's slowing it down:
> 
> https://github.com/numpy/numpy/blob/c592bf2210567ea58bc52f8e15a5f0de582f889b/numpy/core/_methods.py#L101-L111
> 
> The other possible cause is the high indirection: `np.clip` → `ndarray.clip` → `_methods._clip` → `_clip_dep_invoke_with_casting` → `np.core.umath.clip`.

@eric-wieser The deprecation check for NaN is slowing down our code. The suggestion in this thread to use `np.core.umath.clip` works fine.

Nevertheless, would it be a good timing to either remove the deprecated path, or make the warning more verbose (on my system `np.clip(0, np.NaN, 2)` does not show a warning in the console) so we can remove it a bit later?

**Comment by kcharlie2** [comment] 2022-12-22 20:56
At least the documentation should be fixed to reflect the current state of np.clip.

From the latest `np.clip` documentation:  `Equivalent to but faster than np.minimum(a_max, np.maximum(a, a_min)).`

But in fact it's much slower. I didn't see much of a speed improvement using the minimum/maximum in `np.core.umath` over the simple `np.minimum`/`np.maximum`.

**Comment by charris** [comment] 2022-12-22 21:28
@kcharlie2 What NumPy version is that?

**Comment by kcharlie2** [comment] 2022-12-22 23:18
> @kcharlie2 What NumPy version is that?

The latest I have access to is 1.24.0.

```
>>> x = np.array([0, 0, 1, 1, 2, 2, 3, 3])
>>> timeit.timeit('np.clip(x, 1, 2)', number=10000) 
0.1463885570410639
>>> timeit.timeit('np.minimum(2, np.maximum(x, 1))', number=10000) 
0.026599229080602527
```

**Comment by seberg** [comment] 2023-04-25 11:24
This was practically all due to the nan deprecation which is gone now, so closing.  (yeah, might still be a tiny bit slower in some corner cases, but an irrelevant amount.

**Closed by seberg** 2023-04-25 11:24 UTC

**Comment by aallahyar** [comment] 2024-02-12 09:31
I confirm that the issue is (largely) resolved now, according to the tests below:

```python
# done in IPython
>>> np.__version__
'1.26.1'

>>> arr = np.arange(21).reshape(-1, 3) - 10
>>> s = np.std(arr, axis=0)

>>> %timeit np.clip(arr, -s, s)
1.67 µs ± 5.14 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

>>> %timeit np.minimum(s, np.maximum(arr, -s))
1.69 µs ± 8.27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

>>> %timeit np.core.umath.clip(arr, -s, s)
1.16 µs ± 7.69 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
