### ISSUE TITLE
numpy.sign behaves oddly when dtype is numpy.object

### ISSUE THREAD

**Issue by atomicpirate** [numpy/numpy#6229] opened 2015-08-21 14:26 UTC
In [1]: import numpy

In [2]: foo = numpy.array([-.1, 0, .1])

In [3]: numpy.sign(foo)
Out[3]: array([-1.,  0.,  1.])

In [4]: numpy.sign(foo.astype(numpy.object))
Out[4]: array([1, -1, -1], dtype=object)

The underlying data is still just a float:
In [5]: type(foo.astype(numpy.object)[0])
Out[5]: float

This result when using an array of numpy.object does not seem desirable. Either it should operate correctly on the underlying numbers or if called with invalid data (strings, etc) it should throw an exception. This way I could populate an array with heterogeneous data, say a mix of integers and floats, and still get a valid result.

I tested this on:
Mac OS 10.6.8
Python 3.4.2
numpy 1.9.2

**Comment by ewmoore** [comment] 2015-08-21 14:41
Looks like [`OBJECT_sign`](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/loops.c.src#L2619) is missing the logic to return `0` for `0`.  Compare with [BYTE_sign](https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/loops.c.src#L1028).

**Comment by atomicpirate** [comment] 2015-08-21 14:51
Right--zero didn't get a zero result, negative results in +1, positive results in -1. The results for numpy.object seem incorrect on all counts.

**Comment by pv** [comment] 2015-08-21 14:57
I can't reproduce your example.  get:
.
In [7]: numpy.sign(foo.astype(numpy.object))
array([-1, 0, 1], dtype=object)

**Comment by pv** [comment] 2015-08-21 15:01
Ah ok, the incorrect results occur on Python 3 only.

**Comment by pv** [comment] 2015-08-21 15:14
Hah, it's a stupid bug, the `== 0` should be `== 1` here https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/npy_3kcompat.h#L328

**Comment by jaimefrio** [comment] 2015-08-21 16:40
There, and it the two other checks below it, right?

**Comment by pv** [comment] 2015-08-21 17:00
Yes

**Comment by springcoil** [comment] 2015-08-26 08:00
Is this still open - it looks like an easy fix could be done.

**Comment by charris** [comment] 2016-02-20 19:01
Closed by #6269.

**Closed by charris** 2016-02-20 19:01 UTC
Labels: 11 - Bug, component: numpy.core, Easy Fix
