### ISSUE TITLE
Math no longer renders in indexing documentation

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12194] opened 2018-10-17 03:31 UTC
Compare these [1.15 docs](https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.indexing.html) with these [1.13 docs](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html)

**Comment by mattip** [comment] 2018-10-17 04:55
Do you mean the latex rendering? This is specific to the scipy.org website and maybe due to a missing latex package on the machine that builds those pages. On our website [that page](http://www.numpy.org/devdocs/reference/arrays.indexing.html) renders latex as equations. Note also PR #11006 which fixed this for our pages. 

@rgommers?

**Comment by rgommers** [comment] 2018-10-20 05:13
Indeed a duplicate of gh-11753, so let's continue the discussion there if needed.

Note that [1.15.1](https://docs.scipy.org/doc/numpy-1.15.1/reference/arrays.indexing.html) docs for that page are fine again. So it looks like 1.15.0 was uploaded with an `imgmath` issue.

**Closed by rgommers** 2018-10-20 05:13 UTC
Labels: 00 - Bug, component: Documentation
