### ISSUE TITLE
np.arange: the initial and the ending value are different form the ones provided as argument

### ISSUE THREAD

**Issue by Samrangi** [numpy/numpy#10631] opened 2018-02-20 03:28 UTC
<img width="337" alt="py1" src="https://user-images.githubusercontent.com/9477742/36406284-b8e3922c-15c3-11e8-952d-5a67a5c08146.PNG">
<img width="248" alt="py3" src="https://user-images.githubusercontent.com/9477742/36406286-bb97ce3e-15c3-11e8-98b0-cddfd0bb889e.PNG">

When creating an array from 0.2 to 0.8, the maximum value in the array is 0.8, but when I run max of the whole array,  I found the maximum value different from 0.8. It has digits in the 15th and 16th decimal.
When the same is done with 0.7 as the ending value, the maximum of the array is 0.60000000009.. and the value of 0.7 is not included in the array.

PFA the screenshots.

**Comment by crayxt** [comment] 2018-02-20 06:24
Something to learn about floating point numbers (https://stackoverflow.com/questions/21895756/why-are-floating-point-numbers-inaccurate)
Check the np.arange documentation (https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) it has reference for cases like this one

> When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use linspace for these cases.

**Comment by eric-wieser** [comment] 2018-02-20 09:44
Duplicate of #9694.

**Closed by eric-wieser** 2018-02-20 09:44 UTC
Labels: 57 - Close?

**Comment by Samrangi** [comment] 2018-02-20 13:58
Thank You for the explanation. However, I was thinking, where do we use np.arange then?
