### ISSUE TITLE
numpy.random.______ 'size' parameter should be named 'shape'

### ISSUE THREAD

**Issue by capybaralet** [numpy/numpy#7387] opened 2016-03-07 21:44 UTC
Numpy's random number generators have a "size" parameter that should be called shape (since it is in fact the shape of the output).

e.g.
http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.random.standard_normal.html

It might be difficult to change at this point, but it would be nice if it were possible.

**Comment by njsmith** [comment] 2016-03-07 22:16
I think we have several open issues for this... I tend to agree with the idea (when a general principle like the meaning of `shape` in numpy in general conflicts with a local principle like the meaning of `shape` in numpy.random, the general principle should win -- more people know it, plus if you're going to be confusing no matter what then you might as well be confusing and consistent instead of confusing and inconsistent).

But the problem is that a number of distributions already have a `shape` argument that means something else (e.g. gamma). What would you propose to do with them?

**Comment by mattip** [comment] 2019-06-06 05:51
Closing, I think the ship has sailed on this and we will be unable to change the kwarg, even for the new API. Please reopen with concrete suggestions on how to make the transition if you disagree.

**Closed by mattip** 2019-06-06 05:51 UTC
Labels: component: numpy.random
