### ISSUE TITLE
fromfile/tofile on subprocess pipe broken in Python 3

### ISSUE THREAD

**Issue by kalvdans** [numpy/numpy#5208] opened 2014-10-20 08:50 UTC
Piping a numpy array as binary data to another process works in Python2, but in Python3 the following snippet results in "OSError: first argument must be a string or open file". I tested with Python 3.4.0.

```
import subprocess, numpy
wc = subprocess.Popen(["wc"], stdin=subprocess.PIPE)
numpy.eye(5).tofile(wc.stdin)
```

**Comment by LinusU** [comment] 2016-01-11 10:30
Hitting this problem as well, worked around it by dropping `tofile` and `fromfile` in the entire codebase. The following workaround works good enough...

```python
wc.stdin.write(numpy.eye(5).tobytes())
```

**Comment by SamyCookie** [comment] 2018-04-26 09:37
#6158 and #7380 seems to be duplicated

**Comment by mattip** [comment] 2019-01-21 18:55
Cannot duplicate, even when going back to numpy 1.9 on linux with python 3.6. Might be a python 3.4 problem? Closing since there is only partial information. Please reopen with a new reproducer, specifying numpy version and OS if it still exists.

**Comment by mattip** [comment] 2019-01-21 18:59
Closing as a duplicate of #7380 which is more explicit.

**Closed by mattip** 2019-01-21 18:59 UTC
Labels: 00 - Bug, component: numpy.core
