### ISSUE TITLE
np.linalg.inv() returning odd result on ppc64le compared to x86.

### ISSUE THREAD

**Issue by wdirons** [numpy/numpy#11445] opened 2018-06-28 19:49 UTC
This problem originated from a testcase in tensorflow. They create a "lower triangular" numpy array and run np.linalg.inv(x) on the array. For x86, the zeros remain a zeros, on ppc64le the results shown below are non-zero and I'm really not sure where those values are coming from.

This is with the latest version of numpy 1.14.5. (I'll start trying other versions) 

Recreatable testcase:

```
docker run -idt --name $USER-temp ubuntu:18.04 bash
docker attach $USER-temp

apt update
apt install vim python python-pip
pip install numpy
vi test.py
python test.py

where test.py is:

import numpy as np
if __name__ == "__main__":
    x_ = np.array([[[[1., 0.],
                     [2., 3.]]],
                   [[[4., 0.],
                     [5., -6.]]]], dtype=np.float32)
    print(x_)
    x_inv_ = np.linalg.inv(x_)
    print(x_inv_)



x86:

root@08d7b342534c:/# python test.py
[[[[ 1.  0.]
   [ 2.  3.]]]


 [[[ 4.  0.]
   [ 5. -6.]]]]
[[[[ 1.          0.        ]
   [-0.6666667   0.33333334]]]


 [[[ 0.25        0.        ]
   [ 0.20833333 -0.16666667]]]]




ppc64le: 

root@68c0b6023e55:/# python test.py
[[[[ 1.  0.]
   [ 2.  3.]]]


 [[[ 4.  0.]
   [ 5. -6.]]]]
[[[[ 1.0000000e+00  2.7755576e-17]
   [-6.6666669e-01  3.3333334e-01]]]


 [[[ 2.5000000e-01  1.1102230e-17]
   [ 2.0833333e-01 -1.6666667e-01]]]]
root@68c0b6023e55:/#
```

**Comment by wdirons** [comment] 2018-06-29 13:52
Thank you @jvdillon , I'll submit a PR to tensorflow and see if they are willing to accept it.

**Comment by seberg** [comment] 2023-01-02 21:09
I can reproduce the numerical accuracy, but it seems to me that this is just expected numerical inaccuracy, and the issue is many years old, so closing.  The values are 0 within numerical precision after all.

**Closed by seberg** 2023-01-02 21:09 UTC
