### ISSUE TITLE
Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

### ISSUE THREAD

**Issue by kalsep** [numpy/numpy#19873] opened 2021-09-14 09:25 UTC
Getting this error, When initiating the pair plot with the iris datasets.

**Comment by rkern** [comment] 2021-09-14 12:37
I'm guessing you did something like `dtype=np.float64.dtype`. Just do `dtype=np.float64`.

If that wasn't the cause of this error message, we will need to see the precise code that is showing this error message.

**Comment by seberg** [comment] 2021-09-14 15:20
@kalsep it would be good to give more details about what you were doing (ideally, a brief chunk of code that runs into the error).

There is one other possibility:  There was an issue in pandas which was silent before NumPy 1.20 was released.  If you are using a newer NumPy version with an older pandas version, you may have to upgrade your pandas.

Right now, I will close the issue.  But please do post a followup with details if you require more help or think there is a deeper issue.  We can reopen the issue.

**Closed by seberg** 2021-09-14 15:20 UTC

**Comment by kalsep** [comment] 2021-09-14 15:34
it encountered this error with a simple code as
`sns.pairplot(df)`

**Comment by seberg** [comment] 2021-09-14 16:01
@kalsep yes, as I said: Almost certainly, you have to update pandas.  That is somewhat annoying, but pandas uses NumPy so if NumPy slowly changes over time at some point an old pandas version may stop working with a much newer NumPy (what happened here).

As a general note, about why we ask for as much as information as possible:  Even `sns.pairplot(df)` is not very clear.  Ideally, we can just copy paste something to "reproduce" the issue (i.e. a complete short program!).  Try to provide all the information you have, even if it seems unimportant.

In this case I can guess that `sns` is seaborn (or so?) and `df` probably is "dataframe" so I know that you are using pandas.  But those are just guesses and I still don't know what is inside `df` (I would have to search for what iris dataset example you may be referring too).
Also, the error output you see will have included a Traceback/more output than just the error you pasted.  This is vital information both for you and us:  In this case, it will point into the pandas internals making the real issue (incompatible pandas and NumPy versions) much easier to see!
