### ISSUE TITLE
pip install mixes 1.16 and previous versions of numpy

### ISSUE THREAD

**Issue by legalTech-Kenya** [numpy/numpy#12826] opened 2019-01-22 17:59 UTC
Hello. I'm new to python but i'm a fast study. Kindly bear with me. I'm trying to create an executable involving pdfminer.six. One of the requirements was genism which requires scipy and numpy. I installed the later two then installed gensim. Build finished successfully however when i tried to run my program, i got this error message
![capture](https://user-images.githubusercontent.com/45507531/51555498-c752f900-1e88-11e9-9406-a2645711b9ef.PNG)

I then followed the instructions from https://github.com/pyinstaller/pyinstaller/pull/3985/commits/bf7877fc151dd1560469d508d303d3431393a483 but when i run the program again, i got this
![2](https://user-images.githubusercontent.com/45507531/51555647-20bb2800-1e89-11e9-81a9-5763b58c03ab.PNG)

What could i be doing wrong? I'm running python 3.6.5, windows 10 64 bit....

**Comment by eric-wieser** [comment] 2019-01-22 18:32
Your multiarray module is from a different version of numpy than your Python source.

**Comment by hahnec** [comment] 2019-01-28 14:09
There seems to be a problem with the current numpy release (1.16.0). Downgrading numpy via

`python -m pip install numpy==1.15.0`

solved it for me.

**Comment by mattip** [comment] 2019-01-28 14:52
Duplicate of #12736. You should uninstall `pip uninstall numpy` over and over until pip raises an error, then install.

**Comment by rgommers** [comment] 2019-02-16 22:13
duplicate, closing

**Closed by rgommers** 2019-02-16 22:13 UTC
