### ISSUE TITLE
np.load("a.npz") very slow when a.npz file very large

### ISSUE THREAD

**Issue by niuliling123** [numpy/numpy#26499] opened 2024-05-22 08:32 UTC
### Describe the issue:

np.load("a.npz") very slow when a.npz file very large

### Reproduce the code example:

```python
`import numpy as np
import time
x1 = np.arange(250000000, dtype=np.uint8)
x2 = np.arange(250000000, dtype=np.uint8)
x={"x1":x1,"x2":x2}
np.savez('/tmp/test.npz', row=x)
time0=time.time()
xx = np.load("/tmp/test.npz", allow_pickle=True)['row']
print(time.time()-time0)`
```
better way:

```python
def load_from_npz(path, name):
    zf = zipfile.ZipFile(path)
    info = zf.NameToInfo[name + '.npy']
    assert info.compress_type == 0
    zf.fp.seek(info.header_offset + len(info.FileHeader()) + 20)

    encoding='ASCII'
    fix_imports=True
    pickle_kwargs = dict(encoding=encoding, fix_imports=fix_imports)
    array = np.lib.format.read_array(zf.fp, allow_pickle=True, pickle_kwargs=pickle_kwargs)
    return array

```
the different is the input of read_array, if use zf.open(name + '.npy'), read_array will be very slow
all test code :
```
 
import numpy as np
import zipfile
from numpy.compat import (
    isfileobj, os_fspath, pickle
    )

import time
def load_from_npz(path, name):
    zf = zipfile.ZipFile(path)
    info = zf.NameToInfo[name + '.npy']
    assert info.compress_type == 0
    zf.fp.seek(info.header_offset + len(info.FileHeader()) + 20)

    encoding='ASCII'
    fix_imports=True
    pickle_kwargs = dict(encoding=encoding, fix_imports=fix_imports)
    array = np.lib.format.read_array(zf.fp, allow_pickle=True, pickle_kwargs=pickle_kwargs)
    return array

# create .npz file
x1 = np.arange(250000000, dtype=np.uint8)
x2 = np.arange(250000000, dtype=np.uint8)
x={"x1":x1,"x2":x2}
np.savez('/tmp/test.npz', row=x)
time0=time.time()
xx = np.load("/tmp/test.npz", allow_pickle=True)['row']
print("np base:", time.time()-time0)

time0=time.time()
xx = load_from_npz("/tmp/test.npz", 'row')
print("faster:", time.time()-time0)


```

times:
np base: 1.1874120235443115 
faster: 0.3725574016571045

### Python and NumPy Versions:

python3.9
numpy1.24.4

**Comment by rgommers** [comment] 2024-05-22 08:54
duplicate of gh-26498

**Closed by rgommers** 2024-05-22 08:54 UTC
Labels: 00 - Bug
