### ISSUE TITLE
runtimeError: package fails to pass a sanity check” for numpy

### ISSUE THREAD

**Issue by SVijayB** [numpy/numpy#17963] opened 2020-12-09 07:02 UTC
### Reproducing code example:

```python
import numpy as np
import matplotlib.pyplot as plt

n_groups = 4
means_frank = (90, 55, 40, 65)
means_guido = (85, 62, 54, 20)

fig, ax = plt.subplots()
index = np.arange(n_groups)
bar_width = 0.35
opacity = 0.8

rects1 = plt.bar(index, means_frank, bar_width,
alpha=opacity,
color='b',
label='Frank')

rects2 = plt.bar(index + bar_width, means_guido, bar_width,
alpha=opacity,
color='g',
label='Guido')

plt.xlabel('Person')
plt.ylabel('Scores')
plt.title('Scores by person')
plt.xticks(index + bar_width, ('A', 'B', 'C', 'D'))
plt.legend()

plt.tight_layout()
plt.show()
```

### Error message:

```RuntimeError: The current Numpy installation ('C:\\Users\\Username\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime.```

### NumPy/Python version information:

Python version : python3.9
NumPy version : numpy1.19.4

**Comment by mattip** [comment] 2020-12-09 08:06
Duplicate of many other issues. The complete error message should point you to a thread about how this is a problem with windows and will be fixed in a future windows version. The work around is to install NumPy 1.19.3, not 1.19.4. Closing, please reopen if there is something new I missed.

**Closed by mattip** 2020-12-09 08:06 UTC

**Comment by SVijayB** [comment] 2020-12-09 14:27
@mattip thanks for the help!
