### ISSUE TITLE
BUG: `scipy.special` import broken with numpy 1.24.0rc1

### ISSUE THREAD

**Issue by Carreau** [numpy/numpy#22673] opened 2022-11-25 09:36 UTC
### Describe the issue:

NumPy Rc seem to break some of SciPy ? 

it might be a SciPy issue, but as it's the numpy RC.. I prefer to open it here.

### Reproduce the code example:

```python
conda create -n rc python==3.10
conda activate rc
pip install scipy numpy --pre
python -c 'from scipy.spatial.distance import euclidean' 
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bussonniermatthias/miniforge3/envs/dl/lib/python3.10/site-packages/scipy/spatial/__init__.py", line 111, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/Users/bussonniermatthias/miniforge3/envs/dl/lib/python3.10/site-packages/scipy/spatial/_geometric_slerp.py", line 9, in <module>
    from scipy.spatial.distance import euclidean
  File "/Users/bussonniermatthias/miniforge3/envs/dl/lib/python3.10/site-packages/scipy/spatial/distance.py", line 121, in <module>
    from ..special import rel_entr
  File "/Users/bussonniermatthias/miniforge3/envs/dl/lib/python3.10/site-packages/scipy/special/__init__.py", line 649, in <module>
    from . import _ufuncs
ImportError: dlopen(/Users/bussonniermatthias/miniforge3/envs/dl/lib/python3.10/site-packages/...
     ...scipy/special/_ufuncs.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_npy_asinh)
```

### NumPy/Python version information:

```
1.24.0rc1 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:27:15) [Clang 11.1.0 ]
```

**Comment by mattip** [comment] 2022-11-25 10:16
Maybe due to the npmathlib changes, but I would have thought that would turn up in the scipy CI.

**Comment by mattip** [comment] 2022-11-25 10:18
The last line, when formatted a little differently is
```
ImportError: dlopen(<path>/python3.10/site-packages/scipy/special/_ufuncs.cpython-310-darwin.so, 0x0002): \
    symbol not found in flat namespace (_npy_asinh)
```

**Comment by Carreau** [comment] 2022-11-25 11:00
> I would have thought that would turn up in the scipy CI.

I can't find a ``--pre`` in scipy test suite, so they may not have tested the current RC ? 



> The last line, when formatted a little differently is

I've slightly reformatted my comment to make it more readable.

**Comment by mattip** [comment] 2022-11-25 12:07
What scipy version are you getting?

**Comment by Carreau** [comment] 2022-11-25 12:22
Latest, 1.9.3

```
>>> scipy.__version__
'1.9.3'
```

**Comment by mattip** [comment] 2022-11-25 14:03
I cannot replicate the error on macos_x86_64.

The npy_math functions should be linked into the scipy binary, and not depend on numpy providing them: that is the whole point of using a libnpymath.a static library. On linux and on macos, I see that `nm <path>/_ufuncs.cpython-*.so |grep npy_asinh` shows it is linked into the so. Could you try that on your problematic conda environment?

**Comment by mattip** [comment] 2022-11-25 14:08
I can reproduce on macos_arm64. And indeed the `nm ... |grep np_asinh` shows a `U`. I wonder what is wrong with the build there.

**Comment by Carreau** [comment] 2022-11-25 14:10
```
$ nm /.../scipy/special/_ufuncs.cpython-310-darwin.so |grep _npy
                 U _npy_asinh
                 U _npy_atan2
                 U _npy_cabs
                 U _npy_cexp
                 U _npy_clog
                 U _npy_copysign
                 U _npy_cpow
                 U _npy_csqrt
                 U _npy_log1p
```

**Comment by mattip** [comment] 2022-11-25 14:16
macos_arm64 scipy 1.8.0 also does not properly link the npymath symbols. On macos_x86_64, `grep "U _npy"` is empty.

**Comment by mattip** [comment] 2022-11-25 14:20
numpy does link in the symbols properly on macos_arm64:
```
nm <path>/_multiarray_umath.cpython-310-darwin.so|grep "_npy_a"
```

does not show any with a "U"

**Comment by mattip** [comment] 2022-11-27 05:09
I think the problem is [here in the scipy build](https://github.com/scipy/scipy/actions/runs/3502905555/jobs/5867603265#step:6:967). It has gotten a x86_64 version of the library:
```
ld: warning: ignoring file <path>/numpy/core/include/../lib/libnpymath.a, \
   building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

[Earlier in the log](https://github.com/scipy/scipy/actions/runs/3502905555/jobs/5867603265#step:6:279) I see it is installing numpy for x86_64. Maybe the command should have an `arch -arm64` preface or use `python -m pip` ?
```
Downloading numpy-1.23.4-cp38-cp38-macosx_10_9_x86_64.whl
```

This is for the python3.8 macos arm64 wheel. I don't see where the python3.10 macos arm64 wheel is built.

**Comment by mattip** [comment] 2022-11-27 05:10
@rgommers: thoughts?

**Comment by rgommers** [comment] 2022-11-27 10:24
Ah yes, fun. I believe this is a problem for both the distutils and meson builds when cross-compiling from x86-64 to arm64. I'm actually removing the offending symbol here: https://github.com/scipy/scipy/pull/17481. This has always been a problem, but it's been made visible by the recent cleanups to `libnpymath`. In particular, `npy_asinh` & co used to have an implementation but are now using C99 functions (e.g., `#define npy_asinh asinh`). 

So I guess what is happening here is that the correct `npy_asinh` implementation was loaded by `import numpy` already, but in 1.24.0rc1 that does not exist anymore.

> This is for the python3.8 macos arm64 wheel. I don't see where the python3.10 macos arm64 wheel is built.

The Python 3.8 arm64 wheel is cross-compiled on GHA because of some cibuildwheel or Python issue. For Python >= 3.9 those wheels are built on native M1 CI (Cirrus CI). So I'm surprised that @Carreau is seeing it on Python 3.10 - I'll look into that more.

**Comment by mattip** [comment] 2022-11-27 11:06
The last python3.10 wheel build [does download the arm64 wheel](https://cirrus-ci.com/task/4668634954465280?logs=cibuildwheel#L75). When I check it I see it does not depend on external `npy_*` symbols. Maybe the releases (including 1.9.3) were still built with a cross-compiler?

**Comment by rgommers** [comment] 2022-11-27 11:12
Ah yes, that is the case - the `1.9.x` branch does not contain the Cirrus CI config files.

**Comment by Carreau** [comment] 2022-11-27 12:23
Is there a corresponding issue that should be opened on SciPy beyond @rgommers pull request, 
and should we open an issue to remind us to re-remove those symbols in a few years?

**Comment by rgommers** [comment] 2022-11-27 12:32
Doesn't need an issue on this repo I'd say - we have an infinite number of potential cleanups. A code comment saying why we re-export these and when they can be cleaned up (once 1.10.0 is the minimum SciPy version that will work with the next NumPy version) should be enough.

Don't think it needs a SciPy issue either, since the problem is already fixed (once my PR is merged). The actual  bigger-picture issue is gh-20880, we need to get rid of `libnpymath.a` and `libnpyrandom.a` completely.

**Closed** 2022-11-27 17:16 UTC
Labels: 00 - Bug
