### ISSUE TITLE
Numpy report SegmentFault when using together with nltk and opencv

### ISSUE THREAD

**Issue by velconia** [numpy/numpy#12497] opened 2018-12-06 15:11 UTC
### System Environments

OS: Ubuntu16.04 or Ubuntu18.04
This is ```lsb_release -a``` result:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

This is ```uname -a``` result: 
```Linux ubuntu 3.10.0_3-0-0-15 #1 SMP Fri Jan 12 18:18:11 CST 2018 x86_64 x86_64 x86_64 GNU/Linux```

This is ```cpuinfo```:
```
processor       : 10
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
stepping        : 4
microcode       : 0x1
cpu MHz         : 2099.998
cache size      : 4096 KB
physical id     : 10
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 10
initial apicid  : 10
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes xsave avx f16c rdrand hypervisor lahf_lm arat fsgsbase tsc_adjust smep erms xsaveopt
bogomips        : 4199.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
```

Python version: Python3.6.7
This is how I install Python3.6:
```
apt-get install python3.6
```

This is how I install all the Python Libraries: 
```
pip3.6 install nltk==3.4
pip3.6 install opencv-python==3.4.4.19
pip3.6 install numpy==1.14.0
```

Dependencies: DO NOT install opencv via apt (```apt install python-opencv```), which fill fix this problem

### Reproducing code example:
```python
import nltk
try:
    import cv2
except ImportError as e:
    print('error', e)

import numpy
print(numpy.zeros((256, 256), dtype='float32') / 255.0 * 2.0)
```

### Error message:
```
Segmentation fault
```

**Comment by velconia** [comment] 2018-12-06 15:13
And the size of ```numpy.zeros((256, 256), dtype='float32') / 255.0 * 2.0``` is very important, this error only occur when ndarray's size is more than 256 * 256;

**Comment by velconia** [comment] 2018-12-07 07:45
I changed the error message and reproducing way.

**Comment by mattip** [comment] 2018-12-07 08:08
Can you give a complete set of instructions to reproduce, since this seems to depend on other packages? Once you download and expand the python 3.6.0 from python.org, how did you install numpy, ntlk, opencv:, with what options, libraries, in which order? What hardware are you running on?

**Comment by velconia** [comment] 2018-12-07 08:31
@mattip I updated all the informations u listed now.

**Comment by velconia** [comment] 2018-12-10 04:46
@mattip it doesn't help...

**Comment by mattip** [comment] 2018-12-23 09:56
Can you
- Install python3.6 from python.org and add it to the path
- `python3.6 -mpip install numpy==1.14.0`
- test `python -c import numpy; print numpy.__version__; print(numpy.zeros((256, 256), dtype='float32') / 255.0 * 2.0)`
- `python3.6 -mpip install opencv-python==3.4.4.19`
- test `python -c import numpy; print numpy.__version__;  print(numpy.zeros((256, 256), dtype='float32') / 255.0 * 2.0)`
- `python3.6 -mpip install nltk==3.4`
- test `python -c import numpy; print numpy.__version__;  print(numpy.zeros((256, 256), dtype='float32') / 255.0 * 2.0)`

**Comment by seberg** [comment] 2023-01-02 21:33
Going to close this, I don't know what is going on here, but this issue is many years old and doesn't seem like a NumPy issue to begin with (but rather opencv or nltk doing something nasty).  The only known bad systems are on unsupported Python versions by now.

In the unlikely case that anyone can reproduce, it would be good to get a gdb traceback or similar and open a new issue.

**Closed by seberg** 2023-01-02 21:33 UTC
