### ISSUE TITLE
No module named 'numpy.core._multiarray_umath on debug version of CPython

### ISSUE THREAD

**Issue by Armoken** [numpy/numpy#23385] opened 2023-03-14 12:05 UTC
### Describe the issue:

I am developing a project that loads the CPython library at runtime, and using Python C API we import Numpy. We have no problems with the Release version of CPython, but an error occurred when we used Debug version.

### Reproduce the code example:

```python
///// Using Python C API /////
PyObject* numpy = PyImport_ImportModule("numpy.core.multiarray");
// And numpy here equal to NULL

///// Using Python repl /////
import numpy.core.multiarray
```

### Error message:

```shell
///// Using Python C API /////

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\vashcali\Documents\Projects\DesignSuit\ds\ptcl\public\dev\build\src\target\uptolemy\ptcl\Debug\ptcl.exe"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

///// Using Python repl /////
>>> import numpy.core.multiarray
Traceback (most recent call last):
  File "C:\ProgramData\VPI\VPIpython\x64\pyenvs\6\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\ProgramData\VPI\VPIpython\x64\pyenvs\6\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\ProgramData\VPI\VPIpython\x64\pyenvs\6\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\VPI\VPIpython\x64\pyenvs\6\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\ProgramData\VPI\VPIpython\x64\pyenvs\6\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\ProgramData\VPI\VPIpython\x64\pyenvs\6\Scripts\python_d.exe"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Runtime information:

>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.21.6
3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]

**Comment by seberg** [comment] 2023-03-14 12:11
On windows, you have to recompile the entire stack if you use a debug python.  I.e. you will have to install/compile numpy specifically for the debug version, unfortunately.

**Comment by seberg** [comment] 2023-03-15 09:11
There is nothing special, you can probably even pip install, so long you are in the debug python and you got all the necessary build setup, which is annoying on windows admittedly, but maybe you have that already.

**Comment by rgommers** [comment] 2023-03-15 10:33
> On windows, you have to recompile the entire stack if you use a debug python. I.e. you will have to install/compile numpy specifically for the debug version, unfortunately.

Is this really still true? https://docs.python.org/3/using/configure.html#python-debug-build says:
_Changed in version 3.8: Release builds and debug builds are now ABI compatible: defining the `Py_DEBUG `macro no longer implies the `Py_TRACE_REFS` macro (see the [--with-trace-refs](https://docs.python.org/3/using/configure.html#cmdoption-with-trace-refs) option), which introduces the only ABI incompatibility._

Are you aware of written content (docs or a bug report) about this still being a problem on Windows?

**Comment by seberg** [comment] 2023-03-15 10:54
Good point,  @Armoken should probably just upgrade the python version.  He is using 3.7, so it definitely is the reason.

**Comment by mattip** [comment] 2023-03-15 21:51
As far as I know, running a debug python with the debug runtime and a release numpy with the release runtime might lead to some subtle bugs where memory allocated by one would be freed by the other, leading to strange crashes. 

In general on windows, the debug mode is useful when you control the entire stack of an application. For integration work, I have had much better luck using the "release with debug information" mode, since a debugger will still be able to analyze the code, while allowing release versions of the dependencies to run without suspicion of introducing new runtime bugs.

**Comment by seberg** [comment] 2023-03-16 08:11
Ah, tricky.  But closing for now, you can try asking if you need a pointer, though.  But overall, I doubt it is a NumPy issue, so lets reopen it if you end up finding there is more to it.

**Closed by seberg** 2023-03-16 08:11 UTC
Labels: 57 - Close?, 32 - Installation

**Comment by mattip** [comment] 2023-06-14 08:38
Hmm. Confusing.

> Pip install .

Which python is being used here? In which directory? If you have already installed via pip, you should be done, no?

> Then go to the directory of numpy1.19.3 source code and run.
> Python_d setup.py build_ext -i install

Using `setup.py` directly like this was BestPractices a while ago, but newer builds should use `pip` instead. That will ensure you get whatever backend the package is using. For instance, NumPy is moving to meson and away from distutils/setuptools. I tend to use a virtualenv and install an [editable build]() of NumPy into it:
```
> python_d -m venv %TEMP%\venv3d
> %TEMP%\venv3d\Scripts\activate
(venv3d) > python -m pip install -e .
(venv3d) > python -c "import numpy"
```

You are using 1.19 which is quite an old version of NumPy, so YMMV. It does have `pyproject.toml`, so I think my advice is still relevant as long as you update `pip` to the latest version.

**Comment by abdelmaged** [comment] 2023-06-15 20:21
I've built numpy using:

> > python_d -m venv %TEMP%\venv3d
> %TEMP%\venv3d\Scripts\activate
(venv3d) > python -m pip install -e .
(venv3d) > python -c "import numpy"

However, when running simple C++ application with embedding python script that load numpy and just print its version I get this error:
`ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.`

I've debug the app in vscode and noticed this in debug console:
`Loaded 'numpy\numpy\core\_multiarray_umath_d.cp311-win_amd64.pyd'. Module was built without symbols.`

I think there is an issue in numpy preventing creating full debug build.

**Comment by rgommers** [comment] 2023-06-15 20:30
You cannot build a debug build on Windows unless you also have a debug build of Python; it's very well possible that to work around that CPython usability issue, somewhere in the build the debug symbols are turned off. You're going to have to dig through the whole build log I'm afraid to figure out what is happening there. There's nothing of interest in `numpy/distutils/msvccompiler.py` as far as I can tell, and that code is obsolete (as is `distutils` from the stdlib, which is most likely where the problem is), so I'm not sure you want to invest a lot of effort in digging in there.

**Comment by abdelmaged** [comment] 2023-06-16 09:16
Adding the following section in `setup.cfg`
```
[build]
debug = 1
```
Produced debug symbols. One issue though it was missing the `_d` suffix. By manually adding the suffix, embedded python code ran without errors.
