### ISSUE TITLE
Assign shifted diagonal values with `np.fill_diagonal` and similar behaviour as `np.diag`

### ISSUE THREAD

**Issue by scratchmex** [numpy/numpy#18000] opened 2020-12-15 03:29 UTC
## Feature

As the subject says it will be great if `np.fill_diagonal` had a k-ith diagonal argument as `np.diag` does. The behavior expected (and a hack for the solution) is better explained in the [following StackOverflow question](https://stackoverflow.com/questions/65299295/assign-shifted-diagonal-values-with-np-diag/65299483) by me

## Expected behaviour
```python
>>> u = np.zeros(25).reshape(5, 5)
>>> u
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
>>> np.fill_diagonal(u, 1, k=1)
>>> u
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])
```

## Current solution
```python
>>> u = np.zeros(25).reshape(5, 5)
>>> u
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
>>> u[np.eye(len(u), k=1, dtype='bool')] = 1
>>> u
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])
```

## Why this syntax?
This is already intuitive as `np.diag` use the same syntax. For example:
```python
>>> u
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])
>>> np.diag(u, k=1)
array([1., 1., 1., 1.])
```

Unfortunately, as `np.diag` is a function, one cannot assign a value like `np.diag(u, k=1) = 1`. That's why implementing the `k` argument on `np.fill_diagonal` should be desired. 

I want to take this issue and make a PR. Just want to discuss it before to better implement it and document it.

**Comment by adeak** [comment] 2020-12-15 11:32
For the record you can do this if you are willing to break a few things:

```
import numpy as np

u = np.zeros(25).reshape(5, 5)
d = np.diag(u, k=1)

# d[...] = 42  # is an error, because this is a read-only view

d.flags['WRITEABLE'] = True  # but rather don't do this
d[...] = 42  # now works
```

And the result is what you expect:
```
>>> u                                                                                                                                                                                                              
array([[ 0., 42.,  0.,  0.,  0.],
       [ 0.,  0., 42.,  0.,  0.],
       [ 0.,  0.,  0., 42.,  0.],
       [ 0.,  0.,  0.,  0., 42.],
       [ 0.,  0.,  0.,  0.,  0.]])
```

Sort of relevant issue: https://github.com/numpy/numpy/issues/7661 (about making `diag` writeable). See also [this older thread](http://numpy-discussion.10968.n7.nabble.com/The-future-of-ndarray-diagonal-td39426.html) linked from there.

But I agree that making `fill_diagonal` support the offset parameter would make sense and be an idiomatic solution.

**Comment by ilayn** [comment] 2020-12-15 13:55
Fancy indexing also works

```python
I = np.zeros([6, 6])
I[range(0, 5), range(1, 6)] = 1
```

this gives 

```python
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])
```

**Comment by ewmoore** [comment] 2020-12-15 17:13
Duplicate of #14402.  PR open for this in #15079.  So absolutely this should go in somehow.  Seems like it needs a champion to push it through.

**Comment by eric-wieser** [comment] 2020-12-15 17:26
Duplicate of #14402.

**Comment by eric-wieser** [comment] 2020-12-15 17:27
Duplicate of #14402

**Closed** 2020-12-15 17:26 UTC

**Comment by eric-wieser** [comment] 2020-12-15 17:28
@ilayn, a faster way is:
```
In [51]: I = np.zeros([6, 6])

In [52]: np.fill_diagonal(I[:,1:], 1)

In [53]: I
Out[53]:
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])
```

**Comment by ilayn** [comment] 2020-12-15 18:00
@eric-wieser 🤦‍♂️ One day I will learn to remember this before someone tells me.
