### ISSUE TITLE
ENH: Support for fractions.Fraction in np.average()

### ISSUE THREAD

**Issue by evinism** [numpy/numpy#21988] opened 2022-07-15 08:35 UTC
### Proposed new feature or change:

Not sure if this is by design. `np.average()` does not support Fraction. `np.mean()` behaves as expected. 

Actual:
```
from numpy import np
from fractions import Fraction

arr = np.array([Fraction(1, 5), Fraction(3, 5)]))
print(np.average(arr)) # Throws! 
```

Proposed / Expected:
```
from numpy import np
from fractions import Fraction

arr = np.array([Fraction(1, 5), Fraction(3, 5)]))
print(np.average(arr)) # Fraction(2, 5)
```

**Comment by eendebakpt** [comment] 2022-07-18 19:21
The problem is in this part of the code:
```
    if weights is None:
        avg = a.mean(axis)
        scl = np.asarray(avg).dtype.type(a.size/avg.size)
    else:
         ....
```
The output of `a.mean(axis)` is a `Fraction` object, which does not have a field dtype. The problem can be fixed by changing the code into
```
    if weights is None:
        avg = a.mean(axis)
        scl = np.asarray(avg).dtype.type(a.size/avg.size)
    else:
         ....
```
This adds a bit of extra overhead, but that might be acceptable as one could argue the `np.average` should be called with weights (and if no weights should be used, just call `np.mean`)

There are other types that fail for the same reason, for example
```
import numpy as np
import gmpy2
x=np.array([gmpy2.mpfr(1.), gmpy2.mpfr(10.)])

np.mean(x) # good
np.average(x, weights= [1, 10]) # good
np.average(x) # throws
```

**Closed** 2022-09-03 15:51 UTC
Labels: 01 - Enhancement, component: numpy.lib
