### ISSUE TITLE
BUG: Exceptions are silenced in __array_interface__

### ISSUE THREAD

**Issue by mpelchat04** [numpy/numpy#11629] opened 2018-07-27 12:44 UTC
was: Array from PIL image empty without exception

---

I'm reading a bunch of RGB images, one at a time, with different size using the [PIL library](http://pillow.readthedocs.io/en/3.1.x/index.html) and then convert them to numpy array. I use the following code and with 99% of the images I use, it works well.  
```python
from PIL import Image
import numpy as np

in_image = r'path\to\img_rgb.tif'

try:
    in_img = Image.open(in_image)
    in_array = np.array(in_img)
    print(in_array.shape)
    print(in_array)
except Exception as e:
    print(e)
```
Where the result is the following:  
![image](https://user-images.githubusercontent.com/38693210/43285357-b5603a2a-90ec-11e8-9d44-f12c5413a424.png)

Although, 1% of the time, the numpy array as an empty shape ```()``` and the array itself is just a PIL image object and not at all a numpy array. No error and no exception are raised.
![image](https://user-images.githubusercontent.com/38693210/43285388-cdd96a0e-90ec-11e8-8bde-bc6f12e0639e.png)

Plus, when debugging, nothing in the PIL Image object seems to indicate that the image is corrupted or something. 

Here's a sample of images [images_test.zip](https://github.com/numpy/numpy/files/2235725/images_test.zip) containing a "good_img.tif" which return the numpy array correctly and a "bad_img.tif" which return the not good array. 

So I have two questions related to this:  
1- Isn't it weird that no exception is raised when the array shape is empty?  
2- What is happening with the bad image?

**Comment by seberg** [comment] 2018-07-27 13:00
1. Yes it is, we have open issues about it, though. It is a bit tricky to change (in other words, people might be relying on it), but it probably should try to change anyway (with a long warning).
2. PIL has some issue there, what PIL does is to define `image.__array_interface__` or `image.__array__` to tell numpy how to convert/view the data as an ndarray. Now, if PIL fails to do that for whatever reason, you will get exactly what you noticed. You will notice that in that case the `arr.dtype` is going to be object.

**Comment by mpelchat04** [comment] 2018-07-27 13:17
Thanks for your prompt answers.
1. Yes, I guess I can understand some cases where people might want certain array to be of empty shape and in that case, they do not want exception to be raised and a warning could be the solution.
2. If I understand correctly, the error is coming from PIL and the way it tells numpy to view the data. In this case, PIL should gives me error or exceptions... I'll look into that.

**Comment by seberg** [comment] 2018-07-27 14:19
Well, the first point should be the case very rarely, so it would be nice if someone can see whether we cannot change the default (put in a warning in place for now in some of these cases), but there are open issues for that.

Yes, please look into PIL, I am not sure what it does exactly (I assume you are using Pillow not PIL, the fork with the same name, just to be sure, the original PIL is unmaintained). It might be that PIL could define an `__array__` method or so that simply raises an informative error.

I will close this for now, since there is probably nothing in numpy to actually do, but please comment if you find anything or have a question!

**Comment by eric-wieser** [comment] 2018-07-27 15:56
Here's the cause:
```
>>> g = Image.open('good_img.tif')
>>> g.__array_interface__
{'data': b'mbJohMunSvoUrjQpiOphNqgPriTsiUqjTmeOmcLsiRrgPthSphNodMnfNohQoiQodNmbKoeOrgRvlVys]voYphPocOpePsiRvnUpiMndMmbLleLoeOqeOrhRrhRrkRtlVpiTpePuiUtkVohQqiNocNqiNpiOnbMpcNrgPskSshRqgQrhRohSskWwoZsjUldOriPpeLqeQqcNsiSxo[ukUtkVrgQpeOqeSneRrjRqjQkcPe]KrkUpiTqeNreQulRxoVxoZvnXshQrhRrgUneQneQjcMj_JjaLvmZrdRpePojLslSwoVyqXwmWtiQrjTrgVkaQmbPkbNibOe^NoiRofRpeOoeNqjPrkQrgNoeNmaKlbNm`Pi^Ni_Of_MiaNg`MoiQpjRqiQpeNphOodNobLncLofMmePlcPiaPi^Mf[Jf_KicNmdPsmVunUrjTujUshRpfRneQldOg`Kf]Id\\IfZJf[Li`NmfPphSpfRmaLncMukTshSpaOmcOkbNd_Jd]Jc^Lf^Ji^IkaKldKpjSpdRpcOocModNpdPnbQkcQg`Mb\\Gd]Ge`IkaKodOohNldJvnYphSqeSpdRnbNlcNmcOldPkcOf`LjbNkePmbLodMqhOphLpiTrkWsmXphRlaLiaLe]Ke^Lg]Mb]KicNlhPohNpeMqhNqjOphSrkVqjTkdOkcMg^KiaLe`Ni_OkcPphTpjTndMmaJmaLqjPnbQofTmeQd_Jb\\F`UDcYIf]JkbOneRrgQqeOocLpeLpcOsgQ',
 'shape': (16, 16, 3),
 'typestr': '|u1',
 'version': 3}
>>> b = Image.open('bad_img.tif')
OSError: decoder tiff_lzw not available
```

**Comment by eric-wieser** [comment] 2018-07-27 15:56
So I'd say there is a numpy bug here - errors looking up `__array_interface__` are silenced

**Comment by seberg** [comment] 2018-07-27 16:23
Probably right, though that example looks like it should never reach the `__array_interface__` lookup? Anyway, right for sure that we should only be silencing AttributeErrors.

**Comment by seberg** [comment] 2022-11-19 15:41
Looking at the code, we seem to have fixed it (there are other places that could use narrower error checking, but this one looks fine).

**Closed by seberg** 2022-11-19 15:41 UTC
