### ISSUE TITLE
ufunc.at (and possibly other methods) slow

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#11156] opened 2018-05-24 12:34 UTC
I noticed that in many of my codes, seemingly harmless lines like
```python
numpy.add.at(target, idx, vals)
```
take a large share of the runtime. I investigated and found that one gets a speed-up of a factor of 40 (!) by simply moving the critical code to C++.

![f](https://user-images.githubusercontent.com/181628/40485655-6e5a98a0-5f5f-11e8-9e5a-13d9b02eae86.png)

(Not sure what's actually done in `numpy.ufunc`.) I put this into a very simple module, https://github.com/nschloe/fastfunc, so feel free to take some code out of there.

**Comment by mattip** [comment] 2018-05-24 15:34
is the graph generated by https://github.com/nschloe/fastfunc/blob/master/test/performance.py ?

**Comment by seberg** [comment] 2018-05-24 16:27
We can leave this open, #5922 seems like a duplicate. I am surprised I did not create an issue the day we merged it, harharhar. Somewhere hidden in the depths there are some pointers how to make it at least a small factor faster (making it much faster is more involved, using a faster hook into the fancy indexing machinery and requiring to special different cases).

**Comment by jaimefrio** [comment] 2018-05-24 16:59
[Here](https://github.com/numpy/numpy/issues/5922#issuecomment-106342986) I explained what makes `ufunc.at` slow. Your code [here](https://github.com/nschloe/fastfunc/blob/master/src/pybind11.cpp) takes a few shortcuts that are not really available to NumPy:

 - You have hardcoded the operations you have implemented, `+`, `-`, `*` and `/`, which is OK for most use cases, but does not support generic operations. If you had a generic function that took a function pointer that performed the operation, you would have more generic, albeit slower code. That is what NumPy does.

 - You have assumed that the `a` and `b` arrays are of the same type, which is not always the case. Not sure if your code can handle cases where these don't match, but that's a liberty NumPy can't take either.

 - I'm not sure how much magic pybind11 packs, but your iteration scheme seems deceptively simple for all the subtleties of fancy indexing that `ufunc.at` supports. Are you assuming that some/all of the arrays are 1D? That's again something NumPy isn't free to do.

**Comment by eric-wieser** [comment] 2018-05-24 16:59
It would be great if we could start using C++ template instead of the `.c.src` stuff within numpy, but I imagine there are distribution issues with that...

**Comment by nschloe** [comment] 2018-05-24 17:20
> I'm not sure how much magic pybind11 packs, but your iteration scheme seems deceptively simple for all the subtleties of fancy indexing that ufunc.at supports. Are you assuming that some/all of the arrays are 1D? That's again something NumPy isn't free to do.

In `op(target, idx, vals)`, the C++ code assumes `target` and `vals` to be 2D, `idx` to be 1D. All cases are simply reshaped into that; see https://github.com/nschloe/fastfunc/blob/master/fastfunc/helpers.py.

> You have assumed that the a and b arrays are of the same type, which is not always the case. Not sure if your code can handle cases where these don't match, but that's a liberty NumPy can't take either.

This could perhaps be generalized; for now I just wanted to create a show case.

> You have hardcoded the operations you have implemented, +, -, * and /, which is OK for most use cases, but does not support generic operations. If you had a generic function that took a function pointer that performed the operation, you would have more generic, albeit slower code. That is what NumPy does.

Well, then perhaps +, -, *, / should be treated differently than custom functions?

**Comment by ml31415** [comment] 2018-08-30 17:17
> Well, then perhaps +, -, *, / should be treated differently than custom functions?

Yes, all the common things like `min`, `max`, `mean`, `std` and so on clearly deserve a dedicated treatment.

Not sure if you saw [numpy-groupies](https://github.com/ml31415/numpy-groupies) already. If using `numba` or `weave` is an option for you, you might have a look at it. The speeds should be comparable with what you had with your C++ implementation. It has seen proper testing and also several other functions implemented and optimized by now.

**Comment by charris** [comment] 2018-08-30 19:31
> It would be great if we could start using C++ template instead of the .c.src

There was a discussion back in the 2010-2011 time frame about moving to C++. I'm not so much bothered by the current templates, but having smart pointers and error handling would be a big +. The downside is that writing good C++ code takes a lot of expertise and the compiler error messages, especially of templates, are practically indecipherable. There would also be a need for keyword variable name cleanup, things like variables named `new`.  I expect many things have improved since C++11 has come out and been widely implemented, unlike the early days when C++ support was quite spotty and unreliable.

**Comment by mattip** [comment] 2022-12-27 22:13
Duplicate of #5922

**Comment by mattip** [comment] 2023-02-08 08:38
Closing #23136 was merged.

**Closed by mattip** 2023-02-08 08:38 UTC
Labels: 01 - Enhancement, 50 - Duplicate, component: benchmarks
