### ISSUE TITLE
Bugs in computations with integers read from a numpy 2.0 array

### ISSUE THREAD

**Issue by Martin-Seysen** [numpy/numpy#26719] opened 2024-06-17 11:24 UTC
### Describe the issue:

I use numpy arrays, say, of ``dtype=np.uint8``, for storing a large amount of data. When reading data from such an array in numpy 1.x,  I obtain integers which I can use for further calculations as indicated in the minimal example below. This is no longer possible with numpy 2.0; here I obtain some kind of numpy scalars instead, leading to errors or unexpected results.

I think a C or python programmer would expect integers when reading data from integer arrays (as in numpy version 1), and not some special data structures that are hard to understand (as in numpy 2.0). Also, I do not understand why overflow in a subtraction leads to a warning, and overflow in an XOR operation leads to an error. 

### Reproduce the code example:

```python
>>> import numpy as np
>>> np.__version__
'2.0.0'
>>> a = np.array([1], dtype=np.uint8)
>>> a[0] - 2
<stdin>:1: RuntimeWarning: overflow encountered in scalar subtract
np.uint8(255)
>>> a[0] ^ -1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python integer -1 out of bounds for uint8
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python integer -1 out of bounds for uint8
```

### Python and NumPy Versions:

Python 3.12.2
numpy 2.0.0

### Runtime Environment:

[{'numpy_version': '2.0.0',
  'python': '3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, '
            '19:42:21) [MSC v.1916 64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='MartinPC', release='11', version='10.0.22631', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}}]

### Context for the issue:

In a project with almost 100000 lines of code I have dozens (or even hundreds) of  functions reading data from numpy arrays in the way described above. Casting all these data to python integers manually would be a really great burden for me.

**Comment by mhvk** [comment] 2024-06-17 11:46
This is a consequence of the rules for promotions of python scalars having changed, and array scalars now being treated the same as arrays - see [NEP 50](https://numpy.org/neps/nep-0050-scalar-promotion.html). It is one of those cases where one cannot please every one; as you will see from the NEP, we've had years of problems with the old promotion rules. This is actually a difficult problem!

In a bit more detail:
- `type(a[0])` has not changed: it remains a `np.uint8`.
- Promotion of `np.uint8` instances is now the same as for `uint8` arrays.
- Python integers have weak promotion: an attempt is always made to cast them to the same dtype: this works for `2` in subtract, but not for `-1` in the exclusive or, hence the different outcomes.

Solving your particular problem will require either explicitly casting the array scalar with `int(a[0])` or `a[0].item()`, or using a numpy scalar instead of a python one, like `np.int64(-1)`.

**Comment by NeilGirdhar** [comment] 2024-06-17 16:54
> It is still a rather big problem to enter hundreds (or thousands) 

Isn't that a design error if you need thousands of casts?  The pathways out of the "numpy world" to the Python scalar world should ideally be limited, don't you think?

If anything, I think NumPy 2 is generous in giving you a scalar at all.  I don't think you get "NumPy scalars" back in the Array API when you index-away every dimension; instead you get arrays of shape `()`.  You need to do an explicit cast to get a Python scalar if you want one.

**Comment by mhvk** [comment] 2024-06-17 17:17
@Martin-Seysen - I'm really hoping that you'll find it is actually not that many places where you need to change. Certainly, for astropy, it wasn't a big deal; the much bigger issue was the change in representation for numpy scalars (which was a pain, definitely, though one I could see the case for).

Just to be clear: this is not going to change, most people want arrays and the scalars derived from them to behave the same way (and in fact this is now the standard for the Array API).

**Comment by NeilGirdhar** [comment] 2024-06-17 17:20
Also, for this particular problem you may want to consider using the self-documenting function [`bitwise_invert`](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_invert.html#numpy.bitwise_invert).  I would choose `bitwise_invert` over `invert` since the former is part of the Array API, and the latter may disappear eventually.

**Comment by Martin-Seysen** [comment] 2024-06-17 17:22
When I started using numpy arrays of integers about 10-20 years ago, I mainly considered them as compact form of vectors or matrices. When I took a single entry of such an array, I could use that entry as an integer and do calculations with it in the same way as one can do this with an entry of a python list or of a C array. If this is no longer possible in numpy 2.0 without a cast; I can probably not do much about this. But 10 years ago I could not see a design error in this approach.

**Comment by rkern** [comment] 2024-06-17 17:44
When you indexed a single entry of an array, you never got a plain Python `int` or `float`. You always got a numpy scalar object of the same dtype of the array; it's been this way since `Numeric` became `numpy` nearly 20 years ago. And it had a complicated set of type promotion rules that were neither those of array dtypes nor the plain Python types. Those rules had plenty of holes, corner cases, and "nobody wanted this" behaviors. Your particular uses probably didn't trigger them, but others' uses did.

I'm going to close this as it looks like things are behaving as designed and documented. Please feel free to continue asking questions for specific advice on how to convert your code, though [the Discourse](https://discuss.scientific-python.org/c/user/17) might be more helpful.

**Closed by rkern** 2024-06-17 17:44 UTC
Labels: Numpy 2.0 API Changes
