### ISSUE TITLE
f2py executable not getting installed on windows

### ISSUE THREAD

**Issue by ianhbell** [numpy/numpy#7532] opened 2016-04-08 20:42 UTC
According to the docs for f2py, which is installed with numpy, it should be sufficient to execute this command at the shell to call f2py:

```
f2py
```

But this fails because on windows, the only file installed is f2py.py, which is not accessible as f2py at the shell.

At one point, I don't remember when, a script/executable was packaged along with the script that did this properly....

See also: https://github.com/ContinuumIO/anaconda-issues/issues/259#issuecomment-207591726

**Comment by matthew-brett** [comment] 2016-04-08 20:46
I'm not sure how f2py is installed at the moment, but it sounds as if we should use a setuptools entry point, or use something like this : https://matthew-brett.github.io/pydagogue/installing_scripts.html

**Comment by ianhbell** [comment] 2016-04-12 19:17
One "solution" to the problem is to add .PY to the PATHEXT environment variable. Worked for me.  See http://stackoverflow.com/a/8249328.  Clearly it would be better if it worked out of the box without munging environment variables...

**Comment by matthew-brett** [comment] 2016-04-12 20:37
The problem with that is when you are working in a virtualenv or with different Python versions - in which case it can get very confusing.

**Comment by ianhbell** [comment] 2016-04-12 20:39
What about from a conda environment?  Shouldn't that work?  Since then the first python found on the path is used?  I read your link in some detail, and it would be great if you could push the numpy folks to fix this bug.

**Comment by matthew-brett** [comment] 2016-04-13 21:17
I don't know what happens with conda I'm afraid.  I suppose that windows needs to know what command to run when it sees a file with a ".py" extension.  Does it just find Python in the path?   Which path - the path for the current shell?

**Comment by FRidh** [comment] 2016-06-30 20:27
On Nix we also have an issue with the name of `f2py` (https://github.com/NixOS/nixpkgs/issues/14692). 

If we look in the [setup.py](https://github.com/numpy/numpy/blob/master/numpy/f2py/setup.py#L57) for `f2py` we can see how the name of the script is generated. It uses the name of the Python executable to determine how `f2py` should be named. 

I noticed that on Nix the CPython 3.5 version was called `f2py3.5.m` and the 2.7 version `f2py2.7`. The `m` apparently comes in because Python was [configured](http://code.activestate.com/lists/python-list/705250/) with `"--with-pymalloc"`.

The test suite will fail because an executable named `f2py` is expected. I think `setup.py` should simply name the file `f2py`, although to be honest I don't know if it would work then on Windows. Or do you want to support having `f2py` for different Python versions in one environment?

**Comment by awbirdsall** [comment] 2016-11-18 16:44
Stumbled across this discussion when trying to fix the same issue as @ianhbell. I found an existing commit that addresses this by making `python -m numpy.f2py` executable from the command line: https://github.com/numpy/numpy/pull/5565.

This works on my Windows machine.  It's still a discrepancy with the docs, but it definitely beats typing in the full path, and it seems to play nice with my different conda environments.

**Comment by pshassett** [comment] 2018-05-24 23:51
Nice solution @awbirdsall, that solved my problem!  Did you also add .PY to your PATHEXT environment variable?

**Comment by awbirdsall** [comment] 2018-05-25 17:09
@pshassett No, I don't think I ever did. I don't think it's necessary here?

**Comment by mattip** [comment] 2018-08-21 05:43
Anyone on windows care to comment if this issue (cannot find f2py) is still relevant?

**Comment by awbirdsall** [comment] 2018-08-21 12:10
@mattip I just updated numpy on my Windows 10 machine to 1.15.0, and I can confirm `f2py` does now work from the command line. 👍

**Comment by mattip** [comment] 2018-08-21 12:40
Closing, please open a new issue if the problem reappears

**Comment by charris** [comment] 2018-08-21 13:05
@awbirdsall 1.15.0 might be misleading, as it had both entry_points and the old script, which was causing f2py to hang in some circumstances. As a result, the entry_points were removed and we are back to the old. If the 1.14 series did not work for you, I expect that 1.15.1 will also fail.

I have no idea where 1.15.0 may have been installing the f2py startup script on windows. Any chance that you can find out?

**Comment by awbirdsall** [comment] 2018-08-21 17:18
@charris thanks for the information. It looks like the startup script was installed in the /Scripts/ folder of my miniconda installation:

~~~
> where f2py
C:\miniconda3\Scripts\f2py.bat
C:\miniconda3\Scripts\f2py.exe
~~~

**Comment by awbirdsall** [comment] 2018-08-22 00:52
I tried creating a new conda env with python 3.5.5 and then used pip in the new environment to install numpy 1.15.1. Within this environment, the startup script for f2py was not installed, and `f2py` on the command line fails. The `python -m numpy.f2py` workaround command still works.

I don't know python/conda packaging well enough to know whether this behavior arises from a numpy 1.15.1 bug, or me improperly mixing pip and conda.

**Comment by charris** [comment] 2018-08-22 01:06
I note that the original script, that is now failing, was intended to work when multiple Python versions were installed. I think that is kind of hopeless now unless they are run in different environments. So at this point I think we should at least document the `python -m numpy.f2py` approach, and probably recommend it for general use. We can also reinstate the `entry_points` approach, which puts out a simple `f2py` file, but I am not clear on where that ends up in various environments on window. There is a (closed) PR #11757 that uses the `entry_point` approach, but I suspect I would need to build a wheel from it for you to test. Compiling NumPy on Windows is a bear.

**Comment by charris** [comment] 2018-08-22 02:27
Leaving this open for a bit.

**Comment by HaoZeke** [comment] 2023-11-20 02:13
Since the documentation clearly states this might not be present reliably and suggests `python -m numpy.f2py` instead, I'll close this for now :)

**Closed by HaoZeke** 2023-11-20 02:13 UTC
Labels: component: numpy.f2py
