### ISSUE TITLE
Truncation behavior raises exception dependent on native Python int length

### ISSUE THREAD

**Issue by DavidMertz** [numpy/numpy#6289] opened 2015-09-07 18:37 UTC
When casting Python ints to NumPy arrays, the truncation of values to the dtype in the array will either succeed or raise OverflowError depending on the native int type of a particular Python compile.  For example:

``` python
>>> np.array([4192984799048971232000, 3, 4], dtype=np.int16)
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-33-5abc2d80bc8e> in <module>()
----> 1 np.array([4192984799048971232000, 3, 4], dtype=np.int16)

OverflowError: Python int too large to convert to C long
```

Oddly, on a Windows 64-bit Anaconda distribution, the native int type is still 32 bits (even though floats are natively 64 bit.  So on those systems, this will fail in the same way (but succeed on a 64-bit OSX version, with 64 bit native ints.

``` python
>>> # The success case below, the failure on other machines same as above
>>> np.array([4192984799048971232, 3, 4], dtype=np.int16)
array([13280,     3,     4], dtype=int16)
```

Obviously, Python native ints are actually unlimited size numbers, but internally they are stored as fixed bit lengths until forced into the unlimited size format.  So in other words, when they happen to be stored in the fixed size optimization, truncation works, but otherwise it fails.  However, whether this will happen is non-obvious to users, and inconsistent between platforms.

A workaround is to wrap every Python sequence used to initialize an np.array in the following function:

``` python
def chop_bits(nums, bitlen=None):
    bitlen = bitlen or np.array([1],int).dtype.itemsize * 8
    mask = int("0b" + "1"*bitlen, 2)
    for num in nums:
        yield num & mask
```

However, given that it is obviously _possible_ to truncate even more-than-native sized ints to cast to NumPy arrays, doing so would be better default behavior.

**Comment by DavidMertz** [comment] 2015-09-07 18:40
My machine:

```python
>>> np.version.full_version, sys.version_info
('1.9.2',
 sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0))
```

**Comment by njsmith** [comment] 2015-09-09 02:22
The problem is that we're extracting the integer value using `PyInt_AsLong`, which returns a C `long`, which is only 32 bits on 32-bit platforms and 64-bit windows. (This is also why numpy's default int type is different between 64-bit windows and 64-bit everything else.)

I guess we could do better by using `PyLong_AsLongLong` /  `PyLong_AsUnsignedLongLong` instead of `PyInt_AsLong`.

**Comment by DavidMertz** [comment] 2015-09-09 18:02
Would it be feasible (and not absurdly slow in the default, non-overflow case) to implement something like my `chop_bits()` in C?

**Comment by njsmith** [comment] 2015-09-09 21:59
In principle, probably yes. In practice, since we don't support more than 64 bits anyway, just using the 64 bit python api calls is probably easier than reimplementing them :-)

**Comment by DavidMertz** [comment] 2015-09-09 22:38
But the documentation says:

```
PY_LONG_LONG PyLong_AsLongLong(PyObject *obj)
Return a C long long representation of obj. If obj is not an instance of PyLongObject, first call its __int__() method (if present) to convert it to a PyLongObject.

Raise OverflowError if the value of obj is out of range for a long.
```

Which seems to mean that we'll still get an OverFlow error for overly large ints (size depending on platform), when truncation is a perfectly sensible operation.  I used the example of `dtype=np.int16` for my example because it will truncate even moderately sized numbers, but that could be the intention (maybe I should have even used `np.int8` to make the point).

Mostly, I just don't like the inconsistency.  If everything too large raised OverFlowError, that would make sense.  E.g. maybe 512 would to so when trying to use `dtype=np.int8`, and that would be predictable behavior.  But now whether you get an overflow has little relation to the dtype chosen, but is a quirk of your platform and specific numeric values (which might be literals, but might also be results of some calculation where it's not obvious it went over the platform native int size from the Python side of things.

So in effect, if I *really* want my collection of Python ints to get stuck into a NumPy intNN array, I have to make sure to call `chop_bits()` first, but not necessarily chopping to my dtype size, but rather to this other platform size (albeit, chopping to exactly to the dtype size *does* also produce the desired result).

**Comment by njsmith** [comment] 2015-09-09 22:49
Oh, I understand.

Yeah, I don't actually know whether the proper semantics of assigning an out-of-range Python `int` to a fixed-size array should be to wraparound or to error out. We've been moving towards making similar kinds of cases error out (e.g. assigning a float to an int array), but I don't think we've talked about this one in particular. Though I agree that it shouldn't wraparound in some cases and error out in others :-) Since this is a question about how the design should even work, you should take it to the mailing list if you want to move forward.

BTW a simpler version of your `chop_bits` would be:
```
INT_BITS = np.dtype(int).itemsize * 8
def truncate_int(nums, bits=INT_BITS):
    mask = 2 ** INT_BITS - 1
    return [num & mask for num in nums]
```

**Comment by DavidMertz** [comment] 2015-09-09 23:25
Yeah, your function is better. Probably using a bit shift is faster than the exponent too. Or maybe it gets optimized away either way.

**Comment by seberg** [comment] 2023-11-03 07:17
Closing, we are trying to switch to 64bit on 64bi tplatforms for NumPy 2.0.  See the dev release notes for example.  Which will change the default on windows specifically.
(And if we may have to undo that, there is probably not much we can do about this.)

NumPy does never truncate Python int's anymore, that is a different choice that we already did a while ago.  Better is in the eye of the beholder, I prefer to force you to be explicit when you know what you are doing (since I assume most users don't, in the sene that they are not thinking about it).

**Closed by seberg** 2023-11-03 07:17 UTC
