### ISSUE TITLE
Odd interaction of summation with automatic conversion to numpy arrays 

### ISSUE THREAD

**Issue by axch** [numpy/numpy#8630] opened 2017-02-17 18:26 UTC
I find it rather odd that `sum` has the effect of concatenating its input lists when they are length-mismatched.
```
>>> np.sum([[1], [2, 3]])
[1, 2, 3]

>>> np.sum([[1], [2, 3]], axis=0)
[1, 2, 3]
```

If the lengths line up, the behavior is what I would expect:
```
>>> np.sum([[1, 2], [2, 3]])
8

>>> np.sum([[1, 2], [2, 3]], axis=0)
array([3, 5])
```

Is this intentional?  I was rather confused, and the documentation (at https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html) did not indicate that this would happen.

I am using numpy version 1.10.4, Python version 2.7.6, on Ubuntu 14.04.  Also reproduced (by @Schaechtle) in numpy 1.11.2, same platform.

**Comment by ahaldane** [comment] 2017-02-17 18:34
This is caused by numpy falling back to "object"-arrays if the input is made of variable length arrays.
```python
>>> a = np.array([[1], [2, 3]])
>>> print repr(a)
array([[1], [2, 3]], dtype=object)
>>> print a.dtype, a.shape, type(a[0])
object (2,) <type 'list'>
```
Note this array has two elements, each of which is Python list (!)

Your first case is equivalent therefore to computing
>>> [1] + [2,3]

We agre that this silent conversion to object arrays is confusing, and we're thinking of disabling it in the future (see #5353)

**Comment by axch** [comment] 2017-02-17 18:51
OK.

**Comment by seberg** [comment] 2021-11-06 04:35
This gives a pretty clear deprecation warning now for "ragged nested sequences" being converted.  Probably should be converted to an error soon (which would make it more easy to understand).

But I think we can close the issue, since the main thing left to do is go through with the deprecation.

**Closed by seberg** 2021-11-06 04:35 UTC
