### ISSUE TITLE
Provide wheels on PyPI for aarch64

### ISSUE THREAD

**Issue by odidev** [numpy/numpy#15607] opened 2020-02-19 12:04 UTC
Summary
----------
Installing numpy on aarch64 via pip using command "pip3 install numpy" tries to build wheel from source code

Problem description
----------------------
Numpy don't have wheel for aarch64 on PyPI repository. So, while installing numpy via pip on aarch64, pip builds wheel for same resulting in it takes more time to install numpy. Making wheel available for aarch64 will benefit aarch64 users by minimizing numpy installation time.

Expected Output
-------------------
Pip should be able to download numpy wheel from PyPI repository rather than building it from source code.

@numpy-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make numpy wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by mattip** [comment] 2020-02-19 16:59
Duplicate of gh-14886. Closing. Please do not see this as a rejection of your offer, there are plenty of open issues and PRs that could use your help

**Closed by mattip** 2020-02-19 16:59 UTC
