### ISSUE TITLE
UnicodeDecodeError on Windows

### ISSUE THREAD

**Issue by alimanfoo** [numpy/numpy#10015] opened 2017-11-13 01:12 UTC
I get the following behaviour on Windows only, using numpy 1.13.1 installed via conda:

```
>>> import numpy as np
>>> v = np.array('xxx', dtype='U3')[()]
>>> v
'xxx'
>>> a = np.empty(10, dtype='U3')
>>> a[:] = v
>>> a[0] == v
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)
```

I don't understand what's happening here but this seemed surprising to me. Default locale on the Windows machine is cp1252 if that helps to know.

xref https://github.com/alimanfoo/zarr/pull/172

**Comment by eric-wieser** [comment] 2017-11-13 01:15
Yeah, I've seen this before. More revealing:

```
>>> a = np.zeros(10, dtype='U3')
>>> a[:] = np.unicode_('xxx')
>>> a.view(np.void)
array([[120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63],
       [120   0 120   0 120   0   0   0  64  47 105 -63]],
      dtype='|V12')
```

Notice that:
* `x` is using up 2 bytes, not 4
* The garbage at the end

**Comment by eric-wieser** [comment] 2017-11-13 01:19
Found it.

Duplicate of #3258

**Closed by eric-wieser** 2017-11-13 01:19 UTC
