### ISSUE TITLE
Import Numpy on Raspberry Pi3B+

### ISSUE THREAD

**Issue by wise-dachshund** [numpy/numpy#14571] opened 2019-09-21 20:59 UTC
Impossible to import numpy

### Reproducing code example:

import numpy 

### Error message:

Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.7.4/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/pi/.pyenv/versions/3.7.4/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/pi/.pyenv/versions/3.7.4/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.pyenv/versions/3.7.4/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/.pyenv/versions/3.7.4/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/pi/.pyenv/versions/3.7.4/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

### Numpy/Python version information:

Python 3.7.4
numpy-1.17.2

### Additional details
Python was installed through pyenv
numpy was installed through pip 
Raspbian GNU/Linux 9 (stretch)
The only other version of Python installed is 2.7.13

**Comment by charris** [comment] 2019-09-21 21:16
`sudo apt-get install libatlas3-base`

**Comment by seberg** [comment] 2019-09-21 22:05
Please do what Chuck suggested/look at gh-14455. Closing as duplicate of gh-14553 (although we can probably close that as well really)

**Closed by seberg** 2019-09-21 22:05 UTC

**Comment by wise-dachshund** [comment] 2019-09-22 07:46
It worked, thanks!
