### ISSUE TITLE
Segfault calling `np.dtype` on bad object due to recursion

### ISSUE THREAD

**Issue by jcrist** [numpy/numpy#12751] opened 2019-01-15 15:10 UTC
This came up in Dask (https://github.com/dask/dask/pull/4387). We have an object (`dask.delayed.Delayed`) that duck-types method/attribute access to build a graph from user code. Unfortunately this means that when `np.dtype` tries to get the `dtype` attribute it succeeds but doesn't return a valid dtype (it returns another delayed object). This leads to recursion and eventually a segfault.

I'm able to reproduce his without dask as follows:

```python
import numpy as np

class ShouldHaveNoDtype(object):
    """This class happens to have a dtype attribute, but it doesn't actually
    meet the interface"""
    @property
    def dtype(self):
        """Has the attribute, but doesn't return a dtype, leading to recursion"""
        return self


x = ShouldHaveNoDtype()
np.dtype(x)
```

**Comment by seberg** [comment] 2019-01-15 21:07
Just to note, duplicate of gh-3614, that is very old, but we may want to close one.

**Comment by jcrist** [comment] 2019-01-15 21:25
Ah, I did a search but didn't find anything. Not sure if you want to close this one or the older one, but this is indeed a duplicate.

**Comment by seberg** [comment] 2022-11-19 15:44
My PR above fixed this, we just forgot to close the issue.

**Closed by seberg** 2022-11-19 15:44 UTC
