### ISSUE TITLE
ENH: add `mode()` and `nanmode()` to compute modes along an axis

### ISSUE THREAD

**Issue by gabriel-libardi** [numpy/numpy#22273] opened 2022-09-16 13:16 UTC
### Proposed new feature or change:

Currently we can use `median()` and `nanmedian()` to calculate the median of an array along an axis, and we can compute other basic statistical metrics similarly. However, there are no methods to calculate the modes of an array directly.

I would suggest adding the method `mode()`, which returns an array of modes, and `nanmode()`, which does the same but ignoring `NaN`s. They would work in the same fashion as `median()` and `nanmedian()`, and I reckon that they would be useful even to applications that are not related to statistics.

I would appreciate any suggestions or constructive criticism

**Comment by pavani34** [comment] 2022-09-16 19:45
I believe a similar feature is available in scipy.stats. I am pasting the documentation link [(https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html)]

**Comment by rossbar** [comment] 2022-09-16 23:06
Thanks for the proposal @gabriel-libardi - this has been brought up before. See #21363 for further discussion; I will close this as duplicate of that issue.

**Closed by rossbar** 2022-09-16 23:06 UTC
