### ISSUE TITLE
bug from np.poly1d  

### ISSUE THREAD

**Issue by ddk1246** [numpy/numpy#16470] opened 2020-06-01 18:25 UTC
### Reproducing code example:

```python
import numpy as np
import math

def lagrange(x, w):
    print('INla')
    p = 0.0
    for j in range(len(x)):
        pt = w[j]
        print('pt=',pt)
        for k in range(len(x)):
            if k == j:
                continue
            fac = x[j] - x[k]
            print('pt_frist=',pt)
            m=np.poly1d([1.0, -x[k]]) / fac
            pt *= m
            print( 'fun=',m,'pt=',pt)
        p += pt
        print('p=',p)
    return p


x2=[5*math.cos((21-2*k)/22*np.pi) for k in range(0,11,1)]
x3=[5*np.cos((21-2*k)/22*np.pi) for k in range(0,11,1)]

y2=[1/(1+i*i) for i in x2]
y3=[1/(1+i*i) for i in x3]

a=lagrange(x2,y2)
b=lagrange(x3,y3)
print(a,b,a==b)
```

### Error message: 
As mentioned above using the math library does not yield the same results as the numpy library, the error occurs in numpy

### Numpy/Python version information:
python 3.7.4
numpy 1.19

**Comment by rossbar** [comment] 2020-06-03 23:12
There is a lot to decode in your example - any chance you can pare down to a more minimal reproducing example? That would reduce the burden for others to understand what's going on here.

**Comment by ewmoore** [comment] 2020-06-04 01:14
What is happening here is that multiplication between a python float and a `np.poly1d`  results in a `np.poly1d`. If you instead have a `np.float64` scalar you get an `np.array`.   Since the `pt` variable is then an array and not a `np.poly1d`  further multiplications produce element-wise multiplication and not polynomial multiplication.  This happens AFAICT because `np.poly1d` defines `__array__`.

```
In [1]: import numpy as np

In [2]: py = 1.0

In [3]: npy = np.float64(1.0)

In [4]: p = np.poly1d([1., 2., 3.])

In [5]: py * p
Out[5]: poly1d([1., 2., 3.])

In [6]: npy * p
Out[6]: array([1., 2., 3.])

In [7]: (npy * p) * p
Out[7]: array([1., 4., 9.])

In [8]: (npy * p) * p
Out[8]: array([1., 4., 9.])

In [9]: (py * p) * p
Out[9]: poly1d([ 1.,  4., 10., 12.,  9.])
```

The posted code is made to function by changing `pt *= m` to `pt = np.polymul(pt, m)`.  Alternatively using `np.polynomial.Polynomial`s should also work
```
In [10]: poly = np.polynomial.Polynomial([3., 2., 1.])

In [11]: py * poly
Out[11]: 
Polynomial([3., 2., 1.], domain=[-1.,  1.], window=[-1.,  1.])

In [12]: npy * poly
Out[12]: 
Polynomial([3., 2., 1.], domain=[-1.,  1.], window=[-1.,  1.])

In [13]: py *= poly

In [14]: py
Out[14]: 
Polynomial([3., 2., 1.], domain=[-1.,  1.], window=[-1.,  1.])

In [15]: npy *= poly

In [16]: npy
Out[16]: 
Polynomial([3., 2., 1.], domain=[-1.,  1.], window=[-1.,  1.])
```

**Comment by ewmoore** [comment] 2020-06-04 01:22
I don't know that there is really a bug here.  This defect is by no means new and likely can't be corrected without breaking existing code.  Related seem to be quite old #2651, #1429 and I guess the nearly new #15779.

**Comment by rossbar** [comment] 2020-06-04 16:48
I'm going to go ahead and close this as the underlying cause has been reported more clearly in other issues. Thanks @ewmoore for the detailed explanation.

**Closed by rossbar** 2020-06-04 16:48 UTC
