### ISSUE TITLE
manylinux2010 runs slow and hangs while manylinux1 runs fine

### ISSUE THREAD

**Issue by jrj-d** [numpy/numpy#18408] opened 2021-02-14 14:25 UTC
### The issue

I can reproduce this issue, but not in a self-contained way. I'll try to provide as many information as possible here.

I'm working on a Spark application that uses Python and `numpy` in user-defined functions.

In a nutshell, the issue is:
* If I install `numpy` from `numpy-1.20.1-cp37-cp37m-manylinux2010_x86_64.whl`, at some point the Spark application gets stuck while running `numpy` code because it is super slow.
* If I run the exact same Spark application with `numpy` from `numpy-1.20.1-cp37-cp37m-manylinux1_x86_64.whl`, it works just fine.

Summary of the context:
* Python and `numpy` run in a Docker container running Debian 10 (Buster).
* I install `numpy` with `manylinux1` by setting `pip` version to `1.18`. I install `numpy` with `manylinux2010` by setting `pip` version to `20.3`.

Some investigations I made:
* I've reproduced the issue with a Python installed from `apt-get install python3` and with a Python installed from `conda`. So it seems independent of the Python distribution used.
* when the Spark application gets stuck in the `manylinux2010` case, there actually is some Python code running. But it's very slow (around 100x slower than with `manylinux1`). Here's the part that's being run:
```python
def compute_gaussian_symmetric_kl_divergence(mean1, cov1, mean2, cov2):
    try:
        inv_cov1 = np.linalg.inv(cov1)
        inv_cov2 = np.linalg.inv(cov2)
    except Exception:
        print(f"Distance: return None!")
        return None
    trace_formula = "ij,ji"
    output = np.einsum(trace_formula, inv_cov1, cov2) + np.einsum(trace_formula, inv_cov2, cov1)
    mean_diff = np.array(mean2) - np.array(mean1)
    output += mean_diff.dot((inv_cov1 + inv_cov2).dot(mean_diff))
    test = float(output * 0.5 - inv_cov1.shape[0])
    print(f"Distance: {test}")
    return test
```
* I wrote a Python script that does not involve Spark and that times the code above. I wasn't able to prove a performance drop from `manylinux1` to `manylinux2010`.

I know that the difference between `manylinux1` and `manylinux2010` is in packaging the non-Python dependencies.
**Are there some libraries in the OS that I should list and print here to shed light on the problem?**

I provide more details below about the versions of Python, `pip` and `numpy`.

### Detailed versions for the case that runs fast (`manylinux1`)

```bash
$ python3 --version
Python 3.7.3

$ pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

$ pip3 install numpy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/65/b9/0b02ffd2689cbfa5d1da09a59378b626768386add3b654718d43d97e0ef1/numpy-1.20.1-cp37-cp37m-manylinux1_x86_64.whl (13.7MB)
    100% |████████████████████████████████| 13.8MB 30kB/s
Installing collected packages: numpy
  The scripts f2py, f2py3 and f2py3.7 are installed in '/home/sparkuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.20.1

$ pip3 freeze
asn1crypto==0.24.0
cryptography==2.6.1
entrypoints==0.3
keyring==17.1.1
keyrings.alt==3.1.1
numpy==1.20.1
pycrypto==2.6.1
PyGObject==3.30.4
pyxdg==0.25
SecretStorage==2.3.1
six==1.12.0
```

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.1 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
```

### Detailed versions for the case that runs slowly / hangs (`manylinux2010`)

```bash
$ python3 --version
Python 3.7.3

$ pip3 install pip==20.3
Collecting pip==20.3
  Downloading https://files.pythonhosted.org/packages/55/73/bce122d1ed0217b3c1a3439ab16dfa94bbeabd0d31755fcf907493abf39b/pip-20.3-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 352kB/s
Installing collected packages: pip
Successfully installed pip-20.3

$ pip3 --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 20.3 from /home/sparkuser/.local/lib/python3.7/site-packages/pip (python 3.7)

$ pip3 install numpy
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting numpy
  Downloading numpy-1.20.1-cp37-cp37m-manylinux2010_x86_64.whl (15.3 MB)
     |████████████████████████████████| 15.3 MB 4.4 MB/s
Installing collected packages: numpy
  WARNING: The scripts f2py, f2py3 and f2py3.7 are installed in '/home/sparkuser/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.20.1
WARNING: You are using pip version 20.3; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

$ pip3 freeze
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
asn1crypto==0.24.0
cryptography==2.6.1
entrypoints==0.3
keyring==17.1.1
keyrings.alt==3.1.1
numpy==1.20.1
pycrypto==2.6.1
PyGObject==3.30.4
pyxdg==0.25
SecretStorage==2.3.1
six==1.12.0
```

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.20.1 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
```

**Comment by mattip** [comment] 2021-02-14 15:41
Thanks for the report. 

Both the wheels should be using the same OpenBLAS library underneath. The difference may be due to the different compiler used in the two wheels, which would influence any new SIMD code, although your use of einsum should be a simple transpose. The manylinux1 wheel dispatches on
```
['SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2']
```
while the manylinux2010 wheel dispatches on
```
['SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', \
 'AVX512_KNL', 'AVX512_KNM', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL']
```
What is the shape of `(mean1, cov1, mean2, cov2)`? Can you tell us which of the possible CPU features are being used in the manylinux2010 wheel via
```
import numpy
print([k for k,v in numpy.core._multiarray_umath.__cpu_features__.items() if v is True])
```

Perhaps this machine is running under emulation? We have seen before where docker/qemu can report wrong features. Assuming the machine has `AVX512F` and higher features, what happens if you limit the used features to the manylinux1 set with `export NPY_DISABLE_CPU_FEATURES=AVX512F`

**Comment by jrj-d** [comment] 2021-02-14 18:33
Thanks for the fast and detailed reply! That's really great.

Here are the sizes of the vectors and matrices at play:
```
mean1: (25,)
cov1: (25, 25)
mean2: (25,)
cov2: (25, 25)
```
Those sizes are fixed.

I've used the piece of code you shared to print the CPU features being used:
`manylinux1`:
```
['MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512VL', 'AVX512BW', 'AVX512DQ', 'AVX512_SKX']
```
`manylinux2010`:
```
['MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512VL', 'AVX512BW', 'AVX512DQ', 'AVX512_SKX']
```
`manylinux2010` with `export NPY_DISABLE_CPU_FEATURES=AVX512F`:
```
['MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512CD', 'AVX512VL', 'AVX512BW', 'AVX512DQ', 'AVX512_SKX']
```

Note that the computations were still slow enough to cause the Spark app to hang with `NPY_DISABLE_CPU_FEATURES=AVX512F`. Should I try to disable more features?

> Perhaps this machine is running under emulation? We have seen before where docker/qemu can report wrong features.
I don't think that container runs under emulation although I'm not sure. It's a Docker container running on EKS on a `r5.2xlarge` instance.

**Comment by zoj613** [comment] 2021-02-14 19:00
Interesting. I have a similar issue because my code is considerably slower after upgrading to numpy 1.20.1. It runs much faster on 1.20.0 or less. I didn't open an issue because I couldn't figure out the real cause and my code is specialized so I had no idea how to reproduce it since its an MCMC chain.

**Comment by charris** [comment] 2021-02-14 19:16
> It runs much faster on 1.20.0 or less

Not much changed. Does anything look suspicious? What platform? Were you using 1.20.0 or a release candidate?

* `#18306 <https://github.com/numpy/numpy/pull/18306>`__: MAINT: Add missing placeholder annotations
* `#18310 <https://github.com/numpy/numpy/pull/18310>`__: BUG: Fix typo in ``numpy.__init__.py``
* `#18326 <https://github.com/numpy/numpy/pull/18326>`__: BUG: don't mutate list of fake libraries while iterating over...
* `#18327 <https://github.com/numpy/numpy/pull/18327>`__: MAINT: gracefully shuffle memoryviews
* `#18328 <https://github.com/numpy/numpy/pull/18328>`__: BUG: Use C linkage for random distributions
* `#18336 <https://github.com/numpy/numpy/pull/18336>`__: CI: fix when GitHub Actions builds trigger, and allow ci skips
* `#18337 <https://github.com/numpy/numpy/pull/18337>`__: BUG: Allow unmodified use of isclose, allclose, etc. with timedelta
* `#18345 <https://github.com/numpy/numpy/pull/18345>`__: BUG: Allow pickling all relevant DType types/classes
* `#18351 <https://github.com/numpy/numpy/pull/18351>`__: BUG: Fix missing signed_char dependency. Closes #18335.
* `#18352 <https://github.com/numpy/numpy/pull/18352>`__: DOC: Change license date 2020 -> 2021
* `#18353 <https://github.com/numpy/numpy/pull/18353>`__: CI: CircleCI seems to occasionally time out, increase the limit
* `#18354 <https://github.com/numpy/numpy/pull/18354>`__: BUG: Fix f2py bugs when wrapping F90 subroutines.
* `#18356 <https://github.com/numpy/numpy/pull/18356>`__: MAINT: crackfortran regex simplify
* `#18357 <https://github.com/numpy/numpy/pull/18357>`__: BUG: threads.h existence test requires GLIBC > 2.12.
* `#18359 <https://github.com/numpy/numpy/pull/18359>`__: REL: Prepare for the NumPy 1.20.1 release.

**Comment by zoj613** [comment] 2021-02-14 20:16
> > It runs much faster on 1.20.0 or less
> 
> Not much changed. Does anything look suspicious? What platform? Were you using 1.20.0 or a release candidate?
> 
>     * `#18306 <https://github.com/numpy/numpy/pull/18306>`__: MAINT: Add missing placeholder annotations
> 
>     * `#18310 <https://github.com/numpy/numpy/pull/18310>`__: BUG: Fix typo in `numpy.__init__.py`
> 
>     * `#18326 <https://github.com/numpy/numpy/pull/18326>`__: BUG: don't mutate list of fake libraries while iterating over...
> 
>     * `#18327 <https://github.com/numpy/numpy/pull/18327>`__: MAINT: gracefully shuffle memoryviews
> 
>     * `#18328 <https://github.com/numpy/numpy/pull/18328>`__: BUG: Use C linkage for random distributions
> 
>     * `#18336 <https://github.com/numpy/numpy/pull/18336>`__: CI: fix when GitHub Actions builds trigger, and allow ci skips
> 
>     * `#18337 <https://github.com/numpy/numpy/pull/18337>`__: BUG: Allow unmodified use of isclose, allclose, etc. with timedelta
> 
>     * `#18345 <https://github.com/numpy/numpy/pull/18345>`__: BUG: Allow pickling all relevant DType types/classes
> 
>     * `#18351 <https://github.com/numpy/numpy/pull/18351>`__: BUG: Fix missing signed_char dependency. Closes #18335.
> 
>     * `#18352 <https://github.com/numpy/numpy/pull/18352>`__: DOC: Change license date 2020 -> 2021
> 
>     * `#18353 <https://github.com/numpy/numpy/pull/18353>`__: CI: CircleCI seems to occasionally time out, increase the limit
> 
>     * `#18354 <https://github.com/numpy/numpy/pull/18354>`__: BUG: Fix f2py bugs when wrapping F90 subroutines.
> 
>     * `#18356 <https://github.com/numpy/numpy/pull/18356>`__: MAINT: crackfortran regex simplify
> 
>     * `#18357 <https://github.com/numpy/numpy/pull/18357>`__: BUG: threads.h existence test requires GLIBC > 2.12.
> 
>     * `#18359 <https://github.com/numpy/numpy/pull/18359>`__: REL: Prepare for the NumPy 1.20.1 release.

My main suspicion is the PR dealing with shuffling of memoryviews, particularly this commit:
https://github.com/numpy/numpy/pull/18282/commits/044550d603b0d7bbe201d703354dd4857bb3606d
it adds:
```python
        if isinstance(x, memoryview):
            x = np.asarray(x)
```
I can image this would a fair bit of overhead on repeated calls to the shuffle function for the same input. My program passes around a lot of memoryviews/arrays using numpy and scipy. I wonder how many functions in scipy make use of numpy's `shuffle` internally? Since my program runs the same code for upwards of 100K iterations per MCMC chain, a function using shuffle would slow things down since the same memoryview input would be converted to an array every repeated call. I dunno though, im just taking a wild guess because I do not see any other potential culprit.

**Comment by mattip** [comment] 2021-02-14 21:18
@seiko2plus any thoughts about 1.19.5 vs 1.20 with those CPU features?

@zoj613 I fear we are going to have two threads discussing different issues here. Could you open a new issue?

**Comment by zoj613** [comment] 2021-02-14 21:18
Interestingly, the loss in speed vanishes if I restrict the sampler to 1 chain (aka one processor via `joblib`). But if I use 2 chains (1 chain per processor), then on numpy 1.20.1, I get slow speeds.

**Comment by mattip** [comment] 2021-02-14 21:33
@zoj613 thanks.

@jrj-d just to make sure they are separate issues, are you using any multiprocessing or threading? 

The way the cpu features work is there is a "maximum" set of features the compiled NumPy will "dispatch on". The features **detected** will not change between the two wheels, but because the set that NumPy dispatches on changes, behavour may change. So if you could set `NPY_DISABLE_CPU_FEATURES` to disable anything beyond `AVX2` that would be cool. I think this might do the trick:
```
 NPY_DISABLE_CPU_FEATURES=AVX512F,AVX512CD,AVX512VL,AVX512BW,AVX512DQ,AVX512_SKX
```

Another question: on both versions the inputs to the function `mean1`, `cov1`, `mean2`, `cov2` have the same layout (strides), right?

**Comment by seiko2plus** [comment] 2021-02-15 02:26
@mattip,
>  any thoughts about 1.19.5 vs 1.20 with those CPU features?

I don't think it's related to the SIMD changes, accroding to "the part that's being run", we have:

| Number of calls | operations  |
| ---             | ----------- |
| 2               | linalg.inv (OpenBlas?) |
| 2               | dot    (OpenBlas ?)
| 2               | einsum (SIMD/Scalar baseline) |
| 2               | add    (SIMD/Scalar dispatch) |
| 2               | sub    (SIMD/Scalar dispatch) |
| 1               | mul    (SIMD/Scalar dispatch) |
| 3               | possible extra copies/conversions |

"100x" is a huge performance regression for `6` calls of arithmetic operations + einsum,

>  So if you could set NPY_DISABLE_CPU_FEATURES to disable anything beyond AVX2 that would be cool. 

It would be better to disable all dispatched features instead :

```Bash
export NPY_DISABLE_CPU_FEATURES=`python -c "from numpy.core import _multiarray_umath as npu; print(' '.join([x for x in npu.__cpu_dispatch__ if npu.__cpu_features__[x]]))"`
```

**Comment by jrj-d** [comment] 2021-02-15 09:07
> @jrj-d just to make sure they are separate issues, are you using any multiprocessing or threading?
The Python code itself is not using multiprocessing or threading, but Spark runs eight processes of this same code, one for each core of the `r5.2xlarge` instance.

> Another question: on both versions the inputs to the function mean1, cov1, mean2, cov2 have the same layout (strides), right?
The 4 objects have the exact same size in both cases (`(25,)` and `(25,25)`). Does this mean they have the same stride? Can I test this?

I'll disable CPU features in the two ways you've mentioned @mattip and @seiko2plus and report the results of the two runs here. Thanks for your help!

**Comment by mattip** [comment] 2021-02-15 09:40
> Can I test this?

The strides of `mean1` can be printed with `print(mean1.strides)`. The numbers show the number of bytes skipped when indexing along each axis. "C-order" has the strides from left-to-right in decreasing order, "F-order" has them increasing. Transposing an ndarray usually creates a view to the original data with different strides, so indexing will retrieve different values.

**Comment by seberg** [comment] 2021-02-25 00:39
Inputs with shape `(25,)` and `(25, 25)` are *very* small, which would point to overheads as opposed to any SIMD itself?  It could be the openblas with some threading differences? In that case trying `OPENBLAS_NUM_THREADS=1` could be worth a shot.

If one of the cases lead to unaligned memory for some reason `arr.flags.aligned` being `False`, that could explain pretty massive overheads, but not sure about 100x (factor of 2-3 I would not be surprised).

I am trying to think how a different `glibc` could lead to strange results: if `NaNs` are involved and (incorrectly) warned in one case, it might also lead to a huge differenc (could be checked with `with np.errstate(all="raise"):`.  That seems like a very long shot, but if it is not OpenBLAS+threading that is causing it, it at least should be capable of causing a massive slowdown for very small arrays.

**Comment by bashtage** [comment] 2022-01-14 14:55
@mattip This might also have be resolved with time and incremental changes, esp the manylinux2014 packaging variant.

**Comment by mattip** [comment] 2022-01-16 14:48
@jrj-d could you update the issue with results for the recent 1.22 which uses manylinux2014?

**Comment by mattip** [comment] 2022-05-07 17:17
@jrj-d is there any new information? If not, I think we should close this.

**Comment by rgommers** [comment] 2022-11-21 09:59
Looks like we're all good here. No more follow-up for 6 months, so closing. Thanks for the interesting discussion everyone.

**Closed by rgommers** 2022-11-21 09:59 UTC
Labels: 57 - Close?, 32 - Installation
