### ISSUE TITLE
BUG: Incorrect np.add corner case in fresh session

### ISSUE THREAD

**Issue by jburgy** [numpy/numpy#21559] opened 2022-05-21 03:11 UTC
### Describe the issue:

In a very specific context, numpy incorrectly asserts that `0 + 1 == 2`!

### Reproduce the code example:

```python
import numpy as np

# only works in fresh interpreter, possibly uninitialized variable?
assert np.add(0., 1, where=False) == 2.
assert np.add(0., 1, where=False) == 1.
assert np.add(0., 1, where=False) == 1.
```

### NumPy/Python version information:

    1.21.2 3.9.5 (default, Jun 26 2021, 07:40:15) 
    [GCC 6.3.0 20170516]

Then I upgraded numpy to

    1.22.4 3.9.5 (default, Jun 26 2021, 07:40:15) 
    [GCC 6.3.0 20170516]

and the problem persists.

**Comment by charris** [comment] 2022-05-21 03:23
I think the behavior is correct, but still a bit unexpected. Maybe needs an example.

 >   Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uninitialized.

**Comment by jburgy** [comment] 2022-05-21 11:05
How does that statement square with
>This condition is broadcast over the input. At locations where the condition is True, the out array will be set to the ufunc result. Elsewhere, the out array will retain its original value.

**Comment by seberg** [comment] 2022-05-22 18:44
Closing as a duplicate of gh-17192 which discusses whether we should add a warning here.

> How does that statement square with

You are not providing an `out` array, so NumPy uses a new uninitialized one.

**Closed by seberg** 2022-05-22 18:44 UTC
Labels: 33 - Question

**Comment by charris** [comment] 2022-05-22 20:16
> How does that statement square with

False broadcasts to all the output values, so none of the accidental values in the default allocated output are initialized.
