### ISSUE TITLE
BUG: Memory Overflow in np.histogram with bins="auto"

### ISSUE THREAD

**Issue by fingoldo** [numpy/numpy#23564] opened 2023-04-10 00:53 UTC
### Describe the issue:

Something is wrong with the "auto" option.

### Reproduce the code example:

```python
import numpy as np

hist, bin_edges = np.histogram(
    np.array(
        [
            -4.24264069e00,
            -5.55111512e-17,
            3.81837662e01,
            1.77635684e-15,
            -5.65685425e00,
            3.55271368e-15,
            -1.97989899e01,
            0.00000000e00,
            -1.27279221e01,
            4.24264069e00,
            1.41421356e01,
            -1.83847763e01,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            -5.55111512e-17,
            3.53553391e-01,
            9.54594155e00,
            -3.53553391e-01,
            -9.19238816e00,
            3.53553391e-01,
            -3.53553391e-01,
            2.82842712e00,
            -7.21644966e-16,
            -3.18198052e00,
            -5.55111512e-17,
            -5.55111512e-17,
        ]
    ),
    bins="auto",
    density=True,
)
```

### Error message:

```shell
~\AppData\Roaming\Python\Python39\site-packages\numpy\core\function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    137 
    138     delta = stop - start
--> 139     y = _nx.arange(0, num, dtype=dt).reshape((-1,) + (1,) * ndim(delta))
    140     # In-place multiplication y *= delta/div is faster, but prevents the multiplicant
    141     # from overriding what class is produced, and thus prevents, e.g. use of Quantities,

MemoryError: Unable to allocate 3.81 EiB for an array with shape (549572839412124544,) and data type float64
```

### Runtime information:

1.24.2
3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]

### Context for the issue:

A lot of people use numpy for calculation histograms, I think. bins="auto" is very convenient as it eliminates the need to try multiple times with different bins sizes, therefore, it would be good to fix this.

**Comment by WarrenWeckesser** [comment] 2023-04-10 01:08
Thanks for reporting the issue, @fingoldo.  This looks like a duplicate of https://github.com/numpy/numpy/issues/11879 and https://github.com/numpy/numpy/issues/10297, so I'm closing the issue.  Add your comments and example to the existing issue to draw more attention to it, and perhaps renew discussion of how to fix it.

**Closed by WarrenWeckesser** 2023-04-10 01:08 UTC
Labels: 00 - Bug
