### ISSUE TITLE
`pip install numpy` is trying to install 1.20rc1, breaking due to python 3.6.8 on RHEL 7.8

### ISSUE THREAD

**Issue by datakid** [numpy/numpy#17909] opened 2020-12-03 23:42 UTC
I was just trying to install [websockify](https://github.com/novnc/websockify) onto a fresh, and it has a numpy dependency. Which was broken by the rc being pulled. Shouldn't the 1.19.4 release remain as the "latest" until version 1.20 becomes a stable release?

**Comment by seberg** [comment] 2020-12-04 00:00
I just tried and it seems perfectly fine, unless it is system dependend. Note that prereleases are uploaded to PyPI, but pip ingores them unless you pass `--pre`, is there any chance that you got a `--pre` into the pip install for some reason?

**Comment by datakid** [comment] 2020-12-04 00:18
I'm not completely `setup.py` conversant, but [it doesn't look like it](https://github.com/novnc/websockify/blob/4c2edaabc266b0e401553e2c1353a4d2d77637d1/setup.py#L30)

I'm just running `python3 setup.py install`

**Comment by charris** [comment] 2020-12-04 00:31
1.20.x doesn't support Python3.6, so this is even more curious, it should raise an error because of these lines in `setup.py`. 
```
if sys.version_info[:2] < (3, 7):
    raise RuntimeError("Python version >= 3.7 required.")
```

**Comment by datakid** [comment] 2020-12-04 00:37
Sorry, yes that is the error I see. But because it's wrapped in the websockify install, I saw it as broken. My bug report was sloppy and I apologise:
```
Extracting websockify-0.9.0-py3.6.egg to /usr/local/lib/python3.6/site-packages                                                                                         
Adding websockify 0.9.0 to easy-install.pth file                                                                                                                        
Installing websockify script to /usr/local/bin                                                                                                                          
                                                                                                                                                                        
Installed /usr/local/lib/python3.6/site-packages/websockify-0.9.0-py3.6.egg                                                                                             
Processing dependencies for websockify==0.9.0 
Searching for numpy                                                                                                                                                     
Reading https://pypi.org/simple/numpy/                                                                                                                                  
Downloading https://files.pythonhosted.org/packages/81/46/ecc1ea3e5819eb0d83306a8f468693785c94ed5467fcbb6f2529abf0102f/numpy-1.20.0rc1.zip#sha256=98f4e754f1c3db7ca53e53
b1ef6474703b167af75f3784f99b1fe4dd936ea77f                                                                                                                              
Best match: numpy 1.20.0rc1                                                                                                                                             
Processing numpy-1.20.0rc1.zip                                                                                                                                          
Writing /tmp/easy_install-g8wv90c4/numpy-1.20.0rc1/setup.cfg                                                                                                            
Running numpy-1.20.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-g8wv90c4/numpy-1.20.0rc1/egg-dist-tmp-giaczohq                                               
Traceback (most recent call last):                                                                                                                                      
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules                                                                              
    yield saved                                                                                                                                                         
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context                                                                             
    yield                                                                                                                                                               
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup                                                                                 
    _execfile(setup_script, ns)                                                                                                                                         
  File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile                                                                                  
    exec(code, globals, locals)                                                                                                                                         
  File "/tmp/easy_install-g8wv90c4/numpy-1.20.0rc1/setup.py", line 30, in <module>                                                                                      
    install_requires=['numpy'],
RuntimeError: Python version >= 3.7 required.
```

**Comment by charris** [comment] 2020-12-04 00:51
I notice that the directory pointed to contains rc versions for all the releases, so I suspect that whatever software is doing the installing is messing up. Doesn't look like pip, however.  Maybe you should install yourself using `python3 -mpip`. Might check the pip version just in case it is very old, probably could use an update.

**Comment by seberg** [comment] 2020-12-04 00:58
For what its worth, I just tried on an old ubuntu machine with Python 3.6.9 and pip 9.0.1 and it picks up the 1.19.4 wheel fine.

**Comment by Benjamin15** [comment] 2020-12-04 01:49
Got the same issue with fastparquet (python 3.6.8, pip 20.2.2)
command used: python -m pip install -r requirement.txt

**Comment by Benjamin15** [comment] 2020-12-04 02:24
I just test to make the numpy installation before install fastparquet. It works fine. It should resolve your issue @datakid 
However, it's issue for CI pipeline.

**Comment by seberg** [comment] 2020-12-04 03:09
@Benjamin15 can you share the exact `requirements.txt`, etc. I admit, I have no clue, but it seems like *something* is wrong (probably not in NumPy itself), maybe even a (recent?) pip bug?  And right now I feel we can't pinpoint it yet.

**Comment by duanqn** [comment] 2020-12-04 04:09
I just encountered the same issue. My `requirements.txt` has the following line:
`numpy`
(I'm hiding unrelated lines)

**Comment by Benjamin15** [comment] 2020-12-04 05:11
@duanqn I don't think the issue was your numpy. Can you share your log ? I'm curious to see which package is installed when you get the issue.
@seberg My requirement.txt only contains numpy and fastparquet ( i try it in a test project). 
In the setup.py of fastparquet, the numpy is used. I'm not sure how it works in this case. Does it take the numpy version that the user writes in the requirement.txt, or the  one that is write on fastparquet.
In fastparquet, it's numpy >= 1.11.
On my side, it's numpy ==1.18.1

In each case, i think the issue provide from the setup.py script, because fastparquet use numpy in the setup.py. But when I checked the one of websockify, i don't see anything strange. They just pass numpy as install_requires, but I can't believe that's the problem



My requirement.txt:
```
numpy==1.18.1
fastparquet==0.4.1
```

I test with other version of fastparquet, always get the same issue (version tried: 0.3.2, 0.4.0)

**Comment by duanqn** [comment] 2020-12-04 05:21
I also have opencv-python==4.2.0.34 in my `requirements.txt`. But I don't think it's related since I never had a problem before the new version of numpy released.

@Benjamin15 
Some lines from my log are attached below
```
#19 6.441 Searching for numpy
#19 6.441 Reading https://pypi.python.org/simple/numpy/
#19 7.933 Downloading https://files.pythonhosted.org/packages/81/46/ecc1ea3e5819eb0d83306a8f468693785c94ed5467fcbb6f2529abf0102f/numpy-1.20.0rc1.zip#sha256=98f4e754f1c3db7ca53e53b1ef6474703b167af75f3784f99b1fe4dd936ea77f
#19 8.183 Best match: numpy 1.20.0rc1
#19 8.183 Processing numpy-1.20.0rc1.zip
#19 8.667 Writing /tmp/easy_install-vm_cmg5u/numpy-1.20.0rc1/setup.cfg
#19 8.668 Running numpy-1.20.0rc1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vm_cmg5u/numpy-1.20.0rc1/egg-dist-tmp-k1p_8w5v
#19 8.799 Traceback (most recent call last):
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
#19 8.799     yield saved
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
#19 8.799     yield
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
#19 8.799     _execfile(setup_script, ns)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
#19 8.799     exec(code, globals, locals)
#19 8.799   File "/tmp/easy_install-vm_cmg5u/numpy-1.20.0rc1/setup.py", line 30, in <module>
#19 8.799     'opencv-python==4.2.0.34',
#19 8.799 RuntimeError: Python version >= 3.7 required.
#19 8.799
#19 8.799 During handling of the above exception, another exception occurred:
#19 8.799
#19 8.799 Traceback (most recent call last):
#19 8.799   File "setup.py", line 35, in <module>
#19 8.799     'twisted'
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
#19 8.799     return distutils.core.setup(**attrs)
#19 8.799   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
#19 8.799     dist.run_commands()
#19 8.799   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
#19 8.799     self.run_command(cmd)
#19 8.799   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
#19 8.799     cmd_obj.run()
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
#19 8.799     self.do_egg_install()
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
#19 8.799     cmd.run()
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 437, in run
#19 8.799     self.easy_install(spec, not self.no_deps)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
#19 8.799     return self.install_item(None, spec, tmpdir, deps, True)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
#19 8.799     self.process_distribution(spec, dist, deps)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
#19 8.799     [requirement], self.local_index, self.easy_install
#19 8.799   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 774, in resolve
#19 8.799     replace_conflicting=replace_conflicting
#19 8.799   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
#19 8.799     return self.obtain(req, installer)
#19 8.799   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
#19 8.799     return installer(requirement)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
#19 8.799     return self.install_item(spec, dist.location, tmpdir, deps)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
#19 8.799     dists = self.install_eggs(spec, download, tmpdir)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
#19 8.799     return self.build_and_install(setup_script, setup_base)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
#19 8.799     self.run_setup(setup_script, setup_base, args)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
#19 8.799     run_setup(setup_script, args)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
#19 8.799     raise
#19 8.799   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
#19 8.799     self.gen.throw(type, value, traceback)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
#19 8.799     yield
#19 8.799   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
#19 8.799     self.gen.throw(type, value, traceback)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
#19 8.799     saved_exc.resume()
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
#19 8.799     six.reraise(type, exc, self._tb)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
#19 8.799     raise value.with_traceback(tb)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
#19 8.799     yield saved
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
#19 8.799     yield
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
#19 8.799     _execfile(setup_script, ns)
#19 8.799   File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
#19 8.799     exec(code, globals, locals)
#19 8.799   File "/tmp/easy_install-vm_cmg5u/numpy-1.20.0rc1/setup.py", line 30, in <module>
#19 8.799     'opencv-python==4.2.0.34',
#19 8.799 RuntimeError: Python version >= 3.7 required.
```

**Comment by charris** [comment] 2020-12-04 05:27
The requirements.txt approach works for me. I did see `easy_install.py` up above, maybe that is related.
```
(testing) charris@fc [~]$ python -mpip install -r requirements.txt
Collecting numpy
  Downloading numpy-1.19.4-cp39-cp39-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 1.3 MB/s 
Installing collected packages: numpy
Successfully installed numpy-1.19.4
WARNING: You are using pip version 20.2.2; however, version 20.3.1 is available.
You should consider upgrading via the '/home/charris/testing/bin/python -m pip install --upgrade pip' command.
(testing) charris@fc [~]$ cat requirements.txt
numpy
(testing) charris@fc [~]$ python -mpip --version
pip 20.2.2 from /home/charris/testing/lib64/python3.9/site-packages/pip (python 3.9)
```

**Comment by charris** [comment] 2020-12-04 05:33
Yep, it is easy_install that is broken.
```
(testing) charris@fc [~]$ easy_install numpy
WARNING: The easy_install command is deprecated and will be removed in a future version.
Searching for numpy
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/b9/70/83ad65cccc579ebb253c95fd6e4e8caaaff2aa5fa56fc29ae771d1307e2a/numpy-1.20.0rc1-cp39-cp39-manylinux2010_x86_64.whl#sha256=b38a2caf64429bab2c06b87eea0d2b24f736894f805f3d7210ecafb5573cb0de
Best match: numpy 1.20.0rc1
```
You should open issues on the related projects.

**Comment by duanqn** [comment] 2020-12-04 05:37
@charris Sorry, I'm quite new to python. (The code I'm building is not written by me) It seems you have a solution / workaround but I'm not getting it. Do you mean I should not install the package with `python3 setup.py install` ?

**Comment by charris** [comment] 2020-12-04 06:06
You should first install numpy yourself, `python3 -mpip install numpy --user`. The `--user` is the default these days, but just in case... The `python3 -mpip` approach is also preferred in case you have several python versions install because there is no way to know what python version `pip3` or `pip` points to unless you dump their code. If you have unfortunately already installed it you may need to delete it from your site-packages file. I'm in a virtual environment `/home/charris/testing`, so
```
(testing) charris@fc [~]$ ls /home/charris/testing/lib/python3.9/site-packages
easy-install.pth                        pkg_resources
easy_install.py                         __pycache__
numpy-1.20.0rc1-py3.9-linux-x86_64.egg  setuptools
pip                                     setuptools-49.1.3.dist-info
pip-20.2.2.dist-info
```
Most of that junk needs to go and easy_install won't do it for you. OTOH, your install failed, so maybe you lucked out :) Just try installing numpy first with pip and see what happens.

**Comment by charris** [comment] 2020-12-04 07:07
But maybe I'm missing something. How are you folks installing the packages you want? With pip, or easy_install? I also note that websokify is a source release, so pip will try to build it using `python setup.py`, which is proper. The problem isn't `python setup.py`, it is that numpy-1.20.0rc1 is fetched and built since there is no binary numpy-1.20.0rc1 available for Python3.6.

**Comment by duanqn** [comment] 2020-12-04 14:23
> But maybe I'm missing something. How are you folks installing the packages you want? With pip, or easy_install? I also note that websokify is a source release, so pip will try to build it using `python setup.py`, which is proper. The problem isn't `python setup.py`, it is that numpy-1.20.0rc1 is fetched and built since there is no binary numpy-1.20.0rc1 available for Python3.6.

@charris In my case, my team wrote a python package (which includes a setup.py) and we explicitly run `python3 setup.py install` as part of the docker build process. The package we wrote has numpy as its installation dependency.

**Comment by duanqn** [comment] 2020-12-04 14:28
I was able solve this build-breaking issue by restricting our numpy version to `numpy<=1.19`.
Will numpy add back Python 3.6 support in the future stable release? If not, I guess we'll have to pin numpy to 1.19 indefinitely.

**Comment by charris** [comment] 2020-12-04 14:48
> The package we wrote has numpy as its installation dependency.

How is that dependency specified? What I am curious about is the code path followed during installation that causes the problem. Do you simply run `python3 setup.py install <your-package>`?

> Will numpy add back Python 3.6 support in the future stable release?

No. See [NEP-0029](https://numpy.org/neps/nep-0029-deprecation_policy.html). Since we no longer test against Python 3.6 there is no guarantee that future releases will work with that version, so it is probably better to disallow it.

**Comment by charris** [comment] 2020-12-04 15:00
What happens if you run `python3 -mpip install .` instead? That is actually the recommended method these days.

**Comment by charris** [comment] 2020-12-04 15:03
Make that  `python3 -mpip install -e  .` .

**Comment by duanqn** [comment] 2020-12-04 15:44
I checked our dockerfile. This package is built with `python3 setup.py install`. The setup.py contains a call to `setuptools.setup`, with `install_requires=[..., 'numpy', ...]`.

Sorry I can't try the `pip install` approach at this moment (because it's Friday midnight).

**Comment by douglas-raillard-arm** [comment] 2020-12-10 17:02
Joining the bandwagon with a variant of `python -m pip install -r requirements.txt`:
https://readthedocs.org/projects/lisa-linux-integrated-system-analysis/builds/12531220/
The issue is very reproducible on ReadTheDocs but running the same sequence of commands into a Python 3.6 venv on my machine works perfectly fine. I tried to wipe the RTD workspace to no avail.

**Comment by seberg** [comment] 2020-12-10 17:29
I am still confused by this. I thought @charris you only reproduced it with easy-install, but that readthedocs toolchain doesn't seem to  use it?

Does easy_install somehow get involved in that readthedocs incarnation?  It still seems like an upstream bug to me that should maybe be filed, even if just to get input from someone who knows this better?

**Comment by charris** [comment] 2020-12-10 19:56
@douglas-raillard-arm  That error was also due to using easy_install. Why easy_install was being used I don't know.

**Comment by douglas-raillard-arm** [comment] 2020-12-11 12:05
@charris I also noticed the easy_install name in the path of one script along the exception backtrace, but the command line invocation is with pip. Given that pip is up-to-date (there is a `pip install --upgrade pip` before), I don't really understand it either. Maybe ReadTheDocs is using some cache for PyPI that does not propagate properly the pre-release tag ? From reading pip manual, it seemed that pre-release state is based on parsing the package version though (not 100% sure of that).

**Comment by charris** [comment] 2020-12-11 15:03
@douglas-raillard-arm I'm curious if you have easy_install installed anywhere.

**Comment by charris** [comment] 2020-12-11 15:04
NVM: setuptools contains easy_install.

**Comment by charris** [comment] 2020-12-11 15:09
A possibility might be that some source package uses setup_tools in its `setup.py`.

**Comment by rgommers** [comment] 2021-02-12 21:26
- `easy_install` gets invoked if there's a package that put `numpy` into `setup_requires` (not `install_requires`).
- we cannot fix this, there's nothing wrong on our side.
- the fix is a two-step process by the user's script: first `pip install numpy` (which will not pick up pre-releases), then install the package with the problematic `setup_requires` usage (use `--no-build-isolation` for the second command if there's still an `easy_install` invocation).
- `easy_install` has now mean removed from `setuptools` master (to be released soon I expect).

NumPy 1.20.0 final is out, which resolved the issue for people. So I'll close this issue.

**Closed by rgommers** 2021-02-12 21:26 UTC
