### ISSUE TITLE
Why is in1d 1d?

### ISSUE THREAD

**Issue by endolith** [numpy/numpy#8417] opened 2016-12-25 06:39 UTC
I don't see any reason why the first input `ar1` needs to be one dimensional. If not for this limitation, I think it would perfectly answer my question here: http://stackoverflow.com/q/41318942/125507

**Comment by seberg** [comment] 2016-12-25 14:12
Duplicate of gh-8331.

**Closed by seberg** 2016-12-25 14:12 UTC
