### ISSUE TITLE
np.max, np.ma.max returns NAT for masked_array with datetime64

### ISSUE THREAD

**Issue by hdkire** [numpy/numpy#18240] opened 2021-01-27 10:25 UTC
The return value of np.max is always numpy.datetime64('NaT') for masked_array of datetime64 containing masked values.
This can be seen when using np.max, np.argmax and their counterparts from np.ma. It seems that np.min, np.argmin, etc. behaves correctly.

At least np.ma.max should return the largest non-masked value, not NaT.

### Reproducing code example:
```
# Some masked, max returns numpy.datetime64('NaT')
>>> import numpy as np
>>> a = np.ma.masked_array(['2021-01-27T10:33:15', '2021-01-27T10:33:16'], mask=[True, False], dtype='datetime64[us]')
>>> np.max(a)
numpy.datetime64('NaT')
>>> np.min(a)
numpy.datetime64('2021-01-27T10:33:16.000000')

# All masked, masked is returned
>>> a = np.ma.masked_array(['2021-01-27T10:33:15', '2021-01-27T10:33:16'], mask=[True, True], dtype='datetime64[us]')
>>> np.max(a)
masked
>>> np.min(a)
masked

# Masked float column, non-masked value is returned
>>> a = np.ma.masked_array([0.1, 0.2], mask=[True, False])
>>> np.max(a)
0.2
>>> np.min(a)
0.2
```

### NumPy/Python version information:

1.19.5 3.8.6 (default, Sep 25 2020, 09:36:53)

**Comment by Dinkarkumar** [comment] 2021-08-21 15:33
Is the issue still open for contribution ? May I work on resolving this issue ?

**Comment by mattip** [comment] 2021-08-22 06:43
We do not assign work. Anyone can submit a PR. Please mark the PR with `fixes 18240` so other will be aware the issue is being worked on.

**Closed** 2024-11-04 21:01 UTC
Labels: component: numpy.ma, component: numpy.datetime64
