### ISSUE TITLE
BUG: Generator.randint returns None

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#13939] opened 2019-07-08 15:00 UTC
Moving on from #13938 and continuing to translate `RandomState` to `Generator` code, I hit another problem:
```
>>> print(np.random.RandomState(0).randint(0, 10, 2))
[5 0]
>>> print(np.random.Generator(np.random.PCG64()).randint(0, 10, 2))
__main__:1: RuntimeWarning: Renamed to integers
None
```
The RuntimeWarning is fine (though maybe it should be a PendingDeprecationWarning or DeprecationWarning?) but the `None` return is weird and not backward compatible.

**Comment by charris** [comment] 2019-07-08 15:56
I don't think there *is* a `randint`. The `None` is because nothing happens except the warning. The new module is not intended to be backwards compatible, that's why it is new :)

**Comment by charris** [comment] 2019-07-08 15:59
@bashtage Is it worth keeping randint around?

**Comment by bashtage** [comment] 2019-07-08 16:10
I think randint is supposed to be gone. This said, the code in `Generator` is clearly wrong.

https://github.com/numpy/numpy/blob/master/numpy/random/generator.pyx#L511

It calls `integers` and then doesn't return the value.  

@mattip  do you recall if `randint` was supposed to be removed completely to was to be left to help porting?

**Comment by charris** [comment] 2019-07-08 16:18
We should also discuss #13938 here, as it is the same sort of problem. I think the question is whether we want the new module to be a drop in replacement. The downside of that is that we want folks to use the new functions instead of the old in some cases. Let's bring in @rkern to the discussion.

**Comment by mattip** [comment] 2019-07-08 16:23
> doesn't return the value.

That is a bug, it should IMO return the value, or raise an error. I think the intention was to return the value.

**Comment by bashtage** [comment] 2019-07-08 16:25
I would vote, in order:

1. Leave but raise with a message about the new function, remove in 1.18
2. Remove all together
3. Leave with explicit depreciation message that these will be removed very
soon (1.18) and return a value from the replacement function.

3 seems much worse than 1 or 2 though.

**Comment by bashtage** [comment] 2019-07-08 16:26
This function also has no test coverage which is another suggestion that it
shouldn't return a value.

**Comment by rkern** [comment] 2019-07-08 20:43
With `rand`/`randn`/etc., it's easier to just leave them off, because there's a good way to write code that consumes either a `Generator` or `RandomState`; the current preferred methods are available on `RandomState` already. But there is no `RandomState.integers()` method, so you can't write libraries, like `scipy.stats`, that support both 1.16 and 1.17. That's not a great position to put downstream libraries in.

Providing a deprecated `Generator.randint()` method is reasonable, but only delays the problem (unless if we want to support it forever, being increasingly noisy about it). The bare minimum would be to provide a cookbook-style function in our docs that people could vendorize into their own code that would perform `randint` given either a `Generator` or `RandomState`. Then they could support both 1.16 and 1.17 until they can drop 1.16.

```python
def generic_randint(rng, low, high=None, size=None, dtype='l'):
    if isinstance(rng, np.random.RandomState):
        return rng.randint(low, high=high, size=size, dtype=dtype)
    else:
        return ... # The Generator equivalent
```

Or we take our last bite at the `RandomState` apple before NEP 19 forbids us and add `RandomState.integers()` in 1.17.

**Comment by seberg** [comment] 2019-07-08 20:52
Adding `RandomState.integers` seems the easiest solution to me (not `np.random.integers` of course). DeprecationWarnings that cannot be silenced easily are not really much of a solution for most libraries, so that it would not help them much for compatible code to have `randint` with warnings.

**Comment by larsoner** [comment] 2019-07-08 21:35
I just ported over a bunch of code and I just ended up doing
```
func = getattr(rng, 'integers, getattr(rng, 'randint'))
```
It's an easy enough one-liner. I think if it's documented in the same place that says what the differences are (and the docs no longer claim to be a direct or drop-in replacement) then it's easy enough from a user perspective.

**Comment by larsoner** [comment] 2019-07-08 21:37
> Adding RandomState.integers seems the easiest solution to me

I'm not sure how this helps end users much, so I don't see too much value. It does not seem to help write code that works with <= 1.16 RandomState and >= 1.17 Generator.

**Comment by seberg** [comment] 2019-07-08 22:31
@larsoner ah yes, sorry, you are right. Even if we backport it, it does not help much. I suppose your solution (or two code paths for the two objects) is the only way to get around it.

**Comment by rkern** [comment] 2019-07-09 00:36
Ah, duh. Yes.

**Comment by seberg** [comment] 2022-10-19 15:36
`Generator.randint` is fully gone these days.  Not quite sure when that happened, but the issue is not relevant anymore.  Closing.

**Closed by seberg** 2022-10-19 15:36 UTC
