### ISSUE TITLE
numpy.take() with a 'ignore' mode

### ISSUE THREAD

**Issue by clemens87** [numpy/numpy#5573] opened 2015-02-16 07:24 UTC
For me numpy.take() is a great function - but the possibility to behave on out-of-bounds with just ignoring these is really missing.

Example (with not-yet-existing _mode='ignore'_ feature):

```
anylist = [7,15,34,55,76,99]
np.take(anylist, [0,2,4,6], mode='ignore')  # get every second item; array(range(X))*2; here X=4
```

shall result in:

>  array([7, 34, 76])  # ignoring the index 6, which is out of bounds

...
I tried to add this to numpy by my own, but unfortunately - although I think it's not a big deal if you know how (numpy library is build up) - I failed at first with the finding of the right source code place... :-/

**Comment by jaimefrio** [comment] 2015-02-16 08:26
It seems like a good idea, but it is somewhat problematic. Consider the following example:

```
>>> import numpy as np
>>> a = np.arange(10)
>>> idx = [[3, 4, 5], [6, 7, 8]]
>>> a.take(idx)
array([[3, 4, 5],
       [6, 7, 8]])
```

Now imagine we tried the following:

```
>>> idx = [[3, 4, 5], [6, 10, 8]]
>>> a.take(idx, mode='ignore')
```

What would you expect this to return?

There may be ways around this, and it may be helpful for 1-D index arrays. But this type of changes are best discussed first on the mailing list. Can you post this request over there?

**Comment by clemens87** [comment] 2015-02-16 11:19
Thanks for your quick response! Well, in fact I don't see here a conflict, although I've to admit that I just thought of 1d-arrays. Anyway, in your example I would expect to result the same, because there is no index out of bounds. So let's change the 8 to 10 (or higher):
```
>>> idx = [[3, 4, 5], [6, 7, 10]]
>>> a.take(idx, mode='ignore')
```
now what I would expect to result would be:
>  array([[3, 4, 5], [6, 7]], dtype=object)       # doesn't has to keep its (matrix) shape, does it!?

But like I said, I only had 1d-arrays in mind and maybe underestimate the functionality of the function (in higher space).

...
Thanks for the advice with the mailing list...
So I just would have to register at http://mail.scipy.org/mailman/listinfo/numpy-discussion and could send the same kind of feature requet per mail to the mailing list, you mean?

**Comment by juliantaylor** [comment] 2015-02-16 16:15
as a precedent for a change, `np.choose` does have a mode argument which takes raise, clip or wrap
but ignore is problematic for higher dimensional data. we unfortunately do not have variable length arrays.

**Comment by seberg** [comment] 2019-01-03 15:22
I will close this, since the results would typically be ragged arrays, it is a very non-trivial request as pointed out. And the issue is 3 years old.

**Closed by seberg** 2019-01-03 15:22 UTC
