### ISSUE TITLE
BUG: np.arange() not behaving as expected

### ISSUE THREAD

**Issue by gstei** [numpy/numpy#21208] opened 2022-03-17 06:41 UTC
### Describe the issue:

input: np.arange(1.0125, 1.1, 0.0125)
output is: array([1.0125, 1.025 , 1.0375, 1.05  , 1.0625, 1.075 , 1.0875, 1.1   ])
output expected: array([1.0125, 1.025 , 1.0375, 1.05  , 1.0625, 1.075 , 1.0875  ])

### Reproduce the code example:

```python
#They do not have the same behavior
np.arange(0.0125,0.1,0.0125)
np.arange(1.0125,1.1,0.0125)
```

### Error message:

```shell
No error occurs, but the output is not as expected since there is one array element to much.
```

### NumPy/Python version information:

numpy.__version__
'1.21.5'
sys.version
'3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]'

**Comment by mattip** [comment] 2022-03-17 07:35
You are using a non-integral `step` in `arange`. Please carefully read [the documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange) about the numerical problems with this and suggest documentation improvements that would have helped you understand the limitation of floating point accuracy.

**Comment by melissawm** [comment] 2022-03-17 11:59
I am closing this as a duplicate of #19552 (and several other issues linked there), please add a comment there if you have a different issue. Thanks!

**Closed by melissawm** 2022-03-17 11:59 UTC
Labels: 33 - Question
