### ISSUE TITLE
BUG: Debug optimization flags are overwritten during build process

### ISSUE THREAD

**Issue by mtsokol** [numpy/numpy#24788] opened 2023-09-24 17:00 UTC
Hi!
I recently used `gdb` to inspect numpy's C level code and I noticed that some variables aren't available because they have been optimized out, despite using debug mode. I think this happens because in the build process `-O` flag is passed on multiple times.

For example, when building numpy in a release mode with: `python -m pip install . -C'setup-args=-Dbuildtype=release' [...]` one of the outputs is:

```
clang [...] -std=c99 -O3 -fno-strict-aliasing [...] -O2 -pipe [...] -O3 -DNPY_HAVE_SSE2 [..]
```

As the clang uses the last value for duplicated options, the optimization level here is `3`.

But when I build numpy in a debug mode with: `python -m pip install . -C'setup-args=-Dbuildtype=debug' [...]` the same output line is:
```
clang [...] -std=c99 -O0 -g -fno-strict-aliasing [...] -O2 -pipe [...] -O3 -DNPY_HAVE_SSE2 [..]
```
Here, `-g` flag is included but `-O0` is discarded in favor of the last `-O3`. As a result I can stop at a breakpoint in numpy's C code, but some variables are opitmized out:
```
(PyArrayObject *) prototype = <no location, value may have been optimized out>
```

I think it would be beneficial to control the optimization level from one place only. 

Do you think it would be a simple change to the build process? (I've already started looking into how meson builds these commands)

### Reproduce the code example:

```python
python -m pip install . -v --no-build-isolation -Cbuilddir=build -C'compile-args=-v' -C'setup-args=-Dbuildtype=debug'

python -m pip install . -v --no-build-isolation -Cbuilddir=build -C'compile-args=-v' -C'setup-args=-Dbuildtype=release'
```

### Runtime information:

2.0.0.dev0+git20230922.12ea98b
3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:42:20)
[Clang 14.0.6 ]

[{'numpy_version': '2.0.0.dev0+git20230922.12ea98b',
  'python': '3.9.16 | packaged by conda-forge | (main, Feb  1 2023, '
            '21:42:20) \n'
            '[Clang 14.0.6 ]',
  'uname': uname_result(system='Darwin', node='macbook', release='21.6.0', version='Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:23 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_X86_64', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3', 'SSSE3'],
                      'found': ['SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]

**Comment by mtsokol** [comment] 2023-09-24 17:26
One update: After including:
```
-C'setup-args=-Dallow-noblas=true' -C'setup-args=-Ddisable-optimization=true'
```
in the build command there's still one `-O2` that introduces 2nd optimization level.

**Comment by mtsokol** [comment] 2023-09-24 19:04
Ok, I managed to resolve my issue. There are several places where `-O2` might be included:

- In the build type, therefore `-Dbuildtype=debug` is required to get `-O0 -g`,
- From optimization option in meson, so `-Ddisable-optimization=true` is needed to turn them off,
- From `CFLAGS` and `CXXFLAGS` env vars (they might be set by conda environment).

The command that disabled all additional `-O` flags, except from the debug one is:

```sh
python -m pip install . -v --no-build-isolation -Cbuilddir=build -C'compile-args=-v' -C'setup-args=-Dbuildtype=debug' -C'setup-args=-Dallow-noblas=true' -C'setup-args=-Ddisable-optimization=true'
```

**Comment by mattip** [comment] 2023-09-25 20:52
If it is not already documented, we should document this, so others do not have to rediscover it.

**Comment by mtsokol** [comment] 2023-09-25 20:57
Sure! I will append it to the "local setup" section.

**Comment by ngoldbaum** [comment] 2023-09-26 16:23
Nope, pyenv-based

**Comment by mtsokol** [comment] 2023-09-27 11:06
As I'm testing it right now, `-Ddisable-optimization` is connected to CPU optimizations (dispatch, simd, ...) and injected flags differ between build objects. 

 I might be wrong here but I for example `numpy/core/libloops_comparison.dispatch.h_AVX512_SKX.a.p/loops_comparison.dispatch.c` gets additional `-O3` when CPU optimizations are enabled.

Additionally if you run build process with different parameters but same flags printed in terminal it might be due to caching build setup (?) - I see that `build/build.ninja` caches commands and I got an impression that removing build directory influenced used flags.

**Comment by rgommers** [comment] 2023-09-27 19:26
> Right, so conda may need different flag overrides than non-conda

See the `CFLAGS`/`CXXFLAGS` warning in https://meson-python.readthedocs.io/en/latest/how-to-guides/debug-builds.html. It's a design problem in conda, it may get addressed in conda-forge but I'm not holding my breath. 

> I see that `build/build.ninja` caches commands and I got an impression that removing build directory influenced used flags.

These kinds of flags will only be picked up the first time the build is configured, or if you explicitly run `meson reconfigure`. A partial rebuild won't pick up any changes to env vars.

> I think it would be beneficial to control the optimization level from one place only.
> 
> Do you think it would be a simple change to the build process? (I've already started looking into how meson builds these commands)

No - it's not really desired even. Things are layered by design. Some distros will use `CFLAGS` for example to override per-package defaults and force a uniform set of flags across all their packages.



> I might be wrong here but I for example `numpy/core/libloops_comparison.dispatch.h_AVX512_SKX.a.p/loops_comparison.dispatch.c` gets additional `-O3` when CPU optimizations are enabled.

That's indeed the case, and is on purpose. It isn't really useful to pass architecture-specific flags like `-march-native` without using the highest available compiler optimization level. I don't have a great reference to read at hand, but https://stackoverflow.com/questions/71229343/what-exactly-do-the-gcc-compiler-switches-mavx-mavx2-mavx512f-do covers some of this.

> As a result I can stop at a breakpoint in numpy's C code, but some variables are opitmized out:

It's not clear to me that there is any problem. The multiple `-O` flags should be there. If you're missing debug info because your breakpoint ends up inside SIMD-enabled code, I think you want to build with `-Ddisable-optimization` - that should fix it.

**Comment by mtsokol** [comment] 2023-09-28 08:54
> See the `CFLAGS`/`CXXFLAGS` warning in https://meson-python.readthedocs.io/en/latest/how-to-guides/debug-builds.html. It's a design problem in conda, it may get addressed in conda-forge but I'm not holding my breath.

Thank you for pointing to this doc page - that's exactly what I figured out this week in my local setup.

> No - it's not really desired even. Things are layered by design. Some distros will use `CFLAGS` for example to override per-package defaults and force a uniform set of flags across all their packages.
> That's indeed the case, and is on purpose. It isn't really useful to pass architecture-specific flags like `-march-native` without using the highest available compiler optimization level. I don't have a great reference to read at hand, but https://stackoverflow.com/questions/71229343/what-exactly-do-the-gcc-compiler-switches-mavx-mavx2-mavx512f-do covers some of this.

Sure! Now it's clear to me why I found multiple `-O` flags in the build commands.

> It's not clear to me that there is any problem. The multiple `-O` flags should be there. If you're missing debug info because your breakpoint ends up inside SIMD-enabled code, I think you want to build with `-Ddisable-optimization` - that should fix it.

Then I think I can close https://github.com/numpy/numpy/pull/24819. 

I will prepare a PR to update "Debugging" [docs page](https://numpy.org/doc/stable/dev/development_environment.html#debugging) on NumPy website. I will include a short paragraph about build types and that `debug` should be used. That `CFLAGS`/`CXXFLAGS` flags in conda and `-Ddisable-optimization` also add `-O` options and can be turned off for debug setup. Does it make sense?

**Comment by rgommers** [comment] 2023-09-28 09:02
Yes, that sounds like a good plan - thanks for improving those docs!

**Closed** 2023-10-03 07:21 UTC
Labels: 00 - Bug
