### ISSUE TITLE
Faster generation of gamma random variates

### ISSUE THREAD

**Issue by carlosgmartin** [numpy/numpy#15141] opened 2019-12-20 20:07 UTC
### Reproducing code example:

```python
import numpy as np
from time import time

rg = np.random.Generator(np.random.PCG64())
shape = np.random.uniform(100, 200, size=10**7)

start = time()
np.random.gamma(shape)
print(time() - start)

start = time()
rg.gamma(shape)
print(time() - start)
```

The algorithm [currently used by numpy](https://github.com/numpy/numpy/blob/fdd8395f21a252373ff17fd43185c42e040c1b64/numpy/random/src/distributions/distributions.c#L218) seems to be the one presented in [*A simple method for generating gamma variables*](https://dl.acm.org/citation.cfm?id=358414) (2000) by Marsaglia and Tsang. A faster algorithm is presented in [*Extremely efficient generation of Gamma random variables for α ≥ 1*](https://arxiv.org/abs/1304.3800) (2013) by Martino and Luengo. Could it be implemented for numpy?

**Comment by rkern** [comment] 2019-12-20 20:46
Yes, contributions in this vein are welcome. Once implemented, we'll have to benchmark the two methods. If the actual wall-clock performance is only a _little_ bit better or if the range where `shape` gives substantially better performance is rather tight, then we might not go through with it. See [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html#implementation) (specifically, the paragraph starting "Second, breaking stream-compatibility...") for more information about our policy here. For example, the paper touts its performance in terms of acceptance rate, but it seems like it can require substantially more draws from the `BitGenerator` as `shape` increases. I don't have a good feel for where the performances of the two methods might cross over, so we'll just have to implement both and see.

**Comment by psimaj** [comment] 2020-01-15 00:33
I went ahead and changed the implementation of the gamma distribution to the algorithm from the paper in #15330 so that you can benchmark it up to your standards, and perhaps pull it at a later time if you deem it worth it.

**Comment by psimaj** [comment] 2020-01-20 16:07
I independently benchmarked the algorithm presented in the paper, but using C++ and its random and math libraries instead of the NumPy versions. You can see it [here](https://github.com/psimaj/numpy-benchmarks/tree/master/random-gamma-benchmark). 
Maybe my implementation is suboptimal, but while the old NumPy sampler achieves similar efficiency to the C++ stdlib implementation, the algorithm from the paper is 3-5 times slower depending on the _shape_ parameter. Perhaps it might need some refinement, or it's simply not practically better, as the authors had measured the efficiency by the expected number of rejections, mostly disregarding surrounding calculations.

**Comment by rkern** [comment] 2020-01-21 12:51
That's what I was worried about. I think the issue is with the method, not your code.

**Comment by seberg** [comment] 2020-01-28 07:43
Closing since it sounds like the referenced algorithm would not give a speed increase right now. Of course that does not mean we should not add a new algorithm when one is found to be faster.

**Closed by seberg** 2020-01-28 07:43 UTC
Labels: 01 - Enhancement, component: numpy.random
