### ISSUE TITLE
BUG: Serious numerical error/inconsistency on macOS

### ISSUE THREAD

**Issue by cod3licious** [numpy/numpy#11166] opened 2018-05-26 23:11 UTC
I get very very strange numerical inconsistencies like these:
<img width="789" alt="screen shot 2018-05-27 at 0 29 08" src="https://user-images.githubusercontent.com/1093567/40580834-df8b364e-6147-11e8-9b4d-4f6aa0300643.png">
I could reproduce this in ipython and jupyter notebook but only on macOS, not on Linux. Here is a gist with [code to reproduce the error](https://gist.github.com/cod3licious/d2926e0bdc1355f0a921ac083d2799eb) (Note that you need to download and unzip a file first and then appropriately copy your value of `vec_x` to `a`.) The error also happens for `np.dot` and possibly other functions.

My system specs:
macOS 10.13.4 (17E202) 
Python 3.6.4 :: Anaconda custom (64-bit)
jupyter-notebook 5.4.0
ipython 6.2.1
numpy 1.14.2
gensim 3.4.0

This is a cross post from this [jupyter notebook issue](https://github.com/jupyter/notebook/issues/3641) (as I really don't know who's the culprit in the end).

**Comment by pv** [comment] 2018-05-26 23:38
Report it to anaconda too, most likely to do with their stuff.

**Comment by seberg** [comment] 2018-05-27 09:52
This has been opened a few other times already. One thing you could try is, use plain python (not notebook and likely not ipython either), and see if the problem persists if you do not load any gui libraries before numpy.

**Comment by cod3licious** [comment] 2018-05-27 13:32
@seberg ok, I checked, the issue persists in ipython but not in plain python (although this was also installed via anaconda in the same go). what exactly does this mean? is it more likely an ipython/jupyter notebook problem or an anaconda problem?

**Comment by charris** [comment] 2018-05-27 13:41
I'm wondering if there some way to test for this problem so that the relevant people will detect it. It is a pretty severe problem even if not directly ours.

**Comment by cod3licious** [comment] 2018-05-27 13:47
yeah, I only noticed this when creating a matrix with this gensim library, but of course that's not a very straightforward way to reproduce this error. however, I also just noticed in ipython that this error can be even more subtle: while in most cases the norm of `vec_x` was either `nan` or `0.0`, when I just tested it, it gave me
```
In [7]: np.linalg.norm(a)
Out[7]: 1.3041147836012752

In [8]: np.linalg.norm(vec_x)
Out[8]: 1.4142135
```
(again `a` has the same values as `vec_x`), so the result is still very much wrong, but in the original code I only caught the error because I was getting `nan`s, which I knew wasn't supposed to happen. If the numbers were only slightly off, I probably wouldn't even have noticed it, which kind of scares the crap out of me now...

**Comment by pv** [comment] 2018-05-27 13:52
We'd need the problem to be reduced to a simpler python script of this form:
```
import some_other_bad_library
import numpy as np
#import some_other_bad_library   # <- or here
x = np.array([...], dtype=np.float32)
assert_allclose(np.linalg.norm(x), ...)
```
Basically, it's necessary to find out (i) which library imported first or after triggers the issue, and (ii) does the error require that specific `vec_x`, probably not, which you can check, so some simpler and shorter vector can be used.

**Comment by seberg** [comment] 2018-05-27 14:02
@cod3licious it means that your problem is identical to at least one, probably more, issues reported at anaconda (and also here) if you search the issues for words such as `dot float32 Mac`.
This specific thing was about Accelerate being picked up instead of the MKL that numpy is supposed to be linked with in anaconda. Again, this is not a numpy issue as such.

I think bad libraries were things such as Qt (`import PyQt5` may trigger it), but did not check the anaconda issue again.

I agree it is a very sever issue, but how can we test it? The closest would be writing a script that tries to import a few libraries that could do odd things (cv, gui libraries, ...) and then check. Or is there some way to check, at startup, whether the BLAS library that is being used is the one that should be used?

**Comment by cod3licious** [comment] 2018-05-27 14:03
I think the gensim library does a lot with cython, so maybe this is some memory thing or something, like the original array is somehow stored differently than the one I create when manually copying the numbers?
also the error seems pretty consistent with respect to different vectors and it doesn't matter which library is imported first.
I just ran it again and I got for both `vec_x` and `vec_y` the same norm as above, i.e., exactly `1.4142135`, even though the real norms were supposed to be `1.28422` and `2.3991295` respectively. Then I imported `copy.deepcopy` and the norm of a deepcopied `vec_y` then was `6074001000.0`, which is also one of the wrong answers that I got frequently in addition to `nan` and `0.0`.

**Comment by seberg** [comment] 2018-05-27 14:07
@cod3licious, cython having to do with it sounds unlikely to me. Please search the anaconda issues, the import order and thus incorrect library being picked up seems likely, though. You could also check which libraries your python process picked up at run time (which should be wrong).

One thing that I could imagine, is that the bug is triggered by specific memory alignments, so that creating a copy gives a chance of a different alignment.

**Comment by cod3licious** [comment] 2018-05-27 14:08
ahh, ok, I guess the main issue seems to be related with the `float32` indeed; when I manually copy the vector it creates a `float64` array and the original is `float32`, so:
```
In [21]: c = np.array(vec_x, dtype=np.float32)

In [22]: np.linalg.norm(c)   # same wrong answer
Out[22]: 1.4142135

In [23]: c = np.array(vec_x, dtype=np.float64)

In [24]: np.linalg.norm(c)
Out[24]: 1.2842202704483743
```

**Comment by seberg** [comment] 2018-05-27 14:10
OK, see also:

https://github.com/ContinuumIO/anaconda-issues/issues/1461
https://github.com/ContinuumIO/anaconda-issues/issues/7457

I was thinking of the first one, which is very old, so maybe it reappared also. Or it is a remaining seriously bad bug.
Or, there is something else wrong with your install? Such as PyQt or whatever not being installed with anaconda, while the rest is creating inconsistencies?

**Comment by cod3licious** [comment] 2018-05-27 14:13
ok, i restarted ipython and all i did was import numpy and i got this:
```
In [3]: a = np.random.randn(50)

In [4]: a.dtype
Out[4]: dtype('float64')

In [5]: np.linalg.norm(a)
Out[5]: 6.346556830345333

In [6]: b = np.array(a, dtype=np.float32)

In [7]: np.linalg.norm(b)
Out[7]: 3.2927225e-10
```
which...should not happen?!

**Comment by pv** [comment] 2018-05-27 14:26
But you said above it works if you run it in plain Python?

The difference between notebook/ipython and plain python is only loading some additional libraries.

**Comment by cod3licious** [comment] 2018-05-27 14:27
um...ok, i have no idea though what libraries are loaded by default when I start a simple ipython shell...

**Comment by pv** [comment] 2018-05-27 14:27
You find out what is loaded by checking what's in `import sys; print(sys.modules)` as I wrote above.

**Comment by pv** [comment] 2018-05-27 14:42
It's probably a good idea to first check if you can reproduce it with the test code from https://github.com/numpy/numpy/issues/8577 --- if pytq5 is in your sys.modules in ipython, then it's quite likely the same issue. (Also, to be sure, you can check that `print(sys.executable)` is the same in ipython and plain python.)

**Comment by cod3licious** [comment] 2018-05-27 15:08
ok, sorry, I didn't know what you meant before.
so, it's the same python executable in both ipython and regular python and PyQt does not seem to be directly loaded when I start up ipython (at least I don't find it directly when checking `sys.modules`). 
I can reproduce the error in regular python with
```python
import IPython
import numpy as np
a = np.random.randn(2)
print(a.dtype)                   # float64
print(np.linalg.norm(a))         # 7.523412005985283 or some other real number
b = np.array(a, dtype=np.float32)
print(np.linalg.norm(b))         # nan / 0.0 / 6074001000.0 / 1.4142135 (i.e. not the right answer)
```
or if I import `PyQt5.QtWidgets` instead of `IPython` like in the other issue. And it only happens if the library is imported before numpy, not after.

**Comment by pv** [comment] 2018-05-27 15:12
Thanks!
Do you get the issue also with `a = np.ones([2])`?

**Comment by pv** [comment] 2018-05-27 15:34
@cod3licious: can you check if the test code in  #8577 also fails for you, i.e., `dot` instead of `norm`?

**Comment by cod3licious** [comment] 2018-05-27 15:41
yep, I can reproduce this as well.
mkl's speed improvements are really not worth this...

**Comment by pv** [comment] 2018-05-27 19:40
#11169 makes it so that `import numpy` will simply fail if this issue is present to make this issue easy to notice, which looks at the moment to be all that can be done from our side.

This bug is a duplicate of #8577, so closing.

**Closed by pv** 2018-05-27 19:40 UTC

**Comment by msarahan** [comment] 2018-05-29 23:52
The actual fix is more on Intel's side, and should be coming with MKL's 2018 update 3.  Sorry for the trouble in the meantime.

@cod3licious this is not an intrinsic fault of MKL, but a complicated interaction between the OS BLAS (which is loaded when you load a GUI library) and MKL.  If anything, blame Apple.
