### ISSUE TITLE
A big BUG of argsort!

### ISSUE THREAD

**Issue by abcgreat11** [numpy/numpy#12627] opened 2018-12-28 09:44 UTC
### Reproducing code example:

```python
import numpy as np
```

The result of argsort is quite imbalance when there are a lot of same elements in the Numpy array.
For example:
```
a = [3,2,1,4,2.3,2.5,3.1]
print(np.argsort(a))
```
The result is
 array([2, 1, 4, 5, 0, 6, 3], dtype=int64)
However, when I run the following codes: it get back a different result:
```
a=np.array([0, 9, 2, 3, 0, 4, 5, 6, 0, 7, 8, 1])
np.argsort(a)
```
The result is:
array([ 0,  4,  8, 11,  2,  3,  5,  6,  7,  9, 10,  1], dtype=int64)
The tests below show that the result of argsort is quite imbalance when there are a lot of same elements in the Numpy array.

It's OK when I use the function 'sort' in Matlab. But I want to do the same thing in Numpy, can you help me? Thank you very much.

**Comment by eric-wieser** [comment] 2018-12-28 09:59
I don't understand your question here, and it doesn't look to me like there's a bug. I strongly suspect this is a duplicate of #8757.

**Closed by eric-wieser** 2018-12-28 09:59 UTC
