### ISSUE TITLE
Error in modulo numpy.float64

### ISSUE THREAD

**Issue by Andrewnetwork** [numpy/numpy#10075] opened 2017-11-25 03:03 UTC
numpy==1.12.0
python==3.5

```python
k = np.divide(np.log(1000),np.log(10))
# k is numpy.float64 with the value"3.0" 

z = k%1
# 3.0 % 1 should be 0, but z == 1. 

a = np.matrix([3.0])
r = a % 1
#Produces a 0 as expected, r == 0
```
z should be 0, but for some reason it produces a 1.

**Comment by eric-wieser** [comment] 2017-11-25 03:26
This is not a bug, because
```
>>> k == 3
False
```

You're seeing two things here:
* `k !=` - Floating point math is imprecise, and cannot compute the log to infinite precision. Using `log10` here should work fine
* `repr(k) == '3.0'`: Numpy is rounding off the last few digits of 2.9999... when it prints out the number. This should be fixed in 1.14, which prints floats to more decimal places when needed.

**Closed by eric-wieser** 2017-11-25 03:26 UTC

**Comment by Andrewnetwork** [comment] 2017-11-25 05:14
It is highly misleading when introspecting a value with print does not give you the actual value. I still consider this an error, as I can imagine this automatic rounding causing confusion. How would one access the true floating point value then?

**Comment by eric-wieser** [comment] 2017-11-25 05:24
Note that the second problem is already fixed in master, which is why I closed this issue.

**Comment by eric-wieser** [comment] 2017-11-25 05:25
Are you using `print` (`str`) or the interpreter result (`repr`)?

**Comment by ahaldane** [comment] 2017-11-25 05:33
Just a followup on the history of the floating point repr: Before numpy 1.14, numpy floats would print like python2 floats. In python2, `str(2.9999999999999996)` is `3.0`, which I agree is misleading. However, in python2 you can still access the "full precision" value using `repr`.

In numpy 1.14 we will break from python2 `float` behavior and print unique values for all numpy floats, even in python2.

**Comment by Andrewnetwork** [comment] 2017-11-25 05:35
I can't seem to get the full precision value with repr nor float, but thanks lads!
