### ISSUE TITLE
np.unravel_index() does not accept empty inputs

### ISSUE THREAD

**Issue by WeatherGod** [numpy/numpy#7165] opened 2016-02-01 21:55 UTC
I would expect a tuple of empty outputs back. I get the following:

```
>>> np.unravel_index([], (10, 12))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Iterator operand 0 dtype could not be cast from dtype('float64') to dtype('int64') according to the rule 'same_kind'
```

This does not seem to be a regression, as I can see this with numpy v1.9.2, but it does seem silly.

**Comment by gfyoung** [comment] 2016-02-02 14:58
At the very least, the error message does not really make much sense in this context.

**Comment by WeatherGod** [comment] 2016-02-02 15:07
Digging into the code in multiarray/compiled_base.c, I am trying to figure out where this error is occurring. At line 1123, `NpyIter_New()` is called on the passed in indices, and one of the flags is `NPY_ITER_ZEROSIZE_OK`, so that can't be where it is failing (and it should be having a dtype of int64).

What's a good way for me to figure out where this is failing?

**Comment by WeatherGod** [comment] 2016-02-02 15:10
Indeed, looking further down in the function, there are a bunch of checks for empty iterators, so I suspect this function was supposed to work for empty inputs, but something bad is inadvertently happening.

**Comment by gfyoung** [comment] 2016-02-02 15:13
Here are two ways I can think of:

1) IINM, I think you can use `gdb` to add breakpoints to the C code.

2) Create your own "breakpoints" by throwing exceptions at strategic points in the code.  Then you can zoom into where the code is breaking by whether or not your exception or that `TypeError` is thrown first.

**Comment by jaimefrio** [comment] 2016-02-02 15:43
The failure is in the iterator, but it has nothing do, at the time of failing, with it being an empty array, but with it being a float array.

The source of the issue is that [this call](https://github.com/numpy/numpy/blob/maintenance/1.11.x/numpy/core/src/multiarray/compiled_base.c#L1107), when `indices0` is an empty sequence, defaults to a `float64` dtype, and that's what throws the iterator off. Try `np.array([]).dtype` to see the same thing at work on your Python interpreter.

There may be more elegant ways, but a check for `PyArray_SIZE(indices) == 0` that triggers a forced cast to `NPY_INTP` is about as straightforward as you can go.

**Comment by seberg** [comment] 2016-02-02 15:45
I think you can just pass in the dtype into FromAny here, since there is only one reasonable dtype for indices really (Yeah, I know if someone manages to put a huge 64bit number into it on a 32bit syste, that may get funny stuff, but....).

**Comment by seberg** [comment] 2016-02-02 15:46
Ah ok, I guess if you want to avoid the copy, ...

**Comment by WeatherGod** [comment] 2016-02-02 15:58
I think I can put together a PR that does that check and forced cast. I
thought it was already getting forced cast, so I originally didn't think it
was the source of the problem, but I can see now what the problem is.

**Comment by jaimefrio** [comment] 2016-02-02 15:59
May not be worth it, but that's one of the sweetnesses of the new iterator.

What seems ludicrous is that we have specialized branches and functions for C and Fortran order... There's a PR with a net negative line count of ~70 lines waiting there...

**Comment by njsmith** [comment] 2016-02-02 16:19
@seberg: the nice thing is that we even have a special type for indices
(intp), so if someone wants a 64 bit index on a 32 bit system we can just
point to the name of the type :-)

**Comment by seberg** [comment] 2016-02-02 17:18
@njsmith usually I am the one I don't understand ;), but np.intp is 32bits on 32bit systems. Anyway, it does not matter....

**Comment by WeatherGod** [comment] 2016-02-02 17:54
I am new to the C api. Looking at the documentation for PyArray_FromAny(),
it says that it should be protected by PyArray_CheckFromAny(), but it is
protected by PyArray_Check() instead. Is that another problem?

**Comment by njsmith** [comment] 2016-02-02 18:08
@seberg: I mean, if someone asks for 64 bits on a 32 bit system, then we can say sorry, indices are 32 bits, look at this type here, it says so.

**Comment by WeatherGod** [comment] 2016-02-02 18:22
Ok, I have a prototype fix working. Let me put that strawman up as a PR and we can take this discussion over there and poke the heck out of it.

**Comment by WeatherGod** [comment] 2016-02-02 18:32
Oooh, as a side note, the same bug happens in np.ravel_multi_index().

**Comment by gfyoung** [comment] 2016-02-02 18:36
Perhaps you should tackle that one too in your PR :)

**Comment by seberg** [comment] 2016-02-02 18:46
And I thought I remembered a segfault/floating point exception in that one that I never fixed in years ;).

**Comment by WeatherGod** [comment] 2016-02-02 18:47
PR is at #7170.

**Comment by mattip** [comment] 2018-08-31 08:08
It seems discussion is needed, perhaps as mentioned in [this comment](https://github.com/numpy/numpy/pull/11684#issuecomment-411478299) failure is more consistent here?

**Comment by mattip** [comment] 2018-10-10 14:29
The call `np.asarray([])` will return a float array, which cannot be used for indexing. So the original premise, that `np.unravel_index([], (10, 12))` should succeed, is not consistent with `np.asarray`. PR #11684 improves the error messages for empty and float input.

**Closed** 2019-04-18 12:17 UTC
