### ISSUE TITLE
BUG: .tolist() not changing numpy scalars to Python scalars

### ISSUE THREAD

**Issue by TzipHoro** [numpy/numpy#25172] opened 2023-11-17 16:15 UTC
### Describe the issue:

I recently upgraded my project from numpy 1.23.1 to numpy 1.26.1. After doing so array.tolist() is only converting some of the int64 values to int's.

### Reproduce the code example:

```python
import numpy as np
import pandas as pd

df = pd.DataFrame(...)  # df.dtypes == int64, object, object, object, object
records = df.to_records(index=False)  # returns an np.ndarray
records_list = records.tolist()  # all except for 1 of the int64 values got converted to int
```

### Runtime information:

numpy.version == 1.26.1
sys.version == 3.10.11

**Comment by seberg** [comment] 2023-11-17 16:22
Thanks for reporting, but it will be pandas that changed, not NumPy.  There isn't anything we can about that really, it is a known pandas issue that they return object arrays, I am not sure if a more convenient conversion has ben created.

**Comment by TzipHoro** [comment] 2023-11-17 17:04
My pandas version did not change. It works as expected when I roll back the numpy version.

**Comment by seberg** [comment] 2023-11-17 18:06
Hmmm, really?  In that case, please try to give more details, because I don't believe `.tolist()` is the problem `records` is.  That goes through `np.rec.fromarrays` which might have actually changed.

**Comment by vxst** [comment] 2023-11-21 11:42
I can not reproduce your error. 
```python
import numpy as np
import pandas as pd


print(f"numpy: {np.__version__}")
print(f"pandas: {pd.__version__}")
# numpy: 1.26.1
# pandas: 2.1.3

data = {
    "int_column": pd.Series([1, 2, 3], dtype='int64'),
    "obj_column1": pd.Series(['a', 'b', 'c'], dtype='object'),
    "obj_column2": pd.Series(['x', 'y', 'z'], dtype='object'),
    "obj_column3": pd.Series(['dog', 'cat', 'bird'], dtype='object'),
    "obj_column4": pd.Series(['apple', 'banana', 'cherry'], dtype='object')
}

df = pd.DataFrame(data)
print(df.dtypes)

# int_column      int64
# obj_column1    object
# obj_column2    object
# obj_column3    object
# obj_column4    object

records = df.to_records(index=False)
records_list = records.tolist()

print(f"{type(records_list[0][0])}, {type(records_list[1][0])}, {type(records_list[2][0])}")
# <class 'int'>, <class 'int'>, <class 'int'>
```


As you can see, in an environment with Python 3.10 and numpy 1.26.1, all items are being converted to int. Could you provide the output of the pip freeze command from your environment? Additionally, please provide a sample of the pandas dataframe data.

**Comment by seberg** [comment] 2023-11-23 09:01
@TzipHoro without a follow-up with more details about the array/dataframes you got here, I don't think we can look into what changed in NumPy here and do anything about this unfortunately.

**Comment by seberg** [comment] 2023-12-22 14:19
No followup, so closing.  For all I know this could have been a bugfix, or unrelated.  Please just open a new issue with the necessary details if it persists.

**Closed by seberg** 2023-12-22 14:19 UTC
Labels: 00 - Bug, 09 - Backport-Candidate

**Comment by ezander** [comment] 2024-10-03 11:21
I have the same error, completely independent of pandas, so I would like to reopen this issue. Here is an MWE:
```
import sys
import numpy as np

x = np.array(["abcde", np.float64(123.456)],dtype=object)
print(type(x.tolist()[1]))
print(type(x[1].item()))
print(np.__version__)
print(sys.version)
```
Outputs on my system:
```
<class 'numpy.float64'>
<class 'float'>
1.26.4
3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
```

**Comment by seberg** [comment] 2024-10-03 11:51
You are placing a `float64` into an object dtype array.  `object` dtype holds arbitrary objects, so it doesn't ever unpack with `.item()` or `.tolist()` (it would have to do so recursively?).
The second one unpacks the `float64` scalar.

**Comment by ezander** [comment] 2024-10-03 12:05
I'm aware of that, but I don't see how that matters. The documentation of `tolist` says:

> Return a copy of the array data as a (nested) Python list. Data items are converted to the nearest compatible builtin Python type, via the [item](https://numpy.org/doc/1.26/reference/generated/numpy.ndarray.item.html#numpy.ndarray.item) function.

So, I expect it to return something along the lines of `[v.item() for v in x]` (somewhat simplified, of course). 

Another quote from the docs:
> For a 1D array, a.tolist() is almost the same as list(a), except that tolist changes numpy scalars to Python scalars:

And I don't see any exception for object ndarrays here.

**Comment by seberg** [comment] 2024-10-03 12:09
:shrug: that is fair, but asking for a more precise documentation.  The sentence can probably be tweaked slightly to not go into too much detail, but point out that this is true only for most dtypes.
