### ISSUE TITLE
Failure to load .npy file with structured dtype and metadata

### ISSUE THREAD

**Issue by colingavin** [numpy/numpy#14142] opened 2019-07-28 18:43 UTC
The dtype description in an NPY file can be written in a way that prevents the file from being read. The attached array in [bad_array.pkl.zip](https://github.com/numpy/numpy/files/3439471/bad_array.pkl.zip) exhibits this problem. In this case the written dtype is `[('id', '|V16'), ('has_fit', '|b1'), ('timeax', ('|O', {'vlen': dtype('float64')})), ('', '|V8'), ('profile', ('|O', {'vlen': dtype('float64')})), ('', '|V8'), ('area', '<f8')]`. 

(Note that it was obtained from via h5py - if this is an issue with the format of the arrays produced by that library, I'm happy to file a bug there instead.)

### Reproducing code example:

```python
import numpy as np
import pickle
import io

with open('bad_array.pkl', 'rb') as f:
    arr = pickle.load(f)

buf = io.BytesIO()
np.save(buf, arr)
buf.seek(0)
np.load(buf)
```

### Error message:

```
Traceback (most recent call last):
  File "scripts/badnpy.py", line 11, in <module>
    np.load(buf)
  File "/Users/colingavin/Code/908/clarent2/algo/py/.venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/Users/colingavin/Code/908/clarent2/algo/py/.venv/lib/python3.7/site-packages/numpy/lib/format.py", line 712, in read_array
    shape, fortran_order, dtype = _read_array_header(fp, version)
  File "/Users/colingavin/Code/908/clarent2/algo/py/.venv/lib/python3.7/site-packages/numpy/lib/format.py", line 578, in _read_array_header
    d = safe_eval(header)
  File "/Users/colingavin/Code/908/clarent2/algo/py/.venv/lib/python3.7/site-packages/numpy/lib/utils.py", line 1139, in safe_eval
    return ast.literal_eval(source)
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 74, in _convert
    return list(map(_convert, node.elts))
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 72, in _convert
    return tuple(map(_convert, node.elts))
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 72, in _convert
    return tuple(map(_convert, node.elts))
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 79, in _convert
    map(_convert, node.values)))
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/Users/colingavin/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x10b965a58>
```

### Numpy/Python version information:

1.17.0 3.7.2 (default, Jul 14 2019, 10:22:38) 
[Clang 9.0.0 (clang-900.0.39.2)]

**Comment by eric-wieser** [comment] 2019-07-28 19:00
Loads just fine on 1.15.4 + 64-bit windows, looks like a regression

**Comment by seberg** [comment] 2019-07-28 19:43
1.17.x and 1.16.2 I am seeing a `No error set` when coercing the dtype.

**Comment by eric-wieser** [comment] 2019-07-28 19:43
No issues on 1.18.0.dev0+84e8412 + python 3.5 either. Perhaps only the release has the problem, or perhaps it's a 3.7 issue

**Comment by seberg** [comment] 2019-07-28 19:44
Oh, hmmm, maybe then it is a python version related thing, interesting. I was testing with 3.7:
```
np.dtype([('id', '|V16'), ('has_fit', '|b1'), ('timeax', ('|O', {'vlen': np.dtype('float64')})), ('', '|V8'), ('profile', ('|O', {'vlen': np.dtype('float64')})), ('', '|V8'), ('area', '<f8')])
```
resulting in no error set returns.

**Comment by eric-wieser** [comment] 2019-07-28 19:46
On 3.5 and 84e8412, that gives `ValueError: invalid shape in fixed-type tuple. For some reason the pickle does not cause that error

**Comment by seberg** [comment] 2019-07-28 19:49
Oh, interesting, on python 2.7, I get a simple invalid datatype error, on 3.7 I get "no error set", I had not tested the pickle, I can reproduce the error on python 3.7 both with 16.2 and master.

**Comment by eric-wieser** [comment] 2019-07-28 21:33
My hunch is the cause is this line:
https://github.com/numpy/numpy/blob/edf8a5f70bd946135a07bf8b1eada5feddef4b94/numpy/core/src/multiarray/descriptor.c#L501

which calls `print` while an exception is in flight.

**Comment by eric-wieser** [comment] 2019-07-28 21:33
Yep, that fixed it

**Comment by seberg** [comment] 2019-07-29 00:06
Ah, nice, thanks. Guess I can close this then.

**Comment by eric-wieser** [comment] 2019-07-29 00:08
Don't think we can close this, the problem I solved is the one you discovered, not the one this issue reports

**Comment by seberg** [comment] 2019-07-29 00:09
Ohh, sorry. Somewhat thought those were the same, heh...

**Comment by charris** [comment] 2019-08-20 18:00
Pushing off to 1.17.2

**Comment by tacaswell** [comment] 2019-09-17 13:19
@colingavin What version of h5py are you using?  My _guess_ is that you are using close to master?

I think this is related to https://github.com/h5py/h5py/issues/1307 .

If you look at the descr on that array, you get back  

```
In [115]: arr.dtype.descr
Out[115]: 
[('id', '|V16'),
 ('has_fit', '|b1'),
 ('timeax', ('|O', {'vlen': dtype('float64')})),
 ('', '|V8'),
 ('profile', ('|O', {'vlen': dtype('float64')})),
 ('', '|V8'),
 ('area', '<f8')]

```

In h5py 2.10 we started to use the metadata feature of dtypes to stuff a bit of extra information into the dtype.

You can reproduce this via

```python
import numpy as np
import io


dt = np.dtype({'names': ['a', 'b'], 'formats':  [float, np.dtype('S3', metadata={'some': 'stuff'})]})

arr = np.array([(1, 'abc'), (2, 'def')], dtype=dt)
buf = io.BytesIO()
np.save(buf, arr)
buf.seek(0)
np.load(buf)
```

There is also some oddity that metadata is included in the descr when accesses the desrc of a compound dataset, but if you look at each of the component dtypes independently, does not.

```python
In [121]: dt.descr
Out[121]: [('a', '<f8'), ('b', ('|S3', {'some': 'stuff'}))]

In [122]: dt['a'].descr
Out[122]: [('', '<f8')]

In [123]: dt['b'].descr
Out[123]: [('', '|S3')]

In [124]: 
```

It is not clear to me if the bug is the meta-data _being_ included in the compound descr or it _not_ being written in the individual and `descr_to_dtype` not handling this correctly.

**Comment by seberg** [comment] 2019-09-17 16:47
I would not be surprised if `metadata` is a can of worms... I was curious if we can't just deprecate it ;). OTOH, as long as h5py does not expect the metadata to survive any calculations, it should be fine mostly.

**Comment by colingavin** [comment] 2019-09-17 16:50
@tacaswell I'm on h5py 2.9.0.

**Comment by seberg** [comment] 2019-09-17 18:58
OK, this is a possible fix, there are some iffy things, such as what to do when the metadata cannot be stored safely. Should we somehow auto fall-back to pickling, since that is what happens with object arrays, or is it OK to tell users they will have to pickle it?

<details> <summary> Diff adding metadata parsing and storing `np.lib.format` functions. </summary>

```diff
diff --git a/numpy/lib/format.py b/numpy/lib/format.py
index 3bf818812..e0442d742 100644
--- a/numpy/lib/format.py
+++ b/numpy/lib/format.py
@@ -269,7 +269,9 @@ def dtype_to_descr(dtype):
         # dtype().
         return dtype.descr
     else:
-        return dtype.str
+        if dtype.metadata is None:
+            return dtype.str
+        return dtype.str, dtype.metadata
 
 def descr_to_dtype(descr):
     '''
@@ -284,12 +286,27 @@ def descr_to_dtype(descr):
         # No padding removal needed
         return numpy.dtype(descr)
     elif isinstance(descr, tuple):
+        if type(descr[-1]) is dict:
+            # We have stored metadata:
+            if len(descr) == 2:
+                dt = descr_to_dtype(descr[0])
+            else:
+                dt = descr_to_dtype(descr[:-1])
+            return numpy.dtype(dt, metadata=descr[-1])
         # subtype, will always have a shape descr[1]
         dt = descr_to_dtype(descr[0])
         return numpy.dtype((dt, descr[1]))
+
     fields = []
     offset = 0
     for field in descr:
+        if type(field[-1]) is dict:
+            # this is a metadata
+            metadata = field[-1]
+            field = field[:-1]
+        else:
+            metadata = None
+
         if len(field) == 2:
             name, descr_str = field
             dt = descr_to_dtype(descr_str)
@@ -297,6 +314,9 @@ def descr_to_dtype(descr):
             name, descr_str, shape = field
             dt = numpy.dtype((descr_to_dtype(descr_str), shape))
 
+        if metadata is not None:
+            dt = numpy.dtype(dt, metadata=metadata)
+
         # Ignore padding bytes, which will be void bytes with '' as name
         # Once support for blank names is removed, only "if name == ''" needed)
         is_pad = (name == '' and dt.type is numpy.void and dt.names is None)
@@ -406,7 +426,17 @@ def _write_array_header(fp, d, version=None):
     header = ["{"]
     for key, value in sorted(d.items()):
         # Need to use repr here, since we eval these when reading
-        header.append("'%s': %s, " % (key, repr(value)))
+        value_repr = repr(value)
+        header.append("'%s': %s, " % (key, value_repr))
+        if (key == "descr"):
+            # The dtype could contain metadata, test if we can load it:
+            try:
+                safe_eval(value_repr)
+            except:
+                raise TypeError(
+                    "Unable to store array with this dtype in npy format; "
+                    "the dtype is: {}".format(value_repr))
+
     header.append("}")
     header = "".join(header)
     header = _filter_header(header)
```

**Comment by seberg** [comment] 2019-09-17 18:59
Hmmm, or, we drop metadata and give a warning during saving to npy?

**Comment by seberg** [comment] 2019-09-17 20:21
Ah... I tried with @tacaswell dtype, but the real dtype that causes the issue includes a dtype in the metadata, so that `safe_eval` does not just work. It seems to me that dropping the metadata with a warning to use pickle if that is not desired may be best. But it is also very confusing.

**Comment by tacaswell** [comment] 2019-09-17 22:18
Ah, I didn't read the dtype carefully enough, thought it was strings, but it is vlen floats, same symptom, different cause, sorry about that.

**Comment by seberg** [comment] 2019-09-17 22:25
Would just supporting strings be helpful? It seems a tricky issue, since we cannot support arbitrary objects really (unless we auto-fallback to pickle here, which may be OK).

**Comment by seberg** [comment] 2019-09-27 05:09
For starters, I think I tend to "do not try to be smart", so probably just fail when saving, since if you cannot load it, saving is pretty useless (even if in theory editing the file to load it is doable). (I could be convinced that trying to save simple metadata is OK, if that is very useful)

But, even if we fail with a message: Please drop metadata or use pickle, I cannot find a good way to drop the metadata. So if there is a real userbase being hit by that, we probably need a better solution...

**Comment by seberg** [comment] 2019-11-20 22:36
We could probably add a dtype method that returns a new dtype without metadata. It is tricky mainly because structured dtypes need to recursively drop the metadata. At least it adds API in a pretty local place.

**Comment by mattip** [comment] 2019-11-21 23:03
I think a good first step would be to raise an error or at the very least warn when trying to save a dtype with metadata, since we cannot currently load such a file (so this is a bug in round-tripping data)

**Comment by micheles** [comment] 2020-04-29 04:21
For what is worth, this issue is affecting me as well. For various reasons I need to convert composite arrays from .hdf5 into .npz and I cannot do that anymore with hdf5 2.10.0. Here is an example:
```python
import h5py
import numpy
dt = [('id', '<S20'), ('ordinal', numpy.uint32)]
arr = numpy.array([(b'a11', 1), (b'a12', 2)], dt)
with h5py.File('/tmp/x.h5', 'w') as h:
    h['array'] = arr
with h5py.File('/tmp/x.h5', 'r') as h:
    arr1 = h['array'][()]
numpy.savez('/tmp/x.npz', array=arr1)
arr2 = numpy.load('/tmp/x.npz')['array']

~/py38/lib/python3.8/site-packages/numpy/lib/format.py in descr_to_dtype(descr)
    304         # subtype, will always have a shape descr[1]
    305         dt = descr_to_dtype(descr[0])
--> 306         return numpy.dtype((dt, descr[1]))
    307     fields = []
    308     offset = 0

ValueError: invalid shape in fixed-type tuple.
```
The problem is in the metadata:
```python
In [2]: arr1.dtype.descr
Out[2]: [('id', ('|S20', {'h5py_encoding': 'ascii'})), ('ordinal', '<u4')]
```
What do you suggest as a workaround?

**Comment by charris** [comment] 2020-05-16 23:22
Well, this needs fixing, but it won't be ready for the 1.19.x branch. Putting `backport candidate` on it as a reminder for 1.19.

**Comment by charris** [comment] 2020-11-23 19:13
Hate to push this off again. Anyone have ideas for a fix?

**Comment by seberg** [comment] 2020-11-23 19:32
For what its worth, the original snippet, does give a warning now when saving:
```
/home/sebastian/.local/lib/python3.8/site-packages/numpy/lib/format.py:350: UserWarning: metadata on a dtype may be saved or ignored, but will raise if saved when read. Use another form of storage.
```
I do not have a fix, the quickest fix might be to drop the metadata (after the warning). That requires a function which recursively drops the metadata, not sure how quick that is to write.

**Comment by charris** [comment] 2020-11-23 20:10
Guess I'll just push this off again.

**Comment by seberg** [comment] 2021-05-05 18:33
@tacaswell sorry that this got dragged so long, is this still a major issue or was the warning enough to tape it over a bit or do we have to keep prioritizing it? (By now it seems unlikely we can prioritize for 1.21 though :()

**Comment by mattip** [comment] 2021-05-05 18:36
Also: is this really a regression?

**Comment by charris** [comment] 2021-11-16 00:59
Well, heck. Pushed it off again.

**Comment by seberg** [comment] 2022-05-04 16:32
Will push this one of (as discussed also in the triage meeting), but I am not sure how important this issue is still/now, so please ping to bump it if necessary.

**Comment by charris** [comment] 2024-08-01 15:06
@tacaswell Is this still a problem?

**Comment by tacaswell** [comment] 2024-08-01 18:01
Yes, but now with an extra warning:

```
In [2]: import numpy as np
   ...: import io
   ...:
   ...:
   ...: dt = np.dtype({'names': ['a', 'b'], 'formats':  [float, np.dtype('S3', metadata={'some': 'stuff'})]})
   ...:
   ...: arr = np.array([(1, 'abc'), (2, 'def')], dtype=dt)
   ...: buf = io.BytesIO()
   ...: np.save(buf, arr)
   ...: buf.seek(0)
   ...: np.load(buf)
/home/tcaswell/.virtualenvs/cp313/lib/python3.13/site-packages/numpy/lib/format.py:380: UserWarning: metadata on a dtype is not saved to an npy/npz. Use another format (such as pickle) to store it.
  d['descr'] = dtype_to_descr(array.dtype)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 11
      9 np.save(buf, arr)
     10 buf.seek(0)
---> 11 np.load(buf)

File ~/.virtualenvs/cp313/lib/python3.13/site-packages/numpy/lib/_npyio_impl.py:488, in load(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)
    485         return format.open_memmap(file, mode=mmap_mode,
    486                                   max_header_size=max_header_size)
    487     else:
--> 488         return format.read_array(fid, allow_pickle=allow_pickle,
    489                                  pickle_kwargs=pickle_kwargs,
    490                                  max_header_size=max_header_size)
    491 else:
    492     # Try a pickle
    493     if not allow_pickle:

File ~/.virtualenvs/cp313/lib/python3.13/site-packages/numpy/lib/format.py:809, in read_array(fp, allow_pickle, pickle_kwargs, max_header_size)
    807 version = read_magic(fp)
    808 _check_version(version)
--> 809 shape, fortran_order, dtype = _read_array_header(
    810         fp, version, max_header_size=max_header_size)
    811 if len(shape) == 0:
    812     count = 1

File ~/.virtualenvs/cp313/lib/python3.13/site-packages/numpy/lib/format.py:678, in _read_array_header(fp, version, max_header_size)
    676     raise ValueError(msg.format(d['fortran_order']))
    677 try:
--> 678     dtype = descr_to_dtype(d['descr'])
    679 except TypeError as e:
    680     msg = "descr is not a valid dtype descriptor: {!r}"

File ~/.virtualenvs/cp313/lib/python3.13/site-packages/numpy/lib/format.py:337, in descr_to_dtype(descr)
    335 if len(field) == 2:
    336     name, descr_str = field
--> 337     dt = descr_to_dtype(descr_str)
    338 else:
    339     name, descr_str, shape = field

File ~/.virtualenvs/cp313/lib/python3.13/site-packages/numpy/lib/format.py:327, in descr_to_dtype(descr)
    324 elif isinstance(descr, tuple):
    325     # subtype, will always have a shape descr[1]
    326     dt = descr_to_dtype(descr[0])
--> 327     return numpy.dtype((dt, descr[1]))
    329 titles = []
    330 names = []

ValueError: invalid shape in fixed-type tuple.

In [3]: np.__version__
Out[3]: '2.1.0.dev0+git20240725.0819378'
```

**Comment by seberg** [comment] 2024-08-01 18:05
Hmmmm, I somehow thought I once wrote stripping logic, so that it would drop but load.  I guess some half-finished PR somewhere.

**Comment by seberg** [comment] 2024-08-01 18:06
Yeah, https://github.com/numpy/numpy/pull/23371 should cause all metdata to be dropped, so it isn't clear to me why it cannot be loaded.  It would seem that there must be some whole in the logic.

**Comment by seberg** [comment] 2024-08-08 18:48
Haha, the change was fine... The problem is that the code just failed to actually _use_ the cleaned up version...

**Closed** 2024-08-08 20:53 UTC
Labels: 00 - Bug, 06 - Regression, component: numpy.dtype
