### ISSUE TITLE
multinomial casts input to np.float64

### ISSUE THREAD

**Issue by QCaudron** [numpy/numpy#8317] opened 2016-11-25 22:19 UTC
`np.random.multinomial` seems to cast its second argument `pvals` to an array of dtype float64. Whilst this isn't an issue in and of itself, I've come across an interesting scenario where I have an array of dtype float32 whose sum is `0.99999994`, and when it gets cast to float64, its sum is now `1.0000000222053895`, which causes `np.random.multinomial` to raise `ValueError: sum(pvals[:-1]) > 1.0`. 

For a little context, I have an array of dtype float32 because it's come off the GPU, where single precision calculations are a great deal faster.

**Comment by charris** [comment] 2016-11-25 23:37
Hmm, I suspect the float32 sum is off due to rounding. Not by much, though
```
In [18]: nextafter(float32(1), float32(0))
Out[18]: 0.99999994
```
The question is, what is pvals[-1]? If it is large I suspect another problem somewhere. How many values are in pvals?

**Comment by QCaudron** [comment] 2016-11-26 00:07
pvals[-1] is typically also very small, along with most of the other 64 terms in pvals ( one or two terms tend to dominate ).

Happy to upload a .npy if that'd help.

**Comment by charris** [comment] 2016-11-26 00:34
> Happy to upload a .npy if that'd help.

This definitely sounds like a roundoff problem in computing the sum, and maybe in normalizing also. Not sure what your best bet for a fix is, probably depends on the details of your application.

**Comment by QCaudron** [comment] 2016-11-26 00:36
I'm dealing with it application-side; I just thought it might be worth noting, as this is a bit of a surprising behaviour - certainly took me a while to work out what was going on. Is there any reason a float32 array wouldn't be acceptable to `np.random.multinomial` ?

**Comment by charris** [comment] 2016-11-26 00:43
> Is there any reason a float32 array wouldn't be acceptable to np.random.multinomial ?

No. But this is a classic setup for floating point roundoff errors: lots of small values and a couple of big ones. All the small values loose precision when they are added to the big ones. After this you won't be surprised, you will expect it ;)

**Comment by ericmjl** [comment] 2017-07-28 13:25
Many apologies for resurrecting an old thread here, but I noticed that PyMC3 gets issues with numpy's multinomial function when working with float32s returned from the GPU. Is there a reason for explicit casting to float64, rather than simply letting the floats be what they are?

**Comment by ericmjl** [comment] 2017-08-02 12:32
@QCaudron may I ask, what's the fix that you've been working with to get around the multinomial probability rounding problems?

**Comment by QCaudron** [comment] 2017-08-02 16:19
@ericmjl I'm afraid I don't remember the context here, and thus can't provide a workaround ;) My intuition says I cast `pvals` to float64, normalised the array to sum to one, and passed that in.

**Comment by leachim** [comment] 2018-11-07 17:59
I happened to run into this issue today. Wondering whether there is any reason for casting the array to float64? This should probably be fixed in numpy itself.

**Comment by escorciav** [comment] 2019-03-14 06:35
Similar to [leachim](https://github.com/numpy/numpy/issues/8317#issuecomment-436718241) I faced this bug recently. Is there a way to get this fixed?

**Comment by bashtage** [comment] 2019-04-10 22:38
Could someone post an example of an array the reproduces this issue?  I haven't been able to with random arrays.

**Comment by escorciav** [comment] 2019-04-11 09:10
The following snippet should break in a considerable amount of time (<< 10 mins). You can take the tricky case then.

```python
import torch
import numpy as np

while True:
    x = torch.rand(100)
    y = x.numpy()
    y /= y.sum()
    neg_video_ind = np.random.multinomial(1, y)
```

I replicate the (buggy) behavior in my machine, old version of torch and numpy, and google-colab. Go for [this](https://colab.research.google.com/drive/1YlYvOtTkzZqnMEykfdvFniuUKypdd0at) if you only need a 100 vector and not have time to install anything.

**Comment by bashtage** [comment] 2019-04-11 22:18
This allowed it to be easily replicated -- hadn't realized that I needed a relatively large pval array.

**Comment by bashtage** [comment] 2019-04-12 06:16
This always triggers
```
x = np.array([9.9e-01, 9.9e-01, 1.0e-09, 1.0e-09, 1.0e-09, 1.0e-09, 1.0e-09,
       1.0e-09, 1.0e-09, 1.0e-09], dtype=np.float32)
y = x / x.sum()
np.random.multinomial(1, y)
```

**Closed** 2021-02-27 01:04 UTC
Labels: component: numpy.random

**Comment by olfMombach** [comment] 2021-03-31 23:10
I don't really see how that fixes the problem
