### ISSUE TITLE
numpy.ma.mean - axis argument does not accept tuple like numpy.mean

### ISSUE THREAD

**Issue by k8HR8X** [numpy/numpy#6844] opened 2015-12-17 01:43 UTC
numpy  1.10.1 py27_0
Linux carson 3.13.0-71-generic #114~precise1-Ubuntu SMP Tue Dec 1 19:37:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rgommers** [comment] 2015-12-17 05:35
Works for me with numpy 1.10.2:

    >>> x = np.ma.ones((4, 3, 2))
    >>> np.ma.mean(x, axis=(0,1))
    masked_array(data = [1.0 1.0],
                 mask = [False False],
           fill_value = 1e+20)

    >>> x.mean(axis=(0,1))
    masked_array(data = [1.0 1.0],
                 mask = [False False],
           fill_value = 1e+20)

So closing. If I'm missing your point, please give an example that we can reproduce.

**Closed by rgommers** 2015-12-17 05:35 UTC
