### ISSUE TITLE
BUG: int by numpy.int64 division incorrect for 2**63 < dividend < 2**64

### ISSUE THREAD

**Issue by ceu1e** [numpy/numpy#22457] opened 2022-10-20 03:24 UTC
### Describe the issue:

Dividing (e.g.) (2**64-1) // 3 works as expected if 3 is an int, but produces a float result if 3 is a numpy.int64.
Consequently, the corresponding modulus calculation produces an incorrect result (also float).

This seems to occur just for dividends in the range of `2**63` to `2**64`.

Division of int by numpy.int64 should return the correct integer result for the full range of dividend values.

### Reproduce the code example:

```python
import numpy

py3 = 3
npy3 = numpy.int64(3)
n1 = 2**64-1
n2 = 2**63+1
n3 = 2**64+2
n4 = 2**63-2
n5 = 2**128-1
n6 = 2**128+2
print(f"n1 // py3 = {n1 // py3}, n1 % py3 = {n1 % py3}, n1 // npy3 = {n1 // npy3}, n1 % npy3 = {n1 % npy3}")
print(f"n2 // py3 = {n2 // py3}, n2 % py3 = {n2 % py3}, n2 // npy3 = {n2 // npy3}, n2 % npy3 = {n2 % npy3}")
print(f"n3 // py3 = {n3 // py3}, n3 % py3 = {n3 % py3}, n3 // npy3 = {n3 // npy3}, n3 % npy3 = {n3 % npy3}")
print(f"n4 // py3 = {n4 // py3}, n4 % py3 = {n4 % py3}, n4 // npy3 = {n4 // npy3}, n4 % npy3 = {n4 % npy3}")
print(f"n5 // py3 = {n5 // py3}, n5 % py3 = {n5 % py3}, n5 // npy3 = {n5 // npy3}, n5 % npy3 = {n5 % npy3}")
print(f"n6 // py3 = {n6 // py3}, n6 % py3 = {n6 % py3}, n6 // npy3 = {n6 // npy3}, n6 % npy3 = {n6 % npy3}")
```

### NumPy/Python version information:

1.23.4 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

**Comment by LeonaTaric** [comment] 2022-10-20 03:38
well, how do you find the bug? (Such as "In unit test")

**Comment by mattip** [comment] 2022-10-20 06:16
When using numpy your values are automatically cast to numpy scalars. The casting cannot follow the python rules about ints (no value is too big, silently convert to bignum form where the int is represented as a tuple of int values) and instead must use numpy rules. `2**64 -1` is too big for a np.int64, so the expression `(2 **64 - 1) // np.int64(3)` becomes `np.double(2 ** 64 - 1)` // np.int64(3)`.

**Comment by seberg** [comment] 2022-10-20 06:46
Closing as duplicate of gh-12525 and many others.  There are two "problems", one is our weird promotion, the other is that we use uint64 to begin with...

**Closed by seberg** 2022-10-20 06:46 UTC
Labels: 15 - Discussion, 57 - Close?

**Comment by mattip** [comment] 2022-10-20 16:02
Also see [NEP 50](https://numpy.org/neps/nep-0050-scalar-promotion.html)

**Comment by mattip** [comment] 2022-10-20 16:04
If it is speed you want, and pure python code is what you are running, [PyPy](https://www.pypy.org/) may work for you.
