### ISSUE TITLE
Weird TypeError: dist must be a Distribution instance in get_atlas_version

### ISSUE THREAD

**Issue by amueller** [numpy/numpy#7235] opened 2016-02-12 19:36 UTC
When installing the atlas dev packages on travis, I get a really weird error:

```
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/numpy/distutils/system_info.py", line 1409, in get_atlas_version

    c = cmd_config(Distribution())

  File "/home/travis/miniconda/envs/testenv/lib/python3.5/distutils/cmd.py", line 57, in __init__

    raise TypeError("dist must be a Distribution instance")

TypeError: dist must be a Distribution instance
```
See [here](https://travis-ci.org/scikit-learn/scikit-learn/jobs/108684942#L501).

This is the numpy dev wheel. Updating setuptools didn't help.
Any ideas?

**Comment by rgommers** [comment] 2016-02-12 22:30
Hmm, might be caused by the recent switch to ``setuptools``: https://bitbucket.org/pypa/setuptools/issues/73/typeerror-dist-must-be-a-distribution

I'll try to investigate tomorrow.

**Comment by rgommers** [comment] 2016-02-13 17:37
``distutils`` patch that should fix this: http://bugs.python.org/issue23102

Related ``setuptools`` issues:
- https://bitbucket.org/pypa/setuptools/issues/73/typeerror-dist-must-be-a-distribution
- https://bitbucket.org/pypa/setuptools/issues/309
- https://bitbucket.org/pypa/setuptools/issues/488/extension-instance-gets-multiple

Setuptools issue 488 is the only issue that's marked fixed, and is present in setuptools 19.6. However the TravisCI failure linked above was with setuptools 19.6.2, so that wasn't it.

**Comment by rgommers** [comment] 2016-02-13 17:38
Seems to depend on some package importing ``setuptools`` at the wrong time, or ``Cython`` simply being installed, or ...

**Comment by rgommers** [comment] 2016-02-13 19:51
I can reproduce the issue locally now. Took a while, because ``build_ext`` is not triggering ``import setuptools`` in scikit-learn's setup.py. Looks like a ``setuptools`` bug triggered by recent changes in that ``setup.py``. This happens not only with numpy master, but also with 1.11.0b3 and 1.10.4. I'm surprised that no one has run into this before.

**Comment by rgommers** [comment] 2016-02-13 20:01
Okay, the issue is due to https://github.com/scikit-learn/scikit-learn/pull/5492 which is not included in scikit-learn 0.17 (the latest released version), and it's only triggered for ``pip`` installs. So it makes sense that not many people have run into this yet. I'd say the real bug is in ``setuptools`` but for all practical purposes it needs fixing in scikit-learn. I'll see if I can fix things up.

**Comment by rgommers** [comment] 2016-02-13 20:57
Fixed by https://github.com/scikit-learn/scikit-learn/pull/6354, closing this.

**Closed by rgommers** 2016-02-13 20:57 UTC
Labels: component: numpy.distutils

**Comment by amueller** [comment] 2016-02-15 17:44
great, thanks :)
