### ISSUE TITLE
Possible regression with inplace min/max in between 1.20 and 1.21

### ISSUE THREAD

**Issue by groutr** [numpy/numpy#19694] opened 2021-08-17 19:10 UTC
There appears to be possible regression in Numpy 1.21 in np.minimum/maximum when operating inplace on an array. Tests conducted with numpy 1.20 on one affected machine produced the expected results. I think it is reasonable to think that other ufuncs might also be affected.

This regression results in a strange banding pattern in the output array. This is best illustrated by @TrevorGrout-NOAA in his comment here: https://github.com/mapbox/rasterio/issues/2245#issuecomment-899615459. Observed, initially with rasterio (https://github.com/mapbox/rasterio/issues/2245), I was able to trace it back to a call to np.minimum/maximum.

A workaround is to remove the `out=` argument from the call the np.minimum/maximum, allowing it to allocate a new output array.

### Reproducing code example:

To test the issue, please download the archive linked in this comment:
https://github.com/mapbox/rasterio/issues/2245#issuecomment-888071383
Inside that archive, there is a npz file that contains a dump of the arrays from the function in this comment: https://github.com/mapbox/rasterio/issues/2245#issuecomment-887665426
(The array dump was kindly provided by @remi-braun who initially reported the issue and has helped troubleshoot the issue on the rasterio issue tracker)
```python
import numpy as np
import matplotlib.pyplot as plt

arrs = np.load('dumparrs.npz')
merged_data, new_data, merged_mask, new_mask = arrs['1_input']

mask = np.empty_like(merged_data, dtype='bool')
np.logical_or(merged_mask, new_mask, out=mask)
np.logical_not(mask, out=mask)
np.maximum(merged_data, new_data, out=merged_data, where=mask)
plt.imshow(merged_data.squeeze())
```

### NumPy/Python version information:
In each case that the issue was observed, numpy 1.21. 
For @remi-braun, it was encountered inside docker (on windows?) but could not be reproduced on windows itself. Numpy was installed via pip.
For @woest and @TrevorGrout-NOAA, both were using windows. I know @TrevorGrout-NOAA was using Python 3.9 and numpy packages available on conda-forge.

After posting on the numpy gitter, a response pointed out that numpy 1.21 uses SIMD more heavily and the speculation was that perhaps it was somehow related to this issue. This regression may be very specific to certain types of hardware. For example, I am unable to reproduce these issues on my hardware (i5-8350U), however, @TrevorGrout-NOAA, with a near identical processor (i5-8365U) is affected by this issue.
The output of np.libs.utils._opt_info() for both of our machines is:
```
SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C* FMA3* AVX2* AVX512F? AVX512CD? AVX512_SKX? AVX512_CLX? AVX512_CNL?
```

**Comment by seberg** [comment] 2021-08-17 19:27
@groutr thanks for the report. Could you have a quick check with NumPy 1.21.2?  Because we had pretty bad bug when using `where` in combination with certain multi-dimensional outputs.  And frankly, that seems a more likely candidate than SIMD to me.

**Comment by TrevorGrout-NOAA** [comment] 2021-08-17 19:40
Ok, I can confirm that the issue is present in 1.21.1 but appears to be resolved in 1.21.2. 
Thanks @groutr and @seberg

**Comment by seberg** [comment] 2021-08-17 19:47
Great, thanks again for the report.  And sorry about this issue, bugs that can silently corrupt data are terrible :(.

**Closed by seberg** 2021-08-17 19:47 UTC
Labels: 00 - Bug, 06 - Regression

**Comment by groutr** [comment] 2021-08-17 19:49
Thank you for the quick response @seberg.

**Comment by seberg** [comment] 2021-08-17 19:49
For reference: The first bug report (but "just" a crash, so less scary than this one) was: gh-19589, the fix was gh-19600.
