### ISSUE TITLE
Array contiguous change during np.nan_to_num

### ISSUE THREAD

**Issue by sergii-gavrylov** [numpy/numpy#5924] opened 2015-05-28 17:23 UTC
Hello, my current version of numpy is 1.9.2
```python
>>> x = np.array([[1,-np.inf,],[np.nan,4]], order='F')
>>> x
array([[  1., -inf],
       [ nan,   4.]])
>>> x.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
>>> y = np.nan_to_num(x)
>>> y
array([[  1.00000000e+000,  -1.79769313e+308],
       [  0.00000000e+000,   4.00000000e+000]])
>>> y.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
It is not clear to me why CONTIGUOUS flags of the array `y` are different from ones of `x`. I looked at the code in type_check.py on the master branch, and it is different from type_check.py on my machine. So probably it had been already fixed. But still, could anyone point me to a good explanation what the `subok` argument in array creation function is?
I would highly appreciate any clarifications about this nan_to_num behaviour.

**Comment by charris** [comment] 2015-05-28 17:41
Looks like problem with `nan_to_num`. That function creates a copy using `x = array(x, subok=True)`, which should probably also have `order='K'` as an argument. Backward compatibility probably requires adding an `order` keyword to `nan_to_num` in order to fix that.

**Comment by ChanderG** [comment] 2015-08-02 06:50
The function seems to be fine on master. The problem is there in the maintenance/1.9.x branch however. But that copy creation statement ( with the subok=True parameter ) is only in the master.

**Comment by SaurabhJha** [comment] 2015-09-18 16:19
@charris Hi, Can I work on this issue? I am new to Numpy and would like to start with this issue. Thanks.

**Comment by jaimefrio** [comment] 2015-09-18 17:11
You are more than welcome to work on anything you want, Saurabh, no need to ask for permission!

If you need help or guidance, feel free to ask any questions.

**Comment by SaurabhJha** [comment] 2015-09-21 05:36
Hi, I suppose I need to learn Python-C API in order to work on Numpy.

https://docs.python.org/2/c-api/intro.html

Can I just dive in after reading this or do I need to learn other stuff as well. Sorry, haven't worked on a complex code base like this before. Thanks a lot.

**Comment by yashmehrotra** [comment] 2015-09-21 05:50
@SaurabhJha I advice you to dive in right into the code and lookup the C API when required.

**Comment by maniteja123** [comment] 2016-02-02 13:05
Hi, I just tried to reproduce this but seems to be only in Numpy 1.9 but is working fine on master as already mentioned by @ChanderG. It was fixed by https://github.com/numpy/numpy/commit/acbd6a9d4be019629414ec5f9a91c02bce7dec14 .

**Comment by charris** [comment] 2016-02-02 13:54
Thanks for checking @maniteja123, closing then.

**Closed by charris** 2016-02-02 13:54 UTC
Labels: component: numpy.lib, Defect, Easy Fix

**Comment by maniteja123** [comment] 2016-02-02 14:09
Happy to help :-)
