### ISSUE TITLE
parts of the random API missing from intersphinx

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#14359] opened 2019-08-25 19:41 UTC
detected in a couple of doc build issues/PRs in SciPy now, see https://github.com/scipy/scipy/pull/10540#issuecomment-515785664

The `numpy.random` refactor somehow has caused entries in the intersphinx numpy output to go missing. at least `numpy.random.RandomState` and `numpy.random.weibull`, so probably the whole older API is missing (and perhaps the new one as well).

The tracking issue for the workaround in SciPy (explicitly referencing `random.mtrand.<object>` is https://github.com/scipy/scipy/issues/10545

**Comment by rgommers** [comment] 2019-08-25 20:11
okay there's quite a few other issues in the `numpy.random` docs, I'll see if I can send a fix today.

**Comment by Aa88s** [comment] 2019-08-30 23:47
numpy.random

**Comment by rgommers** [comment] 2019-09-01 01:18
gh-14360 doesn't address everything yet, I just discovered that all `np.random.<funcname>` functions are missing from the docs.

**Comment by rgommers** [comment] 2019-09-07 16:59
Left to decide: there's still two namespaces left that look private:

- numpy.random.entropy (contains `random_entropy` and `seed_by_array`, unclear if those need to be public)
- numpy.random.bit_generator (contains only `BitGenerator` as a public object I think)

Left to do:

`doc/source/reference/random/index.rst` is missing links to `numpy.random.<function>`  (e.g. `np.random.seed`, `np.random.randn`). They are completely missing from the docs.

**Comment by bashtage** [comment] 2019-09-13 08:09
> * numpy.random.entropy (contains `random_entropy` and `seed_by_array`, unclear if those need to be public)

I'm not sure these are used anymore after moving to SeedSeq.  They might be removable. The only advantage is that random_entropy ready system entropy to an ndarray.  It predates Python 3.x only and so was needed since there wasn't a good way to universally ready entropy.  IIRC entropy is read from `random` now.

**Comment by mattip** [comment] 2019-09-13 09:08
`entropy.random_entropy` is still used by [`mt19937.pyx`](https://github.com/numpy/numpy/blob/v1.17.2/numpy/random/mt19937.pyx#L170). SeedSequence uses [`randbits`](https://github.com/numpy/numpy/blob/v1.17.2/numpy/random/bit_generator.pyx#L307). Should we move `entropy` to `_entropy` or replace it with `randbits` (mt19967 is legacy, but this is for the case where no seed is provided)?

**Comment by bashtage** [comment] 2019-09-13 09:23
With that one change, then it could be removed.

**Comment by mattip** [comment] 2019-10-15 17:58
`numpy.random.random_integers` and friends are documented via [RandomState](https://numpy.org/devdocs/reference/random/legacy.html#numpy.random.RandomState), i.e. via `numpy.random.RandomState.random_integers`. Since we would like to encourage people not to use these functions directly, I think this is preferable.

**Comment by bashtage** [comment] 2019-10-16 14:14
> `entropy.random_entropy` is still used by [`mt19937.pyx`](https://github.com/numpy/numpy/blob/v1.17.2/numpy/random/mt19937.pyx#L170). ~SeedSequence uses [`randbits`](https://github.com/numpy/numpy/blob/v1.17.2/numpy/random/bit_generator.pyx#L307).~ Should we move `entropy` to `_entropy` or replace it with ~`randbits`~ `SeedSequence().generate_state(RK_STATE_LEN)` (mt19967 is legacy, but this is for the case where no seed is provided)?

I think SS is the right idea here.  Empty to not reproducible so might as well DRY here and remove entropy.

**Comment by mattip** [comment] 2019-11-22 19:01
Is there a way to check that gh-14948 fixes scipy/scipy#10545?

**Comment by rgommers** [comment] 2019-11-24 01:48
> Is there a way to check that gh-14948 fixes scipy/scipy#10545?

discussed with @mattip: this will fix it, let's just merge and then update SciPy after to use inter-sphinx links for the random functions again. 

The Cython changes are the more interesting ones in this PR.

**Comment by charris** [comment] 2019-11-25 23:59
Going to close this as the fix has a 1.18 milestone.

**Closed by charris** 2019-11-25 23:59 UTC
Labels: 00 - Bug, component: Documentation, component: numpy.random
