### ISSUE TITLE
'auto' selection of histogram bins fails in some cases

### ISSUE THREAD

**Issue by seth-a** [numpy/numpy#9327] opened 2017-06-28 21:11 UTC
This is an odd corner case, but there are times using auto to select the number of bins gives only a single bin.

    from pylab import *
    data = zeros(1000)
    data[:100] = 10
    np.histogram(data, bins='auto')

Output is a single bin

     (array([1000]), array([  0.,  10.]))

This must be the result of the sturges/fd estimators since (according to the documentation) auto just takes the max of these two.  It seems like this should fall back to the default number of bins (10 I think), or perhaps sqrt.

**Comment by seth-a** [comment] 2017-06-29 13:37
Looking at this some more it appears to be more than just undesirable behavior, documentation states that 'Auto'  is the "maximum of the 'Sturges' and 'FD' estimators."  Actual code returns the min, `min(_hist_bin_fd(x), _hist_bin_sturges(x))`.

**Comment by seberg** [comment] 2017-06-29 15:44
Yes, its a bug. But the `min` is correct there since that is the width not the number of bins, the problem is that it returns an invalid result for `fd` (0), and then that 0 is turned into 1 as a fail safe. Practically, we probably want to use the other estimator when one fails. Don't remember who implemented this mostly, maybe we can ping them if they are happy to look at it.

**Comment by seberg** [comment] 2017-06-29 15:45
Though the fix should be simple indeed. so if you feel like it, please do give it a shot!

**Comment by seberg** [comment] 2017-07-02 20:37
@nayyarv or @madphysicist want to have a look fix this? Just thought I would ping since you guys worked on this part a lot.

**Comment by nayyarv** [comment] 2017-07-03 06:54
Haha, there are always these unintended side effects I never even considered. The sturges backup was meant to catch situations like this, but i think it works better as max of bins than as min of bandwidth for this very reason.

I'll put something together this evening, but as

**Comment by nayyarv** [comment] 2017-07-03 06:55
Continued
@seberg said, this shouldn't be overly complicated for a bug fix.

**Comment by madphysicist** [comment] 2017-07-05 18:16
@nayyarv I have an idea for a solution that I would like to run by you. I think that the user should be able to get a reasonable histogram here even if they select `'fd'`, so falling back on the other estimator is not necessarily the best option here. Instead, we could modify `_hist_bin_fd` to check if the IQR is zero because the data is shaped unfortunately vs actually having only one value. For example, if IQR is zero, use `np.unique` to see how many distinct values there are and use the min/max values instead.

**Comment by eileenjkim** [comment] 2018-03-09 18:41
Did this ever get resolved? / Will this get resolved? Just ran into this on a project I'm working on.

**Comment by madphysicist** [comment] 2018-03-09 18:47
@eileenjkim This will get fixed. I am currently a bit swamped with other projects, but it is close to the top of my list when I get some free time. I am doing a bit of research into this and other modifications to histograms right now actually. I can't promise a quick turnaround, but I will get to it...

**Comment by eileenjkim** [comment] 2018-03-09 19:56
Thanks @madphysicist !

**Comment by madphysicist** [comment] 2018-03-23 19:32
@eileenjkim. Take a look at the referenced PR (#10739). Looks like it's been fixed. Fix will be out with the next release, or you can grab it from GitHub immediately.

**Comment by seberg** [comment] 2018-03-25 17:32
Seems like we can close this then. Thanks everyone!

**Comment by madphysicist** [comment] 2018-03-27 20:01
@eileenjkim. Take a look at the referenced PR (#10739). Looks like it's been fixed. Fix will be out with the next release, or you can grab it from GitHub immediately.

**Comment by eric-wieser** [comment] 2018-03-27 20:02
Re-opening since that PR isn't merged yet

**Closed** 2018-04-10 04:56 UTC
