### ISSUE TITLE
FIXME in `numpy/__init__.py` related to `numpy.lib` imports

### ISSUE THREAD

**Issue by rossbar** [numpy/numpy#15668] opened 2020-02-28 23:52 UTC
There is a FIXME comment in `numpy/__init__.py` that doesn't seem to have a corresponding issue on GitHub, at least not one that I noticed with a cursory search of the issues.

https://github.com/numpy/numpy/blob/eb167a3fe540780f397a14817f54a95333fbcc6c/numpy/__init__.py#L140-L145

There is additional code in `numpy/__init__.py` related to this FIXME:

https://github.com/numpy/numpy/blob/eb167a3fe540780f397a14817f54a95333fbcc6c/numpy/__init__.py#L178-L184

My intent is getting this into the issue tracker so that it can be discussed/documented and synced up with the code comments. If there is an existing issue that I missed, I'd recommend updating the comment in `numpy/__init__.py` to point there.

**Comment by rgommers** [comment] 2020-02-29 10:08
It was discussed when the PR was merged. I'm not sure there's much we can do about it in the short term.

**Comment by rgommers** [comment] 2020-02-29 10:09
This is not a bug nor an enhancement, so it's not clear we should have an issue for this.

**Comment by rossbar** [comment] 2020-02-29 18:40
Thanks for the additional info - even after you mentioned it, it took me a second to track down the discussion in #14454.

If attention is not desired here, it might be worthwhile to remove the comment just so potential contributors don't get hung up on it. Alternatively, if having the FIXME callout in the comment is desired, perhaps adding an additional comment along the lines of (see GH 14454 for discussion) would be good so that anyone who is curious about the comment can easily find the relevant discussion.

**Comment by rgommers** [comment] 2020-02-29 18:51
Looked into it some more, I think it's not urgent but indeed it would be a decent cleanup to remove the `from .lib import *` and replace it with explicit imports of everything that's imported now. That's about 220 functions, so also a pain. Actually not sure it's worth it - there's too much of a historical mess. Let's see what others think.

adding "see gh-14454 for discussion" is useful either way.

**Comment by rossbar** [comment] 2020-02-29 19:00
I agree - I will make that change.

FWIW I stumbled across this while trying to take a closer look at how the `np` namespace was constructed.

**Closed** 2020-03-01 19:37 UTC
