### ISSUE TITLE
RuntimeError when importing numpy 1.19.4

### ISSUE THREAD

**Issue by Harshavardhan-tech** [numpy/numpy#19790] opened 2021-08-30 17:09 UTC
The newest version of numpy raises an exception when being imported. I am using Python 3.9 64-bit on Windows 10.

### Reproducing code example:

```python
import numpy as np  # raises a RuntimeError
```

### Error message:

```
$ python -c "import numpy"
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Us\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 305, in <module>
  _win_os_check()
  File "C:\Users\Us\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 302, in _win_os_check
  raise RuntimeError(msg.format(__file__))  from None
RuntimeError: The current Numpy installation ('C:\\Users\\Us\\AppData\\Roaming\\Python\\Python39\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://lnkd.in/dg_VxHr
```

### NumPy/Python version information:

NumPy 1.19.4 
Python 3.9.1
![5b7544ad-bbfb-4ca3-886c-bc67e55ed5a9](https://user-images.githubusercontent.com/63655612/131376747-64859b5f-bc29-4a5a-9fce-950f662a8e3c.png)

**Comment by charris** [comment] 2021-08-30 17:31
Windows 2004 had an fmod bug. What Windows version are you using?

**Comment by Harshavardhan-tech** [comment] 2021-08-30 17:36
Windows 10 Pro

**Comment by Harshavardhan-tech** [comment] 2021-08-30 17:53
> Windows 2004 had an fmod bug. What Windows version are you using?

Windows 10 Pro

**Comment by mattip** [comment] 2021-08-31 07:42
Is there a reason you are using NumPy 1.19? Can you upgrade to 1.21 ?

**Comment by mattip** [comment] 2021-08-31 07:44
Duplicate of #17726

**Closed by mattip** 2021-08-31 07:44 UTC
