### ISSUE TITLE
Support zip input in savetxt in Python 3

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#5951] opened 2015-06-08 09:22 UTC
I (and I think a number of other people, judging from code I've seen) have often made use of the following way of calling savetxt in Python 2:

```
np.savetxt('filename.txt', zip(a, b, c))
```

but in Python 3 this now raises an error because `zip` is now an iterator:

```
In [2]: np.savetxt('test.txt', zip([1,2,3],[4,5,6]))
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-96ba7b5b8e1b> in <module>()
----> 1 np.savetxt('test.txt', zip([1,2,3],[4,5,6]))

/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/numpy/lib/npyio.py in savetxt(fname, X, fmt, delimiter, newline, header, footer, comments)
   1042                 ncol = len(X.dtype.descr)
   1043         else:
-> 1044             ncol = X.shape[1]
   1045 
   1046         iscomplex_X = np.iscomplexobj(X)

IndexError: tuple index out of range
```

In order to minimize pain when upgrading from Python 2 to Python 3, I would like to suggest that we explicitly check whether the data argument is a `zip` instance (or even better an iterable object). I don't think this would be ambiguous, and it would be useful in any case to continue supporting the above syntax.

If there is support for this, I can open a pull request.

**Comment by behzadnouri** [comment] 2015-06-08 14:03
the problem is that [`X = np.asarray(X)` in his line](https://github.com/numpy/numpy/blob/01c59d63ad0356650571e239fffb9e7ee38c4c08/numpy/lib/npyio.py#L1149) creates a zero dimension array:
```python
ipdb> X
array(<itertools.izip object at 0x2a9ae7de18>, dtype=object)
ipdb> X.ndim
0
```

I had submitted [patch 5863](https://github.com/numpy/numpy/pull/5863) which unfortunately did not get much love. I verified that your code would actually work if that was merged in. 

Given that `map`, `filter` and `zip` return iterators in python 3, i also emphasize your point that supporting iterators would make enhance 2/3 compatibility.

**Comment by WarrenWeckesser** [comment] 2022-06-19 15:00
Given the lack of activity since 2015, and the closure of https://github.com/numpy/numpy/pull/5863, I'm closing this issue.  If anyone thinks it should remain open, feel free to reopen it.

**Closed by WarrenWeckesser** 2022-06-19 15:00 UTC
Labels: 01 - Enhancement, component: numpy.lib
