### ISSUE TITLE
`TypeError` raised by `help(numpy.typing)`

### ISSUE THREAD

**Issue by pdeblanc** [numpy/numpy#21240] opened 2022-03-25 02:00 UTC
### Describe the issue:

Calling `help(numpy.typing)` raises an exception rather than displaying help text.

### Reproduce the code example:

```python
import numpy.typing
help(numpy.typing)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 2002, in __call__
    self.help(request)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 2061, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 1780, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 1773, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 472, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 1267, in docmodule
    contents.append(self.document(value, key, name))
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 473, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pydoc.py", line 1343, in docclass
    (str(cls.__name__) for cls in type.__subclasses__(object)
TypeError: descriptor '__subclasses__' for 'type' objects doesn't apply to a 'types.GenericAlias' object
```

### NumPy/Python version information:

```
1.22.3 3.9.10 (main, Jan 15 2022, 11:48:00)
[Clang 13.0.0 (clang-1300.0.29.3)]
```

**Comment by ksunden** [comment] 2022-03-25 02:38
Seems to be a but in python itself, can also reproduce with `help(list[str])`, for instance

**Comment by BvB93** [comment] 2022-03-25 11:04
> ref https://bugs.python.org/issue40296

I'm going to close this now as it's an upstream bug, one that has already been fixed and backported.
The recent Python 3.9.12 release already contains aforementioned fix, so I would suggest upgrading if you'd like to use `help(numpy.typing)`.

**Closed by BvB93** 2022-03-25 11:04 UTC
Labels: 00 - Bug, component: numpy.typing
