### ISSUE TITLE
numpy.var and numpy.ndarray.var works have different defaults for ddof

### ISSUE THREAD

**Issue by ManfredEnning** [numpy/numpy#14928] opened 2019-11-18 15:29 UTC
The documentation for numpy.ndarray.var is wrong

 ndarray.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False)

it should be ... ddof=1

Example:

y is an arbitrary 1-dimensional array
np.var(y) - y.var()
Output: -0.3163994546004574

if you specify ddof

np.var(y) - y.var(ddof=0)
Output: 0

it is correct.

```python
import numpy as np
<< your code here >>
```

**Comment by WarrenWeckesser** [comment] 2019-11-20 01:27
Are you sure `y` is a numpy array?

I can't reproduce this:

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.17.2'

In [3]: y = np.array([1, 10, 3, 2, 4, 7])

In [4]: np.var(y) - y.var()
Out[4]: 0.0
```
The docstring for [`numpy.var`](https://numpy.org/devdocs/reference/generated/numpy.var.html) and the method [`ndarray.var`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.var.html) both have the keyword argument specified as `ddof=0`.

Is your `y` actually a Pandas `Series`?  E.g.

```
In [11]: import pandas as pd

In [12]: p = pd.Series(y)

In [13]: p.var()
Out[13]: 11.5

In [14]: y.var()
Out[14]: 9.583333333333334
```

**Comment by WarrenWeckesser** [comment] 2019-11-20 01:34
@ManfredEnning, I'm closing this issue because I don't think your variable `y` is actually a NumPy array.  If I'm wrong, can you provide a complete, minimal, self-contained example that we can run to reproduce the problem?

**Closed by WarrenWeckesser** 2019-11-20 01:34 UTC
Labels: 04 - Documentation
