### ISSUE TITLE
BUG: MaskedArray comparison gives incorrect fill_value for <, >, >=, <=

### ISSUE THREAD

**Issue by stephenworsley** [numpy/numpy#21389] opened 2022-04-25 10:18 UTC
### Describe the issue:

When an inequality is applied to a masked array, if the fill value in that masked array has _already been realized_, the resulting array will have an incorrect fill value (the fill value ought to be boolean).

```python
>>> m = np.ma.array([1, 1], mask=[0, 1])
>>> (m > 1).fill_value
True
>>> m.fill_value
999999
>>> (m > 1).fill_value
999999
```

I believe this is linked with issue #10092 and that both of these issues are due to the fact that while `__eq__` has a special treatment in MaskedArray, the same is not applied to the likes of `__gt__`. This can be seen here: https://github.com/numpy/numpy/blob/732ed25e4a1e3802d82a976f9541f74548b13e6f/numpy/ma/core.py#L4151-L4162

I believe that if equivalent functions were made for `__lt__`, `__le__`, `__gt__` and `__ge__` this ought to solve this issue and also #10092.

### Reproduce the code example:

```python
import numpy as np

m = np.ma.array([1, 1], mask=[0, 1])
print((m > 1).fill_value)
print(m.fill_value)
print((m > 1).fill_value)
```

### NumPy/Python version information:

1.21.5

**Comment by seberg** [comment] 2022-12-07 23:55
Can't reproduce the example, so closing.  This must have been fixed at some point (although I wouldn't be surprised if there are related issues remaining).

**Closed by seberg** 2022-12-07 23:55 UTC
Labels: 00 - Bug
