### ISSUE TITLE
Inconsistent behavior between slice/bool indexing with/without intermediate view

### ISSUE THREAD

**Issue by PierreAndreNoel** [numpy/numpy#18426] opened 2021-02-16 18:10 UTC
In-place operations with boolean indexing do not behave the same way as the equivalent slice indexing when an "intermediate view" is involved. The code below highlights this different behavior: three of the possible permutations have the same outcome, but the fourth one is different (it makes a copy).

Notice that, while the "intermediate view" used below may appear like a rare edge case, they naturally come up in a function call.

### Reproducing code example:

```python
import numpy as np


def test__assign_zero__slice_indexing__no_intermediate():
    a = np.array([[1., 2.], [3., 4.]])

    lines_to_zero_slice_indexing = slice(None, 1)
    a[lines_to_zero_slice_indexing, :] = 0.

    assert np.allclose(a, [[0., 0.], [3., 4.]])  # OK


def test__assign_zero__bool_indexing__no_intermediate():
    a = np.array([[1., 2.], [3., 4.]])

    lines_to_zero_bool_indexing = np.array([True, False])
    a[lines_to_zero_bool_indexing, :] = 0.

    assert np.allclose(a, [[0., 0.], [3., 4.]])  # OK


def test__assign_zero__slice_indexing__with_intermediate():
    a = np.array([[1., 2.], [3., 4.]])

    lines_to_zero_slice_indexing = slice(None, 1)
    intermediate = a[lines_to_zero_slice_indexing, :]
    intermediate[...] = 0.

    assert np.allclose(a, [[0., 0.], [3., 4.]])  # OK


def test__assign_zero__bool_indexing__with_intermediate():
    a = np.array([[1., 2.], [3., 4.]])

    lines_to_zero_bool_indexing = np.array([True, False])
    intermediate = a[lines_to_zero_bool_indexing, :]
    intermediate[...] = 0.

    assert np.allclose(a, [[0., 0.], [3., 4.]])  # FAIL
```

### NumPy/Python version information:

```
1.20.1 3.8.6 (default, Dec 18 2020, 05:24:40) 
[GCC 8.3.0]
```

**Comment by BvB93** [comment] 2021-02-16 21:05
The reason why this doesn't work is because fancy indexing (in general) creates a copy of the to-be-indexed array; not a view.

``` python
In [1]: import numpy as np

In [2]: a = np.array([[1., 2.], [3., 4.]])
    ...: intermediate1 = a[[True, False], :]
    ...: intermediate2 = a[:1, :]

In [3]: print(intermediate1.base)
None

In [4]: print(intermediate2.base)
[[1. 2.]
 [3. 4.]]
```

**Comment by seberg** [comment] 2021-02-16 21:23
I prefer calling it advanced indexing (although maybe array indexing would be even better), but yeah, I will close the issue. This is expected behaviour.

**Closed by seberg** 2021-02-16 21:23 UTC
Labels: 33 - Question

**Comment by PierreAndreNoel** [comment] 2021-02-17 19:49
Thanks both for your answers!

Is there a way to get an actual `view` through boolean/advanced/fancy indexing? Or is the following fix the best I can aim for?

```python
def test__assign_zero__bool_indexing__with_intermediate__fixed():
    a = np.array([[1., 2.], [3., 4.]])

    lines_to_zero_bool_indexing = np.array([True, False])
    intermediate = a[lines_to_zero_bool_indexing, :]
    intermediate[...] = 0.  # Of course, that's not what I actually do to intermediate
    a[lines_to_zero_bool_indexing, :] = intermediate

    assert np.allclose(a, [[0., 0.], [3., 4.]])
```

**Comment by seberg** [comment] 2021-02-17 20:01
A view is (normally) impossible due to the NumPy memory model. So no, you can't do it in NumPy and such a trick is perfectly fine.  If you got `:` in there in the assignment, you might be a bit faster off calling `np.nonzero(lines_to_zero_bool_indexing)` manually and storing that, but I doubt it matters.
