### ISSUE TITLE
7 Tests fail on 1.20.0 RC1 on Fedora Rawhide(34)

### ISSUE THREAD

**Issue by limburgher** [numpy/numpy#17954] opened 2020-12-07 20:26 UTC
```
=================================== FAILURES ===================================
________________ TestArrayLike.test_array_like_not_implemented _________________

self = <numpy.core.tests.test_overrides.TestArrayLike object at 0x7f69149dcf40>

    @requires_array_function
    def test_array_like_not_implemented(self):
        TestArrayLike.add_method('array', TestArrayLike.MyArray)
    
        ref = TestArrayLike.MyArray.array()
    
        with assert_raises_regex(TypeError, 'no implementation found'):
>           array_like = np.asarray(1, like=ref)

array_like = <numpy.core.tests.test_overrides.TestArrayLike.MyArray object at 0x7f69149e9250>
ref        = <numpy.core.tests.test_overrides.TestArrayLike.MyArray object at 0x7f69149e9100>
self       = <numpy.core.tests.test_overrides.TestArrayLike object at 0x7f69149dcf40>

numpy/core/tests/test_overrides.py:472: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.9/unittest/case.py:226: in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
        exc_name   = 'TypeError'
        exc_type   = None
        exc_value  = None
        self       = <unittest.case._AssertRaisesContext object at 0x7f69149e9070>
        tb         = None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <unittest.case._AssertRaisesContext object at 0x7f69149e9070>
standardMsg = 'TypeError not raised'

    def _raiseFailure(self, standardMsg):
        msg = self.test_case._formatMessage(self.msg, standardMsg)
>       raise self.test_case.failureException(msg)
E       AssertionError: TypeError not raised

msg        = 'TypeError not raised'
self       = <unittest.case._AssertRaisesContext object at 0x7f69149e9070>
standardMsg = 'TypeError not raised'

/usr/lib64/python3.9/unittest/case.py:163: AssertionError
____ test_numeric_object_coefficients[coefs1-1 + 2\xb7x\xb9 + 5/7\xb7x\xb2] ____

coefs = array([1, 2, Fraction(5, 7)], dtype=object), tgt = '1 + 2·x¹ + 5/7·x²'

    @pytest.mark.parametrize(('coefs', 'tgt'), (
        (array([Fraction(1, 2), Fraction(3, 4)], dtype=object), (
            "1/2 + 3/4·x¹"
        )),
        (array([1, 2, Fraction(5, 7)], dtype=object), (
            "1 + 2·x¹ + 5/7·x²"
        )),
        (array([Decimal('1.00'), Decimal('2.2'), 3], dtype=object), (
            "1.00 + 2.2·x¹ + 3·x²"
        )),
    ))
    def test_numeric_object_coefficients(coefs, tgt):
        p = poly.Polynomial(coefs)
        poly.set_default_printstyle('unicode')
>       assert_equal(str(p), tgt)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: '1 + 2 x**1 + 5/7 x**2'
E        DESIRED: '1 + 2·x¹ + 5/7·x²'

coefs      = array([1, 2, Fraction(5, 7)], dtype=object)
p          = Polynomial([1, 2, Fraction(5, 7)], dtype=object, domain=[-1,  1], window=[-1,  1])
tgt        = '1 + 2·x¹ + 5/7·x²'

numpy/polynomial/tests/test_printing.py:268: AssertionError
___ test_nonnumeric_object_coefficients[coefs0-1 + 2\xb7x\xb9 + f\xb7x\xb2] ____

coefs = array([1, 2, 'f'], dtype=object), tgt = '1 + 2·x¹ + f·x²'

    @pytest.mark.parametrize(('coefs', 'tgt'), (
        (array([1, 2, 'f'], dtype=object), '1 + 2·x¹ + f·x²'),
        (array([1, 2, [3, 4]], dtype=object), '1 + 2·x¹ + [3, 4]·x²'),
    ))
    def test_nonnumeric_object_coefficients(coefs, tgt):
        """
        Test coef fallback for object arrays of non-numeric coefficients.
        """
        p = poly.Polynomial(coefs)
        poly.set_default_printstyle('unicode')
>       assert_equal(str(p), tgt)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: '1 + 2 x**1 + f x**2'
E        DESIRED: '1 + 2·x¹ + f·x²'

coefs      = array([1, 2, 'f'], dtype=object)
p          = Polynomial([1, 2, 'f'], dtype=object, domain=[-1,  1], window=[-1,  1])
tgt        = '1 + 2·x¹ + f·x²'

numpy/polynomial/tests/test_printing.py:281: AssertionError
_ test_nonnumeric_object_coefficients[coefs1-1 + 2\xb7x\xb9 + [3, 4]\xb7x\xb2] _

coefs = array([1, 2, list([3, 4])], dtype=object), tgt = '1 + 2·x¹ + [3, 4]·x²'

    @pytest.mark.parametrize(('coefs', 'tgt'), (
        (array([1, 2, 'f'], dtype=object), '1 + 2·x¹ + f·x²'),
        (array([1, 2, [3, 4]], dtype=object), '1 + 2·x¹ + [3, 4]·x²'),
    ))
    def test_nonnumeric_object_coefficients(coefs, tgt):
        """
        Test coef fallback for object arrays of non-numeric coefficients.
        """
        p = poly.Polynomial(coefs)
        poly.set_default_printstyle('unicode')
>       assert_equal(str(p), tgt)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: '1 + 2 x**1 + [3, 4] x**2'
E        DESIRED: '1 + 2·x¹ + [3, 4]·x²'

coefs      = array([1, 2, list([3, 4])], dtype=object)
p          = Polynomial([1, 2, list([3, 4])], dtype=object, domain=[-1,  1], window=[-1,  1])
tgt        = '1 + 2·x¹ + [3, 4]·x²'

numpy/polynomial/tests/test_printing.py:281: AssertionError
_________ test_numeric_object_coefficients[coefs0-1/2 + 3/4\xb7x\xb9] __________

coefs = array([Fraction(1, 2), Fraction(3, 4)], dtype=object)
tgt = '1/2 + 3/4·x¹'

    @pytest.mark.parametrize(('coefs', 'tgt'), (
        (array([Fraction(1, 2), Fraction(3, 4)], dtype=object), (
            "1/2 + 3/4·x¹"
        )),
        (array([1, 2, Fraction(5, 7)], dtype=object), (
            "1 + 2·x¹ + 5/7·x²"
        )),
        (array([Decimal('1.00'), Decimal('2.2'), 3], dtype=object), (
            "1.00 + 2.2·x¹ + 3·x²"
        )),
    ))
    def test_numeric_object_coefficients(coefs, tgt):
        p = poly.Polynomial(coefs)
        poly.set_default_printstyle('unicode')
>       assert_equal(str(p), tgt)
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: '1/2 + 3/4 x**1'
E        DESIRED: '1/2 + 3/4·x¹'

coefs      = array([Fraction(1, 2), Fraction(3, 4)], dtype=object)
p          = Polynomial([Fraction(1, 2), Fraction(3, 4)], dtype=object, domain=[-1,  1], window=[-1,  1])
tgt        = '1/2 + 3/4·x¹'

numpy/polynomial/tests/test_printing.py:268: AssertionError
________________________ test_set_default_printoptions _________________________

    def test_set_default_printoptions():
        p = poly.Polynomial([1, 2, 3])
        c = poly.Chebyshev([1, 2, 3])
        poly.set_default_printstyle('ascii')
        assert_equal(str(p), "1.0 + 2.0 x**1 + 3.0 x**2")
        assert_equal(str(c), "1.0 + 2.0 T_1(x) + 3.0 T_2(x)")
        poly.set_default_printstyle('unicode')
>       assert_equal(str(p), "1.0 + 2.0·x¹ + 3.0·x²")
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: '1.0 + 2.0 x**1 + 3.0 x**2'
E        DESIRED: '1.0 + 2.0·x¹ + 3.0·x²'

c          = Chebyshev([1., 2., 3.], domain=[-1,  1], window=[-1,  1])
p          = Polynomial([1., 2., 3.], domain=[-1,  1], window=[-1,  1])

numpy/polynomial/tests/test_printing.py:233: AssertionError
__________________________ test_complex_coefficients ___________________________

    def test_complex_coefficients():
        """Test both numpy and built-in complex."""
        coefs = [0+1j, 1+1j, -2+2j, 3+0j]
        # numpy complex
        p1 = poly.Polynomial(coefs)
        # Python complex
        p2 = poly.Polynomial(array(coefs, dtype=object))
        poly.set_default_printstyle('unicode')
        assert_equal(str(p1), "1j + (1+1j)·x¹ - (2-2j)·x² + (3+0j)·x³")
        assert_equal(str(p2), "1j + (1+1j)·x¹ + (-2+2j)·x² + (3+0j)·x³")
        poly.set_default_printstyle('ascii')
>       assert_equal(str(p1), "1j + (1+1j) x**1 - (2-2j) x**2 + (3+0j) x**3")
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: '1j + (1+1j)·x¹ - (2-2j)·x² + (3+0j)·x³'
E        DESIRED: '1j + (1+1j) x**1 - (2-2j) x**2 + (3+0j) x**3'

coefs      = [1j, (1+1j), (-2+2j), (3+0j)]
p1         = Polynomial([ 0.+1.j,  1.+1.j, -2.+2.j,  3.+0.j], domain=[-1,  1], window=[-1,  1])
p2         = Polynomial([1j, (1+1j), (-2+2j), (3+0j)], dtype=object, domain=[-1,  1], window=[-1,  1])

numpy/polynomial/tests/test_printing.py:250: AssertionError
=============================== warnings summary ===============================
/usr/lib/python3.9/site-packages/nose/importer.py:12
  /usr/lib/python3.9/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import find_module, load_module, acquire_lock, release_lock

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED numpy/core/tests/test_overrides.py::TestArrayLike::test_array_like_not_implemented
FAILED numpy/polynomial/tests/test_printing.py::test_numeric_object_coefficients[coefs1-1 + 2\xb7x\xb9 + 5/7\xb7x\xb2]
FAILED numpy/polynomial/tests/test_printing.py::test_nonnumeric_object_coefficients[coefs0-1 + 2\xb7x\xb9 + f\xb7x\xb2]
FAILED numpy/polynomial/tests/test_printing.py::test_nonnumeric_object_coefficients[coefs1-1 + 2\xb7x\xb9 + [3, 4]\xb7x\xb2]
FAILED numpy/polynomial/tests/test_printing.py::test_numeric_object_coefficients[coefs0-1/2 + 3/4\xb7x\xb9]
FAILED numpy/polynomial/tests/test_printing.py::test_set_default_printoptions
FAILED numpy/polynomial/tests/test_printing.py::test_complex_coefficients - A...
7 failed, 12262 passed, 851 skipped, 1205 deselected, 18 xfailed, 4 xpassed, 1 warning in 780.39s (0:13:00)
error: Bad exit status from /var/tmp/rpm-tmp.EMf3oR (%check)
```

**Comment by seberg** [comment] 2020-12-07 20:40
Could you give the preamble of the test run as well, just to have all the information available? E.g. which python version was this on, and how did you install the RC?

**Comment by limburgher** [comment] 2020-12-07 20:42
3.9.0, and it's part of the RPM build process. The build completed successfully.

**Comment by seberg** [comment] 2020-12-07 20:58
The reason I ask is that I am currently very confused by these failures.  At least if `pytest` is runing with `-v`, the preamble lists some additional things (for me on a dev version):
```
NumPy version 1.21.0.dev0+20201207145531_e507b30
NumPy relaxed strides checking option: True
NumPy CPU features: SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C* FMA3* AVX2* AVX512F? AVX512CD? AVX512_KNL? AVX512_KNM? AVX512_SKX? AVX512_CLX? AVX512_CNL? AVX512_ICL?
==================================================== test session starts =====================================================
platform linux -- Python 3.9.0+, pytest-4.6.11, py-1.9.0, pluggy-0.13.0
rootdir: /home/sebastian/forks/numpy, inifile: pytest.ini
plugins: hypothesis-5.41.4
```

Since I am so confused, a far fetched idea would be that the test failures stem from a pytest plugin that runs tests in parallel using threading?  Although I would think that these mostly use multiprocessing (or ensure no parallel runs within a single file/class), so it seems far fetched indeed.

**Comment by limburgher** [comment] 2020-12-07 21:04
My equivalents are:
NumPy version 1.20.0rc1
NumPy relaxed strides checking option: True
NumPy CPU features: SSE SSE2 SSE3 SSSE3? SSE41? POPCNT? SSE42? AVX? F16C? FMA3? AVX2? AVX512F? AVX512CD? AVX512_KNL? AVX512_KNM? AVX512_SKX? AVX512_CLX? AVX512_CNL? AVX512_ICL?
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.9.1rc1, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
Using --randomly-seed=568158134
rootdir: /home/gwyn/fedora/git/numpy/numpy-1.20.0rc1, configfile: pytest.ini
plugins: hypothesis-5.41.3, timeout-1.4.2, xdist-2.1.0, flake8-1.0.6, randomly-3.4.1, forked-1.3.0, cov-2.10.1

**Comment by seberg** [comment] 2020-12-07 21:07
Thanks!  My best guess right now is that `xdist` is the problem, using `PYTEST_PLUGINS=hypothesis` as an environment variable during the call probably solves the issues...

But I wonder if we can't trivially fix the test to run fine with xdist.

**Comment by rossbar** [comment] 2020-12-07 21:11
It looks like the `set_default_printoptions` isn't working. Not sure if that's a bad interaction with `xdist` or something wrong with `set_default_printoptions` itself.

**Comment by seberg** [comment] 2020-12-07 22:01
OK @rossbar tried to reproduce it based on that theory and was not successful.  Will have a deeper look later maybe, right now I am not sure what is going on. Both tests might be doing a bit strange things around class scoping, but without threading as an explanation, I am not sure what might cause it.

**Comment by limburgher** [comment] 2020-12-07 22:03
My best guess is that we're on pytest 6 and you have 4, but I don't have a good way to test that at the moment.

**Comment by mattip** [comment] 2020-12-07 22:09
we use [pytest 6](https://github.com/numpy/numpy/blob/master/test_requirements.txt#L5). I would focus more on the other pytest additions like xdist.

**Comment by rossbar** [comment] 2020-12-07 22:11
Aha - I was able to reproduce some errors with the `pytest-randomly` plugin (which randomly orders test execution).

Re: the polynomial printing tests, this is likely pointing out a flaw in the tests themselves in that the state from one test may be carried over into another. That's my initial guess anyways - I'm looking into the polynomial tests to see if I can't understand what's going on a bit better.

**Comment by seberg** [comment] 2020-12-07 23:35
Yeah, we probably should consider adding a testrun to the CI that is randomized. On the up-side, if it is test randomization it is hopefully easy to fix :).

**Comment by rossbar** [comment] 2020-12-07 23:44
I have a fix for the polynomial tests in #17957 , which should cover 6 of the 7 failures in the original issue. Thanks for raising this @limburgher , I had never used `pytest-random` before and wouldn't have noticed the problems with these tests otherwise.

**Comment by limburgher** [comment] 2020-12-08 15:19
You're very welcome! With the above applied, I get:
FAILED numpy/core/tests/test_ufunc.py::TestUfunc::test_sum - AssertionError: 
FAILED numpy/core/tests/test_overrides.py::TestArrayLike::test_array_like_not_implemented

**Comment by charris** [comment] 2020-12-21 22:18
@limburgher I assume there are still two failing tests. What was the `test_sum` error?

**Comment by seberg** [comment] 2020-12-21 23:13
@charris the remaining errors should have been fixed by the backport gh-18018 (backport version of gh-17962)

**Comment by charris** [comment] 2020-12-21 23:35
Thanks Sebastian, I'll close this then. @limburgher let us know how 1.20.0rc2 does when it comes out.

**Closed by charris** 2020-12-21 23:35 UTC
Labels: 05 - Testing

**Comment by limburgher** [comment] 2020-12-22 14:13
@charris will do!

**Comment by limburgher** [comment] 2020-12-28 16:48
Looks good, thanks all!
