### ISSUE TITLE
np.concatenate([ [], [1] ]) converts integer to float

### ISSUE THREAD

**Issue by Muxas** [numpy/numpy#8878] opened 2017-03-31 12:18 UTC
When concatenating empty list with a list of INTEGERS result is an array of FLOATS. Since numpy 1.12 you can not use floats (result of such concatenation) for indexing without additional convertion from float to integer.

Following example works in numpy <=1.11 and does not work in numpy >= 1.12:

```
array = np.arange(3)
ind0 = []
ind1 = [1]
total_ind = np.concatenate([ind0, ind1])
print array[total_ind]
```

**Comment by jaimefrio** [comment] 2017-03-31 15:18
Closing because this is a duplicate of #1586. There's #7450 that would fix it, but we never got around to merge...

**Closed by jaimefrio** 2017-03-31 15:18 UTC
