### ISSUE TITLE
install numpy==1.19.2 in arm64v8 error

### ISSUE THREAD

**Issue by ZTurboX** [numpy/numpy#24330] opened 2023-08-04 01:22 UTC
### Describe the issue:

install numpy==1.19.2 in arm64v8 error

 ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpyz6zizng
         cwd: /tmp/pip-install-h_q5hawx/numpy
    Complete output (54 lines):
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            for i in range(1, RK_STATE_LEN):
                self.rng_state.key[i] = val[i]
            self.rng_state.pos = i
    
            self._bitgen.state = &self.rng_state
            self._bitgen.next_uint64 = &mt19937_uint64
                                       ^
    ------------------------------------------------------------
    
    _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_mt19937.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-h_q5hawx/numpy/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/pip-install-h_q5hawx/numpy/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-h_q5hawx/numpy/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-h_q5hawx/numpy/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-h_q5hawx/numpy/tools/cythonize.py", line 78, in process_pyx
        [sys.executable, '-m', 'cython'] + flags + ["-o", tofile, fromfile])
      File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/python3.7', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
    Running from numpy source directory.
    setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Cythonizing sources
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-qqpoaqx6/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-qqpoaqx6/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 249, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-qqpoaqx6/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 499, in <module>
        setup_package()
      File "setup.py", line 479, in setup_package
        generate_cython()
      File "setup.py", line 274, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpyz6zizng Check the logs for full command output.

### Reproduce the code example:

```python
pip install numpy==1.19.2
```

### Runtime information:

build in docke  rarm64v8/centos:7

python=3.7
numpy==1.19.2
cython==3.0.0

**Comment by charris** [comment] 2023-08-04 02:34
Don't use Cython 3, it won't be compatible with NumPy until 1.26 or 2.0

**Comment by ZTurboX** [comment] 2023-08-04 02:40
> Don't use Cython 3, it won't be compatible with NumPy until 1.26 or 2.0

which cython version should install

**Comment by charris** [comment] 2023-08-04 02:59
The latest in the 0.29 series should work fine 0.29.34. If you have the source, there should be a `build_requirements.txt` file.  Any reason you are not using the prebuilt wheels?

**Comment by ZTurboX** [comment] 2023-08-04 04:55
> The latest in the 0.29 series should work fine 0.29.34. If you have the source, there should be a `build_requirements.txt` file. Any reason you are not using the prebuilt wheels?

change cython to 0.29.34 has the same error

**Comment by seberg** [comment] 2023-08-04 06:20
Maybe try with `pip install==1.19.2 --no-build-isolation`, not sure it might not just install a newer Cython temporarily during building, the error does look a bit like Cython 3.

**Comment by FoxRox87** [comment] 2023-08-07 14:03
Does anyone found a solution? I have the same problem and used different versions from numpy and cython but every time I get the same Error.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              for i in range(1, RK_STATE_LEN):
                  self.rng_state.key[i] = val[i]
              self.rng_state.pos = i

              self._bitgen.state = &self.rng_state
              self._bitgen.next_uint64 = &mt19937_uint64
                                         ^
      ------------------------------------------------------------

      _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_bit_generator.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_common.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_mt19937.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-6nxtof_0/numpy_0bf49783dd644ee18f0651f78127f86b/tools/cythonize.py", line 238, in <module>
          main()
        File "/tmp/pip-install-6nxtof_0/numpy_0bf49783dd644ee18f0651f78127f86b/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/tmp/pip-install-6nxtof_0/numpy_0bf49783dd644ee18f0651f78127f86b/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/pip-install-6nxtof_0/numpy_0bf49783dd644ee18f0651f78127f86b/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/tmp/pip-install-6nxtof_0/numpy_0bf49783dd644ee18f0651f78127f86b/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/mnt/c/workspace_testing/venv/bin/python3', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/mnt/c/workspace_testing/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/mnt/c/workspace_testing/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/c/workspace_testing/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-2dm5fskb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-2dm5fskb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-2dm5fskb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]

**Comment by seberg** [comment] 2023-08-07 14:20
@FoxRox87 I am very certain the above is related to Cython 3 use and you must avoid it.  The fix is backported although not quite sure included in 1.25.x right now (it seems to be: gh-23709), definitely not in earlier versions.

If you wish to compile older versions of NumPy, you *must* ensure Cython <3 unfortunately, now I suspect NumPy did not pin <3, so I am not sure the best way to do so.

The use of `--no-build-isolation` should be a hacky way to ensure you use a current installed Cython (which you can pick yourself) because otherwise the install process may install a newer Cython version *temporarily*, I suspect.

**Comment by FoxRox87** [comment] 2023-08-09 09:20
I downgraded my WSL Ubuntu to 20.04 and now it works.

**Comment by rgommers** [comment] 2023-08-11 13:51
In the `1.18.x` branch we're missing upper bounds on the dependency: https://github.com/numpy/numpy/blob/caf44e176893953d6cb48da58c24e40051765cdf/pyproject.toml#L6

Same in `1.19.2`: https://github.com/numpy/numpy/blob/v1.19.2/pyproject.toml. This was fixed in `1.19.3`: https://github.com/numpy/numpy/blob/v1.19.3/pyproject.toml. All later releases are fine.

There's not much we can about this anymore. Once again a reminder that all build-time dependencies must always have upper bounds - the absence of them will cause breakage and must be considered a bug.

I propose we close this issue, since the cause is found and the workaround is provided above.

**Closed** 2023-08-11 15:37 UTC
Labels: 00 - Bug, 32 - Installation

**Comment by Forest-Lee** [comment] 2024-03-17 09:22
> I downgraded my WSL Ubuntu to 20.04 and now it works.

This worked for me, thx a lot!

**Comment by dkohkemper** [comment] 2024-04-02 16:58
I'm having the same problems trying to install Bigfloat in Ubuntu 22.04, it was working well in 20.04 but I had to upgrade. Does anyone officially knows that Bigfloat can't be installed in Ubuntu 22.04?

$ pip install git+https://github.com/mdickinson/bigfloat
Collecting git+https://github.com/mdickinson/bigfloat
  Cloning https://github.com/mdickinson/bigfloat to /tmp/pip-req-build-lb_s8tt8
  Running command git clone --filter=blob:none --quiet https://github.com/mdickinson/bigfloat /tmp/pip-req-build-lb_s8tt8
  Resolved https://github.com/mdickinson/bigfloat to commit 6a9dc17e4b6d82fb652ea6161986f3c3bdea2b55
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          if not (2 <= base <= 62 or -36 <= base <= -2):
              raise ValueError(
                  "Base must satisfy 2 <= base <= 62 or -2 >= base >= -36.")
      
          # Get the appropriate function for freeing the allocated memory.
          cgmp.mp_get_memory_functions (NULL, NULL, &freefunc);
                                                    ^
      ------------------------------------------------------------
      
      mpfr.pyx:112:46: Cannot assign type 'free_func *' to 'void (**)(void *, size_t) noexcept'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-lb_s8tt8/setup.py", line 217, in <module>
          extensions = cythonize(
        File "/home/....../.venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/home/...../.venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: mpfr.pyx
      Compiling mpfr.pyx because it changed.
      [1/1] Cythonizing mpfr.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by rgommers** [comment] 2024-04-02 17:55
That's probably a question for the `bigfloat` project.

**Comment by ari62** [comment] 2024-04-03 02:50
this worked for me (for the version of numpy i was targeting):
```
pip install Cython==0.29.37
pip install numpy==1.18.5 --no-build-isolation
```
