### ISSUE TITLE
Error importing scipy.optimize with new Release: numpy‑1.20.3

### ISSUE THREAD

**Issue by NHades** [numpy/numpy#18991] opened 2021-05-11 13:04 UTC
### Reproducing code example:

```python
import numpy as np
from scipy.optimize import minimize
```

### Error message:
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
     from scipy.optimize import minimize
  File "C:\Python38-32\lib\site-packages\scipy\optimize\__init__.py", line 421, in <module>
      from ._shgo import shgo
  File "C:\Python38-32\lib\site-packages\scipy\optimize\_shgo.py", line 9, in <module>
     from scipy import spatial
  File "C:\Python38-32\lib\site-packages\scipy\spatial\__init__.py", line 107, in <module>
     from . import distance, transform
  File "C:\Python38-32\lib\site-packages\scipy\spatial\transform\__init__.py", line 19, in <module>
     from .rotation import Rotation, Slerp
TypeError: Shared Cython type generator has the wrong size, try recompiling

### NumPy/Python version information:

1.20.3 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]

**Comment by rgommers** [comment] 2021-05-11 13:14
Thanks for the report @NHades. Can you say how exactly you installed python, numpy and scipy? Can you give the output of `pip list` if with pip?

Also, if you again downgrade numpy to 1.20.2, does this import error go away?

**Comment by mattip** [comment] 2021-05-11 13:45
That is very similar to cython/cython#4152  which is caused by using a cython from HEAD that is not yet released so the version number is wrong.

**Comment by rgommers** [comment] 2021-05-11 14:19
Cc @charris, does this ring any bells?

We should have used an already-released Cython ion the numpy-wheels repo I believe.

**Comment by NHades** [comment] 2021-05-11 17:39
@charris, 
   I only use PIP.

**Comment by charris** [comment] 2021-05-11 17:49
@NHades Where did numpy 1.20.2+mkl come from?

**Comment by NHades** [comment] 2021-05-11 18:40
@charris, 

I tried the regular "pip install --upgrade numpy" for stock numpy and I don't see the error. 
so it is in the 1.20.3+mkl release by  Christoph Gohlke. 
sorry for false bug.

**Comment by rgommers** [comment] 2021-05-11 19:43
No worries, thanks @NHades. Closing this issue then.

Cc @cgohlke

**Closed by rgommers** 2021-05-11 19:43 UTC
