### ISSUE TITLE
np.random.normal(size=1) seems to return pointer, gives unexpected results (?)

### ISSUE THREAD

**Issue by amundv** [numpy/numpy#13676] opened 2019-05-30 09:33 UTC
When using argument "size=1" for functions such as numpy.random.normal and numpy.random.choice, the return-value seems to be a pointer. Is this desired behavior? This was unexpected for me in the follow case, where all values of `list1` are changed each iteration. 

### Reproducing code example:

```python
import numpy as np
list1 = []
a = 0
for _ in range(10):
    a += np.random.normal(size=1)
    list1.append(a)
print(list1)
```
seems to result in a list of pointers to the same object, such that printing the list gives the last value of the loop for all list elements. This is different from 

```python
import numpy as np
list1 = []
a = 0
for _ in range(10):
    a += np.random.normal()
    list1.append(a)
print(list1)
```
where list contains the value of `a` at each iteration.  

### Error message:
No error message

### Numpy/Python version information:

1.16.3 3.7.3 (default, Mar 27 2019, 09:23:39) 
[Clang 10.0.0 (clang-1000.11.45.5)]

**Comment by rkern** [comment] 2019-05-30 16:18
Yes, this is the expected behavior. Specifying `size=<integer>` is how you request an array to be returned, even for `size=1`. If you want a scalar, either don't specify the `size` argument, or leave it `size=None`.

**Comment by seberg** [comment] 2019-05-30 16:19
@amundv size is the same as `shape` in most of numpy, so the return is supposed to have a shape of `(1,)` (the different naming is because distributions commonly have a shape parameter).

The way to correctly spell a single number is typically `None` or for a 0D array it would be `()` (although the two may get mixed up.

(I see Robert was quicker with closing).

**Closed by rkern** 2019-05-30 16:18 UTC

**Comment by amundv** [comment] 2019-05-30 19:44
Thank you for answering, @seberg and @rkern, but my question was more related to the fact of returning a pointer, since here Im trying (unsuccessfully) to create a random walk and store in a list, which isnt working in the vase of size=1 since all elements are changed at each iteration.
I wonder if the pointer behavior is desired

**Comment by seberg** [comment] 2019-05-30 19:48
That is the same answer. It returns an array, an array is mutable, this is an error in your code if you do not account for that.

**Comment by amundv** [comment] 2019-05-30 20:03
Yes, you are right. I should probably have written list1.append(np.copy(a)) in the first example, to deal with separate pointers for each iteration...
