### ISSUE TITLE
tofile does not work with gzip files

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#11131] opened 2018-05-21 22:52 UTC
Simple example:

```
import numpy as np
a = np.arange(2**12)
with gzip.GzipFile("test_nb.gz", mode = "wb") as f:
    a.tofile(f)
```

Attempting to gunzip,

```
gunzip test_nb.gz

gzip: test_nb.gz: not in gzip format
```

Note that 

```
import numpy as np
a = np.arange(2**12)
with gzip.GzipFile("test_nb.gz", mode = "wb") as f:
    f.write(a.tobytes())
```
works correctly.

Related: #9179, pandas-dev/pandas#21041

**Comment by charris** [comment] 2018-05-22 02:41
Is this still the case with latest Python?

**Comment by karldw** [comment] 2018-05-22 02:48
Yes, with python 3.6.5 and numpy 1.14.3.

**Comment by stefanv** [comment] 2018-05-22 06:33
Confirmed on numpy 1.14.3 and 1.15.0.dev0+b08ce1a with the example from https://github.com/numpy/numpy/issues/9179:

```
import numpy as np
import gzip

f = gzip.open("/tmp/temp.txt.gz", "wb"); np.array([1,2]).tofile(f); f.close(); gzip.open("/tmp/temp.txt.gz", "rb").read()
```

yields

```
OSError: Not a gzipped file (b'\x01\x00')
```

**Comment by bashtage** [comment] 2018-05-22 07:59
I tried every Numy form 1.09 to 1.14, and it never worked in any of these.  Older NumPy error on `IOError: first argument must be an open file`.  Newer NumPy fail to produce gzip.  

Here is the issue

When running:
```
import numpy as np
import gzip
import struct
with gzip.GzipFile("/tmp/temp.txt.gz","wb") as f:
    f.write(struct.pack('Q',1))
    f.write(struct.pack('Q',2))
gzip.open("/tmp/temp.txt.gz", "rb").read()
```

you get, which is valid
```
hexdump /tmp/temp.txt.gz 

0000000 8b1f 0808 cd0d 5b03 ff02 6574 706d 742e
0000010 7478 6300 8064 2600 0d28 b900 f6dd 1000
0000020 0000 0000                              
0000023
```

When using the example above with array([1,2]) you get which shows that the data is being written directly to the file and not passed to the gzip encoder.
```
hexdump /tmp/temp.txt.gz

0000000 0001 0000 0000 0000 0002 0000 0000 0000
0000010 7478 0000 0000 ffff 6063 0540 5500 bb4b
0000020 10ec 0000 0000                         
0000025
```

```

```

**Comment by bashtage** [comment] 2018-05-22 08:14
It looks like tofile is always just directly (low-level) writing to the underlying file object

https://github.com/numpy/numpy/blob/1290e7fd5d40903d69733b4797f7c30ca025e1f7/numpy/core/include/numpy/npy_3kcompat.h#L159

and so writing to a GzipFile is not going to work.  There is a hint about this here:

https://github.com/numpy/numpy/blob/c11628abd820a1f44b052ea87af810f8f00cf2e4/doc/Py3K.rst.txt#pyfile

**Comment by pv** [comment] 2018-05-22 09:14
Basically, the situation is that Python 3 has very limited C-level API 
for file I/O, https://docs.python.org/3/c-api/file.html, and the low-
level I/O in Numpy should basically be rewritten to act on PyObject*
instead. This was not done so far, and nobody seems to have had the
bandwidth to take it on.

PyObject_AsFileDescriptor works in principle for actual files, but it
appears necessary to do whitelisting of the object classes on which it
can be called, because even the Python stdlib does not follow a
convention on always giving usable file handles.

**Comment by bashtage** [comment] 2018-05-25 07:47
Might be closable -- it still doesn't work with most file-like objects, but at least it instructs users that this is expected.

**Comment by charris** [comment] 2018-05-25 14:17
OK, closing. Thanks for the heads up.

**Closed by charris** 2018-05-25 14:17 UTC
