### ISSUE TITLE
in-place way in numpy sequential ops?

### ISSUE THREAD

**Issue by litianqi715** [numpy/numpy#14065] opened 2019-07-20 03:53 UTC
I use many numpy sequential ops in my project such as:

```python
resize_array = numpy.uint8(numpy.clip(numpy.rint(resize_array), 0, 255))
```

This code will consume another piece of memory same size as resize_array and cause "lack of memory" error sometimes.

I have tried 
```python
resize_array = numpy.uint8(numpy.clip(numpy.rint(resize_array, out= resize_array), 0, 255, out= resize_array))
```
as well but it does no good.

Then the following code works, no additional memory is needed, all ops are in-place.
```python
resize_array = numpy.rint(resize_array, out= resize_array)
resize_tensor = numpy.clip(resize_array, 0, 255, out= resize_array)
resize_tensor = numpy.uint8(resize_tensor)
```

But the last one seems exhausted. If there exists hundunds of lines of np array op, I may need to add 1k more lines of code. Is there another way to use in-place memory in numpy sequential ops? Perhaps a global param to shutdown internal memory allocation?
 
### Reproducing code example:
Following code will consume 8G memory in total, doubles at last line

```python
import numpy as np
aa=np.random.random((800,830,830))
aa=np.rint(aa, out=aa)
aa=np.uint8(np.clip(aa,0,255, out=aa))
```

### Numpy/Python version information:

>>> import sys, numpy; print(numpy.__version__, sys.version)
('1.16.4', '2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]')

**Comment by seberg** [comment] 2019-07-22 19:23
If I use `out`, I would probably just assign it `arr = np.function(..., out=arr)` should just be `np.function(..., out=arr)`.

I cannot reproduce the issue on 1.16.2 or 1.17.x, could you double check that it actually does increase memory for you?

**Comment by litianqi715** [comment] 2019-07-23 03:40
@seberg En....yes, I also cannot reproduce the issue now. Not sure what happened in last three days, perhaps the reboot works? Sorry!

**Comment by seberg** [comment] 2019-07-23 05:30
Ok, lets just close for now. Maybe you find what was causing the issue that you saw and we can look into it. Thanks.

**Closed by seberg** 2019-07-23 05:30 UTC
