### ISSUE TITLE
CPU loop in histogram on Mac OS 10.10.5 (14F1021), python 2.7

### ISSUE THREAD

**Issue by mrkite92** [numpy/numpy#6657] opened 2015-11-09 10:46 UTC
Dear Numpy gurus,

Here is a link to download a zipped directory containing a notebook and some associated data. Running the notebook using the file VVD990305K0002.dat works well, while the VVD990305K0001.dat yields a CPU loop. Without a Timeout protection, my Mac Pro's RAM saturates, and finally the computer crashes in panic. 

https://dl.dropboxusercontent.com/u/2021308/loop_numpy.zip

The stack is :
## matching with 2MASS, checking calibration
```
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-2-db69fe1dc1a6> in <module>()
     41     ax = plt.axes()
     42 
---> 43     hist(dist_match, bins='knuth', ax=ax, histtype='stepfilled', ec='k', fc='#AAAAAA')

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroML/plotting/hist_tools.pyc in hist(x, bins, range, _args, *_kwargs)
     64         bins = bayesian_blocks(x)
     65     elif bins in ['knuth', 'knuths']:
---> 66         dx, bins = knuth_bin_width(x, True, disp=False)
     67     elif bins in ['scott', 'scotts']:
     68         dx, bins = scotts_bin_width(x, True)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroML/density_estimation/histtools.pyc in knuth_bin_width(data, return_bins, disp)
    228     dx0, bins0 = freedman_bin_width(data, True)
    229     M0 = len(bins0) - 1
--> 230     M = optimize.fmin(knuthF, len(bins0), disp=disp)[0]
    231     bins = knuthF.bins(M)
    232     dx = bins[1] - bins[0]

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/optimize.pyc in fmin(func, x0, args, xtol, ftol, maxiter, maxfun, full_output, disp, retall, callback)
    375             'return_all': retall}
    376 
--> 377     res = _minimize_neldermead(func, x0, args, callback=callback, **opts)
    378     if full_output:
    379         retlist = res['x'], res['fun'], res['nit'], res['nfev'], res['status']

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/optimize.pyc in _minimize_neldermead(func, x0, args, callback, xtol, ftol, maxiter, maxfev, disp, return_all, **unknown_options)
    461         xbar = numpy.add.reduce(sim[:-1], 0) / N
    462         xr = (1 + rho) \* xbar - rho \* sim[-1]
--> 463         fxr = func(xr)
    464         doshrink = 0
    465 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/optimize/optimize.pyc in function_wrapper(_wrapper_args)
    283     def function_wrapper(_wrapper_args):
    284         ncalls[0] += 1
--> 285         return function(*(wrapper_args + args))
    286 
    287     return ncalls, function_wrapper

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroML/density_estimation/histtools.pyc in **call**(self, M)
    153 
    154     def **call**(self, M):
--> 155         return self.eval(M)
    156 
    157     def eval(self, M):

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroML/density_estimation/histtools.pyc in eval(self, M)
    175 
    176         bins = self.bins(M)
--> 177         nk, bins = np.histogram(self.data, bins)
    178 
    179         return -(self.n \* np.log(M)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.pyc in histogram(a, bins, range, normed, weights, density)
    263             for i in arange(0, len(a), BLOCK):
    264                 sa = sort(a[i:i+BLOCK])
--> 265                 n += np.r_[sa.searchsorted(bins[:-1], 'left'),
    266                            sa.searchsorted(bins[-1], 'right')]
    267         else:
```
Cheers,
JB

**Comment by mrkite92** [comment] 2015-11-09 10:47
Additional comment: I use Python under MacPorts package manager.

JB

**Comment by eric-wieser** [comment] 2018-05-29 05:57
This looks like `astroML` is just using an unreasonable method of estimating bin widths - I'd encourage you to file an issue there

**Comment by mattip** [comment] 2019-01-16 08:09
@mrkite92 what is the value of `bins` in the failing call to `np.histogram`?

**Comment by mattip** [comment] 2019-02-14 19:47
Closing since the issue is quite old and the original reporter has not responded to requests for more info

**Closed by mattip** 2019-02-14 19:47 UTC
Labels: 57 - Close?
