### ISSUE TITLE
Inconsistent behavior when converting strings to floats

### ISSUE THREAD

**Issue by person142** [numpy/numpy#9924] opened 2017-10-25 15:39 UTC
I get this:

```python
>>> np.finfo(np.longdouble).max
1.189731495357231765e+4932
>>> np.longdouble('1.2e4932')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for long double: 1.2e-4932
>>> np.finfo(np.float64).max
1.7976931348623157e+308
>>> np.float64('2e308')
inf
>>> np.__version__
'1.13.1'
```

Since `NPY_INFINITYL` exists, I would expect to get `inf` for both?

**Comment by sidjee** [comment] 2017-10-28 07:42
I would like to work to resolve this issue.
Also, it would be nice to know where to look first.

**Comment by sidjee** [comment] 2017-10-28 19:55
That pull request was obviously a mistake.
I worked again on the code and made a new function:-
```
NPY_NO_EXPORT long double
strtold_new(const char *s,locale_t locale1){
    errno = 0;
    result = 1;
    const char *p;
    p=s;
    while(!errno){
        ++p;
        result = strtold_l(s,p,locale1);
    }
    if(*p!='e' || *p!='E' || !NumPyOS_ascii_isalnum(*p)){
        return 0;
    }
    else{
        errno = 0;
        result *= NPY_INFINITY;
    }
    return result;
}
```
which would replace this function `strtold_l()` in this code
```
clocale = newlocale(LC_ALL_MASK, "C", NULL);
    if (clocale) {
        errno = 0;
        result = strtold_l(s, endptr, clocale);
        freelocale(clocale);
        if (errno) {
            *endptr = (char*)s;
            result = 0;
        }
    }
    else {
        *endptr = (char*)s;
        result = 0;
    }
```
These changes are in file ` numpy/core/src/multiarray/numpyos.c `.
Above function would be giving NPY_INFINITY when the value of long double calculated is out of bounds.

**Comment by sidjee** [comment] 2017-10-29 05:24
Although it slows down the operation a little bit.

**Comment by sidjee** [comment] 2017-10-29 10:14
This PR was definitely a mistake.
I further worked on the code to improve the ` NumPyOS_ascii_strtold ` function as:-
```
clocale = newlocale(LC_ALL_MASK, "C", NULL);
    if (clocale) {
        errno = 1;
        char *x = s;
        long double i = 0;
        int f = 1;
        /*
        This loop will find the long double of
        endptr if strtold_l(x) stops at *endptr.
        This will be done again and again until the whole
        string value is calculated or there is a
        non recognized character in the string.
        */
        while(errno && f){
            errno = 0;
            result = strtold_l(x, endptr, clocale);
            if(*endptr == x)
                f = 0;
            x = *endptr;
            i++;
        }
        freelocale(clocale);
        if(i!=1){
            if(!errno)
                result = NPY_INFINITY;
            else{
                endptr = (char*)s;
                result = 0;
            }
        }
    }
    else {
        *endptr = (char*)s;
        result = 0;
    }
    return result;
```
The previous code was 
```
clocale = newlocale(LC_ALL_MASK, "C", NULL);
    if (clocale) {
        errno = 0;
        result = strtold_l(s, endptr, clocale);
        freelocale(clocale);
        if (errno) {
            *endptr = (char*)s;
        }
    }
    else {
        *endptr = (char*)s;
        result = 0;
    }
    return result;
```
Can it be further improved??

**Comment by ahaldane** [comment] 2017-10-29 16:32
I agree that it looks like `strtold_l` is failing, but I don't see why the solution should be to loop repeatedly until it works. By failing, `strtold_l` is telling us it can't convert the string to a normal float, so calling it repeatedly won't help.

In this case `strtold_l` is failing because the input string isn't representable as a normal long double, and is returning the errno `ERANGE` meaning "Numerical result out of range", which you can verify by looking at the result of `strerror(errno)`. 

I think the correct solution is detect the `ERANGE` error state, and write code to return the correct result "+/-inf" (or `nan`, depending on the string). To see how to do this, perhaps a look at CPython's `PyOS_string_to_double` for reference will give us a hint, and we might adapt it for `long double`s.

**Comment by sidjee** [comment] 2017-10-30 07:23
Actually I am not iterating ` strtold_l ` over the same string.
This code shows that I am iterating over substrings:-
```
result = strtold_l(x, endptr, clocale);
            if(*endptr == x)
                f = 0;
            x = *endptr;       <----------see this
```
This means that when we get the endptr which points to the locatiion where the calculation stopped and then I am calling `strtold_l` over the new substring starting from `*endptr`.

Also when you were saying about `strerror(errno)`, you didn't considered a case.
Suppose there is a string given to `numpy.longdouble()` as:-
```
str = '12e123456someinvalidcharacters'
numpy.longdouble(str)
```
This will also give show `inf` output which is not correct.

**Comment by sidjee** [comment] 2017-10-30 07:50
What I am saying is that once `strtold_l()` has stopped the calculation we have to check whether the further remaining string will give `NaN` or `inf` cause this will conclude whether the whole numeric string is `NaN` or `inf`.

**Comment by eric-wieser** [comment] 2017-10-31 06:05
> I think the correct solution is detect the ERANGE error state, and write code to return the correct result

That's super easy, because most of the result is already calculated for us:

```
val = strtold(s, endptr);
if (errno == ERANGE) {
    errno = 0;
    val = val > 0 ? NPY_INFINITYl: -NPY_INFINITYl;  // maybe not needed!
}
```

since the spec says:

> If the correct value is outside the range of representable values, plus or
minus HUGE_VAL, HUGE_VALF, or HUGE_VALL is returned (according to the return
type and **sign of the value**),

And I don't know if it's guaranteed that `HUGE_VALL == NPY_INFINITYl`

**Comment by eric-wieser** [comment] 2017-10-31 06:08
@sidjee, your approach is wrong. It's not `strtold`s job to tell if there's string left over, that's the callers job, and we already do that, by checking that `*end == NULL` (the end of the string).

**Comment by eric-wieser** [comment] 2017-10-31 06:09
On my machine (windows), I get the clearer error `invalid literal for long double: 1.2e4932 (Result too large)`

**Comment by eric-wieser** [comment] 2017-10-31 06:10
These lines are why you aren't seeing a better error message:

```c
#ifdef HAVE_STRTOLD_L
    clocale = newlocale(LC_ALL_MASK, "C", NULL);
    if (clocale) {
        errno = 0;
        result = strtold_l(s, endptr, clocale);
        freelocale(clocale);
        if (errno) {
            *endptr = (char*)s;   // WHY
        }
    }
    else {
        *endptr = (char*)s;
        result = 0;
    }
    return result;
#else
```

I have no idea why we mangle the `endptr` if `errno` was set, rather than letting it escape as it was.

**Comment by eric-wieser** [comment] 2017-10-31 06:12
In fact, that's outright dangerous, as `endptr` might be `NULL`.

**Comment by eric-wieser** [comment] 2017-10-31 06:13
Thinking about it, it's probably the callers job to handle `ERANGE` anyway?

**Comment by eric-wieser** [comment] 2017-10-31 06:47
Proposed patch, after #9944:

```diff
--- a/numpy/core/src/multiarray/arraytypes.c.src
+++ b/numpy/core/src/multiarray/arraytypes.c.src
@@ -356,7 +356,14 @@ string_to_long_double(PyObject*op)
     if (s) {
         errno = 0;
         temp = NumPyOS_ascii_strtold(s, &end);
-        if (errno) {
+        if (errno == ERANGE) {
+            if (PyErr_Warn(PyExc_RuntimeWarning,
+                    "overflow encountered in conversion from string") < 0) {
+                Py_XDECREF(b);
+                return 0;
+            }
+        }
+        else if (errno) {
             PyErr_Format(PyExc_ValueError,
                          "invalid literal for long double: %s (%s)",
                          s,
@@ -364,7 +371,8 @@ string_to_long_double(PyObject*op)
             Py_XDECREF(b);
             return 0;
         }
-        else if (end == s || *end) {
+
+        if (end == s || *end) {
             PyErr_Format(PyExc_ValueError,
                          "invalid literal for long double: %s",
                          s);
```

**Comment by sidjee** [comment] 2017-10-31 12:00
@eric-wieser  In one of my previous comments I explained how this may be wrong.
Consider this case:-
```
numpy.longdouble('12e12345abcd')
```
Just by doing this patch doesn't assure the return value to this call is `Invalid literal` and not `inf`.

**Comment by sidjee** [comment] 2017-10-31 12:44
Also I tested `strtold("12e1234",&e)` and it gave me same `errno` as `ERANGE` but `e` was a null string.
Which means my previous approach was apparently wrong.

So I reworked on it and I think this patch willl do it:-
```diff
errno = 0;
result = strtold_l(s, endptr, clocale);
freelocale(clocale);
if (errno) {
+    if(!*endptr){
+        result = NPY_INFINITY;
+    }
+    else{
         *endptr = (char*)s;
+    }
}

**Comment by eric-wieser** [comment] 2017-10-31 16:08
> Consider this case:-
>
>    numpy.longdouble('12e12345abcd')  #inf not Invalid literal
>
> Just by doing this patch, this call will return inf and not Invalid literal.

That's what it's supposed to do. It should return `result = inf` and `endptr = "abcd"`.

Your patch is wrong again, because:
* It doesn't returning infinity in the case above
* it doesn't check for `ERANGE`
* it doesn't check for negative numbers.
* As I mention above, the existing `*endptr = (char*)s;` line is wrong.

**Comment by sidjee** [comment] 2017-10-31 16:28
If `*endptr` is `NULL` as well as `errno` is set then there is only 1 possibility that calculated value is out of range. Thus without checking `ERANGE` it does fix the issue and addresses the problem I mentioned.

Negative numbers are obviously been checked by `strtold` and there's no additional requirement for that.
`*endptr = (char*)s` line was not added by me it was there already to set `*endptr` value if error `Invalid Literal` occurred.

I don't understand why is it necessary to check `ERANGE` when the problem is fixed without it.
Do give it a thought if you understood my point.

**Comment by eric-wieser** [comment] 2017-10-31 16:43
> If `*endptr` is `NULL` as well as `errno` is set then there is only 1 possibility

`*endptr == NULL` is a red herring, and tells you nothing about whether the value is out of range - all it tells you is whether there are extra characters on the end of whatever number was found.

> I don't understand why is it necessary to check ERANGE 

It seems that [on some platforms](https://www.ibm.com/support/knowledgecenter/en/ssw_aix_61/com.ibm.aix.basetrf2/strtof.htm), `strtold` can return `EINVAL`:

> Upon successful completion, the strtof and strtold subroutines return the converted value. If no conversion could be performed, 0 is returned, and the errno global variable may be set to EINVAL.

You shouldn't just assume the error that happened is the one you were expecting, especially when its so easy to check.

> Negative numbers are obviously been checked by `strtold` and there's no additional requirement for that.

Correct, but then you ignore the result of strtold and always return positive infinity.

**Closed** 2017-11-05 22:25 UTC
Labels: 00 - Bug
