### ISSUE TITLE
Inconsistent behavior for ufuncs in Numpy v1.10.X

### ISSUE THREAD

**Issue by jsolbrig** [numpy/numpy#7122] opened 2016-01-26 17:50 UTC
I am copying this from a discussion on the mailing list.  

I am attempting to subclass numpy.ma.MaskedArray.  I am currently using Python v2.7.10.  The problem discussed below does not occur in Numpy v1.9.2, but does occur in all versions of Numpy v1.10.x including v1.10.4.

Using mathematical operators on my subclass behaves differently than using the analogous ufunc. When using the ufunc directly (e.g. np.subtract(arr1,
 arr2)), __array_prepare__, __array_finalize__, and __array_wrap__ are all called as expected, however, when using the symbolic operator (e.g. arr1-arr2) only __array_finalize__ is called. As a consequence, I lose any information stored in arr._optinfo when a mathematical operator is used.
Here is a code snippet that illustrates the issue.

    #!/bin/env python

    import numpy as np
    from numpy.ma import MaskedArray, nomask

    class InfoArray(MaskedArray):
        def __new__(cls, info=None, data=None, mask=nomask, dtype=None, 
                    copy=False, subok=True, ndmin=0, fill_value=None,
                    keep_mask=True, hard_mask=None, shrink=True, **kwargs):
            obj = super(InfoArray, cls).__new__(cls, data=data, mask=mask,
                          dtype=dtype, copy=copy, subok=subok, ndmin=ndmin, 
                          fill_value=fill_value, hard_mask=hard_mask,
                          shrink=shrink, **kwargs)
            obj._optinfo['info'] = info
            return obj

        def __array_prepare__(self, out, context=None):
            print '__array_prepare__'
            return super(InfoArray, self).__array_prepare__(out, context)

        def __array_wrap__(self, out, context=None):
            print '__array_wrap__'
            return super(InfoArray, self).__array_wrap__(out, context)

        def __array_finalize__(self, obj):
            print '__array_finalize__'
            return super(InfoArray, self).__array_finalize__(obj)

    if __name__ == "__main__":
        arr1 = InfoArray('test', data=[1,2,3,4,5,6])
        arr2 = InfoArray(data=[0,1,2,3,4,5])

        diff1 = np.subtract(arr1, arr2)
        print diff1._optinfo

        diff2 = arr1-arr2
        print diff2._optinfo

If run, the output looks like this:

    $ python test_ma_sub.py 
    #Call to np.subtract(arr1, arr2) here
    __array_finalize__
    __array_finalize__
    __array_prepare__
    __array_finalize__
    __array_wrap__
    __array_finalize__
    {'info': 'test'}
    #Executing arr1-arr2 here
    __array_finalize__
    {}

Currently I have simply downgraded to 1.9.2 to solve the problem for myself, but have been having difficulty figuring out where the difference lies between 1.9.2 and 1.10.0.

**Comment by charris** [comment] 2016-01-26 18:08
Looks like 3c6b6bab is the problem commit.

**Comment by charris** [comment] 2016-01-26 18:15
@mhvk Thoughts?

**Comment by mhvk** [comment] 2016-01-26 18:35
@charris - I'll need to look in more detail, which will not be before next week (graduate admissions...). I suspect #5864 more, though, since that directly touched the binary operations (CC @njsmith)

**Comment by charris** [comment] 2016-01-26 19:03
@mhvk I did a bisection and 3c6b6ba is guilty ;) #5864 was my first thought also.

**Comment by jsolbrig** [comment] 2016-01-26 19:27
This is getting a little deep for me at this point, though I will try to help if I can.

While reverting to v1.9.3 solves my current issues, it seems to me that the behavior is incorrect even in the 1.9.3 release.  Calling `np.subtract(arr1, arr2)` correctly enters both __array_prepare__ and __array_wrap__.  Using the subtraction operator (`arr1-arr2`) skips this functionality, which goes counter to the numpy documentation on subclassing ndarray which states that __array_prepare__ is called "before every ufunc" and __array_wrap__ is called "at the end of every ufunc".  This is a problem for code that attempts to properly use __array_prepare__ and/or __array_wrap__ to maintain metadata.  

One issue compounded the other leaving me very confused I think.

**Comment by charris** [comment] 2016-01-26 19:33
@jsolbrig Binary ops are handled a differently from ufuncs as they interact with Python, i.e., Python makes the call to the subtract method. The proper way to handle that is a current topic of ~~discussion~~ contention.

**Comment by jsolbrig** [comment] 2016-01-26 19:39
@charris Wouldn't that mean that the documentation is incorrect, then?  The subtraction operator still calls a ufunc, but __array_prepare__ and __array_wrap__ are not called [as specified in the documentation.](http://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.classes.html#numpy.class.__array_prepare__)  I would expect the behavior of the operator and the function to be exactly the same from the standpoint of subclassing from MaskedArray.

**Comment by seberg** [comment] 2016-01-26 19:42
The thing is that ufunc wrapping works on the `ndarray` level, but masked arrays do *not* get passed into the ufuncs, instead they have their own set of functions. MaskedArrays are not part of the core numpy API and as such they neither have to, nor ever did call those methods. Of course you are right to say that it would be nice if they would behave like a real numpy array, but they are unfortunatly just a tag on module, with all the problems that come with it.

**Comment by jsolbrig** [comment] 2016-01-26 19:46
Okay, yeah, that makes sense.  It does make me wonder, though, if \__array_prepare__ and \__array_wrap__ should be called inside the \__call__ method of \_MaskedBinaryOperation and other similar classes in order to keep consistent behavior for subclassing and make it easier for others in the future.

**Comment by njsmith** [comment] 2016-01-26 21:02
Sure, maybe? It's basically impossible to fix ndarray subclassing to work well, and then MaskedArray has a giant pile of hacks to make it kinda-sorta-work as an ndarray subclass, and then you're trying to subclass *that*. So... if there's an additional hack that will make your particular use case work, then might as well try it; it's unlikely to make things worse :-). (And the accidental regression versus 1.9 is certainly not OK; sorry about that.) As a piece of general advice though I'd strongly recommend trying to find some way to solve your problem that doesn't involve subclassing any of these things :-)

**Comment by jsolbrig** [comment] 2016-01-26 21:30
Yep, I've basically come to the same conclusion that subclassing MaskedArray is probably the wrong solution.  I'm going to have to think about how best to go about it, though.  Using MaskedArray the way I have been has been so convenient other than this problem.  I now have a workaround for this problem and everything seems to work the way I would hope, but it's a little worrisome that it was so difficult to achieve.

After looking at it a bit more, though, it does appear that if called in the appropriate location in _MaskedBinaryOperation, __array_prepare__ and __array_wrap__ would actually work the way they are supposed to.  Do you think it would be worth me looking into how to implement the numpy-consistent behavior?

**Comment by njsmith** [comment] 2016-01-26 21:34
My personal policy is to leave np.ma maintenance to those who care enough to fix things. So really it's up to you to decide whether it's a worthwhile use of your time :-). We would probably merge a pull request that fixed the regression, at least.

**Comment by mhvk** [comment] 2016-01-26 21:38
@jsolbrig - just as a background: the PR that broke things for you tried to fix the case where the `MaskedArray` *contains* an `ndarray` subclass, so we should try to keep that intact (which I think should not be a problem; and anyway, it has test cases...). Anyway, am quite happy to look at possible solutions.

**Comment by mhvk** [comment] 2016-01-27 16:03
Just so it doesn't get lost, in the thread on numpy-dev, @seberg wrote:
> Well, there was definitely a change in that code that will cause this, i.e. the code block:
```
        if isinstance(b, MaskedArray):
            if isinstance(a, MaskedArray):
                result._update_from(a)
            else:
                result._update_from(b)
        elif isinstance(a, MaskedArray):
            result._update_from(a)
```
> was changed to something like:
```
        masked_result._update_from(result)
```

**Comment by charris** [comment] 2016-02-09 20:37
@mhvk Ping...

**Comment by mhvk** [comment] 2016-02-09 21:07
Overwhelmed by my day job right now, in particular graduate admission, but a break is at least in sight...  Hopefully still this week.

**Comment by charris** [comment] 2016-02-20 17:20
@mhvk Ping! I'd like to get another beta out this weekend, what does your schedule look like?

**Comment by mhvk** [comment] 2016-02-20 20:29
The break took longer in coming than expected, but now do have some time. Hopefully this weekend or Monday.

**Comment by charris** [comment] 2016-02-20 21:15
> The break took longer in coming than expected

They always do ;)

**Comment by mhvk** [comment] 2016-02-21 01:19
@jsolbrig - as noted by @seberg and @njsmith, in general one cannot expect a `np.ufunc` call to do exactly the same as a masked array method -- those are all overwritten to do (in principle) the same as `np.ma.ufunc` (I think this is a mistake, but that is with the benefit of hindsight and knowing that something like `__numpy_ufunc__` could resolve this much more elegantly). Anyway, it is also clear that in my original PR to get masked arrays holding ndarray subclasses to work better, I went too far, not quite understanding what I was doing. Hopefully, this will be resolved in #7296...  Note that I used your sample above as a test case (really useful to have it!); still, please check it resolves your larger issue as well.

**Closed** 2016-02-21 03:35 UTC
Labels: 12 - Regression, component: numpy.ma

**Comment by jsolbrig** [comment] 2016-02-22 18:36
@mhvk - Thanks for looking at this.  In my time looking at this I had started wondering why `__numpy_ufunc__` wasn't used here, but it seems that the answer might simply be legacy at this point.  I may look at this now and then to see if I can figure out how to clean some of this up.  Using `__numpy_ufunc__` seems much more appropriate and cleaner that what is currently done and would make MaskedArray significantly easier to maintain in the long-run.  Thankfully things like `_MaskedBinaryOperation` are well isolated, so testing a new solution shouldn't require much modification to the main body of `MaskedArray`.  Do you see any reason that trying to re-implement the ufuncs through `__numpy_ufunc__` wouldn't work?

**Comment by mhvk** [comment] 2016-02-22 18:42
@jsolbrig - yes, definitely, `__numpy_ufunc__` would be the way to go! Though with all the discussion about how exactly to use it (#5844), it may be good to wait a little before spending serious time (that said, the essence is not going to change).

**Comment by jsolbrig** [comment] 2016-02-22 21:27
@mhvk - Thanks for pointing out that thread.  I'll work through it and start participating in the conversation at minimum.  Hopefully I can help create a decent solution, too.  Finding a good solution for this issue would be very helpful for one of my current projects.

**Comment by mhvk** [comment] 2016-02-22 21:30
That's a *very* long one -- though in the mailing list we had concluded that, really, to make progress on `__numpy_ufunc__` it would be very helpful if someone summarized the issues, so in that respect an independent view might be quite useful. (But definitely don't feel obliged...)

**Comment by jsolbrig** [comment] 2016-02-22 21:54
I'll see what I can do.  It would be nice to get involved in one of the
projects that I use so frequently and making a summary would be a good
introduction to the issues surrounding the issues.  I'm not feeling any
obligation beyond wanting to see that what I see as a problem gets fixed
and realizing that I am probably one of a very small set of people who care
enough to have even bothered to dig this deep.

**Comment by mhvk** [comment] 2016-02-22 22:00
That's how it started for me too...  And `__numpy_ufunc__` is a really nice idea.
