### ISSUE TITLE
QST: Install from source without blas with pip

### ISSUE THREAD

**Issue by snowman2** [numpy/numpy#24703] opened 2023-09-14 01:41 UTC
When trying out latest release candidate:

From: https://github.com/pyproj4/pyproj/pull/1330#issuecomment-1718542223

Is there an environment variable you can set to not require blas when installing numpy?

```
/meson.build:207:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
```

**Comment by mattip** [comment] 2023-09-14 05:46
Is this a duplicate of #24704? I think the problem is that the project has a test dependency on NumPy and ends up building from source instead of using pre-built wheels.

**Comment by rgommers** [comment] 2023-09-14 08:23
Besides the "wheels are coming", the answer to the question when you build from source is (as hinted at in the error message) that this works:
```
$ pip install numpy -C-Dallow-noblas=true
$ # or with pypa/build from a local repo
$ python -m build -C-Dallow-noblas=true
```

There is no environment variable to do the same thing. We may relax the requirement for having BLAS installed, but I think it'd be good to see how many people find the current state a problem with the final 1.26.0 release which will include 32-bit Windows wheels.

**Comment by snowman2** [comment] 2023-09-14 12:07
Thanks for the responses 👍

> Is this a duplicate of #24704?

These failures are different because they are for pypy builds and for the i686 architecture. If the wheels are coming, this shouldn't be an issue.

**Comment by snowman2** [comment] 2023-09-17 03:18
For anyone who runs into this - based on: 
- https://meson-python.readthedocs.io/en/latest/how-to-guides/meson-args.html
- https://github.com/numpy/numpy/blob/ba2935d3521e288048ab4a3384d4f22d9975ea09/.circleci/config.yml#L61

This is the syntax for pip:
```
python -m pip install numpy --config-settings=setup-args="-Dallow-noblas=true" 
```

**Comment by aptalca** [comment] 2023-09-19 16:14
> We may relax the requirement for having BLAS installed, but I think it'd be good to see how many people find the current state a problem with the final 1.26.0 release which will include 32-bit Windows wheels.

This will be an issue for aarch64 users on musl based systems as numpy does not provide binary wheels for that. We ([linuxserver.io](https://github.com/linuxserver)) are facing that issue on our docker images that are alpine based with aarch64 images

**Comment by rgommers** [comment] 2023-09-19 20:16
@aptalca thanks for that comment. To make sure I'm understanding it right: are you saying that you're seeing failed builds and that's a problem, or also that it's fine to avoid the failed builds by default by building fallback linear algebra routines that may be ~50x slower?

**Comment by aptalca** [comment] 2023-09-19 23:36
Sorry, I should have clarified.

We are seeing failed builds due to the newly enforced openblas requirement. Previously, numpy would build without openblas just fine. Now we have to either add openblas or add the build argument to allow building without openblas.

In most cases (for us) the speed difference is not noticeable as the apps we build don't rely on complex calculations.

**Comment by Itsmittyhere** [comment] 2023-09-21 22:31
I am trying to install: 
~/klippy-env/bin/pip install -v numpy

I get this error: 
 Library m found: YES
  Found CMake: /usr/bin/cmake (3.18.4)
  WARNING: CMake Toolchain: Failed to determine CMake compilers state
  Run-time dependency openblas found: NO (tried pkgconfig and cmake)
  Run-time dependency openblas found: NO (tried pkgconfig and cmake)

  ../../numpy/meson.build:207:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).

  A full log can be found at /tmp/pip-install-gmgwihuj/numpy_9524064cd0ae4863b894d750518a40a5/.mesonpy-utl0nn8j/build/meson-logs/meson-log.txt
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/pi/klippy-env/bin/python /home/pi/klippy-env/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp2fcjefqc
  cwd: /tmp/pip-install-gmgwihuj/numpy_9524064cd0ae4863b894d750518a40a5
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2 -> 23.2.1
[notice] To update, run: python -m pip install --upgrade pip
pi@voron:~ $

I tried to do this python update, but apparently it doesn't update either. I have no idea what to do.
Thanks in advance.

**Comment by mattip** [comment] 2023-09-22 05:07
@Itsmittyhere what version of python are you using on what platform? Do you intend to build from source? You need to install the development version of a BLAS library.

**Comment by fuglede** [comment] 2023-09-22 11:35
FWIW: I ran into this one while using [cibuildwheel](https://github.com/pypa/cibuildwheel) to build a package that relies on NumPy. Based on your discussion, I have to imagine there's some way of configuring `setup.cfg` to specify "allow-noblas" somehow, but since I have no particular need for supporting PyPy/i686, I could get around it by adding
```toml
[tool.cibuildwheel]
skip = ["pp*", "*i686"]
```
to `pyproject.toml`.

**Comment by rgommers** [comment] 2023-09-22 17:15
Thanks for the comment @fuglede. Using `numpy` as a build dependency on platforms for which we don't publish wheels is a tricky one, and perhaps the best reason so far to go back to `allow-noblas=true`.

There's no config file or environment variable to set that can address this I believe. The way to do it would be to call `pip install numpy -C-Dallow-noblas=true` in the "before build" stage of the `cibuildwheel` invocation.

**Comment by ReenigneArcher** [comment] 2023-10-05 01:22
Also facing this in a docker multiarch build using the `python:3.9.6-slim-bullseye` base image.

I tried adding these packages but it still didn't build.

```txt
build-essential \
cmake \  # after first error said something like cmake installed: NO
libopenblas-dev \
```

Now cmake is found, but openblas is still not found.
```
Found CMake: /usr/bin/cmake (3.18.4)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency openblas found: NO (tried pkgconfig and cmake)
Run-time dependency openblas found: NO (tried pkgconfig and cmake)

../../numpy/meson.build:207:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
```

**Comment by rgommers** [comment] 2023-10-05 08:47
@ReenigneArcher I can't see what's up with that CMake detection. The CMake config files should be packaged, says the [file list here](https://packages.debian.org/bullseye/i386/libopenblas-pthread-dev/filelist).

That said, `pkg-config` is more reliable, and you don't have that installed:
```
Did not find pkg-config by name 'pkg-config'
```
So perhaps try again with that? `pkg-config` will be tried first, before CMake.

**Comment by ReenigneArcher** [comment] 2023-10-05 12:34
@rgommers replacing `cmake` with `pkg-config` resolved it. Thank you!

**Comment by mattip** [comment] 2023-10-05 13:33
It would be nice to debug why the CMake files supplied with openblas are not sufficient. Is there a command-line interface to the cmake module discovery mechanism?

**Comment by rfrenchseti** [comment] 2023-10-20 19:52
Just adding to the above comments, I just ran into the same problem trying to update a package I maintain (that depends on numpy) to work with Python 3.12. I tried everything I could think of, including adding the cibuildwheel pre-install of numpy with the `allow-noblas=true` option and I just couldn't get it to work. Disabling the build of `*i686` eventually solved the problem, but is obviously not ideal.

**Comment by ReenigneArcher** [comment] 2023-10-20 21:02
@rfrenchseti try adding these packages before installing numpy.

```
        pkg-config \
        libopenblas-dev \
```

Names may be different depending on which distro.

**Comment by kif** [comment] 2023-10-26 20:55
Just for info, we face the same issue when doing CI on an architecture where no wheels are provided (PPC64le).
Numpy should just build by default, even with the largest warning about bad performances, but it should not fail building because so many projects have numpy as a dependency.

**Comment by rgommers** [comment] 2023-11-03 19:42
Thanks for the input everyone. I just opened gh-25063 to revert the default to `allow-noblas=true`. That should land in `1.26.2` and `2.0`.

**Closed** 2023-11-03 21:21 UTC
Labels: 33 - Question, 32 - Installation
