### ISSUE TITLE
Static typing read-only Array 

### ISSUE THREAD

**Issue by JosiahKane** [numpy/numpy#16955] opened 2020-07-27 15:07 UTC
The main Python typing module supplies types for `Sequence` and `Mapping` which can broadly be understood as read-only `List` or `Dict` types. This means that a function can annotate an input as `Sequence` to indicate that it is safe to pass a `List` (or something sufficiently list-like) with confidence that the function will not change that parameter. Likewise if a function returns a `Sequence` the calling code is bound not to mutate it.

The existing [writeable flag](https://numpy.org/devdocs/reference/generated/numpy.ndarray.flags.html) works to check similar things at runtime, but of course cannot afford the sorts of guarantees possible with static typing. 

This is a request for a similar Read-only numpy array type. 

- The basic rule is that operations which would change the underlying buffer, such as `__setitem__` or `+=` should simply not exist in the definition of the read-only Array type.
- A read-only array should be a super-type of a regular array. Using a regular array in a context that expects a read-only one should be fine. Using a read-only one in a context that expects a regular array should fail, because that would break the guarantee that it won't be written to. 
- As with the writeable flag, reading operations (including things like slices and views) on a read-only array that would return another numpy array should be annotated as returning a read-only one. 
- However operations on read only arrays that allocate fresh memory can return regular arrays. For example `sum` (so long as it's not in-place) and of course `copy` are not restricted.
- In general, most pure input parameters should be annotated as accepting read-only arrays. Output parameters (notably `out`) should be annotated as only accepting regular mutable arrays. Return types should typically be regular arrays; these can of course be assigned immediately to variables marked read-only.
- As with the writeable flag, this is not a guarantee that the memory buffer will not change. It is just enforcing that it won't be changed by something that only has read-only access.

Examples
```
a: ReadOnlyArray = np.ones((5,5))
b: ReadOnlyArray = np.ones((5))
a += 1 # fails
a[2, 3] = 1 # fails, setitem is not allowed
a.sum() # passes
a.sum(axis=1) # passes
np.vstack([a, b]) # passes, vstack can be typed to work with read-only data.
a.sum(axis=1, out=b) # fails: out parameter should be typed to expect mutable arrays.
a[2].sum() # passes, getitem is fine.
a[2] += 1 # fails, getitem also returns a read-only array.
```

**Comment by rgommers** [comment] 2020-07-27 15:48
@JosiahKane it would be useful to add a motivation for your request. There's a lot of _what_ in your description, but not _why_.

**Comment by eric-wieser** [comment] 2020-07-27 16:46
I suspect you can get a long way today by just annotating readonly arrays with `ArrayLike` instead of `ndarray`, since this already covers the in / out argument distinction.

**Comment by JosiahKane** [comment] 2020-07-27 19:55
@rgommers that's a very fair comment. 

Essentially it affords similar benefits to "const" in many languages such as C++. In terms of correctness, it conveys and enforces any expectations that something should not be changed and any promises that it will not be. 

For a real motivating example, I'm working on a computer vision program. I have a class that uses a 3d array as a video buffer, and this class exposes a `getFrame` method which allows access to 2d frames. I would like to prevent consumers from accidentally writing back over the data in the common buffer. Currently my reasonable options are to have `getFrame` end with a copy call so that no-one sees the original buffer, or to have `getFrame` mark the `writeable` Flag as False so that anything which tries to scribble on it throws an error. The former is relatively safe (and is in fact our current practice) but costly. Rewriting towards the latter would be cheaper, but carries risks of runtime exceptions slipping through if we don't have 100% branch coverage in our tests. Static type checking would be free at runtime, and allow automated checking of every execution path. If `getFrame` is annotated as returning a `ReadOnlyArray`, then anything which tried to scribble on the returned frame would fail type-checking, and we'd immediately know which consumers have to make a copy. 

Further down the line, once support for specifying dtypes lands, this also becomes relevant for allowing handling of covariance. Mutable containers have to be invariant, whereas immutable containers can be covariant. [PEP-484](https://www.python.org/dev/peps/pep-0484/#covariance-and-contravariance) explains more detail. In summary 
`def foo(arr: np.ndarray[signedinteger]):` is something that might be useful to express, but wouldn't safely pass muster. 
On the other hand `def foo(arr: np.ReadOnlyArray[signedinteger]):` would be fine, and the type checker could ensure it's OK to be called by an array of int8, or int32, and reject calls with arrays of float. 

Finally, it can be useful just for people reading the code to see at a glance of the function signature what can change and what can't.

**Comment by JosiahKane** [comment] 2020-07-27 20:07
@eric-wieser, I did think about that, but I think that ArrayLike is too broad. For example, a function annotated as taking a ReadOnlyArray `arr` should be able to rely on `__getitem__` being valid for indexing. Because ArrayLike even includes `bool`, that is not the case. Functions that used that approach would have to immediately switch to a regular array (with no guarantees on whether that's a copy or a shared buffer) at which point there would be no protection for the read-only-ness.

**Comment by BvB93** [comment] 2020-07-28 10:06
As a duct tape solution you could create a (type-checking only) `np.ndarray` subclass and 
annotate all methods which perform in-place methods as `None`.
With `typing.cast` you can force the type checkers to recognize your arrays as 
these "read-only arrays". 
``` python
from typing import cast
import numpy as np

class ReadOnlyArray(np.ndarray):
    __setitem__: None  # type: ignore
    ...

a = cast(ReadOnlyArray, np.ones(10))
a[0] = 1
```
``` shell
>>> mypy test.py
test.py:9: error: "None" not callable
Found 1 error in 1 file (checked 1 source file)
```

**Comment by JosiahKane** [comment] 2020-07-28 11:14
@BvB93, thank you for the suggestion, but I think that's upside down. Array should be a subclass (or rather subtype) of ReadOnlyArray, in the same way as List is a subtype of Sequence. One major issue is that things can climb silently to supertypes. 

Consider this snippet
```
def check(arr: ReadOnlyArray) -> bool:
    """This is annotated to confirm it's safe and won't change arr"""
    return np.any(arr)

def blank(arr: np.ndarray) -> None:
    """This is annotated to warn that it can and will change arr"""
    arr *= 0

a: ReadOnlyArray = foo()
check(a) # This should pass
blank(a) # This should fail, because a must not change.
b: np.ndarray = a # This should also fail, because it loses the promise that this buffer must not change.

c: np.ndarray = bar()
check(c) # This should pass, because it's safe to refrain from writing.
blank(c) # This should pass, because c is writeable.
d: ReadOnlyArray = c # This should pass, because it's safe to promise to refrain from writing.
```

If ReadOnlyArray is a subtype of np.ndarray, many of these are backwards. 
`blank(a)` passes because a ReadOnlyArray is an ndarray, so it just gets silently casted up. The same happens with `b: np.ndarray = a`
Meanwhile `check(c)` and `d: ReadOnlyArray = c` fail, because np.ndarray may not be ReadOnly, so it takes a explicit cast to confirm. 

We then wind up in the weird situation where we need explicit casts to use things that promise not to overwrite our data, and get no warnings at all when using things that are dangerous! 
__________
More conceptually, Liskov Substitutability requires that objects of subtypes be able to stand in place of a supertype. 
This implies that you can add functionality as you go down the inheritance hierarchy, but you can't remove it. All arrays must be readable, which makes reading something you want in your parent type. Only some can be written, which means writing is something you'd want in the child type. If they flip, you have ReadAndWriteArray as your base class, and then ReadAndWriteButWithoutWritingArray as your child class. Obviously you wouldn't call it that, but it emphasises that writing functionality is something that has been removed as you go down the hierarchy.

**Comment by rgommers** [comment] 2020-07-29 22:00
> I would like to prevent consumers from accidentally writing back over the data in the common buffer.
> ....
> Finally, it can be useful just for people reading the code to see at a glance of the function signature what can change and what can't.

I have the impression you're coming from another language. This isn't really feasible as a general strategy in Python, it's too flexible. The basic rule is: never mutate parameters that are passed to you, unless the docs of whatever you're consuming explicitly say it's designed for in-place modifications. So for your "finally": the answer is "nothing" by default, if any array/list/whatever input is mutated it's a bug.

If this was very easy to do I think we could consider it, but asking for a new superclass of `ndarray` seems like a nonstarter - you're asking for a lot of work and new public API, for not much benefit.

**Comment by person142** [comment] 2020-07-30 03:48
> but asking for a new superclass of ndarray seems like a nonstarter - you're asking for a lot of work and new public API, for not much benefit.

Agreed, especially since we haven't had a public release of the types yet! Until users have actually had a chance to try out (and surely find a bunch of problems with) what's there it feels premature to add on new things.

**Comment by JosiahKane** [comment] 2020-07-30 08:26
> I have the impression you're coming from another language. This isn't really feasible as a general strategy in Python, it's too flexible. The basic rule is: never mutate parameters that are passed to you, unless the docs of whatever you're consuming explicitly say it's designed for in-place modifications. So for your "finally": the answer is "nothing" by default, if any array/list/whatever input is mutated it's a bug.
> 
> If this was very easy to do I think we could consider it, but asking for a new superclass of `ndarray` seems like a nonstarter - you're asking for a lot of work and new public API, for not much benefit.

@rgommers, I'm not sure what gives you that impression. Of course the idea of static analysis of mutability is not particular to Python. Other languages have been playing the static analysis game for a while longer. They have shown it to be valuable. However my opening statement wasn't refering to them. Instead I referred to the Python standard library! 

As to the claim "if any array/list/whatever input is mutated it's a bug," that's kind of the point. Static analysis is there to catch bugs! Of course it won't stop everything: as you say, Python is too flexible. Any language that allows redefining classes at runtime or accessing attributes by string name is intrinsically impossible to have a comprehensive automated bug catcher. But in practice, most code uses more conventional methods and properties and such. A difference of type (not necessarily class) to demarcate which methods or properties are safe would help with that.

Most importantly, since this seems to be your real objection
"asking for a new superclass of ndarray seems like a nonstarter"
I'm asking for a **supertype** of ndarray. It doesn't have to be a **superclass**. For example, a complete-enough-to-help version might be done using a PEP-544 [Protocol](https://docs.python.org/3/library/typing.html#typing.Protocol). That does not need explicit listing in the inheritance tree. It just needs to provide stubs for the methods and properties that are safe.

**Comment by eric-wieser** [comment] 2020-07-30 08:31
Just to throw in my 2 cents - I think adding readonly arrays to static typing is a neat idea, but I think it's too much complexity for the initial release of the typing stubs within numpy. I don't think we should close this issue, but I do think we should put it off until at least 1.21.

One of the issues here is it doubles the number of overloads we have to specify for functions which return views that match the readonly-ness of their input.

**Comment by rgommers** [comment] 2020-07-30 09:41
> I'm asking for a supertype of ndarray. It doesn't have to be a superclass. 

sorry yes, brain not working late at night

> Other languages have been playing the static analysis game for a while longer. They have shown it to be valuable.
> ...
> A difference of type (not necessarily class) to demarcate which methods or properties are safe would help with that.

I'm not sure, it feels philosophically wrong to type a mutable container as immutable. It's a deliberate mistyping designed to catch one particular category of user error. There's more such categories that could be brought up, like not wanting users to access private attributes/methods, to not monkeypatch things, etc. - I'm sure there's more.

**Comment by JosiahKane** [comment] 2020-07-30 13:21
> Just to throw in my 2 cents - I think adding readonly arrays to static typing is a neat idea, but I think it's too much complexity for the initial release of the typing stubs within numpy. I don't think we should close this issue, but I do think we should put it off until at least 1.21.

Thanks @eric-wieser. That's a very reasonable position. I figured that it was worth raising it early in the typing process so that there would be time to architect it in as appropriate, not because it is immediately urgent. 

> One of the issues here is it doubles the number of overloads we have to specify for functions which return views that match the readonly-ness of their input.

That sounds like a problem that might be resolved with a well-placed TypeVar. 

```
MaybeMutableArray = TypeVar("MaybeMutableArray", ReadOnlyArray, ReadWriteArray)

def identity_view(arr: MaybeMutableArray) -> MaybeMutableArray:
    ...
```
I'm not familiar enough with the numpy (and ecosystem) typing to know whether this would be the best option, but it doesn't multiply the overloads so it seems worth considering.

**Comment by JosiahKane** [comment] 2020-07-30 17:25
> I'm not sure, it feels philosophically wrong to type a mutable container as immutable. It's a deliberate mistyping designed to catch one particular category of user error. There's more such categories that could be brought up, like not wanting users to access private attributes/methods, to not monkeypatch things, etc. - I'm sure there's more.

I agree that being philosophically right is a worthy sort of design goal. I agree that falsely claiming that something has a specific type, however expedient it may seem at the time, causes far more headaches than it saves. On the other hand, identifying something as a more general but still accurate type is entirely consistent. Indeed, it is often necessary to get a suitably loosely coupled architecture. 

I don't want to put words in your mouth, but I suspect the philosophical incongruity in this case may just be my choice of name for the concept. Perhaps "Read-only" has connotations of an object that somehow actively resists mutation. It may help if I instead refer to a `ReadArray` and a `ReadWriteArray`. A standard numpy `ndarray` is a `ReadWriteArray`; it supports reading and it supports writing. Likewise, a standard numpy `ndarray` is a `ReadArray` by effect of supporting reading. There is nothing in the definition of `ReadArray` that says the implementation cannot also have writing methods. It says only that it must have reading methods. It is then not mistyping to take an `ndarray` and pass it to a function or put it in a list or assign it to a variable which expect a `ReadArray`. 

I'm not particularly wedded to the name "ReadOnlyArray". It was just the best I could come up with at the time to convey the intention behind narrowing of the interface. I agree that if it suggests an object that is intrinsically immutable, the name needs to change. The target name should have more connotations of "This is provided to you for reading." than "This is impossible to write to."

**Comment by BvB93** [comment] 2020-09-17 23:04
> That sounds like a problem that might be resolved with a well-placed TypeVar.
> ``` python
> MaybeMutableArray = TypeVar("MaybeMutableArray", ReadOnlyArray, ReadWriteArray)
> 
> def identity_view(arr: MaybeMutableArray) -> MaybeMutableArray:
>     ...
> ```

So there is a significant practical issue here: the implication in using a typevar is that both the class itself as well as its parameters (dtype & shape)<sup>1</sup> are identical across the input and output. 

The problem is that this is often not case; many functions allow/force a modification of the to-be returned array's dtype and/or shape (with respect to the input), meaning we'd somehow have to decouple the class from its parameters in the typevar. This is simply not possible with what's currently available in python's typing system, it lacking the necessary higher-kinded typevars:<sup>2</sup>

``` python

MaybeMutableArray = TypeVar(
    "MaybeMutableArray", ReadOnlyArray[np.dtype], ReadWriteArray[np.dtype]
)
Dtype = TypeVar("Dtype", bound=np.dtype)

# Unfortunately the syntax below is not possible
def identity_view(arr: MaybeMutableArray, dtype: Dtype) -> MaybeMutableArray[Dtype]:  
    ...

```


<sup>1</sup> This will become relevant once `ndarray` has been made generic w.r.t. its dtype and, eventually, its shape.

<sup>2</sup> Higher-kinded typevars, subscriptable typevars, generic typevars, _etc._. Whatever you want to call them. See https://github.com/python/typing/issues/548.

**Comment by BvB93** [comment] 2021-05-14 13:10
Closing this issue for now.

If there is enough interest then it can be reopened. 
Realistically, I don't see this being implemented anytime soon (if ever), especially since we'd first need aforementioned higher-kinded typevars.

**Closed by BvB93** 2021-05-14 13:10 UTC
Labels: static typing
