### ISSUE TITLE
Slight differences of randn output 

### ISSUE THREAD

**Issue by oXwvdrbbj8S4wo9k8lSN** [numpy/numpy#16715] opened 2020-06-30 19:04 UTC
I use unit tests to ensure that my machine learning pipelines always produce the same output if they receive the same input. As input I use artificial data created via sklearn's _make\_classification_ function, which internally uses numpy's _randn_. To save disk space, I cannot save the complete output but instead only save hash values. This strategy worked fine for over a year, but now, suddenly, the output of _randn_ changed slightly so it is not reproducible across different installations. As test systems, I use _scipy-notebook_ docker containers. I am fairly certain that this change is not due to a code change of numpy but must be related to some other library. However, I have no clue which library that might be.

### Reproducing code example:
I ran the following command with the _scipy-notebook_ docker containers tagged as "04f7f60d34a6" and "dd2087c75645":
```
docker run -it jupyter/scipy-notebook:04f7f60d34a6 python -c "import numpy as np; import hashlib; generator = np.random.RandomState(969); X = generator.randn(96, 15); print( hashlib.sha256(X).hexdigest()); print(X.sum()); print((X**2).sum())"
```
returns 
```
hash: 7bfbf39406588f590580d592d0ac9f6ffb8b16127b465f42edbd1c629678880c
sum: 23.204969031109513
squared sum: 1424.408266916314
version: 1.18.5
```
And
```
docker run -it jupyter/scipy-notebook:dd2087c75645 python -c "import numpy as np; import hashlib; generator = np.random.RandomState(969); X = generator.randn(96, 15); print('hash:', hashlib.sha256(X).hexdigest()); print('sum:', X.sum()); print('squared sum:', (X**2).sum()); print('version:', np.__version__)"
```
returns 
```
hash: 3bca3416367b6bf24037240a1905d84f09152cea5c6c8e69d60e0a51060703f4
sum: 23.204969031109513
squared sum: 1424.408266916314
version: 1.18.5
```
As you can see, the sums and squared sums are equal or they differ at less than 10^-12, but the hash values differ.  The numpy versions in both containers are equal. Therefore, which external library might cause this difference?

### Numpy/Python version information:

Both containers give the following output:
```
1.18.5 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)
[GCC 7.5.0]
```

**Comment by rkern** [comment] 2020-06-30 19:31
`RandomState.randn()` uses an algorithm involving a `sqrt()` and a `log()`, so maybe the `libm` library, or whatever is providing the C-standard math functions (some systems put those functions in the main C runtime libraries and leave `libm` as an empty stub).

**Comment by rkern** [comment] 2020-06-30 19:51
The versions of the `libc6` package (which provides `/lib/x86_64-linux-gnu/libm.so.6`) differ between the two containers. `jupyter/scipy-notebook:04f7f60d34a6` appears to be more up-to-date.

**Comment by rkern** [comment] 2020-06-30 20:05
Also, the versions of `gcc` are quite different, `9.3.0` and `7.5.0`, respectively. I don't know how `numpy` was built for these containers, but if they used those installed versions, then it's even possible that they reordered the arithmetic in the expressions, leading to a different rounding in the last place.

This is not very comforting for you, I am sure, but this experience confirms the assertions that we made in [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html). Thank you for bringing this up.

**Comment by oXwvdrbbj8S4wo9k8lSN** [comment] 2020-07-02 12:52
Thanks for the feedback! According to `import sys, numpy; print(numpy.__version__, sys.version)`, numpy was built using GCC 7.5.0 for both containers (as far as I understand the output). So, the different versions of libm are probably the cause. 
I get that it is very difficult to maintain exact reproducibility. But can you specify something like an upper limit for differences between versions? - Something like "never bigger than 10**(-14)"?

**Comment by rkern** [comment] 2020-07-02 13:33
`sys.version` tells you what compiler built the Python executable. I don't think anything records what version of the compiler built `numpy` itself.

[The old policy](https://numpy.org/neps/nep-0019-rng-policy.html#the-status-quo), which is still in effect for `RandomState`, includes this explicitly: `the same results up to roundoff error`. This is that roundoff error, in this case likely driven by differences in `sqrt()` and `log()` from `libm`.

The new policy for `Generator` deliberately omits any guarantee. We can change the stream entirely between versions. What we lose in reproducibility, which was never really achievable due to factors outside of numpy, we gain in the ability to improve the algorithms.

**Comment by rkern** [comment] 2020-07-02 13:35
I'm going to close this issue, as I don't think there is anything that numpy can or should change here. But please feel free to continue to comment if you have more information that you think would help people who find this issue in their searches later.

**Closed by rkern** 2020-07-02 13:35 UTC
Labels: 33 - Question, component: numpy.random

**Comment by oXwvdrbbj8S4wo9k8lSN** [comment] 2020-07-07 09:54
Just as a comment for other people who encounter this problem:
Since the uniform distribution (via `RandomState.rand`) yields - so far - reproducible values on my test systems, I will work around this issue by creating a pseudo-normal distribution by summing up 12 uniformly distributed values. Of course, the tails of the distribution are limited by the interval [-6,6) but for my purpose, this is sufficient.
