### ISSUE TITLE
Error in py_convert_pandas_df(x)

### ISSUE THREAD

**Issue by norapap** [numpy/numpy#15739] opened 2020-03-11 12:38 UTC
Hello!

I'm using Rstudio with reticulate, and when i try to source my python scripts, i got a systemerror. 
When I run the python scripts stand alone it works like charm, the problem only occurs when i want to reach the python data from r.

### Reproducing code example:
> reticulate::source_python(paste0(project_folder,"data.py"))

### Error message:
Error in py_convert_pandas_df(x) : 
  SystemError: <built-in method item of numpy.ndarray object at 0x000002479842B760> returned a result with an error set

### Numpy/Python version information:
Python: 3.6
Numpy: 1.16.4 (I also tried with 1.18)

**Comment by mattip** [comment] 2020-03-11 19:38
This is the worst kind of bug: 
- it touches at least three open-source packages and it is not clear who should debug it: reticulate, pandas, or numpy.
- in order to even start to reproduce it, we would need specific instructions to reproduce your workspace, including versions of all the software involved, how you set it up, what is in `data.py`, and what operating system/version you are using. Even then the chances of someone diving into this are pretty slim, expecially given that the stand-alone script works like a charm.

**Comment by eric-wieser** [comment] 2020-03-11 20:35
As a start - can you paste the _full_ traceback rather than just the last line?

**Comment by norapap** [comment] 2020-03-12 09:41
Thank you for replying, I'm kinda new to R, so it took time to get any traceback (that was the only line I got back), and now I see this: 
Error in py_convert_pandas_df(x) : 
  SystemError: <built-in method item of numpy.ndarray object at 0x00000127056EE850> returned a result with an error set

Detailed traceback: 
  File "C:\Users\nori\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 791, in iteritems
    for k in self.columns:

**Comment by norapap** [comment] 2020-03-12 10:47
And this is the python code:

# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np
import functools as ft


pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.max_columns', 10)

def get_table(df, table_ref_no = all, col_ref_no = all, row_ref_no = all, \
              col_name = "", cols = ["Year", "Client", "Amount_thuf"], add_cols = []):
    
    sub_table = df
    
    sub_table = sub_table.reset_index().drop(columns = ["index"])
    
     # Selection
    if (cols != all):
        sub_table = sub_table[cols + add_cols]
    
    # Aggregation
    if (len(row_ref_no) > 1):
        sub_table = pd.DataFrame(sub_table.groupby(["Year", "Client"]).sum()).reset_index()
    
    # Renaming
    if (col_name != ""):
        sub_table = sub_table.rename(columns = {"Amount_thuf" : col_name})

    return(sub_table)


excel_file_path = "C:/Users/nori/Projects/data/"
excel_file_name = "Data2016-2018_final.xlsx"
excel_sheet_name = "Total"


orig_df = pd.read_excel(excel_file_path + excel_file_name, sheet_name = excel_sheet_name)
dfo = orig_df
dfo["Amount_thuf"] = pd.to_numeric(dfo["Amount_thuf"], errors = "coerce")
df = dfo

tmp5001 = get_table(df, "Stat", ["C0001"], ["R0001"], "Eredmenytartalek")
tmp5002 = get_table(df, "Stat", ["C0001"], ["R0002"], "Karingadozasi_tartalek")
tmp5003 = get_table(df, "Stat", ["C0001"], ["R0003"], "Nagykarok_tartaleka")
tmp5004 = get_table(df, "Stat", ["C0001"], ["R0004"], "Adozas_utani_eredmeny")
tmp3002 = get_table(dfo, "S05", ["C0200", "C0300"], ["R0210", "R1510"], "Brutto_MSZD_direkt")
tmp3021 = get_table(dfo, "S05", ["C0200"], ["R0220"], "Nem-elet_MSZD_aranyos_VB")

dfs500               = [tmp5001, tmp5002, tmp5003, tmp5004, tmp3002, tmp3021]
print(dfs500)

**Comment by eric-wieser** [comment] 2020-03-12 11:07
Can you show all of the output after `Detailed traceback:`? It should be a lot longer that that.

**Comment by norapap** [comment] 2020-03-12 11:25
This is all, I got: 
Browse[1]> reticulate::source_python(paste0(project_folder,"data.py"))
Error in py_convert_pandas_df(x) : 
  SystemError: <built-in method item of numpy.ndarray object at 0x0000012709211440> returned a result with an error set

Detailed traceback: 
  File "C:\Users\nori\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 791, in iteritems
    for k in self.columns:
Browse[1]>

**Comment by eric-wieser** [comment] 2020-03-12 12:31
Perhaps https://github.com/rstudio/reticulate/issues/184 is relevant here

**Comment by seberg** [comment] 2020-03-20 17:04
Since `py_convert_pandas_df` is a function RStudio, I assume this is a bug in RStudio. Now it may be that some previous real error in the Python code causes the bug, but I do not have much of a hint as to that. I suppose you could try to put the python code you run from R into a block of:
```
try:
    run_code()
except Exception:
    import traceback
    traceback.print_last()
    raise
```
in a hope to print out an actual earlier error. But I do not have much hope, it seems more like a bug in RStudio and you should open an issue there or comment on the one Eric found.

Going to close this for now, since I do not believe there is anything we can do in NumPy. Happy to reopen though if there is any hint that we can.

**Closed by seberg** 2020-03-20 17:04 UTC

**Comment by eric-wieser** [comment] 2020-03-20 17:13
Good thinking on using`traceback` there to get the full stack trace @seberg
