### ISSUE TITLE
np.testing.assert_array_equal prints "[repr failed]" on some matrices

### ISSUE THREAD

**Issue by bmerry** [numpy/numpy#5875] opened 2015-05-14 11:56 UTC
With numpy 1.9.2 on Ubuntu 14.04 with Python 2.7:

``` python
>>> np.testing.assert_array_equal(np.matrix([[2, 1]]), np.matrix([[1, 2]])) 
...

AssertionError: 

Arrays are not equal
(mismatch 100.0%)
 x: [repr failed]
 y: [repr failed]
```

It seems that 1x1 matrices work, and changing `np.matrix` to `np.array` works. Also, manually calling `repr` on the matrix works.

**Comment by eric-wieser** [comment] 2017-01-03 01:08
This is the same as this problem:

```python
>>> np.array_repr(np.matrix(np.eye(2)))
Traceback (most recent call last):
  File "<pyshell#52>", line 1, in <module>
    np.array_repr(np.matrix(np.eye(2)))
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\numeric.py", line 1807, in array_repr
    ', ', "array(")
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 447, in array2string
    separator, prefix, formatter=formatter)
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 325, in _array2string
    _summaryEdgeItems, summary_insert)[:-1]
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 519, in _formatArray
    summary_insert)
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 496, in _formatArray
    word = format_function(a[-1])
  File "C:\Program Files\Python 3.5\lib\site-packages\numpy\core\arrayprint.py", line 598, in __call__
    if isnan(x):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by eric-wieser** [comment] 2017-11-28 18:37
Duplicate of #8442, which has a few more comments

**Closed by eric-wieser** 2017-11-28 18:37 UTC
