### ISSUE TITLE
TypeError: Cannot interpret 'datetime64[ns, tzfile('PRC')]' as a data type

### ISSUE THREAD

**Issue by lotcher** [numpy/numpy#19455] opened 2021-07-12 08:26 UTC
### Reproducing code example:

```python
import numpy as np
>>> time_type = data.index.dtype
>>> time_type
datetime64[ns, tzfile('PRC')]

>>> time_type == np.dtype('int32')
False
>>> time_type in [1,2,3]
False
>>> time_type in {np.dtype('int32')}
False
>>> time_type in [np.dtype('int32')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot interpret 'datetime64[ns, tzfile('PRC')]' as a data type
```

### NumPy/Python version information:

- python3.9  pandas1.2.4  numpy 1.19.3（When I upgrade the numpy version, the problem is solved）

> I'd like to know why an exception is thrown when trying to use "in List[np.dtype]" judgment in this "special" version, while "in set[np.dtype]" or "==" does not cause this problem.

**Comment by seberg** [comment] 2021-07-12 13:41
The order of comparisons is probably different, try the operations.  Anyway, I assume this is a duplicate of gh-19187 which was fixed in https://github.com/numpy/numpy/pull/19228 and should be part of 1.21.x

**Closed by seberg** 2021-07-12 13:41 UTC

**Comment by lotcher** [comment] 2021-07-13 02:17
thanks
