### ISSUE TITLE
Boolean indexing of an ndarray with a torch.tensor mask breaks for size=1

### ISSUE THREAD

**Issue by romanpogodin** [numpy/numpy#17348] opened 2020-09-18 14:35 UTC
Numpy allows to index arrays with boolean pytorch tensors and usually behaves just like pytorch. However, for a dimension of size 1 a pytorch boolean mask is interpreted as an integer index. As a result, indexing of `np.ones(1)` with a `torch.ones(1, dtype=torch.bool)` returns an error as it tries to access the second element. Expected behaviour is achieved by casting the tensor to numpy.

### Reproducing code example:

If the mask is False, indexing with a tensor returns the first element:
```python
import torch
import numpy as np
x = torch.zeros(1, dtype=torch.bool)
y = np.ones(1)
print(y[x.numpy()])
print(y[x])
```
outputs:
```
[]
1.0
```

If the mask is True, the second print raises an error:
```python
import torch
import numpy as np
x = torch.ones(1, dtype=torch.bool)
y = np.ones(1)
print(y[x.numpy()])
print(y[x])
```
outputs:
```
[1.]
IndexError
```
(see the full error below).

For more than one element, the behaviour is as expected:
```python
import torch
import numpy as np
x = torch.ones(2, dtype=torch.bool)
y = np.ones(2)
print(y[x.numpy()])
print(y[x])
```
outputs:
```
[1. 1.]
[1. 1.]
```

### Error message:

```
---------------------------------------------------------------------------

IndexError                                Traceback (most recent call last)

<ipython-input-58-c59be12007b5> in <module>()
      2 y = np.ones(1)
      3 print(y[x.numpy()])
----> 4 print(y[x])

IndexError: index 1 is out of bounds for axis 0 with size 1
```

### NumPy/Python version information:

Python 3.6.9, NumPy 1.19.2, PyTorch 1.6.0

**Comment by seberg** [comment] 2020-09-21 23:11
I seem to recall a similar issue once, but couldn't find it quickly now.  I may be missing something, but I think you should open this as a PyTorch issue (or probably look for an existing one). The issue is that `x.__index__()` is defined. Note that by comparison `x.numpy().__index__()` raises an error.

Of course that will still not allow you to actually index with a numpy array with a torch tensor without calling `.numpy()`, but I do not think that is the big issue here. The big issue is the potential of returning the wrong result.

**Comment by seberg** [comment] 2021-11-06 03:48
Since I consider this a torch issue and easier to fix there, going to close this.  If pytorch figures that making `__index__` more strict (which is what NumPy itself does to avoid this!), please reopen so we can reconsider.  But inaction or not my current angle is that `torch.Tensor.__index__` behaviour is the problem.

If anyone disagrees, please reopen.

**Closed by seberg** 2021-11-06 03:48 UTC
Labels: 33 - Question
