### ISSUE TITLE
vdot does not work on matrices

### ISSUE THREAD

**Issue by rudimeier** [numpy/numpy#11135] opened 2018-05-22 15:13 UTC
Since #5047 (v1.10) `vdot` does not work anymore on matrices.

 Examples:
```python
>>> p=np.array([1,2,3])
>>> np.vdot(p,p)
14
>>> np.vdot(np.matrix(p),np.matrix(p))
matrix([[1]])
>>> np.vdot(np.matrix(p),p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: vectors have different lengths
```

Older numpy versions return `14` in all cases.

**Comment by nafiz6** [comment] 2018-06-04 07:01
For the third case, the dimension of the vector is 3x1 where as the matrix is 1x3. Hence the error for different lengths.
Line 2312 of multiarraymodule.c: `if (PyArray_DIM(ap2, 0) != PyArray_DIM(ap1, 0))` checks for the first index size and finds different lengths. Maybe the dimensions for matrices could be adjusted when passed into the function? 
Either ways, even if it passes the length check, the output is still a matrix.

**Comment by rudimeier** [comment] 2018-06-26 14:28
Just noticed. The bug was already in 1.9.3 too, but only when `_dotblas.cpython-34m.so` is built.

    python3 -c "import numpy as np; print(np.__version__);"
    1.9.3
    $ echo $PYTHONUSERBASE
    /home/rudi/usr

    $ python3 -c "import numpy as np; a=np.vdot(np.mat([[3.,2.]]),np.mat([[3.,2.]])); print(a)"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ValueError: vectors have different lengths

    $ rm /home/rudi/usr/lib/python3.4/site-packages/numpy/core/_dotblas.cpython-34m.so
    $ python3 -c "import numpy as np; a=np.vdot(np.mat([[3.,2.]]),np.mat([[3.,2.]])); print(a)"
    13.0

**Comment by eric-wieser** [comment] 2018-06-26 16:22
This fails because `matrix` is broken by design

```
>>> a = np.array([[1, 2], [3, 4]])
>>> a.shape
(2, 2)
>>> a.reshape((4,)).shape
(4,)
>>> np.matrix(a).shape
(2, 2)
>>> np.matrix(a).reshape((4,)).shape
(1, 4,)
```

It violates the basic assumption that `arr.reshape(shape).shape == shape`.

**Comment by eric-wieser** [comment] 2018-06-26 16:24
Possibly introduced by, but not really the fault of, 3fd6de4c9492daf401ea1e58ea12c4ef3c8c2b2d

**Comment by rudimeier** [comment] 2018-06-26 17:41
> If something is broken by design, the fix is to just not use it. Indeed, in 1.15 calling np.matrix(...) emits a warning

Thanks for clarification. I've already learned it to not use matrix a few years ago. This issue here is a about a colleague's problem. Just a pity that everybody has to learn it the hard way.

Hope the introduced warning will help. Maybe you should also remove all documentation about matrix.

**Comment by mattip** [comment] 2019-04-26 00:11
Closing. The warning should suffice.

**Closed by mattip** 2019-04-26 00:11 UTC
Labels: 06 - Regression, 57 - Close?, component: numpy.matrixlib
