### ISSUE TITLE
4 test cases fail in test running with the latest master code base

### ISSUE THREAD

**Issue by huzq85** [numpy/numpy#12126] opened 2018-10-09 19:18 UTC
### Reproducing code example:

```python
python -c 'import numpy as np; np.test()'
```

### Error message:

```
======================================================= FAILURES =======================================================__________________________________________ TestLinspace.test_denormal_numbers __________________________________________
self = <numpy.core.tests.test_function_base.TestLinspace object at 0x7f70ac7be2e8>

    def test_denormal_numbers(self):
        # Regression test for gh-5437. Will probably fail when compiled
        # with ICC, which flushes denormals to zero
        for ftype in sctypes['float']:
            stop = nextafter(ftype(0), ftype(1)) * 5  # A denormal number
>           assert_(any(linspace(0, stop, 10, endpoint=False, dtype=ftype)))
E           AssertionError

ftype      = <class 'numpy.float128'>
self       = <numpy.core.tests.test_function_base.TestLinspace object at 0x7f70ac7be2e8>
stop       = 0.0

/usr/local/lib/python3.6/dist-packages/numpy-1.16.0.dev0+db5f9d3-py3.6-linux-x86_64.egg/numpy/core/tests/test_function_base.py:308: AssertionError
_____________________________________ TestFloatExceptions.test_floating_exceptions _____________________________________
self = <numpy.core.tests.test_numeric.TestFloatExceptions object at 0x7f70acbb4550>

    def test_floating_exceptions(self):
        # Test basic arithmetic function errors
        with np.errstate(all='raise'):
            # Test for all real and complex float types
            for typecode in np.typecodes['AllFloat']:
                ftype = np.obj2sctype(typecode)
                if np.dtype(ftype).kind == 'f':
                    # Get some extreme values for the type
                    fi = np.finfo(ftype)
                    ft_tiny = fi.tiny
                    ft_max = fi.max
                    ft_eps = fi.eps
                    underflow = 'underflow'
                    divbyzero = 'divide by zero'
                else:
                    # 'c', complex, corresponding real dtype
                    rtype = type(ftype(0).real)
                    fi = np.finfo(rtype)
                    ft_tiny = ftype(fi.tiny)
                    ft_max = ftype(fi.max)
                    ft_eps = ftype(fi.eps)
                    # The complex types raise different exceptions
                    underflow = ''
                    divbyzero = ''
                overflow = 'overflow'
                invalid = 'invalid'

                self.assert_raises_fpe(underflow,
>                                      lambda a, b: a/b, ft_tiny, ft_max)

divbyzero  = 'divide by zero'
fi         = finfo(resolution=1.0000000000000002641e-18, min=-inf, max=inf, dtype=float128)
ft_eps     = 1.084202172485504434e-19
ft_max     = inf
ft_tiny    = 3.3621031431120935063e-4932
ftype      = <class 'numpy.float128'>
invalid    = 'invalid'
overflow   = 'overflow'
self       = <numpy.core.tests.test_numeric.TestFloatExceptions object at 0x7f70acbb4550>
typecode   = 'g'
underflow  = 'underflow'

/usr/local/lib/python3.6/dist-packages/numpy-1.16.0.dev0+db5f9d3-py3.6-linux-x86_64.egg/numpy/core/tests/test_numeric.py:580:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <numpy.core.tests.test_numeric.TestFloatExceptions object at 0x7f70acbb4550>, fpeerr = 'underflow'
flop = <function TestFloatExceptions.test_floating_exceptions.<locals>.<lambda> at 0x7f70aca5a730>
x = 3.3621031431120935063e-4932, y = inf

    def assert_raises_fpe(self, fpeerr, flop, x, y):
        ftype = type(x)
        try:
            flop(x, y)
            assert_(False,
>                   "Type %s did not raise fpe error '%s'." % (ftype, fpeerr))
E                   AssertionError: Type <class 'numpy.float128'> did not raise fpe error 'underflow'.

flop       = <function TestFloatExceptions.test_floating_exceptions.<locals>.<lambda> at 0x7f70aca5a730>
fpeerr     = 'underflow'
ftype      = <class 'numpy.float128'>
self       = <numpy.core.tests.test_numeric.TestFloatExceptions object at 0x7f70acbb4550>
x          = 3.3621031431120935063e-4932
y          = inf

/usr/local/lib/python3.6/dist-packages/numpy-1.16.0.dev0+db5f9d3-py3.6-linux-x86_64.egg/numpy/core/tests/test_numeric.py:535: AssertionError
_______________________________ TestComplexFunctions.test_loss_of_precision_longcomplex ________________________________
self = <numpy.core.tests.test_umath.TestComplexFunctions object at 0x7f70ac0965c0>

    @pytest.mark.skipif(is_longdouble_finfo_bogus(),
                        reason="Bogus long double finfo")
    def test_loss_of_precision_longcomplex(self):
>       self.check_loss_of_precision(np.longcomplex)

self       = <numpy.core.tests.test_umath.TestComplexFunctions object at 0x7f70ac0965c0>

/usr/local/lib/python3.6/dist-packages/numpy-1.16.0.dev0+db5f9d3-py3.6-linux-x86_64.egg/numpy/core/tests/test_umath.py:2642:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.6/dist-packages/numpy-1.16.0.dev0+db5f9d3-py3.6-linux-x86_64.egg/numpy/core/tests/test_umath.py:2592: in check_loss_of_precision
    check(x_series, 50*eps)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array([1.00000000e-20, 1.21736864e-20, 1.48198641e-20, 1.80412378e-20,
       2.19628372e-20, 2.67368693e-20, 3.254862...5156e-04, 4.54267386e-04,
       5.53010871e-04, 6.73218092e-04, 8.19554595e-04, 9.97700064e-04],
      dtype=float128)
rtol = 5.42101086242752217e-18

    def check(x, rtol):
        x = x.astype(real_dtype)

        z = x.astype(dtype)
        d = np.absolute(np.arcsinh(x)/np.arcsinh(z).real - 1)
        assert_(np.all(d < rtol), (np.argmax(d), x[np.argmax(d)], d.max(),
>                                 'arcsinh'))
E       AssertionError: (190, 0.00016990298344866943845, 4.4408920985006261617e-16, 'arcsinh')

d          = array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.000000...2302e-16, 0.00000000e+00,
       3.33066907e-16, 0.00000000e+00, 2.22044605e-16, 1.11022302e-16],
      dtype=float128)
dtype      = <class 'numpy.complex256'>
real_dtype = dtype('float128')
rtol       = 5.42101086242752217e-18
x          = array([1.00000000e-20, 1.21736864e-20, 1.48198641e-20, 1.80412378e-20,
       2.19628372e-20, 2.67368693e-20, 3.254862...5156e-04, 4.54267386e-04,
       5.53010871e-04, 6.73218092e-04, 8.19554595e-04, 9.97700064e-04],
      dtype=float128)
z          = array([1.00000000e-20+0.j, 1.21736864e-20+0.j, 1.48198641e-20+0.j,
       1.80412378e-20+0.j, 2.19628372e-20+0.j, 2.67...7386e-04+0.j, 5.53010871e-04+0.j, 6.73218092e-04+0.j,
       8.19554595e-04+0.j, 9.97700064e-04+0.j], dtype=complex256)

/usr/local/lib/python3.6/dist-packages/numpy-1.16.0.dev0+db5f9d3-py3.6-linux-x86_64.egg/numpy/core/tests/test_umath.py:2565: AssertionError
___________________________________________________ test_nextafter_0 ___________________________________________________
    def test_nextafter_0():
        for t, direction in itertools.product(np.sctypes['float'], (1, -1)):
            tiny = np.finfo(t).tiny
>           assert_(0. < direction * np.nextafter(t(0), t(direction)) < tiny)
E           AssertionError

direction  = 1
t          = <class 'numpy.float128'>
tiny       = 3.3621031431120935063e-4932

/usr/local/lib/python3.6/dist-packages/numpy-1.16.0.dev0+db5f9d3-py3.6-linux-x86_64.egg/numpy/core/tests/test_umath.py:2776: AssertionError
4 failed, 5040 passed, 409 skipped, 167 deselected, 12 xfailed, 1 xpassed in 137.51 seconds

### Numpy/Python version information:

<!-- Output from 'import sys, numpy; print(numpy.__version__, sys.version)' -->
1.16.0.dev0+db5f9d3 3.6.6

```

**Comment by tylerjereddy** [comment] 2018-10-09 19:29
Those look like the same 4 failures I get when developing in Ubuntu on Windows Subsystem for Linux (WSL).

**Comment by huzq85** [comment] 2018-10-09 19:49
@tylerjereddy , yes it is on WSL. Still they are problems, right?

**Comment by tylerjereddy** [comment] 2018-10-09 19:54
Yeah, it is normal for the time being! What I usually do is just get a baseline failure count on the master branch if I'm developing, which is usually 4 fails as of late.

**Comment by charris** [comment] 2018-10-09 20:33
I suspect the problem is that WSL identifies itself as linux without, you know, actually being linux :) Would still be nice to track things down.

**Comment by hmaarrfk** [comment] 2019-01-07 22:50
I'm getting these failures on Linux aarch64 with openmp 0.3.5
https://app.shippable.com/github/Archiconda/numpy-feedstock/runs/6/1/console


````python

test_loss_of_precision_longcomplex


E       AssertionError: (120, 1.7809563130653488765574048895753284e-10, 5.286342315078822882670006871837315e-21, 'arcsinh')

d          = array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       ...000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
      dtype=float128)
dtype      = <type 'numpy.complex256'>
real_dtype = dtype('float128')
rtol       = 9.629649721936179265279889712924637e-33
x          = array([1.00000000e-20, 1.21736864e-20, 1.48198641e-20, 1.80412378e-20,
       ...871e-04, 6.73218092e-04, 8.19554595e-04, 9.97700064e-04],
      dtype=float128)
z          = array([1.00000000e-20+0.j, 1.21736864e-20+0.j, 1.48198641e-20+0.j,
       1.80...8092e-04+0.j,
       8.19554595e-04+0.j, 9.97700064e-04+0.j], dtype=complex256)
****

```

**Comment by tylerjereddy** [comment] 2019-01-07 23:05
I had never heard of `Archiconda`. I think you're using a different linear algebra backend and different gcc version vs. our shippable ARMv8 CI. Looks like it is Python 2.7 and probably different backend usage for your config versus our dev shippable config, so a fair number of differences between ARMv8 runs there & here. Our dev runs don't test Python 2.7 anymore either since master is the 1.17 dev branch.

We should maybe switch the dev shippable config over to the exact version of openblas used for wheel builds at some point I suppose. I don't think the initial discussion re: trying to have ARMv8 NumPy wheels went super-positively given current "standards," so I think I didn't really prioritize wheel-matching the shippable build.

I do still see that same test failing on WSL, and in the last few months WSL has gone from 4->6 test failures on full suite, at least in my hands.

**Comment by eric-wieser** [comment] 2019-01-07 23:06
I think I've seem this before. WSL claims to support `long double`, but always casts results to `double` during arithmetic. I have an issue open somewhere about this, that links to the root WSL issue.

**Comment by tylerjereddy** [comment] 2019-01-07 23:08
@eric-wieser And it makes sense that this pops up on ARMv8 Ubuntu as well, under some gcc / openblas combinations, as reported above?

**Comment by hmaarrfk** [comment] 2019-01-07 23:10
Is shippable running WSL? I was under the impression that I was running in a docker on a 96 core Arm64 bit beast.

Parallel compilation goes super fast, but serial stuff is like molasses.

@tylerjereddy I mostly built archiconda over the last few weeks with jjhelmus' help. The work they did to isolate the compilers and to migrate conda-forge to them made it dooable. I just got to compiling numpy today.

**Comment by tylerjereddy** [comment] 2019-01-07 23:19
> Is shippable running WSL?

No, it is a 96 core machine running Ubuntu as you suggest (not sure on the Docker part, I think they document that somewhere). The curious thing is just that an x86 Windows machine running WSL & an ARMv8 running Ubuntu are reporting a failure for the same test.

It looks like there's a recent `openblas` aarch64 binary in your conda config (` openblas:        0.3.5-h9ac9557_1000                    archiarm  )`, which is cool.

**Comment by hmaarrfk** [comment] 2019-01-07 23:22
xref: https://github.com/Archiconda/build-tools/issues/16
@tylerjereddy yeah, i wrote some scripts that just forked whatever was on master on conda-forge and ran their compilation scripts on shippable.
I ran into some issues with pinned dependencies, but yea.
many times, even 1 version less than bleeding edge had trouble.

I had other failures too on numpy 1.11.3, not sure how much you guys care about that one.

**Comment by seberg** [comment] 2021-11-05 23:04
Since I don't have WSL right now, I am not sure that this issue is still relevant.  However, the test failures indeed all look like duplicates of gh-8726 so closing (i.e. bad `long double`  support by WSL).

**Closed by seberg** 2021-11-05 23:04 UTC
Labels: 05 - Testing
