### ISSUE TITLE
DOC: Multiple axis case is not documented for np.average

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#7616] opened 2016-05-10 19:37 UTC
Apparently, the axis argument of `np.average` can be a tuple:

```
In [20]: np.average([[1.,2],[3,4]],axis=(0,1))
Out[20]: 2.5
```

but this case is not documented:

```
In [21]: np.average?
Signature: np.average(a, axis=None, weights=None, returned=False)
Docstring:
Compute the weighted average along the specified axis.

Parameters
----------
a : array_like
    Array containing data to be averaged. If `a` is not an array, a
    conversion is attempted.
axis : int, optional
    Axis along which to average `a`. If `None`, averaging is done over
    the flattened array.
..
```

**Comment by solarjoe** [comment] 2017-03-03 22:47
The documentation does not mention this, but the code does. It was added a while ago...

https://github.com/numpy/numpy/blob/c47198b4102cf3974e7fee2aa78d822877e391c2/numpy/lib/function_base.py

```
.. versionadded:: 1.7.0
        If axis is a tuple of ints, averaging is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
```

Does someone know why?

**Comment by MSeifert04** [comment] 2017-03-03 23:37
Because it was changed after 1.12 was released so it will only be visible for 1.13 and later.

I think this issue can be closed because it's a duplicate of #8604 which was closed by #8611

**Comment by eric-wieser** [comment] 2017-03-03 23:59
> .. versionadded:: 1.7.0

I think this is referring to the text above it, not below. At any rate, this is confusing, and there should probably a `.. versionadded:: 1.13.0` for the second half of this description

**Comment by MSeifert04** [comment] 2017-03-04 00:32
@eric-wieser The **versionadded** indicates in which version the _parameter_ was added not when the documentation was added. 😄

**Comment by eric-wieser** [comment] 2017-03-04 00:37
@MSeifert04: Right, but the _tuple interpretation_ of the parameter was added in 1.13.0, right? So that should have a separate marker. Or am I interpreting "Because it was changed after 1.12" as incorrectly referring to the feature?

**Comment by MSeifert04** [comment] 2017-03-04 00:41
@eric-wieser Sorry the doc-change was made after 1.12, I don't think the tuple-option was added then (at least not in #8611).

**Comment by mattip** [comment] 2019-05-07 05:00
axis is now documented as `None or int or tuple of ints`. Closing.

**Closed by mattip** 2019-05-07 05:00 UTC
