### ISSUE TITLE
np.random.geometric(10**-20) returns negative values

### ISSUE THREAD

**Issue by Strilanc** [numpy/numpy#17007] opened 2020-08-04 15:25 UTC
Sampling from a geometric distribution should always produce a positive result, but for sufficiently small probabilities negative results are returned.

### Reproducing code example:

```python
import numpy as np
for k in range(1000):
    s = np.random.geometric(10**-20)
    assert s > 0, f'attempt={k}, s={s}'
```

### Error message:

```
AssertionError: attempt=0, s=-9223372036854775808
```
Note: The negative value is equal to -2^63 (the minimum signed 64 bit int) and always seems to be the same for any sufficiently low probability.

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.17.5 3.7.7 (default, May 20 2020, 19:38:38) 
[GCC 9.3.0]
```

**Comment by rossbar** [comment] 2020-08-05 18:15
This behavior is also present in `Generator.geometric`:

```python
>>> rg = np.random.default_rng()
>>> rg.geometric(10**-17)
-9223372036854775808
```

**Comment by eric-wieser** [comment] 2020-08-06 09:51
Cause by the use of `log(1 - p)` when we should be using `log1p(-p)`

**Comment by WarrenWeckesser** [comment] 2021-09-23 12:13
*Status update*: the use of `log1p` was eventually merged in https://github.com/numpy/numpy/pull/18634.  The behavior of `geometric` with very small parameter values was improved, but sufficiently small values still result in negative output.

Older version of numpy:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.20.1'

In [3]: rng = np.random.default_rng()

In [4]: rng.geometric([1e-20, 1e-17, 1e-14], size=(8,3))
Out[4]: 
array([[-9223372036854775808, -9223372036854775808,      227051556282628],
       [-9223372036854775808, -9223372036854775808,      280784450517515],
       [-9223372036854775808, -9223372036854775808,       70898849847385],
       [-9223372036854775808, -9223372036854775808,      213317371815151],
       [-9223372036854775808, -9223372036854775808,       22419424856741],
       [-9223372036854775808, -9223372036854775808,       52804005041871],
       [-9223372036854775808, -9223372036854775808,       10895820626217],
       [-9223372036854775808, -9223372036854775808,       54887000066943]])
```

Main development branch:
```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.22.0.dev0+1145.gc64c7cc0b'

In [3]: rng = np.random.default_rng()

In [4]: rng.geometric([1e-20, 1e-17, 1e-14], size=(8,3))
Out[4]: 
array([[ 6631150008637832192,   323796406389012736,       70615014039656],
       [-9223372036854775808,   323112358600902528,      118087705070250],
       [-9223372036854775808,    67114798115757896,      135744359778299],
       [-9223372036854775808,   130437001080088464,      103507497022235],
       [-9223372036854775808,   382183193371431808,       67394797071065],
       [-9223372036854775808,     6409399571739832,      169966862688167],
       [-9223372036854775808,   391584454336355648,      347655624779143],
       [-9223372036854775808,   109614948793301392,      146244686091573]])
```

**Comment by WarrenWeckesser** [comment] 2023-04-26 22:29
A quick comment about the issue, inspired by comments in https://github.com/scipy/scipy/issues/18372:

The problem is in this code:

https://github.com/numpy/numpy/blob/bc8cf11fd2b31f0fb260fc505fc3e76129c84197/numpy/random/src/distributions/distributions.c#L962-L964

In C, when casting a floating point value to an integer, if the integer part of the value exceeds the largest value that can be represented by the integer, the behavior is *undefined*.  On my Linux machine with gcc 11.3.0, the expression `(int64_t) 9223372036854775808.0` results in `-9223372036854775808`.  On my Mac, with Apple clang 14.0.0, the result is `9223372036854775807`.

**Comment by WarrenWeckesser** [comment] 2023-04-28 16:32
There is a different problem in the legacy `RandomState` implementation:

https://github.com/numpy/numpy/blob/f983afd70046e807dd61962800ce147f42ccc457/numpy/random/src/legacy/legacy-distributions.c#L395-L397

Several uses of `npy_log1p` were added in https://github.com/numpy/numpy/pull/18634, but the expression `log(1 - p)` used in the code shown above was not changed, because of concern that such a change would alter the stream of variates; see https://github.com/numpy/numpy/pull/17020#pullrequestreview-462382711.  So when `p` is less than about 5.6e-17, `log(1 - p)` will be 0, and the result of `ceil(...)` will be `-inf`.  When cast to `long` (on the platforms that I've tested), the result is `-9223372036854775808`.

**Comment by WarrenWeckesser** [comment] 2023-05-01 03:58
gh-23691 is a quick fix for the `Generator.geometric` method.  It checks that the floating point value that is to be converted to `int64_t` is not big enough to invoke undefined behavior.  If the value is too big, `INT64_MAX` is returned.

Should a similar fix be applied to the legacy version?  It would use `LONG_MAX` instead of `INT64_MAX`, and it would have to check for `p` that is so small that `1.0 - p` is zero, and return `LONG_MAX` in that case, too (unless we decide it is safe to replace `log(1.0 - p)` with `log1p(-p)`).

**Comment by rkern** [comment] 2023-05-01 14:05
Nope, legacy is frozen for fixes like this.

**Closed** 2023-05-02 08:19 UTC
Labels: 00 - Bug, component: numpy.random
