### ISSUE TITLE
 Building from git fails: `Error compiling Cython file: Pythonic division not allowed without gil`

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#6719] opened 2015-11-25 14:26 UTC
Building numpy from git fails when Cythonizing `numpy/random/mtrand/mtrand.pyx`, due to an error `Pythonic division not allowed without gil, consider using cython.cdivision(True)`.  This is Python 3.5.0, Cython 0.23.4, with `numpy` git revision `d94043f0fb93985fd4302eae9fcdca2d79239908` on branch `master`.  The same problem occurs on branch `maintenance/1.10.x` with commit `76db1ab4edef69e310426dccf95c15212b1ba4a6`, and on branch `maintenance/1.9.x` with commit `edb902cdc6573553afcf11047ecdfb447e444322`.  However, a regular `pip install numpy` (which installs 1.10.1), works (because releases include compiled cython files, but version control does not).  The failures occur as follows:

```
$ python3.5 setup.py build_ext                                                                       
Running from numpy source directory.
Cythonizing sources
Processing numpy/random/mtrand/mtrand.pyx

Error compiling Cython file:
------------------------------------------------------------
...
            i = 0
            while i < sz:
                Sum = 1.0
                dn = n
                for j from 0 <= j < d-1:
                    mnix[i+j] = rk_binomial(self.internal_state, dn, pix[j]/Sum)
                                                                          ^
------------------------------------------------------------

mtrand.pyx:4484:75: Pythonic division not allowed without gil, consider using cython.cdivision(True)
Traceback (most recent call last):
  File "/tmp/numpy/tools/cythonize.py", line 199, in <module>
    main()
  File "/tmp/numpy/tools/cythonize.py", line 195, in main
    find_process_files(root_dir)
  File "/tmp/numpy/tools/cythonize.py", line 187, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "/tmp/numpy/tools/cythonize.py", line 161, in process
    processor_function(fromfile, tofile)
  File "/tmp/numpy/tools/cythonize.py", line 72, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 263, in <module>
    setup_package()
  File "setup.py", line 251, in setup_package
    generate_cython()
  File "setup.py", line 199, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!
```

What's going wrong?

**Comment by gerritholl** [comment] 2015-11-25 15:31
I added pull request  #6720.  I don't know if this is a workaround that fails to address the problem, or whether this is an actual fix, because I am not sure what the underlying problem is and why it hasn't been reported before — if I run into this problem, shouldn't many others too?

**Comment by charris** [comment] 2015-11-25 15:44
Probably `Cython 0.23.2`, I don't see a problem here with Cython 0.22. Running that bit of code with nogil is also in numpy 1.9, so it isn't new.

**Comment by charris** [comment] 2015-11-25 16:03
Note that two C floats are involved in the division, so the python version of `/` should not matter. I think this is a cython glitch.

**Comment by gerritholl** [comment] 2015-11-25 16:17
Even if it's a bug in cython, wouldn'd numpy still want a workaround?  I tried with both 0.23.2 and 0.23.4 so if it is a Cython bug, it's not a bug occurring in just a single revision.

**Comment by gerritholl** [comment] 2015-11-25 17:11
See pull request #6721

**Comment by charris** [comment] 2015-11-25 18:55
Closed by #6721.

**Closed by charris** 2015-11-25 18:55 UTC

**Comment by njsmith** [comment] 2015-11-25 21:33
Please do file a bug with cython as well.

**Comment by robertwb** [comment] 2015-11-26 06:57
I tried

cdef double bad_call(int j, double* pix, double Sum):
    with nogil:
        res = pix[j] / Sum
    return res

With the latest Cython head, with Python 2.7 and 3.4, with and without the -3 option, and was not able to reproduce this. Is there something non-standard in your setup?

**Comment by gerritholl** [comment] 2015-11-26 10:34
@njsmith I sent an e-mail to the cython-users mailing-list.  I don't feel quite confident enough to formulate what exactly the cython bug is, as I've never used cython myself.

@robertwb As far as I'm aware, I have not personally set anything non-standard.  The machine configuration is different from a typical workstation, though — I'm building on a Red Hat Enterprise Linux Server release 6.7, cython and co installed in my home directory on a panfs filesystem, trying to build on a tmpfs filesystem.  I don't think the filesystem type should matter but it's the only unusual aspect I'm aware of.
