### ISSUE TITLE
BUG: Masked array creation with mask=None is slow

### ISSUE THREAD

**Issue by saimn** [numpy/numpy#17046] opened 2020-08-10 18:51 UTC
Creating a masked array with `mask=None` is orders of magnitude slower than with `mask=False` or `mask=nomask`. This is a bit surprising and it's easy to be tricked by this when creating a masked array in a function where the mask is optional, e.g.:
```
def foo(data, mask=None):
    arr = np.ma.array(data, mask=mask)
    ...
```

The problem is the `np.resize` call here:

https://github.com/numpy/numpy/blob/00a45b4dca164105b50ba29e1735e96b573b639c/numpy/ma/core.py#L2896-L2897

At this point `mask` has been converted to `array(False)`, so one solution would be to ad a special case to call `np.zeros` as done when `mask=False` ?

### Reproducing code example:

```python
In [1]: %numpy
Numpy 1.19.1

In [2]: a = np.zeros(int(1e7))

In [3]: %timeit np.ma.array(a, mask=False)
350 µs ± 9.26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [4]: %timeit np.ma.array(a, mask=None)
1.32 s ± 5.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### Numpy/Python version information:

```
1.19.1 3.8.5 (default, Aug  5 2020, 08:36:46) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment] 2020-08-10 18:58
Is `mask=None` documented as a thing you should be doing?

**Comment by saimn** [comment] 2020-08-10 19:05
Note sure, I cannot find mentions of it but `None` is a pretty standard value for an optional argument, and it is not mentioned either that `None` should not be used ;). `None` is treated as `False` here, and I guess it has always been like that.

**Comment by rossbar** [comment] 2020-08-10 22:51
I couldn't find anything in the documentation about the intended behavior of `mask=None` with a quick grep and a look at the `ma` module docs. I would have expected `mask=None` to have equivalent behavior to `mask=np.ma.nomask` (which is the default for `np.ma.array()`) but it seems @saimn is correct that it is instead equivalent to `mask=False`.

Setting aside the issue of what the behavior *should* be, it seems like this issue could be fixed by adding something like `if mask is None: mask = False`, which will maintain the current behavior while getting rid of the slowdown.

**Comment by eric-wieser** [comment] 2020-09-01 13:42
I don't think there's any point optimizing for a case that is not documented as supported, or recommended. If you're writing a function with its own `mask` argument, default it to `False` not `None`.

**Comment by saimn** [comment] 2020-09-02 09:41
> If you're writing a function with its own mask argument, default it to False not None.

Ok, but that's not for me, I know the trick. I opened this issue because I occasionally find code that fall into this trap, and fixed some occurrences recently. One example while looking quickly at Astropy, https://github.com/astropy/astropy/pull/7422

So if really `None` should not be used, this deserves at least a warning. Otherwise, since the behavior is the same as `False`, there is no reason why it should be that slower, especially when the "fix" is 2 lines of code.

**Comment by rgommers** [comment] 2022-11-21 11:05
This should be quite easy to fix with the suggestion by @rossbar above. I'll remove the `Close?` label and mark it as a good first issue.

**Closed** 2022-12-05 10:47 UTC
Labels: component: numpy.ma, sprintable
