### ISSUE TITLE
BUG: Shouldn't numpy's floating types (e.g. `np.float_`) and python's native `float` type be compatible?

### ISSUE THREAD

**Issue by simonaltrogge** [numpy/numpy#23663] opened 2023-04-25 15:51 UTC
### Describe the issue:

When trying to type hint functions accepting scalars, I get unexpected error messages from my type checker (Pylance). As `np.float_` is a subtype of python's native `float` type, I would expect to be able to pass a variable with type `np.float_` when a native `float` is expected.

### Reproduce the code example:

```python
import numpy as np

def idx(x: float) -> float:
    return x

arr = np.arange(5.0, dtype=np.float_)
sum = np.sum(arr)
idx(sum)
```

### Error message:

```shell
Argument of type "float_" cannot be assigned to parameter "x" of type "float" in function "idx"
  "float_" is incompatible with "float" Pylance (reportGeneralTypeIssues)
```

### Runtime information:

1.24.1
3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

### Context for the issue:

This issue makes it either impossible or much harder to correctly type hint functions such that they are compatible with numpy.

**Comment by MatteoRaso** [comment] 2023-04-25 21:25
I think that this is a problem with PyLance. I don't use PyLance, and the code works fine for me, so it's probably not a Numpy problem.

**Comment by rkern** [comment] 2023-04-25 21:40
`np.float64` (which `np.float_` is just an alias for) is a subclass of `float`.

```
>>> np.float64.mro()
[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]
```

**Comment by rkern** [comment] 2023-04-25 21:45
FWIW, I'd probably just not use `np.float_` there. Idiomatically, I'd just use `dtype=float` or `dtype=np.float64`. `np.float_` and `np.int_` are really there more for reference than for use in `dtype=` arguments.

**Comment by SimonAltrogge** [comment] 2023-05-09 15:48
Even if I change `np.float_` to `np.float64`, I still get an equivalent error message. I have submitted a corresponding bug report to [microsoft/pylance-release](https://github.com/microsoft/pylance-release) (see microsoft/pylance-release#4332).

**Comment by rchiodo** [comment] 2023-05-09 16:35
I think Pylance is correct here. The type float64 (at least in the type stubs) is defined like this:

```python
float64 = floating[_64Bit]
```

where `floating` is a class that isn't derived from float:

```python
class floating(inexact[_NBit1]):
    ...
```

The MRO list at runtime isn't used by Pylance/Pyright. It's determined solely by the type heirarchy we can query statically. 

If I change the definition of floating in the type stub to be like so:

```python
class floating(inexact[_NBit1], float):
   ...
```

Then the error reported by Pylance goes away.

**Comment by rkern** [comment] 2023-05-09 18:17
Well, `floating` doesn't subclass from `float`, only `float64` is.

**Comment by hmc-cs-mdrissi** [comment] 2023-05-10 01:26
Hmm then similarly you could define float64 as,

```python
class float64(floating[_64Bit], float):
 ...
```

**Comment by BvB93** [comment] 2023-05-12 13:36
> Hmm then similarly you could define float64 as,

You could, though the reason why the likes of `np.floating` subclasses (among a few others) are modeled as parametrized generics in the stub files is because, to put it mildly, it's incredibly difficult to determine the output bitsize for a given operation with the currently available typing tools and as such we generally have to resort to simply returning `np.floating[Any]` (arbitrary/unknown-sized float). Now, due to the presence of the `Any`-parameter and the fact that the likes of `np.float64` are treated as sub-types but not proper subclasses, it means that you can freely cast from one to the other (while you cannot do the same for superclass -> subclass without some heavy handed use of `typing.cast` lest typecheckers can and will complain).

The downside of this approach is that information about the `float` superclass is lost from `np.float64`, simply because the various `np.floating` sub-types are all treated as exactly equivalent (barring their bit size). It might be an option instead to pretend that `np.floating` as a whole inherits from `float` (and the similarly with `np.complexfloating` and `complex`). This would technically be a lie, though I suspect it's a minor one and one that might be worth the effort (especially with the autrocious state of statically duck-typing scalars).

**Comment by jorenham** [comment] 2024-08-17 21:39
I believe that this is a duplicate of #21906

**Closed** 2024-08-17 21:40 UTC
Labels: 00 - Bug, 50 - Duplicate, Static typing
