### ISSUE TITLE
ufuncs return 0d arrays instead of scalars for ndarray subclasses

### ISSUE THREAD

**Issue by whoburg** [numpy/numpy#5819] opened 2015-05-01 15:24 UTC
I'm running into a few unexpected behaviors when subclassing `ndarray`, as described here: (http://docs.scipy.org/doc/numpy/user/basics.subclassing.html).

Here's a simple subclass that doesn't try to add any functionality:

``` python
import numpy as np

class MyArray(np.ndarray):

    def __new__(cls, input_array, info=None):
        # cast to be our class type
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        pass
```

Notice that the behavior of `.sum()` differs between an `ndarray` and `MyArray`:

``` python
>>> np.array([1,2,3]).sum()
6
>>> MyArray([1,2,3]).sum()
MyArray(6)
```

I'd like my subclass to have the `np.array` behavior -- I don't want `MyArray.sum()` to return 0-dimensional arrays.

Before I try to solve this problem, I want to point out that the difference is also there for the object `dtype`. Here's a pretty useless object definition, that supports addition:

``` python
class SelfishObject(object):
    def __add__(self, other):
        return self
    def __radd__(self, other):
        return self + other
```

Notice that the behavior of `.sum()` still differs in terms of return type:

``` python
>>> np.array([SelfishObject(), SelfishObject()]).sum()
<__main__.SelfishObject object at 0x1032e25d0>
>>> MyArray([SelfishObject(), SelfishObject()]).sum()
MyArray(<__main__.SelfishObject object at 0x1032e2610>, dtype=object)
```

It seems I can force the behavior I want, using `__array_wrap__`:

``` python
class MyArray(np.ndarray):

    def __new__(cls, input_array):
        # cast to be our class type
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        pass

    def __array_wrap__(self, out_arr, context=None):
        if out_arr.ndim:
            return np.ndarray.__array_wrap__(self, out_arr, context)
```

``` python
>>> np.array([SelfishObject(), SelfishObject()]).sum()
<__main__.SelfishObject object at 0x1032e2610>
>>> MyArray([SelfishObject(), SelfishObject()]).sum()
<__main__.SelfishObject object at 0x1032e2590>
>>> np.array([1,2,3]).sum()
6
>>> MyArray([1,2,3]).sum()
6
```

... but I'm wondering whether this is the preferred/recommended way to deal with this, and whether guidelines for this issue should be added to the documentation.

One related potential unexpected behavior is that the exceptions raised in `__array_wrap__` seem to get caught at a higher level, and therefore appear to be ignored. Even odder, raising in `__array_wrap__` _also_ solves the 0-dimensional array problem:

``` python
class MyArray(np.ndarray):

    def __new__(cls, input_array):
        # cast to be our class type
        obj = np.asarray(input_array).view(cls)
        return obj

    def __array_finalize__(self, obj):
        pass

    def __array_wrap__(self, out_arr, context=None):
        raise RuntimeWarning
```

``` python
>>> MyArray([SelfishObject(), SelfishObject()]).sum()
<__main__.SelfishObject object at 0x1032e2590>
>>> MyArray([1,2,3]).sum()
6
```

**Comment by seberg** [comment] 2015-05-01 15:41
Hmm, that the exception is not being raised is probably a bug. The other stuff, I think is by design (though admittingly I believe that design may have changed before). But yes, better documentation is always welcome.

One sidenote, this is just one of many flaws of subclasses. Do not expect them to ever work a hundred percent  like you would like them to. Subclassing ndarray tends to have issues....

**Comment by mhvk** [comment] 2015-05-01 16:38
Just to note that for some subclasses (e.g., astropy's `Quantity`), we'd really appreciate it if subclass would be generally *kept* in array methods, as one wants to continue being able to keep metadata (the unit of the quantity in this case). Indeed, personally I think it was a design mistake to let an index or summation return a something else than an `ndarray`...

On the exceptions: that is indeed odd.  Note that the `RuntimeWarning` does get raised when you just add two `MyArray` instances:
```
In [7]: MyArray([1]) + MyArray([2])
---------------------------------------------------------------------------
RuntimeWarning                            Traceback (most recent call last)
```

**Comment by whoburg** [comment] 2015-05-01 16:58
Thanks for the initial comments!

Re: documentation, `array.sum` defaults to `numpy.sum`, and here's what the `numpy.sum` documentation says about return types:

```
Returns:	
sum_along_axis : ndarray
    An array with the same shape as a, with the specified axis removed.
    *If a is a 0-d array, or if axis is None, a scalar is returned.*
    If an output array is specified, a reference to out is returned.
```

Note that in the first example above, where `yArray([1,2,3]).sum())` returns `array(6)`, `axis` will default to None, but a scalar is not returned:

```python
>>> np.isscalar(np.array(6))
False
>>> np.isscalar(MyArray([1,2,3]).sum())
False
>>> np.isscalar(np.array([1,2,3]).sum())
True
```

**Comment by hmeine** [comment] 2016-12-13 09:04
I am having exactly this problem, that I expected ``.min()``/``.max()``/``.any()`` to return scalars.  Therefore, we implemented ``__array_wrap__``, using ``PyArray_Return()``, which does the reduction to a scalar when the ndarray has dimensionality 0. However, I just realized that now ``.squeeze()`` gives an exception:

    RuntimeError: ndarray subclass __array_wrap__ method returned an object which was not an instance of an ndarray subclass	

Now, my questions are:
* Should I not expect the above ufuncs to return values that fulfil ``numpy.isscalar()``?
* Is there any simple reference implementation of ``__array_wrap__``? Obviously, it would be nice if the latter could be added to the docs.

**Comment by hmeine** [comment] 2017-01-02 22:48
Wow, I just had a strange experience – I was looking for my old (presumably "paused" / on hold) numpy-discussions list membership, and found that about half of my posts ever on that list were in a discussion (from five years ago) extremely close to this one (but with a behavior change in 1.6.0): http://numpy-discussion.10968.n7.nabble.com/Rationale-for-returning-type-wrapped-min-max-scalars-was-Problem-with-ufunc-of-a-numpy-ndarray-deriv-td31804.html#a31811

The above questions are still relevant and to the point, rephrased in a slightly more general way:
* What is the intended behavior of ndarray subclasses w.r.t. functions returning scalars?
* What is the best way to implement that behavior?

**Comment by eric-wieser** [comment] 2017-04-28 17:22
> Even odder, raising in __array_wrap__ also solves the 0-dimensional array problem:

I think this is the same as #8954

**Comment by eric-wieser** [comment] 2017-04-29 01:45
Nope, nothing to do with #8954. This is a bug in its own right

**Comment by seberg** [comment] 2024-01-28 12:51
Going to close this:  I smuggled in `return_scalar=False` into `__array_wrap__` to allow taping over inconsistencies.  (Although arguably, NumPy shouldn't return *scalars* for 0-D arrays, so that `return_scalar=True` would true for now, could change!)

I don't see what more could be done here...

**Closed by seberg** 2024-01-28 12:51 UTC

**Comment by mhvk** [comment] 2024-01-28 19:52
Indeed, as far as I'm concerned that solves it! Thanks, @seberg!
