### ISSUE TITLE
DeprecationWarning in Python 3 and Numpy 1.8

### ISSUE THREAD

**Issue by cli248** [numpy/numpy#4258] opened 2014-02-03 21:04 UTC
I invoked `python` with `-Wall`, and following expression raised the `DeprecationWarning`,

```
>>> np.divide(.4, 1, dtype=float)
__main__:1: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.
```

Actually, this expression is from `scikit-learn`, see [this](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/fixes.py#L211). 

Any idea what caused the warning, and how could we handle it?

**Comment by seberg** [comment] 2019-09-22 01:51
An old Python3 issue that I cannot reproduce. Must be fixed... closing.

**Closed by seberg** 2019-09-22 01:51 UTC
Labels: 00 - Bug, component: numpy.core
