### ISSUE TITLE
Unexpected behavior when an array of floats is subtracted from a very large integer.

### ISSUE THREAD

**Issue by mmngreco** [numpy/numpy#16689] opened 2020-06-25 19:31 UTC
Doing some calculations I discover this unexpected behavior related with
`dtypes`. I hope some of you can point me if this is a bug or I'm doing
something wrong.

### Reproducing code example:

Here is a minimal peace of my code which tries to reproduce the problem:

```python
import numpy as np

# VERSIONS USED
np.__version__ #  '1.18.1'
np.__version__ #  '1.19.0'

x = 731965.048356481480000000000000000000
x_arr = np.array([x])
big_int = 86400000000000
cnst = 719529

# THIS WORKS
arr1 = (x_arr - cnst) * big_int
out1 = arr1.astype("datetime64[ns]")

# THIS FAILS
arr2 = x_arr * big_int - cnst * big_int
out2 = arr2.astype("datetime64[ns]")

# WORKAROUND
big_int = 86400000000000.  # NOW IS A FLOAT
arr3 = x_arr * big_int - cnst * big_int
out3 = arr3.astype("datetime64[ns]")
```

#### MWE

Here some code that I use for debugging a minimal reproducible example that
shows this unexpected behavior.

```python
def check_dtype(big_int):
    a = np.array([731965.04835648148]) * big_int
    b = 719529 * big_int
    c = a - b
    return c.dtype

works_int = 20000000000000
fails_int = 30000000000000
check_dtype(works_int)  # dtype('float64')
check_dtype(fails_int)  # dtype('O')
```

### Numpy/Python version information:

```python
import sys, numpy; print(numpy.__version__, sys.version)
1.19.0 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0]
```

**Comment by seberg** [comment] 2020-06-25 22:23
This is a known issue, there should be a few duplicates around in recent past also.  The problem is that when NumPy encounters a Python integers it will try the dtypes:

* `long` (`np.int_`)  – on many systems identical to `np.int64`
* `np.int64`
* `np.uint64`
* `object`

You can do even more fun things if you mix in integers that go to unsigned... I will probably propose to deprecate once my other PR is in, I think. Not sure we will actually do it, but getting random types has lots of traps, in almost all cases uses *do* alraedy get the default integer (whatever that is, int32, or int64).  Anyway, closing as duplicate of: gh-16287

**Comment by seberg** [comment] 2020-06-25 22:23
But thanks for reporting, its good to know that it is creating issues in the wild... and it is one of the trickier/more hidden things!

**Closed by seberg** 2020-06-25 22:23 UTC
