### ISSUE TITLE
Importing numpy raises AttributeError in 1.16.0

### ISSUE THREAD

**Issue by dabao12321** [numpy/numpy#12739] opened 2019-01-14 17:08 UTC
Importing numpy raises AttributeError when using latest version, 1.16.0.

### Reproducing code example:

import numpy as np

## Gives error traceback:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-77eedbd5f73a> in <module>
----> 1 from sklearn.datasets import make_classification
      2 from sklearn.preprocessing import StandardScaler,label_binarize
      3 from sklearn.svm import SVC, LinearSVC
      4 from sklearn.multiclass import OneVsRestClassifier
      5 from sklearn.pipeline import make_pipeline

~/.local/lib/python3.6/site-packages/sklearn/__init__.py in <module>
     62 else:
     63     from . import __check_build
---> 64     from .base import clone
     65     from .utils._show_versions import show_versions
     66 

~/.local/lib/python3.6/site-packages/sklearn/base.py in <module>
      8 from collections import defaultdict
      9 
---> 10 import numpy as np
     11 from scipy import sparse
     12 from .externals import six

~/.local/lib/python3.6/site-packages/numpy/__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~/.local/lib/python3.6/site-packages/numpy/core/__init__.py in <module>
     57 from . import numerictypes as nt
     58 multiarray.set_typeDict(nt.sctypeDict)
---> 59 from . import numeric
     60 from .numeric import *
     61 from . import fromnumeric

~/.local/lib/python3.6/site-packages/numpy/core/numeric.py in <module>
   3091 from .umath import *
   3092 from .numerictypes import *
-> 3093 from . import fromnumeric
   3094 from .fromnumeric import *
   3095 from . import arrayprint

~/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py in <module>
     15 from . import numerictypes as nt
     16 from .numeric import asarray, array, asanyarray, concatenate
---> 17 from . import _methods
     18 
     19 _dt_ = nt.sctype2char

~/.local/lib/python3.6/site-packages/numpy/core/_methods.py in <module>
    156     )
    157 
--> 158 _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
    159 
    160 def _array_function(self, func, types, args, kwargs):

AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

**Comment by seberg** [comment] 2019-01-14 17:36
Seems like a duplicate of gh-12736 with some left-over files from another installation? You should probably just make sure you uninstalled numpy completely, and install it again.

**Comment by mattip** [comment] 2019-01-14 19:51
closing, please add any new information to #12736

**Closed by mattip** 2019-01-14 19:51 UTC
