### ISSUE TITLE
Why does everyone use GIL incorrectly?

### ISSUE THREAD

**Issue by Roffild** [numpy/numpy#13723] opened 2019-06-06 00:11 UTC
Why does everyone use GIL incorrectly?

[Recently reported a bug in Pytorch.](https://github.com/pytorch/pytorch/issues/20695#issuecomment-495950840)

Today updated numpy 1.16.3 to 1.16.4

Same problem with GIL.

**Comment by eric-wieser** [comment] 2019-06-06 00:37
Can you elaborate on the problem you're seeing with numpy and what you think the correct behavior is? The issue template should be a good baseline for what type of information we need to act upon issue reports.

**Comment by seberg** [comment] 2019-06-06 18:14
@Roffild please help us out here. I am not willing to dig through huge threads and linked commits on a different tracker based on a rhetorical (and quite frankly dismissive) question. Maybe something could be better, I frankly do not know. But we will have to end up closing this unless you follow up. Also, I doubt that there is a behaviour change in a numpy minor version upgrade. If there is, please tell us what it is.

**Comment by Roffild** [comment] 2019-06-07 00:08
https://bugs.python.org/issue37186

**Comment by bbbbbbbbba** [comment] 2019-06-07 02:06
~~Why does this specific individual use sub-interpreters incorrectly?~~

Seriously, though, I think this is more of a sub-interpreter bug, if not a design choice. In your specific case, maybe compiling numpy without thread support would be a workaround.

**Comment by eric-wieser** [comment] 2019-06-07 02:07
Numpy does not support being loaded by multiple interpreters anyway, as far as I know. I suppose you could load us in just one of them...

**Comment by mattip** [comment] 2019-06-07 07:20
What problem exactly are you seeing in your code, and how can we reproduce it?

**Comment by eric-wieser** [comment] 2019-06-07 07:43
So, I think I've decoded the problem. Numpy has two different modes for handling the GIL:

* `NPY_BEGIN_THREADS_DEF`, `NPY_BEGIN_THREADS`, `NPY_END_THREADS` which match the pattern describe by [Releasing the GIL from extension code](https://docs.python.org/2/c-api/init.html#releasing-the-gil-from-extension-code)
* `NPY_ALLOW_C_API_DEF`. `NPY_ALLOW_C_API`,`NPY_DISABLE_C_API` (and direct `PyGILState_STATE` related calls) which match the pattern described by [Non-Python created threads](https://docs.python.org/3/c-api/init.html#non-python-created-threads)

Most of are calls are the former, which work correctly with multiple interpreters. A small handful use the latter, things such as:
* Allocators
* `xerbla_` callback functions from lapack
* `NpyIter_DebugPrint` which no one ever calls
* All of the generated Cython code

If these APIs are called from a regular python thread, they still do the right thing anyway.

The problem comes only if they're called from some other thread, and have no way of knowing which interpreter they originated from.

This all seems kind of irrelevant anyway until numpy adds support for multiple interpreters.

**Comment by seberg** [comment] 2019-06-07 15:25
Well, our policy with this embedding thing until now has been: Not really much of a priority, PRs welcome, since yes, we do not really support them (although I am not sure what the exact issues are).

Thanks for spelling it out Eric, I expected it was something with subinterpreters, but at least now I understand what "incorrect" means in the context.

**Comment by pv** [comment] 2019-06-07 19:42
Then this is duplicate of #5856

**Comment by Roffild** [comment] 2019-06-07 20:52
[In the official documentation](https://docs.python.org/3/c-api/init.html#thread-state-and-the-global-interpreter-lock), sub-interpreters are described as a ready-made technology. PyGILState_() functions must be marked as deprecated.

In practice, this was not the case.

[The correct example of using GIL is here.](https://github.com/pybind/pybind11/blob/97784dad3e518ccb415d5db57ff9b933495d9024/include/pybind11/pybind11.h#L1846) It is enough to check the status of GIL before use. Or in the library initialization to keep the value PyThreadState_Get() or PyThreadState_GET().

I will change my library and get rid of sub-interpreters.

**Comment by bbbbbbbbba** [comment] 2019-06-07 21:03
I wonder where you got that impression. From my reading of the same documentation, sub-interpreters are buggy and full of caveats, and  PyGILState_() functions are pretty reasonable to use.

**Comment by seberg** [comment] 2019-06-12 02:15
I will close this for now. As Pauli noted, this is indeed a duplicate of gh-5856, and that seems to have all or close to all the information also here. Subinterpreters are an issue, and PRs are welcome, but unless someone from outside steps in, there is unlikely to be a big change here. All I can see likely happening is that we try to remember this issue when designing new API (which does not happen often).

**Closed by seberg** 2019-06-12 02:15 UTC
Labels: 57 - Close?, Embedded
