### ISSUE TITLE
numpy.all may return a generator, which always evals to True

### ISSUE THREAD

**Issue by jaryn** [numpy/numpy#5756] opened 2015-04-08 13:42 UTC
The problem is that you can shoot yourself in the foot with the numpy version of `all`, because it is not consistent with the Python build-in `all` in return value when generator is passed to it:

```
In [1]: import numpy

In [2]: numpy.all(a for a in [False])
Out[2]: <generator object <genexpr> at 0x7f22623eeaa0>

In [3]: bool(numpy.all(a for a in [False]))
Out[3]: True

In [4]: __builtin__.all(a for a in [False])
Out[4]: False
```

This is especially confusing when used with `ipython -pylab` in which case the **buildin**.all is shadowed with the numpy one:

```
$ ipython -pylab
... blah blah...
In [2]: all.func_code
Out[2]: <code object all at 0x7ff967d8c5b0, file "/usr/lib64/python2.7/site-packages
numpy/core/fromnumeric.py", line 1842>
```

**Comment by eric-wieser** [comment] 2020-02-21 14:54
Closing as a duplicate of gh-6555, which has more discussion.

**Closed by eric-wieser** 2020-02-21 14:54 UTC
