### ISSUE TITLE
BUG: Inconsistent behaviour between `np.float64` and other dtypes resulting in dimensionality reduction.

### ISSUE THREAD

**Issue by KelSolaar** [numpy/numpy#24283] opened 2023-07-28 23:03 UTC
### Describe the issue:

`np.float64` (and maybe `np.float128` but I cannot test as I'm on a MacBook Pro M1) behaves differently to other dtypes and reduces the dimensionality of `ndarray` as shown in the code example.

### Reproduce the code example:

```python
>>> for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64] + [np.float16, np.float32, np.float64]:
...     print(dtype)
...     print(dtype([[1]]))
...     print(dtype(dtype([[1]])))
... 
<class 'numpy.int8'>
[[1]]
[[1]]
<class 'numpy.int16'>
[[1]]
[[1]]
<class 'numpy.int32'>
[[1]]
[[1]]
<class 'numpy.int64'>
[[1]]
[[1]]
<class 'numpy.uint8'>
[[1]]
[[1]]
<class 'numpy.uint16'>
[[1]]
[[1]]
<class 'numpy.uint32'>
[[1]]
[[1]]
<class 'numpy.uint64'>
[[1]]
[[1]]
<class 'numpy.float16'>
[[ 1.]]
[[ 1.]]
<class 'numpy.float32'>
[[ 1.]]
[[ 1.]]
<class 'numpy.float64'>
[[ 1.]]
1.0
```

### Error message:

```shell
N/A
```

### Runtime information:

```python
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.24.3
3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
>>> np.show_runtime()
WARNING: `threadpoolctl` not found in system! Install it by `pip install threadpoolctl`. Once installed, try `np.show_runtime` again for more detailed build information
[{'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}}]
```

**Comment by WarrenWeckesser** [comment] 2023-07-28 23:15
Thanks for reporting the issue, @KelSolaar.  This is a duplicate of https://github.com/numpy/numpy/issues/1362.

**Closed by WarrenWeckesser** 2023-07-28 23:15 UTC
Labels: 00 - Bug

**Comment by KelSolaar** [comment] 2023-07-28 23:16
Ah thank you! I could not check `np.float128`, that might be worth doing on the side.
