### ISSUE TITLE
Some package builds fail with 1.16.0rc1 distutils

### ISSUE THREAD

**Issue by vanderwb** [numpy/numpy#12659] opened 2019-01-03 22:14 UTC
I'm not sure if this should be a numpy issue or an issue with the relevant packages, but it is affecting multiple. So far I've seen it with pyhdf/0.9.0, and pynio/1.4.0. Basically, if I try to build these packages with a Python 2.7.15 install and numpy/1.16.0rc1, the builds fail at different steps because of compiler/linker errors. I'll document the pyhdf case only, for simplicity. In the pyhdf setup.py file, they have a line that goes:

extra_link_args = os.environ.get('LINK_ARGS', '')

This extra_link_args gets put into a list and then sent as extra_link_args to distutils. In older versions of numpy, everything works, but in the latest, gcc (v7.3.0) gives the following error:

gcc: error: : No such file or directory

After some digging, I tracked down the issue to the older version (1.15.4) using the "exec_command" function, which will send the string-joined command to the shell if in a POSIX environment. As a result, the empty string scenario (no LINK_ARGS value) is harmless. In the new version, subprocess.check_output is used with no shell option, and so the empty string remains a list element and it send to gcc as arg, which causes it to fail. This behavior was introduced in 83b0340.

### Reproducing code example:

To reproduce, attempt to install pyhdf/0.9.0 from source using a Python install with numpy/1.16.0rc1:

python setup.py install

I am using gcc/7.3.0 on CentOS 7.

### Error message:

gcc: error: : No such file or directory                                                                                                                                                      error: Command "gcc -pthread -shared -Wl,-rpath,/glade/u/apps/dav/opt/hdf/4.2.14/gnu/7.3.0/lib build/temp.linux-x86_64-2.7/pyhdf/hdfext_wrap.o -L/glade/u/apps/dav/opt/hdf/4.2.14/gnu/7.3.0/l
ib -lmfhdf -ldf -ljpeg -lz -o build/lib.linux-x86_64-2.7/pyhdf/_hdfext.so " failed with exit status 1

### Numpy/Python version information:

('1.16.0rc1', '2.7.15 (default, Jan  3 2019, 11:15:38) \n[GCC 7.3.0]')

**Comment by vanderwb** [comment] 2019-01-03 22:32
Thanks for the quick reply. Yes, there is an empty linker argument. I modified Ccompiler_spawn to print the cmd variable right before the check_output call, and it gave the following:

['build/temp.linux-x86_64-2.7/pyhdf/hdfext_wrap.o', '-L/glade/u/apps/dav/opt/hdf/4.2.14/gnu/7.3.0/lib', '-lmfhdf', '-ldf', '-ljpeg', '-lz', '-o', 'build/lib.linux-x86_64-2.7/pyhdf/_hdfext.so', '']

I don't know which behavior should be preferred, but I wonder why the option to run the command using the shell was in exec_command to begin with. It may be to avoid this edgy case.

**Comment by thisco-de** [comment] 2019-02-04 03:30
Similarly, the Fortran code of scipy fails to build when `F77FLAGS` and `NPY_DISTUTILS_APPEND_FLAGS=1` are set in the environment.

**Comment by eric-wieser** [comment] 2019-02-04 03:52
> However, since the value of these two variables is not parsed/split by distutils

It sounds like we need to add in this splitting

**Comment by eric-wieser** [comment] 2019-02-04 04:19
Ok, so there are two separate problems here:

* In 1.16.0 and 1.16.1, we broke our `.cfg` file parsing. This is fixed in #12925.
* Until 1.16.0, `numpy.distutils` patched `distutils` in an incompatible way. Previously, importing `numpy.distutils` would change the semantics of `extra_link_args` from being a list of separate arguments  (as defined in the `distutils` docs) to being a meaningless list to be concatenated with spaces. Numpy 1.16 undoes this, because not only was it a terrible idea, but overwriting the standard library way of doing this with a terrible idea is an even worse idea.

  Unfortunately, the ecosystem has come to depend on us breaking `distutils`.

  ![](https://imgs.xkcd.com/comics/workflow.png)

**Comment by rgommers** [comment] 2019-02-04 19:31
Yes it's a giant mess - there's a reason I was so reluctant to make changes:)

Now that we've committed to the removal of `exec_command` though, I think we have no choice to keep going. The `extra_link_args` seems painful. We could still revert that one (the changes have only been out 22 days only), but I'm now leaning towards biting the bullet and keeping things as is (compatible with `distutils`). That means fixing it in all the packages that relied on the old behavior.

**Comment by rgommers** [comment] 2019-02-04 20:18
@eric-wieser yes I get that. I agree with staying with the compatible version. Don't really care too much about that though, it's well-known that both `numpy.distutils` and `setuptools` monkeypatch `distutils` in various ways. If you use `numpy.distutils` then you should rely on numpy, and never on plain `distutils` anymore. There is no good reason to do that.

**Comment by eric-wieser** [comment] 2019-02-05 07:45
Note that pyhdf have already fixed their problem with fhs/python-hdf4#19. I think that change is mostly backwards compatible - it only fails if `LINK_ARGS` contains escape sequences, which would be escaped once by `shlex` and again by the shell.

**Comment by charris** [comment] 2019-02-25 13:29
@eric-wieser Has this been fixed?

**Comment by eric-wieser** [comment] 2019-03-02 20:57
No, this is caused by the problem identified in #13075

**Closed** 2019-03-04 03:54 UTC
Labels: component: numpy.distutils
