### ISSUE TITLE
genfromtxt requires encoding despite input being unicode

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#10990] opened 2018-04-27 07:20 UTC
Why am I required to specify an encoding here? I'm not asking to encode anything!

```python
>>> from io import StringIO
>>> data = u"1, abc , 2\n 3, xxx, 4"
>>> np.genfromtxt(StringIO(data), delimiter=",", dtype=None)
VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
array([(1, b' abc ', 2), (3, b' xxx', 4)],
      dtype=[('f0', '<i4'), ('f1', 'S5'), ('f2', '<i4')])  # np.bytes_? But I passed in unicode
```

Paradoxically, when and encoding is passed, then no encoding occurs!
```python
>>> np.genfromtxt(StringIO(data), delimiter=",", dtype=None, encoding='ascii')
array([(1, ' abc ', 2), (3, ' xxx', 4)],
      dtype=[('f0', '<i4'), ('f1', '<U5'), ('f2', '<i4')])  # unicode!
```

**Comment by juliantaylor** [comment] 2018-04-27 17:56
ah no the deprecation is intentional. It should warn you about getting back byte strings from fields that are auto-identified as strings.
The wording should be improved.

**Comment by charris** [comment] 2018-05-30 15:13
@juliantaylor Is this a bug or a feature?

**Comment by juliantaylor** [comment] 2018-05-30 16:00
imo not a bug but a doc/deprecation message improvement

**Comment by charris** [comment] 2018-05-30 17:00
@eric-wieser Thoughts?

**Comment by eric-wieser** [comment] 2018-06-04 05:12
> When using auto detection one cannot determine the difference between fields that are supposed to be bytes and fields that should be strings

I don't agree with this - if you're reading from a `unicode` input, the rule is easy - there cannot be any byte fields.

**Comment by juliantaylor** [comment] 2018-06-06 18:01
that the functions understand unicode input is new, the original function did treat all input as bytes.
for backward compatibility this behavior is kept when no encoding is given.

**Comment by charris** [comment] 2018-06-07 22:48
Kicking this off again.

**Comment by charris** [comment] 2018-11-22 15:35
So what is the way forward here?

**Comment by charris** [comment] 2019-11-26 00:24
I'm tempted to close this as it is getting old. Perhaps we can use a default encoding to deal with the backwards compatibility?

**Comment by charris** [comment] 2020-11-23 15:15
I'm going to close this. @eric-wieser Please open a new issue/PR if you want to pursue this.

**Closed by charris** 2020-11-23 15:15 UTC
Labels: 54 - Needs decision
