### ISSUE TITLE
Missing decref when an IndexError is thrown from a recarray

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#7581] opened 2016-04-28 02:15 UTC
Version: 1.10.1

Compare:

```python
>>> a = np.ndarray(5, dtype=[('a', np.float64)])
>>> sys.getrefcount(a)
2
>>> a[5]
IndexError
>>> sys.getrefcount(a)
2
>>> a[5]
IndexError
>>> sys.getrefcount(a)
2
```

With

```python
>>> a = np.recarray(5, dtype=[('a', np.float64)])
>>> sys.getrefcount(a)
2
>>> a[5]
IndexError
>>> sys.getrefcount(a)
3
>>> a[5]
IndexError
>>> sys.getrefcount(a)
4
```

This causes `a.resize` to fail

**Comment by eric-wieser** [comment] 2016-04-28 02:28
Actually, the repro for this is much simpler:

```
>>> a = np.empty(5)

# direct lookups are fine
>>> sys.getrefcount(a)
2
>>> a[5]
IndexError
>>> sys.getrefcount(a)
2

# but lookups inside a function leak references
>>> get = lambda i: a[i]
>>> get(5)
IndexError
>>> sys.getrefcount(a)
3
>>> get(5)
IndexError
>>> sys.getrefcount(a)
4
>>> get(5)
IndexError
>>> sys.getrefcount(a)
5
```

**Comment by charris** [comment] 2016-04-28 02:38
This seems to be fixed in master. What version of numpy are you using?

**Comment by njsmith** [comment] 2016-04-28 02:38
Are you sure the number keeps increasing? Exceptions in functions keep the function's stack frame pinned in memory for a bit (in some attributes of sys) for debugging/stack trace purposes, which can cause different reference counting behavior between functions and not. (I'm wondering because numpy doesnt know whether you're in a function, but you say it affects this...)

(Independently I'd suggest that you should try hard not to use resize, because you'll be fighting Python the whole time. That doesn't mean we shouldn't fix refcnt bugs, but FYI...)

**Comment by charris** [comment] 2016-04-28 02:40
@njsmith Wrong issue?

**Comment by njsmith** [comment] 2016-04-28 05:25
@charris: I don't think so? He said it's a problem for resize, and that the problem only occurs when the call is embedded inside a function, which is really weird.

**Comment by charris** [comment] 2016-05-01 02:30
I will note that `a[0]` returns a view of the original data, upping the refcount if the console holds a reference, ipython for instance. A view might be a bit of a surprise for folks expecting a copy, at least it was for me.

**Comment by ahaldane** [comment] 2016-05-01 05:27
Right, `a[0]` is a view because void-structured-scalars act as views so that `arr['f0'][0] = 1` and `arr[0]['f0'] = 1` do the same thing.

I also can't reproduce the bug in master or 1.10, by the way.

**Comment by eric-wieser** [comment] 2016-05-01 05:35
Maybe the shell is causing me trouble here. My setup is windows / 3.5.0x64 / numpy 1.10.1 / Idle.

The original testcase still fails on my machine, but the later one does not.

**Comment by eric-wieser** [comment] 2016-05-01 05:37
Testing again on python 2.7.11, numpy 1.10.4, the issue doesn't seem to occur. So perhaps this is already fixed

**Comment by charris** [comment] 2016-05-02 02:31
I note that that the behavior differs between python2 and python3. For python2 the reference count is incremented by one and stabilizes whereas for python3 the reference count is not incremented at all. This is also true for numpy 1.9.2, so the behavior is not a regression and probably related to something python is doing with the exception. I don't think there is anything simple that we could do here and, because current behavior is not a regression, I'm going to close this.

**Closed by charris** 2016-05-02 02:31 UTC

**Comment by eric-wieser** [comment] 2016-05-02 03:11
I think there is something wrong in 1.10.1, but I wasn't able to track down the cause. The python2 behavior is correct I think, and comes down to information stored in `sys.exc_info()[2]`, the traceback
