### ISSUE TITLE
dype comparison with other types raise a TypeError (Trac #1001)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1599] opened 2012-10-19 20:43 UTC
_Original ticket http://projects.scipy.org/numpy/ticket/1001 on 2009-02-06 by trac user ashleywalsh, assigned to unknown._

If you compare a dtype with another object for equality a TypeError is raised if the second object cannot be converted to a dtype:

```
>>> import numpy
>>> numpy.dtype(float) == 'float'
True
>>> numpy.dtype(float) == 'i'
False
>>> numpy.dtype(float) == object()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type not understood
>>> numpy.dtype(float) == 'x'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type not understood
```

In my case this caused epydoc to crash because it attempted to compare a dtype that was class attribute with (I think) an object was an attribute of the same name on a super-class.

**Comment by melissawm** [comment] 2021-08-10 20:08
Can't reproduce this anymore - can this be closed?

```
In [1]: import numpy as np
In [2]: np.dtype(float) == 'float'
Out[2]: True

In [3]: np.dtype(float) == 'i'
Out[3]: False

In [4]: np.dtype(float) == object()
Out[4]: False

In [5]: np.dtype(float) == 'x'
Out[5]: False
```

**Comment by seberg** [comment] 2021-08-10 20:16
Yes, thanks for the note! It was fixed with gh-19228 returning NotImplemented rather than raising.

**Comment by seberg** [comment] 2021-08-10 20:17
To be clear: The discussions about bad hashing, etc. are all still valid, but I do think we have more issues open about that.

**Closed by seberg** 2021-08-10 20:16 UTC
Labels: 00 - Bug, component: numpy.core
