### ISSUE TITLE
numpy.sum and python's sum giving different results on a 1-d numpy array

### ISSUE THREAD

**Issue by mgelbart** [numpy/numpy#8632] opened 2017-02-17 23:42 UTC
I'm wondering why the code

```
import numpy
x = numpy.zeros(10)+0.1
print(sum(x) == numpy.sum(x))
```
prints `False`. I realize this is something to do with floating point / roundoff errors, but I'm surprised `numpy.sum` and `sum` behave differently in such a simple situation. Any insight would be appreciated. 

Apologies if this is not the right venue for this question (I could post on StackOverflow if that's better). My system:
- macOS 10.12.3
- Python 3.6.0 via Anaconda 4.3.0
- Numpy 1.11.3

**Comment by pv** [comment] 2017-02-17 23:50
This sort of questions would be better asked on stackoverflow or on 
mailing lists. Note that you are not reporting about a bug here.
.
Probably pairwise summation and vectorization. You can find the 
discussions of those by googling "numpy pairwise summation" etc. or 
searching the pull requests / issues here.

**Comment by pv** [comment] 2017-02-17 23:57
Closing (not a bug).

**Closed by pv** 2017-02-17 23:57 UTC

**Comment by ksze** [comment] 2017-03-07 06:23
I think a more important question is: which result is more correct?

**Comment by seberg** [comment] 2017-03-07 08:13
Pythons should (at least normally) be more correct (unless maybe you use an extended precision long double type in which case I  not sure). But that is just about thinking of adding more stable summation algorithms to numpy.
Numpy's sum can have much better precision compared to itself when done over the fast axis in the memory layout (i.e. typically `arr.sum(-1)` is more exact then `arr.T.copy().sum(0)`).

Anyway, there are other issues open for these things, and for discussions I would suggest the mailng list.

**Comment by seberg** [comment] 2017-03-07 08:15
Just to be clear, python's `sum` will do Kahan summation. Numpy sometimes does (more or less depending on array size) pairwise summation in many (if not most) cases to improve precision without performance cost. You can look up what this means in terms of precision.

**Comment by njsmith** [comment] 2017-03-07 08:34
@seberg: Why do you say Python's `sum` does Kahan summation? [it looks like naive summation to me](https://github.com/python/cpython/blob/8886d5f39286dffa7d9337857b151e7fb4af23fd/Python/bltinmodule.c#L2301). (There's also `math.fsum` which uses a very fancy algorithm with 1 ulp accuracy, but that's different.)

**Comment by seberg** [comment] 2017-03-07 08:38
Oh, serious oops I guess. I must have thought that sum does the same as fsum for floats and then also thought that that algorithm ends up being Kahan summation :(. I wonder if at least `fsum` once used Kahan summation or I was just 100% wrong :). But doesn't matter. So then numpy's sum should actually pretty much always be more accurate then `sum` but less then `fsum`....
