### ISSUE TITLE
import_array raises an exception and does not return a value

### ISSUE THREAD

**Issue by victorliu** [numpy/numpy#14965] opened 2019-11-22 22:32 UTC
It looks like the `import_array` function is largely a pass-through that calls `_import_array` which returns an error code ~~without~~ while also raising an exception. I would like to call the internal version directly without raising an exception, to detect if numpy exists or not. If numpy does exist, then I want my own Python C extension to be able to handle numpy arrays through the `PyArray_*` API, and if not, I want to only allow built-in python sequences.

Currently, calling `import_array` in cases when numpy is not installed simply causes my extension to fail to load.

**Comment by mattip** [comment] 2019-11-22 23:12
Are you sure no error is set? As far as I can tell, `import_array` is defined as below and should both print an error and set an exception. You should call `if (PyError_Occurred()) ...` after `import_array()` to check this.

```
#define import_array() { \
  if (_import_array() < 0) {\
    PyErr_Print(); \
    PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); \
  } \
}
```

**Comment by mattip** [comment] 2019-11-25 19:03
@victorliu could you verfiy that an error is not set in your case?

**Comment by victorliu** [comment] 2019-11-25 20:12
Sorry, I meant to say that an exception is also set. I would prefer that an integer error code is returned without setting an exception. I am currently calling PyErr_Clear to clear the exception, but I'm not sure if that's clearing other potential exceptions during the module loading process.

**Comment by eric-wieser** [comment] 2019-11-25 20:25
> I'm not sure if that's clearing other potential exceptions during the module loading process.

There are only two cases here:

* An exception was already set before you called `import_array()`. This is likely to cause a `SystemError`, and is not a valid thing to do.
* `import_array()` is responsible for the exception that is set, and it tells you what the problem is.

Calling `PyErr_Clear()` is safe, but if you want to be able to distinguish between numpy not being installed, and numpy being broken somehow, you might want to catch only `ImportError`.

**Comment by seberg** [comment] 2019-11-27 17:02
@victorliu I think the comments probably answered your question, so I will close this. If you still have concerns, please keep dicussion and we can also reopen.

**Closed by seberg** 2019-11-27 17:02 UTC
Labels: 53 - Invalid, 57 - Close?
