### ISSUE TITLE
BUG: segmentation fault when combine np.vectorize and recarray

### ISSUE THREAD

**Issue by Roy-Kid** [numpy/numpy#20749] opened 2022-01-06 08:23 UTC
### Describe the issue:

I am using `np.vectorize` to assign each row of np.recarray(and structured array) to a pyfunc, but segmentation fault raise. If I replace recarray with array, it is ok.

### Reproduce the code example:

```python
import numpy as np
#from core import Atoms

natoms = 10
fields = [('id', int), ('name', 'U8'), ('position', float, (3, )), ]
ids = [i for i in range(natoms)]
names = [f"atom{i}" for i in range(natoms)]
positions = np.arange(3*natoms).reshape((natoms, 3))

atoms = np.zeros((natoms, ), fields).view(np.recarray)
atoms.id = ids
atoms.name = names
atoms.position = positions

# atomlist = atoms.getAtomInstances(atoms.data)
print(type(atoms))
def vprint(data):
    print(data)
np.vectorize(vprint)(atoms)
```

### Error message:

```shell
(base) molpy/molpy [ python test.py                        ]   
<class 'numpy.ndarray'>
(0, 'atom0', [0., 1., 2.])
[1]    25311 segmentation fault  python test.py

Here is error message from pytest:


tests/test_atom.py .FFFatal Python error: Segmentation fault

Current thread 0x0000000202bd6600 (most recent call first):
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2244 in <listcomp>
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2244 in _vectorize_call
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 2163 in __call__
  File "/Users/roy/work/molpy/molpy/core.py", line 74 in getAtomInstances
  File "/Users/roy/work/molpy/tests/test_atom.py", line 37 in test_batch_init_atom
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/python.py", line 1641 in runtest
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/main.py", line 323 in _main
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/Users/roy/miniconda3/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/Users/roy/miniconda3/bin/pytest", line 11 in <module>
[1]    24012 segmentation fault  pytest tests/test_atom.py
```
```


### NumPy/Python version information:

1.21.2 3.9.5 (default, May 18 2021, 12:31:01) 
[Clang 10.0.0 ]

**Comment by seberg** [comment] 2022-01-06 14:51
Thanks, a slightly simpler reproducer is to use:
```
natoms = 10
fields = [('id', int), ('name', 'U8'), ('position', float, (3, )), ]
ids = [i for i in range(natoms)]
names = [f"atom{i}" for i in range(natoms)]
positions = np.arange(3*natoms).reshape((natoms, 3))

atoms = np.zeros((natoms, ), fields).view(np.recarray)
atoms.id = ids
atoms.name = names
atoms.position = positions

atoms.astype(object)
```
It also is not recarray related itself, using a normal structured array seems to run into it as well.  Unfortunately, likely related to the fix for thread-safety in these operations (although I did not check how far back the error goes).  Probably something to do with the embedded subarray dtype (positions), but not sure yet.

**Comment by seberg** [comment] 2022-05-19 12:49
Had a look at this, and the problem is deeper and also looks much older.  Older versions don't crash as quickly, but also do return invalid results for subscription (they probably worked fine for assignment, though).

The issue is that the casts return views, but the casts never knew/passed the actual base array that owns the data (at least since Numy 1.7 or so).

**Comment by seberg** [comment] 2022-05-19 20:39
Going to push the milestone.  I am thinking about it, but we need to either return a copy in this cast, or pass through `base`/ownership data into the cast machinery.  Both seem rather bigger changes unfortunately.
Passing through base/ownership might be necessary anyway long-term e.g. to support HPy better (that is subtly different, but may just be similar enough to work).

Maybe returning a copy _is_ just the right way, since as far as I can tell not returning a copy just never worked, so at least we go from broken to "something sensible".

I.e.:
```
np.array([1, 2, 3], "i,i").astype(object)
```
returns tuples, so it does copy, but:
```
np.array([1, 2, 3], "i,2i").astype(object)
```
tries to include array views into the original array for the `2i` part.  My thought would be to return array copies, which would remove the problem of ownership (for now).  The main point being that the views never worked (or at least not for a decade).

(I initially thought that it might not work for assignments, but assignments do not cast the array being assigned, so that was not relevant.)

**Comment by seberg** [comment] 2022-11-16 17:09
We discussed it briefly today, and I will try changing it to return a copy for the next release, since that avoids the otherwise pretty easily occurring segfault.  Of course it is a change that could break odd workflows.

**Comment by seberg** [comment] 2022-11-18 11:52
Was just looking into fixing this, but looks I already did fix it in gh-21925 (which was addressing the equivalent gh-21911).

So we already have the "copy when necessary" in place.  Admittedly, I think we may want to copy more broadly, right now the copy is only made when absolutely necessary (which is the cast for casts).

In any case, the bug appears fixed, so closing.

**Closed by seberg** 2022-11-18 11:52 UTC
Labels: 00 - Bug, Project, triaged
