### ISSUE TITLE
DOC: Some features of docs built with sphinx 6 do not work

### ISSUE THREAD

**Issue by F3eQnxN3RriK** [numpy/numpy#23647] opened 2023-04-23 01:51 UTC
### Issue with current documentation:

The pulldown and search box do not work in documentation built with sphinx 6. 

### Idea or request for content:

These work fine with sphinx 5, so there seems to be a breaking change in sphinx 6 that causes the problem. The sphinx version is currently fixed at 5 (gh-23640), but it would be nice to be able to use sphinx 6 for the build.

**Comment by mattip** [comment] 2023-04-23 07:59
I see the pydata-sphinx-theme tests are [passing with 6.1.3](https://github.com/pydata/pydata-sphinx-theme/actions/runs/4701902932/jobs/8338528942#step:4:43), I wonder what is going wrong. Who would be a likely theme expert to get some eyes on this? @drammock?

**Comment by drammock** [comment] 2023-04-23 17:14
Regarding the "pulldown" I guess you mean the version switcher dropdown? AFAIK that never works on local builds for any project, because of CORS restrictions.

Here's a screenshot showing that search works for me on a local build:

![Screenshot 2023-04-23 at 12-00-43 Search — NumPy v1 25 dev0 Manual](https://user-images.githubusercontent.com/1810515/233853786-96e3e3c0-cf86-4888-a81c-f323623c682d.png)

(further down in the search results, the preview text for pages like "global state" or "indexing on ndarrays" does not display, I believe also due to CORS restrictions).

```
$ mamba list sphinx
# packages in environment at /opt/miniforge3/envs/npdev:
#
# Name                    Version                   Build  Channel
pydata-sphinx-theme       0.9.0              pyhd8ed1ab_1    conda-forge
sphinx                    6.1.3              pyhd8ed1ab_0    conda-forge
sphinx-design             0.4.1              pyhd8ed1ab_0    conda-forge
[rest omitted...]
```
note that I had to do some manual stuff to get this env to even install, as both `breathe` and `sphinx-design` still try to force sphinx<6 when installing with `mamba` (for `sphinx-design` at least I know the installed version is *supposed* to be sphinx-6 compatible... not sure what's up with that).

I've tried a few times to wrap my head around CORS and how to allow things like loading the version dropdown JSON on local builds (or even on PR builds, which often doesn't work either).  I've always failed; if anyone reading this understands how CORS works and what would be necessary please speak up.

**Comment by mattip** [comment] 2023-04-25 07:38
Since we pinned the [devdocs](https://numpy.org/devdocs/) to sphinx 5 in #23640, it is hard to debug a broken deployment. I submitted #23658 to revert the max pinning

**Comment by anshuman0123** [comment] 2023-04-25 17:29
Hey , I am new to open source . Please guide me how can I contribute in this repo

**Comment by mattip** [comment] 2023-04-25 18:24
Hi @anshuman. We have some resources on our [community](https://numpy.org/community/) page, and ways to contribute on the [contribution](https://numpy.org/contribute/) page. You might want to join our next newcomer's meeting MAy 4, which will be announced on this [mail archive thread](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/XJ2Q6VFLZDLP5YUSAM4CNAPFZOZHCQD4/) a few days before.

**Comment by drammock** [comment] 2023-04-26 23:04
Sphinx 6 no longer automatically includes JQuery ([changelog](https://www.sphinx-doc.org/en/master/changes.html#release-6-0-0-released-dec-29-2022), first item under "incompatible changes"). pydata-sphinx-theme version 0.9.0 assumes that it is present, so you'll need to add JQuery. Ways to do this:

- `app.add_js_file('path/to/file.js') in the `setup` function at the end of `conf.py`. Might require hosting/vendoring a copy of jquery
- there is a [sphinxcontrib-jquery](https://github.com/sphinx-contrib/jquery) extension that will inject it for you (I've not used this)
- add a new Jinja template to numpy: `doc/source/_templates/layout.html` that inherits from the theme template but adds an appropriate `<script>` or `<link>` tag to load JQuery.

I can make the PR to numpy tomorrow if you like, just LMK which option you prefer. If unsure, I'd probably pick the 3rd option myself (because I'm familiar with how the templates work)

**Comment by mattip** [comment] 2023-04-27 05:48
Is there a reason we are still with the older version of pydata-sphinx-theme? Maybe we should just update to v0.13.3?

**Comment by rossbar** [comment] 2023-04-27 06:29
> Is there a reason we are still with the older version of pydata-sphinx-theme? Maybe we should update to v0.13.3?

Not that I'm aware of. Presumably the most recent version of the theme includes the necessary JQuery to make these features work? It's worth a shot at least - hopefully this is just fixed by updating. If not, then perhaps we should raise the issue there if it hasn't been already?

**Comment by drammock** [comment] 2023-04-27 10:14
> Presumably the most recent version of the theme includes the necessary JQuery

Actually newer versions of the theme *remove* our use of jQuery (replaced with vanilla JavaScript). But it amounts to the same thing (Sphinx 6 compatibility)

> Is there a reason we are still with the older version of pydata-sphinx-theme?

Scipy has had issues with increased build time on later versions of the theme. These have been difficult to reproduce and hence difficult to fix. I'll do some local tests to see if numpy is likely to suffer the same problem. If not, updating the theme pin seems like the best option. 

Crossrefs:
- https://github.com/pydata/pydata-sphinx-theme/issues/855
- https://github.com/pydata/pydata-sphinx-theme/issues/889
- CC @tupui

**Comment by tupui** [comment] 2023-04-27 10:17
@drammock thanks for having a look 🙇 

I would expect the same issues to arise as we try to keep both SciPy and NumPy's docs in sync. That will definitely be interesting if your tests show now slowdown here.

**Comment by anshuman** [comment] 2023-04-27 11:01
@anshuman0123

**Comment by anshuman** [comment] 2023-04-27 11:02
@anshuman0123 I guess this @mattip's comment was meant for you:

> Hi @anshuman. We have some resources on our [community](https://numpy.org/community/) page, and ways to contribute on the [contribution](https://numpy.org/contribute/) page. You might want to join our next newcomer's meeting MAy 4, which will be announced on this [mail archive thread](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/XJ2Q6VFLZDLP5YUSAM4CNAPFZOZHCQD4/) a few days before.

**Comment by drammock** [comment] 2023-04-27 16:48
building numpy docs with sphinx 6 and pydata-sphinx-theme 0.13.3 I get
```console
$ time make html
[...]
real	3m8.449s
user	3m11.327s
sys	0m33.501s
```

The good news is that after this, `make show` gives a local build *with a working version dropdown* and no browser console errors on the homepage... there are still JS errors on the search results page, but they are all like this:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///opt/numpy/doc/build/html/user/c-info.python-as-glue.html. (Reason: CORS request not http).
```
followed by a related/resultant error
```
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

These search page errors all originate from either `_static/searchtools.js` or `_static/doctools.js`.  I have not looked at the contents of those files yet, and for now I assume that the errors will go away if the website is being properly served.

To me this suggests that updating the theme pin to 0.13.3 will work just fine for NumPy (with the caveat that some colors have changed in the interim so you'll likely want to do a few CSS tweaks).

The times compare favorably (after a `make clean`) against building with sphinx 6 and pydata-sphinx-theme 0.9.0:

```console
$ time make html
[...]
real	3m20.908s
user	3m24.088s
sys	0m33.130s
```

**Comment by drammock** [comment] 2023-04-27 17:19
yep, working on it now. Since I'm not staring at numpy docs every day I'll need to rely on reviewers to make sure I catch all the needed CSS changes. Is there a short list of pages (or a "kitchen sink" page) that I should pay special attention to when comparing against current stable docs?

**Comment by rossbar** [comment] 2023-04-27 17:22
> yep, working on it now. Since I'm not staring at numpy docs every day I'll need to rely on reviewers to make sure I catch all the needed CSS changes. Is there a short list of pages (or a "kitchen sink" page) that I should pay special attention to when comparing against current stable docs?

IMO I wouldn't worry about style tweaks too much... I would generally prefer to go with theme defaults as much as possible to avoid maintenance burden!

**Comment by tupui** [comment] 2023-04-27 17:27
Oh great new for NumPy if there is no build time difference!

**Closed** 2023-04-27 19:29 UTC
Labels: 04 - Documentation

**Comment by mattip** [comment] 2023-04-27 21:24
Closing, PR #23677 was merged.
