### ISSUE TITLE
BUG: astype(np.uint16) behaves differently on different platforms (same numpy version)

### ISSUE THREAD

**Issue by shi-yan** [numpy/numpy#20728] opened 2022-01-04 21:08 UTC
### Describe the issue:

We have the following code: 
```python
I_wb = I_wb.astype(np.uint16)
```
I_wb was float32 before the above conversion.
<img width="811" alt="Screen Shot 2022-01-04 at 12 31 16 PM" src="https://user-images.githubusercontent.com/326807/148121640-5a047b35-ef45-456c-90d2-407030bc51c4.png">

We noticed that when overflow happens, astype could behave differently on different platforms.

as shown in the above image, when running the same code on mac, the value 68469.13 will be truncated to 65535, whereas on linux, the value is applied with a modulo operation . 68469.13 % 65535

on both sides, the code uses numpy 1.21.2

also tried 1.22.0, it's the same.

note: The shape of the data matters,

for example:

```python
I2 = np.zeros((2448, 2048, 3), dtype="float32")
I2[1700,970] = [68469.13, 65472.,   65535.]
```
The above can reproduce, the value 68469.13 gets truncated on certain platforms, but applied with modulo on other platforms.

Whereas the following won't reproduce:

```python
I = np.array([68469.13, 65472.,   65535.], dtype="float32")
``` 

on both platforms I tried, it behaves the same ( modulo)

could this be due to the underlining cpp compiler and optimization level (clang vs. gcc) ?

### Reproduce the code example:

```python
import numpy as np
import sys

print(np.__version__ , sys.version)

I2 = np.zeros((2448, 2048, 3), dtype="float32")
I2[1700,970] = [68469.13, 65472.,   65535.]
print("pixel color: ", I2[1700,970])
I2_wb = I2.astype(np.uint16)
print(I2_wb[1700,970])
```

### Error message:

```shell
compare the reproduce code on different platforms, notice output difference even with matched numpy version.
```

### NumPy/Python version information:

1.22.0
1.21.2

sample output on my mac (value truncated):

```bash
1.21.2 3.9.1 (default, Oct 15 2021, 13:26:04)
[Clang 13.0.0 (clang-1300.0.29.3)]
pixel color:  [68469.13 65472.   65535.  ]
[65535 65472 65535]
```

sample output on my linux (modulo)
```bash
1.21.2 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0]
pixel color:  [68469.13 65472.   65535.  ]
[ 2933 65472 65535]

```

**Comment by madphysicist** [comment] 2022-01-05 07:02
You will likely see the same thing in regular C code on the different platforms. I strongly suspect that the overflow condition is undefined behavior, and any compiler is free to decide how it will handle it, if at all.

**Comment by shi-yan** [comment] 2022-01-05 15:55
ya, right.

https://stackoverflow.com/questions/57650026/optimized-clang-handling-overflow

https://loicpefferkorn.net/2013/09/python-force-c-integer-overflow-behavior/

maybe document it somehow?

**Comment by madphysicist** [comment] 2022-01-05 16:20
I don't know where you would put this, but I suspect that it's already documented at a high level somewhere like https://numpy.org/doc/stable/reference/generated/numpy.can_cast.html

**Comment by seberg** [comment] 2022-01-07 16:32
Duplicate of gh-20728 closing as that.  We should start checking FPEs in casts, although I don't think it helps with this example.  It would help (give a warning) if you cast `NaN` or `Inf` to integers

**Closed by seberg** 2022-01-07 16:32 UTC
Labels: 00 - Bug
