### ISSUE TITLE
Question: dtype of empty arrays

### ISSUE THREAD

**Issue by debnathshoham** [numpy/numpy#19674] opened 2021-08-15 08:21 UTC
Not sure if this is a bug, or by design.
The data type of np arrays seems a little strange for empty arrays (should they be float64?).

### Reproducing code example:

```python
import numpy as np
In [4]: numpy.array(())
Out[4]: array([], dtype=float64)

In [5]: numpy.array([])
Out[5]: array([], dtype=float64)

In [6]: numpy.array(None)
Out[6]: array(None, dtype=object)

In [7]: numpy.array({})
Out[7]: array({}, dtype=object)
```

### NumPy/Python version information:
1.21.0 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09) 
[Clang 11.1.0 ]

**Comment by mattip** [comment] 2021-08-15 08:31
By design. See for instance the bottom of [the basic array creation doc](https://numpy.org/devdocs/user/absolute_beginners.html#how-to-create-a-basic-array) section where it says 
> While the default data type is floating point (`np.float64`), you can explicitly specify which data type you want using the dtype keyword.

**Comment by rossbar** [comment] 2021-08-16 07:45
Closing as resolved by mattip's answer.

**Closed by rossbar** 2021-08-16 07:45 UTC
Labels: 33 - Question
