### ISSUE TITLE
1.19.0 cannot convert string into complex number

### ISSUE THREAD

**Issue by mhh0318** [numpy/numpy#16909] opened 2020-07-20 07:22 UTC
numpy 1.19.0 cannot convert string to complex number.
However, numpy 1.18.1 can perform the codes below correctly

### Reproducing code example:

```python
import numpy as np
list = ['3+4j', '1.23+4.56j', '0.123-1.234j', '0.234+0.456j', '1.123+0.432j']
np.array(list).astype(np.complex)
```

### Error message:
Traceback (most recent call last):
  File "\<stdin\>", line 1, in \<module\>
TypeError: must be real number, not numpy.str_

### Numpy/Python version information:
numpy version: 1.19.0
python version: 3.7.6

**Comment by mattip** [comment] 2020-07-20 08:01
I don't see which of the changes in the [release notes](https://numpy.org/devdocs/release/1.19.0-notes.html) changed this. If it was intentional it should be documented, and if not then it is a bug, and should be fixed. I think it is caused by some refactoring of the dtypes around setitem.

**Comment by eric-wieser** [comment] 2020-07-20 08:09
The fix for this was recently backported

**Comment by mhh0318** [comment] 2020-07-20 08:37
> The fix for this was recently backported

Thanks.

**Comment by mattip** [comment] 2020-07-20 08:40
Could you point to the issue/PR that fixed this? If I am not mistaken it is still occurring on master

**Comment by eric-wieser** [comment] 2020-07-20 08:45
My assumption was that #16242 fixed this in master, but perhaps I am mistaken.

**Comment by mattip** [comment] 2020-07-20 09:18
It seemed the py3k refactor of `UNICODE_to_CDOUBLE` from [1.18.5](https://github.com/numpy/numpy/blob/v1.18.5/numpy/core/src/multiarray/arraytypes.c.src#L1569) to [1.19.0](https://github.com/numpy/numpy/blob/v1.19.0/numpy/core/src/multiarray/arraytypes.c.src#L1528) mistakenly eliminated the stanza that uses `Py_BuildValue` to convert, and tests missed it.

**Comment by seberg** [comment] 2020-07-20 13:16
Yeah, deleting this was intentional. The reason why this happens is that `np.complex128("1+2j") does *not* work, if it worked, the result would not have been affected here

**Comment by eric-wieser** [comment] 2020-07-20 13:22
So it sounds like we need to fix `gentype_new` for `complex` types to perform string parsing?

**Comment by seberg** [comment] 2020-07-20 13:30
Probably should add it to the `setitem` function of complex128, so that:
```
In [1]: arr = np.array([1], dtype=np.complex128)                                                                        
In [2]: arr[0] = "2j"
```
works as well, at which point I expect everything else will fall into place, since our strings also subclass from the python strings anyway.

**Comment by mattip** [comment] 2020-07-20 14:12
The old code used `PyComplex_Type.tp_new(&PyComplex_Type, args, NULL);` to activate the string parsing

**Comment by seberg** [comment] 2020-07-20 14:26
Honestly, I think we can probably pretty much just use `PyComplex_AsCComplex` and be done with it.  Bytes (`"S"`) will have to be handled (python rejects them, we don't since we never changed it since Python 2). That is in principle buggy for complex256, but either complex256 already has the paths in some cases, or it always was, so no reason to bother too much right now.

**Comment by seberg** [comment] 2020-07-20 14:48
Ah, the added complexity is that `PyComplex_AsCComplex` does not convert strings, while `PyFloat_AsDouble` and all the older versions are more than happy to convert both (unicode) strings and byte strings.  So while the paths look completely identical, it turns out the Python API differs in subtle ways between them...

**Comment by mattip** [comment] 2020-07-20 14:55
> Ah, the added complexity is that PyComplex_AsCComplex does not convert strings

Yes, that is the source of this issue. We need to use `PyComplex_Type.tp_new(&PyComplex_Type, args, NULL);`

**Closed** 2020-07-20 21:49 UTC
Labels: 00 - Bug
