### ISSUE TITLE
BUG: np.float64(np.array([1.])) equals 1.0 but not array([1.], dtype=float64)

### ISSUE THREAD

**Issue by haoyang9804** [numpy/numpy#24661] opened 2023-09-07 07:26 UTC
### Describe the issue:

I found this error when solving a [TVM issue](https://github.com/apache/tvm/issues/15282#issuecomment-1708307360).
Just as the title describes, `np.float64(np.array([1.]))` should returns `array([1.], dtype=float64)`, but it actually returns `1.0`.

### Reproduce the code example:

```python
import numpy as np
print(np.float64(np.array([1.])))
```

### Runtime information:

1.24.3
3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
nformation
[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}}]
None

### Context for the issue:

As a popular Python library that is widely used over many other libraries. This error may trigger unexpected errors in other systems. For instance, TVM, a popular machine learning compiler framework, reports a type mismatch caused by this little numpy bug. And it takes me a lot of time to finalize the root cause.

**Comment by seberg** [comment] 2023-09-07 08:10
There is a deprecation warning on this.  Maybe we should bump that to a `FutureWarning`:  FutureWarnings get seen better and in this particular case we want to change the behavior.

I.e. this is in progress and while I am not 100% sure about the timing, maybe we should even change it in main (I think the warning was only added in 1.25 unfortunately).

However, I will also say that as far as I am aware most/all of us really dislike using `np.float64` here, if you want an array, use `np.asarray(..., dtype="float64")`.  `np.float64` is the *scalar* and is just overloaded to also return arrays.  This does not work for all scalars (although it should for NumPy numerical ones).

**Comment by rkern** [comment] 2023-09-07 13:38
Closing as duplicate of #1362

**Closed by rkern** 2023-09-07 13:38 UTC
Labels: 00 - Bug
