### ISSUE TITLE
Problem installing (or using) numpy in an embedded win32 application

### ISSUE THREAD

**Issue by adisc2** [numpy/numpy#13476] opened 2019-05-05 18:15 UTC
### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by adisc2** [comment] 2019-05-05 18:27
I'm having problems importing numpy on an embedded win32 application.  Some background:
1) I only have one version of python installed (Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32, installed as admin in c:/Program Files (x86) )
2) I installed from the command line using "python -m pip install -U numpy". For the record, I did check that the expected version of python was called

The error occurs when I try to do the following from C++:
	Py_Initialize();
	PyRun_SimpleString("import numpy as np");

The error generated is:

// START OF ERROR MSG

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\core\__init__.py", line 40, in <module>
    from . import multiarray
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Trading\TradeStationCode\SnD\Debug\Replay.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath' 

// END OF ERROR MSG

I have verified the paths are fine.

I can import numpy the normal way from a Python console, just not from the embedded application.

Thanks in advance!
    Paul

**Comment by rgommers** [comment] 2023-09-16 08:06
Thanks for the report @adisc2. I'll close this as a duplicate of gh-21443, which has more discussion and context.

**Closed by rgommers** 2023-09-16 08:06 UTC
Labels: 50 - Duplicate, Embedded, 32 - Installation
