### ISSUE TITLE
Float-to-integer conversion makes great values negative

### ISSUE THREAD

**Issue by MarcVincent9** [numpy/numpy#13171] opened 2019-03-21 13:30 UTC
There seems to be an error with float-to-integer conversion for values close to numpy.intXX's upper bound.

Beyond a certain value, which varies with the type of int, a positive float converted to integer becomes negative.

This happens with different float/int types. It doesn't happen with Python's native int() function.

### Reproducing code example:

```python
import numpy as np

ok_64 = np.float64(2**63 - 512.01)
not_ok_64 = np.float64(2**63 - 512)

assert(np.int64(ok_64) == 2**63 - 1024)
assert(np.int64(not_ok_64) == - 2**63)
assert(int(not_ok_64) == 2**63)


ok_32 = np.float32(2**31 - 64.01)
not_ok_32 = np.float32(2**31 - 64)

assert(np.int32(ok_32) == 2**31 - 128)
assert(np.int32(not_ok_32) == - 2**31)
assert(int(not_ok_32) == 2**31)


ok_16 = np.float16(2**15-8.01)
not_ok_16 = np.float16(2**15-8)

assert(np.int16(ok_16) == 2**15 - 16)
assert(np.int16(not_ok_16) == - 2**15)
assert(int(not_ok_16) == 2**15)
```

### Numpy/Python version information:

1.11.1 / 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

1.14.3 / 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]

**Comment by eric-wieser** [comment] 2019-03-21 15:07
This is because `np.float64(2**63 - 512) == np.float64(2**63)`, floats lose precision when storing large integers.

**Comment by MarcVincent9** [comment] 2019-03-21 23:08
OK, but why does the conversion to np.int64 make it negative ? The real problem here is that we have ```python np.int64(np.float64(2**63)) < 0```.

**Comment by eric-wieser** [comment] 2019-03-22 00:11
@MarcVincent: The largest value that can fit in an `int64` is `2**63 - 1`. `2**63` will not fit.

**Comment by Androp0v** [comment] 2019-04-05 16:30
Python's native int type has arbitrary precision and doesn't suffer from overflow errors. Numpy's int64 or int32 have limited precision and any int bigger than what they can store will overflow (in this case, leading to negative numbers). Overflow behaviour is documented [here](https://www.numpy.org/devdocs/user/basics.types.html).

**Comment by eric-wieser** [comment] 2019-04-06 08:43
Closing since this is by design (it matches C)

**Closed by eric-wieser** 2019-04-06 08:43 UTC
