### ISSUE TITLE
Update release checklist to include more QA / encouragement of QA for pre-releases

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#6494] opened 2015-10-17 05:56 UTC
See discussion starting here: https://github.com/numpy/numpy/issues/6462#issuecomment-148107774

It sounds like the actionable conclusions are:
- we should make sure to test RCs against at least scipy, pandas, sklearn, skimage, astropy (list subject to revision). This could be done manually by the release manager (@juliantaylor might have hints?), or some other way (e.g. by pinging the various package authors and waiting for confirmation that they've tested their code before we make the final release -- this would also work to systematically handle dedicated QAers who aren't just running a single package's test, like C. Gohlke or people who want to test internal software stacks).
- We should probably exhort people to test pre-releases on twitter
- It might be good to start a public campaign to encourage everyone who uses `pip install` in their CI setup to add `--pre` to the options... this would dramatically increase the amount of testing that all pre-releases get, not just numpy's. (Doesn't work for those using conda in their CI, alas.)

**Comment by rgommers** [comment] 2015-10-17 16:22
I'd add ``statsmodels`` to that list, it usually turns up a few issues. I used to do this kind of testing around beta time. Simply by hand, since I have all those packages installed anyway.

**Comment by argriffing** [comment] 2015-10-22 17:15
also matplotlib https://github.com/numpy/numpy/issues/6551 although it's already [listed](https://github.com/numpy/numpy/blob/maintenance/1.10.x/doc/HOWTO_RELEASE.rst.txt#announce-to-the-lists)

**Comment by rgommers** [comment] 2015-10-31 23:05
> This could be done manually by the release manager or some other way

Linked in gh-6462 as well but, this should be a good start: https://github.com/MacPython/scipy-stack-osx-testing

The only other thing that's important is testing on Windows. That's a lot harder to automate.

**Comment by ngoldbaum** [comment] 2016-01-30 18:27
I've been manually testing yt when I hear about prerelease numpy releases. This caught some new failures with Numpy 1.11 this week:

https://bitbucket.org/yt_analysis/yt/pull-requests/1969/compatible-with-upcoming-numpy-111-release/diff

**Comment by njsmith** [comment] 2016-01-30 18:34
@ngoldbaum: It looks like from a quick skim that those are all genuine
cleanups/fixes to yt code, rather than any regressions in numpy? (I am
double-checking because I feel like often people treat whatever numpy does
as being unavoidable, like the weather, and often this includes random
mistakes we've made that really should just get fixed on our end :-). Or at
the very least we want to know how much impact even our intentional changes
are having...)

On Sat, Jan 30, 2016 at 10:27 AM, ngoldbaum <notifications@github.com>
wrote:

> I've been manually testing yt when I hear about prerelease numpy releases.
> This caught some new failures with Numpy 1.11 this week:
>
>
> https://bitbucket.org/yt_analysis/yt/pull-requests/1969/compatible-with-upcoming-numpy-111-release/diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6494#issuecomment-177268036>.
>



-- 
Nathaniel J. Smith -- https://vorpus.org <http://vorpus.org>

**Comment by ngoldbaum** [comment] 2016-01-30 18:37
No, I wouldn't call any of those regressions in numpy, otherwise I would have raised it on the mailing list. Just thought I'd comment to indicate that it might be good to check in with yt to do prerelease testing.

**Comment by amueller** [comment] 2016-02-10 18:36
relevant: https://github.com/scikit-learn/scikit-learn/issues/6330

**Comment by mattip** [comment] 2019-04-26 00:58
It would be nice to run a weekly CI job that would try the HEAD wheel against test suites in packages known to be sensitive to NumPy changes. So far this issue suggests scipy, pandas, sklearn, skimage, astropy, and yt

**Comment by rgommers** [comment] 2019-04-26 07:11
Just so we don't plan on reinventing this wheel from scratch: https://github.com/pv/testrig (cross-stack testing tool). Previous discussion about this: https://mail.python.org/pipermail/numpy-discussion/2016-February/074784.html

> It would be nice to run a weekly CI job that would try the HEAD wheel against test suites in packages known to be sensitive to NumPy changes

We've turned this around in the meantime; those packages are all testing against numpy master, which is a more scalable model.

**Comment by amueller** [comment] 2019-04-28 19:22
We have CI with numpy, scipy, pandas and cython nightly builds (or whatever else is on rackspace). Right now still on travis I think but moving to azure pipelines:
https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/travis/install.sh#L113

https://travis-ci.org/scikit-learn/scikit-learn

oh look, it's failing with numeric issues :)

**Comment by amueller** [comment] 2019-04-28 19:24
of @rgommers just said that lol. Yes, I think that's probably a more scaleble solution. If the tests fail,  I think the downstream packages have an easier time determining whether the issue is upstream or downstream. Though arguably if any of these downstream packages break there should have probably been a deprecation cycle.

**Comment by matthew-brett** [comment] 2019-04-28 22:35
I built this when we were starting off with OpenBLAS; it would need a little loving care, but it tests lots of packages against a numpy version:

https://github.com/matthew-brett/manylinux-testing

**Comment by mattip** [comment] 2020-12-02 21:08
I am going to close this, since now that the weekly wheels are available NumPy HEAD is being tested by quite a few packages. More can be done to promote testing but I don't think this issue will help with that. Please reopen if there are actionable tasks we can do to make the situation better.

**Closed by mattip** 2020-12-02 21:08 UTC
Labels: 16 - Development, component: build
