### ISSUE TITLE
np.ma.mean(img) broken for np.float16 type

### ISSUE THREAD

**Issue by user-na** [numpy/numpy#8133] opened 2016-10-10 18:52 UTC
I have a 64x64 image filled with uint8 random numbers. ( [TESTimg.zip](https://github.com/numpy/numpy/files/520200/TESTimg.zip) )

Depending on the dtype, I get slightly different results (as expected):
```
img = np.fromfile(imagepath, dtype=np.uint8).reshape(64,64).astype(np.uint8)
np.ma.mean(img)
Out: 126.73388671875

img = np.fromfile(imagepath, dtype=np.uint8).reshape(64,64).astype(np.float32)
np.ma.mean(img)

Out: 126.73389
```
But for float 16, things go totally wrong:
```
img = np.fromfile(imagepath, dtype=np.uint8).reshape(64,64).astype(np.float16)
np.ma.mean(img)
Out: inf
```

Numpy Version 1.11.1
Python 2.7

**Comment by ahaldane** [comment] 2016-10-10 19:45
This isn't a maskedarray problem, it happens with ndarrays too, and it's probably not a bug. In summary, you are hitting the precision limit of float16. 

The problem is that the maximum non-infinte `float16` value is `65536.0`.  Your array happens to sum to more than this value, and `np.mean` is implemented by summing then dividing by the number of elements. The result of the sum is `inf`.

**Comment by user-na** [comment] 2016-10-10 19:58
With this argumentation, uint8 should deliver an inf result too. But in fact its result is quite accurate.

**Comment by ahaldane** [comment] 2016-10-10 20:12
Yeah, it might be a bit surprising, but the `np.mean` docstring explains:

    `float64` intermediate and return values are used for integer inputs.

So for integer inputs numpy converts to float64 which has enough precision to do the sum. For float inputs numpy leaves the datatype alone, and can't do the sum.

Also, to correct myself: it looks like the maximum `float16` value is 65504.0, or `0 11111 1111111111` in binary. 

By the way, funnily enough `np.float16(65519) == 65504`, because of the way the mantissa of 65519 gets truncated.

**Comment by user-na** [comment] 2016-10-11 06:55
Ok, I now understand that numpy works as specified. 
From a user point of view, this behavior is at least unexpected.

So why not using always `float64 `as long as no explicit `dtype `is specified?
On the other hand one would have to do extra conversion steps and thus slowing down the mean for cases in which the `dtype `(e.g. `float32`) is sufficient. But in this cases one could use the `dtype `parameter.

What about mentioning the overflow behavior in the docstring?

**Comment by ahaldane** [comment] 2016-10-11 19:06
Anyone (including you) is free to propose changes to the docstring.

In my opinion, though, the docstring does a pretty good job warning about precision issues, now that I look at it :). 

It mentions this behavior in the summary at the top, in the description of the `dtype` in the `Parameters` section, it has a paragraph about it in the `Notes` section, and has an example related to precision in `Examples`.

I'm going to go ahead and close this issue, but thanks for reporting possible problems to us!

(also PS I got the binary string wrong. 65504 is `0111101111111111`, I forgot the bias).

**Closed by ahaldane** 2016-10-11 19:06 UTC
