### ISSUE TITLE
Performance regression for simple operations on structured arrays in 1.13.3

### ISSUE THREAD

**Issue by tdpetrou** [numpy/numpy#9934] opened 2017-10-27 16:59 UTC
## Updated response

**Setup**
```
n = 500000
struc = np.empty(n, dtype=[('a', 'int'), 
                           ('b', 'object'), 
                           ('c', 'object'),
                           ('d', 'object'),
                           ('e', 'float'),
                           ('f', 'object'),
                           ('g', 'int')])
obj = ['asdf'] * n

struc['a'] = np.zeros(n)
struc['b'] = obj
struc['c'] = obj
struc['d'] = obj
struc['e'] = [0] * n
struc['f'] = obj
struc['g'] = np.zeros(n)

struc_small = np.empty(n, dtype=[('a', 'int'), 
                                 ('b', 'object')])

struc_small['a'] = np.zeros(n)
struc_small['b'] = obj

arr = np.zeros(n)
```
**Timings**

```
>>> %timeit struc['e'] + 1
1.65 ms ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> %timeit struc['g'] + 1
1.65 ms ± 24.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> %timeit struc_small['a'] + 1
717 µs ± 43.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> %timeit arr + 1
315 µs ± 2.96 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

### Discussion
When using a mix of objects and numerics, performance of basic arithmetic operations slows down with an increasing number of fields. For instance, the structured array with two fields is 2x as slow as a normal numpy array. A structured array with seven fields is 5x slower.

### Old response
I was working in 1.13.3  with a structured array with about 30 fields and 50k rows and noticed a 6x performance slowdown with a simple scalar addition vs a normal array.

```
>>> n=1000000
>>> dict_homo = {'a': np.zeros(n), 'b': np.zeros(n)}
>>> %timeit dict_homo['a']+=1
462 µs ± 33.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> np_homo = np.zeros(n, dtype=[('a', np.double), ('b', np.double)])
>>> %timeit np_homo['a'] + 1
2.47 ms ± 24.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

This appears to be an old issue that might have cropped up again (#6467).  I found [this SO question](https://stackoverflow.com/questions/34933105/speed-up-structured-numpy-array) with similar results.

**Comment by mhvk** [comment] 2017-10-27 17:11
@tdpetrou - could you rerun your test with either doing both in place or both out of place, so we are comparing correctly? (it may be that only one is problematic...)

**Comment by ahaldane** [comment] 2017-10-27 17:22
With both inplace, I do get a big slowdown for the second one. It appears to be a very old behavior, because I see it in 1.9.1, as well as in master.

When working on structured arrays, I remember noticing there are some code paths are extremely and unnecessarily slow, which I was hoping to fix once the multi-field view changes were made (coming up in 1.14). I just looked up my notes on this, here is what they say (though I can't say I remember the details at the moment):

> Structure assignment is slow because it goes through the 'wrong' path in `mapiter_set`. It uses `copyswapn` when `dtype_transfer` would be much faster, since copyswapn iterates through the field dict for every element. See #1984. This should be a somewhat straightforward fix.

I am not sure if that is the cause in your case, but it might be.

**Comment by ahaldane** [comment] 2017-10-27 17:39
Scratch my last comment - I don't think this has to do with structured arrays, but it might just be due to memory layout.

In the following code I create a structured array but then just extract the first field, giving a strided ndarray. So the assignment operations both apply to unstructured ndarrays, but in the 2nd case there is a stride (and it is not C-contiguous)

```python
n=1000000
dict_homo = {'a': np.zeros(n), 'b': np.zeros(n)}
%timeit dict_homo['a']+=1
np_homo = np.zeros(n, dtype=[('a', np.double), ('b', np.double)])
arr_homo_strided = np_homo['a']
%timeit arr_homo_strided[:] += 1
```

Output:
```
1000 loops, best of 3: 444 µs per loop
1000 loops, best of 3: 1.54 ms per loop
```

So I suspect that this is a "normal" slowdown due to bad cache behavior and lack of contiguity.

**Comment by tdpetrou** [comment] 2017-10-27 18:24
@mhvk @ahaldane I have updated my original post to show the large performance difference that I was experiencing. Structured arrays perform worse for an increasing number of fields on basic arithmetic operations. In my personal example, a structured array of 30 fields and 50k rows was 6x slower.

**Comment by mhvk** [comment] 2017-10-27 18:27
Checked better myself now, and agree with @ahaldane's conclusions that it seems to be just a question of striding for in-place. @tdpetrou - could you confirm that you find only small differences for out-of-place and bigger ones for in-place? The difference for you still seems much larger than what we find.

First, doing it out-of-place is roughly equal (on my slow laptop):
```
n=1000000
dict_homo = {'a': np.zeros(n), 'b': np.zeros(n)}
%timeit dict_homo['a']+1
# 100 loops, best of 3: 4.62 ms per loop
np_homo = np.zeros(n, dtype=[('a', np.double), ('b', np.double)])
%timeit np_homo['a']+1
# 100 loops, best of 3: 5.1 ms per loop
```
In-place, the normal one speeds up, while the structured one slows down:
```
%timeit dict_homo['a']+=1
# 100 loops, best of 3: 3.97 ms per loop
%timeit np_homo['a'] += 1
# 100 loops, best of 3: 7.9 ms per loop
```
But it does look like this is just a normal slow-down for in-place for different strides:
```
a = np.zeros((2,n))
%timeit a[0] += 1
# 100 loops, best of 3: 3.95 ms per loop
a = np.zeros((n,2)).T
%timeit a[0] += 1
# 100 loops, best of 3: 8.09 ms per loop
```

**Comment by mhvk** [comment] 2017-10-27 18:46
Sorry, I see I missed the update before commenting. I think it is still a memory layout issue:
```
In [3]: n=1000000

In [4]: a = np.zeros((7,n))

In [5]: %timeit a[0] += 1
100 loops, best of 3: 3.95 ms per loop

In [6]: a = np.zeros((n,7)).T

In [7]: %timeit a[0] += 1
10 loops, best of 3: 28.1 ms per loop
```
The problem is simply that the cost of the computation is dominated by the amount of memory that has to be processed, and since structured arrays are stored by row, you are effectively making the amount of memory that has to be gone over 7 times bigger.

**Comment by tdpetrou** [comment] 2017-10-27 20:30
Apologies, I didn't even see the inplace operation from my original post. Looks like they are
```
>>> n=1000000
>>> dict_homo = {'a': np.zeros(n), 'b': np.zeros(n)}
>>> %timeit dict_homo['a'] + 1
806 µs ± 54.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> np_homo = np.zeros(n, dtype=[('a', np.double), ('b', np.double)])
>>> %timeit np_homo['a'] + 1
>>> 1.35 ms ± 41.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

# inplace
>>> %timeit dict_homo['a'] += 1
605 µs ± 18.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

>>> %timeit np_homo['a'] += 1
1.03 ms ± 34.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Had no idea that structured arrays are stored by row? It's not [mentioned in the structured array docs](https://docs.scipy.org/doc/numpy-dev/user/basics.rec.html).

So, without using pandas, and wanting to maintain the highest level of performance would you guys suggest using a dictionary of single dimensional arrays for heterogenous data?

**Comment by mhvk** [comment] 2017-10-27 21:41
Hmm, indeed, that part of the documentation is not very clear. It is somewhat implicit in the structure being the `dtype` -- this implies the single unit of an array is organized in memory following the dtype prescription (the dtype documentation may explain this -- no time to check right now).

I'm not quite sure what I would recommend: it really depends on details of how you want to use it, etc. And I usually use astropy's `QTable` myself...

Anyway, since the issue itself seems resolved, shall we close it?

**Comment by mhvk** [comment] 2017-10-27 21:43
p.s. If you have some time, a PR clarifying the documentation would be welcome. As noted, there almost certainly is a place somewhere that describes the memory layout, so it would mostly be a matter of finding that and linking to it...

**Comment by tdpetrou** [comment] 2017-10-27 21:55
Yes, let's close it. I'll try and search the docs some more. It might be helpful to note how massive the performance hit is with lots of data. Thanks for the responses.

**Closed** 2017-10-27 21:57 UTC

**Comment by ahaldane** [comment] 2017-10-28 00:16
Yes, something like that will improve your cache behavior. 

We're working on updating the structured array docs in #9056. I might add more emphasis on the poorer cache behavior you get using structured arrays vs using pandas (related to the last 2 paragraphs of the introduction).
