### ISSUE TITLE
BUG: subtraction two numpy arrays of np.uint64 doesn't return the correct result.

### ISSUE THREAD

**Issue by nir-vaknin-vaknin** [numpy/numpy#26998] opened 2024-07-20 10:05 UTC
### Describe the issue:

If there exists a coordinate in numpy array of type `dtype=np.uint64` , `x`, smaller then numpy array of type `dtype=np.uint64` , `y`, the subtraction of the two will be overflowed. 

### Reproduce the code example:

```python
import numpy as np
x = np.array([1,2,3],dtype=np.uint64)
y = np.array([1,2,3],dtype=np.uint64)+1
z = x-y
```

### Error message:

Output:
`[18446744073709551615 18446744073709551615 18446744073709551615]`
Instead of:
`[-1 -1 -1]`

### Python and NumPy Versions:

numpy.__version__ 1.24.2
sys.version 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]

**Comment by mattip** [comment] 2024-07-21 10:47
How can uint64 output -1? That value is not valid unit64.

**Comment by aryanvarshney** [comment] 2024-07-21 19:05
Based on docs, I would say this is not a bug and the expected value when a uint datatype overflows.

[Overflow doc](https://numpy.org/doc/stable/user/basics.types.html#overflow-errors)

You can see the same output with uint8

```
import numpy as np

x = np.array([1,2,3],dtype=np.uint8)
y = np.array([1,2,3],dtype=np.uint8)+1
z = x-y
```

Output:
`
[255 255 255]
`

**Comment by mattip** [comment] 2024-07-22 05:31
Closing as I think the explanations make the problem clear.

**Closed by mattip** 2024-07-22 05:31 UTC
Labels: 33 - Question
