### ISSUE TITLE
import numpy error

### ISSUE THREAD

**Issue by x920** [numpy/numpy#15594] opened 2020-02-18 15:16 UTC
```
ipython
Python 3.8.0 (default, Dec  5 2019, 10:23:28)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38.so: unused DT entry: type 0x6ffffef5 arg 0x18d0
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy/core/_multiarray_tests.cpython-38.so: unused DT entry: type 0x6ffffef5 arg 0xd38
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d4cdadb62aa7> in <module>
----> 1 import numpy

/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy/__init__.py in <module>
    140     from . import _distributor_init
    141
--> 142     from . import core
    143     from .core import *
    144     from . import compat

/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy/core/__init__.py in <module>
    102 # do this after everything else, to minimize the chance of this misleadingly
    103 # appearing in an import-time traceback
--> 104 from . import _add_newdocs
    105 # add these for module-freeze analysis (like PyInstaller)
    106 from . import _dtype_ctypes

/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy/core/_add_newdocs.py in <module>
   4439
   4440
-> 4441 add_newdoc('numpy.core._multiarray_tests', 'format_float_OSprintf_g',
   4442     """
   4443     format_float_OSprintf_g(val, precision)

/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy/core/function_base.py in add_newdoc(place, obj, doc, warn_on_python)
    504     If possible it should be avoided.
    505     """
--> 506     new = getattr(__import__(place, globals(), {}, [obj]), obj)
    507     if isinstance(doc, str):
    508         _add_docstring(new, doc.strip(), warn_on_python)

ImportError: dlopen failed: cannot locate symbol "tanh" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/numpy/core/_multiarray_tests.cpython-38.so"...
```

**Comment by x920** [comment] 2020-02-18 15:17
after installed,first import to tests

**Comment by rgommers** [comment] 2020-05-01 16:25
Closing, old install issue, not a bug and not much we can do here.

**Closed by rgommers** 2020-05-01 16:25 UTC

**Comment by sbroberg** [comment] 2020-05-27 20:07
@rgommers Can you clarify?  What is the "old install issue"?  I'm having the exact same error, when trying to import numpy cross-compiled using the python crossenv module onto aarch64-linux-android (Android 10, API 28).  

I've tried statically linking libm when building numpy, but it only statically links /_multiarray_umath.cpython, not /_multiarray_test.cpython.  libm.so is present in my path, and it is linking correctly against python3.5 (which I see using strace).

Is there a resolution to this issue documented elsewhere?

**Comment by rgommers** [comment] 2020-05-28 09:18
@sbroberg we have a ton of such install issues without steps to reproduce them nor a build log. There's basically nothing we can say except "something went wrong here". 

>  I'm having the exact same error, when trying to import numpy cross-compiled using the python crossenv module onto aarch64-linux-android

If you open a new issue, please try and make it reproducible. Also, cross-compiling is generally problematic, `distutils` doesn't really support it. I also have no idea what `crossenv` is. 

My recommendation would to avoid cross-compiling if at all possible. There are ARM64 wheels in the making, and conda-forge has ARM64 already.

**Comment by mattip** [comment] 2020-05-28 09:24
> There are ARM64 wheels in the making,

You can test drive them at https://anaconda.org/scipy-wheels-nightly/numpy/

**Comment by sbroberg** [comment] 2020-05-29 20:08
@rgommers 

Thanks for the prompt reply.  I can have a very reproducible case for you within a week

> If you open a new issue, please try and make it reproducible. Also, cross-compiling is generally problematic, `distutils` doesn't really support it. I also have no idea what `crossenv` is.
> My recommendation would to avoid cross-compiling if at all possible. There are ARM64 wheels in the making, and conda-forge has ARM64 already.

Believe me, nothing would please me more than to not have to do build this stuff myself.  FYI, [crossenv](https://pypi.org/project/crossenv/) is a python module that facilitates cross-compiling other python modules.

You'll have to forgive me, because python is not my domain, and I've been tasked with being able to run our test suite (written in python) on this qualcomm arm64 android board.  From your suggestion above, I looked briefly at the conda-forge intro page and it presumes I have conda installed.  Does this mean I have to cross compile conda?  The system I'm on has no apt, or even a c compiler.

I've made some progress switching to using Termux and starting an ssh server so I can connect to our Android board (this has apt and allowed me to install numpy successfly via pip), but I'm stuck on getting opencv (with python bindings) to build.  I realize this isn't your job, but I'd appreciate it if you can point me at a resource that sets me in the right direction, as there seem to be a million different ways of supposedly skinning this cat.

**Comment by sbroberg** [comment] 2020-05-29 20:12
> > There are ARM64 wheels in the making,
> 
> You can test drive them at https://anaconda.org/scipy-wheels-nightly/numpy/

@mattip: Thanks for the tip.  I tried doing this on my bare metal environment (running directly in the Android device via adb shell, with a cross-compiled python3.5), but I got this:

`./pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy
Looking in indexes: https://pypi.anaconda.org/scipy-wheels-nightly/simple
ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)
ERROR: No matching distribution found for numpy
`
I see this a lot for a number of packages.  Are there environment variables or system utilities I can call that will tell me the details of my platform that are being used to determine compatibility?

Thanks.

**Comment by rgommers** [comment] 2020-05-29 20:12
> From your suggestion above, I looked briefly at the conda-forge intro page and it presumes I have conda installed. Does this mean I have to cross compile conda?

Here's a self-contained ARM64 installer: https://github.com/conda-forge/miniforge#miniforge3

**Comment by charris** [comment] 2020-05-29 20:18
> cross-compiled python3.5

That's the problem. The test wheels only support 3.6+. If you have a choice, a later version of Python would be good, we may drop 3.6 for numpy 1.20.

**Comment by rgommers** [comment] 2020-05-29 20:19
> I'm stuck on getting opencv (with python bindings) to build. 

Yeah that doesn't sound like fun. I see there are no conda-forge `aarch64` packages. There's unofficial wheels at https://pypi.org/project/opencv-python-aarch64/ though. Worth a try I'd say. You should be able to install those wheels into Miniforge. And Miniforge/conda-forge does have packages for NumPy, SciPy, Pandas, etc. So you may be able to do this without having to build anything.

If those unofficial wheels don't work, asking at (or contributing to) https://github.com/conda-forge/opencv-feedstock may be the best and most sustainable way of doing this.

**Comment by charris** [comment] 2020-05-29 20:38
There are no aarch64 opencv wheels on PyPI that support recent Python. The one that is up there is three years old and only supports Python 3.4.

**Comment by rgommers** [comment] 2020-05-30 12:06
Ah, missed that. Then contributing on the conda-forge feedstock would be my recommendation.
