### ISSUE TITLE
BUG: (Possibly) Problems assigning complex numbers to array elements

### ISSUE THREAD

**Issue by hjelmare** [numpy/numpy#4379] opened 2014-02-27 13:46 UTC
I was trying to assign a complex number value to an element in an array, but got some strange errors. I posted a question on stackoverflow ( http://stackoverflow.com/questions/22016847/assigning-complex-values-to-numpy-arrays ) and it seems I'm not alone in finding the situation a bit confusing.

Comments with numbers denote points of interest

```
from numpy import * 

C = zeros((2,2))     # 1

x = random.rand(1)
y = random.rand(1) + random.rand(1)*1j
print x, x.real, x.imag
print y, y.real, y.imag

C[0,0] = x     # 2
print C

C[0,0] = y    # 3
print C
```

It seems to me like `x` and `y` are both one-element arrays, identical except that `y.dtype` is `complex` while is `x.dtype` is `float`. Line # 2 works just fine, but # 3 gives `ValueError: setting an array element with a sequence.`. I do not understand why `y` would be a sequence if `x` is not.

From the stackoverflow answer, I'm aware that I can work around this strange behaviour by slicing `C[0,0:1] = y`, and this works for both # 2 and # 3, but I don't understand why it is required in one case but not the other.

---

Also, changing # 1 to `C = zeros((2,2), dtype=complex)`, which seems like a reasonable thing to do when I want to store complex values in `C`, changes the error given to `TypeError: can't convert complex to float`. From stackoverflow, it appears this is a known bug? I don't know, but I thinks it's worth mentioning that as well.

**Comment by btel** [comment] 2015-08-14 13:28
I found similar problem:

```python
>>> import numpy as np
>>> print np.__version__
1.9.2
>>> x = np.zeros(3, np.complex128)
>>> c = np.array([1j])
>>> x[0] = c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to float
```

This works:

```python
>>> x[0] = c[0]              
>>> print x
[ 0.+1.j  0.+0.j  0.+0.j]
```

It also works when `c` is an array of floats (note that `x` is still complex):

```python
>>> c = np.array([1])
>>> x[0] = c
>>> print x
[ 1.+0.j  0.+0.j  0.+0.j]
```

**Comment by charris** [comment] 2015-08-14 15:20
The error message is misleading. It looks like the problem here is that you are assigning a 1-D array to a 0-D slot. Perhaps the message should be 'Can't convert a complex array to float".

**Comment by pv** [comment] 2015-08-14 15:26
Typically in Numpy, 1-element arrays are treated as scalars, but that
doesn't seem to work in this case. Note that similar assignment works
for float dtype...

**Comment by seberg** [comment] 2015-08-14 15:55
The problem is that the `__float__` slot exists for arrays with one element (not just 0-d!). However, for reasons of lazyness ;) nobody ever implemented the `__complex__` slot, which explains this phenomenon. On assignment numpy will attempt to use those slots, which makes the assignment work for float numbers when it basically should not work. The real fun starts when you include object arrays into it ;).

**Comment by mattip** [comment] 2018-08-08 00:49
The example failures given now succeed. Closing, please reopen with a failing snippet.

**Closed by mattip** 2018-08-08 00:49 UTC
