### ISSUE TITLE
np.polyfit memory leak

### ISSUE THREAD

**Issue by bstdenis** [numpy/numpy#7078] opened 2016-01-20 21:24 UTC
Running the following code, I end up with ~6 GB of memory used. It scales linearly with the chosen value of n.

```
import numpy as np
n = 3000
xs=range(55115)
for m in range(n):
    ys = np.random.random([55115])
    c = np.polyfit(xs,ys,4)
```

This is what it looks like with "top":

PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
69385 stdenis   20   0 6881224 6.186g   6728 S   0.0  4.9   0:58.56 python

Reproduced with the following versions:
Python 2.7.11, numpy 1.10.2 on CentOS Linux release 7.2.1511
Python 3.4.4, numpy 1.10.4 on CentOS Linux release 7.2.1511

I was not able to reproduce on other machines with
Python 2.7.6, numpy 1.9.1 on Linux
Python 2.7.3, numpy 1.6.2 on Linux

**Comment by charris** [comment] 2016-01-20 22:17
Hmm, there are no changes in `polyfit` since 1.9. Could it be `np.random.random`?. Another possibility is `linalg.lstsq`.

**Comment by charris** [comment] 2016-01-20 22:37
`lstsq` looks like the guilty party.

**Comment by charris** [comment] 2016-01-20 23:12
However, I see this in all Numpy versions from 1.7 to the present. I wonder if it is library dependent?

**Comment by charris** [comment] 2016-01-21 00:20
NVM, pilot error here.

**Comment by charris** [comment] 2016-01-21 01:19
OK, bisect indicates a library problem.
```
commit dd0732e4bda8f4379b17ea479bcecc876ab50ce6
Author: Charles Harris <charlesr.harris@gmail.com>
Date:   Wed Dec 10 17:42:02 2014 -0700

    ENH: Add support for ATLAS > 3.9.33.
    
    Recent ATLAS combines the previous libraries into two
    
    * libsatlas -- single threaded.
    * libtatlas -- threaded.
    
    This fix is a bit of hack in that ATLAS > 3.9.33 is treated as a new,
    separate library covered by atlas_3_10_info, but the latter derived
    from atlas_info, which treats the cblas, atlas, and atlas_lapack
    libraries separately, so the new info has a bit of repetition.
    
    The alternative would be to rewrite atlas_info, but that can wait
    on a larger cleanup of the build system.
    
    Closes #3774.
```
Before this commit, my system (Fedora 23) does not detect ATLAS and compiles `lapack_lite`. This is confirmed by building numpy without ATLAS
```
BLAS=None LAPACK=None ATLAS=None python setup.py install --user
```
Which does not show the leak. It would be interesting to see if other libraries show the problem. @matthew-brett Could you test on the MAC? It would also be interesting for other folks to try other libraries, like OpenBLAS.

**Comment by bstdenis** [comment] 2016-01-21 14:24
Not sure if this is helpful, but the memory leak also scales with the degree of the polynomial fit. 8th degree polynomial fit ends up using ~11 GB instead of 6.

**Comment by bstdenis** [comment] 2016-01-21 15:30
To confirm, the machine on which I see the memory leak has the following atlas libraries:
libsatlas.so.3.10
libtatlas.so.3.10

While the ones where I do not see the leak have:
libatlas.so.3.0

**Comment by charris** [comment] 2016-01-21 17:19
@bstdenis Thanks for the follow up. This looks like an ATLAS problem, so closing. I'll report on the Fedora bugzilla.

**Closed by charris** 2016-01-21 17:19 UTC
Labels: component: Other, Defect
