### ISSUE TITLE
np.dot returning zero with np.float32, but not with the same arrays with dtype np.float64, and not on all machines/shells

### ISSUE THREAD

**Issue by johncoxon** [numpy/numpy#10584] opened 2018-02-14 11:56 UTC
I'm seeing weird behaviour on two MacBooks Pro compared with my colleague's MacBook Pro.

On my first Mac, running High Sierra 10.13.3, IPython 5.3.0, numpy 1.11.0, and Python 2.7.13, installed using Anaconda:
```
In [2]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
In [3]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
In [4]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
In [5]: np.dot(P02, np.cross(P01,P03))
Out[5]: 0.0
```

On my second Mac, running High Sierra 10.13.3, IPython 5.4.1, numpy 1.13.3, and Python 2.7.14, installed using Anaconda:
```
In [1]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
In [2]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
In [3]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
In [4]: np.dot(P02, np.cross(P01,P03))
Out[4]: 0.0
```

On my colleague's Mac, running High Sierra 10.13.3, IPython 5.4.1, numpy 1.13.1, and Python 2.7.13, installed **not** using Anaconda:
```
In [8]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
In [9]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
In [10]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
In [12]: np.dot(P02, np.cross(P01,P03))
Out[12]: 12604.703
```

On my Mac, running High Sierra 10.13.3, **not using IPython**, numpy 1.13.1, and Python 2.7.14, installed using Anaconda:
```
>>> P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
>>> P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
>>> P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
>>> np.dot(P02, np.cross(P01,P03))
12604.703
```

I have checked that `np.__path__` and `np.__config__.show()` are the same in my IPython and Python interactive shells; they are. My colleague can get `np.dot` to work as expected (the `12604` result) on every machine he's tried. How do I go about debugging this? What might be happening?

**Comment by johncoxon** [comment] 2018-02-14 11:58
I should have noted this in the original post – the code works fine if I don't force the arrays to be `float32`. For example:
```
In [2]: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148])
In [3]: P02 = np.array([-17.63671875,  13.19140625,  18.57519531])
In [4]: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ])
In [5]: np.dot(P02, np.cross(P01,P03))
Out[5]: 12604.703743014355
```

**Comment by matthew-brett** [comment] 2018-02-14 12:08
Do you see any differences in `np.cross(P01,P03)`?

What do you get for `python -c 'import numpy; numpy.show_config()'` ?  Does it differ across your cases (for Anaconda installs)?

I have no idea why IPython enters the mix; is it possible this is not deterministic?

**Comment by johncoxon** [comment] 2018-02-14 12:13
On the IPython and Python shells:
```
In [6]: np.cross(P01,P03)
Out[6]: array([-336.38467791,  478.56201365,   19.33093262])
In [7]: np.__config__.show()
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
```
 and 
```
>>> np.cross(P01,P03)
array([-336.38467791,  478.56201365,   19.33093262])
>>> np.__config__.show()
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda2/include']
```

**Comment by johncoxon** [comment] 2018-02-14 12:24
```
In [1]: P01 = np.array([-336.38467791,  478.56201365,   19.33093262], dtype=np.float32)
   ...: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
   ...: np.dot(P02, P01)
   ...: 
Out[1]: 0.0
```
I would agree with it being an Anaconda bug if it weren't for the fact that I get different results in `python` and `ipython` and both are installed using Anaconda:
```
johns-mbp:~ john$ which python
/anaconda2/bin/python
johns-mbp:~ john$ which ipython
/anaconda2/bin/ipython
```

**Comment by matthew-brett** [comment] 2018-02-14 12:29
I'm guessing that there's a bug somewhere in MKL that is sensitive to memory contents.   I assume you're not loading anything in your IPython profile?  But - in any case - I think Anaconda is your first port of call here.

**Comment by johncoxon** [comment] 2018-02-14 12:31
I don't think I'm loading anything in my IPython profile – how could I go about checking?

**Comment by matthew-brett** [comment] 2018-02-14 12:33
You could create a new blank profile, and confirm that you get the same behavior using that profile:

```
ipython profile create testing
ipython --profile=testing
```

**Comment by johncoxon** [comment] 2018-02-14 13:28
```
IPython profile: testing

In [1]: import numpy as np
   ...: P01 = np.array([-13.73046875, -10.4140625 ,  18.88452148], dtype=np.float32)
   ...: P02 = np.array([-17.63671875,  13.19140625,  18.57519531], dtype=np.float32)
   ...: P03 = np.array([  3.30859375,   1.1015625 ,  30.3034668 ], dtype=np.float32)
   ...: np.dot(P02, np.cross(P01,P03))
   ...: 
Out[1]: 0.0
```
It looks like this isn't the problem, then.

**Comment by matthew-brett** [comment] 2018-02-14 14:35
No - I thought not.  I don't think there's anything we can do on the Numpy side; we don't build those binaries, and the ones we do build, don't seem to have this problem.  Why not try over on the Anaconda support channel?  Please feel free to push it back our way if I'm wrong.

**Comment by jiangzhongshi** [comment] 2018-04-12 18:40
I have the similar issue today. 
```
ipython -c "import numpy as np;f=np.ones(2,dtype=np.float32);print(f.dot(f))"
```
This gives me 0.0

Here is my config
```
In [6]: np.__config__.show()
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhongshi/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhongshi/anaconda/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhongshi/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhongshi/anaconda/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhongshi/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhongshi/anaconda/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhongshi/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhongshi/anaconda/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhongshi/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhongshi/anaconda/include']
```

**Comment by pv** [comment] 2018-05-29 23:53
duplicate of #9758 (which has more info?)

**Comment by charris** [comment] 2018-07-16 04:00
Closing as duplicate. See #9758.

**Closed by charris** 2018-07-16 04:00 UTC
Labels: 57 - Close?, component: numpy.core
