### ISSUE TITLE
genfromtxt with names=True doesn't skip comments

### ISSUE THREAD

**Issue by arkottke** [numpy/numpy#3386] opened 2013-05-31 18:12 UTC
If numpy.genfromtxt() is called with `names=True`, as is the case with numpy.recfromcsv(), then the comment lines are ignored. This is due to the following code block:

``` python
    # Keep on until we find the first valid values
    first_values = None
    try:
        while not first_values:
            first_line = next(fhd)
            if names is True:
                if comments in first_line:
                    first_line = asbytes('').join(first_line.split(comments)[1:])
            first_values = split_line(first_line)
```

Is this the intended behavior? It seems like comments should be read and ignored regardless if `names is True`.

**Comment by bsipocz** [comment] 2019-08-16 03:12
Consider closing, as the comment above says it's the intended behaviour.

**Closed** 2019-08-16 06:24 UTC
Labels: component: numpy.lib

**Comment by rgommers** [comment] 2019-08-16 11:38
thanks @bsipocz. triaging these old issues is quite useful. I'll send you an invite for the triage team, so you can add labels, and close issues yourself if something is clearly fixed or invalid.

**Comment by bsipocz** [comment] 2019-08-16 14:57
I can't commit to do this regularly, but nevertheless I'm trying to do some occasional triaging to upstream packages.

**Comment by bsipocz** [comment] 2019-08-16 19:17
btw, is there a policy written up on labeling?

**Comment by rgommers** [comment] 2019-08-17 00:12
> btw, is there a policy written up on labeling?

Not yet, it's on my TODO list - I actually have a rough draft for SciPy based on our recent triage effort there. So far all your comments have been spot on, so please imagine there's a policy in line with what you did over the past couple of days:)

> I can't commit to do this regularly, but nevertheless I'm trying to do some occasional triaging to upstream packages.

No commitments of course, we're all volunteers (well, almost all)! Your efforts are much appreciated:)
