### ISSUE TITLE
Small error in docstring for np.clip

### ISSUE THREAD

**Issue by HPLegion** [numpy/numpy#16431] opened 2020-05-29 16:53 UTC
Hi everyone :)

I found a small inaccuracy in the docs for np.clip. There it says
> Equivalent to but faster than `np.maximum(a_min, np.minimum(a, a_max))`
https://github.com/numpy/numpy/blob/master/numpy/core/fromnumeric.py#L2039-L2051

but the function actually seems to behave like `np.minimum(a_max, np.maximum(a, a_min))`

To be fair: This is only relevant if the user mixes up the order of the inputs.

```python
import numpy as np

def min_max(a, a_min, a_max):
    return np.minimum(a_max, np.maximum(a, a_min))

def max_min(a, a_min, a_max):
    return np.maximum(a_min, np.minimum(a, a_max))

print(np.clip(4, 5, 2))   # Returns 2
print(min_max(4, 5, 2))   # Returns 2
print(max_min(4, 5, 2))   # Returns 5
```

**Comment by eric-wieser** [comment] 2020-05-29 17:02
Duplicate of #15693

**Comment by eric-wieser** [comment] 2020-05-29 17:03
The lines you link to do not say what you claim they do :)

**Closed by eric-wieser** 2020-05-29 17:03 UTC

**Comment by HPLegion** [comment] 2020-05-30 06:49
Oh dear :eyes:  missing duplicate issues and that it is fixed in the lines I quote... :1st_place_medal: 
Cheers for closing :)
