### ISSUE TITLE
BUG: Binary operations between uint64 and intX scalars results in float64

### ISSUE THREAD

**Issue by jmd-dk** [numpy/numpy#20969] opened 2022-02-01 21:58 UTC
### Describe the issue:

Doing any kind of binary arithmetic operation (e.g. addition, multiplication) between an uint64 scalar and a signed integer scalar results in values which are float64. Is this really intended? I would expect the unsigned value to be cast to a signed representation prior to the actual operation, with the result then being a signed integer.

A small example is provided in the next section. I stress that this behavior is:
* Seen for `np.uint64` but not for `np.uint32`, `np.uint16`, `np.uint8`.
  * Also seen for `np.uintp` (but that's just an alias to `np.uint64`, at least on my machine) and for `np.ulonglong` (which is separate from `np.uint64` but also has an itemsize of 8 bytes, at least on my machine).
* As the signed integer below, a `1` (Python `int`) is used. This can be substituted with e.g. `np.int8`, `np.int16`, `np.int32`, `np.int64`, for the same result.

### Reproduce the code example:

```python
import numpy as np

a = np.array([1, 2, 3], dtype=np.uint64)

b = a + 1          # NumPy uint64 array plus signed integer
print(b, b.dtype)  # uint64 (OK; no cast to signed expected as arrays keep their dtype)

c = a[0] + 1       # NumPy uint64 scalar plus signed integer
print(c, c.dtype)  # float64 (???)
```

### NumPy/Python version information:

1.21.4 3.9.9 (main, Jan  6 2022, 23:52:18) 
[GCC 9.3.0]

**Comment by seberg** [comment] 2022-02-01 22:20
Thanks, will use your title, but this is a duplicate of #20905 (and others), so closing.

**Closed by seberg** 2022-02-01 22:20 UTC
Labels: 00 - Bug
