### ISSUE TITLE
Top bar covers link targets

### ISSUE THREAD

**Issue by madphysicist** [numpy/numpy#18591] opened 2021-03-10 19:40 UTC
When I click on a link with an ID, the link target shows up under the bar. This is not as noticeable for functions, which have a very large title, but here is an extreme example of what happens when I go to the docs for [`np.uint8`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.uint8):

![image](https://user-images.githubusercontent.com/4617010/110687228-e6ff2580-81a5-11eb-8f09-67bd861a1798.png)

I have to scroll up a bit to see the actual link target:

![image](https://user-images.githubusercontent.com/4617010/110687475-2594e000-81a6-11eb-8295-6892e5607423.png)

If this issue is with pydata/pydata-sphinx-theme as #18549 was, I would be more than happy to replicate it there as well.

**Comment by WarrenWeckesser** [comment] 2021-03-10 19:48
I've noticed the same thing--the top bar covers the top of the item I'm interested in reading about.

**Comment by eric-wieser** [comment] 2021-03-10 19:59
Is this https://github.com/pydata/pydata-sphinx-theme/pull/280? Do we just need to update the theme?

**Comment by mattip** [comment] 2021-03-10 21:48
The theme is pinned to the latest version. I think we need to adjust [the margin](https://github.com/pydata/pydata-sphinx-theme/pull/280/files#diff-d7ec2df902c26629189141725c9fee3e0074b05edd09a99e51feb8f8f2f19c0dR120) for our navbar height.

**Comment by melissawm** [comment] 2021-03-11 19:49
I think this is a duplicate of #17741

**Comment by mattip** [comment] 2021-03-11 20:11
The theme released a new version. Worth a try. It also has some new left navbar options.

**Comment by mattip** [comment] 2021-05-18 07:03
Closing, fixed by a newer version of the theme. Please reopen if it still appears for you.

**Comment by WarrenWeckesser** [comment] 2021-05-18 16:09
Should the new version have already taken effect at https://numpy.org/doc/stable/reference/index.html?  I still see the top bar covering the start of the documentation, but only when the ilnk uses an internal link.

For example,  if you search for `average`, the first link is [`https://numpy.org/doc/stable/reference/generated/numpy.average.html?highlight=average#numpy.average`](https://numpy.org/doc/stable/reference/generated/numpy.average.html?highlight=average#numpy.average).  Note the internal link `#numpy.average` in the URL.  When I go to that page (using Firefox 88.0), the top bar still covers the top of the documentation, up to and including the line that shows the signature of `average`.   If I remove the internal link and go to [`https://numpy.org/doc/stable/reference/generated/numpy.average.html?highlight=average`](https://numpy.org/doc/stable/reference/generated/numpy.average.html?highlight=average), the top of the documentation is not covered, and it looks the way I would expect it to.

**Comment by madphysicist** [comment] 2021-05-18 16:33
@mattip I'm still seeing the same behavior as @WarrenWeckesser describes. I don't think the issue has been fixed. Please reopen.

**Comment by mattip** [comment] 2021-05-19 04:20
We have not rebuilt the stable docs with the new theme. I was refering to the [devdocs](https://numpy.org/devdocs/reference/generated/numpy.average.html?highlight=average#numpy.average) where the behaviour is better.

**Comment by WarrenWeckesser** [comment] 2021-05-19 12:27
Ah, OK.

**Closed by WarrenWeckesser** 2021-05-19 12:27 UTC
Labels: 04 - Documentation

**Comment by madphysicist** [comment] 2021-05-21 07:11
@mattip, @WarrenWeckesser Thanks. Any idea when the devdocs will become stable docs?

**Comment by mattip** [comment] 2021-05-21 13:22
Any idea when the devdocs will become stable docs?
> After the next release, which should be in a few months
