### ISSUE TITLE
BUG: Evaluation of IS operator for dtype=bool is inconsistent to standard Python

### ISSUE THREAD

**Issue by PhilippWillms** [numpy/numpy#23199] opened 2023-02-11 20:35 UTC
### Describe the issue:

Using the smart numpy way to initialize an array with 0 or 1 for **boolean** type of values reveals inconsistent behavior in evaluation with ALL operator. As shown in the reproduction example, the ALL condition to cehck for "is False" cannot be handled corectly.

### Reproduce the code example:

```python
import numpy as np
if __name__ == "__main__":
    print("Standard Python array with boolean")
    array2_normal = [False, False, False]
    print(array2_normal)
    print("Check for all values to be False ...")
    print(all(array2_normal[k] is False for k in range(3)))
    print("-------------------------------")
    print("Numpy array with IS")    
    array2_numpy = np.zeros(3, dtype=bool)
    print(array2_numpy)
    print("Check for all values to be False ...")
    print(all(array2_numpy[k] is False for k in range(3)))
    print("-------------------------------")
    print("Numpy array with ==")    
    array2_numpy = np.zeros(3, dtype=bool)
    print(array2_numpy)
    print("Check for all values to be False ...")
    print(all(array2_numpy[k] == False for k in range(3)))
```

### Error message:

```shell
Standard Python array with boolean
[False, False, False]
Check for all values to be False ...
True
-------------------------------
Numpy array with IS
[False False False]
Check for all values to be False ...
False
-------------------------------
Numpy array with ==
[False False False]
Check for all values to be False ...
True
```

### Runtime information:

Python version: 3.8.13
Numpy version: 1.23.5

### Context for the issue:

There is a workaround available, i.e. using == comparison in the ALL condition instead of IS,.
However, it would be good to ensure consistency in future versions.

**Comment by mattip** [comment] 2023-02-12 06:46
NumPy boolean scalars are not python scalars. As you point out, they compare equal but are not identical.
```
>>> np.bool_(0) is False
False
```

This does work:
```
>>> array2_numpy = np.zeros(3, dtype=bool)
>>> all(array2_numpy[k] is np.bool_(0) for k in range(3))
True

**Comment by PhilippWillms** [comment] 2023-02-14 19:31
@mattip Ok. I can remember that `np.bool` was removed at some upgrade. Is that still robust for future?

**Comment by mattip** [comment] 2023-02-14 19:50
`np.bool` was an alias for `bool`, and was removed to keep it from getting confused with [`np.bool_`](https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.bool_), which is a different thing. If you are asking if we will ever remove `np.bool_`: I would not really want to predict the future. However python's `bool` inherits from `int`, which is not consistent with the data API spec for the bool [numeric types](https://data-apis.org/array-api/latest/API_specification/data_types.html#data-type-categories) Replacing `np.bool_` with python `bool` would require that CPython make its `bool` no longer inherit from `int`.

**Comment by rgommers** [comment] 2023-02-17 13:59
The question was answered, and this is not a bug. So I'll close the issue.

> Replacing `np.bool_` with python `bool` would require that CPython make its `bool` no longer inherit from `int`.

I don't think that will ever happen. A possible future `np.bool` will have to be a proper numpy dtype, so it won't be identical to Python's `bool`.

**Closed by rgommers** 2023-02-17 13:59 UTC
Labels: 53 - Invalid
