### ISSUE TITLE
Raise warning when condition number is too high?

### ISSUE THREAD

**Issue by astrojuanlu** [numpy/numpy#3755] opened 2013-09-16 16:42 UTC
In certain cases, when trying to solve singular linear systems, no feedback is given about the singular nature of the solution. For example:

```
>>> import numpy
>>> from numpy import array
>>> from numpy.linalg import solve
>>> A=array([[1,2,3],[4,5,6],[7,8,9]])
>>> b=array([15,15,15])
>>> solve(A,b)
array([-39.,  63., -24.])
```

But, on other cases:

```
>>> C=array([[1,1,1],[1,1,1],[1,1,1]])
>>> x=solve(C,b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.local/lib/python3.3/site-packages/numpy/linalg/linalg.py", line 328, in solve
    raise LinAlgError('Singular matrix')
numpy.linalg.linalg.LinAlgError: Singular matrix
```

This issue was raised here:

http://web.archive.org/liveweb/http://www.walkingrandomly.com/?p=5092

A warning based on the condition number of the matrix has been suggested as a possible solution.

**Comment by ilayn** [comment] 2016-08-04 10:40
I think this issue is overlooked in the sense of what to do when there is a catch. But the problem is that numpy does not catch it. Here is again the same example 

```
A = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
b = np.array([[15,15,15]]).T
x = np.linalg.solve(A,b)
print( A @ x )
```

gives back `b` with no warning whatsoever. However `numpy.linalg.matrix_rank(A)` gives correctly `2`. This numerical silencing, or even worse not evaluating condition number (or other ill-conditioned awareness method) is quite against *production-readiness* of the code because there is no warning to catch. This should not go unnoticed for many, many reasons which I'm sure you all are aware. The official response is now then *check your matrices yourself* ? 

The blogpost still exists at [Mike Croucher's blog](http://www.walkingrandomly.com/?p=5092). The solution has changed from `[-39,  63, -24]` to `[ 3 , -21 , 18 ]` between versions though.

**Comment by rkern** [comment] 2016-08-04 16:08
@ilayn No, the official response is that `numpy.linalg.solve()` ought to be rewritten to estimate the condition number at the same time as the solution and issue a warning when it exceeds a tolerance. This issue is still open; it has not been closed. If you would like to contribute your time to solving the problem, you have everyone's blessing to do so.

**Comment by ilayn** [comment] 2016-08-04 19:19
@rkern argh, I was already optimizing Lyapunov and Riccati solvers (can be found on my harold repository - not fully polished yet). I was afraid that you would say that :) 

Anyways I can give it a try but I am definitely not an expert on numerical algorithms. I can do some LU based code for square matrices but sounds pretty scary I have to admit given the size of the user base. 

How professional does it have to be? That is to say, do we have a ill-conditioned example suite or something like that to test ?

**Comment by rkern** [comment] 2016-08-04 22:41
LAPACK already has the routine `[DZ]GESVX` that will do this, so you don't have to implement any new algorithms. "All" you need to do is hook it up in place of `[DZ]GESV` which is currently the routine that is used, and then doing the Python-side stuff to add a new condition number tolerance parameter to `np.linalg.solve()`'s signature, do the checking, and issue the warning. We include C translations of the LAPACK Fortran sources for the subset of subroutines that we use (and their dependencies) so that numpy can be built standalone without a Fortran compiler. Since you will be replacing one such subroutine, that subset will change, and the C translations will need to be regenerated. I'm not sure how well documented or automated that process is.

It's boring, unexciting work, frankly, but I will thank you heartily if you do it!

**Comment by ilayn** [comment] 2016-08-05 15:31
Except the C translation part I think I can cover some distance. Unfortunately I have no idea about that translation part.

**Comment by ilayn** [comment] 2016-11-06 10:08
@rkern After a few months, I've covered some distance on SciPy side with the usage of `f2py` and exposing the "expert" routines of the solvers, see https://github.com/scipy/scipy/pull/6693. Does this help in any way for the C part you have mentioned or is there a need for an explicit f2c translation that is done manually? At least the Python function can be used as a template for the final version. 

I can imagine that the translation can introduce subtle bugs and performance differences. Is it really the case ?

**Comment by mattip** [comment] 2023-01-11 17:58
It has been more than 6 years since this was last commented on. Does anyone want to pick up the idea of 
- Adding `[DZ]GEMVX` functions instead of `[DZ]GEMV`
- Add an implementation for lapack_lite
- Add tests

If not we should close it.

**Comment by ilayn** [comment] 2023-01-11 20:50
Just to mention that SciPy does this already for quite some time. It turns out `gesvx` is too slow and after `getrf` a call to `gecon` is done to shave some time.

**Comment by InessaPawson** [comment] 2023-03-05 23:37
Since no one had the bandwidth to implement the proposed for the past 5+ years, I’m closing this issue for now with a label “Good idea”.  Feel free to reopen it, if you’d like to work on it.

**Closed by InessaPawson** 2023-03-05 23:37 UTC
Labels: component: numpy.linalg, Proposal, 64 - Good Idea
