### ISSUE TITLE
Numpy returning a negative norm with np.dot()

### ISSUE THREAD

**Issue by pnugues** [numpy/numpy#10070] opened 2017-11-23 15:32 UTC
I have a very strange behavior with the np.dot() function. When computing:
np.dot(vector, vector)
I get a negative value, -3.68935e+19, with the array below:
[-0.95558429 -0.79491568 -0.34074336 -0.31960416 -0.50112027 -0.14804825
  0.83092237 -1.04872239 -0.06821966  0.95099533  0.23211323 -0.08363034
 -0.84720689  0.53866994  0.33275896  0.18167147  0.42636991 -0.90105802
  1.03073204  0.35682318  0.753968   -1.25347698 -0.15214275  0.01669976
  0.61865449  0.5806967   1.33312941  0.20144169  0.11802452 -0.29711285
 -0.29448548  1.11324942  0.1951234  -0.20648302 -0.28658506  1.09960926
 -0.36813557 -0.78195006  0.57407916  0.15383098  0.30026323  1.03336143
  0.67244434  0.00452838  0.80118829 -0.23254229  0.66596371  0.15719646
  0.40883717  0.40989453 -1.20930338  0.94520253  0.79906452 -0.22432771
  0.97588438 -1.72914338  0.05262739 -0.54656118  0.30642688  1.95097971
  0.31468016 -0.37122983 -0.77826643  0.06892334 -1.80932391 -0.50851583
 -0.37202829 -1.51686203  0.74873447  0.01304383 -0.19901061 -1.07052517
  0.75449711 -0.21430047  0.67405069  0.30016151 -0.54680014  1.19146216
  0.36444184  0.03734953 -0.32377601  0.56825429  0.81616706 -0.8266384
  1.17172229 -0.30052993  1.3422761  -0.33125407  1.96316791 -0.7671603
 -0.51845783 -1.07401311  0.47158152 -0.20735571  0.62432927  0.3078284
  0.11610977 -1.04085588 -0.97068292  1.1042937 ]

I am using the latest version of Anaconda3 (5.0.1) on macOS 10.13.1
The dtype of the array is float32. The problem disappears when converting it to float or np.float64.

**Comment by charris** [comment] 2017-11-23 15:53
Duplicate of #9758. Seems to be an MKL on Mac problem. Someone (you?) should report this to anaconda.

**Closed by charris** 2017-11-23 15:53 UTC

**Comment by pv** [comment] 2017-11-23 16:33
Consider reportig this to anaconda --- looks like a problem in the 
linear algebra library they ship.

**Comment by mingwandroid** [comment] 2017-11-23 17:17
Reproduction attempt:

1. Installation from `Terminal`:

```
curl -SLO https://repo.continuum.io/archive/Anaconda3-5.0.1-MacOSX-x86_64.sh
bash Anaconda3-5.0.1-MacOSX-x86_64.sh -bfp /tmp/a3
. /tmp/a3/bin/activate
```

2. Get list of packages:

```
conda list --show-channel-urls
# packages in environment at /tmp/a3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  5.0.1            py36h6e48e2d_1    defaults
anaconda-client           1.6.5            py36h04cfe59_0    defaults
anaconda-navigator        1.6.9            py36ha31b149_0    defaults
anaconda-project          0.8.0            py36h99320b2_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
asn1crypto                0.22.0           py36hb705621_1    defaults
astroid                   1.5.3            py36h1333018_0    defaults
astropy                   2.0.2            py36hf79c81d_4    defaults
babel                     2.5.0            py36h9f161ff_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h20fa61d_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.0.0            py36h8fcea71_0    defaults
bokeh                     0.12.10          py36hfd5be35_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1            py36hbd380ad_0    defaults
bzip2                     1.0.6                h92991f9_1    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2017.7.27.1      py36hd973bb6_0    defaults
cffi                      1.10.0           py36h880867e_1    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.4.0            py36h13b7e56_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
conda                     4.3.30           py36h173c244_0    defaults
conda-build               3.0.27           py36hb78d8cd_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
cryptography              2.0.3            py36h22d4226_1    defaults
curl                      7.55.1               h7601780_3    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.26.1           py36hd51f8eb_0    defaults
cytoolz                   0.8.2            py36h290905f_0    defaults
dask                      0.15.3           py36hc3ad2d6_0    defaults
dask-core                 0.15.3           py36hc0be6b7_0    defaults
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.10.22              h50d9ad6_0    defaults
decorator                 4.1.2            py36h69a1b52_0    defaults
distributed               1.19.1           py36h4ae75d2_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.4                h8f26bf8_1    defaults
fastcache                 1.0.2            py36h8606a76_0    defaults
filelock                  2.0.12           py36h0d0b4fb_0    defaults
flask                     0.12.2           py36h5658096_0    defaults
flask-cors                3.0.3            py36h7387b97_0    defaults
freetype                  2.8                  h143eb01_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             hb0f4f8b_2    defaults
gevent                    1.2.2            py36ha70b9d6_0    defaults
glib                      2.53.6               ha08cb78_1    defaults
glob2                     0.5              py36h12393a9_0    defaults
gmp                       6.1.2                h4a9834d_0    defaults
gmpy2                     2.0.8            py36h7ef02cb_1    defaults
greenlet                  0.4.12           py36hf09ba7b_0    defaults
h5py                      2.7.0            py36h6400cee_1    defaults
hdf5                      1.10.1               h6090a45_0    defaults
heapdict                  1.0.0            py36h27a9ac6_0    defaults
html5lib                  0.999999999      py36h79312fd_0    defaults
icu                       58.2                 hea21ae5_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
imageio                   2.2.0            py36h5e01289_0    defaults
imagesize                 0.7.1            py36h3495948_0    defaults
intel-openmp              2018.0.0             h68bdfb3_7    defaults
ipykernel                 4.6.1            py36h3208c25_0    defaults
ipython                   6.1.0            py36hf612aae_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.0.0            py36h24d3910_0    defaults
isort                     4.2.15           py36hceb2a01_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.3              py36h1986823_0    defaults
jedi                      0.10.2           py36h6325097_0    defaults
jinja2                    2.9.6            py36hde4beb4_1    defaults
jpeg                      9b                   haccd157_1    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0            py36h598a6cc_0    defaults
jupyter_client            5.1.0            py36hf6c435f_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.3.0            py36h93810fe_0    defaults
jupyterlab                0.27.0           py36hd3092eb_2    defaults
jupyterlab_launcher       0.4.0            py36h93e02e9_0    defaults
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                hd939716_3    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 h99df5da_5    defaults
libpng                    1.6.32               hce72d48_2    defaults
libsodium                 1.0.13               hba5e272_2    defaults
libssh2                   1.8.0                h1218725_2    defaults
libtiff                   4.0.8                h8cd0352_9    defaults
libxml2                   2.9.4                hbd0960b_5    defaults
libxslt                   1.1.29               h95a2935_5    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.1.0            py36h8179fc0_0    defaults
lzo                       2.10                 hb6b8854_1    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.1.0            py36h5068139_0    defaults
mccabe                    0.6.1            py36hdaeb55d_0    defaults
mistune                   0.7.4            py36hccd6237_0    defaults
mkl                       2018.0.0             h5ef208c_6    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mpc                       1.0.3                hc455b36_4    defaults
mpfr                      3.1.5                h7fa3772_1    defaults
mpmath                    0.19             py36h9185fea_2    defaults
msgpack-python            0.4.8            py36h46767b2_0    defaults
multipledispatch          0.4.9            py36hc5f92b5_0    defaults
navigator-updater         0.1.0            py36h7aee5fb_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.0                  ha932d30_1    defaults
networkx                  2.0              py36hefccab9_0    defaults
nltk                      3.2.4            py36h27d1ea0_0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.0.0            py36h462289e_2    defaults
numba                     0.35.0              np113py36_6    defaults
numexpr                   2.6.2            py36h0f4f1da_1    defaults
numpy                     1.13.3           py36h2cdce51_0    defaults
numpydoc                  0.7.0            py36he54d08e_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.44             py36ha08bf50_0    defaults
openpyxl                  2.4.8            py36he899640_1    defaults
openssl                   1.0.2l               h57f3a61_2    defaults
packaging                 16.8             py36he5e8135_0    defaults
pandas                    0.20.3           py36hd6655d8_2    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   10.3.1           py36hd33c240_0    defaults
pathlib2                  2.3.0            py36h877a6d8_0    defaults
patsy                     0.4.1            py36ha1b3fa5_0    defaults
pcre                      8.41                 h29eefc5_0    defaults
pep8                      1.7.0            py36hc268eb1_0    defaults
pexpect                   4.2.1            py36h3eac828_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    4.2.1            py36h0263179_0    defaults
pip                       9.0.1            py36hbd95645_3    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
ply                       3.10             py36h10e714e_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
psutil                    5.4.0            py36ha052210_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.4.34           py36hecf431b_1    defaults
pycodestyle               2.3.1            py36h83e8646_0    defaults
pycosat                   0.6.2            py36h1486600_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h72f2894_1    defaults
pycurl                    7.43.0           py36hdb90038_3    defaults
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    1.7.4            py36hdee9077_0    defaults
pyodbc                    4.0.17           py36h5478161_0    defaults
pyopenssl                 17.2.0           py36h5d7bf08_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
pytables                  3.4.2            py36hfbd7ab0_2    defaults
pytest                    3.2.1            py36h9963153_1    defaults
python                    3.6.3                h6804ab2_0    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h7fe2238_6    defaults
pytz                      2017.2           py36h2e7dfbc_1    defaults
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.2           py36h087ffad_2    defaults
qt                        5.6.2               h9975529_14    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.3.1            py36h16bb863_0    defaults
readline                  7.0                  h81b24a6_3    defaults
requests                  2.18.4           py36h4516966_1    defaults
rope                      0.10.5           py36h5764ad1_0    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
scikit-image              0.13.0           py36h398857d_1    defaults
scikit-learn              0.19.1           py36hffbff8c_0    defaults
scipy                     0.19.1           py36h3e758e1_3    defaults
seaborn                   0.8.0            py36h74df97e_0    defaults
setuptools                36.5.0           py36h2134326_0    defaults
simplegeneric             0.8.1            py36he5b5b09_0    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.5.3            py36he9c3ed6_0    defaults
sortedcontainers          1.5.7            py36ha982688_0    defaults
sphinx                    1.6.3            py36hcd1b3e7_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.4            py36h908396f_0    defaults
sqlalchemy                1.1.13           py36h156b851_0    defaults
sqlite                    3.20.1               h900c3b0_1    defaults
statsmodels               0.8.0            py36h9c68fc9_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.6              py36h656782e_0    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.7                hcdce994_1    defaults
toolz                     0.8.2            py36h7b95164_0    defaults
tornado                   4.5.2            py36h468dda9_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typing                    3.6.2            py36haa2d9ef_0    defaults
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.4                h4cb4dde_1    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.12.2           py36h168efa1_0    defaults
wheel                     0.29.0           py36h3597b6d_1    defaults
widgetsnbextension        3.0.2            py36h91f43ea_1    defaults
wrapt                     1.10.11          py36hc29e774_0    defaults
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.2            py36h3736301_0    defaults
xlwings                   0.11.4           py36hc75f156_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.3                ha24016e_1    defaults
yaml                      0.1.7                hff548bb_1    defaults
zeromq                    4.2.2                h131e0f7_1    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               h60db283_1    defaults
```

3. Python code (tests a large range of array sizes):

```
import numpy as np
from numpy import sqrt, float32, array
import random

for a in range(1, 10000):
    npa = np.array([random.uniform(-1.0/a,1.0/a) for _ in range(a)], dtype=float32)
    assert np.dot(npa,npa) >= 0.0
```

**Comment by pnugues** [comment] 2017-11-23 21:14
I tried the code you suggested and I printed the values. The bug only shows in Jupyter notebooks. See below:

```import numpy as np
from numpy import sqrt, float32, array
import random

for a in range(1, 10000):
    npa = np.array([random.uniform(-1.0/a,1.0/a) for _ in range(a)], dtype=float32)
    print(npa, np.dot(npa,npa))
    assert np.dot(npa,npa) >= 0.0

[-0.32202038] 0.103697
[ 0.09881387 -0.00417533] 0.0
[ 0.13308252 -0.24686584  0.16380705] 0.0
[ 0.11569552 -0.13192534  0.2496305  -0.07957345] 2.0
[ 0.01183388  0.08716223  0.01115432 -0.1532491   0.14675535] 0.0
[ 0.02153591  0.16175529 -0.15811746  0.08009007  0.02548271  0.11089136] 0.0
[ 0.09288566 -0.09793927 -0.09029671  0.09869239 -0.10522863  0.03654106
 -0.03300986] 0.0
[ 0.08138641  0.04001122  0.07273234  0.06319164 -0.00897063 -0.08978584
  0.09409402 -0.05515618] 0.0
[ 0.01510452 -0.01699    -0.02005721  0.00985001 -0.02425907 -0.03851245
  0.0023487  -0.02577852  0.09738041] 0.0
[ 0.04292577 -0.06403535 -0.01305467 -0.04941495 -0.0689061   0.06612536
  0.03450453 -0.01142765 -0.0869602   0.00417785] -1.0842e-19

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-2-a1cfe9f1f81f> in <module>()
      6     npa = np.array([random.uniform(-1.0/a,1.0/a) for _ in range(a)], dtype=float32)
      7     print(npa, np.dot(npa,npa))
----> 8     assert np.dot(npa,npa) >= 0.0

AssertionError: 
```
