### ISSUE TITLE
dtype richcompare doesn't respect protocol

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#5345] opened 2014-12-03 14:58 UTC
When a type's `__eq__` (or `tp_richcompare` in C) doesn't understand the other type, it should return NotImplemented so that the other type's `__eq__` has a chance to be called. Unfortunately, NumPy's ArrayDesrc doesn't respect that convention and raises TypeError instead, making comparisons fragile:

```
>>> import numpy as np
>>> class A(object):
...     def __eq__(self, other):
...         return True
... 
>>> dt = np.dtype('i8')
>>> A() == dt
True
>>> dt == A()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type not understood
```

It is generally considered bad practice to raise TypeError in a comparison method, and can prevent advanced uses: such as defining a custom type comparable with ArrayDescr, or simply mixing ArrayDescr with other types in e.g. a dictionary.

Indeed let's say I use the standard `lru_cache`, then hash collisions can produce unwanted errors because of the dictionary used internally comparing the keys:

```
>>> @functools.lru_cache()
... def f(x): return str(x)
... 
>>> 
>>> class A(object):
...   def __hash__(self):   
...      return hash(dt)
... 
>>> f(dt)
'int64'
>>> f(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/34/lib/python3.4/functools.py", line 446, in wrapper
    link = cache_get(key)
TypeError: data type not understood
```

**Comment by stefansjs** [comment] 2019-06-27 18:58
Ouch, I just found this out by trying to put a dtype into a type that wants to be hashable. Thanks for the clear writeup! I understand why equality is violates the python API, but couldn't hash be fixed? 

I'm imagining
- if you compare equivalent to a builtin type, return the hash for that type instead of yourself.
- if you are some kind of object/array type hash your string description, plus some alignment info

I can definitely see an argument for hashing dtypes differently from builtin types even though the equality function would return true in that case (which would help me immensely for my use case). In this case, maybe you could return the hash of immutable parameters, like byte order, alignment, size, and builtin type used to construct you. Is this reasonable?

Further, as a workaround, for my custom type, is it sufficient to do something like this?
```
def hash_dtype(np_dtype):
    """ Provides a stable hash for dtypes by hashing some (but not all) properties """
    hash_properties = (np_dtype.type, np_dtype.byteorder, np_dtype.alignment, np_dtype.str)
    return hash(hash_properties)
```

**Comment by seberg** [comment] 2021-02-24 20:33
Closing this as a duplicate of gh-7242 (both issues have quite a lot of discussion).

**Closed by seberg** 2021-02-24 20:33 UTC
