### ISSUE TITLE
Numpy FFT precision makes phase calculations that aren't reasonable

### ISSUE THREAD

**Issue by beick3** [numpy/numpy#19271] opened 2021-06-17 20:41 UTC
I generate a signal consisting of two superimposed sine waves. I perform an FFT using np.fft.fft, then find the phase using np.angle. The precision of the calculations makes the phase plot look effectively like white noise. Code: 

```
import numpy as np
import matplotlib.pyplot as plt

def fftCalcFullPrecision(sig, L):
    Y=np.fft.fft(sig)
    phase=np.angle(Y,deg=True)
    P2=np.abs(Y)/L
    P1=P2[0:int(L/2)]
    phase=phase[0:int(L/2)]
    P1[1:]=2*P1[1:]
    return P1, phase

#Generate a sample frequency
fs=500

#Generate a series representing times of samples from 0 to 15 seconds
#sampled every 1/fs seconds
t=np.arange(0,15,1/fs)

#Generate the sampled signal containing 2 superimposed sine waves
sig=np.sin(2*np.pi*t)+np.sin(2*np.pi*21*t)
L=len(sig)

#Generate the frequency array for plotting the FFT
f=fs*np.arange(0,int(L/2))/L

fftValsHP,phaseHP=fftCalcFullPrecision(sig, L)

plt.figure()
plt.subplot(2,1,1)
plt.plot(f,fftValsHP)
plt.title('amplitude spectrum using full precision')
plt.subplot(2,1,2)
plt.plot(f,phaseHP)
plt.title('phase using full precision')

```
The generated plot is here:
![phaseFullPrecision](https://user-images.githubusercontent.com/25833894/122468970-02868300-cf82-11eb-9972-7b484a64183d.png)

If I round off the values generated by np.fft.fft that are less than 1e-8 (e.g., effectively zero), then I get much more reasonable phase plots:

```
def fftCalc(sig, L):
    Y=np.fft.fft(sig)
    Y2=np.copy(Y)
    real=np.real(Y2)
    imag=np.imag(Y2)
    real[np.argwhere(np.abs(real)<1e-8)]=0
    imag[np.argwhere(np.abs(imag)<1e-8)]=0
    phase=np.arctan2(imag,real)
    P2=np.abs(Y)/L
    P1=P2[0:int(L/2)]
    phase=phase[0:int(L/2)]
    P1[1:]=2*P1[1:]
    return P1, phase

#Generate a sample frequency
fs=500

#Generate a series representing times of samples from 0 to 15 seconds
#sampled every 1/fs seconds
t=np.arange(0,15,1/fs)

#Generate the sampled signal containing 2 superimposed sine waves
sig=np.sin(2*np.pi*t)+np.sin(2*np.pi*21*t)

L=len(sig)

#Generate the frequency array for plotting the FFT
f=fs*np.arange(0,int(L/2))/L

fftVals,phaseRounded=fftCalc(sig,L)

plt.figure()
plt.subplot(2,1,1)
plt.plot(f,fftVals)
plt.title('amplitude using effectively zero')
plt.subplot(2,1,2)
plt.plot(f,phaseRounded)
plt.title('phase using effectively zero')
```

![PhaseRounding](https://user-images.githubusercontent.com/25833894/122469217-4b3e3c00-cf82-11eb-9074-6caa5ee84370.png)

I believe the precision in the values generated by np.fft.fft is causing the issue where, for example 1e-13/1e-15 is a fairly large number, even though they are both effectively zero.

**Comment by charris** [comment] 2021-06-17 21:54
You don't have a signal. You need a fairly smooth spectrum over the region you want to determine the phase over. It also helps if there is a natural center to the data before the fft, a region of stationary phase, for instance, as you get from autocorrelation.

**Comment by mreineck** [comment] 2021-06-18 07:37
> I believe the precision in the values generated by np.fft.fft is causing the issue where, for example 1e-13/1e-15 is a fairly large number, even though they are both effectively zero.

Given your input signal (amplitude of 1 and a length of several thousand samples), numerical noise of that magnitude is expected after a double-precision FFT. I don't know of any approaches which can reduce this significantly (apart from using higher-precision data types).

**Comment by beick3** [comment] 2021-06-18 21:30
> 
> 
> You don't have a signal. You need a fairly smooth spectrum over the region you want to determine the phase over. It also helps if there is a natural center to the data before the fft, a region of stationary phase, for instance, as you get from autocorrelation.

What do you mean I don't have a signal? My signal is defined in the variable signal as two sine waves added together. One with frequency 1 Hz, one with frequency 21 Hz. The second phase plot I show is along the lines of what I would expect...the phase isn't correct because I didn't window the signal appropriately. The first phase plot I show doesn't make any sense, and is a product of the extreme precision of the FFT calculation, which goes away if I force numbers that are effectively zero to be true zeros.

**Comment by charris** [comment] 2021-06-18 21:43
> which goes away if I force numbers that are effectively zero to be true zeros.

In other words, no signal. Without windowing, whether or not you see the sinc function depends on the sampling, and if that is what you were seeing, it would roll off. What it the plot looks like is roundoff error. Yes, the fft has roundoff error. What the phase will look like when there is signal will depend on the choice of center for the original data. Note the you need to fold the data around the center to account for aliasing.

**Comment by seberg** [comment] 2021-12-20 22:39
Sounds like this is all expected behaviour (at least within normal numerical precision), so closing.  (If you are sure otherwise, please comment.)

**Closed by seberg** 2021-12-20 22:39 UTC
