### ISSUE TITLE
`array.tobytes` seems to change leading bits of large uint64 value.

### ISSUE THREAD

**Issue by qiuxiafei** [numpy/numpy#18815] opened 2021-04-20 05:38 UTC
numpy array with large (but valid) uint64 value inside may cause incorrect `tobytes` output.

### Reproducing code example:

If there's only large int in array, it's OK, both the `tobytes` output and `new_data` created via `frombuffer`.
```python
import numpy as np
data = np.array([10446744073709551615]).astype(np.uint64)
print(data.tobytes().hex())
new_data = np.frombuffer(data.tobytes())
print(data)
```
The output looks like:
```
ffffdfc4624afa90
[10446744073709551615]
```
But when another number is add to the array, it goes wrong:
```python
import numpy as np
data = np.array([1, 10446744073709551615]).astype(np.uint64)
print(data.tobytes().hex())
new_data = np.frombuffer(data.tobytes())
print(data)
```
And the output is:
```
01000000000000000000e0c4624afa90
[                   1 10446744073709551616]
```
It seems that the leading bits were changed. And the `new_data` has different content with `data`.

### NumPy/Python version information:
Python: 3.6.8
Numpy: 1.19.5

**Comment by qiuxiafei** [comment] 2021-04-20 06:05
And I found that if the int `1` is wrapped with `np.uint64`, it gets right.
```python
import numpy as np
data = np.array([np.uint64(1), 10446744073709551615]).astype(np.uint64)
print(data.tobytes().hex())
new_data = np.frombuffer(data.tobytes())
print(data)
```
Output:
```
0100000000000000ffffdfc4624afa90
[                   1 10446744073709551615]
```

Am I missing any key parts of numpy ?

**Comment by matthew-brett** [comment] 2021-04-20 08:04
Ouch, yes, I see the problem.   The summary is this: 

```
import numpy as np

print('2^63 alone:', np.array([2 ** 63]))
print('2^63 and 0:', np.array([2 ** 63, 0]))
print('2^63-1 and 0:', np.array([2 ** 63 -1, 0]))
print('2^63 and 2^63:', np.array([2 ** 63, 2 ** 63]))
print('2^63 and 2^64:', np.array([2 ** 63, 2 ** 64]))
print('2^63 and 2^63-1:', np.array([2 ** 63, 2 ** 63-1]))
```

This gives:

```
2^63 alone: [9223372036854775808]
2^63 and 0: [9.22337204e+18 0.00000000e+00]
2^63-1 and 0: [9223372036854775807                   0]
2^63 and 2^63: [9223372036854775808 9223372036854775808]
2^63 and 2^64: [9223372036854775808 18446744073709551616]
2^63 and 2^63-1: [9.22337204e+18 9.22337204e+18]
```

Numpy makes a floating point array, instead of an integer array, from integers >= 2 ^^ 63, but this apppears to be true only when:

* There is more than one value in the input list
* One of those values is less than 2 ** 63

I must say, I found that very surprising ...

**Comment by matthew-brett** [comment] 2021-04-20 08:23
Refining a little, showing dtypes:

```
import numpy as np

def aas(desc, inp):
    r = np.array(inp)
    print(f'{desc}: {r}; dtype {r.dtype}')

aas('2^63 alone:', [2 ** 63])
aas('2^63 and 0:', [2 ** 63, 0])
aas('2^63-1 and 0:', [2 ** 63 -1, 0])
aas('2^63 and 2^63:', [2 ** 63, 2 ** 63])
aas('2^63 and 2^64:', [2 ** 63, 2 ** 64])
aas('2^63 and 2^64-1:', [2 ** 63, 2 ** 64-1])
aas('2^63 and 2^63-1:', [2 ** 63, 2 ** 63-1])
```

This gives:

```
2^63 alone:: [9223372036854775808]; dtype uint64
2^63 and 0:: [9.22337204e+18 0.00000000e+00]; dtype float64
2^63-1 and 0:: [9223372036854775807                   0]; dtype int64
2^63 and 2^63:: [9223372036854775808 9223372036854775808]; dtype uint64
2^63 and 2^64:: [9223372036854775808 18446744073709551616]; dtype object
2^63 and 2^64-1:: [ 9223372036854775808 18446744073709551615]; dtype uint64
2^63 and 2^63-1:: [9.22337204e+18 9.22337204e+18]; dtype float64
```

**Comment by qiuxiafei** [comment] 2021-04-20 09:43
Thanks for your reply @matthew-brett , now I understand why my work-around works. By the way, is this behavior by design?

**Comment by matthew-brett** [comment] 2021-04-20 10:34
I don't know - but I am finding it hard to see what the design would be :)

**Comment by charris** [comment] 2021-04-20 12:34
The problem is that `2 ** 63 - 1` is converted as int64 and `2 ** 63` as uint64 and the combination leads to float64. This case can be fixed by specifying the dtype, This is a numpy wart.

**Closed** 2021-04-21 01:40 UTC

**Comment by matthew-brett** [comment] 2021-04-21 08:38
@charris - do you think there is any way of - er - doing some surgery on this wart?

**Comment by charris** [comment] 2021-04-21 13:11
@matthew-brett Given the NumPy promotion  rules, it isn't easy. C promotes signed/unsigned combinations to unsigned of same precision, NumPy promotes to the next higher precision signed that can represent the unsigned. Since there is no higher precision signed integer type after int64 there is really nowhere to go.

**Comment by seberg** [comment] 2021-04-21 14:36
We could attempt surgery by never going to unsigned by default (rather go to object, or an error) – that would sidesteps the promotion to float unless the input is actually already a numpy uint64.  It wouldn't actually "fix" it maybe, but it would hide it away much better.
Before that, we may need a `dtype="fallback-to-object"` type of switch for `np.array` though.

The other thing is that especially on windows we toggle between `int32` and `int64` based on input size, I am not sure if we should attempt to operate that at the same time, but that would make matters more complex.
