### ISSUE TITLE
BUG: Drastic memory usage increase in recent builds

### ISSUE THREAD

**Issue by larsoner** [numpy/numpy#22233] opened 2022-09-08 21:29 UTC
### Describe the issue:

Recently in MNE-Python our CIs started dying due to memory overconsumption on both

- Linux: https://github.com/mne-tools/mne-python/runs/8253676336?check_suite_focus=true
- Windows: https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=21722&view=logs&j=305851a9-a7bb-55db-0042-7e2b6f48aa1c&t=4d37777d-f36a-53aa-9217-6386d15dddcd&l=2570

On my local Linux machine doing the following as a test with `git bisect --first-parent`:
```
$ mprof run pytest -m "not ultraslowtest" mne/tests/ --tb=short --cov=mne --cov-report=xml --cov-report=html -vv && mprof plot
```
takes ~12GB of memory usage on `main` and also 45357de4cf83340bd05d279673f68a7fd42b2308:

![bad_45357de4cf83340bd05d279673f68a7fd42b2308](https://user-images.githubusercontent.com/2365790/189228170-ad1e3d19-aba8-4711-8706-b92e0d9b2f2c.png)

but only a much more reasonable ~2.5GB of max memory usage on db550d57ee72e097b50d776cce108c64c80c181b:

![good_db550d57ee72e097b50d776cce108c64c80c181b](https://user-images.githubusercontent.com/2365790/189224079-dd532964-1c1d-4bb6-bb2b-75bb63d24ef4.png)

So I think this is due to #21995.

MNE does use SciPy, Numba, scikit-learn, dipy, etc. that could be interacting with NumPy in some bad way, too. I could at least rule out `numba`, `dipy`, and `scikit-learn` by uninstalling them and seeing the same overconsumption, though (some tests will just be skipped or our library with just use slower code paths this way).

I'm happy to work on isolating this further if it's not clear why this might be happening just from having it pinned down to the PR/commit.

### Reproduce the code example:

```python
<not easily reproduced / not yet isolated>
```

### NumPy/Python version information:

See commit numbers above

**Comment by charris** [comment] 2022-09-08 22:18
That's disturbing. Reverting is an option, but it would be nice to figure out _why_ it has that effect.

**Comment by larsoner** [comment] 2022-09-08 23:44
Tomorrow I'll see if I can replicate on something simpler test like maybe just running numpy.test with memprof

**Comment by seberg** [comment] 2022-09-09 06:55
Hmmmpf, the graph does look like we probably introduced a memory leak?  Would be helpful to narrow it down a bit.  Although if that is tricky, we can also run the debugging tools on the NumPy test suite to see if it points to something.

**Comment by rgommers** [comment] 2022-09-09 07:51
SciPy CI jobs started dying as well with no indication of what the problem is other than `Error: The operation was canceled.` in GitHub Actions ([example log](https://github.com/scipy/scipy/runs/8265266654?check_suite_focus=true)). We should revert the PR, and then resubmit and investigate the problem. 

Cc @ eirrgang as author of the relevant PR.

**Comment by seberg** [comment] 2022-09-09 07:53
oh, I missed that we know which PR is at fault.  That should be an easy fix then, no need to revert.

**Comment by rgommers** [comment] 2022-09-09 07:57
@seberg only if you already understand the problem and it can fixed within a few hours. Because it's going to be a huge waste of time if every downstream CI job testing numpy main is going to fail.

**Comment by rgommers** [comment] 2022-09-09 08:52
Broken wheels have been deleted and memory leak should be fixed - see gh-22236.

**Comment by rgommers** [comment] 2022-09-09 08:52
Thanks for finding the root cause @larsoner

**Closed** 2022-09-09 08:51 UTC
Labels: 00 - Bug
