### ISSUE TITLE
CI: Windows CI failing

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#26525] opened 2024-05-24 18:22 UTC
It looks like it started failing on #26514. I don't immediately see what's wrong with that CI job or why the change from that PR would lead to the error seen on CI.

```
$ 'C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe' -P -m pytest -m 'not slow' numpy
C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\_pytest\config\__init__.py:328: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ImportError: cannot import name 'version' from partially initialized module 'numpy' (most likely due to a circular import) (D:\a\numpy\numpy\numpy\__init__.py) (from D:\a\numpy\numpy\numpy\conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest 'D:\a\numpy\numpy\numpy\conftest.py'.
numpy\__init__.py:97: in <module>
    from . import version
E   ImportError: cannot import name 'version' from partially initialized module 'numpy' (most likely due to a circular import) (D:\a\numpy\numpy\numpy\__init__.py)
```

_Originally posted by @ngoldbaum in https://github.com/numpy/numpy/issues/26514#issuecomment-2130055174_

**Comment by ngoldbaum** [comment] 2024-05-24 21:39
I successfully built numpy on windows with MSVC on a local PC with the current main branch, so I doubt the PR where it started is related.

**Comment by ngoldbaum** [comment] 2024-05-24 22:17
I tried to reproduce the exact setup from the failing LP64 test jobs, but every time I try to build numpy with `--vsenv`, I get:

```
LINK : fatal error LNK1181: cannot open input file 'gfortran.lib'
```

**Comment by seberg** [comment] 2024-05-25 08:48
OK, I think I found the difference: `spin` got a new version release and the tests are run with:
```
$ 'C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe' -P -m pytest -m 'not slow' numpy
```
when previously they were run with:
```
$ 'C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe' -P -m pytest '--rootdir=D:\a\numpy\numpy\build-install\usr\Lib\site-packages' -m 'not slow' numpy
```
That seems like a plausible reason, although not sure what the problem is exactly?

CC @stefanv since it is spin related.

**Comment by stefanv** [comment] 2024-05-25 15:10
OK, I'll take a look. We should always pin spin in CI.

**Comment by mattip** [comment] 2024-05-26 10:49
I changed CI to use the `build_requirements.txt` file in #26534

**Comment by seberg** [comment] 2024-05-26 13:05
Fixed for now, closing.  Not sure if the pytest invocation should be changed back, though?

**Closed by seberg** 2024-05-26 13:05 UTC
