### ISSUE TITLE
BUG: Failing to install numpy on Windows on ARM via pip and/or clang

### ISSUE THREAD

**Issue by hydroo** [numpy/numpy#25858] opened 2024-02-20 13:17 UTC
### Describe the issue:

I'm running into various issues on Windows on ARM.
I'll try to compile all of it here.

When I `pip install numpy` on WoA, I get errors when it doesn't find the appropriate version and tries compiling;
```
Collecting numpy
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [390 lines of output]
      + D:\Program Files\Python312-arm64\python.exe C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\vendored-meson\meson\meson.py setup C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103 C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103
      Build dir: C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      C compiler for the host machine: clang (clang 18.1.0 "clang version 18.1.0rc")
```

It then finds my local clang and uses that.
It then fails in various places, with errors like:
```
      [43/313] Compiling C object numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj
      FAILED: numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj
      "clang" "-Inumpy\core\libnpymath.a.p" "-Inumpy\core" "-I..\numpy\core" "-Inumpy\core\include" "-I..\numpy\core\include" "-I..\numpy\core\src\npymath" "-I..\numpy\core\src\common" "-ID:\Program Files\Python312-arm64\Include" "-IC:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc\meson_cpu" "-fcolor-diagnostics" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c99" "-O3" "-fno-strict-aliasing" "-ftrapping-math" "-DNPY_HAVE_CLANG_FPSTRICT" "-DNPY_HAVE_NEON_VFPV4" "-DNPY_HAVE_NEON_FP16" "-DNPY_HAVE_NEON" "-DNPY_HAVE_ASIMD" -MD -MQ numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj -MF "numpy\core\libnpymath.a.p\meson-generated_ieee754.c.obj.d" -o numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj "-c" numpy/core/libnpymath.a.p/ieee754.c
      In file included from ..\numpy\core\src\npymath\ieee754.c.src:7:
      In file included from ..\numpy\core\src\npymath\npy_math_common.h:9:
      In file included from ..\numpy\core\include\numpy/npy_math.h:4:
      ..\numpy\core\include\numpy/npy_common.h:391:2: error: npy_cdouble definition is not compatible with C99 complex definition !         Please contact NumPy maintainers and give detailed information about your         compiler and platform
        391 | #error npy_cdouble definition is not compatible with C99 complex definition ! \
            |  ^
      ..\numpy\core\include\numpy/npy_common.h:398:2: error: npy_cfloat definition is not compatible with C99 complex definition !         Please contact NumPy maintainers and give detailed information about your         compiler and platform
        398 | #error npy_cfloat definition is not compatible with C99 complex definition ! \
            |  ^
      ..\numpy\core\include\numpy/npy_common.h:405:2: error: npy_clongdouble definition is not compatible with C99 complex definition !
Please contact NumPy maintainers and give detailed information about your         compiler and platform

        405 | #error npy_clongdouble definition is not compatible with C99 complex definition ! \

            |  ^

      3 errors generated.
```

I've separately tried to build numpy directly from git.
And what happens is:
```
Has header "complex.h" : YES
Checking for type "complex float" : NO

numpy\_core\meson.build:168:4: ERROR: Problem encountered: "complex.h" header does not include complex type complex float
```

Afaict, the reason for this is that in `numpy\_core\meson.build`, it does the following:
```
if cc.get_argument_syntax() == 'msvc'
  complex_types_to_check = [
    ['NPY_SIZEOF_COMPLEX_FLOAT', '_Fcomplex'],
    ['NPY_SIZEOF_COMPLEX_DOUBLE', '_Dcomplex'],
    ['NPY_SIZEOF_COMPLEX_LONGDOUBLE', '_Lcomplex'],
  ]
else
  complex_types_to_check = [
    ['NPY_SIZEOF_COMPLEX_FLOAT', 'complex float'],
    ['NPY_SIZEOF_COMPLEX_DOUBLE', 'complex double'],
    ['NPY_SIZEOF_COMPLEX_LONGDOUBLE', 'complex long double'],
  ]
endif
```

But `get_argument_syntax` for clang likely yields not MSVC, but clang on Windows does behave like MSVC, including the `complex.h` header and setting `_MSC_VER` .

Does numpy support clang on windows?
If not, pip needs to steer around this (by fetching the x64 binary version), and not cause an install failure outright.
If it is supported, I would expect to fail on x64 windows as well as WoA.

### Reproduce the code example:

```python
pip install numpy

or

D:\projects\misc\numpy-git>python -m spin test -v
```

### Error message:

```shell
C:\Users\ronnyb>pip install numpy
Collecting numpy
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [390 lines of output]
      + D:\Program Files\Python312-arm64\python.exe C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\vendored-meson\meson\meson.py setup C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103 C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103
      Build dir: C:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      C compiler for the host machine: clang (clang 18.1.0 "clang version 18.1.0rc")
      C linker for the host machine: clang lld-link 18.1.0
      C++ compiler for the host machine: clang++ (clang 18.1.0 "clang version 18.1.0rc")
      C++ linker for the host machine: clang++ lld-link 18.1.0
      Cython compiler for the host machine: cython (cython 3.0.8)

[..]
      [43/313] Compiling C object numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj
      FAILED: numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj
      "clang" "-Inumpy\core\libnpymath.a.p" "-Inumpy\core" "-I..\numpy\core" "-Inumpy\core\include" "-I..\numpy\core\include" "-I..\numpy\core\src\npymath" "-I..\numpy\core\src\common" "-ID:\Program Files\Python312-arm64\Include" "-IC:\Users\ronnyb\AppData\Local\Temp\pip-install-obwjnqcd\numpy_5e25cc0bff324a4a963474cf7f014103\.mesonpy-p_umgwkc\meson_cpu" "-fcolor-diagnostics" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c99" "-O3" "-fno-strict-aliasing" "-ftrapping-math" "-DNPY_HAVE_CLANG_FPSTRICT" "-DNPY_HAVE_NEON_VFPV4" "-DNPY_HAVE_NEON_FP16" "-DNPY_HAVE_NEON" "-DNPY_HAVE_ASIMD" -MD -MQ numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj -MF "numpy\core\libnpymath.a.p\meson-generated_ieee754.c.obj.d" -o numpy/core/libnpymath.a.p/meson-generated_ieee754.c.obj "-c" numpy/core/libnpymath.a.p/ieee754.c
      In file included from ..\numpy\core\src\npymath\ieee754.c.src:7:
      In file included from ..\numpy\core\src\npymath\npy_math_common.h:9:
      In file included from ..\numpy\core\include\numpy/npy_math.h:4:
      ..\numpy\core\include\numpy/npy_common.h:391:2: error: npy_cdouble definition is not compatible with C99 complex definition !         Please contact NumPy maintainers and give detailed information about your         compiler and platform
        391 | #error npy_cdouble definition is not compatible with C99 complex definition ! \
            |  ^
      ..\numpy\core\include\numpy/npy_common.h:398:2: error: npy_cfloat definition is not compatible with C99 complex definition !         Please contact NumPy maintainers and give detailed information about your         compiler and platform
        398 | #error npy_cfloat definition is not compatible with C99 complex definition ! \
            |  ^
      ..\numpy\core\include\numpy/npy_common.h:405:2: error: npy_clongdouble definition is not compatible with C99 complex definition !
Please contact NumPy maintainers and give detailed information about your         compiler and platform

        405 | #error npy_clongdouble definition is not compatible with C99 complex definition ! \

            |  ^

      3 errors generated.





OR

for D:\projects\misc\numpy-git>python -m spin test -v

Has header "complex.h" : YES
Checking for type "complex float" : NO

numpy\_core\meson.build:168:4: ERROR: Problem encountered: "complex.h" header does not include complex type complex float
```

### Python and NumPy Versions:

Python 3.12.2
Numpy trunk / 2.16.4

### Context for the issue:

`pip install numpy` fails on Windows on ARM with the default settings.

`D:\ronnyb\projects\misc\numpy-git>python -m spin test -v` fails as well when it finds clang as a compiler.
(I have not tried running MINGW on WoA)

**Comment by rgommers** [comment] 2024-02-20 16:45
Are you actually trying to build with Clang, or is the problem here that you need MSVC but are getting Clang instead?

I don't have much experience with Windows on Arm, but it does work. `clang` on Windows is usually problematic though, should be `clang-cl`.

**Comment by hydroo** [comment] 2024-02-20 18:52
I just wanted to `pip install numpy` and then went down the rabithole hoping it would help find the bug.
I didn't do anything outside of letting it use its defaults in both the pip case, and running tests on the git project directly.

When you say "it does work", do you mean WoA (with the windows devkit?) or clang on Linux?

I can do some follow up tests.

**Comment by rgommers** [comment] 2024-02-20 19:29
I meant "Windows on Arm". I did a bit of digging: there's CI for the Python ecosystem at https://gitlab.com/Linaro/windowsonarm/nightly/-/blob/master/.gitlab-ci.yml?ref_type=heads#L101, it seems to be using x86-64 wheels for numpy though (from [this CI log](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/6199252269)):
```
19/500 | package numpy | https://pypi.org/project/numpy | is_arch_specific | no_wheel | wheel_amd64 | is_installable
```

For building from source, I'd start with using MSVC since I imagine that has the best support:
```
pip install numpy -Csetup-args=--vsenv
```

**Comment by hydroo** [comment] 2024-02-23 14:30
This issue only seems to occur if clang is in the PATH. Otherwise pip successfully installs numpy.
The installed wheel looks like it's arm64 ~~ I see some files like `_multiarray_tests.cp312-win_arm64` ~~ but I'm not completely sure. How can I tell whether the archtecture of the libs in the wheel?

**Comment by rgommers** [comment] 2024-02-23 16:47
Great. The platform tag in the wheel should be accurate; if it says `arm64` then it should be. To be sure, I'd just install it in a Python environment which is also for `arm64` - if it runs it's certainly the right architecture.

**Comment by hydroo** [comment] 2024-02-24 17:40
I imported it successfully. I guess I'll make a new issue if I have get a different error.

Is the clang PATH thingy for pip something you should/could/want to fix, or should we close this issue?

**Comment by rgommers** [comment] 2024-02-24 21:04
> Is the clang PATH thingy for pip something you should/could/want to fix,

No, that works as designed by Meson. The first compiler on PATH is picked, and if none are on the PATH then some extra effort is made to locate MSVC.

I'll close this then. Thanks @hydroo

**Closed by rgommers** 2024-02-24 21:04 UTC
Labels: 32 - Installation
