### ISSUE TITLE
savez needs a lot more memory than save

### ISSUE THREAD

**Issue by fiftysevendegreesofrad** [numpy/numpy#5902] opened 2015-05-21 10:25 UTC
Hello

numpy 1.7.1, Python 2.7.2 (default, Jun 12 2011, 14:24:46) [MSC v.1500 64 bit (AMD64)] on win32.  Definitely running 64 bit as ctypes.c_size_t==ctypes.c_ulonglong.

``` python
import numpy
a = numpy.zeros((30000,30000))
numpy.savez_compressed("foo",a=a)
```

By my reckoning an array of 30,000 x 30,000 float64 should take 7.2GB, and the task manager confirms this.  Before saving I have 21GB free, so there shouldn't be a problem compressing this data.

`numpy.save("foo",a)` works, though `numpy.savez` fails.

**Comment by serhiy-storchaka** [comment] 2017-10-16 14:13
I can't reproduce on Linux. NumPy 1.12.1 and 1.14.0.dev0+ce202ed, Python 2.7.14 and 3.6.3. In all cases VmPeak is around 7 GB (the size of the array).

Could you provide a traceback?

**Comment by charris** [comment] 2017-12-17 05:07
I'm going to close this, the numpy version was very old, and several things have changed. @fiftysevendegreesofrad If this is still a problem, let us know.

**Closed by charris** 2017-12-17 05:07 UTC
