### ISSUE TITLE
Cannot create a file called random.py

### ISSUE THREAD

**Issue by ilanolkies** [numpy/numpy#16198] opened 2020-05-10 05:51 UTC
Based on https://stackoverflow.com/a/25775030/5078258

### Reproducing code example:

```python
# call this file random.py
import numpy as np

print(1000)
```

### Error message:

```
$ python scripts/random.py 
1000
Traceback (most recent call last):
  File "scripts/random.py", line 1, in <module>
    import numpy as np
  File "/Users/ilanolkies/.pyenv/versions/3.6.5/lib/python3.6/site-packages/numpy/__init__.py", line 187, in <module>
    from .testing import Tester
  File "/Users/ilanolkies/.pyenv/versions/3.6.5/lib/python3.6/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from ._private.utils import *
  File "/Users/ilanolkies/.pyenv/versions/3.6.5/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 16, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/Users/ilanolkies/.pyenv/versions/3.6.5/lib/python3.6/tempfile.py", line 45, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random'
```

### Numpy/Python version information:

- Python 3.6.5
- `numpy` 1.16.3

**Comment by mattip** [comment] 2020-05-10 06:01
You opened an issue. What do you think should happen? Can you point to any other python library that has avoided this general python feature?

**Comment by ilanolkies** [comment] 2020-05-10 06:05
Why couldn't I name my file that way? Are there any other _ forbidden_ names?

**Comment by eric-wieser** [comment] 2020-05-10 06:54
Duplicate of #16088

**Closed by eric-wieser** 2020-05-10 06:54 UTC
Labels: 53 - Invalid

**Comment by mattip** [comment] 2020-05-10 07:07
Simplistically, python searches for modules along the `sys.path`, and imports the first one it finds. So any module name in any package you use can be shadowed by a file that appears earlier in `sys.path`. Note in your case, this is not even a NumPy issue: `random.py` is part of the Python (not NumPy) stdlib

**Comment by ilanolkies** [comment] 2020-05-10 07:09
Oh! Thanks 😄
