### ISSUE TITLE
ENH: Bfloat16 support

### ISSUE THREAD

**Issue by zhiqiu** [numpy/numpy#21007] opened 2022-02-07 07:07 UTC
### Proposed new feature or change:

As the title, `Bfloat16` is a new data type of `float number` that is used in cuda A100 cards and intel CPU. Does `numpy` have any plan to support `Bfloat16`?

**Comment by mattip** [comment] 2022-02-07 07:33
Closing. Duplicate of #19808

**Closed by mattip** 2022-02-07 07:33 UTC
