### ISSUE TITLE
BUG: RuntimeWarning: divide by zero encountered in det for a complex matrix with all real values

### ISSUE THREAD

**Issue by astralcai** [numpy/numpy#25214] opened 2023-11-21 02:20 UTC
### Describe the issue:

When calculating the determinant of a complex matrix where all values are real, the function throws 

```
RuntimeWarning: divide by zero encountered in det
```

### Reproduce the code example:

```python
import numpy as np
mat = [[1,0],[0,1]]
mat = np.asarray(mat, dtype="complex128")
np.linalg.det(mat)
```

### Error message:

```shell
/Users/astralcai/Workspace/pennylane/venv/lib/python3.9/site-packages/numpy/linalg/linalg.py:2180: RuntimeWarning: divide by zero encountered in det
  r = _umath_linalg.det(a, signature=signature)
/Users/astralcai/Workspace/pennylane/venv/lib/python3.9/site-packages/numpy/linalg/linalg.py:2180: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
```

### Runtime information:

1.26.1
3.9.6 (default, Aug 11 2023, 19:44:49) 
[Clang 15.0.0 (clang-1500.0.40.1)]

**Comment by seberg** [comment] 2023-11-21 08:24
How did you install numpy (and blas/lapack if you did?).  The form asks you to provide `np.show_runtime()` *with* `threadpoolctl` installed which contains important information here (at least likely).

**Comment by hvsesha** [comment] 2023-11-23 07:11
@seberg Hi I tried in windows and getting output 1+0j .Not getting divide by zero error

**Comment by martin-frbg** [comment] 2023-11-23 11:16
Which version of OpenBLAS is in 1.26.1 ? I cannot reproduce this with 0.3.25

**Comment by seberg** [comment] 2023-11-23 11:34
Then probably fixed already.  Sorry, seems like 1.26.2 is on `0.3.23.dev` (with which I can reproduce on M1)

**Comment by charris** [comment] 2023-11-23 16:20
More precisely, `v0.3.23-293-gc2f4bdbb`. It is currently pinned to avoid problems with the name changes, see #25192. @mattip is it possible to upgrade?

**Comment by mattip** [comment] 2023-11-23 19:47
The pin in #25192 was reverted in #25151, but neither of those affect wheel building. I plan on upgradng the wheel building to build with the scipy-openblas wheels (and, like today, ship the openblas shared objects) soon.

**Comment by charris** [comment] 2023-11-23 19:50
@mattip the 1.26.x tests don't pass without the pin.

**Comment by mattip** [comment] 2023-11-23 20:50
Is there a CI run of the failing build?

**Comment by charris** [comment] 2023-11-23 22:15
There were 4 PRs failing until I pinned the version and rebased them, let me see if I can find them. Note that some of our tests are still building with distutils.

**Comment by charris** [comment] 2023-11-23 23:00
@mattip I reverted in #25240 to show the error. The wheels depend on `tools/openblas_support.py` where OpenB LAS was already pinned, I haven't tried updating that, we should give it a shot.

**Comment by seberg** [comment] 2023-12-22 14:21
I'll assume this has been fixed in Openblas, and the other discussion is a bit unrelated to the issue.  so closing, reopen if it persists with a NumPy using a newer Openblas version.

**Closed by seberg** 2023-12-22 14:21 UTC
Labels: 00 - Bug
