### ISSUE TITLE
DOC: np.append docs should explain how appending different dtypes works

### ISSUE THREAD

**Issue by Fleyderer** [numpy/numpy#26291] opened 2024-04-16 13:45 UTC
### Describe the issue:

When trying to append empty list to existing array, numpy array changes its dtype. This is absolutely not obvious behaviour and I've barely found this problem. 

It may sound like minor problem, but in my case it was a reason of not deleting about 50k images by its indices, when I had to.

### Reproduce the code example:

```python
a = np.array([1, 2], dtype=int)
b = []
np.append(a, b) # array([1., 2.])
```

### Python and NumPy Versions:

Python 3.11.5
Numpy 1.26.4

**Comment by rkern** [comment] 2024-04-16 14:23
It's intended behavior, but it should be documented better.

**Comment by tuhinsharma121** [comment] 2024-04-16 18:24
@rkern Can I work on a PR to document this behaviour? In that case can you assign this issue to me?

**Comment by Fleyderer** [comment] 2024-04-16 18:36
What is "intended" in changing dtype of array, which values are not changed¿

**Comment by rkern** [comment] 2024-04-16 20:45
Both arguments are converted to `ndarray`s through the usual method of `np.asarray()`. The default dtype for empty lists is `float64`. Once the arguments are converted to `ndarray`s, then their dtypes are compared to figure out the common dtype they can both be safely coerced to; `int64` and `float64` can both go to `float64`.

```python
>>> np.asarray([]).dtype
dtype('float64')
```

If you want to work around this, even in the case of empty lists, be sure to coerce _both_ of your arguments to `ndarray`s explicitly with `dtype=int` ahead of time.

```python
>>> a = np.array([1, 2], dtype=int)
>>> b = np.array([], dtype=int)
>>> np.append(a, b)
array([1, 2])
```

**Comment by seberg** [comment] 2024-04-17 07:12
For what it's worth, I would agree that for `append` casting to the first array would probably have been a nicer choice for NumPy, but that doesn't mean I think we should change it (at least not without a long warning which may be tedious).

There was discussion (maybe even a PR?) to add a `dtype=` argument, which would allow you to write `np.append(arr, ..., dtype=arr.dtype)`.
`np.concatenate` already has that option and is really basically what `np.append` uses internally.
That could be reactivated.

(For the empty list case, the `dtype=` argument may still be awkward due to unsafe casting of the "inferred" float64.)

---

Improving the docs is also good of course.

**Closed** 2024-04-22 06:00 UTC
Labels: 04 - Documentation
