### ISSUE TITLE
Inconsistent bitwise shift overflow behavior

### ISSUE THREAD

**Issue by toobaz** [numpy/numpy#10299] opened 2017-12-29 22:43 UTC
```python
In [2]: np.arange(20, dtype='uint') << 64
Out[2]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint64)

In [3]: np.arange(10, dtype='uint') << 64
Out[3]: array([0, 0, 0, 0, 0, 0, 0, 0, 8, 9], dtype=uint64)

In [4]: np.arange(5, dtype='uint') << 64
Out[4]: array([0, 1, 2, 3, 4], dtype=uint64)
```

My understanding is that while ``numpy.left_shift`` should execute a rotation (despite the docs not mentioning this word), the ``<<`` operator should execute a shift (that is, drop overflowing bits). At least, things seem to work this way with values below 64:

```python
In [5]: (np.arange(20, dtype='uint') << 63 == (np.arange(20, dtype='uint') % 2 * 2) ** 63).all()
Out[5]: True

In [6]: (np.arange(10, dtype='uint') << 63 == (np.arange(10, dtype='uint') % 2 * 2) ** 63).all()
Out[6]: True

In [7]: (np.arange(5, dtype='uint') << 63 == (np.arange(5, dtype='uint') % 2 * 2) ** 63).all()
Out[7]: True
```

Instead with 64 some cases (``In [2]:``) shift, some (``In [4]:``) rotate, and some (``In [3]:``) mix the two behaviors!

I'm using ``uint`` for simplicity, but the behavior is not limited to unsigned ints:
```python
In [8]: np.arange(20) << 64
Out[8]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]: np.arange(5) << 64
Out[9]: array([0, 1, 2, 3, 4])
```

**Comment by eric-wieser** [comment] 2017-12-29 23:04
Shifting by 64 bits is undefined behaviour in C

**Comment by charris** [comment] 2017-12-30 00:57
Note that the Intel hardware instructions truncate the shift bits. For instance, for 64 bit integers the lower 6 bits are taken, that is a 64 bit shift is the same as a zero bit shift. There is an old PR to fix this that just needs a bit more work to fix it up.

**Comment by toobaz** [comment] 2018-01-01 16:22
> ``left_shift`` and ``<<`` are the same.

@eric-wieser Yeah, I was confused, sorry.

> Note that the Intel hardware instructions truncate the shift bits. For instance, for 64 bit integers the lower 6 bits of the shift value are taken, that is a 64 bit shift is the same as a zero bit shift. There is an old PR to fix this

@charris I don't see any drawbacks with this... that is, as long as the computational overhead is not a problem, my ideal fix would be to _always_ use the lower 6 bits (i.e. take the bits ``% 64``). But this is not what is happening on my Intel (Core i7) CPU (``Out[2]:`` and ``Out[3]:``)...

**Comment by toobaz** [comment] 2018-01-01 16:24
Anyway, if this is not worth "fixing" (i.e. removing the undefinedness for bits > 64), maybe the limitation should just be mentioned in the docs.

**Comment by mhvk** [comment] 2018-01-01 23:52
The differences may be due to vectorization (of groups of 4? but with a minimum of 8?). But that in turn then suggests the vectorized and unvectorized operations are not the same. It would seem better if we ensured that for shifts >=nbits, the result is guaranteed to be 0, but perhaps this has too much overhead.

**Comment by toobaz** [comment] 2018-01-02 00:21
> It would seem better if we ensured that for shifts >=nbits, the result is guaranteed to be 0

Do you mean "as opposed to taking ``shifts % nbits``" - or do you actually mean the same thing?

**Comment by eric-wieser** [comment] 2018-01-02 00:33
Duplicate of #2449, I think

**Comment by mhvk** [comment] 2018-01-02 22:32
@toobaz - I meant that for shift larger than nbits, the result should be zero, so indeed as opposed to taking `shift % nbits`

**Comment by toobaz** [comment] 2018-01-02 23:33
@mhvk yeah, sorry, I again got confused with rotation

**Comment by skoehler** [comment] 2021-09-09 15:00
I was about to open another issue about shift behavior and its documentation.

I think that exposing Python users to the bad semantics of C shifts is a bad idea. C saying that behavior is undefined actually means that it's platform specific. I dislike that you expose the platform-specific behavior to language like Python. Why not throw an exception when shifting X-bit integer by X or more bits? Or why not assign zeros to the whole array when shifting by X or more bits?

Clearly, the documentation is broken in the sense that it does not mention the undefined behavior that numpy inherits from C. In fact, the documentation seems to imply defined behavior (multiplication by 2**64 plus truncation) when that clearly isn't the actual behavior.

Also, we're clearly using Python to get away from the C world which has traps for us around every corner ;-)

**Comment by madphysicist** [comment] 2022-01-07 00:10
@skoehler You can either have fast or escape the specifics of your platform, but not both. Numpy is an attempt to bring fast to python, so that's just how it is. Every layer of machine independence you add is a layer of complexity that slows you down.

**Comment by skoehler** [comment] 2022-01-07 00:29
> @skoehler You can either have fast or escape the specifics of your platform, but not both. Numpy is an attempt to bring fast to python, so that's just how it is. Every layer of machine independence you add is a layer of complexity that slows you down.

If you choose to keep this behavior, then the documentation needs fixing. It is not stated that a shift may exhibit undefined behavior.

When you say that performance is affected, then this does not seem to apply to the use-case of shifting all elements of an array by the same amount. Here, only one safety-check is needed before working on the array.

It's true, that I didn't think about a more complicated scenario (e.g., shifting each element by a different amount given by another array). I see how implementing the documented semantics (multiplication by 2**x plus truncation) would impact performance. A solution that implements `x << (y % 64)` for 64-bit integers might have less impact and would have the advantage that it's cross-platform.

I would also agree, that the two use-cases (one shift amount, shift amount taken from an array) should have the same semantics.

What is the concept of numpy regarding platform specific behavior? I would hope for functions with well-define cross-platform semantics and fast functions that may exhibit platform-specific behavior. Is there a concept regarding this? And if so where is it stated?

**Comment by madphysicist** [comment] 2022-01-07 00:34
@skoehler That's indeed a good question. I don't know that numpy takes an official stance on fast vs portable, but now I'm very curious.

**Comment by seberg** [comment] 2022-01-07 01:01
Didn't gh-13739 fix the undefined behaviour and this issue should have been closed?  What version of NumPy did you try this on @skoehler, I would expect this to be well defined since NumPy 1.18?

**Comment by toobaz** [comment] 2022-01-07 08:05
> Didn't [gh-13739](https://github.com/numpy/numpy/pull/13739) fix the undefined behaviour and this issue should have been closed? What version of NumPy did you try this on @skoehler, I would expect this to be well defined since NumPy 1.18?

Indeed I cannot reproduce anymore the behavior I initially reported: numpy seems to just drop overflowing bits consistently. I guess this can be closed.

**Comment by seberg** [comment] 2022-01-07 14:34
Closing, if I am missing something please comment, reopen, or open a new issue.

**Closed by seberg** 2022-01-07 14:34 UTC
