### ISSUE TITLE
Strange KeyError 0 in asarray() when data only contains 1-length pandas.Series

### ISSUE THREAD

**Issue by stippingerm** [numpy/numpy#15326] opened 2020-01-14 16:15 UTC
### Reproducing code example:

```python
import numpy as np
import pandas as pd
# Error produced by any of the following
np.asarray([pd.Series([3], index=[13])])  # KeyError: 0
np.asarray([pd.Series([3], index=[13])], dtype=int)  # KeyError: 0
np.asarray([pd.Series([3], index=[13])], dtype=object)  # KeyError: 0
np.array([pd.Series([3], index=[13])], dtype=object)  # KeyError: 0
np.asarray([pd.Series([3], index=[13]), pd.Series([4], index=[14])])  # KeyError: 0
np.asarray([pd.Series([3], index=[13]), [1]])  # KeyError: 0
# Note: no problem for the following
np.asarray([pd.Series([3, 4], index=[13, 14])])  # success
np.asarray([1, pd.Series([3], index=[13])])  # success
np.asarray([pd.Series([3], index=[13]), 1])  # success
np.asarray(pd.Series([3], index=[13]))  # success
```

### Error message:

The problem seems to be that numpy detects that the `Series` contains a single element and tries to access it by the index `0` while the element has index `13`.

```
Traceback (most recent call last):
  File "<ipython-input-25-c9cd7b6d38e7>", line 1, in <module>
    np.asarray([pd.Series([3], index=[13])], dtype=int)
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 1071, in __getitem__
    result = self.index.get_value(self, key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 4730, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 88, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 992, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 998, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
```

Note: the call to np.array() cannot be debugged in Python, probably it is implemented in C.

### Numpy/Python version information:

1.17.4 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

**Comment by seberg** [comment] 2020-01-14 19:38
Hmmm, sounds related to https://github.com/numpy/numpy/pull/14995 and  gh-13958. Makes things even more complicated maybe, but that should fix this as well if we can get away with it.

To be sure (only tested with 1.16 myself, which I think was the version that would have had any change if there was one), this is not a regression, right?

**Comment by seberg** [comment] 2020-01-14 19:41
Ah, this error originates in the actual value setting. I am not sure I was actually changing that, but it is possible that we should simply remove the special casing there as part of that (or a quick followup).

**Comment by rossbar** [comment] 2020-07-18 19:04
I cannot reproduce the errors with:

```python
>>> print(np.__version__)
1.20.0.dev0+046a736
>>> print(pd.__version__)
1.0.5
```

**Comment by seberg** [comment] 2021-11-06 05:44
Closing, since as Ross notes, this can't really be reproduced anymore.  My last note suggests this happened during value setting:  That code is completely different now which explains why it would be gone.

If any issue remains, please open a issue.

**Closed by seberg** 2021-11-06 05:44 UTC
Labels: 57 - Close?
