### ISSUE TITLE
Remove setup.py files from installed files (Trac #1135)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1733] opened 2012-10-19 20:49 UTC
_Original ticket http://projects.scipy.org/numpy/ticket/1135 on 2009-06-09 by @cournape, assigned to @dmcooke._

It does not make much sense to install them, and it confuses some people, especially beginners in numpy, who run setup.py inside the installed version.

**Comment by melissawm** [comment] 2021-08-10 20:03
Is this issue still relevant? If so, can anyone give it a more complete description so the next steps are clearer? Thanks!

**Comment by Joshuah143** [comment] 2021-10-08 04:52
Considering that the link to the original ticket is no longer valid I don't think that the next steps are very clear. Considering that I think the main use case of the install has become much more of a simple `pip install numpy`, I think the original reason for the issue is well past the modern NumPy. I could be wrong though because I can't see the original issue.

Maybe a good candidate to be closed?

**Comment by seberg** [comment] 2022-04-06 16:12
I will just close this. We discussed it briefly, it doesn't seem to cause trouble and the eventual move to meson may just remove the nested `setup.py` files anyway, so the issue will disappear silently with that.

**Closed by seberg** 2022-04-06 16:12 UTC
Labels: 01 - Enhancement, component: numpy.distutils, Triage-review
