### ISSUE TITLE
numpy: Error importing numpy: you should not try to import numpy from         its source directory; please exit the numpy source tree, and relaunch         your python interpreter from there.

### ISSUE THREAD

**Issue by Eric-Li-7** [numpy/numpy#15669] opened 2020-02-29 00:27 UTC
when I import numpy, this error shows up:

```python
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

and if I try to do 'pip' install numpy again on cmd, this shows up.
``` 
'pip' is not recognized as internal or external command, operable program or batch file. 
```
when I searched this error again on the web, a website told me to type 'python' into cmd, and I got this:
```
'python' is not recognized as internal or external command, operable program or batch file. 
```
How do you fix this?

**Comment by rossbar** [comment] 2020-02-29 00:29
It sounds like there is an issue with the way python was installed/configured on your system. What OS are you using? How was Python installed?

**Comment by Eric-Li-7** [comment] 2020-02-29 00:34
I downloaded python from python.org. I use windows 10 version 1909 OS build 18363.657

**Comment by rossbar** [comment] 2020-02-29 00:41
The errors you are seeing indicate that your system is unable to find the Python that you installed. Take a look at the installation docs for Python on windows, particularly the [configuration section](https://docs.python.org/3/using/windows.html#configuring-python) to ensure that things are set up properly.

Alternatively, consider using a package manager like [conda](https://docs.conda.io/en/latest/) to aid with the installation/management of packages such as `numpy`.

I am closing this issue as it is not related to `numpy`. Hope the above resources help!

**Closed by rossbar** 2020-02-29 00:41 UTC

**Comment by adminy** [comment] 2023-11-23 10:13
same issue. Python 3.9 from aws lambda.

**Comment by saipavanmeruga** [comment] 2023-11-26 04:06
> same issue. Python 3.9 from aws lambda.

+ 1

**Comment by gsnadav** [comment] 2023-11-26 16:36
> same issue. Python 3.9 from aws lambda.

for me, installing libopenblas-dev solved this problem. I'm not sure that this is also your problem but maybe the underlying problem is different from the message.

**Comment by greywolf0324** [comment] 2023-11-27 05:21
same here when I'm importing numpy as aws lambda layer external library

**Comment by adminy** [comment] 2023-11-30 17:12
yeah, same here also...

**Comment by saipavanmeruga** [comment] 2023-12-01 01:31
Hi everyone,
I found the working solution for this problem.
Firstly, as @rossbar said this is **NOT** an issue with **numpy**.
Secondly, @greywolf0324 said that we need to do "pip install numpy" in EC2 and it worked, this is may be one of the solution but it is NOT the only solution.
Here is what i found on internet and after reading several blogs.


1. We need to know that Amazon Lambda works on Amazon Linux, yes, Amazon has it's own flavor of Linux. So, if a package must be recognized by Lambda you must install **_manylinux_2_17_x86_64.manylinux2014_x86_64.whl** **wheel file** on your local system (it may be windows or mac, you need to lookup how to unzip whl files in windows/mac according to your preference.) and then create a zip file and upload it to lambda.
2. Now, here is where it gets tricky, you should choose the lambda runtime environment and architecture accurately, because if you choose Lambda runtime environment to be Python 3.11 and create a layer that consits of the numpy 3.9 wheel file and upload it to lambda it is going to fail. And you need to select the same architecture (x86_64) while creating your lambda function. Make sure that you add these points to your checklist.

So, here are the screenshots of what I tried on my personal Mac and uploaded to a Lambda function whose runtime is Python 3.9 and x86_64 architecture.

1. First download the whl file for numpy from this [link](https://pypi.org/project/numpy/#files). (make sure you download the right version required based on your lambda function runtime, mine is python3.9 so I installed cp39_x86_64 package)

2. In mac, you can use the **unzip** command and give the name of the **whl** file

3. <img width="539" alt="Screenshot 2023-11-30 at 8 20 33 PM" src="https://github.com/numpy/numpy/assets/35487807/739b88c1-8eb8-4b9d-a257-c3c6f5fe313f">


4. Once you unzip the and do a ls and you should see something like this

5. <img width="512" alt="Screenshot 2023-11-30 at 8 22 44 PM" src="https://github.com/numpy/numpy/assets/35487807/7bf1767d-acee-49ae-87ce-d4fd7a215e67">

6. Next move them to a folder named python and create a zip file. If i do a ls command then the output should be like this,

7. <img width="176" alt="Screenshot 2023-11-30 at 7 58 57 PM" src="https://github.com/numpy/numpy/assets/35487807/b015f6eb-270f-4340-95c9-4cd870e02f74">

8. Now upload the numpy-layer.zip to lambda and I used  the following config for lambda function.
<img width="1073" alt="Screenshot 2023-11-30 at 8 01 49 PM" src="https://github.com/numpy/numpy/assets/35487807/611005cd-9012-4976-826f-109c6dae75a2">

9. Create a layer using the following config.
<img width="746" alt="Screenshot 2023-11-30 at 8 03 57 PM" src="https://github.com/numpy/numpy/assets/35487807/16885938-55bd-4ffe-bfd6-bd33168b90bc">

10. Now add the layer to your lambda function. Scroll down and click on add a layer 
<img width="1304" alt="Screenshot 2023-11-30 at 8 06 29 PM" src="https://github.com/numpy/numpy/assets/35487807/78c62c4c-b0bf-4073-bffe-fe228f12e1a9">

11. Following is the configuration I used, 
<img width="833" alt="Screenshot 2023-11-30 at 8 07 29 PM" src="https://github.com/numpy/numpy/assets/35487807/69128c47-1be5-47a0-9710-e09d4f1999b2">

12. This is code in my lambda function 
<img width="454" alt="Screenshot 2023-11-30 at 8 29 40 PM" src="https://github.com/numpy/numpy/assets/35487807/b38036a0-071f-4c3a-89ba-3498efd96245">
13. This is output 
<img width="331" alt="Screenshot 2023-11-30 at 8 29 35 PM" src="https://github.com/numpy/numpy/assets/35487807/c1414793-2013-410d-9a17-37be8f500a90">

**Comment by rkochar** [comment] 2023-12-05 18:36
@saipavanmeruga you are correct. it indeed works. I had something else going wrong in the lambda i tested. thanks!

**Comment by rkochar** [comment] 2023-12-05 20:03
@saipavanmeruga you are correct. i was doing a `pip install ...` and did not notice that the python version of lambda is 3.10 but my local machine is 3.11. Changing to `python3.10 -m pip install ...` fixed it. Thanks!

**Comment by hyperific** [comment] 2024-01-16 22:30
> > same issue. Python 3.9 from aws lambda.
> 
> for me, installing libopenblas-dev solved this problem. I'm not sure that this is also your problem but maybe the underlying problem is different from the message.

This worked for me.

**Comment by rayud** [comment] 2024-02-04 07:25
> same issue. Python 3.9 from aws lambda.

Even, I'm also getting the same issues. I have added dependecies in a layer. How to resolve this issue

**Comment by mattip** [comment] 2024-02-04 09:28
This issue is closed. Please open a new one explaining exactly what you are doing in a way that can be reproduced.
