### ISSUE TITLE
weird behavior of np.double(np.asarray([3]))

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#4380] opened 2014-02-27 14:27 UTC
Is this behavior of `np.double` desired?  I'm wondering about the middle case which I would have expected to be `array([3.])` instead of `3.0`.  I assume there is nothing special about `double` or `3` and that this is probably not a real issue, so it can be closed soon.

```
>>> np.double(np.asarray(3))
3.0
>>> np.double(np.asarray([3]))
3.0
>>> np.double(np.asarray([3, 4]))
array([ 3.,  4.])
```

**Comment by seberg** [comment] 2019-01-05 00:38
Closing as a duplicate of gh-10995 and probably a few others.

**Closed by seberg** 2019-01-05 00:38 UTC
