### ISSUE TITLE
Masked Array load() fails on python3

### ISSUE THREAD

**Issue by lfini** [numpy/numpy#10189] opened 2017-12-10 10:53 UTC
numpy.ma.load() fails on files generated bu numpy.ma.dump() in python3. See the following code:

```python
from __future__ import print_function
import sys
import numpy as np

print("Python version:", sys.version)
print("Numpy version:", np.version.full_version)

mma = np.ma.ones((4,4))
mma.dump("mma.dat")

mmb = np.ma.load("mma.dat")
```

And now let's run it:

```
laptop:~/py/Varie/testNPdump$ python testMAdump.py 
Python version: 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]
Numpy version: 1.13.3
```

Now with python3:

```
lfini@lfini-laptop:~/py/Varie/testNPdump$ python3 testMAdump.py 
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
Numpy version: 1.13.3
Traceback (most recent call last):
  File "testMAdump.py", line 11, in <module>
    mmb = np.ma.load("mma.dat")
  File "/usr/local/lib/python3.5/dist-packages/numpy/ma/core.py", line 7868, in load
    return pickle.load(F)
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by charris** [comment] 2017-12-10 17:19
AFAICT, this doesn't work in Python 2 either, check the load result.  IIRC, there has been some discussion about removing those masked array functions.

**Comment by eric-wieser** [comment] 2017-12-10 17:35
Discussion is at #10045

**Comment by eric-wieser** [comment] 2017-12-10 17:36
This is a duplicate of #549, so we should continue discussion there.

**Closed by eric-wieser** 2017-12-10 17:36 UTC
Labels: 00 - Bug, component: numpy.ma
