### ISSUE TITLE
EnvironmentError when pip installing into path with spaces on Windows

### ISSUE THREAD

**Issue by Harmon758** [numpy/numpy#11451] opened 2018-06-29 11:56 UTC
This happens when not using a binary package/wheel, as seen in https://github.com/pydata/numexpr/issues/305 and https://github.com/pypa/pip/issues/5536.

Since there aren't any wheels on PyPI for Python 3.7 yet, `pip install numpy` will raise the error for a Python 3.7 installation that was installed for all users, using the default directory in `%ProgramFiles%`, since `C:\Program Files` has a space in it. This doesn't occur for Python 3.7 installations that were installed only for the current user, in `%LocalAppData%` or another directory without spaces in the path.

Similarly, for other Python versions, installing with `pip install --no-binary :all: numpy` into a path with spaces in it, e.g. `C:\Program Files`, will raise the error.

The error in question is: `Could not install packages due to an EnvironmentError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"c:'`.
When viewing verbose logs with pip, the full traceback is:
```
Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\_internal\commands\install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "c:\program files\python36\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\_internal\req\req_install.py", line 818, in install
    ensure_dir(egg_info_dir)
  File "c:\program files\python36\lib\site-packages\pip\_internal\utils\misc.py", line 86, in ensure_dir
    os.makedirs(path)
  File "c:\program files\python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\program files\python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\program files\python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more times]
  File "c:\program files\python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"c:'
```

The cause of the error can be seen here:
https://github.com/numpy/numpy/blob/a6383b4d0a5ef51178755b2e1f418265b2304f75/numpy/distutils/command/install.py#L58-L81
where every path with spaces in the record is rewritten with quotation marks around it.

Correspondingly, the offending line in pip, https://github.com/pypa/pip/blob/10.0.1/src/pip/_internal/req/req_install.py#L818, attempts to use one of the lines, quotation marks and all, from that record to create a directory.
This results in the error seen.

Even though this line was only added in pip 10 with https://github.com/pypa/pip/commit/c6299ea040d9adaca6e4df8b9732666c53fffb0e, installing with the same conditions except with pip 9 still raises an error:
```
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 920, in install
    with open(inst_files_path, 'w') as f:
OSError: [Errno 22] Invalid argument: '"c:\\program files\\python36\\Lib\\site-packages\\numpy-1.14.5-py3.6.egg-info\\installed-files.txt'
```
as even pip 9 went on to attempt to use a line from the record.

The reason for wrapping paths with spaces in them in quotation marks in the record (which was done with https://github.com/numpy/numpy/commit/ba6c2ba95f4d0ab8a6c153a617aa5d1c789318a5) is due to bdist_rpm being unable to handle paths with spaces in them.
There's a [Python Bug Tracker issue](https://bugs.python.org/issue809163) for this, but it appears to be stale.

Currently, until Python 3.7 wheels are released on PyPI, a simple workaround for this on Python 3.7 is to install using a wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy.

**Comment by Harmon758** [comment] 2019-02-05 06:46
This is still an issue when attempting to install numpy 1.16.1 with pip 19.0.1 on Python 3.8.0a1.

**Comment by eric-wieser** [comment] 2019-02-05 07:19
I was actually just looking at this code the other day, and thought it looked suspicious. It's good to know that the problem manifests itself.

I don't think I have enough background to try and solve this though.

**Comment by mattip** [comment] 2019-09-28 17:55
maybe we could at least warn that spaces in the path name will cause problems

**Comment by eric-wieser** [comment] 2019-09-28 18:01
I wonder if we can just remove the offending distutils lines. Do we have an easy way of testing the bdist_rpm bug they supposedly fix?

**Comment by charris** [comment] 2019-09-28 18:15
Is it possible to just escape the spaces? That works for Linux, but I'm not sure about Windows.

**Comment by eric-wieser** [comment] 2019-09-28 18:35
The problem is that bdist_rpm requires escaped spaces, but windows requires non-escaped ones.

Given that the failure of bdist_rpm with spaces is an upstream bug, and paths with spaces are far more likely on Windows, I think we should just remove our hack that causes the problem

**Comment by sushilphd** [comment] 2019-12-20 06:43
can't install numpy in pycharm with python 3.8.0

**Comment by Harmon758** [comment] 2019-12-20 06:47
This shouldn't be the issue, since NumPy has had wheels for Python 3.8 since [v1.17.3](https://github.com/numpy/numpy/releases/tag/v1.17.3).

**Comment by eric-wieser** [comment] 2019-12-20 10:41
Self-assigning so that I remember to try the above patch.

**Comment by gothburz** [comment] 2020-03-21 00:57
Same issue with pycharm and python 3.0
```
Command "C:\dev\github\attack-cti\venv\Scripts\python.exe C:\dev\github\attack-cti\venv\lib\site-packages\pip-19.0.3-py3.8.egg\pip install --ignore-installed --no-user -
-prefix "C:\Users\Petrus Rex\AppData\Local\Temp\pip-build-env-bc8kclcv\overlay" --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/sim
ple -- setuptools wheel Cython>=0.29.13 "numpy==1.13.3; python_version=='3.6' and platform_system!='AIX'" "numpy==1.14.5; python_version>='3.7' and platform_system!='AIX
'" "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'" "numpy==1.16.0; python_version>='3.7' and platform_system=='AIX'"" failed with error code 1 in None
```
I worked around this issue by dropping pandas into `\venv\Lib\site-packages` from another install.

**Comment by ThoenigAdrian** [comment] 2020-07-14 05:52
fyi same issue happens with pypy 

`C:\Program Files (x86)\pypy2.7-v7.3.1-win32>pypy.exe -m pip install numpy
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting numpy
  Using cached numpy-1.16.6.zip (5.1 MB)
Installing collected packages: numpy
    Running setup.py install for numpy ... done
ERROR: Could not install packages due to an EnvironmentError: [Error 123] The filename, directory name, or volume label syntax is incorrect: "C:`

**Comment by adam-grant-hendry** [comment] 2020-11-14 15:36
Same error with `scikit-image` now

**Comment by MichaelKim39** [comment] 2020-11-30 17:22
Getting this issue for scikit-learn

**Comment by selemis-organization** [comment] 2020-12-13 18:22
Experiencing the issue with scikit-learn as well

**Comment by foncea** [comment] 2020-12-16 19:45
Happened to me with scikit-learn on Python 3.9

**Comment by beckyhsuuuuu** [comment] 2021-01-15 06:00
same problem to me while trying installing pandas under macos big sur 11.1 
python is 3.8 and pip is 20.3.3

**Comment by rgommers** [comment] 2023-09-16 11:50
All the mentioned packages have now switched away from using `numpy.distutils` (most to Meson, scikit-image to setuptools). And `numpy.distutils` itself will stay for a while longer so is deprecated. Hence we won't be looking into this anymore. If someone really needs a fix still, I'd be willing to merge it - but let's close this issue. Thanks all.

**Closed by rgommers** 2023-09-16 11:50 UTC
Labels: 00 - Bug, component: numpy.distutils
