### ISSUE TITLE
BUG?: 1.14 printing requires gc run to clean up all references to printed array

### ISSUE THREAD

**Issue by scoder** [numpy/numpy#10620] opened 2018-02-17 08:58 UTC
Dear NumPy devs, one of our NumPy integration doctests in Cython has been failing on travis for a couple of weeks. I checked the changelog of CPython and Cython from the time when it started, but neither showed anything remotely related. However, the failing travis nodes use NumPy 1.14, and since there were PyPy related changes in that release, I suspect that this could be the cause. I only see the failures in Py3.5+, and they started in the CPython-dev integration test runs for py3.6-dev and py3.7-dev on travis, however those are built (NumPy is pre-installed in them). Here's an example of a [failing run](https://travis-ci.org/cython/cython/builds/342548198).

The now failing [test](https://github.com/cython/cython/blob/2e1066dcfc1c4ccbfaa0babf3cbe9f58640431fd/tests/memoryview/numpy_memoryview.pyx#L415-L423) is simply this:
```
    cdef int[:, :] array = create_array((4, 5), mode="c", use_callback=True)
    print(np.asarray(array)[::2, ::2])
```
Meaning, there is a buffer provider (not NumPy), we take a Cython memory view from it, and then wrap that with `numpy.asarray()` to print it. The difference is when the buffer provider will be deallocated. Previously, it was cleaned up immediately at function exit (and we print a confirmation in a cleanup callback when that happens). With the new NumPy version, it is no longer cleaned up immediately, but only at the next GC run. I added a conditional GC call to the test to trigger that and keep the test from failing (we didn't need a GC run before), but I thought I'd at least bring this change to your attention, in case it's unintentional.

**Comment by seberg** [comment] 2018-02-17 11:33
Sounds like a bug if it is numpy's fault, since there should be no reason to require a gc run, but I don't see why this should happen (not sure about all pypy changes, but those that I remember should be pretty unrelated).
There is a view, an array and the memoryview. The view should reference the array (or maybe the memoryview, but don't think it does here) and the array also the memoryview (stored in `array.base`).

If CPython has something to do with it, it would have to be something about changes in the buffer/memoryview interface. I expect the same goes for NumPy here.

Or.... there is something going on about the new printing functionality causing some more complex referencing. That seems strange, but I think it might be a real thing to look into. The print itself is required? I.e. if you only print a single item from the array or so it is fine?

**Comment by seberg** [comment] 2018-02-17 11:34
If it is the printing, not sure it is a real bug, but could still be nice to remove at least if it is not hard.

**Comment by seberg** [comment] 2018-02-17 12:02
Yeah, it is the printing. Printing temporarily increases the reference count by one.

**Comment by seberg** [comment] 2018-02-17 12:11
So yeah, I guess its not really a bug, but still might be nice to get rid of if it is easy.

**Comment by eric-wieser** [comment] 2018-02-17 14:10
My guess would be it's the recursion detection, but it's not clear to my why that would hold onto a reference.

**Comment by eric-wieser** [comment] 2018-02-17 14:12
> Printing temporarily increases the reference count by one.

Can you give a repro? I can't seem to make this happen on master

**Comment by seberg** [comment] 2018-02-17 15:32
sorry:

```
#!/usr/bin/env python

import numpy as np
import sys
import gc

gc.disable()

arr = np.arange(2000).reshape(5, 2, -1)

view = arr[::2, ::2]

print(sys.getrefcount(view))
print(view)
print(view)
print(sys.getrefcount(view))
gc.collect()
print(sys.getrefcount(view))
```
prints out 2 and then 4. Was using 1.14.0 on py 3.6.4, so there is some chance that it got fixed in master, didn't really excpect much changes since 1.14.0....

**Comment by seberg** [comment] 2018-02-17 15:32
4 and then 2 of course ;).

**Comment by charris** [comment] 2018-02-17 17:47
Yeah, still in master.

**Comment by ahaldane** [comment] 2018-02-17 18:29
It has something to do with the new use of a recursive closure in `_formatArray`.

Here's the code structure which triggers it, where `func` plays the role of `_formatArray`, and `closure` plays the role of `recurse` in `arrayprint.py` :
```python
def func(a):
    def closure(i):
        if i == 0:
            return a
        return closure(i-1)
    return "val"

gc.disable()
a = np.arange(2)
print(sys.getrefcount(a))
r = func(a)
r = func(a)
print(sys.getrefcount(a))
gc.collect()
print(sys.getrefcount(a))
```

Interestingly, it only happens if the closure is recursive, and the closure does not even need to be called.

**Comment by ahaldane** [comment] 2018-02-17 18:32
Yeah, I guess this is the expected behavior:

https://bugs.python.org/issue4921

So we just have to reorganize this code to avoid a recursive closure.

**Comment by seberg** [comment] 2018-02-17 18:52
Can't you just delete the closure function when done with it to solve the cycle manually?

**Comment by ahaldane** [comment] 2018-02-17 19:05
Oh, that's much simpler. I'll submit a PR with just that.

**Comment by ahaldane** [comment] 2018-02-17 20:28
Hah, also, python2 does not allow me to delete the closure function:
```
[1]: def func(a):
...:     def closure(i):
...:         if i == 0:
...:             return a
...:         return closure(i-1)
...:     del closure
...:     return "val"
SyntaxError: can not delete variable 'closure' referenced in nested scope
```
Python3 allows it though.

**Comment by eric-wieser** [comment] 2018-02-18 03:48
Does setting it to None work, if del doesn't?

**Comment by scoder** [comment] 2018-02-18 20:45
Or `a = None`. Seems more explicit to reset the reference to the array than to try to delete some inner function.

**Comment by eric-wieser** [comment] 2018-02-18 22:38
leaving the inner function still leaves a reference cycle though, which we still want to clean up if possible

**Comment by ahaldane** [comment] 2018-02-18 23:12
Both `a = None` and `closure = None`  seem to work. I agree only `closure = None` seems to really remove the cycle, though.

I don't very much like adding these extra `= None` lines though, they seem a little too magical. Maybe we should go with @eric-wieser's idea of a callable class which has the recursive part as a member function, or just leave it as a separate helper function like it is in #10621 right now, and avoid the recursive closures altogether.

Actually, recursive closures seem like something PyPy could be made to account for more nicely. PyPy probably already implements its own version of closures and the co_cellvars table, so it seems there is opportunity to detect and remove the cycle when the closure goes out of scope.... maybe it gets complicated though.

**Comment by ahaldane** [comment] 2018-02-18 23:41
True, perhaps the `= None` trick is the more elegant one in the end. 

I'm still searching for alternate solutions. This is an interesting thread I'm still reading through, which shows a couple other cute solutions: https://mail.python.org/pipermail/python-dev/2009-December/094439.html

(also shows we may want to put the `=None` in a finally block)

**Comment by ahaldane** [comment] 2018-02-19 00:12
So after reading that thread, I think the best is to set the closure to `None` in a `finally` block. I've updated #10621 accordingly, fixing the 4 recursive closures I found.

**Closed** 2018-02-19 08:17 UTC
