### ISSUE TITLE
Compilation failure on Slackbuild for numpy and numpy3

### ISSUE THREAD

**Issue by demeler** [numpy/numpy#14980] opened 2019-11-25 14:19 UTC
The problem occurs when trying to compile the Slackbuild numpy or numpy3. THe compilation fails in the same position (see error message)
I am unsure what needs to be fixed and why this compilation fails. Any help would be appreciated.
### Reproducing code example:

I tried to build a Slackbuild version of the latest numpy/numpy3 source on a recent stock slackware64-current install with OpenBLAS 0.3.3 added (http://slackbuilds.org)

### Error message:

```
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -c numpy/core/src/multiarray/numpyos.c -o build/temp.linux-x86_64-2.7/numpy/core/src/multiarray/numpyos.o -MMD -MF build/temp.linux-x86_64-2.7/numpy/core/src/multiarray/numpyos.o.d" failed with exit status 1
```

**Comment by charris** [comment] 2019-11-25 15:06
What python version? The error message is not helpful, was there more?

**Comment by demeler** [comment] 2019-11-25 15:24
I have both Python 2 (2.7.17) and Python3 (3.7.2) installed. I assume numpy uses Python2, and numpy3 uses Python3. The gcc compiler is gcc 9.2.0. The lines leading up to the error are included below, perhaps that is helpful? Thanks so much for looking at this!

gcc: numpy/core/src/multiarray/numpyos.c
In file included from numpy/core/src/multiarray/numpyos.c:23:
/usr/include/xlocale.h:27:16: error: redefinition of ‘struct __locale_struct’
   27 | typedef struct __locale_struct
      |                ^~~~~~~~~~~~~~~
In file included from /usr/include/bits/types/locale_t.h:22,
                 from /usr/include/string.h:152,
                 from /usr/include/python2.7/Python.h:38,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/bits/types/__locale_t.h:28:8: note: originally defined here
   28 | struct __locale_struct
      |        ^~~~~~~~~~~~~~~
In file included from numpy/core/src/multiarray/numpyos.c:23:
/usr/include/xlocale.h:39:4: error: conflicting types for ‘__locale_t’
   39 | } *__locale_t;
      |    ^~~~~~~~~~
In file included from /usr/include/bits/types/locale_t.h:22,
                 from /usr/include/string.h:152,
                 from /usr/include/python2.7/Python.h:38,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/bits/types/__locale_t.h:42:33: note: previous declaration of ‘__locale_t’ was here
   42 | typedef struct __locale_struct *__locale_t;
      |                                 ^~~~~~~~~~
In file included from numpy/core/src/multiarray/numpyos.c:23:
/usr/include/xlocale.h:42:20: error: conflicting types for ‘locale_t’
   42 | typedef __locale_t locale_t;
      |                    ^~~~~~~~
In file included from /usr/include/string.h:152,
                 from /usr/include/python2.7/Python.h:38,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/bits/types/locale_t.h:24:20: note: previous declaration of ‘locale_t’ was here
   24 | typedef __locale_t locale_t;
      |                    ^~~~~~~~
numpy/core/src/multiarray/numpyos.c: In function ‘NumPyOS_ascii_strtold’:
numpy/core/src/multiarray/numpyos.c:568:13: warning: assignment to ‘locale_t’ {aka ‘struct __locale_struct *’} from incompatible pointer type ‘locale_t’ {aka ‘struct __locale_struct *’} [-Wincompatible-pointer-types]
  568 |     clocale = newlocale(LC_ALL_MASK, "C", NULL);
      |             ^
numpy/core/src/multiarray/numpyos.c:571:39: warning: passing argument 3 of ‘strtold_l’ from incompatible pointer type [-Wincompatible-pointer-types]
  571 |         result = strtold_l(s, endptr, clocale);
      |                                       ^~~~~~~
      |                                       |
      |                                       locale_t {aka struct __locale_struct *}
In file included from /usr/include/python2.7/Python.h:42,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/stdlib.h:305:19: note: expected ‘locale_t’ {aka ‘struct __locale_struct *’} but argument is of type ‘locale_t’ {aka ‘struct __locale_struct *’}
  305 |          locale_t __loc)
      |          ~~~~~~~~~^~~~~
numpy/core/src/multiarray/numpyos.c:572:20: warning: passing argument 1 of ‘freelocale’ from incompatible pointer type [-Wincompatible-pointer-types]
  572 |         freelocale(clocale);
      |                    ^~~~~~~
      |                    |
      |                    locale_t {aka struct __locale_struct *}
In file included from numpy/core/src/multiarray/numpyos.c:4:
/usr/include/locale.h:180:34: note: expected ‘locale_t’ {aka ‘struct __locale_struct *’} but argument is of type ‘locale_t’ {aka ‘struct __locale_struct *’}
  180 | extern void freelocale (locale_t __dataset) __THROW;
      |                         ~~~~~~~~~^~~~~~~~~
In file included from numpy/core/src/multiarray/numpyos.c:23:
/usr/include/xlocale.h:27:16: error: redefinition of ‘struct __locale_struct’
   27 | typedef struct __locale_struct
      |                ^~~~~~~~~~~~~~~
In file included from /usr/include/bits/types/locale_t.h:22,
                 from /usr/include/string.h:152,
                 from /usr/include/python2.7/Python.h:38,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/bits/types/__locale_t.h:28:8: note: originally defined here
   28 | struct __locale_struct
      |        ^~~~~~~~~~~~~~~
In file included from numpy/core/src/multiarray/numpyos.c:23:
/usr/include/xlocale.h:39:4: error: conflicting types for ‘__locale_t’
   39 | } *__locale_t;
      |    ^~~~~~~~~~
In file included from /usr/include/bits/types/locale_t.h:22,
                 from /usr/include/string.h:152,
                 from /usr/include/python2.7/Python.h:38,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/bits/types/__locale_t.h:42:33: note: previous declaration of ‘__locale_t’ was here
   42 | typedef struct __locale_struct *__locale_t;
      |                                 ^~~~~~~~~~
In file included from numpy/core/src/multiarray/numpyos.c:23:
/usr/include/xlocale.h:42:20: error: conflicting types for ‘locale_t’
   42 | typedef __locale_t locale_t;
      |                    ^~~~~~~~
In file included from /usr/include/string.h:152,
                 from /usr/include/python2.7/Python.h:38,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/bits/types/locale_t.h:24:20: note: previous declaration of ‘locale_t’ was here
   24 | typedef __locale_t locale_t;
      |                    ^~~~~~~~
numpy/core/src/multiarray/numpyos.c: In function ‘NumPyOS_ascii_strtold’:
numpy/core/src/multiarray/numpyos.c:568:13: warning: assignment to ‘locale_t’ {aka ‘struct __locale_struct *’} from incompatible pointer type ‘locale_t’ {aka ‘struct __locale_struct *’} [-Wincompatible-pointer-types]
  568 |     clocale = newlocale(LC_ALL_MASK, "C", NULL);
      |             ^
numpy/core/src/multiarray/numpyos.c:571:39: warning: passing argument 3 of ‘strtold_l’ from incompatible pointer type [-Wincompatible-pointer-types]
  571 |         result = strtold_l(s, endptr, clocale);
      |                                       ^~~~~~~
      |                                       |
      |                                       locale_t {aka struct __locale_struct *}
In file included from /usr/include/python2.7/Python.h:42,
                 from numpy/core/src/multiarray/numpyos.c:2:
/usr/include/stdlib.h:305:19: note: expected ‘locale_t’ {aka ‘struct __locale_struct *’} but argument is of type ‘locale_t’ {aka ‘struct __locale_struct *’}
  305 |          locale_t __loc)
      |          ~~~~~~~~~^~~~~
numpy/core/src/multiarray/numpyos.c:572:20: warning: passing argument 1 of ‘freelocale’ from incompatible pointer type [-Wincompatible-pointer-types]
  572 |         freelocale(clocale);
      |                    ^~~~~~~
      |                    |
      |                    locale_t {aka struct __locale_struct *}
In file included from numpy/core/src/multiarray/numpyos.c:4:
/usr/include/locale.h:180:34: note: expected ‘locale_t’ {aka ‘struct __locale_struct *’} but argument is of type ‘locale_t’ {aka ‘struct __locale_struct *’}
  180 | extern void freelocale (locale_t __dataset) __THROW;
      |                         ~~~~~~~~~^~~~~~~~~
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -c numpy/core/src/multiarray/numpyos.c -o build/temp.linux-x86_64-2.7/numpy/core/src/multiarray/numpyos.o -MMD -MF build/temp.linux-x86_64-2.7/numpy/core/src/multiarray/numpyos.o.d" failed with exit status 1

**Comment by seberg** [comment] 2019-11-25 17:08
To be honest, the error looks a bit like the issue is with includes that come from Python and not includes that come from NumPy? Possibly even within the system itself. Unless there is some issue with circular/multiple includes?

**Comment by seberg** [comment] 2019-11-25 17:12
Ah, your system runs into:
```
#ifdef HAVE_XLOCALE_H
    /*
     * the defines from xlocale.h are included in locale.h on some systems;
     * see gh-8367
     */
    #include <xlocale.h>
#endif
```
but that defines a variable which `Python.h` ends up defining as well through `locale_t.h`? Is the use of `HAVE_XLOCALE_H ` somehow incorrect or needs another `#ifdef` here?

**Comment by demeler** [comment] 2019-11-25 17:22
I'm happy to try anything, if you could tell me what to change? From your description it seems like you have a theory that could be tested, I could try if you could let me know what to change.

**Comment by seberg** [comment] 2019-11-25 17:50
Sorry, I do not know this. I can make the hypothesis that removing that `xlocal.h` include might just make things work for you. But removing it indiscriminately is certainly wrong. Possibly adding a check if `locale_t` (or whatever we use from there) is already defined makes sense.

**Comment by mattip** [comment] 2019-11-25 19:11
I seem to remember changes we made somewhere around 1.16 or 1.17 to fix this. I think compiling numpy 1.14 on an up to date python3 is doomed to failure.

**Comment by demeler** [comment] 2019-11-25 19:28
Sorry, this information is insufficient for me to know exactly what changes you envision. Is there something specific code change suggestion I could follow?

**Comment by seberg** [comment] 2019-11-25 19:31
@demeler I think matti is right. You are compiling an old numpy version on a brand new python version. This is unlikely to work out, unless you do some significant digging into what we fixed up over the time to support new python versions.

**Comment by demeler** [comment] 2019-11-25 20:50
I pulled the latest git clone (https://github.com/numpy/numpy.git), compiling it against python 3.7, and ran into exactly the same issue:
gcc: numpy/core/src/common/numpyos.c
In file included from numpy/core/src/common/numpyos.c:23:
/usr/include/xlocale.h:27:16: error: redefinition of ‘struct __locale_struct’
   27 | typedef struct __locale_struct
      |                ^~~~~~~~~~~~~~~
In file included from /usr/include/bits/types/locale_t.h:22,
                 from /usr/include/string.h:152,
                 from /usr/include/python3.7m/Python.h:30,
                 from numpy/core/src/common/numpyos.c:2:
/usr/include/bits/types/__locale_t.h:28:8: note: originally defined here
   28 | struct __locale_struct
      |        ^~~~~~~~~~~~~~~
In file included from numpy/core/src/common/numpyos.c:23:
/usr/include/xlocale.h:39:4: error: conflicting types for ‘__locale_t’
   39 | } *__locale_t;
      |    ^~~~~~~~~~
In file included from /usr/include/bits/types/locale_t.h:22,
                 from /usr/include/string.h:152,
                 from /usr/include/python3.7m/Python.h:30,
                 from numpy/core/src/common/numpyos.c:2:
/usr/include/bits/types/__locale_t.h:42:33: note: previous declaration of ‘__locale_t’ was here
   42 | typedef struct __locale_struct *__locale_t;
      |                                 ^~~~~~~~~~
In file included from numpy/core/src/common/numpyos.c:23:
/usr/include/xlocale.h:42:20: error: conflicting types for ‘locale_t’
   42 | typedef __locale_t locale_t;
      |                    ^~~~~~~~
In file included from /usr/include/string.h:152,
                 from /usr/include/python3.7m/Python.h:30,
                 from numpy/core/src/common/numpyos.c:2:
/usr/include/bits/types/locale_t.h:24:20: note: previous declaration of ‘locale_t’ was here
   24 | typedef __locale_t locale_t;
      |                    ^~~~~~~~
numpy/core/src/common/numpyos.c: In function ‘NumPyOS_ascii_strtold’:
numpy/core/src/common/numpyos.c:568:13: warning: assignment to ‘locale_t’ {aka ‘struct __locale_struct *’} from incompatible pointer type ‘locale_t’ {aka ‘struct __locale_struct *’} [-Wincompatible-pointer-types]
  568 |     clocale = newlocale(LC_ALL_MASK, "C", NULL);
      |             ^
numpy/core/src/common/numpyos.c:571:39: warning: passing argument 3 of ‘strtold_l’ from incompatible pointer type [-Wincompatible-pointer-types]
  571 |         result = strtold_l(s, endptr, clocale);
      |                                       ^~~~~~~
      |                                       |
      |                                       locale_t {aka struct __locale_struct *}
In file included from /usr/include/python3.7m/Python.h:34,
                 from numpy/core/src/common/numpyos.c:2:
/usr/include/stdlib.h:305:19: note: expected ‘locale_t’ {aka ‘struct __locale_struct *’} but argument is of type ‘locale_t’ {aka ‘struct __locale_struct *’}
  305 |          locale_t __loc)
      |          ~~~~~~~~~^~~~~
numpy/core/src/common/numpyos.c:572:20: warning: passing argument 1 of ‘freelocale’ from incompatible pointer type [-Wincompatible-pointer-types]
  572 |         freelocale(clocale);
      |                    ^~~~~~~
      |                    |
      |                    locale_t {aka struct __locale_struct *}
In file included from numpy/core/src/common/numpyos.c:4:
/usr/include/locale.h:180:34: note: expected ‘locale_t’ {aka ‘struct __locale_struct *’} but argument is of type ‘locale_t’ {aka ‘struct __locale_struct *’}
  180 | extern void freelocale (locale_t __dataset) __THROW;
      |                         ~~~~~~~~~^~~~~~~~~
error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -std=c99 -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -Ibuild/src.linux-x86_64-3.7/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/common -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c numpy/core/src/common/numpyos.c -o build/temp.linux-x86_64-3.7/numpy/core/src/common/numpyos.o -MMD -MF build/temp.linux-x86_64-3.7/numpy/core/src/common/numpyos.o.d" failed with exit status 1

**Comment by mattip** [comment] 2019-11-25 22:11
Possible duplicate of gh-13280, with a suggested fix in [this comment](https://github.com/numpy/numpy/issues/13280#issuecomment-480575329). We tried to fix this in gh-12135 but apparently that is insufficient for your system. What is Slackbuild?

**Comment by demeler** [comment] 2019-11-30 20:32
Slackbuild is a package builder from Slackware. The slackbuild environment seems to be irrelevant. The issue can be reproduced when rebuilding from source with the latest git clone, attempting a generic build. I also tried the suggested fix of removing /usr/include from the include list - it didn't help.

**Comment by mattip** [comment] 2019-12-01 05:12
> The issue can be reproduced when rebuilding from source with the latest git clone, attempting a generic build

A generic build succeeds on Ubuntu 18.04, so this is something specific to your setup. Somewhere in your log you should see what flags gcc is being called with. Some of those come from the `sysconfig` module, some from our distutils system, and some from environment variables. Check 
`xxx =sysconfig.get_config_vars(); [(x, xxx[x]) for x in xxx if 'INC' in x]` or your environment.

**Comment by demeler** [comment] 2019-12-01 15:11
I uploaded stdout and stderr, as well as my environment. Perhaps this helps you figure out what is not working?

[stderr.txt](https://github.com/numpy/numpy/files/3908335/stderr.txt)
[stdout.txt](https://github.com/numpy/numpy/files/3908336/stdout.txt)
[environment.txt](https://github.com/numpy/numpy/files/3908337/environment.txt)

**Comment by rossbar** [comment] 2020-07-18 20:45
Any updates here? It's been a while and it seems like the gremlin may live in the specific system setup.

**Comment by demeler** [comment] 2020-07-18 23:47
On Sat, Jul 18, 2020 at 01:46:02PM -0700, Ross Barnowski wrote:
> Any updates here? It's been a while and it seems like the gremlin may live in the specific system setup.

THanks for asking!
there are no updates, since I never received an answer to my last 
report, so I had nothing else to try out, and have given up. My initial 
attempt was to build digikam, some of its dependencies failed without
numpy, so I was stuck and decided to live without digikam.

This was on a stock slackware install, and the slackbuild of numpy 
failed. I just tried again with the latest numpy version (1.14.3)
and it gets through quite a bit of the compile but then still fails 
as shown:

error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG
-g -fwrapv -O3 -Wall -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1
-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1
-DHAVE_CBLAS -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private
-Inumpy/core/include
-Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy
-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core
-Inumpy/core/src/npymath -Inumpy/core/src/multiarray
-Inumpy/core/src/umath -Inumpy/core/src/npysort
-I/usr/include/python3.7m
-Ibuild/src.linux-x86_64-3.7/numpy/core/src/private
-Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath
-Ibuild/src.linux-x86_64-3.7/numpy/core/src/private
-Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath
-Ibuild/src.linux-x86_64-3.7/numpy/core/src/private
-Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c
numpy/core/src/multiarray/numpyos.c -o
build/temp.linux-x86_64-3.7/numpy/core/src/multiarray/numpyos.o -MMD -MF
build/temp.linux-x86_64-3.7/numpy/core/src/multiarray/numpyos.o.d"
failed with exit status 1

Thanks for asking!

-Borries

**Comment by mattip** [comment] 2020-07-19 06:13
If it is still the same error, the problem is that your OS defines `__locale_struct` twice
```
/usr/include/bits/types/__locale_t.h:28:8: note: originally defined here
   28 | struct __locale_struct
      |        ^~~~~~~~~~~~~~~
In file included from numpy/core/src/common/numpyos.c:23:
/usr/include/xlocale.h:39:4: error: conflicting types for ‘__locale_t’
   39 | } *__locale_t;
```

I repeat my comment from above: 
> I seem to remember changes we made somewhere around 1.16 or 1.17 to fix this. I think compiling numpy 1.14 on an up to date python3 is doomed to failure.

You may however find that conda may have solved these problems for you, if it exists for your platform. You should start by installing miniconda, then creating a new conda environment, then activating it, then installing `numpy=1.14`. If that succeeds, you can continue from there.

**Comment by demeler** [comment] 2020-07-24 19:19
> If it is still the same error, the problem is that your OS defines `__locale_struct` twice
> 
> ```
> /usr/include/bits/types/__locale_t.h:28:8: note: originally defined here
>    28 | struct __locale_struct
>       |        ^~~~~~~~~~~~~~~
> In file included from numpy/core/src/common/numpyos.c:23:
> /usr/include/xlocale.h:39:4: error: conflicting types for ‘__locale_t’
>    39 | } *__locale_t;
> ```
> 
> I repeat my comment from above:
> 
> > I seem to remember changes we made somewhere around 1.16 or 1.17 to fix this. I think compiling numpy 1.14 on an up to date python3 is doomed to failure.
> 
> You may however find that conda may have solved these problems for you, if it exists for your platform. You should start by installing miniconda, then creating a new conda environment, then activating it, then installing `numpy=1.14`. If that succeeds, you can continue from there.

I have decided to abandon my efforts to get numpy to work. I tried many things, but trying to get your package to work is like a can of worms, and I simply ran out of time. You can close this ticket.

**Closed** 2020-07-24 19:33 UTC
Labels: 57 - Close?, component: build
