### ISSUE TITLE
Unexpected behavior with csr matrices

### ISSUE THREAD

**Issue by zjpoh** [numpy/numpy#14487] opened 2019-09-11 20:44 UTC
I also have unexpected behavior with csr matrices:
```
import numpy as np
from scipy.sparse import csr_matrix

a = np.array([[1, 0, 2, 2], [1, 4, 2, 4]])
m = csr_matrix(a)

m.shape
Out: (2, 4)

m.todense()
Out:
matrix([[1, 0, 2, 2],
        [1, 4, 2, 4]])

m_2 = np.asarray(m)
# weird shape
m_2.shape
Out: ()

# whereas it seems to be conserved somehow
m_2
Out:
array(<2x4 sparse matrix of type '<type 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>, dtype=object)


m_2.todense()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-3ca00cd97e3f> in <module>()
----> 1 m_2.todense()

AttributeError: 'numpy.ndarray' object has no attribute 'todense'
```

versions:
1.17.1 3.7.2 (default, Feb 12 2019, 08:16:38)
[Clang 10.0.0 (clang-1000.11.45.5)]

     python: 3.7.2 
     scipy: 1.3.1

_Originally posted by @leonardbinet in https://github.com/numpy/numpy/issues/14221#issuecomment-526899594_

**Comment by rgommers** [comment] 2019-09-11 21:43
So what's happening here is that `np.asarray(sparse_matrix)` returns an object array: 
```
In [28]: m_2.shape                                                                 
Out[28]: ()

In [29]: type(m_2)                                                                 
Out[29]: numpy.ndarray

In [30]: m_2.dtype                                                                 
Out[30]: dtype('O')
```

With the sparse array being contained inside:
```
In [31]: m_2[()]                                                                   
Out[31]: 
<2x4 sparse matrix of type '<class 'numpy.int64'>'
        with 7 stored elements in Compressed Sparse Row format>
```

So `m_2.todense()` giving an `AttributeError` is expected, since `m_2` is a `numpy.ndarray`. tl;dr not a bug but highly annoying. Two separate ways forward:
- NumPy may change its behavior regarding creating object arrays at some point, or at least start giving warnings for such cases.
- SciPy could decide to raise a `TypeError` here via an added `__array__` method on all sparse matrices.

**Comment by seberg** [comment] 2019-09-16 21:23
I actually think the second option in scipy is probably the best thing. Raise an error and ask to use `todense` specifically.

**Comment by mattip** [comment] 2019-12-03 13:50
Closing. Please reopen with new information if needed.

**Closed by mattip** 2019-12-03 13:50 UTC
Labels: 57 - Close?, component: numpy.core
