### ISSUE TITLE
Unexpected behavious of `np.select`

### ISSUE THREAD

**Issue by ShivKJ** [numpy/numpy#24333] opened 2023-08-04 04:31 UTC
### Describe the issue:

Consider the dataframe `df`,
```python
import pandas as pd
import numpy as np

df = pd.DataFrame({'x': [1, 2, 3, 4]})
```

```
np.select([df.x <= 2, df.x <  4], ['small', 'medium'], default='large') 
```

This gives expected output which is `array(['small', 'small', 'medium', 'large'], dtype='<U6')`

## Changing column `x` type to `Int64`
```
df['x'] = df['x'].astype('Int64')
```

Now the below code throw error.

```
np.select([df.x <= 2, df.x <  4], ['small', 'medium'], default='large') 
```

This is the error,
```
TypeError: invalid entry 0 in condlist: should be boolean ndarray
```

### Reproduce the code example:

```python
import pandas as pd
import numpy as np

df = pd.DataFrame({'x': [1, 2, 3, 4]})
df['x'] = df['x'].astype('Int64')
np.select([df.x <= 2, df.x <  4], ['small', 'medium'], default='large') 
```
```


### Error message:

```shell
File ~/.virtualenvs/exp/lib/python3.10/site-packages/numpy/lib/function_base.py:847, in select(condlist, choicelist, default)
    845 for i, cond in enumerate(condlist):
    846     if cond.dtype.type is not np.bool_:
--> 847         raise TypeError(
    848             'invalid entry {} in condlist: should be boolean ndarray'.format(i))
    850 if choicelist[0].ndim == 0:
    851     # This may be common, so avoid the call.
    852     result_shape = condlist[0].shape

TypeError: invalid entry 0 in condlist: should be boolean ndarray
```
```


### Runtime information:

```
1.25.2
3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
```

```
[{'numpy_version': '1.25.2',
  'python': '3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 '
            '(clang-1300.0.29.30)]',
  'uname': uname_result(system='Darwin', machine='arm64')},
 {'simd_extensions': {'baseline': ['NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD'],
                      'found': ['ASIMDHP', 'ASIMDDP'],
                      'not_found': ['ASIMDFHM']}},
 {'architecture': 'armv8',
  'filepath': '~/.virtualenvs/exp/lib/python3.10/site-packages/numpy/.dylibs/libopenblas64_.0.dylib',
  'internal_api': 'openblas',
  'num_threads': 10,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]
```

### Context for the issue:

_No response_

**Comment by snorfyang** [comment] 2023-08-04 07:05
Hey, Iet me take this.

**Comment by jacobdadams** [comment] 2023-09-26 15:26
I just experienced something similar with strings, which makes me think it may be due to how pandas handles their "new" nullable types as hinted at by @snorfyang:

```python
import pandas as pd
df = pd.DataFrame({'x': ['a', 'a', 'b', 'c']})
[df.x == 'a', df.x == 'b'][0].dtype  # dtype('bool')
df['x'] = df['x'].astype('string')
[df.x == 'a', df.x == 'b'][0].dtype  # BooleanDtype
```

**Comment by datajungler** [comment] 2023-10-28 08:04
The error actually is not due to `BooleanDtype` of the input conditional array since both `dtype('bool')` and `BooleanDtype` have the same value of their attributes of `.dtype.type`, i.e., `np.bool_`.

```
condlist = [df.x <= 2, df.x <  4]
df['x'] = df['x'].astype('Int64')
condlist_int64 = [df.x <= 2, df.x <  4]

print(condlist[0].dtype.type)
>>> numpy.bool_
print(condlist_int64[0].dtype.type)
>>> numpy.bool_
```

The root cause is that when running through the `np.select` method, any `BooleanDtype` array is automatically converted to be the `object` `dtype` via `np.broadcast_arrays`. 

```
np.broadcast_arrays(condlist)
>>> [array([[ True,  True, False, False],
        [ True,  True,  True, False]])]
np.broadcast_arrays(condlist_int64)
>>> [array([[True, True, False, False],
        [True, True, True, False]], dtype=object)]
```

So, it can be resolved by fixing the `dtype` of the output array as `np.bool_`  given the same `dtype` of input.

**Comment by ngoldbaum** [comment] 2023-10-31 16:20
I don't see how this is a bug in numpy. Has anyone tried reporting this to pandas? This seems like an issue with the design of pandas' nullable dtypes.

**Comment by datajungler** [comment] 2023-11-03 12:19
Just checked, there has been a very similar issue raised from pandas (https://github.com/pandas-dev/pandas/issues/43228).
According to PR #19777, it is required to fix by Pandas side (https://github.com/numpy/numpy/pull/19777)

**Comment by ngoldbaum** [comment] 2023-11-03 13:46
Thanks for finding the pandas issue, I'd suggest looking over there for a solution.

**Closed** 2023-11-03 13:46 UTC
Labels: 00 - Bug
