### ISSUE TITLE
BUG: Large integer arrays are silently coerced to float rather than uint64

### ISSUE THREAD

**Issue by gavinpotter** [numpy/numpy#16030] opened 2020-04-21 11:10 UTC
**List of Python 8 byte integers are not always correctly converted to np.uint64 arrays.**

Lists of 64 bit integers are inconsistently converted into np.arrays.  For example, If you convert the list  "test" below, the values in the array are not the same as the values in the original list.  If, however, you take the first 3 items they do get converted correctly.  If you convert the items individually you also get the correct results.  

Any views?  

```python
import numpy as np
test =[2573020360226874006, 3380361604350789900, 4859923904345895640, 13687853399390180967]


print("A list of 4 integers - Note: they are not identical")
print(test)
converted_numbers = np.array(test).astype(np.uint64)
print(converted_numbers)
print(" ")

print("The first 3 integers - Note they are identical")
test1 = test[:-1]
print(test1)
converted_numbers1 = np.array(test1).astype(np.uint64)
print(converted_numbers1)
print(" ")

print("The last integer")
test2 = test[-1]
print(test2)
converted_numbers2 = np.array([test2]).astype(np.uint64)
print(converted_numbers2)

print("\n","The integers converted individually")
for num in test:
	z = np.uint64(num)
	print(num,z)

```
**Output from the above**
A list of 4 integers - Note: they are not identical
[2573020360226874006, 3380361604350789900, 4859923904345895640, 13687853399390180967]
[ 2573020360226873856  3380361604350790144  4859923904345895936 13687853399390181376]
 
The first 3 integers - Note they are identical
[2573020360226874006, 3380361604350789900, 4859923904345895640]
[2573020360226874006 3380361604350789900 4859923904345895640]
 
The last integer
13687853399390180967
[13687853399390180967]

 The integers converted individually
2573020360226874006 2573020360226874006
3380361604350789900 3380361604350789900
4859923904345895640 4859923904345895640
13687853399390180967 13687853399390180967

### Numpy/Python version information:

![image](https://user-images.githubusercontent.com/41059217/79859329-be711000-83c8-11ea-8e37-f0e6d7b80fc5.png)

**Comment by eric-wieser** [comment] 2020-04-21 11:22
The real problem here is that the values are being converted to float, which loses precision
```python
>>> np.array([2573020360226874006, 3380361604350789900, 4859923904345895640, 13687853399390180967])
array([2.57302036e+18, 3.38036160e+18, 4.85992390e+18, 1.36878534e+19])
```
Specifying the array type immediately rather than casting back from float to uint64 will fix the issue:
```python
>>> np.array([2573020360226874006, 3380361604350789900, 4859923904345895640, 13687853399390180967], dtype=np.uint64)
array([ 2573020360226874006,  3380361604350789900,  4859923904345895640,
       13687853399390180967], dtype=uint64)
```

**Comment by gavinpotter** [comment] 2020-04-21 12:47
Ok - thanks and thanks for the solution.

**Comment by vrakesh** [comment] 2020-04-21 22:03
The coersion seems to occur only when there are four or more big integers, looking into this.

**Comment by eric-wieser** [comment] 2020-04-21 22:11
You're sure it's not just that your first 3 fit in a int64?

**Comment by vrakesh** [comment] 2020-04-21 22:57
I used the same values, suggested above, here is some further testing information. And my assumption above was wrong

If we use duplicates of the same value

```python
x = np.array([4859923904345895640,4859923904345895640,4859923904345895640,4859923904345895640,])
>>> x.dtype
dtype('int64')
>>> np.array([13687853399390180967,13687853399390180967])
array([13687853399390180967, 13687853399390180967], dtype=uint64)

```

If we use one different value additionally

```python
x = np.array([4859923904345895640, 13687853399390180967])
>>> x.dtype
dtype('float64')
>>> 
```
So it looks like more than one big uint64 size number causes this, likely while copying in ``_array_fromobject``` ??

**Comment by seberg** [comment] 2020-04-21 23:10
NumPy "discovers" the dtype of integers by checking their value. Basically, it will use the first value in a row of possible types `long -> int64 -> unint64 -> Python Object` and probably there is an `unsigned long` after the long, but I would have to check that and on many platforms `long` and `int64` are identical.

One of the things we really need to get rid of :).

**Comment by gavinpotter** [comment] 2020-04-22 07:49
Just  to give the motivating example and why it matters.  These numbers are lists of 64 bit xxhashes.  They are all uint64 but many could, of course, fit into smaller datatypes. I can imagine that there could be quite a number of people who might fall into the same trap that I did.  I'm a great believer in adding notes to documentation when there are issues that might take some time to resolve (like this one?  I appreciate its complexity.)  The relevant current documentation is shown below:

dtype : data-type, optional
The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence. This argument can only be used to ‘upcast’ the array. For downcasting, use the .astype(t) method.

How about:
dtype : data-type, optional
The desired data-type for the array. If not given, then the system will attempt to find the minimum type required to hold the objects in the sequence.  For absolute certainty about the data type to be used we recommend that the data-type is specified.  This argument can only be used to ‘upcast’ the array. For downcasting, use the .astype(t) method.

**Comment by seberg** [comment] 2020-04-22 14:49
Hmmm, that current "only to upcast" statement seems wrong. We force cast here for as long as I can remember, although that has its downsides... (Maybe it changed, but it would have to be in 1.7 or well before).

I am unsure if I think that exact additional sentence helps much, but a clarifying addition is always good.  Python integers are probably the only real confusion here (unless you have mixed types), so we could point that out specifically maybe also in a notes section?

**Comment by gavinpotter** [comment] 2020-04-22 17:23
That makes sense, your idea is better.  I agree its only really Python integers that are going to cause a problem.

**Comment by eric-wieser** [comment] 2020-11-09 17:26
Duplicate of #16287

**Closed** 2020-11-09 17:26 UTC
Labels: 04 - Documentation, 07 - Deprecation, component: numpy.core
