### ISSUE TITLE
ENH: RDRAND in numpy to improve performance 

### ISSUE THREAD

**Issue by VictorRodriguez** [numpy/numpy#9365] opened 2017-07-06 00:28 UTC
I would like to know how to use RDRAND instead of PRNG inside the numpy code. most of my code make calls to np.random.rand and np.random.randn. Just a bit if guidance is more than welcome.

**Comment by rkern** [comment] 2017-07-06 00:57
The core uniform PRNG is not yet replaceable. The mechanism for doing this is being developed here as an external package: https://github.com/bashtage/ng-numpy-randomstate

It does not yet have RDRAND implemented, but you are more than welcome to contribute it. It may be a little tricky to get the build infrastructure such that the availability of the RDRAND instruction is detected and gracefully ignored when it is not available.

**Comment by njsmith** [comment] 2017-07-06 02:35
RDRAND is also problematic because it gives real entropy. You can't get reproducible results from an RDRAND-based generator. Its intended use case is cryptographic applications, not numerical simulation.

It also sounds like it's [quite slow](https://en.wikipedia.org/wiki/RdRand#Performance). Assuming the numbers from wikipedia of a 4500 MHz processor needing 463 cycles to generate a 64-bit output, that's 4500 / 463 * 64 = 622 Mb/s, or about [100x slower than PCG](http://www.pcg-random.org/rng-performance.html). In fact it's slow even for a cryptographical PRNG – `openssl speed -evp chacha20` on my laptop manages ~20 Gb/s without hardware acceleration (if you generate >=1024 bytes at a time).

**Comment by njsmith** [comment] 2017-07-06 02:54
Also, it looks like every CPU with an RDRAND supports also supports [AES-NI](https://en.wikipedia.org/wiki/AES_instruction_set); if you want a hardware-accelerated RNG in numpy then this is way more useful. `openssl speed -evp aes-128-ctr` runs at ~35 Gb/s on my laptop with full support for seeding and with ridiculous overkill levels of RNG quality.

**Comment by bashtage** [comment] 2017-07-06 10:13
I think `RDRAND` doesn't make much sense as an underlying PRNG. 

@VictorRodriguez why do you need `RDRAND` for simulating normals?  If you need faster normals then you can use the `randomstate` package which contains the ziggurat generator.  Using a faster PRNG + ziggurat is 4-7x faster than the numpy randn implementation.

**Comment by VictorRodriguez** [comment] 2017-07-09 21:34
Thanks fo the quick feedback, I am going to do more experiments and come back with a proposal.  My intention is to improve the performance of numpy measured by benchmarks like Phoronix  /numpy benchmark and others. Doing a simple grep I found that np.rand ( and similars ) are one of the most used functions on numpy benchmarks.

**Comment by rkern** [comment] 2017-07-10 01:06
I'm sure that they do frequently show up in benchmark code, but they are usually not the focus of the benchmarks themselves. They are used to provide random data for the benchmarked code to operate on. Speeding up the random number functions won't speed up most benchmarks. I assume you are looking at benchmarks like [this one](https://openbenchmarking.org/innhold/3ca0b23d9bf6abb4028a7168871714509f263da8)?

You will notice that almost all of the `np.random` function calls are in the setup sections, not the timed parts of the benchmarks.

In any case, as @njsmith points out, `RDRAND` will probably be slower than things already implemented.

**Comment by simsong** [comment] 2018-12-30 00:00
`RDRAND` is incredibly important for applications where cryptographic-quality random number generation is important. For example, if you are implementing an algorithm that uses differential privacy, then the randomness of the distribution is essential to protecting privacy. In this situation _ you categorically do not want to have reproducible randomness_. Furthermore, `RDRAND`' s performance of [800MBytes/sec ](https://software.intel.com/en-us/articles/intel-digital-random-number-generator-drng-software-implementation-guide) is quite adequate. (In my application, I need to generate approximately 100 billion floating point random numbers; the application is running on a cluster with approximately 600 cores.)

**Comment by njsmith** [comment] 2018-12-30 00:48
@simsong As noted above, the prerequisite to supporting crypto-PRNGs in `numpy.random` is for `numpy.random` to support pluggable generators at all. I don't think there's been much progress on that, but it's just due to lack of interested parties working on it, so if you wanted to contribute there I think it would be welcome. And once that's implemented, there wouldn't be anything stopping you from implementing a generator using whatever mechanism you like, including RDRAND.

I doubt numpy will ever ship a RDRAND-based generator itself, because (a) RDRAND is inferior to other crypto-PRNGs (and isn't designed to replace them), and (b) we're not crypto experts so we probably shouldn't maintain crypto code or make any claims about crypto quality. But that's fine, numpy just needs to provide the infrastructure to let you plug in your favorite generator.

**Comment by simsong** [comment] 2018-12-30 00:56
@njsmith , thanks for the rapid response. As you may be aware, Intel has created the [Intel® Distribution for Python](https://software.intel.com/en-us/distribution-for-python) which has NumPy that's accelerated "integrated Intel® Performance Libraries such as Intel® Math Kernel Library and Intel® Data Analytics Acceleration Library." This includes a new module that replaces `numpy.random` called `numpy.random_intel`. I have not had a chance to try this yet.

I can certainly see giving numpy a simple switch for the RNG the way that, say, OpenSSL has a switch for engines. Are there any other pluggable systems for numpy? It doesn't seem that Intel has implemented a switch either, so there is some design work that would need to be done. I can see simply making it some kind of new top-level `select()` or `config()` function. What is your preference?

**Comment by simsong** [comment] 2018-12-30 00:58
Oh, @njsmith, one other thing — please do not say "RDRAND is inferior to other crypto-PRNGs." It is not inferior. It is different. `RDRAND` is a hardware RNG that is being extended with AES running in counter mode. Being able to generate 800MBytes/sec of random numbers that can resist anything but an adversary that is either computationally unbounded or else one that can crack AES is quite an accomplishment, and it is useful for many applications.

**Comment by simsong** [comment] 2018-12-30 05:00
Okay, I've looked at the intel `random_intel` code. It's hard to figure out what's going on, but it looks like it's a passthrough to `OpenSSL`'s random functions, and that OpenSSL now directly supports RDRAND (see https://wiki.openssl.org/index.php/Random_Numbers and https://software.intel.com/en-us/blogs/2014/10/03/changes-to-rdrand-integration-in-openssl). Apparently OpenSSL's developers do not want to rely on a single entropy source, and so they will not rely solely on RDRAND. Which probably makes sense. The Intel blog is worth reading.

**Comment by rkern** [comment] 2018-12-30 06:01
The work on the pluggable PRNG system is going on here: https://github.com/bashtage/randomgen/

The details will likely not change much between now and when `randomgen` is adopted into numpy, so feel free to start implementing against `randomgen`.

**Comment by bashtage** [comment] 2019-01-04 18:23
@simsong It should be fairly straightforward to implement as long as it can provide 64-bit uints. I think it would be difficult to include in NumPy due to portability but could be a stand-alone "Basic RNG" (which is what I've called the core PRNGs in randomgen).  These basic RNGs more-or-less* need to provide opaque function pointers that return the next 64 bits, 32 bits or double.  For most modern PRNGs that are 64 bits, the 32bits and double are just extracted from the 64-bit value. 

* Plus other house-keeping functions to get/set state and initialize (if needed).

**Comment by simsong** [comment] 2019-01-05 15:06
@bashtage , I'm not sure why it would be difficult to include in NumPy due to portability. It's just some assembler. If the assembler isn't available, we aren't on an Intel machine and we don't have the instructions. I will be looking into this, but realistically over the next 2-3 months. We are also deciding if we should just move over to the Intel Python distribution. However, their integration is not as clean, strangely, and there are people who have reported performance penalties with the Intel release.

**Comment by rgommers** [comment] 2019-01-05 19:33
> It's just some assembler. If the assembler isn't available, we aren't on an Intel machine and we don't have the instructions.

We won't include things that are only available on a small subset of all the hardware we support. We also don't want to include assembler code. Both are not maintainable for us.

**Comment by simsong** [comment] 2019-01-05 19:45
if that's true, then there is no way to support the Intel hardware random number generator RDRAND, because it's accessed through an Intel assembler instruction.

**Comment by njsmith** [comment] 2019-01-05 20:31
There may be intrinsics that let you access it without asm code. But NumPy has to support a variety of compilers, and they sometimes have strange limitations, so someone would have to do the research.

But again, even if the technical issues were worked out, numpy is unlikely to support this natively because we don't have the infrastructure and expertise to safely maintain crypto code, and because RDRAND isn't even popular with cryptographers. The way to do this is as a third-party pluggable backend, where you can take responsibility for your own security and algorithm choices while still using the rest of numpy's infrastructure.

**Comment by simsong** [comment] 2019-01-05 21:47
So your idea is that there is a randomness function which returns N random bytes, and by default it is the Mersenne Twister but that I could replace it in my application with my own user-specified function, which performs the call to RDRAND and provides random bytes?

**Comment by bashtage** [comment] 2019-01-05 21:50
Yes, this exact structure exists in randomgen which will likely serve as
the next gen random number generator in NumPy. Right now randomgen supports
about 10 different PRNG, including legacy MT19937, dSFMT, lots of Xor based
PRNGS, PCG, and some of the Random123 generators.

**Comment by simsong** [comment] 2019-01-05 21:54
Okay, if that exists, then I don't really need to do anything, other than wait for the next release of NumPy?

**Comment by bashtage** [comment] 2019-01-05 21:58
Well, someone will need to write the Basic PRNG that supports drawing using
RDRAND.

As an example, it is pretty easy to write a basic PRNG that uses urandom as
a source on Linux or the equiv crypto provider on Windows. This isn't super
useful in Monte Carlos and so I never pursued this (even though randomgen
provides a function that uses these to fill uint arrays. This function is
used to initialize PRNGs when no seed is set.)

**Comment by simsong** [comment] 2019-01-05 22:05
I'm confused. You just said that you would not accept any code that was processor specific or that included assembler. RDRAND is processor specific. It is only available on Intel. It is only accessible using a specific Intel-specific assembler instruction.

You said that the new version of Numpy will support pluggable random number generators. If so, then I can just use my existing RDRAND implementation with the new Numpy, and I do not need to contribute anything to this release. 

it's not clear to me why you believe that reading random numbers from urandom isn't useful for a Monte Carlo simulation. Isn't `/dev/urandom` good enough for your simulations?

**Comment by bashtage** [comment] 2019-01-05 22:11
That is correct. However with the new infrastructure you could publish a
package called, say, randomgen-rdrand that provides the basic RNG, and then
use it by

```python
from randomgen import RandomGenerator
from randomgen_rdrand import RDRAND

gen = RandomGenerator(RDRAND())
```

**Comment by simsong** [comment] 2019-01-05 22:15
Right. That makes sense! So I'll close this ticket and wait for the new NumPy to come out.

**Comment by simsong** [comment] 2019-01-05 22:16
Looks like you need to close it.

**Closed** 2019-01-05 22:31 UTC
Labels: 01 - Enhancement, component: numpy.random

**Comment by bashtage** [comment] 2020-05-29 06:27
Yes. You should be able to stick the RDRAND bit generator from `randomgen` into a NumPy Generator, if one wanted to. It is very slow.

**Comment by simsong** [comment] 2020-05-29 14:28
> Yes. You should be able to stick the RDRAND bit generator from `randomgen` into a NumPy Generator, if one wanted to. It is very slow.

Speed is really a relative term. We have a cluster with 20 machines, each with 96 cores.  With 8 cores per die, there are 12 8-core processors. There is only 1 random number generator per die. So we have 12*20=240 true random number generators. According to [Intel's documentation](https://software.intel.com/content/www/us/en/develop/articles/intel-digital-random-number-generator-drng-software-implementation-guide.html), serving 64-bit RDRAND requests, the capped ceiling is 800MB/sec. So we can generate 800 * 240 = 192,000 MB/sec, or 192 GB/sec of random numbers, or 48 billion 32-bit random numbers in a second, which is sufficient for our application.  You may need more random numbers per second, or you may have fewer cores, but that is application-specific and should not impact the underlying software engineering.


In any event, when you say that I can patch this into a Numpy Generator, are you referring to https://github.com/bashtage/randomgen?  Can you point me at documentation that would explain how to make numpy use my version? I assume that I can do this without rebuilding all of numpy, but it is not clear from [the NumPy 1.8 documentation on numpy.random](https://numpy.org/doc/1.18/reference/random/index.html) how I would pass in my own rng.  I've also reviewed [NEP 19](https://numpy.org/neps/nep-0019-rng-policy.html)  and it isn't clear from that. So if you have a moment, I would really appreciate a few lines of the Python to glue together numpy's `numpy.random` with my own random bit generator.

Thanks!

**Comment by bashtage** [comment] 2020-05-29 14:56
The only documentation is here as far as I know.

https://bashtage.github.io/randomgen/extending.html#new-bit-generators

**Comment by simsong** [comment] 2020-05-29 15:34
> I would still suggest using `AESCounter`
> 
Thanks for the suggestion to use AESCounter(). In fact, Intel implemented the RDRAND instruction with a AES in counter mode internally for 511 out of 512 draws on the entropy source.  (The entropy pool is from thermal noise, which is then hashed and used for AES in counter mode.) The problem with AESCounter() is that it seeds from `/dev/urandom`, which is not a high-quality random number source when operating in Amazon Web Services. This is why the AWS Key Management Service has a feature for generating random numbers: `/dev/urandom` doesn't access RDRAND (I reviewed the source code), and its source of "randomness" are just not very random when running in AWS.

I am drafting a technical article on this; if you have interest, we would be happy to have you review it off-list.

**Comment by bashtage** [comment] 2020-05-29 15:42
You can combine the two if you have bad or undertain entropy:

```
from randomgen import RDRAND, AESCounter
from numpy.random import Generator
seed_counter = RDRAND().random_raw(4)
aes = AESCounter(seed=seed_counter[:2], counter=seed_counter[2:], mode="sequence")
gen = Generator(aes)
```

Happy to take a look.

**Comment by simsong** [comment] 2020-05-31 00:55
Thanks! That works really well. Will follow-up off-list.

**Comment by VictorRodriguez** [comment] 2020-06-01 14:48
Thanks a lot for all, it works pretty well

**Comment by simsong** [comment] 2020-06-02 00:27
In testing today, we found that RDRAND's speed on our servers was on-par with AESCounter. Both blew away /dev/urandom (which is, presumably, single-threaded).

**Comment by simsong** [comment] 2020-06-03 01:40
@bashtage  — I sent you a copy of the paper off list and didn't get a response; did I send it to the correct address?
