### ISSUE TITLE
bitwise_and with uint64

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#2955] opened 2013-02-01 09:43 UTC
The bit-wise `&` operator works fine with all Numpy integer types, except `uint64`:

```
In [13]: np.int64(123) & 0xffff
Out[13]: 123

In [14]: np.uint64(123) & 0xffff
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Volumes/Raptor/<ipython-input-14-42f055b9f958> in <module>()
----> 1 np.uint64(123) & 0xffff

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'
```

Even Python long integers can be used, so is there a reason why `np.uint64` cannot be used, or is it a bug?

**Comment by jrmlhermitte** [comment] 2017-11-15 19:35
Same problem. Broadcasting to array also works
```python
import numpy as np
a = np.ones(2, dtype=np.uint64)
# this works
a&1
# but this
a[0]&1
# gives this error
#---------------------------------------------------------------------------
#TypeError                                 Traceback (most recent call last)
#<ipython-input-43-e0a82b0140e0> in <module>()
#----> 1 a[0]&1
#
#TypeError: ufunc 'bitwise_and' not supported for the input types, and the
#inputs could not be safely coerced to any supported types according to the
#casting rule ''safe''
#

# but this works
a = np.ones(2, dtype=np.uint32)

a[0]&1
```

workaround also works for me. 

Is there a PR for this yet?

**Comment by seberg** [comment] 2022-11-19 13:47
Closing as duplicate of gh-22624

**Closed by seberg** 2022-11-19 13:47 UTC
