### ISSUE TITLE
BUG: Incorrect behavior

### ISSUE THREAD

**Issue by RohitMugalya** [numpy/numpy#24465] opened 2023-08-20 16:20 UTC
### Describe the issue:

the issue was when casting the dtype of vals in arr into boolean.

### Reproduce the code example:

```python
>>>import numpy as np
>>>arr = np.arange(1, 17).reshape(4, 4)
>>>arr
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
>>>arr.shape
(4, 4)
>>>arr.dtype = bool
>>>arr
array([[ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False,  True, False, False, False]])
>>>arr.shape
(4, 16)
```

### Error message:

```shell
this is a wrong behavior
```

### Runtime information:

1.25.1
3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

### Context for the issue:

I found this when I was learning in ipynb
I was a learner in np and pd.

**Comment by rkern** [comment] 2023-08-20 16:31
Dupe of #24464

**Closed by rkern** 2023-08-20 16:31 UTC
Labels: 50 - Duplicate
