### ISSUE TITLE
Concatenation issue during array transformation 

### ISSUE THREAD

**Issue by kroppian** [numpy/numpy#16785] opened 2020-07-08 19:14 UTC
I'm getting this weird concatenating issue when trying to transform a numpy array. When I filter by the 2nd column of the array, I get correct results, but when I filter by the third, the dtype is changed to U1, and the text is truncated. 

### Reproducing code example:

```python
import numpy as np

dat = np.array([[2.017298e+06, 7.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00], 
                [2.017299e+06, 7.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00], 
                [2.017199e+06, 0.000000e+00, 2.000000e+02, 0.000000e+00, 0.000000e+00], 
                [2.017135e+06, 0.000000e+00, 7.000000e+01, 1.000000e+01, 4.000000e+00]])

resA = np.apply_along_axis( (lambda a : "foo" if (a[1] != 0) else "" ), 1, dat)

resB = np.apply_along_axis( (lambda a : "foo" if (a[2] != 0) else "" ), 1, dat)

print("Res A")
print(resA)
print("Res B")
print(resB)
```

### Output message:
I expected: 
```
Results
Res A
['foo' 'foo' '' '']
Res B
['' '' 'foo' 'foo']
```
But got: 
```
Results
Res A
['foo' 'foo' '' '']
Res B
['' '' 'f' 'f']
```

### Numpy/Python version information:

1.18.1 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0]

**Comment by eric-wieser** [comment] 2020-07-08 19:19
Duplicate of#8352

**Closed by eric-wieser** 2020-07-08 19:19 UTC
