### ISSUE TITLE
delegation to reverse operators alters the operand types

### ISSUE THREAD

**Issue by NeilGirdhar** [numpy/numpy#9677] opened 2017-09-11 13:36 UTC
```
    In [1]: import numpy as np
       ...:
       ...: x = np.float32(4)
       ...:
       ...: class A:
       ...:
       ...:     def __add__(self, other):
       ...:         print(type(other))
       ...:
       ...:     def __radd__(self, other):
       ...:         print(type(other))
       ...:
    
    In [2]: A() + x
    <class 'numpy.float32'>
    
    In [3]: x + A()
    <class 'float'>
```

It seems that numpy is manually delegating to `__radd__` rather than letting Python do its thing with the operands unaltered.  This makes numpy types hard to use.

**Comment by mhvk** [comment] 2017-09-11 19:46
numpy is exceedingly greedy and rather than deferring by returning `NotImplemented`, it turns any other argument into an array with object dtype. It will then iterate over this array, and for each element try to execute the operation. You can see this by making `x` an array:
```
In [11]: x = np.array([1., 2.])

In [12]: A() + x
<class 'numpy.ndarray'>

In [13]: x + A()
<class 'float'>
<class 'float'>
Out[13]: array([None, None], dtype=object)
```
Right now, the only way to avoid this is to define `__array_priority__ = <some high number>` or, in numpy >=1.13, `__array_ufunc__ = None`.

p.s. Many of us would like to get rid of this behaviour, but this is not so easy, since existing code would break.

**Comment by NeilGirdhar** [comment] 2017-09-12 01:57
Thanks for the explanation.  On line 13, why is the result `float` and not `np.float64`?  Why not preserve the numpy type when making the calls?  If the type were `int16`, you would end up silently widening to `int`, and that seems bad.

I guess the motivation was to work with code that does `isinstance(…, int)`, but that code is usually wrong.  It should say `isinstance(…, numbers.Integer)`.

**Comment by mhvk** [comment] 2017-09-12 13:04
I'm actually not completely sure about the underlying logic, but I think it is that if one interacts with an object, then any items in an array are turned into python objects. But, again, best to simply avoid being turned into a `dtype=object` array in the first place...

**Comment by NeilGirdhar** [comment] 2017-09-12 18:05
But `np.float64(1.0)` is a Python object.  I don't see why this can't be fixed today?

**Comment by seberg** [comment] 2024-01-20 08:35
Going to close this, yes there are issues, but the delegation itself is "by design" (for better or worse) and the way to tell NumPy to not do this has been mentioned.

(I would be happy to have a new issue around how one might get away from this greediness)

**Closed by seberg** 2024-01-20 08:35 UTC

**Comment by NeilGirdhar** [comment] 2024-01-20 08:47
Can we at least ensure that the array API promises that this won't happen for valid implementations?

**Comment by seberg** [comment] 2024-01-20 08:51
Frankly, if you want to add such a promise there (which is an issue for the Array API), you better have an idea how to pull of changing it in NumPy.  Saying numpy must change it is useless if it can't.

The Array API does not even *define* a way to mix array objects, interacting with a custom object is undefined to begin with anyway.

**Comment by NeilGirdhar** [comment] 2024-01-20 10:58
Right, that makes sense.  However, I'm not proposing that NumPy change its implementation.  I'm proposing that the NumPy array that implements the array API return `NotImplemented` in the above case—rather than leaving this to be implementation defined.
