### ISSUE TITLE
python-numpy update recreates bug that crashes Kodi 19 which was fixed by python pillow on Arch Linux.

### ISSUE THREAD

**Issue by cgcgcgcgcg** [numpy/numpy#18848] opened 2021-04-25 03:04 UTC
When python-pillow updated on 2021-04-23, Kodi worked fine, but one day later python-numpy updated and crashing began again.
https://github.com/python-pillow/Pillow/pull/5323

**Comment by charris** [comment] 2021-04-25 03:15
Does anyone know what the bug is?

**Comment by cgcgcgcgcg** [comment] 2021-04-25 03:21
> Does anyone know what the bug is?
It all started here:
https://github.com/python-pillow/Pillow/issues/5320

**Comment by cgcgcgcgcg** [comment] 2021-04-25 03:21
> Does anyone know what the bug is?

It all started here.
https://github.com/python-pillow/Pillow/issues/5320

**Comment by rkern** [comment] 2021-04-25 03:33
I believe we're already tracking the root cause (lack of sub-interpreter support) in #18586. The updates "fixing" and "unfixing" the Kodi problems are probably just red herrings.

**Comment by cgcgcgcgcg** [comment] 2021-04-25 08:27
> I believe we're already tracking the root cause (lack of sub-interpreter support) in #18586. The updates "fixing" and "unfixing" the Kodi problems are probably just red herrings.

I'm in no position to help, can follow what others have talked about, but no real python knowledge at all.
I know that I daily use Kodi 19 via Flatpak because Arch package crashes a lot.
The exception was one day after I updated python-pillow, and the next day python-numpy updated and crashes started again.
If it helps here's where the Flatpak working version is:
https://flathub.org/apps/details/tv.kodi.Kodi

And the only thing I could get is what is installed by that -I don't know if it uses another pillow or numpy or just disables them:
![ksnip_20210425-111847](https://user-images.githubusercontent.com/38960370/115986490-1b456e80-a5b9-11eb-85ff-a8ac676aee45.png)

**Comment by rkern** [comment] 2021-04-25 15:20
I'm sorry you are getting bounced around from repo to repo, but there's no bug in numpy that we re-introduced recently. numpy has never supported being run in Python sub-interpreters. Probably what changed is something in one of the Kodi plugins, like TMDbHelper, causing an import of numpy (probably through Pillow). If Kodi has moved to using sub-interpreters, all of the plugins will have to studiously avoid importing numpy entirely.

**Comment by cgcgcgcgcg** [comment] 2021-04-25 21:47
> I'm sorry you are getting bounced around from repo to repo, but there's no bug in numpy that we re-introduced recently. numpy has never supported being run in Python sub-interpreters. Probably what changed is something in one of the Kodi plugins, like TMDbHelper, causing an import of numpy (probably through Pillow). If Kodi has moved to using sub-interpreters, all of the plugins will have to studiously avoid importing numpy entirely.

TMDBH's dev changed his addon, and that worked ever since, and his changes led a reader to suggest the pillow fix which seemed to work for a day until the python-numpy updated.
You are right, if I try Arch's Kodi it crashes on several different occasions, both skin and addons related.
From the start Kodi devs said this ain't their fault and pointed to Linux "faulty" libs -which I know might simply be not true.
The only thing I and others can do is wait.

**Comment by rkern** [comment] 2021-04-26 00:50
> The only thing I and others can do is wait.

Not necessarily. Try, for example, temporarily inserting a `raise RuntimeError()` at the top of `numpy/__init__.py` and starting up Kodi. I'm not familiar with Kodi, so you'll have to find out how Kodi logs Python tracebacks from it and its plugins. That traceback should show you which part of Kodi or its plugins is importing `numpy` (possibly through an intermediate like Pillow). You will have to modify _that_ code to not attempt importing `numpy` (or the intermediate library).

Since `numpy` has never worked with sub-interpreters, the (re)introduced bug is in the code that is trying to import `numpy`, so I'm going to close this.

**Closed by rkern** 2021-04-26 00:50 UTC

**Comment by cgcgcgcgcg** [comment] 2021-05-16 12:12
> > The only thing I and others can do is wait.
> 
> Not necessarily. Try, for example, temporarily inserting a `raise RuntimeError()` at the top of `numpy/__init__.py` and starting up Kodi. I'm not familiar with Kodi, so you'll have to find out how Kodi logs Python tracebacks from it and its plugins. That traceback should show you which part of Kodi or its plugins is importing `numpy` (possibly through an intermediate like Pillow). You will have to modify _that_ code to not attempt importing `numpy` (or the intermediate library).
> 
> Since `numpy` has never worked with sub-interpreters, the (re)introduced bug is in the code that is trying to import `numpy`, so I'm going to close this.
https://github.com/python-pillow/Pillow/issues/5320#issuecomment-841797596

**Comment by cgcgcgcgcg** [comment] 2021-05-17 06:05
I decided to edit directly line 37 of /home/k/.kodi/addons/script.module.websocket/lib/websocket/_abnf.py and replace "import numpy" with:
numpy = None

After initial testing this seems to solves crashes on Arch Linux and Kodi 19.1 seems to work fine.
