### ISSUE TITLE
BUG: Numpy ma diff skipping the mask when using argument 'prepend'

### ISSUE THREAD

**Issue by jsaladich** [numpy/numpy#22465] opened 2022-10-21 09:41 UTC
### Describe the issue:

Hi ,

I have realized that when I pass a masked array in numpy ma diff ```np.ma.diff``` and prepend a masked intial value, the mask is deleted and replaced (in my case for 0. values). Despite being the ```fill_value``` different from 0.

I would expect that ```np.ma.diff``` keeps the mask after calculating the difference, specifically if you are prepending a masked array that keeps the same structure than the input array.
See below:

### Reproduce the code example:

```python
import numpy as np
# a is the dummy array
a = np.random.randn(5,10,10)
a = np.ma.masked_where(a<.1,a)
print(a.mask.any()) # returns True

b = np.ma.diff(a, prepend=a[:1,...],axis=0)
print(b.mask.any()) # returns False (unexpected)

# What I would expect / my workaround
c = np.ma.diff(np.ma.append(a[:1], a, axis=0),axis=0)
print(c.mask.any()) # returns True (as expected)
```

### NumPy/Python version information:

My numpy version is: '1.23.4' 
Python version is: 3.10.6

### Context for the issue:

Shouldn't np.ma module's objects respect always the input mask (if it is properly referenced in its arguments)?

Thanks a lot and keep on with the amazing numpy!

**Comment by markopacak** [comment] 2022-12-06 19:15
I'd like to take this, can someone assign me?

**Comment by markopacak** [comment] 2022-12-06 21:10
The bug is easily fixed by using `np.ma.concatenate` instead of the _non-ma_ version. See my branch:

https://github.com/numpy/numpy/blob/855f1f05e4b4607e22346dd9ec4557f4c92a55e5/numpy/lib/function_base.py#L1437

The problem is that `np.ma.diff` is generated from `np.diff`, so I had to modify the original. 
The solution to this would be to entirely copy `diff` inside the _ma_ module, so I can tweak it and leave the original untouched.

Notes:
- This fixes both _append_ and _prepend_
- All tests pass.

**Closed** 2023-01-18 23:40 UTC
Labels: 00 - Bug, component: numpy.ma
