### ISSUE TITLE
BUG: crash in `test_stringdtype.py::test_ufunc_multiply` under free-threaded build

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#27063] opened 2024-07-27 13:57 UTC
From [this CI log](https://github.com/numpy/numpy/actions/runs/10123674205/job/27997191826), which is from today's wheel build job on `main` for macOS arm64 (cp313t):
```
 _______________________ _core/tests/test_stringdtype.py ________________________
  [gw2] darwin -- Python 3.13.0 /private/var/folders/hn/5bx1f4_d4ds5vhwhkxc7vdcr0000gn/T/cibw-run-e0nrh73s/cp313t-macosx_arm64/venv-test-arm64/bin/python
  worker 'gw2' crashed while running "_core/tests/test_stringdtype.py::test_ufunc_multiply[float('nan')-False-short-other1-True]"
```

@ngoldbaum could you please look into this?

* * *

Unrelated: one more warning in that CI log about a test which re-enables the GIL:
```
  random/tests/test_extending.py::test_cython
    <frozen importlib._bootstrap>:488: RuntimeWarning: The global interpreter lock (GIL) has been enabled to load module 'extending', which has not declared that it can run safely without the GIL. To override this behavior and keep the GIL disabled (at your own risk), run with PYTHON_GIL=0 or -Xgil=0.
```

**Comment by ngoldbaum** [comment] 2024-07-30 16:45
I'm unable to reproduce the crash but have a fix for the other issue and the other warnings I see in the output you didn't call out: https://github.com/numpy/numpy/pull/27085

I guess we should just watch out for this crash? Maybe I can try to see if I can trigger the crash on the actions runner using tmate?

**Comment by ngoldbaum** [comment] 2024-07-30 19:11
Looking closer at the test output, I see the following slightly fishy error from the worker that died:

```
[gw2] node down: Traceback (most recent call last):
    File "/private/var/folders/hn/5bx1f4_d4ds5vhwhkxc7vdcr0000gn/T/cibw-run-e0nrh73s/cp313t-macosx_arm64/venv-test-arm64/lib/python3.13/site-packages/execnet/gateway_base.py", line 1050, in _local_receive
      data = loads_internal(data, channel, strconfig)
    File "/private/var/folders/hn/5bx1f4_d4ds5vhwhkxc7vdcr0000gn/T/cibw-run-e0nrh73s/cp313t-macosx_arm64/venv-test-arm64/lib/python3.13/site-packages/execnet/gateway_base.py", line 1625, in loads_internal
      return Unserializer(io, channelfactory, strconfig).load()
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
    File "/private/var/folders/hn/5bx1f4_d4ds5vhwhkxc7vdcr0000gn/T/cibw-run-e0nrh73s/cp313t-macosx_arm64/venv-test-arm64/lib/python3.13/site-packages/execnet/gateway_base.py", line 1421, in load
      loader(self)
      ~~~~~~^^^^^^
    File "/private/var/folders/hn/5bx1f4_d4ds5vhwhkxc7vdcr0000gn/T/cibw-run-e0nrh73s/cp313t-macosx_arm64/venv-test-arm64/lib/python3.13/site-packages/execnet/gateway_base.py", line 1488, in load_py3string
      self.stack.append(as_bytes.decode("utf-8"))
      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/var/folders/hn/5bx1f4_d4ds5vhwhkxc7vdcr0000gn/T/cibw-run-e0nrh73s/cp313t-macosx_arm64/venv-test-arm64/lib/python3.13/site-packages/xdist/dsession.py", line 415, in _handlefailures
      if rep.failed:
         ^^^^^^^^^^
  AttributeError: 'str' object has no attribute 'failed'
```

It looks like deadsnakes is still installing 3.13b3, which I think is affected by https://github.com/python/cpython/issues/121368, so whenever deadsnakes updates I predict this crash will go away.

**Comment by ngoldbaum** [comment] 2024-08-12 18:08
Hasn't recurred AFAIK so closing

**Closed by ngoldbaum** 2024-08-12 18:08 UTC
Labels: 00 - Bug, component: numpy._core, 39 - free-threading
