### ISSUE TITLE
`np.fromfile` does not play well with `BZ2File` objects

### ISSUE THREAD

**Issue by mraspaud** [numpy/numpy#18760] opened 2021-04-12 22:00 UTC
I'm trying to read numpy arrays from a bz2 file using `fromfile`, but I don't get the expected results.
More specifically I can't round-trip a simple record array through `tofile`, bz2 compression, `bz2.open` and `fromfile`.
The `bz2.open` function claims that a file-object is returned: https://docs.python.org/3/library/bz2.html#bz2.open
and `fromfile` claims it can handle file-objects: https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html?highlight=fromfile#numpy.fromfile

but the results from my experiments shows that `fromfile` is accessing the compressed data, not the uncompressed data.

I understand that `fromfile` is a C function and thus I'm suspecting it isn't using the `BZ2File` methods for seeking, telling, reading etc...

### Reproducing code example:

```python
import numpy as np
import bz2

_BASIC_INFO_TYPE = np.dtype([("hblock_number", "u1"),
                             ("blocklength", "<u2"),
                             ("total_number_of_hblocks", "<u2"),
                             ("byte_order", "u1"),
                             ("satellite", "S16"),
                             ])

arr = np.array([(1, 282, 11, 0, b'Himawari-8')],
                dtype=_BASIC_INFO_TYPE)


arr.tofile('arr.bin')

# zip the resulting file:
with bz2.open('arr.bin.bz2', mode='wb') as zfd:
    with open('arr.bin', mode='rb') as fd:
        zfd.write(fd.read())


with bz2.open('arr.bin.bz2') as fd:
    arr = np.fromfile(fd, dtype=_BASIC_INFO_TYPE, count=1)
print(arr)
# erraneous (compressed data read directly, would return the same if doing `with open('arr.bin.bz2') ...`)
# [(66, 26714, 12601, 65, b'Y&SY\x85z\xe4}\x00\x00\x03\xfd\x80p\x08')]

with bz2.open('arr.bin.bz2') as fd:
    arr = np.frombuffer(fd.read(_BASIC_INFO_TYPE.itemsize), dtype=_BASIC_INFO_TYPE, count=1)
print(arr)
# correct
# [(1, 282, 11, 0, b'Himawari-8')]
```

### Error message:

No error message, just erraneous data.

If my assumption is correct that numpy's `fromfile` shortcuts the fileobject's `seek`, `read`, etc, then it will prevent the use of other file objects, like the ones returned by fsspec.

Note that I suspect the same problem is happening with `np.memmap`.

### NumPy/Python version information:

```
In [1]: import sys, numpy; print(numpy.__version__, sys.version)
1.20.1 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:21:18) 
[GCC 9.3.0]
```

**Comment by mraspaud** [comment] 2021-04-12 22:32
For the record, an example using `fsspec` accessing a similar file (~3MB) on anonymous aws s3 bucket:

```python
import numpy as np
import fsspec

filename = 'HS_H08_20210409_0800_B01_FLDK_R10_S0110.DAT.bz2'
to_get = 's3://noaa-himawari8/AHI-L1b-FLDK/2021/04/09/0800/' + filename
with fsspec.open(to_get, compression='bz2', anon=True) as fd:
    print(np.fromfile(fd, dtype='u1', count=1))

---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-35-9e9c8faa569c> in <module>
      5 to_get = 's3://noaa-himawari8/AHI-L1b-FLDK/2021/04/09/0800/' + filename
      6 with fsspec.open(to_get, compression='bz2', anon=True) as fd:
----> 7     print(np.fromfile(fd, dtype='u1', count=1))
      8 

~/miniconda3/envs/satpy-dev/lib/python3.8/bz2.py in fileno(self)
    143         """Return the file descriptor for the underlying file."""
    144         self._check_not_closed()
--> 145         return self._fp.fileno()
    146 
    147     def seekable(self):

UnsupportedOperation: fileno
```

**Comment by gerritholl** [comment] 2021-04-13 07:08
Duplicate of https://github.com/numpy/numpy/issues/1103 
Related: https://github.com/numpy/numpy/issues/7713

**Comment by seberg** [comment] 2021-04-14 18:59
Its true, it uses the file as a lowlevel file object.  We could try to reject it, we once had a PR to reject gzipped files explicitly IIRC, but I am not sure what came of it.  I will close it as a duplicate, although maybe it can bring back some energy to the old issue.

**Closed by seberg** 2021-04-14 18:59 UTC

**Comment by mraspaud** [comment] 2021-04-19 15:03
Maybe as a start, the documentation for the fromfile and memmap functions could be updated to mention `lowlevel` ?
