### ISSUE TITLE
DOC: Title bar overlaps focused heading anchor

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#17207] opened 2020-09-01 08:53 UTC
When we took on the new theme, we tweaked it to make the title bar taller. This change means that it overlaps focused headings:

https://numpy.org/devdocs/user/building.html#accelerated-blas-lapack-libraries

![image](https://user-images.githubusercontent.com/425260/91829072-df7c2400-ec38-11ea-8592-600638fe635b.png)

We should either remove this customization, or do a more thorough sweep of all the dimensions which assume its old value.

To fix this particular bug, we need to add -30px to the margin for `.header-style:before, h1:before, h2:before, h3:before, h4:before, h5:before, h6:before {`

cc @mattip

**Comment by mattip** [comment] 2020-09-01 10:30
Something is strange with the page layout. The `main` element runs all the way to the top of the page. Your workaround will fix the problem, but is there a better way to redo the way the theme lays out the page? @jorisvandenbossche thoughts?

**Comment by jorisvandenbossche** [comment] 2020-09-28 09:15
Sorry for the slow follow-up here. I remember we struggled with this as well in the theme as well (eg https://github.com/pandas-dev/pydata-sphinx-theme/issues/147), but I suppose the solution is too specific to the exact height of the navbar (which can be influenced by the image right now). 
Not directly a solution yet, but I opened an issue to track this on the theme's side as well: https://github.com/pandas-dev/pydata-sphinx-theme/issues/258

**Comment by mattip** [comment] 2021-01-25 15:17
Closed by updating the theme version to 0.4.2.

**Closed by mattip** 2021-01-25 15:17 UTC
Labels: 04 - Documentation

**Comment by jorisvandenbossche** [comment] 2021-01-25 15:46
I don't think this is fixed by 0.4.2 (it's only a tiny bug fix release to fix a xarray display compatibility issue, it was not a release of latest master). It is fixed on master though, for the upcoming 0.5 release (and then you will need to set a `--header-height` variable)

**Comment by mattip** [comment] 2021-01-25 15:51
Something changed. [This page](https://17941-908607-gh.circle-artifacts.com/0/doc/build/html/reference/generated/numpy.geterr.html#numpy.geterr) (from the CI build of the new theme) no longer overlaps for us. For the next few minutes, until CI finishes, you can see the old page [here](https://numpy.org/devdocs/reference/generated/numpy.geterr.html#numpy.geterr)

**Comment by jorisvandenbossche** [comment] 2021-01-25 16:05
Hmm, on my browser (firefox, Ubuntu), both links give the incorrect offset ..

**Comment by melissawm** [comment] 2021-01-25 16:12
On Firefox I can confirm the title is still overlapping for the CI build of the new theme.

**Comment by mattip** [comment] 2021-01-25 18:25
Ahh, I see. I chose a page that is quite small. Because of differing zoom betwee the two versions, in one case the whole page fit better and showed the header, on the more-zoomed-in one it did now.
