### ISSUE TITLE
Enable Quick Search in documentation

### ISSUE THREAD

**Issue by manuels** [numpy/numpy#8553] opened 2017-02-01 08:34 UTC
It would be handy if [Quick Search](http://www.sphinx-doc.org/en/1.5.2/web/quickstart.html) would be enabled in the numpy documentation.

Maybe there is a good performance reason not to do it - I don't know. But I did not find an older issue discussing this feature.

**Comment by pv** [comment] 2017-02-08 09:56
If it works, I think it could well be enabled.

**Comment by WarrenWeckesser** [comment] 2021-10-02 00:26
The link says "Quick Search", but the URL points to a page about the "quick start" of Spinx 1.5.2.  The page mentions enabling the search feature, but has nothing about "quick search".

The documentation has been overhauled since this issue was created.  The  sections "User Guide", "API Reference" and "Development" all have a search field at the top of the left sidebar.

I'm closing the issue, but feel free to comment or reopen if I misunderstood what the issue is about.

**Closed by WarrenWeckesser** 2021-10-02 00:26 UTC
