### ISSUE TITLE
BUG: escape sequence in string passed to repeat

### ISSUE THREAD

**Issue by Ruth-wj** [numpy/numpy#22070] opened 2022-08-01 11:33 UTC
### Describe the issue:

Due to me being a numpty and forgetting basic python syntax, I tried to do the following to scale a list by a factor.
```
multiplied_strings = np.repeat(['string_1', 'string_2'], 3)
```
all well and good. 

But hypothesis raised the following example which highlighted some strange behaviour when escape characters are included in the strings.
```
multiplied_strings = np.repeat(['0', '0\x00'], 3)
```
this example produces a list of 6 `0` elements. 

### Reproduce the code example:

```python
import numpy as np
multiplied_strings = np.repeat(['0', '0\x00'], 3)
print(multiplied_strings)
```

### Error message:

```shell
N/A
```

### NumPy/Python version information:

1.22.4 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]

**Comment by eric-wieser** [comment] 2022-08-01 11:58
Numpy strings by design cannot store trailing null characters; their length is determined by finding the first non-null character starting from the end of the fixed-length string.

**Comment by seberg** [comment] 2022-08-02 04:32
Indeed, closing as this is a limitation that cannot be avoided.  The only thing we could do is give a warning when storing such a string...

**Closed by seberg** 2022-08-02 04:32 UTC
Labels: 00 - Bug
