### ISSUE TITLE
List with circular reference causes array generation to hang without error message

### ISSUE THREAD

**Issue by Astrokiwi** [numpy/numpy#14934] opened 2019-11-19 12:29 UTC
Creating an array out of a list that (accidentally) has a circular reference sometimes causes the Python terminal to hang, and can not be terminated even by ctrl-C.

Ideally, this should be detected, and an exception should be raised.

### Reproducing code example:

```
import numpy as np
a = []
a.append(a)
np.array(a) # outputs `array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[list([[...]])]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]], dtype=object)`
a.append(a)
np.array(a)  # hangs
```

### Error message:

No error - python simply hangs

### Numpy/Python version information:

1.16.4 3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Comment by seberg** [comment] 2019-11-19 17:07
Just to note. This is probably very low priority, and mitigated when we do not allow `object` dtype occuring without specifically asking for it. There was a duplicate of this issue open somewhere, I did not find it quickly, it is likely we had closed it.

NumPy does not actually hang here, the maximum dimension is just 32, so it tries to figure out whats inside the list to create a final array with 2**32 elements (the shape will be `(2,) * 32`). Unsurprisingly, that takes forever.

**Comment by eric-wieser** [comment] 2019-11-19 17:23
Relates to gh-8963

**Comment by Astrokiwi** [comment] 2019-11-20 11:28
The main problem is that it's poor behaviour for debugging. If you accidentally write `a.append(a)` when you meant to write `a.append(b)`, you should get a helpful exception - or at least a warning message. If a small typo causes numpy to attempt to create a 2**32 sized array and not even let you abort it to get a stack trace, then that's going to be really tricky to track down in a large code.

**Comment by seberg** [comment] 2021-11-06 05:40
This gives a deprecation warning now.  Also, `ctrl+c` works for me, so I think we we can close this.  Aside from finalizing the deprecation, there is probably nothing to be improved here.

**Closed by seberg** 2021-11-06 05:40 UTC
Labels: 00 - Bug
