### ISSUE TITLE
random.shuffle messing up my array in numpy 1.11 

### ISSUE THREAD

**Issue by jlopezpena** [numpy/numpy#7910] opened 2016-08-05 17:53 UTC
I am doing some Montecarlo cross validation tests for some machine learning models. My features live in a pandas dataframe indexed by tuples (the index is important as it has a meaning). To make the Montecarlo train-test splits I am using `numpy.random.shuffle` on the index array like this:

```python
index_copy = features_df.index.values.copy()
for k in range(n_folds):
    np.random.shuffle(index_copy)
    train_ix = index_copy[:train_size]
    test_ix = index_copy[train_size:]
    train_features = features_df.ix[train_ix]
    ... fitting stuff
``` 

My program used to work with numpy 1.10, but upon upgrading to numpy 1.11 it randomly fails with the error `unhashable type: 'numpy.ndarray`, which typically happens if the `train_ix` array passed to the index method has the wrong shape. My `index_copy` typically looks like this:

```
[(Timestamp('2013-12-22 13:00:00'), 692903)
 (Timestamp('2014-03-21 19:30:00'), 693014)
 (Timestamp('2010-05-08 19:00:00'), 1156323)
 (Timestamp('2013-01-26 16:00:00'), 438456)
 (Timestamp('2014-04-25 18:30:00'), 693067)
...
 (Timestamp('2011-10-01 17:00:00'), 359289)
 (Timestamp('2009-11-07 18:00:00'), 1156081)
 (Timestamp('2007-09-15 18:00:00'), 128129)
 (Timestamp('2013-09-21 15:00:00'), 692771)]
```

but when the program crashed I got instead something like this:

```
[(Timestamp('2013-04-27 18:00:00'), 438579)
 (array([(Timestamp('2013-04-27 18:00:00'), 438579), (...),
       (Timestamp('2014-02-22 19:00:00'), 692980)], dtype=object), array([(Timestamp('2009-11-01 16:00:00'), 1156072),
       (Timestamp('2013-05-18 19:00:00'), 438608),
       (Timestamp('2014-03-07 19:30:00'), 692996)], dtype=object))
 (Timestamp('2014-02-22 19:00:00'), 692980) ...,
 (Timestamp('2009-11-01 16:00:00'), 1156072)
 (Timestamp('2013-05-18 19:00:00'), 438608)
 (Timestamp('2014-03-07 19:30:00'), 692996)]
```

Note the `array` inside the second entry.
It seems that somehow `np.random.shuffle` is messing the shape of the input array.

As I mentioned, this happens randomly (I observe it about 1 in 1000 times), and it doesn't occur with numpy 1.10, so it must be caused by some change in 1.11.

Is this a known issue? I tried making a minimal example, but I only encounter the problem with large `ndarrays` with complicated `dtypes`.

**Comment by seberg** [comment] 2016-08-06 09:11
Your index is a 1D object of type ndarray (not just subclass)? I am having trouble seeing how this may be possible, hmmm. Just to double check, is the array is OK before the shuffle operation?
A 1D object array should do nothing weird compared to any typical shuffle as far as I can see (unless maybe there are some threadsafety concerns), so I don't really see right now how it could manage to create new tuples.

**Comment by jlopezpena** [comment] 2016-08-06 09:34
The pandas dataframe index is a bit more complicated than an `ndarray`, but I am shuffling just (a copy of) the index **values**, which is indeed an `ndarray`:

```python
>>> type(index_copy)
numpy.ndarray
>>> index_copy.shape
(36800,)
>>> index_copy.dtype
dtype('O')
```

My algorithm does not fail right away, it fails after 500+ iterations on the for loop. The line that fails is the one that select the `train_ix` rows of a dataframe, because it gets passed an index of the wrong shape. No other method (apart from shuffle) is modifying the `index_copy` variable (or values).

This code has been working for months under numpy 1.10 and it fails when upgrading to numpy 1.11; I have verified that downgrading numpy again solves the issue. 
The issue also disappear if I make a fresh copy of `index_copy` in each step of the for loop, prior to shuffling, but that kills my performance (performance is the only reason I am using `random.shuffle` in the index rather than directly calling the `sample` method in the features dataframe)

**Comment by juliantaylor** [comment] 2016-08-06 10:02
can you provide an example reproducing the issue?
What platform are you on? Which compiler is used?
the new shuffle does create fully overlapping memcpys which is technically not allowed but shouldn't actually create problems in practice. Also a decent compiler should not even use memcpy for object arrays.

**Comment by juliantaylor** [comment] 2016-08-06 10:07
your output does look like the shuffle swapped a pointer to a copy of itself into the array. I'm surprised it doesn't just crash.

**Comment by seberg** [comment] 2016-08-06 10:08
@juliantaylor out of curiousity, I always know the valgrind warnings, but in these cases there is always a 1:1 match of src and dst pointers. If that undefined as well on any machine?

**Comment by jlopezpena** [comment] 2016-08-06 10:09
I am using the numpy version coming with anaconda default channel on Ubuntu 14.04. Not sure how it got compiled, but it should be one of the big three (gcc, LLVM or Intel compiler).

Over the weekend I don't have access to our DB (firewall) but I will try to distill a minimal failing example when I get back to office on Tuesday. I tried yesterday when I spotted the problem, but the randomness of the issue is making it tricky.

And yes, the output looks like there is some pointer arithmetic seriously messed up...

**Comment by seberg** [comment] 2016-08-06 13:03
If it is a special shuffle operation, you could store the random generator state before the shuffle to reproduce it maybe.

**Comment by charris** [comment] 2016-08-06 16:05
Where did you get numpy and on what platform are you running? I'm curious if the compiler might be at fault. Was pandas, cython also upgraded? Can you check that the array is valid before the shuffling starts? Be interesting to see if un-inlining `_raw_shuffle` makes a difference. I suspect that if there is a problem with shuffle that it shouldn't be specific to object arrays. If you can't mess with compiling numpy, a small example that reproduces the problem would be very helpful.

**Comment by charris** [comment] 2016-08-06 16:20
The problem I am having, is seeing how a pointer to the array gets put into the array during the shuffle. I can't see the array pointer being anywhere near in memory to where the array and buffer data is located.

**Comment by charris** [comment] 2016-08-07 16:26
I suspect the problem is not in shuffle, but will be happy to be proven wrong.

**Comment by jlopezpena** [comment] 2016-08-09 15:04
I tried creating an isolated virtual environment to make a reproducible minimal example, but after a clean reinstall and a couple of runs I haven't hit the problem again, so the original issue might have been due to a corrupted binary in my previous installation. Feel free to close the issue, I will keep testing and reopen if I encounter the problem again. Sorry for the noise!

**Comment by charris** [comment] 2016-08-10 15:28
Thanks for the update. Closing.

**Closed by charris** 2016-08-10 15:28 UTC
Labels: 12 - Regression
