### ISSUE TITLE
Segmentation Fault for large array as input to bincount()

### ISSUE THREAD

**Issue by quakberto** [numpy/numpy#6804] opened 2015-12-09 19:47 UTC
The following code produces a segmentation fault in my configuration:
```python
np.bincount(np.ones(np.power(2,32),dtype=(np.uint16)))
```

platform : linux-64
numpy version: 1.93

**Comment by charris** [comment] 2015-12-09 20:03
Hmm, I get a memory error, probably from allocating the `ones`. So I'll guess that the allocation of the bincount array may not be checked. How much memory do you have?

**Comment by charris** [comment] 2015-12-09 20:04
BTW, `2**32` is probably better than `power`. Also, 32 or 64 bit python?

**Comment by quakberto** [comment] 2015-12-09 20:20
Sorry, I could have been clearer:
This does not work:
```python
largeArray = np.ones(2**31,dtype=(np.uint16))
np.bincount(largeArray)
```
This still works:
```python
largeArray = np.ones(2**31-1,dtype=(np.uint16))
np.bincount(largeArray)
```

**Comment by charris** [comment] 2015-12-09 20:30
Works here (16 GiB, 64 bit linux), but uses all memory and ~8GiB swap. It really should not take that many resources...

**Comment by jaimefrio** [comment] 2015-12-09 22:07
The input array is converted to a contiguous np.intp array before
processing, so that's 17 GB on top of the 4 GB of the input array, so your
resource use figures are as expected.

The allocations are all checked for non-NULL returns, and all the counters
are npy_intp, so there is nothing obviously wrong.

We are leaking a reference to np.dtype(np.intp) when calling with a weights
array though, will file a bug report...

Jaime

-- 
(\__/)
( O.o)
( > <) Este es Conejo. Copia a Conejo en tu firma y ayúdale en sus planes
de dominación mundial.

**Comment by charris** [comment] 2015-12-09 22:25
Could be chunked. Does the new iterator allow that?

**Comment by jaimefrio** [comment] 2015-12-09 23:45
Yes, I think so: using a buffered new iterator would be the solution to the memory blow-up in this case. The problem is that setting up the iterator is very expensive, and `bincount` is very fast, so we would see a big degradation of performance, at least for smaller arrays. We could reimplement the chunking just for this function, but it seems like an awful lot of work, not sure it is worth the extra complexity.

**Comment by njsmith** [comment] 2015-12-09 23:47
An intermediate option that would still involve a bit of code duplication
would be to only use the iterator for large arrays where the overhead could
be amortized, since those are the ones that need chunking.
.
Alternatively maybe we should just make the iterator less expensive to set
up :-)

On Wed, Dec 9, 2015 at 3:45 PM, Jaime <notifications@github.com> wrote:

> Yes, I think so: using a buffered new iterator would be the solution to
> the memory blow-up in this case. The problem is that setting up the
> iterator is very expensive, and bincount is very fast, so we would see a
> big degradation of performance, at least for smaller arrays. We could
> reimplement the chunking just for this function, but it seems like an awful
> lot of work, not sure it is worth the extra complexity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6804#issuecomment-163439038>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by charris** [comment] 2015-12-10 02:22
We could use a set of specialized iterators for chunked conversion, stacked matrices, and stacked vectors. I'm not sure what the best design for the latter would be.

**Comment by quakberto** [comment] 2015-12-10 11:08
Ok my numpy installation came from a downloaded precompiled package (probably 32 bit by mistake) and installing a different one solved the problem. Thanks!

**Comment by charris** [comment] 2015-12-10 18:59
@quakberto Would be good to name the package in case someone else runs into this. I'm guessing that it is a problem with a 32 bits numpy running on a 64 bit system, which might indicate a bug somewhere. But I'm going to close this for the time being.

**Closed by charris** 2015-12-10 18:59 UTC
Labels: component: numpy.lib, Defect

**Comment by quakberto** [comment] 2015-12-11 09:57
Sure, I didn't name it because it came from a private anaconda repository:
https://anaconda.org/nanshe/numpy
It's working as expected with the numpy package from the anaconda defaults repository.
