### ISSUE TITLE
Test failures (cython-related?) on osx-64 with CPython 3.13 in conda-forge

### ISSUE THREAD

**Issue by h-vetinari** [numpy/numpy#27314] opened 2024-08-30 01:00 UTC
Building numpy 2.1.0 for CPython 3.13 in conda-forge is [going](https://github.com/conda-forge/numpy-feedstock/pull/329) pretty smoothly, with one exception, which is osx. There we get a crash in
``` 
_core/tests/test_limited_api.py::test_limited_api
```
and about ~20 failures that result in "initialization of <module> did not return an extension module", e.g.
``` 
______________________________ test_fillwithbytes ______________________________
[gw0] darwin -- Python 3.13.0 $PREFIX/bin/python

install_temp = None

    def test_fillwithbytes(install_temp):
>       import checks
E       SystemError: initialization of checks did not return an extension module
```

All told, the result is:
```
=========================== short test summary info ============================
FAILED _core/tests/test_limited_api.py::test_limited_api
FAILED _core/tests/test_cython.py::test_is_timedelta64_object - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_is_datetime64_object - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_get_datetime64_value - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_get_timedelta64_value - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_get_datetime64_unit - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_abstract_scalars - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_default_int - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_ravel_axis - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_convert_datetime64_to_datetimestruct - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::TestDatetimeStrings::test_make_iso_8601_datetime - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::TestDatetimeStrings::test_get_datetime_iso_8601_strlen - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_multiiter_fields[arrays0] - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_multiiter_fields[arrays1] - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_multiiter_fields[arrays2] - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_multiiter_fields[arrays3] - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_dtype_flags - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_conv_intp - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_npyiter_api - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_fillwithbytes - SystemError: initialization of checks did not return an extension module
FAILED _core/tests/test_cython.py::test_complex - SystemError: initialization of checks did not return an extension module
FAILED random/tests/test_extending.py::test_cython - SystemError: initialization of extending did not return an extension module
22 failed, 48208 passed, 2709 skipped, 42 xfailed, 10 xpassed, 1 warning in 320.59s (0:05:20)
```

Given how the failures are overwhelmingly in `test_cython.py`, I'm expecting cython to be the culprit here. I [asked](https://github.com/cython/cython/issues/6368) for a 3.13-compatitble tag in Cython, the statement was that 3.0.11 should work (but that may have been too optimistic).

Logs can be found [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1014215&view=results)

Example failure:

```
_________________________________ test_cython __________________________________
[gw4] darwin -- Python 3.13.0 $PREFIX/bin/python

...
    
        # test that the module can be imported
>       load("extending")

build_dir  = PosixPath('/private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython')
fid        = <_io.TextIOWrapper name='/private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so.p/extending.pyx.c' mode='r' encoding='UTF-8'>
g          = ['/private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so.p/extending.pyx.c']
glob       = <module 'glob' from '/Users/runner/miniforge3/conda-bld/numpy_1724995603034/_test_env_placehold_placehold_placehold_pl...ehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.13/glob.py'>
i          = 1225
line       = '    /* Using NumPy API declarations from "numpy/__init__.cython-30.pxd" */\n'
load       = <function test_cython.<locals>.load at 0x14d4eaac0>
srcdir     = '/Users/runner/miniforge3/conda-bld/numpy_1724995603034/_test_env_placehold_placehold_placehold_placehold_placehold_pl...lacehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.13/site-packages/numpy/random/tests/..'
suffix     = '.cpython-313-darwin.so'
target_dir = PosixPath('/private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build')
tmp_path   = PosixPath('/private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0')
txt_to_find = 'NumPy API declarations from "numpy/__init__'

../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.13/site-packages/numpy/random/tests/test_extending.py:103: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.13/site-packages/numpy/random/tests/test_extending.py:98: in load
    mod = module_from_spec(spec)
        modname    = 'extending'
        so         = PosixPath('/private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so')
        spec       = ModuleSpec(name='extending', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x14d0071d0>, origin='/p...00gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so')
        suffix     = '.cpython-313-darwin.so'
        target_dir = PosixPath('/private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build')
<frozen importlib._bootstrap>:813: in module_from_spec
    ???
        module     = None
        spec       = ModuleSpec(name='extending', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x14d0071d0>, origin='/p...00gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so')
<frozen importlib._bootstrap_external>:1316: in create_module
    ???
        self       = <_frozen_importlib_external.ExtensionFileLoader object at 0x14d0071d0>
        spec       = ModuleSpec(name='extending', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x14d0071d0>, origin='/p...00gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

f = <built-in function create_dynamic>
args = (ModuleSpec(name='extending', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x14d0071d0>, origin='/...gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so'),)
kwds = {}

>   ???
E   SystemError: initialization of extending did not return an extension module

args       = (ModuleSpec(name='extending', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x14d0071d0>, origin='/...gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build/extending.cpython-313-darwin.so'),)
f          = <built-in function create_dynamic>
kwds       = {}

<frozen importlib._bootstrap>:488: SystemError
----------------------------- Captured stdout call -----------------------------
The Meson build system
Version: 1.5.1
Source dir: /private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython
Build dir: /private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/build
Build type: native build
Project name: random-build-examples
Project version: undefined
C compiler for the host machine: x86_64-apple-darwin13.4.0-clang (clang 17.0.6 "clang version 17.0.6")
C linker for the host machine: x86_64-apple-darwin13.4.0-clang ld64 711
C++ compiler for the host machine: x86_64-apple-darwin13.4.0-clang++ (clang 17.0.6 "clang version 17.0.6")
C++ linker for the host machine: x86_64-apple-darwin13.4.0-clang++ ld64 711
Cython compiler for the host machine: cython (cython 3.0.11)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES ($PREFIX/bin/python3.13)
Library npymath found: YES
Library npyrandom found: YES
Did not find pkg-config by name 'pkg-config'
Found pkg-config: NO
Run-time dependency python found: YES 3.13
Build targets in project: 3

Found ninja-1.12.1 at $PREFIX/bin/ninja
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: $PREFIX/bin/ninja -v
[1/9] cython -M --fast-fail -3 /private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/extending.pyx -o extending.cpython-313-darwin.so.p/extending.pyx.c
[2/9] cython -M --fast-fail -3 --cplus --module-name extending_cpp /private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/extending_distributions.pyx -o extending_cpp.cpython-313-darwin.so.p/extending_distributions.pyx.cpp
[3/9] cython -M --fast-fail -3 /private/var/folders/rw/0gwtqtr55hdbnkwp7bt6pkb00000gn/T/pytest-of-runner/pytest-0/popen-gw4/test_cython0/random/_examples/cython/extending_distributions.pyx -o extending_distributions.cpython-313-darwin.so.p/extending_distributions.pyx.c
[4/9] x86_64-apple-darwin13.4.0-clang -Iextending.cpython-313-darwin.so.p -I. -I.. -I$PREFIX/lib/python3.13/site-packages/numpy/_core/include -I$PREFIX/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -O0 -g -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-2.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=12.0 -MD -MQ extending.cpython-313-darwin.so.p/meson-generated_extending.pyx.c.o -MF extending.cpython-313-darwin.so.p/meson-generated_extending.pyx.c.o.d -o extending.cpython-313-darwin.so.p/meson-generated_extending.pyx.c.o -c extending.cpython-313-darwin.so.p/extending.pyx.c
In file included from extending.cpython-313-darwin.so.p/extending.pyx.c:1228:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/arrayobject.h:5:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909:
$PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^
1 warning generated.
[5/9] x86_64-apple-darwin13.4.0-clang -Iextending_distributions.cpython-313-darwin.so.p -I. -I.. -I$PREFIX/lib/python3.13/site-packages/numpy/_core/include -I$PREFIX/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -O0 -g -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-2.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=12.0 -MD -MQ extending_distributions.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.c.o -MF extending_distributions.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.c.o.d -o extending_distributions.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.c.o -c extending_distributions.cpython-313-darwin.so.p/extending_distributions.pyx.c
In file included from extending_distributions.cpython-313-darwin.so.p/extending_distributions.pyx.c:1227:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/arrayobject.h:5:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909:
$PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^
1 warning generated.
[6/9] x86_64-apple-darwin13.4.0-clang  -o extending.cpython-313-darwin.so extending.cpython-313-darwin.so.p/meson-generated_extending.pyx.c.o -L$PREFIX/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,dynamic_lookup -bundle -Wl,-undefined,dynamic_lookup -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-2.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=12.0 $PREFIX/lib/python3.13/site-packages/numpy/random/lib/libnpyrandom.a $PREFIX/lib/python3.13/site-packages/numpy/_core/lib/libnpymath.a -lpython3.13
[7/9] x86_64-apple-darwin13.4.0-clang  -o extending_distributions.cpython-313-darwin.so extending_distributions.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.c.o -L$PREFIX/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,dynamic_lookup -bundle -Wl,-undefined,dynamic_lookup -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-2.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=12.0 $PREFIX/lib/python3.13/site-packages/numpy/random/lib/libnpyrandom.a $PREFIX/lib/python3.13/site-packages/numpy/_core/lib/libnpymath.a -lpython3.13
[8/9] x86_64-apple-darwin13.4.0-clang++ -Iextending_cpp.cpython-313-darwin.so.p -I. -I.. -I$PREFIX/lib/python3.13/site-packages/numpy/_core/include -I$PREFIX/include/python3.13 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -D_LIBCPP_ENABLE_ASSERTIONS=1 -Wall -Winvalid-pch -O0 -g -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-2.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=12.0 -MD -MQ extending_cpp.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.cpp.o -MF extending_cpp.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.cpp.o.d -o extending_cpp.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.cpp.o -c extending_cpp.cpython-313-darwin.so.p/extending_distributions.pyx.cpp
In file included from extending_cpp.cpython-313-darwin.so.p/extending_distributions.pyx.cpp:1239:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/arrayobject.h:5:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12:
In file included from $PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909:
$PREFIX/lib/python3.13/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^
1 warning generated.
[9/9] x86_64-apple-darwin13.4.0-clang++  -o extending_cpp.cpython-313-darwin.so extending_cpp.cpython-313-darwin.so.p/meson-generated_extending_distributions.pyx.cpp.o -L$PREFIX/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,dynamic_lookup -bundle -Wl,-undefined,dynamic_lookup -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/numpy-2.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=12.0 $PREFIX/lib/python3.13/site-packages/numpy/random/lib/libnpyrandom.a $PREFIX/lib/python3.13/site-packages/numpy/_core/lib/libnpymath.a -lpython3.13
```

**Comment by jakirkham** [comment] 2024-08-30 01:35
Given they all failed the same way, am wondering if this has something to do with how they are built

Search for similar issues came across this PyJulia one about having trouble building with macOS due to the statically linked Python ( https://github.com/JuliaPy/pyjulia/issues/150#issuecomment-432912833 ), which they resolved in PR ( https://github.com/JuliaPy/pyjulia/pull/212 )

This appears to be the code used to build the Cython tests in NumPy. Though am less sure what we would need to add to clarify this distinction to Meson (or for that matter why this didn't occur for earlier Python's built the same way)

https://github.com/numpy/numpy/blob/6fbd06bf3309aae73aa2bfacece1d91c4800fc07/numpy/_core/tests/test_cython.py#L35-L78

It could be worth doing a quick sanity check to confirm our Cython builds things ok on macOS with Python 3.13

**Comment by scoder** [comment] 2024-08-30 02:43
Is the failing test using the Limited API of CPython? If so, you'd probably need Cython 3.1 to generate C code for it. Cython 3.0.x does not produce much that is useful under the Limited API, but 3.1 had major improvements going into it that make most language features work.

**Comment by jakirkham** [comment] 2024-08-30 03:10
Thanks for chiming in Stefan! 🙏

I don't think so. Looking at the flags here would expect to see `-DPy_LIMITED_API=<Python hex version>` or similar, which doesn't appear to be the case

https://github.com/numpy/numpy/blob/6fbd06bf3309aae73aa2bfacece1d91c4800fc07/numpy/_core/tests/examples/cython/meson.build#L36-L40

That said, all of my knowledge about this test suite has come from reading the code within the last hour

Hopefully someone more knowledgeable can provide additional context

**Comment by jakirkham** [comment] 2024-08-30 03:13
...and it turns out that is not quite true anyways 🤦‍♂️

There does appear to be a test using the limited API

https://github.com/numpy/numpy/blob/6fbd06bf3309aae73aa2bfacece1d91c4800fc07/numpy/_core/tests/examples/limited_api/setup.py#L9

Though I don't think that is true of all tests

**Comment by h-vetinari** [comment] 2024-08-30 05:43
No change with newer deployment target (12.0)

**Comment by ngoldbaum** [comment] 2024-08-30 14:26
For what it's worth, I was doing all the work to support Python 3.13 using a nightly cython, so I guess unsurprising this was missed.

I don't think this is due to limited API support if the `test_cython` tests are failing.

**Comment by seberg** [comment] 2024-08-30 16:55
Sounds like we may need to make Cython 3.1 a build dependency, then?  I agree, while there is a test that uses the limited API.  I agree that I don't think limited API use should be the root cause here, but not sure it is worth trying to find that.

**Comment by ngoldbaum** [comment] 2024-08-30 21:57
I might be able to scrounge up an old Intel mac to debug this with next week.

**Comment by h-vetinari** [comment] 2024-09-01 20:34
The main issue in numpy seems to be that [this](https://github.com/numpy/numpy/blob/v2.1.0/numpy/_core/tests/examples/cython/checks.pyx) test module cannot be imported after being built with cython 3.0.11. This might be more serious than I initially thought (based on 20 failures out of 50'000), because IIUC it means one cannot use (parts of) the numpy API through cython.

**Comment by charris** [comment] 2024-09-01 21:49
This is the only issue I am waiting on for 2.1.1, so it would be good to get it resolved.

**Comment by rgommers** [comment] 2024-09-02 16:05
Fixed now (see https://github.com/conda-forge/numpy-feedstock/pull/329#issuecomment-2324997419), so closing. tl;dr `pkg-config` was missing, and apparently without it we're hitting some bug in Meson that's specific to Python 3.13 _and_ a staticallly linked `libpython`. Not a problem in Cython or NumPy, so closing this and following up elsewhere.

**Closed by rgommers** 2024-09-02 16:05 UTC
