### ISSUE TITLE
DOC: broken link at https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html

### ISSUE THREAD

**Issue by keithbriggs** [numpy/numpy#21329] opened 2022-04-12 14:28 UTC
> scipy.linalg.eigh

**click**
```

Not Found

The requested URL /doc/scipy-1.8.0/html-scipyorg/reference/reference/generated/scipy.linalg.eigh.html was not found on this server.
```

**Comment by melissawm** [comment] 2022-04-12 15:12
Thanks @keithbriggs, this has been fixed in [the devdocs](https://numpy.org/devdocs/reference/generated/numpy.linalg.eigh.html). All of the scipy links should be fixed with the next release, so I'm closing this as a duplicate of #21059.

**Closed by melissawm** 2022-04-12 15:12 UTC
Labels: 04 - Documentation
