### ISSUE TITLE
BUG(?): Crash upon import after building from source on Windows with rtools compilers

### ISSUE THREAD

**Issue by mdhaber** [numpy/numpy#25251] opened 2023-11-25 05:25 UTC
### Describe the issue:

I just finished setting up a SciPy development environment from scratch on a Windows machine. To do this, I followed [SciPy's "Building from Source"](https://docs.scipy.org/doc/scipy/building/index.html#system-level) guide, including installing rtools with chocolatey. Now I am trying to set up a NumPy development environment using the NumPy [Setting up and using your development environment](https://numpy.org/devdocs/dev/development_environment.html#development-environment) guide. My editable install seems to be successful, but when I try to `import numpy`, Python crashes with the message repeated below.

---

Note that I created a `numpy-dev` environment using `mamba`, but I removed `compilers` from the list in `environment.yml` as is recommended for building SciPy. When `compilers` is installed (although I can't tell if the install was perfectly successful), editable install of NumPy fails with a different message. 
<details>

```
(numpy-dev) C:\Users\matth\numpy>python -m pip install --no-build-isolation --editable .
Obtaining file:///C:/Users/matth/numpy
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      + C:\Users\matth\miniforge3\envs\numpy-dev\python.exe C:\Users\matth\numpy\vendored-meson\meson\meson.py setup C:\Users\matth\numpy C:\Users\matth\numpy\build\cp39 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\matth\numpy\build\cp39\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\matth\numpy
      Build dir: C:\Users\matth\numpy\build\cp39
      Build type: native build
      Project name: NumPy
      Project version: 2.0.0.dev0+git20231124.94bc564

      ..\..\meson.build:1:0: ERROR: Unknown compiler(s): [['cl.exe']]
      The following exception(s) were encountered:
      Running `cl.exe /?` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\matth\numpy\build\cp39\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>

Let me know if I should open a new issue with that information or, if using `compilers` is the preferred approach, I can adapt this one.

I've also tried using `spin` rather than an editable install (after `pip uninstall numpy` and `git clean -dxf`). `spin test -v` seems to build NumPy successfully, but then I get an `ImportError` before tests run.

<details>

```
> spin test - v
...
[495/500] Compiling C object numpy/_core/_multiarray_umath.cp39-win_amd64.pyd.p/src_umath_umathmodule.c.obj
../numpy/_core/src/umath/umathmodule.c:338:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
  338 | }
      | ^
../numpy/_core/src/umath/umathmodule.c:338:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
../numpy/_core/src/umath/umathmodule.c:338:1: warning: visibility attribute not supported in this configuration; ignored [-Wattributes]
[500/500] Linking target numpy/random/_generator.cp39-win_amd64.pyd
$ 'C:\Users\matth\miniforge3\envs\numpy-dev\python.exe' vendored-meson/meson/meson.py install --only-changed -C build --destdir ../build-install
$ export PYTHONPATH="C:\Users\matth\numpy\build-install\usr\Lib\site-packages"
$ export PYTHONPATH="C:\Users\matth\numpy\build-install\usr\Lib\site-packages"
$ cd C:\Users\matth\numpy\build-install\usr\Lib\site-packages
$ 'C:\Users\matth\miniforge3\envs\numpy-dev\python.exe' -m pytest '--rootdir=C:\Users\matth\numpy\build-install\usr\Lib\site-packages' -v -m 'not slow' numpy
ImportError while loading conftest 'C:\Users\matth\numpy\build-install\usr\Lib\site-packages\numpy\conftest.py'.
numpy\__init__.py:119: in <module>
    raise ImportError(msg) from e
E   ImportError: Error importing numpy: you should not try to import numpy from
E           its source directory; please exit the numpy source tree, and relaunch
E           your python interpreter from there.
```

</details>

### Reproduce the code example:

```python
import numpy
```

### Error message:

```shell
(numpy-dev) C:\Users\matth\numpy>python
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
<frozen importlib._bootstrap>:228: Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
C:\Users\matth\numpy\numpy\_core\getlimits.py:227: RuntimeWarning: invalid value encountered in exp2
  epsneg_f128 = exp2(ld(-113))
C:\Users\matth\numpy\numpy\_core\getlimits.py:228: RuntimeWarning: invalid value encountered in exp2
  tiny_f128 = exp2(ld(-16382))
C:\Users\matth\numpy\numpy\_core\getlimits.py:242: RuntimeWarning: invalid value encountered in exp2
  eps=exp2(ld(-112)),
C:\Users\matth\numpy\numpy\_core\getlimits.py:41: RuntimeWarning: invalid value encountered in nextafter
  self._smallest_subnormal = nextafter(
C:\Users\matth\numpy\numpy\_core\getlimits.py:52: RuntimeWarning: invalid value encountered in log10
  self.precision = int(-log10(self.eps))
```

### Runtime information:

'3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]'

**Comment by rgommers** [comment] 2023-11-26 07:53
Re `ERROR: Unknown compiler(s): [['cl.exe']]`: the conda-forge `compilers` package will activate but not install MSVC. So it looks like you don't have MSVC installed from the Microsoft installers?

> Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.

I don't have much of a memory of this, but IIRC we had working builds with at least the Rtools version that was current a year ago. It's not a recommended toolchain for sure, but I'm surprised that an import fails without any indication as to what the problem is.

**Comment by h-vetinari** [comment] 2023-11-28 10:11
> I think I'm still seeing complaints when I `mamba install compilers` - most of them seem to be looking for Microsoft Visual Studio 2019, but I have 2022. Do I need to get 2019?

The `compilers` package is just a convenience wrapper around our default compiler infrastructure (currently at vs2019; unlikely to change soon), and not really meant for development. If you want to use your local install as-is (without installing an older toolset), you need to install `vs2022_win-64` instead of the `compilers` package (if you then still want a fortran compiler as well, it's possible but currently the choices aren't ideal; hopefully that will change early next year).

**Comment by mdhaber** [comment] 2023-11-29 01:36
Thanks @h-vetinari @rgommers! `vs2022_win-64` for the win.

> It depends on whether you want to invest some time in getting it to work

Independently, no, but if you need a button-pusher until you get a Windows machine, I can do that.

I think this issue can be resolved with documentation, but I know that you plan on rewriting the NumPy development build docs, right Ralf? So I can close this if the idea of adding Windows recommendations doesn't need to be tracked.

**Comment by rgommers** [comment] 2023-11-29 08:58
> I think this issue can be resolved with documentation, but I know that you plan on rewriting the NumPy development build docs, right Ralf? So I can close this if the idea of adding Windows recommendations doesn't need to be tracked.

Yes, I will rewrite it all and include a from-scratch section on compiler selection, so no need to track that here. Hence, let's close it. Thanks Matt.

**Closed by rgommers** 2023-11-29 08:58 UTC
Labels: 00 - Bug
