### ISSUE TITLE
TST: Add test for FFT case that used to be buggy in intels fft monkeypatch

### ISSUE THREAD

**Issue by david-hoffman** [numpy/numpy#11762] opened 2018-08-17 01:35 UTC
The result of running an `fft` on an array view is different then running it on a new array of equivalent data.

### Reproducing code example:

```python
import numpy as np

# make random data
a = np.random.rand(3, 3) + 1j * np.random.rand(3, 3)

# make a view with one empty axis
a_view = a[np.newaxis]
# make a new array with one empty axis
a_new = a.reshape(1, 3, 3)

# take ffts  along the last axis of these arrays
b = np.fft.fftn(a, axes=(-1,)).squeeze()
b_view = np.fft.fftn(a_view, axes=(-1,)).squeeze()
b_new = np.fft.fftn(a_new, axes=(-1,)).squeeze()

# check that they all are equal
assert np.array_equal(a_new, a_view), "Arrays not equal ..."
assert np.array_equal(b, b_new), "New array failed ..."
assert np.array_equal(b, b_view), "View failed ..."
```

### Error message:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-164-0858f30a28df> in <module>()
      9 assert np.array_equal(a_view, a_new), "Arrays not equal"
     10 assert np.array_equal(b, b_new), "New array failed ..."
---> 11 assert np.array_equal(b, b_view), "View failed ..."

AssertionError: View failed ...
```

### Numpy/Python version information:

1.15.0 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]

**Comment by seberg** [comment] 2018-08-17 10:45
First of all, the reshape should have the same result as the `np.newaxis` indexing (e.g. it also creates a view), although the strides might be a different, but I do not see why it should matter.

As for the comparison of the arrays, could you please check how much they differ. I do not know why they should differ at all (e.g. if there are random things possible within the FFT computation or so), but I bet the differences are in any case within numerical precision?

One thing is, that you seem to use anaconda and anaconda monkeypatches the FFT to use FFTW or MKLs fft or so, so frankly, that might make the randomness more likely.

**Comment by seberg** [comment] 2018-08-17 10:46
If the FFT is really implemented outside numpy's shipped fftpack, you should probably forward the issue to the packagers.

**Comment by david-hoffman** [comment] 2018-08-17 11:41
I created a non-MKL environment (Anaconda doesn't even have a recipe for FFTW so I doubt it monkey patches it in) using this https://stackoverflow.com/questions/47891872/how-to-use-non-mkl-numpy-under-anaconda.

See the new code snippet below for an answer to:
> As for the comparison of the arrays, could you please check how much they differ.

The result for `b_view` has erroneously repeated columns.

@seberg have you tried this code snippet on your system? Do you not get the same problem?

### Reproducing code example:

```python
import numpy as np

np.set_printoptions(precision=2)

a_view = a[np.newaxis]
# make a new array with one empty axis
a_new = a.reshape(1, 3, 3)

# take ffts  along the last axis of these arrays
b = np.fft.fftn(a, axes=(-1,)).squeeze()
b_view = np.fft.fftn(a_view, axes=(-1,)).squeeze()
b_new = np.fft.fftn(a_new, axes=(-1,)).squeeze()

print("b looks like:")
print(b)
print("b_view looks like:")
print(b_view)
print("b_new looks like:")
print(b_new)

# check that they all are equal
assert np.array_equal(a_new, a_view), "Arrays not equal ..."
assert np.array_equal(b, b_new), "New array failed ..."
assert np.array_equal(b, b_view), "View failed ..."
```

### Error message:

```
b looks like:
[[ 1.64+2.13j  0.1 -0.1j   0.88+0.7j ]
 [ 1.24+1.22j -0.22+1.41j  0.1 +0.1j ]
 [ 0.46+1.11j -0.76-0.41j  0.51-0.36j]]
b_view looks like:
[[1.64+2.13j 0.1 -0.1j  0.88+0.7j ]
 [1.64+2.13j 0.1 -0.1j  0.88+0.7j ]
 [1.64+2.13j 0.1 -0.1j  0.88+0.7j ]]
b_new looks like:
[[ 1.64+2.13j  0.1 -0.1j   0.88+0.7j ]
 [ 1.24+1.22j -0.22+1.41j  0.1 +0.1j ]
 [ 0.46+1.11j -0.76-0.41j  0.51-0.36j]]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-bb445893d976> in <module>()
     24 assert np.array_equal(a_new, a_view), "Arrays not equal ..."
     25 assert np.array_equal(b, b_new), "New array failed ..."
---> 26 assert np.array_equal(b, b_view), "View failed ..."

AssertionError: View failed ...
```

### Numpy/Python version information:

1.15.0 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]

**Comment by seberg** [comment] 2018-08-17 15:46
In case they fix it there, it would still be nice to add a (regression) test to numpy for future generations (and as a warning to others using somehow non-fixed setups)! If you are up to it, we are always happy about pull requests!

**Comment by seberg** [comment] 2018-08-21 09:06
Ok, it is fixed there. We could probably add their test or a similar one to numpy, assuming the numpy test suit, since I guess the numpy test suit did not detect that issue, it is less relevant for numpy's code right now probably, but it could be in the future.

Or just close the issue :)

**Comment by mattip** [comment] 2019-02-19 08:33
Closing

**Closed by mattip** 2019-02-19 08:33 UTC
Labels: 05 - Testing, 29 - Intel/Anaconda
