### ISSUE TITLE
structured dtype of the form np.dtype(["name", "str"]) are confusing

### ISSUE THREAD

**Issue by cournape** [numpy/numpy#450] opened 2012-09-20 14:13 UTC
It is relatively intuitive to want to create a structured array with "str" string for a dtype, which is converted to a "S0" type. I think this should be detected as an error instead ?

**Comment by mattip** [comment] 2018-08-08 01:04
Can we close this?

**Comment by eric-wieser** [comment] 2018-08-08 01:43
Same as #8969, I think. Pick one to leave open.

**Comment by eric-wieser** [comment] 2019-01-13 19:53
Duplicate of #8969, which is described more clearly

**Closed by eric-wieser** 2019-01-13 19:53 UTC
Labels: 01 - Enhancement, 57 - Close?, component: numpy.dtype
