### ISSUE TITLE
incorrect conversion from float128 to long (Trac #1395)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1993] opened 2012-10-19 21:00 UTC
_Original ticket http://projects.scipy.org/numpy/ticket/1395 on 2010-02-09 by trac user amcnabb, assigned to unknown._

I created a float128 and confirmed that it indeed holds a 20 digit number.  However, when I converted it to a Python long (which should be able to hold an arbitrarily large integer), the result was only as accurate as a float64.

> > > a = (numpy.float128(1234567890) \* 10**10 + 1234567890)
> > > a
> > > 12345678901234567890.0
> > > long(a)
> > > 12345678901234567168L

The correct result for long(a) would be 12345678901234567890L.  I am using numpy-1.3.0-6.fc12.x86_64 and python-2.6.2-2.fc12.x86_64.

**Comment by NeilGirdhar** [comment] 2016-05-18 01:57
Just ran into this.

```
In [66]: int(np.float128(123456789012345678901234567890))
Out[66]: 123456789012345677877719597056
```

float128 should be good for 33 digits.

**Comment by ewmoore** [comment] 2016-05-18 02:28
np.float128 is almost certainly an 80-bit value on your machine. It's
stored in 128 bits. Not a bug.

**Comment by NeilGirdhar** [comment] 2016-05-18 02:33
Even if it were an 80-bit value, it should have 19 digits of precision.  It's a bug, and I think it's the same bug.

**Comment by ewmoore** [comment] 2016-05-18 02:37
Yes. Sorry. My email didn't have the earlier messages.

**Comment by charris** [comment] 2016-05-18 02:51
A bit more info.
```
In [1]: np.float128(123456789012345678901234567890)
Out[1]: 1.2345678901234567788e+29

In [2]: np.float128('123456789012345678901234567890')
Out[2]: 1.234567890123456789e+29

In [3]: int(np.float128('123456789012345678901234567890'))
Out[3]: 123456789012345677877719597056L
```
Note that currently the only way to get the float to the right precision is with a string, everything else looks to go through a double. This is numpy `1.12.0.dev0+188110b`.

**Comment by charris** [comment] 2016-05-18 03:14
Note also that on SunOS, float128 is actually quad precision rather than extended precision, so the whole question becomes more complicated. The float128 notation is ambiguous and at some point we will need to address that issue.

**Comment by NeilGirdhar** [comment] 2016-05-18 03:17
Right, but the float128 notation is a different bug?

Also, isn't it a bug that going from int to float128 loses bits along the way because it goes through double?

**Comment by charris** [comment] 2016-05-18 03:24
Yes...

**Comment by NeilGirdhar** [comment] 2016-05-18 03:25
Sorry, mixed up the updates I was getting on my phone.

**Comment by seberg** [comment] 2022-06-15 03:07
As far as I can follow everything works correctly now.  The `repr` of float128 should be right now, the initial example works well.  Converting `int` to longdouble should be right as well (even if actually goes through converting the int to a string first).

So, closing the issue, please open a new one if there are still related issues (or I am missing something).

**Closed by seberg** 2022-06-15 03:07 UTC
Labels: 00 - Bug, component: numpy.core
