### ISSUE TITLE
numpy 1.17.1  6 tests failures for PowerPC 

### ISSUE THREAD

**Issue by michelmno** [numpy/numpy#14438] opened 2019-09-06 10:02 UTC
numpy 6 tests failures for PowerPC 
as reported during package build in openSUSE env (1) and attached log file
Those traces are reported with numpy 1.17.1; while my local trial was with 1.16.2
[python_numpy_standard__ppc64le_201909060820.log](https://github.com/numpy/numpy/files/3583390/python_numpy_standard__ppc64le_201909060820.log)

```
$grep FAILED python_numpy_standard__ppc64le_201909060820.log
[  382s] ../core/tests/test_einsum.py::TestEinsum::test_einsum_sums_cfloat64 FAILED [ 12%]
[ 1107s] ../linalg/tests/test_linalg.py::TestSolve::test_generalized_sq_cases FAILED [ 60%]
[ 1125s] ../linalg/tests/test_linalg.py::TestInv::test_generalized_sq_cases FAILED [ 61%]
[ 1147s] ../linalg/tests/test_linalg.py::TestCond::test_sq_cases FAILED           [ 61%]
[ 1151s] ../linalg/tests/test_linalg.py::TestCond::test_generalized_sq_cases FAILED [ 61%]
[ 1189s] ../linalg/tests/test_linalg.py::TestCholesky::test_basic_property FAILED [ 63%]
```
standalone exemple of the first test:
```
$cat ~/work/test_einsum_sums_cfloat64
import numpy as np
dtype = 'c8'
n = 9
do_opt= 'False'
a = np.arange(2 * 3 * n, dtype=dtype).reshape(2, 3, n)
b = np.arange(n, dtype=dtype)
print('a: {!r}'.format(a))
print('b: {!r}'.format(b))
c = np.einsum("...i, ...i", a, b, optimize=do_opt)
d = np.inner(a, b)
print('check visually if c similar to d (not the case for PowerPC')
print('c: {!r}'.format(c))
print('d: {!r}'.format(d))

$python3 ~/work/test_einsum_sums_cfloat64
a: array([[[ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
          7.+0.j,  8.+0.j],
        [ 9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j, 15.+0.j,
         16.+0.j, 17.+0.j],
        [18.+0.j, 19.+0.j, 20.+0.j, 21.+0.j, 22.+0.j, 23.+0.j, 24.+0.j,
         25.+0.j, 26.+0.j]],

       [[27.+0.j, 28.+0.j, 29.+0.j, 30.+0.j, 31.+0.j, 32.+0.j, 33.+0.j,
         34.+0.j, 35.+0.j],
        [36.+0.j, 37.+0.j, 38.+0.j, 39.+0.j, 40.+0.j, 41.+0.j, 42.+0.j,
         43.+0.j, 44.+0.j],
        [45.+0.j, 46.+0.j, 47.+0.j, 48.+0.j, 49.+0.j, 50.+0.j, 51.+0.j,
         52.+0.j, 53.+0.j]]], dtype=complex64)
b: array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j], dtype=complex64)
check visually if c similar to d (not the case for PowerPC)
c: array([[ 204.+0.j,  528.+0.j,  852.+0.j],
       [1176.+0.j, 1500.+0.j, 1824.+0.j]], dtype=complex64)
d: array([[ 204.+0.j,  500.+0.j,  852.+0.j],
       [1148.+0.j, 1500.+0.j, 1796.+0.j]], dtype=complex64)

>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.2 3.7.3 (default, Apr 09 2019, 05:18:21) [GCC]
```
The other failing tests details present in attached log

(1) https://build.opensuse.org/package/live_build_log/openSUSE:Factory:PowerPC/python-numpy/standard/ppc64le

**Comment by ahaldane** [comment] 2019-09-09 02:28
I think it's related to openblas. I can pass tests on powerpc without linking openblas.

Looks like you are using `openblas-devel-headers-0.3.7-1.1` which is the newest version, just for reference.

**Comment by ahaldane** [comment] 2019-09-09 02:58
Confirmed: When I try to link openblas I actually get even worse than you in those same tests: I get randomly delayed segfaults and invalid-frees and other signs of memory corruption.

**Comment by rgommers** [comment] 2019-12-03 00:20
We have `ppcle64` running on TravisCI and all tests pass with OpenBLAS 0.3.7 (some particular commit, please check) right now. So it would be good to narrow down the issue and, if it's happening with a more recent version of OpenBLAS than we use in our CI, report it to OpenBLAS. Would be very useful if you could do that @michelmno

**Comment by hmaarrfk** [comment] 2020-01-05 16:30
Failures still seem to occur with OpenBLAS 0.3.7, maybe it will be fixed in 0.3.8 ???
https://travis-ci.com/conda-forge/numpy-feedstock/jobs/272495056#L5029

**Comment by bnavigator** [comment] 2020-06-26 18:18
Still (or again?) an issue with 1.18.4 and OpenBLAS 0.3.9

https://build.opensuse.org/package/show/openSUSE:Factory:PowerPC/python-numpy


```
[   37s] openblas-devel-headers-0.3.9-1.2      ########################################
[   37s] libquadmath0-10.1.1+git40-1.12        ########################################
[   37s] libgfortran5-10.1.1+git40-1.12        ########################################
[   38s] libpython3_8-1_0-3.8.3-1.10           ########################################
[   38s] libopenblas_openmp0-0.3.9-1.2         ########################################
[   38s] update-alternatives: using /usr/lib64/libopenblas_openmp.so.0 to provide /usr/lib64/libblas.so.3 (libblas.so.3) in auto mode
[   38s] update-alternatives: using /usr/lib64/libopenblas_openmp.so.0 to provide /usr/lib64/libcblas.so.3 (libcblas.so.3) in auto mode
[   38s] update-alternatives: using /usr/lib64/libopenblas_openmp.so.0 to provide /usr/lib64/liblapack.so.3 (liblapack.so.3) in auto mode
[   38s] update-alternatives: using /usr/lib64/libopenblas_openmp.so.0 to provide /usr/lib64/libopenblas.so.0 (libopenblas_openmp.so.0) in auto mode
[   38s] libopenblas_openmp-devel-0.3.9-1.2    ########################################
...
[  864s] E               Arrays are not almost equal to 12 decimals
[  864s] E               
[  864s] E               Mismatched elements: 2 / 192 (1.04%)
[  864s] E               Max absolute difference: 1.
[  864s] E               Max relative difference: 1.
[  864s] E                x: array([[[ 1.000000000000e+00,  1.297115638874e-18, -4.724840362098e-17,
[  864s] E                        -7.773841053956e-16, -1.146365979120e-16,  4.796253199340e-17,
[  864s] E                        -9.425056501197e-18,  2.183139631582e-16],...
[  864s] E                y: array([[[1., 0., 0., 0., 0., 0., 0., 0.],
[  864s] E                       [0., 1., 0., 0., 0., 0., 0., 0.],
[  864s] E                       [0., 0., 1., 0., 0., 0., 0., 0.],...
...
[  865s] =========================== short test summary info ============================
[  865s] FAILED ../../../BUILDROOT/python-numpy-1.18.4-2.1.ppc64le/usr/lib64/python3.8/site-packages/numpy/linalg/tests/test_linalg.py::TestInv::test_generalized_sq_cases
[  865s] FAILED ../../../BUILDROOT/python-numpy-1.18.4-2.1.ppc64le/usr/lib64/python3.8/site-packages/numpy/linalg/tests/test_linalg.py::TestCond::test_generalized_sq_cases
[  865s] = 2 failed, 10436 passed, 73 skipped, 19 xfailed, 4 xpassed, 335 warnings in 482.02s (0:08:02) =
```

https://bugzilla.opensuse.org/show_bug.cgi?id=1148173

the PowerPC architecture on OpenSUSE might have a general issue. Similar problems with Slycot / python-control:
https://bugzilla.opensuse.org/show_bug.cgi?id=1172555

**Comment by StefanBruens** [comment] 2020-09-27 11:24
@rgommers - Does the CI use a openmp or pthreads openblas build?

I have tried pthreads and openmp, on PPC64(LE) pthreads works and openmp fails, while on Aarch64 both show no issues.

Some of the issues may also be caused by using pytest-xdist - there are known problems with openmp/openblas threading and python threading.

**Comment by rgommers** [comment] 2020-09-27 14:48
I think it's built without OpenMP in our CI: https://github.com/MacPython/openblas-libs/blob/master/travis-ci/build_steps.sh#L127

And same for the conda-forge ppc64le build, no OpenMP: https://github.com/conda-forge/openblas-feedstock/blob/ab17414352c7ca4c08136202101359b1305e0556/.ci_support/linux_ppc64le_SYMBOLSUFFIX64_USE_OPENMP0name_suffix-ilp64target_platformlinux-ppc64le.yaml#L5

I just looked at the build recipes though, it could well be that we're using a binary with a different config - that'd require a bit of detective work, or better just download the exact binary used in CI and inspect it.

**Comment by mattip** [comment] 2023-03-05 07:45
Closing, please reopen or open a new issue if this is still relevant for a supported NumPy version.

**Closed by mattip** 2023-03-05 07:45 UTC
