### ISSUE TITLE
numpy shared library load issue with uwsgi

### ISSUE THREAD

**Issue by jtyoui** [numpy/numpy#16963] opened 2020-07-28 09:17 UTC
### Numpy/Python version information: 1.19.1

```sh

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "/usr/local/bin/uwsgi"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so)

```

**Comment by eric-wieser** [comment] 2020-07-28 09:27
This looks to be a duplicate of #11588, from which the relevant comment is:

> I don't know if this is your issue or not, but as a heads up: in general numpy and mod_wsgi are not compatible.

**Comment by rgommers** [comment] 2021-01-26 08:47
No more follow-up, and indeed looks like a duplicate. I've also changed the title, because this seems unrelated to Alpine.

**Closed by rgommers** 2021-01-26 08:47 UTC
Labels: 32 - Installation, Embedded
