### ISSUE TITLE
BUG: stack function will convert the float value to str if the input data has both float and str

### ISSUE THREAD

**Issue by Knightly123** [numpy/numpy#22191] opened 2022-09-01 05:29 UTC
### Describe the issue:

if the input data is a list which has float value and str value, then use stack function, the line which has both float value and str value will convert to str.

**suggest**: 
       pass in the dtype into asanyarray function in below line:
       arrays = [asanyarray(arr, dtype=dtype) for arr in arrays]

### Reproduce the code example:

```python
e.g., the input list is: 
      list1 =
         [[1.0, 34.4, 56.6],
         [2.0, 'abc', 35.1],
         [3.0, 234, 45.9]]
then:
      data = empty((3,3), dtype=object)
      np.stack(list1, out=data, dtype = object)
result:  the second row's values will be converted to str.
```

### NumPy/Python version information:

mian branch, 1.24

**Comment by seberg** [comment] 2022-09-01 12:07
Closing as duplicate of (e.g.) gh-22042, it is the same promotion behavior.

**Closed by seberg** 2022-09-01 12:07 UTC
Labels: 00 - Bug
