### ISSUE TITLE
Strange behaviour when asking whether list is in numpy array of lists

### ISSUE THREAD

**Issue by BennoKrojer** [numpy/numpy#16181] opened 2020-05-07 17:09 UTC
I think the issue is self explanatory when looking at the code below. The second boolean should be False.
Is this intended? If so, should there be some kind of Warning for the user? I couldn't figure why my code wasn't working until I realized that I have to convert my numpy array to a normal list.
### Reproducing code example:

```python
import numpy as np
>>> a = np.array([['a','b','c'], ['d','e','f']])
>>> ['a','b','c'] in a
True
>>> ['c','b','a'] in a
True```


### Numpy/Python version information:
1.18.1 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]

**Comment by ewmoore** [comment] 2020-05-07 21:07
You can't really use `in` to check for subarray membership.  `needle in haystack` is implemented as `np.all(needle == haystack)`.  So you get `True` for the second example because `'b`' is the second column.  You can do what you're trying to do without converting to a list, but you have to explicitly handle that you are looking for matching rows.  `np.any(np.all(['a', 'b', 'c'] == a, axis=1))` will do what you want.

The only reason that this doesn't throw is that `['a', 'b', 'c']` broadcasts against `a`.  If you wanted to find matching columns it wouldn't even get started.

**Comment by eric-wieser** [comment] 2020-05-07 21:15
I think you said `all` when you meant `any`?

**Comment by eric-wieser** [comment] 2020-05-07 21:16
This feels like something we should deprecate.

**Comment by ewmoore** [comment] 2020-05-07 22:36
Yeah, you're right I did.  Edited.

**Comment by ewmoore** [comment] 2020-05-07 22:43
This is probably a duplicate of #3016.

**Comment by seberg** [comment] 2020-05-11 15:57
Closing this in favor of gh-3016. I marked that as "high" priority, but I will not focus on it for now I think. But its been around long enough and confusing to see if we can bump it (if that list ever gets long, I would remove the high).

**Closed by seberg** 2020-05-11 15:57 UTC
