### ISSUE TITLE
dtype constructor and unsigned long long typecode

### ISSUE THREAD

**Issue by dalcinl** [numpy/numpy#13752] opened 2019-06-11 13:51 UTC
I'm trying to implement some automatic MPI <-> NumPy datatype conversion for to enhance mpi4py. Users usually struggle to get it right from complex types, mostly because NumPy defaults to packed structs, while MPI defaults to aligned structs. I'm stuck with an minor issue. I guess it is related Python 2 legacy from the time we had to use an `L` suffix to write long integers. Minimal reproducer and proposed fix in the following.

### Reproducing code example:

```python
import numpy as np
np.dtype("3L")
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/site-packages/numpy/core/_internal.py", line 199, in _commastring
    newitem = (dtype, eval(repeats))
  File "<string>", line 1
    3L
     ^
SyntaxError: unexpected EOF while parsing
```

### Numpy/Python version information:

```
1.16.3 3.7.3 (default, May 11 2019, 00:38:04) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
```
### Proposed trivial fix (tested)

```diff
diff --git a/numpy/core/_internal.py b/numpy/core/_internal.py
index ab5a64a1a..c70718cb6 100644
--- a/numpy/core/_internal.py
+++ b/numpy/core/_internal.py
@@ -146,7 +146,7 @@ def _reconstruct(subtype, shape, dtype):
 # format_re was originally from numarray by J. Todd Miller
 
 format_re = re.compile(br'(?P<order1>[<>|=]?)'
-                       br'(?P<repeats> *[(]?[ ,0-9L]*[)]? *)'
+                       br'(?P<repeats> *[(]?[ ,0-9]*[)]? *)'
                        br'(?P<order2>[<>|=]?)'
                        br'(?P<dtype>[A-Za-z0-9.?]*(?:\[[a-zA-Z0-9,.]+\])?)')
 sep_re = re.compile(br'\s*,\s*')
```

**Comment by mattip** [comment] 2019-06-11 19:37
PR gh-11859 has this fix and tests to make sure it works

**Comment by mattip** [comment] 2019-06-11 19:38
duplicate of #5645

**Closed** 2019-06-12 01:33 UTC
Labels: 00 - Bug, 50 - Duplicate
