### ISSUE TITLE
Testing array assertion shape check fails with float/1d array comparison

### ISSUE THREAD

**Issue by jennirinker** [numpy/numpy#11101] opened 2018-05-15 12:42 UTC
OS details
------------  
- Windows 7, 64-bit  
- Anaconda version 4.5.3  
- Python 3.6  
- Numpy version 1.14.3 (build py36haf40906_0)  

MWE
------
Current behavior: any of the following lines passes    
```np.testing.assert_array_almost_equal(42, [42])```
```np.testing.assert_array_almost_equal([42], 42)```  
```np.testing.assert_array_equal(42, [42])```
```np.testing.assert_array_equal([42], 42)```

Expected output
------------------
Both ```array_almost_equal``` and ```array_almost_equal``` are supposed to check shapes, but it skips the check when comparing floats to 1D arrays.

Notes
-------
This behavior comes from line 711 in ```numpy/testing/_private/utils.py```:  
```cond = (x.shape == () or y.shape == ()) or x.shape == y.shape```
It specifically skips the shape check when one of the inputs is a float. But why is that skip there?

**Comment by mattip** [comment] 2018-05-15 23:12
The float is converted to a scalar, and then compared element-wise to the non-scalar array. While this is by design, I could not find a statement to this effect in the documentation. The closest I got was [here](http://www.numpy.org/devdocs/reference/generated/numpy.testing.assert_array_equal.html#numpy.testing.assert_array_equal) where it states "The usual caution for verifying equality with floating point numbers is advised."

**Comment by jennirinker** [comment] 2018-05-22 07:58
But that statement applies to comparing values of FPN, no? Which is why we need things like `almost_equal`. I'm not sure that statement is meant to apply to comparing scalars and arrays.

My preference would have the `assert_array_*` functions raise an error at all times the shapes aren't equal. Otherwise, there should be an explicit note in the documentation about this behavior.

**Comment by seberg** [comment] 2023-01-02 21:06
Closing, since for now there is a `strict=True` kwarg, which was added to address this IIRC.

**Closed by seberg** 2023-01-02 21:06 UTC
