### ISSUE TITLE
BUG: Problem with `1 * np.uint64(1)`, wrong result type `np.float64`

### ISSUE THREAD

**Issue by hearues-zueke-github** [numpy/numpy#21395] opened 2022-04-26 11:34 UTC
### Describe the issue:

The multiplication of the python int and the numpy uint64 should return a numpy int64 type, but it is numpy float64 type.

### Reproduce the code example:

```python
import numpy as np
assert type(1*np.uint8(1)) == np.int64
assert type(1*np.uint16(1)) == np.int64
assert type(1*np.uint32(1)) == np.int64
assert type(1*np.uint64(1)) == np.float64 # this makes for me no sense... is there a reason for this?
```

### Error message:

```shell
No errors, but wrong return type only.
```

### NumPy/Python version information:

`sys.version == '3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]'`
`np.__version__ == '1.21.3'`

**Comment by charris** [comment] 2022-04-26 13:24
The problem is that the python int is treated as signed, signed + unsigned promotes and the only available type. The workaround is to explicitly convert the python int, `uint64(1)`.

**Comment by hearues-zueke-github** [comment] 2022-04-26 13:26
So this is not a bug, but an intended behavior? Is this somewhere documented?

**Comment by seberg** [comment] 2022-04-26 19:07
It was intended at some point certainly, but there is also [intention to change it](gh-21103).  Thanks for the report, but I am going to close this as a duplicate of #19294 and others.

**Closed by seberg** 2022-04-26 19:07 UTC
Labels: 00 - Bug
