### ISSUE TITLE
np.matrix doesn't return a matrix wit full brackets

### ISSUE THREAD

**Issue by addy1997** [numpy/numpy#14006] opened 2019-07-15 06:09 UTC
### Reproducing code example:

```python
import numpy as np
<<  a=np.matrix(1,2,3) >>
```

**Comment by addy1997** [comment] 2019-07-15 06:10
this is the main issue when trying to multiply two matrices.

**Comment by rkern** [comment] 2019-07-15 06:41
Did you mean `np.matrix([1, 2, 3])` instead?

**Comment by addy1997** [comment] 2019-07-15 06:57
Yes

**Comment by mattip** [comment] 2019-07-15 13:20
@addy1997 can you give a more complete example of what exactly you are running, what the result is, what you expect, what version of python and numpy you are using, and what OS platform you are on?

**Comment by addy1997** [comment] 2019-07-15 16:39
sure

**Comment by seberg** [comment] 2019-09-22 22:49
Closing, it is way too cryptic for me what the issue is supposed to be. Also, it seems that it probably has to do with `matrix`, which I do not think we have intention of modifying much in any case. Please use `np.array` and the matrix-multiply operator `@` instead (for most purposes).

**Closed by seberg** 2019-09-22 22:49 UTC
Labels: 57 - Close?
