### ISSUE TITLE
NumPy Example at SciPy.org

### ISSUE THREAD

**Issue by zazen000** [numpy/numpy#14282] opened 2019-08-15 15:23 UTC
Copied code for NumPy.ipmt at https://docs.scipy.org/doc/numpy/reference/generated/numpy.ipmt.html#numpy.ipmt.

```python
import numpy as np
principal = 2500.00
per = np.arange(1*12) + 1
ipmt = np.ipmt(0.0824/12, per, 1*12, principal)
ppmt = np.ppmt(0.0824/12, per, 1*12, principal)
fmt = '{0:2d} {1:8.2f} {2:8.2f} {3:8.2f}'
for payment in per:
    index = payment - 1
    principal = principal + ppmt[index]
    print(fmt.format(payment, ppmt[index], ipmt[index], principal))
```

Expected output:

 1   -200.58    -17.17   2299.42
 2   -201.96    -15.79   2097.46
 3   -203.35    -14.40   1894.11
 4   -204.74    -13.01   1689.37
 5   -206.15    -11.60   1483.22
 6   -207.56    -10.18   1275.66
 7   -208.99    -8.76     1066.67
 8   -210.42    -7.32      856.25
 9   -211.87    -5.88      644.38
10   -213.32   -4.42      431.05
11   -214.79   -2.96      216.26
12  -216.26    -1.49     -0.00

I get:

0      -216.26        -1.49         2283.74
 1      -199.21       -18.53        2084.52
 2      -200.58       -17.17        1883.94
 3      -201.96       -15.79        1681.98
 4      -203.35       -14.40        1478.64
 5      -204.74       -13.01        1273.89
 6      -206.15       -11.60        1067.74
 7      -207.56       -10.18         860.18
 8      -208.99        -8.76          651.19
 9      -210.42        -7.32          440.77
10      -211.87        -5.88         228.90
11      -213.32        -4.42         15.57
12      -214.79        -2.96        -199.21

per variable is supposed to start the payment number count at 1, but as you can see, when I do it, it starts at 0 and throws off the entire array.

### Python version information: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

How do I get an accurate array?
Thank you.

**Comment by seberg** [comment] 2019-08-15 15:42
Sounds like a duplicate of gh-9495. Note that the financial functions are fairly unmaintained, the current maintainers just do not care much (or have the background). If someone really cares about this, they should create a standalone package outside of numpy.

For example we had a similar issue opened about npv or so, where it turned out two definitions existed and whatever you do half of the users seem to think it is wrong. Frankly, I think in this case it may well be that the only thing to improve may be a small note in the documentation to clarify this.

**Comment by brilhana** [comment] 2019-09-16 21:03
I'm unable to reproduce this issue on Python 3.7.4 and Numpy 1.7.2.

**Comment by seberg** [comment] 2019-09-16 21:18
Thanks for having a look @brilhana. Yes, I will close this, the example above does not make much sense, since it starts with printing 0, when payment is defined in a way that it should start with 1. @zabbarob if we are missing something, please just post and we can reopen.

**Closed by seberg** 2019-09-16 21:18 UTC
Labels: 50 - Duplicate, component: numpy.lib.financial
