### ISSUE TITLE
eigh crashes python for illegal input on win32

### ISSUE THREAD

**Issue by valhallasw** [numpy/numpy#3343] opened 2013-05-21 09:52 UTC
Using
- Python 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)] on win32) and
- numpy 1.7.1 (as [packaged by python(x,y)](https://code.google.com/p/pythonxy/wiki/Downloads#Plugin_updates))), 

the following snippet:

``` python
>>> np.linalg.eigh(np.zeros((0,0)))
```

results in a python crash with the following output

```
 ** On entry to DSYEVD parameter number  5 had an illegal value
```

The expected result is an exception, with either the same text or a more descriptive error ('cannot calculate eigenvalues of a 0x0 matrix').

On
- Python 2.7.3 (default, Aug  1 2012, 05:14:39, [GCC 4.6.3] on linux2) and
- numpy 1.6.1,

the same snippet results in

``` python
>>> np.linalg.eigh(np.zeros((0,0)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 1188, in eigh
    at = a.transpose().astype(result_t)
ValueError: On entry to DSYEVD parameter number 5 had an illegal value
```

**Comment by ilayn** [comment] 2020-01-06 11:15
this is a no-repro with the latest master

**Comment by mattip** [comment] 2020-01-06 13:45
@ilayn just making sure you checked with 32-bit windows?

**Comment by ilayn** [comment] 2020-01-06 14:56
Yes on a Win7 32bit laptop. But I forgot to check for the Win version, maybe Python 3 made the difference but no idea about the reason.

**Comment by mattip** [comment] 2020-07-13 06:04
I am going to close this, please open a new issue if this can be reproduced.

**Closed by mattip** 2020-07-13 06:04 UTC
Labels: 00 - Bug, component: numpy.linalg
