### ISSUE TITLE
Bug in np.repeat for large 1D array

### ISSUE THREAD

**Issue by ivarzap** [numpy/numpy#11441] opened 2018-06-28 14:18 UTC
Bug? in np.repeat for large 1D array. When several times are repeated (here 50), an incorrect max() is obtained
```
import numpy as np
d=np.load('d.npy')
assert d.shape==(19913914,)
assert np.max(d) == 83480
assert np.max(np.repeat(d,10))==83480
np.max(np.repeat(d,50))
```
In the last line and depending on don't know what, I obtain larger numbers, for example, now: `np.max(np.repeat(d,50))=305530`
Similar behavior is obtained with np.tile().
I am enclosing a gzipped version of 'd.npy'

[d.npy.gz](https://github.com/numpy/numpy/files/2145650/d.npy.gz)

**Comment by seberg** [comment] 2018-06-28 15:21
@ivarzap, I cannot reproduce on python3 with 1.14.5. Which numpy, python version are you using, also which operating system and since these are pretty large numbers, is your sstem 64 or 32 bit?

**Comment by seberg** [comment] 2018-06-28 15:57
Glancing at the code, I don't see an obvious bug as well, nor where there any code changes. In case nobody else can reproduce, could you run it through a tool like valgrind?

**Comment by ivarzap** [comment] 2018-06-28 16:42
I was running that code with a 64bit Ubuntu 16.04, python 3.5.2 and numpy 1.14.3. However and after upgrading to 1.14.5, it looks like I get the correct result. Could it be the numpy version?

**Comment by seberg** [comment] 2018-06-28 19:11
As far as I can see there were no changes in years. Unless, the bug actually hides inside `np.max`/the ufunc machinery (which is why I was aking about the argmax thing).

It could also be a random thing, but I really can't point a finger on how that would be plausible, there is some code I find mildly strange, but it looks OK really. I will try with the `1.14.3` tagged version, but are you sure there isn't something else, or can you still reproduce it on the old version?

**Comment by mattip** [comment] 2018-06-28 20:44
We modified `max` and `min` error checking for 1.14.4, perhaps that fixed (or is now masking a still-existing) issues. What is the dtype?

**Comment by seberg** [comment] 2018-06-28 21:47
Yeah, I tried with the version tagged 1.14.3 though, and it seemed fine (and I do have avx and avx2 if that is important, otherwise mostly newer system, if compiler version matters and using py3.6). That datasets dtype is `uint32`, so not sure if the error changes can do much, I think they were only float related?
valgrind is not showing anything for me as well. @ivarzap it would be very good if you manage to reproduce it again, I suppose there might be something very subtly wrong somewhere and finding it without a reproduction....

**Comment by seberg** [comment] 2021-07-02 00:18
I am going to close this, since the bug vanished and we were not able to reproduce.  Would be great to know what the problem was, but its not worth keeping an issue with nowhere to start digging.

**Closed by seberg** 2021-07-02 00:18 UTC
Labels: 00 - Bug
