### ISSUE TITLE
BUG: exp on macOS fails tests

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13586] opened 2019-05-19 06:38 UTC
@tylerjereddy reports the following test failure output from the latest master branch commit (8a421d9) when running full test suite on a Mac laptop:

@r-devulap, @juliantaylor  - any thoughts?

<details>

```
________________________ TestSpecialFloats.test_exp_values _________________________
[gw1] darwin -- Python 3.6.5 /Users/treddy/miniconda3/envs/numpy_dev_py36/bin/python

self = <numpy.core.tests.test_umath.TestSpecialFloats object at 0x11bccdac8>

    def test_exp_values(self):
        x = [np.nan,  np.nan, np.inf, 0.]
        y = [np.nan, -np.nan, np.inf, -np.inf]
        for dt in ['f', 'd', 'g']:
            xf = np.array(x, dtype=dt)
            yf = np.array(y, dtype=dt)
>           assert_equal(np.exp(yf), xf)
E           RuntimeWarning: invalid value encountered in exp

dt         = 'f'
self       = <numpy.core.tests.test_umath.TestSpecialFloats object at 0x11bccdac8>
x          = [nan, nan, inf, 0.0]
xf         = array([nan, nan, inf,  0.], dtype=float32)
y          = [nan, nan, inf, -inf]
yf         = array([ nan,  nan,  inf, -inf], dtype=float32)

numpy/core/tests/test_umath.py:659: RuntimeWarning
1 failed, 8641 passed, 63 skipped, 15 xfailed, 3 xpassed in 120.79 seconds
```

**Comment by r-devulap** [comment] 2019-05-19 14:03
I was able to reproduce this my SKX, but only when built with clang7.0 (it passes when run with gcc7 and clang6.0). I will debug later today to see where it's coming from ..

**Comment by r-devulap** [comment] 2019-05-19 14:15
This is the instruction that is raising invalid exception: `nan_mask = _mm256_cmp_ps(x, x, _CMP_NEQ_UQ); ` when `x` is a `nan`. Not sure why clang7.0 doesn't like it

**Comment by mattip** [comment] 2019-05-19 15:01
maybe a bug in clang?

**Comment by r-devulap** [comment] 2019-05-19 15:11
probably, `_CMP_LE_OQ` is supposed to non-signaling and as far as I understand that shouldn't set a floating point exception.

**Comment by r-devulap** [comment] 2019-05-19 20:46
Yeah I think this is a clang7 behavior which seems incorrect. I wrote a small test case to confirm this: 

```
printf("mxcsr before = %x\n", _mm_getcsr());                                
__m256 xmin_mask = _mm256_cmp_ps(_mm256_set1_ps(nan), _mm256_set1_ps(1), _CMP_LE_OQ);
printf("mxcsr after = %x\n", _mm_getcsr()); 
```
With gcc and clang6.0: 
```
mxcsr before = 1f80
mxcsr after = 1f80
```

with clang7.0, it sets the invalid bit which I think is incorrect. 
```
mxcsr before = 1f80
mxcsr after = 1f81
```

**Comment by r-devulap** [comment] 2019-05-19 20:49
This test `test_exp_values `only cares about the value of the output, I think it might be okay to disable FPE exceptions just for this test with with `np.errstate(all='ignore'):`

**Comment by mattip** [comment] 2019-05-19 21:01
@charris: We have a mechanism for whitelist/blacklisting compiler bugs, how does it work?

**Comment by charris** [comment] 2019-05-19 21:29
@mattip We have a mechanism for library math functions, but this looks like a constant macro which is probably used to direct a compilation path. If we can detect it during configuration and have a fall back function we can fix it, but I'm not sure what the fallback function would be.

**Comment by charris** [comment] 2019-05-19 21:32
`_CMP_LE_OQ` I wonder what the actual value of this macro is? We could possibly detect/fix that, but it might be architecture dependent.

**Comment by r-devulap** [comment] 2019-05-20 00:13
Its 18 and I think it should be the same across x86 architecture. See https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=3004,3045,3005,2822,737&text=cmp_ps

**Comment by r-devulap** [comment] 2019-05-28 23:43
perhaps this and issue #13400 can be closed now?

**Comment by tylerjereddy** [comment] 2019-05-29 01:01
I can definitely close this because I confirmed the fix this morning.

Perhaps Julian should close the other, though it looks connected at a quick glance.

**Comment by tylerjereddy** [comment] 2019-05-29 01:01
Thanks @r-devulap

**Closed by tylerjereddy** 2019-05-29 01:01 UTC
Labels: 00 - Bug, component: numpy.ufunc
