### ISSUE TITLE
Documentation: RuntimeError when importing numpy

### ISSUE THREAD

**Issue by Harshavardhan-tech** [numpy/numpy#19792] opened 2021-08-30 17:41 UTC
## Documentation

Note that I am using the Python Idle here. Since I do not use any IDE, I suspect that this problem is caused by Numpy, and not by an editor.

I successfully uninstalled Numpy version 1.19.4, and installed Numpy version 1.19.3. Rolling back to Numpy 1.19.3 is a temporary fix.

The problematic Numpy code seems to be:
[How to contribute to the NumPy documentation.docx](https://github.com/numpy/numpy/files/7078427/How.to.contribute.to.the.NumPy.documentation.docx)

def _win_os_check():
    """
    Quick Sanity check for Windows OS: look for fmod bug issue 16744.
    """
    try:
        a = arange(13 * 13, dtype= float64).reshape(13, 13)
        a = a % 17  # calls fmod
        linalg.eig(a)
    except Exception:
        msg = ("The current Numpy installation ({!r}) fails to "
                "pass a sanity check due to a bug in the windows runtime. "
                "See this issue for more information: "
                "https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html")
        raise RuntimeError(msg.format(__file__)) from None

        if sys.platform == "win32" and sys.maxsize > 2**32:
           _win_os_check()

           del _win_os_check

**Comment by charris** [comment] 2021-08-30 18:22
It is telling you that your Windows version has a bug. Downgrading doesn't fix the bug, it just makes it invisible.

**Comment by Harshavardhan-tech** [comment] 2021-08-30 18:45
> It is telling you that your Windows version has a bug. Downgrading doesn't fix the bug, it just makes it invisible.

yes

**Comment by mattip** [comment] 2021-08-31 07:45
Why have you opened 3 issues about the same problem?

Duplicate of #17726

**Closed by mattip** 2021-08-31 07:45 UTC
Labels: 04 - Documentation
