### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by datawranglerai** [numpy/numpy#15584] opened 2020-02-17 11:41 UTC
I'm running PySpark jobs via ``spark-submit``. I've tested on Ubuntu 18.04.3 LTS and Windows 10, receiving the exact same error. I also receive the same error when submitting PySpark jobs to Google Dataproc.

My code structure is borrowed heavily from [this article](https://developerzen.com/best-practices-writing-production-grade-pyspark-jobs-cb688ac4d20f). Specifically, my ``main.py`` file looks like this:

```python
import os
import sys
import argparse
import importlib
import time

# Allows you to run stuff locally - If running locally, you'll have the jobs folder available, in production it's a zip
if os.path.exists('libs.zip'):
    sys.path.insert(0, 'libs.zip')
else:
    sys.path.insert(0, './libs')

if os.path.exists('jobs.zip'):
    sys.path.insert(0, 'jobs.zip')  # makes all modules inside it available for import
else:
    sys.path.insert(0, './jobs')

try:
    import pyspark
except:
    import findspark
    findspark.init()
    import pyspark

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run a PySpark job')
    parser.add_argument('--job', type=str, required=True, dest='job_name', help='The name of the job module you want to run. (ex: poc will run job on jobs.poc package)')
    parser.add_argument('--job-args', nargs='*', help='Extra arguments to send to the PySpark job (example: --job-args template=manual-email1 foo=bar')

    args = parser.parse_args()
    print(f'Called with arguments: {args}')

    environment = {
        'PYSPARK_JOB_ARGS': ' '.join(args.job_args) if args.job_args else ''
    }

    job_args = dict()
    if args.job_args:
        job_args_tuples = [arg_str.split('=') for arg_str in args.job_args]
        print(f'job_args_tuples: {job_args_tuples}')
        job_args = {a[0]: a[1] for a in job_args_tuples}

    print(f'\nRunning job {args.job_name}...\nenvironment is {environment}\n')

    os.environ.update(environment)

    conf = pyspark.SparkConf() \
        .setAppName('xxx') \
        .setMaster('local[*]')

    sc = pyspark.SparkContext.getOrCreate(conf=conf)

    job_module = importlib.import_module('jobs.%s' % args.job_name)

    start = time.time()
    job_module.analyze(sc, **job_args)
    end = time.time()

    print(f'Execution of job {args.job_name} took {end - start} seconds')
```

Whenever I run any code that imports from ``numpy`` I receive the following error message, otherwise my Spark jobs run flawlessly. For example:

```bash
spark-submit --py-files jobs.zip,libs.zip,xxx.py,xxx.py,xxx.py main.py --job my_job
```

I am using a virtual environment for my project, with Python 3.7.5.

### Error message:

```bash
Traceback (most recent call last):
  File "/home/xxx/git/xxx/dist/main.py", line 65, in <module>
    job_module = importlib.import_module('jobs.%s' % args.job_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "jobs.zip/jobs/xxx/__init__.py", line 4, in <module>
  File "/tmp/spark-8a796112-efae-4f6f-a738-68ab88e5eab9/userFiles-d43d0bfd-55db-4247-905f-f002faecc817/xxx.py", line 1, in <module>
    import pandas as pd
  File "/tmp/spark-8a796112-efae-4f6f-a738-68ab88e5eab9/userFiles-d43d0bfd-55db-4247-905f-f002faecc817/libs.zip/pandas/__init__.py", line 17, in <module>
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/home/xxx/envs/xxx/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Numpy/Python version information:

Windows 10:

```bash
1.18.1 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
```

Executing on Ubuntu 18:

```bash
1.18.1 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0]
```

**Comment by mattip** [comment] 2020-03-31 15:18
@datawranglerai it seems this issue was never replied to. Were you able to solve the problem? If so please close it. We are not really specialists in spark, so you may find other forums more helpful.

**Comment by pvillacorta-stratio** [comment] 2020-04-06 20:07
I am having the same issue as well. Did not exactly reproduce the instructions on that link but I am basically doing the same: I am passing a zip file to pyspark via `spark.submit.pyFiles` with my dependencies after generating the zip with `pip install -t dependencies -r requirements.txt` and then zipping the folder. Numpy is a dependency of another python package called `implicit`.

**I am using Python 3.7.7 on a docker with Spark 2.4.5 departing from Ubuntu 18.04**. Actually my docker was originally the [Big Data Europe](https://github.com/big-data-europe/docker-spark) docker but since it departs from Alpine, and thinking that could cause the issue, I changed them to depart from Ubuntu, but no success.

**ERROR MESSAGE:**

```
Traceback (most recent call last):
  File "/tmp/spark/spark-b9ebea01-716c-423f-a678-d8e7c9d0c640/userFiles-b109ab0e-0a46-4efd-a554-8eed7d73e599/dependencies.zip/numpy/core/__init__.py", line 24, in <module>
  File "/tmp/spark/spark-b9ebea01-716c-423f-a678-d8e7c9d0c640/userFiles-b109ab0e-0a46-4efd-a554-8eed7d73e599/dependencies.zip/numpy/core/multiarray.py", line 14, in <module>
  File "/tmp/spark/spark-b9ebea01-716c-423f-a678-d8e7c9d0c640/userFiles-b109ab0e-0a46-4efd-a554-8eed7d73e599/dependencies.zip/numpy/core/overrides.py", line 7, in <module>
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/spark-ab969d27-3904-4c97-877c-b774f3630754/aml.py", line 20, in <module>
    import implicit
  File "/tmp/spark/spark-b9ebea01-716c-423f-a678-d8e7c9d0c640/userFiles-b109ab0e-0a46-4efd-a554-8eed7d73e599/dependencies.zip/implicit/__init__.py", line 1, in <module>
  File "/tmp/spark/spark-b9ebea01-716c-423f-a678-d8e7c9d0c640/userFiles-b109ab0e-0a46-4efd-a554-8eed7d73e599/dependencies.zip/implicit/als.py", line 7, in <module>
  File "/tmp/spark/spark-b9ebea01-716c-423f-a678-d8e7c9d0c640/userFiles-b109ab0e-0a46-4efd-a554-8eed7d73e599/dependencies.zip/numpy/__init__.py", line 142, in <module>
  File "/tmp/spark/spark-b9ebea01-716c-423f-a678-d8e7c9d0c640/userFiles-b109ab0e-0a46-4efd-a554-8eed7d73e599/dependencies.zip/numpy/core/__init__.py", line 54, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/bin/python3.7",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```


**My requirements.txt file:**
```
configparser==5.0.0
py4j==0.10.7
pyspark==2.4.5
implicit==0.4.2
```

**Comment by rossbar** [comment] 2020-07-17 20:27
I'm going to close this due to inactivity since it's been a few months since the last discussion. If the problematic component (spark/docker images/etc) was ever identified or a solution was found, feedback would be most welcome. Perhaps a section on spark could could be added to the [troubleshooting docs](https://numpy.org/devdocs/user/troubleshooting-importerror.html) if that was indeed the source of the problem.

**Closed by rossbar** 2020-07-17 20:27 UTC
Labels: 32 - Installation

**Comment by datawranglerai** [comment] 2020-07-18 14:18
Thanks @rossbar. Just thought I'd post my workaround to close off this thread with a solution.

I think it's more of a problem of approach rather than Spark itself: I was trying to wrap up all my project dependencies into a zip folder, which is neat but fundamentally doesn't work with with Python libraries that are wrappers for C code, like NumPy, since their code requires compilation. That's about where my understanding ends.

### My solution/new approach:

I've had a lot more success with configuring the environment of Spark cluster itself then executing my PySpark programme written in pure Python, installing the Python package dependencies using `pip install`.  

### Example: Dataproc (GCP)

If you're using Google Cloud Platform, you can specify this really easy when you spin up a new Spark cluster by specifying the packages (with version numbers) to the `metadata` argument when creating a Dataproc cluster, as explained [here](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/init-actions). 

```
REGION="europe-west2"
IMAGE_VERSION="1.5-ubuntu18"  # Uses Python 3.7 

gcloud dataproc clusters create my-cluster \
    --image-version=${IMAGE_VERSION} \
    --region=${REGION} \
    --metadata "PIP_PACKAGES=pandas==1.0.5 numpy==1.19.0" \
    --initialization-actions=gs://goog-dataproc-initialization-actions-${REGION}/python/pip-install.sh
```

**Comment by pvillacorta-stratio** [comment] 2020-07-18 14:38
Thanks a lot @datawranglerai . I am aware that it all the packages needed can be installed in the workers by running pip install on each worker. The thing is that we often run in clusters with no external internet access (e.g. in banks) so I was trying to avoid that solution.

**Comment by seberg** [comment] 2020-07-18 14:43
@pvillacorta-stratio AFAIK you can do pip install from folders, so you can pre-download all the files put them into a zip and then pip install them from there.  I do not know the exact incarnation, but I do think it should be pretty straight forward.
