### ISSUE TITLE
numpy.histogram vs. numpy.histogram2d

### ISSUE THREAD

**Issue by ahojnnes** [numpy/numpy#4521] opened 2014-03-19 22:20 UTC
Minor, but:

`numpy.histogram` deprecates the `normed` parameter and introduces a new `density` parameter. `numpy.histogram2d` should use the same interface.

Currently, I don't have the time to fix this...

**Comment by eric-wieser** [comment] 2017-12-11 03:29
Duplicate of #4371

**Closed by eric-wieser** 2017-12-11 03:29 UTC
Labels: component: numpy.lib, difficulty: Easy, priority: normal
