### ISSUE TITLE
numpy installation

### ISSUE THREAD

**Issue by aph61** [numpy/numpy#12395] opened 2018-11-15 11:05 UTC
trying to install numpy (1.15.4) under Python 3.7 (Anaconda 1.9.2). My IDE is Pycharm 2018.2.4 (Community ed.), Windows 7Pro

I tried to install using both conda and pip. In both cases I receive the error message:

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
Original error was: DLL load failed: The specified module could not be found.

Any suggestions to solve the issue?

thanks,

below the complete traceback
```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):

-   File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
-     exec(code_obj, self.user_global_ns, self.user_ns)
-   File "<ipython-input-38-59ab05e21164>", line 1, in <module>
-     import numpy as np
-   File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
-     module = self._system_import(name, *args, **kwargs)
-   File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
-     from . import add_newdocs
-   File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
-     module = self._system_import(name, *args, **kwargs)
-   File "C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
-     from numpy.lib import add_newdoc
-   File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
-     module = self._system_import(name, *args, **kwargs)
-   File "C:\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
-     from .type_check import *
-   File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
-     module = self._system_import(name, *args, **kwargs)
-   File "C:\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
-     import numpy.core.numeric as _nx
-   File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 20, in do_import
-     module = self._system_import(name, *args, **kwargs)
-   File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
-     raise ImportError(msg)
```

**Comment by charris** [comment] 2018-11-15 13:48
I suspect you have several python installations that you don't know about :)

**Comment by aph61** [comment] 2018-11-15 20:34
Hi Charles,

thanks for the suggestion. I re-installed Anaconda from scratch, updated
PyCharm and tried the "import numpy". No luck, error warnings

- you use pip 10.0.1, pip 18.1 available:
- twisted 18.7.0 requires pyhamcrest >= 1.9.0

I updated/installed the packages and importing numpy works fine.
It appears that an Anaconda install by default gives a pip 10.0.1. I think
you have to manually update that

thanks again,

Andreas

**Comment by cmeyer** [comment] 2018-11-16 19:23
The problem seems to be something related to NumPy under 3.7 requiring the PATH to contain C:\Anaconda3\Library\bin. PyCharm doesn't seem to activate the Anaconda environment.

See also https://youtrack.jetbrains.com/issue/PY-27234

In the PyCharm issue linked above, users are treating this like a problem in PyCharm, but I think the problem is more general in how NumPy is requiring PATH to be configured differently in 3.7 from how it was required in 3.6.

We run both 3.6 and 3.7 side by side and we launch using a custom binary (not PyCharm). If we launch using a Windows shortcut to the 3.6 version, it works fine. Launching similar shortcut to the 3.7 version fails with the DLL error unless we explicitly set the PATH appropriately in the shortcut.

**Comment by charris** [comment] 2018-11-16 20:10
NumPy has nothing to do with Anaconda, this sounds like a PyCharm/Anaconda problem. Note that using pip with anaconda is supposed to be OK, but we end up with problem reports anyway.

**Comment by shravanikp** [comment] 2018-11-23 10:51
I see this happening on my Windows 2008 R2 as well.
-- I have removed multiple instances of Python
--Right now on Python 3.6.5
--installed packages using pip and not anaconda

I ve seen this happen on Python 3.5, 3.6,3.7
Reinstalled numpy 1.15.3, 1.14

Running out of options for debugging. This is stopping my work since 2 days.

**Comment by erl987** [comment] 2018-11-23 12:06
@shravanikp Try to add the Anaconda-paths described in the Youtrack-ticket of Jetbrains (https://youtrack.jetbrains.com/issue/PY-27234) to your `PATH` environment variable. That has fixed the problem for me. It is actually a PyCharm and not a numpy problem, I think.

**Comment by aph61** [comment] 2018-11-23 18:57
Hi all,

as most of you, I also had problems getting pycharm + Anaconda 5.3.1./Python
3.7 work together.
For the purist probably a horrible solution, but for me the following
approach worked best.

- get rid of Anaconda completely, do a clean install of Python 3.6.7
- manually add the required libaries (acceptable for me, I don't need that
many)

This is a hack, but I think you get away with it if you have only one, two
projects going.

Andreas (enjoying coding, again)

**Comment by YoungJaeChoung** [comment] 2019-02-19 08:15
@aph61 

Thanks. Your solution saved me before I was going to give up. 
It worked for me, too. Although, I have to reinstall other libraries (like pytorch)
(I didn`t guess that this problem is due to the version of programs)

Thanks, again!!

**Comment by rgommers** [comment] 2019-05-19 10:05
problem resolved and not a NumPy bug, so closing. thanks all

**Closed by rgommers** 2019-05-19 10:05 UTC
