### ISSUE TITLE
argwhere does not work with pandas Series

### ISSUE THREAD

**Issue by drkarthi** [numpy/numpy#15555] opened 2020-02-12 20:33 UTC
np.argwhere() does not work on a pandas series in v1.18.1, whereas it works in an older version v1.17.3. Also, np.where() works on a pandas series but np.argwhere() does not.

### Reproducing code example:

```python
import numpy as np
import pandas as pd

ser = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
np.argwhere(ser < 0)
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in argwhere
  File "/Users/kramanathan/anaconda3/envs/py3.7/lib/python3.7/site-packages/numpy/core/numeric.py", line 584, in argwhere
    return transpose(nonzero(a))
  File "<__array_function__ internals>", line 6, in nonzero
  File "/Users/kramanathan/anaconda3/envs/py3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1896, in nonzero
    return _wrapfunc(a, 'nonzero')
  File "/Users/kramanathan/anaconda3/envs/py3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/kramanathan/anaconda3/envs/py3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapit
    result = wrap(result)
  File "/Users/kramanathan/anaconda3/envs/py3.7/lib/python3.7/site-packages/pandas/core/generic.py", line 1918, in __array_wrap__
    return self._constructor(result, **d).__finalize__(self)
  File "/Users/kramanathan/anaconda3/envs/py3.7/lib/python3.7/site-packages/pandas/core/series.py", line 292, in __init__
    f"Length of passed values is {len(data)}, "
ValueError: Length of passed values is 1, index implies 5.
```

### Numpy/Python version information:

1.18.1 3.7.4 (default, Aug 13 2019, 20:35:49)

**Comment by eric-wieser** [comment] 2020-02-12 22:13
Likely caused by me in #13610

**Comment by eric-wieser** [comment] 2020-02-12 22:14
Can you give the _"Full error message, if any (starting from line Traceback: ...) "_, rather than just the last line?

**Comment by drkarthi** [comment] 2020-02-12 22:31
I have just updated the issue with the full error message

**Comment by drkarthi** [comment] 2020-02-12 22:34
Also interestingly, it does not fail with Python 3.6.9 and numpy 1.18.1 but fails with Python 3.7.4 and numpy 1.18.1

**Comment by eric-wieser** [comment] 2020-02-12 22:43
My guess is your pandas version is different between the two python versions?

**Comment by seberg** [comment] 2020-02-12 22:53
I think this may be a pandas issue, and the error is probably correct. Note that I get:
```
/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:61: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
```
with my default pandas+numpy version. So I doubt it was a change inside NumPy that caused the change in behaviour.

Now... the whole thing comes down to `__array_wrap__` in pandas which cannot wrangle the (array) result back into a Series. That makes a lot of sense, but I am not sure whether we want to modify what NumPy does here.

**Comment by drkarthi** [comment] 2020-02-12 23:20
yes, my pandas versions are 0.25.3 where it does not fail and 1.0.1 where it fails

**Comment by drkarthi** [comment] 2020-02-12 23:23
If the issue is in converting an array to a Series, it seems like a pandas issue. I can take a look into why they chose to deprecate `Series.nonzero()`.

**Comment by drkarthi** [comment] 2020-02-12 23:26
The reason I think this is an issue (either for pandas or numpy) is that the user does not necessarily know that np.argwhere uses the `nonzero()` function behind the scenes.

**Comment by miccoli** [comment] 2023-10-26 14:42
Just for reference: I was not able to reproduce this bug with numpy 1.26 and pandas 2.1.1... maybe it is safe to close the issue.

**Closed** 2023-10-26 14:45 UTC
Labels: 00 - Bug
