### ISSUE TITLE
BUG: Error running NumPy installed via pip3 Xcode on macOS Big Sur

### ISSUE THREAD

**Issue by markub3327** [numpy/numpy#17793] opened 2020-11-17 17:25 UTC
Firstly, I installed Xcode command line developer tools. Then, I installed numpy via pip3. When I try to run python code, I give an error. In previous version (macOS Mojave) everything was okay.

### Reproducing code example:

```python
import numpy as np
```

### Error message:

Python(3853,0x112ed8e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744072247156736, flags: 100) failed (error code=3)
Python(3853,0x112ed8e00) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/martin/Library/Python/3.8/lib/python/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

<img width="1312" alt="Snímka obrazovky 2020-11-17 o 18 24 15" src="https://user-images.githubusercontent.com/74611856/99424571-22799980-2902-11eb-8bfc-0b43eaf1cc88.png">

### NumPy/Python version information:

Numpy: 1.19.4
Python: 3.8.2

**Comment by mattip** [comment] 2020-11-17 17:40
Probably a duplicate of gh-17784

**Comment by markub3327** [comment] 2020-11-17 17:45
I don't think because he is using python 3.9 installed from HomeBrew ... @mattip

**Comment by mattip** [comment] 2020-11-17 19:14
It doesn't matter which version of python is used. If it is installed via HomeBrew, it will have been built with the v11 tools.

**Comment by markub3327** [comment] 2020-11-18 07:12
And I'm not using Homebrew! Python and pip has been installed through the Xcode command tools package only. It was working
 on macOS Mojave. If Xcode command tools are  v11 tools, it will been the same trouble.

**Comment by mattip** [comment] 2020-11-20 08:10
Closing as a duplicate. As [noted in the other issue](https://github.com/numpy/numpy/issues/17784#issuecomment-729950525), one solution is
```
brew install openblas
OPENBLAS="$(brew --prefix openblas)" pip install numpy pandas
```

**Closed by mattip** 2020-11-20 08:10 UTC
