### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by oscarthorn** [numpy/numpy#18175] opened 2021-01-15 18:25 UTC
Hi!

I'm working on a Jetson Xavier NX (arm64) device and I suddenly cannot use numpy installed from pip. Installing numpy 1.19.5 works but importing it gives illegal instruction error. This problem is not present if I instead install python 1.18. I have reproduced this bug on a clean system.

### Reproducing code example:

This works:
`pip install -U numpy`

This does not:
`import numpy`

`Illegal instruction (core dumped)`

**Comment by charris** [comment] 2021-01-15 18:49
This is a duplicate of #18131, seems to be due to the compiler rearranging code.

**Closed by charris** 2021-01-15 18:49 UTC
