### ISSUE TITLE
BUG: Test passes on `ubuntu-latest` but fails for `macos-latest`

### ISSUE THREAD

**Issue by purva-thakre** [numpy/numpy#25395] opened 2023-12-14 17:15 UTC
### Describe the issue:

Got an error while attempting to create a Github Actions workflow for `macos-latest`. The same test passes for `ubuntu-latest`. 

I belive this is related to a bug in `numpy` on `macos`. If it is not a `numpy` bug, feel free to close this issue. 

- The function for this test is available here: https://github.com/vprusso/toqito/blob/3e123d0ea3680452abc56741faae92f6983e8db4/toqito/perms/antisymmetric_projection.py#L10
- The attempt at the Github Actions workflow is available at the link in this item. The test failed when `pytest` was used in `tests/`. https://github.com/vprusso/toqito/blob/623b64d5359c4a18a1d1d0f0566ae0801ab13662/.github/workflows/build-test-actions.yml#L103
- Link to the failing test in the workflow run: https://github.com/vprusso/toqito/actions/runs/7173291207/job/19532340600?pr=339#step:5:1540

Failing test is provided in the code sample portion. 

### Reproduce the code example:

```python
import numpy as np
import pytest

from toqito.perms import antisymmetric_projection

# Create a zero vector of length 27
anti_proj_3_3_partial = np.zeros((27, 1))

# Set specific indices to -0.40824829 and 0.40824829
anti_proj_3_3_partial[5] = -0.40824829
anti_proj_3_3_partial[7] = 0.40824829
anti_proj_3_3_partial[11] = 0.40824829
anti_proj_3_3_partial[15] = -0.40824829
anti_proj_3_3_partial[19] = -0.40824829
anti_proj_3_3_partial[21] = 0.40824829


@pytest.mark.parametrize("dim, p_param, partial, expected_result", [
    # Dimension is 2 and p is equal to 1.
    (2, 1, False, np.array([[1, 0], [0, 1]])),
    # The `p` value is greater than the dimension `d`.
    (2, 3, False, np.zeros((8, 8))),
    # The dimension is 2.
    (2, 2, False, np.array([[0, 0, 0, 0], [0, 0.5, -0.5, 0], [0, -0.5, 0.5, 0], [0, 0, 0, 0]])),
    # The `dim` is 3, the `p` is 3, and `partial` is True.
    (3, 3, True, anti_proj_3_3_partial)
])
def test_antisymmetric_projection(dim, p_param, partial, expected_result):
    """Test function works as expected for a valid input."""
    proj = antisymmetric_projection(dim=dim, p_param=p_param, partial=partial).todense()
    np.testing.assert_allclose(proj, expected_result)
```

### Error message:

```shell
FAILED toqito/perms/tests/test_antisymmetric_projection.py::test_antisymmetric_projection[3-3-True-expected_result3] - IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 27
```

### Python and NumPy Versions:

Python Version = 3.10
Numpy version = 1.26.2

**Comment by ngoldbaum** [comment] 2023-12-17 19:16
Is it possible to demonstrate whatever issue you're having without using your library? It's much easier to understand if there even is an issue if the repro script uses fake data instead of something generated from a black box other library.

**Comment by rgommers** [comment] 2023-12-20 20:08
The upstream issue seems to be resolved for now, and there is nothing actionable here - it's a bug in a downstream project rather than in `numpy` it looks like. Hence I'll close this as invalid. @purva-thakre if you do manage to obtain a reproducer that makes clear there's an issue in numpy itself, please do feel free to post it here and we'll reopen this issue.

**Closed by rgommers** 2023-12-20 20:08 UTC
Labels: 53 - Invalid
