### ISSUE TITLE
Testsuite hangs when built with MKL 2018.2 (but not 2017.1)

### ISSUE THREAD

**Issue by bodgerer** [numpy/numpy#10993] opened 2018-04-27 12:43 UTC
Hi,

I've noticed that numpy's testsuite hangs when numpy is built against MKL 2018.2 - but runs to completion when built against MKL 2017.1.

This is the case for numpy v1.14.2, 1.14.x HEAD and master branches.

I'm on CentOS 7.4 x86_64 on a Broadwell processor, python 2.7.5 (but also affects other pythons), Cython 0.28.2, nose 1.3.7.

By executing this: python -c "import numpy; numpy.test(verbose=2)"

I can see that the hang occurs while running this test: numpy.distutils.tests.test_exec_command.TestExecCommand.test_basic

At this point, the python interpreter is consuming an entire CPU core and, if I strace it, I see a stream of identical lines, all showing:

sched_yield()                           = 0

Any ideas, please?

Thanks!

**Comment by mattip** [comment] 2018-04-27 12:50
Is it a duplicate of #10060, where it is suggested to use this work around:
```
# work-around 1:
KMP_INIT_AT_FORK=FALSE python script.py
# work-around 2:
MKL_THREADING_LAYER=TBB python script.py` 
```

**Comment by bodgerer** [comment] 2018-04-27 14:27
Got it: sorry for the noise. I did search the issues list, just not well enough - honest!

Thanks

**Comment by mattip** [comment] 2018-04-27 14:49
Our fault, that issue was closed but a new MKL has not been released yet. Please leave this open so others can find it

**Comment by oleksandr-pavlyk** [comment] 2019-01-07 14:05
The fix in Intel OpenMP was released in 2018 update 3 of the library. 

Please close.

**Comment by charris** [comment] 2019-01-07 14:16
Thanks for the heads up.

**Closed by charris** 2019-01-07 14:16 UTC
Labels: 00 - Bug, 29 - Intel/Anaconda
