### ISSUE TITLE
DOC: Mixed capitalization styles in page titles

### ISSUE THREAD

**Issue by bjnath** [numpy/numpy#16261] opened 2020-05-16 14:52 UTC
Page titles in the docs use both 
- `sentence case` [("How to contribute to the NumPy documentation")](https://numpy.org/devdocs/dev/howto-docs.html), where only the first word is capitalized, and 
- `title case` [("Releasing a Version")](https://numpy.org/devdocs/dev/releasing.html), which capitalizes principal words (omitting "a", "of", "the", etc.)

Mixing styles makes the docs seem disorganized; a uniform style would give a better impression.

I vote that we converge on sentence case, which is contemporary usage almost everywhere, and I volunteer to go through our pages and PR the needed changes.

**Comment by rgommers** [comment] 2020-05-16 15:08
+1 for `sentence case`. Thanks for working on this @bjnath

**Comment by WarrenWeckesser** [comment] 2020-05-16 16:09
+1 for consistency.

If we adopt sentence case as the preferred style, eventually that convention should be used consistently throughout the NumPy documentation, including in the section headings of the [NumPy docstring standard](https://numpy.org/devdocs/docs/howto_document.html#docstring-standard). Currently it has the section headings "Other Parameters" and "See Also" (which actually gets rendered as "See also:" in the HTML output--go figure).

**Comment by lyzlisa** [comment] 2021-05-09 16:18
@alize-papp and I are working on this issue (WiMLDS Berlin sprint)

**Comment by misalraj** [comment] 2021-05-09 16:55
I have already updated

**Comment by rgommers** [comment] 2021-05-09 17:24
Note that the issue is a little broader than the one example given, it's about consistency of all titles. @misalraj are you interested to go through the docs and check other pages?

**Comment by rgommers** [comment] 2021-05-09 17:25
Or @lyzlisa and @alize-papp did you start on this? gh-18962 only fixes one page.

**Comment by misalraj** [comment] 2021-05-09 17:26
I will look into this. @rgommers 
Thanks for pointing out.

**Comment by rgommers** [comment] 2021-05-09 17:35
Reopening, there is more to do here for other page titles.

**Comment by melissawm** [comment] 2021-09-10 18:17
Remaining issues (from #19849):

- The page subtitles also have mixed styles, sentence casing can be introduced
- Docs under doc/build needs to be worked upon

**Comment by misalraj** [comment] 2021-09-10 18:20
I will check,

**Comment by lalitmusmade** [comment] 2021-10-30 17:23
Working on this as part of the PyDataGlobal 2021 NumPy-SciPy sprint

**Comment by reshamas** [comment] 2022-03-03 21:33
@InessaPawson 
Is there a consensus on what style of capitalizing words is preferred?
Is is `sentence case` or `title case`?

**Comment by InessaPawson** [comment] 2022-03-03 23:52
@reshamas Yes, please use `sentence case` style.

**Comment by SuzaKrish** [comment] 2022-09-16 19:43
@InessaPawson Does this issue still need work?

**Comment by InessaPawson** [comment] 2022-09-16 20:02
@SuzaKrish Yes. The issue was addressed in some parts of the documentation, but not everywhere.

**Comment by SuzaKrish** [comment] 2022-09-16 20:11
I'd like to work on this as part of the GHC'22 Numpy sprint

**Comment by talhabm** [comment] 2023-04-22 21:23
I'm taking a shot at this as part of a sprint during PyCon US 2023.

**Comment by codeguru42** [comment] 2023-04-22 21:29
I am looking into this. I assume that proper names should remain capitalized when they appear in the middle of a title. However, what qualifies as a "proper name"? For example, we in `doc/DISTUTILS.rst` there are the following words (here as lowercase only) in the titles:

* distutils
* python
* scipy
* numpy

In the case of "scipy" and "numpy" what is the captialization? Is it "scipy", "Scipy", or "SciPy"? And similarly for "numpy".

**Comment by charris** [comment] 2023-04-22 22:42
I won't speak for SciPy (heh), but NumPy refers to the project while numpy is the name of the module. It can be a bit confusing to decide which one to use.

**Closed** 2023-11-02 15:33 UTC
Labels: 15 - Discussion, component: documentation, sprintable
