### ISSUE TITLE
binutils version detection can fail.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#24297] opened 2023-07-30 23:17 UTC
The following code is unreliable for finding the binutils version.

https://github.com/numpy/numpy/blob/1a0066b93a29843140793e9b9d31fbbdaf25f1c7/numpy/core/setup.py#L84-L86

For instance, on Fedora 38 `ld -v` returns "GNU ld version 2.39-9.fc38"

I have used the following quick fix in 1.25.2, but am not all that happy with it.
```
        import re
        binutils_ver = os.popen("ld -v").readlines()[0].strip()
        binutils_ver = re.search(r"\d\.\d\d", binutils_ver)
        if binutils_ver is not None:
            return float(binutils_ver.group()) >= 2.38
        else:
            return False
```

@r-devulap Thoughts?

**Comment by r-devulap** [comment] 2023-07-31 05:05
@charris yeah :( I'm aware of this. Duplicate of https://github.com/numpy/numpy/issues/24195. Will get a fix for it soon.

**Closed** 2023-07-31 12:36 UTC
