### ISSUE TITLE
BUG: Build error with Intel Compiler `undefined reference to int string_heapsort_` on v1.23.0++

### ISSUE THREAD

**Issue by stephenmsachs** [numpy/numpy#22011] opened 2022-07-19 08:15 UTC
### Describe the issue:

Numpy will not build with the Intel compielr commencing tag v1.23.0 while v1.22.4 builds fine.

The final link step throws an error.

### Reproduce the code example:

```python
# Intel OneaPI compilers need to be loaded in the environment
# Easiest way to reproduce is to use Spack `spack install py-numpy@1.23.0%intel`

# By hand installation to reproduce:
git clone https://github.com/numpy/numpy.git
cd numpy/
git checkout v1.23.0
git submodule update --init
pip install .
```

### Error message:

```shell
build/temp.linux-x86_64-3.9/numpy/core/src/npysort/quicksort.o: In function `int _INTERNALffdc6c67::string_quicksort_<npy::string_tag, char>(char*, long, void*)':
  /home/ec2-user/numpy/numpy/core/src/npysort/quicksort.cpp:352: undefined reference to `int string_heapsort_<npy::string_tag, char>(char*, long, void*)'
  build/temp.linux-x86_64-3.9/numpy/core/src/npysort/quicksort.o: In function `int _INTERNALffdc6c67::string_quicksort_<npy::unicode_tag, unsigned int>(unsigned int*, long, void*)':
  /home/ec2-user/numpy/numpy/core/src/npysort/quicksort.cpp:352: undefined reference to `int string_heapsort_<npy::unicode_tag, unsigned int>(unsigned int*, long, void*)'
  build/temp.linux-x86_64-3.9/numpy/core/src/npysort/quicksort.o: In function `int _INTERNALffdc6c67::string_aquicksort_<npy::string_tag, char>(char*, long*, long, void*)':
  /home/ec2-user/numpy/numpy/core/src/npysort/quicksort.cpp:448: undefined reference to `int string_aheapsort_<npy::string_tag, char>(char*, long*, long, void*)'
  build/temp.linux-x86_64-3.9/numpy/core/src/npysort/quicksort.o: In function `int _INTERNALffdc6c67::string_aquicksort_<npy::unicode_tag, unsigned int>(unsigned int*, long*, long, void*)':
  /home/ec2-user/numpy/numpy/core/src/npysort/quicksort.cpp:448: undefined reference to `int string_aheapsort_<npy::unicode_tag, unsigned int>(unsigned int*, long*, long, void*)'
  ld: build/lib.linux-x86_64-3.9/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so: hidden symbol `_Z16string_heapsort_IN3npy11unicode_tagEjEiPT0_lPv' isn't defined
  ld: final link failed: Bad value
```

### NumPy/Python version information:

Python 3.9.13
numpy v1.23.0 - main

**Comment by rgommers** [comment] 2022-07-21 18:11
@serge-sans-paille does this look familiar to you? Similar to ICC issues in Pythran that you recently solved perhaps?

**Comment by tylerjereddy** [comment] 2022-07-21 20:12
btw, if you need someone to bisect down to the exact commit just ping me as we use Intel a lot here

**Comment by serge-sans-paille** [comment] 2022-07-21 20:29
Nothing like pythran issues, but the declaration of `string_heapsort_` is

```
template <typename Tag, typename type>
NPY_NO_EXPORT int
string_heapsort_(type *start, npy_intp n, void *varr);
```
@stephenmsachs can you list the output of `nm -C build/temp.linux-x86_64-3.9/numpy/core/src/npysort/heapsort.o` ?

**Comment by tylerjereddy** [comment] 2022-07-21 20:42
@serge-sans-paille I just reproduced and placed the requested output of that command below the fold

<details>

```
00000000000015c0 T aheapsort_bool
0000000000001700 T aheapsort_byte
00000000000027f0 T aheapsort_cdouble
0000000000002610 T aheapsort_cfloat
0000000000002800 T aheapsort_clongdouble
0000000000002810 T aheapsort_datetime
00000000000024b0 T aheapsort_double
0000000000002370 T aheapsort_float
0000000000002360 T aheapsort_half
0000000000001c00 T aheapsort_int
0000000000001e60 T aheapsort_long
0000000000002600 T aheapsort_longdouble
00000000000020e0 T aheapsort_longlong
0000000000001980 T aheapsort_short
0000000000003710 T aheapsort_string
0000000000002820 T aheapsort_timedelta
0000000000001840 T aheapsort_ubyte
0000000000001d30 T aheapsort_uint
0000000000001fa0 T aheapsort_ulong
0000000000002220 T aheapsort_ulonglong
0000000000003a00 T aheapsort_unicode
0000000000001ac0 T aheapsort_ushort
                 U free
00000000000004d0 T heapsort_bool
00000000000005e0 T heapsort_byte
0000000000001580 T heapsort_cdouble
0000000000001360 T heapsort_cfloat
0000000000001590 T heapsort_clongdouble
00000000000015a0 T heapsort_datetime
0000000000001220 T heapsort_double
00000000000010f0 T heapsort_float
00000000000010e0 T heapsort_half
0000000000000a40 T heapsort_int
0000000000000c60 T heapsort_long
0000000000001350 T heapsort_longdouble
0000000000000ea0 T heapsort_longlong
0000000000000800 T heapsort_short
0000000000002830 T heapsort_string
00000000000015b0 T heapsort_timedelta
00000000000006f0 T heapsort_ubyte
0000000000000b50 T heapsort_uint
0000000000000d80 T heapsort_ulong
0000000000000fc0 T heapsort_ulonglong
0000000000002c00 T heapsort_unicode
0000000000000920 T heapsort_ushort
                 U _intel_fast_memcpy
                 U malloc
0000000000000280 T npy_aheapsort
0000000000000000 T npy_heapsort
0000000000000000 W int aheapsort_<npy::cfloat_tag, npy_cfloat>(npy_cfloat*, long*, long)
0000000000000000 W int aheapsort_<npy::double_tag, double>(double*, long*, long)
0000000000000000 W int aheapsort_<npy::ushort_tag, unsigned short>(unsigned short*, long*, long)
0000000000000000 W int aheapsort_<npy::cdouble_tag, npy_cdouble>(npy_cdouble*, long*, long)
0000000000000000 W int aheapsort_<npy::datetime_tag, long>(long*, long*, long)
0000000000000000 W int aheapsort_<npy::longlong_tag, long long>(long long*, long*, long)
0000000000000000 W int aheapsort_<npy::timedelta_tag, long>(long*, long*, long)
0000000000000000 W int aheapsort_<npy::ulonglong_tag, unsigned long long>(unsigned long long*, long*, long)
0000000000000000 W int aheapsort_<npy::longdouble_tag, long double>(long double*, long*, long)
0000000000000000 W int aheapsort_<npy::clongdouble_tag, npy_clongdouble>(npy_clongdouble*, long*, long)
0000000000000000 W int aheapsort_<npy::int_tag, int>(int*, long*, long)
0000000000000000 W int aheapsort_<npy::bool_tag, unsigned char>(unsigned char*, long*, long)
0000000000000000 W int aheapsort_<npy::byte_tag, signed char>(signed char*, long*, long)
0000000000000000 W int aheapsort_<npy::half_tag, unsigned short>(unsigned short*, long*, long)
0000000000000000 W int aheapsort_<npy::long_tag, long>(long*, long*, long)
0000000000000000 W int aheapsort_<npy::uint_tag, unsigned int>(unsigned int*, long*, long)
0000000000000000 W int aheapsort_<npy::float_tag, float>(float*, long*, long)
0000000000000000 W int aheapsort_<npy::short_tag, short>(short*, long*, long)
0000000000000000 W int aheapsort_<npy::ubyte_tag, unsigned char>(unsigned char*, long*, long)
0000000000000000 W int aheapsort_<npy::ulong_tag, unsigned long>(unsigned long*, long*, long)
0000000000000000 W int heapsort_<npy::cfloat_tag, npy_cfloat>(npy_cfloat*, long)
0000000000000000 W int heapsort_<npy::double_tag, double>(double*, long)
0000000000000000 W int heapsort_<npy::ushort_tag, unsigned short>(unsigned short*, long)
0000000000000000 W int heapsort_<npy::cdouble_tag, npy_cdouble>(npy_cdouble*, long)
0000000000000000 W int heapsort_<npy::datetime_tag, long>(long*, long)
0000000000000000 W int heapsort_<npy::longlong_tag, long long>(long long*, long)
0000000000000000 W int heapsort_<npy::timedelta_tag, long>(long*, long)
0000000000000000 W int heapsort_<npy::ulonglong_tag, unsigned long long>(unsigned long long*, long)
0000000000000000 W int heapsort_<npy::longdouble_tag, long double>(long double*, long)
0000000000000000 W int heapsort_<npy::clongdouble_tag, npy_clongdouble>(npy_clongdouble*, long)
0000000000000000 W int heapsort_<npy::int_tag, int>(int*, long)
0000000000000000 W int heapsort_<npy::bool_tag, unsigned char>(unsigned char*, long)
0000000000000000 W int heapsort_<npy::byte_tag, signed char>(signed char*, long)
0000000000000000 W int heapsort_<npy::half_tag, unsigned short>(unsigned short*, long)
0000000000000000 W int heapsort_<npy::long_tag, long>(long*, long)
0000000000000000 W int heapsort_<npy::uint_tag, unsigned int>(unsigned int*, long)
0000000000000000 W int heapsort_<npy::float_tag, float>(float*, long)
0000000000000000 W int heapsort_<npy::short_tag, short>(short*, long)
0000000000000000 W int heapsort_<npy::ubyte_tag, unsigned char>(unsigned char*, long)
0000000000000000 W int heapsort_<npy::ulong_tag, unsigned long>(unsigned long*, long)
```

</details>

**Comment by serge-sans-paille** [comment] 2022-07-21 21:01
Thanks! Can you try the following patch?

```
diff --git a/numpy/core/src/npysort/heapsort.cpp b/numpy/core/src/npysort/heapsort.cpp
index 1f31ed2..1a9ba28 100644
--- a/numpy/core/src/npysort/heapsort.cpp
+++ b/numpy/core/src/npysort/heapsort.cpp
@@ -207,6 +207,9 @@
     return 0;
 }
 
+template <> void string_heapsort_<string_tag, npy_char>(npy_char*, npy_intp, void*);
+template <> void string_heapsort_<unicode_tag, npy_ucs4>(npy_ucs4*, npy_intp, void*);
+
 template <typename Tag, typename type>
 NPY_NO_EXPORT int
 string_aheapsort_(type *vv, npy_intp *tosort, npy_intp n, void *varr)
```

**Comment by tylerjereddy** [comment] 2022-07-21 21:49
@serge-sans-paille that produced an error:

```
numpy/core/src/npysort/heapsort.cpp:210:35: error: unknown type name 'string_tag'; did you mean 'npy::string_tag'?
template <> void string_heapsort_<string_tag, npy_char>(npy_char*, npy_intp, void*);
                                  ^~~~~~~~~~
                                  npy::string_tag
```

If I adjust to:
```diff
diff --git a/numpy/core/src/npysort/heapsort.cpp b/numpy/core/src/npysort/heapsort.cpp
index 1a9ba2878..93331fe26 100644
--- a/numpy/core/src/npysort/heapsort.cpp
+++ b/numpy/core/src/npysort/heapsort.cpp
@@ -207,8 +207,8 @@ string_heapsort_(type *start, npy_intp n, void *varr)
     return 0;
 }
 
-template <> void string_heapsort_<string_tag, npy_char>(npy_char*, npy_intp, void*);
-template <> void string_heapsort_<unicode_tag, npy_ucs4>(npy_ucs4*, npy_intp, void*);
+template <> void string_heapsort_<npy::string_tag, npy_char>(npy_char*, npy_intp, void*);
+template <> void string_heapsort_<npy::unicode_tag, npy_ucs4>(npy_ucs4*, npy_intp, void*);
 
 template <typename Tag, typename type>
 NPY_NO_EXPORT int

```

I'm left with these errors:
```
INFO: icpx: numpy/core/src/npysort/heapsort.cpp
numpy/core/src/npysort/heapsort.cpp:210:18: error: no function template matches function template specialization 'string_heapsort_'
template <> void string_heapsort_<npy::string_tag, npy_char>(npy_char*, npy_intp, void*);
                 ^
numpy/core/src/npysort/heapsort.cpp:158:1: note: candidate template ignored: could not match 'int (char *, npy_intp, void *)' (aka 'int (char *, long, void *)') against 'void (npy_char *, npy_intp, void *)' (aka 'void (char *, long, void *)')
string_heapsort_(type *start, npy_intp n, void *varr)
^
numpy/core/src/npysort/heapsort.cpp:211:18: error: no function template matches function template specialization 'string_heapsort_'
template <> void string_heapsort_<npy::unicode_tag, npy_ucs4>(npy_ucs4*, npy_intp, void*);
                 ^
numpy/core/src/npysort/heapsort.cpp:158:1: note: candidate template ignored: could not match 'int (unsigned int *, npy_intp, void *)' (aka 'int (unsigned int *, long, void *)') against 'void (npy_ucs4 *, npy_intp, void *)' (aka 'void (unsigned int *, long, void *)')
string_heapsort_(type *start, npy_intp n, void *varr)
^
2 errors generated.

```

**Comment by serge-sans-paille** [comment] 2022-07-21 21:53
My bad, what about

```
diff --git a/numpy/core/src/npysort/heapsort.cpp b/numpy/core/src/npysort/heapsort.cpp
index 1f31ed2..a6d6545 100644
--- a/numpy/core/src/npysort/heapsort.cpp
+++ b/numpy/core/src/npysort/heapsort.cpp
@@ -207,6 +207,9 @@
     return 0;
 }
 
+template <> NPY_NO_EXPORT int string_heapsort_<npy::string_tag, npy_char>(npy_char*, npy_intp, void*);
+template <> NPY_NO_EXPORT int string_heapsort_<npy::unicode_tag, npy_ucs4>(npy_ucs4*, npy_intp, void*);
+
 template <typename Tag, typename type>
 NPY_NO_EXPORT int
 string_aheapsort_(type *vv, npy_intp *tosort, npy_intp n, void *varr)
```

**Comment by tylerjereddy** [comment] 2022-07-21 22:01
Looks like we get back to the original error with that patch

<details>

```
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/temp.linux-x86_64-3.8/numpy/core/src/npysort/quicksort.o: in function `int string_quicksort_<npy::string_tag, char>(char*, long, void*)':
/users/treddy/github_projects/numpy/numpy/core/src/npysort/quicksort.cpp:352: undefined reference to `int string_heapsort_<npy::string_tag, char>(char*, long, void*)'
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/temp.linux-x86_64-3.8/numpy/core/src/npysort/quicksort.o: in function `int string_quicksort_<npy::unicode_tag, unsigned int>(unsigned int*, long, void*)':
/users/treddy/github_projects/numpy/numpy/core/src/npysort/quicksort.cpp:352: undefined reference to `int string_heapsort_<npy::unicode_tag, unsigned int>(unsigned int*, long, void*)'
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/temp.linux-x86_64-3.8/numpy/core/src/npysort/quicksort.o: in function `int string_aquicksort_<npy::string_tag, char>(char*, long*, long, void*)':
/users/treddy/github_projects/numpy/numpy/core/src/npysort/quicksort.cpp:448: undefined reference to `int string_aheapsort_<npy::string_tag, char>(char*, long*, long, void*)'
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/temp.linux-x86_64-3.8/numpy/core/src/npysort/quicksort.o: in function `int string_aquicksort_<npy::unicode_tag, unsigned int>(unsigned int*, long*, long, void*)':
/users/treddy/github_projects/numpy/numpy/core/src/npysort/quicksort.cpp:448: undefined reference to `int string_aheapsort_<npy::unicode_tag, unsigned int>(unsigned int*, long*, long, void*)'
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/temp.linux-x86_64-3.8/numpy/core/src/npysort/heapsort.o: in function `heapsort_string':
/users/treddy/github_projects/numpy/numpy/core/src/npysort/heapsort.cpp:741: undefined reference to `int string_heapsort_<npy::string_tag, char>(char*, long, void*)'
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/temp.linux-x86_64-3.8/numpy/core/src/npysort/heapsort.o: in function `heapsort_unicode':
/users/treddy/github_projects/numpy/numpy/core/src/npysort/heapsort.cpp:746: undefined reference to `int string_heapsort_<npy::unicode_tag, unsigned int>(unsigned int*, long, void*)'
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/lib.linux-x86_64-3.8/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: hidden symbol `_Z17string_aheapsort_IN3npy11unicode_tagEjEiPT0_PllPv' isn't defined
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: final link failed: bad value

```

</details>

**Comment by serge-sans-paille** [comment] 2022-07-22 08:10
@tylerjereddy potential fix in #22024, but please not that it works around the issue, and not *fix* it.

**Comment by AaronBallman** [comment] 2022-07-22 10:46
> @AaronBallman if you have time to look at this, it seems that hidden visibility is honored in a strange way by icc here.

Just to double-check, is this only an issue with ICC or does the issue also occur with ICX?

**Comment by erichkeane** [comment] 2022-07-22 13:15
Those diagnostics don't look like ICC, those look like Clang/ICX?  Does this reproduce in Clang/Clang Trunk?  Could our latest ICX release just have had a 'bad' base version?

**Comment by tylerjereddy** [comment] 2022-07-22 14:41
Can you remind me about the relationship between the switch to the newer OneAPI stuff and the switch to clang under the hood? Are those related? There are a bunch of Intel modules I can load, some are the classic and some are OneAPI.

It may also be that OneAPI by default sets the ICX with our module load, so I'd need to explicitly specify the classic versions of CC, CXX in that case if you want to compare?

That said, to be time efficient, I'm not sure if I should perhaps just verify if Serge's temporary fix works on the ICX if it isn't too harmful? Or would prefer if I check if this is a clang-specific bug and then we somehow reject building with subsets of Intel and clang in our build system or something?

**Comment by erichkeane** [comment] 2022-07-22 14:47
I don't know about the whole OneAPI package, I deal only with the Intel 'C/C++ compiler frontends'.  I believe the OneAPI compilation (anything that does offloading/etc) is all ICX/ICPX, which is our clang-based compiler.  The ICC/ICPC compiler is our EDG based classic-compiler (and has different looking diagnostics).

Serge's workaround looks fine to me, it doesn't seem harmful in any way.  It WOULD be nice to see if this problem is reproducible in Clang-trunk, if not, it is likely it'll be fixed in a future ICX (not this upcoming ?2022.3? release, but the one after).

If it fails in clang-trunk, we can also figure out how to fix it there/minimize the issue that way.

**Comment by tylerjereddy** [comment] 2022-07-22 16:24
A clean rebuild attempt on latest `main` (45bc13e6d) after swapping from oneAPI to classic via `module swap intel-oneapi/2021.2.0 intel-classic/2021.2.0` actually produces a different compile error:

```
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: build/temp.linux-x86_64-3.8/numpy/core/src/npysort/quicksort.o: relocation R_X86_64_PC32 against undefined hidden symbol `_Z16string_heapsort_IN3npy10string_tagEcEiPT0_lPv' can not be used when making a shared object
/usr/projects/hpcsoft/common/x86_64/anaconda/2020.07-python-3.8/compiler_compat/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

**Comment by tylerjereddy** [comment] 2022-07-22 16:30
Same result for `intel/19.1.3`, let me see if I can check clang for you as well, but that may take me longer.

**Comment by tylerjereddy** [comment] 2022-07-22 16:43
`CC=clang CXX=clang++ python setup.py install` seems "ok" at the same hash (build succeeds)

```
(python_3_9_12_scipy_general) tyler@gp160:~/github_projects/numpy$ clang++ --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```

If you think there's good reason to test a newer clang than that (latest dev version is really needed?) let me know.

**Comment by AaronBallman** [comment] 2022-07-22 18:25
So ICC gets one behavior, ICX gets another behavior, and Clang has a third behavior? That is a surprise. 

> That said, to be time efficient, I'm not sure if I should perhaps just verify if Serge's temporary fix works on the ICX if it isn't too harmful? Or would prefer if I check if this is a clang-specific bug and then we somehow reject building with subsets of Intel and clang in our build system or something?

Because ICX is based on Clang, we're mostly trying to figure out whether the issue most likely exists in Clang or whether this is some ICX-specific issue. From there we know who to go file an issue with. But in terms of being time efficient, testing Serge's temporary workaround is a good idea.

**Comment by tylerjereddy** [comment] 2022-07-22 19:26
Do you have a table of which clang version is wrapped by which ICX version?

**Comment by erichkeane** [comment] 2022-07-22 19:39
We don't.  The ICX branch is based directly off of clang `main` (though is often behind by a month or two), so we end up having no real good reference as a side effect.  Its also not clear which version of ICX you are using, but I suspect it is somewhere in the post-13.0 pre-14.0 clang versions.

**Comment by tylerjereddy** [comment] 2022-07-22 19:51
Ok, I'll check to see if our HPC sysadmins have a record of this somehow.

**Comment by AaronBallman** [comment] 2022-07-22 20:10
I filed an internal JIRA ticket to see if we can track the version of clang we base an ICX build on to help with this sort of situation in the future. No promises we'll do it, but at least this pointed out a situation where having that information would be helpful.

**Comment by tylerjereddy** [comment] 2022-07-22 22:31
So, here is what I found out/tried:

- the OneAPI version I was reporting with appears to use clang `12.x`, but also has a OpenCL FPGA interface that may use clang `11.x`
- I tried with an ever newer OneAPI version that appears to use clang `14.0`, but also has a OpenCL FPGA interface that may use clang `12.0` -- I got the same compilation error

On a separate machine, I still couldn't reproduce the compilation error with various clang versions--these just work for me:
- `CC=clang-12 CXX=clang++-12 python setup.py install`
- `CC=clang-11 CXX=clang++-11 python setup.py install`
- and we already succeeded with clang-14 above

So, while its unfortunate I'm doing `clang` tests on a different Linux box, I certainly can't find evidence of a `clang`-specific bug on my end.

**Comment by tylerjereddy** [comment] 2022-07-22 22:39
Of course, those tests won't help if you happened to pick a single specific commit of `clang` that has the bug, but in two different OneAPI releases with different clang folder numbering that's perhaps unlikely?

**Comment by AaronBallman** [comment] 2022-07-24 14:51
Thanks for the extra information, that really helps!

> So, while its unfortunate I'm doing clang tests on a different Linux box, I certainly can't find evidence of a clang-specific bug on my end.

Yup, that sounds like enough evidence to me to suggest this is an ICX issue. The next trick will be trying to come up with a simple reproducer that doesn't require trying to compile all of numpy. If we can get something like that, then I can file a JIRA internally that's far easier for us to try to look into addressing (and if we can't get something like that, it's not the end of the world, I can still file the JIRA).

Are you able to devise a reasonably small reproducer that gives the right behavior in Clang and the unexpected behavior in ICX?

> Of course, those tests won't help if you happened to pick a single specific commit of clang that has the bug, but in two different OneAPI releases with different clang folder numbering that's perhaps unlikely?

It's possible, but seems pretty unlikely to me.

**Comment by tylerjereddy** [comment] 2022-07-24 20:24
I'm not particularly strong with C++ but I could probably dissect out a smaller reproducer if it isn't trivial for someone like Serge to do it.

**Comment by serge-sans-paille** [comment] 2022-07-24 20:37
On Sun, Jul 24, 2022 at 01:24:23PM -0700, Tyler Reddy wrote:
> I'm not particularly strong with C++ but I could probably dissect out a smaller
> reproducer if it isn't trivial for someone like Serge to do it.

I'll take a few weeks off starting today, but if you're patient enough, I'll
happily have a look ;-)

**Closed** 2022-09-02 22:00 UTC
Labels: 00 - Bug, 09 - Backport-Candidate, C++
