### ISSUE TITLE
BUG: numpy.ndim raises VisibleDeprecationWarning

### ISSUE THREAD

**Issue by MikhailRyazanov** [numpy/numpy#20979] opened 2022-02-02 21:18 UTC
### Describe the issue:

The documentation for [`numpy.isscalar`](https://numpy.org/doc/stable/reference/generated/numpy.isscalar.html) says that “In most cases `np.ndim(x) == 0` should be used instead of this function”. However, the following code:
```python
import numpy as np
print(np.ndim([1, (2, 3)]) == 0)
```
issues a warning:
```
/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:3162: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return asarray(a).ndim
```

### Reproduce the code example:

```python
import numpy as np
print(np.ndim([1, (2, 3)]) == 0)
```

### Error message:

```shell
/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:3162: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return asarray(a).ndim
```

### NumPy/Python version information:

1.21.5 3.9.10 (main, Jan 16 2022, 17:12:18) 
[GCC 11.2.0]

**Comment by rossbar** [comment] 2022-02-02 21:23
This is not related to `ndim` - the warning arises from the creation of a "ragged" array, i.e. an array where the number of elements is not the same in each dimension:

```python
>>> a = np.array([1, (2, 3)])
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([1, [2, 3]])
```

This warning is intentional, as the automatic creation of ragged arrays will be disallowed in the future. To suppress this warning, you can explicitly use `dtype=object`

**Comment by rossbar** [comment] 2022-02-02 21:24
Closing as this is the intended behavior, but if you feel the warning message can be improved feel free to make a suggestion.

**Closed by rossbar** 2022-02-02 21:24 UTC
Labels: 00 - Bug

**Comment by MikhailRyazanov** [comment] 2022-02-02 21:28
I was expecting that if the documentation suggest to use this function for testing *any* objects, then the function should not raise cryptic warnings. I don't think that this warning was intentional *in this particular case*, so maybe somebody just forgot to modify the `numpy.ndim` code accordingly or to suppress it there?..

**Comment by MikhailRyazanov** [comment] 2022-02-02 21:29
@rossbar, please reopen. This is a usability issue.

**Comment by mattip** [comment] 2022-02-02 21:46
You are using shorthand to write compact code. Expand it:
```
np.ndim(np.array([1, (2, 3)], dtype=object))
```

**Comment by MikhailRyazanov** [comment] 2022-02-02 22:09
@mattip, I was showing a minimal working example to demonstrate the bug. My actual code looks like
```python
def some_function(arg_1, arg_2, ...):
    ...
    if np.ndim(arg_n) == 0:
        ...
    elif ...:
        ...
    else:
        ....
```
Where should I put `dtype=object` in this code?
`arg_n` comes from somewhere outside, which I can't control, and for my code the arguments like `arg_n=0` and `arg_n=[1, (2, 3)]` are both meaningful, but need to be treated differently.

Please look carefully at what [numpy.isscalar](https://numpy.org/doc/stable/reference/generated/numpy.isscalar.html) documentation says about the type of its argument and how it suggests that “In most cases ``np.ndim(x) == 0`` should be used instead of this function”. So I'm trying to follow the documentation and instead get a deprecation warning. I really suppose that if `numpy.ndim` needs to create some intermediate array, then *it* must use this `dtype=object` inside its implementation. Or change the documentation to clarify that ``np.ndim(x)`` cannot be used with `x` of “*any*” type...

**Comment by MikhailRyazanov** [comment] 2022-02-02 22:22
I guess, this:
https://github.com/numpy/numpy/blob/8840d950e0eedf2eadb96d9867d8f8341e51aaac/numpy/core/fromnumeric.py#L3156
needs to be changes to
```python
        return asarray(a, dtype=object).ndim
```
At least, this is what I can guess from the warning. (The worst part is that this warning reports a line inside NumPy core instead of the place in my code where `np.ndim` is used, so I had to debug it to just find where my “error” was...)

**Comment by rossbar** [comment] 2022-02-02 22:23
Generally, numpy functions work on numpy arrays, so when you pass a non-numpy array into a function expecting an [array_like](https://numpy.org/devdocs/glossary.html#term-array_like), almost always the first step is to convert it to a numpy array with e.g. `np.asarray` or `np.asanyarray`. It is during this array-creation process that the `VisibleDeprecationWarning` is being raised.

You can verify this yourself by trying basically any numpy function:

```python
ragged_input = [1, (2, 3)]
np.asarray(ragged_input)
np.sum(ragged_input)
np.shape(ragged_input)
...
```

All of the above will give the `VisibleDeprecationWarning`, because NumPy will (sometime in the near future) no longer support automatic creation of ragged arrays. If a user wants ragged arrays, they must be *explicit* in stating so by requesting an object array, which supports arbitrary objects (including containers of various length) as array elements. 

> I don't think that this warning was intentional in this particular case, so maybe somebody just forgot to modify the numpy.ndim code accordingly or to suppress it there?

This warning is not limited to `ndim` and is very much intentional.

> Where should I put dtype=object in this code?

This depends on what you want your function to do. Do you want to support ragged object arrays as inputs? Then you could do something like the following:

```python
def some_function(arg_1, arg_2, ...):
    a = np.asarray(arg_1, dtype=object)
    if a.ndim == 0:
    ...
```

**Comment by MikhailRyazanov** [comment] 2022-02-02 22:44
@rossbar,
> Do you want to support ragged object arrays as inputs

No, I'm not interested in “ragged object arrays” at all. I just need to distinguish, so to say, simple objects (which can be processed directly) from compound objects (which need to be split before processing).

Once again, [numpy.isscalar](https://numpy.org/doc/stable/reference/generated/numpy.isscalar.html) says that `np.ndim(x) == 0` should return `False` for “*list*, *tuple*, and other sequence objects”. It doesn't say that for some kinds of `x` it should raise a warning. And, by the way, `np.isscalar(x)` does work properly in my test cases, without any warnings.

The worst part, as I said before and to answer your comment
> but if you feel the warning message can be improved feel free to make a suggestion.

is that the warning is cryptic an useless. It indicates some problem in `numpy/core/fromnumeric.py` but doesn't say which user's code triggered it. This is surely a bug.

**Comment by mattip** [comment] 2022-02-02 23:19
Please use isscalar for your use case. It is not appropriate for np.ndims. That is why the documentation state "In most cases". Your case is not one that is served by using np.ndims.

**Comment by MikhailRyazanov** [comment] 2022-02-02 23:36
Why not to modify the `numpy.ndim` code as suggested [above](https://github.com/numpy/numpy/issues/20979#issuecomment-1028413676)?

And in any case, NumPy warnings should point to the relevant line of user's code, not to its own code inside `numpy/core/fromnumeric.py`.

**Comment by seberg** [comment] 2022-02-02 23:42
If anything, we should modify it to use the internal helpers that skip creating the actual array :).

I think some clearer API on "is scalar" is in order, but we basically have:
* Something that NumPy knows about and is a scalar
  * This one can depend on `dtype=...` in principle!
* Something that looks/is an array:
  * This _could_ be 0-D in which case, is it a "scalar"?
* Something else, which would get inserted as scalar for `np.array([some_object], dtype=object`).

So, you see, we should have a new function to tell you if something is a scalar or not, but the "answer" to that simple question is surprisingly tricky.

**Comment by MikhailRyazanov** [comment] 2022-02-03 00:25
Thanks, @seberg, for constructive comments, finally!

I understand that current implementation of `numpy.ndim`, which creates an array just to get its dimensions, is not optimal, but could you please clarify whether simply changing its `return asarray(a).ndim` to `return asarray(a, dtype=object).ndim` would break anything? Because this deprecation warning suddenly popping up for code that was working fine and, moreover, recommended in the documentation (it still is!) is quite annoying and mysterious.

**Comment by seberg** [comment] 2022-02-03 00:58
I don't think the deprecation warning is wrong in this case (you could argue that it is unnecessary in this particular branch, but generally...).
`np.ndim` can't return a reasonable value for `ndim` in all cases, e.g. what should it report for:
```
np.ndim([[1], [2, 3]])  # Is 1 dimensional really right?
```
So I think for `np.ndim` this is probably reasonable, yes, I am willing to be convinced otherwise.

At this time you can use `np.array(..., dtype=object).ndim`, `dtype=object` does not trigger anything particularly special, so it should never lie about the dimension (compared to not providing any dtype, not compared to providing a _different_ dtype!).
Aside from these weird cases, where it may report fewer dimensions than expected.

The cost is, that you actually convert the input to an object array (it might be an integer array).  And I suppose if our API ever grows to deal with this better, you may have to adapt again.  (e.g. we introduce an `ndim=` or `ndmax=` parameter that you must use for these ragged cases even with `dtype=object`).

Now we do have private API, which can be extended (e.g. with a `maxdims` parameter even) in `np.core._multiarray_umath._discover_array_parameters(obj, dtype=<optional>)`, that will still do most of the work of constructing the array, but not _all_ of it.  But while we probably should expose it in some form, it isn't exposed.

So in any case, we have a problem that `np.isscalar` is strange, but I am not sure what the appetite for changing it is (especially without an annoying FutureWarning), so we tell you that `np.ndim` is often better (and it is!).

But some cases fall through the cracks, where `np.ndim(obj)` is a bit shady (a warning seems not unreasonable to me), but `np,ndim(obj) != 0` is completely fine, but we provide no good way to spell it.

Mild extension of that internal API function could allow implementing such a new function (digging down more could probably make it more efficient, but I doubt it may not be super necessary).

**Comment by MikhailRyazanov** [comment] 2022-02-03 01:26
Well, if all this is so hopeless, two last questions:
1. Could somebody please explain in the docs that using `np.dim(x) == 0` has such pitfalls? So that other people can read it there instead of being frustrated like I am in this conversation...
2. Can this `VisibleDeprecationWarning` please-please-please print a reasonable traceback? I have an application, which uses a library, which uses NumPy. Now when I run the application, I get this `VisibleDeprecationWarning` without any clues which of the thousands of lines of my code is “deprecated”. This is not user-friendly. :–(

**Comment by seberg** [comment] 2022-02-03 01:40
I am not saying it is hopeless, I am saying we need an explicit and new API, and that currently doesn't exist.  To really help you specifically, I think we need to understand better what you are doing.

So it may indeed be hopeless, but only mid-term, not long-term :).

> Can this VisibleDeprecationWarning please-please-please print a reasonable traceback?

No, we try to get warning stacklevels right, but since the warning originates in `np.array()` it cannot point outside of that function (it cannot "skip" the function), without unreasonable amount of additional API.  As far as I am aware.

If you need to track down the exact origin with a traceback, you can for example use:
```
import warnings
warnings.simplefilter("error", np.VisibleDeprecationWarning)
```
(Or similar incarnations with `python -W...`

**Comment by MikhailRyazanov** [comment] 2022-02-03 02:06
> I think we need to understand better what you are doing.

I was trying to follow the documentation.So far, I've switched to `np.isscalar(x)`, which looks fine for my case, but I would be happier if the documentation did not recommend the code that can trigger now-deprecated behavior.

> If you need to track down the exact origin with a traceback, you can for example use ...

Thanks, this is what I've found at Stack Exchange. (Which indicates that I'm not the first to be perplexed by this innovation, but apparently the first who dared to report it here, in vain...)

**Comment by mattip** [comment] 2022-02-03 07:00
PRs to improve documentation clarity are welcome, especially if they come with concise examples.

You might be interested in reading [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) which outlines the reasoning for the deprecation warning.  If ragged arrays are important to you, you may be better served by the [awkward-array](https://github.com/scikit-hep/awkward-1.0) project.

**Comment by MikhailRyazanov** [comment] 2022-02-03 11:56
@mattip, I'm **not** interested in ragged arrays at all. And have already [said so](https://github.com/numpy/numpy/issues/20979#issuecomment-1028428341) quite clearly. If you want to help, please read what I write, instead of arguing with your own fantasies.
