### ISSUE TITLE
np.argsort() has something wrong

### ISSUE THREAD

**Issue by starbaby01** [numpy/numpy#11618] opened 2018-07-26 08:30 UTC
i.e:
 a=[2,0,-1,3]
 np.argsort(a)
 output is right:
array([2, 1, 0, 3], dtype=int64)

but:
 a=[2,-1,0,3]
 np.argsort(a)
output has soemthing wrong:
 array([1, 2, 0, 3], dtype=int64)
The correct outpus should be:
 array([2, 0, 1, 3], dtype=int64)

**Comment by eric-wieser** [comment] 2018-07-26 15:45
Duplicate of #8757

**Closed by eric-wieser** 2018-07-26 15:45 UTC
