### ISSUE TITLE
lexsort MemoryError

### ISSUE THREAD

**Issue by pulkin** [numpy/numpy#15998] opened 2020-04-16 13:52 UTC
```python
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.17.0'
>>> np.lexsort(np.empty((0, 2), dtype=int).T)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in lexsort
MemoryError
>>> 
```

**Comment by WarrenWeckesser** [comment] 2020-04-16 14:23
@pulkin, thanks for reporting the issue.  This issue is a duplicate of https://github.com/numpy/numpy/issues/14228, so I'm closing it.

**Closed by WarrenWeckesser** 2020-04-16 14:23 UTC

**Comment by eric-wieser** [comment] 2020-04-16 15:53
Duplicate of #14228
