### ISSUE TITLE
Performance regression between 1.16.4 and 1.11.0

### ISSUE THREAD

**Issue by simoncouture** [numpy/numpy#14776] opened 2019-10-24 22:59 UTC
Hi, I am seeing a performance regression when migrating from numpy 1.11.0 to 1.16.4. The performance decrease seems to be spread across multiple numpy functions, but here is a simple example which shows a consistent performance difference:
```from __future__ import print_function
from __future__ import absolute_import
from __future__ import division

import numpy as np
import cProfile


def mean_test(array):
    return np.mean(array)


def mean_benchmark():
    my_array = np.ones((3, 3), dtype=np.float32)
    for _ in range(7600):
        mean_test(my_array)


if __name__ == "__main__":
    cProfile.run('mean_benchmark()', sort='cumtime')
```

If I run this 3 times, and pick the best run out of the 3, I get:

For numpy 1.11.0:
```python numpy_benchmark.py 
         91207 function calls in 0.125 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.125    0.125 <string>:1(<module>)
        1    0.003    0.003    0.125    0.125 numpy_benchmark.py:113(mean_benchmark)
     7600    0.004    0.000    0.121    0.000 numpy_benchmark.py:9(mean_test)
     7600    0.007    0.000    0.118    0.000 fromnumeric.py:2796(mean)
     7600    0.055    0.000    0.110    0.000 _methods.py:53(_mean)
     7600    0.017    0.000    0.020    0.000 _methods.py:43(_count_reduce_items)
     7600    0.020    0.000    0.020    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     7600    0.005    0.000    0.006    0.000 numeric.py:484(asanyarray)
    15200    0.004    0.000    0.004    0.000 {isinstance}
     7600    0.003    0.000    0.003    0.000 {issubclass}
     7601    0.003    0.000    0.003    0.000 {range}
     7600    0.002    0.000    0.002    0.000 {hasattr}
     7600    0.002    0.000    0.002    0.000 {numpy.core.multiarray.array}
        1    0.000    0.000    0.000    0.000 numeric.py:148(ones)
        1    0.000    0.000    0.000    0.000 {numpy.core.multiarray.copyto}
        1    0.000    0.000    0.000    0.000 {numpy.core.multiarray.empty}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

and for numpy 1.16.4:
```python numpy_benchmark.py 
         98807 function calls in 0.135 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.135    0.135 <string>:1(<module>)
        1    0.004    0.004    0.135    0.135 numpy_benchmark.py:113(mean_benchmark)
     7600    0.004    0.000    0.131    0.000 numpy_benchmark.py:9(mean_test)
     7600    0.010    0.000    0.127    0.000 fromnumeric.py:3014(mean)
     7600    0.062    0.000    0.117    0.000 _methods.py:58(_mean)
     7600    0.020    0.000    0.020    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     7600    0.016    0.000    0.020    0.000 _methods.py:48(_count_reduce_items)
     7600    0.005    0.000    0.006    0.000 numeric.py:541(asanyarray)
    15200    0.005    0.000    0.005    0.000 {issubclass}
    15200    0.004    0.000    0.004    0.000 {isinstance}
     7601    0.003    0.000    0.003    0.000 {range}
     7600    0.002    0.000    0.002    0.000 {hasattr}
     7600    0.002    0.000    0.002    0.000 {numpy.array}
        1    0.000    0.000    0.000    0.000 numeric.py:175(ones)
        1    0.000    0.000    0.000    0.000 {numpy.copyto}
        1    0.000    0.000    0.000    0.000 {numpy.empty}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```
The numpy/python version information printouts are:
For numpy 1.11.0:
```>>> import sys, numpy; print(numpy.__version__, sys.version)
('1.11.0', '2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]')
```
For numpy 1.16.4:
```>>> import sys, numpy; print(numpy.__version__, sys.version)
('1.16.4', '2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]')
```
I'm using pip install to install these different versions of numpy, and I'm running these tests on a machine with Ubuntu 16.04 with a i7-8650U CPU.

It's not a huge difference, but it seems to be consistent and also seems to affect other numpy operations as well. I am seeing a ~5 % decrease in run time for my overall code. I've also tested a few different versions of numpy (1.12.1, 1.13.3, 1.14.5, 1.15.4), and all seem to be slower than 1.11.0.

**Comment by seberg** [comment] 2019-11-18 01:44
Hmm, it does not show up obviously in the timings, but it may be that it is all in C here. It seems likely that this is a small added overhead due to `__array_function__`.

We could hope to improve the speed more generally for some of these things (independently). But it would be larger projects. For example, we currently do a lot of kwarg parsing in C using the typical Python provided parsing functions. These are unfortunately slow on this scale of things (one solution would be relying on cython more, another may be to write some helpers to avoid the generic parsing python provides).

Since I do not think we want to undo `array function` and it is likely as fast as it will get, I am tempted to close, but maybe @shoyer has something, or we can make sure to add it to a tracking issue on array function.

**Comment by olegsinyavskiy** [comment] 2019-11-26 02:32
Hello, we have a bit more data that. I wrote a simple bash oneliner for timing the "bread and butter" of numpy: allocate and reduce:
```time python2.7 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.empty((20, 20)))\")"```

Here are some examples on my 56 cores x86 ubuntu16 machine with numpy 1.11:
```
time python3.6 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.empty((20, 20)))\")"
1.11.0

real    0m3.103s
user    0m3.082s
sys    0m0.020s
```
After installing numpy 1.16:
```
time python3.6 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.empty((20, 20)))\")"
1.16.4

real    0m4.241s
user    0m5.155s
sys    0m4.430s

```

I did more measurements and here is a nice chart with error bars:
![bar_plot_with_error_bars](https://user-images.githubusercontent.com/2086260/69594335-dfb40880-0fb0-11ea-8215-0dbdc0119d4e.png)

Py2 slowdown: 1.42X. But notice Py3 slowdown: 1.64X!

Additionally, I ran:
 - the same across main minor py3 version: 3.5, 3.6, 3.7 - results are roughly similar.
 - the same on mac - similar results
 - the same on tx2 arm board. Results for py2 and 3 give large 65% slowdown. 

I would really appreciate some advice here because numpy upgrade is necessary for many reasons but 40% slowdown is a big deal. In particular, maybe someone can suggest some easy hacks like compilation flags or some internal options?

**Comment by charris** [comment] 2019-11-26 03:03
@pv IIRC, you have some benchmark histories. Where are those located?

**Comment by rgommers** [comment] 2019-11-26 03:05
https://pv.github.io/numpy-bench/

**Comment by rgommers** [comment] 2019-11-26 03:08
40% seems like a lot. The expected slowdown from `__array_function__`:
```
In [1]: %timeit np.amax._implementation(np.empty((20, 20)))                                                                             
4.58 µs ± 57.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [2]: %timeit np.amax(np.empty((20, 20)))                                                                                             
5.2 µs ± 36.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by shoyer** [comment] 2019-11-26 03:19
`__array_function__` isn't even turned on by default on NumPy 1.16 (not until 1.17) so it seems quite likely something else is the culprit here.

**Comment by mattip** [comment] 2019-11-26 03:54
I think `np.amax(np.empty...)` is a problematic API for this kind of micro-benchmark. In your actual code do you see a significant slowdown? I doubt this benchmark reflects your actual use case; some parts of numpy may have gotten faster while others slowed down.

In particular, the `time` output shows a vast difference in `sys` time, indicating something around system calls has changed. Could you try again with a more meaningful allocation than `np.empty`: perhaps allocate once and run many calls to `amax`, or if allocation is what you feel is critical to your workflow then try benchmarking `np.ones` or `np.fill` without the ufunc call.

**Comment by charris** [comment] 2019-11-26 04:05
Hmm, I can't even install the numpy-1.11.3 wheel on my machine, unsupported architecture. Not sure what that is about, I developed 1.11.3 on this platform.
```
charris@fc [~]$ python3.5 -mpip install numpy-1.11.3-cp35-cp35m-manylinux1_x86_64.whl --user
ERROR: numpy-1.11.3-cp35-cp35m-manylinux1_x86_64.whl is not a supported wheel on this platform.
```
So I cannot compare. The simple test isn't that bad for 1.17
```
harris@fc [~]$ time python3   -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.empty((20, 20)))\")"
1.17.4.dev0+5d10f4f

real	0m4.552s
user	0m4.519s
sys	0m0.016s
```
This is on Intel i5. And the profile gives
```
         114009 function calls in 0.088 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.088    0.088 {built-in method builtins.exec}
        1    0.000    0.000    0.088    0.088 <string>:1(<module>)
        1    0.002    0.002    0.088    0.088 speed-regression.py:12(mean_benchmark)
     7600    0.003    0.000    0.086    0.000 speed-regression.py:8(mean_test)
     7600    0.003    0.000    0.083    0.000 <__array_function__ internals>:2(mean)
     7601    0.003    0.000    0.079    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
     7600    0.007    0.000    0.075    0.000 fromnumeric.py:3153(mean)
     7600    0.038    0.000    0.068    0.000 _methods.py:134(_mean)
     7600    0.014    0.000    0.014    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     7600    0.009    0.000    0.009    0.000 _methods.py:50(_count_reduce_items)
     7600    0.001    0.000    0.003    0.000 _asarray.py:88(asanyarray)
    15200    0.002    0.000    0.002    0.000 {built-in method builtins.isinstance}
    15200    0.002    0.000    0.002    0.000 {built-in method builtins.issubclass}
     7600    0.002    0.000    0.002    0.000 {built-in method numpy.array}
     7600    0.001    0.000    0.001    0.000 {built-in method builtins.hasattr}
     7600    0.001    0.000    0.001    0.000 fromnumeric.py:3149(_mean_dispatcher)
        1    0.000    0.000    0.000    0.000 numeric.py:166(ones)
        1    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(copyto)
        1    0.000    0.000    0.000    0.000 {built-in method numpy.empty}
        1    0.000    0.000    0.000    0.000 multiarray.py:1043(copyto)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

**Comment by seberg** [comment] 2019-11-26 15:14
There were likely a few changes, including possiblty the `_wrapreduction` introduction and new kwargs. All of that could add small overheads that accumulate a bit. I doubt we should see this as a serious speed regression that needs to be fixed. It might be motivation to look at what can be done to reduce these type of overheads.

@olegsinyavskiy as Matti was asking, is this really close to your use case? Also if you really care about speed in this code (for such small arrays), have you tried using `np.maximum.reduce` directly to reduce the overhead cost?

**Comment by olegsinyavskiy** [comment] 2019-11-26 17:51
@seberg @mattip this oneliner is just for the community to run. I thought it would be handy to avoid any extra complications with scripts. In production, we obviously use normal profiling utils and real cases. 

This is the actual case we experience slowdown in (obviously, we are not taking max of a random arrays). I found it while profiling the system on ARM (tx2) where slowdown is the most prominent.

Here is an actual real profiling result on numpy 16 on our system:
```
   Ordered by: internal time
   List reduced from 917 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    10083    0.061    0.000    0.061    0.000 {built-in method numpy.array}
     2151    0.048    0.000    0.048    0.000 {method 'reduce' of 'numpy.ufunc' objects}
       13    0.034    0.003    0.043    0.003 perception.py:323(_process_images)
       37    0.029    0.001    0.301    0.008 e_planner.py:304(update_planning)
      129    0.025    0.000    0.122    0.001 e_planner.py:710(_get_forces)
        1    0.023    0.023    1.788    1.788 replay_reader.py:199(run_replay_loop)
```

We mainly use arrays of about 150 x 150, 20 x 20 and 200 x 3. After tracking down several instances of 'reduce' I found them in things like max, sum, min etc. I picked `max` as a representative and picked 20 x 20 at random. 

The case for creation of arrays come from the constructs like `np.mean(a + b)` where `a + b` is created on the fly. Where `a` and `b` are changing as well. Therefore I can't switch to "create once, take max bunch of times" idea.

Here are profiling on the onliner I had:
```
Numpy: 1.11.0
         4000004 function calls in 2.549 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  1000000    1.491    0.000    1.491    0.000 {method 'reduce' of 'numpy.ufunc' objects}
  1000000    0.446    0.000    2.153    0.000 fromnumeric.py:2180(amax)
  1000000    0.370    0.000    0.370    0.000 {numpy.core.multiarray.empty}
  1000000    0.217    0.000    1.707    0.000 _methods.py:25(_amax)
        1    0.026    0.026    0.026    0.026 {range}


Numpy: 1.16.4
         6000004 function calls in 4.600 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  1000000    2.166    0.000    2.166    0.000 {method 'reduce' of 'numpy.ufunc' objects}
  1000000    0.931    0.000    3.606    0.000 fromnumeric.py:69(_wrapreduction)
  1000000    0.649    0.000    4.255    0.000 fromnumeric.py:2397(amax)
  1000000    0.357    0.000    0.357    0.000 fromnumeric.py:70(<dictcomp>)
  1000000    0.318    0.000    0.318    0.000 {numpy.empty}
  1000000    0.151    0.000    0.151    0.000 {method 'items' of 'dict' objects}
        1    0.028    0.028    0.028    0.028 {range}
```

Notice obvious things like _wrapreduction and dict related operations, but mainly notice that `reduce` itself is slower.

**Comment by shoyer** [comment] 2019-11-26 18:40
This might be overhead related to `__array_ufunc__`?

But the bottom line is probably that Python/NumPy is not the right tool for this code if you are concerned about performance when doing operations on small arrays.

**Comment by charris** [comment] 2019-11-26 18:44
Couple of questions.

- Which architectures do you see this on?
- Does this show up in NumPy 1.12 ?
- Where did you get NumPy for ARM ?

I note that there were several changes to `reduce` between 1.11 and 1.12, but the main one seems to have been replacement of `memcpy` by `memmove`. There may be some iterator changes also.

**Comment by charris** [comment] 2019-11-26 19:11
@shoyer Something changed, it would be good to know what and when.

**Comment by charris** [comment] 2019-11-26 23:34
I don't see much difference with 1.11.3
```
charris@fc [~]$ python3.5 speed-regression.py 
         83607 function calls in 0.084 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.084    0.084 {built-in method builtins.exec}
        1    0.000    0.000    0.084    0.084 <string>:1(<module>)
        1    0.002    0.002    0.084    0.084 speed-regression.py:12(mean_benchmark)
     7600    0.004    0.000    0.082    0.000 speed-regression.py:8(mean_test)
     7600    0.009    0.000    0.078    0.000 fromnumeric.py:2843(mean)
     7600    0.036    0.000    0.070    0.000 _methods.py:53(_mean)
     7600    0.014    0.000    0.014    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     7600    0.012    0.000    0.013    0.000 _methods.py:43(_count_reduce_items)
     7600    0.003    0.000    0.004    0.000 numeric.py:484(asanyarray)
    15200    0.002    0.000    0.002    0.000 {built-in method builtins.isinstance}
     7600    0.001    0.000    0.001    0.000 {built-in method builtins.hasattr}
     7600    0.001    0.000    0.001    0.000 {built-in method numpy.core.multiarray.array}
     7600    0.001    0.000    0.001    0.000 {built-in method builtins.issubclass}
        1    0.000    0.000    0.000    0.000 numeric.py:148(ones)
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.copyto}
        1    0.000    0.000    0.000    0.000 {built-in method numpy.core.multiarray.empty}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```
This is with a current compiler `gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)`.

**Comment by olegsinyavskiy** [comment] 2019-11-27 01:00
@shoyer Its just used to be that numpy was the right tool for the job until we decided to upgrade. We have tons of legacy code that uses numpy in this way. IMHO, 180x180 is not so small - its a nice array that might come from many robotic sensors (depth cameras, cheap RGBs etc). 

@charris 
    - Which architectures do you see this on?
      As described above, all measurements are done on x86 by installing from pip. Its just on ARM the difference are more pronounced. So we see it on x86 and ARM. Additionally, I tried it on Mac with the similar results. I do not exclude that the whole issue is about some libraries/compilation flags. I'm just not sure how to debug that.
    - Does this show up in NumPy 1.12 ?
     It looks like a path from 11 to 16 slowdown is incremental. We did some tests to see when does it appear, so it looked like a small performance creep.
     - Where did you get NumPy for ARM ?
    `pip install numpy==1.16.4` It works on ARM by downloading tar and compiling. 

I'm not sure what is `speed-regression.py` so its hard for me to comment on that. This is the reason I posted results with the bash one-liner. If you have some time, would be nice to see results of my one-liner on your machine. Its just a simple copypaste into a terminal.

**Comment by charris** [comment] 2019-11-27 01:32
The `speed-regression.py` was the first code you posted. The short code agrees with your results:
```
charris@fc [~]$ time python3.5 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.empty((20, 20)))\")"
1.11.3

real	0m3.503s
user	0m3.485s
sys	0m0.013s
charris@fc [~]$ time python3.7 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.empty((20, 20)))\")"
1.17.4.dev0+5d10f4f

real	0m4.995s
user	0m4.848s
sys	0m0.035s
```
Also for `ones` instead of `empty`
```
charris@fc [~]$ time python3.5 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.ones((20, 20)))\")"
1.11.3

real	0m5.508s
user	0m5.492s
sys	0m0.008s
charris@fc [~]$ time python3.7 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.ones((20, 20)))\")"
1.17.4.dev0+5d10f4f

real	0m6.852s
user	0m6.827s
sys	0m0.012s
```
For larger arrays the results are reversed, which is interesting.
```
charris@fc [~]$ time python3.5 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(100000): np.amax(np.ones((100, 1000)))\")"
1.11.3

real	0m9.517s
user	0m9.470s
sys	0m0.014s

charris@fc [~]$ time python3.7 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(100000): np.amax(np.ones((100, 1000)))\")"
1.17.4.dev0+5d10f4f

real	0m6.033s
user	0m6.003s
sys	0m0.019s
```
So the problem seems to be small arrays. Apart from possible overhead from `__array_ufunc__`, ISTR that there is a cutoff below which some SIMD optimizations are not made.

**Comment by charris** [comment] 2019-11-27 01:53
If the method is called instead of `amax`, the results are also reversed.
```
charris@fc [~]$ time python3.5 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.ones((20, 20)).max\")"
1.11.3

real	0m2.207s
user	0m2.189s
sys	0m0.015s

charris@fc [~]$ time python3.7 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.ones((20, 20)).max\")"
1.17.4.dev0+5d10f4f

real	0m1.997s
user	0m1.982s
sys	0m0.013s
```
Which suggests `__array_function__` overhead in 1.17 for the `amax` call.

**Comment by rgommers** [comment] 2019-11-27 01:59
> ISTR that there is a cutoff below which some SIMD optimizations are not made.

There's a cutoff below which the temporary elision is not done, but that's large (IIRC 140 kb). I can't remember a size-dependent SIMD optimization (I could be wrong though, if anyone remembers would be nice to identify where this is done).

**Comment by rgommers** [comment] 2019-11-27 02:01
> If the method is called instead of `amax`, the results are also reversed.

Not only reversed, but way faster that the function - that seems to be a pragmatic fix here.

**Comment by charris** [comment] 2019-11-27 02:02
Disabling `__array_function__` results in current NumPy being faster.
```
charris@fc [~]$ export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=0
charris@fc [~]$ time python3.5 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.ones((20, 20)))\")"
1.11.3

real	0m5.782s
user	0m5.760s
sys	0m0.013s
charris@fc [~]$ time python3.7 -c "exec(\"import numpy as np;\nprint(np.__version__)\nfor i in range(1000000): np.amax(np.ones((20, 20)))\")"
1.17.4.dev0+5d10f4f

real	0m5.606s
user	0m5.585s
sys	0m0.012s
```

NumPy 1.11 is still a bit faster for empty arrays, maybe by 5%. I suggest you try running your application with the environment variable set to see if it makes a difference.

**Comment by olegsinyavskiy** [comment] 2019-11-27 02:14
@charris , @rgommers  in your example, you don't seem to call method `max()`. I think you have a misprint forgetting `()`.

**Comment by charris** [comment] 2019-11-27 02:27
@olegsinyavskiy Oops :) Quite right.

If I make the fix, 1.11 is faster with the method, but 1.17 with the method is faster than 1.11 with `amax`. When `__array_function__` is disabled and `amax` is used 1.17 is a hair faster than 1.11.

One other optimization that might be of interest is stacking arrays if that fits with your application.

**Comment by olegsinyavskiy** [comment] 2019-11-27 17:29
@charris Do you think of releasing this array function fix into the wild? Maybe via env variable?

Regarding array stacking, any code rewrite is undesirable since the task was just to upgrade numpy on the legacy codebase, but I guess there is no other option. What do you mean by array stacking?

**Comment by seberg** [comment] 2019-11-27 17:49
@olegsinyavskiy you can already disable `__array_function__` using an environment variable, see: https://numpy.org/neps/nep-0018-array-function-protocol.html#implementation

**Comment by charris** [comment] 2019-11-27 18:04
@olegsinyavskiy Not sure what you mean by the `fix`, it is already and environment variable.
```
export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=0
```
Might be worth renaming that, something like `NUMPY_DISABLE_ARRAY_FUNCTION`. Note that some downstream applications like DASK and CuPY use `__array_function__`, and those might be useful in speeding up your code at some point.

Stacking arrays is putting many arrays into one ndarray object. Note that that multiple axis can be specified in `amax`, so
```
In [3]: np.amax(np.ones((5, 20, 20)), axis=(1,2))                               
Out[3]: array([1., 1., 1., 1., 1.])
```
But as you say, that requires some rewrite. The simplest thing to try up front is the environment variable. I just compile with `-O2`, but I know some of the distributions use `-O3` although it is more susceptible to compiler bugs. What are your current CFLAGS and GCC version?

**Comment by charris** [comment] 2019-11-27 18:29
I assume that you are not working in a virtual environment?

**Comment by olegsinyavskiy** [comment] 2019-12-09 02:02
@charris Thank you for some helpful hints. Here is what we end up doing: replace `np.<reduce>` function to `array.<reduce>` function (e.g. `np.all(a) -> a.all()`). In some places, we wrote `pybind` wrappers that directly call `PyArray_...` functions to avoid python overhead. We are right now in the transition from py2 to py3, so numpy 17 is not an option yet, so we haven't tried `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION` (since in 16 its off by default).

P.S. @charris , no, we don't work in venvs. We use containers for deterministic environments (`docker`-like). As for compiler flags, not sure - we just run `pip wheel` to build wheels on arm and x86 with whatever default args are. How can I check which CFLAGS does it use?

**Comment by seberg** [comment] 2019-12-09 15:32
Just to note, replacing `np.all` with `np.logical_and.reduce` would be a bit quicker than the method and typically the same. In fact, it is likely quicker than your pybind wrappers, because the `PyArray_…` functions usually call back into the ufunc machinery, so that adds some overhead as well.

**Comment by seberg** [comment] 2021-11-05 18:52
I am going to close this, please reopen if it things remain.  The overheads for `array_ufunc` should be much smaller these days (largely non-measurable, when it is unused probably).  The overhead due to `__array_function__` remains, using the methods rather than main namespace functions is still a useful micro-optimization.

In general, the last few releases have seen decent speed-ups of many common small array-cases, so ignore `__array_function__`, I would hope you see a general speed-up nowadays.

**Closed by seberg** 2021-11-05 18:52 UTC
