### ISSUE TITLE
Importing the numpy c-extensions failed

### ISSUE THREAD

**Issue by Pacmansnuff** [numpy/numpy#15842] opened 2020-03-26 18:07 UTC
### Reproducing code example:

```
import numpy 
```

### Error message:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
**-->Done**
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/bin/python3.7",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
**--> looks fine**
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
**-->It was installed directly with Thonny**
     - how you installed numpy
**--->In Thonny, in Manage packages**
     - your operating system
**--->MacOs Catalina 10.15.4** 
     - whether or not you have multiple versions of Python installed
**--->No**
     - if you built from source, your compiler versions and ideally a build log
**--->Not from source**
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Original error was: dlopen(/Users/gaelpacker/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
	/Users/gaelpacker/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: code signature in (/Users/gaelpacker/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

### Numpy/Python version information:
Numpy 1.18.2/Python 3.7

**Comment by mattip** [comment] 2020-03-26 18:19
Duplicate of gh-15670. We need a python-wide response to this problem. Closing, please continue discussion there if you have ideas on how to solve this.

**Closed by mattip** 2020-03-26 18:19 UTC
