### ISSUE TITLE
Cannot install dependent packages with current master

### ISSUE THREAD

**Issue by fonnesbeck** [numpy/numpy#7707] opened 2016-06-05 17:12 UTC
Running a recent build of NumPy from master ('1.12.0.dev0+cc51ba8') on Python 3.5 (OS X 10.11.5), I am not able to build several dependent packages, such as SciPy and Statsmodels. On build, each seems to be unable to locate `npymath`. Here is the output from a failed SciPy build (also from master):

```
    Traceback (most recent call last):
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 373, in read_config
        return _CACHE[pkgname]
    KeyError: 'npymath'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-sdexnjzz-build/setup.py", line 265, in <module>
        setup_package()
      File "/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-sdexnjzz-build/setup.py", line 262, in setup_package
        setup(**metadata)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-sdexnjzz-build/setup.py", line 182, in configuration
        config.add_subpackage('scipy')
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
        caller_level = 2)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
        caller_level = caller_level + 1)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 22, in configuration
        config.add_subpackage('spatial')
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1003, in add_subpackage
        caller_level = 2)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 972, in get_subpackage
        caller_level = caller_level + 1)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 909, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "/private/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-sdexnjzz-build/scipy/spatial/setup.py", line 80, in configuration
        extra_info=get_misc_info("npymath"))
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 2171, in get_info
        pkg_info = get_pkg_info(pkgname, dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 2123, in get_pkg_info
        return read_config(pkgname, dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 375, in read_config
        v = _read_config_imp(pkg_to_filename(pkgname), dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 311, in _read_config_imp
        meta, vars, sections, reqs = _read_config(filenames)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 294, in _read_config
        meta, vars, sections, reqs = parse_config(f, dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 266, in parse_config
        raise PkgNotFound("Could not find file(s) %s" % str(filenames))
    numpy.distutils.npy_pkg_config.PkgNotFound: Could not find file(s) ['/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini']
    
    ----------------------------------------
  Rolling back uninstall of scipy
Command "/Users/fonnescj/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-sdexnjzz-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-a6ef6e4_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-sdexnjzz-build/
```

and here is the same from statsmodels:

```
Traceback (most recent call last):
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 373, in read_config
        return _CACHE[pkgname]
    KeyError: 'npymath'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/z_/kgsm76k94s7_jhnkfydfnd380000gn/T/pip-6x2y6s9_-build/setup.py", line 332, in <module>
        npymath_info = get_info("npymath")
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 2171, in get_info
        pkg_info = get_pkg_info(pkgname, dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 2123, in get_pkg_info
        return read_config(pkgname, dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 375, in read_config
        v = _read_config_imp(pkg_to_filename(pkgname), dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 311, in _read_config_imp
        meta, vars, sections, reqs = _read_config(filenames)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 294, in _read_config
        meta, vars, sections, reqs = parse_config(f, dirs)
      File "/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 266, in parse_config
        raise PkgNotFound("Could not find file(s) %s" % str(filenames))
    numpy.distutils.npy_pkg_config.PkgNotFound: Could not find file(s) ['/Users/fonnescj/anaconda3/lib/python3.5/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini']
    
    ----------------------------------------
Command "python setup.py 
```

**Comment by rgommers** [comment] 2016-06-05 19:18
Any idea if it's specific to OS X or Python 3.5? I can't reproduce this on Linux with current master, and I don't see an immediate candidate among recently merged distutils PRs that could cause this.

**Comment by fonnesbeck** [comment] 2016-06-05 19:19
Will try replicating with 2.7.

**Comment by charris** [comment] 2016-06-05 19:21
Where did you get the source?

**Comment by fonnesbeck** [comment] 2016-06-05 19:22
All packages were installed from github master branches, via pip.

**Comment by fonnesbeck** [comment] 2016-06-05 19:36
Installs fine under 2.7 (both are Anaconda, BTW). I will go back and retry with 3.5.

**Comment by fonnesbeck** [comment] 2016-06-05 20:12
Still fails on 3.5, despite successful re-install of NumPy from master. [Here is the full output](https://gist.github.com/769072613090dc5d1f777cdfc55637c0) of the successful NumPy install and the failed SciPy build.

**Comment by rgommers** [comment] 2016-06-05 20:38
There's something wrong with the numpy install. This should always work, but is failing for you (right?):

    import numpy.distutils
    numpy.distutils.misc_util.get_info('npymath')

Your build log doesn't show anything for numpy. Can you reinstall numpy with ``pip install -U git+https://github.com/numpy/numpy.git -v`` for verbose output?

**Comment by fonnesbeck** [comment] 2016-06-05 20:54
That is correct.

[Here is the verbose install output](https://gist.github.com/3395002e8763b5c913a6b3673c65f385). There are some npymath warnings, but I did not see any errors.

**Comment by matthew-brett** [comment] 2016-06-05 21:05
I get the same error(s) for Python.org Python 3.5 .

**Comment by rgommers** [comment] 2016-06-05 21:13
The build log is not very informative indeed, looks fine. Does ``site-packages/numpy/core/lib/npy-pkg-config/npymath.ini`` exist?

Probably caused by gh-7584.

**Comment by fonnesbeck** [comment] 2016-06-05 21:18
I have one here:

```bash
fonnescj on Marichal.local in ~/anaconda3/pkgs/numpy-1.10.4-py35_0/lib/python3.5/site-packages/numpy/core/lib/npy-pkg-config
$ ls                                                                                                          
mlib.ini    npymath.ini
```

but there is no `lib` directory at all where I would expect it (`~/anaconda3/lib/python3.5/site-packages/numpy/core`):

```bash
fonnescj on Marichal.local in ~/anaconda3/lib/python3.5/site-packages/numpy/core
$ ls
__init__.py                              generate_numpy_api.py                    operand_flag_tests.cpython-35m-darwin.so
__pycache__                              getlimits.py                             records.py
_dummy.cpython-35m-darwin.so             include                                  setup.py
_internal.py                             info.py                                  setup_common.py
_methods.py                              machar.py                                shape_base.py
arrayprint.py                            memmap.py                                struct_ufunc_test.cpython-35m-darwin.so
cversions.py                             multiarray.cpython-35m-darwin.so         test_rational.cpython-35m-darwin.so
defchararray.py                          multiarray_tests.cpython-35m-darwin.so   tests
fromnumeric.py                           numeric.py                               umath.cpython-35m-darwin.so
function_base.py                         numerictypes.py                          umath_tests.cpython-35m-darwin.so
```

**Comment by rgommers** [comment] 2016-06-05 21:23
@charris note that this is probably a blocker for the 1.11.1 release - the ``npy_pkg_config`` change got backported in gh-7590.

**Comment by matthew-brett** [comment] 2016-06-05 21:31
I reverted d73e877 but get the same error.

**Comment by matthew-brett** [comment] 2016-06-05 22:08
I get the same error doing a local install of 1.10.4:

```
$ git co v1.10.4
$ git clean -fxd
$ pip uninstall -y numpy
$ pip install .
$ cd
$ python
>>> import numpy.distutils
>>> numpy.distutils.misc_util.get_info('npymath')
Traceback (most recent call last):
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 378, in read_config
    return _CACHE[pkgname]
KeyError: 'npymath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 2170, in get_info
    pkg_info = get_pkg_info(pkgname, dirs)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 2122, in get_pkg_info
    return read_config(pkgname, dirs)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 380, in read_config
    v = _read_config_imp(pkg_to_filename(pkgname), dirs)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 316, in _read_config_imp
    meta, vars, sections, reqs = _read_config(filenames)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 299, in _read_config
    meta, vars, sections, reqs = parse_config(f, dirs)
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/distutils/npy_pkg_config.py", line 271, in parse_config
    raise PkgNotFound("Could not find file(s) %s" % str(filenames))
numpy.distutils.npy_pkg_config.PkgNotFound: Could not find file(s) ['/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini']
>>> import numpy 
>>> numpy.__version__
'1.10.4'
```

**Comment by charris** [comment] 2016-06-05 22:33
What does `pip --version` show? Is there a `pip3.5`?

**Comment by matthew-brett** [comment] 2016-06-05 22:38
```
$ pip --version
pip 8.1.2 from /Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages (python 3.5)
```

**Comment by charris** [comment] 2016-06-06 00:44
@matthew-brett What if you use `setup.py` instead of pip?

**Comment by charris** [comment] 2016-06-06 00:57
Works here on linux with Python 2.7, 3.4, 3.5 using setup.py.

**Comment by charris** [comment] 2016-06-06 01:10
And just to check, is there anything in the installed `numpy/core/lib`?

**Comment by matthew-brett** [comment] 2016-06-06 01:39
There is no `numpy/core/lib` directory, with the pip install.

Works correctly with install via `python setup.py install`.

**Comment by rgommers** [comment] 2016-06-06 15:50
Summary so far:

- Only happens with ``pip install .`` or ``pip install git+https://github.com/numpy/numpy.git``, not with ``pip install numpy`` or ``python setup.py install``.
- Specific to OS X and Python 3.5 (or 3.x)
- Also happens with older numpy (1.10.4 at least) and older pip (tried 7.1.2)

**Comment by charris** [comment] 2016-06-11 17:13
@rgommers Looks like this is a longer term problem specific to Python 3.5. I'd like to see it fixed but don't think it merits blocker status.

**Comment by rgommers** [comment] 2016-06-11 20:20
> Looks like this is a longer term problem specific to Python 3.5. I'd like to see it fixed but don't think it merits blocker status.

agreed

**Comment by charris** [comment] 2016-06-11 22:57
Just in case, could someone do a search and see if the library is installed anywhere in the system?

**Comment by fonnesbeck** [comment] 2016-06-12 16:37
It is not installed anywhere in my Anaconda Python 3.5 environment. It is present under 2.7.

**Comment by rgommers** [comment] 2016-06-12 16:49
Did a bit of debugging, this is not going to be fun. If I set a breakpoint in ``add_npy_pkg_config`` in ``distutils.misc_util`` and inspect what's added to ``installed_pkg_config``, then on Linux Python 3.5 I get:

    template
        (Pdb) 'numpy/core/npymath.ini.in'

while on OS X I get the same under Python 2.7 but this under Python 3.5:

    template
        (Pdb) '/private/var/folders/bs/gx1g3ccj7wn1bbp_pjl1vm9r0000gn/T/pip-uavhvac7-build/numpy/core/npymath.ini.in'

So somehow the contents of ``self.package_path`` have picked up the absolute path where ``pip`` is building things. The problem is that in ``Configuration.__init__``, this path is determined by grabbing the location of the caller from the frame stack: https://github.com/numpy/numpy/blob/master/numpy/distutils/misc_util.py#L731. Now to figure out which of ``distutils``, ``setuptools``, ``pip`` or ``numpy.distutils`` makes the contents of the stack different on OS X with Python 3.x ......

**Comment by rgommers** [comment] 2016-06-12 19:06
One step further: the issue is that the ``relpath`` function in ``misc_util`` has an issue specific to OS X, because there it receives a path starting with ``/private/var/`` and a ``top_path`` starting with ``/var/``. The latter is symlinked to the former, but ``relpath`` is not smart enough to understand that: http://stackoverflow.com/questions/12482702/pythons-os-chdir-and-os-getcwd-mismatch-when-using-tempfile-mkdtemp-on-ma

**Comment by matthew-brett** [comment] 2016-06-12 19:09
Would a call to `os.path.realpath` help?

**Comment by rgommers** [comment] 2016-06-12 19:11
probably, I'll give it a try. fixing ``rel_path`` and not touching anything else is the way to go here - no telling what will break if I try to clean up the ``get_path_from_frame`` mess

**Comment by rgommers** [comment] 2016-06-12 19:38
OK, fixed by gh-7735 I think.

**Closed** 2016-06-12 20:17 UTC
Labels: component: build
