### ISSUE TITLE
X.dot(X.T, out=K) does not work for X array and K memmap

### ISSUE THREAD

**Issue by horta** [numpy/numpy#7124] opened 2016-01-26 23:01 UTC
``` python
import numpy as np

X = np.memmap('X', shape=(2,3), dtype=float, mode='w+')
X[:] = np.random.randn(2,3)
K = np.empty((2,2), float)

# works
K[:] = X.dot(X.T)

# does not work!
X.dot(X.T, out=K)
```

Error:

> Traceback (most recent call last):
>   File "proof.py", line 11, in <module>
>     X.dot(X.T, out=K)
> ValueError: output array is not acceptable (must have the right type, nr dimensions, and be a C-Array)

Is it not supposed to work that way or it is a bug?

Danilo

**Comment by seberg** [comment] 2016-01-26 23:22
This is somewhat intenional, the output type of the dot function would be a `memmap` array, this is a bit silly, because it does not memmap anything, but....
Frankly, I am not sure that the type check even makes too much sense here. As a workaround, I will suggest to simply make X a baseclass ndarray:
```
X = np.memmap('X', shape=(2,3), dtype=float, mode='w+')
X = np.asarray(X)
```
It will work just as well as long as you do not happen to need some of the extra memmap info around all the time (i.e. manually flushing it to disk).

**Comment by njsmith** [comment] 2016-01-26 23:29
Because of how it's implemented, `dot` has very finicky requirements on the `out=` array -- it's sort of included as a feature for experts who know exactly what they're doing. Probably those checks are a little broken though in that it sounds like it's checking for `type(out) == type(self)` instead of `type(out) == np.ndarray`.

Like @seberg says, a workaround is to create a regular `ndarray` view on the memmap object --  you can do `X_view = np.asarray(X)` and now `X_view` and `X` will refer to the same data in memory, but `np.dot(X_view, X_view.T, out=K)` should work.

**Comment by seberg** [comment] 2019-03-31 13:52
Cannot reproduce it on 1.16, so those checks seem to have been fixed in `np.dot` (out kwarg can be a subclass of ndarray), it is still strange in the sense of returning a memmap, but that is a deficiency of memmap (which I am very sure has an open issue somewhere).

**Closed by seberg** 2019-03-31 13:52 UTC
Labels: 00 - Bug, component: numpy.core
