### ISSUE TITLE
Typing mistakes in documentation

### ISSUE THREAD

**Issue by Arko07-quanta** [numpy/numpy#17185] opened 2020-08-30 07:02 UTC
![Screenshot_20200830-125652_Chrome (1).jpg](https://user-images.githubusercontent.com/63644977/91653239-a5881200-eac0-11ea-99f4-73e40b1c0388.jpg)
Here sum of rows are given as sums of columns and vice versa. Also, I think `axis=0` should give the value of the sum of the rows since numpy first shows rows and then columns in ```np.shape()``` command

**Comment by eric-wieser** [comment] 2020-08-30 08:07
There are two ideas here - the sum formed from adding together rows, and the sum formed by adding together elements within the rows.

We've had confusion over this in the past, hopefully someone can find that discussion and link it here.

**Comment by eric-wieser** [comment] 2020-08-30 08:09
Duplicate of #16697

**Closed by eric-wieser** 2020-08-30 08:09 UTC
Labels: 04 - Documentation
