### ISSUE TITLE
Memory Leak when using np.random.choice with replace = False

### ISSUE THREAD

**Issue by GrimLefourbe** [numpy/numpy#14169] opened 2019-07-31 12:16 UTC
When using choice with an integer arg, the choice function creates a randomised array with np.permutations then returns a slice of this array. This keeps the big array in memory instead of just size elements. The choice function should return a copy of the slice to decrement the ref count of the temporary array.

```python
import numpy as np
a = np.random.choice(a=10**8, size=100, replace=False)
```

### Numpy/Python version information:
Tested in 1.16 but I did not find a fix in the master.

```1.16.2 3.6.8 (default, Apr  1 2019, 17:59:32) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]```

**Comment by seberg** [comment] 2019-07-31 16:35
In case you are interested in that, but `np.random.default_rng.choice` would have a much better behaviour here. (The new random number generator API, it is worth a look!).

**Comment by charris** [comment] 2020-05-28 13:18
Is this still a problem?

**Comment by WarrenWeckesser** [comment] 2020-05-28 19:13
@charris, yes, for the legacy random interface, it still is: https://github.com/numpy/numpy/blob/ba4e4b6558050e0ef0fa3a312a46d65a5f021c16/numpy/random/mtrand.pyx#L979

The recommended way to avoid the problem is to do what @seberg suggested in a comment last year: use the new API that was introduced in 1.17.  It doesn't have this problem:

```
In [8]: rng = np.random.default_rng()

In [9]: a = rng.choice(10**8, size=100, replace=False)
```

In theory, we could fix the old code by making a copy after slicing, but at this point, I don't think we should bother.  If it isn't crashing Python, our policy has been to not touch the old code.

**Comment by mattip** [comment] 2020-05-31 10:15
Closing as a "won't fix" and removing the milestone. Please undo if I am mistaken.

**Closed by mattip** 2020-05-31 10:15 UTC
Labels: 00 - Bug, 03 - Maintenance
