### ISSUE TITLE
BUG: f2py fails with CompilerNotFound error

### ISSUE THREAD

**Issue by shaharkadmiel** [numpy/numpy#13637] opened 2019-05-27 10:56 UTC
After upgrading from numpy version 1.16.2 to 1.16.3, ``f2py -c ... --fcompiler=intelem`` fails with ``CompilerNotFound``. Rolling back to version 1.16.2 everything works as expected.

This doesn't happen with ``--fcompiler=gnu95`` which works on both versions.

Just prior to the traceback I get:
```
customize IntelEM64TCCompiler using build_ext
customize IntelEM64TFCompiler
Found executable /opt/intel/compilers_and_libraries_2018.5.231/mac/bin/intel64/ifort
Intel(R) Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 18.0.5.231 Build 20180823
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
```

```python
Traceback (most recent call last):
  File "/Users/shahar/miniconda3/bin/f2py", line 10, in <module>
    sys.exit(main())
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 683, in main
    run_compile()
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 650, in run_compile
    setup(ext_modules=[ext])
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/Users/shahar/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/shahar/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/shahar/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/Users/shahar/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/shahar/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/shahar/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/command/build_ext.py", line 226, in run
    fcompiler.customize(self.distribution)
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 511, in customize
    get_flags('opt', oflags)
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 502, in get_flags
    flags.extend(getattr(self.flag_vars, tag))
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__
    return self._get_var(name, conf_desc)
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/environment.py", line 56, in _get_var
    var = self._hook_handler(name, hook)
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 709, in _environment_hook
    return hook()
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/intel.py", line 128, in get_flags_opt
    v = self.get_version()
  File "/Users/shahar/miniconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 432, in get_version
    raise CompilerNotFound()
numpy.distutils.fcompiler.CompilerNotFound
```

### Numpy/Python version information:

```
1.16.3 3.7.2 | packaged by conda-forge | (default, Mar 19 2019, 20:46:22) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by mattip** [comment] 2019-05-27 13:51
Could you get to the actual cause of the `CompilerNotFound` error? I think the actual function that is called for `get_version` is `numpy.distutils.ccompiler.CCompiler_get_version`, is that failing on the new version and succeeding on the old (putting a pdb in there and stepping through might shed some light)?

**Comment by shaharkadmiel** [comment] 2019-05-28 06:33
I found this related bug https://github.com/numpy/numpy/pull/13564 and manually implemented the change to line 642 of the ccompiler.py module (https://github.com/numpy/numpy/pull/13564/files) of my currently installed version of numpy (1.16.3). This fixes the issue for me so I vote for implementing this in the next PR.

**Comment by mattip** [comment] 2019-05-28 06:53
That makes this a duplicate of #10569, and will be part of 1.16.4 coming out soon. I will close this, thanks for investigating. Feel free to reopen if needed.

**Closed by mattip** 2019-05-28 06:53 UTC
Labels: 00 - Bug, component: numpy.f2py
