### ISSUE TITLE
`np.rec.fromrecords` looks broken since 1.14.0

### ISSUE THREAD

**Issue by podshumok** [numpy/numpy#10870] opened 2018-04-10 04:00 UTC
```python
>>> dt = [('a', int), ('b', float)]
>>> np.rec.fromrecords([ [1, 1.5], [2, 2.5] ], dtype=dt)
rec.array([[(1, 1. ), (1, 1.5)],
           [(2, 2. ), (2, 2.5)]],
          dtype=[('a', '<i8'), ('b', '<f8')])
```

while in 1.13.3 that would be:
```python
rec.array([(1,  1.5), (2,  2.5)], 
          dtype=[('a', '<i8'), ('b', '<f8')])
```

**Comment by eric-wieser** [comment] 2018-04-10 06:55
Confirmed in master. cc @ahaldane.

`fromrecords` seems generally poorly thought out to me.

**Comment by eric-wieser** [comment] 2018-04-10 06:57
I think this follows on from #10344

**Comment by ahaldane** [comment] 2018-04-13 04:11
Right, looks like #10344.

You can "fix" your code in numpy 1.14 by doing:
```python
np.rec.fromrecords([ (1, 1.5), (2, 2.5) ], dtype=dt)
```
that is, using tuples instead of lists.

We tried to fix this with #10543, this I thought went back to the old behavior but with a  FutureWarning. But looking at that again I'm not sure that reverted the behavior - it only seems to hav added a FutureWarning that doesn't get hit.  Might be worth a second look.

**Comment by eric-wieser** [comment] 2018-04-13 05:28
It seems like everything will work correctly if we sacrifice performance a little and go via an object array (like one codepath already does)

**Comment by ahaldane** [comment] 2018-04-13 05:45
I'm not sure... I think the tricky part is to detect when we got a list of lists that should be converted to a list of tuples. The old code dtected this because the list-of-lists would fail, so then it could fix it up in the except block in `fromrecords`. But now the code no longer fails, so we never get to the fixup.

By the way, another fun example of 1.13 behavior:
```python
>>> p = np.float64(np.pi)
>>> np.rec.fromrecords([ [p, p], [p, p] ], dtype=[('a', 'f4'), ('b', 'f4')])
rec.array([[(  3.37028055e+12,  2.142699), (  3.37028055e+12,  2.142699)],
           [(  3.37028055e+12,  2.142699), (  3.37028055e+12,  2.142699)]], 
          dtype=[('a', '<f4'), ('b', '<f4')])
```

**Comment by podshumok** [comment] 2018-04-13 13:25
BTW, what I was trying to do is to create multidimensional arrays.
so, I had 40x64x4 list of list of list where last 4 elements were of different types.
```
        dtype  = ['u8', 'f8', 'u8', 'f8']
        data = np.array([
            np.array([np.rec.fromrecords(x, dtype=dtype)
            for x in data
        ])
```

**Comment by ahaldane** [comment] 2018-04-13 15:53
@podshumok probably in that particular case, I would recommend:
```python
np.array([[tuple(e) for e in row] for row in data], dtype='u8,f8,u8,f8')
```
(replace `np.array` with  `np.rec.array` if you want a record array)

**Comment by podshumok** [comment] 2018-04-13 16:44
Thank you, I'll give it a try. For now I solved my problem with some `zip`s and standard python sums.

**Comment by mattip** [comment] 2018-04-14 18:45
#10905 was merged, can we close this?

**Comment by ahaldane** [comment] 2018-04-15 23:37
Yes we can. I think it wasn't auto-closed because auto-closing only happens for merges to master.

**Closed by ahaldane** 2018-04-15 23:37 UTC
Labels: 00 - Bug
