### ISSUE TITLE
Entering documentation page from search result covers up the link anchor point

### ISSUE THREAD

**Issue by henrikh** [numpy/numpy#17741] opened 2020-11-09 13:55 UTC
## Documentation

When searching the documentation and clicking on the listed links, the link refers to a specific heading/reference in the generated documentation page. On the new HTML documentation design, the fixed top bar covers up this referenced element:

https://numpy.org/devdocs/reference/generated/numpy.repeat.html?highlight=repeat#numpy.repeat

Image illustrating what is seen when entering the page from a search:

![image](https://user-images.githubusercontent.com/87876/98549521-2f134780-229b-11eb-9c13-b9a9f08bd6ae.png)

Scrolling slightly down reveals the header of the desired content

![image](https://user-images.githubusercontent.com/87876/98549570-45210800-229b-11eb-995c-770102eccf7e.png)

**Comment by rossbar** [comment] 2020-11-09 16:05
It's probably worthwhile to mention this here: https://github.com/pandas-dev/pydata-sphinx-theme

**Comment by mattip** [comment] 2020-11-09 16:25
duplicate of gh-17207, and progress is being made with pandas-dev/pydata-sphinx-theme#258

**Comment by rossbar** [comment] 2020-11-09 16:39
Thanks @mattip - closing as duplicate.

**Comment by eric-wieser** [comment] 2020-11-09 16:40
This is actually a different bug - the sphinx theme only deals with this offset for header links, but does not even attempt to handle it for class / method / attribute links.

**Comment by eric-wieser** [comment] 2020-11-09 16:45
Reported at https://github.com/pandas-dev/pydata-sphinx-theme/issues/282

**Closed by eric-wieser** 2020-11-09 16:45 UTC
Labels: 04 - Documentation
