### ISSUE TITLE
Wrapping a numpy.array around an array.array has some side effects

### ISSUE THREAD

**Issue by MichaelClerx** [numpy/numpy#15860] opened 2020-03-28 19:59 UTC
A python array.array is usually a flexible data structure, but if I wrap a numpy.array around it it "exports a buffer", stopping me from manipulating the original array.array

### Reproducing code example:

```python
#!/usr/bin/env python3
import array
import numpy

x = array.array('d')

for i in range(10):
    x.append(i)

y = numpy.array(x, copy=False)

x.append(11)
```

### Error message:

```
Traceback (most recent call last):
  File "./ff", line 12, in <module>
    x.append(11)
BufferError: cannot resize an array that is exporting buffers
```

### Numpy/Python version information:

Python 3.7.6
Numpy 1.16.4

Does **not** occur for Python 2.7.17 with Numpy 1.16.4

**Comment by seberg** [comment] 2020-03-28 20:11
That is correct, as soon as you export a direct data access to `array.array` it cannot resize or else the data might be invalidated. There is no "solution" to that nor is it a bug. It simply is how the memory management works. If you do not wish this behaviour, you will have to make use of `copy=True`, since then the NumPy array holds no reference to the arrays data. Just to be clear, you should be able to reproduce this just the same if you use `memoryview()` instead of `np.array(..., copy=Flase)`.

**Comment by MichaelClerx** [comment] 2020-03-28 22:07
So what changed since 2.7 then that this has now become an issue where it wasn't before?

And I realise you can't discuss every possible input type on https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html , but nothing there suggests there will be side effects to whatever you pass in as `object`

**Comment by MichaelClerx** [comment] 2020-03-28 22:08
(Just asking!)

**Comment by eric-wieser** [comment] 2020-03-28 22:35
I'm pretty sure you can reproduce this without numpy at all:
```python
import array

x = array.array('d')

for i in range(10):
    x.append(i)

y = memoryview(x)

x.append(11)
```

**Comment by rossbar** [comment] 2020-07-12 16:31
I agree with @eric-wieser : closing as this is not a NumPy  issue. FWIW this is explained (or at least noted) in the [memoryview documentation](https://docs.python.org/3/library/stdtypes.html#memoryview)

**Closed by rossbar** 2020-07-12 16:31 UTC
Labels: 33 - Question
