### ISSUE TITLE
`numpy.exp` is not raising overflow error for large values

### ISSUE THREAD

**Issue by tadeu** [numpy/numpy#11117] opened 2018-05-18 16:58 UTC
Here is an example:

```
import numpy as np
np.seterr(all='raise')
np.exp(750.0)
```

this used to raise `FloatingPointError: overflow...` in older NumPy version, but isn't raising it as of version 1.14.2

**Comment by mattip** [comment] 2018-05-18 17:43
Cannot reproduce on Ubuntu 16.04 64 bit using a local build with gcc. What OS/python are you using, and how did you build or install numpy?

**Comment by tadeu** [comment] 2018-05-18 18:03
I'm using `numpy` from `Anaconda` on Windows x64, it is the one that depends on `mkl_rt`.
This seems to be a machine-dependent problem.

**Comment by njsmith** [comment] 2018-05-18 18:58
Unfortunately we're kind of at the mercy of the c library here – we detect overflow by checking whether the CPU overflow flag is set, and for a complex operation like `exp` then some implementations do that and some don't.

**Comment by mattip** [comment] 2019-09-15 05:19
@oleksandr-pavlyk could this be a compiler incompatibility or is it something the conda-forge recipe patches incorrectly? Compiling vanilla numpy on windows10 raises the `FloatingPointError` as expected

**Comment by tadeu** [comment] 2019-09-16 16:35
It may be an issue of MKL vs other BLAS. This vanilla NumPy compilation is using OpenBLAS?

**Comment by mattip** [comment] 2019-09-16 16:37
The answer to your question is no, this was a compilation using no linalg accelerator. Additionally, BLAS/Lapack is not involved in `np.exp`.

**Comment by tadeu** [comment] 2019-09-16 16:43
Oh, indeed, `exp` has nothing to do with BLAS. My question is more because it _could_ be using VML in the Anaconda version as an optimization (VML is from MKL, incidentally the same provider of optimized BLAS) -- but I didn't look this up.

**Comment by oleksandr-pavlyk** [comment] 2019-09-16 20:48
@tadeu It will be inefficient to use Intel Math Kernel Library's VML routines for a single entry due to an overhead cost. 

I can confirm that NumPy 1.17 from intel channel does raise the FP exception:

```
Python 3.6.9 |Intel Corporation| (default, Sep 11 2019, 11:50:16) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import numpy as np
>>> np.seterr(all='raise')
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>> np.exp(750.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: overflow encountered in exp
>>>
```

However, NumPy in the Intel channel is compiled with Intel C Compiler, and uses Intel's C compiler run-time, which implement scalar transcendental functions. 

NumPy installed from conda-forge channel, presumably also compiled with MSVC raises the error:

```
(np117_v) C:\Users\opavlyk\devel>python
Python 3.6.7 (default, Jul  2 2019, 02:21:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.seterr(all='raise')
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>> np.exp(750.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FloatingPointError: overflow encountered in exp
```

Perhaps someone from Anaconda team needs to look into the problem and comment.

**Comment by tadeu** [comment] 2019-09-17 14:21
Ok, thanks for looking further into this, I've reported it there: https://github.com/AnacondaRecipes/numpy-feedstock/issues/16

**Comment by mattip** [comment] 2019-12-08 08:32
Closing, it seems to be an issue with old versions of NumPy (the original report was 1.14.2) that cannot be reproduced. Please reopen if this appears on a new version.

**Closed by mattip** 2019-12-08 08:32 UTC
Labels: 06 - Regression, 29 - Intel/Anaconda, component: numpy.core
