### ISSUE TITLE
numpy.fft doesn't works.

### ISSUE THREAD

**Issue by elwlwlwk** [numpy/numpy#8639] opened 2017-02-19 12:21 UTC
I'm using numpy 1.12.0 version.
```
>>> a= np.load('a.npy')
>>> len(a)
1030703
>>> np.fft.fft(a[0:len(a)-3])
array([-18765.00000000    +0.j        ,  11107.65388924+14875.98484147j,
        -1335.17295525 +4724.62925166j, ...,
         -386.13524067  +590.33225249j,  -1335.17295525 -4724.62925166j,
        11107.65388924-14875.98484147j])
>>> np.fft.fft(a)
```

I've interrupted cause np.fft.fft(a) doesn't return while 1hours.

Data I used
http://home.wisewolf.org/static/a.npy

**Comment by seberg** [comment] 2017-02-19 12:34
1030703 is a prime number, which is probably the reason. Some other fft implementations are probably faster with that, but there is also the typical method of padding the array with zeros to avoid these inefficient FFT cases.

**Comment by jason-s** [comment] 2018-11-13 23:08
I ran into this today; an array of length 1000000 has almost instant fft calculation, 986656 (=32*11*2803) takes a few seconds, and 986626 (=2*493313) takes longer than I have patience for.

What does padding do to the FFT results?

**Comment by jason-s** [comment] 2018-11-13 23:15
hmm... looks like a duplicate of #1104

**Comment by charris** [comment] 2018-11-13 23:17
Should be fixed when 1.17 is release next year.

**Comment by charris** [comment] 2018-11-13 23:30
Python 3. It can probably be compiled for Python 2.7 as long as you avoid Windows, it needs Python compiled with a C99 compliant compiler.

**Comment by charris** [comment] 2018-11-13 23:32
Anaconda may be using the MKL fft for their distro, I don't know if it works with large prime sizes.

**Comment by seberg** [comment] 2018-11-14 07:47
You can also install `pyfftw`. Though I think the pip install expects an existing FFTW install on the system (don't quite remember). But, maybe it is fast to install and it should solve these extreme cases.

**Comment by seberg** [comment] 2018-11-14 07:52
A, but yes, padding should be a pretty good solution. I am not quite sure how much padding changes things, but it is a pretty standard method.

**Comment by seberg** [comment] 2021-11-05 22:08
Solved for a long time with the new pocketfft supporting bluestein's algorithm

**Closed by seberg** 2021-11-05 22:08 UTC
