### ISSUE TITLE
BUG: np.abs(np.int64(-9223372036854775808))  is negative

### ISSUE THREAD

**Issue by rkishony** [numpy/numpy#22091] opened 2022-08-07 20:01 UTC
### Describe the issue:

np.abs(np.int64(-9223372036854775808))  ->  -9223372036854775808

### Reproduce the code example:

```python
np.abs(np.int64(-9223372036854775808))  # -> -9223372036854775808
```

### NumPy/Python version information:

1.23.0 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:03:09) [Clang 13.0.1 ]

**Comment by eendebakpt** [comment] 2022-08-07 20:32
@rkishony The value 9223372036854775808 is too large to fit into an `int64`:
```
In [211]: np.int64(9223372036854775808)
Traceback (most recent call last):

  File "C:\Users\eendebakpt\AppData\Local\Temp\ipykernel_19728\1206286635.py", line 1, in <cell line: 1>
    np.int64(9223372036854775808)

OverflowError: int too big to convert
```
Using `np.fabs` does work:
```
In [212]: np.fabs(np.int64(-9223372036854775808))
Out[212]: 9.223372036854776e+18
``` 
There is a more detailed discussion about this topic in #5657

**Comment by rkishony** [comment] 2022-08-07 21:01
thx!
Indeed np.int64(9223372036854775808) is too large.

I would then think np.abs(np.int64(9223372036854775808)) should raise an exception is the expected behavior.  
It is really unexpected for ABS to return a negative value.

**Comment by rkern** [comment] 2022-08-07 21:38
Closing as duplicate of #5657

**Closed by rkern** 2022-08-07 21:38 UTC
Labels: 00 - Bug
