### ISSUE TITLE
libraries mkl_rt not found

### ISSUE THREAD

**Issue by duyuyouci** [numpy/numpy#22048] opened 2022-07-27 07:46 UTC
### Steps to reproduce:

build docker image with docker file

FROM ubuntu:16.04
 
ENV PYENV_ROOT=/pyenv
ENV PYENV_VERSION=3.6.12

ENV BOSS2_ENV_PATH=/pitrix/lib/boss2/pitrix-boss2-env-16.04
ENV BUILD_DIR=/builder
ENV OUTPUT_DIR=/output

RUN apt-get update --fix-missing \
    && apt-get install -y \
        build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl \
        llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev git \
        python-openssl python-yaml swig

ENV PATH="${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}"
RUN curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

RUN env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install ${PYENV_VERSION} \
    && ln -s ${PYENV_ROOT}/versions/${PYENV_VERSION}/include/python3.6m /usr/include/python3.6

RUN apt-get update --fix-missing \
    && apt-get install -y \
        libopenblas-dev libblas-dev liblapack-dev \
        libatlas-base-dev cython software-properties-common

RUN apt-get update --fix-missing \
    && apt-get install -y gfortran

RUN apt-get update --fix-missing \
    && apt-get install -y python3-dev

WORKDIR ${BUILD_DIR}
COPY pack.sh ${BUILD_DIR}/pack.sh

CMD ["./pack.sh"]

### Error message:

```shell
install numpy with requirement.txt

numpy == 1.19.5

15:31:01   Running setup.py install for numpy: started
15:32:02     Running setup.py install for numpy: still running...
15:33:03     Running setup.py install for numpy: still running...
15:34:31     Running setup.py install for numpy: still running...
15:34:31     Running setup.py install for numpy: finished with status 'error'
15:34:31     Complete output from command /pitrix/lib/boss2/pitrix-boss2-env-16.04/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-o_0oe8c7/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1kjsilfa/install-record.txt --single-version-externally-managed --compile --install-headers /pitrix/lib/boss2/pitrix-boss2-env-16.04/include/site/python3.6/numpy:
15:34:31     Running from numpy source directory.
15:34:31     
15:34:31     Note: if you need reliable uninstall behavior, then install
15:34:31     with pip instead of using `setup.py install`:
15:34:31     
15:34:31       - `pip install .`       (from a git repo or downloaded source
15:34:31                                release)
15:34:31       - `pip install numpy`   (last NumPy release on PyPi)
15:34:31     
15:34:31     
15:34:31     Cythonizing sources
15:34:31     Processing numpy/random/_bounded_integers.pxd.in
15:34:31     Processing numpy/random/_sfc64.pyx
15:34:31     Processing numpy/random/bit_generator.pyx
15:34:31     Processing numpy/random/_generator.pyx
15:34:31     Processing numpy/random/_mt19937.pyx
15:34:31     Processing numpy/random/_common.pyx
15:34:31     Processing numpy/random/_pcg64.pyx
15:34:31     Processing numpy/random/_bounded_integers.pyx.in
15:34:31     Processing numpy/random/_philox.pyx
15:34:31     Processing numpy/random/mtrand.pyx
15:34:31     blas_opt_info:
15:34:31     blas_mkl_info:
15:34:31     customize UnixCCompiler
15:34:31       libraries mkl_rt not found in ['/pitrix/lib/boss2/pitrix-boss2-env-16.04/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
15:34:31       NOT AVAILABLE
15:34:31     
15:34:31     blis_info:
15:34:31       libraries blis not found in ['/pitrix/lib/boss2/pitrix-boss2-env-16.04/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
15:34:31       NOT AVAILABLE
15:34:31     
15:34:31     openblas_info:
15:34:31     C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
15:34:31     
15:34:31     creating /tmp/tmpmh1sclx_/tmp
15:34:31     creating /tmp/tmpmh1sclx_/tmp/tmpmh1sclx_
15:34:31     compile options: '-c'
15:34:31     gcc: /tmp/tmpmh1sclx_/source.c
15:34:31     gcc -pthread /tmp/tmpmh1sclx_/tmp/tmpmh1sclx_/source.o -L/usr/lib -lopenblas -o /tmp/tmpmh1sclx_/a.out
15:34:31       FOUND:
15:34:31         libraries = ['openblas', 'openblas']
15:34:31         library_dirs = ['/usr/lib']
15:34:31         language = c
15:34:31         define_macros = [('HAVE_CBLAS', None)]
15:34:31     
15:34:31       FOUND:
15:34:31         libraries = ['openblas', 'openblas']
15:34:31         library_dirs = ['/usr/lib']
15:34:31         language = c
15:34:31         define_macros = [('HAVE_CBLAS', None)]
15:34:31     
15:34:31     non-existing path in 'numpy/distutils': 'site.cfg'
15:34:31     lapack_opt_info:
15:34:31     lapack_mkl_info:
15:34:31       libraries mkl_rt not found in ['/pitrix/lib/boss2/pitrix-boss2-env-16.04/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
15:34:31       NOT AVAILABLE
15:34:31     
15:34:31     openblas_lapack_info:
15:34:31     C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
15:34:31     
15:34:31     creating /tmp/tmpw1mx5ocu/tmp
15:34:31     creating /tmp/tmpw1mx5ocu/tmp/tmpw1mx5ocu
15:34:31     compile options: '-c'
15:34:31     gcc: /tmp/tmpw1mx5ocu/source.c
15:34:31     gcc -pthread /tmp/tmpw1mx5ocu/tmp/tmpw1mx5ocu/source.o -L/usr/lib -lopenblas -o /tmp/tmpw1mx5ocu/a.out
15:34:31       FOUND:
15:34:31         libraries = ['openblas', 'openblas']
15:34:31         library_dirs = ['/usr/lib']
15:34:31         language = c
15:34:31         define_macros = [('HAVE_CBLAS', None)]
15:34:31     
15:34:31       FOUND:
15:34:31         libraries = ['openblas', 'openblas']
15:34:31         library_dirs = ['/usr/lib']
15:34:31         language = c
15:34:31         define_macros = [('HAVE_CBLAS', None)]
15:34:31     
15:34:31     /pyenv/versions/3.6.12/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
15:34:31       warnings.warn(msg)
15:34:31     running install
15:34:31     running build
15:34:31     running config_cc
15:34:31     unifing config_cc, config, build_clib, build_ext, build commands --compiler options
15:34:31     running config_fc
15:34:31     unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
15:34:31     running build_src
15:34:31     build_src
15:34:31     building py_modules sources
15:34:31     creating build
15:34:31     creating build/src.linux-aarch64-3.6
15:34:31     creating build/src.linux-aarch64-3.6/numpy
15:34:31     creating build/src.linux-aarch64-3.6/numpy/distutils
15:34:31     building library "npymath" sources
15:34:31     creating build/src.linux-aarch64-3.6/numpy/core
15:34:31     creating build/src.linux-aarch64-3.6/numpy/core/src
15:34:31     creating build/src.linux-aarch64-3.6/numpy/core/src/npymath
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npymath/npy_math_internal.h
15:34:31       adding 'build/src.linux-aarch64-3.6/numpy/core/src/npymath' to include_dirs.
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npymath/ieee754.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npymath/npy_math_complex.c
15:34:31     None - nothing done with h_files = ['build/src.linux-aarch64-3.6/numpy/core/src/npymath/npy_math_internal.h']
15:34:31     building library "npysort" sources
15:34:31     creating build/src.linux-aarch64-3.6/numpy/core/src/common
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/npy_sort.h
15:34:31       adding 'build/src.linux-aarch64-3.6/numpy/core/src/common' to include_dirs.
15:34:31     creating build/src.linux-aarch64-3.6/numpy/core/src/npysort
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/quicksort.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/mergesort.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/timsort.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/heapsort.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/radixsort.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/npy_partition.h
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/selection.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/npy_binsearch.h
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/binsearch.c
15:34:31     None - nothing done with h_files = ['build/src.linux-aarch64-3.6/numpy/core/src/common/npy_sort.h', 'build/src.linux-aarch64-3.6/numpy/core/src/common/npy_partition.h', 'build/src.linux-aarch64-3.6/numpy/core/src/common/npy_binsearch.h']
15:34:31     building library "npyrandom" sources
15:34:31     building extension "numpy.core._multiarray_tests" sources
15:34:31     creating build/src.linux-aarch64-3.6/numpy/core/src/multiarray
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/multiarray/_multiarray_tests.c
15:34:31     building extension "numpy.core._multiarray_umath" sources
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/multiarray/arraytypes.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/multiarray/einsum.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/multiarray/lowlevel_strided_loops.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/multiarray/nditer_templ.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/multiarray/scalartypes.c
15:34:31     creating build/src.linux-aarch64-3.6/numpy/core/src/umath
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/funcs.inc
15:34:31       adding 'build/src.linux-aarch64-3.6/numpy/core/src/umath' to include_dirs.
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/simd.inc
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/loops.h
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/loops.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/matmul.h
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/matmul.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/clip.h
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/clip.c
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/umath/scalarmath.c
15:34:31       adding 'build/src.linux-aarch64-3.6/numpy/core/src/npymath' to include_dirs.
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/templ_common.h
15:34:31       adding 'build/src.linux-aarch64-3.6/numpy/core/src/common' to include_dirs.
15:34:31     conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/npy_cpu_features.c
15:34:31     numpy.core - nothing done with h_files = ['build/src.linux-aarch64-3.6/numpy/core/src/umath/funcs.inc', 'build/src.linux-aarch64-3.6/numpy/core/src/umath/simd.inc', 'build/src.linux-aarch64-3.6/numpy/core/src/umath/loops.h', 'build/src.linux-aarch64-3.6/numpy/core/src/umath/matmul.h', 'build/src.linux-aarch64-3.6/numpy/core/src/umath/clip.h', 'build/src.linux-aarch64-3.6/numpy/core/src/npymath/npy_math_internal.h', 'build/src.linux-aarch64-3.6/numpy/core/src/common/templ_common.h', 'build/src.linux-aarch64-3.6/numpy/core/include/numpy/config.h', 'build/src.linux-aarch64-3.6/numpy/core/include/numpy/_numpyconfig.h', 'build/src.linux-aarch64-3.6/numpy/core/include/numpy/__multiarray_api.h', 'build/src.linux-aarch64-3.6/numpy/core/include/numpy/__ufunc_api.h']
```

**Comment by seberg** [comment] 2022-08-08 06:12
Nobody is going to run the full thing to reproduce it.  Can you please paste everything, since there is no error in the log.  What you point out as an error is completely normal.

**Comment by seberg** [comment] 2022-08-12 06:52
Closing for now, since there is no actual error highlighted, we can reopen if there is one.

**Closed by seberg** 2022-08-12 06:52 UTC
Labels: 57 - Close?, 32 - Installation
