### ISSUE TITLE
empty, zeros, ones, full allocate product of non-zero size elements, even if final array is zero-sized

### ISSUE THREAD

**Issue by huonw** [numpy/numpy#16410] opened 2020-05-28 06:45 UTC
Functions like `np.zeros`, `np.empty`, `np.ones` and `np.full` can be used to allocate large arrays easily. However, they always allocate memory, even if the array contains no data because one of the shape elements is 0. They, in particular, seem to allocate memory ignoring the 0s in the shape (`np.product([x for x in shape if x != 0])`).

If any of the shape elements in zero, there's no possibility of any memory accesses ever, so the allocation seems unnecessary?

If the shape has a zero, one can get an equivalent array using `broadcast_to`, which won't allocate.

### Reproducing code example:

```python
import numpy as np
import tracemalloc as tm

def test(f):
    tm.start()
    arr = f((0, 100, 0, 200, 0, 300, 0), dtype=np.uint8)
    mem, _ = tm.get_traced_memory()
    tm.stop()
    print(f"{f.__name__}: allocated memory: {mem} bytes, array size: {arr.size}")

def full(shape, dtype):
    return np.full(shape, 123, dtype=dtype)

test(np.zeros)
test(np.empty)
test(np.ones)
test(full)

# workaround, use broadcasting
def broadcast(shape, dtype):
    return np.broadcast_to(dtype(), shape)
test(broadcast)
```

```
zeros: allocated memory: 6000248 bytes, array size: 0
empty: allocated memory: 6000080 bytes, array size: 0
ones: allocated memory: 6000080 bytes, array size: 0
full: allocated memory: 6000080 bytes, array size: 0
broadcast: allocated memory: 3680 bytes, array size: 0
```

### Numpy/Python version information:

- `numpy.__version__`: 1.18.4 
- `sys.version`: 3.6.9 (default, Jul 10 2019, 12:25:55) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]

**Comment by eric-wieser** [comment] 2020-05-28 06:59
I think @mattip and I both have (had?) open PRs about this.

**Comment by mattip** [comment] 2020-05-28 07:05
Right, gh-15780 was rejected since it hit undefined behaviour in the C spec, and gh-15788 is still marked "Draft"

**Comment by huonw** [comment] 2020-05-28 08:24
Nice!

I noticed that this applies to (fancy) indexing along a non-zero sized axis too, e.g.:

```python
import numpy as np
import tracemalloc as tm

base = np.broadcast_to(np.uint8(0), (0, 100, 0, 200, 0, 300, 0))
idx = np.arange(100)

tm.start()
arr = base[:, idx, ...]
mem, _ = tm.get_traced_memory()
tm.stop()

print(f"allocated memory: {mem} bytes, array size: {arr.size}")
```
```
allocated memory: 6000480 bytes, array size: 0
```

Can this be considered as part of this issue/those PRs, or should I open a separate one?

**Comment by seberg** [comment] 2020-05-28 15:33
Yes, there is no difference with fancy indexing, since in the end it also allocates a normal array. 
So it is a duplicate of gh-15753 and those PRs address it.
I fine with either proposal (just because at some point this was likely intentionally, does not mean it was good), but to be honest I very enthusiastic about trying to figure out whether or not its a good idea. (I suppose right now I fail to see a bit that this memory loss is actually a big deal. The memory is never touched and in most use cases I would expect there to be much larger arrays flying around somewhere, it seems more like something you run into when running crazy test suits)

**Closed** 2022-05-17 10:04 UTC
Labels: 57 - Close?
