### ISSUE TITLE
Can't install numpy from piwheels.org on raspbian

### ISSUE THREAD

**Issue by FluxedScript** [numpy/numpy#14533] opened 2019-09-17 19:46 UTC
I have install numpy and then had to uninstall and install again and still doesn't work.
I installed python3.7 by using some console commands ages ago
I use Raspbian(Raspberry pi)
I have multiple versions of python
`pi@raspberrypi:~ $ sudo python3.7 -m pip uninstall numpy
Uninstalling numpy-1.17.2:
  Would remove:
    /usr/local/bin/f2py
    /usr/local/bin/f2py3
    /usr/local/bin/f2py3.7
    /usr/local/lib/python3.7/site-packages/numpy-1.17.2.dist-info/*
    /usr/local/lib/python3.7/site-packages/numpy/*
Proceed (y/n)? y
  Successfully uninstalled numpy-1.17.2
pi@raspberrypi:~ $ sudo python3.7 -m pip install numpy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.17.2-cp37-cp37m-linux_armv7l.whl
Installing collected packages: numpy
Successfully installed numpy-1.17.2
pi@raspberrypi:~ $ 
`

Python error
`Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory`

**Comment by mattip** [comment] 2019-09-17 19:50
In #14455 another user reported

> problem was I install with pip and it didn't install libatlas3-base

**Comment by seberg** [comment] 2019-09-21 22:05
Please have a look at the issue Matti linked, closing as duplicate of gh-14553 (although we can probably close that as well really)

**Closed by seberg** 2019-09-21 22:05 UTC
