### ISSUE TITLE
Problems with numpy.array() from ctypes object with _pack_?

### ISSUE THREAD

**Issue by mpvismer** [numpy/numpy#7752] opened 2016-06-16 18:25 UTC
Trying to create a numpy array from ctypes and ran into a problem which seems to be because of the _pack_ attribute in ctypes. Anyone seen this before?

```python
import sys  
import ctypes
import numpy as np

print(sys.version)
print(ctypes.__version__)
print(np.__version__)

class POINT(ctypes.Structure):
    _fields_ = [("x", ctypes.c_int),
                ("y", ctypes.c_float)]  

class POINT_BUG(ctypes.Structure):
    _pack_ = 4
    _fields_ = [("x", ctypes.c_int),
                ("y", ctypes.c_float)]      

n = np.array((POINT*5)())
print(n)

#This fails
nb = np.array((POINT_BUG*5)())
```

Produces ouput:

> ```
> 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
> 1.1.0
> 1.10.4
> [(0, 0.0) (0, 0.0) (0, 0.0) (0, 0.0) (0, 0.0)]
> C:/Users/Mark/Desktop/bugreport.py:23: RuntimeWarning: Item size computed from the PEP 3118 buffer format string does not match the actual item size.
>   ("y", ctypes.c_float)]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
>     execfile(filename, namespace)
>   File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
>   File "C:/Users/Mark/Desktop/bugreport.py", line 23, in <module>
>     nb = np.array((POINT_BUG*5)())
> TypeError: long() argument must be a string or a number, not 'POINT_BUG'
> ```

**Comment by birm** [comment] 2016-06-22 07:19
I'm not sure where the long() error is coming from.
do you have an __array_interface__()?

**Comment by mpvismer** [comment] 2016-06-22 10:04
Brim, thanks for looking at this! Unfortunately, I don't know much more about it other than that it works for the "POINT" class with no _pack_ attribute and fails for the POINT_BUG class with the _pack_ attribute. Hopefully I will be able to look into the numpy internals a bit more at some point.

**Comment by birm** [comment] 2016-06-23 07:18
I was able to get your code working by making POINT_BUG a subclass of POINT, and skipping redefining `_fields_` in POINT_BUG. _However_, I'm not sure if this is  breaking `_pack_`.

**Comment by ahaldane** [comment] 2016-07-06 18:41
I don't use ctypes so this may be a red herring, but the problem appears to be on the ctypes side to me:
```
>>> memoryview((POINT*5)()).format
'T{<i:x:<f:y:}'
>>> memoryview((POINT_BUG*5)()).format
'B'
```
In the first case ctypes gives the right pep3118 structure format, but not the second. Probably the second should be `'=T{<i:x:<f:y:}'` or similar.

**Comment by mpvismer** [comment] 2016-07-06 23:38
I think you right, looks related to this,
http://stackoverflow.com/questions/4964101/pep-3118-warning-when-using-ctypes-array-as-numpy-array

**Comment by eric-wieser** [comment] 2018-02-06 08:56
Duplicate of #10528, where the underlying python bug is linked. Closing this one because I like to think the diagnosis is more thorough there. Thanks for the report!

**Closed** 2018-02-06 08:59 UTC
Labels: 00 - Bug
