### ISSUE TITLE
numpy.arange stop precision issue

### ISSUE THREAD

**Issue by mjasher** [numpy/numpy#5808] opened 2015-04-28 08:35 UTC
All elements of the array generated by `numpy.arange(start, stop, step)` should be strictly smaller than `stop`.

On my Ubuntu 14.04 installation this happened: 
```
In [117]: np.arange(0.5, 0.8, 0.1)
Out[117]: array([ 0.5,  0.6,  0.7,  0.8])

In [118]: np.arange(0.5, 0.9, 0.1)
Out[118]: array([ 0.5,  0.6,  0.7,  0.8])

In [123]: np.arange(0.5, 0.8, 0.1)[-1]
Out[123]: 0.79999999999999993

In [124]: np.arange(0.5, 0.9, 0.1)[-1]
Out[124]: 0.79999999999999993
```
Is this an issue on other installations?

**Comment by rkern** [comment] 2015-04-28 08:49
I'm not entirely sure what you think is wrong with this example. For both examples, all elements are indeed strictly less than `stop`. How they get rounded during printing is another matter.

```
[~]
|4> np.arange(0.5, 0.8, 0.1)
array([ 0.5,  0.6,  0.7,  0.8])

[~]
|5> np.arange(0.5, 0.8, 0.1) < 0.8
array([ True,  True,  True,  True], dtype=bool)
```

In any case, the [docstring for `arange()`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) warns you about the potential traps of using floating point arguments and suggests more predictable alternatives.

**Comment by argriffing** [comment] 2015-04-28 15:08
@mjasher I'm going to assume that you aren't confused by
```python
>>> 0.5 + 0.1 + 0.1 + 0.1 < 0.8
True
```
or
```python
>>> np.array([0.5 + 0.1 + 0.1 + 0.1])
array([ 0.8])
>>> np.array([0.5 + 0.1 + 0.1 + 0.1])[0]
0.79999999999999993
```
or
```python
>>> a = np.array([0.5 + 0.1 + 0.1 + 0.1])
>>> b = np.array([0.8])
>>> print a, '<', b, ':', a < b
[ 0.8] < [ 0.8] : [ True]
```
and that when you said 'strictly smaller' you had in mind something like this:
```python
>>> def strictly_smaller(a, b): return a < b and not np.isclose(a, b)
... 
>>> strictly_smaller(0.5 + 0.1 + 0.1 + 0.1, 0.8)
False
```
I guess that's not how `arange` is implemented. Maybe it could be changed if backwards compatibility is addressed and if there is a decision on how to quantify closeness?

**Comment by jaimefrio** [comment] 2015-05-05 05:00
Thanks for taking the time to report this @mjasher, but as explained by others this is more of a feature than a bug. I am going to close this for now, but feel free to yell at me if you think it deserves closer attention, and I'll reopen it.

**Closed by jaimefrio** 2015-05-05 05:00 UTC

**Comment by mayou36** [comment] 2017-03-25 17:14
@jaimefrio: I would definitely vote to reopen this issue. It is impossible that the function depends on the implementation and some rounding luck! Or let's put it this way:
Numpy is supposed to be a "mathematical-operations"-library. If a function then tells to return a list from 0.5 to 0.8 excluding 0.8 and with stepsize 0.1, it **has** to return a list with **exactly** three components, [0.5, 0.6, 0.7]. I agree, that rounding errors can make life more difficult when doing calculations, but ignoring them actively and basically saying "deal with the problem yourself" is definitely not the solution. Instead, arange *has* to recognize rounding errors, otherwise, the function is *not usable* (search the web, a lot of people complain and work around this error).

A possible implementation could have an additional argument, something like "stopping_precision",  that defines the "stopping-range".

I love numpy and I would really like to see arange to be usable again. Or, honestly, how many functions do you regularly use whose return depends on... luck? And on the other hand, if you call it a "feature": please name *one* single use-case for this "feature" ;)

**Comment by eric-wieser** [comment] 2017-03-25 17:49
@mayou36: The crux of the problem is the different between _"give me steps of 1/10 in the interval [5/10, 8/10)"_, and _"give me steps of `float(0.1)` in `[float(0.5), float(0.8))``. Because you used floating point numbers to ask, `numpy` gives you the latter.

The solution to your problem is an exact representation of `1/10` in numpy, not for numpy to try and infer special meaning to some values of float

**Comment by eric-wieser** [comment] 2017-03-25 17:56
This actually is hidden away inside numpy:

```
>>> from np.core.test_rational import rational
>>> arr = np.arange(rational(5, 10), rational(8, 10), rational(1, 10))
>>> arr
array([rational(1,2), rational(3,5), rational(7,10)], dtype=rational)
>>> arr.astype(float)
array([ 0.5,  0.6,  0.7])
```

**Comment by seberg** [comment] 2017-03-25 18:00
While my guess is that the logic in arange could be better (certainly not perfect, but probably better then it is now). I also believe that changing the behaviour will break a lot of code out there horrifically. There is a reason we the doucmentation asks to use linspace instead....

**Comment by seberg** [comment] 2017-03-25 18:02
While my guess is that the logic in arange could be better (certainly not perfect, but probably better then it is now). I also believe that changing the behaviour will break a lot of code out there horrifically. There is a reason we the doucmentation asks to use linspace instead....

**Comment by mayou36** [comment] 2017-03-25 18:18
@eric-wieser Sure, but then numpy.frange is "broken" in its functionality. If it returns a list [0.5, 0.6, 0.7, 0.7999999], then it does not exactly what it is supposed to do in terms of "numerical stability". Of course, the intrinsic problem of floating-point operations is the problem, but just leaving it to be "random" seems a bit like the division from python2, where you could have unintentionally integer divisions: sure, it said it is like this, but... yeah, you may trapped into it yourself as well at least once (so did I). And as for the division, I would ask: who really needs that?

@seberg I agree, backwards compatibility can be a problem; although I really hope that not a lot of code "relies" on this "feature". Anyway, wouldn't that call for a new function for numpy? Linspace is nice, but if I want to define the step-size, it can be "cumbersome". All that would have to be done is to wrap arange, add the "epsilon-criterium" and fine.

What do you think?

**Comment by charris** [comment] 2017-03-25 18:37
It isn't "broken", it just doesn't behave as you wish. I suggest that the solution here is to adjust your wishes and come to terms with floating point. It will serve you better in the long term.

**Comment by seberg** [comment] 2017-03-25 18:52
I once thought about adding a "step" argument to linspace that would only work when things are numerically clear. In the end we never thought it through all the way and decided to not actually do it. But I still think that is more likely to go anywhere then being annoyed at arange.

Hoping that you won't break much by making arange "more sensible" (and with these things, people do tend to disagree on what "sensible" means) seems a far fetch to me. I think there is a lot of "trial and error" code out there. Frankly, I just don't think its worth the trouble, there are good alternatives IMO, possibly we could put the "maybe you want to use linspace" even more prominently, but that seems about it probably. Anyway, I think that discussions like changing arange are so far fetched, that we should move it to the mailing list if we would want to continue.

**Comment by mayou36** [comment] 2017-03-25 19:00
@charris Sure, but in the end it is not about broken, precision or not, but about deterministic behaviour of a "mathematically" simple function. It is not clear, whether the function returns 3 or 4 entries. Sometimes it includes the last digit and sometimes it does not. It is **completely random**. For example, np.arange(0.5, 0.9, 0.1) yields [0.5, 0.6, 0.7, 0.8] as well (whereas np.arange(0.6, 0.9, 0.1) yields [0.6 0.7, 0.8, 0.9], changing the starting point changes the ending point...). I think this should not happen in a numerical library.

@seberg I completely agree (yes, backwards braking is bad)! And implementing something into linspace would be my prefered approach aswell (also from a users point of view).

**Comment by eric-wieser** [comment] 2017-03-25 19:03
@mayou36: Your complaint should be directed at the floating point spec. When you write `0.1` in software, that doesn't represent the rational number `0.1`. It represents the nearest float to that number.

Now, you could argue that this conversion to "nearest float" is completely random - sometimes the nearest one is bigger, sometime it is smaller.

But ultimately, the job of numpy is to operate on the _numbers you give it_, not the numbers-that-you-want-to-give-it-but-your-representation-does-not-allow

**Comment by mayou36** [comment] 2017-03-25 20:06
@eric-wieser I agree, as long as the "rational()"-thing works, there is truly no reason for complaints. It would, however, be nice, in general, to have an option which handles it (like "stopping_precision", that defines the range around the stopping value things should be stopped or the possibility to use a tuple with (stop, stopping_precision) or similar), as I think/read, it is a frequently occurring case. But, I agree, this would be more like an extra-feature/function and not an issue in an existing function.
Thanks for your replies and your great work with numpy!

**Comment by eric-wieser** [comment] 2017-03-25 20:10
>  I agree, as long as the "rational()"-thing works, there is truly no reason for complaints

Well, you could complain that `rational` is not officially supported, and that would be a very valid complaint :)

**Comment by frohro** [comment] 2019-11-15 21:47
The way I get around this "bug" is to use integers to base things on.
`import numpy as np
N = 128
T = 0.01
k = np.arange(0, N)
t = k*T
`
instead of 
`import numpy as np
N = 128
T = 0.01
t = np.arange(0, NT, T)
`
Maybe this will help someone.  It really is annoying when plotting and you get one less point than you thought because of machine precision and the way numpy.arange was defined.

**Comment by mayou36** [comment] 2019-11-16 09:02
Why don't you use directly the Python builtin `range` then? This does the same.

I would say the workaround is to use frange, which has a well defined step number

**Comment by malin119** [comment] 2019-12-02 11:39
@rkern @argriffing 
`start = 1
stop = 2 + 1/9
step = 1/9
print(np.arange(start, stop, step)[-1] < stop)
-> False
print(list(np.arange(start, stop, step))) 
-> [1.0, 1.1111111111111112, 1.2222222222222223, 1.3333333333333335, 1.4444444444444446, 1.5555555555555558, 1.666666666666667, 1.7777777777777781, 1.8888888888888893, 2.0000000000000004, 2.1111111111111116]
print(stop)
- > 2.111111111111111`

The last element does not have to be smaller than stop. 

@frohro
If you want N elements in a interval, you should use linspace.

**Comment by vaibhavtewari** [comment] 2020-04-10 15:47
Here is one problem I encountered.
z_max = 1.2
ax = np.expm1(np.linspace(np.log(1.), np.log(1. + z_max), 3000))
print ax[ax > z_max]
>[1.2]

**Comment by rkern** [comment] 2020-04-10 16:00
```
>>> np.expm1(np.log(1 + 1.2)) > 1.2
True
```

Not a problem with `np.linspace()`, just that compositions of floating point operations don't always match what they should be with infinite precision real numbers.

**Comment by vaibhavtewari** [comment] 2020-04-10 16:05
I was hoping the end point will be equal or smaller than z_max but it turned out larger than z_max. This was followed by trapz which was returning unphysical values of a physical quantity.

**Comment by rkern** [comment] 2020-04-10 16:07
I would use `ax = ax.clip(0, z_max)` in such cases.

**Comment by sgascoin** [comment] 2020-04-26 20:50
I just discovered this random behavior of arange
`>>> np.arange(0,5,1)`
`array([0., 1., 2., 3., 4.])`
`>>> np.arange(0,5+sys.float_info.epsilon,1)`
`array([0., 1., 2., 3., 4.])`
`>>> np.arange(0,5+sys.float_info.epsilon*2,1)`
`array([0., 1., 2., 3., 4.])`
`>>> np.arange(0,5+sys.float_info.epsilon*3,1)`
`array([0., 1., 2., 3., 4., 5.])` Bingo ! 👍

**Comment by mattip** [comment] 2020-04-26 20:59
The [documentation](https://numpy.org/devdocs/reference/generated/numpy.arange.html) could state it in terms of floating point values rather than in terms of a non-integer step, but the recommendation remains: when using float values, use [`np.linspace`](https://numpy.org/devdocs/reference/generated/numpy.linspace.html#numpy.linspace) instead.

**Comment by aparangement** [comment] 2020-12-04 08:47
> While my guess is that the logic in arange could be better (certainly not perfect, but probably better then it is now). I also believe that changing the behaviour will break a lot of code out there horrifically. There is a reason we the doucmentation asks to use linspace instead....

actually linspace is doing the same.
try
`[i for i in np.linspace(0, 2, 21)]`

**Comment by mayou36** [comment] 2020-12-04 17:39
The same as what? It does, for me, what is documented, e.g. it splits the interval from `start` to `end` in 21 parts, start and end both inclusive. I get an array as expected (btw, just to `np.linspace`, why the list?)

**Comment by mayou36** [comment] 2020-12-04 17:48
So in order to move forward, I propose to:
- if this is an ill-defined problem with integers, why don't we simply raise a `ValueError` and say that it must not be used? This doesn't break existing code with existing functions but may break backwards compatibility; fine! Better break it at some point instead of having this buggy function around.
- at least use a warning, deprecation or whatever for floats.

It's around for too long and potentially still used. Let's break code if necessary but make it a more bug-free world. For the sake of it ;)

**Comment by aparangement** [comment] 2020-12-23 04:33
> The same as what? It does, for me, what is documented, e.g. it splits the interval from `start` to `end` in 21 parts, start and end both inclusive. I get an array as expected (btw, just to `np.linspace`, why the list?)

I was replying to seberg's suggestion to use linspace instead.

Since linspace also returns float like "0.30000000000000004"

It's easier to show the problem by using a list.

Or you could just try:
`numpy.linspace(0, 2, 21)[3]`

The result is the same with Python 2 and 3, under either windows(10) or ubuntu(18.04)

**Comment by mayou36** [comment] 2020-12-23 10:39
> Since linspace also returns float like "0.30000000000000004"
> 

Yes, but this is an inherent problem of computers; they will always only have a finite precision to display digits. Floating point numbers are "never" exact.

The problem here is a different one, the number of elements. E.g. if we use `numpy.arange` and x as stop, is stop included? Because sometimes "it is" (because of the finite precision) and sometimes it is not. For linspace, we don't have this problem, stop is always included.

**Comment by matthew-brett** [comment] 2020-12-23 12:19
> Floating point numbers are "never" exact.

I think you mean [hardly ever](https://www.elyrics.net/read/g/gilbert-&-sullivan-lyrics/i-am-the-captain-of-the-pinafore-lyrics.html) exact.

**Comment by aparangement** [comment] 2020-12-26 09:31
> > Since linspace also returns float like "0.30000000000000004"
> 
> Yes, but this is an inherent problem of computers; they will always only have a finite precision to display digits. Floating point numbers are "never" exact.
> 
> The problem here is a different one, the number of elements. E.g. if we use `numpy.arange` and x as stop, is stop included? Because sometimes "it is" (because of the finite precision) and sometimes it is not. For linspace, we don't have this problem, stop is always included.

I guess you are right from programing point of view.
However the 4th element of linear arithmetic sequence between 0 and 2 with 21 nodes is exactly 0.3, rather than "0.30000000000000004".
I am wondering if there is a solution in python, that's how I found this issue to be honest. And I believe this is a very practical and important concern to a lot of other users.

**Comment by eric-wieser** [comment] 2020-12-26 09:42
Python `float` cannot represent "exactly 0.3".

**Comment by mayou36** [comment] 2020-12-29 14:57
> I guess you are right from programing point of view.
> However the 4th element of linear arithmetic sequence between 0 and 2 with 21 nodes is exactly 0.3, rather than "0.30000000000000004".
> I am wondering if there is a solution in python, that's how I found this issue to be honest. And I believe this is a very practical and important concern to a lot of other users.

What you are talking about here is a completely different problem. Like that a car can't move sideways.
I suggest you highly to read up about binary systems and representations of floating point numbers including about how computers work; I think this will clear up your issue.

If you look, in general, for a way to do precise arithmetic: this is possible with fractions and the module `decimal` may be for you.

**Comment by aparangement** [comment] 2020-12-30 02:13
> > I guess you are right from programing point of view.
> > However the 4th element of linear arithmetic sequence between 0 and 2 with 21 nodes is exactly 0.3, rather than "0.30000000000000004".
> > I am wondering if there is a solution in python, that's how I found this issue to be honest. And I believe this is a very practical and important concern to a lot of other users.
> 
> What you are talking about here is a completely different problem. Like that a car can't move sideways.
> I suggest you highly to read up about binary systems and representations of floating point numbers including about how computers work; I think this will clear up your issue.
> 
> If you look, in general, for a way to do precise arithmetic: this is possible with fractions and the module `decimal` may be for you.

Thank you for your suggestions, I will try to play with decimal, for now I just go back to bash.
However to be honest I still think this should be improved, not by the user but by the developer.
My understanding is that this kind of problem should be carefully checked and implemented, rather to let users read up binary system and  representations of floating point. Otherwise what's point of using library..
