### ISSUE TITLE
DOC: Update dev docs to include a 'Understanding the code base and getting started section'

### ISSUE THREAD

**Issue by rehassachdeva** [numpy/numpy#6996] opened 2016-01-11 20:53 UTC
The idea is to guide the beginners after they are done setting up their fork and development environment to actually start understanding the code base and a general piece of advice for the same.

It can go something like this: 

Understanding the code and getting started

The best strategy to better understand the code base is to pick something you want to change and start reading the code to figure out how it works. When you're in doubt, you can ask questions on the mailing list or on the NumPy Github page. It is perfectly okay if your pull requests aren't perfect, the community is always happy to help. As a volunteer project, things do sometimes get dropped and it's totally fine to ping us if something has sat without a response for, say, a week or so. 

So go ahead and pick something that annoys or confuses you about numpy, experiment with the code, hang around for discussions or go through the reference documents, to try to fix it. Things will fall in place and soon you'll have a pretty good understanding of the project as a whole. Good Luck!

(as told by @njsmith )

If you'd be kind enough to approve this, I'll get started on it.

As far as I understood this would involve making the necessary content and linking changes in source folder of dev docs and building the docs to see if it figures correctly.

**Comment by rgommers** [comment] 2016-02-20 15:47
@rehassachdeva this makes sense, please go ahead. Maybe add a new section at the end of http://docs.scipy.org/doc/numpy-dev/dev/development_environment.html

**Comment by rehassachdeva** [comment] 2016-02-20 16:40
Sir, I'm facing this exception while building the docs:

Exception occurred:
  File "/home/rehas/numpy/doc/sphinxext/numpydoc/docscrape.py", line 235, in parse_item_name
raise ParseError("%s is not a item name" % text)
ParseError: `Arrayterator` is not a item name in u"A 1-D flat iterator for Arrayterator objects.\n\nThis iterator returns elements of the array to be iterated over in\n`Arrayterator` one by one. It is similar to `flatiter`.\n\nSee Also\n--------\n`Arrayterator`\nflatiter\n\nExamples\n--------\n>>> a = np.arange(3 * 4 * 5 * 6).reshape(3, 4, 5, 6)\n>>> a_itor = np.lib.arrayterator.Arrayterator(a, 2)\n\n>>> for subarr in a_itor.flat:\n...     if not subarr:\n...         print subarr, type(subarr)\n...\n0 <type 'numpy.int32'>\n\n"

Also, could you please tell me 
1) if it is possible to build just one file individually and not the entire doc folder? 
2) The contents section on the right hand side will be automatically updated once I add the content in development_environment.rst ?

Thank you.

**Comment by rgommers** [comment] 2016-02-20 16:44
Does that exception halt your doc build? That shouldn't happen. What build command did you use?

> 1) if it is possible to build just one file individually and not the entire doc folder? 

not possible unfortunately. After the first build, rebuilds are much faster though.

> 2) The contents section on the right hand side will be automatically updated once I add the content in development_environment.rst ?

Yes, that's all automatic.

**Comment by rehassachdeva** [comment] 2016-02-20 16:45
Yes, it halts the build. I ran 'make html' in doc folder.

**Comment by rgommers** [comment] 2016-02-20 16:50
That's the right command. Do you have numpy itself on your path (i.e. can you import it from ``doc/``)? If so, can you provide the full build log in a gist?

**Comment by rehassachdeva** [comment] 2016-02-20 17:00
Yes, i can import it.
This is last couple of lines of sphinx-err log:

  File "/home/rehas/.local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1359, in add_content
    ClassLevelDocumenter.add_content(self, more_content, no_docstring)
  File "/home/rehas/.local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 559, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/home/rehas/.local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 521, in process_doc
    self.options, docstringlines)
  File "/home/rehas/.local/lib/python2.7/site-packages/sphinx/application.py", line 508, in emit
    results.append(callback(self, *args))
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/numpydoc.py", line 56, in mangle_docstrings
    doc = get_doc_object(obj, what, u_NL.join(lines), config=cfg)
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape_sphinx.py", line 284, in get_doc_object
    return SphinxObjDoc(obj, doc, config=config)
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape_sphinx.py", line 263, in __init__
    SphinxDocString.__init__(self, doc, config=config)
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape_sphinx.py", line 21, in __init__
    NumpyDocString.__init__(self, docstring, config=config)
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape.py", line 126, in __init__
    self._parse()
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape.py", line 337, in _parse
    self['See Also'] = self._parse_see_also(content)
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape.py", line 259, in _parse_see_also
    push_item(current_func, rest)
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape.py", line 240, in push_item
    name, role = parse_item_name(name)
  File "/home/rehas/Github/numpy/doc/sphinxext/numpydoc/docscrape.py", line 235, in parse_item_name
    raise ParseError("%s is not a item name" % text)
ParseError: `Arrayterator` is not a item name in u"A 1-D flat iterator for Arrayterator objects.\n\nThis iterator returns elements of the array to be iterated over in\n`Arrayterator` one by one. It is similar to `flatiter`.\n\nSee Also\n--------\n`Arrayterator`\nflatiter\n\nExamples\n--------\n>>> a = np.arange(3 * 4 * 5 * 6).reshape(3, 4, 5, 6)\n>>> a_itor = np.lib.arrayterator.Arrayterator(a, 2)\n\n>>> for subarr in a_itor.flat:\n...     if not subarr:\n...         print subarr, type(subarr)\n...\n0 <type 'numpy.int32'>\n\n"

**Comment by rehassachdeva** [comment] 2016-02-20 17:05
Sorry, I think this is what you asked for:

Failed to import 'numpy.doc.internals': no module named numpy.doc.internals
WARNING: [autosummary] failed to import u'numpy.broadcast_to': no module named numpy.broadcast_to
WARNING: [autosummary] failed to import u'numpy.lib.NumpyVersion': no module named numpy.lib.NumpyVersion
WARNING: [autosummary] failed to import u'numpy.ma.MaskedArray.tobytes': no module named numpy.ma.MaskedArray.tobytes
WARNING: [autosummary] failed to import u'numpy.ma.append': no module named numpy.ma.append
WARNING: [autosummary] failed to import u'numpy.matmul': no module named numpy.matmul
WARNING: [autosummary] failed to import u'numpy.moveaxis': no module named numpy.moveaxis
WARNING: [autosummary] failed to import u'numpy.nanmedian': no module named numpy.nanmedian
WARNING: [autosummary] failed to import u'numpy.nanpercentile': no module named numpy.nanpercentile
WARNING: [autosummary] failed to import u'numpy.ndarray.__matmul__': no module named numpy.ndarray.__matmul__
WARNING: [autosummary] failed to import u'numpy.ndarray.tobytes': no module named numpy.ndarray.tobytes
WARNING: [autosummary] failed to import u'numpy.shares_memory': no module named numpy.shares_memory
WARNING: [autosummary] failed to import u'numpy.stack': no module named numpy.stack
WARNING: [autosummary] failed to import u'numpy.testing.assert_raises_regex': no module named numpy.testing.assert_raises_regex
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2326 source files that are out of date
updating environment: 2326 added, 0 changed, 0 removed
reading sources... [ 29%] reference/generated/numpy.lib.Arrayterator            andard_fileirs
Exception occurred:
....

**Comment by rgommers** [comment] 2016-02-20 19:25
> Failed to import 'numpy.doc.internals': no module named numpy.doc.internals

This import error is odd. Can you check that ``numpy/doc/internals.py`` exists in the numpy you are using (check with ``np.__file__`` that you're actually using the numpy you think you are).

I cannot reproduce your failure with numpy 1.11.0b3 or master, and with or without ``numpydoc``. Sphinx version may also matter, I use 1.2.3. Don't use 1.3.0-1.3.4, those versions are known to be buggy. What versions of ``numpy``, ``numpydoc`` and ``Sphinx`` do you use?

**Comment by eayoungs** [comment] 2016-09-27 01:11
rehassachdeva, Is this issue closed? It says that your pull request has been merged but the issue is still 'open'.

**Comment by rehassachdeva** [comment] 2016-09-27 08:17
Yes Eric Youngson. This issue can be closed.
Thanks

**Comment by rgommers** [comment] 2016-09-27 08:36
thanks both

**Closed by rgommers** 2016-09-27 08:36 UTC
Labels: 04 - Documentation
