### ISSUE TITLE
Numpy issue calculating remote sensing index over entire image; Gives incorrect values by order of magnitude and sign for small number of values

### ISSUE THREAD

**Issue by ghobart** [numpy/numpy#21336] opened 2022-04-13 15:51 UTC
I hope this massages finds you all well. I discovered a bug in numpy while generating the remote sensing index Normalized Burn Ratio (NBR) over an entire image with these dimensions 3635 by 11365 for each band.

The index is calculated as follows (BandA- BandB)/( BandA+BandB). By comparing the numpy results with IDL I discovered that a small percentage of values were incorrect by both an order of magnitude and sign.

To solve the issue, I tried 1) casting the arrays to floats, 2) using np.divide, np.add, np.subtract, 3) unfactoring - calculating numerator and denominator in separate statements before finally dividing,  4) using deep copy of the arrays at every step 5) various combinations of the previous steps and anything else that i could think of but the values were always incorrect and always the same. I verified my IDL results by hand as well.

I found a workaround in numpy for this specific process since I only needed the NBR values for specific regions within the image by using np.take to extract the values from both bands region by region and then calculating the NBR values which were correct in this case.

The really bad news is I can't create a small sample to demonstrate this issue. I tried creating two test arrays of ones with the same dimensions and using numpy.put to enter the original image values into the two test arrays for only one of the regions where the NBR values were incorrect but in this case the NBR values were correct.

I can provide the original image data, the numpy results and the IDL results if you are interested in pursuing this issue. Thanks for all your hard work.

**Comment by ghobart** [comment] 2022-04-13 16:07
BTW. I'm using python 3.8 64 bit on a Windows 10 Enterprise (version 20H2) on a HP z8G4 with two Xeon Gold 5118 CPUS with 2  spanned 1TB Samsung Pro NVMe SSD as the system drive and 576 GB of Kingston ECC Ram. I'm reading the data in with Rasterio1.1.7 and using Numpy 1.22.3.

**Comment by mattip** [comment] 2022-04-13 17:26
Can you characterize the failures? Do they always happen in one region of the image or for a certain combination of `(BandA[y,x], BandB[y, x])`?

**Comment by ghobart** [comment] 2022-04-13 17:41
I'm not sure I completely understand your question.  The errors occur with my regions of interest but not necessarily for every pixel/voxel within that region.
I have not tried to systematically identify the x,y coordinates where the errors occur.  The regions where I extract the NBR values are random objects (forest disturbances) across the image. from one to the next the errors are always the same value. If that would be useful I could generate the offending co-ordinate pairs across the image.

**Comment by ghobart** [comment] 2022-04-13 17:42
**from one run to the next the errors are always the same value and co-ordinate location.

**Comment by charris** [comment] 2022-04-13 17:47
What data type is the image and how is it loaded?

**Comment by ghobart** [comment] 2022-04-13 17:49
I'm using rasterio 1.17 to load the np.uint64 image which I cast to a np.float64

**Comment by ghobart** [comment] 2022-04-13 17:54
Correction! loading a Uint16 and casting to float64

**Comment by mattip** [comment] 2022-04-13 21:14
Did you verify that the problematic values in the images as read from rasterio match the values you are feeding to IDL?

**Comment by ghobart** [comment] 2022-04-13 22:23
Yes when I use take() and calculate the NBR values they are correct, it's only when I calculate the NBR values over the entire image that the errors occur.

**Comment by mattip** [comment] 2022-04-14 07:22
I am a bit confused when you said 
> using deep copy of the arrays at every step

Do you mean you did `BandA = BandA.copy(); BandB = BandB.copy()` before the calculations or something else? What does `BandA.flags; BandB.flags` show? Perhaps there is some problem with non-contiguous data.

Before sharing the images, could you share the code you are using?

**Comment by seberg** [comment] 2022-04-15 12:15
I had added the milestone because it seems like this may be a serious issue.

@ghobart Getting the info Matti asked for would be great.  Since you tried to create a new array and fill it with the values. So it would seem this has something to do with how the data is stored in memorys rather than values.  `arr.flags` for all inputs would be the main thing to get an idea.  `arr.strides` may also be good and `arr.__array_interface__["data"][0]` could  help us, in case it is a SIMD alignment issue (but I doubt the last one).
However, if you have called `arr.copy()` on the original data, that should create a C-contiguous copy.  However `np.copy(arr)` could also return a fortran contiguous copy, so knowing how the copies were made that you tried is interesting.

You said that you did cast to float?  So none of the operations include a cast, right? 

The exact code snippet (even if it cannot reproduce it) would hel us to get a clearer picture.  Getting the data, result (and correct result) may also help for us to see if there are patterns for where the errors occur.

**Comment by ghobart** [comment] 2022-04-19 15:03
Apologies for not responding sooner. I have been having an issue accessing the machine where the issue originally manifested itself.  I have tried to recreate the issue on a couple of other machines to generate the flags you requested with no luck. Hopefully I will have access to the machine again very soon but it is out of my control. I will keep you posted.

**Comment by ghobart** [comment] 2022-04-22 14:46
I was briefly able to access the machine where the issue was manifesting itself. I had no idea this was only occurring on one machine until I tried to recreate the issue for this forum. It is strange that that 2 virtually identical machines are giving a different result. One correct and one not. The process was failing both in a standalone python script run on the command line and within a jupyter notebook. 

Here is a paired down version of the code in question. ( One of multiple versions attempted that failed to produce the correct NBR values) As I noted before I was able to workaround this issuing Numpy.take() from b4 and b6 arrays and calculated the NBR values instead of calcualting across the entire array.

import sys, os
import rasterio as rio
import numpy as np
import pickle

sys.path.insert(1, r'Z:\projects-f\IDL2python\C2C_att\Version2')
import C2C_att_parameters as C2C

TARGET_YEARS = C2C.TARGET_YEARS #1984-2020
ZN=C2C.ZN  #UTM zone
POS=C2C.POS # S, N, A (south, north, arctic)
dirHt = C2C.getDirHt()
fileHt = C2C.get_fileHt()


gparams =C2C.POS

svars=C2C.svars #['b4','b5','b6','nbr','greenness']
stats = C2C.stats #['STDV','MEAN'] 

for year in [1986]: #TARGET_YEARS:   
    
        print('starting {}'.format(year))
        prox = os.path.join(r'H:\Idl2Py_c2c_att\UTM_22S\Results\proxy_values','SRef_UTM{}{}_{}_proxy_v2.dat'.format(ZN,POS,year))

        with rio.open(prox) as P:
            sref_data= P.read().astype(np.float32)
            transform=P.transform
            crs_in = P.crs
        
        b4_vals = sref_data[3,:,:].copy()    
        b5_vals = sref_data[4,:,:].copy()     
        b6_vals = sref_data[5,:,:].copy()
        nbr_vals = (b4_vals-b6_vals)/(b4_vals+b6_vals).copy()
        green = np.tensordot(C2C.gparams,sref_data.astype(np.float64),axes=([0],[0]) ).copy()

        print('b4 flags ={}'.format(b4_vals.flags))
        print('b5 flags ={}'.format(b5_vals.flags))
        print('b6 flags ={}'.format(b6_vals.flags))
        print('nbr flags ={}'.format(nbr_vals.flags))
        print('green flags ={}'.format(green.flags))

Here's the flags for all the arrays:
b4 flags =  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

b5 flags =  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

b6 flags =  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

nbr flags =  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

green flags =  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

I compared to the flags on the machine that is producing the correct result and they are identical. :(

**Comment by charris** [comment] 2022-04-22 14:50
That is strange. Are the machines running the same OS/version? I'd suspect a hardware problem except that that would affect a lot more than the one problem.

**Comment by ghobart** [comment] 2022-04-22 14:54
They have exactly the same OS Windows 10 Enterprise, version 20H2, build 19042.1645 corporate edition for Natural Resources Canada. The machine are both HP G4Z8's purchased a about a year apart. The newer one is having the issue.

**Comment by ghobart** [comment] 2022-04-22 15:03
I agree. I have ported serval very large and complex processes from IDL to python and numpy with no issues up until now using the machine in question. 
WRT to this issue. I tried literally dozens of different runs using variations as I noted above. The errors were always identical and for the same pixel locations and value.

**Comment by seberg** [comment] 2022-04-22 15:09
It seems plausible that the one year appart means that you have a new CPU model, so it could still be related to SIMD code.
The only thing left I can think of checking for the input is the `arr.__array_interface__["data"][0]` in case somehow this is related to a SIMD alignment requirement/assumption somewhere that is not ensured correctly.
(only because you say that copying seems to fix it)

Two other things I can think of two ask for:
* Can you check what `np.show_config()` prints on both machines maybe?  It should end with something like:
  ```
  Supported SIMD extensions in this NumPy install:
      baseline = SSE,SSE2,SSE3
      found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
      not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
  ```
* Do you think you can figure out which operation is broken exactly?  My guess would be the division `/`, but anything is plausible of course.

**Comment by seberg** [comment] 2022-04-29 14:23
Ping @ghobart. Sorry for the ping, but this issue still worries me would you have time to try to narrow it down a little bit more with respect to those points?
Also, as an additional thing.  If always the same pixels are wrong, could you write out:
`np.nonzero(array == expected_array)` or so?  So that we can see which pixels are wrong?  (Plus the array shape, but I think we already have that.)

**Comment by ghobart** [comment] 2022-04-29 18:00
Apologies for not responding sooner. I was able to access the machine yesterday long enough to gather the information you requested.

You are correct that the CPU's are different. The machine with the issue has dual Xeon Gold 5218 and the older machine is a dual  Xeon Gold 5118. I do have another Z8G4 with the dual Xeon Gold 5218 but it does not appear to have the issue.

Here are the np.show_config() from all three machines.
[numpy_config_issue_Xeon5218.txt](https://github.com/numpy/numpy/files/8592627/numpy_config_issue_Xeon5218.txt)
[numpy_config_NOissue_Xeon5118.txt](https://github.com/numpy/numpy/files/8592628/numpy_config_NOissue_Xeon5118.txt)
[numpy_config_NOissue_Xeon5218.txt](https://github.com/numpy/numpy/files/8592629/numpy_config_NOissue_Xeon5218.txt)

I think there is a some confusion though. COPY() did not fix the issue. My workaround was to use Numpy.take() for each individual region of interest on both bands and then calculate NBR one region at a time as opposed to calculating NBR for the entire image using the complete arrays of band 4 and band 6 (and then using np.take() to obtain the NBR value for each region).

The dimension of each band of the 6 band image are ( lines , samples) =(11365 ,3635). 

I also ran arr.__array_interface__["data"][0] for the arrays in question. The jupypter notebook asciidoc is attached below.
(FYI I had to change the extension to .txt from .asciidoc to upload.
[Array_interface_output.txt](https://github.com/numpy/numpy/files/8592759/Array_interface_output.txt)

I'll endeavor to go into the lab and access the machine in question on Monday and get you the p.nonzero(array == expected_array) result.

**Comment by ghobart** [comment] 2022-04-29 18:02
BTW. I'm quite sure the issue is with the division but I will try to verify that the next time I have access to the machine.

**Comment by seberg** [comment] 2022-04-29 19:15
@ghobart I am a bit confused since the versions look quite different? One prints out the support SIMD stuff (a new version of NumPy) and is linked against OpenBLAS.  The other does not, and is linked against mkl probably.

Just to be sure, can you say again which NumPy versions you got exactly there?  And potentially how you installed them?  Not that we are running an `intel-numpy` or so...

Instruction is a Gold 5118 vs. a Gold 5218 set, which seems to mean that the latter has `AVX_CLX`, while the former does not.  This could well be the reason (I am not sure).

But as I said, I am confused that the output does not list the capabilities in `show_config`, so it would be nice if you can double check `np.__version__` also exactly?

But in the end, I guess we should dig into the division there, unless anything adds new information...

**Comment by ghobart** [comment] 2022-05-03 14:26
Hi. Thanks for the message. Here is a readme that I set up for our group ages ago that explains the setup process that I used
[INSTALL_cmds_README.txt](https://github.com/numpy/numpy/files/8610884/INSTALL_cmds_README.txt)
One caveat to the above process is that I needed to manually uninstall and reinstall scikit using pip. Looking at this now (with time and experience) I realize I should have used pip without the wheels for everything. Could this be the problem?

The following is the output of pip freeze from the machines with 5218 and 5118 CPUs.
[installed_packages_5118_NOissue.txt](https://github.com/numpy/numpy/files/8610900/installed_packages_5118_NOissue.txt)
[installed_packages_5218_Issue.txt](https://github.com/numpy/numpy/files/8611088/installed_packages_5218_Issue.txt)
[installed_packages_5218_NOissue.txt](https://github.com/numpy/numpy/files/8611107/installed_packages_5218_NOissue.txt)

The machine with the issue (CPU 5218) is running 1.19.5 whereas the machines with no issue (CPU 5118 and 5218 ) are running 1.22.3 and 1.19.5 respectively. 
FYI All the machines have Python2.7 installed for arcpy. The machine with the 5118 also has 32 bit python 3.7 installed although I highly doubt this is relevant. Just to be clear I am running 64 bit python 3.8.1 on all three machines and this is where the issue is manifesting itself.  I hope this helps.

**Comment by seberg** [comment] 2022-05-03 14:46
> The machine with the issue (CPU 5218) is running 1.19.5

Hmmm, that is an old version, so in that sense it is good, since at least the issue is not occurig on newer versions.
`numpy-1.19.5+mkl-cp38-cp38-win_amd64.whl` is also a weird version, it looks like it would be from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) but it does not exist there?

OTOH, I don't remember an explicit issue in 1.19.x that was fixed later that might cause this specifically.

At some point in the 1.19.x cycle, we had problems with a [windows bug](https://github.com/numpy/numpy/issues/17270) that should be fixed on windows though, unless the system is severely oudated.

---

Unfortunately, it seems to me that you should probably just upgrade the NumPy version then?  And that it may well be a weird thing about the specific wheel (although I do not have an idea as to what).

**Comment by charris** [comment] 2022-05-10 03:31
I'm going to remove the milestone. It would still be nice to be sure that current NumPy using OpenBLAS do not have the problem.

**Comment by seberg** [comment] 2022-10-19 09:47
Going to close the issue.  Hopefully, it is indeed long fixed, but it doesn't sound like we will be able to dig into it (unless the original reporter wants to spend time on it, and since upgrading should solve the issue, I expect that is unlikely).

**Closed by seberg** 2022-10-19 09:47 UTC

**Comment by ghobart** [comment] 2022-10-19 13:11
Yes. The upgrade resolved the issue. Thanks for your support. Kind regards
Geordie
