### ISSUE TITLE
DLL load failed: The specific module could not be found. (VSCODE)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [numpy/numpy#15183] opened 2019-12-26 15:08 UTC
Error below occurs upon `import numpy as np`; command works fine when typed directly in terminal, but fails when ran via [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner). My steps to reproduce:

```
## Attempt 1
conda create --name vsc --clone base  # NOTE: "base" is an unchanged Anaconda 10/19 base env

## Attempt 2
conda uninstall numpy
conda install numpy
conda update --all

## Attempt 3
conda uninstall numpy
conda install numpy
```
Output of `import sys; print(sys.version)` is `3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]`. VSCode shows it's running the expected Python interpreter: `Python 3.7.5 64-bit ('vsc': conda)` at bottom-left pane (see clip)

Brief [video demo](https://www.dropbox.com/s/cu4vzyp8ybdq6qo/np_demo.mp4?dl=0)

[Relevant SO](https://stackoverflow.com/questions/59519338/dll-load-failed-the-specific-module-could-not-be-found-vscode-numpy)

<hr>

**Env info**: Windows 10 x64, Anaconda 10/19 (virtual env), VSCode 1.41.1

<hr>

**Full traceback**:

```python
Traceback (most recent call last):
  File "D:\Anaconda\envs\vsc\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "D:\Anaconda\envs\vsc\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "D:\Anaconda\envs\vsc\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Desktop\School\Python\vscode\HelloWorld\app.py", line 1, in <module>
    import numpy as np
  File "D:\Anaconda\envs\vsc\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "D:\Anaconda\envs\vsc\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 
```

<hr>

**All enabled extensions**, sorted alphabetically:

  - Anaconda Extension Pack (1.0.1)
  - AREPL for python (1.0.20)
  - Blade Runner - Run task When Open (1.0.0)
  - Bootstrap 4, Font awesome 4, Font Awesome 5 Free & Pro snippets for Visual studio code (6.1.0)
  - Bracket Light Pro (0.4.3)
  - C/C++ (0.26.3-insiders2)
  - C++ Algorithm Mnemonics (1.0.3)
  - Code Runner (0.9.15)
  - Django (0.19.0)
  - Font Switcher (3.1.0)
  - Glasslt-VSC (0.1.6)
  - HTML CSS Support (0.2.3)
  - kite (0.102.0)
  - MagicPython (1.1.0)
  - One Dark Pro (3.2.1)
  - Python (2019.11.50794)
  - Python Extension Pack (1.6.0)
  - Theme by language (1.1.1)
  - Visual Studio IntelliCode (1.2.2)
  - YAML (0.6.1)

<hr>

**settings.json**:

```json
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "glassit.alpha": 250,
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingQuotes": "never",
    "editor.multiCursorModifier": "alt",
    "workbench.colorTheme": "One Dark Pro",
    "font-switcher.enableLivePreview": true,
    "theme-by-language.themes": {
        "c": "One Dark Pro",
        "*": "One Dark Pro",
        "python": "One Dark Pro"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "window.zoomLevel": 0,
    "editor.minimap.enabled": false,
    "python.formatting.provider": "autopep8",
    "[python]": {
        "editor.defaultFormatter": "ms-python.python"
    },
    "C_Cpp.updateChannel": "Insiders",
    "kite.showWelcomeNotificationOnStartup": false,
    
    "code-runner.executorMap": {
        "python":"$pythonPath $fullFileName",
      },
    "code-runner.showExecutionMessage": false,
    "code-runner.saveFileBeforeRun": true,
}
```

**Comment by rgommers** [comment] 2019-12-26 15:12
I've never seen `--clone`, and based on this report I wouldn't trust it. If you do a clean install of both NumPy and VSCode in a new conda env, does Code Runner work then?

**Comment by OverLordGoldDragon** [comment] 2019-12-26 16:23
@rgommers 

```
conda create --name vsc_test
conda install python==3.7.5
conda install numpy
# in VSCode: import numpy as np, etc
```
Still fails, w/ same error trace - and same deal when working in base env. Also, I don't install VSCode into Anaconda or via Anaconda, but separately and use Anaconda by selecting a Python interpreter in VSCode that's in the desired env.

As for `--clone`, it's a basic Anaconda command for a stable copy of packages into a fresh env; I doubt it's the culprit.

**Comment by rgommers** [comment] 2019-12-26 16:32
Okay I'll try to reproduce. How do you configure Code Runner? If via VSCode settings, those are a bit of a zoo so a screenshot would be helpful.

**Comment by rgommers** [comment] 2019-12-26 16:48
VSCode Python extension works fine. Code Runner is weird, it seems to ignore the path to the Python interpreter.

By the way, I added `conda activate vsc_test` to your example. Without it, you were probably mixing things from different envs.

**Comment by OverLordGoldDragon** [comment] 2019-12-26 18:18
@rgommers Right, I was typing from memory - `activate` was executed; here's the complete `settings.json` as accessed via `File -> Preferences -> Extensions (any tab) -> Edit in settings.json`; Code Runner configs at the very bottom:

```json
{
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "glassit.alpha": 250,
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingQuotes": "never",
    "editor.multiCursorModifier": "alt",
    "workbench.colorTheme": "One Dark Pro",
    "font-switcher.enableLivePreview": true,
    "theme-by-language.themes": {
        "c": "One Dark Pro",
        "*": "One Dark Pro",
        "python": "One Dark Pro"
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "window.zoomLevel": 0,
    "editor.minimap.enabled": false,
    "python.formatting.provider": "autopep8",
    "[python]": {
        "editor.defaultFormatter": "ms-python.python"
    },
    "C_Cpp.updateChannel": "Insiders",
    "kite.showWelcomeNotificationOnStartup": false,
    
    "code-runner.executorMap": {
        "python":"$pythonPath $fullFileName",
      },
    "code-runner.showExecutionMessage": false,
    "code-runner.saveFileBeforeRun": true,
}
```

**Comment by rgommers** [comment] 2019-12-27 12:51
Thanks. I can't reproduce this, but that may be due to not having a Windows 10 machine. On Linux this works fine with Code Runner.

**Comment by zhaoyin214** [comment] 2020-03-25 00:36
maybe this work...

In vscode open `settings.json` file for editing using the following operations:

```
(type)               CTRL + SHIFT + P
(search for:)        open settings
(click:)             Preferences: Open Settings (JSON)
```
add 3 lines to the file

```
{
    ... # any other settings you have already added (remove this line)

    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows": ["/K", "x:\\xxx\\Anaconda3\\Scripts\\activate.bat x:\\xxx\\Anaconda3"],
    "python.condaPath": "x:\\xxx\\Anaconda3\\Scripts\\conda.exe"
}
```

**Comment by gwd666** [comment] 2020-05-13 12:23
So far this worked - on the same problem for - me https://github.com/numpy/numpy/issues/15343#issuecomment-591397147 
In short: activate the Conda env from the prompt and run `> code .` to start VS Code on the project. 
Haven't tried the settings.json tweak form above (yet)

**Comment by rossbar** [comment] 2020-07-18 19:44
Closing as environment management/VS code configuration is hopefully sufficiently covered in the [troubleshooting guide](https://numpy.org/devdocs/user/troubleshooting-importerror.html). If not, PRs to add to the troubleshooting guide to help resolve this (and related) problems are very welcome.

**Closed by rossbar** 2020-07-18 19:44 UTC
Labels: 32 - Installation, 57 - Close?

**Comment by jtskowronek** [comment] 2021-05-19 23:24
> maybe this work...
> 
> In vscode open `settings.json` file for editing using the following operations:
> 
> ```
> (type)               CTRL + SHIFT + P
> (search for:)        open settings
> (click:)             Preferences: Open Settings (JSON)
> ```
> 
> add 3 lines to the file
> 
> ```
> {
>     ... # any other settings you have already added (remove this line)
> 
>     "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
>     "terminal.integrated.shellArgs.windows": ["/K", "x:\\xxx\\Anaconda3\\Scripts\\activate.bat x:\\xxx\\Anaconda3"],
>     "python.condaPath": "x:\\xxx\\Anaconda3\\Scripts\\conda.exe"
> }
> ```

This worked for me, so far...
