### ISSUE TITLE
decide what to do about float->int conversion errors in 1.11

### ISSUE THREAD

**Issue by olebole** [numpy/numpy#7162] opened 2016-02-01 19:50 UTC
As asked by @njsmith, here is another regression with the b2:  sunpy/sunpy#1653
This is mainly since floating points seems to not to be accepted as index anymore.

**Comment by charris** [comment] 2016-02-01 20:14
Not really a regression, floating point indexes have been deprecated for some time.

**Comment by njsmith** [comment] 2016-02-01 20:23
Yeah, it looks like we've been issuing DeprecationWarnings on floating point values used as indices since 1.9.0 (released Sept 2014, so ~1.5 years). I'm pretty convinced it's a good change overall (I know multiple people, including myself, have already caught some nasty subtle bugs thanks to the warning message), but I guess one option would be to back out the change and give people a few more months to catch up (maybe making the warning much more prominent in the mean time). IIRC this was one possible strategy for dealing with deprecations we discussed at the meeting this year -- N months of deprecation, and then a one-time grace period of M additional months if people still complain after the first N months :-).

@olebole: What would you prefer happen here?

(I'm also wondering if we should just give up on silent DeprecationWarnings and make a NumpyDeprecationWarning class that's visible by default...)

**Comment by njsmith** [comment] 2016-02-01 20:24
(Adding milestone since we should probably finish or at least follow-up on the conversation before 1.11.0-final; doesn't necessarily indicate that anything will actually change.)

**Comment by charris** [comment] 2016-02-01 20:27
@njsmith We already have a `VisibleDeprecationWarning`.

**Comment by juliantaylor** [comment] 2016-02-01 20:29
I find two releases too short for from deprecation to removal, especially as .11 is so soon after .10.
Maybe after two releases silent -> visible, and then removal after 4 if its an important change.

**Comment by olebole** [comment] 2016-02-01 20:30
For me, it looks more a problem of sunpy. I have  however no idea how much it takes to fix it. Maybe, one of the sunpy developers could comment here (@Cadair )?

**Comment by njsmith** [comment] 2016-02-01 20:33
@charris: Yeah, but no policy on deciding which kinds of warnings get which treatment, or guidance to downstreams on how to handle these things. I'm saying maybe we should switch *all* our deprecation warnings to be visible, and I guess give our special warning class a better name so that projects who are on top of things have an easy way to hide it again if they want to. Anyway, that's a side discussion for later...

@juliantaylor: talking in terms of number-of-releases doesn't make sense to me, because the time between our releases is historically super variable. Thinking in terms of months makes more sense to me. 1.9 was almost 1.5 years ago (unless I got my math wrong, always possible :-)), and AFAIK pretty much all the folks who are going to upgrade at all have upgraded to at least 1.9 (though obviously not 1.10). I think at this point the folks who haven't made this change are the ones who are just not paying attention to DeprecationWarnings. This is a problem that I think we should worry about; I just question whether waiting longer will actually be effective at solving it :-)

**Comment by Cadair** [comment] 2016-02-01 20:35
I think from the SunPy side, indexing with floats is really a mistake anyway, they should be explicitly cast to integers. It seems like it has been deprecated for long enough, but I am very +1 on having all DeprecationWarnings made visible.

**Comment by juliantaylor** [comment] 2016-02-01 20:39
replace releases with some appropriate time unit then, but I think we should give at least the attentive developers that run with fatal warnings in testsuites a chance to fix stuff before annoying their users.

**Comment by rgommers** [comment] 2016-02-01 20:55
+1 for always visible.

1.5 years after a warning became visible in a minor release seems like a reasonable timeframe.

**Comment by charris** [comment] 2016-02-09 20:54
@juliantaylor The real problem is that DeprecationWarnings are ignored until they turn into errors. I suspect this would never have been noticed if it was still a DeprecationWarning.

**Comment by charris** [comment] 2016-02-09 22:45
Just to note that this is a big problem with StatsModels. We may want to postpone the change for another release cycle, but that won't help if the problems downstream don't get fixed.

**Comment by njsmith** [comment] 2016-02-09 23:03
I checked on the statsmodels mailing list, and it sounds like the problem there is just that they never get around to releasing things :-). Apparently almost all of these issues were already fixed on their master branch, it's just that their last release was in 2014 so no users actually have the fixes yet :-/

https://groups.google.com/forum/#!topic/pystatsmodels/6nGIZnprjjI

Testing statsmodels master against numpy 1.11, only two failures (both trivial test-suite-only problems with floats being passed as sizes to np.random):
https://gist.github.com/TomAugspurger/c90c76db693e6b1dd43a

**Comment by charris** [comment] 2016-02-09 23:08
@njsmith Thanks for testing StatsModels, I was just about to run them myself on their master.

**Comment by njsmith** [comment] 2016-02-09 23:34
I didn't test it, credit for that goes to @TomAugspurger :-)

**Comment by rgommers** [comment] 2016-02-10 06:10
> Apparently almost all of these issues were already fixed on their master branch, it's just that their last release was in 2014 so no users actually have the fixes yet :-/

Statsmodels is very bad at making releases, but to be fair the last one was December 2014, so 14 months ago. There'll be a lot more projects depending on Numpy that released around that time or earlier. I think we should give it one more release.

**Comment by njsmith** [comment] 2016-02-10 07:41
@rgommers: scikit-image also seems to have two pieces of code that fail with float->int issues, and scikit-learn has one... I guess I'm also leaning towards turning these failures back into VERY LOUD WARNINGS for a release or so.

**Comment by seberg** [comment] 2016-02-10 18:33
Well, visibledeprecationwarning is probably loudly enough, simple since it is not a subclass of deprecation warning and thus will not get hidden accidentally as easily. So we might go with that.

@rgommers I seem to remember you saying that deprecating this is at the extreme minimum 1.5 years or something like that, so you were right :)

**Comment by charris** [comment] 2016-02-10 18:59
@seberg We will need to import it into C in order to use it. Or, we could define it in C and export it from multiarray.

**Comment by jreback** [comment] 2016-02-10 19:05
FYI I am planning on turning ``pandas`` warnings to errors in 0.18.0 (coming shortly, though will see if have complains on the RC), see [here](https://github.com/pydata/pandas/pull/12246).

We have been deprecated since May 2014, so more than enough time I think.

**Comment by njsmith** [comment] 2016-02-11 02:55
scikit-image is using `--pre` in their travis builds now, and their master is clean: https://travis-ci.org/scikit-image/scikit-image/builds/108415016
so they'll be okay once they do a release too

**Comment by charris** [comment] 2016-02-16 16:35
The relevant commit was reverted in #7249 changing the errors to `VisibleDeprecationWarning` for numpy 1.11.x.

**Closed by charris** 2016-02-16 16:35 UTC
Labels: 7 - Deprecation

**Comment by shoyer** [comment] 2016-02-16 17:31
I also turned up a failure in the xarray test suit thanks to this change :/.

For future reference, is there an easy way to make an unexpected `DeprecationWarning` error when running a test suite? It's definitely hard to notice these when they're turned off by default...

**Comment by charris** [comment] 2016-02-16 17:50
The `VisibleDeprecationWarning` won't be turned off.

**Comment by charris** [comment] 2016-02-16 17:53
As to making them error or not, hmm, not sure what the best way would be. You can probably set that up in your own testsuite. Anyway, sounds like a good topic for discussion, might raise it on the mailing list.

**Comment by seberg** [comment] 2016-02-16 18:00
@shoyer, use python 3.5 or late python 3.4, and make sure you have a warnings context around all "ignore" filters (if you use python 2, you have to be even more careful and not use ignore filters at all).

My personal opinion is: Set all warnings to error in the test suit, in dev versions and only suppress/catch them locally ("ignore" is tricky/shaky on python <3.4, which is why I did my suppress warnings PR, as annoying as it is). In Release versions, they should maybe print, but not error for sure, since you don't have control over people using a slightly newer numpy version.

We could add filters to show our warnings, but I think using the VisibleDeprecationWarning class is the better option. Maybe we should make VisibleDeprecationWarning standard procedure for any non-trivial deprecation.

Btw. Thanks a lot for making all these maintenance changes Chuck, its a huge amount of work :/.
