### ISSUE TITLE
Importing the numpy c-extensions failed on raspberrypi

### ISSUE THREAD

**Issue by 87bdharr** [numpy/numpy#16012] opened 2020-04-17 22:14 UTC
### Reproducing code example:

```python
import numpy
```

### Error message:

I am trying to import numpy within a virtual python environment on my raspberry pi. However, each time I attempt to import numpy on my Jupiter notebook (connected via ssh) I get an `import error` message (apologies it’s an image, I can’t get the iPad app to copy text):

![925E13CC-8A17-4195-A06B-3E0BE5FB8205](https://user-images.githubusercontent.com/45598743/79617484-884d3b00-80ff-11ea-84e2-bde316da7997.png)
![A997E952-EEC1-4583-A2E7-E0A84A98A9D7](https://user-images.githubusercontent.com/45598743/79617491-8be0c200-80ff-11ea-8bd1-86389c3f11cb.png)

### How I installed numpy
`pip3 install numpy`

### Numpy/Python Version
Python 3.7.3
Numpy 1.18.2

### Actions taken so far
* I have reinstalled numpy within my virtual environment using:
`pip install --upgrade --force-reinstall numpy`
* I have checked numpy within my non-virtualised environment and it works perfectly fine, so there’s something about my virtual environment it doesn’t like.

Can anyone see what the issue might be? Thanks in advance.

**Comment by charris** [comment] 2020-04-17 22:29
What virtual environment? Does it have it's own Python?

**Comment by 87bdharr** [comment] 2020-04-18 10:18
> What virtual environment? Does it have it's own Python?

Hey, I pip installed `virtualenv`, and all of my virtual environments are stored in a directory called ‘python virtual environments’. When I activate my virtual environment	 called ‘(virtual-environment-1) I’m able to run python as shown below. However, when I import numpy I get the `IMPORT ERROR`. Maybe the image below can help?
![image](https://user-images.githubusercontent.com/45598743/79635039-4d322280-8166-11ea-8494-c781fbfc1d74.jpeg)

**Comment by mattip** [comment] 2020-04-18 19:04
Duplicate of gh-14553 and [many others](https://github.com/numpy/numpy/issues?q=is%3Aissue+libf77blas+raspberrypi)

Try `sudo apt-get install libatlas-base-dev`

We should really modify that error message when `platform.uname()[-1] == 'armv7l` to mention this.

**Comment by 87bdharr** [comment] 2020-04-18 20:01
> Duplicate of gh-14553 and [many others](https://github.com/numpy/numpy/issues?q=is%3Aissue+libf77blas+raspberrypi)
> 
> 
> 
> Try `sudo apt-get install libatlas-base-dev`
> 
> 
> 
> We should really modify that error message when `platform.uname()[-1] == 'armv7l` to mention this. 

Works a treat ! Thanks very much

**Closed** 2020-04-18 21:37 UTC
Labels: 32 - Installation
