### ISSUE TITLE
`broadcast_to` fails for zero shapes

### ISSUE THREAD

**Issue by brandonwillard** [numpy/numpy#19425] opened 2021-07-07 16:05 UTC
`numpy.broadcast_to` does not work when one of the shape values in its first argument is zero; however, broadcasting performed through element-wise multiplication with an array of ones _does_ work.

### Reproducing code example:

```python
import numpy as np


X = np.empty((1, 0))

np.broadcast_to(X, (2, 1)).shape
# ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (1,0) and requested shape (2,1)

(np.ones((2, 1)) * X).shape
# (2, 0)
```

### NumPy/Python version information:

`1.19.0 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0]`

**Comment by WarrenWeckesser** [comment] 2021-07-08 23:19
The problem is not specifically that the second dimension of `x` is 0.  The problem is that it is not 1. You'll have the same problem if `x.shape` is, say, (1, 3).

In general, in a call such as `broadcast_to(x, shp)`, if `x.ndmin` and `len(shp)` are the same, `broadcast_to` requires that each element of `x.shape` is either 1 or is equal to the corresponding element in `shp`.

In your example, the result of broadcasting arrays with shapes (1, 0) and (2, 1) is (2, 0), not (2, 1).  You can't broadcast an array with shape (1, 0) *to* the shape (2, 1).  (Note that `broadcast_to(x, (2, 0))` works.)

When you compute `np.ones((2, 1))*x`, you don't have the constraint that the result *must* have shape (2, 1).  Regular broadcasting applies, so the result has shape (2, 0).

**Comment by WarrenWeckesser** [comment] 2021-07-08 23:21
I'm closing the issue, but don't hesitate to ask for clarification if my explanation was confusing.

**Closed by WarrenWeckesser** 2021-07-08 23:21 UTC
Labels: 33 - Question

**Comment by brandonwillard** [comment] 2021-07-08 23:59
Ah, yes, the _strictness_ of `broadcast_to` makes sense as an explanation.  Is there a non-strict version of `broadcast_to` that will produce a view and provide the same type of broadcasting as multiplication with `ones` (e.g. a `broadcast_like`)?

**Comment by WarrenWeckesser** [comment] 2021-07-09 00:34
I think a combination of `broadcast_shapes` and `broadcast_to` will do what you want, perhaps something like:

```
def broadcast_with(x, shp):
    return np.broadcast_to(x, np.broadcast_shapes(x.shape, shp))
```
Examples:

```
In [75]: x = np.zeros((1, 0))

In [76]: y = broadcast_with(x, (2, 1))

In [77]: y
Out[77]: array([], shape=(2, 0), dtype=float64)

In [78]: a = np.arange(6).reshape((1, 2, 3))

In [79]: b = broadcast_with(a, (2, 1, 3))

In [80]: b.shape
Out[80]: (2, 2, 3)

In [81]: b
Out[81]: 
array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])
```
