### ISSUE TITLE
numpy.ndarray.astype converts np.nan differently across OSs

### ISSUE THREAD

**Issue by jamie-sgro** [numpy/numpy#19816] opened 2021-09-02 13:09 UTC
Casting np.arrays to int32 converts `np.nan` to:
1. `array(-2147483648, dtype=int32)` on a local Mac M1 machine
2. `array(0, dtype=int32)` on a docker image running ubuntu

### Reproducing code example:

On the following system:
```
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
```
The following code casts np.nan to -2147483648
```python
>>> import numpy as np
>>> np.array(np.nan).astype(np.int32)
array(-2147483648, dtype=int32)
```

On a docker image with the following system:
``` bash
# uname -srv
Linux 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
```

The following code casts np.nan to 0

```python
>>> import numpy as np
>>>np.array(np.nan).astype(np.int32)
array(0, dtype=int32)
```

**Note:** One can run `docker run -it python:3 bash` to replicate the environment, and `pip install numpy` which installs from `numpy-1.21.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch6`

### NumPy/Python version information:

In our Mac M1 local machinge
``` python
>>> sys.version
'3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12) \n[Clang 11.0.1 ]'
>>> np.__version__
'1.21.2'
```

In our Ubuntu image:
``` python
>>> sys.version
'3.7.11 (default, Jul 27 2021, 15:14:22) \n[GCC 10.2.0]'
>>> np.__version__
'1.21.2'
```

**Comment by seberg** [comment] 2021-09-07 15:40
Unfortunately, we currently use whatever C does, and that is *undefined*.  One thing that should happen here (this is a known bug), is that it should give you an "invalid value" warning as per IEEE (assuming the compiler handles this correctly).

So, I am not sure we can do too much about it, except make sure that the floating point warning shows up correctly. OTOH, if it does not come with a serious performance hit, there may be a point in improving the behaviour more.

**Comment by seberg** [comment] 2021-09-07 15:42
Ah missed the issue before, closing as duplicate of gh-14412.

**Closed by seberg** 2021-09-07 15:42 UTC
