### ISSUE TITLE
numpy import fails when built for mingw-w64

### ISSUE THREAD

**Issue by clin1234** [numpy/numpy#27033] opened 2024-07-24 19:14 UTC
```
❯ python -m numpy --verbose
<frozen importlib._bootstrap>:488: Warning: Numpy built with MINGW-W64 on Windows 64 bits is experimental, and only available for
testing. You are advised not to use it for production.

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
```

❯ pip show numpy
Name: numpy
Version: 2.0.1

**Comment by mattip** [comment] 2024-07-25 01:54
What exactly are you reporting? If there is a crash please copy paste the backtrack as text. If it is just the warning, then why report it?

**Comment by clin1234** [comment] 2024-07-25 02:49
How do I provide a backtrace while importing a module?

**Comment by mattip** [comment] 2024-07-25 05:00
Can you continue to use python after importing numpy, and all you see out of the ordinary is this warning? Then there is no issue, this is a warning not an error. There is nothing to report and we can close this. Be aware that there may be problems further along when using an unsupported configuration.

Does the import fail? Then you should see a traceback of the error that you can copy-paste here.

**Comment by clin1234** [comment] 2024-07-25 15:15
> Can you continue to use python after importing numpy, and all you see out of the ordinary is this warning? Then there is no issue, this is a warning not an error. There is nothing to report and we can close this. Be aware that there may be problems further along when using an unsupported configuration.
> 
> Does the import fail? Then you should see a traceback of the error that you can copy-paste here.

Importing numpy immediately crashes the Python interpreter

**Comment by muscus353** [comment] 2024-07-26 03:54
You shall compile numpy from source by msvc instead of MINGW-W64 on Windows 64 bits. MINGW-W64 will generate .a library, while win64 use .lib library.

**Comment by mattip** [comment] 2024-07-26 04:24
Where are you getting NumPy from? If you are compiling yourself, you should be able to run under a C debugger and see where the segfault is.

**Comment by seberg** [comment] 2024-08-08 19:18
Closing this, we need full details on the setup to be of any help, and there was no activity for two weeks.

**Closed by seberg** 2024-08-08 19:18 UTC
Labels: 57 - Close?

**Comment by davidkhala** [comment] 2024-11-29 01:50
I have the same issue on window 11 recently.
But I have never installed MINGW intentionally in my deskop

**Comment by davidkhala** [comment] 2024-11-29 02:23
I find a solution in my context, see if it matches
If you are using databricks-connect latest version today, `15.4.3`. It will rely on an outdated  numpy version 1.26.4. This is the cause. 

Then I specify numpy = "^2.1". Then `poetry update` help me to find a older compatible databricks-connect version `14.3.2`. 

```
  - Updating numpy (1.26.4 -> 2.1.3)
  - Downgrading databricks-connect (15.4.3 -> 14.3.2)
```

After that `python -m numpy --verbose` works as expected and shows
```
C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\davidkhala-databricks-Xt0HavPi-py3.13\Scripts\python.exe: No module named numpy.__main__; 'numpy' is a package and cannot be directly executed

```

**Comment by mwiedeV1** [comment] 2025-04-29 12:00
1.26.4 also causes Crash on WINGW-W64.
Why they dont test the own libraries?
