### ISSUE TITLE
piecewise is broken with x dtype=int64

### ISSUE THREAD

**Issue by naught101** [numpy/numpy#14606] opened 2019-09-27 07:56 UTC
[piecewise](https://docs.scipy.org/doc/numpy/reference/generated/numpy.piecewise.html) fails if the xdtype isn't a float.

### Reproducing code example:

```python
%pylab

xs1, xs0 = 0, 2
xe0, xe1 = 4, 6
z = linspace(-1, 7, num=900)

ws = np.piecewise(
    z,
    [z < xs1, (xs1 <= z) & (z <= xs0), xs0 < z],
    [1, lambda z: (1 + np.cos((z - xs1) / (xs0 - xs1) * np.pi)) / 2, 0])

plot(z, ws)
```
produces:

![image](https://user-images.githubusercontent.com/167164/65752157-89ad1b00-e14f-11e9-8d42-f3be615a64ae.png)

```python
%pylab

xs1, xs0 = 1970, 2010
xe0, xe1 = 2050, 2090
z = np.arange(1960, 2101)

ws = np.piecewise(
    z,
    [z < xs1, (xs1 <= z) & (z <= xs0), xs0 < z],
    [1, lambda z: (1 + np.cos((z - xs1) / (xs0 - xs1) * np.pi)) / 2, 0])

plot(z, ws)
```
produces:

![image](https://user-images.githubusercontent.com/167164/65752241-b7925f80-e14f-11e9-8804-fc31b53a7f76.png)

They should be pretty much identical functions. If I use
```python
z = np.arange(1960, 2101, dtype=float64) 
```
in the second example, I get this:

![image](https://user-images.githubusercontent.com/167164/65752342-ef99a280-e14f-11e9-8dc8-8b85df1f7e32.png)

Which is correct.

Luckily this only had my head banging against the wall for a couple of hours on a Friday afternoon :D

**Comment by eric-wieser** [comment] 2019-09-27 09:32
Which version of python and numpy!

**Comment by ewmoore** [comment] 2019-09-27 14:12
Looking back through the history, `piecewise` has always, since it was introduced in 8ac222e, chosen its output dtype as the dtype of the `x` input.  I guess it could still be a bug, but it isn't not a regression and it has worked that way for 14 years.

**Comment by ewmoore** [comment] 2019-09-27 14:17
see also #2483

**Comment by naught101** [comment] 2019-09-30 04:00
Ah, sorry:

numpy                     1.16.4           py36h99e49ec_0  
python                    3.6.8                h0371630_0    anaconda

**Comment by mattip** [comment] 2019-12-08 09:11
Closing. The documentation states that the output shape and type will be the same as the input. Please reopen if there is a concrete proposal for a documentation change to make this clearer, I don't think we are open to changing behaviour.

**Closed by mattip** 2019-12-08 09:11 UTC
