### ISSUE TITLE
ValueError: invalid __array_struct__ when assigning to object-dtype ndarray

### ISSUE THREAD

**Issue by TomAugspurger** [numpy/numpy#16939] opened 2020-07-24 11:47 UTC
Hi. Pandas is broken with numpy master :)

### Reproducing code example:

```python

In [1]: import numpy as np
In [2]: out = np.empty(3, dtype="object")
In [3]: out[:] = [np.int64, np.int64, np.int64]
```
### Error message:

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-d20bd885ed9b> in <module>
----> 1 out[:] = [np.int64, np.int64, np.int64]

ValueError: invalid __array_struct__
```

### Numpy/Python version information:

Installed from a wheel with `pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple numpy`

```
1.20.0.dev0+2d12d0c 3.7.6 (default, Dec 30 2019, 19:38:28)
[Clang 11.0.0 (clang-1100.0.33.16)]
```

I don't immediately see what commit could have caused this. https://github.com/numpy/numpy/pull/16850 mentions object-dtype scalars, but doesn't look quite right.

**Comment by rgommers** [comment] 2020-07-24 12:15
The SciPy builds on TravisCI with `NUMPYSPEC='--pre` also just started failing (e.g. https://travis-ci.org/github/scipy/scipy/jobs/711362812, with stats broadcasting and `test_methods_with_lists` and `TestDifferentialEvolutionSolver.test_args_tuple_is_passed` failures), may be related.

**Comment by charris** [comment] 2020-07-24 13:44
Probably because I fixed the nightly cython build failures and triggered new builds yesterday. The nightly builds had stalled out :)

**Comment by charris** [comment] 2020-07-24 13:51
@seberg Thoughts?

**Comment by seberg** [comment] 2020-07-24 14:18
I am a bit surprised I did not notice additional scipy failures when comparing to master.  The SciPy ones are reverse broadcasting, I thought I covered that, but apparently I missed something.

The problem is this type of code:
```
bounds     = [(-np.inf, np.inf), (np.array([2]), np.array([3]))]
np.array(bounds)
```
which only works because `float(np.array([2])` happens to work *for numpy arrays specifically*.  I honestly think those failures are better, but I have to see how we can go through a deprecation.

The pandas code with the dtypes, I am not sure about, may also be coercion related likely.  It seems like we used to ignore errors here at some point and now I know that its necessary to support these classes as objects.

**Comment by seberg** [comment] 2020-07-24 14:23
Ah, on the pandas issue, we currently have this, so that explains the change:
```
In [1]: np.array(np.int64)       
ValueError: invalid __array_struct__
```
they behave identical now, but went towards the error case.

**Comment by eric-wieser** [comment] 2020-07-24 14:24
Was just about to comment the same - this has always been a problem for scalars, it's just we made behavior consistent for lists of them too.

**Comment by eric-wieser** [comment] 2020-07-24 14:25
#8877 is very similar here, our problem is we use `x.__array_struct__` when we ought to be using something like `type(x).__array_struct__`

**Comment by eric-wieser** [comment] 2020-07-24 14:26
An easy fix would be to ignore `__array_struct__` if it is of type `getset_descriptor`.

**Comment by seberg** [comment] 2020-07-24 14:54
True, maybe that is the best solution. We may need to also let `property` pass, and I have to check if there was a similar change for `__array_interface__`.

**Comment by eric-wieser** [comment] 2020-07-24 15:05
Perhaps checking for `tp_get` is sufficient?

**Comment by seberg** [comment] 2020-07-24 15:44
Hmmm, I guess so, although it would also be nice not to rely on inspecting slots?  The closest thing I could find in python are these from `inspect`:
```
def ismethoddescriptor(object):
    """<snip>""""
    if isclass(object) or ismethod(object) or isfunction(object):
        # mutual exclusion
        return False
    tp = type(object)
    return hasattr(tp, "__get__") and not hasattr(tp, "__set__")

def isdatadescriptor(object):
    """<snip>"""
    if isclass(object) or ismethod(object) or isfunction(object):
        # mutual exclusion
        return False
    tp = type(object)
    return hasattr(tp, "__set__") or hasattr(tp, "__delete__")
```
Interestingly, it seems that `tp_descr_get` is always set to `slot_tp_descr_get` (for python defined types), until it is called the first time and sets itself to `NULL`.  The up-side of all of this, is that at least for `__array_struct__` we do a `CapsuleCheck` first, so it doesn't matter too much if it the checks here are slow...

**Comment by seberg** [comment] 2020-07-24 16:48
Opted for `isinstance(arraylike, type) and hasattr(arraylike.special_attribute, "__get__")`...

**Comment by seberg** [comment] 2020-07-24 16:57
As to the SciPy issues, I am wondering if we could just get away with it, but have not thought about trying to keep supporting them much.  Note that this really only affects `np.array`, assignments like `arr[0] = arr` and `arr[0, ...] = arr` could keep using reverse broadcasting (although the first case still only works by using `float(arr)`, I admit.

If we expect this to be extremely rare, I would like it. But, I admit I am worried that the error is very confusing when you look at it for code that previously worked.

I am not sure yet, I suppose I can guess that for basically all of our numerical types, I know that it will incidentally work out (and thus a DeprecationWarning would be in order), but otherwise the error needs to be raised immediately.

**Comment by seberg** [comment] 2020-07-24 20:30
OK, gh-16943 address the SciPy issue. Not by supporting it, but by deprecating it for now.  Its not perfect (you can construct things that skip the deprecation in theory, e.g. scipy sparse matrices might), and you may get the warning but then a failure, which is slightly annoying.  But I think it would be fairly tricky to get it "right", and it is clear that this type of usage is bad incorrect. I.e. in my opinion it seems good enough to cover almost everything, in the face of covering everything requiring to mix up two distinct steps of the array-coercion process.

**Comment by bashtage** [comment] 2020-07-25 22:45
statsmodels with - - pre is also failing with this.

**Comment by charris** [comment] 2020-07-25 23:20
Keeping issue open as it isn't clear we are done with it.

**Comment by bashtage** [comment] 2020-07-28 15:00
This has not been fixed in master, in case it was though that it had:

```
import numpy as np
a = np.empty(3,dtype="object")
a[:]=[np.int8, np.int16, np.int32]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-00becd691fe7> in <module>
----> 1 a[:]=[np.int8, np.int16, np.int32]

ValueError: invalid __array_struct__
```

**Comment by seberg** [comment] 2020-07-28 15:17
@bashtage gh-16941 has not been merged, which would solve this (and also let a few other things pass maybe)

**Comment by seberg** [comment] 2020-11-19 18:47
Closing as the PR is merged now. Please ping if I am missing something.

**Closed by seberg** 2020-11-19 18:47 UTC
