### ISSUE TITLE
BUG: arr.any() raises invalid exception.

### ISSUE THREAD

**Issue by local-minimum** [numpy/numpy#10328] opened 2018-01-05 10:25 UTC
This is an edge case but easy to reproduce:
```
In [1]: v = [None, np.array([{}, {1: 2}], dtype=object)]

In [1]: np.array([v, v]).any()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-cd0bae3ef9b8> in <module>()
----> 1 np.array([v, v]).any()

/home/xxx/.virtualenvs/yyy/lib/python2.7/site-packages/numpy/core/_methods.pyc in _any(a, axis, dtype, out, keepdims)
     36 
     37 def _any(a, axis=None, dtype=None, out=None, keepdims=False):
---> 38     return umr_any(a, axis, dtype, out, keepdims)
     39 
     40 def _all(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The error message is definitely wrong since it suggest doing exactly what I did.

I'm not sure exactly what would be the expected behaviour here, best would if you ask me to ensure that `.any()` (and `.all()`) only could return `True` or `False`. This is not how it works at the moment though so unsure what should be done.

Numpy version `1.12.1` on Ubuntu 17.04.

**Comment by pv** [comment] 2018-01-05 11:20
The current behavior looks like the expected behavior, the only problem probably is the error message is somewhat more complex to understand because it is raised by a comparison of an element in the object array.

**Comment by local-minimum** [comment] 2018-01-05 12:24
Related: if 0-d arrays are scalars, then also `np.array(None).any()` should raise an `Exception` since `any` can't really be defined for scalars.

**Comment by eric-wieser** [comment] 2018-01-05 14:25
@pv: Perhaps we should wrap errors that occur inside object arrays?

We could go further, and have something like
```
class ObjectLoopException(Exception):
    result : ndarray[object]
    exception : ndarray[object]
```
where exceptions are collected for each element, and the result is `None` where exceptions occur.

**Comment by seberg** [comment] 2023-01-02 19:48
Going to close this, since the error is not incorrect and the example doesn't even work anymore (not that it matters, it is easy to fix).

Eric's idea can be discussed, i.e. wrapping internal errors in some fashion to indicate that an error happened in the inner-loop, rather than more generally.  But we should open a new issue if we want to pursue that.

**Closed by seberg** 2023-01-02 19:48 UTC
