### ISSUE TITLE
BUG: Array copy does not zero out gaps in structured dtypes

### ISSUE THREAD

**Issue by ikehall** [numpy/numpy#10789] opened 2018-03-23 15:49 UTC
Recently updated from numpy 1.11.0 to 1.14.0 and some of my code was immediately broken.

You can simulate the broken bits through the following

```python
my_metadata_dtype = np.dtype({'names':['Thing1','Thing2'], 
                             'offsets':[22, 40], 
                             'formats':['>u2','>i4'], 
                             'itemsize'=256})
list_of_arrays = [np.arange(i, i+128, dtype='>i2') for i in range(5)]
array_of_metadata = np.array(list_of_arrays, dtype=my_metadata_dtype)
other_array_of_metadata = np.array(list_of_arrays)
other_array_of_metadata.dtype = my_metadata_dtype
```
One would expect that array_of_metadata and other_array_of_metadata should be the same thing.
They are not.  I submit that the line creating array_of_metadata is buggy.  I believe this produced the same as the lines that produce other_array_of_metadata in previous versions.

But that wasn't even the primary bug I was going to talk about.  I discovered that one while hunting down this one.

Take our other_array_of_metadata:
Let's make a new array from a subset of this array (not just a view)
```python
sub_array = np.array(other_array_of_metadata[2:4])
sub_array.dtype = '>i2'
```

You will see that our sub_array now has strange things in the spaces that were not exposed by our dtype.  Not the nice aranges we had constructed before.  In 1.11, this code would have preserved the data that was not exposed.  Now it appears that the unexposed portions of sub-array are never initialized to anything.  This matters because sometimes we want to only expose a part of our metadata to our code, but when we write the metadata back out to disk, want all of it preserved.  

I can understand making a design choice to not initialize the unexposed portions of a dtype when constructing new elements from literals or from scratch.  But when you already have an element of this dtype, ignoring the empty space seems like an inferior choice.

**Comment by ahaldane** [comment] 2018-03-23 16:11
I think this is the same as #10752, see the discussion there. We want to drop support of `np.array(arange(10))` behaving like a view when using structured dtypes, since it has led to other bugs. It should behave like a copy.

Since change this seems to break multiple people's code though, so maybe we should consider supporting this "view-like" behavior a little longer, but I really think we should remove it eventually.  Let me investigate if we can support `np.array(arange(10))` style creation, with a deprecation warning, for 1.14.3.

**Comment by ikehall** [comment] 2018-03-23 16:40
I think I understand your logic for the decision that was made, however I would argue that the current behavior now is for np.array() to behave like assignment into an array rather than like a copy to an array.  

Perhaps a better solution is to move this view-like copying to a new function. Currently I am getting around this new behavior to get view-like-copying with the following.

```python
def array_copy(array_or_view):
    return np.frombuffer(array_or_view.tostring(), dtype=array_or_view.dtype)
```

I'm not the biggest fan of this, but it works.

**Comment by ahaldane** [comment] 2018-03-23 16:51
Wait a second.. am I confusing something? I just tried your code in 1.11.0 (and 1.11.1) and I get the same behavior as in 1.14.2. Here's a trimmed version of your example:
```python
>>> import numpy as np
>>> np.__version__
'1.11.1'
>>> my_metadata_dtype = np.dtype({'names':['Thing1','Thing2'], 
...                              'offsets':[2, 12], 
...                              'formats':['>u2','>i4'], 
...                              'itemsize': 22})
>>> list_of_arrays = [np.arange(i, i+22, dtype='>i2') for i in range(2)]
>>> a1 = np.array(list_of_arrays, dtype=my_metadata_dtype)
>>> a2 = np.array(list_of_arrays)
>>> a2.dtype = my_metadata_dtype
>>> 
>>> a1
array([[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7),
        (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14),
        (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20),
        (21, 21)],
       [(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8),
        (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15),
        (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21),
        (22, 22)]], 
      dtype={'names':['Thing1','Thing2'], 'formats':['>u2','>i4'], 'offsets':[2,12], 'itemsize':22})
>>> a2
array([[(256, 100665088), (3072, 285217280)],
       [(512, 117442560), (3328, 301994752)]], 
      dtype={'names':['Thing1','Thing2'], 'formats':['>u2','>i4'], 'offsets':[2,12], 'itemsize':22})
>>>
```
I get the same output in 1.14.2. What is your output?

**Comment by ikehall** [comment] 2018-03-23 17:00
Unfortunately I do not have an easy way of reverting back to 1.11.0, so I can't verify, but, for that part of the code (my first example), I was going on what I thought was the behavior back then...perhaps I was wrong.  Sorry.

It was the second example that broke my actual code, and trying to determine what the new behavior was led me to the first example which I apparently erroneously thought was changed.

**Comment by eric-wieser** [comment] 2018-03-23 17:17
I don't understand your `array_copy` function - it looks like it's just `.copy()` to me

**Comment by ikehall** [comment] 2018-03-23 17:33
The difference is that array_copy is faithful to the voids in my dtype whereas copy ignores them.

```python
my_metadata_dtype = np.dtype({'names':['Thing1','Thing2'], 
                             'offsets':[22, 40], 
                             'formats':['>u2','>i4'], 
                             'itemsize':256})
list_of_arrays = [np.arange(i, i+128, dtype='>i2') for i in range(5)]
other_array_of_metadata = np.array(list_of_arrays, dtype='>i2')
other_array_of_metadata.dtype = my_metadata_dtype

subarray_copy = other_array_of_metadata[2:4].copy()
subarray_array_copy = array_copy(other_array_of_metadata[2:4])

subarray_copy.dtype='>i2'
subarray_array_copy.dtype='>i2'
```
Compare those last two arrays.  subarray_array_copy still has the underlying arange with which it was created whereas subarray_copy does not.

**Comment by ikehall** [comment] 2018-03-23 17:55
After some more poking around though, my array_copy does not necessarily respect shape like I would want it to.

Now it is:
```python
def array_copy(array_or_view):
    return np.frombuffer(array_or_view.tostring(), 
                         dtype=array_or_view.dtype).reshape(array_or_view.shape)    
```

**Comment by mattip** [comment] 2019-01-16 08:44
If I understand correctly there are two issues here: 

- did we break old code with no warning
- is the new behaviour correct

In both cases, I think the ship has sailed. @ikehall is there anything more we can do here?

**Comment by ikehall** [comment] 2019-01-18 20:15
There was old code that broke.  I can get (and really already have) onboard with dropping the support for view-like behavior with structured arrays by using the array_copy() method I posted above in place of array().

A better solution might be to make .copy() behave like array_copy(), so that voids in a structured dtype are copied byte for byte into the new array rather than left uninitialized.

ex:
```python
def array_copy(array_or_view):
    return np.frombuffer(array_or_view.tostring(), 
                         dtype=array_or_view.dtype).reshape(array_or_view.shape)

my_dtype = np.dtype({'names':['Thing1','Thing2'], 
                              'offsets':[22, 40], 
                              'formats':['>u2','>i4'], 
                              'itemsize':256})

a = np.zeros(2, my_dtype)
b = np.copy(a)
c = array_copy(a)
a.dtype = '>u2'
b.dtype = '>u2'
c.dtype = '>u2'
```
You will note that b looks substantially different than a or c because the voids in the dtype are left uninitialized.  This is really the issue that broke my old code.  Previously I had just used array() in place of copy, and that had worked for me in the past.  I fixed the broken old code with array_copy() and moved on.  But I think it might be a good idea to make .copy() behave this way too.  I can understand why using array() was not a great idea though.

**Comment by mattip** [comment] 2019-02-14 20:00
I changed the title to reflect the remaining issue: when using np.copy, gaps in the data due to offsets are not set to `0`. I think this fits in with the general behavior of numpy. See for instance the warnings around the use of `numpy.where`.

Perhaps an addition to the documentation of `np.copy` could make this clearer

**Comment by seberg** [comment] 2019-02-14 20:05
Just to crossref gh-12686 is somewhat related (possibly a duplicate even).

**Comment by seberg** [comment] 2021-10-04 22:37
I am closing this, as per Matti's last comment, this is probably the desired behaviour, and it is the behaviour now for many years so there is no point in thinking about a regression. Happy if open new issues about this or related problems though (or reopen this one)!

**Closed by seberg** 2021-10-04 22:37 UTC
Labels: 57 - Close?, component: numpy.dtype
