### ISSUE TITLE
Inconsistent `np.bincount` casting behavior for arrays vs array-likes

### ISSUE THREAD

**Issue by BvB93** [numpy/numpy#19061] opened 2021-05-21 16:22 UTC
`np.bincount` currently seems to use handle different casting rules for arrays (`"safe"`) vs array-likes (`"unsafe"`).

This gives rise to the odd situation where, for example, it is ok to pass a list of (numerical) strings, 
but not an array with the very same content.

Examples
---------
``` python
In [1]: import numpy as np

In [2]: np.bincount(["0", "1", "2"])
Out[2]: array([1, 1, 1], dtype=int64)

In [3]: np.bincount(np.array(["0", "1", "2"]))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-23ed17d55ec9> in <module>
----> 1 np.bincount(np.array(["0", "1", "2"]))

<__array_function__ internals> in bincount(*args, **kwargs)

TypeError: Cannot cast array data from dtype('<U1') to dtype('int64') according to the rule 'safe'

```

**Comment by seberg** [comment] 2021-05-21 19:46
I guess the current code attempts to cast to coerce to int64 directly.  Instead of effectively doing `np.asarray(arr).astype(dtype, copy=False, casting="safe")`.  In general, it is probably OK, to go via that array creation.

<details> <summary> Some thoughts, because this touches NEP 42!:   </summary>

It might be nice to be able to have casting safety available to array coercion more readily.  I.e. to remove the indirection of going via the full casting machinery just to figure out if what "safety" storing the value has.

Basically, we can't implement: `np.asarray(arr, dtype=dtype, casting="safe")` unless we implement it internally using `np.asarray(arr).astype(dtype, copy=False, casting="safe")`.  More importantly maybe, this also affects setting a single element:
```
integer_array_1d[0] = 3.1415
```
which *always* uses force-casting (for python scalars at least).  We have no very direct way to transition away from that...

There are two solutions (aside from just living with the current behaviour – the extra copy isn't too bad, since most inputs should be arrays already):

1. Do not have fast-paths for the item assignment.  Assigning a float to an integer array would always make NumPy float (in a short lived buffer), and use the full casting machinery.
2. (**preferred solution**)  I *adapt NEP 42* with this in mind.  That is `__dtype_setitem__` should return `NPY_CASTING` instead of just an error flag.  It will take a while before we will actually use it, I guess.  But at least we *could* solve all of those quirks explicitly, while also keeping the fast paths intact.  (Note: This still allows option 1. a DType can choose to use option 1., all they have to do is always return "equivalent" for the casting safety and not signal they understand, e.g. the float!)

Thanks for the nudge Bas :).

</details>

**Comment by BvB93** [comment] 2021-05-21 22:01
>  Instead of effectively doing `np.asarray(arr).astype(dtype, copy=False, casting="safe")`

Right, the odd thing is that doesn't seem to be happening here, as this would make aforementioned `U1` to `int64` 
cast illegal, both for arrays and arbitrary array-likes. Instead, `np.bincount` seems to perform something more or less 
like the example below whenever parsing its input.
``` python
if isinstance(obj, np.ndarray):
    return obj.astype(np.intp, casting="safe")
else:
    return np.asarray(obj).astype(np.intp, casting="unsafe")
```
I don't recall seeing a similar pattern anywhere else in the codebase before. Generally when a cast is performed 
it's either safe _or_ unsafe, but here we have this weird mix of both where sometimes it uses safe casting but 
other times it doesn't.

> It might be nice to be able to have casting safety available to array coercion more readily.

Note to self: read up on NEP 42 again; I'm honestly reading some pretty fascinating things in this comment of yours.

**Comment by seberg** [comment] 2021-05-22 04:54
So the actual reason is, that we have an `NPY_ARRAY_FORCECAST` flag for array creation. If that is not set and the input is already a single array (not a sequence of arrays), then "safe" casting is used.  (The force-cast flag, or lack thereof, only works when creating an array from another array).

So yes, without that flag (which `np.array` uses), you get exactly the code you wrote.  I would be surprised if not a few, or even most, other C defined functions have this behaviour.  I.e. `np.take` does the same thing. (But most NumPy functions don't cast to a specific dtype.)

**Comment by WarrenWeckesser** [comment] 2024-07-31 14:41
Closing this as a duplicate of the older issue https://github.com/numpy/numpy/issues/3138

**Closed by WarrenWeckesser** 2024-07-31 14:41 UTC
Labels: 00 - Bug
