### ISSUE TITLE
Signed zero discrepancy vs. Python on float np.remainder

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#6317] opened 2015-09-15 13:02 UTC
```
>>> np.remainder(-1.,1.)
-0.0
>>> (-1.) % 1.
0.0
```

It seems Python is right here, since the result is supposed to be of the same sign as the dividend, e.g.:

```
>>> np.remainder(-1.01,1.)
0.98999999999999999
```

And actually:

```
>>> (-1) % (-1.)
-0.0
>>> np.remainder(-1.,-1.)
-0.0
```

**Comment by ahaldane** [comment] 2015-09-15 16:43
Speaking of `np.remainder`, I also recently noticed that it treats integer zero strangely:

    >>> np.reciprocal(np.array(0))
    -9223372036854775808

 Probably should return 0 with a warning, like `np.int32(1)/np.int32(0)`.  Thus for ints, reciprocal would return 1 if x==1, otherwise 0.

**Comment by ahaldane** [comment] 2015-09-15 16:44
Oh oops misread, you are talking about np.remainder

**Comment by argriffing** [comment] 2015-09-15 16:58
fwiw that's a float nan interpreted as an integer (sorry for continuing off-topic..)
```python
>>> np.float64(np.nan).astype(int)
-9223372036854775808
```

**Comment by ahaldane** [comment] 2015-09-15 17:14
Yes.

Sorry for noise, please continue any side discussion at #6318.

**Comment by mhvk** [comment] 2015-09-15 17:14
The problem with how the remainder is calculated also affects `divmod` -- see #6127

**Comment by pitrou** [comment] 2015-09-15 17:29
> The problem with how the remainder is calculated also affects divmod -- see #6127

I'm not sure this is the same issue. Here the result's value is correct, just the sign is incorrect (note that 0.0 == -1.0).

**Comment by mhvk** [comment] 2015-09-15 17:38
@pitrou - you may be right that the problems are separate. My link was triggered by the problem in `divmod` being in part because the sign of the remainder is checked and then the remainder is changed without changing the quotient. It does seem that part of the code needs some looking after...

**Comment by tlatorre-uchicago** [comment] 2019-01-23 23:03
I think the root of the problem is how the sign is calculated here: https://github.com/numpy/numpy/blob/464f79eb1d05bf938d16b49da1c39a4e02506fa3/numpy/core/src/npymath/npy_math_internal.h.src#L668.

From the most recent commit to that file it looks like the author's intention was to copy the behavior of the python function `float_divmod`, however the sign check there looks like this:

```c
/* div is zero - get the same sign as the true quotient */
floordiv = copysign(0.0, vx / wx); /* zero w/ sign of vx/wx */
```

and `copysign` is defined as:

```c
double
copysign(double x, double y)
{
    /* use atan2 to distinguish -0. from 0. */
    if (y > 0. || (y == 0. && atan2(y, -1.) > 0.)) {
        return fabs(x);
    } else {
        return -fabs(x);
    }
}
```

however the numpy implementation does not use the `atan` trick.

**Comment by bsipocz** [comment] 2019-10-15 20:59
Closing as I think this has been fixed, on current master:
```
In [75]: >>> np.remainder(-1.,1.)                                                                                       
Out[75]: 0.0

In [76]: >>> (-1.) % 1.                                                                                                 
Out[76]: 0.0
```

**Closed by bsipocz** 2019-10-15 20:59 UTC
