### ISSUE TITLE
ENH: Replace updateifcopy arrays.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#9257] opened 2017-06-16 13:53 UTC
Arrays with the `NPY_ARRAY_UPDATEIFCOPY` set are not compatible with python interpreters that do not use refcounting, PyPy in particular. It most cases it should be possible to replace them with a function call, and in those places where that is not possible, such as `flatiter.__array__` we should be able to return array copies instead. Updateifcopy arrays are created in the following spots
```
numpy/core/src/umath/reduction.c:190:        if (PyArray_SetUpdateIfCopyBase(ret_copy, (PyArrayObject *)ret) < 0) {
numpy/core/src/multiarray/iterators.c:1111:            if (PyArray_SetUpdateIfCopyBase(ret, it->ao) < 0) {
numpy/core/src/multiarray/multiarraymodule.c:810:            if (PyArray_SetUpdateIfCopyBase(out_buf, out) < 0) {
numpy/core/src/multiarray/cblasfuncs.c:429:            if (PyArray_SetUpdateIfCopyBase(out_buf, out) < 0) {
numpy/core/src/multiarray/nditer_constr.c:2926:                if (PyArray_SetUpdateIfCopyBase(temp, op[iop]) < 0) {
numpy/core/src/multiarray/ctors.c:2010:            if (PyArray_SetUpdateIfCopyBase(ret, arr) < 0) {
numpy/core/src/multiarray/mapping.c:3208:        if (PyArray_SetUpdateIfCopyBase(a_copy, a) < 0) {
```

**Comment by charris** [comment] 2017-06-16 13:53
See #9249 for some discussion.

**Comment by seberg** [comment] 2017-06-16 14:06
Just checked scipy:
```
scipy/ndimage/src/nd_image.h:        ret->flags |= NPY_UPDATEIFCOPY;
scipy/ndimage/src/nd_image.h:        PyArrayObject *shadow = NA_InputArray(a, t, requires | NPY_UPDATEIFCOPY );
scipy/sparse/sparsetools/sparsetools.cxx:            return PyArray_FROM_OF(obj, NPY_C_CONTIGUOUS|NPY_WRITEABLE|NPY_UPDATEIFCOPY);
scipy/sparse/sparsetools/sparsetools.cxx:            return PyArray_FROM_OTF(obj, typenum, NPY_C_CONTIGUOUS|NPY_WRITEABLE|NPY_UPDATEIFCOPY);
```
The sparsetool stuff is probably real usage as well. But one cxx (with two occurances) sounds pretty harmless.

**Comment by njsmith** [comment] 2017-06-16 19:02
This might be a dupe of #7054.

**Comment by mattip** [comment] 2017-09-19 15:10
once pr #9639 gets merged, we can encourage scipy to use the new semantics

**Comment by mattip** [comment] 2017-11-10 13:34
IMO we can close this

**Closed** 2017-11-10 16:02 UTC
Labels: 17 - Task, 24 - PyPy, component: numpy.core
