### ISSUE TITLE
Unexpected result for numpy.dot 

### ISSUE THREAD

**Issue by fatrabber** [numpy/numpy#10071] opened 2017-11-24 06:37 UTC
Hi All,

This is a similar problem of another unsolved issue:
https://github.com/numpy/numpy/issues/9656

The code:
101     print x.shape
102     print b.shape
103     y_pred = np.dot(x[:5], b)
104     print(y_pred[0])
105
106     y_pred = np.dot(x.astype(np.float64),b.astype(np.float64))
107     print (y_pred[0])
108
109     y_pred = np.dot(x, b)
110     print(y_pred[0])

Output:
(76870, 3073)
(3073, 1)
[ 2.09536389]
[ 10.75221317]
[ 10.69663251]

The expected result should be [ 2.09536389], which is the same if I only use the first 5 rows of x. If I use less than 6 rows, the result will be correct, but as long I used more than 5 rows ( >= 6 ), the result will be wrong.  And every time I run, the wrong results will be slightly different.

I tried float64 and the result is still wrong.

System info:
centos 7

np.config.show()
lapack_opt_info:
libraries = ['mkl_rt', 'pthread']
library_dirs = ['/opt/anaconda2/lib']
define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
include_dirs = ['/opt/anaconda2/include']
blas_opt_info:
libraries = ['mkl_rt', 'pthread']
library_dirs = ['/opt/anaconda2/lib']
define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
include_dirs = ['/opt/anaconda2/include']
lapack_mkl_info:
libraries = ['mkl_rt', 'pthread']
library_dirs = ['/opt/anaconda2/lib']
define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
include_dirs = ['/opt/anaconda2/include']
blas_mkl_info:
libraries = ['mkl_rt', 'pthread']
library_dirs = ['/opt/anaconda2/lib']
define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
include_dirs = ['/opt/anaconda2/include']

np.__version__
'1.13.3'

I once heard a friend working on AI projects told me MKL lib has some crazy bugs like this, but not sure if it is related.

Thanks all.

**Comment by fatrabber** [comment] 2017-11-24 06:57
Changed a different machine, everything is right:

output:
(76870, 3073)
(3073, 1)
[ 2.09536389]
[ 2.09536389]
[ 2.09536389]

I am gonna try to update numpy and compare again. Seems it's MKL related.

In [3]: np.__version__
Out[3]: '1.11.3'

In [4]: np.__config__.show()
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/anaconda2/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda2/include']

**Comment by fatrabber** [comment] 2017-11-24 09:33
Another update.

I think I can be sure that it's MKL's problem. On the first machine, I used same numpy( 1.13.3) but different environment, which does not use MKL, the result is all good.

So between the wrong result and right result, the only different was my environment, which is MKL.

**Comment by pv** [comment] 2017-11-24 10:06
If you get strange results from basic linear algebra when using 
Anaconda, report it to Anaconda issue tracker because it's likely to be 
a problem with the linear algebra libraries they ship.

Only the anaconda developers can fix such issues in their product.

**Comment by mingwandroid** [comment] 2017-11-24 10:28
@fatrabber, would it be possible to get exact, complete reproduction steps here? You could assume `Anaconda` is installed if you want.

**Comment by fatrabber** [comment] 2017-11-24 21:42
@pv OK. I think this is more related to MKL instead of anaconda. Anaconda may just include a bad lib from MKL. I will see where I should dress this to.

Thanks,

**Comment by fatrabber** [comment] 2017-11-24 22:21
@mingwandroid 
Here is what I think may help to reproduce:
1. have anaconda 5.0, which has newest MKL
2. install tensorflow, which creates an environment that uses newest MKL.
3. run this program:

import numpy as np
import tensorflow as tf
row, col = 76870, 3073
#row, col = 10, 3073
a = np.random.normal(size=(row, col))
b = np.random.normal(size=(col, 1))
np_outer = np.dot(a,b)
print(np_outer[0,0])
old_way = 0.0
for i in range(col):
    old_way = old_way + a[0,i] * b[i,0]
print(old_way)

Two outputs will be different.

There are few tricks here:
1. if "import tensorflow as tf" is commented out, results are fine. I think this is because tf uses the news MKL.
2. if the data is not enough, say row is 10 instead of 76870, the results are fine. I think this is because MKL will only be used when the data is large.

If more people can reproduce this, I think we can be sure it's a problem of MKL lib.

Thanks,

**Comment by mingwandroid** [comment] 2017-11-25 00:55
@fatrabber, please take this to https://github.com/ContinuumIO/anaconda-issues/issues

When you do, please explain how you installed `tensorflow`.

**Comment by fatrabber** [comment] 2017-11-25 01:23
Thanks mingwandroid.
The problem has been directed to: https://github.com/ContinuumIO/anaconda-issues/issues/7480

**Comment by msarahan** [comment] 2018-01-25 00:17
@seberg I recommend closing this issue.  It has been resolved at https://github.com/ContinuumIO/anaconda-issues/issues/7480

**Comment by seberg** [comment] 2018-01-25 08:24
@msarahan thanks for the notice!

**Closed by seberg** 2018-01-25 08:24 UTC
Labels: 57 - Close?
