### ISSUE TITLE
np.clip behavior inconsistent with documentation

### ISSUE THREAD

**Issue by rmccampbell** [numpy/numpy#15693] opened 2020-03-03 20:12 UTC
The np.clip function's documentation says:
```
Equivalent to but faster than ``np.maximum(a_min, np.minimum(a, a_max))``.
No check is performed to ensure ``a_min < a_max``.
```
This strict definition would imply that if a_min > a_max it will return a_min. However the experimental behavior is that a_max will be returned instead. This implies either the documentation should be changed to say `np.minimum(a_max, np.maximum(a, a_min))` or the behavior should be changed to match the documentation, or at very least it should be made clear that this behavior is unspecified. 

Note this may be a duplicate of #5142 but that seems to be outdated/not updated for 6 years, and this is specifically about the inconsistency with the documentation. 
### Reproducing code example:

```python
>>> import numpy as np
>>> np.clip(0, 1, -1)
-1
```

### Numpy/Python version information:

Numpy version: 1.17.4
Python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment] 2020-03-03 20:36
Duplicate of #15579, I think

**Comment by seberg** [comment] 2020-03-03 21:24
Right, seems like this was recently fixed, thanks for the report!

**Closed by seberg** 2020-03-03 21:24 UTC
