### ISSUE TITLE
Request for triage permissions

### ISSUE THREAD

**Issue by m-newhauser** [numpy/numpy#25500] opened 2023-12-26 17:54 UTC
Hi, contributors! I signed up to triage for Numpy through CodeTriage and am interested in getting access to assign labels to issues, etc. I'm happy to work with a core developer or other contributor to learn the ropes before being granted such permissions. Let me know!

**Comment by mattip** [comment] 2023-12-26 18:04
Welcome.
What is CodeTriage? We usually give out permissions after someone has some experience with the codebase. As stated on our [contribute](https://numpy.org/contribute/) page, anyone can dive in to the issue tracker.

**Comment by m-newhauser** [comment] 2023-12-27 04:26
That makes total sense. How many issues would you say I should aim for? I’m new to contributing so still building up those skills but think I could help out with prioritizing and following up on existing issues.

**Comment by mattip** [comment] 2023-12-27 04:56
Since our goal is to make the project better in a secure and sustainable way, we don't have a fixed criteria for contributor advancement.

**Comment by rgommers** [comment] 2023-12-28 09:56
I'd encourage you to work for a few months on issues that interest you @m-newhauser, and then check back in case we haven't already noticed and proactively given you triage rights as a result of us noticing sustained constructive contributions.

For triaging, adding better reproducers to issues helps, as does confirming that something is fixed. And if you see suitable issues that interest you, attempting to fix them yourself is great too of course.

I'll close this issue now, since your question is answered - but please don't hesitate to ask if you have more questions.

**Closed by rgommers** 2023-12-28 09:56 UTC
Labels: 33 - Question

**Comment by melissawm** [comment] 2023-12-28 11:27
[CodeTriage](https://www.codetriage.com/) is a service that will regularly send you links to issues from selected open source projects as a suggestion for you to work on. 

@m-newhauser feel free to also join our other [communication channels](https://numpy.org/contribute/) and don't hesitate to reach out if you have questions 😄 Cheers!

**Comment by m-newhauser** [comment] 2023-12-28 16:50
Thank you @rgommers @mattip and @melissawm  for your helpful responses! Will get to work on some issues.
