### ISSUE TITLE
Where is code fragment that checks matrix shape compatilbility?

### ISSUE THREAD

**Issue by LSKhappychild** [numpy/numpy#20374] opened 2021-11-15 06:20 UTC
Hi.
I'm quite sorry to post such dumb question because of my lack of understanding, but
is there any code fragment that checks matrix shape compatibility when doing matrix multiplication like gemv, gemm and so on?
I followed the logic of gemv, but failed to find any logic that checks matrix shape compatibility. I cannot find that in cblas code, either. 
Anyone can give me a slight, but bright insight for me?
Thx in advance

**Comment by rkern** [comment] 2021-11-15 07:01
https://github.com/numpy/numpy/blob/main/numpy/core/src/common/cblasfuncs.c#L253-L360

I found this by noting the error message when I passed in misaligned arrays to `np.dot()` and then searched for a phrase in the error message that seemed promising. I found that the phrase `'not aligned'` appears in an error message raised by the function [`dot_alignment_error()`](https://github.com/numpy/numpy/blob/main/numpy/core/src/multiarray/common.c#L292), and then I searched for where that function is called.

I am going to close this issue as it is not a bug report or a feature requests. Questions can be asked on the [mailing list](https://scipy.org/mailing-lists/), primarily.

**Closed by rkern** 2021-11-15 07:01 UTC
