### ISSUE TITLE
atan2 regression with Sun Studio Compilers on Linux (Trac #1400)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#1998] opened 2012-10-19 21:00 UTC
_Original ticket http://projects.scipy.org/numpy/ticket/1400 on 2010-02-18 by trac user ChristianMarquardt, assigned to unknown._

When compiling numpy-1.4.0 with the Sun Studio Compilers (v12 Update 1) on Linux (an OpenSUSE 11.1 in my case), about 30 tests in numpy.test() fail; all failures are related to the arctan2 function. 

I've found that in r7732 a patch was applied to trunk/numpy/core/src/private/npy_config.h in response to #1799, #1800, and #1801, #undef'ing the HAVE_ATAN2 variable in order to fix a broken atan2() implementation on Solaris. This does no good with the SunStudio 12.1 compiler on Linux, though; it apparently only works without failures with HAVE_ATAN2 defined.

The attached patch ensures that the original patch is only applied on Sun platforms (i.e., not on Linux). If applied, all tests are completed successfully under Linux. BTW, I did not observe #1802 or #1803... 

I have no access to a Solaris machine, so I don't know if the original patch (which was for Sun workshop 6 - I think that's not available any more) is required with Sun Studio 12.1 at all.

**Comment by rgommers** [comment] 2021-05-08 16:15
Duplicate of gh-2417, closing.

**Closed by rgommers** 2021-05-08 16:15 UTC
Labels: 00 - Bug, Patch, component: numpy.core
