### ISSUE TITLE
Mathematically incorrect behaviour of adding numpy vectors

### ISSUE THREAD

**Issue by maldun** [numpy/numpy#5541] opened 2015-02-08 12:14 UTC
Hi!

Currently If I add an 3x1 vector to an 1x3 vector I get a matrix:

```python
In [1]: from numpy import *

In [2]: eins = ones((3,1))

In [3]: eins
Out[3]: 
array([[ 1.],
       [ 1.],
       [ 1.]])

In [4]: zwei = ones(3); zwei
Out[4]: array([ 1.,  1.,  1.])

In [5]: eins + zwei                                                                                     
Out[5]:                                                                                                 
array([[ 2.,  2.,  2.],                                                                                 
       [ 2.,  2.,  2.],                                                                                 
       [ 2.,  2.,  2.]])    
```

This is
1. Mathematically not correct; either it should return an 3x1 or 1x3 vector or return an Exception that the dimensions do not match
2. Unpractilly for programming, because dimension mismatches go on without being noticed, and therefore are hard to debug, and always have to be checked seperately.

I think the best way would do not permit such a behaviour. At least I don't see a use for such a behaviour. If I'm wrong correct me please.

In Octave at least a warning is provided:

```matlab
octave:3> ones(1,3) + ones(3,1)
warning: operator +: automatic broadcasting operation applied
ans =

   2   2   2
   2   2   2
   2   2   2
```

**Comment by WarrenWeckesser** [comment] 2015-02-08 13:44
Actually, this is correct behavior.  It is an example of *broadcasting*, a powerful feature of numpy.  Take a look at http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

**Comment by jaimefrio** [comment] 2015-02-08 14:30
Yes, this is clearly not a bug, but a feature, and a prominent one actually, so I am going to close this. If you have further concerns after reading Warren's link, the [mailing list](http://www.scipy.org/scipylib/mailing-lists.html) may be a better place to get them answered.

**Closed by jaimefrio** 2015-02-08 14:30 UTC

**Comment by maldun** [comment] 2015-02-08 20:29
Ok thank you for pointing me to the link, I already supposed, that it is a not a bug but a feature, since it is also contained in the Matlab/Octave standards.

Nevertheless I think that broadcasting silently may be harmful to the reliability of code, except shape cheks are always done. That Octave gives a warning is a good thing from my opinion, especially since Python warnings can be caught, handled and debugged.

**Comment by pv** [comment] 2015-02-08 20:45
The feature may feel surprising to you, but not to users already
familiar with Numpy, and it is covered by most tutorials. Unlike in
Octave/Matlab where broadcasting is only a recent addition (which is
likely the reason why there is a warning), the feature has always been
part of Numpy.

**Comment by argriffing** [comment] 2015-02-08 21:13
I see this is being [discussed](http://mail.scipy.org/pipermail/numpy-discussion/2015-February/072207.html) on the mailing list, so I'll just say that this may be the first time I've been pro-magic in such a debate.

**Comment by tacaswell** [comment] 2015-02-08 21:49
I disagree there is no basis in math, this broadcasting behaviour is closely related to outer products http://en.wikipedia.org/wiki/Outer_product

**Comment by argriffing** [comment] 2015-02-08 21:53
Here's a related Matlab thread http://www.mathworks.com/matlabcentral/newsreader/view_thread/69365.
