### ISSUE TITLE
BUG: numpy/f2py/tests/test_callback.TestF77Callback.test_all fails on PyPy

### ISSUE THREAD

**Issue by rlamy** [numpy/numpy#9383] opened 2017-07-07 18:05 UTC
Specifically, the call `self.module.t(math.degrees, fun_extra_args=(math.pi,))` fails with `TypeError: degrees() missing 1 required positional argument: 'x'`. The issue lies with the handling of built-in functions in `create_cb_arglist()` (generated [here](https://github.com/numpy/numpy/blob/master/numpy/f2py/cfuncs.py#L1044)). In PyPy, though built-in functions have a different type than user functions, they do have a `__code__` attribute. Therefore, unlike on CPython, line 1099 `tot = PyInt_AsLong(PyObject_GetAttrString(tmp,\"co_argcount\")) - di;` runs, and overrides the presumably expected (and unrelated) calculation of `tot`at lines 1065-1067.

The intent of the code being unclear to me, I'm not sure how to fix it.

**Comment by mattip** [comment] 2017-07-09 11:09
The code in question is 12 years old, the last time anyone touched it was AFAICT four years ago

https://github.com/numpy/numpy/blame/master/numpy/f2py/cfuncs.py#L1099

Maybe a pull request that passes all tests on both Pypy and CPython would be one way to progress

**Comment by mattip** [comment] 2017-07-10 02:26
forcing the --debug and --debug-capi arguments to f2py (by adding them to the f2py_opts in numpy/f2py/tests/util.py), it seems to me the difference is not in tot, but that 3.14 is not passed in. Compare lines 17 and 45 in the debug output [here](https://gist.github.com/mattip/c2867a7e22a6c90cc3053281a7cfff9e). Note that pypy needed a commit to avoid ``PyObject_Print(NULL, ...)``

**Comment by mattip** [comment] 2017-07-10 03:02
sorry, you are correct, the problem is ``tot==0``, since ``di==1``

**Comment by mattip** [comment] 2017-07-10 03:56
It seems the code is trying to differentiate between a class method and a builtin-code object. There must be a better way to test that ...

**Comment by mattip** [comment] 2017-07-10 20:35
created branch pypy-f2py-callback [here](https://github.com/mattip/numpy/commit/946a883f937fa6a0d9d993c04c950bcca5a708b2), still need to run more extensive tests

**Comment by mattip** [comment] 2019-08-18 15:41
Closing. We have PyPy in CI (for linux64). Please reopen/open a new issue if there are still issues with f2py.

**Closed by mattip** 2019-08-18 15:41 UTC
