### ISSUE TITLE
Power of ndarray has another dtype of np.int32 that is unequal to np.int32

### ISSUE THREAD

**Issue by jtsuru** [numpy/numpy#10028] opened 2017-11-15 17:22 UTC
Hello,

I have trouble in comparing dtype of np.int32 array.
The power of np.int32 ndarray has dtype of np.int32 which seems different from _proper np.int32_.

Example:
```python
Jupyter QtConsole 4.3.1
Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np
In [2]: np.__version__
Out[2]: '1.13.3'

In [3]: arr1 = np.arange(10)
In [4]: arr2 = np.arange(10)**2
In [5]: arr1.dtype.type
Out[5]: numpy.int32

In [6]: arr2.dtype.type
Out[6]: numpy.int32

In [7]: arr1.dtype.type == arr2.dtype.type
Out[7]: False

In [8]: arr1.dtype.type is arr2.dtype.type
Out[8]: False

In [9]: arr2.dtype.type == np.int32
Out[9]: False
```

I am using Anaconda version of numpy 1.13.3 with Python 3.6.3 on 64 bit Windows 7.

**Comment by eric-wieser** [comment] 2017-11-15 17:39
One of these is `np.int_` (c long), the other is `np.intc` (c int), which on some platforms are the same size.

Clearly we could do a better job of distinguishing them though

**Comment by eric-wieser** [comment] 2017-12-02 06:59
Closing as a duplicate of #9799, which is the same problem.

**Closed by eric-wieser** 2017-12-02 06:59 UTC
