### ISSUE TITLE
error when using numpy

### ISSUE THREAD

**Issue by Asdf11x** [numpy/numpy#15448] opened 2020-01-27 15:54 UTC
### Reproducing code example:

```python
import numpy as np
```

### Error message:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Eigene_Programme\Anaconda\envs\torchtest\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Das angegebene Modul wurde nicht gefunden.

### Numpy/Python version information:

numpy 1.18

Using conda:
conda create -n myenv python=3.7
conda install -c anaconda numpy

**Comment by NicholasTuttle** [comment] 2020-02-05 18:28
I'm having this same issue

**Comment by NicholasTuttle** [comment] 2020-02-05 18:35
I had this same issue. Open your Anaconda Navigator and uninstall numpy. Then go to numpy and **Mark for specific version installation**. Version 1.17.4 is the one you want
![Capture](https://user-images.githubusercontent.com/42939286/73871630-2d07ee00-481c-11ea-8050-e9717e4cce82.PNG)

**Comment by UGuntupalli** [comment] 2020-06-12 17:48
I am getting the same error. I have removed my anaconda environment and changed the numpy version to 1.17.4 as recommended, but I still get the same error .

**Comment by rossbar** [comment] 2020-06-12 18:04
Please see [this document](https://numpy.org/devdocs/user/troubleshooting-importerror.html) for suggestions on what might be causing the problem and how it can be resolved. Pay particular attention to the sections on ensuring the correct environment is activated.

**Comment by UGuntupalli** [comment] 2020-06-12 18:11
@rossbar, 
    So the weird thing that I am noticing is, I am able to import pandas and numpy in the same environment if I save my code as a jupyter notebook. However the same import would fail if i try to run it in a .py file

**Comment by rossbar** [comment] 2020-06-12 18:23
I'm not sure why that would be. The following should tell you whether NumPy is installing correctly on your system via conda:

```bash
conda create -n testenv python=3.8
source activate testenv
conda install numpy
python -c 'import numpy as np'
```

**Comment by UGuntupalli** [comment] 2020-06-12 18:43
@rossbar : This worked fine. 

So, just for my understanding, specifying numpy or pandas in an environment.yml file and then creating the entire environment at once using conda is not going to work ? I still am struggling with exactly why this is failing. Here are the steps I am following: 

1. I have installed the latest version of Anaconda 
2. I have created a GitHub project with an environment.yml 
3. I do a Git Pull using VS Code of the project on to my local machine 
4. I then try to create the anaconda environment using: 
```python 
   conda env create -f environment.yml
``` 
5. Works as expected and the environment gets created. no problem 
6. I open my project in VSCode and create two files 
    a. test.py 
    b. test.ipynb 
    Both run the same code: 
    ```python 
       import pandas as pd 
       import numpy as np 

       print(pd.__version__) 
       print(np.__version__)
    ```
7. test.py gives the error mentioned in the issue, while test.ipynb fails. I have installed and removed the environments by toggling the versions of the packages for python(3.6.5 to 3.8) and numpy(1.18.1 to 1.17.4). Between each try, I made it a point to do a 
```git 
   git clean -xdf 
```

   I wonder what exactly is the issue. Any clarity is appreciated.

**Comment by rossbar** [comment] 2020-06-12 18:54
Ah, it seems like the best bet for resolving this issue is to read up on using virtual environments with VS code. We link [this article](https://code.visualstudio.com/docs/python/environments) in our troubleshooting doc - hopefully that is sufficient. If not, I would suggest perhaps searching along the lines of "activating conda environments in VS code"

**Comment by UGuntupalli** [comment] 2020-06-12 18:57
@rossbar : I am able to successfully create and activate virtual environments created using Anaconda in VS Code. The problem is only limited to numpy and why it fails to import as expected. I really don't think the problem is my inability to activate an environment. I would really appreciate focusing on why numpy installation fails when an environment is created in that fashion ?

**Comment by rossbar** [comment] 2020-06-12 19:06
Honestly I'm not sure what the specific problem is. The fact that it works in a local Jupyter kernel but not an interpreter is indeed strange. The fact that NumPy works as expected in at least a subset of the setups you are using indicates that the problem isn't necessarily with the installation of NumPy, but more likely with the setup/configuration of the environment(s). Do you get the same PATH and PYTHONPATH when you run in Jupyter vs. the terminal?

**Comment by rossbar** [comment] 2020-07-18 17:48
Possibly related: #16799 

I'm going to close this one since multiple discussions got wrapped up into one issue. If the problem persists, please open a new issue with information about the specific system and installation procedure.

**Closed by rossbar** 2020-07-18 17:48 UTC
Labels: 32 - Installation, 33 - Question

**Comment by kingsyard** [comment] 2021-05-24 15:44
to keep it simple

pip install numpy  
if then also you get the error try with some particular versions that your work may need.

like pip install numpy==0.9 like this check clearly which version of numpy you need.

if you couldnt install it then try

pip install --user numpy
second one is where you are providing permission.(granting user permission).

if you have got any other quarie you can contact us at www.smartaitechnologies.com for more
