### ISSUE TITLE
python3: numpy.search sorted fails on passing an array containing None values.

### ISSUE THREAD

**Issue by rsaim** [numpy/numpy#13513] opened 2019-05-09 09:52 UTC
Passing `a` or `v` having `None` values to `searchsorted(a, v, side='left', sorter=None)` fails in Python 3 as comparison between NoneTypes is no longer allowed.
    
### Reproducing code example:

```python
import numpy as np
np.searchsorted(np.array([1,2,3,4,5]), np.array([None, -10, 10, 2, 3]))

Python 2:
array([0, 0, 5, 1, 2])

Python 3:
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```
Same thing happens with the following:

```python
np.searchsorted(np.array([1,2,3,4,5, None]), np.array([-10, 10, 2, 3]))
```

### Error message:

```
TypeError                                 Traceback (most recent call last)
</path/to/python>python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     51     try:
---> 52         return getattr(obj, method)(*args, **kwds)
     53

TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-15-593bd68b5f1f> in <module>
----> 1 np.searchsorted(np.array([1,2,3,4,5]), np.array([None, -10, 10, 2, 3]))

</path/to/python>python3.7/site-packages/numpy/core/fromnumeric.py in searchsorted(a, v, side, sorter)
   1122
   1123     """
-> 1124     return _wrapfunc(a, 'searchsorted', v, side=side, sorter=sorter)
   1125
   1126

</path/to/python>python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     60     # a downstream library like 'pandas'.
     61     except (AttributeError, TypeError):
---> 62         return _wrapit(obj, method, *args, **kwds)
     63
     64

</path/to/python>python3.7/site-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     40     except AttributeError:
     41         wrap = None
---> 42     result = getattr(asarray(obj), method)(*args, **kwds)
     43     if wrap:
     44         if not isinstance(result, mu.ndarray):

TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

### Numpy/Python version information:

Python 2:
('1.14.3', '2.7.15  \n[GCC 7.3.1  (Red Hat 7.3.1)]')

Python 3:
1.14.3 3.7.3
[GCC 7.3.1 (Red Hat 7.3.1)]

**Comment by seberg** [comment] 2019-05-10 01:44
Honestly, that seems like the correct thing to do. If python phases out comparison (and thus sorting) of None, so will we. One could argue that the first example should be an error or warning due to casting the first input from integer to object (I am pretty sure I saw that as an issue elsewhere recently).

**Comment by rsaim** [comment] 2019-05-10 15:42
I was expecting:

1. The first case in py2 to throw a warning, or
2. Second case to throw a more explicit error in py3, or
3. Reading about it in the searchsorted doc.

**Comment by eric-wieser** [comment] 2019-05-10 15:54
I think the search_sorted docs should show how to use a key function. There's no point adding a kwargs for that though since search sorted already returns indices

**Comment by seberg** [comment] 2019-05-10 21:35
@rsaim there is a warning, but it is in python, you may have to use `python -3` to enable the python 3 warnings though.

**Comment by rsaim** [comment] 2019-05-14 08:29
FTR, I get the following informative error from numpy 1.8.2 + Python 3.4.3 [GCC 4.8.4].
 
```python                                                       
Traceback (most recent call last):                                                                                                                                         
  File "main.py", line 3, in <module>                                                                                                                                      
    np.searchsorted(np.array([1,2,3,4,5]), np.array([None, -10, 10, 2, 3]))                                                                                                
  File "/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py", line 1008, in searchsorted                                                                              
    return searchsorted(v, side, sorter)                                                                                                                                   
TypeError: unorderable types: int() > NoneType() 
```

Would it make sense to reinstate this kind of error?

I confirm that `python2 -3`  gives the following warning:
```python
>>> import numpy as np
>>> np.searchsorted(np.array([1,2,3,4,5]), np.array([None, -10, 10, 2, 3]))
/usr/local/python/python-2.7/std/lib/python2.7/site-packages/numpy/core/fromnumeric.py:52: DeprecationWarning: comparing unequal types not supported in 3.x
  return getattr(obj, method)(*args, **kwds)
array([0, 0, 5, 1, 2])
```

**Comment by bsipocz** [comment] 2022-05-21 21:57
Given that the error message has been changed to `TypeError: '<' not supported between instances of 'NoneType' and 'int'`, and the label and the discussion above that this is expected behaviour, I go ahead and close this.
Please reopen if you think there is more to-be-done here.

**Closed by bsipocz** 2022-05-21 21:57 UTC
Labels: 57 - Close?
