### ISSUE TITLE
pip install numpy 1.15 from wheel: numpy.dtype size changed Expected 96, got 88

### ISSUE THREAD

**Issue by denis-bz** [numpy/numpy#11628] opened 2018-07-27 09:55 UTC
After `pip install numpy` 1.15 from a wheel,

    print "np.dtype.__basicsize__:", np.dtype.__basicsize__  # 96
    print "scipy.dtype.__basicsize__:", scipy.dtype.__basicsize__  # 96
    from scipy import stats
    ~ 20 RuntimeWarning: numpy.dtype size   changed, may indicate binary incompatibility. Expected 96, got 88

(Please add labels, don't see them; is there a label "strange" ?)

A shell script to reproduce this:

    #!/bin/bash
    # re-install numpy scipy: https://github.com/numpy/numpy/issues/11537  denis 27july

    ( cd $site;  rm -r tmp;  mkdir tmp;  mv numpy* scipy* tmp )
    rm -r ~/Library/Caches/pip

    #...............................................................................
    pip2 install --user numpy scipy

    python2 -c '
    import sys
    import numpy as np
    import scipy

    print "versions: numpy %s  scipy %s  python %s  " % (
    		np.__version__, scipy.__version__ , sys.version )
    print "np.dtype.__basicsize__:", np.dtype.__basicsize__
    print "scipy.dtype.__basicsize__:", scipy.dtype.__basicsize__

    from scipy import stats
    '

    pip2 --version
    ls -l $site/scipy/*/*cython*.so
    otool -L $site/scipy/*/*cython*.so  # mac

and the logfile:

    Collecting numpy
      Downloading https://files.pythonhosted.org/packages/3c/bf/e36756c562f7386be78c6942f0a8a647ee4eb374cdf219bece7054832b14/numpy-1.15.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.5MB)
    Collecting scipy
      Downloading https://files.pythonhosted.org/packages/d1/d6/3eac96ffcf7cbeb37ed72982cf3fdd3138472cb04ab32cdce1f444d765f2/scipy-1.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.8MB)
    Installing collected packages: numpy, scipy
      The scripts conv-template, f2py and from-template are installed in '/Users/bz/Library/Python/2.7/bin' which is not on PATH.
      Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Successfully installed numpy-1.15.0 scipy-1.1.0
    versions: numpy 1.15.0  scipy 1.1.0  python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]  
    np.dtype.__basicsize__: 96
    scipy.dtype.__basicsize__: 96
    /Library/Python/2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._ufuncs import *
    /Library/Python/2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._solve_toeplitz import levinson
    /Library/Python/2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._decomp_update import *
    /Library/Python/2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
    /Library/Python/2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from . import _bspl
    /Library/Python/2.7/site-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from . import _csparsetools
    /Library/Python/2.7/site-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
    /Library/Python/2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._tools import csgraph_to_dense, csgraph_from_dense,\
    /Library/Python/2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._traversal import breadth_first_order, depth_first_order, \
    /Library/Python/2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._min_spanning_tree import minimum_spanning_tree
    /Library/Python/2.7/site-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
    /Library/Python/2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from .ckdtree import *
    /Library/Python/2.7/site-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from .qhull import *
    /Library/Python/2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from . import _voronoi
    /Library/Python/2.7/site-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from . import _hausdorff
    /Library/Python/2.7/site-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._trlib import TRLIBQuadraticSubproblem
    /Library/Python/2.7/site-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from ._group_columns import group_dense, group_sparse
    /Library/Python/2.7/site-packages/scipy/stats/_continuous_distns.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
      from . import _stats
    pip 18.0 from /Library/Python/2.7/site-packages/pip (python 2.7)
    -rwxr-xr-x 1 bz admin  306652 Jul 27 11:34 /Library/Python/2.7/site-packages/scipy/linalg/cython_blas.so
    -rwxr-xr-x 1 bz admin  817100 Jul 27 11:34 /Library/Python/2.7/site-packages/scipy/linalg/cython_lapack.so
    -rwxr-xr-x 1 bz admin 2738116 Jul 27 11:34 /Library/Python/2.7/site-packages/scipy/special/cython_special.so
    /Library/Python/2.7/site-packages/scipy/linalg/cython_blas.so:
    	@loader_path/../.dylibs/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
    	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
    	@loader_path/../.dylibs/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    	@loader_path/../.dylibs/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /Library/Python/2.7/site-packages/scipy/linalg/cython_lapack.so:
    	@loader_path/../.dylibs/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
    	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
    	@loader_path/../.dylibs/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    	@loader_path/../.dylibs/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /Library/Python/2.7/site-packages/scipy/special/cython_special.so:
    	@loader_path/../.dylibs/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
    	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
    	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
    	@loader_path/../.dylibs/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    	@loader_path/../.dylibs/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)

**Comment by earwig** [comment] 2018-07-28 02:33
Experiencing this too. The warnings themselves should be benign ([see this SO post](https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility)) but are annoying nonetheless. numpy previously silenced them in \_\_init__.py, but the code to do so was removed in cf46d8cd2aa809be44b684ba234880e0aa4befe9 and I'm not sure why. Perhaps it was a mistake? The relevant issue is #10842, which disabled the warnings elsewhere in tests, but I must be missing something, because tests are not the only place those warnings would have shown up.

**Comment by charris** [comment] 2018-07-28 17:46
I'm not sure the warning is benign, the dtype size hasn't changed in years. I'd like to know where scipy came from.

**Comment by charris** [comment] 2018-07-28 18:33
OK, looking at this more, I think this *is* harmless and we should filter the error. Currently it is only filtered for testing.

**Comment by denis-bz** [comment] 2018-07-29 16:44
Sure, filter. But where's the size 88 in numpy 1.15 coming from --
what changed, if not numpy.dtype: the wheel build chain, .dylibs ?

    #!/bin/bash
    # https://github.com/numpy/numpy/issues/11628
    # scipy 1.1.0, numpy 1.14.5: no warning
    # scipy 1.1.0, numpy 1.15.0: RuntimeWarning: numpy.dtype size changed Expected 96, got 88
    
    set -v

    PYTHONPATH=/Library/Python/2.7/site-packages \
    PYTHONSTARTUP="" \
    \
    python2 -c '
    import numpy
    print "numpy", numpy.__version__, numpy.__path__

    import scipy
    print "scipy", scipy.__version__, scipy.__path__

    from scipy.linalg import solve_toeplitz  # 2 RuntimeWarnings
    '

**Comment by charris** [comment] 2018-07-29 17:00
How did you install SciPy and NumPy in all those different cases?

**Comment by earwig** [comment] 2018-07-29 20:38
I can easily reproduce this by installing the binary wheels for macOS or linux from pypi inside a virtualenv. Runtime warnings occur with scipy-1.1.0 and numpy-1.15.0, but not with numpy-1.14.5. See log for macOS: https://gist.github.com/earwig/8d316e6b053ce9e90d3dbdd7c4a0da70.

Now, I'm afraid we may be talking past each other... I do not believe there was any change in numpy to cause this __other than__ the removal of the `warnings.filterwarnings` calls in \_\_init__.py in cf46d8cd2aa809be44b684ba234880e0aa4befe9, as I previously mentioned, which is included in 1.15.0 but not 1.14.5. scipy targets numpy-1.8.2 when it builds its binary wheels, and appears to have done so for a long time. In numpy-1.8.2, the `numpy.dtype` structure _was_ different (8 bytes smaller, apparently due to the addition of the `hash` field in cca2c1a4fecfa5533b5579204c5f28a12c5b078a as part of numpy-1.10.0), but not in an incompatible way.

Thank you.

**Comment by rgommers** [comment] 2018-07-31 05:44
> Now, I'm afraid we may be talking past each other... I do not believe there was any change in numpy to cause this other than the removal of the warnings.filterwarnings calls in __init__.py in cf46d8c, as I previously mentioned, which is included in 1.15.0 but not 1.14.5

Yes I think this is right. We'll need an 1.15.1 with this fix included. PR is gh-11634, I think it should be merged.

**Comment by charris** [comment] 2018-07-31 17:08
Closed by #11634.

**Closed by charris** 2018-07-31 17:08 UTC
Labels: 05 - Regression

**Comment by yagamiash** [comment] 2018-08-03 21:30
I have no issue with scipy 1.1.0 & numpy 1.14.5

**Comment by rainwoodman** [comment] 2018-08-04 00:03
I thought somehow 1.15 changed the size of dtype. Why is cython not fixed if this warning is a false positive?

**Comment by charris** [comment] 2018-08-04 00:28
The size has changed, it is not a problem, but cython warns.

**Comment by fonnesbeck** [comment] 2018-08-10 01:50
This occurs when installed via conda as well.

**Comment by chilambarasan91** [comment] 2018-08-10 07:06
Getting similar RuntimeWarning while installing the pandas module. PFB warning messages.

will numpy 1.15.1 will fix this issue.?
```
D:\Python27\lib\site-packages\pandas\_libs\__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
D:\Python27\lib\site-packages\pandas\__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import (hashtable as _hashtable,
D:\Python27\lib\site-packages\pandas\core\dtypes\common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos, lib
D:\Python27\lib\site-packages\pandas\core\util\hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import hashing, tslib
D:\Python27\lib\site-packages\pandas\core\indexes\base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import (lib, index as libindex, tslib as libts,
D:\Python27\lib\site-packages\pandas\tseries\offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.tslibs.offsets as liboffsets
D:\Python27\lib\site-packages\pandas\core\ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos as libalgos, ops as libops
D:\Python27\lib\site-packages\pandas\core\indexes\interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs.interval import (
D:\Python27\lib\site-packages\pandas\core\internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import internals as libinternals
D:\Python27\lib\site-packages\pandas\core\sparse\array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.sparse as splib
D:\Python27\lib\site-packages\pandas\core\window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.window as _window
D:\Python27\lib\site-packages\pandas\core\groupby\groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import (lib, reduction,
D:\Python27\lib\site-packages\pandas\core\reshape\reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos as _algos, reshape as _reshape
D:\Python27\lib\site-packages\pandas\io\parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  import pandas._libs.parsers as parsers
D:\Python27\lib\site-packages\pandas\io\pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected zd, got zd
  from pandas._libs import algos, lib, writers as libwriters
```

**Comment by mattip** [comment] 2018-08-10 15:50
Yes, 1.15.1 will mask those harmless warnings

**Comment by Tehsurfer** [comment] 2018-08-15 03:40
I'm getting this warning when using numpy with flask and even though it does appear to be 'harmless' I believe it is the culprit suppressing all of my server's debugging output and print statements which is not the nicest development environment.

(in ubuntu linux on AWS)

`$ sudo python2 server.py
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/ubuntu/.local/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
WARNING:werkzeug: * Debugger is active!
`

**Comment by alexiswl** [comment] 2018-08-20 04:54
For now, rolling back to numpy 1.14.5 through conda, will resolve this
`  conda install numpy==1.14.5 --yes`

**Comment by odbarragan** [comment] 2019-04-18 07:05
As of now, I tried rolling back numpy to 1.14.5 and all other versions but none worked but upgrading to 1.16.1 finally fixed it!

**Comment by odbarragan** [comment] 2019-04-18 07:06
pip install numpy==1.16.1
