### ISSUE TITLE
New(?) test fails in 1.19

### ISSUE THREAD

**Issue by mboisson** [numpy/numpy#16954] opened 2020-07-27 13:39 UTC
We are building a Numpy python wheel from source, and binding it to a version of MKL that is installed on our cluster. Since Numpy 1.19, a single test fails when running `numpy.test()` : 

```
>           assert info.get_lib_dirs() == lib_dirs
E           AssertionError: assert ['/cvmfs/soft.../lib/intel64'] == ['/tmp/tmpwmv.../tmprf9ssim6']
E             At index 0 diff: '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/2019.2.187/mkl/lib/intel64' != '/tmp/tmpwmvc9p10'
E             Right contains one more item: '/tmp/tmprf9ssim6'
E             Full diff:
E             - ['/tmp/tmpwmvc9p10', '/tmp/tmprf9ssim6']
E             + ['/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/2019.2.187/mkl/lib/intel64']
``` 

Now, obviously, the path returned by `info.get_lib_dirs()` is the correct one, it should not find libraries in `/tmp/...`. 

Why is this test failing ?

Note that 10895 other tests pass correctly.

**Comment by charris** [comment] 2020-07-27 14:03
Yes, it is a new test. This is a duplicate of #16769, so closing. A fix from users of MKL would be most appreciated.

**Closed by charris** 2020-07-27 14:03 UTC
