### ISSUE TITLE
Just Installed Anaconda 3 on windows 10 and it fails to import  numpy or matplotlib. 

### ISSUE THREAD

**Issue by Maryamak66** [numpy/numpy#13009] opened 2019-02-21 21:11 UTC
I do see the numpy package among site packages under lib directory! But it fails to import numpy. Here is the error I get when I try to import numpy on anaconda3: 

Traceback (most recent call last):

  File "<ipython-input-1-0484cd13f94d>", line 1, in <module>
    import matplotlib

  File "C:\Users\Maryam\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py", line 141, in <module>
    from . import cbook, rcsetup

  File "C:\Users\Maryam\AppData\Roaming\Python\Python37\site-packages\matplotlib\cbook\__init__.py", line 33, in <module>
    import numpy as np

  File "C:\Users\Maryam\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core

  File "C:\Users\Maryam\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Users\Maryam\Anaconda3\pythonw.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by mattip** [comment] 2019-02-22 07:40
Maybe a duplicate of #12957. If you are running a brand-new Anaconda, they broke updating numpy using pip. You can tell because there will be a DLL file in `C:\Users\Maryam\AppData\Roaming\Python\Python37\site-packages\numpy\.lib`. If so you can "fix" it by adding that path to the system PATH before running python

```
rem This fails
python -c "import numpy"

rem Does this succeed ??? 
PATH=C:\Users\Maryam\AppData\Roaming\Python\Python37\site-packages\numpy\.lib;%PATH%
python -c "import numpy"
```
If not, we will need to know how you installed your software stack.

**Comment by rgommers** [comment] 2019-02-22 15:27
> If so you can "fix" it by adding that path to the system PATH before running python

A healthier fix would be to install `numpy` with `conda` instead of with `pip` (that is *never* a good idea to start with). Run
```
pip uninstall numpy
conda install numpy
```

**Comment by mattip** [comment] 2019-03-06 07:30
Closing. Anaconda seems to have fixed the issue that caused this.

**Closed by mattip** 2019-03-06 07:30 UTC
Labels: 29 - Intel/Anaconda
