### ISSUE TITLE
Inconsistent behavior of broadcast_to with numpy types

### ISSUE THREAD

**Issue by rdturnermtl** [numpy/numpy#12853] opened 2019-01-25 23:12 UTC
The behavior of `np.broadcast_to` is inconsistent when given a scalar numpy type variable.

If we want to construct an array of type variables (this will be an ndarray of dtype object) using `broadcast_to`, it works when given a length 1 list of dtypes.  It also works with a single Python native type or a numpy `dtype` object.  However when we pass a single numpy type variable it gives a strange error message.

### Reproducing code example:

```python
>>> import numpy as np
>>> np.broadcast_to([int], (5,))  # works
array([<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>], dtype=object)
>>> np.broadcast_to(int, (5,))  # works
array([<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>,
       <class 'int'>], dtype=object)
>>> np.broadcast_to([np.dtype('int32')], (5,))  # works
array([dtype('int32'), dtype('int32'), dtype('int32'), dtype('int32'),
       dtype('int32')], dtype=object)
>>> np.broadcast_to(np.dtype('int32'), (5,))  # works
array([dtype('int32'), dtype('int32'), dtype('int32'), dtype('int32'),
       dtype('int32')], dtype=object)
>>> np.broadcast_to([np.int32], (5,))  # works
array([<class 'numpy.int32'>, <class 'numpy.int32'>,
       <class 'numpy.int32'>, <class 'numpy.int32'>,
       <class 'numpy.int32'>], dtype=object)
>>> np.broadcast_to(np.int32, (5,))  # doesn't work
```

### Error message:

```
ValueError: invalid __array_struct__
```

Full error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/numpy_latest/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/numpy_latest/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 118, in _broadcast_to
    array = np.array(array, copy=False, subok=subok)
ValueError: invalid __array_struct__
```

### Numpy/Python version information:

```
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.16.0 3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]
```

**Comment by eric-wieser** [comment] 2019-01-26 01:58
Same root cause as #8877, closing this one to keep discussion there.

**Closed by eric-wieser** 2019-01-26 01:58 UTC
