### ISSUE TITLE
np.sqrt.types is weird

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#6255] opened 2015-08-27 11:14 UTC
There are duplicated entries, and also `e->e` comes after `f->f`, which probably means there'll always be a conversion to float32.

```
>>> np.sqrt.types
['f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']
```

**Comment by eric-wieser** [comment] 2017-04-05 09:29
Duplicate of #7897

**Closed by eric-wieser** 2017-04-05 09:29 UTC
Labels: 11 - Bug, component: numpy.core
