### ISSUE TITLE
Buggy Accelerate Backend when using numpy 1.19

### ISSUE THREAD

**Issue by billlyzhaoyh** [numpy/numpy#15947] opened 2020-04-09 17:27 UTC
Numpy 1.19 cannot import due to run time error in MacOS 10.14.6. Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.

### Reproducing code example:

```python
import numpy as np
```

### Error message:
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

Traceback (most recent call last):
  File "/Users/billyzhaoyh/anaconda/envs/simulation/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/billyzhaoyh/anaconda/envs/simulation/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/billyzhaoyh/Desktop/Simulation/reina-model/calc/__init__.py", line 1, in <module>
    from .utils import calcfunc
  File "/Users/billyzhaoyh/Desktop/Simulation/reina-model/calc/utils.py", line 9, in <module>
    from utils.quilt import load_datasets
  File "/Users/billyzhaoyh/Desktop/Simulation/reina-model/utils/quilt.py", line 4, in <module>
    import quilt
  File "/Users/billyzhaoyh/anaconda/envs/simulation/lib/python3.7/site-packages/quilt/__init__.py", line 87, in <module>
    from .tools.command import (
  File "/Users/billyzhaoyh/anaconda/envs/simulation/lib/python3.7/site-packages/quilt/tools/command.py", line 24, in <module>
    import numpy as np
  File "/Users/billyzhaoyh/Desktop/Simulation/reina-model/src/numpy/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

### Numpy/Python version information:

Python 3.7.6
Numpy -e git+https://github.com/numpy/numpy.git@078ac01a85c4db46e7f148829c2e0d0e0f30c36f#egg=numpy

**Comment by mattip** [comment] 2020-04-09 17:43
This is by design. Did you read the error message? Is it unclear?

**Comment by billlyzhaoyh** [comment] 2020-04-10 15:08
so how can I fix this error, by updating the Accelerate backend? I had a search and don't think I can update that for my MacOS.

**Comment by vrakesh** [comment] 2020-04-11 02:44
@billlyzhaoyh Requesting to use OpenBLAS while building on MacOS instead. Use site.cfg in the root repo directory to build using the same.

**Comment by mattip** [comment] 2020-05-20 18:47
Closing. We strongly recommend not using Accelerate.

**Closed by mattip** 2020-05-20 18:47 UTC

**Comment by xbeta** [comment] 2020-08-14 20:59
> Closing. We strongly recommend not using Accelerate.

Sure, how do we **not** use it?  I got the same error when just run simple `import numpy` in my macOS

**Comment by mattip** [comment] 2020-08-15 20:46
If you are building your own NumPy, get OpenBlas. You can use `python3 tools/openblas_support.py` to download the one used to build the official wheel. If you are using a provider's NumPy, ask them why they are using Accelerate.

**Comment by xbeta** [comment] 2020-08-15 23:01
> If you are building your own NumPy, get OpenBlas. You can use `python3 tools/openblas_support.py` to download the one used to build the official wheel. If you are using a provider's NumPy, ask them why they are using Accelerate.

I am definitely not building on my own.  I am using macOS, and run `pip3 install -U numpy` , so I am not sure what "provider" do you mean by that .

**Comment by mattip** [comment] 2020-08-16 06:36
Pip can build from source behind your back. If it takes more than a few seconds to install, it may be compiling. To force pip to only use binary wheels and never compile, use
```
pip3 install --upgrade --only-binary :all: <package>
```

Can you try to uninstall your numpy and install with the `--only-binary :all:` argument?

**Comment by slw07g** [comment] 2020-08-29 23:57
This fixed the problem for me. (I replaced `pip` with `pip3`)

**Comment by glyph** [comment] 2020-09-03 00:36
A slightly simpler solution:

```console
$ rm -v ~/Library/Caches/pip/wheels/*/*/*/*/*numpy* # clear the pip wheel cache of any built numpy wheels
$ brew install openblas # make sure OpenBLAS is installed
$ # activate your pypy3 virtualenv
$ OPENBLAS="$(brew --prefix openblas)" pip install numpy # let numpy's setup.py know where OpenBLAS is installed
```

This has the added benefit that the wheel will not need to be rebuilt, and any future `pip install numpy`'s on pypy3 will work.

**Comment by glyph** [comment] 2020-09-03 00:47
Workarounds aside though, why is the *default* build behavior to produce a broken wheel that can't even `import`?  It seems like it being "by design" to build such a broken artifact is a bug either way; a self-test at the end of the build that aborts if it finds itself in this state would be a welcome addition.  (Especially if it could provide a helpful error message like "try `brew install openblas`" or somesuch.)

**Comment by xrisk** [comment] 2020-10-07 10:39
Why not simply refuse to build on macOS if openblas is not found?

**Comment by mattip** [comment] 2020-10-07 12:14
There are various valid blas backends, besides OpenBLAS. The only invalid one is Accelerate. Unfortunately, macOS does not provide a way to tell us that they are providing Accelerate, we can only detect it at runtime by triggering a known bad calculation. If you can figure out how to detect Accelerate earlier that would be great. The best we had so far is to detect a symlink, but that is very fragile.

**Comment by mikkelam** [comment] 2020-10-08 09:22
If any python-poetry users come across this thread, I would just like to add that @glyph's solution works as well if you just replace the last line with `OPENBLAS="$(brew --prefix openblas)" poetry add numpy `

**Comment by stephenyang21** [comment] 2020-10-15 18:37
I've tried a previous version of numpy  and it worked  for me
pip3  install numpy==1.18.0

Hope this help

**Comment by SteveG34** [comment] 2020-10-20 00:37
uninstall and install 1.18.0 -- worked for me! kuddos to the above ^^

**Comment by fny** [comment] 2020-10-21 18:36
I'm here to report that the suggestion to use openblas doesn't work. This crashes:

```
OPENBLAS="$(brew --prefix openblas)" pip install numpy
python -c 'import numpy'

# =>  RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
```

while this works without any issues:

```
pip install numpy==1.18.0
python -c 'import numpy'
```

**Comment by xrisk** [comment] 2020-10-21 18:38
@fny check the output to see if pip is using a cached wheel. You might have to clear the cache in that case.

**Comment by glyph** [comment] 2020-10-21 23:43
@fny see https://github.com/numpy/numpy/issues/15947#issuecomment-686159427 for updated instructions

**Comment by meownoid** [comment] 2020-10-26 21:01
Can anyone provide a link where one can read about why Accelerate is a bad BLAS implementation which should not be used? I tried googling "why apple accelerate is a bad blas" and found nothing.

**Comment by charris** [comment] 2020-10-26 23:22
I don't know where a comprehensive breakdown is, but Accelerate has threading problems, some wrong results, and exposes an outdated version of LAPACK.

**Comment by orome** [comment] 2020-10-28 19:21
For reference [this solution](https://github.com/numpy/numpy/issues/15947#issuecomment-686159427) fails. Why isn't this working? And why is any of this even necessary?

**Comment by mattip** [comment] 2020-10-28 19:58
@orome as for "why" ask Apple. They are the ones you bought the system from and are shipping buggy software that the mostly volunteer team of NumPy has to work around. Any anger should should be directed at them, not at us.

**Comment by orome** [comment] 2020-10-28 20:00
> @orome as for "why" ask Apple ... Any anger should should be directed at them, not at us.
That's definitely where it's directed (again)!

**Comment by erithacus-rubecula-z** [comment] 2020-11-04 14:29
> This fixed the problem for me. (I replaced `pip` with `pip3` ... and the numpy version as of today will be 1.19.1)
> https://gist.github.com/yatsu/47bdde35e8abbe7d14bbe730342aa9e0#file-numpy-openblas-macos-pip-sh
> 
> EDIT: Pasting complete solution in case gist gets deleted :)
> 
> ```
> # Setup HomeBrew if not already installed: https://brew.sh/
> brew install openblas
> mkdir /tmp/numpy_local
> cd /tmp/numpy_local
> pip3 download --no-binary :all: --no-deps numpy
> unzip numpy-*.zip  # (assuming there's only one version in this folder)
> cd numpy-1.19.1 # the version may be a later version than this
> 
> cat > site.cfg <<EOF
> [openblas]
> libraries = openblas
> library_dirs = $(brew --prefix openblas)/lib
> include_dirs = $(brew --prefix openblas)/include
> runtime_library_dirs = $(brew --prefix openblas)/lib
> EOF
> 
> pip3 install .
> # cleanup
> cd /tmp
> rm -rf numpy_local
> ```

This somehow didn't work for me. I compiled OpenBLAS from source and installed it in `/opt/OpenBLAS`, and replaced every occurrence of `$(brew --prefix openblas)` with `/opt/OpenBLAS`. My Python 3 installation is from the Xcode command line tools, so I used `pip3 install --user .` instead of `pip3 install .`. Apart from that I followed the script exactly. However, after I run `python3 -c "import numpy"`, the error message is exactly as before:

> RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

Any ideas why this might have happened?

**Comment by MarioCatuogno** [comment] 2020-11-16 00:12
```python
pip install pandas
pip3 install pandas
pip3 install pandas --no-build-isolation --no-cache-dir
sudo pip3 install pandas --no-cache-dir
```

#### Problem description

I've done a clean installation of macOS Big Sur and a clean install of Python3.9 via Homebrew (`brew install python3`). After that I installed pip3 with `brew install pip` command and I wanted to install Pandas but I'm always getting the following error. I've tried with all the commands listed above to install Pandas on macOS Big Sur and Python3...

Anyone can help? These are the only packages actually installed:

Package    Version
---------- -------
pip        20.2.4
setuptools 50.3.2
wheel      0.35.1

#### Expected Output

#### Output of ``pip install pandas``

<details>

  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/tmpzr3sthd6
       cwd: /private/var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/pip-install-pvlaq6iq/pandas
  Complete output (23 lines):
  init_dgelsd failed init
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/pip-build-env-ly4c8n5_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/pip-build-env-ly4c8n5_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/pip-build-env-ly4c8n5_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/pip-build-env-ly4c8n5_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 488, in <module>
      import numpy as np
    File "/private/var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/pip-build-env-ly4c8n5_/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
      raise RuntimeError(msg)
  RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
  RankWarning: Polyfit may be poorly conditioned

  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/zv/0q58rjv549bd4qjdqlrwlvl40000gn/T/tmpzr3sthd6 Check the logs for full command output.

</details>

In this issue [Pandas#37880](https://github.com/pandas-dev/pandas/issues/37880) they say that it's a numpy problem with the latest version of macOS. Any help??

Thanks in advance!

**Comment by fuzunspm** [comment] 2020-11-16 15:16
same issue with same error

**Comment by avideci** [comment] 2020-11-16 15:19
This worked for me on MacOS 11.0.1 Big Sur, `Python 3.8.2`:

```shell
pip3 install --force-reinstall numpy\<1.19
pip3 install --upgrade wheel

brew install libjpeg # optional
brew install pillow # optional
pip3 install matplotlib

....

Successfully installed matplotlib-3.3.3 
```

**Comment by mattip** [comment] 2020-11-16 16:14
This issue is closed. If you are using MacOS 11 with a python you installed from HomeBrew, as of Nov 2020 you should use `brew install NumPy` not `pip install numpy`. Please do not comment here, open a new issue if a careful reading of gh-17784 does not help you figure out what is going on.

**Comment by mohammadnassiri** [comment] 2020-11-17 11:41
These steps helped me to resolve the issue:
https://gist.github.com/mohammadnassiri/31ca8f4f2298d8694a8327814631455c

**Comment by pacuna** [comment] 2020-11-26 17:22
If anyone is using MacPorts, this solved the issue for me:

```
port install openblas
OPENBLAS="$(port contents openblas)" pip install numpy 
```

**Comment by lethefrost** [comment] 2020-11-27 06:52
Same. I found that python3.9/3.8 installed by brew cannot import packages installed by pip/pip3 anymore in macOS Big Sur. I still don't understand what's going wrong here.
One possible solution is to use the python interpreter from its official website. Another solution is to use anaconda. The packages and python interpreter for anaconda are integrated and works well in macOS Big Sur.

**Comment by fuzunspm** [comment] 2020-11-27 06:55
> Same. I found that python3.9/3.8 installed by brew cannot import packages installed by pip/pip3 anymore in macOS Big Sur. I still don't understand what's going wrong here.

as @stephenyang21 suggested try with `pip3 install numpy==1.18.0`

**Comment by mattip** [comment] 2020-11-27 07:16
Using an old version of NumPy is not a good idea: it will use the buggy Accelerate library later versions noisily complain about.
What does this print out?
```
brew install openblas
brew --prefix openblas
```

**Comment by fuzunspm** [comment] 2020-11-27 07:41
```
╰─$ brew --prefix openblas
/usr/local/opt/openblas
```

**Comment by mattip** [comment] 2020-11-27 07:47
and if you this, numpy still does not import properly?
```
OPENBLAS="$(brew --prefix openblas)" pip install numpy==1.19.4
```

**Comment by fuzunspm** [comment] 2020-11-27 07:51
no it won't, still same error output Polyfit

**Comment by mattip** [comment] 2020-11-27 08:02
do you have `DYLD_LIBRARY_PATH` or `LD_LIBRARY_PATH` set in your shell? What does 
```
otool -l $(python -c"import numpy; print(numpy.core._multiarray_umath.__file__)")
```
show for blas?

**Comment by fuzunspm** [comment] 2020-11-27 08:07
```
/Users/username/.virtualenvs/venv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           8    14       1976 0x00800085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x000000000037c000
  fileoff 0
 filesize 3653632
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000001230
      size 0x00000000003354f0
    offset 4656
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x0000000000336720
      size 0x0000000000000a74
    offset 3368736
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x0000000000337194
      size 0x000000000000117e
    offset 3371412
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x0000000000338320
      size 0x000000000000b59a
    offset 3375904
     align 2^5 (32)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000003438ba
      size 0x00000000000356bc
    offset 3422394
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x0000000000378f78
      size 0x00000000000028c0
    offset 3641208
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x000000000037b838
      size 0x00000000000007b8
    offset 3651640
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __DATA_CONST
   vmaddr 0x000000000037c000
   vmsize 0x0000000000004000
  fileoff 3653632
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 3
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x000000000037c000
      size 0x0000000000000240
    offset 3653632
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 446 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA_CONST
      addr 0x000000000037c240
      size 0x0000000000000018
    offset 3654208
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x000000000037c260
      size 0x00000000000018e8
    offset 3654240
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 552
  segname __DATA
   vmaddr 0x0000000000380000
   vmsize 0x0000000000034000
  fileoff 3670016
 filesize 81920
  maxprot 0x00000003
 initprot 0x00000003
   nsects 6
    flags 0x0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x0000000000380000
      size 0x0000000000000df0
    offset 3670016
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 518 (index into indirect symbol table)
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x0000000000380df0
      size 0x0000000000011100
    offset 3673584
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __thread_vars
   segname __DATA
      addr 0x0000000000391ef0
      size 0x0000000000000030
    offset 3743472
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000013
 reserved1 0
 reserved2 0
Section
  sectname __thread_bss
   segname __DATA
      addr 0x0000000000391f20
      size 0x00000000000000a4
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000012
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x0000000000391fd0
      size 0x000000000001fce8
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x00000000003b1cc0
      size 0x0000000000000b14
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000000003b4000
   vmsize 0x00000000000e0000
  fileoff 3751936
 filesize 907784
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 3751936
    rebase_size 1896
       bind_off 3753832
      bind_size 1488
  weak_bind_off 0
 weak_bind_size 0
  lazy_bind_off 3755320
 lazy_bind_size 9336
     export_off 3764656
    export_size 7440
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 3784800
   nsyms 33503
  stroff 4324704
 strsize 335016
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 32527
     iextdefsym 32527
     nextdefsym 467
      iundefsym 32994
      nundefsym 509
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 4320848
  nindirectsyms 964
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid 82BCDF6B-EC7C-3E0E-9181-514C0D4F76F6
Load command 8
       cmd LC_BUILD_VERSION
   cmdsize 32
  platform 1
       sdk 11.0
     minos 11.0
    ntools 1
      tool 3
   version 609.7
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (offset 24)
   time stamp 2 Thu Jan  1 02:00:02 1970
      current version 4.0.0
compatibility version 1.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 02:00:02 1970
      current version 1292.0.0
compatibility version 1.0.0
Load command 12
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 3772096
 datasize 11072
Load command 13
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 3783168
 datasize 1632
```

**Comment by mattip** [comment] 2020-11-27 08:14
Sorry, I guess I meant `otool -L ...`. Anyway, it shows what the problem is: `/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate` should not be there, you should be loading something in `/usr/local/opt/openblas`. Maybe some other macOSx people can suggest how that is supposed to work, I don't use macOSx

**Comment by YiLingPredator** [comment] 2020-11-28 17:04
> I've tried a previous version of numpy and it worked for me
> pip3 install numpy==1.18.0
> 
> Hope this help

Using the older version works for me!

**Comment by mattip** [comment] 2020-11-28 17:52
@YiLingPredator if you use a buggy Accelerate backend, you may not notice until either you get wrong results or errors. This is not recommended.

**Comment by sutao** [comment] 2020-12-03 02:50
For anyone that is encountering this issue, upgrading pip, setuptools and wheel worked for me.

```sh
$ python3 -m pip install --upgrade pip setuptools wheel
```

I am using:
- macOS Big Sur 11.0.1
- Python 3.8.2
- numpy 1.18.5

Hope this helps.

**Comment by ZSSsongshu** [comment] 2020-12-07 07:36
Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend

# 先安装 OpenBLAS
$ brew install openblas
# 然后指定 OpenBLAS 作为 BLAS 提供方, 安装 Numpy 和 pandas
$ OPENBLAS="$(brew --prefix openblas)" pip3 install numpy pandas

**Comment by ZSSsongshu** [comment] 2020-12-07 07:38
1.先安装 OpenBLAS
$ brew install openblas
2. 然后指定 OpenBLAS 作为 BLAS 提供方, 安装 Numpy 和 pandas
$ OPENBLAS="$(brew --prefix openblas)" pip3 install numpy pandas

**Comment by hdsheena** [comment] 2020-12-15 17:03
$ python3 -m pip install --upgrade pip setuptools wheel
followed by 
$ python3 -m pip install --force-reinstall numpy
Works for me on big sur! Thanks!

**Comment by poke1024** [comment] 2021-03-21 16:11
Same here. Strange this is that this seems like a random condition. On some interpreter starts it works, on some it doesn't. :-(

```
macOS 10.15.7 
python 3.8.5
numpy 1.20.1
```

Downgrading to `numpy-1.18.0` works.
