### ISSUE TITLE
Strange and inconsistent type conversion in addition between np.int64 and int

### ISSUE THREAD

**Issue by sanderland** [numpy/numpy#25497] opened 2023-12-26 11:05 UTC
### Describe the issue:

The addition of a np.int64 and certain ints can result in a np.float64, whereas smaller values result in np.int64 and larger values result in an int. This breaks code which expects integers to stay integers, which broke Fraction.

## TL;DR
```python
for p in range(16,22):
    x = int(10**p)
    r = np.int64(1) + x
    print(f"{p}: {type(r)}\t\t{r}")
```

```text
16: <class 'numpy.int64'>		10000000000000001
17: <class 'numpy.int64'>		100000000000000001
18: <class 'numpy.int64'>		1000000000000000001
19: <class 'numpy.float64'>		1e+19
20: <class 'int'>		100000000000000000001
21: <class 'int'>		1000000000000000000001
```

## Detailed examples

NB all `int()` are obviously redundant, but helped me keep track of what is what.

The original code read integer into a np.ndarray, used that to construct Fraction objects and solve some linear equations exactly. During this a TypeError was raised which I traced back to this:
```
a = Fraction(np.int64(1), int(78961))
b = int(203234597957945)
a+b
```
results in: TypeError: both arguments should be Rational instances. A workaround at the time was to initialize the np.array with dtype object, avoiding the implicit int64 conversion.

Tracking down what happens in Fraction: `Fraction(a.numerator * db + b.numerator * da, da * db)`
and reproducing this leads to the following curious case:
```python
np.int64(1) + int(16047607089357295145)
```
1.6047607089357296e+19

Which is indeed not a rational. Further digging led to the example in the previous section.

### Reproduce the code example:

```python
for p in range(16,22):
    x = int(10**p)
    r = np.int64(1) + x
    print(f"{p}: {type(r)}\t\t{r}")
```

### Error message:

```shell
n/a
```

### Python and NumPy Versions:

1.24.4
3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]

1.23.4
3.9.6 (default, Nov 10 2023, 13:38:27) 
[Clang 15.0.0 (clang-1500.1.0.2.5)]

### Context for the issue:

Led to extremely bizarre exceptions in core python libraries which clearly do not expect conversion of Rational to non-Rational types.

**Comment by jakevdp** [comment] 2023-12-26 14:03
Hi - this is working as expected. It is the interplay of two corner-cases in NumPy's semantics. First, NumPy casts Python integers to either `int64` or `uint64` depending on their value:
```python
>>> np.array(2 ** 63 - 1).dtype
dtype('int64')
>>> np.array(2 ** 63).dtype
dtype('uint64')
```
This happens because `2 ** 63 - 1` is the largest representable `int64` value.

Second, type promotion between `int64` and `uint64` results in `float64`:
```python
>>> x = np.int64(1) + np.uint64(1)
>>> x.dtype
dtype('float64')
```
This happens because neither `int64` nor `uint64` can represent the full range of the other type's value, and so promotion casts to a type that can safely represent both.

The result of these two corner cases interacting is the behavior you're seeing: surprising perhaps, but it's working as intended. However I'll note that both of these behaviors are somewhat controversial, and if you dig through the issue tracker and the mailing list, you'll find numerous discussions of potential alternatives.

**Comment by sanderland** [comment] 2023-12-26 15:20
Thanks for the detailed explanation @jakevdp !
Is it correct then that the following is not required in Python?
isinstance(a,Rational) and isinstance(b,Rational) => isinstance(a+b,Rational)
and that therefore the implementers of `Fraction` are incorrect in (apparently) assuming this?

**Comment by jakevdp** [comment] 2023-12-26 17:26
> Is it correct then that the following is not required in Python?
> isinstance(a,Rational) and isinstance(b,Rational) => isinstance(a+b,Rational)

No, this is not required in Python. any type that derives from `int` will be an instance of `Rational`, and any type can override `__add__` to do anything that it wishes.
It's true that `np.int64` and `np.uint64` are a counterexample of this, but this behavior pre-dates the existence of `numbers.Rational` in the Python language.

> therefore the implementers of Fraction are incorrect in (apparently) assuming this?

`Fraction` is designed to work with `int` types. If you use types other than `int`, then the results of operations will be consistent with whatever types you use. I'd recommend only using integers as arguments to `Fraction` if you want it to work as it was intended to work.

**Comment by sanderland** [comment] 2023-12-27 10:56
> Fraction is designed to work with int types.

To clarify, [this line](https://github.com/python/cpython/blob/main/Lib/fractions.py#L294) is the one that errors out after being called by `__add__`. There are clearly some strong assumptions there about integers behaving reasonably and not turning into strings or floats or something when added together.

The full program does something along the lines of:
* Make a 2d np.array of some list of list of integers for convenience of slicing and transposing
* Eventually use some entries to make a system of equations with Fraction, and solve it exactly.
So the sudden appearance of a float in a program that reads, stores, retrieves integers was really surprising.

One more example I made in furthering my understanding of this (and whoever else may come across this):
```python
x = int(1e19)
(np.array(x) * 5, np.array(x//2) * 10, np.array(x//2,dtype=object) * 10)
```
=> (5e+19, -5340232221128654848, 50000000000000000000)
(without any warnings on the middle overflow either 😱 )

Overall I think the lesson seems to be that numpy arrays do not store integers well (unless you like being concerned with their bit length) and to add `dype=object` or `dtype=float` to any numpy array intialized from integers in the future.

**Comment by jakevdp** [comment] 2023-12-27 12:45
> There are clearly some strong assumptions there about integers behaving reasonably and not turning into strings or floats or something when added together.

Exactly: this is what I meant when I said "Fraction is designed to work with int types." If you only use Python integers (i.e. `int` instances) in `Fraction` and avoid using numpy `int64` or `array` types, then you won't run into issues. If you use arrays in place of Python integers, it will not work in cases like the one in your example.

**Comment by seberg** [comment] 2023-12-28 11:06
Going to close this, it's a duplicate of other issues.  Note that NEP 50/NumPy does change it in many cases (but not all!) for Python (but not NumPy) integers.

**Closed by seberg** 2023-12-28 11:06 UTC
Labels: 00 - Bug
