### ISSUE TITLE
Docs for array creation routines: section "ones and zeros" should be renamed

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#7408] opened 2016-03-11 03:18 UTC
The "ones and zeros" sections contains also entries for `full` and `full_like`, which logically belong to that section but are not for "ones and zeros" :-)
I don't have a good suggestion, though.

**Comment by charris** [comment] 2016-03-11 04:23
Maybe `Arrays filled with a single value`.

**Comment by mattip** [comment] 2019-05-07 05:20
Closing, the format of the [page](http://www.numpy.org/devdocs/user/basics.creation.html) has changed.

**Comment by anntzer** [comment] 2020-10-10 11:28
Actually the issue is still present at https://numpy.org/devdocs/reference/routines.array-creation.html#ones-and-zeros, so perhaps worth reopening?

**Comment by rossbar** [comment] 2020-10-20 18:24
@anntzer is right, the problem is in the heading in array creation routines in the reference guide. Relevant source file: `doc/source/reference/routines.array-creation.rst`

**Comment by melissawm** [comment] 2020-10-20 23:05
There doesn't seem to be a [name for these](https://en.wikipedia.org/wiki/List_of_named_matrices). However, `Arrays filled with a single value` doesn't go with `empty`, `empty_like` or `identity` to me. Since the next section is "From existing data", I'd suggest something like "From shape or value" but that may be too vague.

**Closed** 2021-02-25 17:30 UTC
Labels: 04 - Documentation
