### ISSUE TITLE
BUG: can't overwrite the attributes of ndarray class

### ISSUE THREAD

**Issue by mattbarrett98** [numpy/numpy#22177] opened 2022-08-25 19:10 UTC
### Describe the issue:

Examples like the following work fine:
```
>>> import numpy as np
>>> np.add = None
>>> print(np.add)
None
```

However the code below doesn't, is there any way around this?

### Reproduce the code example:

```python
import numpy as np
np.ndarray.__add__ = None
```

### Error message:

```shell
TypeError: can't set attributes of built-in/extension type 'numpy.ndarray'
```

### NumPy/Python version information:

1.21.6 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0]

**Comment by rkern** [comment] 2022-08-25 19:43
We don't support monkey-patching like this. Nor do most built-in/extension types. This is definitely by design, not an oversight.

There might be alternatives to accomplish whatever you would like to accomplish, but you'll need to describe what that is.

**Comment by seberg** [comment] 2022-09-02 10:52
Closing, we won't make attributes mutable and there was no further followup for a while.

**Closed by seberg** 2022-09-02 10:52 UTC
Labels: 33 - Question
