### ISSUE TITLE
command llvm-ar is not available on macos (distutils)

### ISSUE THREAD

**Issue by MarkWieczorek** [numpy/numpy#17777] opened 2020-11-15 13:09 UTC
I use numpy's distutils on macOS to compile and link to fortran source code. Everything has worked fine, up until python 3.9.

Now, with python 3.9, after compiling the source code, distutils tries to create an archive using the command `llvm-ar`: unfortunately, this command does not exist (at least by default) on macOS.

```
 llvm-ar: adding 50 object files to ...
 error: Command "/Users/runner/miniforge3/conda-bld/python-split_1606376626618/_build_env/bin/llvm-ar  ...  failed with exit status 127
```

Prior to python 3.9, this step would use the standard command `ar`, which is available natively on macos.

```
ar: adding 50 object files to ......
```

So, I have no idea why python 3.9 now all of a sudden uses `llvm-ar` on macos.

**Comment by Talador12** [comment] 2020-11-20 22:47
+1

This is causing failed installations on mac-os.

For context

```
building 'npymath' library
      compiling C sources
      C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/kadler/anaconda3/envs/project_name/include -arch x86_64 -fPIC -O2 -isystem /Users/kadler/anaconda3/envs/project_name/include -arch x86_64

      compile options: '-Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath -Inumpy/core/include -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/kadler/anaconda3/envs/project_name/include/python3.9 -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/common -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/common -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath -c'
      llvm-ar: adding 4 object files to build/temp.macosx-10.9-x86_64-3.9/libnpymath.a
      error: Command "/opt/concourse/worker/volumes/live/8e75f32a-160a-4528-66de-c3389541e339/volume/python-split_1605449976272/_build_env/bin/llvm-ar rcs build/temp.macosx-10.9-x86_64-3.9/libnpymath.a build/temp.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/npy_math.o build/temp.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/ieee754.o build/temp.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/npy_math_complex.o build/temp.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/halffloat.o" failed with exit status 127
```

**Comment by mattip** [comment] 2020-11-21 17:01
Where does that command come from? FWIW, neither CPython's distutil nor NumPy's distutil has `llvm-ar` as far as I can tell, so someone with a failing system will have to debug this.

**Comment by Talador12** [comment] 2020-11-23 15:33
`pip install pyarrow==2.0.0`
I should probably crosspost this to pyarrow, but @MarkWieczorek likely is installing a different package that has a dependency on numpy and got the same error.

Note that mine is `adding 4 objects` for that `libnpymath.a` package and his is `adding 50 objects` for another package

**Comment by Talador12** [comment] 2020-12-01 22:11
Well - fixed the issue but it required a change in python environment.

The above pip install was actually using conda, and the cross between them broke the install.

The particular config option set was `conda config --set pip_interop_enabled True`

Looks like the culprit might be numpy installed by conda using the pip interop option. In hindsight, pip and conda don't always mix well.

**Comment by MarkWieczorek** [comment] 2020-12-01 22:30
Unfortunately, the above suggestion doesn't solve the problem of the original post...

**Comment by MarkWieczorek** [comment] 2021-01-05 11:37
I found a temporary fix for this: It is only necessary to set the `AR` shell variable using

```
export AR=/usr/bin/ar
```
However, this is not really "the" solution, and I am confused as to whose fault this is. Someone mentioned that this might be a problem with the python distribution I am using (which is conda-forge).

**Comment by NdodaEnde** [comment] 2021-07-14 10:25
Was this ever solved? I am having the same error.

**Comment by LeonardoAlchieri** [comment] 2021-07-31 13:21
> I found a temporary fix for this: It is only necessary to set the `AR` shell variable using
> 
> ```
> export AR=/usr/bin/ar
> ```
> 
> However, this is not really "the" solution, and I am confused as to whose fault this is. Someone mentioned that this might be a problem with the python distribution I am using (which is conda-forge).

If someone else has the same problem, this actually solved the issue for me.

**Comment by rgommers** [comment] 2022-01-06 10:02
> The above pip install was actually using conda, and the cross between them broke the install.
> 
> The particular config option set was `conda config --set pip_interop_enabled True`
> 
> Looks like the culprit might be numpy installed by conda using the pip interop option. In hindsight, pip and conda don't always mix well.

We have `arm64` wheels now, so this shouldn't be a problem anymore. This is a duplicate of gh-17569. Yes, conda and pip don't mix well. There is a workaround and there are wheels. I'll reference my answer at https://github.com/numpy/numpy/issues/17569#issuecomment-1006391093 and will close this, since there's nothing left to do.

**Closed by rgommers** 2022-01-06 10:02 UTC
Labels: 32 - Installation
