### ISSUE TITLE
BUG: strange result occurs when data overflows during  n-th power calculation

### ISSUE THREAD

**Issue by xiaoxstz** [numpy/numpy#20634] opened 2021-12-21 02:03 UTC
### Describe the issue:

When data overflow happens during n-th power calculation, it would return a wrong result

### Reproduce the code example:

```python
import numpy as np
a = np.array([222,-222],dtype=np.int16)
b = a ** 2
c = a ** 4
d = a + 2**15
>>> b # get wrong result: array([-16252, -16252], dtype=int16)
>>> c # get wrong result: array([17424, 17424], dtype=int16)
>>> d # get correct result: array([32990, 32546], dtype=int32)
```

### Error message:

```shell
array([-16252, -16252], dtype=int16)
array([17424, 17424], dtype=int16)
```

### NumPy/Python version information:

1.21.4 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)

**Comment by charris** [comment] 2021-12-21 02:19
NumPy uses modular arithmetic, it is a feature, not a bug :) The user needs to be aware of their needs and use an appropriate precision.

**Comment by seberg** [comment] 2021-12-23 20:56
Closing, at some point it might be good to look into issuing integer-overflow warnings reliably (if it can be done quickly!).  But it is not currently on the roadmap and there are other issues open about it.
(At this point, I think someone outside the current dev-team would need to help champion such a project.)

**Closed by seberg** 2021-12-23 20:56 UTC
Labels: 00 - Bug

**Comment by xiaoxstz** [comment] 2022-05-10 07:13
It's because that int16 data type covers from -32768 to 32767. 

222^2 = 49284, so you should use int32, instead
