### ISSUE TITLE
numpy distutils support for MinGW is broken under Python 3

### ISSUE THREAD

**Issue by ogrisel** [numpy/numpy#3557] opened 2013-07-28 11:30 UTC
Here is the traceback:

```
Traceback (most recent call last):
  File ".\setup.py", line 128, in <module>
    setup_package()
  File ".\setup.py", line 124, in setup_package
    setup(**metadata)
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\core.py", line 186, in setup
    return old_setup(**new_attr)
  File "C:\Anaconda\envs\py3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Anaconda\envs\py3\lib\distutils\dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda\envs\py3\lib\distutils\dist.py", line 948, in run_command
    cmd_obj.run()
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\command\build_ext.py", line 69, in run
    build_clib.run()
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\command\build_clib.py", line 71, in run
    force=self.force)
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\ccompiler.py", line 560, in new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 91, in __init__
    build_import_library()
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 383, in build_import_library
    return _build_import_library_x86()
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 428, in _build_import_library_
x86
    dlist, flist = lib2def.parse_nm(nm_output)
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\distutils\lib2def.py", line 77, in parse_nm
    data = DATA_RE.findall(nm_output)
TypeError: can't use a string pattern on a bytes-like object
```

This is numpy 1.7.1.

**Comment by ahjulstad** [comment] 2015-02-05 11:46
I can reproduce this, trying to build on win32 with msvc2010 and intelv (Intel Visual Fortan 13.0.1.119).

The error message appears when doing 
```
python setup.py install
```

For me, the fix in https://github.com/numpy/numpy/pull/5535 solves the problem.

**Comment by rgommers** [comment] 2016-01-09 15:52
fixed by gh-5535 it looks like, so closing

**Closed by rgommers** 2016-01-09 15:52 UTC
Labels: component: numpy.distutils, Critical Defect
