### ISSUE TITLE
BUG: Gitpod Instance build failing at startup

### ISSUE THREAD

**Issue by bhavukkalra** [numpy/numpy#21551] opened 2022-05-20 16:53 UTC
### Describe the issue:

The gitpod instance build is failing at startup due to `cython` version being `0.29.28` and required is Cython >= 0.29.30.

![report_error](https://user-images.githubusercontent.com/41142068/169574976-99b72c0d-1660-4dad-9368-b4e084065a7d.PNG)

I suspect it is due to the recent change made in `environment.yml` (maybe other changes as well, but I was only able to find this one involving cython)

[Commit changing cython](https://github.com/numpy/numpy/commit/c0696c5f26f8b45b01c09d21e86c104b7f616577)

### Reproduce the code example:

```python
Open Gitpod Instance via Numpy repo
```

### NumPy/Python version information:

No version output, As numpy isn't building.

**Comment by charris** [comment] 2022-05-20 17:42
I think Cython 0.29.30 just went into mamba yesterday, you may need to update.

**Comment by bhavukkalra** [comment] 2022-05-20 19:04
Update the `environment.yml`?

**Comment by rossbar** [comment] 2022-05-20 20:05
I don't think any changes are required on our end - the environment.yml has been updated already. There's the question of when/how the gitpod environment is updated when we make a change to `environment.yml` @melissawm @trallard do we know how this works? If someone is already using gitpod, is it possible that their instance is cached which could be causing problems?

**Comment by bhavukkalra** [comment] 2022-05-20 20:09
If an `environment.yml` is updated I have observed(Not a fact, but just an observation), in about 24 Hours the latest image gets pushed to dockerHub, which gitpod uses as a base

**Comment by mattip** [comment] 2022-05-21 18:44
> in about 24 Hours the latest image gets pushed to dockerHub, which gitpod uses as a base

[The image](https://hub.docker.com/r/numpy/numpy-gitpod/tags) is apparently pushed by @rgommers, and was last updated 4 days ago. We need an image that includes #21530, which was merged 2 days ago.

**Comment by rgommers** [comment] 2022-05-22 13:55
That's the wrong image to the link. https://hub.docker.com/r/numpy/numpy-dev/tags is the right one, and it was pushed after `environment.yml` was updated 3 days ago. The latest run at https://github.com/numpy/numpy/actions/workflows/docker.yml shows it's from the correct merge commit.

Something went wrong though, since the Gitpod image build has been failing for the last 4 days: https://github.com/numpy/numpy/actions/workflows/gitpod.yml. I'll have a closer look.

**Comment by rgommers** [comment] 2022-05-22 14:05
The problem is actually unrelated, the Gitpod image build is now failing on:
```
Error: buildx failed with: error: failed to solve: process "/bin/bash --login -o pipefail -c git submodule update --init --depth=1 -- numpy/core/src/umath/svml" did not complete successfully: exit code: 128
```

**Closed** 2022-05-22 14:11 UTC
Labels: 16 - Development

**Comment by rgommers** [comment] 2022-05-22 14:30
Okay, new image now built successfully. ([log](https://github.com/numpy/numpy/runs/6544208456?check_suite_focus=true)) for future reference.
