### ISSUE TITLE
"max() got an unexpected keyword argument 'out'" in fromnumeric.py line 2256

### ISSUE THREAD

**Issue by orswan** [numpy/numpy#7460] opened 2016-03-25 00:12 UTC
I will just explain this bug by example:
`

    from scipy import sparse

    e = sparse.eye(3)

    amax(abs(e-e.H))
`

This generates an error: "max() got an unexpected keyword argument 'out'", and the offending code is line 2256 in fromnumeric.py.

**Comment by njsmith** [comment] 2016-03-25 02:29
Unless this is a regression (i.e., it used to work in old versions of numpy but broke in newer versions -- in which case, please let us know!), then I think this is either a bug in `scipy` or else a documentation bug. Either way the workaround is to write it like `abs(e - e.H).max()` so that you're calling the sparse matrix `.max` method instead of the numpy `amax` function -- numpy doesn't know anything about sparse matrix objects from scipy.

@pv: thoughts on whether scipy should fix this? It looks like `np.amax(foo)` does the dubious thing of calling `foo.max(axis=axis, out=out)` whenever `hasattr(foo, "max")`. (Also relevant discussion: https://github.com/numpy/numpy/pull/7325#issuecomment-199147582)

**Comment by gfyoung** [comment] 2016-03-30 06:15
@orswan, @njsmith : I am currently squashing `fromnumeric.py` incompatibilities in fact in <a href="https://github.com/scipy/scipy/pull/6002">#6002</a> in `scipy`, so I will address this issue on the `scipy` end at the very least.

There are several methods that have a similar structure to `max` where they have the `try-except` block if the object is not `ndarray`.  I suspected those might be problematic when I was working on #7325, but I was not sure what the best way was to handle this issue.  Can I just call `_wrap_func` if the object is not `ndarray`?

**Comment by seberg** [comment] 2016-03-30 06:45
So this is a regression?

**Comment by gfyoung** [comment] 2016-03-30 06:51
@seberg : I don't know about regression, but it is a compatibility issue at the very least, very similar to the ones I addressed in #7325.

**Comment by seberg** [comment] 2016-03-30 07:21
Ok, good, then no regression, just wanted to make sure.

**Closed** 2016-08-15 16:08 UTC
