### ISSUE TITLE
Can't use numpy on OSX 10.8.5

### ISSUE THREAD

**Issue by 097115** [numpy/numpy#12947] opened 2019-02-08 07:00 UTC
After installing [the latest](https://pypi.org/project/numpy/#files) release with `pip` (support for 10.8.5 seems to be declared in the filename: numpy-1.16.1-cp37-cp37m-macosx_**10_6**_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl), `numpy` fails with the following error:

```python

3.7.0 (default, Jul 15 2018, 23:10:01) 
[Clang 5.1 (clang-503.0.40)]
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/matplotlib/__init__.py", line 141, in <module>
    from . import cbook, rcsetup
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/matplotlib/cbook/__init__.py", line 33, in <module>
    import numpy as np
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/numpy/__init__.py", line 148, in <module>
    from . import fft
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/numpy/fft/__init__.py", line 6, in <module>
    from .fftpack import *
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/numpy/fft/fftpack.py", line 44, in <module>
    from . import fftpack_lite as fftpack
ImportError: dlopen(/Users/username/Library/Python/3.7/lib/python/site-packages/numpy/fft/fftpack_lite.cpython-37m-darwin.so, 2): Symbol not found: ___sincos_stret
  Referenced from: /Users/username/Library/Python/3.7/lib/python/site-packages/numpy/fft/fftpack_lite.cpython-37m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/username/Library/Python/3.7/lib/python/site-packages/numpy/fft/fftpack_lite.cpython-37m-darwin.so
```

**Comment by rgommers** [comment] 2019-02-08 07:02
duplicate of gh-12939. please install 1.14.6

**Closed by rgommers** 2019-02-08 07:02 UTC

**Comment by dmitriz** [comment] 2019-07-13 12:44
The more recent `numpy 1.15` seems to work as well: https://github.com/numpy/numpy/issues/12939#issuecomment-511119279
