### ISSUE TITLE
ndarray with buffer of integer 0's and 64-bit dtype raises TypeError exception "buffer is too small for requested array", but not float 0's

### ISSUE THREAD

**Issue by mpconte** [numpy/numpy#6616] opened 2015-11-02 19:48 UTC
Python v3.4.3
Numpy v1.10.1
Windows 7 Professional x64

**np.ndarray(shape=(2, 1), buffer=np.array([0, 0]), dtype=np.int64) => raises TypeError: buffer is too small for requested array**

**np.ndarray(shape=(2, 1), buffer=np.array([0, 0]), dtype=np.float64) => raises TypeError: buffer is too small for requested array**

But...

**np.ndarray(shape=(2, 1), buffer=np.array([0.0, 0.0]), dtype=np.int64) => OK**

**np.ndarray(shape=(2, 1), buffer=np.array([0.0, 0.0]), dtype=np.float64) => OK**

**Comment by charris** [comment] 2015-11-02 19:52
Is this also the case for Numpy 1.9?

**Comment by mpconte** [comment] 2015-11-02 19:54
I believe this also happened in numpy v1.8, not sure about v1.9

**Comment by charris** [comment] 2015-11-02 19:55
Oh, I see, it is windows. Your buffer is probably composed of `int32`, try making it `int64`. I don't know if this should be considered an bug or not.

**Comment by mpconte** [comment] 2015-11-02 19:57
That worked, thanks, but it was just unusual behavior to me.

**Comment by njsmith** [comment] 2015-11-02 20:06
Yeah, the problem is just that on windows the default integer type is
always 32 bits, so you're trying to put an array of two 64 bit items into a
buffer that's only big enough for two 32 bit items.
We've talked on and off about switching the default integer size on 64 bit
windows because this is always confusing, but it's difficult because we
have no idea how much existing code would be broken by making this change...

**Comment by charris** [comment] 2015-11-02 20:09
Closing then.

**Closed by charris** 2015-11-02 20:09 UTC
Labels: component: numpy.core, Invalid
