### ISSUE TITLE
Shape argument of random.randn not consistent with zeros

### ISSUE THREAD

**Issue by aamster** [numpy/numpy#12561] opened 2018-12-16 15:26 UTC
zeros takes a tuple as an argument for the shape but randn takes positional arguments for the shape. The shape arguments should be consistent across numpy. I.e I'm trying to avoid this frustration:

```
In [42]: np.random.rand(3, 4)
Out[42]: 
array([[0.3963932 , 0.9112172 , 0.70652219, 0.19683759],
       [0.7527322 , 0.27246836, 0.01735155, 0.91334229],
       [0.33919964, 0.87852726, 0.645863  , 0.7086963 ]])

In [43]: np.zeros(3, 4)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-06beb765944a> in <module>()
----> 1 np.zeros(3, 4)

TypeError: data type not understood

In [44]: np.zeros((3,4))
Out[44]: 
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])```

**Comment by eric-wieser** [comment] 2018-12-16 16:43
I agree, this is unfortunate.

As I understand it, `rand` exists to match the name and signature of the Matlab function. It's possible numpy has another function that _is_ consistent with zeros

**Comment by seberg** [comment] 2018-12-16 16:48
The functions are `random` and `normal`. The documentation could suggest to prefer the more "standardized" functions.

**Comment by oleksandr-pavlyk** [comment] 2018-12-18 03:48
Language consistency notwithstanding, I like `randn` and `rand` for interactive work. It would be an inconvenience for me, and perhaps for some others, if they got deprecated and started issuing warnings. Just my two cents.

**Comment by rkern** [comment] 2018-12-22 18:49
I'm going to close this issue as the inconsistency is by design, and it has been well-deliberated on the mailing list in the past. As pointed out, the numpy-idiomatic methods are `random` and `normal`, which take shape tuples like `zeros/ones/full` and the rest of the `RandomState` methods. `rand` and `randn` exist _only_ to provide this alternate interface because some users, particularly those coming from a MATLAB(TM) background, prefer it for some uses; the inconsistency _is_ the feature for them. I don't think we'll be removing any of these, and `rand/randn` can't be "fixed" without removing this feature.

PRs removing the incidental use of `rand/randn` in documentation's examples should be welcomed, I think.

**Closed by rkern** 2018-12-22 18:49 UTC
