### ISSUE TITLE
BUG: loadtxt raise an ValueError: could not convert string '0x0000' to float64 at row 0, column 1

### ISSUE THREAD

**Issue by cxzchange** [numpy/numpy#22068] opened 2022-08-01 07:43 UTC
### Describe the issue:

I got version 1.23.2.
But loadtxt  raise an ValueError:could not convert string '0x0000' to float64 at row 0, column 1
which works in 1.22.4

### Reproduce the code example:

```python
import numpy as np
from io import StringIO
s = StringIO('0x0000')
np.loadtxt(s)
```

### Error message:

```shell
>>> np.loadtxt(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Workspace\test\venv\lib\site-packages\numpy\lib\npyio.py", line 1301, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "D:\Workspace\test\venv\lib\site-packages\numpy\lib\npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: could not convert string '0x0000' to float64 at row 0, column 1.
```

### NumPy/Python version information:

1.23.2 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]

**Comment by seberg** [comment] 2022-08-02 04:31
This was a rare incompatible change that was on purpose (which doesn't mean we could not reconsider this).
The new way to do this would be to use `np.loadtxt(s, converters=float.fromhex, coding=None)`.  Although it is annoying that the `coding` is necessary, it should not be, it is a compatibility artifact from Python 2 :(.

**Comment by seberg** [comment] 2023-06-21 09:48
Going to close this.

@rossbar it seems to me that for 2.0 we should switch over the default encoding unceremoniously?  Unless we are worried that tracking down the cause of such change is hard.  It seems hopefully OK, since (if you see it) you should see the error occurring inside your converter?

**Closed by seberg** 2023-06-21 09:48 UTC
Labels: 00 - Bug
