### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by SulisEm** [numpy/numpy#14846] opened 2019-11-07 02:38 UTC
just a problem of installation:
- I installed and using just Miniconda 
- how do I installed numpy:
  1) conda update -y --all
  2) conda install -y numpy
 - my operating system is Windows 10 Enterprise 64bit

### Reproducing code example:
python -c "import numpy"

or in my program:

import numpy as np

### Error message:

C:\Users\sulis>python -c "import numpy"
Traceback (most recent call last):
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Impossibile trovare il modulo specificato.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\sulis\Miniconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Impossibile trovare il modulo specificato.

### Numpy/Python version information:

Python version: Python 3.7.5

I can't import Numby:

Traceback (most recent call last):
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Impossibile trovare il modulo specificato.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/sulis/PycharmProjects/scraping-scholar/prova.py", line 1, in <module>
    import sys, numpy;
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\sulis\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\sulis\Miniconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Impossibile trovare il modulo specificato.

**Comment by mattip** [comment] 2019-11-07 03:47
I think you need to activate your conda environment before running python.

**Comment by rgommers** [comment] 2019-11-08 00:22
Let's close this as a duplicate of gh-14848. @SulisEm if you could confirm on that issue that the exact commands in https://github.com/numpy/numpy/issues/14848#issuecomment-551327405 fail for you, that would be helpful.

**Closed by rgommers** 2019-11-08 00:22 UTC
