### ISSUE TITLE
TestVectorize.test_docstring is failing in the benchmark runs.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#23461] opened 2023-03-26 23:59 UTC
```
_________________________ TestVectorize.test_docstring _________________________

self = <numpy.lib.tests.test_function_base.TestVectorize object at 0x7f18c0a6aa90>

    def test_docstring(self):
        @vectorize
        def f(x):
            """Docstring"""
            return x
    
>       assert f.__doc__ == "Docstring"
E       AssertionError: assert None == 'Docstring'
E        +  where None = <numpy.vectorize object at 0x7f18c0a6a220>.__doc__

f          = <numpy.vectorize object at 0x7f18c0a6a220>
self       = <numpy.lib.tests.test_function_base.TestVectorize object at 0x7f18c0a6aa90>
```

**Comment by mattip** [comment] 2023-03-27 05:44
I wonder how this passed in #23061. @MatteoRaso could you take a look?

**Comment by WarrenWeckesser** [comment] 2023-03-27 05:48
It didn't pass.  The failure is still visible in the "benchmark" job in that pull request.

**Comment by MatteoRaso** [comment] 2023-03-27 19:30
>I wonder how this passed in https://github.com/numpy/numpy/pull/23061. @MatteoRaso could you take a look?

This is bizarre. `runtests.py` didn't say anything, so I assumed everything was good. If I understand correctly, this is because it doesn't work with `functools.partial`, right?

**Comment by molsonkiko** [comment] 2023-03-27 20:52
I noticed this when I was doing my last PR just yesterday, so I tried to replicate the docstring test in my REPL. It worked fine in the REPL.

**Comment by WarrenWeckesser** [comment] 2023-03-27 22:44
> This is bizarre. runtests.py didn't say anything, so I assumed everything was good. 

Once you submit a pull request, you have to check the results of the tests that run on github.  Those tests run on a variety of platforms with different versions of Python and different Python options.

> If I understand correctly, this is because it doesn't work with functools.partial, right?

This is a different issue.  In your github pull request, click on the red `x` next to the last commit SHA, scroll down to the job called "Build_Test / benchmark (pull_request)" (the one with the red `x` next to it), and click on "Details".  (Those details might eventually disappear, but as I write this, they are still available.) Scroll through the details to find what went wrong.  The beginning of the relevant description begins at line 3423.

In this case, the problem is that the `benchmark` job runs with the environment variable `PYTHONOPTIMIZE` set to 2, which results in docstrings being discarded and replaced with `None`.  So the test that the docstring of the `vectorize`'d method is `"Docstring"` will fail, because `f.__doc__` (as shown in the details) is actually `None`.

A simple fix might be to only compare `f.__doc__` to `"Docstring"` if `sys.flags.optimize < 2`.

**Comment by bsipocz** [comment] 2023-03-31 21:01
The revert PR has been merged, so this can be closed now. (There was a comment about it in the revert PR, however the auto closing only works if it's mentioned in the OP, or in a commit message, or at the sidebar it's manually linked.

**Closed by bsipocz** 2023-03-31 21:01 UTC
