### ISSUE TITLE
Numpy MKL causes hang with Python Subprocess and Multiprocessing modules.

### ISSUE THREAD

**Issue by chrisgmorton** [numpy/numpy#11734] opened 2018-08-13 17:59 UTC
This appears to be a defect that is specific to Intel's Math Kernel Library and the resolution will likely require changes therein. I'm submitting here as I believe the NumPy team has some relationships/connections with the Intel team and there have been some efforts to make MKL work well with NumPy (and SciPy). I am using Python 3.6.4, built from source on OSX 10.13.4 and Linux 16.04 (WSL). NumPy is built from source using gcc 7.1.0 on Mac and gcc 7.2 on Linux.

When executed with python3 this script will hang the terminal on OSX and Linux. No tests have been performed on Win64. If the size of the vector, x, is reduced by a factor of 10 to 1000, no hang is observed and the script executes correctly. The hang is specific to the call to linalg.norm. It is likely caused by multi-threaded execution of the norm() method using MKL's infrastructure, leaving the system in a state that interferes with Python execution of subprocess.run(). I also get a hang when using Python's Multiprocessing module process creation in place of subprocess.run().

This is important for a few reasons 1) Jupyter QtConsole & Notebook and IPython use subprocess.run() to execute certain os commands (such as ls). Hence we get a hang when working in all these applications. 2) If you want to spawn or fork to subprocesses to execute cpu intensive tasks you'll get a hang if you've previously called np.linalg.norm() with a sufficiently large vector (and perhaps many other NumPy and SciPy calls).

### Reproducing code example:

```python
import numpy as np
import subprocess

x = np.arange(10000) # 1000 shows no hang.
xnorm = np.linalg.norm(x)

subprocess.run('ls')
```

### Error message:

No error message, just a hang.

### Numpy/Python version information:

NumPy 1.14.3
Python 3.6.4
MKL: l_mkl_2018.3.222, m_mkl_2018.3.185

**Comment by mattip** [comment] 2018-08-13 18:17
Duplicate of #10060, #11041 #10993, and maybe others.
Among the fixes that might work:
- update to [mkl 2018.3](https://software.intel.com/en-us/articles/intel-math-kernel-library-release-notes-and-new-features)
- disable threading by `set OPENBLAS_NUM_THREADS=1 `
- try the workarounds suggested in #10060:
```
# work-around 1:
KMP_INIT_AT_FORK=FALSE python script.py
# work-around 2:
MKL_THREADING_LAYER=TBB python script.py` 
```

Please let us know which of these, if any, helped so we can advise others.

**Comment by chrisgmorton** [comment] 2018-08-13 21:50
Correction, I am using l_mkl_2018.3.222 and m_mkl_2018.3.185 already. I updated my original post.

**Comment by mattip** [comment] 2018-08-13 22:42
What about the other workarounds?

> I believe the NumPy team has some relationships/connections with the Intel team and there have been some efforts to make MKL work well with NumPy (and SciPy).

Unfortunately we have no such connections.

**Comment by chrisgmorton** [comment] 2018-08-13 23:05
Using `KMP_INIT_AT_FORK=FALSE` resolves this issue on OSX and Linux. I did not investigate `MKL_THREADING_LAYER=TBB` as this requires installation of other INTEL libraries.

**Closed** 2018-08-16 23:31 UTC
Labels: 50 - Duplicate
