### ISSUE TITLE
Cannot make numpy array with dtype object if elements are numpy array with ndim > 1

### ISSUE THREAD

**Issue by mfkasim1** [numpy/numpy#19470] opened 2021-07-13 22:26 UTC
An error is raised when making a numpy array consisting of numpy arrays with ndim > 1 with different sizes.

### Reproducing code example:

```python
import numpy as np
b = np.array([np.array([[1],
    [1],
    [1]]), np.array([[1, 2],
    [1, 2],
    [1, 2]]), np.array([[1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]]), np.array([[1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4]])], dtype=object)
```

### Error message:

    ValueError: could not broadcast input array from shape (3,1) into shape (3,)

### NumPy/Python version information:

    1.21.0 3.8.5 (default, Sep  4 2020, 07:30:14)
    [GCC 7.3.0]

**Comment by mattip** [comment] 2021-07-14 04:57
Are you asking how to combine the arguments into a single array? Then you can do something like

```
a1 = np.array([[1], [1], [1]])
a2 = np.array([[1, 2], [1, 2], [1, 2]])
a3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
a4 = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
b = np.empty([4], dtype=object)
b[:] = [a1, a2, a3, a4]
```

or are you asking about the confusing error message? There was discussion about not allowing this kind of input, search for "ragged arrays" in the issues and see [NEP 34](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html) where we took a first step toward never guessing what to do with ragged arrays.

**Comment by mfkasim1** [comment] 2021-07-14 10:32
I was asking both actually. I didn't expect the code will raise an error and the error message does not indicate where I should look at.
Anyway, thanks for the workaround.

**Comment by seberg** [comment] 2021-07-14 14:41
Thanks for raising the issue.  I am going to close it as a duplicate of gh-17224 and gh-19113, though.  There are many issues open on it, `depth=...` or similar has been suggested at some point to allow forcing a 1-D object array here.

**Closed by seberg** 2021-07-14 14:41 UTC
