### ISSUE TITLE
memory leak in random.permutation and random.shuffle

### ISSUE THREAD

**Issue by RomanKosobrodov** [numpy/numpy#14131] opened 2019-07-26 04:01 UTC
permutation and shuffle functions in numpy.random leak memory. On different test machines it either caused MemoryError, script termination with SIGKILL from OS, or produced no errors but the script consumed huge amount of  memory (~ 5Gb). 

### Reproducing code example:

```python
import numpy as np

for k in range(1000):
    ind = np.random.permutation(44100 * 1000)
```
or 
```python
import numpy as np

for k in range(1000):
    x = np.empty(44100 * 1000)
    np.random.shuffle(x)
```
Start `top` and watch the memory grow.

### Error message:

Traceback (most recent call last):
  File "leak_memory.py", line 5, in <module>
    ind = np.random.permutation(44100 * 1000)
  File "mtrand.pyx", line 4917, in mtrand.RandomState.permutation
MemoryError

### Numpy/Python version information:
1.16.3 3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0]

OS: Ubuntu 18.04 (Error message and SIGKILL)
       Windows 10 (huge memory consumption)

**Comment by seberg** [comment] 2019-07-26 17:45
Hmmm, should be a duplicate of gh-13808, but that makes that a bit higher priority. I think that PR already had a suggested fix or semi suggested one. So if anyone has a few cycles to look at it that is appreciated.

**Closed** 2019-09-18 14:37 UTC
Labels: 00 - Bug, component: numpy.random, priority: high
