### ISSUE TITLE
Unable to build numpy with GCC 4.8.5

### ISSUE THREAD

**Issue by adamjstewart** [numpy/numpy#14182] opened 2019-08-02 04:16 UTC
I'm trying to install numpy from source but I'm seeing a lot of C99 errors.

### Reproducing code example:

```console
$ python -s setup.py --no-user-cfg build
$ python -s setup.py --no-user-cfg install --prefix=/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/py-numpy-1.17.0-37xrxjmnbitsruc7alrutzpvdil2xhhy --single-version-externally-managed --root=/
```

### Error message:

I see hundreds of errors like:
```
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_bool':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (npy_intp i = 1; i < num; i++) {
     ^
numpy/core/src/npysort/radixsort.c.src:112:5: note: use option -std=c99 or -std=gnu99 to compile your code
```

### Numpy/Python version information:

- Linux CentOS 7
- GCC 4.8.5
- Python 3.7.4
- Numpy 1.17.0

**Comment by dantonini** [comment] 2019-08-05 23:42
I'm trying to compile numpy in a Docker container and I faced this issue.
I was able to correctly compile numpy 1.17.0  + gcc 4.8.5 using:
export CFLAGS='-std=c99' 
pip3 install --no-binary :all: numpy 

I hope this can save some headache to someone else.
Cheers

**Comment by rgommers** [comment] 2019-08-06 00:18
Thanks @adamjstewart and @dantonini. Note that this is a duplicate of gh-14147, which has more details. So closing this issue.

**Closed by rgommers** 2019-08-06 00:18 UTC
Labels: component: build
