### ISSUE TITLE
rounding problem in string representation of np.float32

### ISSUE THREAD

**Issue by arw2019** [numpy/numpy#17880] opened 2020-11-30 04:08 UTC
### Reproducing code example:

I observe a loss of precision when `item()` is called on a `np.float32` scalar:
```python
In [4]: import numpy as np
   ...: 
   ...: fvalue_32 = np.float32(0.1)
   ...: print(fvalue_32)
   ...: print(fvalue_32.item())
0.1
0.10000000149011612
```
which doesn't occur for `np.float64`:
``` python
In [5]: import numpy as np
   ...: 
   ...: fvalue_64 = np.float64(0.1)
   ...: print(fvalue_64)
   ...: print(fvalue_64.item())
0.1
0.1
```
I am running NumPy 1.19.4 on a 64 bit machine. Ran into this while working on https://github.com/pandas-dev/pandas/pull/37377.

**Comment by BvB93** [comment] 2020-12-01 17:16
This is an issue caused by rounding in the string-representation of `np.float32`;
not an actual loss of precision:

``` python
In [1]: import numpy as np

In [2]: f4 = np.array([0.1], dtype=np.float32)

In [3]: print(f4)
   ...: print(f4.item())
[0.1]
0.10000000149011612

In [4]: with np.printoptions(floatmode='fixed', precision=17):
   ...:     print(f4)
[0.10000000149011612]
```

**Comment by arw2019** [comment] 2020-12-01 17:21
> This is an issue caused by rounding in the string-representation of `np.float32`;
> not an actual loss of precision:
> 
> ```python
> In [1]: import numpy as np
> 
> In [2]: f4 = np.array([0.1], dtype=np.float32)
> 
> In [3]: print(f4)
>    ...: print(f4.item())
> [0.1]
> 0.10000000149011612
> 
> In [4]: with np.printoptions(floatmode='fixed', precision=17):
>    ...:     print(f4)
> [0.10000000149011612]
> ```

Right, I misspoke. This came up in the string representation of an `np.float32`-backed pandas data structure.

Is there a work-around? (Or, better still, is this worth fixing on the NumPy side? Happy to work on a PR)

**Comment by eric-wieser** [comment] 2020-12-01 17:33
The behavior here is correct: `f4` is the closing `float32` value to `0.1`, so it prints as `0.1`. Calling `item()` casts it to a builtin `float` (float64), where it is no longer the closest value to `0.1`.

Would following the example of #17592 and changing the repr to `float32(0.1)` make this more or less confusing?

**Comment by arw2019** [comment] 2020-12-01 17:43
> The behavior here is correct: `f4` is the closest `float32` value to `0.1`, so it prints as `0.1`. Calling `item()` casts it to a builtin `float` (float64), where it is no longer the closest value to `0.1`.

Right, makes sense.

> Would following the example of #17592 and changing the repr to `float32(0.1)` make this more or less confusing?

IMO `float32(0.1)` is less confusing

**Comment by BvB93** [comment] 2020-12-01 17:43
> Is there a work-around?

Pandas has a precision option in `pd.set_option`, which set to 5 decimals by default.
I suppose you could round the floats to the precision specified therein before converting them to strings.

**Comment by dgoeries** [comment] 2020-12-03 19:33
We stomped over the same problem. What we require a safe "convert" of a `np.float32` to a `float`.

Our workaround for now is `float(str(value)`, to not get the disturbed value. There is no intention on `numpy` to change this behavior?

**Comment by seberg** [comment] 2020-12-03 19:39
@dgoeries could you explain in what way you feel that approach is "safe", or better?  What it ends up doing is a round operation in *decimal* representation, while the current cast converts it to the *exact same number* (in binary).

**Comment by dgoeries** [comment] 2020-12-03 19:57
@seberg  my use case is covered with a lot of business knowledge. As UI developer one deals with a lot of floating types. If we have a value that we receive from somewhere to display this generic, e.g.
```
>>> motor_position = np.float32(0.00123)
>>> "{:.8g}".format(motor_position)
>>> '0.0012300001'

>>> motor_position = np.float32(0.00123)
>>> "{}".format(motor_position)
'0.001230000052601099'

>>> motor_position = 0.00123
>>> "{}".format(motor_position)
'0.00123'
```
Of course we have to show `0.00123` in the controller displaying the value and not  '0.001230XYZ'. So the "safe convert" for us to maintain this is -> `float(str(0.00123))`.

**Comment by seberg** [comment] 2020-12-03 20:11
@dgoeries printing is fair enough, but what you really want then is `"{!r}.format(np.float32(1.))"`. I.e. the issue is that our `str(float32)` should maybe only give the same precision as necessary in float32 itself. But `fvalue_32.item()` *must* give the result it currently gives.

**Comment by dgoeries** [comment] 2020-12-03 20:28
@seberg thank you very much! Thats exactly what I want :-).

**Comment by seberg** [comment] 2020-12-03 20:34
@dgoeries the only problem is that (see edit), if we change `repr(np.float32(0.1))` to be `float32(0.1)`, then you might be unhappy again and have to change your code to use not use `repr` anymore...

**Comment by arw2019** [comment] 2020-12-03 21:52
Is it worth adding a note to the documentation about this? Otherwise from my side I'm happy with things as they are (now that I understand the origin of the 'item()' behavior)

**Comment by seberg** [comment] 2020-12-03 22:23
Yeah, I think we can close it. If someone has an idea where documentation could be clearer that is of course awesome.  The `__format__` issue is open here: gh-10645

@dgoeries formatting with `{!s}` will also do the trick, and makes more sense in your use-case.

**Closed by seberg** 2020-12-03 22:23 UTC
Labels: 33 - Question

**Comment by dgoeries** [comment] 2020-12-03 22:34
okay thanks again!
