### ISSUE TITLE
.dot() function causing headers issue in apache

### ISSUE THREAD

**Issue by gphein** [numpy/numpy#12196] opened 2018-10-17 03:56 UTC
I am running a local copy of apache with flask (details below). I've been using this setup for quite a while. After installing the numpy 1.15.2 I started getting an error I'd never seen before. The information given did not indicate the root cause or where it happened. Using debug lines and turning things on and off I narrowed the issue to a call to numpy.dot(). When I go back to numpy 1.11.2 the issue goes away (I verified that switching between these two versions of numpy reproduces the issue). 

### Reproducing code example:

OSX 10.13.6
Numpy version 1.15.2

Apache Information:
Server version: Apache/2.4.25 (Unix)
Server built:   Jan 11 2017 20:47:08
Server loaded:  APR 1.6.3, APR-UTIL 1.6.1
Compiled using: APR 1.5.2, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)

VirtualHost WSGI Related Directives:
WSGIScriptAlias /api ...paths...
WSGIDaemonProcess app threads=5 python-path
WSGIProcessGroup app
WSGIApplicationGroup %{GLOBAL}

Log Level is set to debug. Apache error log for the request in error section of this bug report:

```python
# n is 637
# cf_mat is 637 x 68
T = np.tril(np.ones((n, n)))
cum_cf = T.dot(cf_mat)
```

### Error Message

[Tue Oct 16 23:08:24.880764 2018] [wsgi:info] [pid 2927] mod_wsgi (pid=2927): Destroying interpreters.
[Tue Oct 16 23:08:24.880801 2018] [wsgi:info] [pid 2927] mod_wsgi (pid=2927): Cleanup interpreter ''.
[Tue Oct 16 23:08:24.888718 2018] [wsgi:info] [pid 2927] mod_wsgi (pid=2927): Terminating Python.
[Tue Oct 16 23:08:24.894276 2018] [wsgi:info] [pid 2927] mod_wsgi (pid=2927): Python has shutdown.
[Tue Oct 16 23:08:38.674061 2018] [wsgi:error] [pid 2896] [client 127.0.0.1:52759] Truncated or oversized response headers received from daemon process 'app': main.wsgi, referer: http://app.local:8080/
[Tue Oct 16 23:08:38.891779 2018] [core:notice] [pid 1250] AH00052: child pid 2894 exit signal Bus error (10)
[Tue Oct 16 23:08:38.892479 2018] [wsgi:info] [pid 1250] mod_wsgi (pid=2894): Process 'app' has died, deregister and restart it.
[Tue Oct 16 23:08:38.892522 2018] [wsgi:info] [pid 1250] mod_wsgi (pid=2894): Process 'app' terminated by signal 10
[Tue Oct 16 23:08:38.892553 2018] [wsgi:info] [pid 1250] mod_wsgi (pid=2894): Process 'app' has been deregistered and will no longer be monitored.
[Tue Oct 16 23:08:38.893036 2018] [wsgi:info] [pid 2926] mod_wsgi (pid=2926): Destroying interpreters.
[Tue Oct 16 23:08:38.893085 2018] [wsgi:info] [pid 2926] mod_wsgi (pid=2926): Cleanup interpreter ''.
[Tue Oct 16 23:08:38.893966 2018] [wsgi:info] [pid 2932] mod_wsgi (pid=2932): Starting process 'app' with threads=5.
[Tue Oct 16 23:08:38.896535 2018] [wsgi:info] [pid 2932] mod_wsgi (pid=2932): Initializing Python.
[Tue Oct 16 23:08:38.901116 2018] [wsgi:info] [pid 2926] mod_wsgi (pid=2926): Terminating Python.
[Tue Oct 16 23:08:38.908279 2018] [wsgi:info] [pid 2926] mod_wsgi (pid=2926): Python has shutdown.
[Tue Oct 16 23:08:38.924792 2018] [wsgi:info] [pid 2932] mod_wsgi (pid=2932): Attach interpreter ''.
[Tue Oct 16 23:08:38.935445 2018] [wsgi:info] [pid 2932] mod_wsgi (pid=2932): Adding '...path...' to path.
[Tue Oct 16 23:08:38.935744 2018] [wsgi:info] [pid 2932] mod_wsgi (pid=2932): Adding '...path...' to path.
[Tue Oct 16 23:08:38.935957 2018] [wsgi:info] [pid 2932] mod_wsgi (pid=2932): Adding '...path...' to path.
[Tue Oct 16 23:08:38.936897 2018] [wsgi:debug] [pid 2932] src/server/mod_wsgi.c(8908): mod_wsgi (pid=2932): Started thread 0 in daemon process 'app'.
[Tue Oct 16 23:08:38.936910 2018] [wsgi:debug] [pid 2932] src/server/mod_wsgi.c(8908): mod_wsgi (pid=2932): Started thread 1 in daemon process 'app'.
[Tue Oct 16 23:08:38.936956 2018] [wsgi:debug] [pid 2932] src/server/mod_wsgi.c(8908): mod_wsgi (pid=2932): Started thread 3 in daemon process 'app'.
[Tue Oct 16 23:08:38.936977 2018] [wsgi:debug] [pid 2932] src/server/mod_wsgi.c(8908): mod_wsgi (pid=2932): Started thread 2 in daemon process 'app'.
[Tue Oct 16 23:08:38.936988 2018] [wsgi:debug] [pid 2932] src/server/mod_wsgi.c(8908): mod_wsgi (pid=2932): Started thread 4 in daemon process 'app'.

### Numpy/Python version information:

Numpy: 1.15.2
Python 3.5.2

**Comment by mattip** [comment] 2018-10-17 05:06
Cannot reproduce the problem on my machine:
```
import numpy as np
n = 637
cf_mat = np.random.random((637, 68))
T = np.tril(np.ones((n, n)))
cum_cf = T.dot(cf_mat)
# Expected: a crash. Got: a result
```
It seems like the python process is dying. Can you run this code directly on the machine? What is the `dtype` of `cf_mat` just before the crash?

**Comment by njsmith** [comment] 2018-10-17 05:46
Do you get the crash if you use some other way of running the app besides `mod_wsgi`? `mod_wsgi` uses subinterpreters, which cause all kinds of havoc with numpy (and other C extension modules), so I don't know if that's related here but it's always a suspicion when we see mysterious issues + mod_wsgi together.

**Comment by seberg** [comment] 2022-05-21 17:25
Going to close this, since it is specific to a crtain setup and likely only with subinterpreters (which we do not quite support properly).

Happy to reopen the isuse though (or a new one to be opened).

**Closed by seberg** 2022-05-21 17:25 UTC
