### ISSUE TITLE
BUG: Inconsistent Length of Arrays Generated by np.arange with Floating-Point Steps

### ISSUE THREAD

**Issue by emrecemal** [numpy/numpy#26087] opened 2024-03-20 08:59 UTC
### Describe the issue:

I noticed that when using numpy.arange with floating-point steps, the inclusive endpoint behaves inconsistently. Sometimes, the range exceeds the expected endpoint. This occurs when creating an array with a range that should include the endpoint.

### Reproduce the code example:

```python
import numpy as np

a = np.arange(0, 901 * 0.001, 0.001)
print(len(a))  # Expected 901, and correctly prints 901

b = np.arange(0, 1001 * 0.001, 0.001)
print(len(b))  # Expected 1001, but prints 1002

c = np.arange(0, 0.901, 0.001)
print(len(c))  # Correctly prints 901

d = np.arange(0, 1.001, 0.001)
print(len(d))  # Correctly prints 1001
```

### Python and NumPy Versions:

1.26.4
3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

**Comment by mattip** [comment] 2024-03-20 09:20
Duplicate of many such issues. Please read the warning in the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange) about non-integer steps. The values you are using cannot be exactly represented by a computer's floating point numbers.

**Closed** 2024-03-20 10:01 UTC
Labels: 00 - Bug, 53 - Invalid
