### ISSUE TITLE
Cannot call numpy.sign on a pandas.Series

### ISSUE THREAD

**Issue by sirinath** [numpy/numpy#18826] opened 2021-04-21 17:46 UTC
I am getting the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-64d25859301b> in <module>
      8 stat.loc[:, 'Position'] += stat.loc[:, 'MFI1']
      9 stat.loc[:, 'Position'] += stat.loc[:, 'MFI2']
---> 10 stat.loc[:, 'Position'] += np.sign(stat.loc[:, 'MFI1Fast'] - 0.5)
     11 stat.loc[:, 'Position'] += np.sign(stat.loc[:, 'MFI1Slow'] - 0.5)
     12 stat.loc[:, 'Position'] += np.sign(stat.loc[:, 'MFI2Fast'] - 0.5)

C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\generic.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   1934         self, ufunc: Callable, method: str, *inputs: Any, **kwargs: Any
   1935     ):
-> 1936         return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
   1937 
   1938     # ideally we would define this to avoid the getattr checks, but

C:\ProgramData\Miniconda3\lib\site-packages\pandas\core\arraylike.py in array_ufunc(self, ufunc, method, *inputs, **kwargs)
    356         # ufunc(series, ...)
    357         inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
--> 358         result = getattr(ufunc, method)(*inputs, **kwargs)
    359     else:
    360         # ufunc(dataframe)

TypeError: unorderable types for comparison
```

`stat` is a `DataFrame` hence `stat.loc[:, 'Position']` is an `Series`

**Comment by BvB93** [comment] 2021-04-21 17:59
What exactly is the content here of `stat.loc[:, 'Position']`?
I can't reproduce the issue with a simple integer series (pandas 1.2.4, numpy 1.21.0.dev):
```  python
In [1]: import numpy as np
   ...: import pandas as pd

In [2]: s = pd.Series(np.arange(10))

In [3]: np.sign(s)
Out[3]:
0    0
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int32
```

**Comment by seberg** [comment] 2021-04-21 21:23
It could be an object array containing a NaN or NA (masked value), which is in fact not properly orderable.  The error is set by numpy so could be modified or I suppose a case be made for changing it. But since the input is probably an `object` and not float, my first gut feeling is that raising an error is correct.

**Comment by sirinath** [comment] 2021-04-22 01:02
`stat.loc[:, 'MFI1Fast']`

```
AAF.N0000     0.438611
AAIC.N0000    0.412539
ABAN.N0000      0.0549
ABL.N0000     0.393552
ACAP.N0000    0.736537
                ...   
VONE.N0000    0.807948
VPEL.N0000    0.654168
WAPO.N0000    0.628006
WATA.N0000    0.088078
YORK.N0000    0.493403
Name: MFI1Fast, Length: 287, dtype: object
```

**Comment by seberg** [comment] 2021-04-26 16:01
I will stick with it being correct and close the issue. Since there is no protocol for the sign, I don't think we can change NumPy to do it (obviously ufuncs could special case python floats, I am personally not a fan of that idea and we have issues about that I think).

**Closed by seberg** 2021-04-26 16:01 UTC
