### ISSUE TITLE
linalg/tests/test_build.py incorrectly reports both g77 and gfortran (Trac #1519)

### ISSUE THREAD

**Issue by thouis** [numpy/numpy#2116] opened 2012-10-19 21:06 UTC
_Original ticket http://projects.scipy.org/numpy/ticket/1519 on 2010-06-23 by trac user gvubrugier, assigned to unknown._

If "libgfortran" appears twice in the output of ldd, the test suite will fail although libg2c does not appear. For example:

ldd /usr/lib/python2.6/site-packages/numpy/linalg/lapack_lite.so
    linux-gate.so.1 =>  (0xffffe000)
    liblapack.so.3.0 => /usr/lib/sse2/liblapack.so.3.0 (0xb7105000)
    libf77blas.so.1.1 => /usr/lib/sse2/libf77blas.so.1.1 (0xb70e9000)
    libcblas.so.1.1 => /usr/lib/sse2/libcblas.so.1.1 (0xb70ca000)
    libatlas.so.3.0 => /usr/lib/sse2/libatlas.so.3.0 (0xb6b6e000)
    libgfortran.so.3 => /usr/lib/libgfortran.so.3 (0xb6ab3000)
    libm.so.6 => /lib/i686/libm.so.6 (0xb6a8d000)
    libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6a7f000)
    libc.so.6 => /lib/i686/libc.so.6 (0xb6931000)
    libblas.so.1.1 => /usr/lib/sse2/libblas.so.1.1 (0xb63a2000)
    libgfortran.so.2 => /usr/lib/libgfortran.so.2 (0xb6304000)
    /lib/ld-linux.so.2 (0xb77ff000)

Possible solution:
    The "founds" variable in grep_dependencies() should be a 
    set.

**Comment by mattip** [comment] 2019-08-18 16:24
I think we should close this as a "won't fix" since linking with two versions of libgfortran sounds like a recipe for disaster. Please reopen if you disagree and/or can reproduce.

**Closed by mattip** 2019-08-18 16:24 UTC
Labels: 00 - Bug, component: Other
