### ISSUE TITLE
f2py fails for functions returning character(len=len(input_string))

### ISSUE THREAD

**Issue by chatcannon** [numpy/numpy#3425] opened 2013-06-12 10:14 UTC
I've written simple toupper() and tolower() functions in Fortran that start like this:

``` fortran
pure function toupper(str)
  character(len=*) intent(in) :: str
  character(len=len(str)) :: toupper
  ...
```

When wrapping these with f2py, I get an error looking like this:

> /tmp/tmpmrZ5Ra/src.linux-x86_64-2.7/RMCfunctionsmodule.c: In function ‘f2py_rout_RMCfunctions_mod_functions_toupper’:
> /tmp/tmpmrZ5Ra/src.linux-x86_64-2.7/RMCfunctionsmodule.c:926:23: error: ‘str_Dims’ undeclared (first use in this function)
> 
> ``` c
> slen(toupper) = len(str);
>                       ^
> ```

I guess the `len(str)` needs to be replaced by `slen(str)`.

This problem occurs with both f2py-2.7 and f2py-3.3
It does not depend on the name of the variable `str` - I tried a couple of other names.

**Comment by Goutte** [comment] 2021-04-07 00:51
I can confirm the issue is still here in numpy `1.20`.
Barring a fix (it's been 8 years), any tip on how to bypass this issue would be welcome!

**Comment by melissawm** [comment] 2021-05-13 19:21
Here's what I've managed to get so far:

1. Wrapping the following:
```fortran
  pure function test(str)
    character(len=*), intent(in) :: str
    character(len=len(str)) :: test
    integer :: i

    test(1:1) = 'A'
    do i = 2, len(str)
       test(i:i) = str(i:i)
    enddo
    
  end function test
```
I get:
```bash
/tmp/tmpdg8zrhbc/src.linux-x86_64-3.9/stringsmodule.c: In function 'f2py_rout_strings_strings_test':
/tmp/tmpdg8zrhbc/src.linux-x86_64-3.9/stringsmodule.c:279:20: error: 'str_Dims' undeclared (first use in this function)
  279 |   slen(test) = len(str);
      |                    ^~~
```

2. I tried using a subroutine, with the following signature file:
```fortran
python module strings ! in 
    interface  ! in :strings
        module strings ! in :strings:strings.f90
            subroutine test(str, a) ! in :strings:strings.f90:strings
                character*(*) intent(in) :: str
                character*len(str) intent(out) :: a
            end subroutine test
        end module strings
    end interface 
end python module strings
```
Running `$ f2py -c strings.f90 strings.pyf` compiles fine, but

```python
>>> import strings
>>> print(strings.strings.test.__doc__)  # should return a as output, but returns
test(str,a)

Wrapper for ``test``.

Parameters
----------
str : input string(len=-1)
a : input string(len=1)
```

(note the incorrect intent for `a`)

3. Changing `strings.pyf` to use `character(len=slen(str)), intent(out) :: a` runs fine and works.

So the problem seems to be when using a function but not a subroutine.

When inspecting the code, IIUC the problem comes from the fact that we need to use `slen` for the C function wrapper, but `len` for the fortran function wrapper (both generated by f2py). 

My question to @pearu is if we should require the use of the `slen` expression in the pyf file in this case, or try to fix this from f2py itself, considering the two separate cases of the fortran and C function wrappers.

**Comment by pearu** [comment] 2021-05-31 13:52
My first reaction (without looking at code) is that f2py should be fixed by replacing `len(..)` call with `slen(..)` when `len` is used in the context of character `len` specification. Note that there are three kinds of length functions involved here: `slen` and `len` defined by f2py and to be used withing .pyf files, and `len` that is Fortran intrinsic. f2py `len` should be used in the context of arrays while f2py `slen` in the context of character types.

**Closed** 2022-06-06 15:46 UTC
Labels: 00 - Bug, component: numpy.f2py
