### ISSUE TITLE
`numpy.mgrid` creates an extra row due to FP error

### ISSUE THREAD

**Issue by bhaveshshrimali** [numpy/numpy#10636] opened 2018-02-20 19:25 UTC
It has to do with FP but I think it is still precarious considering a 'small' error changes the entire mesh. 
Following is an MWE 
```
>>>np.mgrid[0.:0.5+0.5/2:0.5/2, 0.:0.2+0.2/2:0.2/2].reshape(2,-1).T
array([[ 0.  ,  0.  ],
       [ 0.  ,  0.1 ],
       [ 0.  ,  0.2 ],
       [ 0.  ,  0.3 ],
       [ 0.25,  0.  ],
       [ 0.25,  0.1 ],
       [ 0.25,  0.2 ],
       [ 0.25,  0.3 ],
       [ 0.5 ,  0.  ],
       [ 0.5 ,  0.1 ],
       [ 0.5 ,  0.2 ],
       [ 0.5 ,  0.3 ]])`
```

which is due to the FP representation of `0.1+0.2`

However if I use the following, I get the expected result
```
>>> np.mgrid[0.:0.75:0.25, 0.:0.3:0.1].reshape(2,-1).T
array([[ 0.  ,  0.  ],
       [ 0.  ,  0.1 ],
       [ 0.  ,  0.2 ],
       [ 0.25,  0.  ],
       [ 0.25,  0.1 ],
       [ 0.25,  0.2 ],
       [ 0.5 ,  0.  ],
       [ 0.5 ,  0.1 ],
       [ 0.5 ,  0.2 ]])`
```

A silly workaround would be use only the first few (~16) decimal places for such cases but I do think that `float(format(0.1+0.2,'.16f'))` is not very natural to many people

**Comment by eric-wieser** [comment] 2018-02-20 19:42
This precariousness is inherited from the floating point numbers themselves:
```
>>> p1 = 0.1   # avoid constant folding
>>> p2 = 0.2
>>> p3 = 0.3

>>> (p1 + p2) / p1
3.0000000000000004
>>> ceil(_)
4
>>> p3 / p1
2.9999999999999996
>>> ceil(_)
3
```

That's the division that happens inside `mgrid`. In one case, it decides on 4 steps, and in the other, 3.

**Comment by eric-wieser** [comment] 2018-02-20 19:43
Essentially a duplicate of #9694, since mgrid is just a wrapper around arange

**Closed by eric-wieser** 2018-02-20 19:43 UTC
