### ISSUE TITLE
Trying to install Numpy with ATLAS already present fails with "mismatched quote

### ISSUE THREAD

**Issue by UnitedMarsupials** [numpy/numpy#11974] opened 2018-09-17 20:29 UTC
The simple `pip3 install numpy` worked the first time I tried it on this RHEL6 system. Then I added the `atlas-devel` (and `atlas`) packages via yum, uninstalled and tried installing it again.

### Reproducing code example:

`pip3 install numpy`

### Error message:

The error is triggered by an attempt to pass `-DATLAS_INFO="\"3.8.4\""` to the compiler. Somehow this results in a bunch of "unmatched quote" errors.

I'm including the full output of the (failed) install: 
[numpy-install.log](https://github.com/numpy/numpy/files/2390146/numpy-install.log). It ends with:

`error: Command "/prod/pfe/local/bin/gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O3 -march=native -pipe -O3 -march=native -pipe -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -DATLAS_INFO="\"3.8.4\"" -I/usr/include -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Inumpy/core/include -Ibuild/src.linux-x86_64-3.6/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/prod/pfe/local/include/python3.6 -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -c numpy/core/src/multiarray/temp_elide.c -o build/temp.linux-x86_64-3.6/numpy/core/src/multiarray/temp_elide.o -MMD -MF build/temp.linux-x86_64-3.6/numpy/core/src/multiarray/temp_elide.o.d" failed with exit status 1`
### Numpy/Python version information:

Trying to install the latest numpy (1.15.1 at this time). Python-3.6.6.

**Comment by UnitedMarsupials** [comment] 2018-09-17 21:08
I can force numpy to install by adding `ATLAS=None` to the environment. But then trying to install scipy fails with the same mismatched quote error (see scipy/scipy#9270). And, unlike numpy, scipy can not be installed without one of the accelerated libraries...

It seems, the code (in `numpy.distutils`?) trying to process the strings in the defines is subtly broken...

**Comment by charris** [comment] 2018-09-17 21:18
Could be a problem somewhere, the ATLAS version is long obsolete and probably seldom tested, but I never had a problem with it when it was still current.

**Comment by UnitedMarsupials** [comment] 2018-09-17 21:48
BTW, maybe, it is not the quoting style that changed, but the method of invoking the compiler (`system` vs. `exec`)? Changed to expect a different kind/level of escaping for the special characters? Because I see in 1.12.1's build the same command-line: 
`compile options: '-DATLAS_INFO="\"3.8.4\"" -I/usr/include -Inumpy/core/include -Ibuild/src.linux-x86_64-3.6/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/prod/pfe/local/include/python3.6 -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -Ibuild/src.linux-x86_64-3.6/numpy/core/src/private -c'`
but it works, whereas in 1.13.0 and above it does not...

**Comment by charris** [comment] 2018-09-17 22:33
Offhand, I see three possibilities, #7862, #8824, and #9050 with the first most likely.

**Comment by UnitedMarsupials** [comment] 2018-09-17 22:49
Yes, undoing the #7862 did the trick. I'm puzzled, how no one noticed this problem in 18 months...

**Comment by charris** [comment] 2018-09-17 23:08
Hmm, I cannot reproduce with 1.13.0.

- Python 3.6.6
- gcc version 8.1.1
- pip 9.0.1
- bash shell

**Comment by charris** [comment] 2018-09-17 23:10
Didn't install with pip, though
```
python3 setup.py build -j 4 install --user &> install3.log
```

**Comment by charris** [comment] 2018-09-17 23:11
So I think you need and old version of ATLAS to see it.

**Comment by charris** [comment] 2018-09-18 00:05
I have `-DATLAS_INFO="\"3.10.3\"" ` and that works fine.

**Comment by charris** [comment] 2018-09-18 00:18
@pitrou Any ideas?

**Comment by UnitedMarsupials** [comment] 2018-09-18 00:28
> I have -DATLAS_INFO="\"3.10.3\"" and that works fine.

Could you post the output of `python3 setup.py build`, please? I'd like to compare... Thanks!

> Didn't install with pip, though

Why not? I'm actually trying to install through [Ansible's pip-module](https://docs.ansible.com/ansible/2.6/modules/pip_module.html) -- because I need the same installation on a whole bunch of computers... I already have to build a few things from source, and it is messy -- whatever is available via pip, I'd like to install as such. Are there known problems with that method?

**Comment by charris** [comment] 2018-09-18 00:40
> Why not?

I'm always changing versions around, forward and back, and need to clean out the install directory on a regular basis to keep things running. Pip just makes that a little bit harder.

> Could you post the output of python3 setup.py build,

[install3.log](https://github.com/numpy/numpy/files/2390720/install3.log)

**Comment by UnitedMarsupials** [comment] 2018-09-18 01:29
Ok, I know, what it is. My login shell is `tcsh`. Yours, I'm sure, is from the `sh`-family (most likely -- `bash`).

If I attempt `env SHELL=bash pip3 install numpy`, the mismatched quote problem goes away... What a "teachable moment"... Of course, numpy's distutils needs fixing to work regardless of the user's shell -- so this PR should remain open.

But, at least, now we have a work-around... Thank you for your help.

**Comment by charris** [comment] 2018-09-18 01:56
> My login shell is tcsh.

Thought that might be it, it was why I listed the shell above.

> Of course, numpy's distutils needs fixing to work regardless of the user's shell 

See bottom of #11824. There are several fixes in progress.

I'll close this as a duplicate of #11824 and #9970.

**Closed by charris** 2018-09-18 01:56 UTC
