### ISSUE TITLE
object array creation new conversion to int

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#3804] opened 2013-09-27 16:56 UTC
#3696 introduced a suble change in behavior for record arrays

``` python
import numpy as np
items = np.array([(1, 1), (2, 2)], dtype=[('f0', '<i4'), ('f1', '<i4')])
freq = [2, 1]
v = np.array([items, freq]).T
print map(type, v[1,0])
```

before the PR it keept the numpy scalars

```
[<type 'numpy.int32'>, <type 'numpy.int32'>]
```

now it converts them to python integers.

```
[<type 'int'>, <type 'int'>]
```

The reason seems to be that old code just copied the points of the object, while the new code goes through PyArray_CopyInto which calls dtype->get_element on each entry.
The get_elemnt of int arrays converts it to python integers in python2.

This causes a test failure in scipy where a int type array now compares false to the np.int32 type array (test_stats.py)

I'm not sure whats the best way to fix that or if it even should be fixed.

**Comment by ahaldane** [comment] 2015-03-08 15:01
it seems to me it should return a void scalar:

    >>> items = np.array([(1, 1), (2, 2)], dtype=[('f0', '<i4'), ('f1', '<i4')])
    >>> freq = [2, 1]
    >>> x = np.array([items, freq]).T[1,0]
    >>> type(x)
    numpy.void
    >>> x.dtype
    dtype([('f0', '<i4'), ('f1', '<i4')])

**Comment by ahaldane** [comment] 2015-03-08 15:45
I think the solution might be to add a new function `VOID_to_OBJECT` in `arraytypes.c.src`, instead of using `@FROMTYPE@_to_OBJECT` as used presently. Actually, if you look at `@FROMTYPE@_to_OBJECT` it seems to me that void types currently get cast to Object using `npy_char_getitem`, which seems wrong.

**Comment by ahaldane** [comment] 2015-03-14 17:35
After examining it a little more:

I think the problem here is that object arrays have two distinct (sometimes incompatible) functions: 1) to allow arrays containing arbitrary python objects, and 2) to cast numpy-numeric-types to python-numeric-types. The two functions are conflicting in this issue.

1) is useful for nested ndarrays of different lengths, or for arrays of special numeric types (eg mpmath's multiprecision objects). 2) is useful for large integers: In order to compute `arange(10) + 2**128` numpy casts to Object (converting to python integers) since python integers have arbitrary size.

Here are a few examples that helped me think about what was going on. The current rule seems to be: If the sub-sequences are the same length cast all elements to the closest compatible type (which may be object/python-types if there is any non-numeric element). If the sub-sequences are different length, create an object array but do not cast to object.

    def printtype(x):
        if isinstance(x, np.ndarray):
            if x.dtype == dtype('O'):
		return x.dtype, type(x[0])
            return x.dtype
        return type(x)
    printtypes = lambda a: (a.dtype, [printtype(x) for x in a])

    >>> printtypes( np.array([np.array([(1,),(2,),(3,)], dtype=[('f0', 'i4')]), [1,2,3]]) )
    (dtype('O'), [(dtype('O'), tuple), (dtype('O'), int)])

    >>> printtypes( np.array([np.array([(1,),(2,),(3,)], dtype=[('f0', 'i4')]), [1,2]]) )
    (dtype('O'), [dtype([('f0', '<i4')]), list])

    >>> printtypes( np.array([np.array([1,2,3]), [1,2]]) )
    (dtype('O'), [dtype('int64'), list])

    >>> printtypes( np.array([np.array([1,2,3]), [1,2,3]], dtype=np.object) )
    (dtype('O'), [(dtype('O'), int), (dtype('O'), int)])

    >>> printtypes( np.array([np.array([1,2,3]), [1,2,3]]) )
    (dtype('int64'), [dtype('int64'), dtype('int64')])

However we do it, I think there should be a way of creating object arrays both with and without casting to python types. What should that look like?

One far-out idea is doing `arange(10).astype(np.object)` could give you an object array where each element is an `np.int` scalar, while `arange(10).astype(np.pytype)` would give you an object array of python ints.

**Comment by charris** [comment] 2015-06-19 03:08
@seberg @ahaldane I'm going to remove this from the 1.10 blockers. Do you think is still need fixing at some point?

**Comment by njsmith** [comment] 2015-06-19 03:14
It looks to me like a valid bug, but it's not a 1.10 blocker in any sense.

**Comment by ahaldane** [comment] 2015-06-19 04:23
I agree with @njsmith, it's not urgent

**Comment by charris** [comment] 2016-01-12 20:43
Bumbing up to 1.12 release, and will continue to do so until someone steps up to fix this.

**Comment by seberg** [comment] 2020-09-09 18:45
I am going to close this. I think that gh-16876 basically half covers this, and its so many years ago that we should not worry about the initial "regression" anymore, I think.

**Closed by seberg** 2020-09-09 18:45 UTC
Labels: 06 - Regression, 54 - Needs decision
