### ISSUE TITLE
np.logical_and() issue

### ISSUE THREAD

**Issue by Luffy-Hll** [numpy/numpy#16491] opened 2020-06-03 13:58 UTC
```
yi=[0.3,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,1.0]
y=np.where(np.logical_and((y>=yi[j]),(y<yi[j+1])),j+(y-yi[j])/(yi[j+1]-yi[j]),y)
```
I want to normalize an array by list as shown above, but I find some errors of feed back values.
for example: 0.494 got normalize value of 8.4, the detail is as below. There's two **True** here by np.logical_and(), it makes no sense.
so I add trace back to check out what happend and why feed back 7.1, 
```
samples	00        11        22        33	44        55	66        77	88        y
0.494	**True**	    False    False    False    False    False	False    False	**True**     8.4
```
my samples values have about 10000 lines.
I want to upload my samples values but always warning: 'something went really wrong, and we can't process that file.'  I will try later.

### Reproducing code example:

```python
import numpy as np
y=df1['samples']
        y=np.array(y)

        y=np.array(y)

        yi=[0.3,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,1.0]
        yi=np.array(yi)
        ymin=yi.min()
        print('ymin',ymin)
        ymax=yi.max()

        y[y<ymin]=ymin
        y[y>ymax]=ymax
     
        for j in range(0, len(yi)-1):
            if j==0:
                print(j)
                df1['00']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==1:
                print(j)
                df1['11']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==2:
                print(j)
                df1['22']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==3:
                print(j)
                df1['33']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==4:
                print(j)
                df1['44']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==5:
                print(j)
                df1['55']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==6:
                print(j)
                df1['66']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==7:
                print(j)
                df1['77']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            if j==8:
                print(j)
                df1['88']=np.logical_and((y>=yi[j]),(y<yi[j+1]))
            y=np.where(np.logical_and((y>=yi[j]),(y<yi[j+1])),j+(y-yi[j])/(yi[j+1]-yi[j]),y)
         
        y=np.where(y==ymax,len(yi)-1,y)
```

### Numpy/Python version information:
1.18.4 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]

**Comment by eric-wieser** [comment] 2020-06-03 14:14
Are you looking for `np.interp`?

**Comment by Luffy-Hll** [comment] 2020-06-03 14:25
> 
> 
> Are you looking for `np.interp`?

No, actually I use map_coordinates. Firstly I normalize two np array and then map_coordinates(map,[array1,array2]). 
But here is something wrong with feedback value of np.logical_and().

**Comment by eric-wieser** [comment] 2020-06-03 14:36
So just to be clear, the repro is:
```
y = 0.494
yi=[0.3,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,1.0]
for j in range(0, len(yi)-1):
    y=np.where(np.logical_and((y>=yi[j]),(y<yi[j+1])),j+(y-yi[j])/(yi[j+1]-yi[j]),y)
y
```
which gives `8.4`.

We can immediately dismiss `logical_and` as the problem with:
```
y = 0.494
yi=[0.3,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,1.0]
for j in range(0, len(yi)-1):
    a = (y>=yi[j])
    b = (y<yi[j+1])
    c = np.logical_and(a, b)
    assert c == (a and b)  # check that logical_and is fine
    y=np.where(c, j+(y-yi[j])/(yi[j+1]-yi[j]), y)
```

So the conclusion is that the problem must lie somewhere else, presumably with your algorithm

**Comment by eric-wieser** [comment] 2020-06-03 14:37
Is this the output you want?
```
In [85]: np.interp(0.494, yi, np.arange(len(yi)))
Out[85]: 0.97
```

**Comment by Luffy-Hll** [comment] 2020-06-03 15:17
> 
> 
> So just to be clear, the repro is:
> 
> ```
> y = 0.494
> yi=[0.3,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,1.0]
> for j in range(0, len(yi)-1):
>     y=np.where(np.logical_and((y>=yi[j]),(y<yi[j+1])),j+(y-yi[j])/(yi[j+1]-yi[j]),y)
> y
> ```
> 
> which gives `8.4`.
> 
> We can immediately dismiss `logical_and` as the problem with:
> 
> ```
> y = 0.494
> yi=[0.3,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,1.0]
> for j in range(0, len(yi)-1):
>     a = (y>=yi[j])
>     b = (y<yi[j+1])
>     c = np.logical_and(a, b)
>     assert c == (a and b)  # check that logical_and is fine
>     y=np.where(c, j+(y-yi[j])/(yi[j+1]-yi[j]), y)
> ```
> 
> So the conclusion is that the problem must lie somewhere else, presumably with your algorithm

I mean for 10000 values, only Dozens return wrong value, others are OK. And when I pull out these numbers separately and calculate, it works fine.

**Comment by eric-wieser** [comment] 2020-06-03 15:19
Didn't I just show above that I can reproduce the issue with a single value?

**Comment by eric-wieser** [comment] 2020-06-03 15:52
I'm going to close this, because I can produce exactly the same (apparently unwanted) output without using numpy at all:
```python
y = 0.494
yi=[0.3,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,1.0]
for j in range(0, len(yi)-1):
    y=j+(y-yi[j])/(yi[j+1]-yi[j]) if (y>=yi[j]) and (y<yi[j+1])) else y
y  # 8.4
```

**Closed by eric-wieser** 2020-06-03 15:52 UTC
Labels: 33 - Question

**Comment by Luffy-Hll** [comment] 2020-06-04 01:27
> 
> 
> Didn't I just show in the comment you quote that I can reproduce the issue with a single value?

sorry to bother, you are right. 
it's algorithm issue.
