### ISSUE TITLE
Importing the numpy c-extensions failed

### ISSUE THREAD

**Issue by choikwunyu** [numpy/numpy#14666] opened 2019-10-09 04:26 UTC
Error popped up while trying to import numpy on Jupyter notebooks

### Reproducing code example:

Upgraded to Mac OX 10.15, and everything was fine for a while, and pandas_profiling disappeared, so I reinstalled it. Then it said NumPy had duplicates so I uninstalled NumPy (via Conda) until Conda could not detect any NumPy package. And then I encountered this error. 

Here are my current paths:
```
which -a python
/usr/bin/python

jupyter kernelspec list
Available kernels:
  ir         /Users/choikwunyu/Library/Jupyter/kernels/ir
  python3    /Users/choikwunyu/anaconda3/share/jupyter/kernels/python3

echo $PATH
/anaconda3/bin:~/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/Library/TeX/texbin
```

### Error message:

```ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/Users/choikwunyu/anaconda3/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/choikwunyu/anaconda3/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/choikwunyu/anaconda3/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-darwin.so
  Reason: image not found 
```

### Numpy/Python version information:

```-bash: syntax error near unexpected token `numpy.__version__,'-```

**Comment by mattip** [comment] 2019-12-08 13:14
Sorry it took so long to relate to this issue.
I think this is an issue with parts of conda being removed, so that a needed `libopenblas.dylib` cannot be found. I assume since time has passes since this was opened that the original reporter either solved the problem or reinstalled from scratch.

Closing, please reopen if needed with clear steps to reproduce.

**Closed by mattip** 2019-12-08 13:14 UTC
Labels: 32 - Installation
