### ISSUE TITLE
Find a BUG in numpy-1.11.1 : TypeError: unorderable types

### ISSUE THREAD

**Issue by Lvctao** [numpy/numpy#7947] opened 2016-08-19 07:11 UTC
I use numpy-1.11.1 doing image match, when I call method _unique_ in _arraysetops.py_, there was a **TypeError** occurred: 
`File "/System/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/lib/arraysetops.py", line 198, in unique
    ar.sort()
TypeError: unorderable types: dict() > dict()`

The factor is that in Python 3.5 `list.sort()` no longer accept the _cmp_ argument providing a comparison function. It should use the _Key_ argument instead of `ar.sort()`.
The reference documentation site is "_https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons_"

**Comment by jaimefrio** [comment] 2016-08-19 09:12
By the time it gets called, `ar` is a ndarray (or a subclass of it), not a list, so those changes don't apply here.

It looks like you are trying to find unique elements in an array of dictionaries? If that's the case, I'm afraid your use case is not supported. Could you share some sample code causing the error?

I think the best we can hope for here is to convey a more understandable error message.

**Comment by Lvctao** [comment] 2016-08-19 09:45
I just started to learn python, and is using Python3.5 to learn an image matching project (https://github.com/ascribe/image-match). It maybe improper to say it's a bug as a newcomer to Python. 
The detailed problem is decribed here https://github.com/ascribe/image-match/issues/38. My solution is delete `ar.sort()`, then the problem disappeared.
NOW, as newcomer, I do not know why this problem occurred, because my issue put up in the image matching project (https://github.com/ascribe/image-match/issues/38) was closed just now. I am sorry for saying it is a bug.

**Comment by jaimefrio** [comment] 2016-08-19 13:40
You are more than welcome to report any issue that you find, sorry if my reply came across otherwise. It is (much) better to close an issue as "not a bug", than to have a real bug go unnoticed because it was never reported.

So please, keep reporting anything suspicious that you find! And thanks a lot for taking the time to report this one. Since it seems like the root cause was not in numpy, I am going to close this one. But please, keep reporting, and feel free to ask for this to be reopened if you need further clarification.

Thanks again!

**Closed by jaimefrio** 2016-08-19 13:40 UTC
