### ISSUE TITLE
Change documentation to generate better stubs

### ISSUE THREAD

**Issue by b78** [numpy/numpy#17806] opened 2020-11-19 15:22 UTC
Pycharm generates numpy stubs from the documentation. For min the documentation is 
```
a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
```
which confuses Pycharm to think that initial is a required parameter.

Would it be possible to apply the following change?
```
:100644 100644 c9968f122 000000000 M	numpy/core/_add_newdocs.py

diff --git a/numpy/core/_add_newdocs.py b/numpy/core/_add_newdocs.py
index c9968f122..d6fd44e94 100644
--- a/numpy/core/_add_newdocs.py
+++ b/numpy/core/_add_newdocs.py
@@ -3227,7 +3227,7 @@ add_newdoc('numpy.core.multiarray', 'ndarray', ('itemset',
 
 add_newdoc('numpy.core.multiarray', 'ndarray', ('max',
     """
-    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
+    a.max(axis=None, out=None, keepdims=False, initial=None, where=True)
 
     Return the maximum along a given axis.
 
@@ -3257,7 +3257,7 @@ add_newdoc('numpy.core.multiarray', 'ndarray', ('mean',
 
 add_newdoc('numpy.core.multiarray', 'ndarray', ('min',
     """
-    a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
+    a.min(axis=None, out=None, keepdims=False, initial=None, where=True)
 
     Return the minimum along a given axis.
 
@@ -4738,7 +4738,7 @@ add_newdoc('numpy.core', 'ufunc', ('signature',
 
 add_newdoc('numpy.core', 'ufunc', ('reduce',
     """
-    reduce(array, axis=0, dtype=None, out=None, keepdims=False, initial=<no value>, where=True)
+    reduce(array, axis=0, dtype=None, out=None, keepdims=False, initial=None, where=True)
 
     Reduces `array`'s dimension by one, by applying ufunc along one axis.
```

**Comment by eric-wieser** [comment] 2020-11-19 17:31
The problem is that this wouldn't be correct. Passing `initial=None` gives a different result to not passing it at all.

**Comment by seberg** [comment] 2021-02-24 23:33
I am going to close this. If there is a clear solution to this, please propose it, the current proposal doesn't seem to quite fit.  Also we have type stubs now, so the problem is probably just gone.  And I am not sure we should work around the PyCharm "signature guessing" limitations to begin with.

**Closed by seberg** 2021-02-24 23:33 UTC
