### ISSUE TITLE
NEP50 Link is broken in devdocs

### ISSUE THREAD

**Issue by ernimd** [numpy/numpy#26371] opened 2024-05-02 11:34 UTC
https://github.com/numpy/numpy/blame/b2960879bbf90af0cc3e533d2721d3a30470b056/doc/source/release/2.0.0-notes.rst#L79

In the docs resolves to https://numpy.org/devdocs/release/NEP50

**Comment by melissawm** [comment] 2024-05-07 20:58
Our NEPs should be reachable via intersphinx mapping, so in this case we could use 
```
:ref:`NEP 50 <NEP50>`
```
instead of
```
`NEP 50 <NEP50>`_.
```
to create a link. Would you be willing to submit a PR for this @ernimd ? [Our contribution guidelines are here](https://numpy.org/devdocs/dev/index.html) 😄 

Just for information, I ran `grep -R "NEP"` in the doc/source folder and found a number of instances where neps are hardlinked instead of using the intersphinx mapping. Not sure if this is something we want to fix also?

**Comment by anushatomar13** [comment] 2024-05-16 07:01
Hi, @melissawm 
I would like to work on this issue. I have read the contribution guidelines. If the issue is not assigned already, could you please assign it to me?
Thanks

**Comment by melissawm** [comment] 2024-05-16 10:21
@anushatomar13 we do not assign issues, If you have a solution please submit your pull request. Thanks!

**Comment by anushatomar13** [comment] 2024-05-16 10:34
@melissawm 
I have created a pull request for the same. Please let me know if it looks fine or if any additional changes are required. 
https://github.com/numpy/numpy/pull/26453

Thanks

**Comment by Mukulikaa** [comment] 2024-06-16 15:12
Fixed by #26527.

**Closed by Mukulikaa** 2024-06-16 15:12 UTC
Labels: 04 - Documentation
