### ISSUE TITLE
PyPy has gone missing.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17281] opened 2020-09-10 02:32 UTC
```
+(/io/multibuild/common_utils.sh:469): install_pypy(): wget -nv https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.1-linux64.tar.bz2 -P downloads
https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.1-linux64.tar.bz2:
2020-09-10 02:11:44 ERROR 404: Not Found.
```

@mattip Any idea what is going on here? The needed package seems to be available at 
https://downloads.python.org/pypy/pypy3.6-v7.3.1-src.tar.bz2 for source. There is also a CentOS 6 compatible binary at https://downloads.python.org/pypy/pypy3.6-v7.3.1-linux64.tar.bz2. Should we be using one of those?

**Comment by mattip** [comment] 2020-09-10 04:04
Perhaps a duplicate of gh-16092? Is this on the release branch? I should have marked gh-16094 for backporting.

**Comment by charris** [comment] 2020-09-10 11:53
> Is this on the release branch?

Yes. The changelog says  gh-16094 was in 1.19.0... and `test_pypy` is the same in both master and the release branch. Looks like something in the wheels repo isn't working correctly.

**Comment by charris** [comment] 2020-09-10 11:59
The problem is `multibuild\common_utils.sh`, `PYPY_URL=https://bitbucket.org/pypy/pypy/downloads`. That looks to be the same reason the nightly builds are failing. That's actually good, I can fix things for the release without messing up the release branch.

**Comment by matthew-brett** [comment] 2020-09-10 12:02
Isn't the URL fixed in latest multibuild 'devel'?

**Comment by mattip** [comment] 2020-09-10 12:03
Ahh, this is multibuild/multibuild#348 which was merged, so indeed updating multibuild should fix it. Thanks @matthew-brett

**Comment by charris** [comment] 2020-09-10 12:41
OK, updated both `master` and `v1.19.x` branches of `numpy-wheels`.

**Comment by charris** [comment] 2020-09-10 13:10
Looks fixed. Note that the Anaconda nightly/staging repos don't allow overloading files with the same names :) I was curious about that so just redid the 1.19.2 release build and only the PyPy build succeeded, the others errored when trying to upload.

**Closed** 2020-09-10 13:11 UTC
