### ISSUE TITLE
Strange behavior when indexing by position and range at same time

### ISSUE THREAD

**Issue by Ced4** [numpy/numpy#11045] opened 2018-05-04 11:56 UTC
Hello,

I have identified a strange behavior when I was trying to slice a multidimensional array into a sub-array. If I have an array with the shape of e.g. `(1, 6, 200, 100, 6)` and want to slice it by indexing `[:, 0 :, range(0, 100, 10), 0]` I was assuming to get back an array of the shape `(1, 200, 10)` but instead I get the shape `(10, 1, 200)` - so somehow the range-sliced dimension is put to the front. This only happens if there is a specific index before the range-sliced dimension.
Maybe the following code snipped make it more clear:
```
>>> test = numpy.ones((1, 6, 200, 100, 6))
>>> test[:, 0, :, range(0, 100, 10), 0].shape
(10, 1, 200)
>>> test[:, :, :, range(0, 100, 10), 0].shape
(1, 6, 200, 10)
>>> test[:, 0, :, :, 0][:, :, range(0, 100, 10)].shape
(1, 200, 10)
```

The first output is unexpected, the second one is as expected and the third one is a workaround.
Is this behavior intended or do I miss something?

**Comment by jaimefrio** [comment] 2018-05-04 12:42
It is intended behavior. See #6256 for the latest proposal to fix this, which has been laying around for a couple of years without much more being done.

Am closing this, but feel free to ask for clarifications if something doesn't make sense!

**Closed by jaimefrio** 2018-05-04 12:42 UTC

**Comment by jaimefrio** [comment] 2018-05-04 12:46
My answer was a little too terse: if you don't feel like reading through the linked NEP, see #6370 for a similar issue with a shorter explanation of why the behavior is expected.
