### ISSUE TITLE
New errors after numpy and matplotlib upgrade to latest version.

### ISSUE THREAD

**Issue by mmcclish** [numpy/numpy#15983] opened 2020-04-15 13:32 UTC
I recently upgraded to the latest version of numpy (1.18.1) and matplotlib (3.2.1). My python script was performing fine prior to the upgrade and now, it's hit with error messages. I'm running on python version 3.7.7. Below is the error message.

### Error message:
```
Traceback (most recent call last):
  File "C:\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "work5.py", line 435, in <module>
    readdata()
  File "work5.py", line 92, in readdata
    h, xh, yh = np.histogram2d(totals, psd, (NGbinNum,PSDbinNum), range = [ x_range, y_range ] )
  File "<__array_function__ internals>", line 6, in histogram2d
  File "C:\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\twodim_base.py", line 715, in histogram2d
    hist, edges = histogramdd([x, y], bins, range, normed, weights, density)
  File "<__array_function__ internals>", line 6, in histogramdd
  File "C:\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\histograms.py", line 1053, in histogramdd
    edges[i] = np.linspace(smin, smax, bins[i] + 1)
  File "<__array_function__ internals>", line 6, in linspace
  File "C:\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

**Comment by eric-wieser** [comment] 2020-04-15 13:41
Duplicate of #15821 I think

**Comment by eric-wieser** [comment] 2020-04-15 13:41
Duplicate of #15821

**Comment by eric-wieser** [comment] 2020-04-15 13:43
Ah, having said that we could produce a clearer error message here. Your issue appears to be that `NGbinNum` and `PSDbinNum` are `float`s, but asking for `1.1` histogram bins is nonsense, so they are required to be integers.

**Comment by mmcclish** [comment] 2020-04-15 13:44
Thank you for the timely reply. I will look into all of this. Much appreciated.

**Comment by eric-wieser** [comment] 2020-04-15 13:50
Closing in favor of #15984, which tracks producing a better error message.

**Closed by eric-wieser** 2020-04-15 13:50 UTC
