### ISSUE TITLE
BUG: incorrect promotion state when using multiple threads

### ISSUE THREAD

**Issue by colesbury** [numpy/numpy#23057] opened 2023-01-20 20:28 UTC
### Describe the issue:

For context, this issue originally came up in the context [1] of the nogil fork, but the problem exists in CPython as well, albeit rarely. The rest of this description is focused on CPython.

The dispatch/promotion logic temporarily swaps the `npy_promotion_state` to "weak". The problem is that `npy_promotion_state` is a global variable and `promote_and_get_info_and_ufuncimpl` can call functions that release the GIL, so the swap is sometimes visible to other threads. For example, it may allocate a tuple object, which can trigger a garbage collection cycle, which can call arbitrary Python code or destructors that may temporarily release the GIL.
 https://github.com/numpy/numpy/blob/df3751b03d789ee04cac3a9a8a7f7f3aba58735c/numpy/core/src/umath/dispatching.c#L956-L960

Additionally, the promotion state can be permanently set to "weak" in some interleavings:

```
npy_promotion_state=legacy

T1                                      T2
old_promotion_state=legacy
npy_promotion_state=weak
promote_and_get_info_and_ufuncimpl()
...                                     old_promotion_state=weak
...                                     npy_promotion_state=weak
...                                     promote_and_get_info_and_ufuncimpl()
npy_promotion_state=legacy              ...
                                        npy_promotion_state=weak

npy_promotion_state=weak !!
```

The code example reproduces this behavior. The default "legacy" promotion logic allows adding a large Python int to a np.uint8, butthe "weak" logic keeps the result as a np.uint8 leading to an OverflowError. The code is fairly contrived in order to reliably reproduce a rare failure. I've tested in on Python 3.9 with NumPy 1.24.0 on Linux -- it might not reproduce reliably on other versions of Python.

[1] https://github.com/colesbury/nogil/issues/102

### Reproduce the code example:

```python
import numpy as np
import threading
import gc
import time

nthreads = 8
N = 100
gc.set_threshold(10)

def callback(*args):
    # sleep to release the GIL briefly. In real code, this might
    # happen due to a destructor written in Python, for example.
    time.sleep(0.01)

gc.callbacks += [callback]

def run():
    for _ in range(N):
        # create a new ufunc
        def myadd(*args):
            return np.uint8(0) + sum(args)
        myadd = np.frompyfunc(myadd, 21, 1)

        # create a bunch of objects so that we are on the cusp of a GC cycle
        garbage = []
        while gc.get_count()[0] < 8:
            garbage.append({})
        myadd(*[255, *range(20)])

        # The promotion state should still be legacy
        assert np._get_promotion_state() == "legacy", f"{np._get_promotion_state()=}"

threads = []
for i in range(nthreads):
    threads.append(threading.Thread(target=run))
for t in threads:
    t.start()
for t in threads:
    t.join()
```

### Error message:

```shell
OverflowError: Python integer 445 out of bounds for uint8
```

### Runtime information:

NumPy 1.24.0
Python 3.9.2 (tags/v3.9.2:1a79785e3e, Oct 21 2021, 14:47:44)
[GCC 9.3.0]

### Context for the issue:

This is not an urgent issue, but I wanted to write it up so that it can possibly be addressed in the future.

**Comment by charris** [comment] 2023-01-20 20:37
@colesbury Thanks for the analysis.

**Comment by seberg** [comment] 2023-01-20 21:58
I know, this was never designed to be safe, because making it safe would be slow and I saw no purpose on it.  I thought I documented it to not be.

**Comment by seberg** [comment] 2023-01-20 22:03
OK, sorry, didn't look close enough.  The nogil work may also just warrent looking into it, but I had never thought of this going wrong by doing nested calls in threads... hmmm.

**Comment by seberg** [comment] 2023-01-21 09:09
Sorry, was a bit late yesterday, thanks for the nice report (silly me thought first it was about modifying it manually)!

I see you do alrady have a workaround using thread-locals!  Maybe that is even the way to go.  Threading the state into the functions is very annoying while also avoiding to break ABI (and at least astropy in some way).
I am still surprised the GIL gets released in this call-chain.

Anyway, I have to look into it a bit more.  It may be that only the "disable warnings" part of the code actually matters here and that is a very very niche use-case not useful for production anyway.

**Comment by lesteve** [comment] 2024-05-30 12:21
I am wondering whether this is still an issue with CPython 3.13.

I tried the snippet from the OP and I can't get it to fail anymore. I can't get the issue in the original reproducer in scikit-learn https://github.com/colesbury/nogil/issues/102#issue-1551116534.

**Comment by lesteve** [comment] 2024-05-30 12:21
And I guess it would be nice to use the `no-GIL` label for better tracking?

**Comment by seberg** [comment] 2024-05-30 12:35
This doesn't really matter at all with NumPy 2, it should also be fixed, so closing.  Ping @ngoldbaum just for awareness.

**Closed by seberg** 2024-05-30 12:35 UTC
Labels: 00 - Bug, component: numpy.ufunc

**Comment by ngoldbaum** [comment] 2024-05-30 13:02
Should be fixed now that the promotion state is thread-local, I think.

**Comment by lesteve** [comment] 2024-05-30 13:28
OK great to hear this has been fixed :pray:
