### ISSUE TITLE
Subset of 3d array returns an array with wrong shape

### ISSUE THREAD

**Issue by Didou09** [numpy/numpy#18059] opened 2020-12-23 11:55 UTC
### Reproducing code example:
```

In [118]: import numpy as np                                                                                                                                                                  

In [119]: a = np.random.random((5,6,7))                                                                                                                                                       

In [120]: a[0, :, [1,2]].shape                                                                                                                                                                
Out[120]: (2, 6)
```

one would expect shape `(6, 2)`...

Seems to occur only if the first index is set to a unique index and the last one to an iterable of indices

### NumPy/Python version information:

```
In [121]: import sys, numpy; print(numpy.__version__, sys.version)                                                                                                                            
1.18.1 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0]
```

**Comment by eric-wieser** [comment] 2020-12-23 12:01
Duplicate of #17276

**Closed** 2020-12-23 12:02 UTC
