### ISSUE TITLE
Calling np.fft.irfft simultaneously in multiple threads prevents handling of SIGINT

### ISSUE THREAD

**Issue by tedsta** [numpy/numpy#11798] opened 2018-08-21 23:20 UTC
When running `np.fft.irfft` or `np.fft.irfft2` simultaneously in multiple threads, it messes up something with the handling of SIGINT for the entire Python process. I even tried using the `signal` module to register a SIGINT handler separately. After starting the threads, whether they complete successfully or not, the process can no longer handle SIGINT.

### Reproducing code example:

Running forever, can't CTRL-C:

```python
import threading
import numpy as np
import time

def task(lock, done):
    while not done.is_set():
        # Try using the lock and see SIGINT handling restored
        #with lock:
        np.fft.irfft(np.array(range(10000)))
    print("Task done")

threads = []
done_event = threading.Event()
lock = threading.Lock()
for i in range(10):
    thread = threading.Thread(target=task, args=(lock, done_event))
    threads.append(thread)
    thread.start()

print("All tasks started")

try:
    while True:
        time.sleep(0.1)
except KeyboardInterrupt:
    print("Keyboard interrupt!")

print("Shutting down")
done_event.set()
for thread in threads:
    thread.join()
print("Shutdown successful")
```

Even weirder - can't CTRL-C even after the threads are finished:

```python
import threading
import numpy as np
import time

def task(lock, done):
    for i in range(100):
        if done.is_set():
            break
        # Try using the lock and see SIGINT handling restored
        #with lock:
        np.fft.irfft(np.array(range(10000)))
    print("Task done")

threads = []
done_event = threading.Event()
lock = threading.Lock()
for i in range(10):
    thread = threading.Thread(target=task, args=(lock, done_event))
    threads.append(thread)
    thread.start()

print("All tasks started")

try:
    while True:
        time.sleep(0.1)
except KeyboardInterrupt:
    print("Keyboard interrupt!")

print("Shutting down")
done_event.set()
for thread in threads:
    thread.join()
print("Shutdown successful")
```

### Numpy/Python version information:

1.15.1 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

EDIT: Running on Ubuntu 16.04

**Comment by charris** [comment] 2018-08-21 23:30
I assume this isn't a new problem?

**Comment by tedsta** [comment] 2018-08-21 23:47
Not sure, I just ran into it yesterday and narrowed it down to this today. If it helps, I was running on Numpy 1.13, noticed I was out of date, updated, but I still have the same issue.

This looks suspicious: https://github.com/numpy/numpy/blob/820765d762513510a8e46f108e8bc8b366127f8f/numpy/core/include/numpy/npy_interrupt.h#L36-L38

**Comment by tedsta** [comment] 2018-08-22 00:47
Ok, so I cloned master and built locally. Issue is still present, but goes away if I change this function to always return `True`:

https://github.com/numpy/numpy/blob/641058fb79a93aed6033ead31714d092abd27194/numpy/core/setup.py#L77-L80

**Comment by seberg** [comment] 2018-08-22 06:42
This is a very old problem IIRC, there may even still be a related one (with an open issue) causing crashes, and before ctrl+c did not work at all. Or maybe it changed to no segfaults and no ctrl+c does not work again, but that doesn't sound like a regression.

**Comment by seberg** [comment] 2018-08-22 06:44
Ah was thinking of this: https://github.com/numpy/numpy/issues/7545 so maybe that does not explain why it doesn't work, just would explain if it crashes hard instead of working.

**Comment by mreineck** [comment] 2019-08-01 11:26
I'm optimistic that this problem may be gone after the switch to pocketfft in numpy 1.17.

**Comment by seberg** [comment] 2019-08-01 16:45
@mreineck really, the sigint handling changed with pocketfft? I would have thought that happens in the basic wrapper?

**Comment by mreineck** [comment] 2019-08-01 17:35
> @mreineck really, the sigint handling changed with pocketfft? I would have thought that happens in the basic wrapper?

I don't remember changing the signal handling (and there are NPY_SIGINT_ON/OFF statements in the code), but it's definitely possible that I broke something by accident.

**Comment by mreineck** [comment] 2019-08-01 18:00
Sorry, I got totally confused by three simultaneous messages dealing with three different FFT problems.  Please ignore my last comments on this!

**Comment by mreineck** [comment] 2019-08-01 18:08
Given that
- messing with SIGINT seems to be really difficult to get right (see discussion in #7545)
- worst-case run-time of FFTs has increased a lot with pocketfft
- scipy's FFT seems to leave the interrupt handlers alone

...maybe it would be OK just to remove the SIGINT stuff?

**Comment by seberg** [comment] 2019-08-01 18:11
To be honest, maybe yes, the current solution is not really much good as well...

**Comment by seberg** [comment] 2019-08-01 19:32
Hmmm, it might work to check:
```
PyEval_ThreadsInitialized()
```
so that we can allow `SIGINT` handling when the program is obviously single threaded, but avoid it for multi threaded programs. Although, my guess is that by now (with ipython and things) most interactive sessions are not obviously single threaded.

**Comment by seberg** [comment] 2020-06-08 05:27
I just stumbled on this again, and decided that removing is probably the best course of action. I agree we should just remove it. There was maybe a reason for it when we did not have pocketfft which means that runtimes could be ridiculously slow occasionally. But that is just not the case anymore, and there is simply no good solutions.

**Comment by mreineck** [comment] 2020-06-08 08:16
I'm not sure what the plans for future `numpy` releases are, but if inclusion of C++ modules is on the table, it may be worth switching `numpy` to `scipy`'s implementation of `pocketfft`. The speedups are considerable, and the interface code is simpler.

**Comment by seberg** [comment] 2020-07-17 13:16
Closing, we removed the sigint handling from fft, its just not worth the trouble anymore.

**Closed by seberg** 2020-07-17 13:16 UTC
Labels: 00 - Bug, component: numpy.fft
