### ISSUE TITLE
 mistake output for np.arange()

### ISSUE THREAD

**Issue by decacent** [numpy/numpy#10505] opened 2018-02-01 08:16 UTC
I encounter a error output in using np,arange(), in python 3.5, numpy 1.13, windows 10 64 bit.

```py
np.arange(0.24,0.34,0.02)
Out[43]: array([ 0.24,  0.26,  0.28,  0.3 ,  0.32,  0.34])

np.arange(0.24,0.36,0.02)
Out[44]: array([ 0.24,  0.26,  0.28,  0.3 ,  0.32,  0.34])

np.arange(0,0.16,0.02)
Out[45]: array([ 0.  ,  0.02,  0.04,  0.06,  0.08,  0.1 ,  0.12,  0.14])

np.arange(0,0.14,0.02)
Out[46]: array([ 0.  ,  0.02,  0.04,  0.06,  0.08,  0.1 ,  0.12,  0.14])

np.arange(0.24,0.32,0.02)
Out[51]: array([ 0.24,  0.26,  0.28,  0.3 ,  0.32])

np.__version__
Out[48]: '1.13.3'

````

**Comment by eric-wieser** [comment] 2018-02-01 08:30
Duplicate of #9694. Expected behavior due to how floats work: https://0.30000000000000004.com/

```
>>> a = 0.34
>>> b = 0.24
>>> (a - b) / 0.02
5.000000000000002
```

**Closed by eric-wieser** 2018-02-01 08:30 UTC
