### ISSUE TITLE
numpy.power(1, numpy.nan) and numpy.power(numpy.nan, 0) return NaN on 32-bit Python 3.4

### ISSUE THREAD

**Issue by solariscp** [numpy/numpy#8931] opened 2017-04-12 14:34 UTC
In 32-bit Python 3.4.5, numpy v1.11.2 on Windows:

numpy.power(1, numpy.nan) returns NaN
numpy.power(numpy.nan, 0) returns NaN

In 64-bit Python 3.4.5, numpy v1.11.2 and 32-bit and 64-bit Python 3.5 with numpy v1.11.2, both of those calls return 1.

The behavior on 32-bit Python 3.4.5 numpy v1.11.2 seems incorrect.

**Comment by eric-wieser** [comment] 2017-04-12 14:41
Is this reproducible this on `master`?

If you fancy checking yourself, @solariscp, you can do so by cloning this repo and then running `runtests.py -i` in the source directory, which will open a python session with everything imported

**Comment by solariscp** [comment] 2017-04-12 19:15
Thanks for the instructions.

I am seeing the issue on the master branch with 32-bit Python 3.4.5 on Windows. 64-bit Python 3.4.5 doesn't have the issue, nor do Python 3.5 environments.

**Comment by eric-wieser** [comment] 2017-04-12 19:54
What is the output of the following on your setup with the issue?
```python
def builtin_t(x): return x
for t1 in [builtin_t, np.int32, np.int64, np.float32, np.float64]:
    for t2 in [builtin_t, np.float32, np.float64]:
        res1 = numpy.power(t1(1), t2(numpy.nan))
        res2 = numpy.power(t2(numpy.nan), t1(0))

        print(t1.__name__, t2.__name__, res1, res2)
```

**Comment by solariscp** [comment] 2017-04-17 21:06
nan nan builtin_t builtin_t
nan nan builtin_t float32
nan nan builtin_t float64
nan nan int32 builtin_t
nan nan int32 float32
nan nan int32 float64
nan nan int64 builtin_t
nan nan int64 float32
nan nan int64 float64
nan nan float32 builtin_t
nan nan float32 float32
nan nan float32 float64
nan nan float64 builtin_t
nan nan float64 float32
nan nan float64 float64

**Comment by eric-wieser** [comment] 2017-04-17 21:13
Apologies, that was the wrong thing to ask.

Can you repeat that but with `pow` instead of `numpy.power`?

**Comment by seberg** [comment] 2017-04-18 14:34
I expect these are differences in the platform pow implementation and not directly to do with numpy, to be honest.

**Comment by solariscp** [comment] 2017-04-19 19:12
Here are the results using pow:

1.0 1.0 builtin_t builtin_t
nan nan builtin_t float32
nan 1.0 builtin_t float64
nan nan int32 builtin_t
nan nan int32 float32
nan 1.0 int32 float64
nan nan int64 builtin_t
nan nan int64 float32
nan 1.0 int64 float64
nan nan float32 builtin_t
nan 1.0 float32 float32
nan 1.0 float32 float64
nan 1.0 float64 builtin_t
nan nan float64 float32
nan 1.0 float64 float64

**Comment by eric-wieser** [comment] 2017-04-19 21:03
Reassuring that the builtin `pow` works at least... 

So to summarize parts of that table:

* `t(nan) ** np.float64(0)` is correct for all x
* `1 ** nan` is broken for every data type in numpy

I find this particularly unsettling:
```
nan nan float32 builtin_t
nan 1.0 float32 float32
nan 1.0 float32 float64
nan 1.0 float64 float64
```

I was under the impression that numpy would evaluate this top case as one of the four cases below it - clearly it does not... What code path does `float32 ** float` take!?

**Comment by eric-wieser** [comment] 2017-04-19 21:08
Some other things to try then:

```
nan_32 = np.float32(np.nan)
nan_64 = np.float64(np.nan)

nan_64_from_32 = nan_32.astype(np.float64)
nan_32_from_64 = nan_64.astype(np.float32)

nans = [nan_32, nan_64, nan_64_from_32, nan_32_from_64]

for nan in nans:
    print("{!r} = {!r}".format(nan, nan[np.newaxis].view(np.uint8)))
```

**Comment by solariscp** [comment] 2017-05-03 18:13
Sorry for not responding to this a couple of weeks ago.

The code above gave me an error: ValueError: new type not compatible with array.

Making slight changes to the code (specifically adding a copy inside of the loop):

nan_32 = np.float32(np.nan)
nan_64 = np.float64(np.nan)

nan_64_from_32 = nan_32.astype(np.float64)
nan_32_from_64 = nan_64.astype(np.float32)

nans = [nan_32, nan_64, nan_64_from_32, nan_32_from_64]

for nan in nans:
    print("{!r} = {!r}".format(nan, nan[np.newaxis].copy().view(np.uint8)))

Here was the output:

nan = array([  0,   0, 192, 127], dtype=uint8)
nan = array([  0,   0,   0,   0,   0,   0, 248, 127], dtype=uint8)
nan = array([  0,   0,   0,   0,   0,   0, 248, 127], dtype=uint8)
nan = array([  0,   0, 192, 127], dtype=uint8)

**Comment by seberg** [comment] 2022-12-20 21:50
This seems indeed buggy on the given platform, but I am going to close it considering that it is a pretty old system:  Basically hoping that it is fixed by this point either by all relevant system libs (implementing C99 standard correctly).

If anyone (or the original author) still sees this type of behavior:  Please definitely open an issue, it is incorrect and even if the cause is probably a faulty system library we could consider blacklisting it.

**Closed by seberg** 2022-12-20 21:50 UTC
Labels: 00 - Bug, component: numpy.core
