### ISSUE TITLE
np.equal not implemented for string arrays?

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5399] opened 2014-12-27 19:58 UTC
https://github.com/scikit-learn/scikit-learn/issues/4014

```
a = np.array(['eggs', 'spam', 'spam', 'eggs', 'spam', 'spam', 'spam', 'spam',
    'spam', 'spam', 'spam', 'eggs', 'eggs', 'spam', 'eggs', 'eggs',
    'eggs', 'eggs', 'eggs', 'spam'],
    dtype='|S4')

b = np.array(['eggs', 'spam', 'spam', 'eggs', 'eggs', 'spam', 'spam', 'spam',
    'spam', 'eggs', 'spam', 'eggs', 'spam', 'eggs', 'spam', 'spam',
    'eggs', 'spam', 'spam', 'eggs'],
    dtype='|S4')

print(a == b)
print(np.equal(a, b))
```

```
[ True  True  True  True False  True  True  True  True False  True  True
 False False False False  True False False False]
NotImplemented
```

**Comment by bsipocz** [comment] 2019-08-16 02:45
Duplicate of #4470, please close.

**Comment by charris** [comment] 2019-08-16 03:01
Thanks @bsipocz .

**Closed** 2019-08-16 03:01 UTC
