### ISSUE TITLE
RuntimeError when importing numpy 1.19.4

### ISSUE THREAD

**Issue by songyang-dev** [numpy/numpy#17726] opened 2020-11-07 06:21 UTC
The newest version of numpy raises an exception when being imported. I am using Python 3.9 64-bit on Windows 10.

### Reproducing code example:

```python
import numpy as np # raises a RuntimeError
```

### Error message:

```
$ python -c "import numpy"
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Song\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\Song\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\Song\\AppData\\Roaming\\Python\\Python39\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```
### NumPy/Python version information:
NumPy 1.19.4
Python 3.9.0 (3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)])

**Comment by mattip** [comment] 2020-11-07 19:52
What did you find unsatisfactory at https://tinyurl.com/y3dm3h86 ?

**Comment by wonkodv** [comment] 2020-11-07 23:30
https://github.com/numpy/numpy/wiki/FMod-Bug-on-Windows

**Comment by szabi-luxonis** [comment] 2020-11-08 09:16
> The newest version of numpy raises an exception when being imported. I am using Python 3.9 64-bit on Windows 10.
> 
> ### Reproducing code example:
> ```python
> import numpy as np # raises a RuntimeError
> ```
> 
> ### Error message:
> ```
> $ python -c "import numpy"
>  ** On entry to DGEBAL parameter number  3 had an illegal value
>  ** On entry to DGEHRD  parameter number  2 had an illegal value
>  ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
>  ** On entry to DHSEQR parameter number  4 had an illegal value
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Song\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 305, in <module>
>     _win_os_check()
>   File "C:\Users\Song\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py", line 302, in _win_os_check
>     raise RuntimeError(msg.format(__file__)) from None
> RuntimeError: The current Numpy installation ('C:\\Users\\Song\\AppData\\Roaming\\Python\\Python39\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
> ```
> 
> ### NumPy/Python version information:
> NumPy 1.19.4
> Python 3.9.0 (3.9.0 (tags/v3.9.0:9cf6752, Oct 5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)])

Use `1.19.3` as a workaround until they fix it.

**Comment by thesauravkarmakar** [comment] 2020-11-12 07:46
Revert to `1.19.3`. 
Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an

**Comment by HilitOreny** [comment] 2020-11-16 02:35
I encountered the same problem as well. Just like you, I have Python 3.9 64-bit on Windows 10.
I tried to import pandas (which depends on Numpy), and got this error:

![image](https://user-images.githubusercontent.com/69712717/99206175-65812300-27c3-11eb-92ab-2d1dbdb45dc2.png)

```
Traceback (most recent call last):

File "C:\Users\yello\Documents\GitHub\SheCodes\Sustain\sustain_code_example.py", line 1, in <module>  import pandas

File "C:\Users\yello\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\__init__.py", line 11, in <module>
    __import__(dependency)

File "C:\Users\yello\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 305, in <module>    _win_os_check()

File "C:\Users\yello\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check

raise RuntimeError(msg.format(__file__)) from None

RuntimeError: The current Numpy installation ('C:\\Users\\yello\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

Note that I am using the Python Idle here. Since I do not use any IDE, I suspect that this problem is caused by Numpy, and not by an editor.  

I successfully uninstalled Numpy version 1.19.4, and installed Numpy version 1.19.3. Rolling back to Numpy 1.19.3 is a temporary fix. 

The problematic Numpy code seems to be:

```
def _win_os_check():
    """
    Quick Sanity check for Windows OS: look for fmod bug issue 16744.
    """
    try:
        a = arange(13 * 13, dtype= float64).reshape(13, 13)
        a = a % 17  # calls fmod
        linalg.eig(a)
    except Exception:
        msg = ("The current Numpy installation ({!r}) fails to "
                "pass a sanity check due to a bug in the windows runtime. "
                "See this issue for more information: "
                "https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html")
        raise RuntimeError(msg.format(__file__)) from None

if sys.platform == "win32" and sys.maxsize > 2**32:
    _win_os_check()

del _win_os_check
```

Can somebody please help? I have no idea how to fix this problematic code...

**Comment by arshiajs** [comment] 2020-11-17 06:51
I have this error too. Is anyone could help me ?

**Comment by mattip** [comment] 2020-11-17 08:05
`python -m pip install numpy==1.19.3`

**Comment by thesauravkarmakar** [comment] 2020-11-17 08:35
> I have this error too. Is anyone could help me ?

Revert to `1.19.3`. 
Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an

**Comment by arshiajs** [comment] 2020-11-17 08:39
> 
> 
> > I have this error too. Is anyone could help me ?
> 
> Revert to `1.19.3`.
> Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an

but i am using 1.19.3 and still got this error :|

**Comment by thesauravkarmakar** [comment] 2020-11-17 08:49
> > > I have this error too. Is anyone could help me ?
> > 
> > 
> > Revert to `1.19.3`.
> > Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an
> 
> but i am using 1.19.3 and still got this error :|

Try this numpy version `1.18.4` should work!

**Comment by Zenahr** [comment] 2020-11-26 09:16
@HilitOreny Had the same problem. Solved it via the answer from @mattip

```
pip uninstall pandas
python -m pip install numpy==1.19.3
pip install pandas
```

**Comment by andre1gauna** [comment] 2020-11-27 01:24
> What did you find unsatisfactory at https://tinyurl.com/y3dm3h86 ?

Have you even opened the link, my friend?

**Comment by andre1gauna** [comment] 2020-11-27 01:25
> `python -m pip install numpy==1.19.3`

Thank you very much!!

**Comment by GSZIEGL** [comment] 2020-11-28 18:04
> > > > I have this error too. Is anyone could help me ?
> > > 
> > > 
> > > Revert to `1.19.3`.
> > > Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an
> > 
> > 
> > but i am using 1.19.3 and still got this error :|
> 
> Try this numpy version `1.18.4`, it should work!

Hi,
I have the same problem. I Have already tried the 1.19.3 and also the 1.18.4 version but I get the same runtime error.
I don't have any other idea.
Any other comments?
Thx,
Gabor

**Comment by GSZIEGL** [comment] 2020-11-28 18:05
> @HilitOreny Had the same problem. Solved it via the answer from @mattip
> 
> ```
> pip uninstall pandas
> python -m pip install numpy==1.19.3
> pip install pandas
> ```

Hi,
I have tried this option and also the install of 1.19.3 / 1.18.4 veriosn without any success.
Any new ideas?
Thx
Gabor

**Comment by bkamantha** [comment] 2020-12-02 09:56
> `python -m pip install numpy==1.19.3`

its worked for me

**Comment by GSZIEGL** [comment] 2020-12-02 10:10
Thank you, i am gonna try it.
Have a nice day.

*Üdvözlettel:*
*Sziegl Gábor*
*30/774-0693*








BHANUKA KAMANTHA <notifications@github.com> ezt írta (időpont: 2020. dec.
2., Sze, 10:57):

**Comment by hehe24h** [comment] 2020-12-02 14:35
> `python -m pip install numpy==1.19.3`

work, thank you so much

**Comment by GSZIEGL** [comment] 2020-12-02 15:07
Hi all,

I tried your recommendation, but unfortunately I have the same error
message.
Do you have any other idea?
I paste the hole message, maybe there are also other problems:





























*DataSource.Error: ADO.NET <http://ADO.NET>: ΡУτђõⁿ ščŗϊφť εяŗóř.Traceback
(most recent call last):  File "PythonScriptWrapper.PY", line 2, in
<module>    import os, pandas, matplotlib  File
"C:\Gabi\Anaconda\envs\myenv\lib\site-packages\pandas\__init__.py", line
11, in <module>    __import__(dependency)  File
"C:\Gabi\Anaconda\envs\myenv\lib\site-packages\numpy\__init__.py", line
305, in <module>    _win_os_check()  File
"C:\Gabi\Anaconda\envs\myenv\lib\site-packages\numpy\__init__.py", line
302, in _win_os_check    raise RuntimeError(msg.format(__file__)) from
NoneRuntimeError: The current Numpy installation
('C:\\Gabi\\Anaconda\\envs\\myenv\\lib\\site-packages\\numpy\\__init__.py')
fails to pass a sanity check due to a bug in the windows runtime. See this
issue for more information: https://tinyurl.com/y3dm3h86
<https://tinyurl.com/y3dm3h86>Részletek:    DataSourceKind=Python
DataSourcePath=Python    Message=ΡУτђõⁿ ščŗϊφť εяŗóř.Traceback (most recent
call last):  File "PythonScriptWrapper.PY", line 2, in <module>    import
os, pandas, matplotlib  File
"C:\Gabi\Anaconda\envs\myenv\lib\site-packages\pandas\__init__.py", line
11, in <module>    __import__(dependency)  File
"C:\Gabi\Anaconda\envs\myenv\lib\site-packages\numpy\__init__.py", line
305, in <module>    _win_os_check()  File
"C:\Gabi\Anaconda\envs\myenv\lib\site-packages\numpy\__init__.py", line
302, in _win_os_check    raise RuntimeError(msg.format(__file__)) from
NoneRuntimeError: The current Numpy installation
('C:\\Gabi\\Anaconda\\envs\\myenv\\lib\\site-packages\\numpy\\__init__.py')
fails to pass a sanity check due to a bug in the windows runtime. See this
issue for more information: https://tinyurl.com/y3dm3h86
<https://tinyurl.com/y3dm3h86>    ErrorCode=-2147467259
ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException*


Thank you for your support again.

*Üdvözlettel:*
*Sziegl Gábor*
*30/774-0693*








Ròm Tiến Đạt <notifications@github.com> ezt írta (időpont: 2020. dec. 2.,
Sze, 15:35):

**Comment by yaswanth-github** [comment] 2020-12-03 02:31
> @HilitOreny Had the same problem. Solved it via the answer from @mattip
> 
> ```
> pip uninstall pandas
> python -m pip install numpy==1.19.3
> pip install pandas
> ```

it is working use this

**Comment by GSZIEGL** [comment] 2020-12-03 07:18
I have just tried it but no positive result. I have got the same error
message again.
Should I maybe delete Anaconda and Power BI and after that download/install
them again?

*Üdvözlettel:*
*Sziegl Gábor*
*30/774-0693*








yaswanth-github <notifications@github.com> ezt írta (időpont: 2020. dec.
3., Cs, 3:31):

**Comment by alaeltayeb** [comment] 2020-12-05 09:37
Hi , I faced the same problem but keep in mind am using sublime 3 as my python interface, am learning python and the data science  science overall so am quite a beginner so here's how I solved this, I installed numpy 1.19.3 instead of 1.19.4
i simply add this code in the command prompt 
pip install numpy==1.19.3
and my codes worked well!

**Comment by Saad-py** [comment] 2020-12-05 16:57
So I had the same error and my code was so simple that just import numpy and pandas open a csv file. I got nervous and frustrated with this error then I used the python IDLE for it and it worked.

Note I used python 3.7 and numpy 1.19.3


@GSZIEGL Hope you find this helpfull just use the IDLE

**Comment by Saad-py** [comment] 2020-12-05 16:58
> So I had the same error and my code was so simple that just import numpy and pandas open a csv file. I got nervous and frustrated with this error then I used the python IDLE for it and it worked.
> 
> Note I used python 3.7 and numpy 1.19.3
> 
> @GSZIEGL Hope you find this helpfull just use the IDLE

My problem was that I am using pycharm not the IDLE the IDLE does suppourt Kite which is not good but still gotta get it to work

**Comment by Saad-py** [comment] 2020-12-05 17:02
Solution:

pip uninstall pandas
pip uninstall numpy
pip install numpy==1.19.3
pip install pandas

If this doesen't works then try using the IDLE or VS code editor again VS CODE editor

**Comment by therealsteveross** [comment] 2020-12-06 16:40
> > `python -m pip install numpy==1.19.3`
> 
> Thank you very much!!

Thank you!  Worked after an hour of uninstalling and reinstalling Python.  I never would have figured this out.

**Comment by errorsolve** [comment] 2020-12-09 03:49
Here Is All Possible Solution added [**runtimeError: package fails to pass a sanity check for numpy and pandas in python**](https://exerror.com/runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-and-pandas/)

**Comment by phanirithvij** [comment] 2020-12-09 23:22
@mattip I would suggest updating the tiny URL link to point directly to the workaround [comment](https://developercommunity.visualstudio.com/comments/1242128/view.html) or https://github.com/numpy/numpy/issues/17726#issuecomment-728757954

https://developercommunity.visualstudio.com/comments/1242128/view.html

**Comment by andyitem** [comment] 2020-12-13 08:20
> > > I have this error too. Is anyone could help me ?
> > 
> > 
> > Revert to `1.19.3`.
> > Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an
> 
> but i am using 1.19.3 and still got this error :|

try using this :

python -m pip install numpy==1.19.3 --upgrade
python -m pip install xlrd==1.2.0 --upgrade

> > > I have this error too. Is anyone could help me ?
> > 
> > 
> > Revert to `1.19.3`.
> > Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an
> 
> but i am using 1.19.3 and still got this error :|

try using this :

python -m pip install numpy==1.19.3 --upgrade
python -m pip install xlrd==1.2.0 --upgrade

**Comment by andyitem** [comment] 2020-12-13 08:21
> > > I have this error too. Is anyone could help me ?
> > 
> > 
> > Revert to `1.19.3`.
> > Refer: https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an
> 
> but i am using 1.19.3 and still got this error :|

try using this :

python -m pip install numpy==1.19.3 --upgrade
python -m pip install xlrd==1.2.0 --upgrade

**Comment by cdle-net** [comment] 2020-12-16 13:47
I do this, comment line 295 of __init__.py 
http://diy.cdle.net/?p=1027

**Comment by Angeldsf7** [comment] 2020-12-18 07:49
> @HilitOreny Had the same problem. Solved it via the answer from @mattip
> 
> ```
> pip uninstall pandas
> python -m pip install numpy==1.19.3
> pip install pandas
> ```

I had the same problem, this worked . but I wasn't doing it right, you have to be sure that you chaged the version, if you are using PyCharm as I do , go to settings, select your proyect , python interpreter , click on + and add numpy, but be sure is the 1.19.3 version, you can change it right there. Thank you so much I was about to get dessesperated 👍

**Comment by kingsyard** [comment] 2021-05-24 15:43
to keep it simple

pip install numpy  
if then also you get the error try with some particular versions that your work may need.

like pip install numpy==0.9 like this check clearly which version of numpy you need.

if you couldnt install it then try

pip install --user numpy
second one is where you are providing permission.(granting user permission).

if you have got any other quarie you can contact us at www.smartaitechnologies.com for more

**Comment by seberg** [comment] 2023-06-09 13:58
Closing, this was a Microsoft windows bug to begin with.  And the versions are so old, nobody runs into it anymore.

**Closed by seberg** 2023-06-09 13:58 UTC
