### ISSUE TITLE
BUG: error Python 3.13 free-threaded `RuntimeError: Identity cache already includes the item.`

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#26690] opened 2024-06-14 08:58 UTC
### Describe the issue:

When using simple numpy operations in multiple threads, you sometimes get `RuntimeError: Identity cache already includes the item.`

Looks like this had already been noticed in some cases by @ogrisel with Python 3.9 nogil in https://github.com/numpy/numpy/issues/21337 2 years ago, although according to https://github.com/colesbury/nogil/issues/48#issuecomment-1098438898 it was fixed in the nogil Numpy https://github.com/colesbury/numpy/commits/v1.22.3-nogil. Maybe some changes have not been fully upstreamed?

cc @rgommers and @ngoldbaum.

I run the script below like this, which triggers the error eventually:
```bash
for i in $(seq 1 100); do PYTHON_GIL=0 python test-numpy.py; done     
```

Note that there is nothing special about `a.sum` below, you can trigger the same issue with `np.max`, `a != 1`, etc ...

### Reproduce the code example:

```python
import numpy as np
import threading, queue

a = np.ones(1000)

def f(*args, **kwargs):
    return a.sum()

q = queue.Queue()

def worker():
    while True:
        item = q.get()
        f(item)
        q.task_done()

for i in range(2):
    threading.Thread(target=worker, daemon=True, name=f"worker-{i}").start()

for item in range(100000):
    q.put(item)

q.join()
print("done")
```

### Error message:

```shell
Exception in thread worker-1:
Traceback (most recent call last):
  File "/opt/python-free-threading-release/lib/python3.13/threading.py", line 1039, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/opt/python-free-threading-release/lib/python3.13/threading.py", line 990, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/test-numpy2.py", line 15, in worker
    f(item)
    ~^^^^^^
  File "/tmp/test-numpy2.py", line 7, in f
    return a.sum()
           ~~~~~^^
  File "/home/lesteve/venvs/python3.13-free-threading-no-debug/lib/python3.13/site-packages/numpy/_core/_methods.py", line 52, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
RuntimeError: Identity cache already includes the item.
```

### Python and NumPy Versions:

```
2.1.0.dev0+git20240611.ee73d0d
3.13.0b1+ experimental free-threading build (heads/3.13:6892b400dc, May 24 2024, 17:10:10) [GCC 14.1.1 20240507]
```

### Runtime Environment:

```
[{'numpy_version': '2.1.0.dev0+git20240524.1f73030',
  'python': '3.13.0b1+ experimental free-threading build '
            '(heads/3.13:6892b400dc, May 24 2024, 17:10:10) [GCC 14.1.1 '
            '20240507]',
  'uname': uname_result(system='Linux', node='thinkpad', release='6.9.2-arch1-1', version='#1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'architecture': 'Haswell',
  'filepath': '/usr/lib/libopenblas.so.0.3',
  'internal_api': 'openblas',
  'num_threads': 12,
  'prefix': 'libopenblas',
  'threading_layer': 'openmp',
  'user_api': 'blas',
  'version': '0.3.27'},
 {'filepath': '/usr/lib/libgomp.so.1.0.0',
  'internal_api': 'openmp',
  'num_threads': 12,
  'prefix': 'libgomp',
  'user_api': 'openmp',
  'version': None}]
```

### Context for the issue:

This was actually observed first in scikit-learn test suite locally and in one [CI build](https://github.com/lesteve/scikit-learn/actions/runs/9501475134/job/26187089099)

<details>

```
  =================================== FAILURES ===================================
  ___________________ test_sgd_multiclass_njobs[SGDClassifier] ___________________
  joblib.externals.loky.process_executor._RemoteTraceback: 
  """
  Traceback (most recent call last):
    File "/tmp/tmp.QFChQugvDY/venv/lib/python3.13/site-packages/joblib/_utils.py", line 72, in __call__
      return self.func(**kwargs)
             ~~~~~~~~~^^^^^^^^^^
    File "/tmp/tmp.QFChQugvDY/venv/lib/python3.13/site-packages/joblib/parallel.py", line 598, in __call__
      return [func(*args, **kwargs)
              ~~~~^^^^^^^^^^^^^^^^^
    File "/tmp/tmp.QFChQugvDY/venv/lib/python3.13/site-packages/sklearn/utils/parallel.py", line 127, in __call__
      return self.function(*args, **kwargs)
             ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
    File "/tmp/tmp.QFChQugvDY/venv/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 436, in fit_binary
      y_i, coef, intercept, average_coef, average_intercept = _prepare_fit_binary(
                                                              ~~~~~~~~~~~~~~~~~~~^
          est, y, i, input_dtye=X.dtype
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      )
      ^
    File "/tmp/tmp.QFChQugvDY/venv/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py", line 343, in _prepare_fit_binary
      y_i[y != est.classes_[i]] = -1.0
          ^^^^^^^^^^^^^^^^^^^^
  RuntimeError: Identity cache already includes the item.
  """
  
  The above exception was the direct cause of the following exception:
  
  klass = <function SGDClassifier at 0x5de0cddbb80>
  
      @pytest.mark.parametrize("klass", [SGDClassifier, SparseSGDClassifier])
      def test_sgd_multiclass_njobs(klass):
          # Multi-class test case with multi-core support
  >       clf = klass(alpha=0.01, max_iter=20, n_jobs=2).fit(X2, Y2)
  
  ../venv/lib/python3.13/site-packages/sklearn/linear_model/tests/test_sgd.py:685: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  ../venv/lib/python3.13/site-packages/sklearn/base.py:1514: in wrapper
      return fit_method(estimator, *args, **kwargs)
  ../venv/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py:938: in fit
      return self._fit(
  ../venv/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py:725: in _fit
      self._partial_fit(
  ../venv/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py:649: in _partial_fit
      self._fit_multiclass(
  ../venv/lib/python3.13/site-packages/sklearn/linear_model/_stochastic_gradient.py:804: in _fit_multiclass
      result = Parallel(
  ../venv/lib/python3.13/site-packages/sklearn/utils/parallel.py:65: in __call__
      return super().__call__(iterable_with_config)
  ../venv/lib/python3.13/site-packages/joblib/parallel.py:2007: in __call__
      return output if self.return_generator else list(output)
  ../venv/lib/python3.13/site-packages/joblib/parallel.py:1650: in _get_outputs
      yield from self._retrieve()
  ../venv/lib/python3.13/site-packages/joblib/parallel.py:1754: in _retrieve
      self._raise_error_fast()
  ../venv/lib/python3.13/site-packages/joblib/parallel.py:1789: in _raise_error_fast
      error_job.get_result(self.timeout)
  ../venv/lib/python3.13/site-packages/joblib/parallel.py:745: in get_result
      return self._return_or_raise()
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <joblib.parallel.BatchCompletionCallBack object at 0x5de13e58d10>
  
      def _return_or_raise(self):
          try:
              if self.status == TASK_ERROR:
  >               raise self._result
  E               RuntimeError: Identity cache already includes the item.
  
  ../venv/lib/python3.13/site-packages/joblib/parallel.py:763: RuntimeError
```

</details>

**Comment by rgommers** [comment] 2024-06-14 09:05
Thanks for the report @lesteve. I suspect that this will be fixed by one of the PRs that @ngoldbaum has in progress (gh-26430).

**Comment by ngoldbaum** [comment] 2024-06-14 15:26
This is coming from the `PyArrayIdentityHash` code and should have been fixed by https://github.com/numpy/numpy/pull/26348, #26430 is unrelated.

I ran the reproducer 100 times on my Mac and didn't see any crashes. You say it triggers the error eventually, does the crash happen more often on Linux?

**Comment by ngoldbaum** [comment] 2024-06-14 15:47
Interesting: I can trigger after about 10 iterations of the bash for loop on an x86 ubuntu laptop. Will try to dig in further. We might need atomics here as well if this comes down to out-of-order execution breaking some assumption. Let me see if replacing the mutex with a global lock fixes it (albeit probably at the cost of increased lock contention).

**Comment by lesteve** [comment] 2024-06-14 15:52
Glad to hear that you can reproduce! For me as well it tend to crash before 10-20 iterations of the bash loop, I have never seen it reach iteration 100.

**Comment by ngoldbaum** [comment] 2024-06-14 16:39
I think I understand what's happening. Not sure why the race condition doesn't happen on a Mac, but at least under gcc it seems to be more likely to get into a situation where two threads simultaneously call `PyArrayIdentityHash_SetItem` with a cold cache. One thread wins the race and fills the cache. Another thread loses the race, waits on the other thread for the lock, then acquires it and tries to fill the dict entry. It sees the data filled in by the other thread and raises an exception.

When Sam did this in the nogil fork he set the option in `PyArrayIdentityHash_SetItem` to not check if any keys already exist, bypassing this exception.

However, as @mhvk pointed out in https://github.com/numpy/numpy/pull/26348#issuecomment-2081478479, users can define ufunc loops outside of NumPy, and not having an error here might be problematic if they are doing something unusual.

I think one way to fix this would be to acquire the lock earlier, before checking if the key exists in the cache, or maybe only after seeing that the cache is empty to optimize the happy path where the cache is hot. The key is that the locked section checks if the cache key is filled in already after acquiring the lock and after it already saw that the cache was cold. I think in that case it means a race condition happened and we couldn't trigger that if a user tried to replace a ufunc loop in situation where we want the error to happen.

**Comment by ngoldbaum** [comment] 2024-06-14 17:52
Here's an odd thing. If you apply the following diff:

```
diff --git a/numpy/_core/src/common/npy_hashtable.c b/numpy/_core/src/common/npy_hashtable.c
index 02fe5ca297..1d9f1ef96d 100644
--- a/numpy/_core/src/common/npy_hashtable.c
+++ b/numpy/_core/src/common/npy_hashtable.c
@@ -230,8 +230,9 @@ PyArrayIdentityHash_SetItem(PyArrayIdentityHash *tb,
     if (value != NULL) {
         if (tb_item[0] != NULL && !replace) {
             UNLOCK_TABLE(tb);
-            PyErr_SetString(PyExc_RuntimeError,
-                    "Identity cache already includes the item.");
+            PyErr_Format(PyExc_RuntimeError,
+                         "Identity cache already includes the item with key %S.",
+                         key);
             return -1;
         }
         tb_item[0] = value;
```

Then at least on the laptop where I can reproduce the crash, the crash goes away.

**Comment by mhvk** [comment] 2024-06-14 19:30
Yikes, sounds like gcc doing a misplaced optimization reordering for the existing case...

**Comment by ngoldbaum** [comment] 2024-06-14 20:05
I don't think it's due to optimization, it still happens in a debug build with no optimization and when I look at the disassembly with `disassemble /s` under gdb there's no reordering happening with no optimization.

**Comment by ngoldbaum** [comment] 2024-06-14 20:55
Opened #26693 with a possible fix.

**Closed** 2024-06-18 20:02 UTC
Labels: 00 - Bug, 39 - no-GIL
