### ISSUE TITLE
c api call to gemm

### ISSUE THREAD

**Issue by nouiz** [numpy/numpy#8229] opened 2016-11-01 16:54 UTC
It would be useful to us and I'm pretty sure to other people to be able to call gemm in C.
There is the file numpy/core/src/multiarray/cblasfuncs.c that contain this function:

```
static void
gemm(int typenum, enum CBLAS_ORDER order,
     enum CBLAS_TRANSPOSE transA, enum CBLAS_TRANSPOSE transB,
     int m, int n, int k,
     PyArrayObject *A, int lda, PyArrayObject *B, int ldb, PyArrayObject *R)
```

Giving access to it would solve this, this function is currently private and do not do error checking. The function:
```
NPY_NO_EXPORT PyObject *
cblas_matrixproduct(int typenum, PyArrayObject *ap1, PyArrayObject *ap2,
                    PyArrayObject *out)
```

In the same file does the error checking, but do not allow the alpha and beta parameter.

Before going further and plan how to implement it. Would a PR that add a public function PyArray_Gemm that take the 3 ndarray + alpha + beta be accepted?

**Comment by njsmith** [comment] 2016-11-01 16:59
This is a duplicate of #6324, there's some discussion there.

**Closed** 2016-11-01 20:39 UTC
