### ISSUE TITLE
np asarray  not work on np.random.uniform res

### ISSUE THREAD

**Issue by xjoyzaza** [numpy/numpy#14246] opened 2019-08-10 14:22 UTC
### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by rkern** [comment] 2019-08-10 16:32
Can you edit this to provide a reproducing code example? I'm not seeing any problem, if I'm interpreting your title correctly.

```
[scratch]
|1> np.asarray(np.random.uniform(0, 1, size=10))
array([0.66759245, 0.79366748, 0.41458603, 0.02768129, 0.43916962,
       0.19435865, 0.50987383, 0.36459251, 0.29724832, 0.43831547])

[scratch]
|2> np.asarray(np.random.uniform(0, 1))
array(0.27012336)
```

**Comment by xjoyzaza** [comment] 2019-08-11 01:47
you can try random a 2d array : uniform = np.random.uniform(-1,1,(10,10)) which type is ndarray
then transfer it to list   uniform = uniform.tolist()
then try to  convert it to ndarray again uniform =  np.asarray(uniform)  which type is still list...

**Comment by seberg** [comment] 2019-08-11 02:02
@xjoyzaza , that will still give you an array. I am going to close this for now, please give a specific example and I am happy to reopen.

**Closed by seberg** 2019-08-11 02:02 UTC

**Comment by xjoyzaza** [comment] 2019-08-11 13:18
you can run this :
res = np.random.uniform(-1,1,(10,10)).tolist() 
res = np.asarray(res)

then you can get a res is a list not a ndarray.

**Comment by xjoyzaza** [comment] 2019-08-11 13:22
in addition vstack on  uniform result return List type too  : 
```
 res = np.array([]).reshape(0, 10)
 initials =np.random.uniform(-1,1,(10,10))
 res = np.vstack([res, initials])
```

**Comment by mattip** [comment] 2019-08-11 13:32
```python
res = np.random.uniform(-1,1,(10,10)).tolist()
res2 = np.asarray(res)
```

works fine for me. What version of python, numpy are you using, and where did you get them?

**Comment by seberg** [comment] 2019-08-11 13:51
Honestly, I am starting to think you are just using `print` and because arrays print much like a nested list think it is a list. Try `repr()`.

**Comment by xjoyzaza** [comment] 2019-08-11 14:17
is strange , i feed it to keras weight which expect 1 weight it cause a error :
with a  weight list of length 4, but the layer was expecting 1 weights. Provided weights: [[] ...]
