### ISSUE TITLE
np.in1d bug on the object array

### ISSUE THREAD

**Issue by ray306** [numpy/numpy#17923] opened 2020-12-04 23:49 UTC
The `np.in1d`  method (Numpy 1.19.1, Python 3.8.3) makes some errors on the irregular-object array:

**Case 1:**
```python
np.in1d([(1,), 2], [(1,), 2])
```
The output should be `[True,  True]` but it says:
### Error message:
```python
array([False,  True])
```

**Case 2:**
```python
np.in1d([(1,), (2,)], [(1,), 2])
```
The output should be `[True,  False]` but it says:
### Error message:
```python
array([True,  True])
```

**Comment by tylerjereddy** [comment] 2020-12-15 03:44
`np.isin()` had the same behavior (calls `np.in1d()`). Not sure if a brute force pure Python loop to check element-wise equality would be an acceptable or desirable fix, although the code is kind of half way there already with a pure Python iteration through the elements in the second argument.

Assuming that probably wouldn't fly though, I noticed that `np.testing.assert_array_equal()` does have the machinery to correctly recognize the number of matching and non-matching elements for the inputs provided. I don't know if that machinery is substantially faster than the brute force Python looping offhand.

**Comment by seberg** [comment] 2020-12-17 22:33
I had discussed this briefly with Tyler, and we found that the root cause are these lines of code:
https://github.com/numpy/numpy/blob/225c3360721ba515de88a1e191ede58e8b95593d/numpy/lib/arraysetops.py#L582-L583

The issue here is that the for loop `a` is the plain python object and not an array. The `==` will than effectively call `np.asarray(a, dtype=object)`, which causes the tuple to be unpacked.

The solution could be to write the for loop like this (for object arrays): `for a in (arr[i,...] for i in range(len(arr))):` although I would hope we can find a prettier way.

**Comment by tylerjereddy** [comment] 2020-12-18 00:14
I got past the first case with the diff below, but then I realized we are really in trouble for the second case because the first thing `np.in1d()` does is call `np.asarray()` and once you do that on `[(1,), (2,)]` in case 2 above the tuples are gone no matter what you do later on. `np.asarray()` does preserve the tuple with `[(1,), 2]`.

Seems like the fix would have to be pretty invasive then for this to handle the all-tuple object input vs. just some tuples? Indeed, when  all elements are a tuple that seems like a not-so-unusual way to specify a 2D array of data so could probably argue that's the right thing to do I guess.

(this doesn't work with structured dtypes I don't think):

```diff
diff --git a/numpy/lib/arraysetops.py b/numpy/lib/arraysetops.py
index 6c6c1ff80..45b148f44 100644
--- a/numpy/lib/arraysetops.py
+++ b/numpy/lib/arraysetops.py
@@ -579,8 +579,10 @@ def in1d(ar1, ar2, assume_unique=False, invert=False):
                 mask &= (ar1 != a)
         else:
             mask = np.zeros(len(ar1), dtype=bool)
+            store = np.empty(shape=1, dtype=object)
             for a in ar2:
-                mask |= (ar1 == a)
+                store[0] = a
+                mask |= (ar1 == store)
         return mask
 
     # Otherwise use sorting

```

**Comment by tylerjereddy** [comment] 2020-12-18 00:19
So yeah, I guess we'd have to clarify if the proposed "correct" answer to case 2 above is actually correct or not.

**Comment by apoorv-jain** [comment] 2020-12-26 06:47
I was trying to resolve this issue. There is one thing I wanted to ask whether the 
`np.in1d([(1,), (2,3)], [(1,), 2])` should be `array([True,True)]` or `array([True,False)]`

**Comment by seberg** [comment] 2020-12-27 17:13
The second one is correct and it should do nothing special aside from whatever comparing the original object dos.

**Comment by AngelGris** [comment] 2021-02-07 15:28
I was checking on this but I'm afraid the behavior of `==` over the Numpy array class is defined in it's C++ implementation so the comparison between tuples in the arrays that is failing should also be fixed in that implementation and not on the Python side.

**Comment by seberg** [comment] 2021-02-07 16:31
@AngelGris that is not what is going on, the tuple is incorrectly unpacked _before_ the `==` operation (which does nothing strange for `obect`s).  The diff that Tyler posted is good, might need to think about a nicer way, but mostly we need to transform it into a PR with a test.

**Comment by seberg** [comment] 2021-02-07 16:32
Oh, sorry, the `==` operator *does* call `np.asarray(a)` which unpacks.  But I don't think we can change that behviour, so a python side fix similar to the one above is better.

**Comment by AngelGris** [comment] 2021-02-07 19:46
I've been doing some more research on this and I find it weird too how the arrays are being built when containing tuples.
Take the following example:
```
>>> import numpy as np
>>> np.array([(1,), (2,1)], dtype=object)
array([(1,), (2, 1)], dtype=object)
>>> np.array([(1,), [2]], dtype=object)
array([[1],
       [2]], dtype=object)
>>> np.array([(1,), (2,)], dtype=object)
array([[1],
       [2]], dtype=object)
>>> np.array([(1,2), (2,3)], dtype=object)
array([[1, 2],
       [2, 3]], dtype=object)
```

So when the tuples have the same amount of items the array constructor converts them into arrays and that's what we pass later to `in1d()`. For instance if we want to compare the first 2 arrays (`[(1,), (2, 1)]` and `[[1], [2]]`) and given that we built both of them containing tuples we would expect to get `[True, False]` as the result, but we will get `[False, False]` because we will be comparing an array containing tuples with another array containing arrays

Now I'm wondering if the problem is the array constructor, the unpacking of tuples, or both.

**Comment by seberg** [comment] 2021-02-07 19:53
Yes, that is all problematic, but I guess nobody had the inertia yet to try and go for a big change such as "only unpack lists for `dtype=object`".  If I were to design things from scratch, I would definitely prefer that.

That doesn't mean it cannot be changed, especially since we can limit it to the `dtype=object` path, but it might be a bit painful and it definitely needs a proper deprecation/future warning period.

**Comment by AngelGris** [comment] 2021-02-08 17:54
@seberg the approach suggested by @tylerjereddy worked fine, just needed to check the dtype for ar2 to use that only on objects. My unit tests were failing because of the problem with the array constructor I mentioned before but I found a work around to make the constructor work as expected and the unit tests, using the failing cases reported in this, are passing now.
Please check my PR at your earliest convenience and let me know what you think.

**Comment by BvB93** [comment] 2021-02-09 12:29
For those unaware: a PR is up at https://github.com/numpy/numpy/issues/17923.

**Closed** 2021-02-10 16:31 UTC
Labels: 00 - Bug, component: numpy.lib
