### ISSUE TITLE
Float64 has attribute __getitem__ while float does not

### ISSUE THREAD

**Issue by pabogdan** [numpy/numpy#13653] opened 2019-05-28 14:49 UTC
Hello, 

Using numpy `1.16.3` I've noticed that `np.float64` behaves like an iterable in that it has the `__getitem__` attribute. When using a library that attempts to be generic in its handling of iterables, it calls `max(<iterable>) `, which fails. 

It is indeed the case that `np.max(<iterable>)` behaves correctly. 
### Reproducing code example:

```python
import numpy as np
x = np.float(80)
if hasattr(x, "__getitem__"):
    print(max(x))
y = np.float64(80)
if hasattr(y, "__getitem__"):
    print(max(y))
```

### Error message:

```
Traceback (most recent call last):
  File "npfloat64_bug.py", line 7, in <module>
    print(max(y))
TypeError: 'numpy.float64' object is not iterable
```
### Numpy/Python version information:

('1.16.3', '2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]')
('1.15.2', '2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]')
1.16.2 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
1.15.4 3.5.2 (default, Nov 12 2018, 13:43:14)[GCC 5.4.0 20160609]

asking colleagues to test this has yielded the same result for numpy 1.16.0 and 1.16.1

#### However, this behaves as expected:
('1.15.2', '2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]')

**Comment by eric-wieser** [comment] 2019-05-28 15:33
This problem exists with 0d arrays too. The numpy way to determine if something is iterable is to call `len(...)` and see if it fails.

**Comment by seberg** [comment] 2019-05-28 21:39
This is a long standing issue, which we have currently no way to move on easily. What confuses me (and what I cannot reproduce), is the claim that this is a regression and used to work in numpy 1.15. Numpy 1.15 should have the exact same issue.

**Comment by pabogdan** [comment] 2019-05-28 23:43
@seberg I've just tried it with version `1.8.2` ('2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]') and the issue is still present. We might have made a mistake when testing this around the office on that one machine.

**Comment by eric-wieser** [comment] 2019-05-29 06:27
An example of what `__getitem__` actually does:
```python
>>> x = np.float64(80)
>>> y = x[...]
>>> y
array(80.0)  # promotes to array
```
But even if supporting `x[...]` is a little peculiar, your code has exactly the same problem with `y`.

The problem here is that 0d and 1d arrays have the same type, but one is a sequence and the other is not. Python doesn't like types which are sometimes sequences and sometimes not.

**Comment by seberg** [comment] 2019-05-29 15:52
Yes, I will close this, I am sure we have issues open about the "acting like a sequence" thing of 0D arrays, and there is no way around it (and also true `__getitem__` is not the best check to begin with probably.

**Closed by seberg** 2019-05-29 15:52 UTC
Labels: 57 - Close?
