### ISSUE TITLE
ENH: Remove `PyArray_Return` logic converting 0-D arrays to scalars indiscriminately

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#15165] opened 2019-12-24 21:23 UTC
This is something similar to https://github.com/numpy/numpy/issues/10363.

When feeding a `float` to a numpy function, you get a `numpy.float64`. When feeding an array of rank > 0 to a numpy function, you get an array of the same rank. UNLESS the array is rank 0, i.e., a scalar for most intents and purposes. Then you get a `numpy.float64`.

MWE:
```python
import numpy

print(type(numpy.sqrt(2.0)))                  # numpy.float64, okay
print(type(numpy.sqrt(numpy.array([2.0]))))   # numpy.ndarray, okay
print(type(numpy.sqrt(numpy.array(2.0))))     # numpy.float64, gnrg
```
It'd be more consistent if the numpy functions returned an array if you feed it it one, even for rank 0.

**Comment by seberg** [comment] 2019-12-24 21:39
Almost duplicate of gh-13105. I would be surprised if there is no duplicate around, it is also listed here: https://github.com/numpy/numpy/wiki/Backwards-incompatible-ideas-for-a-major-release

Basically, ufuncs (and a lot of other functions) always call `PyArray_Return`, which causes this. I expect the idea behind it was/is that scalars can be optimized more. So if you return scalars, basic math on 0D objects is much faster.
That does not mean I agree with the sentiment, there should be better solutions for the problem (also I have personally long argued that if `np.ufunc.reduce(..., axis=None)` returned scalars, it would probably be consistent and there would be so few 0D arrays around, that it might not matter (although `np.array` would create 0D arrays I guess)...

In any case, I agree, I have been complaining about it for as long as I can remember, but see also the first issue.

**Comment by nschloe** [comment] 2019-12-24 21:55
I think this is the OG bug report: https://github.com/numpy/numpy/issues/6051.

**Comment by eric-wieser** [comment] 2019-12-24 23:15
Yep, that's a fairly convincing duplicate - closing

**Closed by eric-wieser** 2019-12-24 23:15 UTC
Labels: 60 - Major release
