### ISSUE TITLE
numpy.any() and numpy.all() return string instead of bool for arrays of strings

### ISSUE THREAD

**Issue by strue36** [numpy/numpy#12897] opened 2019-01-31 13:39 UTC
The documentation for numpy.any() states that it 

> Returns single boolean unless axis is not None

Calling numpy.any() on an array of strings (dtype=object) returns the first string in the array

### Reproducing code example:

```python
import numpy as np
example_array = np.array(['a', 'b', 'c'], dtype=object)
example_array.any()
```

Returns 'a' (using all() returns 'c')

### Numpy/Python version information:

1.15.2 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

**Comment by fivemok** [comment] 2019-02-22 20:40
For ```dtype=object```, it appears ```np.any()``` has a type signature ```OO->O```. I think this is duplicate of https://github.com/numpy/numpy/issues/4253.

**Comment by eric-wieser** [comment] 2019-03-24 05:17
Definitely a duplicate of #4352

**Closed by eric-wieser** 2019-03-24 05:17 UTC
Labels: 00 - Bug, component: numpy.ufunc
