### ISSUE TITLE
ImportError: /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by JaiKotia** [numpy/numpy#14148] opened 2019-07-29 07:45 UTC
I'm facing an issue when importing numpy into a safe execute instance (this one: https://github.com/cemc/safeexec). It works fine in my docker container, but when I try to import numpy in the safe execute sandbox, the following error appears.

I have ensured that only one version of numpy is installed and that it is the latest version. I have even reinstalled numpy several times and tried older versions. Solutions for other similar issues have not helped solve my issue.

### Code:
import numpy as np

### Error message:

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray

  File "/usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides

  File "/usr/local/lib/python3.5/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (

ImportError: /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so: failed to map segment from shared object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "file.py", line 1, in <module>
    import numpy

  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core

  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.

Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:

  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.

  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /usr/local/lib/python3.5/dist-packages/numpy/core/_multiarray_umath.cpython-35m-x86_64-linux-gnu.so: failed to map segment from shared object

Command exited with non-zero status (1)

Execution_Time : 0.051841

### Numpy/Python version information:

Python 3.5.3
Numpy 1.16.4

I installed numpy using pip3.

**Comment by mavho** [comment] 2019-11-18 18:03
Have you fixed this error? I'm getting the same thing and tried reinstalling numpy. Not sure what to do.

**Comment by seberg** [comment] 2019-11-18 18:11
These type of errors mean something is wrong with the installation. In this case it cannot load a required library.

We would need to know more about the installation and things. This is almost certainly not an issue in NumPy, so you may get lucky here, but there is likely only so much we can help with and asking e.g. at safeexec may be more productive.

**Comment by mavho** [comment] 2019-11-18 19:12
I will try redownloading python later today, I'm working on centos 8, and I did a yum module install python36. 
I can actually import numpy regularly through a virtual environment, but I'm facing an issue when I'm importing pandas through a restful api deployed on an Apache server using mod_wsgi.
 Currently, I've circumvented the problem by not importing pandas at all and running the file importing pandas as a subprocess instead.

**Comment by cloudmountofficial** [comment] 2020-10-23 16:23
Did somebody find a solution? 

I am running [Jobeinabox](https://github.com/trampgeek/jobeinabox) [Docker] and am able to import numpy from inside Python3 cli, but unable to import it inside jobeinabox execution environment. jobeinabox is similar to safe exec, it has separate threads to run different code submissions. It is basically a code judge.

This is the error I got:

```
***Error***
Traceback (most recent call last):
  File "__tester__.python3", line 1, in <module>
    import numpy as np
  File "/usr/local/lib/python3.6/dist-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "/usr/local/lib/python3.6/dist-packages/numpy/random/__init__.py", line 181, in <module>
    from . import _pickle
  File "/usr/local/lib/python3.6/dist-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "_bit_generator.pxd", line 14, in init numpy.random.mtrand
ImportError: /usr/local/lib/python3.6/dist-packages/numpy/random/_bit_generator.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object
```

**Comment by mattip** [comment] 2020-10-24 18:21
Closing. Please reopen if I misunderstood that the problem is solved.

**Closed by mattip** 2020-10-24 18:21 UTC
Labels: 32 - Installation, 57 - Close?

**Comment by rajatkumarraghuvanshi1** [comment] 2020-11-10 09:18
just increase memory for the process, this exception will go away.

**Comment by maryam-se** [comment] 2021-07-30 19:04
I have a same problem import numpy regularly through a virtual environment, but I'm facing an issue when I'm importing pandas through a restful api deployed on an Apache server using mod_wsgi. and I got the same error 
how I can increase memory of process ?

**Comment by isdsava** [comment] 2022-04-12 03:21
Using Docker EE for windows 2019 server this error was caused by not setting the --memory when using docker run. The default must be very small and when increasing it ( in my case to 4 gig) these errors stopped.
