### ISSUE TITLE
numpy.remainder not working as defined.

### ISSUE THREAD

**Issue by jakehanson** [numpy/numpy#7272] opened 2016-02-18 05:32 UTC
For some reason, numpy.remainder function is not working as defined for the following specific case:

np.remainder(.60,.04) = 0.04

0.60-np.floor(0.60/0.04)*0.04 = 0.00   (Function as defined)

This seems to be the only case for which the definition does not match the function output.

**Comment by njsmith** [comment] 2016-02-18 08:19
What version of numpy?

On Wed, Feb 17, 2016 at 9:32 PM, jakehanson <notifications@github.com>
wrote:

> For some reason, numpy.remainder function is not working as defined for
> the following specific case:
>
> np.remainder(.60,.04) = 0.04
>
> 0.60-np.floor(0.60/0.04)*0.04 = 0.00 (Function as defined)
>
> This seems to be the only case for which the definition does not match the
> function output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/7272>.
>



-- 
Nathaniel J. Smith -- https://vorpus.org <http://vorpus.org>

**Comment by omegahm** [comment] 2016-02-18 12:50
I'm not sure what it is, that isn't working:

```python
>>> np.__version__
'1.10.4'
>>> 0.60 % 0.04
0.039999999999999966
>>> np.remainder(0.60, 0.04)
0.039999999999999966
```

**Comment by pv** [comment] 2016-02-18 14:01
Probably duplicate of gh-7224

**Comment by jakehanson** [comment] 2016-02-18 16:48
Hi Pauli, I beleive you're correct. Ideally i would like the remainder to
return something close to 0 rather than x2 if x1 is divisible by x2, but I
understand how floating point error can cause this. Thank you all for the
responses.

**Closed** 2017-08-08 20:50 UTC
