### ISSUE TITLE
Numpy silently assigns zeroes

### ISSUE THREAD

**Issue by hhristov94** [numpy/numpy#12449] opened 2018-11-25 19:44 UTC
Numpy silently assigns zeroes instead of the correct array if the array has a negative fraction.

### Reproducing code example:

```python
A = np.array([[3,2,4],
              [2,1,3],
              [1,2,4]])
b = A[1,0:3] - 0.66*A[0,0:3]
A[1,1:3] = b[1:3]

A
```

Output:
```python
array([[3, 2, 4],
       [2, 0, 0],
       [1, 2, 4]])
```
### Numpy/Python version information:
OS: Windows 10
Numpy version :  1.14.5
Python version :  3.6.6
1.14.5 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]

**Comment by hhristov94** [comment] 2018-11-25 19:55
Updated to Numpy version 1.15.4 . The issue still persists.

**Comment by eric-wieser** [comment] 2018-11-25 20:33
This fails for the same reason as:
```
>>> arr = np.array([1, 2, 3])
>>> arr.dtype
int  # or something
>>> arr[0] = 1.5
>>> arr[0]
1
```

Assigning to an array never changes its type.

You could argue we should emit a warning or error here, rather than rounding. I think there are multiple issues open about that.

**Closed by eric-wieser** 2018-11-25 20:33 UTC

**Comment by eric-wieser** [comment] 2018-11-25 21:02
Duplicate of #8733
