### ISSUE TITLE
Unexpected behavior of arange

### ISSUE THREAD

**Issue by cateryna** [numpy/numpy#14358] opened 2019-08-25 17:56 UTC
Encountered unexpected behavior of numpy.arange (stop number is INCLUDED in the output)

In: np.arange(20,25.1,0.1)
Out: array([ 20. ,  20.1,  20.2,  20.3,  20.4,  20.5,  20.6,  20.7,  20.8,
        20.9,  21. ,  21.1,  21.2,  21.3,  21.4,  21.5,  21.6,  21.7,
        21.8,  21.9,  22. ,  22.1,  22.2,  22.3,  22.4,  22.5,  22.6,
        22.7,  22.8,  22.9,  23. ,  23.1,  23.2,  23.3,  23.4,  23.5,
        23.6,  23.7,  23.8,  23.9,  24. ,  24.1,  24.2,  24.3,  24.4,
        24.5,  24.6,  24.7,  24.8,  24.9,  25. ,  25.1])

The behavior noticed in python 3.6.1 as well as in python 2.7.13

**Comment by grlee77** [comment] 2019-08-25 20:32
This sounds like a known limitation of `arange` floating point step size. See #13613, for example

**Comment by seberg** [comment] 2019-09-16 18:36
I will close this @cateryna the `np.arange` is not very good (but I think we have issues open about it). As the documentation warns, it is best avoided for floating point. The problem is that it is a simple addition algorithm, on top of that it calculates the step from the difference between two initial values internally.

**Closed by seberg** 2019-09-16 18:36 UTC
