### ISSUE TITLE
Power PC long double repr needs more precision.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#7940] opened 2016-08-15 23:35 UTC
On PPC this test fails as reported in #7836

```
    o = 1 + np.finfo(np.longdouble).eps
    assert_equal(np.longdouble(repr(o)), o,
                 "repr was %s" % repr(o))
```

with

```

AssertionError:
Items are not equal: repr was 1.0
 ACTUAL: 1.0
 DESIRED: 1.0
```

Among other things, probably finfo, it looks like repr does not have sufficient digits.

**Comment by juliantaylor** [comment] 2016-08-17 13:19
duplicate of #2669
see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=702169
finfo actually returns too much precision

**Comment by charris** [comment] 2017-02-03 20:18
Should be closed by #8504.

**Comment by matthew-brett** [comment] 2017-02-04 01:04
Oh dear - I'm afraid we still have this one : http://nipy.bic.berkeley.edu/builders/numpy-py2.7-debian-ppc/builds/716/steps/shell_5/logs/stdio

**Comment by matthew-brett** [comment] 2017-02-04 10:17
The problem is that the eps is too small for the repr precision.

The longdouble repr print precision is [unconditionally set to be the same](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/scalartypes.c.src#L850) as the [double repr precision == 17](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/scalartypes.c.src#L847) in `scalartypes.c.src`.  (The actual double precision is 15).  Then, any longdouble that has `eps` > 1e-18 will generate a repr '1.0' for `1 + eps`.  For example, this same test fails on SPARC (float128).

Should the longdobule repr precision depend on the longdouble type?  (33 digits in the case of SPARC float128, 31 in the case of PPC longdouble).  Or should we skip this test for precision > 18 digits?

**Comment by eric-wieser** [comment] 2017-02-21 21:36
Sorry, in what way is `NPY_SIZEOF_LONGDOUBLE == NPY_SIZEOF_DOUBLE` "unconditional"?

**Closed** 2017-02-22 22:27 UTC
Labels: 11 - Bug
