### ISSUE TITLE
The argsort function is broken. It does not return correct indices for the sorted array

### ISSUE THREAD

**Issue by vsnupoudel** [numpy/numpy#19880] opened 2021-09-16 07:11 UTC
Argsort does not return indices that sort the input array

### Reproducing code example:

```python
import numpy as np
x = np.array([ 3 ,1, 2])
np.argsort(x)
```
The output is array([1, 2, 0]). Shouldn't it be [2,0,1]

### NumPy/Python version information:

v1.21

**Comment by eric-wieser** [comment] 2021-09-16 07:38
Duplicate of #8757.

**Closed by eric-wieser** 2021-09-16 07:38 UTC
