### ISSUE TITLE
ndarray.ctypes creates a reference cycle

### ISSUE THREAD

**Issue by pijyoi** [numpy/numpy#13808] opened 2019-06-20 09:49 UTC
Reading attribute "ctypes.data" from an ndarray causes a leak.
version <= 1.14.5 doesn't leak
version >= 1.16.2 leaks
latest 1.16.4 leaks

### Reproducing code example:

```python
import numpy as np
import sys

print(np.version.full_version)

data = np.empty(8192)

before = sys.getrefcount(data)
data.ctypes.data
after = sys.getrefcount(data)
print(before, after)

assert before==after
```

### Error message:

  File "/mnt/d/code/python/test_numpy_leak.py", line 17, in <module>
    assert before==after
AssertionError

### Numpy/Python version information:

1.16.4 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]

----

Summary (@seberg) 2019-12-03

This has been partially fixed by gh-14469; There are still issues here, although they are mainly issues with upstream ctypes creating deep reference cycles.

**Comment by eric-wieser** [comment] 2019-06-20 15:43
What happens if you call gc.collect() before getting the refcount for a second time?

**Comment by seberg** [comment] 2019-06-20 20:31
Unfortunately, that does not help. I tracked down a little and found https://github.com/numpy/numpy/blob/d94acc7f73795ecbec71b672fd7c5f07e0ce9f09/numpy/core/_internal.py#L272 to be central to it. Specifically the last call to cast may be important.

I poked at circular references on the `arr.base` but reviving an older branch implementing `tp_traverse` did not seem to help (yet). So, not sure yet where it comes from.

**Comment by eric-wieser** [comment] 2019-06-20 20:59
`.data` is a red herring.

There is a circular reference here:
```
arr.ctypes._data._some_internal_ref = arr
```

I think the problem is that `arr.ctypes.data` needs to construct `_data` every time, rather than holding onto the reference

**Comment by seberg** [comment] 2019-06-20 21:07
Yeah, that fixes it. I am just a bit surprised right now that the reference cycle cannot be broken...

**Comment by eric-wieser** [comment] 2019-06-20 21:09
The cycle isn't leaked at this point, it's still referenced by `globals()['data']`. The test here is not a good one

**Comment by seberg** [comment] 2019-06-20 21:18
Ack, maybe I was just being stupid anyway, adding the collects at the wrong spot, oh man... Anyway, I think we can close this. The cycle can be broken and it is definitely cleaned up on master.

**Comment by seberg** [comment] 2019-06-20 21:18
Ah well, at least that circular reference stuff is rebased on master again. Eventually that might end up being useful ;).

**Comment by eric-wieser** [comment] 2019-06-21 07:58
Reopening since actually there shouldn't be a cycle here, `array.ctypes` returns a temporary.

At worst this is an unnecessary cycle though, not a leak - so not worth milestoning.

**Comment by pijyoi** [comment] 2019-06-22 14:13
Although technically there isn't a leak, however the following code will balloon in memory usage with numpy 1.16, unless gc.collect() is called explicitly. With numpy 1.15, memory usage stays constant.

```python
import os
import time
import gc
import numpy as np
import psutil

def stuff():
    data = np.ones(100*1048576, dtype=np.uint8)
    addr = data.ctypes.data

process = psutil.Process(os.getpid())

cnt = 0
while 1:
    stuff()
    # gc.collect()
    print(cnt, process.memory_info().rss//1048576)

    cnt += 1
    time.sleep(0.1)
```

**Comment by eric-wieser** [comment] 2019-06-22 15:10
Presumably the garbage collector will kick in by itself eventually?

The behavior change is likely due to the fact that `arr.ctypes.data` now holds a reference to `arr`, which is a bug fix

**Comment by pijyoi** [comment] 2019-06-22 15:51
In my real application that creates 50 MB arrays every second, resident memory grew to 20 GB after running for a couple of hours. (And still growing)

So while the automatic gc does kick in, it didn't seem to be able to stop the memory usage from growing slowly.

My workaround was to not use ndarray.ctypes.data.

**Comment by seberg** [comment] 2022-11-19 09:36
This seems to have been fixed in gh-14469 but not closed.

**Closed by seberg** 2022-11-19 09:36 UTC
Labels: 00 - Bug
