### ISSUE TITLE
Best practices for re-exposing numpy's Literal parameters in downstream libraries

### ISSUE THREAD

**Issue by mwaskom** [numpy/numpy#22415] opened 2022-10-09 19:51 UTC
*Asked on gitter first but was directed here.*

I have a question about the correct way for downstream libraries to handle some of numpy's `Literal` parameter types. I suppose this is a general question, but the specific case is the `method` parameter for `numpy.percentile`. The parameter is typed as a Literal with a [long list](https://github.com/numpy/numpy/blob/3cf2ca1611ecaf1d13c41075a7025b96e54e3ee3/numpy/lib/function_base.pyi#L500) of options, using a private type alias.

All well and good. But say I am writing a function that's going to use `numpy.percentile` behind the scenes and want to expose a `method` parameter to my users. How am I to type this parameter? Mypy complains if I use `str`. But I can't reference numpy's `_MethodKind` directly, due to the leading underscore. So I have resorted to copying the type alias definition into my codebase. This works, but seems seems non-ideal: what if numpy adds some additional options in the future?

Am I missing something about how to work with `Literal` types? Surely I'm not the first person to run into this problem.

**Comment by mattip** [comment] 2022-10-10 18:23
@BvB93 any thoughts?

**Comment by mathause** [comment] 2022-10-13 06:25
In xarray we currently spell them out: https://github.com/pydata/xarray/blob/3599f873d65d96488e30a47374ca36039006f8d5/xarray/core/types.py#L179

but of course would not mind a central solution.

cc @headtr1ck

**Comment by jorenham** [comment] 2024-08-17 21:52
Closing as a duplicate of #16676

**Closed by jorenham** 2024-08-17 21:52 UTC
Labels: 15 - Discussion, 50 - Duplicate, Static typing

**Comment by mwaskom** [comment] 2024-08-18 02:20
Doesn’t seem related to me, but also fine to close as wontfix imo.

**Comment by jorenham** [comment] 2024-08-18 04:50
@mwaskom Your both talking about exposing the `typing.Literal` aliases that NumPy uses in its stubs, right 🤔?

**Comment by mwaskom** [comment] 2024-08-18 12:31
I read the linked issue as asking something completely different, but if the threshold for duplicate is "broadly about the same topic", then, sure.

**Comment by jorenham** [comment] 2024-08-18 16:27
> but if the threshold for duplicate is "broadly about the same topic", then, sure.

I mark issues as duplicate if think that fixing one would also resolve the other, and vica versa. I.e. when they are *equivalent*; they need not be *equal*.

**Comment by mwaskom** [comment] 2024-08-18 17:50
Ok. I really don't see how "add more literal types" resolves "numpy's literal types cause problems for downstream libraries". But like I said this issue hadn't gotten much traction so it's fine for numpy to not address it. I just think it's odd to categorize it as a duplicate.

**Comment by jorenham** [comment] 2024-08-18 18:48
I never said the solution is to "add more literal types". What I said was

> exposing the `typing.Literal` aliases that NumPy uses in its stubs

or in other words: To make the `Literal`s that NumPy uses part of the public `numpy.typing` API.

But don't get me wrong; I think it's a good idea. 
I ran into this problem a couple of times actually, see https://github.com/jorenham/Lmo/blob/dev/lmo/typing/np.py#L109-L124 for instance.

**Comment by jorenham** [comment] 2024-08-18 18:49
See also https://github.com/numpy/numpy/pull/26871
