### ISSUE TITLE
Broken f2py script in wheeled numpy 1.9.3

### ISSUE THREAD

**Issue by azag0** [numpy/numpy#6348] opened 2015-09-23 22:37 UTC
After installing wheeled numpy 1.9.3, the f2py script starts with
```
#!/Users/travis/build/MacPython/numpy-wheels/venv/bin/python
```
I don't know who travis is, but she's definitely not a user on my laptop... Numpy 1.9.2 worked fine as I recall. Numpy compiled from master is of course fine as well.

**Comment by njsmith** [comment] 2015-09-23 22:42
CC @matthew-brett 

I guess a rebuilt wheel could use a "post-release" version number (1.9.3.post1), to avoid going straight to 1.9.4? Or we could go straight to 1.9.4, it's a little silly but we won't run out of numbers.

**Comment by matthew-brett** [comment] 2015-09-23 23:49
Oh dear.  The problem is that this patch is not merged for the 1.9 series:

https://github.com/numpy/numpy/pull/5815

For me all wheels back through 1.9.0 have broken f2py.

I guess this is a case for 1.9.4.   I'll start another branch.

**Comment by matthew-brett** [comment] 2015-09-24 00:17
See: https://github.com/numpy/numpy/pull/6349

**Comment by matthew-brett** [comment] 2015-09-24 00:21
Oops - see #6350 instead.

**Comment by azag0** [comment] 2016-05-09 21:18
This can be probably closed now? I didn't really follow what happened afterwards.

**Closed** 2016-05-09 21:36 UTC
