### ISSUE TITLE
numpy 1.12 on OS X with mkl produces incorrect answer for numpy.dot

### ISSUE THREAD

**Issue by torcolvin** [numpy/numpy#8577] opened 2017-02-08 00:20 UTC
Running numpy.dot normally produces the expected answer:

```
$  python -c "import numpy ; f=numpy.ones(2,dtype=numpy.float32);print f.dot(f)"
2.0
```

If I import a PyQt5 module first, I get a different answer:
```
$  python -c "import PyQt5.QtWidgets ; import numpy ; f=numpy.ones(2,dtype=numpy.float32);print f.dot(f)"
0.0
```

Other folks appear to have found the issue [here](https://support.enthought.com/hc/en-us/articles/204469560--RESOLVED-OSX-Numpy-float32-linear-algebra-bug), with an implied implication of the Accelerate library being loaded first. I could not discover the resolution they used, and I would prefer one that did not require fixing python import order.

**Comment by njsmith** [comment] 2017-02-08 01:01
Where did you get your numpy with MKL? Unfortunately this sounds like a bug
in MKL, which is closed source software that we can't debug and that we
don't even distribute, so I'm not sure what we can do exactly...

Does the problem also occur with the official builds on pypi ("pip install
numpy")?

**Comment by torcolvin** [comment] 2017-02-08 01:32
I built copy of numpy with MKL 2017u1 (to use with other applications that use ifort / mkl). I was hopeful there was some idea of an known interaction with VecLib or an idea to go forth and debug.

**Comment by njsmith** [comment] 2017-02-08 01:38
I suppose one option would be to see if you can reproduce your problem with
Anaconda's numpy+MKL build and then file a bug report with them 😈

**Comment by mistguy** [comment] 2017-02-13 13:01
I am using numpy with MKL in anaconda 4.3 (python3.6 version) and the results are correct.

**Comment by torcolvin** [comment] 2017-02-15 20:23
I can reproduce with anacoda python, so I'll try filing a bug with them too.

**Comment by mingwandroid** [comment] 2017-02-17 16:55
Thanks @njsmith! :-)

**Comment by mingwandroid** [comment] 2017-02-17 16:56
But seriously, we'll do our best to investigate this.

**Comment by pv** [comment] 2018-05-29 23:54
duplicate of #9758 (which has more info)?

**Comment by charris** [comment] 2018-05-30 00:17
Hmm, let's just link them together for now.

**Comment by rgommers** [comment] 2018-07-16 03:15
fixed. see https://github.com/numpy/numpy/issues/9758#issuecomment-397400117 for details

**Closed by rgommers** 2018-07-16 03:15 UTC
Labels: 00 - Bug, component: build
