### ISSUE TITLE
 RuntimeWarning: Invalid value encountered in percentile

### ISSUE THREAD

**Issue by doanchientrinh** [numpy/numpy#13098] opened 2019-03-05 15:21 UTC
I get this error when I run my code. I need your help. Thanks!
```
**C:\Users\doanc\Anaconda3\lib\site-packages\numpy\lib\function_base.py:4291: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)**



%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.style.use('seaborn-whitegrid')
import numpy as np
import pandas as pd

births = pd.read_csv('births.csv')

quartiles = np.percentile(births['births'], [25, 50, 75])
mu, sig = quartiles[1], 0.74 * (quartiles[2] - quartiles[0])

births = births.query('(births > @mu - 5 * @sig) & (births < @mu + 5 * @sig)')

births['day'] = births['day'].astype(int)

births.index = pd.to_datetime(10000 * births.year + 100 * births.month + births.day, format='%Y%m%d')
births_by_date = births.pivot_table('births',  [births.index.month, births.index.day])
births_by_date.index = [pd.datetime(2012, month, day) for (month, day) in births_by_date.index]
```

**Comment by Kai-Striega** [comment] 2019-04-11 08:15
@doanchientrinh as you have said the error occurs in ``np.percentile``. As the error message says, at least one of the values is invalid. This could either be a bug in the function or that one of the values in your csv file is not compatible/being read incorrectly. 

I think the latter is more likely, would you be able to share your csv file?

**Comment by Kai-Striega** [comment] 2019-05-12 07:50
@eric-wieser can this be closed? The error *probably* comes from `births` containing an invalid value... just like the error says. Without having the data we can't reproduce this, and it doesn't look like it's a bug from numpy.

**Comment by seberg** [comment] 2019-05-12 08:11
Yes, seems right that the behaviour is probably due to bad data (meaning the warning serves its purpose). If it is not, we should reopen the issue, but since there was no followup multiple weeks, will close it for now.

**Closed by seberg** 2019-05-12 08:11 UTC
