### ISSUE TITLE
Expected behaviour regarding new `copy` keyword in `__array__` implementations

### ISSUE THREAD

**Issue by jorisvandenbossche** [numpy/numpy#25941] opened 2024-03-05 14:24 UTC
Moving from https://github.com/numpy/numpy/pull/25922, which added this to the docs:

> NumPy will pass ``copy`` to the ``__array__`` special method in situations where
it would be set to a non-default value (e.g. in a call to
``np.asarray(some_object, copy=False)``). Currently, if an
unexpected keyword argument error is raised after this, NumPy will print a
warning and re-try without the ``copy`` keyword argument. Implementations of
objects implementing the ``__array__`` protocol should accept a ``copy`` keyword
argument with the same meaning as when passed to `numpy.array` or
`numpy.asarray`.

Thinking through how to update some `__array__` implementations, I am wondering: what are the expectations from numpy how an `__array__` implementations handles this keyword fully or partially? 

When `copy=True` is being passed, does numpy assume that the `__array__` implementation already made that copy? But what if the implementation defers dtype casting to numpy (which is currently possible), then it might be a waste to already copy up front?

_Originally posted by @jorisvandenbossche in https://github.com/numpy/numpy/pull/25922#discussion_r1512762568_

**Comment by rgommers** [comment] 2024-03-05 15:04
Deprecated though, right? The signature should already have included the `dtype` keyword, even though it was still working to not have that.

> then it might be a waste to already copy up front?

What we want to achieve I think is that only a single copy is ever made. We can have two now in many cases, because the other library may copy from its internal implementation into an array, and then numpy will make another copy. The only way to get it right is for the other library to do the copy if `copy=True`, and for numpy not to do so if the method call including `copy=True` succeeded.

The old behavior is:
- the only contract of `__array__` is that it must return a `numpy.ndarray` instance,
- the implementer of `__array__` may or may not make a copy in the process of producing an array
- NumPy _may_ make a copy of the returned array if needed when `copy=False`, and _must_ make a copy if `copy=True` (it cannot know otherwise if it has exclusive ownership of the underlying data)
- end result for `copy=True` is: either 1 or 2 copies made (NumPy cannot know which)

The intended new behavior is:
- `copy` is always passed on to the `__array__` implementer, with the same semantics as for `asarray` (`False`: "never copy", `None`: "copy-if-needed", `True`: ensure data is a semantic copy / unique to returned array) 
- that implementer _must_ ensure that the data can not be used anymore by anything other than the numpy array it's returning (that usually means "copy the data in memory" but it can also mean something like "invalidate any other reference to this data")
- end result:
  - `copy=False`: guarantee that no data is copied in memory
  - `copy=None`: 0 or 1 copies made, data may be a view
  - `copy=True`: 0 or 1 copies made, data is guaranteed to not be a view

It looks like we need to do two things:
1. Make the expectations on implementers of `__array__` clearer in our docs,
2. Ensure we actually do not make a second copy if `copy=True` if passing along the copy keyword in the call to `__array__` succeeded.

This change of `__array__` kinda came in at the end of a long PR/discussion about the `asarray`/`array` behavior, so I didn't realize until now that this is actually also a performance improvement, potentially avoiding an unnecessary copy.

**Comment by jorisvandenbossche** [comment] 2024-03-05 15:53
It seems that on current main, numpy still does a copy afterwards, so `np.asarray(arr, dtype="int64", copy=True)` actually gives a copy even with the `__array__` implementation above. But I assume numpy will want to change that to avoid the additional copy?

**Comment by ngoldbaum** [comment] 2024-03-05 16:10
> But I assume numpy will want to change that to avoid the additional copy?

Right now it's actually not possible to get to the code path in numpy that calls `__array__` with `copy=True`, but in the future we'll want to restructure things to avoid the extra copy.

**Comment by ngoldbaum** [comment] 2024-03-20 18:41
This should probably be fixed:

```
import numpy as np

class HasArray:
    def __array__(self, values=None, dtype=None, copy=None):
        print(copy)
        return

arr = HasArray()

np.array(arr, copy=True)
```

Right now the `print(copy)` will print `None` where it really should print True.

We also need to update the docs to cover how implementers should handle this. I'll try to do this this week.

**Comment by mattip** [comment] 2024-04-03 18:06
Closing, thanks.

**Comment by jorisvandenbossche** [comment] 2024-04-08 15:18
I have an additional question here that is not fully covered in the migration guide note that closed this issue:

> For any `__array__` method on a non-NumPy array-like object, a `copy=None` keyword can be added to the signature - this will work with older NumPy versions as well. If `copy` keyword is considered in the `__array__` method implementation, then for `copy=True` always return a new copy.

I don't know what "if copy keyword is considered" means _exactly_ (only when handling the copy keyword in your actual implementation, or whenever adding the copy keyword to the signature?), but it seems that adding `copy=None` to your `__array__` implementation actually does impact the behaviour.

```python
# no copy keyword -> raises an error (and depr warning) when specifying copy=False

class MyArray:
    def __array__(self, dtype=None):
        return np.array([1,2,3], dtype=int)

>>> np.array(MyArray(), copy=False)
DeprecationWarning: __array__ should implement the 'dtype' and 'copy' keyword argument
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

# adding copy keyword just to signature -> no error

class MyArray:
    def __array__(self, dtype=None, copy=None):
        return np.array([1,2,3], dtype=int)

>>> np.array(MyArray(), copy=False)
array([1, 2, 3])
```

So just adding `copy=None` to the signature but further ignoring it (to get rid of the deprecation warning) results in `np.array(.., copy=False)` to no longer raise an error, while there is no guarantee that the result is not copied?

And this is what for example pandas did (https://github.com/pandas-dev/pandas/issues/57739, and I just wanted to do the same for pyarrow). 

Is the behaviour difference expected? (also in the case of `copy=False` that is now raising, the `__array__` method might actually be returning something that is not a copy, and thus numpy can be raising an incorrect error) 
And should the recommendation then be to only add `copy=None` to your `__array__` signature when actually honoring the keyword, also when it is passed `copy=False`? (the current doc note only mentions that it should honor `copy=True`)

**Comment by ngoldbaum** [comment] 2024-04-08 15:32
> So just adding copy=None to the signature but further ignoring it (to get rid of the deprecation warning) results in np.array(.., copy=False) to no longer raise an error, while there is no guarantee that the result is not copied?

This is working as intended. We only raise the warning if the function doesn't support the keyword at all. As soon as you add the keyword (even if you ignore it), numpy has to assume the implementation has done what the user expects when `copy=False` is passed. It would be nice if we could do something fancier and actually check if a copy happened or not, but I don't think there's a way to tell from inside numpy?

>  (also in the case of copy=False that is now raising, the __array__ method might actually be returning something that is not a copy, and thus numpy can be raising an incorrect error)

Hmm, maybe it would be better to reword the error message to say something like "numpy tried passing copy=False, but the `__array__` implementation doesn't accept a `copy` keyword, so numpy can't guarantee that a copy won't be made".

Ping @mtsokol, can we get some minor updates to docs and error messages to alleviate the confusion @jorisvandenbossche ran into?

**Comment by jorisvandenbossche** [comment] 2024-04-08 15:45
And https://numpy.org/devdocs/user/basics.interoperability.html#the-array-method already mentions the expected behaviour.

It might be good to add a link to that from https://numpy.org/doc/stable/reference/generated/numpy.ndarray.__array__.html

**Comment by seberg** [comment] 2024-04-08 15:48
If we touch the docs, it would be nice to use "must" rather than "should".  Should can (and when it comes to such things does) convey that downstream has a choice: they don't!  So the correct terminology is "must".

**Comment by jorisvandenbossche** [comment] 2024-04-09 10:07
Another point of feedback: for implementing the `copy=False` case correctly, it is unfortunate (for this specific case, not necessarily for general usage!) that the `copy` keyword of `astype` is not strict. 
Because we have a (typical?) usage of something like:

```python
class MyArray:

    def __array__(self, dtype=None):
            if dtype is None:
                return self._ndarray
            return self._ndarray.astype(dtype)
```

To update this to have a `copy=None` keyword ànd honor the `copy=False` case, it's not sufficient to add `astype(dtype, copy=False)` as that still doesn't guarantee no copy was made. Once would have the return value of `astype` to check if it returned the calling ndarray as is, to detect if a copy happened or not?

**Comment by ngoldbaum** [comment] 2024-04-09 15:34
The `copy` keyword for `astype` is mentioned in NEP 56, where disallowing copies with `copy=False` is ruled out because `astype` implies a user explicitly requests a different dtype and a copy has to happen if the dtype changes. See also https://github.com/numpy/numpy/issues/25925.

From your edit, it sounds like you figured out an appropriate workaround.

**Comment by mtsokol** [comment] 2024-04-09 15:36
@jorisvandenbossche I think this could be the shortest way to support both `dtype` and `copy`:
```python

def __array__(self, dtype=None, copy=None):
    dtype = self._ndarray.dtype if dtype is None else dtype
    return np.array(self._ndarray, dtype=dtype, copy=copy)
```

**Comment by seberg** [comment] 2024-04-17 19:06
This has been explained, and a new PR is open to change the behavior, but it will be in 2.1 with a deprecation.  Closing this.

**Closed by seberg** 2024-04-17 19:06 UTC
Labels: component: numpy._core, Numpy 2.0 API Changes

**Comment by hmaarrfk** [comment] 2024-09-08 02:47
Can this comment https://github.com/numpy/numpy/issues/25941#issuecomment-1978979695 be linked to in the deprecation warning?

it was very useful to me. I can make the PR if ok!

**Comment by mattip** [comment] 2024-09-08 17:29
Do you mean adding a link to the comment? Most of it has been put into the migration guide, no?
