### ISSUE TITLE
"libraries mkl_rt not found" This issue looks similar to #22048

### ISSUE THREAD

**Issue by Prajwalmithun** [numpy/numpy#23042] opened 2023-01-19 05:23 UTC
### Steps to reproduce:

1. Cloning my repository 
```
git clone https://github.com/Prajwalmithun/homomorphic_encryption.git
cd homomorphic_encryption
```

2. Build a docker image out of "Dockerfile"

```
# docker build -t catdog . 
```

This is the "Dockerfile"

```
FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

COPY . .

CMD ["python3", "cat_lovers_VS_dog_lovers.py"]
```

### Error message:

```shell
error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [1198 lines of output]
      Collecting setuptools<=60.9
        Downloading setuptools-60.9.0-py3-none-any.whl (1.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 29.4 MB/s eta 0:00:00
      Collecting wheel
        Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting cython==3.0.0a10
        Downloading Cython-3.0.0a10-py2.py3-none-any.whl (1.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 19.2 MB/s eta 0:00:00
      Collecting numpy==1.21
        Downloading numpy-1.21.0.zip (10.3 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 46.1 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting cmake>=3.15
        Downloading cmake-3.25.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.7 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 28.8 MB/s eta 0:00:00
      Collecting toml>=0.10
        Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [1162 lines of output]
            setup.py:63: RuntimeWarning: NumPy 1.21.0 may not yet support Python 3.11.
              warnings.warn(
            Running from numpy source directory.
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/_common.pyx
            Processing numpy/random/mtrand.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_generator.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/_mt19937.pyx
            Cythonizing sources
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE <<<<<<<<<<<<<<<<<<<<<<<<<<<
      
            blis_info:
              libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE    <<<<<<<<<<<<<<<<<<<<<<<
      
            openblas_info:
              libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE  <<<<<<<<<<<<<<<<<<<<<<<<
      
            accelerate_info:
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries tatlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE   <<<<<<<<<<<<<<<<<<<<<<<
      
            atlas_3_10_blas_info:
              libraries satlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_info:
              libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            /tmp/pip-install-4ehy1tdc/numpy_a86ce636ce4d4fdbb1c5b35c67384bf0/numpy/distutils/system_info.py:2026: UserWarning:
                Optimized (vendor) Blas libraries are not found.
                Falls back to netlib Blas library which has worse performance.
                A better performance should be easily gained by switching
                Blas library.
              if self._calc_info(blas):
            blas_info:
              libraries blas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            /tmp/pip-install-4ehy1tdc/numpy_a86ce636ce4d4fdbb1c5b35c67384bf0/numpy/distutils/system_info.py:2026: UserWarning:
                Blas (http://www.netlib.org/blas/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [blas]) or by setting
                the BLAS environment variable.
              if self._calc_info(blas):
            blas_src_info:
              NOT AVAILABLE
      
            /tmp/pip-install-4ehy1tdc/numpy_a86ce636ce4d4fdbb1c5b35c67384bf0/numpy/distutils/system_info.py:2026: UserWarning:
                Blas (http://www.netlib.org/blas/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [blas_src]) or by setting
                the BLAS_SRC environment variable.
              if self._calc_info(blas):
              NOT AVAILABLE
      
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
              libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_lapack_info:
              libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_clapack_info:
              libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            flame_info:
              libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /usr/local/lib
              libraries tatlas,tatlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries tatlas,tatlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
              NOT AVAILABLE
      
            atlas_3_10_info:
              libraries lapack_atlas not found in /usr/local/lib
              libraries satlas,satlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries satlas,satlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_3_10_info'>
              NOT AVAILABLE
      
            atlas_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /usr/local/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_threads_info'>
              NOT AVAILABLE
      
            atlas_info:
              libraries lapack_atlas not found in /usr/local/lib
              libraries f77blas,cblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib
              libraries f77blas,cblas,atlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_info'>
              NOT AVAILABLE
      
            lapack_info:
              libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            /tmp/pip-install-4ehy1tdc/numpy_a86ce636ce4d4fdbb1c5b35c67384bf0/numpy/distutils/system_info.py:1858: UserWarning:
                Lapack (http://www.netlib.org/lapack/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [lapack]) or by setting
                the LAPACK environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
            lapack_src_info:
              NOT AVAILABLE
      
            /tmp/pip-install-4ehy1tdc/numpy_a86ce636ce4d4fdbb1c5b35c67384bf0/numpy/distutils/system_info.py:1858: UserWarning:
                Lapack (http://www.netlib.org/lapack/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                the LAPACK_SRC environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
              NOT AVAILABLE
...
...
...
########### EXT COMPILER OPTIMIZATION ###########
            Platform      :
              Architecture: x64
              Compiler    : gcc
      
            CPU baseline  :
              Requested   : 'min'
              Enabled     : SSE SSE2 SSE3
              Flags       : -msse -msse2 -msse3
              Extra checks: none
      
            CPU dispatch  :
              Requested   : 'max -xop -fma4'
              Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
              Generated   :
                          :
              SSE41       : SSE SSE2 SSE3 SSSE3
              Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1
              Extra checks: none
              Detect      : SSE SSE2 SSE3 SSSE3 SSE41
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_arithmetic.dispatch.c
                          :
              AVX2        : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C
              Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mavx2
              Extra checks: none
              Detect      : AVX F16C AVX2
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_arithm_fp.dispatch.c
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_arithmetic.dispatch.c
                          :
              (FMA3 AVX2) : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C
              Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2
              Extra checks: none
              Detect      : AVX F16C FMA3 AVX2
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_trigonometric.dispatch.c
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_exponent_log.dispatch.c
                          :
              AVX512F     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2
              Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f
              Extra checks: AVX512F_REDUCE
              Detect      : AVX512F
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_arithm_fp.dispatch.c
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_arithmetic.dispatch.c
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_trigonometric.dispatch.c
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_exponent_log.dispatch.c
                          :
              AVX512_SKX  : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD
              Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq
              Extra checks: AVX512BW_MASK AVX512DQ_MASK
              Detect      : AVX512_SKX
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_arithmetic.dispatch.c
                          : build/src.linux-x86_64-3.11/numpy/core/src/umath/loops_exponent_log.dispatch.c
            CCompilerOpt.cache_flush[804] : write cache to path -> /tmp/pip-install-4ehy1tdc/numpy_a86ce636ce4d4fdbb1c5b35c67384bf0/build/temp.linux-x86_64-3.11/ccompiler_opt_cache_ext.py
      
            ########### CLIB COMPILER OPTIMIZATION ###########
            Platform      :
              Architecture: x64
              Compiler    : gcc
      
            CPU baseline  :
              Requested   : 'min'
              Enabled     : SSE SSE2 SSE3
              Flags       : -msse -msse2 -msse3
              Extra checks: none
      
            CPU dispatch  :
              Requested   : 'max -xop -fma4'
              Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
              Generated   : none
            CCompilerOpt.cache_flush[804] : write cache to path -> /tmp/pip-install-4ehy1tdc/numpy_a86ce636ce4d4fdbb1c5b35c67384bf0/build/temp.linux-x86_64-3.11/ccompiler_opt_cache_clib.py
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy <<<<<<<<<<<<<<<<<<<
      Failed to build numpy  <<<<<<<<<<<<<<<<<<<<<<<<
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

### Additional information:

I have indicated error lines with arrow marks ie., <<<<<<<<<<<<<<<<<<<< this way 

Please check this. 
Thank you!

**Comment by rkern** [comment] 2023-01-19 05:56
All of those libraries that you marked are optional, so their absence is likely not the reason for the ultimate failure. That's probably hidden in the `...` region that you omitted. The numpy build process does not find those libraries because they do not exist in the Linux distribution that's used in the `python` Docker image that you derive from. You would need to install one of them using `apt` if you want to build numpy against them, but that would not fix your problem.

I'm going to close this, as the stated hypothesis isn't a problem, and there is no information to follow up to help find the real problem. Now that you know this hypothesis about the root cause of your build problem isn't the case, you can do some more investigation on your own to narrow down the real problem. Then you can decide whether or not it's an actual bug that is in our capacity to act on.

**Closed by rkern** 2023-01-19 05:56 UTC
Labels: 32 - Installation
