### ISSUE TITLE
numpy ImportError: lapack_lite.cpython-36m-x86_64-linux-gnu.so: undefined symbol: zgelsd_

### ISSUE THREAD

**Issue by debpolaris** [numpy/numpy#9190] opened 2017-05-31 00:00 UTC
Hi, I'm using CentOS 6 server in an intranet. There is no connection on the external internet.
That is why I install python3.6 and numpy 1.11.2 by source build.

Before installed numpy, I built Lapack and Atlas by source followed this guide.
( https://www.scipy.org/scipylib/building/linux.html )

After installed numpy, I got an error.
```
$ python3 -c "import numpy; numpy.test('full')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/lib/polynomial.py", line 20, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/linalg/__init__.py", line 51, in <module>
    from .linalg import *
  File "/usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/linalg/lapack_lite.cpython-36m-x86_64-linux-gnu.so: undefined symbol: zgelsd_


$ ldd /usr/local/lib/python3.6/site-packages/numpy-1.11.2-py3.6-linux-x86_64.egg/numpy/linalg/lapack_lite.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007fffd2fff000)
	/work/RESEARCH/SRC/ATLAS/lib/libtatlas.so (0x00007feb28c25000)
	libpgmp.so => /opt/pgi/linux86-64/12.6/libso/libpgmp.so (0x00007feb28ab5000)
	libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00007feb2887a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007feb2865e000)
	libpgf90.so => /opt/pgi/linux86-64/12.6/libso/libpgf90.so (0x00007feb281f8000)
	libpgf90_rpm1.so => /opt/pgi/linux86-64/12.6/libso/libpgf90_rpm1.so (0x00007feb280f6000)
	libpgf902.so => /opt/pgi/linux86-64/12.6/libso/libpgf902.so (0x00007feb27fe3000)
	libpgf90rtl.so => /opt/pgi/linux86-64/12.6/libso/libpgf90rtl.so (0x00007feb27eb6000)
	libpgftnrtl.so => /opt/pgi/linux86-64/12.6/libso/libpgftnrtl.so (0x00007feb27d89000)
	libpgc.so => /opt/pgi/linux86-64/12.6/libso/libpgc.so (0x00007feb27c2a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007feb27a21000)
	libm.so.6 => /lib64/libm.so.6 (0x00007feb2779d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007feb273fc000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007feb27109000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003345000000)
```
There is two python version on my server, python2.6(by rpm) and python 3.6(/usr/local, by source)

I'm googling and searching in this forum but I can't find the solution.

**Comment by charris** [comment] 2017-05-31 00:45
Couple of questions: where did you get the source, and how did you compile/install the code?

**Comment by debpolaris** [comment] 2017-05-31 01:03
Because it's an intranet server. there is no Internet connection on this server.
So, I'm compile and installed it.

And here my compile & install code
-- python3 build & install
`# python3 setup.py build --fcompiler=pg -j 4 install --prefix /usr/local --record install.txt`

-- Lapack build
```
cd lapack-3.7.0
cp INSTALL/make.inc.gfortran make.inc
cd SRC
make
```

-- Atlas build
```
cd ATLAS_3.10.1
mkdir MYBUILD
cd MYBUILD
../configure -Fa alg -fPIC -Ss flapack $(lapack_path)/liblapack.a
make
cd lib
make shared
make ptshared
```

Is there something wrong???

**Comment by njsmith** [comment] 2017-05-31 01:14
I don't know off the top of my head what went wrong with your build – someone else might have more ideas about how to debug it. But before you spend a bunch of time on that, have you considered copying over one of the official wheel files and installing that? (e.g., [this wheel](https://files.pythonhosted.org/packages/b1/e2/884cfbfd4f21b2313210d1d2ea72ecc381b98826d1b7e6606929ac6c0a08/numpy-1.12.1-cp36-cp36m-manylinux1_x86_64.whl) should work for centos 6 / python 3.6 / x86-64, and you can install it by copying it over then doing `pip install <path to .whl file>`) It might save you some time...

**Comment by charris** [comment] 2017-05-31 01:15
Yes, but I was wondering where the source came from. Is there a missing `make install` for the atlas build? Also, did you try using `site.cfg` to set up paths so that atlas is detected? The output of the build might be interesting in that regard. Note that this is the first use of the pg compiler that I have seen.

**Comment by njsmith** [comment] 2017-05-31 01:18
(One possible thing to check would be whether the pg compiler is mangling LAPACK's fortran symbols in the same way that numpy expects – the output from `readelf -a /work/RESEARCH/SRC/ATLAS/lib/libtatlas.so | grep zgel` might be interesting to see.)

**Comment by debpolaris** [comment] 2017-05-31 01:31
Thank you, njsmith
There is no message `readelf`

Maybe something was missing when I compiled Lapack...

**Comment by njsmith** [comment] 2017-05-31 01:35
Note that the official wheel files have their own blas/lapack included inside them; if you use them then you don't need to compile your own lapack. (And it's openblas, which will generally be more efficient than atlas anyway.)

Do you mean that you have no `readelf`, or that the command worked but had no output?

**Comment by debpolaris** [comment] 2017-05-31 01:42
Oh, I'm really sorry. there is no output message `readelf`

I should use whl package instead of source compile.

**Comment by charris** [comment] 2017-05-31 01:52
I suspect you will also want to install scipy, and there are no wheels for that. Might be worth figuring out just what the problem is when you are compiling your own.

**Comment by njsmith** [comment] 2017-05-31 02:17
@charris: scipy has wheels on Linux (and also MacOS) – it's only Windows that's a problem.

If you can do `readelf -a /work/RESEARCH/SRC/ATLAS/lib/libtatlas.so` and post the output somewhere (it'll be long), then that might give us a hint about how the pgi compiler works.

**Comment by seberg** [comment] 2022-11-06 15:04
Closing, since it is a many years old compilation/linking problem with an atlas build.  It seems unlikely that there is anything actionable (and easier to reopen a new issue if there is).

**Closed by seberg** 2022-11-06 15:04 UTC
Labels: 32 - Installation
