### ISSUE TITLE
np.divide.accumulate gives incorrect results for float64 on Numpy 1.15.0 using Intel compiler

### ISSUE THREAD

**Issue by stevesimmons** [numpy/numpy#11796] opened 2018-08-21 16:59 UTC
I have a unit test failing on `np.divide.accumulate` with numpy 1.15.0 compiled with the Intel compiler. The same code is fine with a local build of GCC.

Perhaps this is related to ENH: umath: don't make temporary copies for in-place accumulation (https://github.com/numpy/numpy/pull/10665) where @juliantaylor fixed `numpy/core/src/umath/loops.c.src` for GCC's `ivdep` pragma. That was reviewed by @eric-wieser .

### Reproducing code example

Source code was 1.15.0 compiled with the Intel compiler 2018.1.163.  where np.divide.accumulate fails in the numpy unit tests. 

I can reproduce with this Python 2.7 test case for `float64` dtype. It runs correctly for `float32` and `float128` on the Intel compiler. It also runs correctly for `float64` using GCC instead of Intel.

```
$ python -c "import numpy as np; acc = np.divide.accumulate;  
  a = np.ones(8, dtype=np.float64);  
  print acc(a, out=2*np.ones_like(a)); print acc(a); print acc(a); print acc(a); 
  print acc(a, out=2*np.ones_like(a))"
[1. 1. 2. 2. 2. 2. 2. 2.]
[1. 1. 1. 1. 2. 2. 2. 2.]
[1. 1. 1. 1. 1. 1. 2. 2.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 2. 2. 2. 2. 2. 2.]
```
Notice how only the next two elements are set each time `np.divide.accumulate` runs. That suggests the `float64`s are being processed in pairs. Then in the final line, specifying the output array again returns to the first line's incorrect behavior.

### Numpy/Python version information:

numpy 1.15.0 build with ICC 2018.1.163.  
python 2.7.11 built with GCC 4.9.3.

**Comment by charris** [comment] 2018-08-21 18:59
I find it curious that it is only the Intel compiler that has problems.

**Comment by charris** [comment] 2018-08-21 20:34
What platform? If you are doing your own compiles, MKL's 2018 update 3 is recommended. You may also want to experiment with optimization levels.

**Comment by charris** [comment] 2018-08-21 20:49
@juliantaylor Thoughts?

**Comment by charris** [comment] 2018-08-21 20:50
Might also be worth updating Python 2.7.

**Comment by juliantaylor** [comment] 2018-08-25 09:41
reproducable with gcc is you remove the overlap check which does not work with avx enabled as it assumes sse sized vectors
what flags are you using to compile numpy? You should be able to work around it be removing the flag that forces compilation with avx/avx2, numpy will not be slower, it can autodetect your cpu features and use correct code at runtime.

**Comment by juliantaylor** [comment] 2018-08-25 10:03
But I am not sure how this triggers with icc, the overlap is for the example is 8 bytes so the existing 16 byte SSE2 check should catch it and no vectorized code be executed. Instead it should run the usual loop trivial loop that a decent compiler should not be able to miscompile.
Can you debug which code path it takes in the `DOUBLE_divide` function?

**Comment by stevesimmons** [comment] 2018-09-05 23:52
I have been able to duplicate this with Numpy 1.15.1 against Py 3.7.0, using the latest Intel compiler version (2018 update 3). I got the compiler with Intel's 30-day evaluation license.

`np.divide.accumulate` fails in exactly the same way when compiled with `-O3 -aAVX` flag. It is ok when compiled using the `-O3 -no-vec` flags instead.

**Comment by charris** [comment] 2018-09-19 15:19
@juliantaylor Is there anything we should do about this?

**Comment by charris** [comment] 2018-09-19 16:46
OK, thanks. I'm going to make NumPy 1.15.2 this weekend, so will remove the milestone while the investigation of this problem is ongoing.

**Comment by juliantaylor** [comment] 2018-09-19 17:15
If you can modify the code it would be helpful to just put a puts("nosimd"); underneath the line

    else if (!run_binary_simd_@kind@_@TYPE@(args, dimensions, steps)) {

https://github.com/numpy/numpy/blob/master/numpy/core/src/umath/loops.c.src#L1731
when it prints in your example we at least know that our simd check is working properly and the compiler is miscompiling the simple loop.

Otherwise we would probably need a disassembly which you can produce by running `gdb --args <your reproducting commandline>` 

```
break DOUBLE_divide
run
disassemble
```
or via an equivalend objdump -D command on the umath.so

**Comment by charris** [comment] 2018-11-17 17:55
@juliantaylor Do you think your recent overlap fix PR fixed this?

**Comment by charris** [comment] 2018-11-22 15:14
Leaving open as tracking issue, but pushing off to 1.17.

**Comment by svenevs** [comment] 2019-02-18 20:58
Hello, I ran into this problem today, some specs

- Fedora 27
- Intel 18.0.0 (can't update :/ CUDA is very specific about compiler versions)
    - GCC 6.3.0 backend
- python 3.7.2 (compiled with same stack)
- numpy 1.16.1

Same hardware / python / numpy versions on gcc 7.3.1 and clang 6.0.0 stack had no tests, so this definitely seems isolated to intel (possibly no longer a problem with newer versions, but I don't have access :/).

I hit this issue by just doing `import numpy; numpy.test()`, the actual test that failed has code like this

```py
def test_noncommutative_reduce_accumulate(self):
    # ...
    todivide = np.array([2.0, 0.5, 0.25])
    # ...
    assert_array_equal(np.divide.accumulate(todivide),
      np.array([2., 4., 16.]))
```

(bad result being `array([2.e+000, 4.e+000, 4.e-323])`).  So I know how to know whether or not I fix it :)

> Try using `#pragma intel optimization_level 2` atop `@TYPE@_divide` to see if lowering the optimization level for that routine alleviates the problem.

So if I'm understanding right, `#ifdef __INTEL_COMPILER` and `#pragma` these three functions

https://github.com/numpy/numpy/blob/1dfb0ab7358b0cae068b41b3d07452713594ef6b/numpy/core/src/umath/loops.c.src#L1090

https://github.com/numpy/numpy/blob/1dfb0ab7358b0cae068b41b3d07452713594ef6b/numpy/core/src/umath/loops.c.src#L1204

https://github.com/numpy/numpy/blob/1dfb0ab7358b0cae068b41b3d07452713594ef6b/numpy/core/src/umath/loops.c.src#L2640

Possibly turning opt down lower if no success.  I will be testing this tomorrow but wanted to post here and double check that this is the approach we are looking for / solicit any extra guidance (e.g., ways to verify I've tested all three of those?).

I didn't understand what `puts("simd");` was for, and `numpy` code is quite foreign to me (it's beautiful, but I've never really looked around here before...I've definitely been taking `numpy` for granted so I'm hoping maybe I can solve this issue!)

**Comment by seberg** [comment] 2019-02-18 21:11
@svenevs you should probably start with doing modifications here:

https://github.com/numpy/numpy/blob/1dfb0ab7358b0cae068b41b3d07452713594ef6b/numpy/core/src/umath/loops.c.src#L1820

which are the loops that get executed for the typical floating point types. Note that "kind" in that code bunch can be `divide`

**Comment by V-Kh** [comment] 2019-04-26 23:40
I've tested numpy 1.16.3  (py3 and py2) with the most recent icc,  everything seems to be fine now. However, I would like to have more tests to run.

**Comment by charris** [comment] 2019-05-22 23:06
@V-Kh Any updates? I'm inclined to close this.

**Comment by seberg** [comment] 2019-05-22 23:26
@charris does that mean that gh-12991 is not necessary, or should be merged?

**Comment by svenevs** [comment] 2019-05-23 00:11
Eep. Sorry, I recently removed overly aggressive spam filters. 12991 should not be merged. I will be able to test with Intel 2019 tonight. Assuming no patch needed, will add preprocessor logic to check Intel versions and only reduce if necessary.

What's still unanswered is how to treat Windows. I'm inclined to say 12991 should only do *nix. Somebody who has Windows / Intel can test on their own / patch as needed. In other words, only fix what we know is broken.

**Comment by seberg** [comment] 2019-05-23 00:16
Thanks @svenevs just in case, one thing that would be nice is to ensure that our test suits finds these errors (if possible). Probably that is already the case, but if not it would be good to add them. After that anyone using these compilers will know that something is off.

**Comment by charris** [comment] 2019-05-23 01:18
@oleksandr-pavlyk Do you know if this is fixed in latest Intel compiler.

**Comment by charris** [comment] 2019-06-06 18:20
@svenevs What is the status of this? The 1.17 release is coming up...

**Comment by svenevs** [comment] 2019-06-06 22:13
Since we don't know exactly what version numbers are affected, I don't really know what to do. Options I think we have

1. Any Intel compiler gets O2 on this method (meh...)
2. Since newer Intel versions (2019+, maybe 2018+) don't seem to have a problem, just close issue and ignore.
3. Middle ground. Add Intel specific setup.py argument or environment variable to say "please reduce this method".

For (3) the idea would be to encourage users to compile from source and `numpy.test()`. If that fails, encourage recompile with `--reduce-intel-optimization` or whatever.

It's also easier to implement, Intel version checking with the preprocessor is a little obtuse.

**Comment by charris** [comment] 2019-07-17 14:39
Closing. We have a test that fails for the bad compilers and Intel has fixed in newer compilers. See resolution of #12991 .

**Closed by charris** 2019-07-17 14:39 UTC
Labels: 00 - Bug, 26 - Compiler, 29 - Intel/Anaconda
