### ISSUE TITLE
matrix().max() reports `TypeError: float() argument must be a string or a number`

### ISSUE THREAD

**Issue by HuangYanqiColumbia** [numpy/numpy#17248] opened 2020-09-04 13:59 UTC
The following reporducing code reports `TypeError: float() argument must be a string or a number`

### Reproducing code example:

```python
import numpy as np
np.matrix(np.random.randn(100, 100)).max()
```

### Error message:
---------------------------------------------------------------------------
![Screen Shot 2020-09-04 at 8 57 27 AM](https://user-images.githubusercontent.com/47264245/92247443-daafae00-ee8c-11ea-9b36-bc77e7fab87f.png)

### Numpy/Python version information:

1.18.1 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0]

**Comment by mattip** [comment] 2020-09-05 19:24
The complete error message has 
> ... not `_NoValueType` 

which is supposed to be a singleton. Maybe you are reloading NumPy or in some other way invalidating the global numpy state? Does this happen if you run your test case above immediately after starting NumPy?

**Comment by AnshuTrivedi** [comment] 2020-10-06 08:57
@mattip @eric-wieser  
@HuangYanqiColumbia  I tried to reproduce error and there is no issue even after running 2-3 times same code on notebook. Used seed to produce same result.

> np.random.seed(1)
np.matrix(np.random.randn(100, 100)).max()
4.026849044547378

I think issue can be closed if solved for @HuangYanqiColumbia.

**Comment by mattip** [comment] 2020-10-06 10:08
Closing since the original reporter did not give us the needed information to continue. Please reopen or open a new issue if needed. Thanks @AnshuTrivedi for following through.

**Closed by mattip** 2020-10-06 10:08 UTC
