### ISSUE TITLE
BUG: numpy arange doesn't give correct number of elements in the output array

### ISSUE THREAD

**Issue by yanggwang** [numpy/numpy#20832] opened 2022-01-16 17:18 UTC
### Describe the issue:

When I try this, the result is of 8144 elements
np.arange(0, 81.43, 0.01).shape
(8144,)
But, it should be 8143
See the following counter example:
np.arange(0, 81.45, 0.01).shape
(8145,)
np.arange(0, 81.44, 0.01).shape
(8144,)
np.arange(0, 11.44, 0.01).shape
(1144,)

### Reproduce the code example:

```python
import numpy as np
np.arange(0, 81.43, 0.01).shape

np.arange(0, 81.45, 0.01).shape

np.arange(0, 81.44, 0.01).shape

np.arange(0, 11.44, 0.01).shape
```

### NumPy/Python version information:

1.20.1 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]

**Comment by mattip** [comment] 2022-01-16 17:39
Duplicate of #19249 and others. Please carefully read the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) especially the warning there, and use linspace instead.

**Closed by mattip** 2022-01-16 17:39 UTC
Labels: 00 - Bug
