### ISSUE TITLE
Equality testing by index does not behave consistently

### ISSUE THREAD

**Issue by JSGandora** [numpy/numpy#7751] opened 2016-06-16 16:21 UTC
Observe the following two examples:

Example 1:
```
import numpy as np
import pandas as pd

A = np.array([0, 1, 0])
B = pd.Series([0, 1, 0])

print A[A == B]
```
which prints out
```
[1 1 1]
FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  print A[A == B]

Process finished with exit code 0
```

Example 2:
```
import numpy as np
import pandas as pd

A = np.array([0, 0, 0])
B = pd.Series([0, 1, 0])

print A[A == B]
```

which prints out:

```
[0 0 0]
FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  print A[A == B]

Process finished with exit code 0
```
whereas we expect example 2 to print out [1, 0, 1].  Is this a bug?  Does this have anything to do with the FutureWarning?

I am running Python version 2.7.11

**Comment by mhvk** [comment] 2016-06-16 16:41
The problem is that your boolean-like array is treated as a set of indices (of 0 and 1). So, in example 1, you get `A[[1, 1, 1]] -> [1 1 1]` and in example 2 `A[[1, 0, 1]] -> [0, 0, 0]`

In the future, this will return the as what now would happen with `A[np.array([True, True, True])] -> [0 1 0]` and `A[np.array([True, False, True])] -> [0, 0]`.

I'd recommend to write `np.array(A == B, dtype=np.bool_)` (or something similar) to be sure this works now and keeps working.

**Comment by JSGandora** [comment] 2016-06-16 16:46
Thank you, that fixes the problem!

**Comment by seberg** [comment] 2016-06-16 16:47
Yeah, and yes, the futurewarning is exactly about this issue, and it is telling you that it will do what you expect it to do in the future. And I think at least numpy 1.12 is that future. And the result will be (and is in current master at least):

```
# Example 1:
In [5]: print A[A == B]
[0 1 0]

# Example 2:
In [10]: print A[A == B]
[0 0]
```

If you expect `[1, 0, 1]` in example two, I am not sure what you are expecting though, that is the boolean array is `True, False, True`, but surely not `A[A == B]`.

Anyway, the futurewarning is in place, exactly to try and clear this up as far as I can see, so closing this. If you have any further question please feel free to continue the discussion.

**Closed by seberg** 2016-06-16 16:47 UTC
