### ISSUE TITLE
BUG: Overflow reported when negating uint64

### ISSUE THREAD

**Issue by bashtage** [numpy/numpy#24737] opened 2023-09-18 15:58 UTC
### Describe the issue:

A usually valid operation, negation of an unsigned integer, is raising an underflow warning.

### Reproduce the code example:

```python
import numpy as np

a = np.uint64(0xffffffff)
b = -a
```

### Error message:

```shell
`RuntimeWarning: overflow encountered in scalar negative`
```

### Runtime information:

```
1.25.2
3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
```

### Context for the issue:

Wrapping unsigned integer values is fairly common in C using negation.  This used to be free from warnings, so was surprised to see this.

**Comment by ngoldbaum** [comment] 2023-09-18 18:32
I can reproduce this. It looks like this changed sometime after NumPy 1.23, with the 1.23.3 wheel:

```
In [1]: import numpy as np

In [2]: a = np.uint64(0xffffffff)

In [3]: b = -a

```

and the NumPy 1.24.3 wheel:

```
In [1]: import numpy as np
   ...: 
   ...: a = np.uint64(0xffffffff)

In [2]: b = -a
<ipython-input-2-064521cdc161>:1: RuntimeWarning: overflow encountered in scalar negative
```

**Comment by charris** [comment] 2023-09-18 19:18
Works for me: gcc 13.2.1

Apparently C++ does have a preference, the hex literal has the type of the first type where it fits:

- int
- unsigned int
- long int
- unsigned long int
- long long int
- unsigned long long int

Maybe that is related? I assume the conversion is done by Python or a library.

**Comment by ngoldbaum** [comment] 2023-09-18 19:27
I bisected the behavior change to https://github.com/numpy/numpy/pull/21437, so ping @seberg too

**Comment by ngoldbaum** [comment] 2023-09-18 19:41
I bisected this to https://github.com/numpy/numpy/pull/21648, ping @Micky774.

(I posted an incorrect comment earlier that said a different PR was the cause and I deleted that comment, sorry for the duplicate e-mail)

**Comment by seberg** [comment] 2023-09-19 06:46
This needs a decision that we want to allow some scalar operators to wrap silently to users while we warn for others.
I.e. there was a reason for this change, that if you have an unsigned int and don't realize it, getting the wrong result deserves a warning.  (something that NEP 50 may make slightly more common)

**Comment by bashtage** [comment] 2023-09-19 08:25
Would it be possible to separate unary negation from multiplication by a negative number, where unary would not warn?

**Comment by seberg** [comment] 2023-09-19 09:13
Yes, we can do all of that.  We just need to decide to do it.

**Comment by Micky774** [comment] 2023-09-19 15:41
IMO it's safer to offer a warning that can be suppressed than to remove the warning because it is sometimes used. The behavior is still noteworthy in some cases and I think it is safe to optimize for those cases.

**Comment by RubTalha** [comment] 2023-11-16 13:33
https://stackoverflow.com/questions/77467422/runtimewarning-overflow-encountered-in-scalar-negative

**Comment by mattip** [comment] 2024-01-10 18:52
In the latest triage meeting we decided to close this for now. In the future, we would prefer that scalars perform more like 0d arrays (and not warn), but that would be part of a larger effort and may even need a NEP.

**Closed by mattip** 2024-01-10 18:52 UTC
Labels: 00 - Bug, 09 - Backport-Candidate, triage review
