### ISSUE TITLE
fromiter does not work with dtype=numpy.long

### ISSUE THREAD

**Issue by tcwalther** [numpy/numpy#5426] opened 2015-01-06 18:50 UTC
Running `numpy.long(2**127)` works fine, but

```
numpy.fromiter((2**127 for v in xrange(10)), dtype= numpy.long, count=10)
```

fails with `OverflowError: long too big to convert`.

I assume the long is converted to an int and then back to a long, and that fails. Explicitly casting it to `numpy.long` does not help either:

```
numpy.fromiter((numpy.long(2**127) for v in xrange(10)), dtype=numpy.long, count=10)
```

Using `dtype=numpy.float` works, though.

**Comment by jaimefrio** [comment] 2015-01-06 19:19
`numpy.long` is the C `long int` type on your platform, not Python's arbitrary precision long integers. So you are basically trying to fit a 128 bit number in a 64 bit container, hence the error.

The proper thing to do would be to create an array of `object` dtype. Unfotunately, this doesn't work either, but it is a feature, not a bug: ;-)

```
>>> np.fromiter((2**127 for v in xrange(10)), dtype=object, count=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot create object arrays from iterator
```

**Comment by jaimefrio** [comment] 2015-01-06 19:29
Why `np.long(2**127)` works is a mistery to me, probably another of those cases where numpy tries to be smarter than it should, especially since `np.int64(2**127)` fails, but `np.dtype(np.long) is np.dtype(np.int64)` evaluates to `True`.

**Comment by maniteja123** [comment] 2015-01-06 19:45
In 1.9.1, I got ``np.dtype(np.long) is np.dtype(np.int64)`` as ``False``. They are having different ``id``.

    >>>id(np.dtype(np.int64))
    139984638518016
    >>> id(np.dtype(np.long))
    139984638517056

In the dev version, it is coming ``True`` as you pointed out.

    >>> id(np.dtype(np.int64))
    3072069792L
    >>> id(np.dtype(np.long))
    3072069792L

Was there any change in the implementation of dtypes from 1.9.1 to present dev version ?

**Comment by jaimefrio** [comment] 2015-01-06 20:12
They could be different instances of the same object. I think the proper thing to check is that `np.dtype(np.int64).num` and `np.dtype(np.long).num` returns the same value, which should be `7` for `long`, see [here](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/include/numpy/ndarraytypes.h#L59).

**Comment by maniteja123** [comment] 2015-01-06 20:21
Oh, I still don't quite get what exactly is ``num`` referring to from the ``ndarraytypes.h`` file. But this is the output I am gettting.

    >>>np.dtype(np.long).num
    9
    >>> np.dtype(np.int64).num
    7
    >>> np.__version__
    '1.9.1'

    >>>np.dtype(np.long).num
    9
    >>> np.dtype(np.int64).num
    7
    >>> np.__version__
    '1.10.0dev+3e20e32'

**Comment by maniteja123** [comment] 2015-01-06 20:24
Ok, I understand now. Since it is a ``enum``, it is the position corresponding to the ``dtype``. But the output is as above, contradicting what you say.

**Comment by maniteja123** [comment] 2015-01-06 20:32
Sorry, I think it is my mistake. I have the version on different machines, mostly with different underlying system architecture. 

For the dev version on 32 bit
    >>>np.dtype(np.int32).num
    7
    >>>np.dtype(np.int).num
    7
    >>>np.dtype(np.longlong).num
    9

And the machine with 1.9.1 is a 64 bit
    >> np.dtype(np.int32).num
    5 
    >>> np.dtype(np.int).num
    7
    >>> np.dtype(np.int64).num
    7

**Comment by jaimefrio** [comment] 2015-01-06 20:46
I obviously don't fully understand how exactly the `.num` are assigned, [here](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/include/numpy/npy_common.h#L364) is where more of that magic happens. But the point is that whatever `np.dtype(np.long).num` is, it will be the same as `np.dtype(np.intxx).num` for some `xx`, so it is a fixed width integer type, almost certainly under 128 bits, that shouldn't accommodate `2**127`.

**Comment by jaimefrio** [comment] 2015-01-06 20:49
Going back to the original question, [here](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/multiarray/ctors.c#L3581) is where the error for `object` dtype is raised. I don't think the comment there is right: when memory is realloc'ed, a reference is lost and a new one created, since the array only holds pointers to the objects, not the objects themselves. So I think it is only clean-up that would need to take care of references.

**Comment by maniteja123** [comment] 2015-01-06 20:53
@jaimefrio I think I found the problem

    >>>np.longlong(2**127)
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    OverflowError: long too big to convert
    >>> np.longlong.mro()
    [<type 'numpy.int64'>, <type 'numpy.signedinteger'>, <type 'numpy.integer'>, <type
    'numpy.number'>, <type 'numpy.generic'>, <type 'int'>, <type 'object'>]

     >>>  np.long.mro()
     [<type 'long'>, <type 'object'>]
     >>> np.long(2**127)
     170141183460469231731687303715884105728L

**Comment by maniteja123** [comment] 2015-01-06 21:11
[PyDataType_REFCHK](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/include/numpy/ndarraytypes.h#L569)
[PyDataType_FLAGCHK]https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/include/numpy/ndarraytypes.h#L566)
[NPY_ITEM_REFCOUNT ](https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/include/numpy/ndarraytypes.h#L537) is declared as `0x01`

    >>>np.dtype('O').flags
    63
    >>>np.dtype(np.int32).flags
    0
    >>>np.dtype(np.float32).flags
    0

**Comment by njsmith** [comment] 2015-01-06 21:14
I think what's confusing everyone here is that 'np.long' is just an alias
for __builtins__.long. This is silly, but it is true:

In [2]: np.long is long
Out[2]: True

(See also np.int, np.str, etc. These things confuse everyone on a regular
basis. Perhaps if the python devs ever review my patch --
http://bugs.python.org/issue22986 -- then we'll be able to deprecate them
;-).)

So this is why np.long(2**127) works: np.long is an arbitrary-precision
integer type. (In fact it's just a no-op b/c 2**127 is already a python
long.)

When used to specify a dtype, though, 'long' gets mapped to fixed-width
int64.

On Tue, Jan 6, 2015 at 8:21 PM, Maniteja Nandana <notifications@github.com>
wrote:

> Oh, I still don't quite get what exactly is num referring to from the
> ndarraytypes.h file. But this is the output I am gettting.
>
> >>>np.dtype(np.long).num
> 9
> >>> np.dtype(np.int64).num
> 7
> >>> np.__version__
> '1.9.1'
>
> >>>np.dtype(np.long).num
> 9
> >>> np.dtype(np.int64).num
> 7
> >>> np.__version__
> '1.10.0dev+3e20e32'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5426#issuecomment-68927172>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by juliantaylor** [comment] 2015-01-06 21:21
whether np.long is np.int64 depends on whether you are on 32 bit or 64 bit, on windows it will always be false as its C long is always 32 bit

**Comment by maniteja123** [comment] 2015-01-06 21:26
@juliantaylor I was testing on Linux 32 and 64 bit systems, it was ``True`` on 32-bit, ``both 9``, but were different on 64-bit, ``np.long`` was ``9`` and ``np.int64`` was ``7``.

**Comment by njsmith** [comment] 2015-01-06 21:31
'np.long is np.int64' is never true, but I just checked on a 32-bit linux
and np.dtype(np.long) gave me int64.

Recall that plain ol' Python 'int' maps to C long (in python 2), and that
Python 'long' (= np.long) has nothing to do with C long. It makes sense
that Python 'long' would get mapped to the largest width integer type.

On Tue, Jan 6, 2015 at 9:21 PM, Julian Taylor <notifications@github.com>
wrote:

> whether np.long is np.int64 depends on whether you are on 32 bit or 64
> bit, on windows it will always be false as its C long is always 32 bit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5426#issuecomment-68935856>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by maniteja123** [comment] 2015-01-06 21:41
@njsmith I am using Python 2. I understand python 'long' maps  to the largest width, but why does ``np.int64`` map to ``9`` on ``32-bit``, while it maps to ``7`` on ``64-bit``. I am not that aware of the differences at the internal architecture level. Can you please clarify ? Thanks :)

**Comment by njsmith** [comment] 2015-01-06 22:03
Well, it's a bug, basically... 7 is NPY_LONG and corresponds to a C 'long'.
9 is NPY_LONGLONG and corresponds to a C 'long long'. On an LP64
architecture (like 64-bit unix), C 'long' and C 'long long' are just two
different names for the same 64-bit int type. And numpy inherits this
redundancy, and ends up with two totally identical type numbers.

**Comment by maniteja123** [comment] 2015-01-06 22:07
@njsmith Thanks, I understand it now :)

**Comment by kernc** [comment] 2017-07-12 11:47
> The proper thing to do would be to create an array of object dtype. Unfotunately, this doesn't work either, but it is a feature, not a bug: ;-)

@jaimefrio Why would this be a feature? How would it be different from equally explicit dtype:
```py
a = np.fromiter(obj_generator, dtype=object, count=3)
a = np.array(list(obj_generator), dtype=object)
```

**Comment by eric-wieser** [comment] 2017-12-02 07:54
Closing this issue since the underlying problem is not realizing `np.long is long` (#6103)

**Closed by eric-wieser** 2017-12-02 07:54 UTC
