### ISSUE TITLE
Numpy treatment of self-recursive lists

### ISSUE THREAD

**Issue by abalkin** [numpy/numpy#8259] opened 2016-11-08 21:59 UTC
Is this expected?

```
>>> x = [None]
>>> x[0] = x
>>> x
[[...]]
>>> import numpy as np
>>> np.array(x)
array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]], dtype=object)
>>> a = np.array(x)
>>> a.shape
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
>>> np.__version__
'1.11.1'
```

**Comment by charris** [comment] 2016-11-08 23:26
I think the descent into the dimensions is expected, OTOH, I would have expecte and error when it hit the maximum 32 dimensions rather than tossing the remainder into an object.

**Comment by adler-j** [comment] 2016-11-14 04:28
Very much related to #7901

**Comment by eric-wieser** [comment] 2019-04-24 06:14
Closing as a duplicate of #7901, I think these are clearly the same problem.

Note that the output is now the only marginally less cryptic
```
array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[list([[...]])]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]],
      dtype=object)
```

**Closed by eric-wieser** 2019-04-24 06:14 UTC
