### ISSUE TITLE
numpy.random.multinomial generating incorrect outputs for large n

### ISSUE THREAD

**Issue by junaid572** [numpy/numpy#16587] opened 2020-06-12 14:16 UTC
multinomial function from numpy.random produces incorrect output when the number of experiments, n, (the first argument) is greater than 1e9. 
Additionally, an error message is printed when n = 1e15.
The issue seems to be reproducible only on Windows. The behavior is as intended on ubuntu and macOS. 
### Reproducing code example:

```python
import numpy as np
N = 10**10
freq = np.random.multinomial(N, [0.5, 0.5])/N
print(freq) # should be close to [0.5, 0.5] but is array([0.07050322, 0.07050332])
```

### Error message (only when N = 10**15):

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4214, in numpy.random.mtrand.RandomState.multinomial
  File "_common.pyx", line 352, in numpy.random._common.check_constraint
ValueError: n < 0

### Numpy/Python version information:
1.18.5 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

**Comment by bashtage** [comment] 2020-07-01 16:46
I don't think this is fixable since you are using RandomState. You should be using `np.random.Generator` which does not have this issue.  It is due to RandomState using 32 bit integers on Windows while it uses 64 bit integers on other platforms. Generator always uses 64 bit integers.

**Comment by bashtage** [comment] 2020-07-02 14:34
@mattip I think this is a won't fix issue since it is a limitation of using C long in RandomState on Windows.

**Comment by rossbar** [comment] 2020-07-10 21:08
Closing as the issue is fixed in `numpy.random.Generator`, thanks @bashtage

**Closed by rossbar** 2020-07-10 21:08 UTC
Labels: component: numpy.random
