### ISSUE TITLE
Strange error under Apache and mod_wsgi

### ISSUE THREAD

**Issue by blagasz** [numpy/numpy#8559] opened 2017-02-03 16:23 UTC
I am building a web app with Flask when I encountered the strangest error. 

`pandas-0.19.2` calls in `pandas.core.indexing`

    # 32-bit floating point machine epsilon
    _eps = np.finfo('f4').eps

The call never finish in `numpy-1.12.0` when called from the Apache server environment with `mod_wsgi` (compiled for `Python/3.5.1+` and runtime using `Python/3.5.2`). The code loads properly when run from a normal `Python/3.5.2` interpreter.

The very same code executes properly with `pandas-0.18.1` and `numpy-1.11.1` in the same Apache setup.

**Comment by charris** [comment] 2017-02-03 16:46
I don't see any changes in `numpy/core/{machar.py, getlimits.py}` that should make a difference, the only thing added is a number of bits attribute (itemsize * 8). How did you install numpy? Are you sure that that line is where the hang occurs?

**Comment by blagasz** [comment] 2017-02-03 16:53
I installed numpy with pip3 on Ubuntu. I couldn't get any traceback, so I traced the error with the primitive print messages method. I could trace it to the `machar.py` line #226 and the print statement after the for cycle never gets called.

**Comment by matthew-brett** [comment] 2017-02-03 17:09
I wonder whether this is a problem with the manylinux wheel not finding Python symbols?  Have a look at [this thread](https://mail.python.org/pipermail/distutils-sig/2016-February/028275.html).

Does it work correctly when you compile numpy yourself (`pip3 install --no-binary numpy numpy`) or use the system numpy (`apt-get install python-numpy`)?

**Comment by charris** [comment] 2017-02-03 17:15
Doesn't seem like the code itself is at fault as the number of repeats is limited.

**Comment by njsmith** [comment] 2017-02-03 17:33
Does mod_wsgi use subinterpreters?

**Comment by pv** [comment] 2017-02-03 17:38
mod_wsgi uses Python subinterpreters. IOW, this is likely duplicate of 
gh-5856

**Comment by njsmith** [comment] 2017-02-03 17:53
So basically: numpy + default-configured-mod_wsgi is not a supported
configuration. It might work sometimes, but other times you will hit issues
like this, and we don't have any realistic plan for how to make numpy safe
for multiple subinterpreters.

You might be able to avoid the issue by configuring mod_wsgi not to use
subinterpreters, possibly with the WSGIApplicationGroup directive. Or there
are lots of ways to host a wsgi app besides mod_wsgi.

**Comment by charris** [comment] 2017-02-03 20:28
Closing this as a duplicate of #5856. I expect this particular problem is fixed by #8505, but the subinterpreter problem in general still remains.

**Closed by charris** 2017-02-03 20:28 UTC
Labels: 11 - Bug, 13 - Wish List, 50 - Duplicate

**Comment by blagasz** [comment] 2017-02-06 13:28
Thank you guys for the quick and satisfying explanation.
