### ISSUE TITLE
np.linalg.eigvals() unexpected results on ARM CPUs

### ISSUE THREAD

**Issue by millettmb** [numpy/numpy#18422] opened 2021-02-16 04:06 UTC
### Reproducing code example:
1. Procure 2x EC2 instances, ideally a `t2.micro` (x86) and `t4g.micro` (ARM) running Ubuntu 20.04 LTS (freetier)
2. `sudo apt update && sudo apt install python3-pip && pip3 install numpy` to install requirements
3. Open a `python3` interactive shell to run the following code:

```python
import numpy as np
values = [-20, 2, 3, 4, 5, 4, 3, 2]
values = values[int(non_zero[0]):int(np.non_zero[-1])+1]
_, e = np.frexp(values[::-1])
c = int(-0.5 * (np.max(e) + np.min(e)))
p = values[::-1]
p = np.ldexp(p, c)
A = np.diag(np.full(p.size - 2, p[0]), k=-1)
A[0,:] = -p[1:]
eigenvalues = np.linalg.eigvals(A)
print(eigenvalues)
```

(All values up until the `eigvals` function call are equal on both machines)

On the ARM based CPU, you will see the following output:
`[-0.14294258 -0.05014252 -0.06678331 -0.06036967  0.01308302 -0.29849543
  0.23065051]`

On the x86 based CPU, you will see the following output:
`[-0.35561591+0.14999412j -0.35561591-0.14999412j -0.10977392+0.35797579j
 -0.10977392-0.35797579j  0.15723786+0.31047243j  0.15723786-0.31047243j
  0.24130395+0.j        ]`

There is no stack trace or error thrown. 

### Error:
I believe that the eigenvalues produced on the ARM CPU are incorrect, as they do not include complex conjugate pairs (with real number input). It's been a while since I've studied linear algebra, but I believe this to be the case.

I found this error originally due to an issue I encountered with the `numpy_financial` package, which calls the `np.linalg.eigvals` function from the `irr` function. More information on the issue over there: https://github.com/numpy/numpy-financial/issues/37

### NumPy/Python version information:
Both machines running Ubuntu 20.04 LTS, kernel 5.4.0-1047-aws. Python version 3.8.5. Numpy version 1.20.1.

**Comment by millettmb** [comment] 2021-02-16 04:46
So after a bit more tinkering, I've found out a way to solve this issue. You'll need to follow along with the guide here: https://github.com/aws/aws-graviton-getting-started/blob/master/python.md.

1. If you already have `numpy` installed through `pip`, uninstall it using `pip3 uninstall numpy`
2. Run the following code:

```
sudo apt update
sudo apt-get install build-essential python3-pip python3-dev libblas-dev gfortran liblapack-dev
python3 -m pip install --user --upgrade pip
sudo apt -y install python3-scipy python3-numpy libopenblas-dev libblis-dev
sudo update-alternatives --set libblas.so.3-aarch64-linux-gnu \
    /usr/lib/aarch64-linux-gnu/blis-openmp/libblas.so.3
```
3. Install `numpy_financial` if you haven't already, this will use the `numpy` version we have just installed
4. Open a Python interactive shell and enter the following code to test that it's been installed properly

```
import numpy_financial
numpy_financial.irr([-20, 2, 3, 4, 5, 4, 3, 2])
```
If all has gone well, you should get a result of `0.03603774756546341`. If it's been installed incorrectly, you'll get a value of `0.08389095415117676`.

How should we best inform the ARM user base of this issue? Should we include some information on the `numpy` install guide (https://numpy.org/install)? Currently there's no information there about ARM based installations, and installing `numpy` following the guide there on ARM CPUs is susceptible to reproducing the issue listed above.

**Comment by millettmb** [comment] 2021-02-16 04:56
I've found that there is a specific repo for the `numpy` website, and have since moved the discussion to the issue listed here https://github.com/numpy/numpy.org/issues/401.

**Comment by mattip** [comment] 2021-02-16 07:58
I could not reproduce on an ARM64 machine. I  used a virtualenv instead of installing via `sudo pip3`, which is really to be avoided. After deleting line 3 of your script, and then doing
```
sudo apt install virtualenv
virtualenv -p python3.7 venv3
venv3/bin/python -m pip install numpy==1.20
<run script>
```

I got the correct complex output. I am confused why updating the system openblas library had any effect: we ship our own OpenBLAS in the wheel. When you do `ldd $(venv3/bin/python -c "import numpy; print(numpy.core._multiarray_umath.__file__)")` you should see
- that it is using numpy from inside the virtualenv 
- that it links to `numpy.libs/libopenblasp-r0-3c76c92e.3.13.dev.so`, which is OpenBLAS 0.3.13 with a mangled name.

Are you sure you are using the pip-installed numpy and not the system one?

**Comment by rgommers** [comment] 2021-04-05 20:40
Graviton is a custom chip from Amazon that AFAIK is only available on AWS. It does however look like `pip` will install `aarch64` manylinux wheels from PyPI. And apparently OpenBLAS has an issue with the Graviton chip.

I don't think it's reasonable for us to have specific install instructions for an AWS-specific chip on https://numpy.org/install/, especially since our wheels are supposed to just work. There is something really broken here though it looks like.

**Comment by rgommers** [comment] 2021-04-05 20:42
@millettmb if you could try the following, that'd be helpful:

1. Install numpy with `pip install numpy` (use a separate virtualenv if needed to not mess up your working install).
2. Run `python -c "import numpy as np; np.test()"` and report the output.

**Comment by boegel** [comment] 2021-05-24 07:42
I'm seeing the same problem with numpy 1.20.3 using GCC 10.3, binutils 2.36.1, Python 3.9.5, OpenBLAS 0.3.15.

I can reproduce the issue with the `np.linalg.eigvals` test script provided by @millettmb: on Intel and AMD systems I'm getting the correct result (`[[-0.35561591...`), likewise on POWER9.
On an AWS Graviton2 instance (`c6gd.2xlarge`), I'm getting the wrong result (`[-0.14294258 ...`).

54 tests in the numpy test suite fail (see attached output), most of them with `LinAlgError: Eigenvalues did not converge` or `LinAlgError: SVD did not converge in Linear Least Squares` (not sure if those could have the same underlying cause?).

The output also includes messages like this 51 times:

```
  ** On entry to DLASCL parameter number  4 had an illegal value
```

(sometimes it's `parameter number 5`)

Thanks to linking numpy with [FlexiBLAS](https://www.mpi-magdeburg.mpg.de/projects/flexiblas) I can easily switch to a different BLAS library. When using [BLIS](https://github.com/flame/blis) 0.8.1, I'm not seeing the problem: the `np.linalg.eigvals` test case produces the correct result, and the numpy test suite passes fully.
That tells me the problem is in OpenBLAS 0.3.15.

Maybe @martin-frbg has any ideas here?

**Comment by martin-frbg** [comment] 2021-05-24 10:56
Graviton2 (NEOVERSEN1 target in OpenBLAS) is using the same GEMM kernels as most other supported ARMV8 cpus (originally written for ThunderX2T99 and provided by someone from Cavium in 2017/18). Unfortunately it is not covered by any of the current CI setups, I will need to look into getting AWS instances set up. The DLASCL errors suggest that NaNs are generated somewhere - as the input seems to be valid, perhaps things are getting miscompiled ?

**Comment by mattip** [comment] 2021-05-24 11:33
@seiko2plus any thoughts?

**Comment by boegel** [comment] 2021-05-24 12:10
@martin-frbg I can put you in touch with somebody at AWS who may be able to provide some free credits for testing on Graviton2, send me an email if you're interested.

**Comment by martin-frbg** [comment] 2021-05-24 14:46
@boegel thx - I belatedly remembered that there is/was  Graviton2 access on Travis so if/while that is still avaiable I'll try to reproduce the issue there first. (I do notice that the regular LAPACK testsuite run does not look particularly bad there)

**Comment by seiko2plus** [comment] 2021-05-26 20:25
First, the issue appears in (neoverse-n1) processors, while other processors such as (Cortex-A53) do not show any errors. It seems the errors occur if one of the following SIMD features is available (asimdhp asimdrdm asimddp). 

Secondly, By testing `LAPACKE_dgeev` with args (LAPACK_ROW_MAJOR, 'N', 'N', ...) on `Cortex-A53` returned zero while `neoverse-n1` was returning the number of dimensions.

Third, I tried to rebuild OpenBLAS with option `DYNAMIIC_ARCH` on different versions of GCC but I was not able to reproduce test errors on `neoverse-n1` and `LAPACKE_dgeev` was working just fine on both processors.

Eventually, I think the problem is not general, and it might be specific to the compiler who built it or, with the compiler build options. I wonder if someone could provide me the version of the compiler that built the library and the build log so that I could be able to reproduce the errors.

**Comment by boegel** [comment] 2021-05-27 08:05
@seiko2plus Thanks for the help on this!

For me, on AWS Graviton2, I was using the following software versions:
* GCC 10.3.0 + binutils 2.36.1
* Python 3.9.5
  configured with:
  ```
  export CFLAGS="-O2 -ftree-vectorize -mcpu=native -fno-math-errno -fPIC"
  ./configure --build=aarch64-unknown-linux-gnu  --host=aarch64-unknown-linux-gnu  --enable-shared  --with-lto  --enable-optimizations  --with-ensurepip=upgrade
  ```
* OpenBLAS 0.3.15, built with:
  ```
  make -j 8 libs netlib shared  BINARY='64'  CC='gcc'  FC='gfortran'  MAKE_NB_JOBS='-1'  USE_OPENMP='1'  USE_THREAD='1'  CFLAGS='-O2 -ftree-vectorize -mcpu=native -fno-math-errno'
  ```
   (so not using `DYNAMIC_ARCH`)
   `make tests` passed in full for this OpenBLAS build
* FlexiBLAS 3.0.4 using OpenLAS 0.3.15 as a backend
* numpy 1.20.3, which is linked to OpenBLAS via FlexiBLAS
   using the following (auto-generated) `site.cfg`:
    ```
    [DEFAULT]
    library_dirs = /software/GCCcore/10.3.0/lib64:/software/GCCcore/10.3.0/lib:/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib64:/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib:/software/ScaLAPACK/2.1.0-gompi-2021.04-fb/lib64:/software/ScaLAPACK/2.1.0-gompi-2021.04-fb/lib:/software/FFTW/3.3.9-gompi-2021.04/lib64:/software/FFTW/3.3.9-gompi-2021.04/lib
    include_dirs= /software/FlexiBLAS/3.0.4-GCC-10.3.0/include:/mnt/shared/home/boegel/software/FFTW/3.3.9-gompi-2021.04/include
    search_static_first=True
    [atlas]
    atlas_libs = flexiblas, gfortran
    [lapack]
    lapack_libs = flexiblas, gfortran
    [fftw]
    libraries = fftw3
    ```
    relevant output from `python setup.py config`:
    ```
    atlas_blas_threads_info:
    ...
      FOUND:
        language = c
        define_macros = [('HAVE_CBLAS', None)]
        libraries = ['flexiblas', 'gfortran']
        library_dirs = ['/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib64', '/software/GCCcore/10.3.0/lib64']
    ...
      FOUND:
        libraries = ['flexiblas', 'gfortran', 'flexiblas', 'gfortran']
        library_dirs = ['/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib64', '/software/GCCcore/10.3.0/lib64']
        language = c
        define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', 1)]
    ```
    ```
    lapack_info:
      libraries lapack not found in [...]
    Library lapack was not found. Ignoring
      FOUND:
        libraries = ['flexiblas', 'gfortran']
        library_dirs = ['/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib64', '/software/GCCcore/10.3.0/lib64']
        language = f77

      FOUND:
        libraries = ['flexiblas', 'gfortran', 'flexiblas', 'gfortran']
        library_dirs = ['/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib64', '/software/GCCcore/10.3.0/lib64']
        language = c
        define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', 1)]
    ```

**Comment by ggouaillardet** [comment] 2021-06-13 12:40
That really looks like a gcc bug

here is a reproducer

```c
#include <stdio.h>

extern void dgeev_(char*, char*, int *, double*, int *, double *, double *, double *, int *, double *, int *, double *, int *, int *);

int main(int argc, char *argv[]) {
        char JOBVL = 'N';
        char JOBVR = 'N';
        int N = 3;
        double A[9] = {1, 4, 7, 2, 5, 8, 3, 6, 9};
        int LDA = 3;
        double WR[3] = {-1, -1, -1};
        double WI[3] = {-1, -1, -1};
        double VL[9] = {-1, -1, -1, -1, -1, -1, -1, -1, -1};
        int LDVL = 3;
        double VR[9] = {-1, -1, -1, -1, -1, -1, -1, -1, -1};
        int LDVR = 3;
        double WORK[102];
        int LWORK = 102;
        int info = 666;

        dgeev_(&JOBVL, &JOBVR, &N, A, &LDA, WR, WI, VL, &LDVL, VR, &LDVR, WORK, &LWORK, &info);

        printf("info = %d\n", info);
        return 0;
}
```

The expected behavior is `info = 0`.
It works fine when `openblas` is built with `gcc 8.3.1` or `gcc 8.5.0`, but fails with `gcc 9.4.0` and later
(I will keep digging to find if the issue occurred in the middle of the gcc 9 series)

**Comment by ggouaillardet** [comment] 2021-06-13 15:40
Two more datapoint.

`gcc 9.1.0` fails the test (read only the gcc 8 series can pass this test), and even at `-O1`.
The code is still a bit optimized at `-O1` and I am having some hard time isolating the bug ...

I will continue tomorrow (my timezone).

**Comment by ggouaillardet** [comment] 2021-06-14 05:30
I filled this `gfortran` bug at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101053

**Comment by martin-frbg** [comment] 2021-06-14 06:27
might be interesting to see if the bug occurs with plain "netlib" Reference-LAPACK as well, seems Andrew Pinski  suspects something else is clobbering registers in between.(But did he try on Graviton2 ratger than generic armv8?)

**Comment by martin-frbg** [comment] 2021-06-14 06:44
otherwise the DNRM2KERNEL entry in kernel/OpenBLAS/arm64/KERNEL.NEOVERSEN1 would be a good candidate for replacing (setting to nrm2.S as in other KERNEL files there)
The ThunderX2 version currently used for Graviton2 got some fixes for Inf/NaN handling somewhat recently which may have introduced a new glitch

**Comment by martin-frbg** [comment] 2021-06-14 07:08
meh - could you check if adding "d9" (from above-mentioned change) to the clobber list in line 324 of dznrm2-thunderx2t99.c fixes this ?

**Comment by ggouaillardet** [comment] 2021-06-14 07:14
yeah, I spotted some inline assembly that does not restore a register as it should ...

**Comment by ggouaillardet** [comment] 2021-06-14 07:15
```patch
--- orig/OpenBLAS-0.3.15/kernel/arm64/dznrm2_thunderx2t99.c     2021-05-03 06:50:22.000000000 +0900
+++ OpenBLAS-0.3.15/kernel/arm64/dznrm2_thunderx2t99.c  2021-06-14 15:54:26.087232321 +0900
@@ -321,7 +321,7 @@
        : "cc",
          "memory",
          "x0", "x1", "x2", "x3", "x4", "x5", "x6",
-         "d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8"
+         "d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8", REGINF
        );
 
 }
```

fixed one bug ... I am now checking if there are some remaining issues

**Comment by AGSaidi** [comment] 2021-06-16 14:37
@martin-frbg TravisCI does support Graviton. There are instructions for using it [here](https://aws.amazon.com/blogs/opensource/getting-started-with-travis-ci-com-on-aws-graviton2/). I'm also happy to help gen you access to a Graviton instance directly.

**Comment by martin-frbg** [comment] 2021-06-16 14:45
I was misled by the OpenBLAS Ci job still using travis-ci.org rather than .com (and the "Graviton" job silently running on Intel), and I still need Xianyi to make administrative changes to CI setups (like initiating the migration to travis-ci.com) as the github project is still "owned" by him alone.

**Comment by AGSaidi** [comment] 2021-06-16 15:34
I ran `make lapack-test` manually having built both the NEOVERSEN1 target and the ARMV8 generic target on a 64c graviton2 system. 

For the n1 target there is one failure:
```
Testing REAL              RFP-linear-equation-routines-LIN/xlintstrfs < stest_rfp.in > stest_rfp.out   STFSM auxiliary routine:     1 out of  7776 tests failed to pass the threshold
 passed: 5352
failing to pass the threshold: 1

			-->   LAPACK TESTING SUMMARY  <--
SUMMARY             	nb test run 	numerical error   	other error
================   	===========	=================	================
REAL             	1308369		1	(0.000%)	0	(0.000%)
DOUBLE PRECISION	1316957		0	(0.000%)	0	(0.000%)
COMPLEX          	776316		0	(0.000%)	0	(0.000%)
COMPLEX16         	777128		0	(0.000%)	0	(0.000%)

--> ALL PRECISIONS	4178770		1	(0.000%)	0	(0.000%)

```


For the generic target there are many :( including segfaults...
```

			-->   LAPACK TESTING SUMMARY  <--
SUMMARY             	nb test run 	numerical error   	other error
================   	===========	=================	================
REAL             	88181		118062	(133.886%)	367	(0.416%)
DOUBLE PRECISION	88181		116933	(132.606%)	425	(0.482%)
COMPLEX          	92124		115390	(125.255%)	387	(0.420%)
COMPLEX16         	182513		37412	(20.498%)	31	(0.017%)

--> ALL PRECISIONS	450999		387797	(85.986%)	1210	(0.268%)
```

**Comment by martin-frbg** [comment] 2021-06-16 16:00
The is an elusive single failure in REAL on most systems (can't remember right now what it is), usually accompanied by a single failure in the corresponding COMPLEX function - as far as I can tell, these may be actual inaccuracies in the respective tests.
The carnage for GENERIC (I assume ARMV8 ?) looks like something fundamental went wrong - this should be almost all plain C kernels. I'll see if I can reproduce it on local hardware. (Reporting more numerical errors than tests run does not make much sense either, I wonder if the python script just went haywire)

**Comment by AGSaidi** [comment] 2021-06-16 16:13
>  (I assume ARMV8?)

Correct:
```
make TARGET=ARMV8
```

**Comment by martin-frbg** [comment] 2021-06-16 16:20
Should be nowhere near as bad (it is not in any of the CI runs, but I do run it semi-regularly locally). And the one in REAL on Graviton should be STFSM I think - if it is what I call the "usual" one... would you happen to have the testing_results.txt available ?

**Comment by AGSaidi** [comment] 2021-06-16 16:34
Tried to replicate the issue with `TARGET=ARMV8` and they all passed but one. I'm trying to figure out what i did the first time around, but sorry about the noise. 

Both ARMV8 and the NEOVERSEN1 target fail on this test.

ARMV8 output:
```
 *** Error(s) or Failure(s) while testing STFSM               ***
      Failure in STFSM, CFORM='T', SIDE='L', UPLO='U', TRANS='T', DIAG='N', M= 50, N = 50, test=  42.299
  STFSM auxiliary routine:     1 out of  7776 tests failed to pass the threshold
```
Neoverse N1 output:
```
  *** Error(s) or Failure(s) while testing STFSM               ***
      Failure in STFSM, CFORM='T', SIDE='L', UPLO='U', TRANS='T', DIAG='N', M= 50, N = 50, test=  33.319
  STFSM auxiliary routine:     1 out of  7776 tests failed to pass the threshold
```

**Comment by martin-frbg** [comment] 2021-06-16 16:41
Most likely culprit would be a mismatch of gcc and (lib)gfortran, that would usually be blowing up left and right due to ABI mismatch. I can discuss the STFSM thing with the Reference-LAPACK people if you like, but IIIRC  from the documentation of the tests and earlier discussions, a serious test failure would be orders of magnitude away from the threshold, not something like 42 instead of an expected 20 (again IIRC)

**Comment by mattip** [comment] 2021-07-27 20:12
@millettmb could you update this issue after trying the latest release 1.21.1 with OpenBLAS v0.3.17?

**Comment by boegel** [comment] 2021-09-08 07:44
For me the OpenBLAS patch by @ggouaillardet fixed the problems we were seeing with the numpy test suite on `aarch64`/Graviton2, cfr. https://github.com/easybuilders/easybuild-easyconfigs/issues/11959

**Comment by mattip** [comment] 2022-05-07 17:15
The original reporter did not update with new information, but another user did confirm the issue is fixed. I will close the issue, please reopen if I am mistaken.

**Closed by mattip** 2022-05-07 17:15 UTC
Labels: 00 - Bug, component: numpy.linalg
