### ISSUE TITLE
Matmul extremely slow when used on the real/imag part of a comlex128 array

### ISSUE THREAD

**Issue by pj1989** [numpy/numpy#17810] opened 2020-11-20 10:19 UTC
`matmul` (aka `@`) is extremely slow when one of the two arrays is the real or imaginary part of a complex array extracted with `.real` or `.imag`.

This was already observed in [this issue](https://github.com/numpy/numpy/issues/13229), but was not marked as a bug, while I think this should be.

### Reproducing code example:

Consider the following benchmark. 

```python
import numpy as np
from timeit import repeat

A  = np.random.rand(200, 1000) + 0j
B = np.random.rand(1000, 50000)

def time(stmt):
    print(f'testing {stmt}')
    res = repeat(stmt, globals={'A':A,'B':B, 'np':np}, number=1, repeat=10)
    res = np.array(res)*1000
    print(f'{np.mean(res):.0f} ms ± {np.std(res):.0f} ms per loop (mean ± std. dev. of 10 runs, 1 loop each)')

time('A @ B')
time('A.real @ B')
time('A.imag @ B')
time('A.astype(np.float64()) @ B')
time('A.real.astype(np.float64()) @ B')
time('A.real.copy() @ B')
```
On my PC the results are:

```
testing A @ B
1046 ms ± 73 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

testing A.real @ B
21980 ms ± 4978 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

testing A.imag @ B
18140 ms ± 970 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

testing A.astype(np.float64()) @ B
<string>:6: ComplexWarning: Casting complex values to real discards the imaginary part
161 ms ± 16 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

testing A.real.astype(np.float64()) @ B
166 ms ± 12 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)

testing A.real.copy() @ B
150 ms ± 11 ms per loop (mean ± std. dev. of 10 runs, 1 loop each)
```

Note how the most trivial/elegant/obvious solution `A.real @ B` (and `A.imag @ B` depending on what you have to do) is 120 times slower than `A.real.copy() @ B`

Also `A@B` is much slower, but I suspect this has to be with the fact that in this case `A` is complex bringing `matmul` on a different path, even if `A.imag` is all 0.

### NumPy/Python version information:
```
import sys, numpy; print(numpy.__version__, sys.version)
1.18.1 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
```

**Comment by rgommers** [comment] 2020-12-30 16:54
Thanks @pj1989. I copied your comment to gh-13229, and will close this as a duplicate of that issue.

**Closed by rgommers** 2020-12-30 16:54 UTC
