### ISSUE TITLE
operator.pos does not trigger __array_ufunc__

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#9166] opened 2017-05-23 19:04 UTC
Consider the following example:

```
import numpy as np
from operator import abs, neg, pos

class MyArr(np.ndarray):
    def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
        print('calling array_ufunc from %s' % ufunc)
        func = getattr(ufunc, method)
        inp = [i.view(np.ndarray) for i in inputs]
        return func(*inp, **kwargs)

data = np.array([[1, 2, 3], [1, 2, 3]])

arr = data.view(MyArr)

for op in abs, neg, pos:
    print(op(arr))
    print(type(op(arr)))
```

In numpy 1.13rc2, this prints:

```
calling array_ufunc from <ufunc 'absolute'>
[[1 2 3]
 [1 2 3]]
calling array_ufunc from <ufunc 'absolute'>
<class 'numpy.ndarray'>
calling array_ufunc from <ufunc 'negative'>
[[-1 -2 -3]
 [-1 -2 -3]]
calling array_ufunc from <ufunc 'negative'>
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]]
<class '__main__.MyArr'>
```

So it looks like `__array_ufunc__` isn't being invoked even though there is now a `np.positive` ufunc.

**Comment by ngoldbaum** [comment] 2017-05-23 19:06
ping @mhvk

**Comment by eric-wieser** [comment] 2017-05-23 19:36
This is by design - it was decided not to change `ndarray.__pos__` to invoke `np.positive`, due to compatibility concerns (a simple implementation would break `-string_array`).

I think @mhvk or @shoyer can probably give a more insightful rationale.

Perhaps the existance of `__array_ufunc__` in a subclass should force the new behaviour into action?

**Comment by shoyer** [comment] 2017-05-23 19:40
Closing this in favor #9081, where we've discussed a few options for what to do here.

This is currently described in a footnote in the NEP: https://github.com/numpy/numpy/blob/master/doc/neps/ufunc-overrides.rst#list-of-operators-and-numpy-ufuncs

**Closed** 2017-05-23 19:41 UTC
