### ISSUE TITLE
np.timedelta64 does not accept np.int64

### ISSUE THREAD

**Issue by denfromufa** [numpy/numpy#7462] opened 2016-03-25 21:55 UTC
`np.timedelta64(2,'h')` returns `numpy.timedelta64(2,'h')`, but `np.timedelta64(np.int64(2),'h')` returns:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-75-fd40c0d8eac0> in <module>()
----> 1 np.timedelta64(np.int64(2),'h')

ValueError: Could not convert object to NumPy timedelta

```

**Comment by denfromufa** [comment] 2016-03-25 21:57
np.version.full_version='1.10.4'

**Comment by charris** [comment] 2016-03-26 00:28
This is fixed in numpy 1.11.0, which should be out this weekend.
```
In [1]: np.timedelta64(np.int64(2),'h')
Out[1]: numpy.timedelta64(2,'h')
```

**Closed by charris** 2016-03-26 00:28 UTC

**Comment by denfromufa** [comment] 2016-03-26 03:22
Can you point me to corresponding PR?

Looks like this is not documented in release notes for numpy 1.11.0

In the meantime I put this question on SO before you replied here on github:

http://stackoverflow.com/questions/36228799/np-timedelta64-does-not-accept-np-int64

Feel free to answer on SO, so that I can accept your answer.

**Comment by shoyer** [comment] 2016-03-26 03:39
I'm not sure exactly what was going on here, but if this was fixed in 1.11 I suspect this is the patch that did it: https://github.com/numpy/numpy/pull/6465

As you can see from that discussion, datetime64/timedelta64 has been somewhat neglected over the past few years, and nobody thought very carefully about dtype promotion rules involving them until numpy 1.10 enabled stricter type coercion by default.

I'm pretty sure there is no test coverage for this case so at the very least that would be a welcome addition.

**Comment by mdickinson** [comment] 2017-01-20 17:22
I'm not seeing the fix on Windows. I do see the desired behaviour on OS X / Linux, but that seems to date back to at least version 1.9.

Here's a Windows session (Python 2.7.11, NumPy 1.11.3). `int32` is accepted, but `int64` is not.
```
Python 2.7.11 |Master 2.1.0.dev1849 (64-bit)| (default, Jun 11 2016, 11:33:47) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.11.3'
>>> numpy.timedelta64(numpy.int64(3), 'D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Could not convert object to NumPy timedelta
>>> numpy.timedelta64(numpy.int32(3), 'D')
numpy.timedelta64(3,'D')
```

On OS X, it appears to be the reverse behaviour: `np.int64` is accepted, but `np.int32` is not.
```
Python 2.7.12 |Enthought, Inc. (x86_64)| (default, Dec  9 2016, 02:53:04) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.11.3'
>>> numpy.timedelta64(numpy.int64(3), 'D')
numpy.timedelta64(3,'D')
>>> numpy.timedelta64(numpy.int32(3), 'D')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Could not convert object to NumPy timedelta
```

I see the exact same behaviour (on both platforms) with NumPy 1.9.

At a guess `np.int64` is accepted on OS X simply because it's a subclass of `int`, and similarly for `np.int32` on Windows.

**Comment by seberg** [comment] 2017-01-20 17:27
Which means that python ints are accepted.

**Comment by mdickinson** [comment] 2017-01-22 08:32
Looks like this is a duplicate of #7617, in any case.
