### ISSUE TITLE
random.uniform documentation suggests `high` is excluded

### ISSUE THREAD

**Issue by mdickinson** [numpy/numpy#10803] opened 2018-03-26 11:09 UTC
There's a possibility of confusion from the `np.random.uniform` documentation, which says:

> Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high).

Arguably, that's true, in the sense that we're using an expression that (mathematically) draws from `[low, high)`, but rounding and numerical errors mean that in practice, `high` _can_ be generated:

```
>>> low = 1.0
>>> high = 1.0 + 2**-40
>>> low, high, low < high
(1.0, 1.0000000000009095, True)
>>> np.random.uniform(low, high, size=10**6).max() == high
True
```

The current documentation leads to people (well, at least one SO user) writing things like `np.random.uniform(low, np.nextafter(high, np.inf))` when they want a closed interval, which probably isn't a good idea:

```
>>> np.random.uniform(low, np.nextafter(high, np.inf), size=10**6).max() > high
True
```

**Comment by SahanaJavgal** [comment] 2019-03-31 03:19
Hello, Im new to Open Source and I am Applying for Outreachy. I would like to work on this Issue. Could you please assign it to me

**Comment by eric-wieser** [comment] 2019-03-31 04:41
This strikes me as a bug in uniform

**Comment by rkern** [comment] 2019-04-01 02:53
No, just sloppy documentation. Given floating point arithmetic, it is actually pretty hard to come up with an algorithm that guarantees the `[closed, open)` condition for arbitrary ranges (and is simple and efficient). What we currently have in the docstring is the _intention_ of the code. The appropriate thing to do is document the caveat, [like the stdlib `random` module does](https://docs.python.org/3/library/random.html#random.uniform).

**Comment by eric-wieser** [comment] 2019-04-08 04:04
> it is actually pretty hard to come up with an algorithm that guarantees the [closed, open) condition for arbitrary ranges

Is it sufficient to change the FPU rounding mode to be `FE_DOWNWARD`?

**Comment by RyanWangGit** [comment] 2019-04-18 19:26
If `high` is actually sometimes generated, then I think there's also a problem in generating other random distributions which relies on uniform being [0, 1), see  #13361.

By the way, can you confirm that `low` **can** be picked? Using the same method:
```
>>> low = 0.0
>>> high = 0.0 + 2**-40
>>> low, high, low < high
(0.0, 9.094947017729282e-13, True)
>>> np.random.uniform(low, high, size=10**8).min() == low
False
```

**Comment by rkern** [comment] 2019-04-18 22:40
Yes. `rk_double()` returns a number in `[0, 1)`; specifically, the lowest number it generates is 0.0 and the highest is `((1<<53) - 1) / (1<<53)`. `rk_uniform()` computes a number in `[low, high]` (intending to be `[low, high)`) by computing `low + (high - low) * U`, where `U` is a draw from `rk_double()`. So if `U==0.0`, which is very rare so I wouldn't expect to see one in 10**8 draws, then floating point arithmetic guarantees that you get `low`. The problem with `high` only comes in these absurd ranges where `low + (high-low) * ((1<<53)-1)/(1<<53)` works out to be `high` or a little above.

The other places, like #13361, don't do this multiplication and don't suffer the same floating point error accumulation. `2-U-U > 0`.

**Comment by RyanWangGit** [comment] 2019-04-18 23:24
I see, I was mixing `rk_double()` and `rk_uniform()`.

Probably should add this to #13361: the problem is `U + U == 0` if `U == 0`.

**Comment by mdickinson** [comment] 2019-04-19 16:37
> The problem with `high` only comes in these absurd ranges where `low + (high-low) * ((1<<53)-1)/(1<<53)` works out to be `high` or a little above.

Why "absurd"? `[1.0, 1.5)` is such a range.

**Comment by rkern** [comment] 2019-04-19 16:41
Ah, oops. I only saw absurd examples and made a bad assumption.

What do you think of the suggestion to muck with the rounding mode? Examples suggest that it works, but I can only guess if that's provable.

**Comment by mdickinson** [comment] 2019-04-19 16:44
I'd be worried (a) about unintended consequences, and (b) about performance problems due to pipeline flushes. I'd also be bothered at some level about the effect on the actual distribution, but suspect that those effects aren't measurable at any reasonable level, so that's just my OCD.

IOW, I agree with your suggestion that

> The appropriate thing to do is document the caveat

**Comment by mdickinson** [comment] 2019-04-19 16:46
> (b) about performance problems due to pipeline flushes

Actually, I suppose this is unfounded, assuming that generations of random numbers are batched appropriately.

**Comment by mdickinson** [comment] 2019-04-19 16:54
As far as provability goes, yes, I believe that barring corner cases that we probably don't care about (overflows to infinity and the like) it should be possible to prove that changing the rounding mode to round-towards-zero works: the computed `high - low` will be provably no larger in absolute value than the exact difference, `max_random * (high - low)` should then be strictly smaller in absolute value than the exact difference, but with the correct sign, and then adding that to `low` can't take us as far as `high`.

**Comment by mdickinson** [comment] 2019-04-19 16:56
> then adding that to `low` can't take us as far as `high`.

Gah, not true. It can, if `low` and `high` are both negative, with `low < high`. Then the directed round on the result of the addition goes the wrong way (_towards_ `high`, rather than away from it), and could take us up to `high`. I dare say one could work around this case somehow.

**Comment by rkern** [comment] 2019-04-19 17:02
Okay, let's just document the current behavior. :-)

**Comment by eric-wieser** [comment] 2019-04-19 18:51
> it should be possible to prove that changing the rounding mode to round-towards-zero work

> Then the directed round on the result of the addition goes the wrong way

Surely round-towards-minus-infinity (`FE_DOWNWARD`) solves this?

**Comment by mdickinson** [comment] 2019-04-19 19:35
> Surely round-towards-minus-infinity (`FE_DOWNWARD`) solves this?

Ah yes, true; I was (wrongly) thinking in terms of round-towards-zero. Sorry. So for `low < high`, with round-towards-negative-infinity, yes, all three rounds go the right way (regardless of the sign of `low` or `high`) in `low + random() * (high - low)`.

For `low > high` (which is currently supported), you'd need to be a bit more careful to make sure everything rounds the right way. I think

`- (random() * (low - high) - low)`

should do it, again using FE_DOWNWARD.

For `low == high` (which is also currently supported), you'd need to make that an error if you want to forbid `high` from ever being produced. I'd expect that to break some corner cases in real code, so it's probably better just to allow `high` to be produced in that case.

**Closed** 2019-05-19 15:57 UTC
Labels: 04 - Documentation, component: numpy.random
