### ISSUE TITLE
BUG: pytest 6 test failing on M1

### ISSUE THREAD

**Issue by spyroot** [numpy/numpy#21322] opened 2022-04-11 10:30 UTC
### Describe the issue:

Hi Folks,

Is it normal that 6 tests fail on M1?   ( It looks like all 6 test for dtype=complex64)

```
FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/core/tests/test_ufunc.py::TestUfuncGenericLoops::test_unary_PyUFunc_O_O_method_full[reciprocal] - Assertion...
FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestSVDHermitian::test_herm_cases - AssertionError: In test case: <LinalgCase:...
FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestPinvHermitian::test_herm_cases - AssertionError: In test case: <LinalgCase...
FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestEighCases::test_herm_cases - AssertionError: In test case: <LinalgCase: hc...
FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/typing/tests/test_generic_alias.py::TestGenericAlias::test_getattr[__copy__] - AttributeError: 'types.Gener...
FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/typing/tests/test_generic_alias.py::TestGenericAlias::test_getattr[__deepcopy__] - AttributeError: 'types.G...
6 failed, 14311 passed, 98 skipped, 1253 deselected, 19 xfailed, 3 xpassed, 23 warnings in 109.99s (0:01:49)
```

### Reproduce the code example:

```python
I listed tests.  
This one is more verbose.  (it looks like most of test related to complex dtype) 

miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py:382:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <numpy.linalg.tests.test_linalg.TestPinvHermitian object at 0x12db0b580>, require = {'hermitian'}, exclude = {'generalized', 'size-0'}

    def check_cases(self, require=set(), exclude=set()):
        """
        Run func on each of the cases with all of the tags in require, and none
        of the tags in exclude
        """
        for case in self.TEST_CASES:
            # filter by require and exclude
            if case.tags & require != require:
                continue
            if case.tags & exclude:
                continue

            try:
                case.check(self.do)
            except Exception as e:
                msg = f'In test case: {case!r}\n\n'
                msg += traceback.format_exc()
>               raise AssertionError(msg) from e
E               AssertionError: In test case: <LinalgCase: hcsingle>
E
E               Traceback (most recent call last):
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 576, in assert_almost_equal
E                   assert_almost_equal(actualr, desiredr, decimal=decimal)
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 583, in assert_almost_equal
E                   return assert_array_almost_equal(actual, desired, decimal, err_msg)
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1046, in assert_array_almost_equal
E                   assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
E                   raise AssertionError(msg)
E               AssertionError:
E               Arrays are not almost equal to 5 decimals
E
E               Mismatched elements: 4 / 4 (100%)
E               Max absolute difference: 1.4734483
E               Max relative difference: 0.9652817
E                x: array([[0.57435, 3.47345],
E                      [3.47345, 0.03472]], dtype=float32)
E                y: array([[1., 2.],
E                      [2., 1.]], dtype=float32)
E
E               During handling of the above exception, another exception occurred:
E
E               Traceback (most recent call last):
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py", line 350, in check_cases
E                   case.check(self.do)
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py", line 85, in check
E                   do(self.a, self.b, tags=self.tags)
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py", line 835, in do
E                   assert_almost_equal(dot(dot(a, a_ginv), a), a, single_decimal=5, double_decimal=11)
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py", line 41, in assert_almost_equal
E                   old_assert_almost_equal(a, b, decimal=decimal, **kw)
E                 File "/Users/spyroot/miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 579, in assert_almost_equal
E                   raise AssertionError(_build_err_msg())
E               AssertionError:
E               Arrays are not almost equal to 5 decimals
E                ACTUAL: array([[0.5743456 +0.0000000e+00j, 3.4734483 +4.2373457e+00j],
E                      [3.4734483 -4.2373452e+00j, 0.03471828+5.9604645e-08j]],
E                     dtype=complex64)
E                DESIRED: array([[1.+0.j, 2.+3.j],
E                      [2.-3.j, 1.+0.j]], dtype=complex64)

case       = <LinalgCase: hcsingle>
exclude    = {'generalized', 'size-0'}
msg        = 'In test case: <LinalgCase: hcsingle>\n\nTraceback (most recent call last):\n  File "/Users/spyroot/miniconda3/envs/to...4645e-08j]],\n      dtype=complex64)\n DESIRED: array([[1.+0.j, 2.+3.j],\n       [2.-3.j, 1.+0.j]], dtype=complex64)\n'
require    = {'hermitian'}
self       = <numpy.linalg.tests.test_linalg.TestPinvHermitian object at 0x12db0b580>
```

### NumPy/Python version information:

>>> import sys, numpy; print(numpy.__version__, sys.version)
1.21.2 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]

**Comment by BvB93** [comment] 2022-04-11 11:52
> ``` 
> FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/typing/tests/test_generic_alias.py::TestGenericAlias::test_getattr[__copy__] - AttributeError: 'types.Gener...
> FAILED miniconda3/envs/torchenv/lib/python3.10/site-packages/numpy/typing/tests/test_generic_alias.py::TestGenericAlias::test_getattr[__deepcopy__] - AttributeError: 'types.G...
> ```
Can't speak for the other ones, but the bottom two are due to a Python >= 3.9.8 and >= 3.10.1 regression; this issue was fixed in numpy 1.21.5 (xref https://github.com/numpy/numpy/pull/20357).

**Comment by spyroot** [comment] 2022-04-13 04:12
I'll check 20357 but what about test_linalg ?  It looks like an issue with zero somewhere in the denominator.

**Comment by mattip** [comment] 2022-04-13 06:20
M1 can run in either x86_64 emulation mode or native arm64 mode. Do you know what you are using?

Is there a reason you are testing NumPy 1.21? As @BvB93 says, there are newer releases for that version, the one you are using has bugfixes. Did you enable the conda-forge channel in conda?

It is not clear what backend linalg is using: OpenBLAS or something else. It is a bit difficult to discover what happens at runtime. If this code succeeds you are using OpenBLAS:
```
import numpy as np
import ctypes
dll = ctypes.CDLL(np.core.multiarray._multiarray_umath.__file__)
get_config = dll.openblas_get_config
get_config.restype = ctypes.c_char_p
res = get_config()
print(res)
```

**Comment by mattip** [comment] 2022-04-13 06:53
FWIW, I can replicate on a M1 machine using the native arm64 version. The x86_64 variant passes cleanly. Here is what I did:
```
% conda create -y -n python310 python=3.10
% conda activate python310
% conda install -y numpy pytest hypothesis
% python
>>> import numpy as np
>>> np.__version__
'1.22.3'
>>> # report OpenBLAS version as above
b'OpenBLAS 0.3.20 NO_AFFINITY USE_OPENMP VORTEX MAX_THREADS=128'
>>> np.test(verbose=3)
...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestSVDHermitian::test_herm_cases - AssertionError: In tes...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestPinvHermitian::test_herm_cases - AssertionError: In te...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestEighCases::test_herm_cases - AssertionError: In test c...
```

The errors I get are similar to the ones in the OP. When I run
```
% python -m pytest ~/miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py
```

I get 6 failures:
```
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestSVDHermitian::test_generalized_herm_cases - AssertionE...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestSVDHermitian::test_herm_cases - AssertionError: In tes...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestPinvHermitian::test_generalized_herm_cases - Assertion...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestPinvHermitian::test_herm_cases - AssertionError: In te...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestEighCases::test_generalized_herm_cases - AssertionErro...
FAILED miniforge3/envs/python310/lib/python3.10/site-packages/numpy/linalg/tests/test_linalg.py::TestEighCases::test_herm_cases - AssertionError: In test c...
```

I would like to refactor this down to a simpler reproducer.

**Comment by spyroot** [comment] 2022-04-13 10:04
Yes,  I run everything in native arm64.  ( Python and the rest ).  Note it is the latest build for M1.  ( conda-forge) 
ver 1.21.2 
Python 3.10.4

**Comment by seberg** [comment] 2022-11-03 10:22
M1 support has been moving forward, going to close this for inactivity.  If the issues still exists, please just open a new issue.

**Closed by seberg** 2022-11-03 10:22 UTC
Labels: 00 - Bug
