### ISSUE TITLE
unexpected type deduction when values between 2^63 and 2^64 - 1

### ISSUE THREAD

**Issue by wyx528** [numpy/numpy#18875] opened 2021-04-29 05:28 UTC
When create a numpy array from a list of integers, if some integers are in range [2^63, 2^64) and some integers are in range [0, 2^63), we get a numpy array with `dtype=np.float64` instead of `dtype=np.uint64`.

### Reproducing code example:

```python
import numpy as np
import sys

a = np.array([2**63, 2**63 + 1, 2**63 + 2**62])
print(a, a.dtype) # It's ok!

a = np.array([2**63, 2**63 + 1, 2**63 + 2**62, 123456])
print(a, a.dtype) # In this case, a.dtype == np.float64, but we expect np.uint64

a = np.array([2**63, 2**63 + 1, 2**63 + 2**62, 123456], dtype=np.uint64)
print(a, a.dtype) # It's ok!

print(np.__version__, sys.version)
```

### NumPy/Python version information:

```
1.18.5 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0]
```

**Comment by bashtage** [comment] 2021-04-29 09:59
When you have something that is in-range for int64, and then you have something that is out-of-range for int64, it chooses float as a common type. It does not check that the value that was in range for int64 was also in range for uint64, and so the only "safe" thing to do is to use a "larger" type, hence float64.

**Comment by eric-wieser** [comment] 2021-04-29 10:03
We seem to be getting reports of this issue way more often than we used to, even though I think it's been around for a very long time.

**Comment by seberg** [comment] 2021-04-29 14:17
This was probably the case since the dawn of time, since it only relies on what dtype we use as default for integers and not even value-based promotion itself.

@wyx528 as Eric noted, is there some specific reason you ran into this that might be interesting to us?  I agree with it being weird, and I have some thoughts on potentially changing it but it would be interesting to know why we are getting more reports.  (beyond larger numbers being used more commonly due to e.g. more memory).

**Comment by wyx528** [comment] 2021-04-30 05:45
> This was probably the case since the dawn of time, since it only relies on what dtype we use as default for integers and not even value-based promotion itself.
> 
> @wyx528 as Eric noted, is there some specific reason you ran into this that might be interesting to us? I agree with it being weird, and I have some thoughts on potentially changing it but it would be interesting to know why we are getting more reports. (beyond larger numbers being used more commonly due to e.g. more memory).

I show a scenario where this issue will occur.
Recently, the mainstream recommender system usually uses embeddings as the input of the model. The first step of the training procedure is using id to lookup embeddings, just like the code below
```python
input_ids = read_id_from_xxx_data_source() # type(input_ids) == <class 'list'>
```
the `ids` sometimes are genereated by a specific hash algorithm, which may lead to each value in range [2^63, 2^64).
If do `input_ids = np.array(input_ids).astype(np.uint64)` at this time, nothing will happen.

But if we add an operation such as `input_ids.append(0)` to help us to lookup a default embedding vector and do `input_ids = np.array(input_ids).astype(np.uint64)`, it will be equivalent to `input_ids = np.array(input_ids, dtype=np.float64).astype(np.uint64)`  which leading to accuracy error in big integers.

**Comment by seberg** [comment] 2021-04-30 14:22
Ah, a hash using uint64 and storing them as (python/untyped) ints makes sense. It doesn't change the situation much though, I guess.
Ah, finally found the issue I wanted to link this to.  Closing as duplicate of gh-16287, thanks for the report.

**Closed by seberg** 2021-04-30 14:22 UTC
