### ISSUE TITLE
np.linalg.eigh computes incorrect results for matrices of 560x560 or larger on OSX w/Accelerate

### ISSUE THREAD

**Issue by ihaque** [numpy/numpy#6896] opened 2015-12-29 18:54 UTC
Reproduction on OS X 10.10.4 and Numpy 1.10.2: https://gist.github.com/ihaque/882dc3fbc1731f88abb2

`np.linalg.eigh` computes incorrect eigenvalues/eigenvectors for matrices with at least 560 rows/columns, when built against Accelerate in OS X 10.10.4 (maybe other versions?). Everything is fine if matrices are 559 rows/cols or below, and the results are OK if using Numpy built against a different BLAS such as MKL.

`np.linalg.eig` and `scipy.linalg.eigh` are not affected by this problem.

This may be a bug in OS X 10.10.4's Accelerate; @rmcgibbo could not repro on 10.10.3: https://gist.github.com/rmcgibbo/945b6a8cc0a2f9ca21ae

**Comment by rmcgibbo** [comment] 2015-12-29 19:00
Also worth noting, the error is in a small number of eigenpairs that are off by a huge amount (right?), and the numpy binaries are from Continuum/Anaconda.

**Comment by ihaque** [comment] 2015-12-29 19:02
Yes, it's a handful of eigenpairs which end up not even being eigenvectors (ie, they do not satisfy Mv = wv). Happened with both Anaconda as well as the standard wheel from PyPI.

**Comment by rmcgibbo** [comment] 2015-12-29 19:07
I just tried the test case on an OS X 10.11.2 box and can't reproduce there either.

**Comment by argriffing** [comment] 2015-12-29 19:08
> rmat *= rmat.T  # Ensure symmetric

ಠ_ಠ

**Comment by pv** [comment] 2015-12-29 19:11
The result from `rmat *= rmat.T` is undefined. When lhs/rhs of in-place operations overlap in memory, and the result depends on the order of operations, the result is undefined.

**Comment by ihaque** [comment] 2015-12-29 19:18
Changed test code. It doesn't change anything about the bug. (Found it in a different piece of code; this is just a minimal reproduction.)

**Comment by pv** [comment] 2015-12-29 19:25
Lapack / accelerate bug seems then likely. Knowing what lapack version accelerate bundles could be interesting, as it may be a lapack bug --- some dsyev bugs appear in the erratas, although dsyevd is absent.

**Comment by ihaque** [comment] 2015-12-29 19:40
Happy to provide more system information if you can give me a pointer for where to look!

**Comment by ihaque** [comment] 2015-12-29 19:47
`/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Headers/clapack.h` indicates 

> LAPACK v3.2.1 as provided Apple Computer

**Comment by ihaque** [comment] 2015-12-29 20:28
> Lapack / accelerate bug seems then likely, and for those we can't do much

@pv agreed that there's not much that can be done inside numpy if the backing library is broken. What about including a self-test for this problem (more generally, a set of self-tests to detect known bugs in system libraries and alert the user)?

**Comment by rmcgibbo** [comment] 2015-12-29 20:33
On that subject, does `python -c 'import numpy; numpy.test()'` give any relevant errors on your machine?

**Comment by ihaque** [comment] 2015-12-29 20:49
```
Ran 5931 tests in 28.037s

OK (KNOWNFAIL=3, SKIP=7)
```

**Comment by rmcgibbo** [comment] 2015-12-29 21:46
Here's a testcase in c++, printing the largest eigenvalues of one of the upper or lower triangles of a random symmetric matrix using `dsyevd` (used by numpy.linalg.eigh) and `dsyevr` (used by scipy.linalg.eigh) from Accelerate. Do you get a difference, @ihaque?

https://gist.github.com/rmcgibbo/c4217cef7e1ba36f43bc

**Comment by ihaque** [comment] 2015-12-29 21:59
Tried the C++ testcase on a range of values from 50 to 2000, and saw no difference in the results between dsyevd and dsyevr.

**Comment by rmcgibbo** [comment] 2015-12-29 22:02
Stranger and stranger. And that wasn't using the gist revision where I accidentally had lines 187-188 calling the same function, right?

**Comment by ihaque** [comment] 2015-12-29 22:10
Nope, definitely calling the right functions.

**Comment by argriffing** [comment] 2015-12-29 22:11
This probably doesn't matter, but the gist uses UPLO='U' whereas numpy has UPLO='L' by default.

**Comment by ihaque** [comment] 2015-12-29 22:16
Surprisingly, that *does* make a difference. I changed UPLO to 'L' in both init_dsyevd and init_dsyevr, and the eigenvalues start to diverge at N=556:

```
$ ./test 555 20
N = 555
seed = 20
dsyevr Eigenvalues: [13.058153  13.078821  13.245772  13.434283  277.330668  ]
dsyevd Eigenvalues: [13.058153  13.078821  13.245772  13.434283  277.330668  ]

$ ./test 556 20
N = 556
seed = 20
dsyevr Eigenvalues: [13.144169  13.174443  13.276684  13.382298  277.803290  ]
dsyevd Eigenvalues: [13.119638  13.165492  13.262570  13.381886  277.803290  ]
```

Here are the results with UPLO = 'U':

```
$ ./test 555 20
N = 555
seed = 20
dsyevr Eigenvalues: [13.058153  13.078821  13.245772  13.434283  277.330668  ]
dsyevd Eigenvalues: [13.058153  13.078821  13.245772  13.434283  277.330668  ]

[ihaque:~/tmp]
$ ./test 556 20
N = 556
seed = 20
dsyevr Eigenvalues: [13.119638  13.165492  13.262570  13.381886  277.803290  ]
dsyevd Eigenvalues: [13.119638  13.165492  13.262570  13.381886  277.803290  ]
```

Looks like dsyevd is doing the right thing?

**Comment by ihaque** [comment] 2015-12-29 22:19
FWIW I've upgraded to 10.10.5 and it hasn't changed the results.

**Comment by rmcgibbo** [comment] 2015-12-29 22:22
If UPLO actually matters here, one numpy test case would be to take a symmetric matrix and look for any differences between the eigenvalues returned with different values of UPLO.

**Comment by ihaque** [comment] 2015-12-29 22:31
Sure enough, calling `np.linalg.eigh` with UPLO='U' seems to fix the bug:

```
$ python testcase.py | tabulate
               Case    eigh(L) vs eig    eigh(U) vs eig    eigh(L) vs eigh(U)
-----------------------------------------------------------------------------
N=559 (remove head)              True              True                  True
N=559 (remove tail)              True              True                  True
              N=560             False              True                 False
```

**Comment by marscher** [comment] 2016-02-11 11:08
I wonder if this could be related? ContinuumIO/anaconda-issues/issues/658 using MKL libs to provide BLAS

**Comment by rmcgibbo** [comment] 2016-02-11 12:24
No, I don't think this issue (OS XAccelerate specific) is related at all to yours.

**Comment by pv** [comment] 2016-03-02 19:17
@ihaque: did you report this bug to Apple? If not, that could be useful --- esp. including the reproducing c++ program should make it easier for them to fix it.

**Comment by pv** [comment] 2016-03-02 19:19
Also: close? --- the issue has been verified to be in Accelerate.

**Comment by charris** [comment] 2017-08-16 21:29
@matthew-brett Do you know if this is still a problem? What is the status of the discussion about moving away from Accelerate?

**Comment by mattip** [comment] 2019-08-18 17:26
Closing, we no longer use Accelerate

**Closed by mattip** 2019-08-18 17:26 UTC
Labels: component: numpy.linalg
