### ISSUE TITLE
BUG: Strange behaviour of `np.float64` vs `np.float32` during casting

### ISSUE THREAD

**Issue by vovaf709** [numpy/numpy#24654] opened 2023-09-06 17:31 UTC
### Describe the issue:

`np.float32` and `np.float64` behave differently when applied to single value array of 1-s

### Reproduce the code example:

```python
np.float64(np.ones(1))  # 1.0
np.float32(np.ones(1))  # array([1.], dtype=float32)
```

### Runtime information:

1.23.0
3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]

**Comment by WarrenWeckesser** [comment] 2023-09-06 17:35
Thanks for reporting the issue, @vovaf709.  This is a duplicate of https://github.com/numpy/numpy/issues/1362.

**Closed** 2023-09-06 17:35 UTC
Labels: 00 - Bug
