### ISSUE TITLE
repr of numpy arrays and matrices is lossy

### ISSUE THREAD

**Issue by donhatch** [numpy/numpy#26661] opened 2024-06-11 03:22 UTC
### Describe the issue:

When `obj` is (or contains) a `numpy.matrix` or `numpy.array`,
`repr(obj)` (or equivalently `"%r"%obj` or `f"{obj!r}"` etc.)
should print the contained numbers (`numpy.float64`'s) in enough precision to represent them unambiguously, but it does not.

This is unexpected and unnecessarily frustrating when trying to display, examine, and reproduce results
from numpy and scipy routines.

### Reproduce the code example:

```python
>>> import numpy

>>> numpy.array([1/3])
array([0.33333333])
>>> str(numpy.array([1/3]))
'[0.33333333]'
>>> repr(numpy.array([1/3]))
'array([0.33333333])'          # <--- unexpected and disappointing; should be 'array([0.3333333333333333])'
>>> type(numpy.array([1/3]))
<class 'numpy.ndarray'>

>>> numpy.matrix([[1/3]])
matrix([[0.33333333]])
>>> str(numpy.matrix([[1/3]]))
'[[0.33333333]]'
>>> repr(numpy.matrix([[1/3]]))
'matrix([[0.33333333]])'       # <--- unexpected and disappointing; should be 'matrix([[0.3333333333333333]])'
>>> type(numpy.matrix([[1/3]]))
<class 'numpy.matrix'>

# To view the objects at full precision, one must go to more effort,
# e.g. by inspecting the individual elements
# (numpy.float64's), which have non-defective __repr__ methods:

>>> numpy.array([1/3])[0]
0.3333333333333333
>>> str(numpy.array([1/3])[0])
'0.3333333333333333'
>>> repr(numpy.array([1/3])[0])
'0.3333333333333333'                  # <--- as expected
>>> type(numpy.array([1/3])[0])
<class 'numpy.float64'>

>>> numpy.matrix([[1/3]])[0,0]
0.3333333333333333
>>> str(numpy.matrix([[1/3]])[0,0])
'0.3333333333333333'
>>> repr(numpy.matrix([[1/3]])[0,0])
'0.3333333333333333'                  # <--- as expected
>>> type(numpy.matrix([[1/3]])[0,0])
<class 'numpy.float64'>
```

### Python and NumPy Versions:

numpy 1.24.2
python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]

### Context for the issue:

Note that this bug report is specifically about `repr()`, *not* about `str()`;
`str`'s behavior is a matter of taste (personally I dislike when *any* kind of default printing
of numbers is lossy, but some people prefer it that way and won't be convinced otherwise).
But `repr`'s behavior is not: `repr()` should print numbers with enough precision to represent them unambiguously.

Here are some stackoverflow answers that agree:
  https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr#answer-2626364
  https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr#answer-19597196
  https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr#answer-1436721
  https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr#answer-44099267

### Another typical example:

Here is a (simplified) typical example session of how this behavior is frequently frustrating and time-wasting for me.
In this example, the frustration is compounded by the additional unhelpfulness of `scipy.optimize.OptimizeResult.__repr__`
(on which I may file a separate bug report, if it doesn't get resolved with the current one).
```
>>> import math
>>> import scipy
>>> scipy.optimize.root(fun=lambda x:[math.sin(x[0])], x0=[3])
 message: The solution converged.
 success: True
  status: 1
     fun: [ 1.225e-16]
       x: [ 3.142e+00]
    nfev: 6
    fjac: [[-1.000e+00]]
       r: [ 1.000e+00]
     qtf: [ 4.795e-13]
```
Hmm, that's an unhelpful (only 4 significant digits!?) representation of the solution,
which we expect to be `x=[3.141592653589793]` (give or take some low order bits, perhaps).
So, we run the solver again, this time saving the result and then going to some effort to try to inspect it:
```
>>> result = scipy.optimize.root(fun=lambda x:[math.sin(x[0])], x0=[3])
>>> type(result)
<class 'scipy.optimize._optimize.OptimizeResult'>
>>> type(result.x)
<class 'numpy.ndarray'>
>>> result.x
array([3.14159423])
```
Still not very good, so we try harder...
```
>>> str(result.x)
'[3.14159423]'
>>> repr(result.x)
'array([3.14159423])'
```
Still not very good, so we try even harder...
```
>>> type(result.x[0])
<class 'numpy.float64'>
>>> result.x[0]
3.141592653589793
>>> list(result.x)
[3.141592653589793]
```
And finally we can see that the solution is correct (and very accurate).

I hope the behavior of various classes' `__repr__`'s can be fixed so that examining results like this will take far less effort.

**Comment by rkern** [comment] 2024-06-11 03:35
It's a long-standing, well-deliberated design decision. Opinions and preferences differ on the subject, but the consensus for the default has stood for decades, now. I don't think there is a ton of pent-up desire to change now, but I could be wrong.

One can use the [`np.printoptions()`](https://numpy.org/doc/stable/reference/generated/numpy.printoptions.html) context manager to control this in your code to suit your own preferences.

**Comment by donhatch** [comment] 2024-06-11 04:38
Hi @rkern !

I didn't expect this to be controversial.  My understanding is that `repr` has a commonly-understood intent/contract in python (see the references I gave); that is: to represent the object unambiguously, and that numpy's implementation of it simply violates that, making this a bug (rather than an enhancement request).

Furthermore, this behavior makes numpy a bad citizen / broken link in the ecosystem of container __repr__'s which call repr() on the component items expecting those items' __repr__'s to be non-lossy.  That expectation is violated when the component items are of these numpy types, which makes it so that the container's `__repr__` can't honor its contract/intent either.

> It's a long-standing, well-deliberated design decision. Opinions and preferences differ on the subject,

Can you give references to this design decision and the opinion/preference that `repr()` on these objects should be lossy by default?  At the moment, I honestly know of no stated argument for that whatsoever, compelling or otherwise. As I mentioned in the bug report, there is `str()` (and equivalently `print(obj)`, `"%s"%obj`, `f"{obj}"` etc.) for those people who enjoy lossiness; I'm not expecting or asking for any of those to change, and this bug report has nothing to do with those.

> but the consensus for the default has stood for decades, now. I don't think there is a ton of pent-up desire to change now, but I could be wrong.

Consensus among whom?  This long-time user and potential contributor does indeed have a ton of pent-up desire to change it :-)   Fixing this would make numpy and scipy significantly more usable and valuable, for me, and I suspect I'm not the only one who feels that way and who has for quite a long time.   I haven't yet heard any argument for keeping it the way it is; if there isn't one, I'd be happy to contribute a fix.

**Comment by rkern** [comment] 2024-06-11 06:37
FWIW, the actual `__repr__` convention that we break is that we don't use `<>` brackets to indicate that we are not a faithful reproduction. There are tons of objects that would be "bad citizens" if we really expected them all to absolutely be non-lossy. Nonetheless, we persist with the present format as a compromise between showing enough of the structure and data to be mostly be useful at interactive prompts without emitting unusable screenfuls of data by accident. That latter is a hard limit for us. We'll never guarantee round-trippable output, and we never had to, even by the strictest reading of the guidelines. Where we have deviated from those guidelines is not making it `<array [...]>`.

> Can you give references to this design decision and the opinion/preference that repr() on these objects should be lossy by default?

If you dig hard enough, you can probably find the original discussions in the [MATRIX-SIG archives](https://mail.python.org/pipermail/matrix-sig/), probably before 1997 or so. Look for Konrad Hinsen's ArrayPrinter and discussions around that (other keywords: "array2string", "array_repr", etc.). While that started as the pretty-printer for `__str__`, with `precision` being limited from the very beginning, it got adopted as the core of the implementation for `__repr__` in 1997 (adding the `array([...])` bits around it). [Here is Konrad rejecting the idea of strictly maintaining roundtrippability, without objection even from Guido himself.](https://mail.python.org/pipermail/matrix-sig/1997-March/001353.html)

Somewhat later discussions in the `numpy-discussion` mailing list [around the time of the Numeric to numarray transition](https://mail.python.org/archives/list/numpy-discussion@python.org/thread/OFLCBEDMMSAFW3I4O57IXZKG6LWFUM2E/#7PFHYXZBWV6BUZJ3GU6L6AHXNUB32I2M) are more to the point (numarray did preserve roundtrippability at first, and this was found to be largely unusable in practice, and that was with array sizes 20 years ago).

> Consensus among whom?

The numpy development team. This is not a new discussion for us. It pops up once a decade or so. Guaranteeing roundtrippability is definitely off the table, given our past experiences. Changing to `<array ...>` at this very late stage, with all of the documentation and books written out there, is also almost certainly a no-go (and doesn't address your actual problems with the status quo in any case).

**Comment by mattip** [comment] 2024-06-11 06:43
My take is to differentiate between the `repr` of an ndarray and that of a scalar. For scalars: yes, we want the repr to faithfully round-trip. Not so for ndarrays: it is more of a foot-gun than a feature in typical user scenarios. If you so desire you should be able to use the various print options to get a `repr` that can round-trip. In general that is the approach we try to take in NumPy: those who wish to can override the default values to mold NumPy to their desires, while using reasonable defaults. 

There are other places where `repr` does not round-trip. For instance, pandas has an [explicit test](https://github.com/pandas-dev/pandas/blob/629ffeb26e9c385cab2f4f0aacb466be8266ff69/pandas/tests/indexes/multi/test_formats.py#L18) that a `repr` of a MultiIndex does not roundtrip. Pytorch has a `torch.set_printoption` function that mirrors NumPy's function, so it seems others have found NumPy's default behaviour reasonable.

**Comment by rgommers** [comment] 2024-06-11 08:30
> Changing to `<array ...>` at this very late stage, with all of the documentation and books written out there, is also almost certainly a no-go

Agreed. I'm pretty sure that we don't want to make a change here.

**Comment by donhatch** [comment] 2024-06-11 09:40
Regarding the suggested workaround:
> One can use the [np.printoptions()](https://numpy.org/doc/stable/reference/generated/numpy.printoptions.html)context manager to control this in your code to suit your own preferences.


I had to dig a bit to find the relevant incantation.  For reference, it looks like it's the `floatmode='unique'` option:


```
>>> import numpy as np

>>> np.array([1/3])   # typing an expression at the interactive prompt shows its repr()
array([0.33333333])
>>> with np.printoptions(floatmode='unique'): np.array([1/3])
array([0.3333333333333333])

>>> np.array([np.float128(1)/3])
array([0.33333333], dtype=float128)
>>> with np.printoptions(floatmode='unique'): np.array([np.float128(1)/3])
array([0.33333333333333333334], dtype=float128)
```

However, it doesn't seem to work for `scipy.optimize.OptimizeResult`:

```
>>> import math, numpy as np, scipy
>>> with np.printoptions(floatmode='unique'): scipy.optimize.root(fun=lambda x:[math.sin(x[0])], x0=[3])
 message: The solution converged.
 success: True
  status: 1
     fun: [ 1.225e-16]
       x: [ 3.142e+00]
    nfev: 6
    fjac: [[-1.000e+00]]
       r: [ 1.000e+00]
     qtf: [ 4.795e-13]
```  

Any hints on how to make the numbers in that come out in full precision?  (in particular, the solution `x` is `[3.141592653589793]`)

**Comment by mattip** [comment] 2024-06-11 11:23
That is really a question for SciPy, but here ya go:
```
res = scipy.optimize.root(fun=lambda x:[math.sin(x[0])], x0=[3])
print(res.__repr__.__code__)
```

points to [here](https://github.com/scipy/scipy/blob/d5e1e03ac12fb5ad7fa4949e7ffea2137e780b15/scipy/_lib/_util.py#L879), which calls [`_dict_formatter`](https://github.com/scipy/scipy/blob/d5e1e03ac12fb5ad7fa4949e7ffea2137e780b15/scipy/_lib/_util.py#L957) to do the work. That has its own `np.printoptions` context manager. You would have to somehow override that to get different formatting. Probably easier to do your own printing of `res.x`

**Comment by rkern** [comment] 2024-06-11 23:28
I'm going to close this as I am fairly confident that we're not going to make changes to numpy here.

Please do feel free to continue to ask questions here if you need more help identifying how to use the customizations available to you to get the output you want, though other forums might be better if `scipy`'s code is more the root cause, as it is with `OptimizationResult`. I think a request to use `floatmode='unique'` inside of `_dict_formatter` there might get a better reception (though it is still an enhancement request, not a bug fix, even there).

**Closed by rkern** 2024-06-11 23:28 UTC
Labels: 01 - Enhancement
