### ISSUE TITLE
np.append, np.unique and np.array do not to store unichr(0) as unichr

### ISSUE THREAD

**Issue by rafaelvalle** [numpy/numpy#7600] opened 2016-05-03 20:03 UTC
```
In [1]: import numpy as np

In [2]: np.append([], (unichr(0)))
Out[2]:
array([u''],
      dtype='<U32')

In [3]: np.append([], (unichr(1)))
Out[3]:
array([u'\x01'],
      dtype='<U32')

In [4]: np.unique(unichr(0))
Out[4]:
array([u''],
      dtype='<U1')

In [5]: np.unique(unichr(1))
Out[5]:
array([u'\x01'],
      dtype='<U1')

In [6]: np.array([unichr(0)])
Out[6]:
array([u''],
      dtype='<U1')

In [7]: np.array([unichr(1)])
Out[7]:
array([u'\x01'],
      dtype='<U1')

In [8]: np.array([unichr(0), unichr(1)])
Out[8]:
array([u'', u'\x01'],
      dtype='<U1')

In [9]: [unichr(0)]
Out[9]: [u'\x00']
```

**Comment by WarrenWeckesser** [comment] 2021-11-03 17:37
This is a known limitation of NumPy string types: they cannot end with a null character, because there is no way to distinguish a trailing null character from the padding at the end of the string within the fixed width data field.

Although this github issue is much older than https://github.com/numpy/numpy/issues/20118, I'm closing it as a duplicate of the newer issue, as the newer one has a longer description of the issue.  That issue remains open as a documentation issue.

**Closed by WarrenWeckesser** 2021-11-03 17:37 UTC
