### ISSUE TITLE
numpy 2.0.1 build issue on ibm AIX OS 

### ISSUE THREAD

**Issue by Ganeshkumhar1** [numpy/numpy#27531] opened 2024-10-08 15:50 UTC
### Describe the issue:

I am trying to build numpy 2.0.1 on AIX OS with ibm-clang_r compiler. numpy is using meson build in this version and I am hitting issue -

$ python -m build --wheel --no-isolation .
* Getting build dependencies for wheel...
* Building wheel...
+ /tmp/3392379693/python/bin/python /home/user/numpy/2.0.1/numpy-2.0.1/vendored-meson/meson/meson.py setup /home/user/numpy/2.0.1/numpy-2.0.1 /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i/meson-python-native-file.ini
The Meson build system
Version: 1.4.99
Source dir: /home/user/numpy/2.0.1/numpy-2.0.1
Build dir: /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i
Build type: native build
Project name: NumPy
Project version: 2.0.1

../meson.build:1:0: ERROR: Unable to detect linker for compiler `ibm-clang_r -Wl,--version -L/tmp/3392379693/python/lib -I/tmp/3392379693/python/include -I/tmp/3392379693/python/include/openssl`
stdout:
stderr: ld: 0706-012 The -- flag is not recognized.
.ibm-clang: error: linker command failed with exit code 255 (use -v to see invocation)

seems linker ld on AIX does not support --version flag.  tried few suggestion found on internet but could not get past this issue. 

does meson build supported on AIX ? could some one please suggest way out from here?

PS - I was able to build numpy 1.26.4  which had setup.py . ( did not use meson build for this ) simply built whl file using python setup.py bdist_wheel, but with 2.0.1 this is not the case as setup.py is removed from this version and have to build using meson build.

### Reproduce the code example:

```python
$ python -m build --wheel --no-isolation .
* Getting build dependencies for wheel...
* Building wheel...
+ /tmp/3392379693/python/bin/python /home/user/numpy/2.0.1/numpy-2.0.1/vendored-meson/meson/meson.py setup /home/user/numpy/2.0.1/numpy-2.0.1 /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i/meson-python-native-file.ini
The Meson build system
Version: 1.4.99
Source dir: /home/user/numpy/2.0.1/numpy-2.0.1
Build dir: /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-5yatrh9i
Build type: native build
Project name: NumPy
Project version: 2.0.1

../meson.build:1:0: ERROR: Unable to detect linker for compiler `ibm-clang_r -Wl,--version -L/tmp/3392379693/python/lib -I/tmp/3392379693/python/include -I/tmp/3392379693/python/include/openssl`
stdout:
stderr: ld: 0706-012 The -- flag is not recognized.
.ibm-clang: error: linker command failed with exit code 255 (use -v to see invocation)
```

### Python and NumPy Versions:

python version 3.12.6
numpy version 2.0.1

**Comment by mattip** [comment] 2024-10-09 08:56
I wonder where `--version` is coming from. Is it coming from your python build?

`python -m sysconfig | grep version`

**Comment by Ganeshkumhar1** [comment] 2024-10-09 09:47
I think it is coming from meson build 
https://github.com/numpy/meson/blob/31161eef3fc8cf0bf834edc1dd29e490fc6d7713/mesonbuild/linkers/detect.py#L176


bash-5.2$ python -m sysconfig | grep version
Python version: "3.12"
        py_version = "3.12.6"
        py_version_nodot = "312"
        py_version_nodot_plat = ""
        py_version_short = "3.12"

**Comment by mattip** [comment] 2024-10-09 13:21
That executes `$linker_cmd --version` in a shell to determine the version of the linker. It should not add `-Wl,--version` to the actual link command. Do you have any environment variables set that might be relevant?

**Comment by Ganeshkumhar1** [comment] 2024-10-10 04:19
-Wl,--Version  is getting formed to detect the compiler here - https://github.com/numpy/meson/blob/31161eef3fc8cf0bf834edc1dd29e490fc6d7713/mesonbuild/linkers/detect.py#L140

-Wl is coming from gnu.py LINKER_PREFIX -
https://github.com/numpy/meson/blob/31161eef3fc8cf0bf834edc1dd29e490fc6d7713/mesonbuild/compilers/mixins/gnu.py#L360

**Comment by mattip** [comment] 2024-10-10 06:45
Ahh, OK. So this is a meson bug with that compiler. Sorry to be so slow to understand. We vendor meson to add some capabilities, and that code [comes from upstream meson](https://github.com/mesonbuild/meson/blob/739683943aa8caca37343b105a0f363abf772fa9/mesonbuild/linkers/detect.py#L140). I cannot transfer the issue there, could you open [a new one](https://github.com/mesonbuild/meson/issues/new/choose) for this compiler?

**Comment by Ganeshkumhar1** [comment] 2024-10-10 06:56
@mattip raised issue with meson - [issue](https://github.com/mesonbuild/meson/issues/13773)

**Comment by rgommers** [comment] 2024-10-14 07:36
For those who, like me, were confused by what compiler `ibm-clang_r` is, see https://www.ibm.com/docs/en/openxl-c-and-cpp-lop/17.1.1?topic=new-llvm-clang-infrastructure. The IBM open XL compilers version 17 seem to have moved to LLVM.

It's the same status here as for the older `xlc` compiler versions: not supported, only GCC is. To fix that, someone should add support for this compiler to Meson (also pointed out in the issue linked above).

**Comment by mattip** [comment] 2024-10-14 08:44
As mentioned in the upstream issue, this may have been fixed upstream. What is the policy on re-syncing vendored meson with upstream? Do we only re-sync on official releases? The potential fix is already part of 1.6.0rc1.

**Comment by rgommers** [comment] 2024-10-14 09:12
> What is the policy on re-syncing vendored meson with upstream? Do we only re-sync on official releases? The potential fix is already part of 1.6.0rc1.

We can sync whenever/whatever we want. It's very hard currently to just sync though, since the reason we maintain a fork is large features we need that aren't in Meson's master branch, and they have a lot of merge conflicts. If the fix in question can be identified, I'd be fine with backporting it separately though, in order to close this issue.

**Comment by rgommers** [comment] 2024-10-14 09:14
Ah, and that fix was just identified an hour ago - it seems backportable, so let's do that. I am just about to backport another fix, so I can try doing both of those today - helps to just have to bump the vendored meson once.

**Comment by mattip** [comment] 2024-10-14 09:16
Thanks!

**Comment by rgommers** [comment] 2024-10-14 16:38
Slightly annoying - the upstream fix is imperfect, it somehow triggers stdout output `Could not locate executable icc` when a search for the `icc` linker fails in a `numpy.distutils` test. That shouldn't be happening anyway, so I think there's something wrong with the patch. It only fails with Conda on x86-64, so I can't reproduce it locally. I suspect it searches for linkers by name, and the conda linker has an unusual name (e.g., `arm64-apple-darwin20.0.0-ld`).

```
 E           AssertionError: Modules that are not really public but looked public and can not be imported: ['numpy.distutils.command.develop', 'numpy.distutils.command.egg_info']
check_importable = <function test_api_importable.<locals>.check_importable at 0x122b26b60>
module_name = 'numpy.distutils.unixccompiler'
module_names = ['numpy.distutils.command.develop', 'numpy.distutils.command.egg_info']
w          = []
numpy/tests/test_public_api.py:438: AssertionError
----------------------------- Captured stdout call -----------------------------
WARN: Could not locate executable icc
WARN: Could not locate executable ecc
```

Trying to see if we can get away with just silencing the warnings.

**Comment by rgommers** [comment] 2024-10-14 18:27
Okay, found the problem - actually the patch is fine, and it uncovered a problem in `numpy.distutils`. Fix is on its way.

**Closed** 2024-10-15 14:25 UTC
Labels: component: build, 32 - Installation

**Comment by Ganeshkumhar1** [comment] 2024-10-18 05:11
@rgommers How do I pull the required changes to build numpy 2.0.1 ?

**Comment by rgommers** [comment] 2024-10-18 07:49
The change has been backported to the `maintenance/2.1.x` branch, but not `maintenance/2.0.x`. So if you want to build 2.0.1 plus this fix, you can use `git cherry-pick` to put the needed patches (see gh-27562) on top of 2.0.1.

**Comment by Ganeshkumhar1** [comment] 2024-10-30 10:56
I am sorry for opening it again. I am still facing issue in building the numpy 2.0.1 AIX. 

steps I did -

git clone https://github.com/numpy/numpy.git
cd numpy
git checkout v2.0.1
git submodule update --init –recursive

cd vendored-meson/meson/
git checkout 0d93515fb826440d19707eee47fd92655fe2f166
cd ../../



export PKG_CONFIG_PATH=[OpenBLAS install prefix]/lib/pkgconfig
export CC="[Open XL install prefix]/opt/IBM/openxlC/17.1.2/bin/ibm-clang_r"
export CXX="[Open XL install prefix]/opt/IBM/openxlC/17.1.2/bin/ibm-clang++_r"
export CFLAGS=-m64
export CXXFLAGS=-m64


tried using meson -

bash-5.2$ meson setup builddir . --buildtype=release
The Meson build system
Version: 1.6.0
Source dir: /home/user/numpy
Build dir: /home/user/numpy/builddir
Build type: native build
Project name: NumPy
Project version: 2.0.1
C compiler for the host machine: ibm-clang_r (clang 17.1.2 "IBM Open XL C/C++ for AIX 17.1.2 (5725-C72, 5765-J18), version 17.1.2.12, clang version 17.0.6 (build 038d167 038d1671f9374f6559080fed073ed8837f9b34ff)")
C linker for the host machine: ibm-clang_r ld.aix 7.2.5
C++ compiler for the host machine: ibm-clang++_r (clang 17.1.2 "IBM Open XL C/C++ for AIX 17.1.2 (5725-C72, 5765-J18), version 17.1.2.12, clang version 17.0.6 (build 038d167 038d1671f9374f6559080fed073ed8837f9b34ff)")
C++ linker for the host machine: ibm-clang++_r ld.aix 7.2.5
Cython compiler for the host machine: cython (cython 3.0.10)
Host machine cpu family: ppc64
Host machine cpu: powerpc
Program python3 found: YES (/home/user/python/bin/python3.12.bin)
Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
Run-time dependency python found: YES 3.12
Has header "Python.h" with dependency python-3.12: YES
Compiler for C supports arguments -fno-strict-aliasing: YES
Compiler for C supports arguments -ftrapping-math: YES

meson_cpu/x86/meson.build:2:15: ERROR: Module "features" does not exist

A full log can be found at /home/user/numpy/builddir/meson-logs/meson-log.txt

**Comment by mcepl** [comment] 2024-11-22 23:42
I don’t think https://github.com/numpy/numpy/pull/27562 is the solution. I have got the same here while packaging the latest version of numpy (perhaps with the newest `setuptools`?) for openSUSE/Factory:

```
[  694s] =================================== FAILURES ===================================
[  694s] _____________________________ test_api_importable ______________________________
[  694s] [gw7] linux -- Python 3.10.15 /usr/bin/python3.10
[  694s] 
[  694s]     def test_api_importable():
[  694s]         """
[  694s]         Check that all submodules listed higher up in this file can be imported
[  694s]     
[  694s]         Note that if a PRIVATE_BUT_PRESENT_MODULES entry goes missing, it may
[  694s]         simply need to be removed from the list (deprecation may or may not be
[  694s]         needed - apply common sense).
[  694s]         """
[  694s]         def check_importable(module_name):
[  694s]             try:
[  694s]                 importlib.import_module(module_name)
[  694s]             except (ImportError, AttributeError):
[  694s]                 return False
[  694s]     
[  694s]             return True
[  694s]     
[  694s]         module_names = []
[  694s]         for module_name in PUBLIC_MODULES:
[  694s]             if not check_importable(module_name):
[  694s]                 module_names.append(module_name)
[  694s]     
[  694s]         if module_names:
[  694s]             raise AssertionError("Modules in the public API that cannot be "
[  694s]                                  "imported: {}".format(module_names))
[  694s]     
[  694s]         for module_name in PUBLIC_ALIASED_MODULES:
[  694s]             try:
[  694s]                 eval(module_name)
[  694s]             except AttributeError:
[  694s]                 module_names.append(module_name)
[  694s]     
[  694s]         if module_names:
[  694s]             raise AssertionError("Modules in the public API that were not "
[  694s]                                  "found: {}".format(module_names))
[  694s]     
[  694s]         with warnings.catch_warnings(record=True) as w:
[  694s]             warnings.filterwarnings('always', category=DeprecationWarning)
[  694s]             warnings.filterwarnings('always', category=ImportWarning)
[  694s]             for module_name in PRIVATE_BUT_PRESENT_MODULES:
[  694s]                 if not check_importable(module_name):
[  694s]                     module_names.append(module_name)
[  694s]     
[  694s]         if module_names:
[  694s] >           raise AssertionError("Modules that are not really public but looked "
[  694s]                                  "public and can not be imported: "
[  694s]                                  "{}".format(module_names))
[  694s] E           AssertionError: Modules that are not really public but looked public and can not be imported: ['numpy.distutils.msvccompiler']
[  694s] 
[  694s] check_importable = <function test_api_importable.<locals>.check_importable at 0x7f2efdce7b50>
[  694s] module_name = 'numpy.distutils.unixccompiler'
[  694s] module_names = ['numpy.distutils.msvccompiler']
[  694s] w          = [<warnings.WarningMessage object at 0x7f2efcdc51b0>, <warnings.WarningMessage object at 0x7f2efcc208b0>, <warnings.War...x7f2efcc217e0>, <warnings.WarningMessage object at 0x7f2efcc21960>, <warnings.WarningMessage object at 0x7f2f075b0220>]
[  694s] 
[  694s] ../../../BUILDROOT/python-numpy-2.1.3-0.x86_64/usr/lib64/python3.10/site-packages/numpy/tests/test_public_api.py:436: AssertionError
[  694s] ----------------------------- Captured stdout call -----------------------------
[  694s] WARN: Could not locate executable icc
[  694s] WARN: Could not locate executable ecc
[  694s] =========================== short test summary info ============================
[  694s] FAILED tests/test_public_api.py::test_api_importable - AssertionError: Module...
```

[Complete build log](https://github.com/user-attachments/files/17877513/_log.txt) with the list of all packages used and steps taken to reproduce.

**Comment by charris** [comment] 2024-11-23 00:14
@mcepl 

I'm pretty sure this is a setuptools version problem. We fixed it in main by moving the test to python 3.12, which skips the test because 3.12 doesn't have distutils. Before that, updating to `actions/cache` 4.1.1 also fixed some problems. If you need a quick fix, I suggest skipping the offending test, the failure is probably unrelated to whether NumPy works correctly.

**Comment by charris** [comment] 2024-11-23 00:20
@mcepl 

I note that you are using setuptools 75.6.0-1.1, we had it pinned at 65.5.1.

**Comment by mcepl** [comment] 2024-11-23 09:27
> @mcepl
> 
> If you need a quick fix, I suggest skipping the offending test, the failure is probably unrelated to whether NumPy works correctly.

That’s obviously exactly what I did.

> I note that you are using setuptools 75.6.0-1.1, we had it pinned at 65.5.1.

Yes, I feel bad, that the developer of the most important package in the Python toolset has no clue what the stable API, but have you noticed that 65.5.1 is from Nov 4, 2022?

**Comment by rgommers** [comment] 2024-11-23 10:33
> but have you noticed that 65.5.1 is from Nov 4, 2022?

We know. For context: `numpy.distutils` has been deprecated for a long time, and we no longer want to keep up with regular breakage in `setuptools`, it's just too much of time sink for us. We'll patch critical issues that prevent the few people that still rely on `numpy.distutils` from using it, but that's about it.
