### ISSUE TITLE
timedelta64 doesn't accept int64 as input

### ISSUE THREAD

**Issue by naught101** [numpy/numpy#5664] opened 2015-03-11 05:45 UTC
Seems to me that timedelta should be able to accept numpy integers as input, but it can't:

```
>>> import sys, numpy
>>> sys.version
'3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:03:53) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
>>> numpy.version.version
'1.9.2'
>>> np.timedelta64(4, 'm')
numpy.timedelta64(4,'m')
>>> np.timedelta64(np.int64(4), 'm')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-432735e2a44e> in <module>()
----> 1 np.timedelta64(np.int64(4), 'm')

ValueError: Could not convert object to NumPy timedelta
```

This is numpy installed via conda on kubuntu 14.04

Not sure if this is related to https://github.com/numpy/numpy/issues/2543

**Comment by ahaldane** [comment] 2017-12-02 04:29
Seems to be fixed now. Close?

**Comment by eric-wieser** [comment] 2017-12-02 04:38
There's a newer version of this issue somewhere, but I don't remember whether we fixed it

**Comment by eric-wieser** [comment] 2017-12-02 04:39
#10091?

**Comment by ahaldane** [comment] 2017-12-02 04:49
Hmm I didn't see that one, I didn't realize it was being worked on.

Curiously on my system the examples in this issue and that one work fine for me, even though that PR isn't merged.

**Comment by eric-wieser** [comment] 2017-12-02 06:40
I'll bet that on your system, `issubclass(np.int64, int)` returns true

**Comment by eric-wieser** [comment] 2017-12-02 06:53
Duplicate of #10004. I know this came first, but there's more useful discussion there.

**Closed by eric-wieser** 2017-12-02 06:53 UTC
