### ISSUE TITLE
[missing feature]  'numpy.float32' object has no attribute 'is_integer' ?

### ISSUE THREAD

**Issue by mingwugmail** [numpy/numpy#17794] opened 2020-11-17 21:41 UTC
I also run into this error:

https://github.com/sfu-db/dataprep/issues/231

```
/miniconda3/lib/python3.6/site-packages/pandas/core/common.py", line 164, in cast_scalar_indexer
    if lib.is_float(val) and val.is_integer():
AttributeError: 'numpy.float32' object has no attribute 'is_integer'
```

with dtype=numpy.double, the code runs fine; shouldn't `is_integer` be defined for all float types?

version:
numpy                          1.17.2
pandas                         1.1.3

Linux  4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mingwugmail** [comment] 2020-11-17 21:43
Or is this is also a pandas bug?

**Comment by eric-wieser** [comment] 2020-11-17 21:45
We have an issue filed for this somewhere, this is more a missing feature than a bug

**Comment by mingwugmail** [comment] 2020-11-17 21:50
@eric-wieser  does the latest version  numpy 1.19.4 have the fix?

**Comment by mingwugmail** [comment] 2020-11-17 21:56
Looks like it's not fixed yet:

```
$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a=np.array([1,2,3], dtype=np.float32)
>>> a[0].is_integer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.float32' object has no attribute 'is_integer'

>>> np.__version__
'1.19.4'
```

**Comment by eric-wieser** [comment] 2020-11-17 21:57
I'm going to close this as a duplicate of the other issue - but thanks for the report, it's helpful to know when people notice things are missing.

**Closed by eric-wieser** 2020-11-17 21:57 UTC
