### ISSUE TITLE
f2py -c --help-fcompiler hangs

### ISSUE THREAD

**Issue by connorourke** [numpy/numpy#12884] opened 2019-01-30 17:00 UTC
Running 

`f2py -c --help-compiler`

hangs indefinitely on Ubuntu 18.04 as a result of `shlex.split()` being called on `None`.

This occurs at line 471 in `fcompiler/__init__.py` when `show_fcompilers()` calls `customize()` and `self.command_vars.compiler_f77 = f77`, `self.command_vars.compiler_f90 = None`

### Reproducing code example:
```python
import shlex
import os

shlex.split(None,posix=(os.name=='posix'))
```
### Numpy/Python version information:

**Python Version**: Python 3.6.7
**Numpy version**: 1.16.0 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by mattip** [comment] 2019-01-30 17:04
Duplicate of #12823, fixed in #12824 and backported to 1.16.1 in #12843.

**Closed** 2019-01-30 17:11 UTC
