### ISSUE TITLE
Inconsistent casting behavior in array-scalar vs array-array multiplication

### ISSUE THREAD

**Issue by idfah** [numpy/numpy#5297] opened 2014-11-19 21:06 UTC
Say we have an array of single precision floats.

``` python
>>> a = np.array((1,2,3), dtype=np.float32)
>>> a.dtype
dtype('float32')
```

If we multiply this array with a 64 bit int scalar, the result still consists of single precision floats.

``` python
>>> (a*1L).dtype
dtype('float32')
```

This is also true of we multiply with a 0-d numpy array containing a 64 bit int.

``` python
>>> (a*np.array(1L)).dtype
dtype('float32')
```

However, if we multiply with an 1-d (or n-d) array of 64 bit ints, we now get double precision floats.

``` python
>>> (a*np.array((1L,))).dtype
dtype('float64')
>>> (a*np.ones((1,))).dtype
dtype('float64')
>>> (a*np.ones(a.shape)).dtype
dtype('float64')
```

I can see the argument for either behavior (since the int has 64 bits perhaps the result should too) but it seems like it should be consistent either way.

I stumbled across this when I discovered that `np.meshgrid` changes the dtype of single precision float arrays (perhaps a separate issue?) because it multiplies by an array of `np.ones` unless `copy=False`.

``` python
>>> ax, ay = np.meshgrid(a,a)
>>> ax.dtype
dtype('float64')

>>> ax, ay = np.meshgrid(a,a, copy=False)
>>> ax.dtype
dtype('float32')
```

**Comment by rgommers** [comment] 2016-11-06 04:57
``meshgrid`` issue fixed in gh-5302, and the rest is not a bug. so closing.

**Closed by rgommers** 2016-11-06 04:57 UTC
