### ISSUE TITLE
 Cannot load module _multiarray_umath.so on AIX6.1 by gcc

### ISSUE THREAD

**Issue by absoult-dev** [numpy/numpy#15994] opened 2020-04-16 10:26 UTC
```
export 'CC=gcc -lgcc'
export LDSHARED="/opt/freeware/lib64/python3.7/config-3.7m/ld_so_aix gcc -bI:/opt/freeware/lib64/python3.7/config-3.7m/python.exp"
export CFLAGS="-pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts"

# oslevel -s
6100-09-12-1837
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/freeware/libexec/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/lto-wrapper
Target: powerpc-ibm-aix6.1.0.0
Configured with: ../gcc-6.3.0/configure --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --with-local-prefix=/opt/freeware --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran,objc,obj-c++ --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --with-cloog=no --with-ppl=no --disable-libstdcxx-pch --enable-__cxa_atexit --host=powerpc-ibm-aix6.1.0.0
Thread model: aix
gcc version 6.3.0 (GCC) 
# python -V
Python 3.7.4
# pip list
Package    Version
---------- -------
Cython     0.29.16
numpy      1.16.0 
pip        19.1   
setuptools 40.8.0 


# python3
Python 3.7.4 (default, Nov  7 2019, 21:34:34) 
[GCC 6.3.0] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/overrides.py", line 9, in <module>
    from numpy.core._multiarray_umath import add_docstring, ndarray
ImportError:    0509-022 Cannot load module /opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so.
        0509-026 System error: Cannot run a file that does not have a valid format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was:     0509-022 Cannot load module /opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so.
        0509-026 System error: Cannot run a file that does not have a valid format.
```

**Comment by mattip** [comment] 2020-04-16 11:40
Duplicate of gh-15976. What does `file /opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so` say? That `so` name looks wrong. What does your python report for `python -c"import imp; print(imp.get_suffixes())"`? Where did you get this numpy from?

**Comment by absoult-dev** [comment] 2020-04-16 12:37
> Duplicate of [gh-15976](https://github.com/numpy/numpy/issues/15976). What does `file /opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so` say? That `so` name looks wrong. What does your python report for `python -c"import imp; print(imp.get_suffixes())"`? Where did you get this numpy from?

I get numpy from：https://pypi.org/project/numpy/

#  python -c "import imp; print(imp.get_suffixes())"
-c:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
[('.cpython-37m.so', 'rb', 3), ('.abi3.so', 'rb', 3), ('.so', 'rb', 3), ('.py', 'r', 1), ('.pyc', 'rb', 2)]
#

**Comment by mattip** [comment] 2020-04-16 13:15
Using `pip install` on AIX should have compiled from source since there are no AIX compatible binary wheels. If you compiled from source, you should not be getting an invalid file from your compiler. What does `file /opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so` show?

**Comment by absoult-dev** [comment] 2020-04-16 13:21
> Using `pip install` on AIX should have compiled from source since there are no AIX compatible binary wheels. If you compiled from source, you should not be getting an invalid file from your compiler. What does `file /opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so` show?

When I cat _multiarray_umath.so,it returned out messy code

**Comment by mattip** [comment] 2020-04-16 14:08
Don't use `cat`, use `file`. `man file` shows:
```
NAME
     file — determine file type

SYNOPSIS
     file [-bcdEhiklLNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type] [-e testname] [-F separator] [-f namefile]
          [-m magicfiles] [-P name=value] file ...
     file -C [-m magicfiles]
     file [--help]

DESCRIPTION
     This manual page documents version 5.32 of the file command.

     file tests each argument in an attempt to classify it.  There are three sets of tests,
     performed in this order: filesystem tests, magic tests, and language tests.  The first
     test that succeeds causes the file type to be printed.
```

**Comment by absoult-dev** [comment] 2020-04-16 14:17
> Don't use `cat`, use `file`. `man file` shows:
> 
> ```
> NAME
>      file — determine file type
> 
> SYNOPSIS
>      file [-bcdEhiklLNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type] [-e testname] [-F separator] [-f namefile]
>           [-m magicfiles] [-P name=value] file ...
>      file -C [-m magicfiles]
>      file [--help]
> 
> DESCRIPTION
>      This manual page documents version 5.32 of the file command.
> 
>      file tests each argument in an attempt to classify it.  There are three sets of tests,
>      performed in this order: filesystem tests, magic tests, and language tests.  The first
>      test that succeeds causes the file type to be printed.
> ```

# file /opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so
/opt/freeware/lib64/python3.7/site-packages/numpy-1.16.0-py3.7-aix-6.1.egg/numpy/core/_multiarray_umath.so: executable (RISC System/6000) or object module not stripped

**Comment by absoult-dev** [comment] 2020-04-16 15:10
It seems the gcc compiler use 32bit as the default？
Should i run：export 'CC=gcc -maix64'？

**Comment by absoult-dev** [comment] 2020-04-16 15:22
I had found this：
# python setup.py build --help-fcompiler
Running from numpy source directory.
Gnu95FCompiler instance properties:
  archiver        = ['/usr/bin/gfortran', '-cr']
  compile_switch  = '-c'
  compiler_f77    = ['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-
                    fno-second-underscore', '-maix64', '-fPIC', '-O3', '-
                    funroll-loops']
  compiler_f90    = ['/usr/bin/gfortran', '-Wall', '-g', '-fno-second-
                    underscore', '-maix64', '-fPIC', '-O3', '-funroll-loops']
  compiler_fix    = ['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-
                    fno-second-underscore', '-maix64', '-Wall', '-g', '-fno-
                    second-underscore', '-maix64', '-fPIC', '-O3', '-funroll-
                    loops']
  libraries       = ['gfortran']
  library_dirs    = ['/opt/freeware/lib/gcc/powerpc-ibm-
                    aix6.1.0.0/6.3.0/ppc64']
  linker_exe      = ['/usr/bin/gfortran', '-Wall', '-maix64', '-Wall', '-
                    maix64']
  linker_so       = ['/opt/freeware/lib/python3.7/config/ld_so_aix',
                    '/usr/bin/gfortran', '-Wall', '-g', '-lpthread', '-
                    maix64', '-
                    bI:/opt/freeware/lib/python3.7/config/python.exp', '-
                    Wall', '-g', '-lpthread', '-maix64', '-shared']
  object_switch   = '-o '
  ranlib          = ['/usr/bin/gfortran']
  version         = LooseVersion ('6.3.0')
  version_cmd     = ['/usr/bin/gfortran', '-dumpversion']

How can i change the value of libraries and library_dirs

**Comment by mattip** [comment] 2020-04-16 15:32
Sorry, these are really specific build questions for a platform we have no access to. Please ask your IT group or look around stackoverflow/google. This issue tracker is for issues dealing with issues in NumPy itself.

**Comment by absoult-dev** [comment] 2020-04-16 15:40
> Sorry, these are really specific build questions for a platform we have no access to. Please ask your IT group or look around stackoverflow/google. This issue tracker is for issues dealing with issues in NumPy itself.

This file‘s ’not to be built on 64bit enviroment is the reason？

**Comment by absoult-dev** [comment] 2020-04-16 16:49
I had solved the problem by doing this：
export 'CC=gcc -lgcc -maix64'
export LDSHARED="/opt/freeware/lib64/python3.7/config-3.7m/ld_so_aix gcc -lgcc -maix64 -bI:/opt/freeware/lib64/python3.7/config-3.7m/python.exp"
export CFLAGS="-pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -fno-tree-dominator-opts"

Thanks all

**Closed** 2020-04-20 13:59 UTC
