### ISSUE TITLE
BUG: Python 3.11.4 and cimport numpy

### ISSUE THREAD

**Issue by sametcopur** [numpy/numpy#24156] opened 2023-07-10 15:15 UTC
### Describe the issue:

in python 3.11.4, i cannot cimport numpy but i can import numpy in .pyx, also in previous version of python both works. is it about python version or is it bug?

### Reproduce the code example:

```python
c_aux.pyx 
cimport numpy as np

main.ipynb
import pyximport; pyximport.install(); import c_aux
```

### Error message:

```shell
ImportError: Building module c_aux failed: ["distutils.errors.CompileError: command 'C:\\\\Program Files\\\\Microsoft Visual Studio\\\\2022\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.36.32532\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit code 2\n"]
```

### Runtime information:

1.25.1
3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
[{'numpy_version': '1.25.1',
  'python': '3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='SAMETCAPUR', release='10', version='10.0.19044', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\sametc\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.23-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23'}]

**Comment by mattip** [comment] 2023-07-11 07:32
Cannot reproduce. What is the complete traceback, the compiler error is missing? What version of cython are you using?

**Comment by seberg** [comment] 2023-07-25 07:14
Closing for now, since there is nothing to be done without more details, even if it is a Numpy issue.

**Closed by seberg** 2023-07-25 07:14 UTC
Labels: 00 - Bug
