### ISSUE TITLE
Masked array remains dtype=='S1' or dtype=='S2' when invoking .filled()

### ISSUE THREAD

**Issue by pafoster** [numpy/numpy#8387] opened 2016-12-16 20:33 UTC
Observed using numpy-1.11.2: If I create a masked array

X = np.ma.array(('a','b','c'), mask=(0,1,0))

then invoking X.filled() yields:

array(['a', 'N', 'c'],  dtype='|S1')

Yet the documentation at https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.default_fill_value.html#numpy.ma.default_fill_value suggests that the string filling value should be ‘N/A’. The behaviour is analogous if I create a masked array

Y = np.ma.array(('aa','bb','cc'), mask=(0,1,0))

Then invoking Y.filled() yields:

array(['aa', 'N/', 'cc'], dtype='|S2')

This behaviour is especially problematic when the non-masked entries in the array already include the respective strings 'N', 'N/'.

**Comment by charris** [comment] 2016-12-16 22:48
Yeah, the fill value for strings is screwed up 8)

**Comment by pafoster** [comment] 2016-12-16 23:01
Ah, I see now #3295 already reports this behaviour.

**Comment by mhvk** [comment] 2017-05-04 19:55
I'll close this since it is indeed a duplicate of #3925

**Closed by mhvk** 2017-05-04 19:55 UTC
Labels: 50 - Duplicate, component: numpy.ma

**Comment by eric-wieser** [comment] 2017-05-04 21:34
Wrong issue number, @mhvk?

**Comment by mhvk** [comment] 2017-05-04 21:40
Thanks, corrected!
