### ISSUE TITLE
BUG: np.any vs any

### ISSUE THREAD

**Issue by JavierEscobarOrtiz** [numpy/numpy#25405] opened 2023-12-17 09:35 UTC
### Describe the issue:

I find a different behavior from the built-in function `any` and `np.any`. I don't know if this is expected. It seems that the if statement evaluates the output of `np.any()` as `True` or exits in the second if.

### Reproduce the code example:

```python
import numpy as np

array = np.array([1, 2, 3, 4, 5])

if any(element is None for element in array):
    print('This print does not appear')

if np.any(element is None for element in array):
    print('This print appears')

if np.any(element is None for element in array) == True:
    print('This print does not appear')
```

### Python and NumPy Versions:

numpy=1.26.2
python= 3.11.5

**Comment by ngoldbaum** [comment] 2023-12-17 19:04
What's happening is that `element is None for element in array` is a generator expression (i.e. it is lazily generated and does not initialize a result until you iterate over it) and numpy doesn't automatically exhaust a generator expression to turn it an array. For example:

```
In [9]: np.array(element is None for element in array)
Out[9]: array(<generator object <genexpr> at 0x1074ace10>, dtype=object)
```

So, you're more or less saying `np.any(a_one_element_object_array_the_contains_a_generator)`, which is True, since generators are truthy.

If you want to create an array form an iterator, you want `np.fromiter()`.

One could argue whether or not doing this with a generator is useful, but to change that behavior we'd need to consider whether users are relying on the existing behavior.

Closing because this is working as intended.

**Closed** 2023-12-17 19:16 UTC
Labels: 00 - Bug

**Comment by JavierEscobarOrtiz** [comment] 2023-12-17 19:57
Thanks for the answer @ngoldbaum

**Comment by seberg** [comment] 2023-12-18 08:35
There is actually an issue somewhere about considering to reject iterators being put into an array like this in general.  I ran into some issue trying it, I think some downstream libraries effectively abused these code paths and would need fixing also...
