### ISSUE TITLE
BUG: error in np.histogram with 32-bit values

### ISSUE THREAD

**Issue by astrofrog** [numpy/numpy#11586] opened 2018-07-18 11:11 UTC
I'm having issues using np.histogram with certain arrays of 32-bit values. For example:

```python
In [17]: np.histogram(np.array([-96.84163 , -14.239843], dtype=np.float32), range=(-96.84162582956903, 0.0), bins=10)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-35074303c1c0> in <module>()
----> 1 np.histogram(np.array([-96.84163 , -14.239843], dtype=np.float32), range=(-96.84162582956903, 0.0), bins=10)

~/miniconda3/envs/dev/lib/python3.6/site-packages/numpy/lib/function_base.py in histogram(***failed resolving arguments***)
    810             else:
    811                 n += np.bincount(indices, weights=tmp_w,
--> 812                                  minlength=n_equal_bins).astype(ntype)
    813     else:
    814         # Compute via cumulative histogram

ValueError: 'list' argument must have no negative elements
```

This is with Numpy 1.14.3

**Comment by michaelaye** [comment] 2018-08-17 21:14
yeah, not fixed in 1.15.0

**Comment by eric-wieser** [comment] 2018-08-18 04:58
The int16 case repros on `master` on my machine, sadly.

**Comment by michaelaye** [comment] 2018-08-18 05:37
I had that warning as well, it’s in my feedback above. Or are you saying you don’t get the ValueError?

**Comment by eric-wieser** [comment] 2018-08-18 07:53
Sorry, I missed that in your output.

Looks like uint16 worked in 1.13.3, so I assume it worked in 1.14 too (and this is therefore a regression)

Can you open a new issue about the uint16 case?

**Comment by eric-wieser** [comment] 2018-08-19 07:28
@michaelaye: The `int16` problem was fixed in #11781 and will make it to 1.15.1

I'm afraid that I'm still not able to reproduce the float32 issue you describe. Can you give the traceback that 1.15.0 gives for you?

**Comment by michaelaye** [comment] 2018-08-21 23:28
Sorry if I gave the impression that I had this case with floating points. I only had it with int16. I didn't realize beforehand it was type-related.

**Comment by eric-wieser** [comment] 2018-08-22 00:10
So to be clear, the float32 problem no longer exists on numpy 1.15.0? If so, it sounds like this can be closed,.

**Comment by charris** [comment] 2018-08-22 00:13
No, 1.15.1, which was released today. Be good if you would check.

**Comment by charris** [comment] 2018-08-22 18:00
@michaelaye Thanks for the update, closing this.

**Closed by charris** 2018-08-22 18:00 UTC
Labels: 00 - Bug
