### ISSUE TITLE
[numpy-1.19.3 , py3.8.5, Linux Ubuntu Env] Hstack method -> Unable to allocate memory , 180 KiB

### ISSUE THREAD

**Issue by MarkBel** [numpy/numpy#17684] opened 2020-10-30 15:16 UTC
The error has occured when using hstack, with array with shape (700, 33) and data type float64. The problem is not regarding the system as $ echo 1 > /proc/sys/vm/overcommit_memory
This will enable "always overcommit" mode, and you'll find that indeed the system will allow you to make the allocation no matter how large it is (within 64-bit memory addressing at least). The usage just required 180 KiB of space, so it can not be the root cause of the problem.

### Reproducing code example:

```python
import numpy as np
np.hstack(columns_from_the_dataframe)
```

### Error message:

```
Traceback (most recent call last):
  File "<__array_function__ internals>", line 5, in hstack
  File "/usr/local/lib/python3.8/dist-packages/numnumpy-1.19.3py/core/shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
MemoryError: Unable to allocate 180. KiB for an array with shape (700, 33) and data type float64
```
### NumPy/Python version information:

numpy-1.19.3

**Comment by eric-wieser** [comment] 2020-10-30 15:29
Here's the code that emits that error:

https://github.com/numpy/numpy/blob/08f9eeb4a39761131af059b944225874835e94b0/numpy/core/src/multiarray/ctors.c#L809-L834

There are only two ways this can fail:
* `malloc` returns null
* Our cache is somehow corrupt

**Comment by seberg** [comment] 2020-10-30 15:49
This is a bit scary.  Did this issue appear with 1.19.3 and not with 1.19.2?

Our cache could corrupt, but it seems to me the main way that might happen is if we free an array without holding the GIL by accident?  It would be interesting if you could provide a more complete example? I am guessing here that the `np.hstack` call is not enough to produce this failure (e.g. say you are loading the dataframe using `pickle`)?

**Comment by charris** [comment] 2020-10-30 16:12
> Did this issue appear with 1.19.3 and not with 1.19.2?

I'd really like to know that also, as 1.19.4 is in preparation. Is the issue repeatable?

**Comment by MarkBel** [comment] 2020-10-30 16:17
@charris @seberg No issue as for 1.19.2, np.hstack works fine and smooth.

**Comment by seberg** [comment] 2020-10-30 16:31
Uff, there are very few changes aside from the OpenBLAS one so it is a bit hard to imagine what might be going on, unless it has to do with the wheel rather than the changes? Or it is some existing race condition that just didn't show up before?

Is there any chance of being able to give a full reproducing example?  Running it in `gdb` may also be nice, but I admit I do not have much hope that it will show anything useful.

**Comment by charris** [comment] 2020-10-30 16:43
This leaves me in a quandary :( I suppose the safe thing to do would be to put out a 1.19.4rc1.

**Comment by charris** [comment] 2020-10-30 16:47
> unless it has to do with the wheel rather than the changes

Scary. We believe we are using newer docker images for the manylinux releases.

**Comment by charris** [comment] 2020-10-30 18:48
@MarkBel Could you try installing 1.19.4 from the staging repo?
```
python -mpip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy
```
I'd like to get 1.19.4 tested before uploading to PyPI.

**Comment by MarkBel** [comment] 2020-11-01 15:18
> @MarkBel Could you try installing 1.19.4 from the staging repo?
> 
> ```
> python -mpip install -i https://pypi.anaconda.org/multibuild-wheels-staging/simple numpy
> ```
> 
> I'd like to get 1.19.4 tested before uploading to PyPI.

I will do my best tmr and give you the feedback back.

**Comment by charris** [comment] 2020-11-01 16:17
Thanks!

**Comment by MarkBel** [comment] 2020-11-02 07:53
@charris Coming back with the positive feedback, I have just upgraded numpy to 1.19.4 from the staging repo as you suggested and no issue has occurred regarding memory allocation, here we go!

**Comment by charris** [comment] 2020-11-02 15:22
@MarkBel Thanks.

**Comment by AnkitSnh2** [comment] 2020-12-17 00:22
I still see the issue by calling 
S = np.cumsum(image)

logs:
Traceback (most recent call last):
  File "main.py", line 158, in <module>
    tf.app.run()
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 102, in main
    tmp = integral_image(train_image[idx])
  File "C:\Users\***\
***\Desktop\images\Research Project\JAAD\haar\viola-jones-algo-master\detection\utils\integ_img.py", line 27, in integral_image
    S = np.cumsum(image)
  File "<__array_function__ internals>", line 6, in cumsum
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 2483, in cumsum
    return _wrapfunc(a, 'cumsum', axis=axis, dtype=dtype, out=out)
  File "C:\Users\***\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
MemoryError: Unable to allocate 23.7 MiB for an array with shape (6220800,) and data type uint32



>python -c "import numpy; print(numpy.version.version)"
1.19.4

**Comment by seberg** [comment] 2020-12-17 01:24
Would anyone be able to create a minimal, shareable example? Otherwise it is very hard to dig into it to see what is going on.  There are few changes in 1.19.3 but it seems a bit like there might be a subtle but serious bug somewhere, and any starting point to find it would be *very* useful.

**Comment by AnkitSnh2** [comment] 2020-12-17 09:55
I tried reproing the issue, but it gives no issue with single image file. Can this be the problem because program tries to allocate more memory than available in stack? In my case I have to calculate cumsum of around 1400 images.

**Comment by mattip** [comment] 2020-12-17 10:13
If each image is 23.7MB, then you would need `(1400 * 23.7) / 1024 = 32.4 GB to just hold the array. So I think @AnkitSnh2's issue is very different from the one in the beginning of this issue, which seems to have been solved by changing OpenBLAS. Closing. @AnkitSnh2 if you still cannot work out what is going on, please open a new issue and detail exactly what you are doing.

**Closed by mattip** 2020-12-17 10:13 UTC
