### ISSUE TITLE
BUG: unique function return inverse in wrong type when input is an element. (numpy 2.0.0)

### ISSUE THREAD

**Issue by zexee** [numpy/numpy#26753] opened 2024-06-19 12:01 UTC
### Describe the issue:

np.unique behave differently in 2.0

### Reproduce the code example:

```python
import numpy as np
np.unique(1, return_index=True, return_inverse=True)

# in previous version, return is (array([1]), array([0]), array([0]))
# in 2.0 return is (array([1]), array([0]), array(0))
```

### Python and NumPy Versions:

2.0.0
3.9.18 (main, Sep  7 2023, 00:00:00)
[GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]

**Comment by wingkitlee0** [comment] 2024-06-20 01:22
It seems that this is intended. Based on the doc (below), one would expect that `unique[unique_inverse]` reproduces the input of `np.unique` 
```
unique_inverse : ndarray, optional
        The indices to reconstruct the original array from the
        unique array. Only provided if `return_inverse` is True.
```

Example:
```
In [2]: unique, unique_index, unique_inverse = np.unique(1, return_index=True, return_inverse=True)
   ...: print(unique, unique_index, unique_inverse)
   ...: print(unique[unique_inverse])
[1] [0] 0
1
```

**Comment by seberg** [comment] 2024-07-13 16:04
Closing, this indeed changed and it has the advantage of allowing to reconstruct the original array.  That is the good thing.
When you pass `axis=0` NumPy 2.0.0 also changed behavior, but I think that was a mistake and it will be reverted in 2.0.1.

**Closed by seberg** 2024-07-13 16:04 UTC
Labels: 00 - Bug
