### ISSUE TITLE
Numpy error No module named 'numpy.core._multiarray_umath' Linux / python 3.10 / 

### ISSUE THREAD

**Issue by rinukz** [numpy/numpy#21171] opened 2022-03-08 11:03 UTC
### Steps to reproduce:

`python -m pip install numpy`

Numpy error No module named 'numpy.core._multiarray_umath'   Linux / python 3.10 /

### Error message:

```shell
Python 3.10.0 (default, Dec 11 2021, 13:38:34) [GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ta
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.10/site-packages/ta/__init__.py", line 8, in <module>
    from ta.wrapper import (
  File "/opt/lib/python3.10/site-packages/ta/wrapper.py", line 8, in <module>
    import pandas as pd
  File "/opt/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/opt/bin/python"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.10/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/opt/bin/python"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

### Additional information:

import numpy
Traceback (most recent call last):
  File "/opt/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/opt/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lib/python3.10/site-packages/numpy/__init__.py", line 144, in <module>
    from . import core
  File "/opt/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/opt/bin/python"
  * The NumPy version is: "1.22.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

**Comment by rinukz** [comment] 2022-03-09 06:38
> How did you install NumPy?

python -m pip install numpy

**Comment by bhavukkalra** [comment] 2022-03-09 14:18
Hi, Could you share more info like(This also includes steps that you could try to get more info on what might be causing this)
1) What OS are you using? 
2) Could you try running the same command that you mentioned `python -m pip install numpy` in a separate virtual environment
3) Seeing by the additional information you shared. The error seem have to came through this procedure
You tried importing a package which had numpy as transitive dependency and It failed in importing it.

Having the above point in mind. Could you share the out put of the command `pip show numpy`?

**Comment by rinukz** [comment] 2022-03-10 10:23
> Hi, Could you share more info like(This also includes steps that you could try to get more info on what might be causing this)
> 
> 1. What OS are you using?
> 2. Could you try running the same command that you mentioned `python -m pip install numpy` in a separate virtual environment
> 3. Seeing by the additional information you shared. The error seem have to came through this procedure.
>    You tried importing a package which had numpy as transitive dependency and It failed in importing it.
> 
> Having the above point in mind. Could you share the out put of the command `pip show numpy`?

i uninstalled 3.10 and down greade to 3.9 .  all module work fine.

**Comment by mattip** [comment] 2022-03-10 12:42
Thanks for the update. Closing

**Closed by mattip** 2022-03-10 12:42 UTC
Labels: 32 - Installation

**Comment by ILYSHI** [comment] 2022-07-22 12:10
But the problem is not solved on Python 3.10

**Comment by jhaggle** [comment] 2022-11-29 16:08
+1

**Comment by JohnieBraaf** [comment] 2022-12-24 18:34
I was able to workaround this for python 3.10 using the following install method:
`python -m pip install numpy --no-binary=:all:`

I takes a bit longer to build/install but it fixes the errors.

**Comment by andyl-flwls** [comment] 2024-07-11 20:35
using 1.26.2 will solve this issue I tried, not sure other version supports for python3.10
