### ISSUE TITLE
BUG: ndarray prevents __radd__ overloading in custom classes

### ISSUE THREAD

**Issue by adrianschlatter** [numpy/numpy#21182] opened 2022-03-12 11:46 UTC
### Describe the issue:

I write a custom class MyClass that supports addition with ndarrays. That means

* `MyClass + ndarray`
* `ndarray + MyClass`

are meaningful operations (that return a MyClass object). The former works flawlessly, the latter does not. Here's what happens (see demo in example code):

For `ndarray + MyClass`, Python first tries `ndarray.__add__(...)`. This method does not know (and can not know) how to do additions involving MyClass objects. Therefore, I expect it to `raise NotImplementedError`. Instead, it tries to do elementwise addition, i.e., it calls `MyClass.__radd__(...)` multiple times with a float as argument (instead of once with an ndarray). The attached code example demonstrates this and also shows that `*, //, %, -` behave the same way. The only exception seems to be `np.matrix` multiplication which (correctly) calls `MyClass.__rmul__(...)` with the entire matrix as argument (but it also tries to go elementwise with `//, %, +, -`).

I hoped to stop numpy from doing this by making clear that MyClass does not support addition with floats by raising NoteImplementedError in `MyClass.__radd__(...)`. However, numpy does not revert to calling `MyClass.__radd__(...)` with the entire ndarray and just fails (not shown in the attached code).

Also, I cannot resort to only use `MyClass + ndarray` because this sort of addition is not commutative.

### Reproduce the code example:

```python
import numpy as np


class MyClass():

    def __rmul__(self, left):
        print(type(left))

    def __rfloordiv__(self, left):
        print(type(left))

    def __rmod__(self, left):
        print(type(left))

    def __radd__(self, left):
        print(type(left))

    def __rsub__(self, left):
        print(type(left))


print('ndarray:\n\n')

M = np.eye(2)
thing = MyClass()

print('Multiply:')
result = M * thing
print('\nAdd:')
result = M + thing
print('\nSub:')
result = M - thing
print('\nTruediv:')
result = M // thing
print('\nModulo:')
result = M % thing

print('\n\nmatrix:\n\n')

M = np.matrix(np.eye(2))
thing = MyClass()

print('Multiply:')
result = M * thing
print('\nAdd:')
result = M + thing
print('\nSub:')
result = M - thing
print('\nTruediv:')
result = M // thing
print('\nModulo:')
result = M % thing
```

### Error message:

```shell
ndarray:


Multiply:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

Add:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

Sub:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

Truediv:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

Modulo:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>


matrix:


Multiply:
<class 'numpy.matrix'>

Add:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

Sub:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

Truediv:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

Modulo:
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
```

### NumPy/Python version information:

1.20.1 3.9.4 (default, Apr  9 2021, 09:32:38) 
[Clang 10.0.0 ]

**Comment by alajoieumich** [comment] 2022-03-23 17:04
Looking into this

**Comment by adrianschlatter** [comment] 2022-03-27 19:48
Great! Let me know if I can assist.

**Comment by seberg** [comment] 2022-06-11 00:16
Not sure how this got lost...  In any case, this is expected behavior.  The problem is that NumPy is *very* aggressive in trying to take care of the operation by coercing the other argument into an array.  (What if it was a list?)

The solution is to implement `__array_ufunc__ = None` or `__array_priority__` on your object to inform NumPy that your class knows better.

Going to close the issue since it is a bit older and I think this answer should be enough to clear up the problem.

**Closed by seberg** 2022-06-11 00:16 UTC
Labels: 00 - Bug
