### ISSUE TITLE
init dgesdd failed init python for estimating large matrix

### ISSUE THREAD

**Issue by rudascience** [numpy/numpy#14284] opened 2019-08-16 03:30 UTC
Hi everyone, 
I was facing "init dgesdd failed init" error when I tried to estimate a huge matrix (>=10k) with tick.hawkesADM4, since my data is large, I need to estimate for the matrix with size around 200k. But when I tried with only 10k on the linux with huge (around 50GB) , It always pop up an error of failed init.

Can anyone help me please? 
Thank you.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment] 2019-08-16 05:53
Duplicate of X-DataInitiative/tick#377, and even though the tick project asked for a complete example you did not provide what they asked for there.

Please supply the version of python and numpy in use and where you got them, as requested in the template when you opened the issue. We cannot guess as to the cause of this issue until you provide at least what is asked for.

**Comment by rudascience** [comment] 2019-08-16 11:15
Hi, 
Sorry about that.  I cant reproduce the code since it takes time. Hopefully, following information might help.
I am using Python version: 3.7.0; numpy 1.15.4
I just tried to fit my data (events: is a list of 46399 one-dimension np.arrays) with tick.hawkesADM4 :

learner=HawkesADM4(decay)
learner.fit(events)
E.g, 

The errors when I run my script on windows with n=4000, and also got these errors when running on the server: 
C:\ProgramData\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in _raise_linalgerror_svd_nonconvergence(err, flag)
    104 
    105 def _raise_linalgerror_svd_nonconvergence(err, flag):
--> 106     raise LinAlgError("SVD did not converge")
    107 
    108 def _raise_linalgerror_lstsq(err, flag):

LinAlgError: SVD did not converge

When I running on the server with n=46399, the error is "init dgesdd failed init".

Thank you.

**Comment by mattip** [comment] 2019-08-16 11:30
Maybe related to #13956 where the lapack interface uses 32 bit integers. Are you using numpy from Anaconda or from pip?

**Comment by rudascience** [comment] 2019-08-20 05:35
Hi,
I am using numpy from Anaconda. Can you please tell me what should I do next?
Thanks!

**Comment by eric-wieser** [comment] 2019-08-20 05:54
Can you give any more context on the "init dgesdd failed init" error? Is it a python exception? Can you give the traceback up to the first frame of your code?

**Comment by iamaneek** [comment] 2020-01-14 01:20
I encountered a similar error;  changed from categorical_crossentropy to  sparse_categorical_crossentropy. Worked for me!

**Comment by masiarek** [comment] 2020-10-14 03:56
/usr/local/bin/python3.9 /Users/amasa/PycharmProjects/pythonProject/voting.py
init_dgelsd failed init
Traceback (most recent call last):
  File "/Users/amasa/PycharmProjects/pythonProject/voting.py", line 1, in <module>
    import re, sys, numpy
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned


Process finished with exit code 1

**Comment by mattip** [comment] 2020-10-14 06:16
@masiarek that is something different: you are using python3.9 which still does not have binary wheels, so it compiles locally with your buggy macOS version of Accelerate. So you are not using "numpy from Anaconda" rather "numpy locally compiled".

**Comment by rgommers** [comment] 2022-02-18 05:11
No further follow-up. Also we now ship 64-bit BLAS in our wheels, so this may be resolved. I'll close this issue.

**Closed by rgommers** 2022-02-18 05:11 UTC

**Comment by green-nsh** [comment] 2023-08-27 02:37
I have the same problem. How can I solve it? Or do I need to replace the computer with a higher memory configuration?
