### ISSUE TITLE
BUG: `numpy.ma.fix_invalid` makes changes in-place in numpy 2.1.0 even with `copy=True`

### ISSUE THREAD

**Issue by kounelisagis** [numpy/numpy#27253] opened 2024-08-20 15:43 UTC
### Describe the issue:

`numpy.ma.fix_invalid` behaves differently between NumPy 2.1.0 and NumPy 2.0.0. Specifically, when passing a pandas Series containing a `numpy.nan` value, `numpy.ma.fix_invalid` now makes changes in-place, even if the `copy` argument is set to its default value of `True`. This issue occurs only with pandas Series, not with NumPy arrays, for example.

### Reproduce the code example:

```python
>>> import pandas as pd, numpy as np
>>> pd.__version__; np.__version__
'2.2.2'
'2.1.0'
>>> my_series = pd.Series([1.0, 2.0, np.nan, 0.0, 1.0])
>>> my_series
0    1.0
1    2.0
2    NaN
3    0.0
4    1.0
dtype: float64
>>> np.ma.fix_invalid(my_series)
masked_array(data=[1.0, 2.0, --, 0.0, 1.0],
             mask=[False, False,  True, False, False],
       fill_value=1e+20)
>>> my_series
0    1.000000e+00
1    2.000000e+00
2    1.000000e+20
3    0.000000e+00
4    1.000000e+00
dtype: float64
```

### Python and NumPy Versions:

2.1.0
3.10.14 (main, May  6 2024, 14:42:37) [Clang 14.0.6 ]

### Context for the issue:

Problem discovered here: https://github.com/TileDB-Inc/TileDB-Py/pull/2042

**Comment by ngoldbaum** [comment] 2024-08-21 14:53
I think a Pandas developer likely needs to dive into this to understand where the behavior difference is coming from and whether or not Pandas should handle it. Can you file an issue on the Pandas repo reporting this?

**Comment by kounelisagis** [comment] 2024-08-26 13:54
But I tried using the same version of Pandas with NumPy 2.0.0, as well as with an earlier version of NumPy (<2.0), and there wasn't any problem.

**Comment by ngoldbaum** [comment] 2024-08-26 14:34
The fact that it's a pandas data type that's showing different behavior points to something in the Pandas codebase behaving differently. 

A Pandas developer would also be better able to reduce this down to a smaller example that doesn't depend on pandas to show that NumPy changed behavior somewhere in a way we didn't intend.

**Comment by fengluoqiuwu** [comment] 2024-10-20 11:22
Same bug happens in `np.array()`.

```python
>>> import pandas as pd, numpy as np
>>> my_series = pd.Series([1.0, 2.0, np.nan, 0.0, 1.0])
>>> test = np.array(my_series)
>>> test[2] =1
>>> my_series
0    1.0
1    2.0
2    1.0
3    0.0
4    1.0
dtype: float64
```

It seems like the cause of the bug, because `fix_invalid` calling `masked_array()` to copy the data first

**Comment by fengluoqiuwu** [comment] 2024-10-20 11:24
Same bug happens in `np.array()`.

```python
>>> import pandas as pd, numpy as np
>>> my_series = pd.Series([1.0, 2.0, np.nan, 0.0, 1.0])
>>> test = np.array(my_series,copy=True)
>>> test[2] =1
>>> my_series
0    1.0
1    2.0
2    1.0
3    0.0
4    1.0
dtype: float64
```

It seems like the cause of the bug, because `fix_invalid` calling `masked_array()` to copy the data first.

**Comment by seberg** [comment] 2024-11-15 12:18
Closing as fixed in pandas.

**Closed by seberg** 2024-11-15 12:18 UTC
Labels: 00 - Bug
