### ISSUE TITLE
BUG: np.reshape missing optional copy argument

### ISSUE THREAD

**Issue by Illviljan** [numpy/numpy#27373] opened 2024-09-10 20:13 UTC
### Describe the issue:

According to the [array api](https://data-apis.org/array-api/latest/API_specification/generated/array_api.reshape.html#array_api.reshape) reshape is supposed to have a copy argument.

### Reproduce the code example:

```python
import numpy as np
import array_api_strict as xps

xps.reshape(xps.zeros((1,2,3)), (3,2,1), copy=True)
np.reshape(np.zeros((1,2,3)), (3,2,1), copy=True)  # TypeError: reshape() got an unexpected keyword argument 'copy'
```

### Python and NumPy Versions:

2.0.2
3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:24:51) [MSC v.1940 64 bit (AMD64)]

**Comment by mattip** [comment] 2024-09-10 20:31
Fixed in #26292 which is part of the latest release (2.1). Please update.

**Closed by mattip** 2024-09-10 20:31 UTC
Labels: 00 - Bug

**Comment by FelixBenning** [comment] 2024-09-21 20:42
<img width="564" alt="Screenshot 2024-09-21 at 22 38 41" src="https://github.com/user-attachments/assets/17e1f866-0419-487a-9505-4c94f263bbc8">

there seems to be an issue with linters still

**Comment by FelixBenning** [comment] 2024-09-21 20:43
@mattip perhaps I should have added a mention of you since this issue is closed and might not be on the radar anymore.

**Comment by mattip** [comment] 2024-09-22 05:21
@FelixBenning please open a new issue, and don't forget to help us reproduce: what version of NumPy, operating system, linter ...
