### ISSUE TITLE
numpy converts to float if given a list of numpy.uint64 mixed with python ints

### ISSUE THREAD

**Issue by maxnoe** [numpy/numpy#18557] opened 2021-03-05 18:40 UTC
If a python list argument to `np.array` contains a mixture of `int` and `np.uint64`, the array will have `dtype=np.float64`.
Which results in a loss of information, since values are not exactly representable by float64.

### Reproducing code example:

```python
import numpy as np

def print_array(a):
    print(a.dtype, a)


large = 2**63 - 1

print_array(np.array([-1, large]))
print_array(np.array([-1, np.int64(large)]))
print_array(np.array([-1, np.uint64(large)]))

```

Results in:

```
int64 [                 -1 9223372036854775807]
int64 [                 -1 9223372036854775807]
float64 [-1.00000000e+00  9.22337204e+18]
```

### NumPy/Python version information:

```
1.20.1 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0]
```

**Comment by IchiruTake** [comment] 2021-03-08 08:33
> If a python list argument to `np.array` contains a mixture of `int` and `np.uint64`, the array will have `dtype=np.float64`.
> Which results in a loss of information, since values are not exactly representable by float64.
> 
> ### Reproducing code example:
> ```python
> import numpy as np
> 
> def print_array(a):
>     print(a.dtype, a)
> 
> 
> large = 2**63 - 1
> 
> print_array(np.array([-1, large]))
> print_array(np.array([-1, np.int64(large)]))
> print_array(np.array([-1, np.uint64(large)]))
> ```
> 
> Results in:
> 
> ```
> int64 [                 -1 9223372036854775807]
> int64 [                 -1 9223372036854775807]
> float64 [-1.00000000e+00  9.22337204e+18]
> ```
> 
> ### NumPy/Python version information:
> ```
> 1.20.1 3.9.2 (default, Feb 20 2021, 18:40:11) 
> [GCC 10.2.0]
> ```

I don't think this was a bug. Recheck your code, numpy array will choose the data type that best match with your data without changing its value meaning. In this case, your data type will not match as unsigned integer cannot be suitable with negative value. Thus, it will change into float64 as default data type.

**Comment by maxnoe** [comment] 2021-03-08 09:02
> Recheck your code, numpy array will choose the data type that best match with your data without changing its value meaning. 

The two values are exactly representable by int64 but not by float64 since it is larger that 2⁵². The obvious choice here is int64. It would go so far to say that this is a bug, since it actually destroys the exact value of the uint64 when a standard dtype able to exactly represent the data exists.

These kind of conversions should check signed integer variants before floats.

**Comment by seberg** [comment] 2021-03-08 16:19
If you use `np.uint64` thats what is used in `np.array`. The value is never checked, and I *very* strongly believe we should stop checking values (it just makes everything unpredictable).  
With that in mind, this becomes `int64 + uint64 -> float64` which is very weird of course, and there are a few issues about it open probably, e.g. gh-5745, and gh-8851 (this one you could at least fix explicitly even with the float64 general promotion rule).  There is another issue for when `uint64` is actually just a very large Python integer, where this happens as well, and where it is even a bit more mad.

In any case, whether you call it bug or not, its not that "obvious" a choice to me, so while I accept that this is an issue, I don't really have a suggestion of how to change it... Others do pick uint64 or int64 outputs in such a case, and maybe some future could do that, but such a future would probably need at least warnings for integer-rollovers, and we don't have those.

**Comment by IchiruTake** [comment] 2021-03-11 08:20
> If you use `np.uint64` thats what is used in `np.array`. The value is never checked, and I _very_ strongly believe we should stop checking values (it just makes everything unpredictable).
> With that in mind, this becomes `int64 + uint64 -> float64` which is very weird of course, and there are a few issues about it open probably, e.g. [gh-5745](https://github.com/numpy/numpy/issues/5745), and [gh-8851](https://github.com/numpy/numpy/issues/8851) (this one you could at least fix explicitly even with the float64 general promotion rule). There is another issue for when `uint64` is actually just a very large Python integer, where this happens as well, and where it is even a bit more mad.
> 
> In any case, whether you call it bug or not, its not that "obvious" a choice to me, so while I accept that this is an issue, I don't really have a suggestion of how to change it... Others do pick uint64 or int64 outputs in such a case, and maybe some future could do that, but such a future would probably need at least warnings for integer-rollovers, and we don't have those.
I
> > Recheck your code, numpy array will choose the data type that best match with your data without changing its value meaning.
> 
> The two values are exactly representable by int64 but not by float64 since it is larger that 2⁵². The obvious choice here is int64. It would go so far to say that this is a bug, since it actually destroys the exact value of the uint64 when a standard dtype able to exactly represent the data exists.
> 
> These kind of conversions should check signed integer variants before floats.

No, I think Numpy works well in this case
Float64 allows number up to 1.7976931348623157 * 10^308 which is the pre-defined data type of Numpy that don't violate the meaning of your array, when you assign some number inside the array that is violate with pre-defined, Numpy will change your manual control data type.
I believe this is what it works:

First it would check first to search for some manual defined datatype that can be fit. If possible, re-check the array to ensure no data is violated. If violated, it will default change your data type into float64 (assume your ndarray are numeric contained, else np.object_).

Yes, I agree with seberg that int64 + uint64 to become float64 is relatively weird, but this is the only solution possible as ndarray written in C/C++ which was a static/statistic array rather than Python List (generic)

**Comment by seberg** [comment] 2022-05-12 10:04
Closing this one as a duplicate of gh-19146 (Not that the other issue has additional information.  This is rightly a fairly common issue unfortunately, but it doens't help much to have many issues open).

**Closed by seberg** 2022-05-12 10:04 UTC
