### ISSUE TITLE
Comparison of numpy.complex64 should throw a type error, as in the bare python complex number type

### ISSUE THREAD

**Issue by bcrowell** [numpy/numpy#19168] opened 2021-06-04 16:51 UTC
### Reproducing code example:

    $ python3 -c 'print(1.0<1.0+1.0j)'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    TypeError: '<' not supported between instances of 'float' and 'complex'
    $ python3 -c 'import numpy; print(1.0<numpy.complex64(1.0+1.0j))'
    True
    $ python3 -c 'import numpy; print(1.0<numpy.complex64(1.0-1.0j))'
    False

### NumPy/Python version information:

1.17.4 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0]

The bare python implementation throws an error, as it should. The behavior of the numpy.complex64 class shows behavior that is inconsistent with that, doesn't make sense mathematically, and doesn't seem to be documented anywhere. It appears to be doing a lexicographic comparison of real and imaginary parts. It should throw a type error instead. Since the present behavior does not seem to be defined anywhere, nobody should be depending on the undefined behavior, and fixing it should not cause problems.

**Comment by mattip** [comment] 2021-06-07 05:36
Duplicate of #15981

**Comment by seberg** [comment] 2022-03-18 15:53
Going to close, as it is marked as duplicate.  Thanks for the report!

**Closed by seberg** 2022-03-18 15:53 UTC
Labels: 50 - Duplicate
