### ISSUE TITLE
Emergency stop in the function "numpy.correlate"

### ISSUE THREAD

**Issue by gadpetrovich** [numpy/numpy#14366] opened 2019-08-26 19:12 UTC
python.exe crashes when I try to take a correlation in a negative slice.

OS: Windows 10 Pro 10.0.18362 x64.

### Reproducing code example:

```python
import numpy as np
a = np.ones((2,), dtype=np.float64)
b = np.correlate(a[0:1], a[-1:0], mode='same')
```

### Error message:

Event in the windows application log:
```
   python.exe 
   3.7.3150.1013 
   5c9954fa 
   ntdll.dll 
   10.0.18362.267 
   c00f8a30 
   c0000374 
   00000000000f9269 
   58e4 
   01d55c3f47182e12 
   e:\projects\forecast_scripts\venv37\scripts\python.exe 
   C:\WINDOWS\SYSTEM32\ntdll.dll 
   19c70a1a-33d0-419e-8a48-9d6f37d57a27 
```

### Numpy/Python version information:
1.16.4/3.7.3

1.16.4 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

**Comment by seberg** [comment] 2019-09-16 19:20
Interesting, the bug seems sometimes hidden (not quite sure why, but it just writes one value to far out). The issue is that `n1 - n2 + 1` is 2, so the inner loop is called twice, while `n_right` is `-1` (which does not make sense). Maybe the nicest thing might be to calculate `(n1 - n2 + 1)` differently. I think this is necessary for modes 0 and 1, but should add tests to make sure.

**Comment by seberg** [comment] 2019-09-16 19:27
Hmm, maybe it is best to raise an error, at least if mode is not same? The full mode ends up smaller than same, valid mode ends up with length 2, which kind of makes sense, but is all pretty confusing.

**Comment by seberg** [comment] 2019-09-22 01:04
Interesting, I just found gh-8736 where it seemed like they were also converging on simply going with an error. To be clear, I will close that one, because the code really should be fixed on the C side, and that is not very hard.

We should simply raise an error from the C side and add tests for now (the linked old PR may be a start for tests).

To be honest, there is probably not much of a reason to move the whole function to C in any case, since all it takes is parsing of `mode`.

**Comment by mattip** [comment] 2019-11-06 20:20
gh-14829 fixed the problem for empty input. Closing. Please reopen or open a new issue if there are still crashes with `correlate`

**Closed by mattip** 2019-11-06 20:20 UTC
Labels: 00 - Bug, component: numpy.core, good first issue
