### ISSUE TITLE
BUG:Deployment in Django

### ISSUE THREAD

**Issue by maharana1b** [numpy/numpy#22114] opened 2022-08-12 07:23 UTC
### Describe the issue:

I created a machine learning project based on regression, it is working fine in my local server, but after deployment it's throwing the error mentioned below.

### Reproduce the code example:

```python
It is from my deployment server as above.
```

### Error message:

```shell
UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
```

### NumPy/Python version information:

numpy version 1.13.1

**Comment by mattip** [comment] 2022-08-12 09:36
That is a warning. It should not prevent your program from running unless you are turning warnings into errors. Is there something actionable you think we should do? If so we need more information to reproduce the problem.

**Comment by rgommers** [comment] 2022-08-24 05:11
No further follow-up and not a bug, so I'll close the issue.

**Closed by rgommers** 2022-08-24 05:11 UTC
Labels: 00 - Bug, 57 - Close?
