### ISSUE TITLE
in operator with dtype and set does not work as expected

### ISSUE THREAD

**Issue by pohlt** [numpy/numpy#16208] opened 2020-05-11 17:51 UTC
When testing if the dtype of an array is present in a set of dtypes, the answer is unexpected.

### Reproducing code example:

```python
import numpy as np
f32_dtype = np.zeros(1, dtype=np.float32).dtype

# test with list of dtypes
print(f32_dtype in [np.float32, np.uint8])  # => True (as expected)

# test with set of dtypes
print(f32_dtype in {np.float32, np.uint8})  # => False (not as expected)
```

### Error message:

none

### Numpy/Python version information:

numpy 1.18.4
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

**Comment by eric-wieser** [comment] 2020-05-11 19:02
What you're seeing here is that `dtype(np.float32) == np.float32`, but `hash(dtype(np.float32)) != hash(np.float32)`

**Comment by pohlt** [comment] 2020-05-11 19:06
Ah, I see. Thanks for the explanation.
And the list case never uses hashes for the comparison and that's why it works. Still, IMHO, unexpected behavior.

**Comment by eric-wieser** [comment] 2020-05-11 19:22
Agreed that this is a bit unpleasant - we might be able to adjust `dtype.__hash__` to fix this.

**Comment by Qiyu8** [comment] 2020-05-15 07:06
I think `dtype(np.float32)` should not equal to `np.float32`, because in string form, `dtype('float32')` is different with `<class 'numpy.float32'>`, The correct equation is `dtype(np.float32).type == np.float32`, OTOH, The hash comparison result is correct.

**Comment by seberg** [comment] 2020-05-15 14:26
Yeah, its a bit trickier since there also many strings, etc. which will evaluate equal.  I think `np.dtype(np.float64)` is probably too common, so that I do not really want to consider getting rid of it, and the meaning of the two versions is unfortunately subtly different (byte-order checking).

Anyway, I agree that all of this would be nice to fix, but not sure I consider it super important to be honest, since the noise of fixing it seems likely high to me?

For completeness:
```
In [12]: f8 == "f8"                                                                                                     
Out[12]: True

In [13]: f8 == "float64"                                                                                                
Out[13]: True

In [14]: f8 == ("float64", ())                                                                                          
Out[14]: True

In [15]: f8 == np.float64                                                                                               
Out[15]: True

In [16]: hash(f8) == hash((f8.kind, "<", chr(f8.flags), f8.itemsize, f8.alignment))                                     
Out[16]: True
```
The last one is the actual way we define the hash here currently (which can easily be changed).

**Comment by seberg** [comment] 2021-02-24 20:35
Going to close this as duplicate of gh-7242.

**Closed by seberg** 2021-02-24 20:35 UTC
Labels: 00 - Bug, component: numpy.dtype
