### ISSUE TITLE
BUG: numpy.arange() function return unexpected results

### ISSUE THREAD

**Issue by code-yuan-shi** [numpy/numpy#21134] opened 2022-03-02 09:05 UTC
### Describe the issue:

Examples are as follows:
``np.arange(0,1.12,0.04)
will return
``array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  , 1.04, 1.08, 1.12])
but
``np.arange(0,1.18,0.04)
return 
``array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  , 1.04])

### Reproduce the code example:

```python
import numpy as np

# One open interval, one closed interval
print(np.arange(0,1.12,0.04))

print(np.arange(0,1.08,0.04))
```

### NumPy/Python version information:

1.22.2 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]

**Comment by bashtage** [comment] 2022-03-02 11:45
I can't reproduce.

```
In [2]: np.arange(0,1.18,0.04)
Out[2]:
array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  , 1.04, 1.08, 1.12, 1.16])
```

**Comment by bashtage** [comment] 2022-03-02 11:51
Your first example differs from the second.  The second happens because of numeric noise.  Since you are using floats it is possible that `0 + 0.04 * 28 < 1.12` when , and so 1.12 is in the interval.  In fact, this is exactly the case

```
In [6]: 1.12/0.04
Out[6]: 28.000000000000004
```

But 

`0 + 0.04 * 27 >= 1.08` so that 1.08 is excluded

and in fact, this is also the case

```
In [7]: 1.08/0.04
Out[7]: 27.0
```

This is a common "gotcha" when using floating-point intervals.  The simple solution is usually to add 1/2 the step size the end point if you know it should be an integer divisor.  Alternatively, you could use `np.arange(0,28)*0.04` which would always give you precise control of the end point since it is integral.

**Comment by melissawm** [comment] 2022-03-02 19:18
I will close this as a duplicate of #19552, we should have better documentation on this soon (I'm working on it). Please comment there if you have suggestions, thanks!

**Closed by melissawm** 2022-03-02 19:18 UTC
Labels: 00 - Bug
