### ISSUE TITLE
TYP: incorrect array_finalize definition in ndarray for subclassing

### ISSUE THREAD

**Issue by henryiii** [numpy/numpy#20756] opened 2022-01-06 20:05 UTC
https://github.com/numpy/numpy/blob/4adc87dff15a247e417d50f10cc4def8e1c17a03/numpy/__init__.pyi#L1505-L1506

Currently, mypy does not allow users to define `__array_finalize__`, since the super class (ndarray) does not have an argument. So the following error is produced:

```
src/vector/_backends/numpy_.py:899: error: Signature of "__array_finalize__" incompatible with supertype "ndarray"  [override]
src/vector/_backends/numpy_.py:899: note:      Superclass:
src/vector/_backends/numpy_.py:899: note:          def __array_finalize__(self) -> None
src/vector/_backends/numpy_.py:899: note:      Subclass:
src/vector/_backends/numpy_.py:899: note:          def __array_finalize__(self, obj: Any) -> None
```

This type stub should have a `obj: Any` argument.

**Comment by BvB93** [comment] 2022-01-07 14:26
This seems to be a duplicate of https://github.com/numpy/numpy/pull/20764 (though the focus of that issue is admittedly a bit broader).
In any case, PR https://github.com/numpy/numpy/pull/20764 will resolve the issue.

**Comment by BvB93** [comment] 2022-01-08 14:20
Closed by https://github.com/numpy/numpy/pull/20768

**Closed by BvB93** 2022-01-08 14:20 UTC
Labels: 50 - Duplicate, static typing
