### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`.

### ISSUE THREAD

**Issue by luke110** [numpy/numpy#25052] opened 2023-11-02 05:08 UTC
### Describe the issue:

When I execute the program I get an error AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
I am using numpy==1.24.4。

### Reproduce the code example:

```python
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### Error message:

```shell
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

### Runtime information:

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by mattip** [comment] 2023-11-02 05:35
How can we reproduce this? You did not add the code that causes the error to appear.

**Comment by luke110** [comment] 2023-11-02 06:03
> 我们如何重现这个？您没有添加导致出现错误的代码。

I encountered this problem when reproducing the FairMOT project。The address of this project is https://github.com/ifzhang/FairMOT。The parameters I added when executing train.py under src were mot --exp_id crowdhuman_dla34 --gpus 0 --batch_size 8 --load_model "'../models/ctdet_coco_dla_2x.pth'" --num_epochs 60 --lr_step " '50'" --data_cfg "'../src/lib/cfg/crowdhuman.json'"
Using tensorboard。After executing, I encountered this problem。

**Comment by mattip** [comment] 2023-11-02 07:51
[This issue](https://github.com/ifzhang/FairMOT/issues/520) is not in english, but I think it is a duplicate of this one. The upstream repo uses `np.float`. They should convert it to `float` or `np.float64`. Closing, as there is nothing we can do here.

**Closed by mattip** 2023-11-02 07:51 UTC
Labels: 00 - Bug

**Comment by dphdmn** [comment] 2024-02-17 10:19
# I have same issue

Just had same exact issue in [my little](https://colab.research.google.com/drive/1wKP1NhUbj626KvxKxa3m37cW_0QUIKOj?usp=sharing#forceEdit=true&sandboxMode=true&scrollTo=PM0BejBUZRcm) Google Collab project, so it just suddenly [stopped working, as someone reported to me](https://media.discordapp.net/attachments/1208329159378604093/1208330856322568232/image.png?ex=65e2e4cd&is=65d06fcd&hm=2160640f6b5c79394da8354a8e743767b3c7c9be2a151d8d498610bdb40ec44d&=&format=webp&quality=lossless&width=1440&height=590).

It seems like it automatically installed version [1.25.2](https://i.imgur.com/7IR1G0K.png), and **it does not work there anymore.**

# How I fixed it in my project

Fixed by downgrading to the lowest requirement numpy version (for my project it was [1.22.0](https://github.com/forestagostinelli/DeepCubeA/blob/master/requirements.txt#L2))

**`!pip install --upgrade numpy===1.22.0`**

# How to recreate bug

Go to [my little](https://colab.research.google.com/drive/1wKP1NhUbj626KvxKxa3m37cW_0QUIKOj?usp=sharing#forceEdit=true&sandboxMode=true&scrollTo=PM0BejBUZRcm) Google Collab project

- run "Setup"
- skip _"Numpy Bug fix"_
- run "scramble"
- run "Solve"

Without downgrading - [Image](https://i.imgur.com/1LedyF3.png)
With downgrading (run "Numpy Bug Fix" before "Solve") - [Image](https://i.imgur.com/7IR1G0K.png)

## Expected result:
```
State: 0, SolnCost: 85.00, # Moves: 85, # Nodes Gen: 6,021,237, Time: 62.25
State: 12 6 4 9 18 3 5 17 11 7 13 22 14 24 10 23 2 21 1 20 19 0 16 8 15
Solution: RDLLLDRDRRDLLULURUULDDDLDRRRURUULLURRDLDDLUULLURRRDDDRULDLLLDRRRURDLULULDLUURDRRULLUL
```

## Unexpected result:
```
Traceback (most recent call last):
  File "/content/DeepCubeA/search_methods/astar.py", line 644, in <module>
    main()
  File "/content/DeepCubeA/search_methods/astar.py", line 379, in main
    env: Environment = env_utils.get_environment(args.env)
  File "/content/DeepCubeA/utils/env_utils.py", line 17, in get_environment
    env = NPuzzle(puzzle_dim)
  File "/content/DeepCubeA/environments/n_puzzle.py", line 32, in __init__
    super().__init__()
  File "/content/DeepCubeA/environments/environment_abstract.py", line 20, in __init__
    self.dtype = np.float
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

# Why?

**Not sure why it suddenly installed 1.25.2 by default, but it might be the main issue.**

~Honestly, I have no idea why numpy developers would just randomly remove compatibility features to force everyone to downgrade or expect all the small developers to fix their old projects.~
