### ISSUE TITLE
Should be able to convert string arrays to bool_

### ISSUE THREAD

**Issue by charris** [numpy/numpy#12252] opened 2018-10-23 17:27 UTC
NumPy can create boolean arrays out of strings, but cannot convert string arrays to bool_. I think we should follow Python here and assign truth values to strings.

### Reproducing code example:

```python
>>> import numpy as np
>>> np.array('N', dtype='?')
array(True)
>>> np.array('N').astype('?')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'N'
```

**Comment by eric-wieser** [comment] 2018-10-23 17:59
Duplicates #9875, I think

**Comment by mattip** [comment] 2019-04-29 23:16
Closing as a duplicate of #9875. Please reopen if I misunderstood

**Closed by mattip** 2019-04-29 23:16 UTC
Labels: 01 - Enhancement
