### ISSUE TITLE
cumsum ignores dtype parameter of `int`

### ISSUE THREAD

**Issue by Woodz** [numpy/numpy#17590] opened 2020-10-20 04:38 UTC
### Reproducing code example:

```python
import numpy as np
cumsum = np.cumsum([1,2,3], dtype=int)
type = cumsum.dtype
```
#### Expected
type = int

#### Actual
type = int64

### NumPy/Python version information:

1.18.1 3.8.2 (default, Aug 25 2020, 09:23:57) 
[Clang 12.0.0 (clang-1200.0.32.2)]

**Comment by Qiyu8** [comment] 2020-10-20 06:39
@Woodz, Which platform are you running on? I got the correct `int32` result in windows.

**Comment by Woodz** [comment] 2020-10-20 06:42
> @Woodz, Which platform are you running on? 

I am on macOS Catalina (v 10.15.6), 64-bit

> I got the correct `int32` result in windows.

Note: Expected is `int` (i.e. inbuilt Python datatype), not `numpy.int32`

**Comment by charris** [comment] 2020-10-20 12:52
The use of `int` is deprecated, the builtin `int` type was C long, which varies in size across platforms.

**Comment by rkern** [comment] 2020-10-20 13:13
When you request a `dtype`, the argument that you pass gets interpreted to one of the known numpy dtypes. You can specify one of the builtin Python types that have a corresponding numpy implementation (`int`, `float`, `complex`, etc.). You can also pass one of the numpy scalar types (`np.int32`, `np.complex64`, etc.) that correspond exactly to the known numpy dtypes. There are also a variety of strings that are interpreted into dtypes.

When you ask an `ndarray` for its `.dtype` attribute, you will get an actual numpy `dtype` instance that was the result of that interpretation, not necessarily the exact object that you passed to the `dtype=` argument of the function that created the array.

Because of the platform dependency that @charris mentioned, requested `dtype=int` is interpreted into `dtype('int64')` on 64-bit macOS and `dtype('int32')` on Windows (either 32-bit or 64-bit because of a choice Microsoft made when developing the 64-bit version). Both of you are observing the expected behavior on your respective platforms.

**Comment by eric-wieser** [comment] 2020-10-20 13:33
@charris: `dtype=int` is not deprecated, just `dtype=np.int` which is a bad spelling of the same thing.

**Comment by Woodz** [comment] 2020-10-21 07:57
> When you request a `dtype`, the argument that you pass gets interpreted to one of the known numpy dtypes. You can specify one of the builtin Python types that have a corresponding numpy implementation (`int`, `float`, `complex`, etc.). You can also pass one of the numpy scalar types (`np.int32`, `np.complex64`, etc.) that correspond exactly to the known numpy dtypes. There are also a variety of strings that are interpreted into dtypes.
> 
> When you ask an `ndarray` for its `.dtype` attribute, you will get an actual numpy `dtype` instance that was the result of that interpretation, not necessarily the exact object that you passed to the `dtype=` argument of the function that created the array.
> 
> Because of the platform dependency that @charris mentioned, requested `dtype=int` is interpreted into `dtype('int64')` on 64-bit macOS and `dtype('int32')` on Windows (either 32-bit or 64-bit because of a choice Microsoft made when developing the 64-bit version). Both of you are observing the expected behavior on your respective platforms.

Thanks for the detailed implementation details @rkern . This makes a lot of sense from the implementation perspective, but as an end user, I would not expect this to occur. If this behaviour is correct and expected, then I would recommend that:
- The API documentation is updated to explain this
- Warning logging is added if a non-numpy datatype is passed in to explain that this datatype has been interpreted into the appropriate numpy datatype

**Comment by rkern** [comment] 2020-10-21 13:35
I don't think we're not going to issue a warning. These are expected and convenient inputs. It would be much too noisy.

The `dtype` interpretation behavior is documented here: https://numpy.org/doc/stable/reference/arrays.dtypes.html

I don't think we're going to repeat that full explanation everywhere there is a `dtype=` argument.

**Comment by seberg** [comment] 2022-11-19 16:19
Going to close this, it doesn't seem like much to do here.  Maybe one day we decide to modify things slightly, but the argument is not ignored and the result is correct, considering how `dtype=int` and `np.dtype(int)` work generally.

**Closed by seberg** 2022-11-19 16:19 UTC
