### ISSUE TITLE
BUG: np.dtype("Float16") raising inconsistently depending on locale

### ISSUE THREAD

**Issue by jbrockmendel** [numpy/numpy#20512] opened 2021-12-03 18:55 UTC
In https://github.com/pandas-dev/pandas/pull/44715 I depend on `np.dtype("Float16")` to raise `TypeError: data type 'Float16' not understood`, and it does on most CI builds.

Two builds on which it does not raise are 1) a build with `locale.getlocale()[0] != "en_US"` and 2) a py310 windows [build](https://github.com/pandas-dev/pandas/runs/4404315478?check_suite_focus=true) with npdev.

**Comment by seberg** [comment] 2021-12-03 20:29
Confusing, I thought we removed those upper case versions.  There is probably something wrong in this file:
https://github.com/numpy/numpy/blob/eeef9d4646103c3b1afd3085f1393f2b3f9575b2/numpy/core/_type_aliases.py#L26

with that dict (or the one below) being filled with additional values that should not be added.  That files uses the custom `english_lower`, is that function maybe not working as advertised?

**Comment by scratchmex** [comment] 2021-12-04 02:26
I cannot reproduce. Running

```python
from pprint import pprint
import locale

locale.setlocale(locale.LC_ALL, "en_GB")

print(f"{locale.getlocale() = }")

import numpy as np

print("_concrete_typeinfo = ", end="")
pprint(np.core._type_aliases._concrete_typeinfo)
print("sctypeDict = ", end="")
pprint(np.core._type_aliases.sctypeDict)

print(np.dtype("Float16"))
```
I get
```python
locale.getlocale() = ('en_GB', 'ISO8859-1')
_concrete_typeinfo = {'bool': numpy.core.multiarray.typeinforanged(char='?', num=0, bits=8, alignment=1, max=1, min=0, type=<class 'numpy.bool_'>),
 'byte': numpy.core.multiarray.typeinforanged(char='b', num=1, bits=8, alignment=1, max=127, min=-128, type=<class 'numpy.int8'>),
 'cdouble': numpy.core.multiarray.typeinfo(char='D', num=15, bits=128, alignment=8, type=<class 'numpy.complex128'>),
 'cfloat': numpy.core.multiarray.typeinfo(char='F', num=14, bits=64, alignment=4, type=<class 'numpy.complex64'>),
 'clongdouble': numpy.core.multiarray.typeinfo(char='G', num=16, bits=256, alignment=16, type=<class 'numpy.complex256'>),
 'datetime': numpy.core.multiarray.typeinforanged(char='M', num=21, bits=64, alignment=8, max=9223372036854775807, min=-9223372036854775808, type=<class 'numpy.datetime64'>),
 'double': numpy.core.multiarray.typeinfo(char='d', num=12, bits=64, alignment=8, type=<class 'numpy.float64'>),
 'float': numpy.core.multiarray.typeinfo(char='f', num=11, bits=32, alignment=4, type=<class 'numpy.float32'>),
 'half': numpy.core.multiarray.typeinfo(char='e', num=23, bits=16, alignment=2, type=<class 'numpy.float16'>),
 'int': numpy.core.multiarray.typeinforanged(char='i', num=5, bits=32, alignment=4, max=2147483647, min=-2147483648, type=<class 'numpy.int32'>),
 'intp': numpy.core.multiarray.typeinforanged(char='p', num=7, bits=64, alignment=8, max=9223372036854775807, min=-9223372036854775808, type=<class 'numpy.int64'>),
 'long': numpy.core.multiarray.typeinforanged(char='l', num=7, bits=64, alignment=8, max=9223372036854775807, min=-9223372036854775808, type=<class 'numpy.int64'>),
 'longdouble': numpy.core.multiarray.typeinfo(char='g', num=13, bits=128, alignment=16, type=<class 'numpy.float128'>),
 'longlong': numpy.core.multiarray.typeinforanged(char='q', num=9, bits=64, alignment=8, max=9223372036854775807, min=-9223372036854775808, type=<class 'numpy.longlong'>),
 'object': numpy.core.multiarray.typeinfo(char='O', num=17, bits=64, alignment=8, type=<class 'numpy.object_'>),
 'short': numpy.core.multiarray.typeinforanged(char='h', num=3, bits=16, alignment=2, max=32767, min=-32768, type=<class 'numpy.int16'>),
 'string': numpy.core.multiarray.typeinfo(char='S', num=18, bits=0, alignment=1, type=<class 'numpy.bytes_'>),
 'timedelta': numpy.core.multiarray.typeinforanged(char='m', num=22, bits=64, alignment=8, max=9223372036854775807, min=-9223372036854775808, type=<class 'numpy.timedelta64'>),
 'ubyte': numpy.core.multiarray.typeinforanged(char='B', num=2, bits=8, alignment=1, max=255, min=0, type=<class 'numpy.uint8'>),
 'uint': numpy.core.multiarray.typeinforanged(char='I', num=6, bits=32, alignment=4, max=4294967295, min=0, type=<class 'numpy.uint32'>),
 'uintp': numpy.core.multiarray.typeinforanged(char='P', num=8, bits=64, alignment=8, max=18446744073709551615, min=0, type=<class 'numpy.uint64'>),
 'ulong': numpy.core.multiarray.typeinforanged(char='L', num=8, bits=64, alignment=8, max=18446744073709551615, min=0, type=<class 'numpy.uint64'>),
 'ulonglong': numpy.core.multiarray.typeinforanged(char='Q', num=10, bits=64, alignment=8, max=18446744073709551615, min=0, type=<class 'numpy.ulonglong'>),
 'unicode': numpy.core.multiarray.typeinfo(char='U', num=19, bits=0, alignment=4, type=<class 'numpy.str_'>),
 'ushort': numpy.core.multiarray.typeinforanged(char='H', num=4, bits=16, alignment=2, max=65535, min=0, type=<class 'numpy.uint16'>),
 'void': numpy.core.multiarray.typeinfo(char='V', num=20, bits=0, alignment=1, type=<class 'numpy.void'>)}
sctypeDict = {0: <class 'numpy.bool_'>,
 1: <class 'numpy.int8'>,
 2: <class 'numpy.uint8'>,
 3: <class 'numpy.int16'>,
 4: <class 'numpy.uint16'>,
 5: <class 'numpy.int32'>,
 6: <class 'numpy.uint32'>,
 7: <class 'numpy.int64'>,
 8: <class 'numpy.uint64'>,
 9: <class 'numpy.longlong'>,
 10: <class 'numpy.ulonglong'>,
 11: <class 'numpy.float32'>,
 12: <class 'numpy.float64'>,
 13: <class 'numpy.float128'>,
 14: <class 'numpy.complex64'>,
 15: <class 'numpy.complex128'>,
 16: <class 'numpy.complex256'>,
 17: <class 'numpy.object_'>,
 18: <class 'numpy.bytes_'>,
 19: <class 'numpy.str_'>,
 20: <class 'numpy.void'>,
 21: <class 'numpy.datetime64'>,
 22: <class 'numpy.timedelta64'>,
 23: <class 'numpy.float16'>,
 '?': <class 'numpy.bool_'>,
 'B': <class 'numpy.uint8'>,
 'D': <class 'numpy.complex128'>,
 'F': <class 'numpy.complex64'>,
 'G': <class 'numpy.complex256'>,
 'H': <class 'numpy.uint16'>,
 'I': <class 'numpy.uint32'>,
 'L': <class 'numpy.uint64'>,
 'M': <class 'numpy.datetime64'>,
 'M8': <class 'numpy.datetime64'>,
 'O': <class 'numpy.object_'>,
 'P': <class 'numpy.uint64'>,
 'Q': <class 'numpy.ulonglong'>,
 'S': <class 'numpy.bytes_'>,
 'U': <class 'numpy.str_'>,
 'V': <class 'numpy.void'>,
 'a': <class 'numpy.bytes_'>,
 'b': <class 'numpy.int8'>,
 'b1': <class 'numpy.bool_'>,
 'bool': <class 'numpy.bool_'>,
 'bool8': <class 'numpy.bool_'>,
 'bool_': <class 'numpy.bool_'>,
 'byte': <class 'numpy.int8'>,
 'bytes': <class 'numpy.bytes_'>,
 'bytes0': <class 'numpy.bytes_'>,
 'bytes_': <class 'numpy.bytes_'>,
 'c16': <class 'numpy.complex128'>,
 'c32': <class 'numpy.complex256'>,
 'c8': <class 'numpy.complex64'>,
 'cdouble': <class 'numpy.complex128'>,
 'cfloat': <class 'numpy.complex128'>,
 'clongdouble': <class 'numpy.complex256'>,
 'clongfloat': <class 'numpy.complex256'>,
 'complex': <class 'numpy.complex128'>,
 'complex128': <class 'numpy.complex128'>,
 'complex256': <class 'numpy.complex256'>,
 'complex64': <class 'numpy.complex64'>,
 'complex_': <class 'numpy.complex128'>,
 'csingle': <class 'numpy.complex64'>,
 'd': <class 'numpy.float64'>,
 'datetime64': <class 'numpy.datetime64'>,
 'double': <class 'numpy.float64'>,
 'e': <class 'numpy.float16'>,
 'f': <class 'numpy.float32'>,
 'f16': <class 'numpy.float128'>,
 'f2': <class 'numpy.float16'>,
 'f4': <class 'numpy.float32'>,
 'f8': <class 'numpy.float64'>,
 'float': <class 'numpy.float64'>,
 'float128': <class 'numpy.float128'>,
 'float16': <class 'numpy.float16'>,
 'float32': <class 'numpy.float32'>,
 'float64': <class 'numpy.float64'>,
 'float_': <class 'numpy.float64'>,
 'g': <class 'numpy.float128'>,
 'h': <class 'numpy.int16'>,
 'half': <class 'numpy.float16'>,
 'i': <class 'numpy.int32'>,
 'i1': <class 'numpy.int8'>,
 'i2': <class 'numpy.int16'>,
 'i4': <class 'numpy.int32'>,
 'i8': <class 'numpy.int64'>,
 'int': <class 'numpy.int64'>,
 'int0': <class 'numpy.int64'>,
 'int16': <class 'numpy.int16'>,
 'int32': <class 'numpy.int32'>,
 'int64': <class 'numpy.int64'>,
 'int8': <class 'numpy.int8'>,
 'int_': <class 'numpy.int64'>,
 'intc': <class 'numpy.int32'>,
 'intp': <class 'numpy.int64'>,
 'l': <class 'numpy.int64'>,
 'long': <class 'numpy.int64'>,
 'longcomplex': <class 'numpy.complex256'>,
 'longdouble': <class 'numpy.float128'>,
 'longfloat': <class 'numpy.float128'>,
 'longlong': <class 'numpy.longlong'>,
 'm': <class 'numpy.timedelta64'>,
 'm8': <class 'numpy.timedelta64'>,
 'object': <class 'numpy.object_'>,
 'object0': <class 'numpy.object_'>,
 'object_': <class 'numpy.object_'>,
 'p': <class 'numpy.int64'>,
 'q': <class 'numpy.longlong'>,
 'short': <class 'numpy.int16'>,
 'single': <class 'numpy.float32'>,
 'singlecomplex': <class 'numpy.complex64'>,
 'str': <class 'numpy.str_'>,
 'str0': <class 'numpy.str_'>,
 'str_': <class 'numpy.str_'>,
 'string_': <class 'numpy.bytes_'>,
 'timedelta64': <class 'numpy.timedelta64'>,
 'u1': <class 'numpy.uint8'>,
 'u2': <class 'numpy.uint16'>,
 'u4': <class 'numpy.uint32'>,
 'u8': <class 'numpy.uint64'>,
 'ubyte': <class 'numpy.uint8'>,
 'uint': <class 'numpy.uint64'>,
 'uint0': <class 'numpy.uint64'>,
 'uint16': <class 'numpy.uint16'>,
 'uint32': <class 'numpy.uint32'>,
 'uint64': <class 'numpy.uint64'>,
 'uint8': <class 'numpy.uint8'>,
 'uintc': <class 'numpy.uint32'>,
 'uintp': <class 'numpy.uint64'>,
 'ulonglong': <class 'numpy.ulonglong'>,
 'unicode': <class 'numpy.str_'>,
 'unicode_': <class 'numpy.str_'>,
 'ushort': <class 'numpy.uint16'>,
 'void': <class 'numpy.void'>,
 'void0': <class 'numpy.void'>}
Traceback (most recent call last):
  File "bug1.py", line 15, in <module>
    print(np.dtype("Float16"))
TypeError: data type 'Float16' not understood
```

**Comment by jbrockmendel** [comment] 2021-12-04 03:21
Thanks for giving that a try.  Maybe it's more specific than `locale.getlocale()[0] != "en_US"`?  I think the pertinent build specifically has "zh_CN".

**Comment by seberg** [comment] 2021-12-05 03:23
It seems all pretty strange, I tried running NumPy with env-variables `LANG=zh_TW.UTF-8 LC_CTYPE="zh_TW.UTF-8" LC_ALL="zh_TW.UTF-8"  (I installed the locale) and can't repro.

Is there any chance a 3rd party is adding it to `np. sctypeDict`?  We even have a test that this fails, but not sure anyone would run the tests on a weirder setup...

**Comment by jbrockmendel** [comment] 2021-12-07 23:08
Looks like #16554 might be relevant.

> Is there any chance a 3rd party is adding it to np. sctypeDict? We even have a test that this fails, but not sure anyone would run the tests on a weirder setup...

Not that I'm aware of.

**Comment by seberg** [comment] 2021-12-07 23:09
Yeah, but that was in since 1.20 and I would have thought that the PR nuked any remaining bits of accepting `np.dtype("Float16")`, unless you are running into this on a <1.20?

**Comment by jbrockmendel** [comment] 2021-12-08 00:29
> unless you are running into this on a <1.20?

 I think the affected build is using 1.19.5.

**Comment by seberg** [comment] 2021-12-08 05:31
OK, from the PR you linked, it sounds like you can live with this failing on old NumPy.  And there isn't really anything we can do anyway, so closing.

**Closed by seberg** 2021-12-08 05:31 UTC
Labels: 00 - Bug
