### ISSUE TITLE
`float64` does not respect `__rmul__()` protocol

### ISSUE THREAD

**Issue by ElieGouzien** [numpy/numpy#17650] opened 2020-10-27 12:14 UTC
`float64` does not respect `__rmul__()` protocol and does unexpected things instead.
I didn't test, but it might be similar for the other operators.

### Reproducing code example:

```python
import numpy as np
x = np.float64(2)
x * (1,)
```
raises a `TypeError` (expected),  while `__mul__((1,))` correctly returns `NotImplemented`.

--------------------------------------------------

```python
import numpy as np
class Test(tuple):
    def __rmul__(self, other):
        return None
x = np.float64(2)
x * Test((1,))
```
returns `array([2])`, what is not correct (`None` is the expected result).
On the contrary, `2 * Test((1,))` correctly returns `None`.

### NumPy/Python version information:

python: 3.8.2
numpy: 1.19.2

**Comment by BvB93** [comment] 2020-10-27 20:32
On both windows and mac identical results are observed for all `np.number` subclasses, with the exception of `np.longdouble` and `np.clongdouble` for some reason. (The example below is from windows) 

``` python
In [1]: import numpy as np

In [2]: class Test(tuple):
   ...:     def __rmul__(self, other):
   ...:         return None

In [3]: number_types = [t for t in np.ScalarType if issubclass(t, np.number)]
   ...: number_types.sort(key=lambda t: t.__name__)

In [4]: for typ in number_types:
   ...:     out = typ(1) * Test((1,))
   ...:     print(f"{typ}: {out!r}")
   ...:
<class 'numpy.clongdouble'>: None
<class 'numpy.complex128'>: array([1.+0.j])
<class 'numpy.complex64'>: array([1.+0.j])
<class 'numpy.float16'>: array([1.])
<class 'numpy.float32'>: array([1.])
<class 'numpy.float64'>: array([1.])
<class 'numpy.int16'>: array([1])
<class 'numpy.int32'>: array([1])
<class 'numpy.int64'>: array([1])
<class 'numpy.int8'>: array([1])
<class 'numpy.intc'>: array([1])
<class 'numpy.longdouble'>: None
<class 'numpy.timedelta64'>: array([1], dtype=timedelta64)
<class 'numpy.uint16'>: array([1])
<class 'numpy.uint32'>: array([1])
<class 'numpy.uint64'>: array([1])
<class 'numpy.uint8'>: array([1])
<class 'numpy.uintc'>: array([1])
```

**Comment by seberg** [comment] 2020-10-27 20:36
There is a lot of weirder things going on here, but overall numpy scalars are agressive at converting the other side into an array using `np.asarray(...)`.  The way to avoid this to use:
```
class Test(tuple):
    __array_ufunc__ = None
    def __rmul__(self, other):
        return None
```

**Comment by seberg** [comment] 2024-07-10 15:44
Closing this, as explained it's by design (for better or worse) for the moment.  `__array_ufunc__` or `__array_priority` can be used to inform NumPy to stop doing it.

**Closed by seberg** 2024-07-10 15:44 UTC
