### ISSUE TITLE
ENH: A `scale` kwarg to  `np.sinc` to chose between pi and 1 may be useful

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#13457] opened 2019-05-02 21:24 UTC
There are [two common ways to define the sinc function](https://en.wikipedia.org/wiki/Sinc_function) numpy uses the one more common in digital signal processing and information theory, but less used in other sciences.

There was a PR in gh-7322 which however ended in a discussion of how to best solve this. Since the PR was inactive, and did not use the method that the discussion seemed to converge on, closing the PR (and opening this issue instead).

The PR gh-7322, and especially the discussion will, however, be very valueable if anyone decides to push this.

TODO:
 * The main task when picking this up, is to see what was previously discussed happen and likely involve the mailing. The decision of what to do (and possibly how to do it) is more involved than the change.

**Comment by seberg** [comment] 2019-05-02 21:30
The decisions needed here would be:

* Using `sinc_pi` as an alternative spelling to a kwarg.
* Whether we may think about waiting for ufunc support for kwarg (does not seem too relevant frankly, the function is currently not a ufunc, so unless we want to make it one soon the kwarg is not a burden)

**Comment by mattip** [comment] 2020-02-12 19:37
After discussion, we decided to close this. If someone has a use case for a `pi`-less `sinc` they should propose this again. The problem is that the names are already taken by the wrong interpretaion. We should have `sinc` and `sinc_pi`, but to be backward compatible we would have to do `sinc` and `sinc_no_pi` which is just wrong.

**Closed by mattip** 2020-02-12 19:37 UTC
Labels: 01 - Enhancement, 54 - Needs decision, component: numpy.lib

**Comment by dustiestgolf** [comment] 2020-05-29 23:14
Hi, I think that the default behaviour of the function `sinc` should be the one which does the least under the hood and I believe that the current implementation is misleading. This issue currently remains open elsewhere ([11004](https://github.com/numpy/numpy/issues/11004)).

NEP 23 is a good guide for deprecation policy but it is not yet complete. For example In the discussion about NEP 23 ([here](http://numpy-discussion.10968.n7.nabble.com/backwards-compatibility-and-deprecation-policy-NEP-tp45941p45948.html)) the actual procedure for breaking backwards compatibility is described differently from what is in the NEP as it stands. In particular for a bad default I think there is a compelling case to make an incompatible change using the more visible FutureWarning. It looks like there may be some changes this summer to NEP 23 and something like this should probably be brought up in [that discussion](https://github.com/numpy/numpy/issues/16193). 

Some reasons for breaking compatibility: 
- adding factors when you want them rather than removing them when you don't is a better pattern in general 
- consistency across the scipy ecosystem
  - [sympy](https://docs.sympy.org/latest/modules/functions/elementary.html?highlight=sinc#sinc) does not match numpy's approach 
  - [scipy](https://github.com/scipy/scipy/blob/5b256648e3b190f9f9b79ca33afba579e1d96d38/scipy/sparse/linalg/matfuncs.py#L730) requires more verbose documentation than is necessary. 
- as much as this may introduce bugs it may catch bugs in code where people assumed the simplest behaviour and never bothered to check the docs. 
- As mentioned above the current version is not the one most commonly used in most sciences. 
- Transitioning from other languages to numpy is made more difficult for example both [Matlab](https://www.mathworks.com/help/signal/ref/sinc.html) and [Mathematica](https://mathworld.wolfram.com/SincFunction.html) use the no-pi version.

I would like to see more discussion on this issue. Thanks!

**Comment by seberg** [comment] 2020-05-29 23:29
I agree that it is bit of a trap and I personally agree with the email that there are some cases where after careful consideration we should be open to some changes.
But *changing* behaviour from one default to the other in this way is potentially extremely disruptive and the potential of silently wrong results in old code resurrected after years, with almost no chance of noticing the change is real.
The only way to actually *change* behaviour, would be to create two new functions IMO and remove this entirely. (And if several years from then someone thinks its a great idea to resurrect, *maybe*, but probably not.)

This is far more disruptive then other changes (e.g. the rcond) listed in that email, which may create rare issues if you try to reproduce old results, but is very unlikely to give you patently *wrong* results), or edge cases that hopefully would have stricken a user as strange when they wrote the code (and are *much* less pervasive due to hitting far fewer users).

There is one argument I can actually see for `sinc_pi` or a similar naming/function. For someone who is used to tab completion, they will notice the alternative giving them a heads-up.  For everyone else, I am good with adding `.. warning::` directive to the documentation or similar.

**Comment by dustiestgolf** [comment] 2020-05-30 05:20
I agree that this would be much more disruptive. As much as I would like to keep the name `sinc` for the function as I would like it to be implemented, you are correct. The potential fallout of the change is too great and much too quiet. The different implementations across scipy is unnerving to me but I would be loathe to push other packages toward normalized sinc as the default. 

You make a compelling case and I agree that even if we made two separate functions it is unlikely and dangerous for `sinc` to be resurrected at any point. I think your last paragraph is the direction I feel is best. I would suggest `sinc_norm` instead since it is more explicit than `sinc_pi`. 

I do think that having a true `sin(x)/x` function would be nice to have as an option, but it is only a factor of `pi` and if users are clued in by `sinc_norm` or `sinc_pi` its not that difficult (although it is unsightly) to unnormalize the inputs. I have no good ideas for naming the unnormalized `sinc` if we wanted to do this. In order of my preference these are the names for `sin(x)/x` that I think could work:
- `sinc_math`
  - this naming is explicit about which definition is being used
  - both new sinc's would show up in autocomplete popups
  - would fit nicely with `sinc_norm` if we went that direction
  - potentially confusing since the name makes it sound field specific
- `sa` or `samp`
  - Based on the Wikipedia article for [`sinc`](https://en.wikipedia.org/wiki/Sinc_function) that was linked above the unnormalized version is sometimes known as the sampling function `Sa(x)`
  - Based on the Wikipedia citation this name is in line with the communications convention which the current `sinc` also follows so there is some consistency there. 
  - would only require adding the sampling function without any need to modify `sinc` while sticking with a field's convention
  - I dont think its a good idea to choose a convention specific to a particular field here for the same reason I dont like doing it for sinc. 

(I was wrong about matlab's implementation they use the normalized sinc. I have struck that out in my previous post, sorry. not sure how I mixed that up.)

**Comment by rgommers** [comment] 2020-05-30 09:34
The docs for `sinc` have `pi`, but the normalization could be spelled out more clearly. I'll send a PR.

Please no new functions for something that's trivial to do as `sinc(x / np.pi)`.

**Comment by rgommers** [comment] 2020-05-30 09:43
Also, NumPy, SciPy and Matlab do the same thing. SymPy and Mathematica, which have a fairly different (and smaller) audience, make the opposite choice. So there's no reason to worry about consistency here - just documenting things clearly to minimize mistaken assumptions by users.

**Comment by dustiestgolf** [comment] 2020-06-02 13:19
That sounds good to me! Thanks for considering it and for the explanation about the different choices between numpy and sympy.
