### ISSUE TITLE
BUG: stop catching at least criticial errors in array comparisons

### ISSUE THREAD

**Issue by mahdibaghbanzadeh** [numpy/numpy#21222] opened 2022-03-19 20:30 UTC
### Describe the issue:

I'm trying to compare each row of a NumPy array with the whole NumPy array without using iteration.
```
>>> sample = np.array([[1,2,3],[4,5,6]])
>>> sample
array([[1, 2, 3],
       [4, 5, 6]])
```
First I reshape the 2D-array to a 3D-array:
```
>>> sample2=sample.reshape(sample.shape[0],1,sample.shape[1])
```
And then with the following line of code, I can compare the rows:
```
>>> sample2 == sample
array([[[ True,  True,  True],
        [False, False, False]],

        [[False, False, False],
        [ True,  True,  True]]])
```
...which is the result that I'm looking for.

But this does not work with large numpy arrays:
```
>>> sample3 = np.random.randint(low= 0, high = 2, size = 30000000).reshape(30000,1000)
>>> sample4 = sample3.reshape(sample3.shape[0],1,sample3.shape[1])
>>> sample4 == sample3  
<ipython-input-229-e1d55c6bb1ca>:1: DeprecationWarning: elementwise
comparison failed; this will raise an error in the future.
False
```
### Reproduce the code example:

```python
import numpy as np
sample3 = np.random.randint(low= 0, high = 2, size = 30000000).reshape(30000,1000)
sample4 = sample3.reshape(sample3.shape[0],1,sample3.shape[1])
sample4 == sample3
```

### Error message:

```shell
<ipython-input-229-e1d55c6bb1ca>:1: DeprecationWarning: elementwise
comparison failed; this will raise an error in the future.
False
```

### NumPy/Python version information:

1.19.5

**Comment by shriekdj** [comment] 2022-03-19 21:43
try this
```python3
import numpy as np
sample3 = np.random.randint(low= 0, high = 2, size = 30000000).reshape(30000,1000)
sample4 = sample3.reshape(sample3.shape[0],1,sample3.shape[1])
np.array_equal(sample3, sample4)
```

**Comment by mahdibaghbanzadeh** [comment] 2022-03-20 07:33
> 

the result is not what I expected...
I have provided an example though

**Comment by seberg** [comment] 2022-04-06 20:37
Sorry that you didn't get an answer earlier.  It seems to me that it works just fine, the problem is the "deprecation" here.  If that was gone (finalized), you would be getting a `MemoryError` instead.  The result array is simply too large:
```
MemoryError: Unable to allocate 838. GiB for an array with shape (30000, 30000, 1000) and data type bool
```

**Comment by seberg** [comment] 2022-04-06 20:39
Well, even if we don't finalize the deprecation though, we could probably stop catching `MemoryError` and possibly some others... Those are critical errors after all.

**Comment by seberg** [comment] 2022-12-07 22:48
The deprecation is finalized (for NumPy 1.25).  So closing the issue, although if anyone wants to be a bit better about memory errors for backporting, that would be fine.

**Closed by seberg** 2022-12-07 22:48 UTC
Labels: 00 - Bug
