### ISSUE TITLE
Can't install numpy in Python 3.8.0

### ISSUE THREAD

**Issue by NulAsh** [numpy/numpy#14726] opened 2019-10-16 13:11 UTC
After running `pip install numpy`, i see the following:
```
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/ac/36/325b27ef698684c38b1fe2e546e2e7ef9cecd7037bcdb35c87efec4356af/numpy-1.17.2.zip
Installing collected packages: numpy
    Running setup.py install for numpy ... done
ERROR: Could not install packages due to an EnvironmentError: [WinError 123] The filename, directory name, or volume label syntax is 
incorrect: '"c:'
```
Windows 7 x64,  Python 3.8.0, MS Visual Studio 2017.

**Comment by Harmon758** [comment] 2019-10-16 21:03
Duplicate of #11451

**Comment by rubitry** [comment] 2019-10-16 21:04
numpy just got released a week ago, and libraries like numpy are still working on it to support the installation. So it might take some time, try switching to 3.7.4 or prior version of python.

**Comment by Harmon758** [comment] 2019-10-16 21:09
For Python 3.8 wheels, see #14698. In the meantime, the workaround in #11451 still applies.

**Closed** 2019-10-17 17:43 UTC
