### ISSUE TITLE
Possible bug in np.min, np.max, np.ndarray.min, np.ndarray.max

### ISSUE THREAD

**Issue by MLobo1997** [numpy/numpy#15905] opened 2020-04-03 10:14 UTC
When using `np.min` or `np.max` by setting the value of `initial` to `np.inf` and `-np.inf`, respectively,  the output is not what was expected. Perhaps I'm missing something, sorry if this is not actually a bug.

### Reproducing code example:

```
In[44]: np.array([-10,20,30,-25]).min(initial=np.inf)
Out[44]: -9223372036854775808
In[45]: np.array([-10,20,30,-25]).min(initial=-np.inf)
Out[45]: -9223372036854775808
In[46]: np.array([-10,20,30,-25]).max(initial=np.inf)
Out[46]: 30
In[47]: np.array([-10,20,30,-25]).max(initial=-np.inf)
Out[47]: 30
In[48]: np.min([-10,20,30,-25], initial=np.inf)
Out[48]: -9223372036854775808
In[49]: np.min([-10,20,30,-25], initial=-np.inf)
Out[49]: -9223372036854775808
In[50]: np.max([-10,20,30,-25], initial=np.inf)
Out[50]: 30
In[51]: np.max([-10,20,30,-25], initial=-np.inf)
Out[51]: 30
```

### Numpy/Python version information:

1.18.1 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) 
[GCC 7.3.0]

**Comment by Dan-Patterson** [comment] 2020-04-03 19:33
np.array([-10.,20.,30.,-25.]).min(initial=np.inf)
-25.0
type(np.inf)  # float
When the array is initally constructed as float, it behaves properly

**Comment by anirudh2290** [comment] 2020-04-03 19:52
Looks like a bug to me, request maintainers to add labels "00 - Bug" , "component: numpy.core"

**Comment by mattip** [comment] 2020-04-04 18:08
I think the `initial` should error if the value is not representable as the `dtype` used for computation.

**Comment by ldrobner** [comment] 2020-04-06 23:01
is this still an issue? If so I would like to work on this problem

**Comment by seberg** [comment] 2020-04-06 23:22
Sure @ldrobner if the issue is not closed and has no PR linked already (and this one is not) you are very welcome to open a PR. mattip's last comment is the one we should implement.
Note that this code is within the C code and in that the ufunc/umath machinery, so you should bring some basic C-skills and not be scared to dig a bit (feel free to ask for help).

**Comment by ldrobner** [comment] 2020-04-06 23:34
I know a little C. Do you know exactly where I can find this code? I've been going through the code base for a little but it's pretty massive and I haven't been able to find it.

**Comment by seberg** [comment] 2020-04-06 23:52
This code is in `numpy/core/src/umath/`in the `reduction.c` and `ufunc_object.c`. The function `PyUFunc_ReduceWrapper` uses `identity` to assign with `PyArray_FillWithScalar`.
However, at that time it can also be an identity provided by NumPy itself, where we probably do not want to make much checks. It is called from `PyUFunc_Reduce` where `initial` is first parsed (and replaces the `identity` provided by NumPy internally when no `initial` is given.
We would probably have to add a check at that place. I am not quite sure how to do that best immediately, so will let you dig a bit. The problem is that the input is an arbitrary python object, so you may need to convert it first.

**Comment by ldrobner** [comment] 2020-04-06 23:57
I'll start looking at it and thinking about it. I'll come running for help before I start coding. Thanks

**Comment by seberg** [comment] 2022-11-19 10:37
I changed this and now it raises an error.  If you were to pass `np.float64(np.inf)` you would at the very least get an "invalid value" warning (not quite sure, didn't try).  So closing.

**Closed by seberg** 2022-11-19 10:37 UTC
Labels: 00 - Bug, component: numpy.core
