### ISSUE TITLE
DEP: consider Deprecating `arr.dtype = ...` attribute setting

### ISSUE THREAD

**Issue by abinramapuram** [numpy/numpy#14565] opened 2019-09-21 09:50 UTC
When I have used np.float16(20240) it gives converted value as 20240.0. But when used with an array as  array.dtype = np.float16, got the converted value for 20240 as 28.25.  What conversion is done there?

**Comment by charris** [comment] 2019-09-21 13:41
I can't reproduce this.
```
In [1]: array([20240]*3, dtype=float16)                                         
Out[1]: array([20240., 20240., 20240.], dtype=float16)
```
What version of NumPy are you using and where did you get it?

**Comment by seberg** [comment] 2019-09-21 18:22
He wrote `arr.dtype = np.float16`, that is something you should **never** do, use `np.view` if you must. The correct thing to do is to use `arr.astype(np.float16)`. I am surprised we never deprecated it though, heh.

**Comment by seberg** [comment] 2019-09-21 19:52
Hmmm, recarrays use it during finalization. Which is not totally crazy, I guess.

**Comment by seberg** [comment] 2019-09-21 20:06
Maybe the best solution would be to hide a `change_dtype_inplace` function away in some dark corner, its pretty popular in `scipy.sparse`, but at least for scipy does not seem too bad if we were to deprecate it.

**Comment by abinramapuram** [comment] 2019-09-24 06:22
> He wrote `arr.dtype = np.float16`, that is something you should **never** do, use `np.view` if you must. The correct thing to do is to use `arr.astype(np.float16)`. I am surprised we never deprecated it though, heh.

Okeyy.. And I wish to know about that conversion. How the value 20240 is converted as 28.25 when use dtype=np.float16?? What calculation done there??

**Comment by mattip** [comment] 2019-09-24 06:31
The array holds a chunk of bytes, the dtype tells numpy what those bytes mean. So the code
```
np.array([20240], dtype='int16').view('float16')
array([28.25], dtype=float16)
```
is equivalent to telling numpy: take the 16 bit integer 20240 and **cast it** to a 16-bit float using [IEEE 754 standard](https://en.wikipedia.org/wiki/Half-precision_floating-point_format)

**Comment by eric-wieser** [comment] 2019-09-24 08:16
The word "cast" is misleading here. The C cast in question is `*(uint16_t *)&float16_val`, which is very different from `(uint16_t)float16_val

**Comment by mattip** [comment] 2019-10-03 13:16
Closing. Please reopen if there is a real desire to deprecate assigning to `arr.dtype`, which could be done by making it a `@property` with a getter and no setter

**Closed by mattip** 2019-10-03 13:16 UTC
Labels: 07 - Deprecation, 15 - Discussion, component: numpy.core

**Comment by eric-wieser** [comment] 2019-10-03 17:35
IMO there is a real desire to eliminate all mutable container properties, since they make views harder to understand. Note that @seberg renamed the PR, suggesting he is likely also if this mindset.

**Comment by seberg** [comment] 2019-10-03 18:32
Yeah, of course I am of that opinion :). The main issue is that also some of our own subclasses use it during their `__array_finalize__`, where it actually makes a bit sense (and I am not 100% all of them can simply be replaced by returning a new view).
