### ISSUE TITLE
numpy strings use too much memory

### ISSUE THREAD

**Issue by ri938** [numpy/numpy#15347] opened 2020-01-18 18:39 UTC
We are trying to upgrade our company software to python3.  After completing this we realised all our services were using too much memory and the reason is that the numpy unicode arrays uses 4x as much memory as the python2 numpy strings.  This is because it uses 4 byte characters rather than 1 byte characters.

I know there is the bytestring np.bytes_ but it is not equivalent to a string and using this would require rewriting a substantial part of our codebase.  For example you would have to convert it to a string anytime you wanted to use the column for our purposes.  For example in order to check equality, to merge with other datasets etc.

Can you provide a way to have more memory efficient string arrays.  At the moment we are likely to revert our codebase to python2 again and this is the only reason.

**Comment by eric-wieser** [comment] 2020-01-18 18:47
This has been discussed before - we've talked about adding Unicode encodings other than utf32, but the infrastructure to do that is still quite a way off.

> For example in order to check equality

In this case, you can use `my_bytes_arr ==  my_str_scalar.encode('utf8')`.

**Comment by eric-wieser** [comment] 2020-01-18 18:49
> I know there is the bytestring np.bytes_ but it is not equivalent to a string

It is exactly equivalent to what python2 called a string.

**Comment by ri938** [comment] 2020-01-18 18:49
I know there is way to perform actions on bytestrings but 
1) we have large string arrays and to repeatedly translate strings to and from bytestrings is slow
2) it will require a large code rewrite to achieve this and so use lots of development time

**Comment by charris** [comment] 2020-01-18 18:50
Yep, NumPy uses utf-32 for unicode strings. That was to avoid problems in dealing with the different encodings. If Python 2 (ascii) was adequate before, may I suggest that you could use ordinary string arrays.
```
In [9]: a = np.array(["hi", "world"], dtype='S')                                

In [10]: a                                                                      
Out[10]: array([b'hi', b'world'], dtype='|S5')
```
The downside there is that the elements are interpreted as byte strings, but depending on your application that might be OK. Can you provide more details?

**Comment by ri938** [comment] 2020-01-18 18:51
there is no avoiding having to translate the arrays into strings at times and this is slow
for example we want to put the arrays into pandas and then use that to merge on

**Comment by charris** [comment] 2020-01-18 18:52
So is the problem that pandas cannot use byte strings?

**Comment by ri938** [comment] 2020-01-18 18:53
well now bytestrings and strings cannot be merged without converting one to the other

**Comment by ri938** [comment] 2020-01-18 18:54
this is just an example to show that we will have to convert between the two numpy arrays regularly and its slow
Our tables of numpy arrays take about 1s to convert between bytestring and string columns when we have to do that

**Comment by eric-wieser** [comment] 2020-01-18 18:55
It sounds like in your python2 code, all your strings are already bytestrings. Have you considered just keeping them as bytestrings everywhere in python 3? That sounds less bad than being trapped in 2.

**Comment by ri938** [comment] 2020-01-18 18:57
I would have to look into this -- I will see how much of a rewrite this requires.  Thanks for the help.

**Comment by charris** [comment] 2020-01-18 18:58
I suspect that this may be a common problem for some applications that are just now making the move to Python 3, so we would be happy to implement a solution if we could figure out what that was. I'm going to reopen this so you can keep us updated and make suggestions.

**Comment by ri938** [comment] 2020-01-18 19:12
Here is roughly our use case for future reference:
* we have ordered dictionaries with numpy array values which we find is much more efficient than pandas in general (allthough we sometimes convert to a pandas array for some tasks like merging)
* a typical dictionary has values length 3 million and about 70 keys or which about 30  values are string numpy arrays
* to convert one of these numpy string arrays from string to bytestring or the reverse takes about 0.8s
* because we use so many strings the memory difference in python3 to use strings only is a lot

**Comment by charris** [comment] 2020-01-18 19:22
@ri938 

When do you need to make the conversions?

**Comment by ri938** [comment] 2020-01-18 23:28
We use the columns to generate features for machine learning which may apply functions on the string contents. 

We have decided to convert the subset of columns that is responsible for the high memory use to bytestrings. This is achieveable without a new dtype but with a bit of inconvenience.  However if many others also present the same problem it may be worth considering to add this.

**Comment by charris** [comment] 2020-01-19 00:07
Thanks for the update.  Bytestrings are definitely awkward, although the problem is somewhat less in recent Python releases. My thought was basically ascii with indexing that returned strings rather than bytestrings for the elements, so it would basically just be dtype `'S'` considered as a sort of encoding. But I don't know if that would help and that is the first thing to figure out.

**Comment by rkern** [comment] 2020-01-19 00:17
Consider using object arrays.

**Comment by ri938** [comment] 2020-01-19 00:32
Yeah ideal for us would be a dtype S which is just single byte encoding strings.  There seems to be a precendent for this already in numpy like there is float32 and float64 and different int sizes.  This would also make numpy backwards compatible with python2 and so anyone who wants to migrate can do so trivially. 

 Object arrays seem to use too much memory also.

**Comment by charris** [comment] 2020-01-19 00:55
We could call it `'SU'` ;) Just to demonstrate compression if storage size is the only problem
```
In [47]: a.dtype                                                                                                                        
Out[47]: dtype('<U2')

In [48]: a.nbytes                                                                                                                       
Out[48]: 800000

In [49]: p = blosc.compress(pickle5.dumps(a))                                                                                           

In [50]: len(p)                                                                                                                         
Out[50]: 3437

In [51]: pu = pickle5.loads(blosc.decompress(p))                                                                                        

In [52]: pu.nbytes                                                                                                                      
Out[52]: 800000
```
Of course,  that was just an array of 100,000 strings `'hi'`, so pretty good compression.

**Comment by charris** [comment] 2020-01-19 02:42
I think it would be pretty easy for someone familiar with numpy to make a subarray class for strings that did the indexing thing.

**Comment by ri938** [comment] 2020-01-20 11:20
Storage size in memory is the only problem with using unicode strings as they are.  We are thinking about using our own numpy arrays for strings which use same memory as bytestrings but behave as if they were just strings. This seems more sensible that converting our entire codebase to expect bytestrings.  This would be a subarray class as you mentioned.  We have used subarrays before, but could you summarise how you could get this to work for strings?

**Comment by eric-wieser** [comment] 2020-01-20 11:27
A quick terminology point - this is a subarray:
```python
a = np.zeros(1, dtype=[('b', (int, (2, 3, 4))])
b = a['b']   # b is a subarray dtype within a - because it has its own shape
```
and this is an array subclass:
```python
class MyArray(np.ndarray):
    pass
a = np.zeros(10).view(MyArray)
```

**Comment by eric-wieser** [comment] 2020-01-20 11:32
>  This seems more sensible that converting our entire codebase to expect bytestrings

Really, you should think about this as "not (yet) converting it to expect unicode". As I said in https://github.com/numpy/numpy/issues/15347#issuecomment-575928475, your entire python2 codebase already expects bytestrings - the trick is to convert it to python 3 without also converting it to expect unicode.

What fraction of your code interfaces with numpy arrays? Can you just `encode` to bytestrings when you start working with them, and `decode` when you're done?

**Comment by eric-wieser** [comment] 2020-01-20 11:43
> I think it would be pretty easy for someone familiar with numpy to make a subarray class for strings that did the indexing thing.

Perhaps:
```
class EncodedStringArray(np.ndarray):
    def __new__(cls, arr, encoding='utf8', errors='strict'):
        arr = np.asarray(arr)
        assert np.issubdtype(arr.dtype, np.str_)
        arr = np.vectorize(str.encode)(arr, encoding=encoding, errors=errors)
        self = arr.view(type=cls)
        self.encoding = encoding
        self.errors = errors
        return self

    def __getitem__(self, item):
        ret = ndarray.__getitem__(self, item)
        if isinstance(ret, bytes):
            ret = ret.decode(encoding=self.encoding, errors=self.errors)
        return ret

    def __setitem__(self, item):
        assert not isinstance(item, bytes)
        if isinstance(item, str):
            item = item.decode(encoding=self.encoding, errors=self.errors)
        return ndarray.__setitem__(self, item)

    def __array_finalize__(self, other):
        assert np.issubdtype(other.dtype, np.bytes_)
```

**Comment by ri938** [comment] 2020-01-20 14:34
This is great, thanks.  One problem I find is that I still have to make lots of changes to the code to make sure that I create Encoded arrays where possible always. I have lots of code that looks like "return np.array(mystrings)" which needs to be replaced with EncodedArray in order to stop memory shooting up.  We will likely have to have our own array class which behaves like numpy arrays most of the time except for when dealing with strings.

**Comment by eric-wieser** [comment] 2020-01-20 16:01
> I have lots of code that looks like "return np.array(mystrings)"

Is `mystrings` a list or another array?

**Comment by ri938** [comment] 2020-01-20 16:18
mixture of both

**Comment by eric-wieser** [comment] 2020-01-20 16:21
Using `np.asanyarray` will ensure that you don't downcast `EncodedStringArray` to a regular array.

**Comment by ri938** [comment] 2020-01-20 16:57
The issue is the lack of built in encoded string mainly. I can work around it not being default.

**Comment by ri938** [comment] 2020-01-22 15:02
I am experimenting with using the EncodedStringArray as above with some success so far.  A couple of issues I am having: 

I want to swap all the instances of string arrays with encoded arrays. I want some functions like np.in1d to work on an encoded array as if this was a string array.   But when I do
np.array(EncodedStringArray(list('abc'))) it will return an array of bytestrings not an array of strings.
Do you know how I can get a subclass to work in this way.

**Comment by eric-wieser** [comment] 2020-01-22 15:04
Use `np.asanyarray` everywhere you currently use `np.array` or `np.asanyarray`

**Comment by ri938** [comment] 2020-01-22 15:05
I cant because I use functions like np.in1d(my_encoded_array, ['test', 'check']) and these numpy functions themselves use np.asarray within them

**Comment by eric-wieser** [comment] 2020-01-22 15:21
That wasn't clear from your comment above. In that case, you might find you need to implement `__array_function__` for each function you need different behavior from. This isn't going to be easy, which is why subclasses are not a good solution for new data-types.

**Comment by charris** [comment] 2020-01-22 15:27
@eric-wieser Should we be changing some of those functions to use `asanyarray`?

@ri938 Might be useful to have a list of functions you find problematic.

**Comment by rkern** [comment] 2020-01-22 15:34
It's quite likely that we need to revisit the idea of one or more new encoded-string dtypes to solve this problem rather than an `ndarray` subtype. [The long and contentious previous discussion on the subject.](https://mail.python.org/pipermail/numpy-discussion/2017-April/076668.html) That effort stalled, but we did collect a number of concrete use cases to guide and constrain the design.

**Comment by ri938** [comment] 2020-01-22 15:36
array = EncodedStringArray(['test', 'check'])
so far I have ran into problems with:

1) np.array(array) : this will return a bytestring array when I really wanted it to convert to a string array
2) np.in1d  (uses asarray)
3) np.array_equal   (uses asarray)

**Comment by seberg** [comment] 2020-01-22 16:33
Having a string dtype with encoding seems good. The question is on which time frame we can add that though...

**Comment by ri938** [comment] 2020-01-23 11:45
I have managed to get something working with a custom class to replace all string numpy arrays we use in tables.  Its hacky but I want to show you just so you can see what my use case looks like. 

One problem I still have is that this currently doesn't allow unicode characters to be inserted. And using the np.vectorize method you gave in the above example is too slow -- it takes 4s to create an array rather than the 0.8s currently.  Most of the arrays I use do not contain unicode characters but a few rare ones do.  I would probably just have to insert a try-except.

```python
import numpy as np

HANDLED_FUNCTIONS = {}


class EncodedStringArray(np.ndarray):
    """Numpy array for holding strings as bytestrings. This trades
    lower memory use for occasional slower processing times and is to work around
    that python3 numpy strings using 4x as much memory as python2.

    See "numpy strings use too much memory #15347"
    """

    def __new__(cls, arr):
        arr = np.asarray(arr)
        if np.issubdtype(arr.dtype, np.str_):
            arr = arr.astype(np.bytes_)
        elif arr.dtype.type is not np.bytes_:
            raise TypeError('expected string values')
        self = arr.view(cls)
        return self

    def astype(self, dtype, *args, **kwargs):
        new = super(EncodedStringArray, self).astype(dtype, *args, **kwargs)
        if new.dtype.type is not np.bytes_:
            new = np.array(new)
        if new.dtype.type is np.object_:
            new = new.astype(str).astype(object)
        return new

    def argsort(self, *args, **kwargs):
        # this was returning an EncodedStringArray but with integer types and then crashing python when I tried to use it in the code so I jus override it
        indexes = super(EncodedStringArray, self).argsort(*args, **kwargs)
        assert indexes.dtype.type is np.int64
        return np.array(indexes, dtype=np.int64)

    def __getitem__(self, item):
        ret = np.ndarray.__getitem__(self, item)
        if isinstance(ret, bytes):
            ret = ret.decode(encoding='utf8', errors='strict')
        return ret

    def __setitem__(self, key, value):
        if not isinstance(value, bytes):
            value = np.bytes_(value)
        return np.ndarray.__setitem__(self, key, value)

    def __array_finalize__(self, other):
        assert other.dtype.type is np.bytes_

    def _format_comparison_input(self, obj):
        if isinstance(obj, str):
            obj = np.bytes_(obj)
        elif isinstance(obj, np.ndarray) and obj.dtype.type in [np.str_, np.object_]:
            # potentially slow conversion
            obj = obj.astype(np.bytes_)
        elif isinstance(obj, list):
            obj = np.array(obj, dtype=np.bytes_)
        return obj

    def __eq__(self, obj):
        obj = self._format_comparison_input(obj)
        return np.ndarray.__eq__(self, obj)

    def __ne__(self, obj):
        obj = self._format_comparison_input(obj)
        return np.ndarray.__ne__(self, obj)

    def __gt__(self, obj):
        obj = self._format_comparison_input(obj)
        return np.ndarray.__gt__(self, obj)

    def __lt__(self, obj):
        obj = self._format_comparison_input(obj)
        return np.ndarray.__lt__(self, obj)

    def __ge__(self, obj):
        obj = self._format_comparison_input(obj)
        return np.ndarray.__ge__(self, obj)

    def __le__(self, obj):
        obj = self._format_comparison_input(obj)
        return np.ndarray.__le__(self, obj)

    def __array_function__(self, func, types, args, kwargs):
        if func in HANDLED_FUNCTIONS:
            res = HANDLED_FUNCTIONS[func](*args, **kwargs)
        else:
            res = super(EncodedStringArray, self).__array_function__(func, types, args, kwargs)
        return res


def implements(numpy_function):
    """Register an __array_function__ implementation for EncodedStringArray objects."""
    def decorator(func):
        HANDLED_FUNCTIONS[numpy_function] = func
        return func
    return decorator


@implements(np.in1d)
def in1d(ar1, ar2):
    ar2 = np.asarray(ar2, dtype=np.bytes_)
    return np.in1d(np.array(ar1, dtype=np.bytes_), ar2)


@implements(np.array_equal)
def array_equal(ar1, ar2):
    ar2 = np.asarray(ar2, dtype=np.bytes_)
    return np.array_equal(np.array(ar1, dtype=np.bytes_), ar2)```

**Comment by charris** [comment] 2020-01-29 04:03
Just curious how things are going.

**Comment by ri938** [comment] 2020-01-29 08:58
I consider this complete for us although of all the parts of upgrading to python3 this was the main source of pain and took maybe as long as updating everything else.  What I did was:
1) wrote a numpy array like the one I posted above which uses bytes but behaves as if it contains strings.
2) I modified our table class which stores this arrays to always make sure strings are as encoded strings.  This meant I didnt have to change any code except the table and everything in code base could benefit.
3) fix a couple of issues in the codebase that I could not resolve: for example np.vectorise was acting on this array as if it was bytestrings and so I have to just avoid using that. 
So I do not require any further help and thanks for the help given.

**Comment by seberg** [comment] 2021-11-06 00:22
While I would love to see encoded strings,  we can't change NumPy Unicodes and at least right now encoded strings are even mentioned on the "roadmap".  (Although, I would prefer if someone would try to start outside of NumPy for now, since the experimental support should be pretty close to useful now)

In any case, going to close this, since I don't think it is a real TODO item.

**Closed by seberg** 2021-11-06 00:22 UTC
Labels: 15 - Discussion, component: numpy.dtype
