### ISSUE TITLE
BUG?: `numpy.vectorize` triggers computation on dask arguments

### ISSUE THREAD

**Issue by magonser** [numpy/numpy#10567] opened 2018-02-10 13:20 UTC
`dask.array.Array` implements `__array_ufunc__` to make calls of ufuncs with dask arguments lazy. However current implementation of `numpy.vectorize` triggers computation of dask inputs during broadcasting stage. 

Example:
```python
a = da.ones((10,), chunks=2)

def pyfunc(x):
    return x

ufunc = np.vectorize(pyfunc)

b = ufunc(a)
# Out: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
# Expected: another dask array, which is not yet computed
```

**Comment by hpaulj** [comment] 2018-02-12 00:00
`vectorize` with just one argument just iterates over the (scalar) elements, passing each to your function.  The return `dtype` is determined by a test calculation on the first element.  For more control use `otypes` and `signature`  But I doubt if those change the handling of a `dask.array`.  I'm not familiar with `dask`, and neither is `vectorize`.

**Comment by jakirkham** [comment] 2018-02-19 00:47
This may be a duplicate of issue ( https://github.com/numpy/numpy/issues/10155 ).

**Comment by shoyer** [comment] 2018-02-19 01:12
Let's keep discussion over in #10155.

**Closed by shoyer** 2018-02-19 01:12 UTC
