### ISSUE TITLE
BUG: numpy.arange may include stop for some small inputs

### ISSUE THREAD

**Issue by ziyuang** [numpy/numpy#24301] opened 2023-07-31 12:42 UTC
### Describe the issue:

The array created from `numpy.arange(start, stop, step)` should not include `stop`, but it may for some small inputs.,

### Reproduce the code example:

```python
import numpy as np

print(np.arange(0.0, 60e-6, 1e-6))
```

### Error message:

```shell
# Output
[0.0e+00 1.0e-06 2.0e-06 3.0e-06 4.0e-06 5.0e-06 6.0e-06 7.0e-06 8.0e-06
 9.0e-06 1.0e-05 1.1e-05 1.2e-05 1.3e-05 1.4e-05 1.5e-05 1.6e-05 1.7e-05
 1.8e-05 1.9e-05 2.0e-05 2.1e-05 2.2e-05 2.3e-05 2.4e-05 2.5e-05 2.6e-05
 2.7e-05 2.8e-05 2.9e-05 3.0e-05 3.1e-05 3.2e-05 3.3e-05 3.4e-05 3.5e-05
 3.6e-05 3.7e-05 3.8e-05 3.9e-05 4.0e-05 4.1e-05 4.2e-05 4.3e-05 4.4e-05
 4.5e-05 4.6e-05 4.7e-05 4.8e-05 4.9e-05 5.0e-05 5.1e-05 5.2e-05 5.3e-05
 5.4e-05 5.5e-05 5.6e-05 5.7e-05 5.8e-05 5.9e-05 6.0e-05]
```

### Runtime information:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
1.25.1
3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
>>> print(numpy.show_runtime())
[{'numpy_version': '1.25.1',
  'python': '3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) '
            '[GCC 12.2.0]',
  'uname': uname_result(system='Linux', node='ziyuan-XPS-15-9520', release='5.19.0-50-generic', version='#50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL',
                                    'AVX512_SPR']}},
 {'filepath': '/home/ziyuan/mambaforge/lib/libmkl_rt.so.2',
  'internal_api': 'mkl',
  'num_threads': 14,
  'prefix': 'libmkl_rt',
  'threading_layer': 'intel',
  'user_api': 'blas',
  'version': '2022.1-Product'},
 {'filepath': '/home/ziyuan/mambaforge/lib/libomp.so',
  'internal_api': 'openmp',
  'num_threads': 20,
  'prefix': 'libomp',
  'user_api': 'openmp',
  'version': None}]
None
```

### Context for the issue:

This is a floating-point arithmetic issue in general, but a rescaling inside numpy can get this around.

```
>>> print(np.arange(0.0, 60e-5, 1e-5)/10)
[0.0e+00 1.0e-06 2.0e-06 3.0e-06 4.0e-06 5.0e-06 6.0e-06 7.0e-06 8.0e-06
 9.0e-06 1.0e-05 1.1e-05 1.2e-05 1.3e-05 1.4e-05 1.5e-05 1.6e-05 1.7e-05
 1.8e-05 1.9e-05 2.0e-05 2.1e-05 2.2e-05 2.3e-05 2.4e-05 2.5e-05 2.6e-05
 2.7e-05 2.8e-05 2.9e-05 3.0e-05 3.1e-05 3.2e-05 3.3e-05 3.4e-05 3.5e-05
 3.6e-05 3.7e-05 3.8e-05 3.9e-05 4.0e-05 4.1e-05 4.2e-05 4.3e-05 4.4e-05
 4.5e-05 4.6e-05 4.7e-05 4.8e-05 4.9e-05 5.0e-05 5.1e-05 5.2e-05 5.3e-05
 5.4e-05 5.5e-05 5.6e-05 5.7e-05 5.8e-05 5.9e-05]
```

**Comment by mattip** [comment] 2023-07-31 13:18
Welcome to the wonderful wacky world of floating point math on computers. The arange documentation [warns about this](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange).

> When using a non-integer step, such as 0.1, it is often better to use [numpy.linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace)

and there is a more detailed description as well further down. 

Closing as a duplicate of #24246 and many others.

**Closed by mattip** 2023-07-31 13:18 UTC
Labels: 00 - Bug

**Comment by ziyuang** [comment] 2023-07-31 14:38
We need to calculate `num` correctly to make `linspace` behave as expected, where we will face the same issue. So `linspace` is not better. For example, `math.ceil(60e-6/1e-6)` gives `61` while we will expect `60`, the same number as `math.ceil(59.5e-6/1e-6)`.
