### ISSUE TITLE
intp on 32bit architectures not same as int32

### ISSUE THREAD

**Issue by iyer-arvind** [numpy/numpy#6038] opened 2015-07-03 09:50 UTC
np version 1.9.2 (but bug in previous versions as well)
python version 3.4.3 (but bug with previous versions as well)

The following demonstrates the problem: 
On 64Bit architecture: 

``` python
>>> import numpy as np
>>> np.intp
<class 'numpy.int64'>
>>> np.intp==np.int64
True
```

On 32Bit architecture:

``` python
>>> import numpy as np
>>> np.intp
<class 'numpy.int32'>
>>> np.intp==np.int32
False
```

**Comment by mattip** [comment] 2019-08-18 21:52
Still valid on latest HEAD

**Comment by eric-wieser** [comment] 2019-08-18 21:59
Relates to #10151

**Comment by seberg** [comment] 2019-08-19 13:09
Lets close this as a duplicate of that one, thanks all.

**Closed by seberg** 2019-08-19 13:09 UTC
