### ISSUE TITLE
How can I make sure svd having same result on different machine

### ISSUE THREAD

**Issue by penolove** [numpy/numpy#11500] opened 2018-07-04 16:31 UTC
I have 2 machines (i7-6700 4c8t, i5-7500(4c4t) )
setting env varible with:
# both with numpy 1.14.5

export NUMEXPR_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
```
import numpy as np
from numpy import linalg
np.random.seed(5)
X = np.random.rand(4000, 4000) * 100000000
print(np.sum(X)) # 799968160548285.0
U, S, V = linalg.svd(X, full_matrices=False)
print(np.sum(U))
# i7 6700 - 63.92077245597571
# i5 7500 - 63.92077245597459 
```

there are slightly difference, but as my matrix get more sparse
the difference can up to -19 v.s -2.7
are there ways/ variable to set,  to repoduce result / reduce the difference?

dockerfile:
```
FROM ubuntu:16.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN apt-get update
RUN apt-get install -y software-properties-common vim
RUN apt-get install -y git

RUN apt-get update && \
    apt-get install -y git make build-essential libssl-dev libbz2-dev libreadline-dev libsqlite3-dev curl wget llvm libgraphviz-dev pkg-config&& \
    curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash

ENV PYENV_ROOT=/root/.pyenv
ENV PATH=${PYENV_ROOT}/bin:$PYENV_ROOT/shims:/usr/texbin:${PATH}

RUN echo 'eval "$(pyenv init -)"' >> /root/.bashrc

RUN pyenv install 3.6.5
```

**Comment by seberg** [comment] 2018-07-05 09:53
That sounds like a pretty impossible thing to do, though I guess you may find a lapack implementation that is pretty stable, but add different hardware, etc...
Modern linear algebra packages are expected to give slightly different results. The large results are probably due to a very ill conditioned problem (e.g. check also `np.linalg.cond(...)`, which is based on the SVD too).

There are reasons we have functions like `np.all_close` and especially for testing (linear algebra packages) approximate checks are always necessary.

I will close the issue, feel free to keep discussing, or if you think something else is going, please say so. Although typically numpy has little or no influence on linear algebra results.

**Closed by seberg** 2018-07-05 09:53 UTC

**Comment by matthew-brett** [comment] 2018-07-05 15:17
Just to add, if you're using OpenBLAS, maybe via the pip wheel, you can force the kernel that OpenBLAS uses, with environment variables, as in:

```
export OPENBLAS_CORETYPE=prescott
python my_test_script.py
```

Maybe the same kernel will generate the same results.  You can see which kernel OpenBLAS chose by default by setting:

```
export OPENBLAS_VERBOSE=2
```

**Comment by ianlini** [comment] 2018-07-06 12:49
Thanks, @matthew-brett!
I can reproduce the operations on different machines using the same `OPENBLAS_CORETYPE` and `OPENBLAS_NUM_THREADS`.
Reproducibility is really important in machine learning because we usually want to run the same code in a lot of machines, and check whether their results are the same. If their results are different, it's hard to figure out whether there is a bug when we deploy the code to another machine. A little difference in a part of the data may result in a big change in machine learning (e.g., 1% accuracy difference).

**Comment by pv** [comment] 2018-07-06 12:53
It's useful to be aware that bit-for-bit floating point reprodicibility
is often easier said than done (openblas settings will not always help
you):
https://software.intel.com/sites/default/files/managed/de/a1/FP_Consistency_091117.pdf
