### ISSUE TITLE
Array assignment is not parallelized

### ISSUE THREAD

**Issue by Mazay0** [numpy/numpy#10291] opened 2017-12-28 09:27 UTC
This loop is not parallel: 
https://github.com/numpy/numpy/blob/7bb2d5a8f0219aa5acb5fda05929f1a0745a1883/numpy/core/src/multiarray/array_assign_array.c#L94

It would be nice to parallelize it, because on multicore machines this code is a bottleneck for example in numpy.tensordot() function.

**Comment by seberg** [comment] 2017-12-28 15:15
Numpy does not parallelize anything (linear algebra is parallel due to the linear algebra package you use, and definetly worth it in many cases).
There might be optimization possible here (I am not even quite sure why tensordot would do explicit assignments or copies, unless it is because of how your code is written, such as overlap of the out argument, so maybe check your code?).

Not that anyone is likely to parallelize anything at all within numpy anytime soon, parallelizing an assignment should not be helpful at all. A single thread should be able to max out your memory bandwidth, if it does not max it out, threading will not help either, you would have to implement blocked iteration.

Frankly, I find it very likely that you are just seeing that matrix products are increadibly fast and get close to the copy itself. If it is much faster then the copy, it might be iteration order, or maybe the way the code is written unnecessary copy operations are necessary.

Or, numpy does unnecessary copy operations somewhere, that would be more interesting if true.

Feel free to keep discussing, but will close this in a bit, or we morph it into a different issue after figuring out what is slow. Parallelization should not be a solution, and right now I am not even quite convinced that there is anything slow at all, can you share your profiling results that comes to this conclusion?

**Comment by seberg** [comment] 2017-12-28 15:29
I might be completly wrong about my assessment, but please give a bit of info to convince me ;) and maybe an example of the code you are profiling.

**Comment by Mazay0** [comment] 2017-12-28 16:23
I completely understand, that this issue looks strange. So big thanks for resonable response.
 The problem arises when I use tensordot to contract 12th order tensor with another 6th order tensor (presented as ndarrays both). The  tensor sizes are equal 5 for each dimension,  so the whole size of the first one is about 8 GB (gigabytes).  To contract arrays tensordot () use general matrix multiplication function from BLAS and it works well (optimized and parallelized). But tensor contraction can be represented by matrix multiplication only when the last axes of the first tensor contracted with first axes of the second tensor. Shortly speaking tensordot needs specific order of axes, so on each tensordot () call both arrays are transposed and reshaped. And this transpose-reshape procedure is not parallelized. If you have a 64 cores computer, parallelized matrix multiplication works much faster than non-parallel preliminary reshaping, despite of large computational complexity. 

So I think that in modern world of many-core computers array assignment worth parallelizing.

**Comment by Mazay0** [comment] 2017-12-28 16:31
I don't have profiling results on hands right now, but when I attach to the process with gdb it almost always stops in the reshape function near the line referenced in initial post. I can try to fit tensor sizes to make convincing profiling results on a reasonable computing time, but it will take some time, because on my PC such a big tensor just do not fit in memory and the Big Server is not always available.

**Comment by seberg** [comment] 2017-12-28 17:51
Sorry, somewhat missed that obvious reshape....

So the problem is reshaping+transpose which makes sense since many reshapes cannot be done without copy. Also those are exactly the type of operations that might be slow since numpy has no blocked iteration (and for which it may be reasonable to implement something outside the typical iteration machinery).

If the reshape could be managed without copy that would be neat, but that probably depends too much on the input. I also dunno if the new path optimized einsum might also help you (though have my doubts).

It remains that I do not believe parallelization would help much or at all and that numpy will not do that in any case (it would have to be some larger new features, with being able to enable it or some such, since we believe it is bad syle for a low level lib to parallize implicitly).

**Comment by seberg** [comment] 2017-12-28 17:53
Well, einsum might be faster because of the slow reshape I guess, not because it is actually all that fast.

**Comment by seberg** [comment] 2017-12-28 18:30
OK, I think there could be an optimization hidden, you could try locally. Instead of reshaping, you could try to do:
```
at = np.empty(at_shape, order='F')
at.reshape(a.shape)[...] = a
```
since you know that the reshape will trigger a copy, changing the at array order not to be C could speed up things a lot (depending on input, likely close to what is possible). Now it might be to add logic like this somewhere, but not sure where.

**Comment by jzwinck** [comment] 2018-03-09 05:41
Numba makes it trivial to write a parallel copy (or assign) function:

    @numba.vectorize(['f4(f4)', 'f8(f8)'], target='parallel')
    def parallel_copy(array):
        return array

Then you can do:

    parallel_copy(a) # instead of a.copy() or np.copy(a)
    parallel_copy(a, out=b) # instead of b[:] = a.copy()

For an array of one million doubles, this is about twice as fast as `ndarray.copy()`.  For 10 million doubles it is about four times faster (on an x86-64 desktop with many cores).

It sure would be nice if NumPy could use multiple cores by default to get quick wins for large arrays.

**Comment by seberg** [comment] 2019-04-26 00:04
I think I will close this. We will not do parallelization. There may be other optimizations for the specific use case though (reading through my own comments, that is what I seemed to think).

**Closed by seberg** 2019-04-26 00:04 UTC
Labels: 57 - Close?
