### ISSUE TITLE
Inconsistent behavior in casting from float32 to uint8 depending on platform

### ISSUE THREAD

**Issue by ptrblck** [numpy/numpy#19881] opened 2021-09-16 09:33 UTC
The following code snippet:
```python
import numpy as np
print(np.array(-2, dtype=np.float32).astype(np.uint8))
```
returns different results on x86 and ARM:
```python
ARM:
> 0
x86:
> 254
```

The issue seems to be similar to https://github.com/numpy/numpy/issues/16073 and https://github.com/numpy/numpy/issues/2398.
My guess is that `char` might be used internally, which "has an implementation-defined choice of “signed char” or “unsigned char” as its underlying type" ([source](http://eel.is/c++draft/basic.types#basic.fundamental-7), [ARM reference](https://developer.arm.com/documentation/den0013/d/Porting/Miscellaneous-C-porting-issues/unsigned-char-and-signed-char)).

Using this assumption, I've rebuilt numpy using:
```
CFLAGS="-fsigned-char" python setup.py develop -vvv
```
but the behavior didn't change.

After discussing this issue with @t-vi I'm unsure, if this is expected (undefined) behavior or a bug, which could be fixed.

Numpy version:
```
1.22.0.dev0+1068.gdc7dafe70 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:29) 
[GCC 9.3.0]
```

**Comment by seberg** [comment] 2021-09-16 14:50
Float to int casts are undefined behaviour in C.  And NumPy currently inherits it being undefined.  Since it is undefined, it can depend a bit on how you do it or which system.

It would be nice to improve these, the one thing that is on my not-done list is checking for FPU errors which would at least give an "invalid value" warning here (assuming compilers get it right).  Duplicate of gh-14412.

**Comment by seberg** [comment] 2023-04-25 06:41
As said, this is expected.  We can have an issue about changing it (we probably do, but can expand). This isn't that, so closing.

**Closed by seberg** 2023-04-25 06:41 UTC
Labels: component: numpy.core
