### ISSUE TITLE
numpy.bincount and scipy.ndimage.sum are slow under Windows

### ISSUE THREAD

**Issue by MikhailRyazanov** [numpy/numpy#15513] opened 2020-02-05 02:23 UTC
The functions `numpy.bincount()` and `scipy.ndimage.sum()` in NumPy/SciPy running under Windows 10 (Numpy 1.18, SciPy 1.4, both installed through pip) are about twice slower than the same functions on the same machine running under Debian (NumPy 1.12, SciPy 0.18, both installed through apt).

### Reproducing code example:

```python
import numpy as np
from scipy.ndimage import sum as imsum
from time import time

N = 10000  # data dimensions
# pixel array for analysis
A = np.random.RandomState(0).rand(N, N)
# bin number for each pixel
x2 = np.arange(N)**2
r = np.sqrt(x2 + x2[:, None]).astype(int)
r[r >= N] = N

t0 = time()
b = np.bincount(r.reshape(-1), A.reshape(-1))
print('reshape:    ', time() - t0)

t0 = time()
b = np.bincount(r.flatten(), A.flatten())
print('flatten:    ', time() - t0)

t0 = time()
b = np.bincount(r.ravel(), A.ravel())
print('ravel:      ', time() - t0)

t0 = time()
b = imsum(A, r, range(N))
print('ndimage.sum:', time() - t0)
```

### Typical timings (on AMD Ryzen 3):

Under Windows:
```
reshape:     0.6197371482849121
flatten:     1.1199564933776855
ravel:       0.6599655151367188
ndimage.sum: 1.4999728202819824
```

Under Debian:
```
reshape:     0.338172912598
flatten:     0.606091022491
ravel:       0.338004112244
ndimage.sum: 0.812026977539
```

As can be seen, in all cases the Windows version is ~2 times slower. And, what is also strange, the dedicated `scipy.ndimage.sum()` function is always more than twice slower than its simulation through `numpy.bincount()` with weights.

For comparison, a straightforward C(++) [implementation](https://gist.github.com/MikhailRyazanov/9d01009e8b1843d1a062a8f704fa3435) does the job in 0.1–0.2 s under both systems (it is surely less flexible but pretty close to what `scipy.ndimage.sum()` should do).

### Numpy/Python version information:

More or less any versions (see above for the specifics).

**Comment by eric-wieser** [comment] 2020-02-05 02:59
The type of `int` varies by platform. Can you switch to `int64` or `intp`?

**Comment by charris** [comment] 2020-02-05 03:13
Doesn't surprise me. The wheels are not optimized for native hardware, Debian probably does that better, especially for AMD hardware like Rysen. Have you tried Windows versions from Anaconda? They might do better. Might be worth some experimentation to see what the cause is. For another example of extreme variations in timings, see #14177.

**Comment by MikhailRyazanov** [comment] 2020-02-05 03:27
@eric-wieser, thanks for advice! Here are the timings  with
`r = np.sqrt(x2 + x2[:, None]).astype(np.intp)`:
```
reshape:     0.31998443603515625
flatten:     0.8799750804901123
ravel:       0.33998537063598633
ndimage.sum: 10.639670372009277
```
`numpy.bincont()` looks good, but `scipy.ndimage.sum()` becomes _terribly slow_.

Timings with `np.int32` are the same as with `int`, and with `np.int64` are the same as with `np.intp` (I guess, this is what `int` and `intp` actually are).

Under Debian (on Intel i5, I can test AMD Ryzen 3 later) there is almost no difference for any integer types in all cases.

**Comment by MikhailRyazanov** [comment] 2020-02-05 03:40
@charris, matrix operations on that machine are actually slightly faster under Windows than under Debian (perhaps, the BLAS version is better). So it shouldn't be memory access or something very OS-specific. As I said, my dumb C++ code with just `-Ox -fp:fast` MSVC options (not hardware-specific, as I understand) is actually fast.

I can probably try Anaconda later, but it's sad to see this poor performance in the default PyPi build...

**Comment by eric-wieser** [comment] 2020-02-05 11:14
> (I guess, this is what `int` and `intp` actually are).

`int` is `int32` on windows but `int64` on debian, `np.intp` is `int64` on most platforms these days - so you'd expect a (possibly negligeable) change on one platform or the other depending on which type you pick.

**Comment by MikhailRyazanov** [comment] 2020-02-05 23:29
@charris,
> Have you tried Windows versions from Anaconda? They might do better.

It actually performs exactly the same as the PyPI version.
But Anaconda also installs a gigabyte of MKL stuff, which does _matrix multiplication more than twice slower_ than the default NumPy... So it looks like a really bad choice for modern AMD CPUs.

**Comment by MikhailRyazanov** [comment] 2020-02-06 00:00
@eric-wieser,

I've also run the tests with different integer types in Debian, and there apparently `np.intp = int`. Using `np.intc` does decrease the performance:
```
reshape:     0.513790845871
flatten:     0.712885141373
ravel:       0.516979932785
ndimage.sum: 1.15052890778
```
but not as much as under Windows. Especially for `scipy.ndimage.sum()`.

So it seems that using `np.intp` for `bincount()` avoids the slowdown, at least for the current implementation.
I've looked at the `bincount` code and suspect that the following code
https://github.com/numpy/datetime/blob/dd2fb142820467993b43b108e4b76d7b2bcfdfe5/numpy/lib/src/_compiled_base.c#L116
is responsible for the performance drop. As I understand, it creates a new array for indexing if the initial array is not of the `np.intp` type already (this is consistent with that
```
b = np.bincount(r.reshape(-1).astype(np.intp), A.reshape(-1))
```
gives the same timings). Is this conversion really necessary? I think, in the following C code any integer type can be used for indexing.

And the extremely poor performance of `scipy.ndimage.sum` with `np.intp` under Windows is still strange, since
```
b = imsum(A, r.astype(int), range(N))
```
is executed in 1.8 s instead of 10.6 s.

**Comment by rossbar** [comment] 2020-07-18 02:38
Is there any followup to this issue? The examples are a bit confusing because multiple operations are being combined (e.g. `reshape` + `bincount`, `flatten` + `bincount`, etc.). A better MRE (i.e. using `timeit` and testing *only* bincount in a reproducible way) might help chase down potential problems here.

**Comment by MikhailRyazanov** [comment] 2020-07-18 03:01
If the question was for me, then the main problem, as I have explained, is that while the `bincount` documentation says “`ints`” everywhere, in reality they must be `intp`s, and if `intp` ≠ `int`, as it happens under Windows, a significant performance degradation occurs due to the internal `intp` → `int` conversion. So I would strongly suggest to change `int` to `intp` in the `bincount` documentation or at least add a note with a reference to https://numpy.org/doc/stable/reference/arrays.indexing.html?highlight=intp#detailed-notes, because this is not something immediately obvious.

**Comment by seberg** [comment] 2024-07-11 09:33
Going to close this, the default int is now intp.  So the windows specific part of it is gone in NumPy 2.  (Which doesn't mean other paths couldn't be sped up in principle.)

**Closed by seberg** 2024-07-11 09:33 UTC
Labels: 33 - Question
