### ISSUE TITLE
Latest numpy + intel compilers and mkl

### ISSUE THREAD

**Issue by samtsevich** [numpy/numpy#10613] opened 2018-02-16 20:46 UTC
Got such kind of error on my mac:

```
>>> import numpy
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/multiarray.cpython-36m-darwin.so, 2): Symbol not found: _main
  Referenced from: /usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/multiarray.cpython-36m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/multiarray.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen(/usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/multiarray.cpython-36m-darwin.so, 2): Symbol not found: _main
  Referenced from: /usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/multiarray.cpython-36m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.6/site-packages/numpy-1.14.0rc1-py3.6-macosx-10.13-x86_64.egg/numpy/core/multiarray.cpython-36m-darwin.so
```

Any ideas how to solve it? 

Thanks

**Comment by charris** [comment] 2018-02-16 21:02
Not sure what the problem is. Did you compile NumPy yourself?

**Comment by samtsevich** [comment] 2018-02-16 21:04
Hey, charris,

Yes, I tried to compile it with MKL to increase the speed of my calculations. But it failed.

**Comment by hameerabbasi** [comment] 2018-02-20 09:27
I'm not entirely sure if this addresses the original issue, but is using Anaconda an option? It uses MKL by default.

**Comment by samtsevich** [comment] 2018-02-20 13:06
Of course, I can install an _intelpython_ package or _Anaconda_, but it will create an incompatibility of other packages for my project. That's why I tried to compile it myself. I thought that you can suggest me why it returns such error.
Anyway, I will appreciate if you can let me know what the problem is/can be.

thanks

**Comment by hameerabbasi** [comment] 2018-02-20 13:34
What compiler are you using?

**Comment by samtsevich** [comment] 2018-02-20 13:35
Intel C and Intel Fortran

**Comment by homocomputeris** [comment] 2018-02-23 00:11
Check out ArchLinux's [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-numpy-mkl) from AUR and see if you can repeat the procedure on your system.

**Comment by samtsevich** [comment] 2018-02-28 19:48
@homocomputeris 
Didn't get how it works and what a purpose of this code.
Give me please more comments about it.

**Comment by homocomputeris** [comment] 2018-03-01 16:40
Theoretically, the build options for MKL look like this:
`python3 setup.py config --compiler=intelem build_clib --compiler=intelem build_ext --compiler=intelem`

**Comment by samtsevich** [comment] 2018-03-01 19:00
@homocomputeris 
Yes, it is. But, build process finished without any errors.
That kind of error (see the first post here) **might** be solved somehow by adding an extra flag to C or Fortran compilers, but I am not sure.

**Comment by rgommers** [comment] 2018-04-29 05:06
This is likely due to some build config or distutils issue; setting `LD_LIBRARY_PATH` may solve it. See https://github.com/numpy/numpy/issues/8653#issuecomment-282796562 and https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl

**Comment by mattip** [comment] 2018-08-08 21:04
the loader cannot load a shared object since it exports the function `_main`, maybe need to set the equivalent of `-shared` flag somewhere. @samtsevich were you able to resolve this?

**Comment by RobinTournemenne** [comment] 2018-11-10 21:52
I have exactly the same problem. Any Idea? I also think a special flag could do the work...

**Comment by seberg** [comment] 2022-05-12 13:15
Closing this issue, since it is a build/installation issue that is 4 years old.  Just open a new issue if it still exists in some form.

**Closed by seberg** 2022-05-12 13:15 UTC
Labels: 32 - Installation
