### ISSUE TITLE
mailing list is down again, and has been for a bit...

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#6325] opened 2015-09-17 04:57 UTC
Feel silly filing a bug but I'm not sure who to even ping -- I have a vague memory that usually when this happens then usually Ralf pings somebody? Which is not very helpful right now :-) Maybe... @rkern knows to talk to? scipy-dev actually bounced email for me earlier today as an unknown address, so that's exciting too.

(In the longer run I'm starting to wonder if we should give up and move to @python.org like matplotlib and nipy both did recently -- back in July I talked to Chip Parker @ Enthought briefly when I had some problem and he got in touch with me about it, and when I asked him about the instability he assured me that it was going to be sorted out any time now, but I am losing faith...)

**Comment by juliantaylor** [comment] 2015-09-17 07:00
we should look for an alternative, having the mailing list go down every second week for a few days since more than 6 month now is ridicilous

**Comment by njsmith** [comment] 2015-09-17 07:33
python.org is probably the most obvious alternative? They provide mailman hosting for arbitrary python-related things on request. Better than google groups anyway...

**Comment by njsmith** [comment] 2015-09-17 07:53
(I mean, better on some metrics anyway. I guess google groups might be more friendly to some users who prefer the web-forum-like approach. Mostly I am peevish at them because they have my main email address blacklisted. (You can subscribe mail to a google group with a non-gmail email address... but only if google thinks you don't have a gmail address. If they know you have a gmail address, then you are forbidden to use anything except that gmail address as your primary identity.))

**Comment by matthew-brett** [comment] 2015-09-18 20:36
List appears to be down still.  Nothing since Monday on the archives : https://mail.scipy.org/pipermail/numpy-discussion/2015-September/thread.html

I am happy to contact the postmaster@python.org to ask to set up the new list.  I suggest `numpy-discussion@python.org`.  Any objections?  Who has administrative access to the current list?

**Comment by infowolfe** [comment] 2015-09-19 00:46
https://mail.scipy.org/pipermail/numpy-discussion/2015-September/073575.html

Sorry for the spam, when the migration took place earlier this week I function tested on a list with 2 subscribers (both within Enthought). Unbeknownst to me, someone 10+ years ago followed http://www.jamesh.id.au/articles/mailman-spamassassin/ which resulted in quite a few similar copies of the following in mailman's logfiles:
```
Sep 18 09:00:01 2015 (19661) scipy-organizers: <scrubbed> deleted after exhausting notices
    self._onefile(msg, msgdata)
  File "/usr/lib/mailman/Mailman/Queue/Runner.py", line 190, in _onefile
    keepqueued = self._dispose(mlist, msg, msgdata)
  File "/usr/lib/mailman/Mailman/Queue/IncomingRunner.py", line 130, in _dispose
    more = self._dopipeline(mlist, msg, msgdata, pipeline)
  File "/usr/lib/mailman/Mailman/Queue/IncomingRunner.py", line 150, in _dopipeline
    __import__(modname)
ImportError: No module named SpamAssassin
```

@juliantaylor: FYI, this most recent "ridiculous" downtime was us migrating mail.scipy.org off of an unstable and basically unmaintained/unmaintainable Fedora Core 3 vm hosted on Enthought's legacy T1 infrastructure to a maintainable CentOS 7 cloud instance hosted on Rackspace and owned by the community (Sheila Miguez / @codersquid is the primary account holder). As you can probably guess though, the heavy lifting in attempting to drag a loose collection of 10-year out of date software into the modern era was less than trivial. The last few downtimes were the source vm in question's host crashing during backup runs, as we preferred to have continuity and consistency with regard to the mailing lists, rather than starting from scratch (as you would if the lists moved to python.org). Sadly, we weren't omniscient and weren't able to see and correct each and every strange thing done by someone who's long moved on. I apologize sincerely for not catching all of them.

**Comment by njsmith** [comment] 2015-09-19 00:59
@infowolfe: OK, deep breath, can you fill us in on what the status is now?

* Is everything believed to be working now?
* Are there any further operational changes planned?
* Has all email sent since Monday disappeared into the ether and need to be resent?
* If we were to run into issues again, what's the procedure -- who do we talk to and what's the plan for maintaining things? (I'm sure @codersquid is great but most of us probably have no idea who this is...)
* What do you mean about "continuity and consistency" -- the preservation of the URLs for the pipermail html pages, or...?

**Comment by infowolfe** [comment] 2015-09-19 01:24
* The entire week's worth of *errored* emails were still stored (mailman does this in a 'shunt' queue), when I issued `/usr/lib/mailman/bin/unshunt` it opened the floodgates and all emails from Monday until $now were released for processing. Currently postfix is processing the stored backlog, which is why many subscribers will be getting quite a few thread replies all at once.
* I need to finish the [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) configuration on apache to get all web-related stuffs hosted on this machine speaking via https by default
* All email since Monday was retained and is being processed as we speak
* I'm not sure what the procedure will be moving forward, this is probably something that should be discussed and handled at a pay grade higher than my own. The motive for this migration was twofold: ease the maintenance burden, on me personally, but also moving forward for whoever the next "me" is; provide a more consistently stable platform for hosting SciPy related mailing lists and projects. I'm not sure if you've noticed, but we've been gradually turning over responsibility for SciPy projects related hosting to the community (www.scipy.org is on AWS, conference.scipy.org is on Rackspace, mail.scipy.org/wiki.scipy.org/projects.scipy.org is now on this new Rackspace instance), including giving a couple people access to the AWS Route53 provided by Enthought.
* There were 0 emails lost between turn-down of the previous system and turn-up of the current system. All archive emails are present and accounted for... had there not been that rather strange hiccup, I honestly doubt anybody would have noticed the migration. We've got every byte of data from the old VM on the new instance and probably 99% of the old stuff is configured, up to date and working on the new instance, despite a decade-long gap between source and destination. URLs weren't really a concern specifically -- the idea/plan/hope was that nobody'd notice that anything had changed behind the scenes (except perhaps noting that things didn't take quite as long to load).

**Comment by njsmith** [comment] 2015-09-19 17:12
@infowolfe: Thanks for the details, and it sounds like you're in a tough position -- thanks for your efforts.

> I'm not sure if you've noticed, but we've been gradually turning over responsibility for SciPy projects related hosting to the community (www.scipy.org is on AWS, conference.scipy.org is on Rackspace, mail.scipy.org/wiki.scipy.org/projects.scipy.org is now on this new Rackspace instance)

We haven't, because your posts in this thread are literally the first time that anyone has told us (most of us) anything at all about how this infrastructure works -- it's just been a total black box that we have no control or visibility over.

Honestly, it's still pretty obscure from where I sit. It doesn't matter to us so much which datacenter the servers live in -- mostly we want/need to know who is taking care of them. If this is beyond your "pay grade", then who should we be talking to?

**Comment by matthew-brett** [comment] 2015-09-19 17:38
Do I understand correctly - that one of the reasons for moving to the Rackspace machine was so that people in the numpy community can help maintain the server, if it runs into trouble?

**Comment by pv** [comment] 2015-09-19 18:11
That's the case at least with the current www.scipy.org / docs.scipy.org server (current list: me, ralf, david, julian, takluyver). The other servers are in enthough's hands (rkern has been the contact).

**Comment by matthew-brett** [comment] 2015-09-19 18:42
I guess most of us would prefer an option where we didn't have to help maintain the mailman server - making python.org a good alternative.

**Comment by pv** [comment] 2015-09-19 18:51
Well, I'm not volunteering for that either. But as I understand, enthought is promising do that.

**Comment by njsmith** [comment] 2015-09-21 05:12
It would still be good to hear directly from someone at Enthought what they are actually promising or not, and what the arrangements are (e.g. contact points)...

**Comment by dpinte** [comment] 2015-09-21 08:39
@njsmith thanks for asking. It is definitely important that expectations are set on who's responsible for what. The set of services hosted on the old scipy.org virtual machine were definitely left in an un-ideal state for more than some years. While Enthought is very happy to provide technical support and maintenance services, the community needs to steer, guide and and take the technical decisions needed if we want to see an improvement in the future. 

There is a need for the numpy/scipy community to have a vision of the infrastructure needed to support the projects (mailing lists, documentation servers, sub-project sites, etc.). I had some brief discussions with @rgommers last year about this but we never closed the loop on that. It is probably time to give another push to it. While we can surely see the different services continuing to be supported/maintained by Enthought and others, the ownership of the services running under the scipy.org domains need to be actively owned by the numpy/scipy community. We should probably start with a map of all the hosted services and for each of them have a clear process identified for the maintenance and support of it (in particular we need at least 3 point-of-contacts with access and understanding of service).

**Comment by charris** [comment] 2015-09-21 15:31
@infowolfe the planet scipy site has the wrong content: https://planet.scipy.org/. I don't know if that is related but suspect so.

**Comment by matthew-brett** [comment] 2015-09-22 00:53
I think it would be very little effort to move the website to github hosting, and we could move the mailing lists to Python.org.   We could move the wiki to the github wiki if we wanted to keep it.    That would reduce the maintenance burden on Enthought.

I guess we then have to move planet.scipy.org somewhere - what does that need to keep it running?

**Comment by njsmith** [comment] 2015-09-22 01:04
@dpinte: Thanks for the update. It does sound like the next step would be for someone -- and I guess in practice this would have to be someone at Enthought! -- to write down a list of what the actual current infrastructure is and send it to numpy-discussion and scipy-dev. I think the community would be glad to join in the discussion, but it's hard without the information being out there.

**Comment by dpinte** [comment] 2015-09-22 06:58
@njsmith Enthought can definitely provide a description of the infrastructure for the part Enthought currently maintains. There are other parts though that are completely left in the wild at the moment (one example is conference.scipy.org that I had to interact with some weeks ago. It is hosted at Rackspace but completely unmaintained and totally undocumented). I really think there is a need for the scipy community to get organized. What would you think of setting up a call with the different stakeholders? We need to solve a number of questions around the long term maintainability of the infrastructure, what services we want to support and not, what can be hosted on community infrastructure (like Python.org), etc.

**Comment by codersquid** [comment] 2015-09-22 16:31
@dpinte I would be happy to attend a meeting about this. I am the owner of the Rackspace account that is running some of the scipy sites. My goal with getting account from Rackspace is to provide a resource for open source open science projects to have access to simple infrastructure. I've given a lot of numfocus and scipy people access to it. We should have more documentation about it. I would also not mind turning ownership over to numfocus.

**Comment by njsmith** [comment] 2015-09-22 17:43
@dpinte: I thought conference.scipy.org was the website for a conference
owned and run (legally speaking) by Enthought? (I have no opinion on
whether this is good or bad.)
.
In any case, a call sounds like a good idea. Want to send a doodle or
whenisgood to numpy-discussion and scipy-dev?

@njsmith <https://github.com/njsmith> Enthought can definitely provide a
description of the infrastructure for the part Enthought currently
maintains. There are other parts though that are completely left in the
wild at the moment (one example is conference.scipy.org that I had to
interact with some weeks ago. It is hosted at Rackspace but completely
unmaintained and totally undocumented). I really think there is a need for
the scipy community to get organized. What would you think of setting up a
call with the different stakeholders? We need to solve a number of
questions around the long term maintainability of the infrastructure, what
services we want to support and not, what can be hosted on community
infrastructure (like Python.org), etc.

—
Reply to this email directly or view it on GitHub
<https://github.com/numpy/numpy/issues/6325#issuecomment-142197067>.

**Comment by njsmith** [comment] 2015-09-23 06:06
@infowolfe @dpinte: btw the scipy-dev mailing list appears to still be bouncing email, and wiki.scipy.org is down -- not sure if those are related to this or not.

**Comment by dpinte** [comment] 2015-09-24 18:41
@njsmith I'll send a doodle asap. 

About the status: the migration of the old scipy.org box was a really large project with a lot of hidden issues. @infowolfe is stabilizing the different services. This is will more likely take some more days then we will be a in a sweet environment!

**Comment by njsmith** [comment] 2015-10-04 07:27
@dpinte: ping :-).

Also, does anyone know who to talk to to set up a new mailing list? ("numpy-steering-council-private" or something like that)

**Comment by dpinte** [comment] 2015-10-05 09:49
@njsmith here is the doolde for the infrastructure call: http://doodle.com/poll/24dig3gdhxnk9qaw

For the new mailing list, I suspect the mailman service on scipy.org could host that. @infowolfe how are things running now? Can we add a new list?

**Comment by njsmith** [comment] 2015-10-05 23:36
@dpinte: FWIW I'd like to make the infrastructure call, but unfortunatley I can't make any of those times (I'm travelling Thursday, and before 10am California time is difficult for me).

**Comment by dpinte** [comment] 2015-10-06 08:06
@njsmith I'll try to propose some better time slots. I more than likely be in the US in the short term. That will help.

**Comment by njsmith** [comment] 2015-10-06 14:39
@dpinte: thanks! There are lots of contributors in Europe as well, so
morning US/evening Europe does seem to be the right strategy for these
things generally.

@infowolfe: any update on the new mailing list discussion?

**Comment by rgommers** [comment] 2015-10-09 02:31
+1 on evening in Europe - I can join any day except maybe Thu next week

**Comment by rgommers** [comment] 2015-12-01 21:10
All: @dpinte started an overview at https://github.com/scipy/scipy/wiki/Web-service-infrastructure. Please add the things you know about.

**Comment by shoyer** [comment] 2016-09-13 18:14
Just a heads up, it looks like the HTTPS certificate for scipy.org has expired. I get a security warning when I try to go to this page:
https://mail.scipy.org/pipermail/numpy-discussion

**Comment by rgommers** [comment] 2016-09-13 19:36
Thanks @shoyer. Christian, the new Enthought sysadmin, is already working on getting that resolved.

**Comment by shoyer** [comment] 2016-09-26 04:38
I think the mailing list may still be having issues, or at least the [archives](https://mail.scipy.org/pipermail/numpy-discussion/2016-September/thread.html) may not be being updated.

My most recent post has not gone through, and the archives show nothing since @dpinte's test message last week.

**Comment by dpinte** [comment] 2016-09-26 08:40
@shoyer I'll be happy to start investigating. It would be good to get more details than `has not gone through`. Any error messages?

**Comment by dpinte** [comment] 2016-09-26 08:45
I think we should seriously investigate migrating the mailing lists to a pro maillman hosting. The current setup is very complex and highly undocumented. There are services costing about $4 per month out there that we could migrate to.

**Comment by rgommers** [comment] 2016-09-26 08:55
> I'll be happy to start investigating. It would be good to get more details than has not gone through. Any error messages?

The whole thing has been down for 10 days, I thought you guys were still working on it. ``scipy-dev`` and ``scipy-user`` too, although exactly 2 messages came through on ``scipy-dev``.

    Delivery to the following recipient has been delayed:

         scipy-dev@scipy.org

    Message will be retried for 1 more day(s)

    Technical details of temporary failure:
    TLS Negotiation failed: generic::failed_precondition: starttls error (0): protocol error

> I think we should seriously investigate migrating the mailing lists to a pro maillman hosting. The current setup is very complex and highly undocumented. There are services costing about $4 per month out there that we could migrate to.

That would be great.

**Comment by dpinte** [comment] 2016-09-26 08:58
@rgommers thanks for the feedback. I have asked a quote to one of the providers.

Regarding the error it seems it is the same I had just after the SSL cert update. It is weird that some messages passed and some not. I'll pass the information to Christian for investigation. There is clearly something that needs to be taken care of related to the SSL cert change.

**Comment by dpinte** [comment] 2016-09-26 09:22
The issue has been isolated ... `qpsmtpd` configuration was pointing to a different SSL cert ... and thus the SSL connections to `mail.scipy.org:25` were failing (`openssl s_client -connect mail.scipy.org:25 -starttls smtp` to replicate). I have now updated the second cert file and connections pass.  I think the issue is now solved.

**Comment by shoyer** [comment] 2016-09-26 18:16
Glad to see things are working now! Gmail didn't give any error messages when my message didn't get through.

Paid mailman hosting sounds like a great idea, though I'd also be happy with a transition to python.org, especially if we could move over the archives.

**Comment by seberg** [comment] 2018-12-22 17:06
I am having problems with the mailing list right now, but I think this issue was about the old mail server before moving the list to python.org, so closing this.

**Closed by seberg** 2018-12-22 17:06 UTC
Labels: component: Other
