### ISSUE TITLE
BUG: Support for 'Y', years is missed out in timedelta64

### ISSUE THREAD

**Issue by tripti-nference** [numpy/numpy#26253] opened 2024-04-10 11:04 UTC
### Describe the issue:

Environment details
Python3.10
Numpy 1.26.4

Steps to reproduce:
> 1. import numpy as np
> 2. np.timedelta64(1, 'Y')

**Actual**: ValueError: Unit Y is not supported.Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'
**Expected**: It should support as my scripts using this methods were working in numpy **1.26.0** stable release.

### Reproduce the code example:

```python
import numpy as np
np.timedelta64(1, 'Y')
```

### Error message:

```shell
ValueError: Unit Y is not supported.Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'
```

### Python and NumPy Versions:

1.26.4
3.10.6 | packaged by conda-forge [GCC 10.4.0]

### Runtime Environment:

![Screenshot 2024-04-10 at 4 30 17 PM](https://github.com/numpy/numpy/assets/106962210/18f5391d-3b0e-4446-a681-8c2a3c0579ce)

### Context for the issue:

Project that I work on deals with very frequent usage of numpy datetime and timedelta as i work on events duration analysis and do many operations on datetime. In one place, I want to know number of years between events. for that, I am dividing time difference with np.timedelta64(1' 'Y') to get the result. But it fails in the dev release of numpy.

**Comment by eric-wieser** [comment] 2024-04-10 12:18
> Only unambiguous timedelta values durations are supported.

This is because the length of a year is ambiguous. A "month" unit is left out for the same reason.

**Comment by ngoldbaum** [comment] 2024-04-19 17:14
Closing since this is working as intended

**Closed by ngoldbaum** 2024-04-19 17:14 UTC
Labels: 33 - Question
