### ISSUE TITLE
Numpy implicitly converts integers to floats when initializing an array with uint64's

### ISSUE THREAD

**Issue by Guthman** [numpy/numpy#18724] opened 2021-04-03 23:56 UTC
### Reproducing code example:

```python
import numpy as np

integer_list = [18446744073709551615]
arr = np.array(integer_list)
arr.dtype

# Returns: dtype('uint64')

# So far, so good... But:

# Same list as above, with with a smaller number at the first index
integer_list = [
    9223372036854775807,
    18446744073709551615
]
arr = np.array(integer_list)
arr.dtype
# Returns: dtype('float64')
```

It looks like Numpy only looks at the first element in the object when deciding what dtype the array should have. I think (although I'm not sure) that this behaviour causes unpredictable behaviour in Pandas down the line.

```python
import pandas as pd

integer_list = [
    9223372036854775807,
    18446744073709551615
]

df = pd.DataFrame(integer_list)
df[0].dtype
# Returns: dtype('uint64')

df[0].to_numpy(int)
# Returns (on Windows*): array([-1, -1])
# Returns (on Debian): array([9223372036854775807, -1])
```

When using `to_numpy()`, Pandas calls `np.asarray()` under the hood and passes the values of the Series. So I don't think anything is wrong on the Pandas side. Numpy seems to get confused and makes some wrong decisions about the appropriate length and signedness of the integer it should use. 

### NumPy/Python version information:

**Windows**
Numpy version: 1.19.2 
Python version: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]

**Debian**
Numpy version: 1.20.2 3.7.3 
Python version: Python 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]

And, to maybe save someone some time:

On Windows, a c_long object is always 32 bit, regardless of the OS being 64 bit (as opposed to Unix). See: https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types

**Comment by mattip** [comment] 2021-04-04 05:58
I don't know what pandas is doing under the hood to the returned values from NumPy, but when I do `np.asarray(integer_list)`, I get a float array. What happens if you do `df[0].to_numpy(df[0].dtype)` instead?

**Comment by Guthman** [comment] 2021-04-04 09:36
That works as expected, creating an array with dtype `uint64`. Which confirms that the problem is caused by how Numpy decides which dtype to use when it isn't explicitly passed. Pandas isn't doing much under the hood, `to_numpy()` is defined as  

```python
    def to_numpy(self, dtype=None, copy=False, na_value=lib.no_default, **kwargs):
        if is_extension_array_dtype(self.dtype):
            # pandas\core\base.py:837: error: Too many arguments for "to_numpy"
            # of "ExtensionArray"  [call-arg]
            return self.array.to_numpy(  # type: ignore[call-arg]
                dtype, copy=copy, na_value=na_value, **kwargs
            )
        elif kwargs:
            bad_keys = list(kwargs.keys())[0]
            raise TypeError(
                f"to_numpy() got an unexpected keyword argument '{bad_keys}'"
            )

        result = np.asarray(self._values, dtype=dtype)
        # TODO(GH-24345): Avoid potential double copy
        if copy or na_value is not lib.no_default:
            result = result.copy()
            if na_value is not lib.no_default:
                result[self.isna()] = na_value
        return result

**Comment by seberg** [comment] 2021-04-05 17:54
Going to close this as a duplicate of gh-16287.  A combination of not always going to the default (signed) integer and weird promotion rules.
I am all in favor of only ever returning the defaul tinteger (although the fact that this is 32bit on 64bit windows is annoying there).  But, I am not sure how big a change it would be.  In any case, I think it probably would make sense to try and put a futurewarning on it...

**Closed by seberg** 2021-04-05 17:54 UTC
