### ISSUE TITLE
Numpy hangs forever when matching ufunc types for custom dtype

### ISSUE THREAD

**Issue by will133** [numpy/numpy#6762] opened 2015-12-03 17:38 UTC
I'm using python 2.7 on numpy 1.10.1 with a custom dtype implementation.  Essentially the self->userloops is defined with types that do not match the specified_types.  In such case numpy will hang indefinitely.

It seems like the function  type_tuple_userloop_type_resolver in numpy/numpy/core/src/umath/ufunc_type_resolution.c is incorrect.  It can get into an infinite loop  around line 1745, which looks like:

``` c
            while (funcdata != NULL) {
                int *types = funcdata->arg_types;
                int matched = 1;

                if (n_specified == nop) {
                    for (j = 0; j < nop; ++j) {
                        if (types[j] != specified_types[j] &&
                                    specified_types[j] != NPY_NOTYPE) {
                            matched = 0;
                            break;
                        }
                    }
                } else {
                    if (types[nin] != specified_types[0]) {
                        matched = 0;
                    }
                }
                if (!matched) {
                    continue;
                }

                switch (ufunc_loop_matches(self, op,
                            casting, casting,
                            any_object, use_min_scalar,
                            types, NULL,
                            &no_castable_output, &err_src_typecode,
                            &err_dst_typecode)) {
                    /* It works */
                    case 1:
                        set_ufunc_loop_data_types(self, op,
                            out_dtype, types, NULL);
                        return 1;
                    /* Didn't match */
                    case 0:
                        PyErr_Format(PyExc_TypeError,
                             "found a user loop for ufunc '%s' "
                             "matching the type-tuple, "
                             "but the inputs and/or outputs could not be "
                             "cast according to the casting rule",
                             self->name ? self->name : "(unknown)");
                        return -1;
                    /* Error */
                    case -1:
                        return -1;
                }

                funcdata = funcdata->next;
            }
```

I see that if matched = 0, then the loop does a "continue" without updating the funcdata.  Thus funcdata is never null and will run forever.

**Comment by seberg** [comment] 2019-05-14 04:38
The code above was fixed in 7844860e1b (and a duplicate of gh-9351).

**Closed by seberg** 2019-05-14 04:38 UTC
Labels: 00 - Bug, component: numpy.core, component: numpy.dtype
