### ISSUE TITLE
np.take does not accept slices as indeces.

### ISSUE THREAD

**Issue by petered** [numpy/numpy#9472] opened 2017-07-27 11:39 UTC
np.take should take slices too.

Example:

    a=np.arange(9).reshape(3,3)

I can do:

    >>> np.take(a, [0,2], axis=0)
    array([[0, 1, 2],
           [6, 7, 8]])

But not:

    np.take(a, slice(None, None, 2), axis=0)

Traceback (most recent call last):
 ....
TypeError: long() argument must be a string or a number, not 'slice'

**Comment by seberg** [comment] 2017-08-06 11:17
We could add it I guess, I am pretty ambivalent about it. Note you can easily write a similar function by doing:
```
def mytake(arr, index, axis=0):
    return arr[(None,)*axis + (index, Ellipsis)]
```
and be done with it. The thing is that take is implemented very different from indexing right now (it can be faster in some cases, you find a lot of "take is faster" out there, but in many of those that is not true anymore).

**Comment by seberg** [comment] 2024-01-28 14:03
Closing as duplicate of gh-8149

**Closed by seberg** 2024-01-28 14:03 UTC
