### ISSUE TITLE
Are any generalized ufuncs exposed directly by NumPy?

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#10692] opened 2018-03-05 01:05 UTC
I'm finally writing an `__array_ufunc__` implementation for xarray, and would love to be to test it by calling some real gufuncs on my objects.

Ideally, I would use a gufunc exposed by NumPy. But somewhat to my surprise, I can't find a NumPy gufunc suitable for testing. `numpy.linalg` uses gufuncs under the hood, but all of these gufunc seem to have wrappers that start by calling `np.asarray()`, which casts xarray objects to NumPy arrays first.

Does NumPy expose any ufuncs with a signature? Or am I going to need to mock one up?

**Comment by jaimefrio** [comment] 2018-03-05 06:23
There are a couple of simple ones in umath_tests, I think it's from
numpy.core.umath import umath_tests you'd want to check.

**Comment by shoyer** [comment] 2018-03-05 06:46
> There are a couple of simple ones in umath_tests, I think it's from
numpy.core.umath import umath_tests you'd want to check.

Thanks @jaimefrio. These are helpful (it's actually `from numpy.core import umath_tests`), but I wouldn't want to rely on an these for a test suite since they don't appear to be part of NumPy's public API.

**Comment by shoyer** [comment] 2018-03-05 18:03
For now I'm using mock: https://github.com/shoyer/xarray/blob/4e6ac28d5e330b201c520ed90d34466aab18990d/xarray/tests/test_ufuncs.py#L170-L174

But yes, we really should expose some gufuncs! :)

I do wonder if we really need all the Python logic around the `numpy.linalg` gufuncs, e.g., as seen for `numpy.linalg.det`:
https://github.com/numpy/numpy/blob/v1.14.0/numpy/linalg/linalg.py#L1869-L1876

**Comment by mhvk** [comment] 2018-03-05 18:40
I agree. I think @eric-wieser mostly wanted to be absolutely sure that, for now, there would be no regressions in `linalg` because of casting etc. I'm not sure what the further plans are, but ideally some of the `gufuncs` get exposed so they can be used without the overhead.

**Comment by mattip** [comment] 2019-01-09 19:44
matmul is a gufunc that is exported. Can we close this?

**Comment by mhvk** [comment] 2019-01-09 21:34
Yes!

**Closed by mhvk** 2019-01-09 21:34 UTC
