### ISSUE TITLE
BUG: type checking broken with np.sinc

### ISSUE THREAD

**Issue by bmerry** [numpy/numpy#21898] opened 2022-07-01 12:57 UTC
### Describe the issue:

There seems to be something whacky with the type annotations for np.sinc that causes mypy to later think that an array is a boolean array when clearly it is not. See the reproducing code below. This seems to have started with numpy 1.22 (presumably due to the more accuracy dtype annotations). Changing `np.sinc` to `np.sin` or `np.exp` makes the problem disappear, which is why I assume it is specific to `sinc`.

### Reproduce the code example:

```python
import numpy as np

def what_the() -> None:
    idx = np.arange(16, dtype=float)
    c = idx * np.sinc(idx)
    c /= np.sum(c)
```

### Error message:

```shell
Error message from mypy 0.961:


show_type.py:6: error: Invalid self argument "ndarray[Any, dtype[bool_]]" to attribute function "__itruediv__" with type "Callable[[ndarray[Any, dtype[floating[_NBit1]]], Union[_SupportsArray[dtype[Union[bool_, integer[Any], floating[Any]]]], _NestedSequence[_SupportsArray[dtype[Union[bool_, integer[Any], floating[Any]]]]], bool, int, float, _NestedSequence[Union[bool, int, float]]]], ndarray[Any, dtype[floating[_NBit1]]]]"
```

Note the `bool_` on the first line.
```


### NumPy/Python version information:

1.23.0 3.10.5 (main, Jun 11 2022, 16:53:24) [GCC 9.4.0]

**Comment by BvB93** [comment] 2022-07-01 13:02
This seems to be the same issue as https://github.com/numpy/numpy/issues/20099, which in turn is causes by a mypy bug (https://github.com/python/mypy/issues/11347). A pr was created for the issue upstream, but I've yet to see it merged.

**Comment by BvB93** [comment] 2022-07-01 13:41
> This also seems to be partly caused by `dtype=float` not being treated the same as `dtype=np.float64`; if I use the latter then the problem disappears. That sounds like a separate issue though.

Yeah, https://github.com/numpy/numpy/issues/19252 goes into it it more details, but the gist of the problem is that there is no convenient way of mapping `float` to a `np.float64` (or a `np.generic` subtype in general) with the currently available typing tools...

**Closed** 2022-07-01 13:41 UTC
Labels: 00 - Bug, 50 - Duplicate, Static typing

**Comment by bmerry** [comment] 2022-07-01 13:45
> Yeah, https://github.com/numpy/numpy/issues/19252 goes into it it more details, but the gist of the problem is that there is no convenient way of mapping float to a np.float64 (or a np.generic subtype in general) with the currently available typing tools...

Ah, I might have been too quick to open #21900 then. Feel free to close it as duplicate.
