### ISSUE TITLE
asarray/array problem with list appended with itself more than once.

### ISSUE THREAD

**Issue by mshemuni** [numpy/numpy#15081] opened 2019-12-10 06:04 UTC
Numpy tried to convert an infinite list to numpy.ndarray and I never stopped.
This problem occurs when an array appended with itself more than once.

### Example:

```python
from numpy import asarray as ar
#from numpy import array as ar
a = []
#Range must be more than 1.
for i in range(2):
    a.append(a)

#This line does not stop.
print(ar(a))
```

### Numpy/Python version information:
np.__version__: 1.16.5
Python: 3.7.4

**Comment by eric-wieser** [comment] 2019-12-10 06:47
Duplicate of 7901, which is a another report regarding self-containing / self-referential arrays.

Numpy does not treat this as infinite, but treats it as having shape `(2,)*32`, which means it iterates for a very long time

**Closed by eric-wieser** 2019-12-10 06:47 UTC
