### ISSUE TITLE
BUG: AttributeError: module 'numpy' has no attribute '_SupportsBuffer'

### ISSUE THREAD

**Issue by glopesdev** [numpy/numpy#27654] opened 2024-10-28 14:16 UTC
### Describe the issue:

Trying to use `_SupportsBuffer` for type hinting results in the following cryptic error message: `AttributeError: module 'numpy' has no attribute '_SupportsBuffer'`.

This is strange since hinting succeeds seamlessly in Pylance, but on closer inspection one can realize that `_SupportsBuffer` is defined in a **`__init__.pyi`** stub instead of a regular **`.py`** file.

I'm quite new to type hinting so these kind of subtleties are completely lost on me. Searching the internet has come up empty and no idea of quite where to start working around this.

### Reproduce the code example:

```python
import numpy as np

def read(buffer: np._SupportsBuffer):
    return np.frombuffer(buffer)
```

### Error message:

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\gonca\Projects\github\harp-tech\harp-python\example.py", line 3, in <module>
    def read(buffer: np._SupportsBuffer):
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\gonca\Projects\github\harp-tech\harp-python\.venv\Lib\site-packages\numpy\__init__.py", line 428, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute '_SupportsBuffer'
```

### Python and NumPy Versions:

2.1.2
3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

### Context for the issue:

Sadly this single type hinting failure is compromising the typing of an entire API since it affects a single function at the very bottom of the stack. At least documenting a workaround or reason for the issue would be extremely valuable.

**Comment by jakevdp** [comment] 2024-10-28 16:21
I think this is working as intended: `_SupportsBuffer` is not meant to be a public API available in the `numpy` namespace.

**Comment by jorenham** [comment] 2024-10-28 21:32
The `_SupportsBuffer` protocol (or type-alias) isn't part of the public api (the leading `_` is an indicator of that), and exists only when type checking. 
But even so, due to the lack of `__all__` in `numpy<2.2.0`, IDE's could have suggested otherwise, e.g. by having it show up as an autocomplete.

In the upcoming NumPy 2.2 release, the global `numpy` namespace will have an explicit `__all__`  in the typing sutbs, and `_supportsBuffer` will be marked as `@typing.type_check_only`. This means that you IDE won't suggest it as if it were part of the public API.

@jakevdp's suggestion about about `Buffer` is indeed the correct way to handle this.

**Comment by glopesdev** [comment] 2024-10-29 10:06
@jakevdp @jorenham thank you for taking the time to clarify this, I now understand what is happening much better.

I do require compatibility with earlier versions. The suggestion to use `Buffer` from `typing_extensions` is a good one for getting the code to run, but unfortunately for some reason it doesn't allow Pylance to be happy about type inference on my own calls to `np.frombuffer`, I'm assuming since `numpy` itself does not use it since I am on Python < 3.12 (see stack trace below):

```
No overloads for "frombuffer" match the provided argumentsPylance[reportCallIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportCallIssue)
multiarray.pyi(727, 5): Overload 3 is the closest match
Argument of type "Buffer" cannot be assigned to parameter "buffer" of type "_SupportsBuffer" in function "frombuffer"
  Type "Buffer" is not assignable to type "_SupportsBuffer"
    "Buffer" is not assignable to "bytes"
    "Buffer" is not assignable to "bytearray"
    "Buffer" is not assignable to "memoryview[int]"
    "Buffer" is not assignable to "array[Any]"
    "Buffer" is not assignable to "mmap"
    "Buffer" is not assignable to "ndarray[Any, dtype[Any]]"
    "Buffer" is not assignable to "generic"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

I ended up using my own definition of `BufferLike` as follows:

```python
import mmap
import sys
from typing import Any, Union
from numpy.typing import NDArray

if sys.version_info >= (3, 12):
    from collections.abc import Buffer as BufferLike
else:
    BufferLike = Union[bytes, bytearray, memoryview, mmap.mmap, NDArray[Any]]
```

I know it's not great as it may not cover a few missing cases (`_array.array[Any]` and `generic` which I could not get in the declaration), but it's good enough as a workaround for now.

Feel free to close this issue unless there is anything left to discuss.

**Comment by ngoldbaum** [comment] 2024-10-30 02:10
Closing since this can be worked around and we shouldn't have been exposing this in the first place.

**Closed by ngoldbaum** 2024-10-30 02:10 UTC
Labels: 00 - Bug
