### ISSUE TITLE
https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html

### ISSUE THREAD

**Issue by angryjiang** [numpy/numpy#15010] opened 2019-11-29 18:59 UTC
https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html

The ddof definition in the above link is incorrect. ddof should be 1 instead of 9.

**Comment by eric-wieser** [comment] 2019-11-29 19:04
Duplicate of gh-13940?

**Comment by angryjiang** [comment] 2019-11-30 04:02
> Duplicate of [gh-13940](https://github.com/numpy/numpy/issues/13940)?

It's the same issue but on a different page. Not too sure if this should be considered a duplicate or not.

**Comment by WarrenWeckesser** [comment] 2019-12-01 02:51
I agree that the use of `ddof = 9` is confusing, especially with the comment `# N - 1`.  In the unweighted case, with the mean estimated from the data, `N - 1` would be the degrees of freedom, not `ddof`.  So I agree that we should change that line to

    ddof = 1

This is not the same issue as gh-13940.  That issue refers to this text from the `var` docstring:

> The variance is the average of the squared deviations from the mean, i.e., var = mean(abs(x - x.mean())**2).
>
> The mean is normally calculated as x.sum() / N, where N = len(x). If, however, ddof is specified, the divisor N - ddof is used instead.

gh-13940 points out the ambiguity of which "mean" is being referred to at the beginning of the second sentence.

**Closed** 2019-12-01 05:00 UTC
Labels: 04 - Documentation
