### ISSUE TITLE
invalid special value handling of avx exp

### ISSUE THREAD

**Issue by juliantaylor** [numpy/numpy#13400] opened 2019-04-24 18:16 UTC
Unfortunately I did not comment that on the original MR but there are errors in handling special values of the new float32 avx based exp and log functions.

executed on an axv2 machine, avx512 still needs to be tested
log:

```
d = np.ones(5, dtype=np.float32) * 1.121

# wrong result
d[...] = np.nan
print(np.log(d))
[89.1283 89.1283 89.1283 89.1283 89.1283]

# correct but raises divide by zero error, which glibc scalar function does not
d[...] = 0.
print(np.log(d))

# raises invalid value error
d[...] = -2. 
print(np.log(d))
d[...] = -np.inf
print(np.log(d))
```

exp 
```
# raises invalid value instead of overflow
d[...] = 1e17
print(np.exp(d))

#raises invalid value
d[...] = np.nan
print(np.exp(d))
d[...] = np.inf
print(np.exp(d))
d[...] = -np.inf
print(np.exp(d))
```

**Comment by rgommers** [comment] 2019-04-25 08:53
This was gh-13134. @r-devulap could you have a look at this?

**Comment by r-devulap** [comment] 2019-04-25 15:58
yup, taking a look.

**Comment by r-devulap** [comment] 2019-04-27 16:39
Started a PR https://github.com/numpy/numpy/pull/13415 to fix this. Will fix the issue with log soon.

**Comment by r-devulap** [comment] 2019-05-07 20:49
PR #13415 is merged, perhaps this issue can be closed?

**Comment by seberg** [comment] 2019-05-07 20:55
@r-devulap just before it gets lost, was this comment a possible problem with the current fix: https://github.com/numpy/numpy/pull/13415#discussion_r279924513

**Comment by r-devulap** [comment] 2019-05-07 21:06
yes, unfortunately I don't have access to a mac and I cannot reproduce that problem on my SKX with ubuntu and gcc/clang. But since that portion of test `test_exp_values` only cares about verifying the output of exp, I can may be ignore floating point errors by updating the test with `np.errstate(all='ignore')`. Would that be acceptable?

**Comment by mattip** [comment] 2019-05-17 03:26
@tylerjereddy Is the occasional `RuntimeWarning: invalid value encountered in exp` on macOS still a valid concern or have they dissapeared?

**Comment by tylerjereddy** [comment] 2019-05-17 17:24
@mattip Yes, I still get the follow test failure output from the latest master branch commit (8a421d9) when running full test suite:

```
________________________ TestSpecialFloats.test_exp_values _________________________
[gw1] darwin -- Python 3.6.5 /Users/treddy/miniconda3/envs/numpy_dev_py36/bin/python

self = <numpy.core.tests.test_umath.TestSpecialFloats object at 0x11bccdac8>

    def test_exp_values(self):
        x = [np.nan,  np.nan, np.inf, 0.]
        y = [np.nan, -np.nan, np.inf, -np.inf]
        for dt in ['f', 'd', 'g']:
            xf = np.array(x, dtype=dt)
            yf = np.array(y, dtype=dt)
>           assert_equal(np.exp(yf), xf)
E           RuntimeWarning: invalid value encountered in exp

dt         = 'f'
self       = <numpy.core.tests.test_umath.TestSpecialFloats object at 0x11bccdac8>
x          = [nan, nan, inf, 0.0]
xf         = array([nan, nan, inf,  0.], dtype=float32)
y          = [nan, nan, inf, -inf]
yf         = array([ nan,  nan,  inf, -inf], dtype=float32)

numpy/core/tests/test_umath.py:659: RuntimeWarning
1 failed, 8641 passed, 63 skipped, 15 xfailed, 3 xpassed in 120.79 seconds
```

**Comment by tylerjereddy** [comment] 2019-05-17 17:27
I don't think it is occasional either--I haven't see any fluke passes lately. I could use `pytest-repeat` if you really need likelihood of failure, but seems to happen all the time for me on mac.

**Comment by charris** [comment] 2019-05-23 00:55
Hmm, this is unfortunate with 1.17 coming on soon.

**Comment by r-devulap** [comment] 2019-05-23 04:59
If I am not wrong, this particular issue was fixed. The test failure seems to be because of a bug in clang7.0 and a new issue was opened to address it (see https://github.com/numpy/numpy/issues/13586). Although, I am not fully sure how to address it..

**Comment by charris** [comment] 2019-06-06 18:18
@juliantaylor Just want to check if this can be closed.

**Comment by charris** [comment] 2019-06-26 17:27
Closing as it seems to be fixed. I expect it will come up again if it persists.

**Closed** 2019-06-26 17:27 UTC
Labels: 00 - Bug, component: numpy.core
