### ISSUE TITLE
np.asanyarray inconsistent behavior for tuple/array of arrays

### ISSUE THREAD

**Issue by adambielski** [numpy/numpy#8330] opened 2016-11-29 15:48 UTC
When passing tuple of ndarrays to np.asanyarray, it may return array of arrays OR give ValueError when first dimensions of arrays match. Found out trying to np.save a tuple (sometimes worked, sometimes did not).

```python
np.__version__
'1.11.2'

a = np.ones((2,1))
b = np.ones(3)
np.asanyarray((a,b))
array([array([[ 1.],
       [ 1.]]), array([ 1.,  1.,  1.])], dtype=object)

b = b[:-1] # now the first dimensions match
np.asanyarray((a,b))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ml/anaconda/envs/face_lasagne/lib/python2.7/site-packages/numpy/core/numeric.py", line 533, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not broadcast input array from shape (2,1) into shape (2)
```

**Comment by charris** [comment] 2016-12-03 21:50
Yep, looks like a bug in `np.array`.

**Comment by eric-wieser** [comment] 2018-07-23 05:16
Closing as a duplicate of #7453

**Closed by eric-wieser** 2018-07-23 05:16 UTC
Labels: 00 - Bug
