### ISSUE TITLE
BUG: gh-10882 may have broken ctypes compatibility in older versions of python

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#11150] opened 2018-05-24 05:37 UTC
#10882 changed the behavior of `np.array` from.

* Try to get a PEP3118 buffer interface
  * Try to convert the buffer interface into an array
  * If the buffer interface is not correct, **try `__array_interface__` instead**
  * sometimes call `abort()` due to bad error silencing (#6741)
* If there's no buffer interface, try `__array_interface__` instead

To

* Try to get a PEP3118 memory view
   * Try to convert the buffer interface into an array
   * If the buffer interface is not correct, **fail and tell the user that something is wrong**
* If there's no buffer interface, try `__array_interface__` instead

This means that objects which incorrectly implement the buffer interface now fail loudly, rather than silently-or-with-abort().

Unfortunately, prior to python/cpython#31, (before 2.7.14 / 3.6.3 / 3.7.0) ctypes did not implement the buffer interface correctly for integer types (the format and itemsize didn't match)

Do we have a minimum supported patch version of python? If so, should we enable tests for it so that this doesn't happen again?

**Comment by eric-wieser** [comment] 2018-05-25 21:28
That assumes that this was tested...

**Comment by mattip** [comment] 2018-05-31 19:16
I am confused as to what the user-experienced problem is. From the cpython link, the following fails:
```
import ctypes, numpy
numpy.asarray(memoryview(ctypes.c_long(42)))
```
on an older python, whether I use `HEAD` or numpy 1.11.

**Comment by mattip** [comment] 2018-06-05 18:32
@eric-wieser could you clarify if the problem is a different exception type or something deeper?

**Comment by eric-wieser** [comment] 2018-06-06 08:41
@mattip: I think the case that matters is `numpy.asarray(ctypes.c_long(42))`

**Comment by eric-wieser** [comment] 2018-06-06 08:50
Turns out my WSL has python 2.7.12, so I'm all set to test this:
```python
>>> sys.version_info
'2.7.12 (default, Dec  4 2017, 14:50:18) \n[GCC 5.4.0 20160609]'
>>> bad = ctypes.c_long(42)
>>> ctypes.sizeof(bad)   # this failure requires 64-bit long (ie, not windows native)
8

# 1.14
>>> np.asarray(ctypes.c_long(42))
RuntimeWarning: Item size computed from the PEP 3118 buffer format string does not match the actual item size.
array(42)

# master
>>> np.asarray(ctypes.c_long(42))
RuntimeError: Item size computed from the PEP 3118 buffer format string does not match the actual item size.

```

**Comment by charris** [comment] 2018-06-07 22:57
@eric-wieser  We can close this now?

**Comment by eric-wieser** [comment] 2018-06-07 23:13
Not unless things have changed since I ran my test above (which shows it failing)

**Comment by charris** [comment] 2018-06-07 23:48
Hmm. I vote that we document the required versions, with a strong suggest that folks keep current. Given that the problems are fixed upstream that seems reasonable. What about python 3.5?

**Comment by eric-wieser** [comment] 2018-06-07 23:50
In case it changes your mind, ubuntu 16.04 ships with python 2.7.12, which exhibits the ctypes bug

**Comment by eric-wieser** [comment] 2018-06-07 23:53
I could try tweaking #10882 to have a special case for ctypes objects,

**Comment by charris** [comment] 2018-06-07 23:57
Sure, give it a shot, but don't spend a lot of time on it.

**Comment by eric-wieser** [comment] 2018-11-19 08:36
Reopening - this is a real issue for `ndpointer`, which provides:

* A valid but unsupported PEP3118 interface
* `__array_interface__`

This causes toinsson/pyrealsense#82, which unfortunately they never raised upstream.

#12380 has made the error message even more cryptic, so we really ought to fix this for 1.16.

**Comment by mattip** [comment] 2018-11-26 17:41
The follow-on issue #12421 was left open but tentatively declared "won't fix", does that mean this issue is also "won't fix", or at least can be removed from the 1.16 milestone?

**Comment by eric-wieser** [comment] 2018-11-26 23:43
Yeah, this can be removed from the milestone

**Comment by vadimkantorov** [comment] 2020-07-27 19:24
I also stumbled on this: I have unrelated buffer interface (inherited from ctypes impl) and my custom __array_interface__ that I'd like to be used

**Comment by mattip** [comment] 2023-03-31 08:59
@eric-wieser we have dropped support for python<3.8, I think we can close this?

**Comment by seberg** [comment] 2024-08-09 11:50
Agreed with Matti, seems like we can close it with old Python versions long EOL and unsupported.

**Closed by seberg** 2024-08-09 11:50 UTC
Labels: 00 - Bug, 06 - Regression
