### ISSUE TITLE
BUG:  numpy.argsort 

### ISSUE THREAD

**Issue by MrTheyosyos** [numpy/numpy#22020] opened 2022-07-21 06:55 UTC
### Describe the issue:

wrong output.

### Reproduce the code example:

```python
import numpy as np

mat = np.array([[7,5,1,6],[1,9,8,2],[2,7,3,8]])

mat
>>array([[7, 5, 1, 6],
         [1, 9, 8, 2],
         [2, 7, 3, 8]])

np.argsort(mat, axis=1)
>>array([[2, 1, 3, 0],
         [0, 3, 2, 1],
         [0, 2, 1, 3]])


# expected:
array([[3, 1, 0, 2],
       [0, 3, 2, 1],
       [0, 2, 1, 3]])
```

### NumPy/Python version information:

Name: numpy
Version: 1.22.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD

**Comment by WarrenWeckesser** [comment] 2022-07-21 14:45
This is a duplicate of https://github.com/numpy/numpy/issues/8757 (and several other issues reporting the same "problem").

@MrTheyosyos, `argsort` does not *rank* the values.  For ranking, you can use a function such as [`scipy.stats.rankdata`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rankdata.html).

**Closed by WarrenWeckesser** 2022-07-21 14:45 UTC
Labels: 00 - Bug

**Comment by WangAYi** [comment] 2024-01-18 03:11
hello
