### ISSUE TITLE
Regression in ma.median handling of nan values, and calculates incorrect value

### ISSUE THREAD

**Issue by mwcraig** [numpy/numpy#8340] opened 2016-12-05 00:11 UTC
The handling of `nan` values in masked arrays passed in to `ma.median` changed some time between 1.10.2 and 1.11.2, and the value returned in 1.11.2  is incorrect. In 1.10.2 `nan` was returned in this case. In 1.11.2 an (incorrect) numerical result is returned.

This example demonstrates both problems:

```python
import numpy as np
dm = np.ma.array([1, np.nan, 3])
np.ma.median(dm)
```

In numpy 1.10.2 the output is as expected: `nan`

In numpy 1.11.2 the output is incorrect (not `nan` *and* not the correct numerical value ignoring the `nan`):

```
masked_array(data = 3.0,
             mask = False,
       fill_value = 1e+20)
```

Based on test failures we are seeing in https://github.com/astropy/astropy/pull/5232, the issue continues in 1.12.0b1.

**Comment by juliantaylor** [comment] 2016-12-05 00:30
caused by af671c4aada0888e9e38ce0836ed119686e8c5ee in gh-7911

**Comment by charris** [comment] 2016-12-05 00:32
Are you sure `3.` is incorrect? NumPy sorts `nan` to the end.

**Comment by juliantaylor** [comment] 2016-12-05 00:36
it is at least inconsistent, we changed median to always return `nan` if one is in there.

**Comment by charris** [comment] 2016-12-05 00:42
Hmm, didn't realize that. I would have thought 3 was a more useful result as a common use of the median is to remove outliers.

**Comment by charris** [comment] 2016-12-05 00:45
So it was changed sometime after 1.8, 1.9 I presume.

**Comment by juliantaylor** [comment] 2016-12-05 00:46
and once again, masked_array was not considered when that change was made. The masked median will still behave as the old median, just treat nan as infinity and return the middle.
The mentioned PR just removed a fast path that went into the normal median.

**Comment by charris** [comment] 2016-12-05 01:00
Does that mean that the behavior for masked arrays depended on whether of not the fast path was taken? Also, doesn't partition have a fallback to sorting the array?

**Comment by mwcraig** [comment] 2016-12-05 01:04
I suppose 3. makes sense as the result if `nan` is treated as `inf`. I had thought it was doing the calculation ignoring the `nan` so was expecting 1.5.

**Comment by juliantaylor** [comment] 2016-12-05 01:06
yes as there are two different median implementations, the normal unmasked one and the masked.
The unmasked uses partition and treats nan special (since relatively recently, always returning nan), the masked always sorts but doesn't treat nans special, they end up being treated as infinity by their behavior.
Additionally there is nanmedian which can either use normal median + removing nans via indexing or use masked median depending on what is faster (in this case nans are masked so it is fine)

**Comment by juliantaylor** [comment] 2016-12-05 01:09
note we did the change in behavior of np.median in 1.10: https://github.com/numpy/numpy/blob/master/doc/release/1.10.0-notes.rst#median-warns-and-returns-nan-when-invalid-values-are-encountered

**Comment by mwcraig** [comment] 2016-12-05 01:16
The 1.10 behavior is what I had expected.

**Comment by juliantaylor** [comment] 2016-12-05 01:20
yes, so the issue is `np.ma.median` needs to be changed to behave the same as `np.median` in this situation.

**Comment by juliantaylor** [comment] 2016-12-05 01:21
But for third parties, don't pass unmasked `nan` to median, regardless which version, you either get a wrong result or `nan` back depending on version.

**Comment by charris** [comment] 2016-12-05 01:27
@juliantaylor Did not recall that. The change must not have been too disturbing as no one has complained (yet). Almost sounds like something that could have been handled with a new keyword. Anyway, water under the bridge and all that.

So I agree, we should fix the masked version. Should we issue a FutureWarning or just go with it?

**Comment by charris** [comment] 2016-12-05 02:39
The guestion I have is if something needs to be done for 1.12.0. It sounds as if the current situation is backward compatible as much as it can be given the two possible results possible in 1.10 and unfixed 1.11 so I don't feel it is urgent to change things. If there are no changes to make, I plan on making 1.12.0rc1 tomorrow.

**Comment by mwcraig** [comment] 2016-12-05 03:02
fwiw, I think it could wait until 1.12.1.

**Comment by charris** [comment] 2016-12-05 03:05
@mwcraig We try not to change behavior in micro-versions, they are for bug fixes.

**Comment by mwcraig** [comment] 2016-12-05 03:21
Ah, ok, so next change would be 1.13, then? In that case this seems more urgent, since I think the change from 1.10 to 1.11 was a regression in the intended behavior, and the timescale between releases is long. 

Though I'd also consider the current situation a bug, personally, since you get a different result for median depending on whether you used the masked or unmasked median when called with the same data (though the data has to be a masked array to expose the issue, I'd expect the same result from the two flavors of median if mask is `False`).

**Comment by juliantaylor** [comment] 2016-12-05 17:15
I think it would be good to squeeze it into 1.12, I'll have a look today.

**Comment by charris** [comment] 2016-12-05 17:43
I'm going to do a 11.3 for the file append issue, so If you fix it up for 1.12 I might put it in 1.11.3 also.

**Comment by juliantaylor** [comment] 2016-12-05 22:18
such a change should not be in a bugfix release.

It is also quite tricky without quite large performance impact. The problem is that `NaN` is the minimum filler element of the masked sort, so the ordering of masked elements and `NaN` is undefined but at the end.
One could fix that by changing median to sort with `endwith=False` so the masked elements go to the front and we can check for `NaN` at the end like in the regular median.
But that makes the maximum filler `-inf` and there could be an array containing these values where the median ends up computed wrongly, though I can't construct one of the top my head now. So unless the property of Inf actually makes this impossible we need some different method.

The way out of this normally is sorting the mask, but this would almost double the runtime of the masked median, maybe some clever partial sorting could work ...

**Comment by juliantaylor** [comment] 2016-12-05 22:24
hm actually the `-inf` filling should always be fine as long as we remove the mask from the lower and higher indices of the medians.

**Comment by charris** [comment] 2016-12-05 22:38
Nans sort as larger than inf.

**Comment by juliantaylor** [comment] 2016-12-05 22:39
yes and that is why for floats nan is the minimum_fill_value

**Comment by juliantaylor** [comment] 2016-12-05 22:43
hm overriding the minimum_fill_value for median could be another option as we don't really care about the masked elements being at the end for nans present, we will return nan anyway.

**Comment by juliantaylor** [comment] 2016-12-05 22:50
eh that works and is much simpler than rewiring the code to index from the other direction :D 
thanks for hint to push me in that direction :)

**Comment by charris** [comment] 2016-12-08 21:49
@juliantaylor Any progress? I'm holding up 1.12.0rc1 for this.

**Comment by juliantaylor** [comment] 2016-12-08 22:51
stuff got in the way unfortunately but I got the median to behave correctly but I still have to write a lot of tests, the medians are full of subtleties. I will probably not get it done until saturday/sunday.
I do think if we want to change it should go into 1.12, is there a reason we can't wait?
fwiw I'd also like gh-8220 fixed in 1.12, I only just recently saw it.

**Comment by juliantaylor** [comment] 2016-12-08 22:52
my wip in progress branch is juliantaylor:masked-median-nan2 if you want to pick it up, currently fails nanmedian tests which use that function.

**Comment by charris** [comment] 2016-12-08 23:06
I can wait, just wanted to have some idea of the timeline. I didn't want to release 1.12.0 final until after Python 3.6, but that is only a week off and NumPy 1.12.0rc1 should cook for at least two weeks... I was hoping to release this year but I suppose a week or two won't matter.

**Comment by juliantaylor** [comment] 2016-12-10 13:58
hm changing the fill_value does not work as then we can't distinguish inf and nan anymore, reversing the indexing it is then

**Comment by charris** [comment] 2016-12-10 14:38
I think it should work. If the masked values are filled with inf and a nan appears at the end when sorted, return nan. Otherwise, count the number of masked values and ignore that many values at the end of the sorted result.

**Comment by juliantaylor** [comment] 2016-12-10 14:46
that is what I'm doing but it didn't work, though probably due to a bug elsewhere as the ordering should only be undefined for equal elements not larger as nan is

**Comment by juliantaylor** [comment] 2016-12-10 14:59
ah forgot to ignore masked nan values in checking the result, back to writing tests.

**Comment by juliantaylor** [comment] 2016-12-10 16:52
hm no I was correct, the issue is that sorting with inf fill value replaces nans with inf so they don't sort behind the infs anymore and we can't distinguish between them anymore even when the original masked values actually are nans.

e.g. 
    a = np.array([[np.nan, np.nan, np.inf], [np.nan, np.nan, np.inf]])
    np.nanmedian(a, axis=1)

with mimum fill value of inf here the sorted masked array has indefined ordering with the nans

**Comment by charris** [comment] 2016-12-10 17:32
No, I still think is works. Only masked nans should be replaced with the fill value, and since we ignore masked values, it doesn't matter.

**Comment by juliantaylor** [comment] 2016-12-10 17:49
in the case of nanmedian the nans are masked and we are selecting based on the mask being at the end which is not the case anymore here. I have updated the branch which has a failing test.

**Comment by charris** [comment] 2016-12-10 18:05
I don't see the problem. If there is an unmasked nan, it will be at the end and the result is nan. If there are no unmasked nans, they are replaced by inf and sort to the end with the other infs. What am I missing?

**Comment by juliantaylor** [comment] 2016-12-10 18:07
they are replaced in a copy so they are still nans and are selected, but you are right if we don't make a copy we could return the correct result.

**Comment by charris** [comment] 2016-12-10 18:07
Oh, nanmedian, not masked median.

**Closed** 2016-12-12 23:10 UTC
Labels: 11 - Bug, component: numpy.ma
