### ISSUE TITLE
BUG: a.dtype in set(dtypes) doesn't work

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#25782] opened 2024-02-07 10:10 UTC
### Describe the issue:

One can check if an array dtype is from a _list_ of types, but not from a _set_.

### Reproduce the code example:

```python
import numpy as np

a = np.array([1,2,3])

print(a.dtype == np.int64)
print(a.dtype in [np.int64])
print(a.dtype in {np.int64})
```
```python
True
True
False
```

### Python and NumPy Versions:

1.26.4
3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]

**Comment by seberg** [comment] 2024-02-07 10:49
Duplicate of e.g. gh-17864.  dtype `==` is overloaded so absurdly (by coercing the other side), that it is utterly impossible to provide consistent hashes...
(Not that it would be *easy* if it was less overloaded, but if you limit yourself to the scalar types you might have a fighting chance at least.)

**Comment by ngoldbaum** [comment] 2024-02-08 02:33
Closing as a duplicate of #17864

**Closed by ngoldbaum** 2024-02-08 02:33 UTC
Labels: 00 - Bug
