### ISSUE TITLE
Printing [[]] leads to []

### ISSUE THREAD

**Issue by AllenShieh** [numpy/numpy#10969] opened 2018-04-25 04:42 UTC
This issue has been seen in both python 2 and python 3 with numpy.

Consider such numpy arrya `b = numpy.array([[]])`. `print(len(b))` would result in 1, `print(b.size)` would result in 0, and `print(b)` would result in [], as implemented in /numpy/core/arrayprint.py around line 665. 

We found this when debuging in our own project, where we need to check whether an array is empty or not. More description can be seen in this [blog](http://allenshieh.github.io/pythoncon/). We think when array size is 0, but it has some [] in the array, the printing should not just print an empty array out (actually it is completely not empty!).

**Comment by eric-wieser** [comment] 2018-04-25 04:57
What would you like `np.empty((0, 1))` to print?

Note that `repr` already gives something reasonable:

```python
>>> np.array([[]])
array([], shape=(1, 0), dtype=float64)
```

**Comment by AllenShieh** [comment] 2018-04-25 16:05
I think I understand the reason behind this. But still, to some extent, we cannot say that an array containing an empty array is an empty array, if we treat the array inside as an element of the array outside, right? Just think printing [[]] leads to [] looks strange to me (and maybe some other people).

**Comment by eric-wieser** [comment] 2018-04-25 16:55
> we cannot say that an array containing an empty array is an empty array, if we treat the array inside as an element of the array outside, right

Yes, but that's spelt differently:

```python
a = np.zeros(2, dtype=object)  # 1d array...
a[0] = np.array([])  # ... containing arrays
a[1] = np.array([1, 2, 3])  # ... of different sizes
```
or

```python
a = np.zeros(1, dtype=[('the_subarray', int, (0,))])  # 1d array with empty arrays as its elements
```

**Comment by eric-wieser** [comment] 2019-04-20 04:12
A related PR is #10119

**Comment by seberg** [comment] 2021-11-06 05:19
Closing as duplicate of the newer gh-16665

**Closed by seberg** 2021-11-06 05:19 UTC
