### ISSUE TITLE
Interrupting build leaves working copy in a broken copy

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#5467] opened 2015-01-19 18:04 UTC
If you try to build Numpy, for example:
```
$ python3.4 setup.py build_ext --inplace
```

and press Ctrl-C before the end, the working copy ends up broken. Any further invocation fails:
```
$ python3.4 setup.py build_ext --inplace
Running from numpy source directory.
Traceback (most recent call last):
  File "setup.py", line 251, in <module>
    setup_package()
  File "setup.py", line 235, in setup_package
    from numpy.distutils.core import setup
  File "/home/antoine/np/numpy/distutils/__init__.py", line 37, in <module>
    from numpy.testing import Tester
  File "/home/antoine/np/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/home/antoine/np/numpy/testing/utils.py", line 17, in <module>
    from numpy.core import float32, empty, arange, array_repr, ndarray
  File "/home/antoine/np/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'
```

You then have to issue a non-trivial invocation of "git clean" to start again from a blank slate.

**Comment by rgommers** [comment] 2015-01-19 21:01
Interesting. This doesn't happen for Python 2.7, so I never noticed. Maybe something to do with the change to ``importlib`` or something in ``distutils``?

**Comment by juliantaylor** [comment] 2015-01-19 21:05
never had this issue either, but I'm also an avid user of git clean -xfd and out of place installs (into /tmp/local)
I guess you can probably interrupt it at a time where is multiarray built but its dependencies like _compiled_base not, maybe an extension ordering issue.
more information on why it does not import would be needed, e.g. python -v output or an ldd of the multiarray.so might be interesting.

**Comment by wackywendell** [comment] 2015-10-11 16:42
I just had this issue.

I had worked on numpy months ago, so I still had an old version on my computer; when I ran `git pull` followed by `python setup.py build_ext --inplace`, it failed with the same message: `ImportError: cannot import name 'multiarray'`. Same for Ctrl-C in the middle. This happened both with and without a virtualenv.

 Here's the full traceback:

```
Running from numpy source directory.
Traceback (most recent call last):
  File "setup.py", line 260, in <module>
    setup_package()
  File "setup.py", line 244, in setup_package
    from numpy.distutils.core import setup
  File "/home/wendell/code/numpy/numpy/distutils/__init__.py", line 21, in <module>
    from numpy.testing import Tester
  File "/home/wendell/code/numpy/numpy/testing/__init__.py", line 14, in <module>
    from .utils import *
  File "/home/wendell/code/numpy/numpy/testing/utils.py", line 17, in <module>
    from numpy.core import float32, empty, arange, array_repr, ndarray
  File "/home/wendell/code/numpy/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'
```

Running `git clean -xfd` (followed by `python setup.py build_ext --inplace -j 4`) did fix it. I'm running Python 3.5 on Arch Linux, so that may have something to do with it.

Perhaps this should be noted in the install docs?

Also, I was noticing that the [Contributing to Numpy](http://docs.scipy.org/doc/numpy-dev/dev/index.html) docs do not have a section on testing, or as far as I could tell even mention testing. Am I missing a section somewhere? I might try and add something to them about that.

**Comment by rgommers** [comment] 2015-10-11 18:39
Yes, you're missing a section because the dev docs are outdated (they should be rebuilt as part of the 1.10 release): 
https://github.com/numpy/numpy/blob/master/doc/source/dev/development_environment.rst#running-tests

https://github.com/numpy/numpy/blob/master/doc/source/dev/development_environment.rst#rebuilding--cleaning-the-workspace

**Comment by rgommers** [comment] 2015-10-11 18:41
Since ``git clean -xdf`` is documented there now (and it really should be what every ``git`` user should use instead of crap that doesn't work like ``python setup.py clean``), can we close this issue? I don't think that there's anything else to do here.

**Comment by jakirkham** [comment] 2016-01-10 20:09
I have had a similar error where I was able to build and install. However, if I import when using `python-dbg`, I get this exact same error. Does not occur when using `python`.

**Comment by rgommers** [comment] 2016-01-16 11:57
I managed to reproduce this now, should be fixed by gh-7029.

@jakirkham I'm not sure that your issue is exactly the same. If it's not fixed by my PR, can you maybe open a new issue?

**Closed** 2016-01-16 16:39 UTC
Labels: component: build, Defect
