### ISSUE TITLE
rolling sparse matrices creates "dense" matrices (and takes up the full amount of space in RAM)

### ISSUE THREAD

**Issue by tpchuckles** [numpy/numpy#25494] opened 2023-12-26 02:31 UTC
### Describe the issue:

If I have a sparse matrix which is mostly zeros, the zeros don't contribute to RAM consumption. if i roll said matrix, the resulting matrix's zeros contribute to RAM consumption. 

This is critical if you have large datasets which are mostly zeros, and the oom-killer steps in (e.g., I am currently processing some [spectroscopy image](https://en.wikipedia.org/wiki/Energy-dispersive_X-ray_spectroscopy) datasets: 900 x 900 pixels, with 4096 levels per pixels. if I use 16-bit ints for these, i should expect roughly 6GB of ram usage. Fortunately, the datasets are sparse, with only a few hundred mb of non-zero data...until i roll them. i eventually do some binning and slicing to reduce the size of the datasets i'm working with, but I still need to do some rolling beforehand). 

I have included a basic code example below. I am also including a workaround (an alternative "roll" function) which sidesteps this issue, by creating a new zeros matrix and then sparsely filling it. I'm not sure if this is a system-specific issue, or if numpy should attempt to detect if a matrix is "sparse", or have a flag or something, or what.

### Reproduce the code example:

```python
# THIS IS THE MINIMUM CODE TO REPRODUCE THE PROBLEM
import numpy as np
a=np.zeros((900,900,4096),dtype=np.uint16)
# manually check gnome-system-monitor, python is consuming 16MB RAM. interestingly, sys.getsizeof(a) returns 6635520144, the calculated size i would expect. I suppose the memory is allocated but not filled?
b=np.roll(a,5,axis=0)
# python rockets up to 6.6GB ram consuption in gnome-system-monitor. checking type(b[0,0,0]) can confirm we still have int16s. do this a few more times and the oom-killer will step in.

# THIS IS MY WORKAROUND FUNCTION (maybe numpy roll could detect if an input matrix is sparse, or have some sort of sparse flag? i don't know the best course of action)
def sparseroll(a,n,axis=0):
	if n==0:
		return a
	dtype=type(a.flat[0])
	b=np.zeros(np.shape(a),dtype=dtype)
	where=np.asarray(np.where(a!=0)) # each axis ends up in a row
	where2=np.zeros(np.shape(where),dtype=int)
	where2+=where
	where2[axis]+=n # increment the coordinated of the entire row (along specified axis)
	where2[where2>=np.asarray(np.shape(a))[:,None]]=0 # handle wrapping about end (negative wrapping handled automatically)
	where=tuple(where) ; where2=tuple(where2) # convert back to "lists of indices per axis"
	b[where2]=a[where]
	return b
```

### Python and NumPy Versions:

1.24.2
3.11.4 (main, Dec  7 2023, 15:43:41) [GCC 12.3.0]
ubuntu 23.04 ; kernel 6.6.2

### Runtime Environment:

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2',
                                'AVX512F',
                                'AVX512CD',
                                'AVX512_SKX',
                                'AVX512_CLX',
                                'AVX512_CNL',
                                'AVX512_ICL'],
                      'not_found': []}}]

### Context for the issue:

This affects handling of large sparse matrices, which I use for data analysis for my research. If folks think the workaround function I included is appropriate "fix", i'm happy to do a pull request.

**Comment by mattip** [comment] 2023-12-26 12:11
The use of  `ndarray.zeros()` does not create a sparse matrix. These can be created using [`scipy.sparse`](https://docs.scipy.org/doc/scipy/reference/sparse.html), but not via NumPy. You are seeing a glitch caused by an implementation detail of `malloc`: it is reserving memory and only actually allocates pages when the array is written to. Another memory allocation strategy would show different behaviour. I think you would see different results on windows, for instance.

**Comment by tpchuckles** [comment] 2023-12-26 14:37
> The use of `ndarray.zeros()` does not create a sparse matrix. These can be created using [`scipy.sparse`](https://docs.scipy.org/doc/scipy/reference/sparse.html), but not via NumPy. You are seeing a glitch caused by an implementation detail of `malloc`: it is reserving memory and only actually allocates pages when the array is written to. Another memory allocation strategy would show different behaviour. I think you would see different results on windows, for instance.

yeah, I did think it was odd i couldn't find anything on "sparse numpy arrays" on the internet. also interesting: it's not just that the array hasn't been written to (i can write to it and it doesn't immediately blow up to the 6.6GB), and it also doesn't scale in RAM directly based on how much is written to it (I can write to 100,000 random fields, and it blips up to 400MB (rather than 195kb like i'd expect for 100k 2-byte ints)

**Comment by rkern** [comment] 2023-12-26 15:47
"We" (as in numpy) are doing nothing in particular. Your OS is doing the actual allocation of memory pages as locations within those pages are written to by your code. Given a typical 4096-byte page, randomly hitting 100,000 locations in a much larger memory space would probably hit 100,000 different pages, allocating about 400MB of memory. Allocations happen a page at a time, not a byte at a time.

I think we have identified the root cause here, and there is nothing to be changed in numpy, so I am going to close this. If you still have questions, please feel free to continue the conversation on the closed issue.

**Closed by rkern** 2023-12-26 15:47 UTC
Labels: 00 - Bug
