### ISSUE TITLE
Converting ns/as-precision datetime64 to datetime.datetime results in integer

### ISSUE THREAD

**Issue by gerritholl** [numpy/numpy#8546] opened 2017-01-30 15:53 UTC
Converting ns/as-precisiong datetime64 to datetime.datetime results in integer:

`datetime.datetime` does not support nanoseconds ([see issue](http://bugs.python.org/issue15443)).  When numpy casts it should round or raise an error, instead it silently returns int:

```
In [186]: numpy.datetime64("1985-08-13", "us").astype(datetime.datetime)
Out[186]: datetime.datetime(1985, 8, 13, 0, 0)

In [187]: numpy.datetime64("1985-08-13", "ns").astype(datetime.datetime)
Out[187]: 492739200000000000

In [189]: numpy.datetime64("1985-08-13", "as").astype(datetime.datetime)
Out[189]: -8200712707674996736
```

**Comment by gerritholl** [comment] 2017-01-30 16:39
This is painful because xarray (and pandas, I believe) [internally uses nanosecond-precision](http://xarray.pydata.org/en/stable/time-series.html), which means those cannot be correctly converted to `datetime.datetime` objects.

**Comment by gerritholl** [comment] 2017-01-30 17:10
More direct illustration: `timedelta64(100, 'ns').item()` → `100`.  I understand that `datetime.datetime` is unable to represent this but I'm not convinced this is the best approach.

**Comment by shoyer** [comment] 2017-01-30 17:35
This is basically the same issue as #7619 and #4337

**Comment by eric-wieser** [comment] 2017-10-18 04:46
It seems to me that `timedelta64(100, 'ns').item() == timedelta64(100, 'ns')` is the best approach here, which at least is consistent with #8547

**Comment by eric-wieser** [comment] 2019-02-18 08:55
Closing as a duplicate of #12550, since there's far more discussion there

**Closed by eric-wieser** 2019-02-18 08:55 UTC
Labels: 00 - Bug, component: numpy.datetime64
