### ISSUE TITLE
BUG: np.pad fails for sizes that do not fit in `np.int_`

### ISSUE THREAD

**Issue by eric-wieser** [numpy/numpy#12023] opened 2018-09-24 02:51 UTC
```python
>>> np.pad(np.zeros((0, 0)), [(0, 2**30), (0, 0)],  'constant')
array([], shape=(1073741824, 0), dtype=float64)
>>> np.pad(np.zeros((0, 0)), [(0, 2**31), (0, 0)],  'constant')
ValueError: [(0, 2147483648), (0, 0)] cannot contain negative values.
>>> np.pad(np.zeros((0, 0)), [(0, 2**32), (0, 0)],  'constant')
array([], shape=(0, 0), dtype=float64)
```
Switching an internal cast to `intp` solves the issue

**Comment by lagru** [comment] 2018-09-24 08:43
I can't reproduce this on a 64 bit system.

```python
>>> np.pad(np.zeros((0, 0)), [(0, 2**30), (0, 0)],  'constant')
array([], shape=(1073741824, 0), dtype=float64)
>>> np.pad(np.zeros((0, 0)), [(0, 2**31), (0, 0)],  'constant')  # Second line
array([], shape=(2147483648, 0), dtype=float64)
>>> np.pad(np.zeros((0, 0)), [(0, 2**32), (0, 0)],  'constant')
array([], shape=(4294967296, 0), dtype=float64)
```

Am I missing something? Is this supposed to fail on 32-bit systems if `np.int_` corresponds to `np.int32`?

**Comment by seberg** [comment] 2018-09-24 09:36
@lagru, yes, you are not using windows. In 64bit linux, `np.int_` (which is C `long`) is also 64 bit and thus sufficiently large. One of the reasons such buigs tend to linger a bit longer, less user (probably even more so with huge arrays).

**Comment by lagru** [comment] 2018-09-24 09:41
Interesting. @seberg thanks for the explanation.

**Comment by seberg** [comment] 2023-11-03 07:24
Closing, since `int_` is now intp on main (hopefully that pans out).  Although it could stil lbe changed to intp explicitly...

**Closed by seberg** 2023-11-03 07:24 UTC
Labels: 00 - Bug, component: numpy.lib
