### ISSUE TITLE
BUG: assert_array_equal needs to let `DeprecationWarnings` pass through.

### ISSUE THREAD

**Issue by lesteve** [numpy/numpy#8323] opened 2016-11-27 20:54 UTC
It started failing one day ago or so in the scikit-learn tests using the development numpy wheels from https://travis-dev-wheels.scipy.org/.

I can reproduce the error on numpy master with this snippet:
```py
import numpy as np

my_list = [[np.array([1, 2]),
            np.array([1, 2, 3])]]

np.testing.assert_array_equal(my_list, my_list)
```

The expected behaviour is that there is no exception since I compare `my_list` to itself. The actual behaviour is is an AssertionError with numpy master.

The same snippet runs fine with numpy 1.11.2.

**Comment by charris** [comment] 2016-11-27 21:05
This is no doubt due to the new lack of identity fallback when the array comparisons don't yield scalar boolean values.  The test would probably fail previously if the second array was a copy of the first rather than the same array. I think the failure here is probably the right thing to do.

**Comment by charris** [comment] 2016-11-27 21:12
The identity fallback has been deprecated since NumPy 1.9. Perhaps that wasn't passed through the test?

**Comment by charris** [comment] 2016-11-27 21:19
However, I see that now a proper error is not raised in this case as it should have been, so that is a bug.

**Comment by lesteve** [comment] 2016-11-27 22:00
> This is no doubt due to the new lack of identity fallback when the array comparisons don't yield scalar boolean values. The test would probably fail previously if the second array was a copy of the first rather than the same array. I think the failure here is probably the right thing to do.

OK thanks, I wasn't aware of these subtleties and as you hinted the following snippet fails already on 1.11.2:

```py
import numpy as np

my_list = [[np.array([1, 2]),
            np.array([1, 2, 3])]]

my_list_2 = [[np.array([1, 2]),
            np.array([1, 2, 3])]]

np.testing.assert_array_equal(my_list, my_list_2)
```

It looks like we were just (un)lucky to be in a edge case where the test would still pass so we'll just change our tests.

> The identity fallback has been deprecated since NumPy 1.9. Perhaps that wasn't passed through the test?

For the record, I don't get any DeprecationWarning running the first snippet I posted with numpy 1.11.2.

**Comment by lesteve** [comment] 2016-11-27 22:26
It seems like `numpy.testing.assert_equal` follows my naive (and wrong) expectation for both the first and the second snippet. Is there any caveat in using `numpy.testing.assert_equal` in cases like these when comparing nested structures containing arrays?

**Comment by charris** [comment] 2016-11-27 22:43
Looks like better error messages are being raised, but `assert_array_equal` is dropping them.

**Comment by charris** [comment] 2016-11-27 22:49
The problem is that the equal/not_equal loops requires that comparison of two elements return a boolean. Comparison of two arrays is typically an array, so that is the source of the problem for object arrays, and the same for nested lists. The identity was never available for anything but `equal/not_equal`, and isn't always correct either, comparing NaNs for example.

**Comment by charris** [comment] 2016-11-27 22:52
We try to get these deprecations out early in the release cycle precisely to uncover problems, so thanks for the report.

**Comment by charris** [comment] 2017-05-05 22:17
Changed the title and pushed off to 1.14.

**Comment by charris** [comment] 2017-11-27 23:02
@eric-wieser  Looks like this is sort of fixed in #10096.

**Comment by eric-wieser** [comment] 2017-11-28 00:49
@charris: After that PR, now both an AssertionError with a detailed message, and the deprecation warning, are shown (at least in py 3 which sets the __context__ attribute of the exception).

I suppose in principle it would be better to customize the error message to indicate that comparison wasn't possible.

**Comment by charris** [comment] 2017-11-28 21:55
Hmm, good enough. I'll close this, the original issue was fixed and what remains seems not a big thing. We'll see if there are related complaints in the future.

**Closed by charris** 2017-11-28 21:55 UTC
