### ISSUE TITLE
__setitem__ shape mismatch error is incorrect

### ISSUE THREAD

**Issue by yuyu2172** [numpy/numpy#8280] opened 2016-11-16 03:13 UTC
The error message produced by setting value of mismatching shape to array is incorrect.

Here is an example.

```python
>>> a = numpy.zeros((4, 4, 4))
>>> ind = numpy.array([[1,0], [2, 3]])
>>> v_shape = (2,2,4,4)
>>> v = numpy.arange(np.prod(v_shape)).reshape(v_shape)
>>> a[:, ind, :] = v

ValueError: shape mismatch: value array of shape (2,2,4,4) could not be broadcast to indexing result of shape (2,2,4,4)
```

The shape that is requested by this example is `(4, 2, 2, 4)`. Therefore, error message should say 

```python
ValueError: shape mismatch: value array of shape (2,2,4,4) could not be broadcast to indexing result of shape (4,2,2,4)
```

**Comment by eric-wieser** [comment] 2017-02-13 19:54
This is something more complex than just passing the wrong object into the error message. If you repeat with `v_shape == (2, 3, 4, 5)`, you'll see that `(2,2,4,4)` still appears in the output. So there's a permutation of axes happening here

**Comment by eric-wieser** [comment] 2017-02-13 19:57
I think there's some "advanced indexing" transformation happening under the hood, since:

```
>>> a[:,ind,:].shape
(4, 2, 2, 4)
>>> np.array([a])[0,:,ind,:].shape
(2, 2, 4, 4)
```

**Comment by seberg** [comment] 2017-02-13 23:36
Yes, should be a duplicate flying around somewhere. Basically there is a transpose going on internally, and it is not being undone for error reporting.

**Comment by eric-wieser** [comment] 2017-02-24 01:34
Duplicate of #5710

**Comment by mattip** [comment] 2019-05-30 09:18
Closing as a duplicate. If you feel there is more to this issue that is missing in #5710, please reopen.

**Closed by mattip** 2019-05-30 09:18 UTC
Labels: 00 - Bug, component: numpy.core, priority: low
