### ISSUE TITLE
Decide whether the value of scalars (not just the type) should affect result type of mixed scalar/array operations

### ISSUE THREAD

**Issue by njsmith** [numpy/numpy#2878] opened 2013-01-02 11:18 UTC
Consider an operation between an array and a scalar:

```
  result = arr + scalar
```

Our job is to pick `result.dtype`.

In numpy before 1.6, if `arr` and `scalar` had the same basic kind of dtype (e.g. both some kind of float), then we simply used `arr.dtype` as the result dtype -- so in particular, if `arr.dtype` was `float32`, and `scalar.dtype` as `float64`, then the result was `float32`. Perhaps a surprising special case the first time you see it, but the rule is easy to remember, and provides important usability (since `scalar` here is usually a python literal, and python literals always have a fixed size that shouldn't be causing upcasting all the time).

In numpy 1.6, this was changed so that the value of `scalar` was also taken into account. So far as I can tell, the rule is now, if the `scalar` cannot be exactly represented using `arr.dtype`, then we go ahead and perform an upcast to a type that can hold both the value of `scalar` and is also consistent with `arr.dtype`. So for example it's entirely possible to have `int8 + int32` give you an `int16`. Examples:

```
In [19]: arr = np.array([1.], dtype=np.float32)

In [20]: (arr + (2**16-1)).dtype
Out[20]: dtype('float32')

In [21]: (arr + (2**16)).dtype
Out[21]: dtype('float64')

In [25]: arr = np.array([1.], dtype=np.int8)

In [26]: (arr + 127).dtype
Out[26]: dtype('int8')

In [27]: (arr + 128).dtype
Out[27]: dtype('int16')
```

This change is documented (a bit obscurely) here:
- http://docs.scipy.org/doc/numpy/reference/generated/numpy.result_type.html

It's also been discussed on the list:
- http://thread.gmane.org/gmane.comp.python.numeric.general/52044
- http://mail.scipy.org/pipermail/numpy-discussion/2011-September/058563.html
- http://thread.gmane.org/gmane.comp.python.numeric.general/47986

This change has caused a fair amount of confusion, and AFAICT everyone who's expressed an opinion has disliked it. But, in the discussions so far it's been hard to separate out from all the other changes made in 1.6 (or even tell which changes we're talking about), so no consensus has been reached. So, we need to decide what to do about this.

Some options:
1. Keep the current behaviour as is, `128 + int8 -> int16`
2. Revert to 1.5-and-earlier behaviour, `128 + int8 -> int8`
3. Revert to 1.5-and-earlier behaviour when it comes to selecting an output dtype, but then use `safe` casting rules when coercing the input to this dtype. (Right now IIUC we use the exact same rules for `scalar + arr` and `np.add(scalar, arr, dtype=selected_dtype)`, i.e., we treat the selected dtype as if it were explicitly requested and do an `unsafe` forced cast. The suggestion here is to treat the implicitly-selected output dtype as if it were implicitly selected, and use more conservative casting.) Result: `128 + int8 -> error`, (and you can use the full `np.add(...)` form if you really meant this).

Right now I like option 3 the best but am open to discussion.

CC: @delallea, @matthew-brett

**Comment by seberg** [comment] 2021-03-08 16:05
I am going to close the issue. It would have been absolutely fantastic if we would have been able to prioritized this back in the day, but that's life, and now I/we get headaches :).

Effectively, I *really* want this (and I guess at least now more people are starting to want it to, so lets see...). My guess is that the previous logic used "same-kind casting" for scalars.  Just to note it, there are two details/differences to the suggestions here:

* It seems most likely that the ancient version also did this for `np.int64(1000)` and 0-D arrays (i.e. use same-kind), which I wholeheartedly disagree with.  The original value-based introduction might have taped over some strange things there, although it was probably not the best way to tape it over; but you are always smarter later...
* Of course option 3 is great, but we have to see whether or not to prioritize having it.  It is not quite correct to say that this is using "safe" casting rules.  The problem is that the casting levels are unrelated to *values*.  To some degrees that can be seen as a technical decision, but it is very deep.  We could hope for a future with a "attempt-safe" type of rule, which uses a different casting function and errors if a value cannot be represented (only useful for integers probably).
  Fortunately, even if we want to press for it... Its probably not tricky, as it isn't really a cast at all! It is the coercion of a single scalar, so we might rather flag that in the scalar-coercion (read the DType's `setitem`) and defer adding an "attempt-safe" flag to casting later.  Maybe a more probably option would be that we add proper integer-rollover error flags.

**Comment by rgommers** [comment] 2021-03-10 14:09
Are you continuing this in a new issue @seberg? It sounds like this is the exact thing you're proposing on the Pandas mailing list right now?

**Comment by rgommers** [comment] 2021-03-10 15:38
More like "complexity was large enough that it took a major refactor to fully understand and unravel":)

Agreed it could be a good roadmap issue. And I guess we can put "in progress" behind it now.

**Comment by seberg** [comment] 2021-03-10 15:42
Honestly, for me it is important to call it "in progress", so I can argue why to use clunky code keeping legacy-duplication around, at least for now.  I probably cannot spend enough cycles alone on it to actually push it forward over a finish line. There is just too much grind...

**Comment by rgommers** [comment] 2021-03-10 15:47
>  I probably cannot spend enough cycles alone on it to actually push it forward over a finish line. There is just too much grind...

I'm unlikely to wrap my head around all the dtype refactor implementation work you've done, but I'm happy to help with review/discussion/testing/etc.

**Comment by albertopasqualetto** [comment] 2023-08-18 13:53
This could also help to solve #9464

**Comment by seberg** [comment] 2024-08-09 10:31
This has been fixed with NumPy 2.

**Closed by seberg** 2024-08-09 10:31 UTC
Labels: 54 - Needs decision, Proposal, component: numpy.dtype
