### ISSUE TITLE
BUG: repr/str of ndarray with zero size but non-trivial shape doesn't capture the array's structure

### ISSUE THREAD

**Issue by jpivarski** [numpy/numpy#21862] opened 2022-06-28 14:35 UTC
### Describe the issue:

Suppose we have an array whose total size is zero (product of `shape[i]` is zero) but the `shape != (0,)`. Below, I'm making one by slicing a non-empty array.

```python
>>> array = np.array([[1, 2, 3], [4, 5, 6]])
>>> array
array([[1, 2, 3],
       [4, 5, 6]])
>>> array.tolist()
[[1, 2, 3], [4, 5, 6]]
>>> array[:, :0]
array([], shape=(2, 0), dtype=int64)
>>> array[:, :0].tolist()
[[], []]
```

The `repr` looks like `[]`, but I would expect it to be `[[], []]`, as the list representation is. This is minor, but I thought I'd point it out.

I also didn't see anything like it in the current open issues.

### Reproduce the code example:

```python
See above.
```

### Error message:

```shell
No error message.
```

### NumPy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.22.4 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
```

**Comment by WarrenWeckesser** [comment] 2022-06-29 23:28
Thanks for reporting the issue, @jpivarski.  I haven't looked into the history, but I suspect this is intentional.

In general, there is no way to create a repr that can be used to reproduce an arbitrary array that has an axis with length 0 that is not the last axis.  For example,

```
In [28]: g = np.ones((2, 0, 3, 4))

In [29]: g.tolist()
Out[29]: [[], []]

In [30]: h = np.ones((0, 3, 4))

In [31]: h.tolist()
Out[31]: []

```
For `g`, the elements of the outer sequence have length 0.  The only way to represent that is `[]`; there is no way to indicate that, if there *were* elements at the next level, they would have shape (3, 4).  For `h`, that problem occurs at the top level.  The first axis has length 0, so the list representation must be `[]`, and that is all we can do.

So perhaps the simplest thing to do is what we do now: if any axis has length 0, show the array as `[]`, but also include the `shape` in the output.

**Comment by seberg** [comment] 2022-06-29 23:54
Duplicate of gh-16665.  There were a few option discussed there that may be worthwhile to pursue.  Just the list really would not due, since the `0` could be anywhere.
(Although the repr probably came from a time where numpy was much sloppier with empty arrays.)

**Closed by seberg** 2022-06-29 23:54 UTC
Labels: 00 - Bug
