### ISSUE TITLE
numpy validation error

### ISSUE THREAD

**Issue by bergen288** [numpy/numpy#16725] opened 2020-07-01 20:26 UTC
My issue is about numpy validation error. numpy package is installed successfully on AIX7.2.  Below is my script to install Python packages:
```r
pkg=$1
python -m pip install --no-build-isolation --no-index --find-links ./ $pkg >$pkg.log 2>&1 &
``` 
Below is the installation log:
```r
Looking in links: ./
Processing ./numpy-1.19.0.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: still running...
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517): started
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): still running...
  Building wheel for numpy (PEP 517): finished with status 'done'
  Created wheel for numpy: filename=numpy-1.19.0-cp37-cp37m-aix_7_2.whl size=7706816 sha256=38c8ee54b43f5e20e91e180e250f82afa7da6d8c0081b4d568ab0c49f285e5e8
  Stored in directory: /.cache/pip/wheels/b4/04/85/06f72c4f689e4767646bf1f18f5f103c3bce9e3bae68918194
Successfully built numpy
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.0
    Uninstalling numpy-1.19.0:
      Successfully uninstalled numpy-1.19.0
Successfully installed numpy-1.19.0
```
#### Reproducing code example:

```
import numpy as np
np.test('full')
import scipy
scipy.test()
```

#### Error message:

I started a batch python step with above 4 lines around 9am this morning.  Its output file hadn't been updated since 9:04am and the session was still running.  I was afraid it was in endless looping so it was killed around 3:45pm.  The log file is very large so I will attached it at the bottom.  Below are just first few lines. 
```
NumPy version 1.19.0
NumPy relaxed strides checking option: True

==================================== ERRORS ====================================
______________ ERROR collecting testing/tests/test_decorators.py _______________
/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/test_decorators.py:16: in <module>
    import nose  # noqa: F401
        KnownFailureException = <class 'numpy.testing._private.utils.KnownFailureException'>
        SkipTest   = <class 'unittest.case.SkipTest'>
        __builtins__ = <builtins>
        __cached__ = '/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/__pycache__/test_decorators.cpython-37.pyc'
        __doc__    = '\nTest the decorators from ``testing.decorators``.\n\n'
        __file__   = '/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/test_decorators.py'
        __loader__ = <_pytest.assertion.rewrite.AssertionRewritingHook object at 0xa00000000e1e508>
        __name__   = 'numpy.testing.tests.test_decorators'
        __package__ = 'numpy.testing.tests'
        __spec__   = ModuleSpec(name='numpy.testing.tests.test_decorators', loader=<_pytest.assertion.rewrite.AssertionRewritingHook object at 0xa00000000e1e508>, origin='/opt/freeware/lib64/python3.7/site-packages/numpy/testing/tests/test_decorators.py')
        assert_    = <function assert_ at 0xa000000013443a8>
        assert_raises = <function assert_raises at 0xa00000001344e58>
        dec        = <module 'numpy.testing._private.decorators' from '/opt/freeware/lib64/python3.7/site-packages/numpy/testing/_private/decorators.py'>
        pytest     = <module 'pytest' from '/opt/freeware/lib/python3.7/site-packages/pytest/__init__.py'>
        warnings   = <module 'warnings' from '/opt/freeware/lib64/python3.7/warnings.py'>
```

#### Scipy/Numpy/Python version information:
```
Python 3.7.6
numpy  1.19.0
scipy  1.5.0  
```
Below is the additional numpy test and error.  I posted this issue on scipy forum first and was told it is numpy issue.
```
import numpy as np
a = np.arange(15).reshape(3, 5)

Traceback (most recent call last):
  File "numpy.py", line 1, in <module>
    import numpy as np
  File "/home/xzhang/python/numpy.py", line 2, in <module>
    a = np.arange(15).reshape(3, 5)
AttributeError: module 'numpy' has no attribute 'arange'
```
[numpy.p3.txt](https://github.com/numpy/numpy/files/4860281/numpy.p3.txt)

**Comment by charris** [comment] 2020-07-01 23:31
> File "/home/xzhang/python/numpy.py", line 2, in <module>

Where does `numpy.py` come from?

**Comment by charris** [comment] 2020-07-01 23:32
What `pytest` version are you using?

**Comment by bergen288** [comment] 2020-07-02 12:48
@charris 
```
pytest                 5.4.3
```
numpy.py is my file with following 2 lines.  
```
import numpy as np
a = np.arange(15).reshape(3, 5)
```

**Comment by charris** [comment] 2020-07-02 16:49
What happens if you change the name of `numpy.py`?

**Comment by bergen288** [comment] 2020-07-02 19:52
There was an file access permission issue.  I have fixed it and rerun the following script (its name is mynumpytest.py in this case)
```
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
np.test('full')
```
There are 49 failures.  The detail log is attached at the bottom.  
Thanks.
```
=========================== short test summary info ============================
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_floor_div_warnings[op11-op21]
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_floor_div_warnings[op12-op22]
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_divmod_warnings[op11-op21]
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_divmod_warnings[op12-op22]
FAILED core/tests/test_half.py::TestHalf::test_half_fpe - AssertionError: Did...
FAILED core/tests/test_numeric.py::TestFloatExceptions::test_floating_exceptions
FAILED core/tests/test_umath.py::TestSpecialFloats::test_exp_values - Asserti...
FAILED core/tests/test_umath.py::TestExpm1::test_special - AssertionError: 
FAILED core/tests/test_umath.py::TestComplexFunctions::test_branch_cuts - Ass...
FAILED core/tests/test_umath.py::TestComplexFunctions::test_branch_cuts_complex64
FAILED core/tests/test_umath.py::test_nextafter - AssertionError
FAILED core/tests/test_umath.py::test_nextafterf - AssertionError
FAILED f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_in_from_2casttype[LONGDOUBLE]
FAILED f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_f_in_from_23casttype[LONGDOUBLE]
FAILED f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_c_in_from_23casttype[LONGDOUBLE]
FAILED f2py/tests/test_compile_function.py::test_f2py_init_compile[extra_args0]
FAILED f2py/tests/test_compile_function.py::test_f2py_init_compile[--noopt --debug]
FAILED f2py/tests/test_compile_function.py::test_f2py_init_compile[] - Assert...
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[t0]
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[t1]
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[s0]
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[s1]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[t0]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[t1]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[s0]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[s1]
FAILED lib/tests/test_format.py::test_large_archive - OSError: [Errno 28] No ...
FAILED lib/tests/test_format.py::test_empty_npz - OSError: [Errno 28] No spac...
FAILED lib/tests/test_format.py::test_unicode_field_names - OSError: [Errno 2...
FAILED lib/tests/test_io.py::TestSavezLoad::test_big_arrays - OSError: [Errno...
FAILED lib/tests/test_io.py::TestSavezLoad::test_savez_filename_clashes - Ass...
FAILED lib/tests/test_io.py::TestSavezLoad::test_not_closing_opened_fid - OSE...
FAILED lib/tests/test_io.py::TestSavezLoad::test_closing_fid - OSError: [Errn...
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt0]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt1]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt2]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt3]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt4]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt5]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt6]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt7]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt8]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt10]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt13]
FAILED linalg/tests/test_linalg.py::test_generalized_raise_multiloop - Assert...
FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[svd]
FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[eigh]
FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[cholesky]
FAILED tests/test_public_api.py::test_all_modules_are_expected - AssertionErr...
49 failed, 10861 passed, 81 skipped, 17 xfailed, 3 xpassed, 1 warning in 745.09s (0:12:25)
```
[mynumpytest.p3.txt](https://github.com/numpy/numpy/files/4866347/mynumpytest.p3.txt)

**Comment by bashtage** [comment] 2020-07-03 09:21
> FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[svd]
> FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[eigh]
> FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[cholesky]

Could you post more about these?

**Comment by bergen288** [comment] 2020-07-03 18:09
@bashtage 
The whole log file (mynumpytest.p3.txt) was attached at the bottom in my  previous post.

**Comment by bashtage** [comment] 2020-07-03 18:15
It seems to not raise LinAlgebraError on singular arrays. Do you get failures if you don't use an optimized Blas?

**Comment by charris** [comment] 2020-07-03 19:59
#16505 may be related, that fix will be in 1.19.1.

**Comment by bergen288** [comment] 2020-07-04 01:47
In the log, the following sample code gives me good result:
```
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
```
Only ```np.test('full')``` causes the issue.  Will the issue impact other package installation that requires numpy package such as scipy, statsmodels, et al?  If numpy is upgraded to 1.19.1, do I have to re-install scipy, statsmodels, and other packages?
Thanks.

**Comment by charris** [comment] 2020-07-04 11:07
> do I have to re-install scipy, statsmodels, and other packages?

No. The big question is if the problems get fixed.

**Comment by rossbar** [comment] 2020-07-10 19:54
@bergen288 if you are interested (and have the time) to see whether the problem is fixed on `master`, you could try the following procedure:

```bash
git clone https://github.com/numpy/numpy.git && cd numpy
python -m venv numpy_test_env
source numpy_test_env/bin/activate
python -m pip install -r test_requirements.txt
python runtests.py --mode full
```

**Comment by bergen288** [comment] 2020-07-10 21:03
My AIX server doesn't have direct internet access.  But I can download numpy-master.zip file and upload it to my AIX server.  Will it work?

**Comment by rossbar** [comment] 2020-07-10 21:17
Ah sorry I hadn't considered that - it makes things a bit more tedious as you'd need to have the testing dependencies (cython, pytest, and hypothesis at the very least,) installed as well. If you've already installed them with pip then they should (hopefully) be cached, but if not then having to manually install everything would be annoying.

**Comment by bergen288** [comment] 2020-07-11 02:38
@rossbar 
I manually installed all packages listed in ```test_requirements.txt``` and run the following command:
```
python -m pip install --no-build-isolation --no-index --find-links ../ -r test_requirements.txt >numpy-master.log 2>&1 &
```
Here is the list of numpy-master.log.
```
Looking in links: ../
Ignoring pickle5: markers 'python_version == "3.6" and platform_python_implementation != "PyPy"' don't match your environment
Requirement already satisfied: cython==0.29.21 in /opt/freeware/lib/python3.7/site-packages (from -r test_requirements.txt (line 1)) (0.29.21)
Requirement already satisfied: hypothesis==5.19.0 in /opt/freeware/lib/python3.7/site-packages (from -r test_requirements.txt (line 2)) (5.19.0)
Requirement already satisfied: pytest==5.4.3 in /opt/freeware/lib/python3.7/site-packages (from -r test_requirements.txt (line 3)) (5.4.3)
Requirement already satisfied: pytz==2020.1 in /opt/freeware/lib/python3.7/site-packages (from -r test_requirements.txt (line 4)) (2020.1)
Requirement already satisfied: pytest-cov==2.10.0 in /opt/freeware/lib/python3.7/site-packages (from -r test_requirements.txt (line 5)) (2.10.0)
Requirement already satisfied: pickle5 in /opt/freeware/lib64/python3.7/site-packages (from -r test_requirements.txt (line 6)) (0.0.11)
Requirement already satisfied: cffi in /opt/freeware/lib64/python3.7/site-packages (from -r test_requirements.txt (line 9)) (1.14.0)
Requirement already satisfied: mypy==0.782 in /opt/freeware/lib/python3.7/site-packages (from -r test_requirements.txt (line 14)) (0.782)
Requirement already satisfied: typing_extensions in /opt/freeware/lib/python3.7/site-packages (from -r test_requirements.txt (line 15)) (3.7.4.2)
Requirement already satisfied: sortedcontainers<3.0.0,>=2.1.0 in /opt/freeware/lib/python3.7/site-packages (from hypothesis==5.19.0->-r test_requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: attrs>=19.2.0 in /opt/freeware/lib/python3.7/site-packages (from hypothesis==5.19.0->-r test_requirements.txt (line 2)) (19.3.0)
Requirement already satisfied: packaging in /opt/freeware/lib/python3.7/site-packages (from pytest==5.4.3->-r test_requirements.txt (line 3)) (20.4)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /opt/freeware/lib/python3.7/site-packages (from pytest==5.4.3->-r test_requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: pluggy<1.0,>=0.12 in /opt/freeware/lib/python3.7/site-packages (from pytest==5.4.3->-r test_requirements.txt (line 3)) (0.13.1)
Requirement already satisfied: wcwidth in /opt/freeware/lib/python3.7/site-packages (from pytest==5.4.3->-r test_requirements.txt (line 3)) (0.2.5)
Requirement already satisfied: py>=1.5.0 in /opt/freeware/lib/python3.7/site-packages (from pytest==5.4.3->-r test_requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: more-itertools>=4.0.0 in /opt/freeware/lib/python3.7/site-packages (from pytest==5.4.3->-r test_requirements.txt (line 3)) (8.4.0)
Requirement already satisfied: coverage>=4.4 in /opt/freeware/lib64/python3.7/site-packages (from pytest-cov==2.10.0->-r test_requirements.txt (line 5)) (5.2)
Requirement already satisfied: pycparser in /opt/freeware/lib/python3.7/site-packages (from cffi->-r test_requirements.txt (line 9)) (2.20)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.3 in /opt/freeware/lib/python3.7/site-packages (from mypy==0.782->-r test_requirements.txt (line 14)) (0.4.3)
Requirement already satisfied: typed-ast<1.5.0,>=1.4.0 in /opt/freeware/lib64/python3.7/site-packages (from mypy==0.782->-r test_requirements.txt (line 14)) (1.4.1)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/freeware/lib/python3.7/site-packages (from packaging->pytest==5.4.3->-r test_requirements.txt (line 3)) (2.4.7)
Requirement already satisfied: six in /opt/freeware/lib/python3.7/site-packages/six-1.15.0-py3.7.egg (from packaging->pytest==5.4.3->-r test_requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: zipp>=0.5 in /opt/freeware/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.4.3->-r test_requirements.txt (line 3)) (3.1.0)
```
The last step is below:
```
nohup python runtests.py --mode full>runtests.log 2>&1 &
```
Attached are runtests.log and build.log files.  Lots of errors in each file.  Please take a look.
Thanks.

[runtests.log](https://github.com/numpy/numpy/files/4906160/runtests.log)
[build.log](https://github.com/numpy/numpy/files/4906161/build.log)

**Comment by rossbar** [comment] 2020-07-11 16:55
Wow, thanks for going through all the trouble to set this up on your system. Taking a look at the test summaries from the log files, it looks like the test failures related to linalg and the random generator have been resolved on master:

<details>
  <summary>1.19.0 tests summary (full log attached above as "mynumpytest.p3.txt")</summary>
<pre>
=========================== short test summary info ============================
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_floor_div_warnings[op11-op21]
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_floor_div_warnings[op12-op22]
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_divmod_warnings[op11-op21]
FAILED core/tests/test_datetime.py::TestDateTime::test_timedelta_divmod_warnings[op12-op22]
FAILED core/tests/test_half.py::TestHalf::test_half_fpe - AssertionError: Did...
FAILED core/tests/test_numeric.py::TestFloatExceptions::test_floating_exceptions
FAILED core/tests/test_umath.py::TestSpecialFloats::test_exp_values - Asserti...
FAILED core/tests/test_umath.py::TestExpm1::test_special - AssertionError: 
FAILED core/tests/test_umath.py::TestComplexFunctions::test_branch_cuts - Ass...
FAILED core/tests/test_umath.py::TestComplexFunctions::test_branch_cuts_complex64
FAILED core/tests/test_umath.py::test_nextafter - AssertionError
FAILED core/tests/test_umath.py::test_nextafterf - AssertionError
FAILED f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_in_from_2casttype[LONGDOUBLE]
FAILED f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_f_in_from_23casttype[LONGDOUBLE]
FAILED f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_c_in_from_23casttype[LONGDOUBLE]
FAILED f2py/tests/test_compile_function.py::test_f2py_init_compile[extra_args0]
FAILED f2py/tests/test_compile_function.py::test_f2py_init_compile[--noopt --debug]
FAILED f2py/tests/test_compile_function.py::test_f2py_init_compile[] - Assert...
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[t0]
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[t1]
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[s0]
FAILED f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[s1]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[t0]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[t1]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[s0]
FAILED f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[s1]
FAILED lib/tests/test_format.py::test_large_archive - OSError: [Errno 28] No ...
FAILED lib/tests/test_format.py::test_empty_npz - OSError: [Errno 28] No spac...
FAILED lib/tests/test_format.py::test_unicode_field_names - OSError: [Errno 2...
FAILED lib/tests/test_io.py::TestSavezLoad::test_big_arrays - OSError: [Errno...
FAILED lib/tests/test_io.py::TestSavezLoad::test_savez_filename_clashes - Ass...
FAILED lib/tests/test_io.py::TestSavezLoad::test_not_closing_opened_fid - OSE...
FAILED lib/tests/test_io.py::TestSavezLoad::test_closing_fid - OSError: [Errn...
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt0]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt1]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt2]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt3]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt4]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt5]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt6]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt7]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt8]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt10]
FAILED linalg/tests/test_linalg.py::TestMatrixPower::test_exceptions_not_invertible[dt13]
FAILED linalg/tests/test_linalg.py::test_generalized_raise_multiloop - Assert...
FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[svd]
FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[eigh]
FAILED random/tests/test_generator_mt19937.py::TestRandomDist::test_multivariate_normal[cholesky]
FAILED tests/test_public_api.py::test_all_modules_are_expected - AssertionErr...
49 failed, 10861 passed, 81 skipped, 17 xfailed, 3 xpassed, 1 warning in 745.09s (0:12:25)
</pre>
</details>

<details>
  <summary>master test summary (full log attached above as "runtests.log")</summary>
<pre>
=========================== short test summary info ============================
FAILED numpy/core/tests/test_numeric.py::TestFloatExceptions::test_floating_exceptions
FAILED numpy/core/tests/test_umath.py::TestSpecialFloats::test_exp_values - A...
FAILED numpy/core/tests/test_umath.py::TestExpm1::test_special - AssertionErr...
FAILED numpy/core/tests/test_umath.py::TestComplexFunctions::test_branch_cuts
FAILED numpy/core/tests/test_umath.py::TestComplexFunctions::test_branch_cuts_complex64
FAILED numpy/core/tests/test_umath.py::test_nextafter - AssertionError
FAILED numpy/core/tests/test_umath.py::test_nextafterf - AssertionError
FAILED numpy/f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_in_from_2casttype[LONGDOUBLE]
FAILED numpy/f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_f_in_from_23casttype[LONGDOUBLE]
FAILED numpy/f2py/tests/test_array_from_pyobj.py::TestSharedMemory::test_c_in_from_23casttype[LONGDOUBLE]
FAILED numpy/f2py/tests/test_compile_function.py::test_f2py_init_compile[extra_args0]
FAILED numpy/f2py/tests/test_compile_function.py::test_f2py_init_compile[--noopt --debug]
FAILED numpy/f2py/tests/test_compile_function.py::test_f2py_init_compile[] - ...
FAILED numpy/f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[t0]
FAILED numpy/f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[t1]
FAILED numpy/f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[s0]
FAILED numpy/f2py/tests/test_return_character.py::TestF77ReturnCharacter::test_all[s1]
FAILED numpy/f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[t0]
FAILED numpy/f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[t1]
FAILED numpy/f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[s0]
FAILED numpy/f2py/tests/test_return_character.py::TestF90ReturnCharacter::test_all[s1]
FAILED numpy/lib/tests/test_format.py::test_large_archive - OSError: [Errno 2...
FAILED numpy/lib/tests/test_format.py::test_empty_npz - OSError: [Errno 28] N...
FAILED numpy/lib/tests/test_format.py::test_unicode_field_names - OSError: [E...
FAILED numpy/lib/tests/test_io.py::TestSavezLoad::test_big_arrays - OSError: ...
FAILED numpy/lib/tests/test_io.py::TestSavezLoad::test_savez_filename_clashes
FAILED numpy/lib/tests/test_io.py::TestSavezLoad::test_not_closing_opened_fid
FAILED numpy/lib/tests/test_io.py::TestSavezLoad::test_closing_fid - OSError:...
FAILED numpy/lib/tests/test_io.py::TestSavezLoad::test_closing_zipfile_after_load
FAILED numpy/random/tests/test_extending.py::test_cffi - AttributeError: func...
30 failed, 11669 passed, 87 skipped, 20 xfailed, 3 xpassed, 1 warning in 1046.58s (0:17:26)
</pre>
</details>

**Comment by seberg** [comment] 2021-07-09 03:40
Closing, since this issue is probably about mainly about a correct install, and I guess it was most likely fixed.  If not, please let us know here (or just open a new issue).

**Closed by seberg** 2021-07-09 03:40 UTC
Labels: 57 - Close?
