### ISSUE TITLE
bitwise_and.reduce() only bitwise-ands bit 1

### ISSUE THREAD

**Issue by o-smirnov** [numpy/numpy#5414] opened 2015-01-02 15:51 UTC
All other bits come out 0:

```
In [2]: a=numpy.array([0x1,0x3])

In [3]: numpy.bitwise_and.reduce(a)
Out[3]: 1

In [4]: a=numpy.array([0x2,0x3])

In [5]: numpy.bitwise_and.reduce(a)
Out[5]: 0
```

Surely this is because ```bitwise_and.identity``` is 1, when it should be -1 (i.e. all bits set).

**Comment by charris** [comment] 2015-01-02 16:31
Duplicate of #5250.

**Closed by charris** 2015-01-02 16:31 UTC
