### ISSUE TITLE
Behavior of the absolute value function

### ISSUE THREAD

**Issue by ChristophWiesmeyr** [numpy/numpy#5018] opened 2014-08-29 10:07 UTC
I have just spent quite some time debugging my code because the absolute value function might return negative values. See the following working example:

```
import numpy as np
np.array([-32768,-3000],dtype=np.dtype('int16'))
np.abs(_)
```

While the second value is converted to +3000 as expected, the second value is left untouched. I understand that +32768 is out of range for this datatype but I am interested whether returning -32768 is a concious design choice as I was expecting positive values from this function no matter what.

**Comment by seberg** [comment] 2019-05-14 05:04
Closing as duplicate of 5657 (since it is abs(INT_MIN) is a bit special), the other bug mentioned in `np.allclose` hsa been fixed, as mentioned in the last comment.

**Closed by seberg** 2019-05-14 05:04 UTC
Labels: 00 - Bug, 54 - Needs decision, component: numpy.core
