### ISSUE TITLE
BUG: concatenating datetime with NAT switches array to object mode 

### ISSUE THREAD

**Issue by axil** [numpy/numpy#23670] opened 2023-04-27 11:30 UTC
### Describe the issue:

When I concatenate an array of datetimes with a not-a-time scalar twice, it falls back to object mode.

### Reproduce the code example:

```python
This works correctly:

>>> import numpy as np
>>> a = np.array([np.datetime64('2023-04-27')])
>>> np.r_[a, np.datetime64('nat'), a]

array(['2023-04-27',        'NaT', '2023-04-27'], dtype='datetime64[D]')

This fails:

>>> import numpy as np
>>> a = np.array([np.datetime64('2023-04-27')])
>>> np.r_[a, np.datetime64('nat'), a, np.datetime64('nat')]

array([datetime.date(2023, 4, 27), None, datetime.date(2023, 4, 27), None],
      dtype=object)
```

### Runtime information:

1.24.3
3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]

[{'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': 'C:\\Users\\<username>\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.21'}]

### Context for the issue:

It breaks my regression tests.

**Comment by ngoldbaum** [comment] 2023-04-27 15:06
I'm not sure why this is happening, but as a workaround, making sure all elements you're trying to concatenate are arrays does what you expect:

```python
>>> np.r_[a, np.array(np.datetime64('nat')), a, np.array(np.datetime64('nat'))]
array(['2023-04-27',        'NaT', '2023-04-27',        'NaT'],
      dtype='datetime64[D]'
```

**Comment by ngoldbaum** [comment] 2023-04-27 16:17
Looked a little closer, ultimately this is happening because of this difference:

```python
>>> arraytypes = [np.dtype('<M8[D]'), np.dtype('<M8[D]')]
>>> scalartypes = [np.dtype('<M8'), np.dtype('<M8')]
>>> print(np.core.numerictypes.find_common_type(arraytypes, scalartypes))
object
print(np.core.numerictypes.find_common_type(arraytypes, scalartypes[1:]))
None
```

If you take a look at `find_common_types`, this behavior ultimately comes from the `_can_coerce_all` helper:

https://github.com/numpy/numpy/blob/4d5e600b799c68fda9c2f06e37fcb3b8af3b18ab/numpy/core/numerictypes.py#L573-L586

Since it unconditionally returns `dtypelist[0]` if there is only one type, the case where there's only one scalar passed to `np.r_` doesn't coerce to object, while if there's more than one scalar type, `_can_coerce_all` can't find a coerceable dtype, so it returns `None`, and `find_common_dtype` says that the common dtype is `object`. The reason it can't find a coerceable dtype is because datetimes are explicitly excluded from `__test_types` defined above `_can_coerce_all`.

Unfortunately I don't have enough context about this code to say what the appropriate fix is. Maybe there should be a check for whether `dtypelist[0]` is in `__test_types` before returning it?

**Comment by seberg** [comment] 2023-04-27 16:34
gh-22539 should contain the fix since the problem is that `find_common_types` is awful. That could be liberated since I don't know if the deprecation should be done timely or not.

**Comment by seberg** [comment] 2023-05-17 13:32
Oh, Chuck was nice enough to push through that deprecation and it contained the fix, so closing.

**Closed by seberg** 2023-05-17 13:32 UTC
Labels: 00 - Bug
