### ISSUE TITLE
-shared flag missing from gfortran link line of lapack_lite numpy v1.16.0, fedora 28, python 2.7.15

### ISSUE THREAD

**Issue by burlen** [numpy/numpy#12799] opened 2019-01-18 21:45 UTC
I am having a build failure during linking of `lapack_lite` module. The `-shared` flag is not included in the link line, and the linker is looking for a `main` function. I am compiling against a Python in a non-system location, and am also setting various build flags through the environment. None the less, the `-shared` flag should be added in the numpy configuration.

### Reproducing code example:
```bash
$ 'env' 'CC=/usr/lib64/ccache/gcc' 'CXX=/usr/lib64/ccache/g++' 'CPPFLAGS= -I/work/apps/teca-deps/2.1.3/include' 'CFLAGS=-I/work/apps/teca-deps/2.1.3/include  -O3 -march=native -mtune=native -DNDEBUG' 'CXXFLAGS=-I/work/apps/teca-deps/2.1.3/include  -O3 -march=native -mtune=native -DNDEBUG' 'LDFLAGS=-L//work/apps/teca-deps/2.1.3/lib -L/work/apps/teca-deps/2.1.3/lib64' 'LD_LIBRARY_PATH=/work/apps/teca-deps/2.1.3/lib/:/work/apps/teca-deps/2.1.3/lib64/:' 'DYLD_LIBRARY_PATH=/work/apps/teca-deps/2.1.3/lib/:/work/apps/teca-deps/2.1.3/lib64/:' 'PKG_CONFIG_PATH=/work/apps/teca-deps/2.1.3/lib/pkgconfig:/work/apps/teca-deps/2.1.3/lib64/pkgconfig:' 'PATH=.:/work/apps/teca-deps/2.1.3/bin/:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/bloring/.local/bin:/home/bloring/bin' 'PYTHONHOME=/work/apps/teca-deps/2.1.3' 'MPLBACKEND=Agg' 'PYTHONPATH=/work/apps/teca-deps/2.1.3/lib:/work/apps/teca-deps/2.1.3/lib/python2.7/site-packages/' '/work/apps/teca-deps/2.1.3/bin/python' 'setup.py' 'build' 'install' '--prefix=/work/apps/teca-deps/2.1.3'
```

### Error message:
```
building 'numpy.linalg.lapack_lite' extension
compiling C sources
C compiler: /usr/lib64/ccache/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/work/apps/teca-deps/2.1.3/include -O3 -march=native -mtune=native -DNDEBUG -I/work/apps/teca-deps/2.1.3/include -fPIC

creating build/temp.linux-x86_64-2.7/numpy/linalg
creating build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite
compile options: '-DNO_ATLAS_INFO=-1 -I/usr/include -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/work/apps/teca-deps/2.1.3/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/common -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-2.7/numpy/core/src/common -Ibuild/src.linux-x86_64-2.7/numpy/core/src/npymath -c'
gcc: numpy/linalg/lapack_litemodule.c
gcc: numpy/linalg/lapack_lite/python_xerbla.c
/usr/bin/gfortran -Wall -g -L//work/apps/teca-deps/2.1.3/lib -L/work/apps/teca-deps/2.1.3/lib64 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o -L/usr/lib64/atlas -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/work/apps/teca-deps/2.1.3/lib -Lbuild/temp.linux-x86_64-2.7 -ltatlas -ltatlas -ltatlas -ltatlas -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -L//work/apps/teca-deps/2.1.3/lib -L/work/apps/teca-deps/2.1.3/lib64 build/temp.linux-x86_64-2.7/numpy/linalg/lapack_litemodule.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o -L/usr/lib64/atlas -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/work/apps/teca-deps/2.1.3/lib -Lbuild/temp.linux-x86_64-2.7 -ltatlas -ltatlas -ltatlas -ltatlas -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/numpy/linalg/lapack_lite.so" failed with exit status 1
```

### Numpy/Python version information:
This is a builld issue on v1.16.0 tag

### Proposed fix
```diff
diff --git a/numpy/distutils/fcompiler/gnu.py b/numpy/distutils/fcompiler/gnu.py
index 81769e562..b93b42c12 100644
--- a/numpy/distutils/fcompiler/gnu.py
+++ b/numpy/distutils/fcompiler/gnu.py
@@ -306,7 +306,7 @@ class Gnu95FCompiler(GnuFCompiler):
                           "-fno-second-underscore"] + _EXTRAFLAGS,
         'compiler_fix' : [None, "-Wall",  "-g","-ffixed-form",
                           "-fno-second-underscore"] + _EXTRAFLAGS,
-        'linker_so'    : ["<F90>", "-Wall", "-g"],
+        'linker_so'    : ["<F90>", "-Wall", "-g", "-shared"],
         'archiver'     : ["ar", "-cr"],
         'ranlib'       : ["ranlib"],
         'linker_exe'   : [None, "-Wall"]
```

**Comment by charris** [comment] 2019-01-20 02:38
I suppose the problem is G95 here.  I'm not convinced this is the correct solution, compare the `get_flags_linker_so` method for `Gnu95FCompiler` and `GnuFCompiler`. Note that in the latter case the shared flag is not used on Darwin. I don't know why `get_flags_linker_so` method was not just inherited, but suppose there was a good reason.

**Comment by burlen** [comment] 2019-01-22 17:10
The above patch is apparently in the wrong place as it breaks mac build. I closed the merge request as I do not have the resources to diagnose problems on non linux systems.

**Comment by rgommers** [comment] 2019-03-04 00:46
> export NPY_DISTUTILS_APPEND_FLAGS=1

That is the correct thing to do; either that or specify *all* the linker flags you need in `LDFLAGS`.

So not a bug, but I'll leave this open because we should fix the docs (https://www.numpy.org/devdocs/reference/distutils.html should have an example with `LDFLAGS` and `NPY_DISTUTILS_APPEND_FLAGS`).

**Comment by rgommers** [comment] 2022-02-18 05:31
Appending flags (which `NPY_DISTUTILS_APPEND_FLAGS=1` enabled) is now the default, so I'll close this issue.

**Closed by rgommers** 2022-02-18 05:31 UTC
Labels: 04 - Documentation, component: numpy.distutils
