### ISSUE TITLE
numpy.float64.__round__ is incompatible with float.__round__ in python3

### ISSUE THREAD

**Issue by sam-s** [numpy/numpy#11557] opened 2018-07-13 18:41 UTC
In Python 3, `round(_float_)` returns an **integer**, but `round(_np.float64_)` returns a **float**:
```
>>> np.float64(1).__round__()
1.0
>>> 1.0.__round__()
1
```
The result is that if a [`np.float64`](https://docs.scipy.org/doc/numpy/user/basics.types.html) seeps into my data, the stock [`round`](https://docs.python.org/3/library/functions.html#round) produces unexpected results: `round(x)` can be an integer or a float depending on whether `x` is a regular `float` or a `np.float64`.
```
>>> [type(round(t(1))).__name__ for t in [float, np.float16, np.float32, np.float64, np.float128]]
['int', 'float16', 'float32', 'float64', 'float128']
```

The distinction does matter, e.g., [`np.partition`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.partition.html) raises `TypeError: Partition index must be integer`.

PS. Python 3.7.0, numpy 1.14.5

**Comment by simongibbons** [comment] 2018-07-25 06:12
I got bitten by this today as well.

**Comment by mhvk** [comment] 2018-07-25 15:38
I've been caught by this as well, so it may be good to think what would be exactly what is wanted here.  I think it simply is that if the python `round` is called on a numpy object, it should have as python would - the easiest might be for our definition of `__round__` to be, effectively, `round(float(self))`. That would also ensure we do not return an `int` on python2 (which is of course where this all came from...).

**Comment by eric-wieser** [comment] 2018-07-25 15:47
We should be careful here to match whatever behavior we choose for #6248 - in particular, the dtype of `round(float64)`  - should it always just return object arrays?

**Comment by mhvk** [comment] 2018-07-25 17:44
Hmm, good point.  I think python3 sees `round` as a type converter like `int`; if so, there is no reason it should work for arrays. (And it doesn't, so no worries about backwards compatibility.) Getting object arrays would certainly be more surprising... 

Hadn't quite realized this is a duplicate of #5700 and #3511...

**Comment by mhvk** [comment] 2019-03-22 21:39
It does seem that now that we're python3 only, we should just adjust our scalar `__round__` method to match the behaviour of python's `round`. I'm going ahead and remove the "needs decision" label - of course, someone still needs to have the time to actually implement this...

Also, am on purpose keeping it separate from discussion of ufuncs (`around`, `ceil`, `floor`,...)

**Comment by matthew-brett** [comment] 2019-03-23 10:24
Isn't this going to introduce some problems with back-compatibility?

**Comment by mhvk** [comment] 2019-03-23 14:19
@matthew-brett - I'm not sure what is worse: `round(1.)` giving a different ttype then `round(np.float64(1.))` or changing the outcome of the latter (where that of the first has changed already by going to python3). Especially since `int` behave much more like float than vice versa.

Of course, really we should have done this for python3 when it came out...

p.s.  Just in case: the behaviour of `np.around` and `scalar.round()` would not change.

**Comment by serhiy-storchaka** [comment] 2019-10-31 11:20
Note that `round(1., 0)` and `round(1., None)` returns different types.

**Comment by seberg** [comment] 2020-05-14 12:39
Round was fixedrecently in master for the scalars.

**Closed by seberg** 2020-05-14 12:39 UTC
Labels: 00 - Bug, 50 - Duplicate, component: numpy.core
