### ISSUE TITLE
BUG: Multiprocessing issue for .npz files

### ISSUE THREAD

**Issue by Th-Fo** [numpy/numpy#18124] opened 2021-01-05 17:24 UTC
Accessing the entries of a NpzFile object can raise a BadZipFile error (for an intact .npz file) under the following circumstances:
* First, `np.load('my_file.npz')` is called in some process.
* Afterwards, this process is forked, e.g. via multiprocessing module.
* Several of these processes (either multiple child processes, or the parent plus >=1 child processes) access its entries after forking.
The occurrence of this error depends on the .npz file, on the order in which the entries are read out, and apparently also on the machine (on the RAM size?), but seems deterministic for a certain configuration. It happens on all Python and NumPy versions I have tested, including Python 3.9.1 and NumPy 1.19.2 (newest versions available for me). It is not clear to me whether the problem is on the level of Numpy, zipfile, or somewhere else.

Minimal example:

a) Generating the dataset. This part is a bit "tricky" because different .npz files are needed to trigger the bug on different machines; however, for all machines I have tried, I was able to find a .npz file which reproduced the bug (the Python/NumPy version didn't play a role then).

Among the easiest configurations with a high chance to trigger the bug are

```
# especially for machines with <=32 GB RAM
import numpy as np
np.savez(
		'data.npz',
		item_0=np.random.randn(10000),
		item_1=np.random.randn(200),
		item_2=np.random.randn(10000)
)
```

and

```
# especially for machines with >150 GB RAM
import numpy as np
np.savez(
		'data.npz',
		item_0=np.random.randn(100000),
		item_1=np.random.randn(200000)
)
```

If this doesn't work, try

```
import collections
import numpy as np

typical_size = 1000 # also try 10000 or 100000
sizes = np.round(-typical_size*np.log(np.random.rand(20))).astype(int)

np.savez(
		'data.npz',
		**collections.OrderedDict([
			('item_%d'%idx, np.random.randn(size))
			for idx, size in enumerate(sizes)
		])
)
```

b) apply the "recipe" described in the beginning:

```
import multiprocessing
import numpy as np
import time

def func(data):
	for _ in data.values(): # accessing the .npz file from the child processes
		time.sleep(0.2) # to make the access order deterministic

data = np.load('data.npz') # loading the .npz file in the parent process
for _ in range(2):
	# launching child processes inside this loop, passing data as an argument to the target function
	subproc = multiprocessing.Process(target=func, args=[data])
	subproc.start()
	time.sleep(0.1) # to make the access order deterministic
```

result:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "minimal_example.py", line 6, in func
    for _ in data.values():
  File "/usr/lib64/python3.6/_collections_abc.py", line 762, in __iter__
    yield self._mapping[key]
  File "/usr/lib64/python3.6/site-packages/numpy/lib/npyio.py", line 256, in __getitem__
    magic = bytes.read(len(format.MAGIC_PREFIX))
  File "/usr/lib64/python3.6/zipfile.py", line 872, in read
    data = self._read1(n)
  File "/usr/lib64/python3.6/zipfile.py", line 962, in _read1
    self._update_crc(data)
  File "/usr/lib64/python3.6/zipfile.py", line 890, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'item_1.npy'
```

Remarks:
* The error does not occur if np.load is called within each child process, or if the parent process passes an own NpzFile instance to each child process. This might serve as a quick fix, but at least doubles the runtime for calling np.load if both the parent and the child process need to access the considered file, and might be complicated to implement for applications into which multiprocessing is deeply built in.

* Dependent on the .npz file and the machine, slightly different errors can occur, including:

  zipfile.BadZipFile: Bad magic number for file header
  zipfile.BadZipFile: Truncated file header
  zipfile.BadZipFile: File name in directory 'item_2.npy' and header b'it' differ.
  EOFError

* For a fixed order in which the entries are read out, the entries whose readout cause an error are deterministic. If the exception is caught and readout is repeated, accessing an entry succeeds or fails always like it did for the first time (I guess the reason for this is in the caching). This behavior can be seen, for example, by replacing func in the minimal example with

```
import traceback
def func(data):
	for key in 3*list(data.keys()):
		try:
			data[key]
		except Exception:
			traceback.print_exc()
		time.sleep(0.2) # to make access order deterministic
		pass
```

**Comment by eedalong** [comment] 2021-08-09 03:32
+1

**Comment by chevalierNoir** [comment] 2023-06-23 00:39
Is there a workaround for this bug? I'm having similar issues.

**Comment by rkern** [comment] 2023-06-23 01:19
The workaround is to avoid calling `np.load()` until you get into the worker processes. On an `.npz` file, you get no important savings by loading it in the main process because loading the actual array data is delayed until you access each one. If you want to load all of the data into memory in the parent process and have all of the child processes inherit it via the fork, preload all of the arrays into a dictionary and pass that to the children.

I can reduce the problem down to a numpy-free script that only uses `zipfile.ZipFile`. It's a problem with that object; it does not work well across process forks, presumably because the forks will share open file descriptors held by `ZipFile` (which is in turn held by the `NpzFile` object returned by `np.load()`).

```
❯ cat zipfile_test.py
import multiprocessing
import time
import zipfile


def func(zf, namelist):
    for name in namelist:
        with zf.open(name) as f:
            _ = f.read() # accessing the .npz file from the child processes
        time.sleep(0.2) # to make the access order deterministic

zf = zipfile.ZipFile('data.npz', allowZip64=True)
namelist = zf.namelist()
for _ in range(2):
    # launching child processes inside this loop, passing data as an argument to the target function
    subproc = multiprocessing.Process(target=func, args=[zf, namelist])
    subproc.start()
    time.sleep(0.1) # to make the access order deterministic

❯ python zipfile_test.py
Process Process-2:
Traceback (most recent call last):
  File "/home/rkern/.edm/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rkern/.edm/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "zipfile_test.py", line 9, in func
    _ = f.read() # accessing the .npz file from the child processes
  File "/home/rkern/.edm/envs/py38/lib/python3.8/zipfile.py", line 926, in read
    buf += self._read1(self.MAX_N)
  File "/home/rkern/.edm/envs/py38/lib/python3.8/zipfile.py", line 1030, in _read1
    self._update_crc(data)
  File "/home/rkern/.edm/envs/py38/lib/python3.8/zipfile.py", line 958, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'item_1.npy'
Process Process-1:
Traceback (most recent call last):
  File "/home/rkern/.edm/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rkern/.edm/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "zipfile_test.py", line 9, in func
    _ = f.read() # accessing the .npz file from the child processes
  File "/home/rkern/.edm/envs/py38/lib/python3.8/zipfile.py", line 926, in read
    buf += self._read1(self.MAX_N)
  File "/home/rkern/.edm/envs/py38/lib/python3.8/zipfile.py", line 1010, in _read1
    data = self._read2(n)
  File "/home/rkern/.edm/envs/py38/lib/python3.8/zipfile.py", line 1043, in _read2
    raise EOFError
EOFError
```

**Comment by mallorbc** [comment] 2023-10-19 01:33
I am having an issue like this inside a pytorch dataloader

**Comment by adosar** [comment] 2024-03-23 21:58
@mallorbc Same issue here.

**Comment by DaniilBoiko** [comment] 2024-03-29 22:17
For PyTorch data loader it looks like something like this works
```python
def worker_init_fn(worker_id):
    worker_info = torch.utils.data.get_worker_info()
    dataset = worker_info.dataset

    # open all files again in each worker
    dataset.reopen_files()


train_loader = DataLoader(
   ..., worker_init_fn=worker_init_fn
)
```

And define `.reopen_files()` method in your dataset class:
```python
def __init__(self):
    #code
    self.files_open = {
        file: np.load(
            file, allow_pickle=True
        ) for file in tqdm(self.files)
    }

def reopen_files(self):
    self.files_open = {
        file: np.load(
            file, allow_pickle=True
        ) for file in tqdm(self.files)
    }
```

**Comment by Jovendish** [comment] 2024-05-30 06:44
@mallorbc Same issue

**Comment by rkern** [comment] 2024-05-30 14:01
As the issue is with the stdlib's `zipfile.ZipFile` object and nothing specific to numpy, there is little we can do about it, so I am going to close this issue.

**Closed by rkern** 2024-05-30 14:01 UTC

**Comment by rkern** [comment] 2024-06-25 20:01
[It's already reported and is not considered a bug to be fixed.](https://github.com/python/cpython/issues/83544) It's just a limitation of `ZipFile`.

**Comment by rkern** [comment] 2024-10-21 18:17
It works by making sure that each forked worker process opens a fresh `ZipFile` that does not share the invalid file descriptors from the parent process.

As for whether it is necessary to open the files under `__init__`, it depends on whether or not one needs access to those contents by operations done in the parent process. If you don't also do it in `__init__`, then the data loader object is not complete and ready to use in the parent process and can _only_ be used in worker processes. Which may be fine for your use case, but not others.
