### ISSUE TITLE
ValueError: scale < 0,numpy.random.normal

### ISSUE THREAD

**Issue by LiuYiChen0704** [numpy/numpy#14897] opened 2019-11-13 12:37 UTC
My numpy version is 1.17.4 .When I use numpy.random.normal and scale =nan ,It is ok.
But When I change numpy'version to 1.16.1,it raise error,
Error is:
```
  File "mtrand.pyx", line 1661, in mtrand.RandomState.normal
ValueError: scale < 0
```
Why?

**Comment by bashtage** [comment] 2019-12-04 00:13
The method used to validate inputs was changed in 1.17.  It may be too string in these cases.  It often rules out NaNs since these can produce infinite loops in some generators (but not this one).

**Comment by bashtage** [comment] 2019-12-04 00:15
Formally it is because the test is now `not scale >= 0`, which picks up negatives and NaNs, rather than `scale < 0` which lets NaNs pass.

**Comment by bashtage** [comment] 2019-12-04 00:17
@mattip  This is a regression that will need some careful thought, testing across different distributions, and a fix (I'll take it on) for RandomState to support the stream guarantee.

**Comment by eric-wieser** [comment] 2019-12-04 01:25
I'm confused - @bashtage is describing 1.17 as too strict, yet @LiuYiChen0704 is describing 1.16 as the one that complains.  Is someone saying the wrong thing?

**Comment by bashtage** [comment] 2019-12-04 08:26
A bit of investigating shows no issue:

```
import numpy as np
np.random.normal(0, np.nan)
nan

np.__version__
'1.17.4'

np.random.normal(np.nan, np.nan, size=10)
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
```

```
import numpy as np
np.random.normal(0, np.nan)
nan

np.__version__
 '1.16.5'

np.random.normal(np.nan, np.nan,size=10)
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
```

@LiuYiChen0704 could you provide an example the reproduces your problem?

**Comment by bashtage** [comment] 2019-12-04 09:17
Cannot repro on 1.16.1 either

```
In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.16.1'

In [3]: np.random.normal(np.nan, np.nan, size=10)
Out[3]: array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
```

**Comment by mattip** [comment] 2019-12-11 08:56
Closing. The original reporter did not clarify how to reporduce, and guessing was not productive. If needed, please reopen.

**Closed by mattip** 2019-12-11 08:56 UTC
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.random
