### ISSUE TITLE
histogram2d example error

### ISSUE THREAD

**Issue by maluethi** [numpy/numpy#10922] opened 2018-04-17 14:04 UTC
I found that the example code for the histogram2d has an issue when adapted. The code below works for a symmetric amount of bins. But if one changes the number of bins (e.g. removing a bin on [line 655](https://github.com/numpy/numpy/blob/4092a9e160cc247a4a45724579a0c829733688ca/numpy/lib/twodim_base.py#L655) ` xedges = [0, 1, 1.5, 3])` in only one dimensions, the example raises an exception: 

`TypeError: Axes don't match array shape`

My understanding of this error: This is due to the fact that ` im.set_data(xcenters, ycenters, H)` on line 696 is erroneous. The `set_data` functions behaves counter-intuitive and sets data in screen coordinates and not in plot coordinates, see theses [lines](https://github.com/matplotlib/matplotlib/blob/e18af550cf20c8c5e4499720afee2c1e38c020db/lib/matplotlib/image.py#L945) in matplotlib. The fix for this is to invert the xedges, yedges order in the `set_data` call. With that adjustment the code works fine for an asymmetric number of bins. Although, I don't understand why the data is displayed correctly in the symmetric bin number case.

I am happy to fix this (by inverting the order), but am unsure about how to move on. Is it OK to just go along, fix it, and create a pull request? Can anyone guide me along?

https://github.com/numpy/numpy/blob/4092a9e160cc247a4a45724579a0c829733688ca/numpy/lib/twodim_base.py#L689-L702

**Comment by mattip** [comment] 2018-04-18 06:28
Duplicate of #8115 This is an old version of that file, it was updated in PR #8121 which was merged Oct 8, 2016. Please reopen if there are more issues with the documentation here.

**Closed by mattip** 2018-04-18 06:28 UTC
