### ISSUE TITLE
Original error was: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by aweng126** [numpy/numpy#16719] opened 2020-07-01 14:23 UTC
### problem description

I was trying to learn lambda function of AWS,  I packaged library and source code to a deployment package and upload thme, so I can invoke it  .however ,when it comes to the matmul function ,it didn't work, I had try third version of numpy, none of them works,  python version is python3.7, numpy version is 1.16,1.18,1.19. the lambda code is very esay,[matmul function](https://github.com/kmu-bigdata/serverless-faas-workbench/blob/master/aws/cpu-memory/matmul/lambda_function.py)
```
import numpy as np
from time import time


def matmul(n):
    A = np.random.rand(n, n)
    B = np.random.rand(n, n)

    start = time()
    C = np.matmul(A, B)
    latency = time() - start
    return latency


def lambda_handler(event, context):
    n = int(event['n'])
    result = matmul(n)
    print(result)
    return result
```
and this is the log cotent
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/var/lang/bin/python3.7",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

END RequestId: c4fc9fea-2802-4ff0-b41c-ec014cad474b
REPORT RequestId: c4fc9fea-2802-4ff0-b41c-ec014cad474b	Duration: 1.57 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 50 MB	
```

is there anybody has idea?

**Comment by mattip** [comment] 2020-07-01 14:31
Duplicate of #13465, see the solutions there, especially [this comment](https://github.com/numpy/numpy/issues/13465#issuecomment-545378314) that points to [this AWS document](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-use-any-programming-language-and-share-common-components/)

**Comment by rossbar** [comment] 2020-07-01 19:36
Perhaps it's worth adding a link on the AWS lambda config to [the troubleshooting importerror doc](https://numpy.org/devdocs/user/troubleshooting-importerror.html)

**Comment by rossbar** [comment] 2020-07-10 19:41
I'm going to close this as duplicate - @aweng126 if you're still having trouble feel free to reopen.

**Closed by rossbar** 2020-07-10 19:41 UTC

**Comment by aweng126** [comment] 2020-07-19 09:56
thanks everyone, I think i had found the problem. I zip the code and packages in my Mac, and then I upload the file as function.zip as a lambda function. however, amazon execute your code with linux , the packages installed in mac like numpy  have some differences with that installed in linux. so when I launch a ec2 in aws, the problem is fixed.

**Comment by mattip** [comment] 2023-02-04 20:03
When you say "I packaged library and source code to a deployment package and upload thme" what exactly do you mean? You must package a version of NumPy that can run on the target machine, this is probably what happens when you "add aws in-build pandas library in my aws lambda function layer"
