### ISSUE TITLE
CircleCI failed to upload devdocs on merge.

### ISSUE THREAD

**Issue by charris** [numpy/numpy#17972] opened 2020-12-09 19:25 UTC
See [here](https://app.circleci.com/pipelines/github/numpy/numpy/5305/workflows/931de39a-06b1-4366-a515-d8e5aa969828/jobs/17393)

**Comment by mattip** [comment] 2020-12-09 19:30
I wonder if this is caused by an overlap in the build process: after the build started another PR was merged preventing the current one from merging on top. Did it happen just this once?

**Comment by charris** [comment] 2020-12-09 20:05
> Did it happen just this once?

AFAICT, yes. I only saw it because I received notice from circleCI, which happens now and then. Your explanation is probably correct since more recent PRs haven't (yet) resulted in new notices. I did note this effect in the nightly builds I triggered after the versioneer PR was merged, the revision count went from 129 to 133.

It is a bit odd, as the expected hash isn't in the numpy repo. If the problem doesn't persist we can close this.

**Closed** 2021-02-06 21:51 UTC
