### ISSUE TITLE
DOC: contradicting numpy.inp and npy_intp documentation

### ISSUE THREAD

**Issue by lorentzenchr** [numpy/numpy#26084] opened 2024-03-19 20:06 UTC
### Issue with current documentation:

https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.intp states
> `numpy.intp`: Compatible with the C `intptr_t`.

while https://numpy.org/devdocs/reference/c-api/dtype.html#c.npy_intp states
> `Py_ssize_t` (a signed integer with the same size as the C `size_t`).
> Note: Before NumPy 2.0, this was the same as `Py_intptr_t`

### Idea or request for content:

I guess the first doc entry about `numpy.intp` just needs an update and replace `intptr_t` by `Py_ssize_t`.

**Comment by ngoldbaum** [comment] 2024-03-20 15:37
@ogrisel just reported #26092 which is a dupe of this, but that issue is a bit more descriptive so closing this in favor of that issue. I'm not sure what the answer here is otherwise I'd just respond.

**Closed by ngoldbaum** 2024-03-20 15:37 UTC
Labels: 04 - Documentation
