### ISSUE TITLE
mean of float16 returns unexpected result

### ISSUE THREAD

**Issue by c-wilson** [numpy/numpy#7933] opened 2016-08-12 15:14 UTC
I am seeing the following issue when I take axis means of float16 arrays:

``` python
import numpy as np
import matplotlib.pyplot as plt
```

``` python
a = np.random.rand(5000,500)

plt.plot(a.mean(axis=0))
plt.plot(a.astype(np.float16).mean(axis=0))
```

![output_3_1](https://cloud.githubusercontent.com/assets/5377850/17626807/dd64c718-607c-11e6-8594-bfa570396047.png)

You can see that the mean of the float16 array (green) is some weird constant, whereas the float64 array's mean is time-varying as expected. This only happens with large arrays in axis 0 (>5000).

It is not a matplotlib issue: if I convert the float16 mean array back to float64 I get the same behavior. I'm running is on python 3.5, numpy version 1.11.1 from Anaconda Mac 10.11.6

**Comment by charris** [comment] 2016-08-12 16:21
Not surprising. The sum accumulates until 1 is less that the float16 granularity, at which point it becomes fixed. The more numbers averaged, the more likely that is to happen. If you use 1000 unstead of 5000 you will start to see some variation. As to the solution, float16 was never intended for computation, it was for compact storage and getting high dynamic range in images where precision did not matter so much. So, don't do your computations in float16. Here you could do `a.astype(np.float16).mean(axis=0, dtype=np.float32)`.

On the numpy side, it might be worth making float32 the default type for float16 sums, as float16 was not designed for such computations.

**Comment by seberg** [comment] 2016-08-13 05:37
It is the default type along the fast axis, we need a way to disable loop order optimization for it, I believe..

**Comment by TobiasLe** [comment] 2017-03-31 07:45
I have a similar issue with mean calculation with dtype = np.flaot32
https://github.com/numpy/numpy/issues/8869

**Comment by WarrenWeckesser** [comment] 2020-03-16 04:51
This behavior with `float16` input is no longer reproducible with, for example, numpy 1.18.1:

```
In [14]: a = np.random.rand(5000, 50)                                           

In [15]: a.mean(axis=0)                                                         
Out[15]: 
array([0.49920779, 0.50023323, 0.50385335, 0.49863011, 0.49031848,
       0.4986143 , 0.50227111, 0.50234441, 0.49492954, 0.5042278 ,
       0.50794871, 0.49536775, 0.50245531, 0.49761094, 0.49873809,
       0.49928466, 0.50280978, 0.49909972, 0.49430732, 0.4995724 ,
       0.49583437, 0.50023925, 0.49552395, 0.50310697, 0.50801633,
       0.49960157, 0.49462101, 0.50438778, 0.50634269, 0.49995217,
       0.49883872, 0.50319984, 0.49230402, 0.49777859, 0.49651967,
       0.49633652, 0.4982165 , 0.50187905, 0.49510268, 0.50481601,
       0.49738592, 0.5030401 , 0.49827075, 0.50254704, 0.49664551,
       0.49904945, 0.49859195, 0.50275932, 0.49999425, 0.4995092 ])

In [16]: a.astype(np.float16).mean(axis=0)                                                               
Out[16]: 
array([0.4993, 0.5   , 0.504 , 0.4985, 0.4902, 0.4985, 0.5024, 0.5024,
       0.4949, 0.5044, 0.508 , 0.4954, 0.5024, 0.4976, 0.4988, 0.4993,
       0.503 , 0.499 , 0.4944, 0.4995, 0.4958, 0.5   , 0.4956, 0.503 ,
       0.508 , 0.4995, 0.4946, 0.5044, 0.5063, 0.5   , 0.4988, 0.5034,
       0.4922, 0.4978, 0.4966, 0.4963, 0.4983, 0.502 , 0.495 , 0.505 ,
       0.4973, 0.503 , 0.4983, 0.5024, 0.4966, 0.499 , 0.4985, 0.503 ,
       0.5   , 0.4995], dtype=float16)
```
When the input data type is `float16` and an explicit `dtype` argument is not given, the input array is cast to `float32` before computing the result.  The return value is then cast back to `float16`.

To reproduce the old behavior, pass `dtype=np.float16` to `mean`:

```
In [22]: a.astype(np.float16).mean(dtype=np.float16, axis=0)                                             
Out[22]: 
array([0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097,
       0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097,
       0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097,
       0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097,
       0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097,
       0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097, 0.4097,
       0.4097, 0.4097], dtype=float16)
```

**Comment by WarrenWeckesser** [comment] 2020-03-16 04:56
I'm closing this issue, but note that issue #8869 reported by @TobiasLe is still open.

**Closed by WarrenWeckesser** 2020-03-16 04:56 UTC
