### ISSUE TITLE
numpy.loadtxt "skipcols" - New parameter needed

### ISSUE THREAD

**Issue by szg0000** [numpy/numpy#14427] opened 2019-09-05 11:00 UTC
New parameter needed, to add the columns which need to be skipped.
e.g:
columns = (1,2,3)  - to skip columns 2,3,4

**Comment by kalvdans** [comment] 2019-10-13 21:36
I think it is redundant since we already have `usecols` which does the same thing.

usecols=(0,4) - to skip columns 2,3,4

**Comment by szg0000** [comment] 2020-04-14 19:40
Sometimes you don't know how many columns you have.

**Comment by eric-wieser** [comment] 2020-04-15 11:35
Duplicate of #13878

**Closed by eric-wieser** 2020-04-15 11:35 UTC
