### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by youssefkotb** [numpy/numpy#15087] opened 2019-12-10 15:14 UTC
Traceback (most recent call last):
  File "C:\Users\ASUS\Anaconda3\envs\tf k np installed 3.6\lib\site-packages\numpy\core\__init__.py", line 17, in <module>
    from . import multiarray
  File "C:\Users\ASUS\Anaconda3\envs\tf k np installed 3.6\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\ASUS\Anaconda3\envs\tf k np installed 3.6\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Youssef/Python Material/Projects/Project 5243 using 3.6/5243.py", line 2, in <module>
    import numpy as np
  File "C:\Users\ASUS\Anaconda3\envs\tf k np installed 3.6\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\ASUS\Anaconda3\envs\tf k np installed 3.6\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "D:\Youssef\Python Material\Projects\Project 5243 using 3.6\venv\Scripts\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

Process finished with exit code 1

**Comment by mattip** [comment] 2019-12-10 16:27
Hi @youssefkotb. It seems you are using 
`D:\Youssef\Python Material\Projects\Project 5243 using 3.6\venv\Scripts\python.exe`
but you somehow are getting numpy from a totally different location
`C:\Users\ASUS\Anaconda3\envs\tf k np installed 3.6\lib\site-packages\numpy\core_init_.py`.
It seems the two are not compatible: for instance one is 32-bit windows, one is 64-bit, or some other mismatch. You might be able to see this by examining the string printed by `python -c "import sys; print(sys.version)"`, once with the `python.exe` you are using above and once with the `python.exe` in `C:\Users\ASUS\Anaconda3\envs\tf k np installed 3.6`. 

This mismatch might be caused by a `PYTHONPATH` environment variable or some other script messing with the `sys.path`.

**Comment by seberg** [comment] 2019-12-23 23:19
@youssefkotb did Matti's hint help you fix your issue? I am going to tentatively close the issue, but if problems remain please comment with more details if possible and we can reopen.

**Closed by seberg** 2019-12-23 23:19 UTC
