### ISSUE TITLE
Fancy indexing inconsistency with object dtype

### ISSUE THREAD

**Issue by luispedro** [numpy/numpy#5722] opened 2015-03-26 11:06 UTC
Here is a test-case, where I expect the results to always be the same, but they are not.

```
import numpy as np
dtype=object

print("[[0]] = array-like")
A = np.zeros(2, dtype=dtype)
A[[0]] = [[1,2,3,4]]
print(A)

print("[[0]] = ndarray")
B = np.zeros(2, dtype=dtype)
B[[0]] = np.array([[1,2,3,4]])
print(B)

print("[[T,F]] = array-like")
C = np.zeros(2, dtype=dtype)
C[np.array([True, False])] = [[1,2,3,4]]
print(C)

print("[[T,F]] = ndarray")
D = np.zeros(2, dtype=dtype)
D[np.array([True, False])] = np.array([[1,2,3,4]])
print(D)

print("[0] = array-like")
E = np.zeros(2, dtype=dtype)
E[0] = [1,2,3,4]
print(E)
```

To be clear, I expected the result to always be `[ [1,2,3,4], 0]`.

The results in 1.8 are different, but also wrong.

*

A probably related bug: when using `dtype=int`, then I would expect all the calls to trigger an error message, but they do not.

Tested on both 1.9.2 and current master.

**Comment by seberg** [comment] 2015-03-26 12:05
No, that the behaviour is fully correct (at least in 1.9.2 there are probably cases where this is different in 1.8, but has been made consistent in 1.9, though I admit in 1.9.2 there is also a bug that I just fixed here).
If you do `np.array([[1, 2, 3, 4]])` and assign it you assign a `(1, 4)` dimensional array into a `(1,)` array. This is an *error* however, it made to much problems to actually make this an error in 1.9. so that there is an incorrect fallback to some old wrong behaviour which makes this "work" by just not using all of the value error. Rerun the thing with: `warnings.simplefilter("always")` in a fresh session. The simple fact is `[[1, 2, 3, 4]]` can be viewed as `arr = np.empty(1, dtype=object); arr[0] = [1, 2, 3, 4]`

**Comment by luispedro** [comment] 2015-03-26 12:22
> The simple fact is [[1, 2, 3, 4]] can be viewed as arr = np.empty(1, dtype=object); arr[0] = [1, 2, 3, 4]

Yes, this is the interpretation I expected and it seems to be used for `A` (this is the one that behaves differently on 1.8—where it behaves like `B`).

Shouldn't `C` be the same, though? What is the difference between `A` & `C`?

*

So, the current behaviour is that is unravels the left-hand-size and uses the values that it needs, ignoring the rest? This seems like something that `R` would do. Was it kept because it broke other code?

**Comment by seberg** [comment] 2015-03-26 12:28
Oh right, sorry. Yes, C is still "wrong", I made an issue about that back then (gh-4320). Maybe it is time to fix it as well. Want to have a look ;). It will require changing the boolean assignment code a bit.

**Comment by seberg** [comment] 2015-03-26 12:29
About the raveling, yes, that is because it broke other code, but we have the deprecation, so lets say 1.11 we can maybe kill those annoying special cases.

**Comment by seberg** [comment] 2019-01-03 15:50
Closing this since it is a duplicate of gh-4320 as pointed out.

**Closed by seberg** 2019-01-03 15:50 UTC
