### ISSUE TITLE
NumPy scalars are not collections.Hashable on Python 3

### ISSUE THREAD

**Issue by shoyer** [numpy/numpy#5562] opened 2015-02-12 04:23 UTC
xref: https://github.com/pydata/pandas/issues/9276

For example:

```
In [1]: import numpy as np

In [2]: import collections

In [3]: isinstance(3.14, collections.Hashable)
Out[3]: True

In [4]: isinstance(np.float64(3.14), collections.Hashable)
Out[4]: False
```

On Python 2.7, the last output here is `True` (which is the correct value)

**Comment by nigeil** [comment] 2015-02-19 13:37
This peculiarity seems to be limited in scope - I only see it with np.float(64) in my short tests.
'''
In [4]: isinstance(np.float32(3.14), collections.Hashable)
Out[4]: True

In [5]: isinstance(np.float64(3.14), collections.Hashable)
Out[5]: False

In [6]: isinstance(np.float128(3.14), collections.Hashable)
Out[6]: True

In [7]: isinstance(np.float(3.14), collections.Hashable)
Out[7]: True

In [8]: isinstance(np.int(3.14), collections.Hashable)
Out[8]: True
'''

I'm not sure where these types are implemented, but I think this afternoon I'm going to poke around the code and look to see what differences there are between the different float types.

**Comment by mattip** [comment] 2019-01-21 20:10
Cannot reproduce on linux64, numpy 1.13, numpy 1.16, python 3.6.6.

**Comment by mattip** [comment] 2019-02-14 19:40
Closing. Please reopen or open a new issue if the issue can be reproduced

**Closed by mattip** 2019-02-14 19:40 UTC
Labels: 00 - Bug, 57 - Close?
