### ISSUE TITLE
Error loading numpy module in moviepy - Pypy

### ISSUE THREAD

**Issue by mattwilson888** [numpy/numpy#16142] opened 2020-05-03 08:11 UTC
Moviepy does not appear to be officially supported by Pypy, but its slow execution time is motivating me to wade through the errors and attempt to hack a solution together. Right now I am getting this error from this code on this version:

```Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:59:05)
[PyPy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
```
from moviepy.editor import *

clip = VideoFileClip("vid_file")

clip.write_videofile('test.mp4', threads=4, logger=None)
```
```
Traceback (most recent call last):
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/_multiarray_umath.pypy36-pp73-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "thread_test.py", line 1, in <module>
    from moviepy.editor import *
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/moviepy/editor.py", line 24, in <module>
    import imageio
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/imageio/__init__.py", line 22, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/imageio/core/__init__.py", line 10, in <module>
    from .util import Image, Array, Dict, asarray, image_as_uint, urlopen
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/imageio/core/util.py", line 19, in <module>
    import numpy as np
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/home/matt/Documents/pyth-test-env/pypy3/bin/python",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/_multiarray_umath.pypy36-pp73-x86_64-linux-gnu.so)
```

I have uninstalled and reinstalled numpy, and verified I am using the version my virtual env intends. I am wondering if its possible to use the information given on the last line of the error to solve this directly.

**Comment by mattip** [comment] 2020-05-03 12:13
Duplicate of gh-16111. I think the problem is that the build is linking to the libm shipped with the snap rather than the libm provided in your environment. This is not a numpy-specific problem. Perhaps some other forum might be more appropriate for debugging compilation within a snap container.

**Comment by mattip** [comment] 2020-05-03 12:22
Sorry, not link but runtime. What happens if you use `LD_LIBRARY_PATH=/path/to/lib pypy3 -c"import numpy"`. For me  `/path/to/lib` is `/lib/x86_64-linux-gnu`

**Comment by mattwilson888** [comment] 2020-05-11 00:55
Sorry for the late reply, and thank you for responding. Inputting the above command gave the following:

```LD_LIBRARY_PATH=/lib/"x86_64-linux-gnu" pypy3 -c"import numpy"
Traceback (most recent call last):
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/_multiarray_umath.pypy36-pp73-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "/home/matt/Documents/pyth-test-env/pypy3/bin/pypy3"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/matt/Documents/pyth-test-env/pypy3/site-packages/numpy/core/_multiarray_umath.pypy36-pp73-x86_64-linux-gnu.so)
```

**Comment by rossbar** [comment] 2020-07-11 21:54
I'm going to close this as it does seem like more of a system configuration issue and not necessarily numpy specific. Please feel free to reopen if the issue persists and more specific information about the failure becomes available.

**Closed** 2020-07-11 21:55 UTC
Labels: 24 - PyPy, 32 - Installation
