### ISSUE TITLE
unexpected behavior of in for lists of arrays

### ISSUE THREAD

**Issue by tylerharvey** [numpy/numpy#17462] opened 2020-10-06 01:38 UTC
The behavior of `in` with lists of numpy arrays is extremely surprising to me and seems like a bug. 

### Reproducing code example:

```python
import numpy as np
list_of_arrays = [np.array([1,2]),np.array([3,4]),np.array([5,6])]
for element in list_of_arrays:
    print(element in list_of_arrays)
```

### Error message:

This throws a ValueError only on the second iteration of the loop. 
```
True
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-4d23bc98448e> in <module>
      2 list_of_arrays = [np.array([1,2]),np.array([3,4]),np.array([5,6])]
      3 for element in list_of_arrays:
----> 4     print(element in list_of_arrays)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I'm unclear on whether this involves any overloading for numpy arrays here besides boolean comparisons, so maybe this is an unfixable (on the numpy side) problem with the default implementation of `in`.
 
### NumPy/Python version information:

1.19.2 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]

**Comment by AnshuTrivedi** [comment] 2020-10-06 04:20
@tylerharvey try this code. 

> list_of_arrays = [np.array([1,2]).any(),np.array([3,4]).any(),np.array([5,6]).any()]
for element in list_of_arrays:
    print(element in list_of_arrays)

Error is due there are more than one elments in each np.array inside list.

**Comment by AnshuTrivedi** [comment] 2020-10-06 04:34
@eric-wieser @charris i have reproduced error of issue  #17462 and suggested possible solution to the problem.
I think this issue can be closed and need no change.

**Comment by rkern** [comment] 2020-10-06 05:00
This is a consequence of the combinations of two design choices:

1. `list.__contains__()` (the special method called by the `in` operator on lists) uses the `__eq__()` special method of the object to compare the object to each of the list items. It will coerce the return value to a `bool` if it isn't one already. But, it first checks for identity first, which can avoid the `__eq__()` call if the two objects are actually the same object.
2. `ndarray.__eq__()` does not return a `bool` but instead returns a boolean array of the elementwise equality comparisons. This allows useful and convenient expressions using the `==` operator. Arrays with multiple items don't have a well-defined truth value, so we raise that exception when something (like `in`) tries to coerce it to a `bool`.

In your case, since you checked with the same objects that were in the list, the first iteration of the loop (`element = list_of_arrays[0]`) checked `element is list_of_arrays[0]` which was `True` so `element == list_of_arrays[0]` was not checked and the `in` expression stopped checking the remaining elements and returned `True`. However, the second time through (with `element = list_of_arrays[1]`), `element is list_of_arrays[0]` was `False` so `element == list_of_arrays[0]` was checked, it returns a boolean array, which doesn't have a truth value. That's why it succeeds on the first iteration and not the second.

The design choice of (1) happened before Python allowed `__eq__()` to return something other than a `bool`. Python never grew another special method for doing a "is this object equivalent to this other one, yes or no?" in addition to the "whatever you want the expression `a == b` to return for whatever semantics you find convenient".

This can be an annoying combination of choices sometimes, we grant, but these are old design choices. We are mostly comfortable with the balance of the benefits that (2) provides outside of this combination against this annoyance, so I don't think this will change.

**Comment by AnshuTrivedi** [comment] 2020-10-06 05:04
@rkern Is there possibility to improve or change in code for this issue?

**Comment by tylerharvey** [comment] 2020-10-06 05:26
@rkern Okay, makes sense. My colleague and I had noticed that `in` works for object identity but it didn't occur to me that there were multiple comparisons happening.

**Comment by mattip** [comment] 2020-10-06 06:05
Closing, please reopen if something is not clear.

**Closed by mattip** 2020-10-06 06:05 UTC

**Comment by rkern** [comment] 2020-10-06 16:28
@AnshuTrivedi I don't think there is much that we can (or, at least, are willing to) change in numpy for this use case.
