### ISSUE TITLE
Problem with numpy and other things

### ISSUE THREAD

**Issue by CristhianLM3** [numpy/numpy#15972] opened 2020-04-14 13:12 UTC
Hi, I have a problem with Python and some libraries. Install python from the official website, simply download and install it directly with version 3.7 on my Macbook Pro macOS Catalina version 10.15.4 where through Thonny, I installed the numpy, pandas, matlob and other libraries, I don't have any other python ; but it doesn't work for me and it marks this error.
I tried all the solutions but still not working. 

### Reproducing code example:

import numpy as np
A=[4,7,8,9,10,4]
B=[3,5,7,8,9,3]
U=[-2,-3,4,5,6,-7,-8,9,10,0]
print(np.add(A,B))
print("Positive",np.positive(U))
print(np.negative(U))
print(np.multiply(A,B))
print(np.multiply(A,3))
print(np.power(B,2))
print(np.subtract(B,A))
print(np.floor_divide(B,2))
print(np.divide(B,10))

### Error message: 

ImportError:   IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!  Importing the numpy c-extensions failed. - Try uninstalling and reinstalling numpy. - If you have already done that, then:   1. Check that you expected to use Python3.7 from "/Applications/Thonny.app/Contents/Frameworks/Python.framework/Versions/3.7/bin/python3.7",      and that you have no directories in your PATH or PYTHONPATH that can      interfere with the Python and numpy version "1.18.2" you're trying to use.   2. If (1) looks fine, you can open a new issue at      https://github.com/numpy/numpy/issues.  Please include details on:      - how you installed Python      - how you installed numpy      - your operating system      - whether or not you have multiple versions of Python installed      - if you built from source, your compiler versions and ideally a build log  - If you're working with a numpy git repository, try `git clean -xdf`   (removes all files not under version control) and rebuild numpy.  Note: this error has many possible causes, so please don't comment on an existing issue about this - open a new one instead.  Original error was: dlopen(/Users/cristhianjair/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): no suitable image found.  Did find:        /Users/cristhianjair/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so: code signature in (/Users/cristhianjair/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

**Comment by eric-wieser** [comment] 2020-04-14 13:15
Duplicate of #15670

**Closed by eric-wieser** 2020-04-14 13:15 UTC
