### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by NickosKal** [numpy/numpy#19126] opened 2021-05-28 13:32 UTC
### Reproducing code example:

```python
history = model.fit_generator(generator=train_generator,
                              steps_per_epoch=steps_per_epoch,
                              epochs=final_epoch,
                              callbacks=callbacks,
                              validation_data=val_generator,
                              validation_steps=ceil(val_dataset_size/batch_size),
                              initial_epoch=initial_epoch)

numpy_loss_history = np.array(history)
np.save(file="loss_history.txt", arr=numpy_loss_history)

plt.figure(figsize=(20,12))
plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.legend(loc='upper right', prop={'size': 24})

dataset_val = DataGenerator()
#
# # TODO: Set the paths to the datasets here.
# The directory that contain the test images
Dataset_test_images_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\test'

# The directories that contain the annotations.
Dataset_train_labels_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\train'
Dataset_test_labels_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\val'

# The paths to the image sets.
Dataset_val_image_set_filename = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\val.txt'
# The XML parser needs to now what object class names to look for and in which order to map them to integers.

dataset_val.parse_xml(images_dirs=[Dataset_test_images_dir],
                  image_set_filenames=[Dataset_val_image_set_filename],
                  annotations_dirs=[],
                  classes=classes,
                  include_classes='all',
                  exclude_truncated=False,
                  exclude_difficult=True,
                  ret=False)

pred_generator = dataset_val.generate(batch_size=1,
                             shuffle=True,
                             transformations=[],
                             returns={'processed_images',
                                      'filenames',
                                      'inverse_transform',
                                      'original_images',
                                      'original_labels'},
                             keep_images_without_gt=False)

for ii in range(1, 195):

    batch_images, batch_filenames, batch_inverse_transforms, batch_original_images, _ = next(pred_generator)

    i = 0 # Which batch item to look at

    print("Image:", batch_filenames[i])
    print()
    print("Ground truth boxes:\n")

    y_pred = model.predict(batch_images)
    y_pred_decoded = decode_detections(y_pred,
                                       confidence_thresh=0.5,
                                       iou_threshold=0.45,
                                       top_k=200,
                                       normalize_coords=normalize_coords,
                                       img_height=img_height,
                                       img_width=img_width)

    np.set_printoptions(precision=2, suppress=True, linewidth=90)
    print("Predicted boxes:\n")
    print('   class   conf xmin   ymin   xmax   ymax')
    print(y_pred_decoded[i])

    plt.figure(figsize=(20,12))
    plt.imshow(batch_images[i])

    current_axis = plt.gca()

    colors = plt.cm.hsv(np.linspace(0, 1, n_classes+1)).tolist() # Set the colors for the bounding boxes

    # Draw the ground truth boxes in green (omit the label for more clarity)
    for box in y_pred_decoded[i]:
        xmin = box[1]
        ymin = box[2]
        xmax = box[3]
        ymax = box[4]
        label = '{}'.format(classes[int(box[0])])
        current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color='green', fill=False, linewidth=2))
        current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':'green', 'alpha':1.0})

    # Draw the predicted boxes in blue
    for box in y_pred_decoded[i]:
        xmin = box[-4]
        ymin = box[-3]
        xmax = box[-2]
        ymax = box[-1]
        color = colors[int(box[0])]
        label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
        current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color=color, fill=False, linewidth=2))
        current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':color, 'alpha':1.0})
    plt.show()
```

And this is the error I am getting:
```
Traceback (most recent call last):
  File "C:/Users/Nickos_Kal/Desktop/SSD_FLAGS_STABLE/Train_Flags_SSD7_peirama.py", line 264, in <module>
    np.save(file="loss_history.txt", arr=numpy_loss_history)
  File "<__array_function__ internals>", line 6, in save
  File "C:\Users\Nickos_Kal\AppData\Roaming\Python\Python37\site-packages\numpy\lib\npyio.py", line 530, in save
    pickle_kwargs=dict(fix_imports=fix_imports))
  File "C:\Users\Nickos_Kal\AppData\Roaming\Python\Python37\site-packages\numpy\lib\format.py", line 676, in write_array
    pickle.dump(array, fp, protocol=3, **pickle_kwargs)
TypeError: can't pickle _thread.RLock objects

Process finished with exit code 1
```
Any suggestions would be appreciated. 
Thanks in advance!

**Comment by bashtage** [comment] 2021-05-28 13:48
Can you produce a simpler example that reproduces the problem. Ideally it would be copy and paste runnable in a new IPython session.

**Comment by NickosKal** [comment] 2021-05-28 14:08
```
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, TerminateOnNaN, CSVLogger
from keras import backend as K
from keras.models import load_model
from math import ceil
import numpy as np
from matplotlib import pyplot as plt

from models.keras_ssd7 import build_model
from keras_loss_function.keras_ssd_loss import SSDLoss
from keras_layers.keras_layer_AnchorBoxes import AnchorBoxes
from keras_layers.keras_layer_DecodeDetections import DecodeDetections
from keras_layers.keras_layer_DecodeDetectionsFast import DecodeDetectionsFast

from ssd_encoder_decoder.ssd_input_encoder import SSDInputEncoder
from ssd_encoder_decoder.ssd_output_decoder import decode_detections, decode_detections_fast

from data_generator.object_detection_2d_data_generator import DataGenerator
from data_generator.object_detection_2d_misc_utils import apply_inverse_transforms
from data_generator.data_augmentation_chain_variable_input_size import DataAugmentationVariableInputSize
from data_generator.data_augmentation_chain_constant_input_size import DataAugmentationConstantInputSize
from data_generator.data_augmentation_chain_original_ssd import SSDDataAugmentation
from data_generator.object_detection_2d_geometric_ops import Resize


def recall_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall


def precision_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision


def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))


img_height = 720  # Height of the input images
img_width = 1280  # Width of the input images
img_channels = 3  # Number of color channels of the input images
intensity_mean = 127.5  # Set this to your preference (maybe `None`). The current settings transform the input pixel values to the interval `[-1,1]`.
intensity_range = 127.5  # Set this to your preference (maybe `None`). The current settings transform the input pixel values to the interval `[-1,1]`.
n_classes = 8  # Number of positive classes
scales = [0.08, 0.16, 0.32, 0.64, 0.96]  # An explicit list of anchor box scaling factors. If this is passed, it will override `min_scale` and `max_scale`.
aspect_ratios = [0.5, 1.0, 2.0]  # The list of aspect ratios for the anchor boxes
two_boxes_for_ar1 = True  # Whether or not you want to generate two anchor boxes for aspect ratio 1
steps = None  # In case you'd like to set the step sizes for the anchor box grids manually; not recommended
offsets = None  # In case you'd like to set the offsets for the anchor box grids manually; not recommended
clip_boxes = False  # Whether or not to clip the anchor boxes to lie entirely within the image boundaries
variances = [1.0, 1.0, 1.0, 1.0]  # The list of variances by which the encoded target coordinates are scaled
normalize_coords = False  # Whether or not the model is supposed to use coordinates relative to the image size

K.clear_session()  # Clear previous models from memory.

model = build_model(image_size=(img_height, img_width, img_channels),
                    n_classes=n_classes,
                    mode='training',
                    l2_regularization=0.005,
                    scales=scales,
                    aspect_ratios_global=aspect_ratios,
                    aspect_ratios_per_layer=None,
                    two_boxes_for_ar1=two_boxes_for_ar1,
                    steps=steps,
                    offsets=offsets,
                    clip_boxes=clip_boxes,
                    variances=variances,
                    normalize_coords=normalize_coords,
                    subtract_mean=intensity_mean,
                    divide_by_stddev=intensity_range,
                    coords='corners')

# 2: Optional: Load some weights

# model.load_weights('./ssd7_weights.h5', by_name=True)

# 3: Instantiate an Adam optimizer and the SSD loss function and compile the model
from keras.optimizers import Adam, SGD, Adadelta

adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
adade = Adadelta()

ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)

model.compile(optimizer=adade, loss=ssd_loss.compute_loss, metrics=[precision_m, recall_m, f1_m])

train_dataset = DataGenerator(load_images_into_memory=False, hdf5_dataset_path=None)
val_dataset = DataGenerator(load_images_into_memory=False, hdf5_dataset_path=None)

# 2: Parse the image and label lists for the training and validation datasets. This can take a while.

# TODO: Set the paths to the datasets here.

# The directories that contain the images.
Dataset_train_images_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\train1'
Dataset_test_images_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\test'

# The directories that contain the annotations.
Dataset_train_labels_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\train'
Dataset_test_labels_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\val'

# The paths to the image sets.
Dataset_train_image_set_filename = r"C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\train.txt"
Dataset_val_image_set_filename = r"C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\val.txt"

# The XML parser needs to now what object class names to look for and in which order to map them to integers.
classes = ['background', 'off', 'Yellow', 'Red', 'RedLeft', 'Green', 'GreenLeft', 'GreenStraight']

train_dataset.parse_xml(images_dirs=[Dataset_train_images_dir],
                        image_set_filenames=[Dataset_train_image_set_filename],
                        annotations_dirs=[Dataset_train_labels_dir],
                        classes=classes,
                        include_classes='all',
                        exclude_truncated=True,
                        exclude_difficult=True,
                        ret=False)

val_dataset.parse_xml(images_dirs=[Dataset_test_images_dir],
                      image_set_filenames=[Dataset_val_image_set_filename],
                      annotations_dirs=[Dataset_test_labels_dir],
                      classes=classes,
                      include_classes='all',
                      exclude_truncated=True,
                      exclude_difficult=True,
                      ret=False)

# Optional: Convert the dataset into an HDF5 dataset. This will require more disk space, but will
# speed up the training. Doing this is not relevant in case you activated the `load_images_into_memory`
# option in the constructor, because in that cas the images are in memory already anyway. If you don't
# want to create HDF5 datasets, comment out the subsequent two function calls.

# train_dataset.create_hdf5_dataset(file_path='big_dataset_flags_trainval.h5',
#                                   resize=False,
#                                   variable_image_size=True,
#                                   verbose=True)
#
# val_dataset.create_hdf5_dataset(file_path='big_dataset_flags_test.h5',
#                                 resize=False,
#                                 variable_image_size=True,
#                                 verbose=True)

train_dataset_size = train_dataset.get_dataset_size()
val_dataset_size = val_dataset.get_dataset_size()

print("Number of images in the training dataset:\t{:>6}".format(train_dataset_size))
print("Number of images in the validation dataset:\t{:>6}".format(val_dataset_size))

# 3: Set the batch size.

batch_size = 1

# 4: Define the image processing chain.
resize = Resize(height=img_height, width=img_width)

data_augmentation_chain = DataAugmentationConstantInputSize(random_brightness=(-48, 48, 0.5),
                                                            # random_contrast=(0.5, 1.8, 0.5),
                                                            random_saturation=(0.5, 1.8, 0.5),
                                                            random_hue=(18, 0.5),
                                                            # random_flip=0.5,
                                                            # random_translate=((0.03,0.5), (0.03,0.5), 0.5),
                                                            # random_scale=(0.5, 2.0, 0.5),
                                                            n_trials_max=3,
                                                            # clip_boxes=True,
                                                            # overlap_criterion='area',
                                                            # bounds_box_filter=(0.3, 1.0),
                                                            # bounds_validator=(0.5, 1.0),
                                                            n_boxes_min=1,
                                                            background=(0, 0, 0))

# 5: Instantiate an encoder that can encode ground truth labels into the format needed by the SSD loss function.

# The encoder constructor needs the spatial dimensions of the model's predictor layers to create the anchor boxes.
predictor_sizes = [model.get_layer('classes4').output_shape[1:3],
                   model.get_layer('classes5').output_shape[1:3],
                   model.get_layer('classes6').output_shape[1:3],
                   model.get_layer('classes7').output_shape[1:3]]

ssd_input_encoder = SSDInputEncoder(img_height=img_height,
                                    img_width=img_width,
                                    n_classes=n_classes,
                                    predictor_sizes=predictor_sizes,
                                    scales=scales,
                                    aspect_ratios_global=aspect_ratios,
                                    two_boxes_for_ar1=two_boxes_for_ar1,
                                    steps=steps,
                                    offsets=offsets,
                                    clip_boxes=clip_boxes,
                                    variances=variances,
                                    matching_type='multi',
                                    pos_iou_threshold=0.5,
                                    neg_iou_limit=0.3,
                                    normalize_coords=normalize_coords)

# 6: Create the generator handles that will be passed to Keras' `fit_generator()` function.

train_generator = train_dataset.generate(batch_size=batch_size,
                                         shuffle=True,
                                         transformations=[resize],
                                         label_encoder=ssd_input_encoder,
                                         returns={'processed_images',
                                                  'encoded_labels'},
                                         keep_images_without_gt=False)

val_generator = val_dataset.generate(batch_size=batch_size,
                                     shuffle=False,
                                     transformations=[resize],
                                     label_encoder=ssd_input_encoder,
                                     returns={'processed_images',
                                              'encoded_labels'},
                                     keep_images_without_gt=False)

model_checkpoint = ModelCheckpoint(filepath='ssd7_epoch-{epoch:02d}_loss-{loss:.4f}_val_loss-{val_loss:.4f}.h5',
                                   monitor='loss',
                                   verbose=1,
                                   save_best_only=True,
                                   save_weights_only=False,
                                   mode='auto',
                                   period=1)

csv_logger = CSVLogger(filename='ssd7_training_log.csv',
                       separator=',',
                       append=True)

early_stopping = EarlyStopping(monitor='val_loss',
                               min_delta=0.0,
                               patience=10,
                               verbose=1)

reduce_learning_rate = ReduceLROnPlateau(monitor='val_loss',
                                         factor=0.2,
                                         patience=8,
                                         verbose=1,
                                         epsilon=0.001,
                                         cooldown=0,
                                         min_lr=0.00001)

callbacks = [model_checkpoint,
             csv_logger,
             # early_stopping,
             # reduce_learning_rate,
             ]

initial_epoch = 0
final_epoch = 5
steps_per_epoch = int(100 / batch_size)


history = model.fit_generator(generator=train_generator,
                              steps_per_epoch=steps_per_epoch,
                              epochs=final_epoch,
                              callbacks=callbacks,
                              validation_data=val_generator,
                              validation_steps=ceil(val_dataset_size/batch_size),
                              initial_epoch=initial_epoch)

numpy_loss_history = np.array(history)
np.save("loss_history.txt", numpy_loss_history)

plt.figure(figsize=(20,12))
plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.legend(loc='upper right', prop={'size': 24})

dataset_val = DataGenerator()
#
# # TODO: Set the paths to the datasets here.
# The directory that contain the test images
Dataset_test_images_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\test'

# The directories that contain the annotations.
Dataset_train_labels_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\train'
Dataset_test_labels_dir = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\val'

# The paths to the image sets.
Dataset_val_image_set_filename = r'C:\Users\Nickos_Kal\Desktop\SSD_FLAGS_STABLE\Nick\val.txt'
# The XML parser needs to now what object class names to look for and in which order to map them to integers.

dataset_val.parse_xml(images_dirs=[Dataset_test_images_dir],
                  image_set_filenames=[Dataset_val_image_set_filename],
                  annotations_dirs=[],
                  classes=classes,
                  include_classes='all',
                  exclude_truncated=False,
                  exclude_difficult=True,
                  ret=False)

pred_generator = dataset_val.generate(batch_size=1,
                             shuffle=True,
                             transformations=[],
                             returns={'processed_images',
                                      'filenames',
                                      'inverse_transform',
                                      'original_images',
                                      'original_labels'},
                             keep_images_without_gt=False)

for ii in range(1, 195):

    batch_images, batch_filenames, batch_inverse_transforms, batch_original_images, _ = next(pred_generator)

    i = 0 # Which batch item to look at

    print("Image:", batch_filenames[i])
    print()
    print("Ground truth boxes:\n")

    y_pred = model.predict(batch_images)
    y_pred_decoded = decode_detections(y_pred,
                                       confidence_thresh=0.5,
                                       iou_threshold=0.45,
                                       top_k=200,
                                       normalize_coords=normalize_coords,
                                       img_height=img_height,
                                       img_width=img_width)

    np.set_printoptions(precision=2, suppress=True, linewidth=90)
    print("Predicted boxes:\n")
    print('   class   conf xmin   ymin   xmax   ymax')
    print(y_pred_decoded[i])

    plt.figure(figsize=(20,12))
    plt.imshow(batch_images[i])

    current_axis = plt.gca()

    colors = plt.cm.hsv(np.linspace(0, 1, n_classes+1)).tolist() # Set the colors for the bounding boxes

    # Draw the ground truth boxes in green (omit the label for more clarity)
    for box in y_pred_decoded[i]:
        xmin = box[1]
        ymin = box[2]
        xmax = box[3]
        ymax = box[4]
        label = '{}'.format(classes[int(box[0])])
        current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color='green', fill=False, linewidth=2))
        current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':'green', 'alpha':1.0})

    # Draw the predicted boxes in blue
    for box in y_pred_decoded[i]:
        xmin = box[-4]
        ymin = box[-3]
        xmax = box[-2]
        ymax = box[-1]
        color = colors[int(box[0])]
        label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
        current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color=color, fill=False, linewidth=2))
        current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':color, 'alpha':1.0})
    plt.show()

```

Here is the code where I am using it and I get that error I looked at the .py that the error comes from but still can't figure out what to change in order to fix it

**Comment by NickosKal** [comment] 2021-05-28 14:40
I don't thinks so cause I get this error only when I am using it to save the parameter that I apply fit on as shown above if I try to save something that doesn't have to do with object detection model the function works fine.

**Comment by BvB93** [comment] 2021-05-28 14:55
What's currently contained within the `numpy_loss_history` array?
Based on what has shown thus far it seems to be an object array containing one or more unpicklable object,
but we need to know more before we can confirm this.

**Comment by NickosKal** [comment] 2021-05-28 15:09
the `history` is trained with images and their annotations. So the `numpy_loss_history` contains the results of the fitting that I am doing. If it is helpfull I could upload all the .py file that I use. Sorry if I am not very helfull I am still trying to learn about object detection models and how they work.

**Comment by bashtage** [comment] 2021-05-28 15:11
The `history` is the problem it sounds like it.  What is the dtype of `numpy_loss_history`?  `object`.  If it is `object`, then some of the things in it are not pickleable.  These are not NumPy objects, and so you will need to report it to the project who has the unpickleable object

**Comment by bashtage** [comment] 2021-05-28 15:13
Also a plausible candidate: https://github.com/matterport/Mask_RCNN/issues/1126

**Comment by bashtage** [comment] 2021-05-28 15:14
And the likely solution: https://stackoverflow.com/questions/47066635/checkpointing-keras-model-typeerror-cant-pickle-thread-lock-objects

**Comment by NickosKal** [comment] 2021-05-28 16:11
Yeah the `numpy_loss_history` has dtype object. Thanks for your time and your help I will read the solotution you posted :)

**Comment by NickosKal** [comment] 2021-05-29 13:02
Hey @bashtage the error was solved by changing the np.save to model.save don't know if that way is the right one because the predictions are all wrong

**Comment by seberg** [comment] 2023-06-21 12:05
Closing, sounds like this was a Tensorflow issue to begin with.

**Closed by seberg** 2023-06-21 12:05 UTC
Labels: 57 - Close?
