### ISSUE TITLE
operator.lshift and operator.rshift mismatch when applying to scalars vs arrays

### ISSUE THREAD

**Issue by hameerabbasi** [numpy/numpy#10385] opened 2018-01-12 16:24 UTC
For some small example data, on my system (and one other), `operator.lshift` and `operator.rshift` randomly return incorrect results.

PC 1:

- macOS 10.13.2
- Anaconda (latest)
- Python 3.6.4
- Numpy 1.13.3

PC 2:

- Same as PC 1, except Numpy 1.14.0
- New Conda env

Third config:

- PC 1, but with system Python 2.7 and a clean VENV
- Numpy 1.14.0

Simple test (only fails on some data) and doesn't fail on third configuration. But it can be reproduced reliably.

```
import numpy as np

if __name__ == '__main__':
    x = np.load('x.npy')
    y = np.load('y.npy')

    print(x.shape)  # (2, 3, 4)
    print(y.shape)  # (2, 3, 4)

    print(x.shape == y.shape)  # True

    print(x[0, 2, 0] << y[0, 2, 0])  # 1476395008
    print((x << y)[0, 2, 0])  # 0

    print(x[0, 2, 0] << y[0, 2, 0] == (x << y)[0, 2, 0])  # False
```

Attaching example data/project on which this happens (produced with `np.save`):
[numpy_test.zip](https://github.com/numpy/numpy/files/1626656/numpy_test.zip)

I strongly suspect this isn't really a Numpy bug, but maybe Python 3 related or possibly related to the compiler Anaconda uses.

**Comment by eric-wieser** [comment] 2018-01-12 16:40
Prediction: you're running something like `uint64 << 64`, which is implementation-defined in C

**Comment by hameerabbasi** [comment] 2018-01-12 16:47
@eric-wieser Both are `np.int_`, so `np.int64`.

**Comment by hameerabbasi** [comment] 2018-01-12 17:07
I should be more clear: I'm not comparing across implementations, I'm comparing the same implementation against itself. Just doing indexing first vs operator first.

**Comment by eric-wieser** [comment] 2018-01-12 17:30
> doing it on scalars and arrays shouldn't yield different results. 

Implementation-defined means that the implementation can do whatever it wants - in this case, you're probably seeing that the compiler-vectorized form of the shift has a different implementation to the scalar one.

Duplicate of #2449, #10299 (the latter has an easier-to-reproduce test, so leaving as the canonical one)

**Closed** 2018-01-12 17:31 UTC
