### ISSUE TITLE
BUG: Error when using `nanmax()` and `nanmin()` on an object array with an axis specified.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#9008] opened 2017-04-27 15:10 UTC
This was the underlying cause of a problem reported on stackoverflow: http://stackoverflow.com/questions/43659827/numpy-error-when-specifying-axis-in-nanmax-while-nansum-works-an-the-same-case

The error is raised when applying `nanmax()` or `nanmin()` to an array with object data type and specifying an axis.

Here's the example from my answer:
```
In [2]: import numpy as np

In [3]: np.__version__
Out[3]: '1.13.0.dev0+bca7922'

In [4]: a = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=object)

In [5]: np.nanmax(a, axis=0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-a020f98a2536> in <module>()
----> 1 np.nanmax(a, axis=0)

/Users/warren/miniconda3numpy/lib/python3.5/site-packages/numpy-1.13.0.dev0+bca7922-py3.5-macosx-10.6-x86_64.egg/numpy/lib/nanfunctions.py in nanmax(a, axis, out, keepdims)
    343         # Fast, but not safe for subclasses of ndarray
    344         res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
--> 345         if np.isnan(res).any():
    346             warnings.warn("All-NaN slice encountered", RuntimeWarning, stacklevel=2)
    347     else:

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
There is no error when the axis is not given:
```
In [6]: np.nanmax(a)
Out[6]: 4.0
```
`nansum()` handles the axis without an error:
```
In [7]: np.nansum(a, axis=0)
Out[7]: array([4.0, 6.0], dtype=object)
```
There are several other issues involving the nan-functions and object arrays, but I couldn't tell if  this issue is a duplicate.  Sorry for the noise if it is.

**Comment by Satyadev592** [comment] 2017-04-27 15:30
http://stackoverflow.com/questions/43659827/numpy-error-when-specifying-axis-in-nanmax-while-nansum-works-an-the-same-case/43660147#43660147

There is an answer with three downvotes that explains why this is not a bug. Happy realisation :)

**Comment by eric-wieser** [comment] 2017-04-27 15:31
So, ideally this breaks down into:

* We need a `O->?` loop for the `np.isnan` ufunc - an implementation would probably look like:
    * Try `np.array(item).astype(float)`, and if that succeeds, return its result
    * return false otherwise
* We need to correct the `OO->?` loop for `fmin` and `fmax` (#8975)

As a quick workaround, we should just not allow object arrays to take that special case  branch

**Comment by Satyadev592** [comment] 2017-04-27 15:33
Yes, explicity type cast to float as nanmax does in the beginning of it's source code  
res = np.fmax.reduce(a, axis=axis, out=out, **kwargs)
        if np.isnan(res).any():

The np.isnan() fails on object type columns.

**Comment by eric-wieser** [comment] 2017-04-27 15:35
@Satyadev592: Not the right fix. `np.fmax.reduce` is broken on object columns to.

This is essentially a different manifestation of the problem at #8974, and the quick fix to numpy would be as described there.

**Comment by Satyadev592** [comment] 2017-04-27 15:41
Yes, fmax is broken on object columns as well. But the assumption that axis is the reason for this is wrong. It's purely the data type of the column. The code works with row wise axis just because it coerces the data type to float (purely because of the dataset here)

**Comment by eric-wieser** [comment] 2017-04-27 15:46
The code example at the top of this page directly contradicts that claim, does it not?

The problem manifests itself when all of the following are true: axis is specified, dtype is object, and input is 2d or higher

**Comment by Satyadev592** [comment] 2017-04-27 17:11
Take a numpy array with only string values and try the nanmax on either axis. It still pops an error. The error this time is something to do with the fmax, dig a bit deeper , it's got something to do with numpy not having good support for the object datatype. If this is a bug , then a bug for each numpy function should be created for lack of support for object datatypes. This particular problem makes you think axis is a reason while it has nothing to do with the problem. 

Also shifting an explicity casting to float inside source code is probably not a good idea. Numpy does not seem to be designed for object types [Well established i think]

**Comment by eric-wieser** [comment] 2017-04-27 17:31
>Take a numpy array with only string values 

Strings are an entirely different beast, and have little to do with the `object` dtype. The problem _there_ is that _flexible_ types (np.bytes_, np.void, np.unicode_) are not supported by the `ufunc` system, due to having variable sizes. `object` arrays are perfectly supported by `ufunc`s - it just so happens that we don't have an implementation of `isnan` for them.

> If this is a bug , then a bug for each numpy function should be created for lack of support for object datatypes.

Absolutely. If you can find numpy functions that fail with object arrays, _where it would make sense for them not to_, then either:
 * Their documentation should be updated to warn about this
 * They should be fixed so that they do.

**Comment by ahaldane** [comment] 2017-04-28 02:10
This issue would be fixed by https://github.com/numpy/numpy/pull/6320 (I just tested the example).

```python
[1]: a = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=object)
[2]: np.nanmax(a, axis=0)
array([3.0, 4.0], dtype=object)
[3]: x = np.array([1, np.nan])
[4]: np.fmin.reduce(x)
1.0
[5]: np.fmin.reduce(x.astype(object))
1.0
```

**Comment by mattip** [comment] 2020-03-17 13:41
Closing, all the examples work correctly (including the last one `np.fmin.reduce(x.astype(object))` which returns `nan`). Please reopen if I misunderstood.

**Closed by mattip** 2020-03-17 13:41 UTC
Labels: 00 - Bug, component: numpy.lib

**Comment by eric-wieser** [comment] 2020-03-17 13:56
The bug here is that the case you mention should _not_ return nan

**Comment by eric-wieser** [comment] 2020-03-17 13:58
However that's covered in gh-8975, so fine to close this

**Comment by eric-wieser** [comment] 2020-03-17 14:00
Closed by gh-9013
