### ISSUE TITLE
np.quantile with wrong calculation?

### ISSUE THREAD

**Issue by Philipp-Seidel** [numpy/numpy#13267] opened 2019-04-05 10:30 UTC
Under certain settings, np.quantile makes mistakes in determining the correct quantile. Is this a bug? In the output, 0.73 means that only 73% of values are larger or equal than the determined quantile; by definition it should be >= 75% for p=0.25.

I know, that I can produce the correct result with np.quantile(x, 0.25, interpolation="lower") = 366, where 26% of values <= 366 and 76% of values >= 366. My point is, the standard version of the method delivers a result that does not fulfill the most general defintion of quantiles.

### Reproducing code example:

```python
import numpy as np
x = np.array([374, 358, 341, 355, 342, 334, 353, 346, 355, 344,
              349, 330, 352, 328, 336, 359, 361, 345, 324, 386,
              334, 370, 349, 327, 342, 354, 361, 354, 377, 324])

q = np.quantile(x, 0.25)

print(q)

print(len(x[x<=q]) / len(x))

print(len(x[x>=q]) / len(x))
```

### Numpy/Python version information:

337.25

0.26666666666666666

0.7333333333333333

**Comment by seberg** [comment] 2019-04-06 14:48
I am not sure what you expect. There are many subtleties about the definition (and other than linear, the numpy interpolation kwarg should probably be used with care, because it gives uncommon definitions probably). However, the quantiles cannot be exactly 75% here, so it has to go one way or the other? Because of the defintion used by numpy, I think your check will always go towards the median, because of how the full range is defined (I am not quite sure though).

This thread may give some more pointers: https://github.com/numpy/numpy/issues/10736

**Comment by cobykobi** [comment] 2019-04-11 15:30
Looks to me that when you have a sorted array 1..n and you request quantile x the result should be element x*n.
What I found in numpy is that since the elements are numbered 0.. n-1 what they calculate is (n-1)*x and this is wrong.
For example try 
aaaa=np.array([1,2,3,4,5])
print (np.quantile(aaaa,0.3))
result is 2.2 but 0.4 of the elements are smaller than 2.2  and result should be between 1 and 2.
Hope I was clear enough.

**Comment by Philipp-Seidel** [comment] 2019-04-11 15:53
@seberg
So, its true, the English Wikipedia has no good definition, but just a lot of implementation examples. If you can digest a little German, the correct mathematical definition is given there under "Definition - Für Zufallsvariablen"; It is essentially the mathematical expression of my last post, but it is essential to understand the details; the quantile itself belongs to both sets and the comparisons are larger OR EQUAL and smaller OR EQUAL. That is the definition of quantile, so any implementation should deliver results that can be tested against this definition. A way of doing this is how I wrote it down in my first post.

Statistics books will tell you, that with the implementation of a quantile, you need to distinguish two cases, one where n*p is element in natural numbers and second case, otherwise... In the first case, a whole range of values (if I remember rightly, any value between floor (n*p) and floor(n*p) + 1 fulfills the definition, and here is the case, where implementations and solution truely can differ... In the second case, it MUST be floor(n*p) + 1... n is the overall number of elements in the data set... Hope this helps...

**Comment by Philipp-Seidel** [comment] 2019-04-11 15:53
And this I forgot...
https://de.wikipedia.org/wiki/Quantil_(Wahrscheinlichkeitstheorie)

**Comment by seberg** [comment] 2019-04-11 20:22
@Philipp-Seidel, well I still think it is two different ways of thinking about it. The way numpy uses (and it is not alone in choosing this as the main version I think, but maybe should check) is based on estimating the quantile for the underlying probability distribution (my quick understanding).

Also in the definition you linked, if the random variable is drawn from a continuous distribution, the quantile function does try its best (within the limitations I know it has) to estimate the real quantile, I think. 

I think, one thing to note is that the definition is based on the Probability distribution, while you are arguing based on a small set of numbers drawn *from* that probability distribution.

**Comment by cobykobi** [comment] 2019-04-12 12:28
Even when I apply the german wiki definition for random value:
{\ displaystyle P (X \ leq x_ {p}) \ geq p \ quad} ו {\ displaystyle \ quad P (x_ {p} \ leq X) \ geq 1-p} {\ displaystyle \ quad P (x_ {p} \ leq X) \ geq 1-p}
 This does not hold for the random variable I brought above who takes the values 1,2,3,4,5  each with 0.2 probability. The numpy gives 2.2 for the 0.3 quantile  but P(X>=2.2)>=1-0.3 does not hold for this example.

**Comment by Philipp-Seidel** [comment] 2019-04-12 20:11
@seberg the definition is for continous values. When I refer e.g. to floor(np), I mean the floor(np)th element of the sorted array. 
If you want, I can write you a quantile function that doesnt do mistakes... Should be really fast. Just make case separation between np = natural number and otherwise, in first case, original numpy.quantile works fine, in the second case, the result is floor(np) + 1 (element of sorted array)

**Comment by Philipp-Seidel** [comment] 2019-04-12 20:13
@cobykobi 
That is exactly what I mean... numpy.quantile returns wrong quantiles, that do not fulfill the definition. Btw, in your example, the correct answer is 2. 40% of elements smaller or equal than 2, 80% larger or equal, therefore fulfilling 30% and 70%...

**Comment by eric-wieser** [comment] 2019-04-12 20:23
I think this duplicates #10736

**Comment by seberg** [comment] 2019-04-13 09:08
@cobykobi I think your obesrvation is really what is in gh-10736, I encourage you to read R docs or the wolfram page about it:

https://www.rdocumentation.org/packages/stats/versions/3.5.0/topics/quantile
http://mathworld.wolfram.com/Quantile.html

Yeah, I guess I was confused and this really is the same issue in the end, basically we are probably missing the method that gives what you expect @Philipp-Seidel?

**Comment by Philipp-Seidel** [comment] 2019-04-13 11:56
algorithm quantile(x : dataset, p : float)
     n = dataset.length;
     local_x = dataset.copy();
     if (n*p == floor(n*p)):
           return np.quantile(x, p);
     else:
           local_x = np.sort(local_x);
           return local_x[floor(n*p) + 1];
end quantile.

**Comment by Philipp-Seidel** [comment] 2019-04-13 12:00
This algorithm should perform well... And then: when the if-clause is true, you can use all the different interpolations (lower, higher, average...) to determine at will either the lower limit, upper limit, or whatever value in between in the range of possible quantiles; 
Otherwise, (n*p not a natural number...), there is only one correct answer, the (floor(np) + 1)th element of the sorted array. Cheers

**Comment by Philipp-Seidel** [comment] 2019-04-13 12:28
> ![percentiles](https://user-images.githubusercontent.com/28983449/37341904-fd59d6d4-26ba-11e8-819f-be78062b4012.png)

**Comment by seberg** [comment] 2019-04-13 12:30
@Philipp-Seidel could you confirm that it is indeed then H&F that you are looking for and that this is thus a duplicate of gh-13267?

**Comment by Philipp-Seidel** [comment] 2019-04-13 12:32
> @Philipp-Seidel could you confirm that it is indeed then H&F that you are looking for and that this is thus a duplicate of [gh-13267](https://github.com/numpy/numpy/issues/13267)?

yes :-) We agree to agree

**Comment by seberg** [comment] 2019-04-13 12:34
OK, I will close this then. Sorry for getting confused about what you wanted, I thought it first but somewhere got lost with those `>=`, etc.

It would be good to attack this issue. The reason why it always got stuck a bit is that it would be nice if some statistician could help design a new API (I long think we should probably replace the old one).

**Closed by seberg** 2019-04-13 12:34 UTC

**Comment by Philipp-Seidel** [comment] 2019-04-13 12:42
well, glad I could help. I am not a statistician, just a biologist that takes some university courses to move in direction of computational sciences. But I think, I am okay in math, and if you want me help formulate an API, we can have a try... But I guess, we really discussed the problem now, with algorithm and graph, and I myself understood, why it is such a complex subject, because there are cases, where many results are correct...

**Comment by seberg** [comment] 2019-04-13 12:47
Well, we will not change the default, the question is what options we should provide to keep it full featured but reasonably easy to use....
