### ISSUE TITLE
BUG: Bad behavior of float128 and complex256 on an m2 Mac

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#22796] opened 2022-12-14 07:01 UTC
With numpy built from the main development branch (simply running `pip3 install .` in the source directory) on an m2 Macbook (macOS Ventura 13.0), there is a test of `np.pad` using `dtype` `complex256` that crashes Python.  It looks like there is something wrong with the types `float128` and `complex256`:
```
% ipython
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [2]: np.__version__
Out[2]: '1.25.0.dev0+179.g1a21e72a2'

```
`float128` is only 8 bytes:
```

In [3]: np.float128(3).itemsize
Out[3]: 8
```
Something is wrong:
```
In [4]: np.float128(3)
Out[4]: 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001681872397518720604
```
If I understand https://github.com/numpy/numpy/issues/22290 correctly, the types `np.float128` and `np.complex256` shouldn't even exist for this build.

### NumPy/Python version information:

1.25.0.dev0+179.g1a21e72a2 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]

**Comment by rgommers** [comment] 2022-12-14 08:11
I can confirm that on macOS M1 with numpy 1.23.3, neither `float96` nor `float128` are available. I'd expect M2 to behave the same.

On the other hand, with that same setup, this is also wrong:
```python
>>> np.clongdouble(1.5).itemsize
16
```
Should be 8 bytes, as confirmed by https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms: _The `long double` type is a double precision IEEE754 binary floating-point type, which makes it identical to the `double` type. This behavior contrasts to the standard specification, in which a long double is a quad-precision, IEEE754 binary, floating-point type._

**Comment by seberg** [comment] 2022-12-14 09:12
Maybe @Developer-Ecosystem-Engineering knows where to look at.  If `long double` didn't change in some way, did some defines to detect the CPU change?
The code goes through `strtold`, but since the itemsize and name mismatch here, I would suspect there is some simple issue in the hardware detection.

**Comment by WarrenWeckesser** [comment] 2022-12-14 10:18
@rgommers, `clongdouble` is the complex long double, so it should be an alias for `complex128` (with itemsize 16) or `complex256` (with itemsize 32), depending on the platform.

Running `git bisect` points to the commit d4de105d84e2d097916152b6065b6736b795d187 in https://github.com/numpy/numpy/pull/22614 where the broken `float128` and `complex256` dtypes appear.  Before this, those types are not defined in the numpy namespace.  Maybe the macro check for `APPLE` and  `__arm64__` that was removed is still needed?

**Comment by rgommers** [comment] 2022-12-14 10:33
ugh, not awake yet, of course

> Running `git bisect` points to the commit [d4de105](https://github.com/numpy/numpy/commit/d4de105d84e2d097916152b6065b6736b795d187) in #22614 where the broken `float128` and `complex256` dtypes appear. Before this, those types are not defined in the numpy namespace. Maybe the macro check for `__APPLE__` and `__arm64__` that was removed is still needed?

Thanks for bisecting that. How did you build/install numpy? I'll see if I can reproduce on M1

**Comment by seberg** [comment] 2022-12-14 10:55
Ah, I don't get `float128` on M1; that commit would somehow seem to affect M2 but not M1?

**Comment by WarrenWeckesser** [comment] 2022-12-14 15:03
> How did you build/install numpy?

Python was installed using the installer from https://www.python.org/, and numpy was installed by running `pip3 install .` in the source directory.

**Comment by rgommers** [comment] 2022-12-14 15:27
Must be due to the universal binary install of Python, and the wrong architecture being run for some reason. @WarrenWeckesser could you check if it happens with the Meson build as well? You should see configure output that will be useful:
```
$ python dev.py build
....
Host machine cpu family: x86_64
Host machine cpu: x86_64
...
Checking for size of "double" : 8
Checking for size of "long double" : 16
```

I don't think there's any similar output for `setup.py` in the build log.

**Comment by WarrenWeckesser** [comment] 2022-12-14 16:01
When I use `dev.py`:

```
...
Host machine cpu family: aarch64
Host machine cpu: aarch64
...
Checking for size of "float" : 4
Checking for size of "double" : 8
Checking for size of "long double" : 8
...
```
So it looks like it won't create `float128`, etc.

But when I try to import numpy (with `PYTHONPATH` set to the `site-packages` directory within `numpy/build-install`), I get the old error about being unable to find the symbol `_npy_asinh`:
```
...
Original error was: dlopen(/Users/warren/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002):
symbol not found in flat namespace '_npy_asinh'
```

<details>
<summary>Full import error message</summary>

```
% ipython
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/core/__init__.py:23
     22 try:
---> 23     from . import multiarray
     24 except ImportError as exc:

File ~/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/core/multiarray.py:10
      9 import functools
---> 10 from . import overrides
     11 from . import _multiarray_umath

File ~/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/core/overrides.py:8
      7 from .._utils._inspect import getargspec
----> 8 from numpy.core._multiarray_umath import (
      9     add_docstring, implement_array_function, _get_implementing_args)
     12 ARRAY_FUNCTIONS = set()

ImportError: dlopen(/Users/warren/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_npy_asinh'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import numpy as np

File ~/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/__init__.py:143
    140 # Allow distributors to run custom init code
    141 from . import _distributor_init
--> 143 from . import core
    144 from .core import *
    145 from . import compat

File ~/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/core/__init__.py:49
     25     import sys
     26     msg = """
     27 
     28 IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
   (...)
     47 """ % (sys.version_info[0], sys.version_info[1], sys.executable,
     48         __version__, exc)
---> 49     raise ImportError(msg)
     50 finally:
     51     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11"
  * The NumPy version is: "1.25.0.dev0+183.gfd2639a5c"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/warren/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_npy_asinh'
```

</details>

**Comment by rgommers** [comment] 2022-12-14 17:01
The root cause for the `_npy_asinh` issue (which was gh-22673) is related to the x86-64 static library being included in an arm64 build. Which is wrong, but tends to work when you have Rosetta installed. I hope nothing changed on M2 there. Is this a new machine Warren, and do you by any chance not have Rosetta on it?

**Comment by rgommers** [comment] 2022-12-14 17:09
Ah, I can actually reproduce the `_npy_asinh` one on M1 - I just upgraded to macOS 13 and it appeared. There's a relevant build warning that I think is new:
```
function 'npy_asinh' has internal linkage but is not defined [-Wundefined-internal]
```
I'll look into that.

**Comment by WarrenWeckesser** [comment] 2022-12-14 17:32
>  Is this a new machine Warren, and do you by any chance not have Rosetta on it?

It is a new machine, and I haven't installed Rosetta yet.

**Comment by rgommers** [comment] 2022-12-14 20:49
The `npy_asinh` issue should be fixed in gh-22802. So for this one, we're back to only the original issue: on a universal2 build of Python, there's something wrong with the check for `long double`.

**Comment by rgommers** [comment] 2022-12-14 21:01
I'm inclined to simply revert gh-22614 again. We have no arm64 CI yet (need to add in Cirrus CI), and these universal2 setup.py builds are a mess. If we revert it we can add a note to the header that it can be cleaned up once `setup.py` is gone.

**Comment by mattip** [comment] 2022-12-15 02:45
Can we identify that we are building on a universal2 python and warn/error?

**Comment by rgommers** [comment] 2022-12-15 08:45
I'm not sure how that would help. The python.org installer is popular, so we shouldn't bother all the users of it with a warning that they can't do anything with. The problem isn't even that installer, it's that distutils attempts to build universal2 extensions by default. Meson doesn't have that problem, so it will go away naturally.

**Closed** 2022-12-15 13:08 UTC
Labels: 00 - Bug
