### ISSUE TITLE
ENH: `reshape` should really have a `copy`kwarg.

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#11884] opened 2018-09-05 08:28 UTC
A bit random, but I just read some style guidelines of a larger python project which suggested to use

```python
arr.shape = (100, 10)
# Instead of:
arr = arr.reshape(100, 10)
```
I very much dislike this use, because the ndarray container should be considered immutable IMO. It also is practically pretty useless, the **only** gain is that you implicetely add an assertion:
```python
arr = arr.reshape(100, 10)
assert arr.base is not None
```
Assuming you don't actually want to have the side effect of changing the shape of the array at another place as well (which maybe is reasonable in very rare cases, but horrifies me a bit).

Anyway, reading that suggestion, I think it really is time that we add a `copy=None` kwarg, so that you can do `arr = arr.reshape(100, 10, copy=False)` (or `copy=True`) to be explicit about it without modifying the container.
The only reason that never happened, is because we already have `Reshape` and `NewShape` functions in the `C-API`. Frankly, thats annoying, but for all I care it would be a good start to just add it to the python API without changing the C level one.

**Comment by shoyer** [comment] 2018-09-13 21:26
+1 this seems like a great idea.

**Comment by rgommers** [comment] 2022-03-29 11:54
This is a duplicate of gh-9818. I'll close this and refer back to this issue from that one.

**Closed by rgommers** 2022-03-29 11:54 UTC
