### ISSUE TITLE
Why did't np.sum()  give a RuntimeWarning when overflow encountered in long_scalars

### ISSUE THREAD

**Issue by yichen8** [numpy/numpy#13783] opened 2019-06-14 10:40 UTC
### Reproducing code example:

```python
In [1]: import numpy as np

In [2]: import sys

In [3]: sys.version
Out[3]: '3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]'

In [4]: np.__version__
Out[4]: '1.16.4'

In [5]: np.sum(np.arange(10**5))
Out[5]: 704982704

In [6]: sum(np.arange(10**5))
/Anaconda3/Scripts/ipython:1: RuntimeWarning: overflow encountered in long_scalars
Out[6]: 704982704

In [7]: np.sum(np.arange(10**5, dtype=np.int64)) # right result
Out[7]: 4999950000
```

**Comment by seberg** [comment] 2019-06-14 15:11
This is because numpy does not have overlfow warnings for integer array operations, only for scalar operations (we have many issues open on it, it is a recurring problem). Implementing these is a performance hit, so we would need to change our infrastructure a bit to do it. It could be a nice larger sized project for someone, but it may not be simple.

In case someone tries to reproduce this:

1. This is on windows, so the default integer is 32bit only.
2. sum actually does `0 + ...`, on platforms where the default is 64bits the first cast will cause an upcast to 64bits.

**Comment by yichen8** [comment] 2019-06-14 15:45
Yes, it could be a large project. 

Performance more important than accuracy?  Giving a warning message should be necessary.

Thank you.

**Comment by mattip** [comment] 2019-06-15 18:37
Closing as a duplicate of #8987

**Closed by mattip** 2019-06-15 18:37 UTC
Labels: 50 - Duplicate, 57 - Close?
