### ISSUE TITLE
BUG: set_printoutoptions(legacy=...) is not silent any more

### ISSUE THREAD

**Issue by dimpase** [numpy/numpy#27319] opened 2024-08-31 18:40 UTC
### Describe the issue:

with numpy 2.1.0, one gets undocumented output:
```
>>> np.set_printoptions(legacy="1.25")
<Token var=<ContextVar name='format_options' default={'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': 9223372036854775807, 'override_repr': None} at 0x7f3140e96d40> at 0x7f3140e6d280>
```

### Reproduce the code example:

```python
import numpy as np
np.set_printoptions(legacy="1.25")
```

### Python and NumPy Versions:

```
>>> import sys, numpy; print(numpy.__version__); print(sys.version)
2.1.0
3.12.5 (main, Aug 29 2024, 22:41:14) [GCC 14.2.1 20240817]
```

### Runtime Environment:

```
>>> import numpy; numpy.show_runtime()
[{'numpy_version': '2.1.0',
  'python': '3.12.5 (main, Aug 29 2024, 22:41:14) [GCC 14.2.1 20240817]',
  'uname': uname_result(system='Linux', node='hilbert', release='6.0.8-gentoo-x86_64', version='#2 SMP PREEMPT_DYNAMIC Sun Dec 18 22:31:12 GMT 2022', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Haswell',
  'filepath': '/tmp/a/lib/python3.12/site-packages/numpy.libs/libscipy_openblas64_-ff651d7f.so',
  'internal_api': 'openblas',
  'num_threads': 4,
  'prefix': 'libscipy_openblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.27'}] 
```

### Context for the issue:

documentation does not show any output like this, so it's probably a bug.

It invalidates a lot of doctests for us, too.

**Comment by mattip** [comment] 2024-08-31 18:50
I think this is a duplicate of #27254, which was backported to 2.1.x in #27259, and will be part of the next bugfix release.

**Comment by dimpase** [comment] 2024-08-31 19:14
right. sorry, didn't manage to find the issue you cite

**Comment by charris** [comment] 2024-08-31 20:49
Closing. Thanks for the report.

**Closed by charris** 2024-08-31 20:49 UTC
Labels: 00 - Bug
