### ISSUE TITLE
BUG: Casting to list maintains numpy data types

### ISSUE THREAD

**Issue by MichaelClerx** [numpy/numpy#26730] opened 2024-06-17 19:11 UTC
### Describe the issue:

I didn't see this mentioned in the release notes or migration change, but it's a pretty big change so either a bug or something that needs fixing in the documentation?

```
>>> import numpy as np
>>> np.__version__
'1.24.4'
>>> list(np.array([1,2,3]))
[1, 2, 3]
```

```
>>> import numpy as np
>>> np.__version__
'2.0.0'
>>> list(np.array([1,2,3]))
[np.int64(1), np.int64(2), np.int64(3)]
```

### Reproduce the code example:

```python
import numpy as np
list(np.array([1,2,3]))
```

### Python and NumPy Versions:

2.0.0
3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)]

### Context for the issue:

Causes lots of unit tests to fail, i.e. where numpy output is being compared with results specified as simple lists.

**Comment by rkern** [comment] 2024-06-17 19:16
It's always maintained the scalar types. The only thing that has changed is [NEP 51](https://numpy.org/neps/nep-0051-scalar-representation.html) which makes the `repr()` of numpy scalars explicit.

```python
>>> np.__version__
'1.23.5'
>>> list(np.arange(3))
[0, 1, 2]
>>> [type(x) for x in list(np.arange(3))]
[numpy.int64, numpy.int64, numpy.int64]
```

**Comment by MichaelClerx** [comment] 2024-06-17 19:22
Thanks that makes sense.
It's a bit annoying in doctests though, which now need to be rewritten to avoid things like:
```
Expected:
    59.8733529...
Got:
    np.float64(59.87335290959168)
```
and
```
Expected:
    True
Got:
    np.True_
```
It's easy to fix, but makes the example code look a lot more convoluted

**Comment by ngoldbaum** [comment] 2024-06-17 19:24
You may be interested in "legacy" printing mode: https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html#numpy.set_printoptions

**Comment by ngoldbaum** [comment] 2024-06-17 19:26
It certainly makes it more obnoxious to update doctests, but you could configure your test runner to set that option and then later migrate all your doctests to the new printing format at your leisure.

We did consider the impact this change would have on doctests and decided it was worth it to avoid surprising users, who expect custom types to have custom reprs.

**Comment by rkern** [comment] 2024-06-17 19:28
Please feel free to ask on this thread for help with specific workarounds, but things are working as intended, so I'm going to close this.

**Comment by MichaelClerx** [comment] 2024-06-17 19:28
Thanks for your help. Congratulations on the new release!

**Closed by rkern** 2024-06-17 19:28 UTC
Labels: 00 - Bug
