### ISSUE TITLE
BUG: typings: `a - b` returns `NoReturn` instead of `ndarray`

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#20265] opened 2021-11-01 13:40 UTC
### Describe the issue:

Running
```
pyright foo.py
```
on
```python
import numpy as np


def myfun(x: np.ndarray, b: np.ndarray):
    v = b - x
    v.copy()
```
gives
```
  /tmp/dummy.py:6:7 - error: Cannot access member "copy" for type "NoReturn"
    Member "copy" is unknown (reportGeneralTypeIssues)
```
The vector operations `+`, `*`, `/` work fine.

### NumPy/Python version information:

1.21.3 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0]

**Comment by BvB93** [comment] 2021-11-01 15:42
Duplicate of https://github.com/numpy/numpy/issues/20099 and (to some extent) https://github.com/numpy/numpy/issues/20072.

Interestingly, it appears that this bug is not limited to mypy (xref https://github.com/python/mypy/issues/11347).
Annoying as it is, I'm wondering if it might be best to temporarily remove the dunder overloads...

**Comment by nschloe** [comment] 2021-11-01 15:47
It's funny that only `-` is concerned, not `+`, `*`, or `/`.

**Comment by BvB93** [comment] 2021-11-01 15:52
> It's funny that only `-` is concerned, not `+`, `*`, or `/`.

The problem is that `self` annotations are ignored when a `Any`-parametrized object is passed to an overload method. 
So what happens is that `np.ndarray` (or equivalently `np.ndarray[Any, Any]`) will just pick whatever happens to be the first overload, which turns out to be to `NoReturn` overload used for boolean arrays:
https://github.com/numpy/numpy/blob/fa397e9d9a821a178ad620b28bb334b800d2c93d/numpy/__init__.pyi#L2013-L2014

**Comment by BvB93** [comment] 2021-11-01 16:39
Closing this in favor of https://github.com/numpy/numpy/issues/20099

**Closed by BvB93** 2021-11-01 16:39 UTC
Labels: 00 - Bug, 50 - Duplicate, static typing
