### ISSUE TITLE
DOC: Example in "Writing your own ufuncs" has a bug

### ISSUE THREAD

**Issue by ufrese** [numpy/numpy#25283] opened 2023-11-30 19:14 UTC
### Issue with current documentation:

I tried out the example in "Writing your own ufuncs" at

https://numpy.org/doc/stable/user/c-info.ufunc-tutorial.html 

in particular the single_type_logit.c step. 
Sometimes npufunc.logit did not find the the logic ufunc:

module 'npufunc' has no attribute 'logit'

Sometimes it did find, but crash. The reason seems to lie in the call

PyUFunc_FromFuncAndData(funcs, NULL, types, 1, 1, 1, PyUFunc_None, "logit", "logit_docstring", 0);

It seems to be not allowed to pass NULL as the data parameter (2nd). Instead one has to pass an array containing a NULL:

static void* data[] = {NULL};
...
PyUFunc_FromFuncAndData(funcs, data, types, 1, 1, 1, PyUFunc_None, "logit", "logit_docstring", 0);

Then the example worked. If I am right, please change the documentation.

**Comment by WarrenWeckesser** [comment] 2023-11-30 20:12
Thanks for reporting the issue, @ufrese.  This is a duplicate of https://github.com/numpy/numpy/issues/14613.  The problem should have been fixed by https://github.com/numpy/numpy/pull/20689, which was included in NumPy 1.23.0.  Which version of NumPy are you using?

**Comment by rgommers** [comment] 2023-12-08 09:02
Seems fixed already, so closing. Thanks @ufrese and @WarrenWeckesser

**Closed by rgommers** 2023-12-08 09:02 UTC
Labels: 04 - Documentation, 57 - Close?
