### ISSUE TITLE
BUG: Equality of empty structured arrays

### ISSUE THREAD

**Issue by ghost** [numpy/numpy#11946] opened 2018-09-13 22:09 UTC
Equality checking for empty structured arrays (in particular for
dtypes with shaped subfields) is not consistent with that of empty
unstructured arrays (with and without shapes).

#### Expected behavior: empty structured arrays
```python
import numpy as np

dt = "f4"
x = np.array([], dtype=dt)
y = np.array([], dtype=dt)

x == y
> np.array([], dtype=bool)

np.array_equal(x, y)
> True

np.allclose(x, y)
> True
```
```python
import numpy as np

dt = "(4, 4)f4"
x = np.array([], dtype=dt)
y = np.array([], dtype=dt)

x == y
> np.array([], dtype=bool)

np.array_equal(x, y)
> True

np.allclose(x, y)
> True
```

#### Observed behavior: empty structured arrays
```
import numpy as np

dt = "i8, f4"
x = np.array([], dtype=dt)
y = np.array([], dtype=dt)

x == y
> np.array([], dtype=bool)

np.array_equal(x, y)
> True

np.allclose(x, y)
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2270, in allclose
>    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2360, in isclose
>    dt = multiarray.result_type(y, 1.)
> TypeError: invalid type promotion
```

#### Observed behavior: empty structured arrays with shaped subfields
```
import numpy as np

dt = "i8, (4, 4)f4"
x = np.array([], dtype=dt)
y = np.array([], dtype=dt)

x == y
> np.array([], dtype=bool)

np.array_equal(x, y)
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2428, in array_equal
>    return bool(asarray(a1 == a2).all())
> ValueError: cannot reshape array of size 0 into shape (0,newaxis)

np.allclose(x, y)
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2270, in allclose
>    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2360, in isclose
>    dt = multiarray.result_type(y, 1.)
> TypeError: invalid type promotion
```

#### Empty structured arrays:

> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2270, in allclose
>    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2360, in isclose
>    dt = multiarray.result_type(y, 1.)
> TypeError: invalid type promotion

#### Empty structured arrays with shaped subfields:

`np.array_equal(x, y)`
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2428, in array_equal
>    return bool(asarray(a1 == a2).all())
> ValueError: cannot reshape array of size 0 into shape (0,newaxis)

`np.allclose(x, y)`
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2270, in allclose
>    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
>  File "/home/onalant/source/foo/lib/python3.5/site-packages/numpy/core/numeric.py", line 2360, in isclose
>    dt = multiarray.result_type(y, 1.)
> TypeError: invalid type promotion

### Numpy/Python version information:

```
1.15.1 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56)
[GCC 7.3.0]
```

**Comment by ahaldane** [comment] 2018-09-14 15:47
Both errors confirmed in python2, numpy 1.11.3.

The type promotion bug is due to a more fundamental issue with structured arrays: Doing `x*3` will give you the same type promotion error. It's not clear to me that such a multiplication *should* work. Whether or not that's the case, I can however see there is a TODO comment about structured array in the code for `PyArray_PromoteTypes`, so maybe some fix should be made. Also relevant is that numpy allows casting from float to a structure, eg `np.array([3]).astype(dt)` works, so there may be some inconsistency here.

The `ValueError: cannot reshape` error indeed seems like a bug with empty structured arrays containing subarrays. However, the current behavior of other comparison operators on structured arrays is up in the air (they give DeprecationWarnings), so I would add this to the mental list of things to fix about structured array comparisons. Subarrays in particular are still quite buggy.

**Comment by onalant** [comment] 2018-09-14 20:12
Thank you @ahaldane.

The type promotion error makes more sense to me now. I appreciate
the explanation.

While I would like to be proactive in helping with this issue, I do not
have sufficient knowledge about Numpy internals to make a meaningful
contribution in the short term. Unless there are others who are blocked
by this bug, perhaps it would be best to put this issue on hold (temporary
closure)?

**Comment by ahaldane** [comment] 2018-09-14 20:53
It's best to simply leave the issue open until it is fixed or otherwise resolved. Having a github issue makes it easy for devs to search and track progress, and serves as a reminder that something needs to be fixed.

Thank you for the report, it is important for us to hear about bugs.

**Comment by seberg** [comment] 2022-11-19 09:13
Closing, the shape mismatch error is fixed.  The other is not specific to empty structured arrays, but just `isclose` doesn't work on any structured array since it needs to do math.  So it is much more general.

**Closed by seberg** 2022-11-19 09:13 UTC
Labels: 00 - Bug, component: numpy.dtype
