### ISSUE TITLE
BUG: sdist build fails on Fedora

### ISSUE THREAD

**Issue by stefanv** [numpy/numpy#24401] opened 2023-08-11 20:13 UTC
### Describe the issue:

In `core/setup.py`, `can_link_svml_fp16` does the following check:

```
    if can_link_svml():
        binutils_ver = os.popen("ld -v").readlines()[0].strip()[-4:]
        return float(binutils_ver) >= 2.38
```

`ld -v` returns the following on my machine:

```
GNU ld version 2.37-37.fc36
```

### Reproduce the code example:

```python
`python setup.py sdist`
```

### Runtime information:

N/A

**Comment by rgommers** [comment] 2023-08-11 20:22
That's a bug indeed, thanks for the report Stefan. I'll close this as a duplicate of gh-24195.

**Closed by rgommers** 2023-08-11 20:22 UTC
Labels: 00 - Bug
