### ISSUE TITLE
Feature request: Make numpy.reciprocal equivalent to 1/a

### ISSUE THREAD

**Issue by mruberry** [numpy/numpy#17021] opened 2020-08-06 10:32 UTC
I would like to suggest updating `numpy.reciprocal` to be consistent with `numpy.divide` and Python 3's division operator by having it promote integer inputs to double. Currently, the [docs for reciprocal](https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html?highlight=reciprocal#numpy.reciprocal) say it "is not designed to work with integers... because of the way Python handles integer division." This statement refers to Python 2, not 3, however. 

### Today:
```
import numpy as np
a = np.array((1, 2, 3))
np.reciprocal(a)
: array([1, 0, 0])
```

### Proposed result:

```
array([1., 0.5, 0.33333333])
```

This would make `numpy.reciprocal(a)` equivalent to `(1 / a)`.

cc @rgommers

**Comment by eric-wieser** [comment] 2020-08-06 10:43
Duplicate of #10374

**Comment by rgommers** [comment] 2020-08-06 12:01
Indeed a duplicate, so let's close this issue. Thanks @mruberry and @eric-wieser

**Closed by rgommers** 2020-08-06 12:01 UTC
Labels: 50 - Duplicate
