### ISSUE TITLE
Internal compiler error when installing on Raspberry Pi 4 with RPi OS (Buster)

### ISSUE THREAD

**Issue by mearlboro** [numpy/numpy#21686] opened 2022-06-07 16:29 UTC
### Describe the issue:

```
numpy/core/src/umath/loops_trigonometric.dispatch.c.src:202:20: internal compiler error: in convert_move, at expr.c:218
       NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(FLOAT_@func@)
                          ^
      0xb6b59717 __libc_start_main
          /build/glibc-FUvrFr/glibc-2.28/csu/libc-start.c:308
```

### Reproduce the code example:

```python
pip3 install numpy
```

### Error message:

```shell
https://pastebin.com/EGraqF50
```

### NumPy/Python version information:

Raspberry Pi 4 + Raspberry Pi OS Buster.
Python 3.7.3
Numpy version being attempted is 1.21 (didn't choose it in particular, it's just the one pip would install).

Apt packages installed so far are: 
        - python3
        - python3-pip
        - build-essential                                                                               
        - cmake                                                                                         
        - libhdf5-dev                                                                                   
        - libatlas-base-dev                                                                             
        - gfortran                                                                                      
        - libavcodec-dev                                                                                
        - libavformat-dev                                                                               
        - libswscale-dev                                                                                
        - libv4l-dev                                                                                    
        - libopenblas-dev    
        
I've setup an identical system a year ago, running the exact same code (using Ansible for setup) and there was no issue.

**Comment by mattip** [comment] 2022-06-07 21:22
Duplicate of #23108

**Closed by mattip** 2022-06-07 21:22 UTC
Labels: 00 - Bug
