### ISSUE TITLE
Importing the multiarray numpy extension module failed.

### ISSUE THREAD

**Issue by atulanandnitt** [numpy/numpy#12921] opened 2019-02-02 17:47 UTC
I am trying to execute:
python blur_faces_on_webcam.py

or 

>face_recognition .\examples\knn_examples\train\obama .\examples\knn_examples\t
est\

(djangoVenv)   face_recognition\examples>python blur_faces_on_webcam.py
Traceback (most recent call last):
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: This drive is locked by BitLocker Drive Encryption. You must unlock this drive from Control Panel.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "blur_faces_on_webcam.py", line 1, in <module>
    import face_recognition
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\face_recognition\__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distan
ce
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\face_recognition\api.py", line 5, in <module>
    import numpy as np
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\python_venvs\python3_x\djangoVenv\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: This drive is locked by BitLocker Drive Encryption. You must unlock this drive from Control Panel
.

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by chrisjbillington** [comment] 2019-02-02 21:54
"This drive is locked by BitLocker Drive Encryption. You must unlock this drive from Control Panel."

Did you try doing this?

**Comment by seberg** [comment] 2022-11-06 15:08
Old installation problem, apparently due to bitlocker not allowing a dll load.  That does not sound like something NumPy has to look into (and even if, the issue is very old now), so closing.

**Closed by seberg** 2022-11-06 15:08 UTC
Labels: 32 - Installation
