### ISSUE TITLE
Numpy 1.20.3 detected as trojan

### ISSUE THREAD

**Issue by goitmc** [numpy/numpy#19053] opened 2021-05-20 18:53 UTC
Upgrading from 1.20.2 to 1.20.3 results in McAfee flagging and deleting _common.cp37-win_amd64.pyd
"The Trojan named Artemis!AA5930A5315E was detected and deleted."
### Reproducing code example:

```python
import numpy as np
```

### Error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Continuum\anaconda3\lib\site-packages\numpy\__init__.py", line 156, in <module>
    from . import random
  File "...\Continuum\anaconda3\lib\site-packages\numpy\random\__init__.py", line 179, in <module>
    from . import _pickle
  File "...\Continuum\anaconda3\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 1, in init numpy.random.bit_generator
ModuleNotFoundError: No module named 'numpy.random._common'

### NumPy/Python version information:

Numpy fails to load due to deleted file.  Version reported by pip is 1.20.3.

**Comment by mattip** [comment] 2021-05-20 19:17
Duplicate of #19040, and probable false positive.

**Closed by mattip** 2021-05-20 19:17 UTC
