### ISSUE TITLE
np.asarray for PIL.Image with dtype throw error in python 3.8.10

### ISSUE THREAD

**Issue by outtoin** [numpy/numpy#19386] opened 2021-07-01 10:14 UTC
### Reproducing code example:

```python
import numpy as np
from PIL import Image
arr = np.random.randint(255, size=(100, 100, 3), dtype=np.uint8)
img = Image.fromarray(arr)
np.asarray(img, dtype=np.uint8)
```

This works in python 3.8.5, but not works in python 3.8.10
Otherwise, np.asarray for np.array is works fine both 3.8.5 and 3.8.10
```python
import numpy as np
arr = np.random.randint(255, size=(100, 100, 3), dtype=np.uint8)
np.asarray(arr, dtype=uint8) # works either python 3.8.5 and 3.8.10!
```

### Error message:

```
>>> np.asarray(img, dtype=np.float32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: __array__() takes 1 positional argument but 2 were given
```

---
In python 3.8.5

```python
>>> np.asarray(img, dtype=np.uint8)
array([[[203, 111,  36],
        [162, 137,  13],
        [187, 139,  67],
        ...,
        [ 76, 166, 144],
        [188, 226,  76],
        [ 29,  69, 115]],

       [[ 39, 195,  40],
        [111, 193,  39],
        [  5,   2, 147],
        ...,
        [199, 202, 249],
        [ 57, 115,  24],
        [240, 164,  81]],

       [[228, 114, 115],
        [238, 171, 152],
        [202, 135, 210],
        ...,
        [ 27, 173, 107],
        [160,   4, 217],
        [254,  15, 205]],

       ...,

       [[  1,  31, 234],
        [177, 216,  85],
        [232,  67, 164],
        ...,
        [236, 166,  73],
        [ 11, 195,  78],
        [ 26,  86, 218]],

       [[112, 231, 199],
        [139, 181,  62],
        [166,  84, 193],
        ...,
        [150,  88,  98],
        [244,  51, 230],
        [ 51,  57,   0]],

       [[ 52, 139, 142],
        [189, 220,  28],
        [244, 222, 176],
        ...,
        [238, 239, 134],
        [187,  16, 203],
        [100,  66, 157]]], dtype=uint8)

import sys, numpy; print(numpy.__version__, sys.version)
1.19.5 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0]
```

### NumPy/Python version information:

```python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.19.5 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0]
```

**Comment by seberg** [comment] 2021-07-01 14:09
@outtoin could you check your PIL version to narrow it down? `img.__array__` doesn't even exist on the one I am using, and the problem is related to calling `img.__array__(dtype)` instead of `img.__array__()`.  It may be that the NumPy behaviour changed subtly in 1.19, though.  So that maybe we forgot to pass the `dtype` earlier and PIL was fine to miss it.

There must be some PIL change involved.  It would be good to know whether the PIL version is just very outdated, or a NumPy change is causing problems.

**Comment by JOBR0** [comment] 2021-07-01 15:07
I got the same error with numpy 1.21.0 and Pillow 8.3.0.
If I use Pillow 8.2.0 it works fine.

**Comment by JOBR0** [comment] 2021-07-01 15:20
https://github.com/python-pillow/Pillow/issues/5571

**Comment by seberg** [comment] 2021-07-01 15:21
Thanks!  Going to close this issue, since it seems the pillow folks agree they it is an issue on their side.  But please do make a note here (or open a new issue) if there is anything we can do in NumPy.

**Closed by seberg** 2021-07-01 15:21 UTC

**Comment by outtoin** [comment] 2021-07-02 02:30
@JOBR0 I can't thank you enough. you're my time saver 👍
