### ISSUE TITLE
BLAS issues on OS X 10.10.3

### ISSUE THREAD

**Issue by ppodolsky** [numpy/numpy#5887] opened 2015-05-17 13:54 UTC
It occurs at using scikit TSNE algorthm on the following line:
TSNE(n_components=3, verbose=1).fit_transform(X)

**\* Break **\* bus error
 Generating stack trace...
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8ee1b8ea in cblas_dscal + 0x2f from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8ee6418d in dtrScale + 0x47 from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8edf50b6 in APL_dsyrk + 0xa5 from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8eef3696 in cblas_dgemm + 0x478 from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x000000010a216775 in dotblas_matrixproduct + 0x1665 from /usr/local/lib/python3.4/site-packages/numpy/core/_dotblas.so
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099fb869 in PyEval_EvalFrameEx + 0x51fd from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f64b5 in PyEval_EvalCodeEx + 0x656 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099feb38 in fast_function + 0x141 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099fb6fb in PyEval_EvalFrameEx + 0x508f from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f64b5 in PyEval_EvalCodeEx + 0x656 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x000000010998422f in function_call + 0x174 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000109963e2a in PyObject_Call + 0x67 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099fbdaf in PyEval_EvalFrameEx + 0x5743 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f64b5 in PyEval_EvalCodeEx + 0x656 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x000000010998422f in function_call + 0x174 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000109963e2a in PyObject_Call + 0x67 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099fbdaf in PyEval_EvalFrameEx + 0x5743 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f64b5 in PyEval_EvalCodeEx + 0x656 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099feb38 in fast_function + 0x141 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099fb6fb in PyEval_EvalFrameEx + 0x508f from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f64b5 in PyEval_EvalCodeEx + 0x656 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099feb38 in fast_function + 0x141 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099fb6fb in PyEval_EvalFrameEx + 0x508f from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f64b5 in PyEval_EvalCodeEx + 0x656 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099feb38 in fast_function + 0x141 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099fb6fb in PyEval_EvalFrameEx + 0x508f from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f64b5 in PyEval_EvalCodeEx + 0x656 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001099f5e59 in PyEval_EvalCode + 0x3f from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000109a1a185 in run_mod + 0x3a from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000109a1a424 in PyRun_FileExFlags + 0xb2 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000109a19c31 in PyRun_SimpleFileExFlags + 0x386 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000109a2cfcf in Py_Main + 0xc0b from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
 0x0000000109954e27 in <unknown> from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Resources/Python.app/Contents/MacOS/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8739b5c9 in start + 0x1 from /usr/lib/system/libdyld.dylib

 **\* Break **\* segmentation violation
 Generating stack trace...
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00000001144d5a2c in _ZN5TCint12ResetGlobalsEv + 0x34 from /usr/local/lib/root/libCore.so
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000114481c25 in _ZN5TROOT20EndOfProcessCleanupsEb + 0x33 from /usr/local/lib/root/libCore.so
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x000000011450924c in _ZN11TUnixSystem4ExitEib + 0x40 from /usr/local/lib/root/libCore.so
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000114507aa3 in _ZN11TUnixSystem15DispatchSignalsE8ESignals + 0xe7 from /usr/local/lib/root/libCore.so
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8a511f1a in _sigtramp + 0x1a from /usr/lib/system/libsystem_platform.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x0000000109a0a2a1 in vgetargskeywords + 0x2f0 from /usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/Python
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8ee1bb57 in catlas_dset + 0x2c from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
 0x00007fff8ee1b8ea in cblas_dscal + 0x2f from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8ee6418d in dtrScale + 0x47 from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8edf50b6 in APL_dsyrk + 0xa5 from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x00007fff8eef3696 in cblas_dgemm + 0x478 from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
[invalid usage]: unrecognized option '-d'
Usage: atos [-p pid] [-o executable] [-f file] [-s slide | -l loadAddress] [-arch architecture] [-printHeader] [address ...]
 0x000000010a216775 in dotblas_matrixproduct + 0x1665 from /usr/local/lib/python3.4/site-packages/numpy/core/_dotblas.so

<Here I stopped process>

**Comment by pv** [comment] 2015-05-17 13:59
The errors appear to come from OSX Accelerate. If you are using
multiprocessing (no idea what the scikit does), you cannot use OSX
Accelerate as the BLAS library.

**Comment by rgommers** [comment] 2015-05-17 14:08
It's scikit-learn, this functionality: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/manifold/t_sne.py. I don't see any use of multiprocessing there though. @PashaPodolsky can you provide a self-contained example to reproduce this issue?

**Comment by PashaPodolsky** [comment] 2015-05-17 14:21
Now I've managed to workaround this by configure numpy for the OpenBLAS instead of Acceleration OS X.
The trouble disappeared, so, it's issue of numpy, not of scikit. Is there any places in your code where you are trying to run atos with -d option?
I'll try to provide reproducable example in a time.

Python 3.4
Numpy 1.9.2 installed by pip3
OS X 10.10.3

**Comment by PashaPodolsky** [comment] 2015-05-17 14:28
Just want to point on this line from the opening post:
0x000000010a216775 in dotblas_matrixproduct + 0x1665 from /usr/local/lib/python3.4/site-packages/numpy/core/_dotblas.so

**Comment by pv** [comment] 2015-05-17 14:28
The atos call is probably called directly by OSX/Accelerate to generate
some debugging information.

**Comment by pv** [comment] 2015-05-17 14:30
Yes, the failure occurs inside Accelerate, being called by Numpy.

**Comment by PashaPodolsky** [comment] 2015-05-17 14:31
Okey, I've got it.
If you finally decided that it's not an issue on your side - close it and I'll send it to Apple Developers. Thank you!

**Comment by pv** [comment] 2015-05-17 14:35
@PashaPodolsky: We don't know what is the cause of the failure --- where the crash occurs does not really tell us what is the cause. There are several possibilities, including the multiprocessing issue in which case it is Accelerate issue. A reproducible test case would be needed to trace this.

**Comment by PashaPodolsky** [comment] 2015-05-17 14:54
import numpy as np
from sklearn.manifold import TSNE
X = np.random.rand(70000, 93)
TSNE(n_components=3, verbose=1).fit_transform(X)

**Comment by rgommers** [comment] 2015-05-17 19:27
I can reproduce this. With a smaller matrix ``(20000, 93)`` it doesn't crash though. And I don't see any use of joblib in ``TSNE``. The code is kind of difficult to follow though. I don't have gdb installed on my OS X laptop at the moment. What is needed here is to figure out exactly where the example crashes, and preferably then construct an example that isolates the call to numpy.

**Comment by matthew-brett** [comment] 2015-05-17 20:16
Minimal test case:

```
import numpy as np

X = np.random.rand(70000, 93)
distances = np.dot(X, X.T)
```

Oops.  This is on OSX 10.9, numpy 1.9.2

**Comment by rgommers** [comment] 2015-05-17 20:33
Yep, that segfaults on 10.10.3 built against Accelerate.

**Comment by mattip** [comment] 2019-01-16 08:06
We no longer recommend using Accelerate, it is unsupported by the upstream vendor.

**Closed by mattip** 2019-01-16 08:06 UTC
Labels: 00 - Bug, 57 - Close?, component: numpy.core
