### ISSUE TITLE
random.multivariate_normal broken in python 3

### ISSUE THREAD

**Issue by joergdietrich** [numpy/numpy#7018] opened 2016-01-15 14:23 UTC
The following example

```
mean = [0, 0]
cov = [[1, 0], [0, 100]]
X = np.random.multivariate_normal(mean, cov, 5000)
np.cov(X.T)
```

gives 

```
array([[  1.01629146,   0.13048989],
       [  0.13048989,  99.91261005]])
```

in python-2.7.11 and 

```
array([[  0.24674711,   0.25914975],
       [  0.25914975,  49.40051605]])
```

in python-3.4.4 both with numpy 1.10.2.

**Comment by argriffing** [comment] 2016-01-15 16:39
I cannot reproduce this weirdness.
```
$ python3
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.10.4'
>>> np.random.seed(1234)
>>> mean = [0, 0]
>>> cov = [[1, 0], [0, 100]]
>>> X = np.random.multivariate_normal(mean, cov, 5000)
>>> np.cov(X.T)
array([[  9.97002560e-01,  -5.27846963e-02],
       [ -5.27846963e-02,   9.84156657e+01]])
>>> X = np.random.multivariate_normal(mean, cov, 5000)
>>> np.cov(X.T)
array([[   0.97617963,    0.21704395],
       [   0.21704395,  100.05581608]])
>>> X = np.random.multivariate_normal(mean, cov, 5000)
>>> np.cov(X.T)
array([[  1.00649875,   0.15702974],
       [  0.15702974,  98.43386093]])
```

**Comment by charris** [comment] 2016-01-15 16:50
How did you install numpy? What platform are you on? If you installed numpy yourself, you might want to check that you have made a clean install.

**Comment by joergdietrich** [comment] 2016-01-15 16:55
This is anaconda with mkl optimization on 

```
$ uname -a
Linux shiraz 3.9-1-amd64 #1 SMP Debian 3.9.8-1 x86_64 GNU/Linux
```

**Comment by argriffing** [comment] 2016-01-15 17:26
If something about the installation is broken, then I wonder if `np.test()` would detect it?

**Comment by njsmith** [comment] 2016-01-15 17:36
Wow, that is nasty an extremely nasty bug. I'm glad you caught it before it
wrecked too much havoc! If you did :-(
.
multivariate_normal relies non-trivially on linear algebra internally so I
am suspicious that something has gone wrong with anaconda's MKL integration
code, in which case this will be something that only they can debug or fix,
but it's hard to know for sure. Like Alex says, you should try running
np.test() to see if it catches any other broken things.

**Comment by joergdietrich** [comment] 2016-01-15 21:18
np.test() doesn't run for very long ...

```
Running unit tests for numpy
NumPy version 1.9.3
NumPy is installed in /home/joerg/applications/anaconda3/lib/python3.4/site-packages/numpy
Python version 3.4.4 |Anaconda 2.3.0 (64-bit)| (default, Jan 11 2016, 13:54:01) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
.........................../home/joerg/applications/anaconda3/lib/python3.4/site-packages/numpy/core/fromnumeric.py:2630: RuntimeWarning: overflow encountered in multiply
  return round(decimals, out)
FS....................................................................................................................................................................................S.............F.Segmentation fault (core dumped)
```

I have opened https://github.com/ContinuumIO/anaconda-issues/issues/627

**Comment by njsmith** [comment] 2016-01-16 04:16
Closing here for now then -- feel free to reopen if it turns out to be our bug :-)

**Closed by njsmith** 2016-01-16 04:16 UTC
