### ISSUE TITLE
uint64 converted to float when dividing by python integer

### ISSUE THREAD

**Issue by hmaarrfk** [numpy/numpy#13057] opened 2019-02-28 14:40 UTC
I totally get why it is a cause for concern when adding to an int, but I feel like floor division by a positive should be expected to return an integer "safe". 
### Reproducing code example:
```python
import numpy as np
np.uint64(0) // 4 
```

```
Out[2]: -0.0
```

I guess since I need to divide by 4 I'll just bitshift, but this was kinda unexpected for me.

### Numpy/Python version information:

```
In [3]: import sys, numpy; print(numpy.__version__, sys.version)                                                                                      
1.16.1 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0]
```
installed through conda  / conda-forge

xref: https://github.com/numpy/numpy/issues/5745

**Comment by seberg** [comment] 2022-11-19 13:47
Closing as duplicate of gh-22624

**Closed by seberg** 2022-11-19 13:47 UTC
