### ISSUE TITLE
numpy.distutils.misc_util.appendpath issue

### ISSUE THREAD

**Issue by nrgolovich** [numpy/numpy#5803] opened 2015-04-27 04:52 UTC
I'm using python 2.7, numpy 1.9.1 on OSX 10.9.1

I'm trying to install yt for the dark-sky simulation data access. 

When I execute python setup.py install 

an importerror appears because of the line:

from numpy.distutils.misc_util import appendpath 
saying this doesn't exist. 

Any help would be appreciated, thanks!

**Comment by rgommers** [comment] 2015-04-27 07:44
Works fine for me with 1.9.1. It's likely an issue with your numpy install or PYTHONPATH. Can you execute the following?

    $ python -c "import numpy; numpy.test()"

and

    >>> from numpy.distutils import misc_util
    >>> dir(misc_util)

**Comment by eric-wieser** [comment] 2019-04-20 05:40
Closing this, the issue is old and unreproducible

**Closed by eric-wieser** 2019-04-20 05:40 UTC
