### ISSUE TITLE
np.float32 dtype wrong result in np.linalg.norm and np.dot, attributed to MKL bug

### ISSUE THREAD

**Issue by ZivJia** [numpy/numpy#10918] opened 2018-04-17 03:02 UTC
<img width="847" alt="screen shot 2018-04-16 at 11 01 46 pm" src="https://user-images.githubusercontent.com/31265128/38846412-2fa2cf4a-41ca-11e8-91b7-0157b1a44d1e.png">

**Comment by eric-wieser** [comment] 2018-04-17 03:38
It's hard to debug from an image - can you edit your post to include the text?

What version of numpy?

**Comment by matthew-brett** [comment] 2018-04-17 09:09
Here's something that seems to be equivalent:

```
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
for dtt in (np.float16, np.float32, np.float64):
    print(a1.astype(dtt).dot(a2.astype(dtt)))
```

For that I get the expected:

```
<class 'numpy.float16'> 32.0
<class 'numpy.float32'> 32.0
<class 'numpy.float64'> 32.0
```
with numpy 1.14.2 on Mac, standard pip binary.

**Comment by ZivJia** [comment] 2018-04-17 20:25
import numpy as np
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
for dtt in (np.float16, np.float32, np.float64):
    print(a1.astype(dtt).dot(a2.astype(dtt)))

i used the code provided by matthew-brett
still get the result 32.0   0.0    32.0
the version is 1.13.3

**Comment by matthew-brett** [comment] 2018-04-17 21:34
I get the expected result (32, 32, 32) on Mac, with numpy 1.13.3.

@ZivJia - what platform are you on?  How did you install Numpy?

What do you get for:

```
import numpy
numpy.show_config()
```

**Comment by ZivJia** [comment] 2018-04-18 16:58
mine is Mac too, with numpy 1.13.3 like you do. I upgraded the numpy with pip3 install. 
the configurations are as follows:
<img width="560" alt="screen shot 2018-04-18 at 12 55 45 pm" src="https://user-images.githubusercontent.com/31265128/38946662-267ed5c8-4308-11e8-8974-94cfd866873c.png">

**Comment by matthew-brett** [comment] 2018-04-18 17:30
Ah no - it looks as if you have an Anaconda install (`/Users/zhiyuanjia/anaconda2`), and you are therefore using the Intel Math Kernel Library (MKL).  Maybe you are installing the Numpy pip package via `pip3`, into a Python 3 installation, but you have `anaconda2` earlier in your PATH, hence your output above.

We don't build the Anaconda / MKL package - would you mind raising an issue with the packagers over at https://github.com/ContinuumIO/anaconda-issues/issues ?

**Comment by matthew-brett** [comment] 2018-04-18 17:40
I'm pretty sure you're hitting https://github.com/numpy/numpy/issues/9758 - see that issue for lots of discussion.  It does appear to be an MKL bug, and [appears to be fixed in the latest update of MKL](https://github.com/numpy/numpy/issues/9758#issuecomment-370809277) - maybe updating your Anaconda installation will help?

**Comment by ZivJia** [comment] 2018-04-21 05:16
Thanks i that's the jupyter problem. I tried that in pycharm, it's working properly.

**Comment by mattip** [comment] 2018-04-26 12:12
Duplicate of #9758

**Closed by mattip** 2018-04-26 12:12 UTC
Labels: 00 - Bug, 50 - Duplicate, component: numpy.linalg
