### ISSUE TITLE
numpy.uint64 + int = float64

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#15084] opened 2019-12-10 11:02 UTC
When adding int `1` to a numpy {u}int array, usually a type conversion to int64 happens. This is normal. If, however, the type is `uint64`, the array gets converted to `float64`. I had not expected that. Perhaps it's correct though. Opinions?

MWE:
```python
import numpy

a = numpy.array(0, dtype=int)
print((a + 1).dtype)  # int64

a = numpy.array(0, dtype=numpy.uint16)
print((a + 1).dtype)  # int64

a = numpy.array(0, dtype=numpy.uint32)
print((a + 1).dtype)  # int64

a = numpy.array(0, dtype=numpy.uint64)
print((a + 1).dtype)  # float64!
```

**Comment by nschloe** [comment] 2019-12-10 12:19
I think casting it to `float64` is a sensible choice after all. The problem is that `1` is cast into a `numpy.in64` first. The sum of a `uint64` and an `int64` does not fit into either of the two data types, so out comes a `float64`.

**Comment by seberg** [comment] 2019-12-10 16:02
Closing as duplicate, e.g. of gh-12525. But yes it is an issue. The problem is that the only way to solve such issues would probably to revamp promotion rules within quite a lot. In most languages categories of types (float, int) are well ordered. If they are not things get weird for example.

The int + uint casting for 64bit integers is a bit separate to the dtype ordering though.

**Closed by seberg** 2019-12-10 16:02 UTC
