### ISSUE TITLE
BUG: Building without SIMD instructions results in Illegal Instructions on old systems

### ISSUE THREAD

**Issue by aaron-jencks** [numpy/numpy#27929] opened 2024-12-08 01:37 UTC
### Describe the issue:

I'm trying to install numpy for another repo [freqtrade](https://github.com/freqtrade/freqtrade). It requires numpy v1.26.4, and I'm in the process of verifying the issue on a more recent release v2.1.3.

I'm trying to set up a system to do trading stuff on an old computer, namely a system with a Pentium Pro CPU and 128 MB of RAM. The features of the CPU are extremely limited since the Pentium Pro has NO SIMD extensions. I found a page on your support forum (https://numpy.org/doc/2.1/reference/simd/build-options.html) about compiling numpy for a host system and tried to do that namely:

```
python -m build --wheel -Csetup-args=-Dcpu-baseline="native" -Csetup-args=-Dcpu-dispatch="none"
```

To which I can get the build system to skip trying to detect SIMD extensions, since for some reason it still finds them even though they aren't supported by my processor? I think that may be a different bug wrt the `detect` system detecting unsupported features.

Here is the output of `cat /proc/cpuinfo`
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 1
model name	: Pentium Pro
stepping	: 7
microcode	: 0xc6
cpu MHz		: 199.429
cache size	: 256 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 2
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 mtrr pge mca cmov cpuid pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 398.85
clflush size	: 32
cache_alignment	: 32
address sizes	: 36 bits physical, 32 bits virtual
power management:

```

### Reproduce the code example:

```python
wget https://files.pythonhosted.org/packages/source/n/numpy/numpy-1.26.4.tar.gz
tar -xvf ./numpy-1.26.4.tar.gz
cd numpy-1.26.4
python -m build --wheel -Csetup-args=-Dcpu-baseline="native" -Csetup-args=-Dcpu-dispatch="none"
```

### Error message:

```shell
[272/311] Generating numpy/random/_bounded_integer_pxd with a custom command
FAILED: numpy/random/_bounded_integers.pxd 
/tmp/build-env-72buuq3_/bin/python /home/aaron/workspace/numpy-build/numpy-1.26.4/numpy/_build_utils/tempita.py ../numpy/random/_bounded_integers.pxd.in -o numpy/random/_bounded_integers.pxd
Illegal instruction
[273/311] Compiling C object numpy/linalg/_umath_linalg.cpython-311-i386-linux-gnu.so.p/lapack_lite_f2c_blas.c.o
ninja: build stopped: subcommand failed.

ERROR Backend subprocess exited when trying to invoke build_wheel
```

### Python and NumPy Versions:

python: 3.11.2
numpy: 1.26.4

### Runtime Environment:

I created a virtual environment with the following packages installed:
```
meson 
ninja 
cython==0.29.34  # this is important as newer versions of cython contain illegal instructions as well
build
```

### Context for the issue:

It doesn't really block my work, as I have other systems, but I feel that it should be important that numpy can be compiled without SIMD extensions.

**Comment by mattip** [comment] 2024-12-08 06:18
I think the problem is SSE2. [That processor](https://en.wikipedia.org/wiki/List_of_Intel_Pentium_Pro_processors), whose last iteration came out over 25 years ago, and only supports 32-bit operating systems, lacks any SSE support. I am pretty sure something in compilation of NumPy requires SSE2 but could not find documentation that confirms that. Perhaps we should make that explicit somewhere. In any case, you cannot use any OpenBLAS since 0.26. PR #27851 suggests moving to a minimum of SSE4.1, which would also preclude all "Pentium 4" and other Prescott processors before ["Sandy Bridge"](https://en.wikipedia.org/wiki/List_of_Intel_Pentium_processors) released in 2011. 

If your stack requires NumPy 1.26.4, I doubt the other components will work with a 32-bit CPU without any SSE support. For fun you could try going back in versions with the NumPy wheels on PyPI to find a version that works. You may need to go back as far as 1.7, since I see [1.8 already uses SSE2 loops](https://numpy.org/doc/stable/release/1.8.0-notes.html#performance-improvements-via-sse2-vectorization) but they may be optional if you build your own version from source. Note that version 1.7.2 provides wheels for Python<3.4.

**Comment by ngoldbaum** [comment] 2024-12-08 17:03
I don’t think realistically we can offer support for such an old processor. If in principle the patches to add support are simple (doubt it…) then we might accept that as a PR. I’m going to close this though since I don’t think any of the developers will realistically work on this.

**Closed by ngoldbaum** 2024-12-08 17:03 UTC
Labels: 33 - Question

**Comment by aaron-jencks** [comment] 2024-12-08 18:34
First of all, thank you for responding!

No worries, I will open an issue in the other repo, I don't see how a cryptocurrency trading bot would need such high performance... Maybe I can find a way to remove the dependency from their repo instead, it'd probably be easier.
