### ISSUE TITLE
Error: Import Numpy and Subsequently Pandas with python3.9 on MacOS builds wheels

### ISSUE THREAD

**Issue by hxwood** [numpy/numpy#17475] opened 2020-10-07 00:35 UTC
I do not know how to fix a buggy Accelerate backend..

Input:
`import numpy as np `
or 
`import pandas as pd`

Output:
```
init_dgelsd failed init
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/hannahwood/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/pandas/__init__.py", line 11, in <module>
    __import__(dependency)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/hannahwood/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

```

**Comment by mattip** [comment] 2020-10-07 05:26
Where did you get your python and NumPy from? homebrew? PyPI? If you are building your own, you should find some hints in the error message. If not we need more information.

**Comment by hxwood** [comment] 2020-10-07 09:02
I believe it may be an error with the latest version of python 3.9 that was released on October 5th. I am getting my numpy and pandas directly from the website for python 3.9 download with Mac.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattip** [comment] 2020-10-07 09:19
You will have to wait a few weeks for the ecosystem to catch up. I changed the title to reflect the new information. Closing, duplicate of gh-17482

**Closed by mattip** 2020-10-07 09:19 UTC
