### ISSUE TITLE
BUG: Non-normalized eigenvectors in linalg.eigh for complex hermitian matrix on osx-arm64

### ISSUE THREAD

**Issue by aschelle** [numpy/numpy#21950] opened 2022-07-08 14:30 UTC
### Describe the issue:

The `linalg.eigh` function should return the 'normalized eigenvectors' of a symmetric or hermitian matrix. Below I used a simple symmetric matrix and calculated the determinant (which should be 1) and whether the two eigenvectors are normalized. 
 - When using `dtype=float` for the matrix, the results are correct.
 - When using `dtype=complex` for the matrix, the eigenvectors are not normalized.

I did run the below code on several machines and **only** got the bug on my macbook m1 on arm64. When emulating the `osx-64` numpy package, the result is correct. The concrete versions, which I checked, are listed below.

### Reproduce the code example:

```python
import numpy as np
# Forcing `matrix` to be of dtype=complex
matrix = np.array([[0,1+0j],[1,0]])
eigenvectors = np.linalg.eigh(matrix)[1]
# Check if `The array v of (column) eigenvectors is unitary`
print(1 - abs(np.linalg.det(eigenvectors)))
# Check explicitly if eigenvectors are normalized
print(1 - eigenvectors[:,0].T.conj()@eigenvectors[:,0])
print(1 - eigenvectors[:,1].T.conj()@eigenvectors[:,1])
# All outputs should be close to 0
```

### Error message:

```shell
# OUTPUT on osx-arm64
-1.216802553763662
(-0.9999999999999998-2.2371143170757382e-17j)
(-1.707106781186547-3.251767952832691e-17j)
```

### Versions where the bug occurred
 - 1.23.0 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:05:37) [Clang 13.0.1 ]
   numpy from conda-forge, `osx-arm64`
 - 1.21.5 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ]
    numpy from anaconda channel, `osx-arm64`

### Other versions where the bug did not occur
 - 1.22.3 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] 
    Emulation of `osx-64` on M1
 - 1.21.4 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
    x86_64 linux system

**Comment by rgommers** [comment] 2022-07-09 11:04
```
$ conda list numpy
numpy                     1.22.3           py39h64940a9_2    conda-forge

# Output of reproducer in this issue:
...
1.1102230246251565e-16
(2.220446049250313e-16+0j)
(2.220446049250313e-16+0j)
```

```
$ conda list numpy
numpy                     1.23.0           py39h7df2422_0    conda-forge

# Output of reproducer in this issue:
...
1.1102230246251565e-16
(2.220446049250313e-16+0j)
(2.220446049250313e-16+0j)
```
This is with the default BLAS/LAPACK library, OpenBLAS, version `0.3.18`:
```
libopenblas               0.3.18          openmp_h5dd58f0_0    conda-forge
```

Upgrading to OpenBLAS `0.3.20` reproduces the problem:
```
$ conda list openblas
libopenblas               0.3.20          openmp_h2209c59_0    conda-forge

# Output of reproducer in this issue:
...
-1.216802553763662
(-0.9999999999999998-2.2371143170757382e-17j)
(-1.707106781186547-3.251767952832691e-17j)
```
I believe we already knew that `0.3.20` was buggy, but I can't find the relevant issue right now. @mattip maybe you do?

**Comment by rgommers** [comment] 2022-07-11 12:02
This was https://github.com/MacPython/openblas-libs/issues/83 and https://github.com/xianyi/OpenBLAS/issues/3659

**Comment by h-vetinari** [comment] 2022-07-11 13:36
> This was [MacPython/openblas-libs#83](https://github.com/MacPython/openblas-libs/issues/83) and [xianyi/OpenBLAS#3659](https://github.com/xianyi/OpenBLAS/issues/3659)

I'm not sure these are related TBH. There were some incorrect CFLAGS in https://github.com/MacPython/openblas-libs/issues/83 (blocking compilation), but this looks like OpenBLAS is skipping normalization somewhere.

**Comment by h-vetinari** [comment] 2022-07-11 13:40
I don't have an osx-arm; could you please post the outputs of `np.linalg.eigh(matrix)`, @aschelle?

CC @martin-frbg - any idea why eigenvectors on osx-arm for complex matrices might not get normalized correctly (regression between 0.3.18 & 0.3.20)?

**Comment by rgommers** [comment] 2022-07-11 13:46
Maybe there was yet another ticket. IIRC it was the target architecture being `vortex`, while it should be a generic `arm<xxx>` instead.

**Comment by martin-frbg** [comment] 2022-07-11 13:50
Probably https://github.com/xianyi/OpenBLAS/issues/3654 - long-standing (unnoticed) bug in ThunderX2 DNRM2/ZNRM2 kernel that was exposed by my propagating said kernel to other performant (and less obscure) arm64 cpus in 0.3.19

**Comment by h-vetinari** [comment] 2022-07-11 13:59
Thanks a lot @martin-frbg for the quick response! :)

Is there any timeline for 0.3.21 already?

**Comment by aschelle** [comment] 2022-07-11 14:15
> I don't have an osx-arm; could you please post the outputs of `np.linalg.eigh(matrix)`, @aschelle?
> 
> CC @martin-frbg - any idea why eigenvectors on osx-arm for complex matrices might not get normalized correctly (regression between 0.3.18 & 0.3.20)?

Yes, here is the output for `eigh`:

    >>> np.linalg.eigh(matrix)
    (array([-1.,  1.]), array([[-0.70710678-0.70710678j,  0.70710678+1.20710678j],
       [ 0.70710678+0.70710678j,  0.70710678+0.5j       ]]))'''

Indeed, the real part looks as normalized, but the imaginary part makes no sense to me.

Hopping not to disturb the conversation, but: You are awesome :). Thank you all very much for your time and expertise. It's a real pleasure following the discussion.

**Comment by h-vetinari** [comment] 2022-08-10 07:26
Openblas 0.3.21 is now live & available in conda-forge. Could you try if the issue still persists?

**Comment by rgommers** [comment] 2022-08-12 06:02
It was not fixed in `0.3.21`:

```python
>>> import numpy as np
...
... # Forcing `matrix` to be of dtype=complex
... matrix = np.array([[0, 1 + 0j], [1, 0]])
... eigenvectors = np.linalg.eigh(matrix)[1]
... # Check if `The array v of (column) eigenvectors is unitary`
... print(1 - abs(np.linalg.det(eigenvectors)))
... # Check explicitly if eigenvectors are normalized
... print(1 - eigenvectors[:, 0].T.conj() @ eigenvectors[:, 0])
... print(1 - eigenvectors[:, 1].T.conj() @ eigenvectors[:, 1])
... # All outputs should be close to 0
-1.216802553763662
(-0.9999999999999998-2.2371143170757382e-17j)
(-1.707106781186547-3.251767952832691e-17j)
>>>
>>> eigenvectors
array([[-0.70710678-0.70710678j,  0.70710678+1.20710678j],
       [ 0.70710678+0.70710678j,  0.70710678+0.5j       ]])
>>>
>>> for k, v in threadpoolctl.threadpool_info()[0].items():
...     print(k, v)
user_api blas
internal_api openblas
prefix libopenblas
filepath /Users/rgommers/mambaforge/envs/scipy-dev/lib/libopenblas_vortexp-r0.3.21.dylib
version 0.3.21
threading_layer openmp
architecture VORTEX
num_threads 8
```

**Comment by h-vetinari** [comment] 2022-08-12 07:16
Augh. Could someone with an osx-arm machine raise an issue upstream?

**Comment by martin-frbg** [comment] 2022-08-12 14:30
I cannot reproduce this on my CortexA510 hardware (using either "VORTEX" or "NEOVERSEN1" targets), and I do not have Apple hardware (or access where I could install numpy). (Numpy 1.22.3 I think, termux-supplied libopenblas.so overwritten with own builds)

**Comment by h-vetinari** [comment] 2022-08-12 15:46
Not sure if relevant, but the conda-forge builds for osx-arm currently [set](https://github.com/conda-forge/openblas-feedstock/blob/main/recipe/build.sh#L50-L54) `DYNAMIC_ARCH=0`.

Are you able to reproduce the issue with the conda-forge builds (of numpy+openblas)?

**Comment by martin-frbg** [comment] 2022-08-12 21:51
my builds were DYNAMIC_ARCH=0 as well (and also so far without OpenMP, have not looked up what options you are using in conda-forge). Not sure if I can plug a conda environment into termux without trashing the latter

**Comment by martin-frbg** [comment] 2022-08-13 10:51
Not reproducible on an M1 running Linux either - unfortunately the OSX M1 in the gcc compile farm has been unavailable for some weeks already.

**Comment by isuruf** [comment] 2022-08-23 21:18
Should be fixed with the newest openblas package from conda-forge. It was a gfortran compiler bug.

**Comment by mattip** [comment] 2022-08-23 22:07
If I understand correctly, the problem and the fix are in conda-forge packages, and this does not affect the numpy wheels uploaded to PyPI. If that is true I am not sure what we could backport from this issue to the 1.23.3 release. Or do we need to update to OpenBLAS 0.30.21 in order to avoid the problem?

**Comment by isuruf** [comment] 2022-08-23 22:21
When making numpy wheels with openblas 0.3.20 or 0.3.21 be aware that this issue might come up and if it does bump the gfortran version.

**Comment by charris** [comment] 2022-09-08 18:09
> if it does bump the gfortran version.

NumPy 1.23.x is using 0.3.20, do we need to worry, or is our gfortran version used for wheels sufficient?

**Comment by isuruf** [comment] 2022-09-08 20:13
Yes, you should check before releasing those wheels.

**Comment by charris** [comment] 2022-09-08 20:29
Who can check? I note that 1.23.2 didn't seem to have the problem (?) and I don't think anything should have changed since then.

**Comment by isuruf** [comment] 2022-09-08 21:09
Can confirm that 1.23.2 doesn't have the problem.

**Comment by charris** [comment] 2022-09-08 22:20
@isuruf  Thanks for checking. I'll be releasing 1.23.3 this weekend, so that feedback is helpful.

**Comment by charris** [comment] 2022-10-11 19:02
> It was a gfortran compiler bug.

Going to close this. @isuruf Do you recall the compiler version?

**Closed by charris** 2022-10-11 19:02 UTC
Labels: 00 - Bug, 09 - Backport-Candidate
