### ISSUE TITLE
Dead link to Code of Conduct

### ISSUE THREAD

**Issue by maxkapur** [numpy/numpy#17690] opened 2020-11-02 01:16 UTC
The Code of Conduct link at the following node is a deadend:

https://github.com/numpy/numpy/blob/v1.19.0/.github/CODE_OF_CONDUCT.md

**Comment by mattip** [comment] 2020-11-02 05:48
Duplicate of gh-17458, fixed in gh-17459. There is not much we can do about the tagged versions. I guess we should backport that to the 1.19.x release branch.

**Closed by mattip** 2020-11-02 05:48 UTC
Labels: 04 - Documentation
