### ISSUE TITLE
Numpy 1.16.4 fails to import Python3.7 OSX10.6.8

### ISSUE THREAD

**Issue by amethyst79** [numpy/numpy#13822] opened 2019-06-22 23:51 UTC
Installed Python3.7 (latest which will work) on OSX10.6.8 from installer package ok.
Installed numpy using pip:
python3 -m pip install  numpy
"Successfully installed numpy-1.16.4"
Ran Python program, got error below. Checked path:
echo $PATH
/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
 Same result just typing 'import numpy' from the Python interactive shell.
There is Python2 install aliased as 'python' in /usr/bin - Python2 can import numpy without error.

### Error message:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/overrides.py", line 9, in <module>
    from numpy.core._multiarray_umath import add_docstring, ndarray
ImportError: dynamic module does not define module export function (PyInit__multiarray_umath)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Puzzle_class.py", line 6, in <module>
    import numpy as np
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 
### Numpy/Python version information:

Python 3.7.0:1bf9cc5093 26/6/18
Numpy 1.16.4

**Comment by Xanlarel** [comment] 2019-06-28 00:40
Same issue here

**Comment by mattip** [comment] 2019-07-14 21:38
This is the OSX10.6.8 from 2011? It is going to be difficult for us to replicate the problem enough to fix it.

`ImportError: dynamic module does not define module export function` implies something changed with the runtime loader, perhaps we are not targetting this version any more?

**Comment by oleksandr-pavlyk** [comment] 2020-01-06 19:40
@amethyst79 What exact version of Python 3.7 are you using? Please include output of `python --version`. 

On an unrelated project, on OSX, I see this issue when compiling the native extension with Python 3.7.6, but it works just fine with Python 3.7.3

**Comment by amethyst79** [comment] 2020-01-06 21:16
Python 3.7.0

**Comment by mattip** [comment] 2020-07-13 06:09
Closing due to inaction. Please reopen if this reproduces cleanly with the latest CPython versions.

**Closed by mattip** 2020-07-13 06:09 UTC
Labels: 32 - Installation
