### ISSUE TITLE
Casting object array of uint32 arrays to uint32 array unexpectedly "works"

### ISSUE THREAD

**Issue by cfarrow** [numpy/numpy#7072] opened 2016-01-20 16:40 UTC
`np.array([np.array([1, 2], np.uint32), np.array([3], np.uint32)], object).astype(np.uint32)` gives me `array([0, 3], dtype=uint32)`, `array([3, 3], dtype=uint32)`, or something else entirely on occasion. This is completely different than `np.array([np.array([1, 2], np.int32), np.array([3], np.int32)], object).astype(np.int32)`, which throws a `ValueError`.

This has been verified with numpy `1.9.2` and `1.8.1` on Python 2.7.10, OSX 10.8.5. Also with Python/numpy version combinations  `(2.7.10, 1.9.2)`, `(2.7.11, 1.10.4)` and `(3.5.1, 1.10.4)`, OSX 10.9.5.

Edit: Updated version combinations.

**Comment by seberg** [comment] 2019-03-31 13:48
One heck of a strange bug, but I cannot reproduce it in 1.16 and it is pretty old so I will close it.

**Closed by seberg** 2019-03-31 13:48 UTC
