### ISSUE TITLE
np.average crashes for 1D decimal object array (now only without weights)

### ISSUE THREAD

**Issue by NateyB** [numpy/numpy#8696] opened 2017-02-25 22:51 UTC
I'm running macOS 10.12.3, Python 3.6.0, and NumPy 1.12.0.

When using the decimal package with NumPy, the arrays are of type 'object'. While most operations are performed flawlessly, calling np.average() with one of these arrays throws an error if weights are not provided (`AttributeError: 'decimal.Decimal' object has no attribute 'dtype'`), and a different error if weights are provided (`AttributeError: 'bool' object has no attribute 'any'`). Contrarily, calling np.mean() executes without error.

The source of the problem in both cases appears to be the assumption that the result of folding the input array results in a standard supported dtype, rather than being based on the operations available to the object type.

Therefore, I suspect that this issue will extend to any types which support the requisite numeric operations but are not natively supported by NumPy.

I resolved the weighted problem for my use case by changing the line `if (scl == 0.0).any()` (line 1138 in `lib/function_base.py`) to check if scl were an array first, and if not then removing the `any()` call, though I don't know if that solution is desirable or acceptable for the purposes of NumPy.

Sample input:
```
import numpy as np                                                              
import decimal as dc                                                            
                                                                                
values = np.array([dc.Decimal(x) for x in range(10)])                           
weights = np.array([dc.Decimal(x) for x in range(10)])                          
weights /= weights.sum()                                                        
                                                                                
print(np.mean(values))                                                          
print(np.average(values, weights=weights))                                      
```

Corresponding output:
```
4.5
Traceback (most recent call last):
  File "bugreport.py", line 9, in <module>
    print(np.average(values, weights=weights))
  File "/usr/local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1138, in average
    if (scl == 0.0).any():
AttributeError: 'bool' object has no attribute 'any'
```

**Comment by warut-vijit** [comment] 2017-03-04 04:01
Yes, this seems like a bug and certainly doesn't reflected the intended behavior as described in the docs. Decimal arrays should be acceptable as arguments for this function.

**Comment by vbar** [comment] 2019-04-12 16:56
Apparently the problem had regressed - I've just seen it with numpy 1.16.2 (Python 3.7 on Windows).

**Comment by eric-wieser** [comment] 2019-04-13 07:15
The test is still there, and presumably passing in CI:

https://github.com/numpy/numpy/blob/dea1239b6dcaf072fc9b70e6af0c0a100cead69e/numpy/lib/tests/test_function_base.py#L376-L380

Either your installation is a mixture of different versions, or you're seeing a different problem

**Comment by vbar** [comment] 2019-04-15 06:34
I presume the test is for the case when weights are provided; my problem appears for average without weights:

Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit
(AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import decimal
>>> a = np.array([decimal.Decimal(x) for x in range(10)])
>>> np.average(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\function_base.py", line 393, in average
    scl = avg.dtype.type(a.size/avg.size)
AttributeError: 'decimal.Decimal' object has no attribute 'dtype'
>>> np.__version__
'1.16.2'

A mixture of different versions is quite improbable - this is a new computer for a new project, where I've just installed Python and numpy...

**Comment by eric-wieser** [comment] 2019-04-15 06:46
Turns out we didn't read the issue carefully enough:

> throws an error if weights are not provided (`AttributeError: 'decimal.Decimal' object has no attribute 'dtype'`), and a different error if weights are provided (`AttributeError: 'bool' object has no attribute 'any'`)

We only fixed one of these two problems.

**Comment by caioaamaral** [comment] 2020-12-03 15:33
Any updates on this? I've found similar issue, but without the `dc.Decimal(x)`

```py
x_model = np.average(x, weights=weights)  # where x and weights are a np.array of floats
```

Output error is (run at `Python 2.7.12` and `numpy 1:1.11.0-1ubuntu1`):

```log
 File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 946, in average
    if (scl == 0.0).any():
AttributeError: 'bool' object has no attribute 'any'
```

Upgrade numpy to 1.16 solves the issue for me.

**Comment by seberg** [comment] 2022-06-15 00:31
The issue seems to be still relevant when `weights` are *not* given.

**Comment by WarrenWeckesser** [comment] 2024-12-16 00:01
Can anyone still reproduce any of the problems reported here?  With Python 3.12.8 and numpy 2.2.0 on Linux, @vbar's example works for me:

```
In [1]: np.__version__
Out[1]: '2.2.0'

In [2]: import decimal

In [3]: a = np.array([decimal.Decimal(x) for x in range(10)])

In [4]: np.average(a)
Out[4]: Decimal('4.5')
```

**Comment by WarrenWeckesser** [comment] 2024-12-16 01:20
I added @vbar's example as a unit test in https://github.com/numpy/numpy/pull/28009, and it passed on all platforms. So unless someone can give an example that crashes with numpy 2.2.0, I think we can close this issue.

**Comment by seberg** [comment] 2024-12-16 07:52
yes, we changed any/all to return bools.

**Closed by seberg** 2024-12-16 07:52 UTC
Labels: 00 - Bug, component: numpy.lib
