### ISSUE TITLE
np.random.choice slower than np.random.multinomial (again)?

### ISSUE THREAD

**Issue by achalddave** [numpy/numpy#7543] opened 2016-04-13 04:43 UTC
Issue #4188 originally pointed out that np.random.multinomial is faster than np.random.choice by a factor of 10. This was supposed to be fixed by a few commits mentioned in that issue, but I'm seeing np.random.multinomial faster than np.random.choice again by a factor of 3:

```
In [4]: probs = [1/50.] * 50

In [5]: %timeit np.random.choice(50, p=probs)
The slowest run took 7.32 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 17.3 µs per loop

In [6]: %timeit np.random.multinomial(1, probs).argmax()
The slowest run took 8.11 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.67 µs per loop
```

**Comment by jvd10** [comment] 2016-08-23 23:20
I think that I can confirm that this is still an issue with 1.11.1

`print(np.__version__)`
`probs = [1/50.] * 50`
`%timeit -n 1 -r 1 [np.random.choice(50, p=probs) for x in range(1000)]`
`%timeit -n 1 -r 1 [np.random.multinomial(1, probs).argmax() for x in range(1000)]`

`1.11.1`
`1 loops, best of 1: 33.5 ms per loop`
`1 loops, best of 1: 7.27 ms per loop`

**Comment by bashtage** [comment] 2019-06-01 05:29
@mattip Looks to be fixed in `Generator`. Can't be fixed in `RandomState`

```python
In [8]: rg = np.random.Generator()

In [9]: %timeit rg.choice(50, p=probs)
37.3 µs ± 5.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [10]: %timeit rg.multinomial(1, probs).argmax()
28.5 µs ± 4.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by mattip** [comment] 2019-06-01 19:57
OK, closing. If you wish better performance, use the new APIs.

**Closed by mattip** 2019-06-01 19:57 UTC
Labels: 01 - Enhancement, component: benchmarks, component: numpy.random

**Comment by bjourne** [comment] 2020-05-30 13:31
`np.random.multinomial` is still faster:

```python
In [151]: rg = np.random.default_rng()                                                                                                                                          

In [152]: %timeit rg.multinomial(1, P, 1).argmax()                                                                                                                              
28.1 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [153]: %timeit rg.choice(len(P), p = P)                                                                                                                                      
40 µs ± 511 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Additionally, the calls return different values even if you initialize the generator with the same seed:
```python
In [158]: np.random.default_rng(1234).choice(len(P), p = P)                                                                                                                     
Out[158]: 48

In [159]: np.random.default_rng(1234).multinomial(1, P, 1).argmax()                                                                                                             
Out[159]: 33
```

**Comment by bashtage** [comment] 2020-06-02 08:29
Depends on size of `P`.

```
n=1000

P=np.ones(n) / n

%timeit rg.multinomial(1, P, 1).argmax()
27.1 µs ± 239 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit rg.choice(len(P), p = P)
24.7 µs ± 223 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

n=1000000

P=np.ones(n) / n

%timeit rg.multinomial(1, P, 1).argmax()
17.3 ms ± 833 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit rg.choice(len(P), p = P)
7.7 ms ± 36.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops eac
```

Since multinomial isn't always faster, it isn't worth changing for very small performance gains in some cases. 

The values are different since choice doesn't use multinomial under the hood.
