### ISSUE TITLE
internal compiler error when compiling on ARM v8 ThunderX2 

### ISSUE THREAD

**Issue by undertherain** [numpy/numpy#13622] opened 2019-05-25 13:03 UTC
Compilation of NumPy 1.16.x fails when I compile it on a machine with Cavium ThunderX2 CPU

Versions 1.15.4 and below compile normally

### Reproducing code example:

get last stable release, run `python3 setup.py install`
or `pip install`

### Error message:
the first error which is not from  _configtest.c is

```gcc: build/src.linux-aarch64-3.7/numpy/core/src/npymath/npy_math_complex.c
In file included from numpy/core/include/numpy/npy_math.h:580:0,
                 from numpy/core/src/npymath/npy_math_common.h:9,
                 from numpy/core/src/npymath/npy_math_complex.c.src:34:
numpy/core/src/npymath/npy_math_internal.h.src: In function ‘npy_cacoshf’:
numpy/core/src/npymath/npy_math_internal.h.src:482:12: internal compiler error: Segmentation fault
     return @kind@@c@(x, y);
            ^~~~~~~~~~~~~~~
0x994aff crash_signal
````
full compilation log: https://pastebin.com/83Jj3knk

### Environment:
OS: CentOS Linux release 7.6.1810 (AltArch)
Python 3.7.2, tried several other versions.
GCC 7.4.0, also tried system's default 4.8.5
CPU: 
```	
Family: ARM
Manufacturer: Cavium Inc.
ID: F1 0A 1F 43 00 00 00 00
Signature: Implementor 0x43, Variant 0x1, Architecture 15, Part 0x0af, Revision 1
Version: Cavium ThunderX2(R) CPU CN9975 v2.1 @ 2.0GHz
```

**Comment by tylerjereddy** [comment] 2019-05-28 03:00
Hmm, ARMv8 testing is part of our CI these days--I wonder what is so different about your setup? Pretty sure shippable is using Ubuntu for their native builds--so that's one difference.

**Comment by undertherain** [comment] 2019-05-29 13:55
Well, one thing I should mention is that we have x64 nodes with _amlost_ identical software stack (same OS, packages version, Python installed with same spack comand etc) - and NumPy 1.16.x compiles ok. 
I'm be able to physically access servers in a couple of weeks and try to live-boot to ubuntu arm server and try compiling on it, if no other solutions emerge until then...

**Comment by crbaird** [comment] 2019-06-07 17:34
I'm also seeing this issue on CentOS 7.6. Interestingly, it builds just fine on the same hardware with SLE 12 SP4.

**Comment by mattip** [comment] 2019-06-11 06:30
I am not sure we can help with this too much since our CI succeeds. What compiler is SLE 12 SP4 using? 

You might be able to extract this as a stand-alone compiler bug by looking a few lines up for the actual gcc call and the gcc-options, then whittling down the example until it fails, starting off by removing unneeded include paths. Mine is below. Note the file you want to compile is actually the processed `numpy/core/src/npymath/npy_math.c`

<details>
```
x86_64-linux-gnu-gcc -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -Inumpy/core/include -Ibuild/src.linux-x86_64-3.6/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -I/path/to/python/include/python3.6m -Ibuild/src.linux-x86_64-3.6/numpy/core/src/common -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.6/numpy/core/src/common -Ibuild/src.linux-x86_64-3.6/numpy/core/src/npymath -c numpy/core/src/npymath/npy_math.c
```

**Comment by eric-wieser** [comment] 2019-06-11 06:47
It would be useful to know what the value of `NPY_USE_C99_COMPLEX` is on your build - that seems like the most likely difference between 1.15 and 1.16

**Comment by linedot** [comment] 2019-06-17 21:02
Experiencing the same issue on CentOS 7.6 on Huawei Taishan 2280 ARM64 servers. 
[Reduced example](https://godbolt.org/z/aE8jHX) not failing to compile on native GCC versions 8.2.0, 8.3.0 and 9.1.0
Any advice on further debugging?

**Comment by siddhesh** [comment] 2019-10-09 21:54
An ICE would typically mean a compiler bug.  I'll see if I can find a centos box to reproduce this.

**Comment by siddhesh** [comment] 2019-10-10 17:15
Sorry I couldn't find a suitable machine to reproduce this.  If someone can give me access I'll be happy to help isolate the problem.

**Comment by maxim-kuvyrkov** [comment] 2019-10-23 14:51
I've reproduced this on cortex-a72 with both CentOS 7.6 and Ubuntu 18.04.  I'm looking into this.
The hunch that this is a glibc bug (also my first guess) seems to be wrong.  The crash reproduces with glibc-2.27.

Please report bugs like this to the upstream community (https://gcc.gnu.org/bugzilla/).  The GNU Toolchain community prioritizes ICE (internal compiler error) and wrong-code bugs.  Most of the time you just need to attach pre-processed source file and cc1 command line -- add "-v -save-temps" to compilation flags to get these.

**Comment by nSircombe** [comment] 2019-10-23 15:01
Not reported as a NumPy failure, but it is here:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90075

...and fixed, I believe.

NumPy builds with 9.2.0 on Aarch64 for me now.

**Comment by maxim-kuvyrkov** [comment] 2019-10-23 15:12
@nSircombe , thanks!  This saved me some cycles digging into this further.  The patch was backported to gcc-7 and gcc-8 release branches, and will be in next update releases, which distros should pick up.
GCC 7.5 is expected to release in the next couple of weeks, and will be the final GCC 7 update.
Is anything else required from GCC side of things?  Or should this be closed?

**Comment by nSircombe** [comment] 2019-10-23 16:20
I've not tested the newer versions of GCC 7 & 8. But I can confirm that `pip install numpy` works for 9.2.0.

**Comment by maxim-kuvyrkov** [comment] 2019-10-23 16:47
Confirmed that GCC 7 built from current gcc-7-branch works fine.

**Comment by mattip** [comment] 2019-10-23 18:01
Thanks for the detective work. Should we wait for the toolchain to be released to close this?

**Comment by BaptisteGerondeau** [comment] 2019-11-14 13:56
Release 1.17.4 has moved things around, and the above workaround patch is no longer applicable. Here is what works for me at the moment :

```
--- numpy/core/src/npymath/npy_math_internal.h.src.orig	2019-11-14 12:20:01.387180922 +0000
+++ numpy/core/src/npymath/npy_math_internal.h.src	2019-11-14 12:19:17.960646234 +0000
@@ -477,7 +477,7 @@
  * #KIND = ATAN2,HYPOT,POW,FMOD,COPYSIGN#
  */
 #ifdef HAVE_@KIND@@C@
-NPY_INPLACE @type@ npy_@kind@@c@(@type@ x, @type@ y)
+NPY_INPLACE __attribute__((optimize("-O0"))) @type@ npy_@kind@@c@(@type@ x, @type@ y)
 {
     return @kind@@c@(x, y);
 }
```
Not sure if it is the "best" (least worse) workaround though, feel free to give some feedback !

**Comment by mattip** [comment] 2020-03-07 21:06
Closing, please reopen if there are still problems with this particular toolchain.

**Closed by mattip** 2020-03-07 21:06 UTC
Labels: component: build
