### ISSUE TITLE
`np.multiply` vs. `*` 

### ISSUE THREAD

**Issue by arokem** [numpy/numpy#7428] opened 2016-03-17 15:13 UTC
In the course of our work over on [dipy](https://github.com/nipy/dipy/pull/951), we stumbled into the following behavior:

The following line: 
https://github.com/nipy/dipy/blob/master/dipy/denoise/shift_twist_convolution.pyx#L68

raises this error (on np 1.11, but not earlier): 

```
Traceback (most recent call last):
  File "contextual_enhancement.py", line 149, in <module>
    sh_order=8, test_mode=True)
  File "dipy/denoise/shift_twist_convolution.pyx", line 68, in dipy.denoise.shift_twist_convolution.convolve (dipy/denoise/shift_twist_convolution.c:2147)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

When changed to this: 

https://github.com/stephanmeesters/dipy/blob/enhance_5d_update_pr/dipy/denoise/shift_twist_convolution.pyx#L69

This error no longer occurs. What does the error mean (it's a bit opaque in this context), and how do we avoid it in the future?

Thanks!

**Comment by rkern** [comment] 2016-03-17 15:17
What does `output_norm = output * (np.amax(odfs_dsf)/np.amax(output))` do? If you run that function under pure Python (no Cython) what does it do?

**Comment by charris** [comment] 2016-03-17 15:35
Note that float indexes will not error in Numpy 1.11, we reverted that to allow more time for downstream projects to adjust. There has been a deprecation warning out for ~1.5 years, and the error will return in 1.12.

**Comment by seberg** [comment] 2016-03-17 15:41
The reason should be that `output` is actually a sequence and not an ndarray but you actually

**Comment by seberg** [comment] 2016-03-17 18:25
On second thought, I really get confused and I think Robert Kern is right to ask what even happens, also outside Cython.
output should be a typed memoryview, how is the multiplication of a typed memoryview even *defined* in Cython? My first guess is, it is not, so that numpy converts the memoryview to an array.

My guess is, the change does not change the output?! So for some reason the numpy scalar got first shots at trying to repeat the sequence and then Cython multiplied elementwise? Or did numpy try to repeat the sequence, and when it fails tries to convert to ndarray instead?

**Comment by njsmith** [comment] 2016-03-17 18:39
Here's a simplified case, without Cython (trying on py34):
```
In [8]: m = memoryview(np.ones(3))

In [9]: m * 4
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-a2ec8a2e7818> in <module>()
----> 1 m * 4

TypeError: unsupported operand type(s) for *: 'memoryview' and 'int'

In [10]: m * np.int64(4)
Out[10]: array([ 4.,  4.,  4.])

In [11]: m * np.float64(4.1)
/home/njs/.user-python3.4-64bit/bin/ipython:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  #!/home/njs/.user-python3.4-64bit/bin/python3.4
Out[11]: array([ 4.1,  4.1,  4.1])
```

So it looks like `memoryview.__mul__` just returns `NotImplemented` pretty much always. So then the array scalar's `__rmul__` gets called, and it does an odd thing: it seems to always coerce the memoryview to an array and perform elementwise multiplication (good), but for a float array scalar somehow in the process it triggers the `__index__` warning. Notice that this doesn't affect the final result, though -- the float is not truncated, and it never does sequence repetition (even when passed an integer).

Also note that `ndarray` itself does not hit this warning -- only the scalar does:
```
In [12]: m * np.array(4)
Out[12]: array([ 4.,  4.,  4.])

In [13]: m * np.array(4.0)
Out[13]: array([ 4.,  4.,  4.])
```

So the current mystery is, where is that warning being issued in `memoryview * np.float64(4.1)`?

**Comment by seberg** [comment] 2016-03-17 18:39
Bah, this is crazy. What used to happen in cases such as this was this:
```
If (other object has no multiply slot):
     as_int = int(scalar)  # failure, will error, but all numerical types can do this
    try:
         operator.repeat(other, as_int)
   except:
         pass

return np.multiply(other, scalar)  # or something similar.
```
Now we want to make the `int` more strict so that `[1, 2, 3] * np.float64(3.5)` will not work, but then the `np.multiply` fallback for when the other does not even support repeating does not get executed.

My guess: We should test whether the other object claims to have a sequence repeat implemented, and otherwise deirectly call the numpy multiply/equivalent logic (I am a bit suprised, I somewhat thought we have a special scalar*scalar case, but that is orthogonal).

**Comment by seberg** [comment] 2016-03-17 18:41
It appears we should have been giving spurious warnings for this case all along, since it probably should keep working and was never a sequence repeat here.

**Comment by njsmith** [comment] 2016-03-17 18:42
Wow. I didn't know that this `nb_mul`/`sq_repeat` mess could get *worse* :-(

**Comment by seberg** [comment] 2016-03-17 18:49
Well, my guess is, it should be easy enough to fix, just reverse the seq logic....

**Comment by njsmith** [comment] 2016-03-17 21:07
Yeah, it sounds like it would be a straightforward fix to make it instead look like
```
if (other object has sq_repeat) and (I am an integer):
    call sq_repeat
else:
    ...
```
I guess during the deprecation period it would instead be
```
if (other object has sq_repeat) and (int(self) succeeds):
    if (index(self) raises an error):
        warn
    call sq_repeat
else:
    ...
```

My broader concern is that it's very very unclear to me whether this fall-back to `sq_repeat` logic is correct at all. Should we check for `NotImplemented`, surely it's somehow a bug that `[1, 2] * np.array(2)` and `[1, 2] * np.int64(2)` return different results, *cough* `__numpy_ufunc__` *cough*, etc. etc. I guess we don't need to deal with this broader issue though right now -- we should probably make the simple fix just to get rid of the spurious warning first.

**Comment by seberg** [comment] 2016-03-17 21:52
Not quite right I guess. Question is whether we want `[1, 2, 3, 4] * np.float64(3.5)` to raise or convert the list to an array.
As it currently repeats the list, I think it should be an error, so we don't have to care whether the the scalar can be made an integer.

Or maybe a better argument, we must *not* care whether or not the scalar is integer because:
```
[1, 2, 3] * np.float64(3.)
```
must be identical to
```
[1, 2, 3] * 3
```
*unless* it raises an error. I know there are good reason why one might expect the array multiply logic in the float case, but here it just seems to fall into a dark pit of ugliness if you try to make it work. All fancier array-likes will already know how to multiply with a scalar anyway.

**Comment by njsmith** [comment] 2016-03-17 22:50
My knee-jerk response is that `list * numpy scalar` should always convert to an array, because I don't like inconsistencies between 0dim arrays and scalars, and:
```
In [1]: [1, 2, 3] * np.array(3.)
Out[1]: array([ 3.,  6.,  9.])

In [2]: [1, 2, 3] * np.array(3)
Out[2]: array([3, 6, 9])
```
(And the 0dim array behaviour I think is correct, because we obviously want this for arrays with >=1 dimension, and we'd really like to avoid adding more 0dim special cases.)

Not sure if whether or not I trust this knee-jerk response though.

I think it's more important that `[1, 2, 3] * np.float64(3.5)` and `[1, 2, 3] * np.float64(3.0)` do the same thing, then that it is that `[1, 2, 3] * np.float64(3.0)` and `[1, 2, 3] * np.int64(3)` do the same thing.

Note also that in pure python:
```
In [3]: [1, 2, 3] * 3.0
TypeError: can't multiply sequence by non-int of type 'float'
```
so there's definitely no reason to make `[1, 2, 3] * np.float64(3.0)` repeat except for the backcompat issue.

I guess we don't really have to decide on the final outcome right now -- the likely possibilities are to either to make `[1, 2, 3] * np.float64(...)` an error, or else to make it convert-to-array... and even if we do want to make it convert-to-array, passing through an error state in between is probably a good idea, so our next step is the same in either case. I expect it is *very* rare that people are depending on the repeat behavior for numpy floats here, but still better safe than sorry.

What's less obvious is what `[1, 2, 3] * np.int64(...)` should do. I think there's a pretty reasonable argument that we might want to deprecate the repeat interpretion here, just because it's very ambiguous what should happen. But that's probably far enough from the original issue that it should be handled as a separate issue.

So I think that suggests that the immediate fix for this issue is:
```
if (other argument has sq_repeat):
    try:
        i = index(self)
    except:
        i = int(self)
        issue deprecation warning for index
        call sq_repeat
```

sound right?

**Comment by seberg** [comment] 2016-03-17 23:21
Sorry, my first reaction was too far in the other direction. The 0D array is the big issue, I agree and I doubt there is any good solution, but somehow overlooked how big the issue is. In the end, I am not sure...

But I guess we are stuck with an error on floats for now in any case for starters. And that is already the case for master. And then we could go from there to the other way around.
Since we are using a VisibleDeprecationWarning now fixing it even in 1.11 could be nice, but maybe not a priority.

**Comment by charris** [comment] 2016-03-17 23:27
I don't want to do anything more for 1.11, 1.12 will be branched soon enough.

**Comment by seberg** [comment] 2016-03-18 06:54
Sure. If someone else complains we can put it into a point release if there is one.

**Comment by arokem** [comment] 2016-03-18 16:17
Thanks everyone for the comments. I think that we have a fix for now, and
you all seem to know what's going on... My only (and possibly
not-too-useful; I'm definitely out of my depth...) comment is that if this
indeed keeps raising an error -- the index error was quite confusing (to
me), so if it is possible to catch this kind of thing and give users some
more direct guidance, that would be great. If you want to close this issue,
that's OK with me, or keep it open, if you want to keep it around. As
always - thanks for everything that you do!

**Comment by OmerJog** [comment] 2019-10-17 21:01
Is this still needed?

**Comment by seberg** [comment] 2019-10-17 21:08
Hmmm, good question. Currently `list * float_scalar` is an error, while `list * 0D_array` gives `np.multiply` (array) behaviour.

So, there may still be the open question of making `list * float_scalar` convert to arrays, but since it is an error currently, I am wondering if it might make sense to just leave things as is right now. Are you running into this as an issue?

**Comment by seberg** [comment] 2021-05-27 06:03
Close it, as the last comment said:
```
[1, 2, 3] * np.float64(4.1)
```
raises and mismatches with 0-D arrays.  But that is tricky and most of the discussion is about things that are not relevant anymore.  We should just open a new issue when we run into it again.

**Closed by seberg** 2021-05-27 06:03 UTC
Labels: 00 - Bug, 06 - Regression, 57 - Close?
