### ISSUE TITLE
random.random_integers fails if upper bound is 2**31 or higher

### ISSUE THREAD

**Issue by eraoul** [numpy/numpy#4085] opened 2013-11-30 22:07 UTC
This code gives an error (I tried numpy 1.7.1 and 1.8.0; I'm using 64-bit versions in Windows 8.1 64 bit, with python 2.7.5, Anaconda 1.8.0 64 bit)

x = numpy.random.random_integers(2**31,size=1).astype(numpy.uint64)

"Python int too large to convert to C long"

Note that the docs don't specify an upper bound on the range. This behavior is confusing.

If 2**31 is replaced by 2**30 it works fine.

**Comment by dhirschfeld** [comment] 2015-08-11 01:25
Just bitten by this :frowning:. I understand that it's not a bug per-se but it would still be great if someday this was fixed. 

Perhaps this issue could be left open as an enhancement issue? At least that way it would have some visibility and might get picked up at a future numpy sprint.

**Comment by njsmith** [comment] 2015-08-11 01:50
We definitely would be happy to provide some way to sample 64 bit integers,
but it's not obvious how it should work technically. A general rule we
follow is that the dtype returned by a function should not depend on the
specific numerical values passed to that function. On win64, these
functions return an int32 dtype, because that's thid platform's default
integer in general. (Maybe it shouldn't be, but the point is it's a much
more general thing, e.g. array([1, 2, 3]) returns an int32 array.) And
obviously you can't get 64 bit integers into an int32 array.
.
Maybe the thing to do is to add a dtype= argument to the methods? Where if
dtype=int64 then it accepts larger input integers?

**Comment by pv** [comment] 2015-08-11 07:29
dtype= argument sounds good to me. Reopen?

**Comment by bashtage** [comment] 2016-07-11 07:57
@rkern Is this still relevant given the `dtype` changes in random integers?

**Comment by rkern** [comment] 2016-07-11 13:10
Fixed by #6910

**Closed by rkern** 2016-07-11 13:10 UTC
Labels: component: numpy.random
