### ISSUE TITLE
Implement stacked version of linalg.lstsq.

### ISSUE THREAD

**Issue by cmeyer** [numpy/numpy#7580] opened 2016-04-27 23:56 UTC
Having stacked versions of all possible linear algebra functions would be nice, lstsq being one in particular.

See also http://stackoverflow.com/questions/30442377 regarding a workaround using svd.

See also #3217.

**Comment by eric-wieser** [comment] 2017-11-07 04:24
Duplicate of #8720, which has more discussion

**Closed by eric-wieser** 2017-11-07 04:24 UTC
Labels: component: numpy.linalg
