### ISSUE TITLE
numpy.histogram and numpy.digitize should be able to give same behavior

### ISSUE THREAD

**Issue by stephenholtz** [numpy/numpy#9208] opened 2017-06-02 16:39 UTC
Using some set of parameters with `numpy.digitize` should yield the same bin classification as those from `numpy.histogram`.

For instance given an array `x` I may have 10 bins (11 bin edges). If I pass any individual entry from the array to `numpy.digitize`:

```
import numpy 

counts,bin_edges = numpy.histogram(X,bins=10)
ind = numpy.digitize(x[i],bin_edges,right=True)
```

For `x[i] <= bin_edges[0]`  left edge cases and  `x[i] >= bin_edges[-1]` right edge cases I will get `ind` as `0` or `bin_edges.shape[0]`, respectively. There should be a way to have the output agree with histogram without adding new binning.

I currently add something like this to fix the bounding issue on the left edge case
```
fix = lambda x: 1 if x == 0 else x
ind = fix(ind)
```
For the right edge case use the `right=True` parameter and only pass `bin_edges[:-2]`.

**Comment by eric-wieser** [comment] 2018-02-14 18:30
I think what you're noticing here is that the final boundary of histogram is considered inclusive, whereas for `digitize` it is not. I think this was a poor design choice, but I also think we're stuck with it.

You can see the relevant implementation [here](https://github.com/numpy/numpy/blob/master/numpy/lib/histograms.py#L337-L346) - although note that this is computing the cumulative histogram

**Comment by eric-wieser** [comment] 2018-04-10 09:11
Duplicate of #4217

**Closed by eric-wieser** 2018-04-10 09:11 UTC
