### ISSUE TITLE
Regression: Change in behaviour for `np.array()` on class that defines __array__

### ISSUE THREAD

**Issue by mhvk** [numpy/numpy#13958] opened 2019-07-10 15:26 UTC
An issue has been raised for numpy 1.17rc in astropy (https://github.com/astropy/astropy/issues/8976), which after a bit of digging boils down to the change below in bahaviour for classes that define `__array__` as well as a `__len__` and `__getitem__`. I must admit I think the behaviour in both cases is strange, as it doesn't simply use `__array__` but rather seems to iterate, but the behaviour in 1.17 definitely makes (even) less sense than that in 1.16.

```
import numpy as np
class A:
    """A recarray mimic in which one indexes items by order not name"""
    def __init__(self, item):
        self.item = item
    def __array__(self, dtype=None):
        return self.item
    def __len__(self):
        return len(self.item.dtype.names)
    def __getitem__(self, item):
        return self.item[self.item.dtype.names[item]]

dtype = np.dtype([('a', 'f'), ('b', 'i')])
rec1 = A(np.array((1., 1), dtype=dtype))
rec2 = A(np.array((2., 2), dtype=dtype))
np.array([rec1, rec2], dtype=object)
# numpy 1.16
# array([[array(1., dtype=float32), array(1, dtype=int32)],
#        [array(2., dtype=float32), array(2, dtype=int32)]], dtype=object)
# numpy 1.17rc
# array([[(1.0, 1), (1.0, 1)],
#        [(2.0, 2), (2.0, 2)]], dtype=object)
```
Note that the following do not depend on version:
```
len(rec1)
# 2
rec1[0]
# array(1., dtype=float32)
np.array(rec1)
# array((1., 1), dtype=[('a', '<f4'), ('b', '<i4')])
```

**Comment by seberg** [comment] 2019-07-10 16:40
Hmm, we new switch between using the array interface (for filling the array) and using the iteration only for discovery of dimension, that must be the issue, we will have to see how much we have to revert for compatibility in this regard.

**Comment by mhvk** [comment] 2019-07-10 17:27
My expectation would have been that `__array__()` is called before anything else (if it is present), and that any checks on length are done on whatever it returns. But that expectation is broken both in the old and the new versions...

But perhaps if we break things, we might as well try to make it more logical?

**Comment by mattip** [comment] 2019-07-10 18:46
The [documentation for `__array__`](http://www.numpy.org/devdocs/reference/arrays.classes.html#numpy.class.__array__) is a bit silent on this, it only says 
> If a class (ndarray subclass or not) having the `__array__` method is used as the output object of an ufunc, results will be written to the object returned by `__array__`. Similar conversion is done on input arrays.

So the interaction with non-`ufunc` things like `concatenate` might need to be addressed in documentation

**Comment by mhvk** [comment] 2019-07-10 20:19
The documentation for `np.array` itself does mention `__array__` as well:
```
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
```
This suggests `__array__` would be tried first, before looking at whether the class is iterable. And that is also what happens for a straight `np.array(rec1)`, just not if the classes are inside a `list` - which admittedly is a trickier situation.

**Comment by mhvk** [comment] 2019-07-10 20:22
Just for reference, just passing in arrays directly is still consistent between versions:
```
np.array([rec1.__array__(), rec2.__array__()])
# array([(1., 1), (2., 2)], dtype=[('a', '<f4'), ('b', '<i4')])
np.array([rec1.__array__(), rec2.__array__()], dtype=object)
# array([array((1., 1), dtype=[('a', '<f4'), ('b', '<i4')]),
#        array((2., 2), dtype=[('a', '<f4'), ('b', '<i4')])], dtype=object)
```
But neither 1.16 nor 1.17 reproduces the second example.

**Comment by charris** [comment] 2019-07-21 18:50
@mhvk @seberg getting close to 1.17.0 final. What is the best way forward here?

**Comment by seberg** [comment] 2019-07-22 04:03
I suppose I will look at this tomorrow (unless someone beats me to it). I am not quite sure what the solution is, but I would like to go over to use `array` information always, which however means replacing/caching the array-like, so it might not be quite trivial.

Worst case, we might have to revert that speed up change for 1.17.

**Comment by seberg** [comment] 2019-07-22 22:16
OK, so basically, I think I can add correct code into `discover_dimensions` at which point, this code probably tries `__array__` three times on the same object. Could try to add a cache for those things, but that seems like it might be a larger thing to do. Will dig a bit more.

**Comment by seberg** [comment] 2019-07-22 23:08
Just to list/summarize the issue:
  * gh-13399 tried to improve performance for converting sequences of array likes.
  * gh-13663 tried to fix-up a corner case, just for compatibility reasons.
     - gh-13671 notes that this fixup is necessary to not break pandas, but somewhat incorrect
  * This issue points out that the whole logic is utterly broken if the exported Sequence-like interface has a mismatch with the array-like interface. And that it is now in a sense even more broken because we use both the array-like or sequence-like interface side by side. (This is similar to the previous note, but goes one step further).

I took a bit of a stab at prefering `__array__`, we will end up calling it a bit often (and something is still messy with respect to dtype discovery).

The other options is to just revert the order in gh-13399 in `setArrayFromSequence` (gh-13663 is not needed then). Tensorflow might actually still be faster, because I am not sure it defines the sequence interface at all, but it likely means undoing the speed advantage.

@superbobry do you happen to have an insight into this?

**Comment by seberg** [comment] 2019-07-22 23:27
So even after fixing the dimension discovery to honor `__array__`. The result is a bit funny. For the case above with object dtype, it is just the same funny as for arrays (because an array is also not unpacked for object dtype). For no given dtypes it then breaks down because `VOID_setitem` cannot handle array-likes.

**Comment by seberg** [comment] 2019-07-22 23:36
@mhvk would a result of:
```
array([<__main__.A object at 0x7f9e5c2b5a18>,
       <__main__.A object at 0x7f9e5c2b59b0>], dtype=object)
```
in your example (with object dtype; a failure without dtype) be better? Maybe coercing `__array__` yet another time is OK, at least for now.

**Comment by mhvk** [comment] 2019-07-23 01:50
@seberg - for `astropy`, it doesn't really matter, we can fix it on our end, so I think it is really more a question of what the behaviour should be.  To make an array of objects from a list of instances of `A` if the user passes in `dtype=object` certainly is reasonable!

The alternative would be to always immediately use `__array__`. I thought this was more consistent with how arrays themselves are treated, but then I noticed:
```
np.array([np.ones(3), np.ones(3)], dtype=object)
# Looks like array gets expanded
# array([[1.0, 1.0, 1.0],
#        [1.0, 1.0, 1.0]], dtype=object)
np.array([np.ones(4), np.ones(3)], dtype=object)
# Oh, but not if the shapes do not match...
# array([array([1., 1., 1., 1.]), array([1., 1., 1.])], dtype=object)
```
I guess the problem indeed boils down to not knowing whether to treat the list entries as the objects themselves, as duck arrays, or as further iterables.

Overall, your suggestion does seem the most logical: after all, without it, it would be impossible ever to make an array of `A` object instances, which seems strange. 

One question is whether it would not be better to put this off to 1.18 (i.e., revert for now), so that one can also address the whole `dtype=object` question more generally (e.g., I think my example above should logically give an object array with 2 entries in both cases).

**Comment by charris** [comment] 2019-07-23 02:49
Reversion until 1.18 seems reasonable given how tricky this seems to be.

@mhvk What do mean by "address the whole `dtype=object` question?"

**Comment by mhvk** [comment] 2019-07-23 14:45
@charris - good old #5353, the idea that one should never coerce to object unless explicitly asked to (though here of course the idea is to try to define what `dtype=object` implies)

**Comment by charris** [comment] 2019-07-23 15:29
@mhvk Just wanted to make sure :) I don't think we have that scheduled, @seberg might be a good topic for discussion tomorrow.

**Comment by superbobry** [comment] 2019-07-24 09:33
> Tensorflow might actually still be faster, because I am not sure it defines the sequence interface at all, but it likely means undoing the speed advantage.

`tf.Tensor` does define a sequence interface and that was the where most of the time was spent when converting a sequence of tensors to a NumPy array (prior to gh-13399).

**Comment by seberg** [comment] 2019-07-24 21:16
Yeah, but I am sorry. If this is the last thing that is needed for the release, and we want to do that soon. I feel like it might be best to revert it at least in the 1.17 branch. Unless someone steps up to advocate that such an object is so inherently broken and rare that we can get away with pretty much anything...

**Comment by superbobry** [comment] 2019-07-25 10:07
I'm fine with reverting. Sadly, don't have time to investigate this further at the moment.

**Comment by charris** [comment] 2019-07-25 23:33
Reverted in 1.17, still in 1.18 while we search for a better solution.

**Comment by mhvk** [comment] 2019-07-26 00:09
Thanks all for looking into this!

**Comment by seberg** [comment] 2019-10-15 23:52
**PR https://github.com/numpy/numpy/pull/14109 still need to be backported** (or a better fix found). Note that my new code that hopefull lands (or a different version of it of course). Which does not matter much here, but right now I am personally not very enthusiastic about looking into trying to find a solution because of that.

**Comment by mattip** [comment] 2019-11-12 14:36
In the [alternatives to NEP 34](https://numpy.org/neps/nep-0034.html#alternatives) it was suggested to add a new array creation function that would add a `depth` keyword to determine how deeply to recurse into objects when creating an array from a sequence of sequences. What do we want to do for 1.18?

**Comment by mattip** [comment] 2019-11-24 00:58
(with @charris) Pushing off to 1.19.0 when we should rework the `discover_dimensions` machinery

**Comment by mhvk** [comment] 2019-11-24 01:12
Will the original change that caused the problem be reverted for 1.18 as well? It still would seem to make sense to make just one change...  Thanks, all!

**Comment by mattip** [comment] 2019-11-25 18:44
Let's discuss this more. I would like to keep the performance improvements in the general case since, in my opinion, that will improve the life of  the vast majority of our users. We could warn if we detect use of both protocols that behaviour is inconsistent.

**Comment by charris** [comment] 2019-11-26 00:06
Now that this is pushed off, It sounds like we need to revert the change for 1.18.

**Comment by charris** [comment] 2019-11-26 00:09
@seberg is it your suggestion that the reversion be in master?

**Comment by seberg** [comment] 2019-11-26 00:45
I guess we should put it into master, unless anyone argues that the regression does not matter much at all. There should be ways to make the speed up happen without the regression, or at least while doing it on purpose (and consistently). It is easy enough to revert to revert as a basis for new work...

**Comment by charris** [comment] 2019-11-26 01:58
@seberg Reverted in #14983, please check that.

**Comment by mattip** [comment] 2019-11-26 04:02
The original PR showed a 30x speedup. Perhaps we should reconsider reverting that?

**Comment by rgommers** [comment] 2019-11-27 18:46
Reverting in master seems right, looks like this needs someone to sit down and work out the desired behavior in detail for all reported cases, and some tests to enforce that behavior, and then look again at the original speedup to see if it can be adapted.

**Closed** 2020-02-26 21:39 UTC
Labels: 06 - Regression, 56 - Needs Release Note., component: numpy.core
