### ISSUE TITLE
svd requires positive-size matrices

### ISSUE THREAD

**Issue by argriffing** [numpy/numpy#5419] opened 2015-01-03 17:37 UTC
If I'm using svd to help compute the norm of a matrix by looking at its singular values, then I want a size-0 matrix to have a length-0 sequence of singular values whose aggregate function (e.g. ~~max~~, sum) will be 0.  But numpy explicitly forbids empty inputs with `_assertNoEmpty2d(a)`.

**Comment by njsmith** [comment] 2015-01-03 18:34
Seems reasonable, though if full_matrices=True then one has to decide what
to do with the n x n 'u' matrix if the input is n x 0. I think just
returning np.eye(n) would satisfy all the SVD invariants?

(BTW, max([]) is an error.)

On Sat, Jan 3, 2015 at 5:37 PM, argriffing <notifications@github.com> wrote:

> If I'm using svd to help compute the norm of a matrix by looking at its
> singular values, then I want a size-0 matrix to have a length-0 sequence of
> singular values whose aggregate function (e.g. max, sum) will be 0. But
> numpy explicitly forbids empty inputs with _assertNoEmpty2d(a).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5419>.
>



-- 
Nathaniel J. Smith
Postdoctoral researcher - Informatics - University of Edinburgh
http://vorpus.org

**Comment by argriffing** [comment] 2015-01-03 18:40
> a length-0 sequence of singular values whose aggregate function (e.g. max, sum) will be 0. 

> (BTW, max([]) is an error.)

Yep, just noticed that.

**Comment by seberg** [comment] 2015-01-04 09:13
We explicitly forbid it mostly because 1. our gufunc stuff doesn't handle it (which is easy to fix, I got the PR ready mostly) and 2. at least not all lapacks can handle it. If the math is clear about the definition I think we can just special case it.

**Comment by maniteja123** [comment] 2015-01-04 09:40
Just wanted to clarify regarding ``np.max`` and ``np.min`` functions,

    >>>np.max(np.array([]))
    ValueError: zero-size array to reduction operation maximum which has no identity

Is this expected behavior ? because this is a cause for some of the exceptions mentioned in #5420 .

**Comment by seberg** [comment] 2015-01-04 09:48
Yes, it is expected. There is no reasonable definition of a maximum from an empty sequence. You could argue it is -inf, but -inf is a rather special beast in any case.

**Comment by maniteja123** [comment] 2015-01-04 10:08
@seberg , Thanks. Yeah, there isn't a proper definition, but raising an exception means the other codes which use these utility functions, like ``np.linalg.norm`` or ``np.clip`` need to take care of the edge cases, or is it okay to raise exceptions. Whereas ``np.clip`` is designed to handle these cases, as mentioned in gh-5420, ``np.linalg.norm`` fails to handle all of them.

**Comment by seberg** [comment] 2015-01-04 10:24
Sure. We are forcing our users to think about  what is correct and explicitly handle it when we cannot say it for sure, and we have to do it ourselves :). The fact is, very old numpy versions or even numeric didn't have a very clear handling of these cases I think, so in some places the special cases may still be missing or even  be incorrect/weird, though I think numpy is mostly clean by now when it comes to empty arrays.

**Comment by maniteja123** [comment] 2015-01-04 10:30
@seberg , thanks for the response :) Yeah, numpy is clean in most of the places when it comes to empty arrays. Just wanted to know if the exception in ``np.linalg.norm`` was intentional or unreported, because neither the documentation or the references mentioned about the vector or matrix norms don't talk about either *negative order* or *empty arrays/matrices*.  I understand that old numpy code might need for special cases to be taken care of.

**Comment by argriffing** [comment] 2015-01-04 16:38
Sorry for having parenthetically mentioned `max` in my first comment in this PR.  It seems to have quite shifted the topic of discussion...

**Comment by maniteja123** [comment] 2015-01-04 17:03
@argriffing Sorry, It's me who has diverted the discussion. I was just  about the behavior of different functions on zero sized arrays, which I found when going through gh-5420

**Comment by seberg** [comment] 2015-01-05 11:03
So just to note. If this interests anyone, gh-3861 was the PR I mentioned before, and I think what is mostly needed for it is to clean up all those empty array cases in linalg (since linalg is the biggest user of gufuncs).

**Comment by eric-wieser** [comment] 2017-02-24 01:40
Related: #8654

**Comment by eric-wieser** [comment] 2018-07-31 17:04
Fixed in #11424

**Closed by eric-wieser** 2018-07-31 17:04 UTC
Labels: component: numpy.linalg
