### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by dstiers11** [numpy/numpy#17947] opened 2020-12-07 12:11 UTC

**Comment by mattip** [comment] 2020-12-07 13:22
Perhaps related to https://www.github.com/ablinov/declutter/tree/master/.github%2Fworkflows%2Fbump_homebrew_formula.yml but seems to be opened here by mistake. Closing, @dstiers11 please follow the instructions especially the "steps to reproduce" to open an issue here.

**Closed by mattip** 2020-12-07 13:22 UTC
Labels: 32 - Installation
