### ISSUE TITLE
asarray inconsistent behavior when working with complex128 datatype

### ISSUE THREAD

**Issue by antonl** [numpy/numpy#3983] opened 2013-10-26 04:27 UTC
It appears that asarray and view behave differently. 

I am passing a buffer from C of `"<dd"` data type to represent a complex128 record (struct module format string). Accessing the buffer with `np.asarray(buf, 'complex128')` coerces records to real, dropping the imaginary part. Using `np.asarray(buf).view('complex128')` has the expected behavior. 

Steps to reproduce in python:

``` python
import numpy as np
x = np.random.rand(2,2) +1j*np.random.rand(2,2)
y = np.asarray(x, dtype=np.complex128)
buf = np.asarray(y).view(np.dtype('<f8, <f8'))  # this is the sort of structure I pass from C

np.asarray(buf, np.complex128) - y # shows that imaginary part has been dropped
```

**Comment by seberg** [comment] 2020-09-09 18:40
I can't reproduce this on current NumPy, always getting an error:
```
import numpy as np
x = np.random.rand(2,2) +1j*np.random.rand(2,2)
y = np.asarray(x, dtype=np.complex128)
buf = np.asarray(y).view(np.dtype('<f8, <f8'))  # this is the sort of structure I pass from C

np.asarray(buf, np.complex128) - y # shows that imaginary part has been dropped
```
With the result:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-41668aacd613> in <module>
      4 buf = np.asarray(y).view(np.dtype('<f8, <f8'))  # this is the sort of structure I pass from C
      5 
----> 6 np.asarray(buf, np.complex128) - y # shows that imaginary part has been dropped

/usr/lib/python3/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

TypeError: Cannot cast array data from dtype([('f0', '<f8'), ('f1', '<f8')]) to dtype('complex128') according to the rule 'unsafe'
```
So I assume we can close the issue.

**Closed by seberg** 2020-09-09 18:41 UTC
Labels: 00 - Bug, 54 - Needs decision, component: numpy.core
