### ISSUE TITLE
BUG: Averaging and slicing twice an n-dim array in a single line gives erroneous results

### ISSUE THREAD

**Issue by Beaconian** [numpy/numpy#27505] opened 2024-10-04 18:47 UTC
### Describe the issue:

In n-dimentional numpy arrays, when simultaneously averaging and slicing one dimention with an integer and another with another array or list, the results are not correct. 

### Reproduce the code example:

```python
import numpy as np
matrix = np.zeros((20, 30, 40, 50))
print(np.mean(matrix[], axis = -1).shape); # This collapse the last dimension, resulting in a shape of (20, 30, 40)


print(np.mean(matrix[0, :, :, [2, 3]], axis = -1).shape) 
#this should deliver a shape of (30, 40), but the result is (2, 30). Apparently it collapses the third dimension (of length 40) instead of averaging across idxs 2 and 3 from the fourth dimention.
```

### Python and NumPy Versions:

Python 3.12.7
numpy 1.26.4

### Runtime Environment:

[{'numpy_version': '1.26.4',
  'python': '3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 '
            '64 bit (AMD64)]',
  'uname': uname_result(system='Windows', node='DESKTOP-TDNFBIU', release='10', version='10.0.19045', machine='AMD64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Zen',
  'filepath': 'C:\\Users\\__user__\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\numpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll',
  'internal_api': 'openblas',
  'num_threads': 8,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

### Context for the issue:

Just working on data as ussual

**Comment by jakevdp** [comment] 2024-10-04 19:20
Hi - the issue is that you've hit a strange corner of Numpy indexing semantics: `matrix[0, :, :, [2, 3]]` pushes the indexed dimensions to the front of the array, so the expected output shape is `(2, 30, 40)` and taking the mean along the last dimension yields an array of shape `(2, 30)`.

You can read about this behavior here: https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing. In particular:

> Two cases of index combination need to be distinguished:
>
> - The advanced indices are separated by a slice, [Ellipsis](https://docs.python.org/3/library/constants.html#Ellipsis) or [newaxis](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis). For example `x[arr1, :, arr2]`.
> - The advanced indices are all next to each other. For example `x[..., arr1, arr2, :]` but not `x[arr1, :, 1]` since 1 is an advanced index in this regard.
>
> In the first case, the dimensions resulting from the advanced indexing operation come first in the result array, and the subspace dimensions after that.

The indexing in your example falls under the first case, and so the indexed dimensions are pushed to the front.

**Comment by Beaconian** [comment] 2024-10-04 21:13
Thanks for the quick response! I guess I have some reading to do on this type of indexing

**Comment by seberg** [comment] 2024-10-05 08:55
The question was answered, closing.

**Closed by seberg** 2024-10-05 08:55 UTC
Labels: 33 - Question
