### ISSUE TITLE
BUG: TypeError in np.array_equal with equal_nan=True for string Arrays 

### ISSUE THREAD

**Issue by monikasingh8097** [numpy/numpy#27618] opened 2024-10-22 17:04 UTC
### Describe the issue:

When using np.array_equal with equal_nan=True to compare string arrays containing np.nan, a TypeError is raised. This is unexpected behavior, as np.nan should be treated as a valid value for comparison in string arrays . 

### Reproduce the code example:

```python
import numpy as np
a1 = np.array(['bug', 'test',np.nan])   
a2 = np.array(['bug', 'test',np.nan])  
result = np.array_equal(a1, a2, equal_nan=True)  
print(result) # Error

import numpy as np
a1 = np.array(['bug', 'test',np.nan])   
a2 = np.array(['bug', 'test',np.nan])  
result = np.array_equal(a1, a2, equal_nan=False)  
print(result) # True
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/monik/bug/./new_error.py", line 5, in <module>
    result = np.array_equal(a1, a2, equal_nan=True)  
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monik/bug/test-env/lib/python3.11/site-packages/numpy/_core/numeric.py", line 2569, in array_equal
    a1nan, a2nan = isnan(a1), isnan(a2)
                   ^^^^^^^^^
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Python and NumPy Versions:

2.1.2
3.11.9 (main, Apr 27 2024, 21:16:11) [GCC 13.2.0]

I have checked this issue in the older version of NumPy (1.25.0) got the same error.

**Comment by yuanx749** [comment] 2024-10-23 02:41
Related to #16377. `isnan` doesn't support string or object dtype.

**Comment by zanzo2003** [comment] 2024-10-23 06:55
The issue over here that we are  facing arises because the np.array_equal function doesn't work well with np.nan when the array contains strings. When we mix np.nan (a float) with strings in a numpy array, the array's data type becomes object, which causes comparison difficulties with np.nan. We will need to write a custom array_equal() function to tackle this type of arrays. Please assign this issue to me I will come up with a custom array_equal function to handle this.

**Comment by ngoldbaum** [comment] 2024-10-23 17:58
> Please assign this issue to me I will come up with a custom array_equal function to handle this.

We don't assign issues, but also we don't add new functions to NumPy quickly like that either. Also you're not correct in your analysis of what's happening.

I'm pretty sure this isn't what the reporter wants:

```
>>> import numpy as np
>>> a1 = np.array(['bug', 'test',np.nan])
>>> a1
array(['bug', 'test', 'nan'], dtype='<U32')
```

Note how `np.nan` is coerced silently to the string `nan`.

Maybe this is what you want?

```
>>> a1 = np.array(['bug', 'test',np.nan], dtype=object)
>>> a1
array(['bug', 'test', nan], dtype=object)
>>> np.array_equal(a1, a1, equal_nan=True)
True
```

Going to close this since this is working as intended (although maybe coercing NaN is weird, I bet it would be hard to change for backward compatibility reasons).

**Closed by ngoldbaum** 2024-10-23 17:58 UTC
Labels: 00 - Bug

**Comment by ngoldbaum** [comment] 2024-10-23 17:59
Also maybe what you *really* want is the new StringDType: https://numpy.org/doc/stable/user/basics.strings.html#variable-width-strings

**Comment by zanzo2003** [comment] 2024-10-23 18:08
@ngoldbaum  Ohh. I get it, thanks for letting me know. So basically numpy defaults np.nan to a string representation of 'nan' and by specifying the dtype as 'object' we can prevent this silent coercion and use array_equal() method for the desired result.

**Comment by zanzo2003** [comment] 2024-10-23 18:11
I am new to open source and don't know much about it. If possible can you please guide me or drop a few documents where i can learn more about how to contribute to open source? @ngoldbaum
