### ISSUE TITLE
BUG: Access violation when importing numpy on Windows Server 2022/Python 3.13

### ISSUE THREAD

**Issue by jenskeiner** [numpy/numpy#27894] opened 2024-12-03 15:39 UTC
### Describe the issue:

While running a CI workflow for one of my Python projects on GitHub, I noticed that the job that was running Python 3.13 on the current `windows-latest` image was failing. All other Python versions and OS combinations I tests against ({3.10,3.11,3.12} x {ubuntu-latest, macos-latest}) are passing.

Example for a failed workflow run: https://github.com/jenskeiner/exchange_calendars_extensions/actions/runs/12139710770/job/33848270536?pr=119

The issue on the failing job seems to be that importing numpy fails with an exception in `_core/getlimits.py`. The error message "Windows fatal exception: access violation" seems to indicate that the code somehow triggers an illegal access to some ressource.

### Reproduce the code example:

```python
# To the best of my knowledge, it should be enough to just import numpy in the 
# problematic environment to trigger the issue. I am not 100% sure though as I 
# can't reproduce the issue locally due to not being able to run the exact same 
# environment.
import numpy
```

### Error message:

```shell
Using CPython 3.13.0
Creating virtual environment at: .venv
Installed 33 packages in 324ms
Windows fatal exception: access violation

Current thread 0x00001208 (most recent call first):
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\numpy\_core\getlimits.py", line 52 in __init__
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\numpy\_core\getlimits.py", line 232 in _register_known_types
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\numpy\__init__.py", line 295 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1022 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pandas\__init__.py", line 27 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1022 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\tests\test_api.py", line 7 in <module>
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\assertion\rewrite.py", line 184 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
File "C:\Users\runneradmin\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\importlib\__init__.py", line 88 in import_module
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\pathlib.py", line 587 in import_path
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\python.py", line 493 in importtestmodule
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\python.py", line 546 in _getobj
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\python.py", line 284 in obj
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\python.py", line 562 in _register_setup_module_fixture
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\python.py", line 549 in collect
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\runner.py", line 389 in collect
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\runner.py", line 341 in from_call
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\runner.py", line 391 in pytest_make_collect_report
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\runner.py", line 567 in collect_one_node
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 835 in _collect_one_node
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 970 in genitems
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 975 in genitems
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 975 in genitems
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 809 in perform_collect
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 347 in pytest_collection
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 336 in _main
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 283 in wrap_session
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\main.py", line 330 in pytest_cmdline_main
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_callers.py", line 103 in _multicall
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_manager.py", line 120 in _hookexec
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\pluggy\_hooks.py", line 513 in __call__
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\config\__init__.py", line 175 in main
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Lib\site-packages\_pytest\config\__init__.py", line 201 in console_main
  File "D:\a\exchange_calendars_extensions\exchange_calendars_extensions\.venv\Scripts\pytest.exe\__main__.py", line 8 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main
```

### Python and NumPy Versions:

Python: 3.13.0
NumPy: 2.0.2 (as per uv.lock)

### Runtime Environment:

Microsoft Windows Server 2022, 10.0.20348, Datacenter (container running on GitHub runner)

### Context for the issue:

The combination of Python 3.13 and Windows as operating system may not be the most widely used as of today, but given that the issue seems to make numpy unusable in this environment, I would recommend to prioritize this with at least a medium level of severity. It is not directly affecting my work because I don't use the affected combination of Python version and OS. However, a broad range of users may potentially affected once Python 3.13 becomes even more widely used.

**Comment by mattip** [comment] 2024-12-03 16:26
That shouldn't happen.
I cannot reproduce the workflow. I am new to uv, and it complains about something missing:
```
>cd /d d:\temp
>mkdir test_issue27894
>cd test_issue27894
>wget https://github.com/astral-sh/uv/releases/download/0.5.5/uv-x86_64-pc-windows-msvc.zip
>unzip uv-x86_64-pc-windows-msvc.zip
>uv python install 3.13
>git clone https://github.com/jenskeiner/exchange_calendars_extensions.git
>cd exchange_calendars_extensions
>..\uv run pytest
error: No `project` table found in: `d:\test_issue27894\temp\exchange_calendars_extensions\pyproject.toml`
```

I see your CI run is using a cache. Can you try to reset so it starts fresh?

**Comment by jenskeiner** [comment] 2024-12-03 16:43
Hi, thanks for comming back so quickly.

I realized that I was not using the latest NumPy version and I actually can't reproduce it with NumPy 2.1.3. So this may have been transitory and perhaps does not need to be treated with high priority. I'm investigating why I was using an older NumPy version in the first place, as NumPy is only a transitive dependency for me.

The reason it's not running in your environment is likely that you need to switch to the feature branch `feature/uv`. I just switched from poetry to uv and it required some changes to the layout of `pyproject.toml`. The issue popped up when I ran my usual CI workflow on the feature branch, so I got stuck there. Maybe try again on the feature branch? You also need to set the environment variable PACKAGE_VERSION to, say, '0' or my package won't install. (I'm already looking for a way to use a sensible default when not set.)

Btw, you can install `uv` using `pip` or `pipx` as well.

I am still wondering what happended there but I couldn't even reproduce it in a separate GH workflow which was just importing NumPy, but not running pytest in the project context; see (https://github.com/jenskeiner/exchange_calendars_extensions/actions/runs/12143368310/job/33860065556). The job fails, but with different error output. It could still be the same underlying issue as it was also idling for about 5 minutes before failing. There's also a clear warning that the environment I am using there is experimental.

From my point of view, it would be fine to close this report (at your discretion) as I can't see the issue with the latest NumPy version.

**Comment by mattip** [comment] 2024-12-03 16:47
Closing. Probably some weird caching. The two biggest problems in software are naming things, caches, and off-by-one errors.

**Closed by mattip** 2024-12-03 16:47 UTC
Labels: 00 - Bug

**Comment by jenskeiner** [comment] 2024-12-03 16:49
Thanks anyway for looking into it.
