### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jamesresearching** [numpy/numpy#5226] opened 2014-10-24 03:43 UTC
An attempt to upgrade matplotlib results in an automatic upgrade of numpy but fails. I have also tried installing numpy 1.8 and 1.7, but both failed (with different errors).

Output log is here: http://pastebin.com/pRaUXjDK

Any idea what's wrong?
(Max OSX 10.6)
Thanks!

**Comment by seberg** [comment] 2019-01-03 15:05
Closing since the issue is so old and installation related.

**Closed by seberg** 2019-01-03 15:05 UTC
