### ISSUE TITLE
np.rint(-0.0) wrong on Windows32

### ISSUE THREAD

**Issue by pitrou** [numpy/numpy#7004] opened 2016-01-13 15:29 UTC
`np.rint(-0.0)` correctly returns `-0.0` on Linux and Windows64, but not on Windows32:

```
Python 3.4.4 |Continuum Analytics, Inc.| (default, Jan 11 2016, 13:44:19) [MSC v
.1600 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy as np

In [2]: np.floor(-0.0)
Out[2]: -0.0

In [3]: np.rint(0.0)
Out[3]: 0.0
```

**Comment by matthew-brett** [comment] 2016-01-13 17:04
What version of numpy are you using?

**Comment by pitrou** [comment] 2016-01-13 17:11
Numpy 1.10.1.

**Comment by matthew-brett** [comment] 2016-01-13 17:14
Maybe related to this : https://github.com/numpy/numpy/issues/6685 - can you upgrade to 1.10.2?

**Comment by pitrou** [comment] 2016-01-13 18:53
I see. This would likely fix it, indeed. Since I'm using conda, I'll wait for the updated release on the Anaconda channels. Thank you!

**Comment by njsmith** [comment] 2016-01-13 19:03
Should this bug and that one both be closed then, or...?

**Comment by pitrou** [comment] 2016-01-13 19:11
Perhaps someone with knowledge to build Numpy on a Windows box could test? :-)

**Comment by gfyoung** [comment] 2016-01-14 03:19
I don't see this bug on my Windows32 machine.
```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more inform
>>> import numpy as np
>>> np.__version__
'1.10.2'
>>> np.rint(-0.0)
-0.0
```

**Comment by charris** [comment] 2016-04-17 17:38
Closing. Please reopen if the issue is still valid in 1.11

**Closed by charris** 2016-04-17 17:38 UTC
