### ISSUE TITLE
BUG: crash when importing numpy

### ISSUE THREAD

**Issue by jsmith173** [numpy/numpy#23864] opened 2023-06-01 16:46 UTC
### Describe the issue:

This simple program causes crash

`import numpy as np`

It works good on some computer but causes crash on some others.

### Reproduce the code example:

```python
import numpy as np
```

### Error message:

```shell
No traceback.
I debugged manually with sys.stderr.write

I have a similar problem at core/getlimits.py
https://github.com/numpy/numpy/issues/18202

MachArLike
 self.precision = int(-log10(self.eps)) <-- this line causes crash
```

### Runtime information:

Numpy version: 1.23.4
Python version: 3.9.13 compiled manually on windows 10, win32

### Context for the issue:

Please advise how to avoid it. It is permanently on one of our important computer.

**Comment by rkern** [comment] 2023-06-01 17:05
It probably has something to do with the way that you manually compiled your Python. That's probably changing the way FPE signals are handled. numpy relies on them not being set to abort.

**Comment by jsmith173** [comment] 2023-06-01 18:07
Manually means: I have used the Visual Studio project for compiling Python. I didn't changed the compiler options.
Numpy is installed/compiled via 'pip'

**Comment by rkern** [comment] 2023-06-01 19:01
Have you tested on this same computer with a `python.org` build of Python?

**Comment by seberg** [comment] 2023-06-01 19:07
The way it fails must be due to floating point errors enabled for whatever reasons, embedding the process will do the trick on certain things (do I remember delphi? It seems strange but maybe it was right).  If you also compiled Python the same way (or just running in the same bad environment) `math.inf - math.inf` probably kills the process the same way.

**Comment by rkern** [comment] 2023-06-01 19:14
Or `math.log10(2.0 ** -52)`

**Comment by rkern** [comment] 2023-06-01 19:15
Maybe also an issue with the environment or various runtime DLLs that are present on this important computer. What's special about this computer?

**Comment by jsmith173** [comment] 2023-06-02 03:38
The computer is a Windows server however the problem is solved by installing numpy 1.20.2

**Comment by seberg** [comment] 2023-06-02 05:49
Hmmm, in that case there is one other possibility, and that is that invalid instructions for speed are picked up, this sometimes happens on virtual machines for example.  That could actually be a bug, is that running in a machine a virtual machine?

If that is the problem it would be nice if you can check https://numpy.org/devdocs/user/troubleshooting-importerror.html#segfaults-or-crashes and try the `SET NPY_DISABLE_CPU_FEATURES="AVX2,FMA3"` part (with the particular ones you get).

**Comment by rgommers** [comment] 2023-09-16 09:31
No more follow-up, probably not a bug, and we've switched build systems now so SIMD build support is different. Hence closing - thanks all.

**Closed by rgommers** 2023-09-16 09:31 UTC
Labels: 57 - Close?, 33 - Question
