### ISSUE TITLE
np.loadtxt & np.genfromtxt cause a python GUI crash when using dtype input without delimiter

### ISSUE THREAD

**Issue by mp-v2** [numpy/numpy#7567] opened 2016-04-21 23:27 UTC
Both these functions cause a full crash of Spyder when I use the dtype variable to try to load strings, without manually specifying a delimiter

i.e.:
`np.genfromtxt(datafileloc)`
**^works but with NaNs for the columns that are strings**

`np.genfromtxt(datafileloc, dtype=None)`
**^fails**

`np.genfromtxt(datafileloc, delimiter=' ', dtype=None)`
**^works**

`ids = np.genfromtxt(datafileloc, delimiter=' ', dtype=None)`
**^fails**

`ids = (np.genfromtxt(datafileloc, delimiter=' ', dtype=None)).tolist()`
**^works**

This seems like a bug to me / an oversight with the output type / something that should have a more specific error message?

**Comment by mattip** [comment] 2019-05-07 05:02
does this reproduce?

**Comment by seberg** [comment] 2021-07-09 03:26
Closing, we would need a reproducer of this, and it is very very old.  By the looks of it, it seems like it was a Spyder bug at the time (since the last line succeeds).

**Closed by seberg** 2021-07-09 03:26 UTC
Labels: 57 - Close?
