### ISSUE TITLE
Speed up __pow__ for exponent -2 and -0.5

### ISSUE THREAD

**Issue by TomDLT** [numpy/numpy#9363] opened 2017-07-05 11:21 UTC
Numpy uses different functions for power [internally](
https://github.com/numpy/numpy/blob/b9e3ac9abb6e435cdf6bbe33e0bc894d6a879a53/numpy/core/src/multiarray/number.c#L464):
- When the exponent is in `{-1, 0, 0.5, 1, 2}`, it uses respectively `{reciprocal, one_like, sqrt, ~identity, square}`.
- For any other exponent, it uses a much slower routine.

Therefore, calling `a **= 2; a **= -1` is much faster than `a **= -2`.

I guess it could be possible to improve the logic in `fast_scalar_power` to also handle the cases `{-2, -0.5}`, cf. https://github.com/scikit-learn/scikit-learn/pull/9277#issuecomment-313064108

A benchmark on `a **= b; a **= -1` versus `a **= -b` gives me (v1.11.3):
![figure_1](https://user-images.githubusercontent.com/11065596/27860284-25fff35c-617c-11e7-8607-c07fb1b7aac1.png)

(Click on details to show the script)
<details>

```py
import numpy as np
from time import time
import matplotlib.pyplot as plt

n_points = int(1e6)
power_range = np.arange(0, 4.1, 0.1)
durations = np.zeros((2, power_range.size))

array = np.random.randn(n_points)
np.abs(array, array)

for i, power in enumerate(power_range):
    array_copy = array.copy()
    start = time()
    array_copy **= -power
    durations[0, i] = time() - start

    array_copy = array.copy()
    start = time()
    array_copy **= power
    array_copy **= -1
    durations[1, i] = time() - start


plt.figure(figsize=(10, 4))
ax = plt.gca()
ax.plot(power_range, durations[0], '-o', label='one operation')
ax.plot(power_range, durations[1], '-o', label='two operations')
ax.set(xlabel='power', ylabel='time', title='Elementwise power in Numpy')
ax.legend()
plt.show()
```
</details>

**Comment by mhvk** [comment] 2017-07-07 22:41
No real objection, but I'm not completely sure I like splitting what was a single call into multiple ones; it may become just a bit too much magic. If one goes for it, though, one might as well include `x**4` and x**(1/4) (which are similarly easy).

p.s. On the single function side: we seem to be missing `1/3` -> `cbrt` here.

**Comment by juliantaylor** [comment] 2017-07-08 09:07
somewhat overlaps with the long standing request of adding more compound operations to numpy, like multiply-and-add, squared/abs sum/max/min etc. Having reciprocal square and square-root ufuncs would make implementation in `fast_scalar_power` consistent
reciprocal square-root could also be implemented less precise but very fast in hardware, though that would probably need a special `fast_` name as the accuracy is not suitable for many applications (or via an accuracy context manager)

`1/3` was intentionally not mapped to `cbrt` as it is not consistent with pythons scalar `**(1./3.)` for complex numbers and it would change the results of existing code slightly depending on the platform. Though it might be something we could revisit.

**Comment by seberg** [comment] 2017-07-09 15:08
I would be personally fine with adding such ufuncs that are there for composite things, etc. But I would probably want to put them into a submodule so they don't clutter the main namespace. We could even start by putting them into their own module, but not sure there is much point, unless the list of candidates is extremely long (and it would not help here)….

**Comment by mhvk** [comment] 2017-07-09 16:29
This is getting a bit off-topic, but I've been wondering about a general interface for multiple ufuncs in series -- ideally, they'd run in series on chunks. It is particularly handy for our `Quantity` subclass, for which often one of the inputs has to be multiplied with a scale (say, adding two numbers with compatible but different units, in which one has to be scaled, or calculating the sine of a number in angular units not equal to radians). But it would obviously also help cases like those discussed here.

**Comment by seberg** [comment] 2017-07-09 16:42
Well, to some degree, you can just use `numexpr`, putting something in that direction (not exactly that) into numpy has been a long standing idea I suppose, but not sure anyone ever seriously thought of tackling it. I could imagine something like a way to create new (composited) ufuncs personally. But that is yet another orthogonal thing :)

**Comment by njsmith** [comment] 2017-07-09 16:57
Sure, but in the mean time it sounds like adding special cases for -2 and -0.5 would significantly improve some real programs (sklearn is actually taking the trouble to special case this themselves!), at pretty minimal cost in complexity.

The main reason I can see not to do this is if we're worried about accuracy – `pow` as used currently has only one rounding step, while splitting the operation into two introduces an extra intermediate that gets rounded. Does anyone have a sense of how bad this is? It might be useful to measure the discrepancy between the one step and two step resilts (and ideally also the arbitrary precision result using mpmath) across a wide range of inputs, including very large and very small ones.

**Comment by eric-wieser** [comment] 2017-07-09 19:04
Given that there's a `RSQRTSS` SSE instruction, I think there's a strong argument for a `np.invsqrt` function to handle the 0.5 case, which circumvents the two-step problem.

**Comment by njsmith** [comment] 2017-07-09 20:19
Hardware implementations typically have low precision; I think this is what Julian was referring to above.

**Comment by numpynewb** [comment] 2018-05-04 16:34
I have been struggling mightily with the fast_scalar_power implementations. They seem to act to obfuscate numpy operator APIs, so I am not so sure that adding more would be helpful, unless contained within a separate module (as was suggested above).

For example, see below for a simple interval class implementation, and the issues that the shortcuts seem to cause.

```python
import numpy as np

class interval(object):

    def __init__(self, lo=None, hi=None):
        self.lo = min([lo, hi])
        self.hi = max([lo, hi])
        
    def __repr__(self):
        return f'Interval({self.lo}, {self.hi})'

    def __pow__(self, other):
        if other == 0: 
            ans = 1
        elif other == 1: 
            ans = self
        elif (other % 2) == 0:
            if self.lo >= 0: 
                ans = interval(lo=self.lo ** other, hi=self.hi ** other)
            if (self.lo < 0) and (self.hi > 0): 
                ans = interval(lo=0, hi=max(self.lo ** other, self.hi ** other))
            if (self.hi <= 0): 
                ans = interval(lo=self.hi ** other, hi=self.lo ** other)
        else:
            ans = interval(lo=self.lo ** other, hi=self.hi ** other)

        return ans
    
    __rpow__ = __pow__ 
```


If I now try to perform basic power operations with an array of intervals, it mostly works:

```python
>>> vector_of_intervals = np.array([interval(-2, 2), interval(-4, 4), interval(-6, 6)])
>>> vector_of_intervals ** 4
array([Interval(0, 16), Interval(0, 256), Interval(0, 1296)], dtype=object)
```

However, if I try to use an operand that becons a shortcut, it will not work:

```python
>>> vector_of_intervals ** 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'interval' and 'interval'
```


The simple response might be to add `__mult__` methods for the interval class, but the problem is that while the product of interval(-2, 2) and interval(-2, 2) is interval(-4, -4), the square is not (it is interval(0, 4), since 0 is the lowest possible bound; see above `__pow__` definition). 

While this specific example is not particularly imporant, it demonstrates the unreliable, and seemingly uncontrollable, behavior of the basic numpy operators when shortcuts are used. I could be wrong, but it is not clear how this particular issue can be resolved without casting the interval class as a ndarray subclass, which is less than ideal and a big loss in API flexibility.  Again, I could be wrong and there might be a simple way around this, but I cannot see how to control or curtail the fast_scalar_power shortcuts in this exemplar case.

Apologies for being so verbose, and potentially unclear, I am new.

**Comment by mhvk** [comment] 2018-05-04 19:36
@numpynewb - Yes, it is not only good that `__pow__` dispatches to different functions; it would be preferable if those short-cuts were done much deeper down, when it was already clear one was dealing with a regular array of numbers. 

But more to your point: it certainly would seem that for `dtype=object`, we should not run the fast dispatch at all, for any exponent. Right now, it seems for `exponent=2`, no checks on the `dtype` are done, which I think is a bug. As I think it is a separate issue from this one, I made a new issue, #11047.

**Comment by eric-wieser** [comment] 2018-05-04 19:58
Note that `np.square` will not work on your class either.

Isn't the fix to implement `__mul__` as something like:

````
def __mul__(self, x):
    if self is x:
        return Interval(self.lo*self.lo, self.high*self.high)
    else:
        return Interval(...)  # whatever the full expression is
```

Which will fix both `np.power` and  `np.square`

**Comment by numpynewb** [comment] 2018-05-04 20:34
@eric-wieser I had thought about this. But, consider the following implementation.

```python
import numpy as np
import warnings

class Interval(object):

    def __init__(self, lo=None, hi=None):
        self.lo = min([lo, hi])
        self.hi = max([lo, hi])
        
    def __repr__(self):
        return f'Interval({self.lo}, {self.hi})'
    
    def __mul__(self, other):
        if other is self:
            return self ** 2

        elif isinstance(other, type(self)):
            lo = min(self.lo * other.lo, self.lo * other.hi, self.hi * other.lo, self.hi * other.hi)
            hi = max(self.lo * other.lo, self.lo * other.hi, self.hi * other.lo, self.hi * other.hi)
            return Interval(lo, hi)

        elif isinstance(other, np.ndarray):
            return other * self

        else:
            if other < 0:
                new_int = abs(other) * self
                return -Interval(new_int.lo, new_int.hi)
            else:
                return Interval((+other) * self.lo, other * self.hi)

    def __pow__(self, other, modulo=None):
        if other == 0: 
            ans = 1
        elif other == 1: 
            ans = self
        elif (other % 2) == 0:
            if self.lo >= 0: 
                ans = Interval(lo=self.lo ** other, hi=self.hi ** other)
            if (self.lo < 0) and (self.hi > 0): 
                ans = Interval(lo=0, hi=max(self.lo ** other, self.hi ** other))
            if (self.hi <= 0): 
                ans = Interval(lo=self.hi ** other, hi=self.lo ** other)
        else:
            ans = Interval(lo=self.lo ** other, hi=self.hi ** other)

        return ans

    
    __rpow__ = __pow__ 
    __rmul__ = __mul__
```

Everything seems to be going well:

```python
>>> vector_of_intervals = np.array([Interval(-2, 2), Interval(-4, 4), Interval(-6, 6)])
>>> vector_of_intervals ** 4
array([Interval(0, 16), Interval(0, 256), Interval(0, 1296)], dtype=object)
>>> 
>>> vector_of_intervals ** 2
array([Interval(0, 4), Interval(0, 16), Interval(0, 36)], dtype=object)
>>> np.power(vector_of_intervals, 2)
array([Interval(0, 4), Interval(0, 16), Interval(0, 36)], dtype=object)
>>> np.square(vector_of_intervals)
array([Interval(0, 4), Interval(0, 16), Interval(0, 36)], dtype=object)
```

The issue then becomes with letting `__mul__` know when an operation is coming from a true power call, or from a call to the regular multiplication machinery:

```python
>>> an_interval = Interval(-2, 2)
>>> an_interval * an_interval
Interval(0, 4)
```

With this implementation, it can't tell the difference. And, indeed, we can see that it returns the special power case, and not the regular multiplicative case (which should return `Interval(-4, 4)`). 

Just by way of clarification, the reason that the square of an interval straddling 0 requires special care is because the `Interval(-4, 4)` result is actually twice as wide as it should be; the lower bound of the squared `Interval(-2, 2)` is actually 0, and not less. For example, if we are just squaring both the lower and upper bounds (`self.lo` and `self.hi`), we would actually only need to return a single value; 4. But, we have to remember that 0 is included within the bounds of the original interval (`Interval(-2, 2)`), so we must consider 0 as being the lowest possible bound, because `0 ** 2` is `0`. Multiplying two intervals straddling zero should, however, rightfully contain the full width. This is because when we generate and multiply all reasonable combinations from both bounds of the operands, the min and max  will, in this case, be -4, and 4, respectively. Hope this makes sense.

**Comment by eric-wieser** [comment] 2018-05-04 20:55
> With this implementation, it can't tell the difference.

I think that's a feature - if you have a single sample from an interval and multiply it by itself, then the result is bounded by the interval you give there.

If you take two samples from the same interval, then you get the other result. You can spell that as `an_interval * copy.copy(an_interval)`

**Comment by mhvk** [comment] 2018-05-04 21:07
This seems to drift rather far off-topic! One shouldn't have to worry about `object ** 2` being reinterpreted as `object * object`, i.e., the fast route should only be taken if it is *known* that the result will be correct.

**Comment by numpynewb** [comment] 2018-05-04 21:09
Agreed, and apologies for the drift and thank you both for engaging!

**Comment by eric-wieser** [comment] 2018-05-04 22:49
Yep, I see the argument now - the object itself can always choose to optimize `__pow__` if it wants to.

**Closed** 2024-05-16 14:40 UTC
Labels: 01 - Enhancement, component: numpy._core
