### ISSUE TITLE
amax raises warning when array contains NaN

### ISSUE THREAD

**Issue by c-johan-s** [numpy/numpy#12574] opened 2018-12-17 08:38 UTC
Numpy amax method raises warning when input is an array that contains NaN. I do not recall that numpy did this in previous versions. Also, from the documentation, it says that amax shall propagate NaN, so I would expect it to return NaN without raising a warning. 

### Reproducing code example:

```python
import numpy as np
b = np.arange(5, dtype=float)
b[2] = np.NaN
np.amax(b)
```
NaN is returned, as expected, but a RuntimeWarning is issued, which I did not expect.  

### Error message:
C:\Python\WinPython\WPy-3710\python-3.7.1.amd64\lib\site-packages\numpy\core\_methods.py:26: RuntimeWarning: invalid value encountered in reduce return umr_maximum(a, axis, None, out, keepdims)

### Numpy/Python version information:
1.14.6 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]

**Comment by mattip** [comment] 2018-12-17 08:44
Duplicate of #12038. Fixed on HEAD (and in 1.16.x to-be-released). See PR #12236

**Closed by mattip** 2018-12-17 08:44 UTC
