### ISSUE TITLE
Incorrect BLAS library: how to know which is correct and link that?

### ISSUE THREAD

**Issue by czhao028** [numpy/numpy#11481] opened 2018-07-02 19:23 UTC
I ran this command earlier to try to upgrade numpy behind a corporate firewall:
`pip install --upgrade --ignore-installed --install-option '--install-data=/usr/local' numpy`

StackOverflow suggestion: [https://stackoverflow.com/questions/39187374/how-to-correctly-uninstall-numpy-on-macosx](https://stackoverflow.com/questions/39187374/how-to-correctly-uninstall-numpy-on-macosx)

Now, I run into this error when importing numpy in Jupyter Notebook:

`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/numpy/__init__.py in _sanity_check()
    214             if not abs(x.dot(x) - 2.0) < 1e-5:
--> 215                 raise AssertionError()
    216         except AssertionError:

AssertionError: 

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-1-c37133897594> in <module>()
      1 import os
      2 import glob
----> 3 import nltk
      4 from defaults import *
      5 import pickle

~/anaconda3/lib/python3.6/site-packages/nltk/__init__.py in <module>()
    112 # Import top-level functionality into top-level namespace
    113 
--> 114 from nltk.collocations import *
    115 from nltk.decorators import decorator, memoize
    116 from nltk.featstruct import *

~/anaconda3/lib/python3.6/site-packages/nltk/collocations.py in <module>()
     37 from nltk.probability import FreqDist
     38 from nltk.util import ngrams
---> 39 from nltk.metrics import ContingencyMeasures, BigramAssocMeasures, TrigramAssocMeasures
     40 from nltk.metrics.spearman import ranks_from_scores, spearman_correlation
     41 

~/anaconda3/lib/python3.6/site-packages/nltk/metrics/__init__.py in <module>()
     14 """
     15 
---> 16 from nltk.metrics.scores import          (accuracy, precision, recall, f_measure,
     17                                           log_likelihood, approxrand)
     18 from nltk.metrics.confusionmatrix import ConfusionMatrix

~/anaconda3/lib/python3.6/site-packages/nltk/metrics/scores.py in <module>()
     16 
     17 try:
---> 18     from scipy.stats.stats import betai
     19 except ImportError:
     20     betai = None

~/anaconda3/lib/python3.6/site-packages/scipy/__init__.py in <module>()
     60 __all__ = ['test']
     61 
---> 62 from numpy import show_config as show_numpy_config
     63 if show_numpy_config is None:
     64     raise ImportError(

~/anaconda3/lib/python3.6/site-packages/numpy/__init__.py in <module>()
    220             raise RuntimeError(msg.format(__file__))
    221 
--> 222     _sanity_check()
    223     del _sanity_check

~/anaconda3/lib/python3.6/site-packages/numpy/__init__.py in _sanity_check()
    218                    "pass simple sanity checks. This can be caused for example "
    219                    "by incorrect BLAS library being linked in.")
--> 220             raise RuntimeError(msg.format(__file__))
    221 
    222     _sanity_check()

RuntimeError: The current Numpy installation ('/Users/noy932/anaconda3/lib/python3.6/site-packages/numpy/__init__.py') fails to pass simple sanity checks. This can be caused for example by incorrect BLAS library being linked in.

How do I find the right BLAS library and link it in?
`

**Comment by seberg** [comment] 2018-07-02 21:46
IIRC a lot of this had to do with anaconda and gui tools causing a system Accelerate or so to be loaded. Not sure if that was right, but you may want to try to use `import numpy` before any other import (or well that nltk one, which probably pulls in a lot of things) as a workaround.
Numpy is a bit brutal with the error, but the alternative is silently nonsense result in linear algebra....

**Comment by seberg** [comment] 2018-07-02 21:51
Ah, sorry, nvm. Jupyter notebooks were enough to trigger it, a plain python session may work. I don't really know, I expect there are open anaconda issues that might help (for numpy for example https://github.com/numpy/numpy/issues/9758 and those linked there might be the same issue).

**Comment by seberg** [comment] 2018-07-02 21:52
aha: https://github.com/ContinuumIO/anaconda-issues/issues/8070

**Comment by charris** [comment] 2018-07-02 22:00
Mind, the problem isn't new, it is that numpy is now checking for it.

**Comment by charris** [comment] 2018-07-02 22:13
Sounds like you are using a mix of Pip and NumPy. If I am reading #9758 correctly, you should upgrade numpy in Anaconda.

**Comment by charris** [comment] 2018-07-02 22:17
See also https://github.com/ContinuumIO/anaconda-issues/issues/9460.

**Comment by charris** [comment] 2018-07-02 22:23
Let's leave this open so that it is more easily found.

**Comment by czhao028** [comment] 2018-07-03 16:11
thanks for your comments guys! it finally worked, what a relief. For future viewers, I did "conda install numpy=1.14", restarted jupyter notebook, reconnected the kernel, ran import numpy by itself, and it worked!

**Comment by charris** [comment] 2018-07-03 16:37
Another suggestion is `conda update --all`.

**Comment by czhao028** [comment] 2018-07-03 20:51
so turns out I still have issues in PyCharm; would any of you know what could be the issue here? I upgraded numpy to 1.14.5 but pycharm refuses to acknowledge it's there. it's causing me a bunch of problems with gensim (as you can see below, all the weights are nan, which isn't an issue in jupyter)

<img width="306" alt="screen shot 2018-07-03 at 4 49 01 pm" src="https://user-images.githubusercontent.com/21087118/42244020-46daa440-7ee1-11e8-9603-d9cae489f689.png">
<img width="337" alt="screen shot 2018-07-03 at 4 49 09 pm" src="https://user-images.githubusercontent.com/21087118/42244021-46e8d6be-7ee1-11e8-8f97-64391f27cc23.png">
<img width="472" alt="screen shot 2018-07-03 at 4 49 15 pm" src="https://user-images.githubusercontent.com/21087118/42244022-47063e52-7ee1-11e8-95bb-432da07e99de.png">
<img width="525" alt="screen shot 2018-07-03 at 4 49 23 pm" src="https://user-images.githubusercontent.com/21087118/42244023-4715abe4-7ee1-11e8-8ba3-71fb4d1804e1.png">
<img width="256" alt="screen shot 2018-07-03 at 4 50 32 pm" src="https://user-images.githubusercontent.com/21087118/42244024-4721336a-7ee1-11e8-9627-02037ca7fc72.png">

**Comment by VasylHafych** [comment] 2018-10-05 12:32
Hi everyone, 

I am experiencing the same issue as @czhao028 . Namely, while running `import numpy as np` from **Jupyter Notebook** I am getting the following error: 
```jypyter
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py in _sanity_check()
    219             if not abs(x.dot(x) - 2.0) < 1e-5:
--> 220                 raise AssertionError()
    221         except AssertionError:

AssertionError: 

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-3-0aa0b027fcb6> in <module>()
----> 1 import numpy as np

~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py in <module>()
    225             raise RuntimeError(msg.format(__file__))
    226 
--> 227     _sanity_check()
    228     del _sanity_check

~/anaconda3/lib/python3.7/site-packages/numpy/__init__.py in _sanity_check()
    223                    "pass simple sanity checks. This can be caused for example "
    224                    "by incorrect BLAS library being linked in.")
--> 225             raise RuntimeError(msg.format(__file__))
    226 
    227     _sanity_check()

RuntimeError: The current Numpy installation ('/Users/hafych/anaconda3/lib/python3.7/site-packages/numpy/__init__.py') 
fails to pass simple sanity checks. 
This can be caused for example by incorrect BLAS library being linked in.
```
However, there is no error when I am typing this in Python from the terminal. Here are some details: 

```python
>>> import numpy
>>> numpy.__path__
['/Users/hafych/anaconda3/lib/python3.7/site-packages/numpy']
>>> numpy.version.version
'1.15.1'
>>> numpy.show_config()
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hafych/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hafych/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hafych/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hafych/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hafych/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hafych/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hafych/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hafych/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/hafych/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/hafych/anaconda3/include']
>>> 

```

@charris @seberg, is there a way to fix this issue with **Jupyter Notebook**? I have started working on a project, so the need to find a workaround is almost urgent. I will greatly appreciate your advice.

PS: I am using MacBook Pro (13-inch, 2016) with MacOS High Sierra (V 10.13.6) and Anaconda (version 1.7.2). 
 
Cheers, 
Vasyl

**Comment by charris** [comment] 2018-10-05 14:02
Check if you have multiple numpy installations. See #8577 and #9745 for more about the error. Maybe Jupyter also needs an update.

**Comment by VasylHafych** [comment] 2018-10-05 15:57
> Check if you have multiple numpy installations. See #8577 and #9745 for more about the error. Maybe Jupyter also needs an update.

Thank you for the reply. 

I have cleaned up Python environment completely, as it has been explained [here](https://stackoverflow.com/a/52123490). Then I installed Anaconda  (version 1.7.2), so no other version of python are present on my Mac. 

Now, when I try `python -c "import numpy ; f=numpy.ones(2,dtype=numpy.float32);print (f.dot(f))"` I am getting **2.0**. 

 However, when I try `python -c "import PyQt5.QtWidgets ; import numpy ; f=numpy.ones(2,dtype=numpy.float32);print (f.dot(f))"` I am getting a similar error like that with a Jupyter notebook



```terminal
Traceback (most recent call last):
  File "/Users/hafych/anaconda3/lib/python3.7/site-packages/numpy/__init__.py", line 220, in _sanity_check
    raise AssertionError()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hafych/anaconda3/lib/python3.7/site-packages/numpy/__init__.py", line 227, in <module>
    _sanity_check()
  File "/Users/hafych/anaconda3/lib/python3.7/site-packages/numpy/__init__.py", line 225, in _sanity_check
    raise RuntimeError(msg.format(__file__))
RuntimeError: The current Numpy installation ('/Users/hafych/anaconda3/lib/python3.7/site-packages/numpy/__init__.py') 
fails to pass simple sanity checks. 
This can be caused for example by incorrect BLAS library being linked in.

```
Note, that the last mistake (the same as that I was getting in a **Jupyter notebook**) I received in **Terminal**. What can cause this problem? 

Also, could you please explain how to check if multiple Numpy versions are present?

**Comment by charris** [comment] 2018-10-05 17:27
IIRC, the pyqt5 problem was a problem with the Intel compiler that should have been fixed, it isn't the same as the sanity check error. You may be able to fix it by reversing the order of import.

**Comment by chang48** [comment] 2018-10-11 21:52
I'm having a similar issue. The error can be triggered by simply import numpy in jupyter notebook. Importing numpy works in command line mode though. My environment is a conda environment where I have 

- python 3.7.0
- numpy 1.15.2
- jupyter 1.0.0
- mkl 2019.0
- pyqt 5.9.2

It would be really appreciated if this problem can be resolved.

<img width="1156" alt="screen shot 2018-10-11 at 2 45 31 pm" src="https://user-images.githubusercontent.com/2575869/46835946-7e0cec80-cd64-11e8-9821-2e67b6fbeea5.png">

**Comment by charris** [comment] 2018-10-11 22:20
Both of these are  Intel compiler problems on anaconda, you should inquire or report to them. In any case, keep your anaconda current. See #11168 for a bit more information. This is not a NumPy problem, NumPy is just telling you that there is an installation/library problem.

**Comment by chang48** [comment] 2018-10-11 22:46
> Both of these are Intel compiler problems on anaconda, you should inquire or report to them. In any case, keep your anaconda current. See #11168 for a bit more information. This is not a NumPy problem, NumPy is just telling you that there is an installation/library problem.

I'm using miniconda though. But I'll take a look at their github and report/reference the issue. Many thanks @charris !

**Comment by charris** [comment] 2018-10-12 00:20
@chang48 Thanks for the update, that should be helpful to others who experience the problem.

**Comment by adam-erickson** [comment] 2018-12-20 00:36
I ran into this issue while installing pytorch from source with Anaconda3 version 5.3.1. It appears that `numpy` is linked to `intel_openblas` by default. Running the following command fixes the error by linking an updated `numpy` to standard `openblas`:

`condo update numpy`

**Comment by adam-erickson** [comment] 2018-12-29 04:46
That fix apparently is not working now. This fix does the same thing until MKL is updated:

```bash
conda uninstall --force blas
conda install "blas=*=openblas"
conda update --force numpy
```

Now, `numpy` should be linked against the `openblas` variant of the `blas` package, which works fine. Previously, `conda update numpy` performed this with one command.

**Comment by Meteodan** [comment] 2019-01-16 23:42
> Update: that fix apparently is not working now. This fix does the same thing until MKL is updated:
> 
> ```shell
> conda uninstall --force blas
> conda install "blas=*=openblas"
> conda update --force numpy
> ```
> 
> Now, `numpy` should be linked against the `openblas` variant of the `blas` package, rather than `mkl`, as the former works. Previously, `conda update numpy` performed this with one command. I prefer OpenBLAS anyway, as it is open-source and truly cross-platform.

First, I too, have run into this issue in the OP, when importing in a Jupyter notebook.
When I do the above procedure to force the use of openblas, I instead get the error reported in this issue: #12739 

It seems that the above commands are leaving behind some files from the older installation of numpy in my case (mine went from 1.15.4 to 1.16.0 with the openblas linked. To solve this, I had to:

`conda install numpy=1.15.4=py36_blas_openblash4251c03_1000`

To revert back to 1.15.4 but linked to openblas. Then numpy imported with no errors into the jupyter notebook. However, I haven't tested all my code using this environment to see if there are any other problems (i.e. with other packages that depend on the old blas; not sure if this is an issue or not)

**Comment by mattip** [comment] 2019-08-18 19:57
This issue has become a jumble of different installation issues. Closing, in the hopes that people will open a new issue for each installation problem.

**Closed by mattip** 2019-08-18 19:57 UTC
