### ISSUE TITLE
BUG: npyio: np.savez is limited by /tmp size

### ISSUE THREAD

**Issue by perimosocordiae** [numpy/numpy#5601] opened 2015-02-24 16:10 UTC
When creating the npz file, each array is written to a temporary file before adding to a zip archive: https://github.com/numpy/numpy/blob/master/numpy/lib/npyio.py#L601

This means that if /tmp is close to full, npz file creation will fail even when the actual target device has plenty of space. Even worse, it fails with a cryptic IOError message that doesn't point to /tmp.

**Comment by juliantaylor** [comment] 2015-02-24 17:19
you can work around this by setting the TMPDIR environment variable.
It boils down to we don't know where to put the temp file, I think the destination dir is most likely to have the space and would be a better choice.
But really what we need is just a non-stupid interface for zipfiles where we can stream data in instead of doing the copy ... but python only provides that for gzip and not zip.

**Comment by perimosocordiae** [comment] 2015-02-24 22:07
Would it be possible to write the data to a string, then use [ZipFile.writestr](https://docs.python.org/2/library/zipfile.html#zipfile.ZipFile.writestr) to avoid a temp file? It'll mean another copy of the data in memory, though, which may not be desirable in all cases.

**Comment by juliantaylor** [comment] 2015-02-24 22:14
yes there is also some code in some fork doing that, but that means you may need a lot of ram, as far as I recall you can't use writestring multiple times in small chunks
another approach that works is making a named pipe/fifo and dumping the data into there to coax the zipmodule into thinking its receiving one file, but that doesn't work on windows.

**Comment by njsmith** [comment] 2015-02-25 01:00
Honestly the most practical approach might be to just add streaming support
to zipfile. (We'd have to carry a fork or only support streaming on newer
python versions, but it's not like zipfile is a fast-changing module.) If
you look at the source code for ZipFile.writestr, it's not terribly
complicated -- the only tricky bit is that you have to set flag bit 0x08 in
the file header and follow the rules described here:
   https://en.wikipedia.org/wiki/Zip_%28file_format%29#File_headers
(And notice that writestr already has code to do this.)

On Tue, Feb 24, 2015 at 2:14 PM, Julian Taylor <notifications@github.com>
wrote:

> yes there is also some code in some fork doing that, but that means you
> may need a lot of ram, as far as I recall you can't use writestring
> multiple times in small chunks
> another approach that works is making a named pipe/fifo and dumping the
> data into there to coax the zipmodule into thinking its receiving one file,
> but that doesn't work on windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/5601#issuecomment-75858496>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by perimosocordiae** [comment] 2015-03-03 17:44
Looks like this is essentially what we'd need: http://stackoverflow.com/a/10407062/10601

**Comment by serhiy-storchaka** [comment] 2017-10-15 17:04
This looks like a duplicate of #3464.

**Comment by serhiy-storchaka** [comment] 2017-10-15 17:05
#9863 solves this issue in Python 3.6+ by getting rid of temporary files.

**Comment by charris** [comment] 2017-10-15 21:51
After the release of NumPy 1.14.0, temporary files can be avoided by upgrading to Python 3.6, which allows writing streams directly to the zipfile. So closing this.

**Closed by charris** 2017-10-15 21:51 UTC
