### ISSUE TITLE
BUG: np.matmul segfaults on PyPy, perhaps related to BLAS SKX

### ISSUE THREAD

**Issue by Qiyu8** [numpy/numpy#16737] opened 2020-07-03 02:25 UTC
I'm trying to solve the CI failure of #16482 , It's seems like a strange stuck occurred which causes the failure of TestCholesky.test_basic_property.

### Reproducing code example:

```python
import numpy as np
shape = (50, 50)
a = np.random.randn(*shape)
a = np.matmul(a.T, a) #stucked
```
The stuck disappeared when shape is under(40, 40) or change a.T to a.
### Error message:

no response, Into an infinite loop

### Numpy/Python version information:

1.20.0.dev0+3cf4c28 3.7.0 (default, Mar 16 2020, 00:02:15)
[GCC 7.3.0]

**Comment by Qiyu8** [comment] 2020-07-03 02:47
Another openBlas issue.  everything turns to normal when remove openblas.

**Comment by mattip** [comment] 2020-07-03 06:48
Could you link to the CI failure?

**Comment by Qiyu8** [comment] 2020-07-03 07:05
The CI failure link is [here](https://dev.azure.com/numpy/numpy/_build/results?buildId=11110&view=logs&j=cb7817a0-aed9-5b1b-ffdb-285e933f569f&t=713c0b5c-565d-5b6b-cd58-66e4f64bd786&l=4381)

**Comment by seiko2plus** [comment] 2020-07-03 07:12
@Qiyu8, I confirm it BLAS SKX issue, but this not realated to ARM64

**Comment by mattip** [comment] 2020-07-03 08:49
I don't see what the actual AVX512 SKX variant is on the [AVX512 wikipedia page](https://en.wikipedia.org/wiki/AVX-512). Could you point me to some documentation? I see the test is 
```
int main(void)
{
    /* VL */
    __m256i a = _mm256_abs_epi64(_mm256_setzero_si256());
    /* DQ */
    __m512i b = _mm512_broadcast_i32x8(a);
    /* BW */
    b = _mm512_abs_epi16(b);
    return _mm_cvtsi128_si32(_mm512_castsi512_si128(b));
}
```

**Comment by mattip** [comment] 2020-07-03 09:03
Is it correct that the [travis linux runs](https://travis-ci.org/github/numpy/numpy/jobs/703751244#L5921) do not enable AVX512_SKX, nor do the [windows azure runs](https://dev.azure.com/numpy/numpy/_build/results?buildId=11110&view=logs&j=41da7a62-01d8-5a8a-1897-893bcc993eb5&t=fc328d23-6727-5f4b-4465-69bf6193461e&l=2246). So it seems only the PyPy runs have that option. Perhaps this is a problem with general support for that flag in OpenBLAS?

**Comment by seiko2plus** [comment] 2020-07-03 09:14
@mattip, By AVX512 SKX, we usually refer to the new AVX512 features that started to appear in skylake servers(Xeon) they were formerly called AVX3.2 (AVX512F + AVX512CD + AVX512BW + AVX512DQ + AVX512VL).
These features also supported by the successor chips such as CLX(Cascade Lake), CNL(Cannon Lake) and ICL(Ice Lake).
NOTE: Xeon Phi KNL(Knights Landing) and KNM(Knights Mill) don't support AVX512 features (AVX512BW + AVX512DQ + AVX512VL).

> Could you point me to some documentation?

https://en.wikichip.org/wiki/intel/microarchitectures/
https://gcc.gnu.org/wiki/cauldron2014?action=AttachFile&do=get&target=Cauldron14_AVX-512_Vector_ISA_Kirill_Yukhin_20140711.pdf
https://software.intel.com/content/www/us/en/develop/articles/additional-intel-avx-512-instructions.html

**Comment by seiko2plus** [comment] 2020-07-03 09:21
@mattip,
> Is it correct that the travis linux runs do not enable AVX512_SKX?

No, Travis and Azure sometimes provide servers with SKX support and sometimes not.
That's why azure sometimes success and other times fail. And according to the CI [log](https://travis-ci.org/github/numpy/numpy/jobs/703751244#L5921) that you have mentioned, I can see the support of SKX features through the testing log
```C
NumPy version 1.20.0.dev0+4fd295c
NumPy relaxed strides checking option: True
NumPy CPU features: SSE SSE2 SSE3 SSSE3* SSE41* POPCNT* SSE42* AVX* F16C* FMA3* AVX2* AVX512F* AVX512CD* AVX512_KNL? AVX512_KNM? AVX512_SKX* AVX512_CNL?
````

**Comment by seiko2plus** [comment] 2020-07-03 09:25
>Perhaps this is a problem with general support for that flag in OpenBLAS?

I'm not sure yet why OpenBLAS is crashing but maybe the issue caused by some kind buggy SIMD kernel activated when SKX features been available.

**Comment by Qiyu8** [comment] 2020-07-03 09:44
you are right, only the matrix scale larger than (40,40), OpenBLAS start crashing. That's so much like SIMD.

**Comment by mattip** [comment] 2020-07-03 10:25
> I can see the support of SKX features through the testing log

whoops, I didn't look carefully enough. So any idea what is going on? Maybe the JIT is setting flags that disable SKX?

**Comment by isuruf** [comment] 2020-07-04 20:14
Is this not reproducible under other python configurations? I see that in the azure pipelines you linked, there are only 3 linux builds. First one uses i686 openblas which doesn't use SKX kernels. Last one uses gcc48 which doesn't support SKX kernels either. So, I think that this is PyPy is not significant

**Comment by martin-frbg** [comment] 2020-07-08 12:45
Seeing that neither me nor the author of most SKX kernels in OpenBLAS could reproduce the purported failures on local AVX512-capable hardware, could you provide backtraces or similar debug output that would at least make it clearer if this is really "some kind buggy SIMD kernel" or just a borked VM in Azure?

**Comment by Qiyu8** [comment] 2020-07-09 02:13
@mattip @isuruf  I don't think It's `AVX512 SKX `or `PyPy` related bug, I have a reproduce routine with `Lastest NumPy+ARMV8+Openblas 0.3.9`,  none of this is related with `AVX512 SKX `or `PyPy`, and unfortunately, this bug don't produce any backtraces or output. I have tried with Openblas 0.3.10, this bug disappeared. should I close this issue?

**Comment by mattip** [comment] 2020-07-09 05:40
When I open the failed Azure [build log](https://dev.azure.com/numpy/numpy/_build/results?buildId=11110&view=logs&j=cb7817a0-aed9-5b1b-ffdb-285e933f569f&t=713c0b5c-565d-5b6b-cd58-66e4f64bd786&l=4381) on latest NumPy head (from a few days ago) on linux X86_64 with OpenBLAS 0.3.10 , I get a pop-up message that the task has failed 4 times in the last 179 runs, so maybe @martin-frbg is correct and this is some quirky VM problem on Azure. Let's leave this open for a while in case the issue returns, in the mean time I will close the related OpenBLAS issue.

Thanks to all who dug into this to try to reproduce.

**Comment by royjacobson** [comment] 2020-07-10 16:00
Just happened to me here:

https://dev.azure.com/numpy/numpy/_build/results?buildId=11274&view=logs&j=cb7817a0-aed9-5b1b-ffdb-285e933f569f&t=713c0b5c-565d-5b6b-cd58-66e4f64bd786&l=4390

**Comment by mattip** [comment] 2020-08-09 06:41
Is this happening any more after updating OpenBLAS?

**Comment by mattip** [comment] 2020-08-17 05:05
I think we can close this? Updating OpenBLAS seems to have fixed it. Please reopen if I am mistaken.

**Closed by mattip** 2020-08-17 05:05 UTC
Labels: 05 - Testing, 24 - PyPy, component: numpy.linalg
