### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by FpEye** [numpy/numpy#15590] opened 2020-02-17 20:09 UTC
I have installed Python by execuble archive on Python.org
I do use Windows 10 64 bits
Numpy already comes with Anaconda3, I uninstalled and installed numpy with conda install/uninstall numpy (I do use 1.18.1 version)
I have just one python version (3.7.4)
I was tryna import tensorflow
I can neither import numpy nor tensorflow
Error Message:
PS C:\Users\filip\Desktop\Filipe\Python\Scripts> & C:/Users/filip/AppData/Local/Continuum/anaconda3/python.exe c:/Users/filip/Desktop/Filipe/Python/Scripts/Teste.py
C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/filip/Desktop/Filipe/Python/Scripts/Teste.py", line 1, in <module>
    import numpy as np
  File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\filip\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\filip\AppData\Local\Continuum\anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Não foi possível encontrar o módulo especificado.

**Comment by mattip** [comment] 2020-02-17 20:23
Have you activated your conda environment? 
```
conda activate base
```
What do you get if you try to run the python CLI (python with no script)
```
PS C:\Users\filip\Desktop\Filipe\Python\Scripts> & C:/Users/filip/AppData/Local/Continuum/anaconda3/python.exe
```
If it gives warnings, you should make sure you solve those first.

**Comment by fpedu** [comment] 2020-02-18 16:33
I did but i received this message 
PS C:\Users\filip\Desktop\Filipe\Python\Scripts> conda activate base
conda : O termo 'conda' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a grafia 
do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

And everytime i try to run the python CLI this appear:
C:\Users\filip>python
'python' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by rgommers** [comment] 2020-05-01 16:25
Closing, old install issue, not a bug and not much we can do here.

**Closed by rgommers** 2020-05-01 16:25 UTC
