### ISSUE TITLE
BUG: NumPy types don't return NotImplemented for operator overloading of operands they can't handle

### ISSUE THREAD

**Issue by Mou141** [numpy/numpy#27348] opened 2024-09-05 11:12 UTC
### Describe the issue:

I have been using hist version 2.7.2 with NumPy [https://pypi.org/project/hist/](https://pypi.org/project/hist/). Hist's histogram objects overload the multiply operator to allow histograms to be scaled by scalar values. The `__mul__` method on hist.Hist can handle both python numeric types and NumPy's numeric types.

Python evaluates operator overloading from left to right. The `__mul__` method on the left operand is evaluated first. If that method returns `NotImplemented`, the `__mul__` method on the right operand is evaluated. Internally, `hist.Hist` stores its bin counts and variances as a structured NumPy array.

When a python numeric type is multiplied by a `hist.Hist` object (e.g. `4.0 * h`), the `__mul__` method on the python object returns `NotImplemented` and `__mul__` is called on the `hist.Hist` object.

When a NumPy numeric type is multiplied by a `hist.Hist` object (e.g. `np.float64(12.0) * h`), the `__mul__` method on the NumPy type passes the object to `np.multiply` which cannot multiply the `hist.Hist` object. `numpy.core._exceptions._UFuncNoLoopError` is raised.

Because `NotImplemented` is not returned, python doesn't delegate to the `__mul__` method of the `hist.Hist` object.

### Reproduce the code example:

```python
import numpy as np
import hist

h = hist.Hist.new.Regular(5, 0.0, 1.0, flow=True).Weight()
h.fill(np.random.random(100))

np.float64(12.0) * h
```

### Error message:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('float64'), dtype([('value', '<f8'), ('variance', '<f8')])) -> None
```

### Python and NumPy Versions:

1.26.4
3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]

### Runtime Environment:

[{'numpy_version': '1.26.4',
  'python': '3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]',
  'uname': uname_result(system='Linux', node='IT099142', release='6.8.0-40-generic', version='#40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2', machine='x86_64')},
 {'simd_extensions': {'baseline': ['SSE', 'SSE2', 'SSE3'],
                      'found': ['SSSE3',
                                'SSE41',
                                'POPCNT',
                                'SSE42',
                                'AVX',
                                'F16C',
                                'FMA3',
                                'AVX2'],
                      'not_found': ['AVX512F',
                                    'AVX512CD',
                                    'AVX512_KNL',
                                    'AVX512_KNM',
                                    'AVX512_SKX',
                                    'AVX512_CLX',
                                    'AVX512_CNL',
                                    'AVX512_ICL']}},
 {'architecture': 'Prescott',
  'filepath': '/home/ae23898/Documents/MSc_R_Code/python_env/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-0cf96a72.3.23.dev.so',
  'internal_api': 'openblas',
  'num_threads': 20,
  'prefix': 'libopenblas',
  'threading_layer': 'pthreads',
  'user_api': 'blas',
  'version': '0.3.23.dev'}]

### Context for the issue:

Code which uses NumPy often mixes python `float` and NumPy floating point types. It is often not known at runtime which will be used. Having `4.0 * obj` evaluating differently from `np.float64(4.0) * obj` (where `obj` is an arbitrary object implementing `__mul__`) leads to intermittent errors that are very difficult to debug.

**Comment by mhvk** [comment] 2024-09-05 19:53
It is indeed somewhat tricky to get this right. However, normally things do work. E.g.,
```
class A:
    def __mul__(self, obj):
        return f"multiplying {self} with {obj}"
    def __rmul__(self, obj):
        return f"reverse multiplying {self} with {obj}"

a = A()
np.float64(1.)*a
# 'reverse multiplying <__main__.A object at 0x7fb44ec9e010> with 1.0'
```

From your traceback, it looks like the problem is not actually the multiplication with `hist` itself, but rather with some structured array with `value` and `variance` entries. Does `hist` perhaps define an `__array__` method? If that is present, numpy generally decides that it knows how to handle an object: it calls `__array__()` before doing the multiplication.
To avoid that, one can also define `__array_ufunc__ = None` -- this tells numpy that ufuncs just do not work on that class.

**Comment by seberg** [comment] 2024-09-10 17:11
IIRC there is a duplicate and this is unfortunately a regression.  The problem is that the PR trying to avoid recursion, means that `scalar <op> array_like` is now not prioritizing `__array__()`, IIRC.
To some degree, I am not sure whether or not that is all wrong, but I guess we have no choice but try to preserve it.

**Comment by seberg** [comment] 2024-10-01 10:12
Sorry, I was traveling, and thought this had anything to do with recent changes in how scalars are handled.  That is not the case, the described behavior is exactly as advertised and correct.

NumPy is (unfortunately maybe) very aggressive about converting other objects to arrays.  Arguably, scalars should do that even less... but they pretend to be arrays and until that is clearer from a user-perspective we can't even (slowly start) to change that.

In any case, the design is the following, NumPy **will** convert, unless you:
* Define `__array_priority__` to be greater `-10000` (I think, the scalar priority)
* Define `__array_ufunc__`, which can be `None` (`None` will disable any ufunc/math operations on the object though).

Closing, as this is all by design as Marten had correctly allured to.  Although, I think that defining `__array_priority__` may be the simpler solution (to some degree `__array_ufunc__` may be the cleaner solution, but not sure it is as practical).

**Closed by seberg** 2024-10-01 10:12 UTC
Labels: 00 - Bug, 06 - Regression

**Comment by seberg** [comment] 2024-10-01 10:14
@Mou141 please don't hesitate to ask if you need more pointers.  The correct (enough) behavior in these things is pretty tricky to get right!
