### ISSUE TITLE
Absolute silently returning negative values (architecture dependent)

### ISSUE THREAD

**Issue by mapio** [numpy/numpy#9463] opened 2017-07-26 15:04 UTC
Taking the absolute value of the smallest negative machine size integer returns a negative value.

On ARM (Raspian OS) machines (e.g. Raspberry Pi 3). If you run

    numpy.absolute(np.array([-2**31]))

you get

    array([-2147483648])

On Intel (Apple OS X), on the other hand,

    numpy.absolute(np.array([-2**63]))

you get

    array([-9223372036854775808])

The `dtype` for the array is `int32` on ARM and `int64` on Intel.

**Comment by eric-wieser** [comment] 2017-07-26 15:08
This is probably because on ARM, `np.array([1]).dtype == np.int32`, but on OSX, `np.array([1]).dtype == np.int64`.

I don't know if this is deliberate?

On both platforms, I would expect this behaviour
```python
>>> numpy.absolute(np.array([-2147483648], dtype=np.int32))
array([-2147483648])
```

because `2147483648` cannot be stored in an np.int32

**Comment by pv** [comment] 2017-07-26 15:10
Duplicate of gh-5657

**Comment by mapio** [comment] 2017-07-26 15:10
Yes, the reason is exactly the one you highlight. The point is that I was not expecting `numpy.absolute` to return negative values (it is not at all documented, for example).

Of course, if the `dtype` must be preserved, it'll be impossible to represent the value, but an exception should be probably risen (or the behaviour should be documented).

**Closed** 2017-07-26 15:11 UTC

**Comment by eric-wieser** [comment] 2017-07-26 15:16
(feel free to keep discussing at the duplicate)
