### ISSUE TITLE
diag still read-only

### ISSUE THREAD

**Issue by akhmerov** [numpy/numpy#7661] opened 2016-05-22 22:47 UTC
It seems that the [promised](https://github.com/numpy/numpy/blob/master/doc/release/1.9.0-notes.rst#the-diagonal-and-diag-functions-return-readonly-views) change of `diag`/`diagonal` to return a writeable view was forgotten in 1.10 and 1.11.

Is the fix as easy as changing the flag on creation?

**Comment by shoyer** [comment] 2016-05-23 00:03
We put off making this change in 1.10 after getting some significant pushback. See this [blog post](https://khinsen.wordpress.com/2014/09/12/the-state-of-numpy/) and the subsequent mailing list discussion (which could be turned up with some searching) for more details.

**Comment by akhmerov** [comment] 2016-05-23 00:22
Do you mean [this](http://numpy-discussion.10968.n7.nabble.com/The-future-of-ndarray-diagonal-td39426.html) discussion?

It seems to conclude with something like:

> I would love to do the PR once a decision is reached.

Perhaps now, almost 1.5 years after the last posts in that discussion and more than 2 years after the release of v1.8 it could be a good time to re-raise the topic. Maybe it's time to do the change it in 1.12?

**Comment by shoyer** [comment] 2016-05-23 00:42
Yes, that looks like the right discussion. It does look like it petered out without a resolution -- I would suggest re-raising it on the mailing list.

**Comment by ahaldane** [comment] 2016-07-06 19:08
PR #6054 implements a deprecation warning for this change, by the way. The idea would be to warn in 1.12, then implement in 1.13.

**Comment by rgommers** [comment] 2021-05-08 16:03
Closing as a duplicate of gh-5407.

**Closed by rgommers** 2021-05-08 16:03 UTC
