### ISSUE TITLE
Installing Numpy on Mac 10.8 fails

### ISSUE THREAD

**Issue by anishek** [numpy/numpy#3525] opened 2013-07-16 08:20 UTC
Trying to install numpy using "pip install numpy". fails with the error  below. I tried getting more info on #scipy on irc.freenode.net. and was suggested to post a bug here. 

Python 2.7.5 was installed using brew. 
Also tried to install via "pip-2.7 install numpy" and i get the same error. Original intention was to install gdal via "brew install gdal" which has dependency on numpy and hence trying to install this.

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/setup.py", line 214, in <module>

```
setup_package()
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/setup.py", line 207, in setup_package

```
configuration=configuration )
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/core.py", line 186, in setup

```
return old_setup(**new_attr)
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup

```
dist.run_commands()
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands

```
self.run_command(cmd)
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

```
cmd_obj.run()
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/egg_info.py", line 8, in run

```
self.run_command("build_src")
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command

```
self.distribution.run_command(command)
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

```
cmd_obj.run()
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/build_src.py", line 152, in run

```
self.build_sources()
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/build_src.py", line 163, in build_sources

```
self.build_library_sources(*libname_info)
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/build_src.py", line 298, in build_library_sources

```
sources = self.generate_sources(sources, (lib_name, build_info))
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/build_src.py", line 385, in generate_sources

```
source = func(extension, build_dir)
```

  File "numpy/core/setup.py", line 646, in get_mathlib_info

```
st = config_cmd.try_link('int main(void) { return 0;}')
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/config.py", line 251, in try_link

```
libraries, library_dirs, lang)
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/config.py", line 149, in _link

```
libraries, library_dirs, lang))
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/config.py", line 89, in _wrap_method

```
ret = mth(*((self,)+args))
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/config.py", line 143, in _link

```
(src, obj) = self._compile(body, headers, include_dirs, lang)
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/config.py", line 99, in _compile

```
(body, headers, include_dirs, lang))
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/command/config.py", line 89, in _wrap_method

```
ret = mth(*((self,)+args))
```

  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/config.py", line 138, in _compile

```
self.compiler.compile([src], include_dirs=include_dirs)
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/ccompiler.py", line 203, in CCompiler_compile

```
self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
```

  File "/private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy/numpy/distutils/unixccompiler.py", line 34, in UnixCCompiler__compile

```
self.spawn(self.compiler_so + cc_args + [src, '-o', obj] +
```

TypeError: coercing to Unicode: need string or buffer, list found

---
```
Command python setup.py egg_info failed with error code 1 in /private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy

Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /private/var/folders/61/zlk3fs0x6_j5zdqm3t_m0hww0000gp/T/pip-build-aagarwal/numpy
```

**Comment by arogozhnikov** [comment] 2016-07-27 01:11
I have the same issue when using pythran on mac os 10.11 (I have numpy and xcode CLI installed)

```
Traceback (most recent call last):
  File "/Users/axelr/.venvs/rep/bin/pythran", line 11, in <module>
    sys.exit(run())
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/run.py", line 133, in run
    **compile_flags(args))
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 346, in compile_pythranfile
    **kwargs)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 317, in compile_pythrancode
    **kwargs)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 279, in compile_cxxcode
    output_binary, **kwargs)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 232, in compile_cxxfile
    extension_args = make_extension(**kwargs)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/config.py", line 81, in make_extension
    numpy_blas = numpy_sys.get_info("blas")
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/system_info.py", line 378, in get_info
    return cl().get_info(notfound_action)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/system_info.py", line 566, in get_info
    self.calc_info()
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/system_info.py", line 1685, in calc_info
    lib = self.has_cblas(info)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/system_info.py", line 1714, in has_cblas
    include_dirs=self.get_include_dirs())
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 230, in CCompiler_compile
    single_compile(o)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 194, in single_compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/unixccompiler.py", line 48, in UnixCCompiler__compile
    self.spawn(self.compiler_so + cc_args + [src, '-o', obj] +
TypeError: coercing to Unicode: need string or buffer, list found
```

Any ideas?

**Comment by rgommers** [comment] 2016-11-06 09:01
@arogozhnikov how would I reproduce that issue with Pythran?

**Comment by arogozhnikov** [comment] 2016-11-06 09:54
I don't remember how I got that error, but I tried to use pythran on MacOS X again, and got other unicode-related error.

```
%%file _pythran.py
"""
Naive dotproduct! Pythran supports numpy.dot
"""
#pythran export dprod(int list, int list)
def dprod(l0,l1):
    """WoW, generator expression, zip and sum."""
    return sum(x * y for x, y in zip(l0, l1))
```

and then 
```
!pythran _pythran.py
```
gives
```
WARNING  Pythran support disabled for module: omp
/var/folders/r9/83ys7d7j3_768l9xyfk4xhls150gv4/T/tmpxpZjyZ/source.c:1:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^
1 error generated.
/var/folders/r9/83ys7d7j3_768l9xyfk4xhls150gv4/T/tmpxpZjyZ/source.c:1:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^
1 error generated.
/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/system_info.py:635: UserWarning: Specified path  is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
Traceback (most recent call last):
  File "/Users/axelr/.venvs/rep/bin/pythran", line 11, in <module>
    sys.exit(run())
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/run.py", line 133, in run
    **compile_flags(args))
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 346, in compile_pythranfile
    **kwargs)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 317, in compile_pythrancode
    **kwargs)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 279, in compile_cxxcode
    output_binary, **kwargs)
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/pythran/toolchain.py", line 249, in compile_cxxfile
    '--build-temp', buildtmp,
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 206, in run
    self._cxx_compiler = compiler.cxx_compiler()
  File "/Users/axelr/.venvs/rep/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 517, in CCompiler_cxx_compiler
    cxx.compiler_so = [cxx.compiler_cxx[0]] + cxx.compiler_so[1:]
TypeError: can only concatenate list (not "unicode") to list
```

Python2, os X 10.11, numpy '1.10.4', pythran '0.7.6post1' (latest).

(Meanwhile it works on linux workstation)

**Comment by rgommers** [comment] 2016-11-07 08:55
Thanks. I can't reproduce this on OS X 1.12.0 with numpy 1.11.2.

How I tried to reproduce this.

    conda create --name pythranissue python=2
    source activate pythranissue
    conda install --name pythranissue numpy
    pip install pythran  # no osx conda package
    pythran dprod.py 
    python -c "import dprod"

There are no warnings. With ``numpy==1.10.4`` I do get the ``#include <cblas.h>`` warnings, but those seem to be unrelated. So there's something in the environment that triggers this ``TypeError``, it's not just OS and numpy version.

**Comment by mattip** [comment] 2018-08-08 19:15
The original issue was about numpy and mac 10.8. Closing, please open a new issue about pythran if the issue still persists.

**Closed by mattip** 2018-08-08 19:15 UTC
Labels: 00 - Bug, component: numpy.distutils, priority: low
