### ISSUE TITLE
Inconsistency in astype() from float64 to datetime64 for np.nan on numpy-1.11.1

### ISSUE THREAD

**Issue by mmnelemane** [numpy/numpy#7830] opened 2016-07-12 16:46 UTC
On x86:
`>>>np.float64(np.nan).astype('M8[ns]')`
`numpy.datetime64('NaT')`

On ARM:
`>>>np.float64(np.nan).astype('M8[ns]')`
`numpy.datetime64('1970-01-01T00:00:00.00000000')`

Some tests for pandas fail on ARM due to this difference

Traceback (most recent call last):
  File "/root/venv/lib/python2.7/site-packages/pandas/tseries/tests/test_timeseries.py", line 4072, in test_NaT_cast
    assert_series_equal(result, expected)
  File "/root/venv/lib/python2.7/site-packages/pandas/util/testing.py", line 1049, in assert_series_equal
    check_less_precise, obj='{0}'.format(obj))
  File "pandas/src/testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas/src/testing.c:3887)
  File "pandas/src/testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas/src/testing.c:2769)
  File "/root/venv/lib/python2.7/site-packages/pandas/util/testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (100.0 %)

**Comment by QuLogic** [comment] 2017-10-22 00:11
I think this is a dupe of #8325 and though this is older, it seems to have gotten a bit more activity.

**Comment by eric-wieser** [comment] 2017-10-22 00:29
Yep, duplicate of #8325

**Closed by eric-wieser** 2017-10-22 00:29 UTC
