### ISSUE TITLE
numpy.random.multivariate_normal unexpected behaviour after seed

### ISSUE THREAD

**Issue by TastyColin** [numpy/numpy#13597] opened 2019-05-21 03:21 UTC
When changing the covariance matrix in numpy.random.multivariate_normal after setting the seed, the results depend on the order of the eigenvalues. For instance, in the case of a bi-variate Gaussian distribution with a covariance = 0, if we multiply by 4  (=2^2), the variance of one variable, the corresponding realisation is expected to be multiplied by 2. My guess is that when calculating the root square of the covariance, the eigenvalues are sorted.

(I use this function to simulate vector autoregressive models, and I need my noise realisations to be constant when changing the noise's variance.)

### Reproducing code example:

```python
import numpy as np

np.random.seed(0)
print(np.random.multivariate_normal(np.zeros(2), np.diag([1,1])))
np.random.seed(0)
print(np.random.multivariate_normal(np.zeros(2), np.diag([4,1]))) # multiply by 2 the first variable's variance
np.random.seed(0)
print(np.random.multivariate_normal(np.zeros(2), np.diag([1,4]))) # multiply by 2 the second variable's variance
```

output:
```
[1.76405235 0.40015721]
[3.52810469 0.40015721]
[0.40015721 3.52810469]
```

Expected output:
```
[1.76405235 0.40015721]
[3.52810469 0.40015721]
[0.88202618 0.2000786 ]
```
### Numpy/Python version information:
1.14.5 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]

**Comment by rkern** [comment] 2019-05-21 03:36
The only reproducibility guarantee that we provide is that the outputs are reproduced when you initialize the PRNG with the same state and you call the methods in the same order _with the same parameters_.

If you have a case where the distribution can be derived from a scaling/linear-transformed version of a standardized distribution, and you need the variations to be consistent despite the scaling/linear-transform, then you should draw the standardized distribution and do the scaling/linear-transforms yourself.

**Comment by seberg** [comment] 2019-05-21 17:49
As Robert Kern notes and knows best, there are no guarantees for this specific use case (and we are relaxing the guarantees anyways). For this specific function, things are even trickier I think, since it calls linear algebra tools and those can very easily behave differently on different platforms (although in typical cases probably not much).

In any case, you will have to do the transforms yourself unfortunately. The code for `multivariate_normal` is written in cython, but most of it is probably just normal python calls, so it may be useful as a start for your.

I hope this helps. If you have any questions, please do not hesitate to continue here, but I will close the issue.

**Closed by seberg** 2019-05-21 17:49 UTC

**Comment by dionman** [comment] 2020-01-10 15:10
hi,
a related question: I experience indeterminism after fixing the seed and passing identical arguments for function calls of the form ``` np.random.multivariate_normal(muw, Sigw, sz) ```, when ```Sigw``` has repeated eigenvalues. What's the most principled approach to tackle this problem?

**Comment by charris** [comment] 2020-01-10 15:24
Is this during the same session or in different sessions on different platforms? I think the only way to guarantee repeatable streams in this situation is to reuse a given factorization of the covariance matrix as when there are repeated eigenvalues it isn't unique. A cholesky based factorization is probably more repeatable, but even there I would expect differences between libraries and platforms. How different are the results?

**Comment by dionman** [comment] 2020-01-12 17:47
This happens during the same session on the same platform. Results do not diverge a lot, but still difference is noticeable. Could you explain to me the intuition why cholesky factorization can be more repeatable compared to svd?

**Comment by charris** [comment] 2020-01-12 18:01
Ordinary Cholesky follows a predictable set of steps, no pivoting or branching, so the result is essentially unique up compiler optimizations. SVD is an iterative solution and not unique when identical singular values are present. As to why results might vary in your case, I'm not sure, but if they are close, even if not identical, it suggests some numerical sensitivity. I'm just guessing that that might occur in the factorization, but I suppose it could also happen in the matrix multiplication step.
