### ISSUE TITLE
IndexError with np.ma.median along axis on unmasked array

### ISSUE THREAD

**Issue by MSeifert04** [numpy/numpy#8015] opened 2016-09-04 15:59 UTC
Something has changed between numpy 1.11 and the master branch, and it seems `np.ma.median` cannot handle an unmasked (``mask=False``) MaskedArray.

For example: `np.ma.median(np.ma.array(np.ones((5, 5))), axis=0)` throws an IndexError.

I haven't investigated it but to me it seems that `np.ma.array` creates a new mask (if the array hasn't got a mask already) and it is `False` (scalar). When using an axis with `np.ma.median` I suspect that the mask is applied to the data and then throws this Error:

```
IndexError                                Traceback (most recent call last)
<ipython-input-26-b5117c1f3918> in <module>()
----> 1 np.ma.median(np.ma.array(np.ones((5, 5))), axis=0)

C:\-\lib\site-packages\numpy\ma\extras.py in median(a, axis, out, overwrite_input, keepdims)
    693 
    694     r, k = _ureduce(a, func=_median, axis=axis, out=out,
--> 695                     overwrite_input=overwrite_input)
    696     if keepdims:
    697         return r.reshape(k)

C:\-\lib\site-packages\numpy\lib\function_base.py in _ureduce(a, func, **kwargs)
   3631         keepdim = [1] * a.ndim
   3632 
-> 3633     r = func(a, **kwargs)
   3634     return r, keepdim
   3635 

C:\-\lib\site-packages\numpy\ma\extras.py in _median(a, axis, out, overwrite_input)
    736             low = high
    737     else:
--> 738         low[odd] = high[odd]
    739 
    740     if np.issubdtype(asorted.dtype, np.inexact):

C:\-\lib\site-packages\numpy\ma\core.py in __getitem__(self, indx)
   3161 
   3162         """
-> 3163         dout = self.data[indx]
   3164         # We could directly use ndarray.__getitem__ on self.
   3165         # But then we would have to modify __array_finalize__ to prevent the

IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index
```

Which currently breaks some tests for astropy (see https://github.com/astropy/astropy/issues/5303).

**Comment by charris** [comment] 2016-09-04 16:06
Grrr, and I now get
```
In [1]: np.ma.median(np.ma.array(np.ones((5, 5))), axis=0)
/home/charris/.local/lib/python2.7/site-packages/numpy-1.11.0.dev0+88f5645-py2.7-linux-x86_64.egg/numpy/ma/core.py:3153: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  dout = self.data[indx]
/home/charris/.local/lib/python2.7/site-packages/numpy-1.11.0.dev0+88f5645-py2.7-linux-x86_64.egg/numpy/ma/core.py:3258: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  _data[indx] = dval
```
in the coming 1.11.x branch.

**Comment by charris** [comment] 2016-09-04 16:19
As a side note
```
In [6]: np.median(np.ma.array(np.ones((5, 5))), axis=0)
Out[6]: 
masked_array(data = [ 1.  1.  1.  1.  1.],
             mask = False,
       fill_value = 1e+20)
```
so the problem is specific to the masked version of median.

**Comment by MSeifert04** [comment] 2016-09-04 16:30
@charris Thank you for the fast reply. 

I think `np.median` has no problems there because it simply ignores the mask (#7330).

**Comment by charris** [comment] 2016-09-04 17:31
`_median` has got to be one of the ugliest functions in numpy.

**Comment by charris** [comment] 2016-09-04 17:41
OK, immediate fix was easy, but there is another oddity
```
In [5]: np.ma.median(np.ma.array(np.ones((5, 5))), axis=1)
```
raises an axis out of bounds error.

**Comment by charris** [comment] 2016-09-04 18:32
Should be fixed by #8016.

**Comment by charris** [comment] 2016-09-04 19:19
The `IndexError` message is also pretty strange...

**Comment by charris** [comment] 2016-09-04 19:44
@seberg When does that workaround need to be fixed?

**Comment by seberg** [comment] 2016-09-05 05:52
You mean that one: `IndexError: in the future, 0-d boolean arrays will be interpreted as a valid boolean index`? It means that:
```
arr = np.ones((4, 4))
arr[np.array(False), :, :] == np.ones((0, 4, 4))  # copy is made
arr[np.array(True), :, :] == np.ones((1, 4, 4))  # copy is made
```
after the deprecation, might already fix the issue at hand if we go through with it (did not check it, but if it ran into this rare case already, it seems likely that doing the generalized thing that used to be not supported may be the right thing).

**Comment by charris** [comment] 2016-09-05 13:28
@seberg I was trying to remember when the future would arrive :0

**Comment by charris** [comment] 2016-09-05 15:25
Note that `ma.median` doesn't handle 0-d arrays.

**Comment by seberg** [comment] 2016-09-05 16:26
I think we can probably do it pretty soon, however it should probably be one version of the deprecation of `operator.index(np.array(True))`.

The case of numpy bools (or probably also usual bool), seems to still be only another deprecation warning, so to be safe we should probably wait till 1.13

**Closed** 2016-09-06 13:41 UTC
Labels: 11 - Bug, component: numpy.ma
