### ISSUE TITLE
cannot install numpy on python 3.13

### ISSUE THREAD

**Issue by jirafey** [numpy/numpy#25917] opened 2024-03-02 16:47 UTC
### Steps to reproduce:

```pip install numpy```

### Error message:

```shell
pip install numpy
Collecting numpy
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [184 lines of output]
      + C:\Users\joe\PycharmProjects\pythonProject3\venv\Scripts\python.exe C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-mes
on\meson\meson.py setup C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9
e0f2e8c4c909c9f7556f4cfd3de\.mesonpy-pjnbsayc -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\.mesonpy-pjnbsayc\meson-python-native-file.ini
      Traceback (most recent call last):
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\msetup.py", line 358, in run
          app.generate()
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\msetup.py", line 183, in generate
          return self._generate(env, capture, vslite_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\msetup.py", line 228, in _generate        
          intr.run()
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 3002, in run
          super().run()
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 164, in run
          self.evaluate_codeblock(self.ast, start=1)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 2414, in func_subdir
          self.evaluate_codeblock(codeblock)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 206, in evaluate_statement
          return self.evaluate_if(cur)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 301, in evaluate_if
          self.evaluate_codeblock(i.block)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 228, in evaluate_statement
          self.evaluate_foreach(cur)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 472, in evaluate_foreach
          self.evaluate_codeblock(node.block)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 206, in evaluate_statement
          return self.evaluate_if(cur)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 306, in evaluate_if
          self.evaluate_codeblock(node.elseblock)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 198, in evaluate_statement
          self.assignment(cur)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 635, in assignment
          value = self.evaluate_statement(node.value)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 826, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [Previous line repeated 4 more times]
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 109, in wrapped
          ret = f(*wrapped_args, **wrapped_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 127, in wrapped
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1779, in func_dependency
          d = df.lookup(kwargs)
              ^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreter\dependencyfallbacks.py", line 355, in lookup
          dep = func(kwargs, func_args, func_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\interpreter\dependencyfallbacks.py", line 87, in _do_dependency
          dep = dependencies.find_external_dependency(name, self.environment, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\dependencies\detect.py", line 124, in find_external_dependency
          d = c()
              ^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\dependencies\blas_lapack.py", line 497, in __init__
          super().__init__('OpenBLAS', env, kwargs, language, force_use_global_compilers)
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 137, in __init__
          CMakeDependency.class_cmakeinfo[self.for_machine] = self._get_cmake_info(cm_args)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 185, in _get_cmake_info
          ret1, out1, err1 = self._call_cmake(cmake_opts, 'CMakePathInfo.txt')
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 618, in _call_cmake
          build_dir = self._setup_cmake_dir(cmake_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\vendored-meson\meson\mesonbuild\dependencies\cmake.py", line 589, in _setup_cmake_dir
          cmake_txt = importlib.resources.read_text('mesonbuild.dependencies.data', cmake_file, encoding = 'utf-8')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'importlib.resources' has no attribute 'read_text'
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de
      Build dir: C:\Users\joe\AppData\Local\Temp\pip-install-4xkbybbi\numpy_f33b9e0f2e8c4c909c9f7556f4cfd3de\.mesonpy-pjnbsayc
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      C compiler for the host machine: ccache gcc (gcc 13.2.0 "gcc (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders, r5) 13.2.0")
      C linker for the host machine: gcc ld.bfd 2.42
      C++ compiler for the host machine: ccache c++ (gcc 13.2.0 "c++ (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders, r5) 13.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.42
      Cython compiler for the host machine: cython (cython 3.0.8)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (C:\Users\joe\PycharmProjects\pythonProject3\venv\Scripts\python.exe)
      Run-time dependency python found: YES 3.13
      Has header "Python.h" with dependency python: YES
      Compiler for C supports arguments -fno-strict-aliasing: YES
      Test features "SSE SSE2 SSE3" : Supported
      Test features "SSSE3" : Supported
      Test features "SSE41" : Supported
      Test features "POPCNT" : Supported
      Test features "SSE42" : Supported
      Test features "AVX" : Supported
      Test features "F16C" : Supported
      Test features "FMA3" : Supported
      Test features "AVX2" : Supported
      Test features "AVX512F" : Supported
      Test features "AVX512CD" : Supported
      Test features "AVX512_KNL" : Supported
      Test features "AVX512_KNM" : Supported
      Test features "AVX512_SKX" : Supported
      Test features "AVX512_CLX" : Supported
      Test features "AVX512_CNL" : Supported
      Test features "AVX512_ICL" : Supported
      Test features "AVX512_SPR" : Supported
      Configuring npy_cpu_dispatch_config.h using configuration
      Message:
      CPU Optimization Options
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. ```
```

### Additional information:

Windows 11

**Comment by mattip** [comment] 2024-03-02 18:10
Duplicate of #25506, fixed on HEAD. If you are going to try an unreleased Python, you should  installing from git, not from PyPI, via `pip install git+https://github.com/numpy/numpy.git`

**Closed by mattip** 2024-03-02 18:10 UTC
Labels: 32 - Installation
