### ISSUE TITLE
complex-valued comparison incorrectly succeeds

### ISSUE THREAD

**Issue by nschloe** [numpy/numpy#17361] opened 2020-09-21 19:47 UTC
Since there is no ordering in the complex numbers, vanilla Python correctly rejects something like
```python
0 < 1 + 1j
```
with
```
TypeError: '<' not supported between instances of 'int' and 'complex'
```
Numpy incorrectly does something -- no idea what though. In any case, the following should probably fail:
```python
import numpy

z = 1 + 1j
0 < numpy.array(z)  # succeeds?!
```

**Comment by pv** [comment] 2020-09-22 11:40
Complex numbers can be ordered, and Numpy uses the lexicographic order. It's true that no ordering exists that satisfies similar relations vs. both addition and multiplication as for reals. But I don't think the present behavior is really incorrect.

**Comment by seberg** [comment] 2020-09-23 16:52
There was some discussion previously and we were seriously considering deprecating it in gh-15981, and not long ago Rakesh started working on that in gh-17030.

That said, it is hard to say what fallout might crop up which may lead us to keep the current behaviour. And it indeed is not a bug as such.

I am going to close this in favor of the linked issue, @nschloe if you want to discuss this further, I would suggest commenting either on the issue or PR.

**Closed by seberg** 2020-09-23 16:52 UTC
