### ISSUE TITLE
AttributeError: NumpyDistribution instance has no attribute 'include_package_data'

### ISSUE THREAD

**Issue by kumarsaurabh20** [numpy/numpy#7692] opened 2016-05-29 17:46 UTC
Hi,
while installing numpy I get this error:
AttributeError: NumpyDistribution instance has no attribute 'include_package_data'

Any suggestions?
PS: Log file is attached
[numpy.txt](https://github.com/numpy/numpy/files/288468/numpy.txt)

**Comment by rgommers** [comment] 2016-05-29 18:54
Hmm, that looks fairly familiar. Similar to gh-7235.

A few questions:

- is this with current numpy master (what exact commit)?
- what version of setuptools do you have installed?
- do you get the same error with ``pip install .``?

**Comment by rgommers** [comment] 2016-05-29 19:00
I think we can get rid of ``NumpyDistribution`` anyway, but this stuff is really fragile so that's probably not a complete solution. Importing ``Distribution`` directly from ``setuptools`` instead of from ``distutils`` to avoid the monkeypatching may be better, but also doesn't sound appealing.

**Comment by kumarsaurabh20** [comment] 2016-05-29 19:03
Yes this is with current numpy master.
I installed setuptools from master branch https://github.com/pypa/setuptools

> pip install

 worked well. I tried to install numpy for a software specific python 2.7

**Comment by rgommers** [comment] 2016-05-29 19:11
Might be a ``setuptools`` regression then. I see that there's a new ``setuptools`` release today, can't reproduce your issue with that though. Could you see if your problem is still there when you install ``setuptools`` 21.2.2?

**Comment by kumarsaurabh20** [comment] 2016-06-02 16:58
Sorry for the delayed reply. 

I tried with the latest setuptool release (21.2.2) but ended up with the same error. However, things ran smoothly with previous version of numpy. I tried v1.10.4 (Jan 7 release).

**Comment by rgommers** [comment] 2016-06-03 06:19
Thanks @kumarsaurabh20. Numpy v1.10.4 doesn't use ``setuptools`` at all, so it makes sense that this issue doesn't occur there.

Found one more mention of the same problem on the mailing list:
http://article.gmane.org/gmane.comp.python.numeric.general/63030/match=include_package_data

And this one seems very much the same, but with older Numpy and ``pip`` (which bundles and forces use of ``setuptools``): https://groups.google.com/forum/#!topic/scikit-fuzzy/wWoq6okHOLQ

And for this project the same, right when switching to ``setuptools``: https://github.com/nipy/PySurfer/issues/74

Here two examples of the same issue *but without Numpy involved*: http://stackoverflow.com/questions/24846953/error-installing-cryptography-on-centos
https://bugs.launchpad.net/swift/+bug/1217288

This problem seems to be quite hard to reproduce, because it depends on some timing variation during monkeypatching of the ``distutils`` ``Distribution`` instance or some combination of ``setuptools`` version with something else (``pbr`` version?).

**Comment by rgommers** [comment] 2016-06-03 06:32
@kumarsaurabh20 just to make sure: you're not using ``pbr``, ``d2to1`` or any other packaging helper tool right? Or any modifications to your ``site.py`` or ``sitecustomize`` which import some other package? It would be helpful to see the content of ``sys.modules.keys()`` at the point where you encounter the failure.

**Comment by rgommers** [comment] 2016-06-03 06:36
Last request for now: can you please check that if you patch your  Python ``distutils`` with the patches in http://bugs.python.org/issue23102 the issue goes away? If so, I'm going to try to get that moving, because that looks like the structural solution.

**Comment by rgommers** [comment] 2023-09-16 08:40
We've switched build systems from `numpy.distutils` to Meson, hence this issue is no longer relevant. Hence closing - thanks all.

**Closed by rgommers** 2023-09-16 08:40 UTC
Labels: 00 - Bug, component: numpy.distutils, component: build
