### ISSUE TITLE
'string'*numpy.bool_(True) raises TypeError; was ok in numpy 0.9

### ISSUE THREAD

**Issue by mcgfeller** [numpy/numpy#9234] opened 2017-06-09 10:51 UTC
Dear all

I encountered a potential regression when upgrading from numpy 1.9 to 1.12.

```python
>>> 'string'*numpy.bool_(True) 
TypeError: an integer is required
```

Numpy version: 1.12.1
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Windows 7, 64-bit

This worked ok in Numpy 1.9 with the same Python and OS version.

Actually, this is is simplified from the actual use case:
```python
>>>a_np = numpy.float64(3.1415)
>>>'string'*(a_np>0)
```

This works ok when a_np is numpy.float(3.1415), because the result type of the comparison is bool, not numpy.bool_.

Thank you and best regards
Martin

**Comment by eric-wieser** [comment] 2017-06-09 11:50
I think this is by design, but I'm not sure when it was introduced.

The workaround is to use 'string'*int(numpy.bool_(True))`

**Comment by charris** [comment] 2017-06-09 16:42
Just for reference
```
In [3]: type(a_np > 0)
Out[3]: numpy.bool_
```
So this is probably a change in the return type for scalar comparisons. This has been true since at least 1.10.0.

**Comment by eric-wieser** [comment] 2017-07-13 15:35
Can we close this as wontfix/invalid, since bool_ is deliberately not treated like an integer?

**Comment by seberg** [comment] 2017-07-13 16:52
Actually, the thing is that `operator.index(np.bool_(True)` won't work, but yes, it is by design, because if we would allow this `some_list[np.bool_(True)]` would work, and then things blow up, because we have to do something different then that for `some_array[no.bool_(True)]`, and really IMO the annoying thing is that *python* inherited that True and False is basically just 1 and 0 instead of considering them some special object.

We have had a deprection in place for this since a while (probably it is there in 1.9), though unfortunatly you won't see it nuless you enable it (`import warnings; warnings.simplefilter("always")` at the start of the program, or the according flags to python).

You might want to run your program with these warnings enabled (or even the deprecation warnings set to error) to find other such problems. We changed quite a bit of things prohibiting silent conversions to integer, and there is no going back anymore IMO.

About running with errors to find these problems:
```
import warnings
# use "always" to see them, but "error" gives a traceback since often it is unclear
# where it comes from exactly.
warnings.filterwarnings("error", category=DeprecationWarning, message="")
```
For message, just put in the beginning of the message the warning prints (it uses regular expression stuff, but you don't have to care).

**Comment by seberg** [comment] 2017-07-13 16:54
I am really sorry that this is annoying you, it was a long and painful change for us as well. However, with the correct warning settings it should be very quick to add explicit conversions to integer where needed.

If you have python 3 code (or dual use code). A very common thing may also be to use `//` operator instead of `/` to explicitly use the integer/floor division.

**Comment by eric-wieser** [comment] 2017-07-13 16:56
That last comment looks like it might have been intended for another issue, since it refers to division?

**Comment by seberg** [comment] 2017-07-13 16:58
Hmmm, maybe I am wrong. Just realized that this is very specifically the `np.bool_` type, and I don't specifically remember the deprecation there. But I suspect it is the same thing anyway, because it is a necessary change for where we wanted to go there.

@eric-wieser no, it was meant here. It is a different issue, but it is another "integer deprecation" related issue, which I suspect this is as well. If you had code like `arr[5/3]` this used to work in python 3 even though it should not and it should be converted to `arr[5//3]`.

**Comment by seberg** [comment] 2017-07-13 17:02
OK, sorry all. I was wrong of course :). You are right it is the subclass thing, actually it seems `"string" * object` does not really use `operator.index` which actually seems to work. And frankly it is OK, since we need to filter for usual python bools also in our indexing, etc.

So please ignore all I wrote :), it is not a necessary change for that....

**Comment by eric-wieser** [comment] 2017-07-13 17:07
@seberg: `string*x` [uses `operator.index`](https://github.com/python/cpython/blob/d174d24a5d37d1516b885dc7c82f71ecd5930700/Objects/abstract.c#L941-L945)

**Comment by seberg** [comment] 2017-07-13 17:08
OK, maybe, but *we* actually throw an error specifically here, which I have to agree is unnecessary and probably a bug. It probably snuck in when we removed that this works for floats, which it used and that was a real error?

**Comment by seberg** [comment] 2017-07-13 17:09
Ah, it makes sense though, because it is probably generic code for all scalars, and they just try to convert themself to integer using numpy's "convert to integer" functions. And since in most places we do not want to convert booleans, we throw an error.

This seems to be an exception though, since here we specifically might want to allow booleans for compatibility with python.

**Comment by eric-wieser** [comment] 2017-07-13 17:11
> OK, maybe, but we actually throw an error specifically here

Hm, that's interest. It seems that `sequence_repeat` doesn't get tried unless both `__add__` and `__radd__` have given up. And actually, `operator.index(np.bool_(True))` appears to work just fine.

**Comment by seberg** [comment] 2017-07-13 17:12
Or... we just return NotImplemented if the other is a string (but need to check if it is also ok in python 2.7). Yes, makig `index` from numpy bools works fine, the normal C-side "convert to integer" function of numpy disallows it though.

**Comment by eric-wieser** [comment] 2017-07-13 17:13
> we just return NotImplemented if the other is a string

Or any object implementing `tp_as_sequence->sq_repeat`

**Comment by eric-wieser** [comment] 2017-07-13 17:14
I'm actually pretty confused right now about where this error is originating from

**Comment by seberg** [comment] 2017-07-13 17:16
I am not quite sure if there is a sequence repeat for the non-sequence operand?  Or our `__rmul__`/`__mul__` for scalars. It must somehwere have a `PyArray_PyIntAsIntp` call, that will cause the error.

**Comment by eric-wieser** [comment] 2017-07-13 17:16
`gentype_multiply` has `PyArray_PyIntAsIntp` specifically for this case, where it should probably have `PyNumber_AsSsize_t`

**Comment by seberg** [comment] 2017-07-13 17:17
Yes, that is what I meant. Ours disallows bools, and apparently this is the one tiny exceptions where we might not want that.

**Comment by mcgfeller** [comment] 2017-07-14 11:03
Thanks for your careful considerations. I can confirm that a DeprecationWarning is shown in 1.9. I can live with the changed behavior, 

Thanks again! Martin

**Comment by seberg** [comment] 2017-07-14 12:02
Yeah, but it is still accidentally deprecated ;). It happened in this (and possibly one or so other place). So I think we should undo it, even if it is not a big problem.

**Closed** 2017-12-27 18:00 UTC
Labels: 00 - Bug, difficulty: Easy

**Comment by eric-wieser** [comment] 2017-12-27 18:06
@seberg: went with your suggestion of returning `NotImplemented`, which apparently works fine

**Comment by seberg** [comment] 2017-12-27 23:20
Hehe, I don't really remember, but I am sure it must have been reasonable ;)
