### ISSUE TITLE
Numpy tests fail on musl/AlpineLinux

### ISSUE THREAD

**Issue by xdmiodz** [numpy/numpy#7128] opened 2016-01-27 11:46 UTC
On AlpineLinux, which is a mil based Linux distributive, some of numpy's test fail. The log is attached.
[log.txt](https://github.com/numpy/numpy/files/106482/log.txt)

There are two types of issues - one for various missed overflow/underflow exceptions, the second one is for incorrect results from musl's trigonometric functions.

The first one can be fixed by including `fenv.h` header in musl builds, AFAIU this can be done in `numpy/numpy/core/src/npymath/ieee754.c.src` and `numpy/core/include/numpy/ufuncobject.h 
` by replacing `__GLIBC__` with `__GNUC__`

The second group can be fixed by disabling the trigonometric functions in `numpy/numpy/core/src/private/npy_config.h` not only for glibc, but also for musl. An issue here is that musl doesn't provide any macro like the `__GLIBC__` to detect it. 

So the question, is numpy interested in such a patch? Could you please share your opinions  what is best way to implement it?

Otherwise the patch can be implement in corresponding package for AlpineLinux

**Comment by kylekyle** [comment] 2016-03-19 00:46
Yep, still no numpy for alpine users (which is increasingly popular as a docker base). It's made life miserable for our python users. Would love to see a patch.

**Comment by charris** [comment] 2016-03-19 01:04
What library does AlpineLinux use? It must be something pretty close to glibc if the same trig functions fail.

**Comment by charris** [comment] 2016-03-19 01:13
OK, it's musl. Is the really no macro to identify the presence of musl? One problem is other libc implementations combined with the gnuc compiler, so we can't just use `__GNUC__`.

**Comment by njsmith** [comment] 2016-03-19 01:47
Another case where trying to have an explicit list of all bad libm versions
bites us :-/ If someone is feeling particularly inspired, an fully
comprehensive solution would be to tackle #7173.

**Comment by mattip** [comment] 2018-10-09 17:34
Duplicate of #12095, closing this since the other has more information

**Closed by mattip** 2018-10-09 17:34 UTC
