### ISSUE TITLE
Original error was: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by rda112** [numpy/numpy#15878] opened 2020-03-31 11:59 UTC
Importing the numpy c-extensions failed.

Original error was: No module named 'numpy.core._multiarray_umath'

python Version: 
3.7.0

numpy version
1.18.2

Operating System :Windows
### Error message:

Failed to load entry point 'info':

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "c:\python37\python_d.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.2" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'

tried reinstalling numpy. but the problem persist

**Comment by mattip** [comment] 2020-03-31 12:59
From the exe name `c:\python37\python_d.exe` it would seem you are using a debug build. This is probably a duplicate of gh-11508, see [this comment](https://github.com/numpy/numpy/issues/11508#issuecomment-542039599) for some ideas on what you might be able to do.

**Comment by rossbar** [comment] 2020-07-12 03:48
Closing due to inactivity, if the issue persists, please feel free to reopen with the most recent information.

**Closed by rossbar** 2020-07-12 03:48 UTC
Labels: 32 - Installation
