### ISSUE TITLE
Creating and argsorting an array with a structured dtype leaks memory

### ISSUE THREAD

**Issue by dpitch40** [numpy/numpy#7860] opened 2016-07-21 17:17 UTC
The following snippet of code consumes steadily increasing amounts of memory when run (even after the calls to gc.collect every 5000th iteration), as observed from the task manager. I have confirmed that changing the sort `kind` does not affect the issue.

```
import gc
import numpy as np

n = 0
while True:
    names = ["POH"] + \
        ["Head %d Really Long Data Field Name With Many Words" % i for i in xrange(200)]
    formats = [">f"] + [">I"] * 200
    offsets = range(0, 804, 4)

    dt = np.dtype({"names": names, "formats": formats, "offsets": offsets})
    array = np.zeros((1000,), dt)

    sortedIndices = np.argsort(array, order=["POH"])

    n += 1
    if n % 1000 == 0:
        print n
        if n % 5000 == 0:
            gc.collect()
```

I am running numpy 1.11.0 with Python 2.7.11 on 64-bit Windows 7.

**Comment by jaimefrio** [comment] 2016-07-22 08:12
Can you debug the cause of the leak? I.e. I'm betting on either the dtype creation or the argsort itself, but it could be the array creation. So if you could move the dtype and array creation in and out of the loop and report in which of the four possible cases the leak persists it would be very helpful. Thanks!

**Comment by dpitch40** [comment] 2016-07-22 14:04
Removing the dtype creation from the loop appears to stop the leak (as does removing the array creation as well). I don't think removing the array creation from the loop but not the dtype creation is possible. So the only case when it leaks is when they are both in the loop, and when I argsort the array.

**Comment by seberg** [comment] 2016-07-22 14:12
That makes sense, argsort should have a reference leak on the array dtype, in the cases you described, it would only increase the reference count of the dtype by one and thus not leak actual memory, since it is only one dtype that survives.

**Comment by dpitch40** [comment] 2016-07-22 14:19
So do you think it could be that argsort is leaking a reference to the copy of the dtype each time? It also doesn't appear to happen if I use a simple dtype (i.e. one without named fields to argsort on).

**Comment by seberg** [comment] 2016-07-22 14:21
Yes, a simple dtype will just find an existing dtype and return it from a table I believe `np.dtype('i') is np.dtype('i')`. It all adds up, just need to hunt down in the code where the reference is leaked. Almost certainly a missing DECREF somewhere.

**Comment by njsmith** [comment] 2016-07-22 19:31
To confirm that it's the dtype being leaked, you could put the dtype outside the loop and then call `sys.getrefcount` on it each time through - if that number grows without bound, then we're definitely leaking references to it.

**Comment by dpitch40** [comment] 2016-07-22 19:43
No, it doesn't appear to; it stays constant at 3. I tried moving the creation of `names`, `formats`, and `offsets` outside the loop while leaving the creation of `dt` inside. This also stops the leak, and the reference count of `names` stays constant at 2.

**Comment by seberg** [comment] 2016-07-25 09:28
Yes, right. What is leaking is not the dtype itself but the `"POH"` string.

**Comment by dpitch40** [comment] 2016-07-25 13:30
Okay, now I see what you mean. Even declaring `names` outside the loop, the sys.getrefcount of (apparently) each entry of `names` increases by 1 with each iteration of the loop. But this stops if I declare `dt` outside the loop. So it seems like argsort is leaking each name the first time it is called with a given dtype. I'm guessing it happens faster if names is declared in the loop because then the actual objects are being leaked and not just redundant references to the same object.

**Comment by seberg** [comment] 2019-01-02 22:46
This bug has been fixed in python master as part of gh-12624

**Closed by seberg** 2019-01-02 22:46 UTC
