### ISSUE TITLE
ENH: float 4 IBM format support as part of the basic types (such as 'f4')

### ISSUE THREAD

**Issue by thoth291** [numpy/numpy#6463] opened 2015-10-12 23:32 UTC
I'm aware that there are some ufunctions which convert float4ibm to ieee float and inverse.
The point of this enhancement request that there are many file formats (mostly in Earth Science) dealing with float4ibm and doing something like:

``` python
#assuming that 'w4' is format for float4ibm
mytype=numpy.dtype([('integer','>i4'),('float4ibm','>w4'),('string','S5')])
...
a=numpy.fromfile(fd,dtype=mytype,count=100)
...
a.tofile('updated.data',dtype=mytype)
```

looks much cleaner (and possibly closer to the user) than

``` python
#implement ufunc or cython or python version of **float4ieee** and **float4ibm**
mytype=numpy.dtype([('integer','>i4'),('float4ibm','i4'),('string','S5')])
...
a=numpy.fromfile(fd,dtype=mytype,count=100)
b=float4ieee(a['float4ibm'][:])
...
a['float4ibm'][:]=float4ibm(b)
a.tofile('chnaged.data',dtype=mytype)
```

My point is that **ibm float** is the same thing as **ieee 4 byte** and having one implemented and not another is unfair.

**Comment by njsmith** [comment] 2015-10-13 00:04
What is "ibm float"? I've never heard of this.

On Mon, Oct 12, 2015 at 4:32 PM, Anar Yusifov <notifications@github.com>
wrote:

> I'm aware that there are some ufunctions which convert float4ibm to ieee
> float and inverse.
> The point of this enhancement request that there are many file formats
> (mostly in Earth Science) dealing with float4ibm and doing something like:
>
> #assuming that 'w4' is format for float4ibm
> mytype=numpy.dtype([('integer','>i4'),('float4ibm','>w4'),('string','S5')])
> ...
> a=numpy.fromfile(fd,dtype=mytype,count=100)
> ...
> a.tofile('updated.data',dtype=mytype)
>
> looks much cleaner (and possibly closer to the user) than
>
> #implement ufunc or cython or python version of **float4ieee** and **float4ibm**
> mytype=numpy.dtype([('integer','>i4'),('float4ibm','i4'),('string','S5')])
> ...
> a=numpy.fromfile(fd,dtype=mytype,count=100)
> b=float4ieee(a['float4ibm'][:])
> ...
> a['float4ibm'][:]=float4ibm(b)
> a.tofile('chnaged.data',dtype=mytype)
>
> My point is that *ibm float* is the same thing as *ieee 4 byte* and
> having one implemented and not another is unfair.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numpy/numpy/issues/6463>.
>



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by thoth291** [comment] 2015-10-13 00:09
As far as I can say: https://en.wikipedia.org/wiki/IBM_Floating_Point_Architecture
This is what people normally do: http://stackoverflow.com/questions/7125890/python-unpack-ibm-32-bit-float-point in those cases.

**Comment by rkern** [comment] 2015-10-13 09:06
It's certainly fair to only implement IEEE floats since none of the CPU architectures that we support implement native IBM float arithmetic.

You will always have to convert to a native float somewhere along the line. The conversions could be made more convenient, certainly, and it might be useful to implement these conversion functions in numpy (@njsmith, yes these are quite common in the geosciences. The standards date from the 70s when VAXes ruled the Earth). One could imagine a function that takes a structured array and converts specified fields in-place and returns a view on the converted data with the native dtypes and another to go the other way.

It might also be reasonable to implement an arithmetic-less dtype for this purpose, so you just need to use `.astype()`. However, that approach encourages (requires) memory-copying while the explicit conversions above can be written to avoid that, which is often desirable since you only need to do these conversions upon I/O.

**Comment by mhvk** [comment] 2015-10-13 13:45
Learn something new every day! It would seem most logical to have the conversion done in whichever package actually reads the files that contain this format, rather than this be something in numpy (just like astronomy will not try to include a FITS reader on numpy...). Indeed, from a bit of googling, it seems `obspy` includes a python interface to some fast C code that just does that: https://docs.obspy.org/_modules/obspy/segy/unpack.html
That said, the conversion function linked to above is quite trivial to write in terms of in-place numpy functions.

**Comment by mhvk** [comment] 2015-10-13 13:46
@rkern - looking at further searches, it seemed you already wrote a ufunc to do the conversion -- https://mail.scipy.org/pipermail/scipy-user/2009-January/019392.html

**Comment by charris** [comment] 2015-10-13 14:08
I wouldn't say vaxes ruled the earth in the 70's, that would be IBM 360's and PDP10 mainframes and PDP 8 and PDP 11 minicomputers ;) Late 70's, and 80's though, yeah. Nice machines, and then the asteroid hit.

**Comment by thoth291** [comment] 2015-10-13 14:25
I'm aware about all of these methods (including segpy2). But please just consider a bit of a bigger picture.
As @rkern mentioned - seismic data comes from 70s and since those days many *exabytes of data*. And every day even more is generated. It's all happened long time before cheap little-endian machines so the format of the data is DE-facto IBM float.
I can't say for sure but according of what I know earth science data processing is in top 5 in the world by amount of data being processed on the supercomputers.
The comment of @rkern 
>One could imagine a function that takes a structured array and converts specified fields in-place and returns a view on the converted data with the native dtypes and another to go the other way.

might be a good start in the right direction.

Would it be a good for numpy to get a compliment from the big industry about running numpy job on a big cluster of 200K haswell cores - bringing powerful numpy tools to provide stability and rapid prototyping experience?

Thanks.

**Comment by thoth291** [comment] 2015-10-13 14:47
In addition to what I've said just would like to clarify: I'm not asking you guys to implement any seismic data formats in numpy (so no need to refer to FETS). All what I dream of - just a bit more closer to numpy support of IBM float and that's it.

Here is what we found with my friend related to justification of my words in previous topic.

http://www.hpcwire.com/2015/03/25/seismic-supercomputing-balloons-to-five-petaflops-and-this-ones-a-cray/

**Top supercomputers in oil and gas are now in 2-5 PFLOP range (BP, Total, Eni, PGS). They would all be placed somewhere between positions # 10 and # 25 on Top 500 June 2015 list, if the oil companies bothered to submit performance test results to Top500.**

http://www.economist.com/node/15582301

**"With 50 seismic vessels working around the clock industry-wide, this adds up to a total of around 12 petabytes of new data every year" - this is for marine seismic only**

http://www.matimop.org.il/Uploads/general_files/Eldad_Weiss_-_OG_technology_conference_V1.2_-PDF.PDF

**"$10B annual spending on data collection; currently accessible and archived data totals 150 - 200 petabytes and adding about 6 - 10 petabytes/year" - you can multiply this (200 PBs) by 10 for 2016-2017. We will be firmly in the exabyte territory by 2020, if we are not already.**

https://bldl.ii.uib.no/bldl-opening-presentations/Bouzas-BergenV1-Bouzas.pdf

**"Online storage: 38 petabytes" - Schlumberger alone had 38 PBs of storage. This is definitely higher by now. Although, it is not for seismic only.**

http://www.theplatform.net/2015/04/21/why-big-oil-keeps-spending-on-massive-supercomputers/

**"There are about a dozen petaflop systems in the world that are not in government labs or academic research. All the publicly announced of these Petascale systems are in oil and gas."**

**Comment by mhvk** [comment] 2015-10-13 14:50
@thoth291 - I don't think I was trying to diminish the importance, but really just argue where things belong. Surely, if one runs large jobs on supercomputers, one has standard seismic python packages that one uses (with hopefully numpy under the hood). Separation of concerns suggests those should those take care of the conversion. 

And yes, astronomy is also a large user of supercompuers, and at least on my blue gene jobs here in Toronto, I combine packages I wrote myself with astropy + numpy. If an equivalent to `astropy` does not exist for seismic studies, perhaps it should be made to?

Anyway, since I will neither be writing the code nor deciding the fate of any pull request to implement it, I'll shut up now.

**Comment by rkern** [comment] 2015-10-13 14:55
@charris My time resolution for everything before I was born is in terms of decades. :-)

@mhvk There is certainly a case to be made for supporting the format piecemeal in each package that needs it, but it does mean that many of these will do it poorly or inefficiently because writing the proper C code is annoying. I've personally done it poorly/inefficiently on at least three separate occasions. The case for supporting IBM floats in numpy, at least for conversion purposes, is similar to that for our support for `float16` which we only did to communicate with GPUs that use that format.

**Comment by seberg** [comment] 2021-07-01 23:46
We won't be adding such a new dtype to NumPy I think, so closing as the issue is ancient.  New dtypes *can* be added, and that support should be much nicer soon hopefully.

**Closed by seberg** 2021-07-01 23:46 UTC
Labels: 57 - Close?
