### ISSUE TITLE
einsum optimize default arg is documented as True but defaults to False

### ISSUE THREAD

**Issue by acbellini** [numpy/numpy#10258] opened 2017-12-22 16:20 UTC
np.einsum documentation says that the optimize arg default is True:
https://github.com/numpy/numpy/blob/963c704b3e8b03e48a3b10998af5c19a4c03cabc/numpy/core/einsumfunc.py#L867

but when the argument is missing, it defaults to False:
https://github.com/numpy/numpy/blob/963c704b3e8b03e48a3b10998af5c19a4c03cabc/numpy/core/einsumfunc.py#L1060

Proposed fix: change the argument to default to True, as it makes sense to use optimization unless explicitly disabled

**Comment by charris** [comment] 2017-12-22 16:31
@dgasmith Thoughts?

**Comment by dgasmith** [comment] 2017-12-22 18:42
Whoops, we had agreed to flip the optimization to True as we thought the algorithm was sufficiently battle tested through a full release already. It looks like only half of it was changed correctly. Great catch to fix this in the RC.

@acbellini Let me know if I can help out.

**Comment by charris** [comment] 2017-12-22 20:53
Closed by #10259.

**Closed by charris** 2017-12-22 20:53 UTC

**Comment by acbellini** [comment] 2017-12-22 21:12
Yay! my first ever Numpy PR :D !!!!

**Comment by peijunz** [comment] 2018-03-22 06:58
Dear developers @acbellini @charris 

Although the optimization is changed to `True` by default, there is still inconsistency in line 822:
https://github.com/numpy/numpy/blob/6914bb41f0fb3c1ba500bae4e7d671da9536786f/numpy/core/einsumfunc.py#L819-L822

The signature of this function is still showing `optimization=False`. Could you please improve it?

Thank you!

**Comment by dgasmith** [comment] 2018-03-22 14:08
In NumPY 1.14.1 (?) `optimize` was turned off by default as it was showing a few regressions. 

Einsum is a pure C function and has low latency as most other functions like `sum` or `tensordot` have a bit of Python overhead that can easily swamp the compute time for very small operations. I didn't realize that folks were using it in this fashion, but makes quite a bit of sense in retrospect.

I think the only way forward to have `optimize=True` by default would be to write a bit of the optimization tech in C so the latency goes down.

**Comment by dgasmith** [comment] 2018-03-22 17:57
Ah, ok it looks like they way it shook out was to `kwargs.pop('optimize', len(operands) > 3)` so you need 3 or more tensors (as one is the input string), but this also doesn't account for the other input methods.

I didn't make those changes, but if I recall correctly the idea was `optimize=True` for 3 or more tensors is a good idea as order can be optimized and not just using the einsum vs tensordot switch for 2 operands.

I think the current behavior is fairly reasonable, but does need to be documented correctly.
