### ISSUE TITLE
BUG: regression in setArrayFromSequence

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#13659] opened 2019-05-28 19:16 UTC
In #13399 we improved performance of `setArrayFromSequence` by generalizing the faster assignment loop from only ndarrays to other sequences. This broke pandas since `np.array([pd.DataFrame()])` now raises an error `could not broadcast input array from shape (0,0) into shape (0)`

**Comment by mattip** [comment] 2019-05-28 19:16
@superbobry any ideas?

**Comment by mattip** [comment] 2019-05-28 19:20
I think it is due to `pd.DataFrame().__array__()` returning `array([], shape=(0, 0), dtype=float64`, maybe we need to special case `shape` with 0 in it

**Comment by seberg** [comment] 2019-05-28 19:35
It seems to me the result of that on old numpy versions is incorrect though:
```
In [3]: np.array([pd.DataFrame()])
Out[3]: array([], shape=(1, 0), dtype=float64)

In [4]: np.array([pd.DataFrame().__array__()])
Out[4]: array([], shape=(1, 0, 0), dtype=float64)
```

**Comment by mattip** [comment] 2019-05-29 05:06
I wonder if returning `array([], shape=(0, 0), dtype=float64)` will break  panda's tests. I can check that once we stop raising an exception on `np.array([pd.DataFrame()])`

**Comment by eric-wieser** [comment] 2019-05-29 06:01
I assume `np.array([pd.DataFrame().__array__()])` still works fine on master?

**Comment by mattip** [comment] 2019-05-29 06:39
yes, that is equivalent to `np.array([np.ndarray(shape=(0,0))])` and returns `array([], shape=(1, 0, 0), dtype=float64)`. 

I have a failing test with a simple class with `__iter__` and `__array__`, now searching for the difference in the `__array__` path from the `ndarray` path

**Comment by mattip** [comment] 2019-05-29 06:42
> I wonder if returning array([], shape=(0, 0), dtype=float64) 

This is the wrong approach, we should still return shape (1, 0) since `[pd.DataFrame()]` is a list with one "zero-length" element, so it is like `np.array([[]])` which has shape `(1, 0)`

**Comment by seberg** [comment] 2019-05-29 07:01
It sounds like the incorrect path is (in the new code) during dimensionality discovery probably? While the old paths were identically wrong I suppose?

**Comment by mattip** [comment] 2019-05-29 07:38
Dimension discovery is OK, the output array is being created correctly with shape (1, 0). There is code internally that does calls the code below, now I need to go back to before the change and figure out the equivalent code there

<details>

```
# setup
out = np.ndarray(shape=(1,0))
arg = [obj]  # has `__array__` which returns `ndarray(shape=(0,0))`

def setArrayFromSequence(out, arg, dim=0, dst=None):
    #for recursive calls
    if dst is None:
        dst = out
    if isinstance(arg, np.narray):
        dst[:] = arg
        return
    tmp = convert_to_ndarray(arg)
    if tmp:
        dst[:] = tmp
        return
    s = len(arg)
    if s == 1:
        # broadcast the single object across dst
        for i in out.shape(dim):
            setArrayFromSequence(out, arg[0], dim+1, dst[i])
    else:
        ...
```
In the second recursive call to setArrayFromSequence, `convert_to_ndarray` succeeds since `obj` implements `__array__`, but then we get to `dst[:] = tmp`, where `dst` has shape `(0,)` and tmp has shape `(0,0)`.

**Comment by eric-wieser** [comment] 2019-05-29 15:53
Sounds like the problem is that using iteration alone, you can't discovered dimensions nested within length-0 dimensions, unlike __array__ which can.

So (1,0,0) is the correct result shape in my mind.

**Comment by mattip** [comment] 2019-05-29 17:16
> the behaviour change seems like it may actually be a bug fix, 

I think that it is orthogonal to this PR which is about restoring previous behavior from a regression that breaks pandas's tests by raising an error.

**Comment by seberg** [comment] 2019-05-29 17:28
I am OK, with basically reverting for now to the previous (arguably incorrect) state. 1.17 is already packed with a huge amount of changes anyway.

**Comment by seberg** [comment] 2019-05-29 17:51
Another strange beast is an array-like which does not also implement the sequence protocol. Those fail pretty badly right now in most cases. Just made sure that your PR seems to be in line with master in this regard though.

**Comment by superbobry** [comment] 2019-05-29 19:23
> Another strange beast is an array-like which does not also implement the sequence protocol.

Could you give an example? Are you referring to object having buffer/array interface which aren't sequences?

**Comment by seberg** [comment] 2019-05-29 20:09
@superbobry yes, something like:
```
class MyArrayLike:
    def __array__(self):
         return np.zeros((0, 3))
```

**Comment by seberg** [comment] 2019-05-30 20:45
Ok, I merged the regression fix. Note that the result is actually incorrect and should change in a future version of numpy. See gh-13671 about this.

**Closed by seberg** 2019-05-30 20:45 UTC
Labels: 00 - Bug, 06 - Regression, component: numpy.core
